nethack/sys/amiga/amidos.c File Reference
#include `hack.h`
*
#include `winami.h`
*
#include <libraries/dos.h>
*
#include <exec/execbase.h>
*
#include <intuition/intuition.h>
*
#include `NH:sys/amiga/winami.p`
*
#include `NH:sys/amiga/amiwind.p`
*
#include `NH:sys/amiga/amidos.p`
*
Functions
static boolean record_exists (void)
void flushout ()
getuid ()
char * getlogin ()
int abs (int x)
void nethack_exit (code)
void regularize (char *s)
Variables
char Initialized
struct window_procs amii_procs
int Enable_Abort = 0
char PATH [PATHLEN] = `NetHack:`
Function Documentation
int abs (int x)
Definition at line 71 of file amidos.c.
Referenced by create_room(), create_subroom(), dig_corridor(), drag_ball(), fill_room(), load_maze(), makelevel(), makemaz(), and mkmap().
{
    return x < 0? -x: x;
}
void flushout ()
Definition at line 49 of file amidos.c.
References stdout.
Referenced by dosave0().
{
    (void) fflush(stdout);
}
char* getlogin ()
Definition at line 63 of file amidos.c.
References NULL.
{
    return ((char *) NULL);
}
getuid ()
Definition at line 55 of file amidos.c.
Referenced by create_savefile(), get_saved_games(), ghack_init_main_window(), ghack_sig_handler(), MAIN(), main(), process_options(), prscore(), restgamestate(), savegamestate(), set_savefile_name(), topten(), vms_getuid(), and X11_init_nhwindows().
{
    return 1;
}
void nethack_exit (code)
Definition at line 465 of file amidos.c.
References amii_procs, chdir(), CleanUp(), exit(), and windowprocs.
{
#ifdef CHDIR
    extern char orgdir[];
#endif
#ifdef CHDIR
    chdir(orgdir); /* chdir, not chdirx */
#endif
#ifdef AMII_GRAPHICS
    if(windowprocs.win_init_nhwindows==amii_procs.win_init_nhwindows)
    CleanUp();
#endif
    exit(code);
}
static boolean record_exists (void) [static]
void regularize (char * s)
Definition at line 483 of file amidos.c.
References index().
{
    register char *lp;
    while((lp = index(s, ':')) || (lp = index(s, '/')))
    *lp = '_';
}
Variable Documentation
struct window_procs amii_procs
Referenced by Abort(), kbhit(), and nethack_exit().
int Enable_Abort = 0
Definition at line 40 of file amidos.c.
char Initialized
Referenced by amii_display_nhwindow(), amii_init_nhwindows(), amii_raw_print(), and amii_raw_print_bold().
char PATH[PATHLEN] = `NetHack:`
Definition at line 44 of file amidos.c.
Referenced by parse_config_line().