nethack/sys/amiga/amiwind.c File Reference
#include `NH:sys/amiga/windefs.h`
*
#include `NH:sys/amiga/winext.h`
*
#include `NH:sys/amiga/winproto.h`
*
Functions
int kbhit ()
void Abort (long rc)
void CleanUp ()
void amiv_loadlib (void)
void amii_loadlib (void)
Function Documentation
void Abort (long rc)
Definition at line 741 of file amiwind.c.
References Abort(), amii_getret(), amii_procs, chdir(), exit(), orgdir, printf, and windowprocs.
Referenced by Abort(), amii_create_nhwindow(), and amii_init_nhwindows().
{
    int fault = 1;
#ifdef CHDIR
    extern char orgdir[];
    chdir(orgdir);
#endif
#ifdef AMII_GRAPHICS
    if (Initialized
      && ConsoleDevice
      && windowprocs.win_init_nhwindows==amii_procs.win_init_nhwindows) {
      printf("\n\nAbort with alert code %08lx...\n", rc);
      amii_getret();
    } else
#endif
      printf("\n\nAbort with alert code %08lx...\n",rc);
      /* Alert(rc); this is too severe */
#ifdef __SASC
# ifdef INTUI_NEW_LOOK
    if(IntuitionBase->LibNode.lib_Version >= 37)
    {
        struct EasyStruct es =
        {
            sizeof(struct EasyStruct),
            0,
            "NetHack Panic Request",
            "NetHack is Aborting with code == 0x%08lx",
        "Continue Abort|Return to Program|Clean up and exit",
        };
        fault = EasyRequest(NULL, &es, NULL, (long)rc);
        if(fault == 2)
            return;
    }
# endif
    if(fault == 1)
    {
/* __emit(0x4afc); */ /* illegal instruction */
    __emit(0x40fc); /* divide by */
    __emit(0x0000); /* #0 */
      /* NOTE: don't move amii_cleanup() above here - */
      /* it is too likely to kill the system */
      /* before it can get the SnapShot out, if */
      /* there is something really wrong. */
    }
#endif
#ifdef AMII_GRAPHICS
    if(windowprocs.win_init_nhwindows==amii_procs.win_init_nhwindows)
      amii_cleanup();
#endif
#undef exit
#ifdef AZTEC_C
    _abort();
#endif
    exit((int) rc);
}
void amii_loadlib (void)
Definition at line 932 of file amiwind.c.
{
}
void amiv_loadlib (void)
Definition at line 927 of file amiwind.c.
{
}
void CleanUp (void)
Definition at line 799 of file amiwind.c.
Referenced by nethack_exit().
{
    amii_cleanup();
}
int kbhit ()
Definition at line 544 of file amiwind.c.
References amii_procs, amikbhit(), and windowprocs.
{
    int c;
# ifdef TTY_GRAPHICS
        /* a kludge to defuse the mess in allmain.c */
        /* I hope this is the right approach */
    if(windowprocs.win_init_nhwindows==amii_procs.win_init_nhwindows)return 0;
# endif
    c = amikbhit();
    if(c <= 0)
        return(0);
    return(c);
}