nethack/src/ball.c File Reference
#include `hack.h`
*
Macros
#define BCPOS_DIFFER 0	/* ball & chain at different positions */
#define BCPOS_CHAIN 1	/* chain on top of ball */
#define BCPOS_BALL 2	/* ball on top of chain */
#define CHAIN_IN_MIDDLE(chx, chy) (distmin(x, y, chx, chy) <= 1 && distmin(chx, chy, uball->ox, uball->oy) <= 1)
#define IS_CHAIN_ROCK(x, y)
#define SKIP_TO_DRAG
Functions
STATIC_DCL int NDECL (bc_order)
STATIC_DCL void NDECL (litter)
void ballfall ()
void placebc ()
void unplacebc ()
STATIC_OVL int bc_order ()
void set_bc (int already_blind)
void move_bc (int before, int control, xchar ballx, xchar bally, xchar chainx, xchar chainy)
boolean drag_ball (xchar x, xchar y, int *bc_control, xchar *ballx, xchar *bally, xchar *chainx, xchar *chainy, boolean *cause_delay, boolean allow_drag)
void drop_ball (xchar x, xchar y)
STATIC_OVL void litter ()
void drag_down ()
Macro Definition Documentation
#define BCPOS_BALL 2	/* ball on top of chain */
Definition at line 86 of file ball.c.
Referenced by bc_order(), and move_bc().
#define BCPOS_CHAIN 1	/* chain on top of ball */
Definition at line 85 of file ball.c.
Referenced by bc_order(), move_bc(), placebc(), and set_bc().
#define BCPOS_DIFFER 0	/* ball & chain at different positions */
Definition at line 84 of file ball.c.
Referenced by bc_order(), move_bc(), placebc(), and set_bc().
#define CHAIN_IN_MIDDLE(chx, chy) (distmin(x, y, chx, chy) <= 1 && distmin(chx, chy, uball->ox, uball->oy) <= 1)
Referenced by drag_ball().
#define IS_CHAIN_ROCK(x, y)
Value:
(IS_ROCK(levl[x][y].typ) || (IS_DOOR(levl[x][y].typ) && \
      (levl[x][y].doormask & (D_CLOSED|D_LOCKED))))
Referenced by drag_ball().
#define SKIP_TO_DRAG
Value:
{ *chainx = oldchainx; *chainy = oldchainy; \
    move_bc(0, *bc_control, *ballx, *bally, *chainx, *chainy); \
    goto drag; }
Referenced by drag_ball().
Function Documentation
void ballfall ()
Definition at line 13 of file ball.c.
References carried, FALSE, flags, HEAD, is_metallic, NO_KILLER_PREFIX, obj::ox, obj::oy, rn1, setuqwep(), setuswapwep(), setuwep(), u, uarmh, uball, uquiver, uswapwep, uwep, you::ux, you::uy, and flag::verbose.
{
    boolean gets_hit;
    gets_hit = (((uball->ox != u.ux) || (uball->oy != u.uy)) &&
            ((uwep == uball)? FALSE : (boolean)rn2(5)));
    if (carried(uball)) {
        pline("Startled, you drop the iron ball.");
        if (uwep == uball)
            setuwep((struct obj *)0);
        if (uswapwep == uball)
            setuswapwep((struct obj *)0);
        if (uquiver == uball)
            setuqwep((struct obj *)0);;
        if (uwep != uball)
            freeinv(uball);
    }
    if(gets_hit){
        int dmg = rn1(7,25);
        pline_The("iron ball falls on your %s.",
            body_part(HEAD));
        if (uarmh) {
            if(is_metallic(uarmh)) {
            pline("Fortunately, you are wearing a hard helmet.");
            dmg = 3;
            } else if (flags.verbose)
            Your("%s does not protect you.", xname(uarmh));
        }
        losehp(dmg, "crunched in the head by an iron ball",
            NO_KILLER_PREFIX);
    }
}
STATIC_OVL int bc_order ()
Definition at line 150 of file ball.c.
References BCPOS_BALL, BCPOS_CHAIN, BCPOS_DIFFER, carried, level, dlevel_t::objects, obj::ox, obj::oy, u, uball, and uchain.
Referenced by drop_ball(), move_bc(), and set_bc().
{
    struct obj *obj;
    if (uchain->ox != uball->ox || uchain->oy != uball->
      oy || carried(uball)
        || u.uswallow)
    return BCPOS_DIFFER;
    for (obj = level.objects[uball->ox][uball->oy]; obj; obj = obj->nexthere) {
    if (obj == uchain) return BCPOS_CHAIN;
    if (obj == uball) return BCPOS_BALL;
    }
    impossible("bc_order: ball&chain not in same location!");
    return BCPOS_DIFFER;
}
boolean drag_ball (xchar x, xchar y, int * bc_control, xchar * ballx, xchar * bally, xchar * chainx, xchar * chainy, boolean * cause_delay, boolean allow_drag)
Definition at line 360 of file ball.c.
References abs(), BC_BALL, BC_CHAIN, carried, CHAIN_IN_MIDDLE, FALSE, find_mac(), hmon(), HOLE, invent, IS_CHAIN_ROCK, Levitation, levl, Luck, m_at, move_bc(), newsym(), omon_adj(), obj::ox, obj::oy, PIT, POOL, SKIP_TO_DRAG, SLT_ENCUMBER, SPIKED_PIT, TRAPDOOR, TRUE, u, uball, uchain, you::ux, you::ux0, you::uy, you::uy0, trap::x, and trap::y.
Referenced by teleds().
{
    struct trap *t = (struct trap *)0;
    boolean already_in_rock;
    *ballx = uball->ox;
    *bally = uball->oy;
    *chainx = uchain->ox;
    *chainy = uchain->oy;
    *bc_control = 0;
    *cause_delay = FALSE;
    if (dist2(x, y, uchain->ox, uchain->oy) <= 2) { /* nothing moved */
        move_bc(1, *bc_control, *ballx, *bally, *chainx, *chainy);
        return TRUE;
    }
    /* only need to move the chain? */
    if (carried(uball) || distmin(x, y, uball->ox, uball->
      oy) <= 2) {
        xchar oldchainx = uchain->ox, oldchainy = uchain->oy;
        *bc_control = BC_CHAIN;
        move_bc(1, *bc_control, *ballx, *bally, *chainx, *chainy);
        if (carried(uball)) {
        /* move chain only if necessary */
        if (distmin(x, y, uchain->ox, uchain->oy) > 1) {
            *chainx = u.ux;
            *chainy = u.uy;
        }
        return TRUE;
        }
#define CHAIN_IN_MIDDLE(chx, chy) \
(distmin(x, y, chx, chy) <= 1 && distmin(chx, chy, uball->ox, uball->oy) <= 1)
#define IS_CHAIN_ROCK(x,y) \
(IS_ROCK(levl[x][y].typ) || (IS_DOOR(levl[x][y].typ) && \
      (levl[x][y].doormask & (D_CLOSED|D_LOCKED))))
/* Don't ever move the chain into solid rock. If we have to, then instead
 * undo the move_bc() and jump to the drag ball code. Note that this also
 * means the "cannot carry and drag" message will not appear, since unless we
 * moved at least two squares there is no possibility of the chain position
 * being in solid rock.
 */
#define SKIP_TO_DRAG { *chainx = oldchainx; *chainy = oldchainy; \
    move_bc(0, *bc_control, *ballx, *bally, *chainx, *chainy); \
    goto drag; }
        if (IS_CHAIN_ROCK(u.ux, u.uy) || IS_CHAIN_ROCK(*chainx, *chainy)
            || IS_CHAIN_ROCK(uball->ox, uball->oy))
        already_in_rock = TRUE;
        else
        already_in_rock = FALSE;
        switch(dist2(x, y, uball->ox, uball->oy)) {
        /* two spaces diagonal from ball, move chain inbetween */
        case 8:
            *chainx = (uball->ox + x)/2;
            *chainy = (uball->oy + y)/2;
            if (IS_CHAIN_ROCK(*chainx, *chainy) && !already_in_rock)
            SKIP_TO_DRAG;
            break;
        /* player is distance 2/1 from ball; move chain to one of the
         * two spaces between
         * @
         * __
         * 0
         */
        case 5: {
            xchar tempx, tempy, tempx2, tempy2;
            /* find position closest to current position of chain */
            /* no effect if current position is already OK */
            if (abs(x - uball->ox) == 1) {
            tempx = x;
            tempx2 = uball->ox;
            tempy = tempy2 = (uball->oy + y)/2;
            } else {
            tempx = tempx2 = (uball->ox + x)/2;
            tempy = y;
            tempy2 = uball->oy;
            }
            if (IS_CHAIN_ROCK(tempx, tempy) &&
                !IS_CHAIN_ROCK(tempx2, tempy2) &&
                !already_in_rock) {
            if (allow_drag) {
                /* Avoid pathological case *if* not teleporting:
                 * 0 0_
                 * _X move northeast -----> X@
                 * @
                 */
                if (dist2(u.ux, u.uy, uball->ox, uball->oy) == 5 &&
                  dist2(x, y, tempx, tempy) == 1)
                SKIP_TO_DRAG;
                /* Avoid pathological case *if* not teleporting:
                 * 0 0
                 * _X move east -----> X_
                 * @ @
                 */
                if (dist2(u.ux, u.uy, uball->ox, uball->oy) == 4 &&
                  dist2(x, y, tempx, tempy) == 2)
                SKIP_TO_DRAG;
            }
            *chainx = tempx2;
            *chainy = tempy2;
            } else if (!IS_CHAIN_ROCK(tempx, tempy) &&
                IS_CHAIN_ROCK(tempx2, tempy2) &&
                !already_in_rock) {
            if (allow_drag) {
                if (dist2(u.ux, u.uy, uball->ox, uball->oy) == 5 &&
                    dist2(x, y, tempx2, tempy2) == 1)
                SKIP_TO_DRAG;
                if (dist2(u.ux, u.uy, uball->ox, uball->oy) == 4 &&
                  dist2(x, y, tempx2, tempy2) == 2)
                SKIP_TO_DRAG;
            }
            *chainx = tempx;
            *chainy = tempy;
            } else if (IS_CHAIN_ROCK(tempx, tempy) &&
                IS_CHAIN_ROCK(tempx2, tempy2) &&
                !already_in_rock) {
            SKIP_TO_DRAG;
            } else if (dist2(tempx, tempy, uchain->ox, uchain->oy) <
             dist2(tempx2, tempy2, uchain->ox, uchain->oy) ||
               ((dist2(tempx, tempy, uchain->ox, uchain->oy) ==
             dist2(tempx2, tempy2, uchain->ox, uchain->oy)) && rn2(2))) {
            *chainx = tempx;
            *chainy = tempy;
            } else {
            *chainx = tempx2;
            *chainy = tempy2;
            }
            break;
        }
        /* ball is two spaces horizontal or vertical from player; move*/
        /* chain inbetween *unless* current chain position is OK */
        case 4:
            if (CHAIN_IN_MIDDLE(uchain->ox, uchain->
      oy))
            break;
            *chainx = (x + uball->ox)/2;
            *chainy = (y + uball->oy)/2;
            if (IS_CHAIN_ROCK(*chainx, *chainy) && !already_in_rock)
            SKIP_TO_DRAG;
            break;
        
        /* ball is one space diagonal from player. Check for the
         * following special case:
         * @
         * _ moving southwest becomes @_
         * 0 0
         * (This will also catch teleporting that happens to resemble
         * this case, but oh well.) Otherwise fall through.
         */
        case 2:
            if (dist2(x, y, uball->ox, uball->oy) == 2 &&
                dist2(x, y, uchain->ox, uchain->oy) == 4) {
            if (uchain->oy == y)
                *chainx = uball->ox;
            else
                *chainy = uball->oy;
            if (IS_CHAIN_ROCK(*chainx, *chainy) && !already_in_rock)
                SKIP_TO_DRAG;
            break;
            }
            /* fall through */
        case 1:
        case 0:
            /* do nothing if possible */
            if (CHAIN_IN_MIDDLE(uchain->ox, uchain->
      oy))
            break;
            /* otherwise try to drag chain to player's old position */
            if (CHAIN_IN_MIDDLE(u.ux, u.uy)) {
            *chainx = u.ux;
            *chainy = u.uy;
            break;
            }
            /* otherwise use player's new position (they must have
               teleported, for this to happen) */
            *chainx = x;
            *chainy = y;
            break;
        
        default: impossible("bad chain movement");
            break;
        }
#undef SKIP_TO_DRAG
#undef IS_CHAIN_ROCK
#undef CHAIN_IN_MIDDLE
        return TRUE;
    }
drag:
    if (near_capacity() > SLT_ENCUMBER && dist2(x, y, u.ux, u.
      uy) <= 2) {
        You("cannot %sdrag the heavy iron ball.",
                invent ? "carry all that and also " : "");
        nomul(0);
        return FALSE;
    }
    if ((is_pool(uchain->ox, uchain->oy) &&
            /* water not mere continuation of previous water */
            (levl[uchain->ox][uchain->oy].typ == POOL ||
             !is_pool(uball->ox, uball->oy) ||
             levl[uball->ox][uball->oy].typ == POOL))
        || ((t = t_at(uchain->ox, uchain->oy)) &&
            (t->ttyp == PIT ||
             t->ttyp == SPIKED_PIT ||
             t->ttyp == HOLE ||
             t->ttyp == TRAPDOOR))) {
        if (Levitation) {
        You_feel("a tug from the iron ball.");
        if (t) t->tseen = 1;
        } else {
        struct monst *victim;
        You("are jerked back by the iron ball!");
        if ((victim = m_at(uchain->ox, uchain->oy)) != 0) {
            int tmp;
            tmp = -2 + Luck + find_mac(victim);
            tmp += omon_adj(victim, uball, TRUE);
            if (tmp >= rnd(20))
            (void) hmon(victim,uball,1);
            else
            miss(xname(uball), victim);
        } /* now check again in case mon died */
        if (!m_at(uchain->ox, uchain->oy)) {
            u.ux = uchain->ox;
            u.uy = uchain->oy;
            newsym(u.ux0, u.uy0);
        }
        nomul(0);
        *bc_control = BC_BALL;
        move_bc(1, *bc_control, *ballx, *bally, *chainx, *chainy);
        *ballx = uchain->ox;
        *bally = uchain->oy;
        move_bc(0, *bc_control, *ballx, *bally, *chainx, *chainy);
        spoteffects(TRUE);
        return FALSE;
        }
    }
    *bc_control = BC_BALL|BC_CHAIN;
    move_bc(1, *bc_control, *ballx, *bally, *chainx, *chainy);
    if (dist2(x, y, u.ux, u.uy) > 2) {
        /* Awful case: we're still in range of the ball, so we thought we
         * could only move the chain, but it turned out that the target
         * square for the chain was rock, so we had to drag it instead.
         * But we can't drag it either, because we teleported and are more
         * than one square from our old position. Revert to the teleport
         * behavior.
         */
        *ballx = *chainx = x;
        *bally = *chainy = y;
    } else {
        *ballx = uchain->ox;
        *bally = uchain->oy;
        *chainx = u.ux;
        *chainy = u.uy;
    }
    *cause_delay = TRUE;
    return TRUE;
}
void drag_down ()
Definition at line 747 of file ball.c.
References A_STR, carried, FALSE, KILLED_BY_AN, litter(), NO_KILLER_PREFIX, uball, and uwep.
{
    boolean forward;
    uchar dragchance = 3;
    /*
     * Assume that the ball falls forward if:
     *
     * a) the character is wielding it, or
     * b) the character has both hands available to hold it (i.e. is
     * not wielding any weapon), or
     * c) (perhaps) it falls forward out of his non-weapon hand
     */
    forward = carried(uball) && (uwep == uball || !uwep || !rn2(3));
    if (carried(uball))
        You("lose your grip on the iron ball.");
    if (forward) {
        if(rn2(6)) {
            pline_The("iron ball drags you downstairs!");
            losehp(rnd(6), "dragged downstairs by an iron ball",
                NO_KILLER_PREFIX);
            litter();
        }
    } else {
        if(rn2(2)) {
            pline_The("iron ball smacks into you!");
            losehp(rnd(20), "iron ball collision", KILLED_BY_AN);
            exercise(A_STR, FALSE);
            dragchance -= 2;
        }
        if((int) dragchance >= rnd(6)) {
            pline_The("iron ball drags you downstairs!");
            losehp(rnd(3), "dragged downstairs by an iron ball",
                NO_KILLER_PREFIX);
            exercise(A_STR, FALSE);
            litter();
        }
    }
}
void drop_ball (xchar x, xchar y)
Definition at line 643 of file ball.c.
References BC_CHAIN, you::bc_felt, bc_order(), you::bc_order, you::bglyph, Blind, you::cglyph, you::dx, you::dy, HOLE, In_sokoban, KILLED_BY, LEFT_SIDE, LEG, Levitation, levl, MON_AT, newsym(), obj::ox, obj::oy, PIT, RIGHT_SIDE, rn1, SPIKED_PIT, TRAPDOOR, TRUE, TT_BEARTRAP, TT_INFLOOR, TT_LAVA, TT_PIT, TT_WEB, u, uchain, you::utrap, you::utraptype, you::ux, you::ux0, you::uy, you::uy0, you::uz, vision_full_recalc, trap::x, and trap::y.
Referenced by throwit().
{
    if (Blind) {
    u.bc_order = bc_order(); /* get the order */
                            /* pick up glyph */
    u.bglyph = (u.bc_order) ? u.cglyph : levl[x][y].glyph;
    }
    if (x != u.ux || y != u.uy) {
    struct trap *t;
    const char *pullmsg = "The ball pulls you out of the %s!";
    if (u.utrap && u.utraptype != TT_INFLOOR) {
        switch(u.utraptype) {
        case TT_PIT:
        pline(pullmsg, "pit");
        break;
        case TT_WEB:
        pline(pullmsg, "web");
        pline_The("web is destroyed!");
        deltrap(t_at(u.ux,u.uy));
        break;
        case TT_LAVA:
        pline(pullmsg, "lava");
        break;
        case TT_BEARTRAP: {
        register long side = rn2(3) ? LEFT_SIDE : RIGHT_SIDE;
        pline(pullmsg, "bear trap");
        set_wounded_legs(side, rn1(1000, 500));
#ifdef STEED
        if (!u.usteed)
#endif
        {
            Your("%s %s is severely damaged.",
                    (side == LEFT_SIDE) ? "left" : "right",
                    body_part(LEG));
            losehp(2, "leg damage from being pulled out of a bear trap",
                    KILLED_BY);
        }
        break;
          }
        }
        u.utrap = 0;
        fill_pit(u.ux, u.uy);
    }
    u.ux0 = u.ux;
    u.uy0 = u.uy;
    if (!Levitation && !MON_AT(x, y) && !u.utrap &&
                (is_pool(x, y) ||
                 ((t = t_at(x, y)) &&
                  (t->ttyp == PIT || t->ttyp == SPIKED_PIT ||
                   t->ttyp == TRAPDOOR || t->ttyp == HOLE)))) {
        u.ux = x;
        u.uy = y;
    } else {
        u.ux = x - u.dx;
        u.uy = y - u.dy;
    }
    vision_full_recalc = 1; /* hero has moved, recalculate vision later */
    if (Blind) {
        /* drop glyph under the chain */
        if (u.bc_felt & BC_CHAIN)
        levl[uchain->ox][uchain->oy].glyph = u.cglyph;
        u.bc_felt = 0; /* feel nothing */
        /* pick up new glyph */
        u.cglyph = (u.bc_order) ? u.bglyph : levl[u.
      ux][u.uy].glyph;
    }
    movobj(uchain,u.ux,u.uy); /* has a newsym */
    if (Blind) {
        u.bc_order = bc_order();
    }
    newsym(u.ux0,u.uy0); /* clean up old position */
    if (u.ux0 != u.ux || u.uy0 != u.uy) {
        spoteffects(TRUE);
        if (In_sokoban(&u.uz))
        change_luck(-1); /* Sokoban guilt */
    }
    }
}
STATIC_OVL void litter ()
Definition at line 728 of file ball.c.
References invent, obj::nobj, otmp, obj::owt, and uball.
Referenced by drag_down().
{
    struct obj *otmp = invent, *nextobj;
    int capacity = weight_cap();
    while (otmp) {
        nextobj = otmp->nobj;
        if ((otmp != uball) && (rnd(capacity) <= (int)otmp->owt)) {
            if (canletgo(otmp, "")) {
                Your("%s you down the stairs.",
                     aobjnam(otmp, "follow"));
                dropx(otmp);
            }
        }
        otmp = nextobj;
    }
}
void move_bc (int before, int control, xchar ballx, xchar bally, xchar chainx, xchar chainy)
Definition at line 231 of file ball.c.
References BC_BALL, BC_CHAIN, you::bc_felt, bc_order(), you::bc_order, BCPOS_BALL, BCPOS_CHAIN, BCPOS_DIFFER, you::bglyph, Blind, carried, you::cglyph, levl, map_object(), newsym(), obj::ox, obj::oy, u, uball, and uchain.
Referenced by drag_ball(), and teleds().
{
    if (Blind) {
    /*
     * The hero is blind. Time to work hard. The ball and chain that
     * are attached to the hero are very special. The hero knows that
     * they are attached, so when they move, the hero knows that they
     * aren't at the last position remembered. This is complicated
     * by the fact that the hero can "feel" the surrounding locations
     * at any time, hence, making one or both of them show up again.
     * So, we have to keep track of which is felt at any one time and
     * act accordingly.
     */
    if (!before) {
        if ((control & BC_CHAIN) && (control & BC_BALL)) {
        /*
         * Both ball and chain moved. If felt, drop glyph.
         */
        if (u.bc_felt & BC_BALL)
            levl[uball->ox][uball->oy].glyph = u.bglyph;
        if (u.bc_felt & BC_CHAIN)
            levl[uchain->ox][uchain->oy].glyph = u.cglyph;
        u.bc_felt = 0;
        /* Pick up glyph at new location. */
        u.bglyph = levl[ballx][bally].glyph;
        u.cglyph = levl[chainx][chainy].glyph;
        movobj(uball,ballx,bally);
        movobj(uchain,chainx,chainy);
        } else if (control & BC_BALL) {
        if (u.bc_felt & BC_BALL) {
            if (u.bc_order == BCPOS_DIFFER) { /* ball by itself */
            levl[uball->ox][uball->oy].glyph = u.bglyph;
            } else if (u.bc_order == BCPOS_BALL) {
            if (u.bc_felt & BC_CHAIN) { /* know chain is there */
                map_object(uchain, 0);
            } else {
                levl[uball->ox][uball->oy].glyph = u.bglyph;
            }
            }
            u.bc_felt &= ~BC_BALL; /* no longer feel the ball */
        }
        /* Pick up glyph at new position. */
        u.bglyph = (ballx != chainx || bally != chainy) ?
                    levl[ballx][bally].glyph : u.cglyph;
        movobj(uball,ballx,bally);
        } else if (control & BC_CHAIN) {
        if (u.bc_felt & BC_CHAIN) {
            if (u.bc_order == BCPOS_DIFFER) {
            levl[uchain->ox][uchain->oy].glyph = u.cglyph;
            } else if (u.bc_order == BCPOS_CHAIN) {
            if (u.bc_felt & BC_BALL) {
                map_object(uball, 0);
            } else {
                levl[uchain->ox][uchain->oy].glyph = u.
      cglyph;
            }
            }
            u.bc_felt &= ~BC_CHAIN;
        }
        /* Pick up glyph at new position. */
        u.cglyph = (ballx != chainx || bally != chainy) ?
                    levl[chainx][chainy].glyph : u.bglyph;
        movobj(uchain,chainx,chainy);
        }
        u.bc_order = bc_order(); /* reset the order */
    }
    } else {
    /*
     * The hero is not blind. To make this work correctly, we need to
     * pick up the ball and chain before the hero moves, then put them
     * in their new positions after the hero moves.
     */
    if (before) {
        if (!control) {
        /*
         * Neither ball nor chain is moving, so remember which was
         * on top until !before. Use the variable u.bc_order
         * since it is only valid when blind.
         */
        u.bc_order = bc_order();
        }
        remove_object(uchain);
        newsym(uchain->ox, uchain->oy);
        if (!carried(uball)) {
        remove_object(uball);
        newsym(uball->ox, uball->oy);
        }
    } else {
        int on_floor = !carried(uball);
        if ((control & BC_CHAIN) ||
                (!control && u.bc_order == BCPOS_CHAIN)) {
        /* If the chain moved or nothing moved & chain on top. */
        if (on_floor) place_object(uball, ballx, bally);
        place_object(uchain, chainx, chainy); /* chain on top */
        } else {
        place_object(uchain, chainx, chainy);
        if (on_floor) place_object(uball, ballx, bally);
                                /* ball on top */
        }
        newsym(chainx, chainy);
        if (on_floor) newsym(ballx, bally);
    }
    }
}
STATIC_DCL int NDECL (bc_order)
STATIC_DCL void NDECL (litter)
void placebc ()
Definition at line 99 of file ball.c.
References you::bc_order, BCPOS_CHAIN, BCPOS_DIFFER, carried, u, uball, uchain, you::ux, and you::uy.
Referenced by movebubbles(), and teleds().
{
    if (!uchain || !uball) {
    impossible("Where are your ball and chain?");
    return;
    }
    (void) flooreffects(uchain, u.ux, u.uy, ""); /* chain might rust */
    if (carried(uball)) /* the ball is carried */
    u.bc_order = BCPOS_DIFFER;
    else {
    /* ball might rust -- already checked when carried */
    (void) flooreffects(uball, u.ux, u.uy, "");
    place_object(uball, u.ux, u.uy);
    u.bc_order = BCPOS_CHAIN;
    }
    place_object(uchain, u.ux, u.uy);
    u.bglyph = u.cglyph = levl[u.ux][u.uy].glyph; /* pick up glyph */
    newsym(u.ux,u.uy);
}
void set_bc (int already_blind)
Definition at line 173 of file ball.c.
References BC_BALL, BC_CHAIN, you::bc_felt, bc_order(), you::bc_order, BCPOS_CHAIN, BCPOS_DIFFER, you::bglyph, carried, you::cglyph, levl, newsym(), obj::ox, obj::oy, u, uball, uchain, you::ux, and you::uy.
{
    int ball_on_floor = !carried(uball);
    u.bc_order = bc_order(); /* get the order */
    u.bc_felt = ball_on_floor ? BC_BALL|BC_CHAIN :
      BC_CHAIN; /* felt */
    if (already_blind || u.uswallow) {
    u.cglyph = u.bglyph = levl[u.ux][u.uy].glyph;
    return;
    }
    /*
     * Since we can still see, remove the ball&chain and get the glyph that
     * would be beneath them. Then put the ball&chain back. This is pretty
     * disgusting, but it will work.
     */
    remove_object(uchain);
    if (ball_on_floor) remove_object(uball);
    newsym(uchain->ox, uchain->oy);
    u.cglyph = levl[uchain->ox][uchain->oy].glyph;
    if (u.bc_order == BCPOS_DIFFER) { /* different locations */
    place_object(uchain, uchain->ox, uchain->oy);
    newsym(uchain->ox, uchain->oy);
    if (ball_on_floor) {
        newsym(uball->ox, uball->oy); /* see under ball */
        u.bglyph = levl[uball->ox][uball->oy].glyph;
        place_object(uball, uball->ox, uball->oy);
        newsym(uball->ox, uball->oy); /* restore ball */
    }
    } else {
    u.bglyph = u.cglyph;
    if (u.bc_order == BCPOS_CHAIN) {
        place_object(uball, uball->ox, uball->oy);
        place_object(uchain, uchain->ox, uchain->oy);
    } else {
        place_object(uchain, uchain->ox, uchain->oy);
        place_object(uball, uball->ox, uball->oy);
    }
    newsym(uball->ox, uball->oy);
    }
}
void unplacebc ()
Definition at line 125 of file ball.c.
References BC_BALL, BC_CHAIN, you::bc_felt, you::bglyph, Blind, carried, you::cglyph, levl, newsym(), obj::ox, obj::oy, u, uball, and uchain.
Referenced by movebubbles(), and teleds().
{
    if (u.uswallow) return; /* ball&chain not placed while swallowed */
    if (!carried(uball)) {
    obj_extract_self(uball);
    if (Blind && (u.bc_felt & BC_BALL)) /* drop glyph */
        levl[uball->ox][uball->oy].glyph = u.bglyph;
    newsym(uball->ox,uball->oy);
    }
    obj_extract_self(uchain);
    if (Blind && (u.bc_felt & BC_CHAIN)) /* drop glyph */
    levl[uchain->ox][uchain->oy].glyph = u.cglyph;
    newsym(uchain->ox,uchain->oy);
    u.bc_felt = 0; /* feel nothing */
}