nethack/include/bitmfile.h File Reference
Data Structures
struct RGB
Macros
#define UWORD unsigned short
#define ULONG unsigned long
#define UBYTE unsigned char
#define XIMG_MAGIC 0x58494D47
Enumerations
enum FILE_TYP { IMG,
XIMG
 }
Functions
const char * get_file_ext (FILE_TYP typ)
int bitmap_to_file (FILE_TYP typ, int ww, int wh, unsigned int pwx, unsigned int pwy, unsigned int planes, unsigned int colors, const char *filename, void(*get_color)(unsigned int colind, struct RGB *rgb), void(*get_pixel)(int x, int y, unsigned int *colind))
Macro Definition Documentation
#define UBYTE unsigned char
Definition at line 15 of file bitmfile.h.
Referenced by bitmap_to_img().
#define ULONG unsigned long
Definition at line 14 of file bitmfile.h.
#define UWORD unsigned short
Definition at line 13 of file bitmfile.h.
Referenced by bitmap_to_img(), and EditColor().
#define XIMG_MAGIC 0x58494D47
Definition at line 17 of file bitmfile.h.
Referenced by bitmap_to_img().
Enumeration Type Documentation
enum FILE_TYP
Enumerator
IMG
XIMG
Definition at line 20 of file bitmfile.h.
{ IMG, XIMG } FILE_TYP;
Function Documentation
int bitmap_to_file (FILE_TYP typ, int ww, int wh, unsigned int pwx, unsigned int pwy, unsigned int planes, unsigned int colors, const char * filename, void(*)(unsigned int colind, struct RGB *rgb) get_color, void(*)(int x, int y, unsigned int *colind) get_pixel)
Definition at line 323 of file bitmfile.c.
References bitmap_to_img(), get_color(), get_pixel(), IMG, and XIMG.
Referenced by main().
    {
    switch (typ)
        {
        case IMG:
        case XIMG:
            return(bitmap_to_img(typ,ww,wh,pwx,pwy,planes,colors,
      filename,get_color,get_pixel));
        default:
            return(-1);
        };
}
const char* get_file_ext (FILE_TYP typ)
Definition at line 310 of file bitmfile.c.
References IMG, and XIMG.
    {
    switch (typ)
        {
        case IMG:
        case XIMG:
            return("IMG");
        default:
            return("");
        };
}