nethack/sys/wince/celib.c File Reference
#include `hack.h`
*
#include <fcntl.h>
*
Macros
#define NEED_VARARGS
#define IS_LEAP(yr) (((yr)%4==0 || (yr)%100==0) && !(yr)%400==0)
#define FILE_TABLE_SIZE 256
Functions
struct tm *__cdecl localtime (const time_t *ptime)
time_t __cdecl time (time_t *timeptr)
static HANDLE get_file_handle (int i)
static int alloc_file_handle (HANDLE h)
int __cdecl close (int f)
int __cdecl creat (const char *fname, int mode)
int __cdecl eof (int f)
long __cdecl lseek (int f, long offset, int origin)
int __cdecl open (const char *filename, int oflag,...)
int __cdecl read (int f, void *buffer, unsigned int count)
int __cdecl unlink (const char *filename)
int __cdecl write (int f, const void *buffer, unsigned int count)
int __cdecl rename (const char *oldname, const char *newname)
int __cdecl access (const char *path, int mode)
int chdir (const char *dirname)
char * getcwd (char *buffer, int maxlen)
void chdrive (char *str)
char * get_username (int *lan_username_size)
void Delay (int ms)
void more ()
int isatty (int f)
Variables
xx xx xx xx xx xx xx xx xx
union {
 time_t t_val
 struct time_pack {
  unsigned int ss:6
  unsigned int mm:6
  unsigned int dd:5
  unsigned int hh:6
  unsigned int mo:4
  unsigned int yr:10
  unsigned int wd:3
 } tm_val
} _t_cnv
static char _day_mo_leap [12] = { 31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 }
static char _day_mo [12] = { 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 }
static TCHAR _nh_cwd [MAX_PATH]
const int MAGIC_OFFSET =5
static HANDLE _nh_file_table [FILE_TABLE_SIZE]
static int file_pointer = -1
int errno
Macro Definition Documentation
#define FILE_TABLE_SIZE 256
Definition at line 74 of file celib.c.
Referenced by alloc_file_handle(), close(), and get_file_handle().
#define IS_LEAP(yr) (((yr)%4==0 || (yr)%100==0) && !(yr)%400==0)
Definition at line 22 of file celib.c.
Referenced by localtime().
#define NEED_VARARGS
Definition at line 4 of file celib.c.
Function Documentation
int __cdecl access (const char * path, int mode)
Definition at line 314 of file celib.c.
Referenced by fopen_config_file().
{
    DWORD attr;
    WCHAR f[MAX_PATH+1];
    ZeroMemory(f, sizeof(f));
    MultiByteToWideChar(CP_ACP, 0, path, -1, f, MAX_PATH);
    
    attr = GetFileAttributes(f);
    if(attr == (DWORD)-1) return -1;
    if ((attr & FILE_ATTRIBUTE_READONLY) && (mode & 2))
        return -1;
    else
        return 0;
}
static int alloc_file_handle (HANDLE h) [static]
Definition at line 87 of file celib.c.
References _nh_file_table, abort, file_pointer, FILE_TABLE_SIZE, MAGIC_OFFSET, MessageBox(), and NULL.
Referenced by creat(), and open().
{
    int i;
    if(file_pointer==-1) {
        file_pointer=0;
        for(i=0; i<FILE_TABLE_SIZE; i++)
            _nh_file_table[i] = INVALID_HANDLE_VALUE;
    }
    i = (file_pointer+1)%FILE_TABLE_SIZE;
    while(_nh_file_table[i]!=INVALID_HANDLE_VALUE) {
        if(i==file_pointer) {
            MessageBox(NULL, _T("Ran out of file handles."), _T("Fatal Error"), MB_OK);
            abort();
        }
        i = (i+1) % FILE_TABLE_SIZE;
    }
    
    file_pointer = i;
    _nh_file_table[file_pointer] = h;
    return file_pointer+MAGIC_OFFSET;
}
int chdir (const char * dirname)
Definition at line 330 of file celib.c.
References _nh_cwd, and NH_A2W.
Referenced by Abort(), byebye(), chdirx(), main(), nethack_exit(), and xexit().
{
    ZeroMemory(_nh_cwd, sizeof(_nh_cwd));
    NH_A2W(dirname, _nh_cwd, MAX_PATH);
    return 0;
}
void chdrive (char * str)
Definition at line 352 of file celib.c.
{
    return;
}
int __cdecl close (int f)
Definition at line 110 of file celib.c.
References _nh_file_table, FILE_TABLE_SIZE, and MAGIC_OFFSET.
Referenced by bclose(), bitmap_to_img(), check_recordfile(), dorecover(), dosave0(), getbones(), getlock(), main(), mread(), restlevelfile(), restore_saved_game(), restore_savefile(), savebones(), unlock_file(), veryold(), and write_level_file().
                         {
    int retval;
    f -= MAGIC_OFFSET;
    if(f<0 || f>=FILE_TABLE_SIZE) return -1;
    retval = (CloseHandle(_nh_file_table[f])? 0 : -1);
    _nh_file_table[f] = INVALID_HANDLE_VALUE;
    return retval;
}
int __cdecl creat (const char * fname, int mode)
Definition at line 119 of file celib.c.
References alloc_file_handle(), NH_A2W, and NULL.
Referenced by create_bonesfile(), create_levelfile(), create_savefile(), getlock(), and vms_creat().
{
    HANDLE f;
    TCHAR wbuf[MAX_PATH+1];
    ZeroMemory(wbuf, sizeof(wbuf));
    NH_A2W(fname, wbuf, MAX_PATH);
    f = CreateFile(
        wbuf,
        GENERIC_READ | GENERIC_WRITE,
        0,
        NULL,
        CREATE_ALWAYS,
        FILE_ATTRIBUTE_NORMAL,
        NULL);
    if(f==INVALID_HANDLE_VALUE) return -1;
    else return alloc_file_handle(f);
}
void Delay (int ms)
Definition at line 368 of file celib.c.
Referenced by FlashButton(), lock_file(), makesound(), and topl_flash_resp().
{
    (void)Sleep(ms);
}
int __cdecl eof (int f)
Definition at line 139 of file celib.c.
References get_file_handle(), and NULL.
{
    DWORD fpos, fsize;
    HANDLE p = get_file_handle(f);
    if(f==-1) return -1;
    fpos = SetFilePointer(p, 0, NULL, FILE_CURRENT);
    fsize = SetFilePointer(p, 0, NULL, FILE_END);
    if(fpos==0xFFFFFFFF || fsize==0xFFFFFFFF) return -1;
    if(fpos==fsize) return 1;
    else {
        SetFilePointer(p, fpos, NULL, FILE_BEGIN);
        return 0;
    }
}
static HANDLE get_file_handle (int i) [static]
Definition at line 78 of file celib.c.
References _nh_file_table, FILE_TABLE_SIZE, and MAGIC_OFFSET.
Referenced by eof(), lseek(), read(), and write().
{
    i -= MAGIC_OFFSET;
    if(i>=0 && i<FILE_TABLE_SIZE)
        return _nh_file_table[i];
    else
        return INVALID_HANDLE_VALUE;
}
char* get_username (int * lan_username_size)
Definition at line 360 of file celib.c.
References BUFSZ.
Referenced by set_savefile_name().
{
    static char username_buffer[BUFSZ];
    strcpy(username_buffer, "nhsave");
    return username_buffer;
}
char* getcwd (char * buffer, int maxlen)
Definition at line 337 of file celib.c.
References _nh_cwd, NH_W2A, and NULL.
Referenced by main().
{
    if(maxlen<(int)_tcslen(_nh_cwd)) return NULL;
    else return NH_W2A(_nh_cwd, buffer, maxlen);
}
int isatty (int f)
Definition at line 378 of file celib.c.
Referenced by getlock(), and yy_init_buffer().
{
    return 0;
}
struct tm* __cdecl localtime (const time_t * ptime)
Definition at line 26 of file celib.c.
References _day_mo, _day_mo_leap, _t_cnv, IS_LEAP, NULL, tm::tm_hour, tm::tm_isdst, tm::tm_mday, tm::tm_min, tm::tm_mon, tm::tm_sec, tm::tm_wday, tm::tm_yday, and tm::tm_year.
Referenced by do_date(), and main().
{
    static struct tm ptm;
    int i;
    if(!ptime) return NULL;
    _t_cnv.t_val = *ptime;
    ptm.tm_sec = _t_cnv.tm_val.ss ; /* seconds after the minute - [0,59] */
    ptm.tm_min = _t_cnv.tm_val.mm; /* minutes after the hour - [0,59] */
    ptm.tm_hour = _t_cnv.tm_val.hh; /* hours since midnight - [0,23] */
    ptm.tm_mday = _t_cnv.tm_val.dd; /* day of the month - [1,31] */
    ptm.tm_mon = _t_cnv.tm_val.mo-1; /* months since January - [0,11] */
    ptm.tm_year = _t_cnv.tm_val.yr; /* years since 1900 */
    ptm.tm_wday = _t_cnv.tm_val.wd; /* days since Sunday - [0,6] */
    ptm.tm_yday = _t_cnv.tm_val.dd; /* days since January 1 - [0,365] */
    for(i=0; i<ptm.tm_mon; i++)
        ptm.tm_yday += IS_LEAP(_t_cnv.tm_val.yr+1900)?_day_mo_leap[i] :
      _day_mo[i] ;
    ptm.tm_isdst = 0; /* daylight savings time flag - NOT IMPLEMENTED */
    return &ptm;
}
long __cdecl lseek (int f, long offset, int origin)
Definition at line 156 of file celib.c.
References get_file_handle(), NULL, SEEK_CUR, SEEK_END, and SEEK_SET.
Referenced by dorecover(), main(), and restlevelfile().
{
    HANDLE p = get_file_handle(f);
    DWORD fpos;
    switch(origin) {
    case SEEK_SET:
        fpos = SetFilePointer(p, offset, NULL, FILE_BEGIN);
        break;
    case SEEK_CUR:
        fpos = SetFilePointer(p, offset, NULL, FILE_CURRENT);
        break;
    case SEEK_END:
        fpos = SetFilePointer(p, offset, NULL, FILE_END);
        break;
    default:
        fpos = 0xFFFFFFFF;
        break;
    }
    if(fpos==0xFFFFFFFF) return -1;
    else return (long)fpos;
}
void more ()
Definition at line 373 of file celib.c.
{
}
int __cdecl open (const char * filename, int oflag, ...)
Definition at line 178 of file celib.c.
References _nh_cwd, _O_CREAT, _O_EXCL, _O_RDONLY, _O_RDWR, _O_TRUNC, _O_WRONLY, alloc_file_handle(), fname, NH_A2W, NULL, and O_APPEND.
Referenced by bitmap_to_img(), check_recordfile(), create_bonesfile(), create_levelfile(), create_savefile(), getlock(), lock_file(), main(), open_bonesfile(), open_levelfile(), open_savefile(), restore_savefile(), vms_open(), and write_level_file().
{
    TCHAR fname[MAX_PATH+1];
    TCHAR path[MAX_PATH+1];
    HANDLE f;
    DWORD fileaccess;
    DWORD filecreate;
    /* O_TEXT is not supported */
    /*
     * decode the access flags
     */
    switch(oflag & (_O_RDONLY | _O_WRONLY | _O_RDWR)) {
        case _O_RDONLY: /* read access */
                fileaccess = GENERIC_READ;
                break;
        case _O_WRONLY: /* write access */
                fileaccess = GENERIC_READ | GENERIC_WRITE;
                break;
        case _O_RDWR: /* read and write access */
                fileaccess = GENERIC_READ | GENERIC_WRITE;
                break;
        default: /* error, bad oflag */
                return -1;
    }
    /*
     * decode open/create method flags
     */
    switch (oflag & (_O_CREAT | _O_EXCL | _O_TRUNC)) {
        case 0:
        case _O_EXCL: // ignore EXCL w/o CREAT
            filecreate = OPEN_EXISTING;
            break;
        case _O_CREAT:
            filecreate = OPEN_ALWAYS;
            break;
        case _O_CREAT | _O_EXCL:
        case _O_CREAT | _O_TRUNC | _O_EXCL:
            filecreate = CREATE_NEW;
            break;
        case _O_TRUNC:
        case _O_TRUNC | _O_EXCL: // ignore EXCL w/o CREAT
            filecreate = TRUNCATE_EXISTING;
            break;
        case _O_CREAT | _O_TRUNC:
            filecreate = CREATE_ALWAYS;
            break;
        default:
            return -1;
    }
    /* assemple the file name */
    ZeroMemory(fname, sizeof(fname));
    ZeroMemory(path, sizeof(path));
    NH_A2W(filename, fname, MAX_PATH);
    if(*filename!='\\' && *filename!='/') {
        _tcscpy(path, _nh_cwd);
        _tcsncat(path, _T("\\"), MAX_PATH - _tcslen(path));
    }
    _tcsncat(path, fname, MAX_PATH - _tcslen(path));
    /*
     * try to open/create the file
     */
    if ((f = CreateFile(path,
                         fileaccess,
                         0,
                         NULL,
                         filecreate,
                         FILE_ATTRIBUTE_NORMAL,
                         NULL))
         == INVALID_HANDLE_VALUE)
    {
        return -1;
    }
    if(!(oflag & O_APPEND)) SetFilePointer(f, 0, NULL, FILE_BEGIN);
    return alloc_file_handle(f);
}
int __cdecl read (int f, void * buffer, unsigned int count)
Definition at line 266 of file celib.c.
References get_file_handle(), and NULL.
Referenced by copy_bytes(), dorecover(), main(), mread(), restore_savefile(), uptodate(), and veryold().
{
    HANDLE p = get_file_handle(f);
    DWORD bytes_read;
    if(!ReadFile(p, buffer, count, &bytes_read, NULL))
        return -1;
    else
        return (int)bytes_read;
}
int __cdecl rename (const char * oldname, const char * newname)
Definition at line 303 of file celib.c.
Referenced by commit_bonesfile().
{
    WCHAR f1[MAX_PATH+1];
    WCHAR f2[MAX_PATH+1];
    ZeroMemory(f1, sizeof(f1));
    ZeroMemory(f2, sizeof(f2));
    MultiByteToWideChar(CP_ACP, 0, oldname, -1, f1, MAX_PATH);
    MultiByteToWideChar(CP_ACP, 0, newname, -1, f2, MAX_PATH);
    return !MoveFile(f1, f2);
}
time_t __cdecl time (time_t * timeptr)
Definition at line 50 of file celib.c.
References _t_cnv.
{
    SYSTEMTIME stm;
    GetLocalTime(&stm);
    _t_cnv.tm_val.yr = stm.wYear-1900;
    _t_cnv.tm_val.mo = stm.wMonth;
    _t_cnv.tm_val.dd = stm.wDay;
    _t_cnv.tm_val.hh = stm.wHour;
    _t_cnv.tm_val.mm = stm.wMinute;
    _t_cnv.tm_val.ss = stm.wSecond;
    _t_cnv.tm_val.wd = stm.wDayOfWeek;
    if(timeptr)
        *timeptr = _t_cnv.t_val;
    return _t_cnv.t_val;
}
int __cdecl unlink (const char * filename)
Definition at line 276 of file celib.c.
References _nh_cwd, fname, and NH_A2W.
Referenced by commit_bonesfile(), delete_bonesfile(), delete_levelfile(), delete_savefile(), EditColor(), eraseoldlocks(), restore_savefile(), unlock_file(), validate_prefix_locations(), and vms_creat().
{
    TCHAR wbuf[MAX_PATH+1];
    TCHAR fname[MAX_PATH+1];
    
    ZeroMemory(wbuf, sizeof(wbuf));
    ZeroMemory(fname, sizeof(fname));
    NH_A2W(filename, wbuf, MAX_PATH);
    if(*filename!='\\' && *filename!='/') {
        _tcscpy(fname, _nh_cwd);
        _tcsncat(fname, _T("\\"), MAX_PATH - _tcslen(fname));
    }
    _tcsncat(fname, wbuf, MAX_PATH - _tcslen(fname));
    return !DeleteFileW(fname);
}
int __cdecl write (int f, const void * buffer, unsigned int count)
Definition at line 293 of file celib.c.
References get_file_handle(), and NULL.
Referenced by bitmap_to_img(), bwrite(), copy_bytes(), getlock(), main(), restore_savefile(), and write_maze().
{
    HANDLE p = get_file_handle(f);
    DWORD bytes_written;
    if(!WriteFile(p, buffer, count, &bytes_written, NULL))
        return -1;
    else
        return (int)bytes_written;
}
Variable Documentation
char _day_mo[12] = { 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 } [static]
Definition at line 24 of file celib.c.
Referenced by localtime().
char _day_mo_leap[12] = { 31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 } [static]
Definition at line 23 of file celib.c.
Referenced by localtime().
TCHAR _nh_cwd[MAX_PATH] [static]
Definition at line 72 of file celib.c.
Referenced by chdir(), getcwd(), open(), and unlink().
HANDLE _nh_file_table[FILE_TABLE_SIZE] [static]
Definition at line 75 of file celib.c.
Referenced by alloc_file_handle(), close(), and get_file_handle().
union { ... } _t_cnv [static]
Referenced by localtime(), and time().
unsigned int dd
Definition at line 14 of file celib.c.
Referenced by place_niche().
int errno
Definition at line 345 of file celib.c.
Referenced by bitmap_to_img(), c__translate(), create_bonesfile(), create_levelfile(), fopen_config_file(), getlock(), gettty(), lock_file(), open_levelfile(), ReadImageFiles(), restore_savefile(), setctty(), validate_prefix_locations(), veryold(), and vms_open().
int file_pointer = -1 [static]
Definition at line 76 of file celib.c.
Referenced by alloc_file_handle().
unsigned int hh
Definition at line 15 of file celib.c.
const int MAGIC_OFFSET =5
Definition at line 73 of file celib.c.
Referenced by alloc_file_handle(), close(), and get_file_handle().
unsigned int mm
Definition at line 13 of file celib.c.
Referenced by deadbook(), dokick(), load_maze(), and makemaz().
unsigned int mo
Definition at line 16 of file celib.c.
unsigned int ss
Definition at line 12 of file celib.c.
time_t t_val
Definition at line 10 of file celib.c.
struct { ... } time_pack tm_val
unsigned int wd
Definition at line 18 of file celib.c.
Referenced by amii_create_nhwindow().
unsigned int yr
Definition at line 17 of file celib.c.