nethack/src/detect.c File Reference
#include `hack.h`
*
#include `artifact.h`
*
Functions
STATIC_DCL void FDECL (do_dknown_of,(struct obj *))
STATIC_DCL boolean FDECL (check_map_spot,(int, int, CHAR_P, unsigned))
STATIC_DCL boolean FDECL (clear_stale_map,(CHAR_P, unsigned))
STATIC_DCL void FDECL (sense_trap,(struct trap *, XCHAR_P, XCHAR_P, int))
STATIC_DCL void FDECL (show_map_spot,(int, int))
STATIC_PTR void FDECL (findone,(int, int, genericptr_t))
STATIC_PTR void FDECL (openone,(int, int, genericptr_t))
struct obj * o_in (struct obj *obj, char oclass)
struct obj * o_material (struct obj *obj, unsigned material)
STATIC_OVL void do_dknown_of (struct obj *obj)
STATIC_OVL boolean check_map_spot (int x, int y, char oclass, unsigned material)
STATIC_OVL boolean clear_stale_map (char oclass, unsigned material)
int gold_detect (struct obj *sobj)
int food_detect (struct obj *sobj)
int object_detect (struct obj *detector, int class)
int monster_detect (struct obj *otmp, int mclass)
STATIC_OVL void sense_trap (struct trap *trap, xchar x, xchar y, int src_cursed)
int trap_detect (struct obj *sobj)
const char * level_distance (d_level *where)
void use_crystal_ball (struct obj *obj)
STATIC_OVL void show_map_spot (int x, int y)
void do_mapping ()
void do_vicinity_map ()
void cvt_sdoor_to_door (struct rm *lev)
STATIC_PTR void findone (int zx, int zy, genericptr_t num)
STATIC_PTR void openone (int zx, int zy, genericptr_t num)
int findit ()
int openit ()
void find_trap (struct trap *trap)
int dosearch0 (int aflag)
int dosearch ()
void sokoban_detect ()
Variables
boolean known
xx xx xx xx xx xx xx xx xx
struct {
 const char * what
 d_level * where
} level_detects []
Function Documentation
STATIC_OVL boolean check_map_spot (int x, int y, char oclass, unsigned material)
Definition at line 78 of file detect.c.
References ALL_CLASSES, COIN_CLASS, FALSE, glyph_at(), glyph_is_object, glyph_to_obj, GOLD, level, m_at, monst::mgold, monst::minvent, obj::nobj, o_in(), o_material(), objects, dlevel_t::objects, otmp, and TRUE.
Referenced by clear_stale_map().
{
    register int glyph;
    register struct obj *otmp;
    register struct monst *mtmp;
    glyph = glyph_at(x,y);
    if (glyph_is_object(glyph)) {
        /* there's some object shown here */
        if (oclass == ALL_CLASSES) {
        return((boolean)(!(level.objects[x][y] || /* stale if nothing here */
                ((mtmp = m_at(x,y)) != 0 &&
                (
#ifndef GOLDOBJ
                 mtmp->mgold ||
#endif
                         mtmp->minvent)))));
        } else {
        if (material && objects[glyph_to_obj(glyph)].oc_material == material) {
            /* the object shown here is of interest because material matches */
            for (otmp = level.objects[x][y]; otmp; otmp = otmp->nexthere)
                if (o_material(otmp, GOLD)) return FALSE;
            /* didn't find it; perhaps a monster is carrying it */
            if ((mtmp = m_at(x,y)) != 0) {
                for (otmp = mtmp->minvent; otmp; otmp = otmp->nobj)
                    if (o_material(otmp, GOLD)) return FALSE;
                }
            /* detection indicates removal of this object from the map */
            return TRUE;
        }
            if (oclass && objects[glyph_to_obj(glyph)].oc_class == oclass) {
            /* the object shown here is of interest because its class matches */
            for (otmp = level.objects[x][y]; otmp; otmp = otmp->nexthere)
                if (o_in(otmp, oclass)) return FALSE;
            /* didn't find it; perhaps a monster is carrying it */
#ifndef GOLDOBJ
            if ((mtmp = m_at(x,y)) != 0) {
                if (oclass == COIN_CLASS && mtmp->mgold)
                    return FALSE;
                else for (otmp = mtmp->minvent; otmp; otmp = otmp->nobj)
                    if (o_in(otmp, oclass)) return FALSE;
                }
#else
            if ((mtmp = m_at(x,y)) != 0) {
                for (otmp = mtmp->minvent; otmp; otmp = otmp->nobj)
                    if (o_in(otmp, oclass)) return FALSE;
                }
#endif
            /* detection indicates removal of this object from the map */
            return TRUE;
            }
        }
    }
    return FALSE;
}
STATIC_OVL boolean clear_stale_map (char oclass, unsigned material)
Definition at line 144 of file detect.c.
References check_map_spot(), COLNO, FALSE, ROWNO, TRUE, and unmap_object().
Referenced by food_detect(), gold_detect(), and object_detect().
{
    register int zx, zy;
    register boolean change_made = FALSE;
    for (zx = 1; zx < COLNO; zx++)
        for (zy = 0; zy < ROWNO; zy++)
        if (check_map_spot(zx, zy, oclass,material)) {
            unmap_object(zx, zy);
            change_made = TRUE;
        }
    return change_made;
}
void cvt_sdoor_to_door (struct rm * lev)
Definition at line 982 of file detect.c.
References D_CLOSED, D_LOCKED, D_NODOOR, DOOR, Is_rogue_level, u, you::uz, and WM_MASK.
Referenced by dokick(), dosearch0(), findone(), and openone().
{
    int newmask = lev->doormask & ~WM_MASK;
#ifdef REINCARNATION
    if (Is_rogue_level(&u.uz))
        /* rogue didn't have doors, only doorways */
        newmask = D_NODOOR;
    else
#endif
        /* newly exposed door is closed */
        if (!(newmask & D_LOCKED)) newmask |= D_CLOSED;
    lev->typ = DOOR;
    lev->doormask = newmask;
}
STATIC_OVL void do_dknown_of (struct obj * obj)
Definition at line 64 of file detect.c.
References obj::cobj, Has_contents, obj::nobj, and otmp.
Referenced by object_detect().
{
    struct obj *otmp;
    obj->dknown = 1;
    if (Has_contents(obj)) {
    for(otmp = obj->cobj; otmp; otmp = otmp->nobj)
        do_dknown_of(otmp);
    }
}
void do_mapping ()
Definition at line 942 of file detect.c.
References A_WIS, COLNO, display_nhwindow, docrt(), dlevel_t::flags, flush_screen(), level, ROWNO, show_map_spot(), TRUE, u, Underwater, and WIN_MAP.
Referenced by dosit().
{
    register int zx, zy;
    int uw = u.uinwater;
    u.uinwater = 0;
    for (zx = 1; zx < COLNO; zx++)
    for (zy = 0; zy < ROWNO; zy++)
        show_map_spot(zx, zy);
    exercise(A_WIS, TRUE);
    u.uinwater = uw;
    if (!level.flags.hero_memory || Underwater) {
    flush_screen(1); /* flush temp screen */
    display_nhwindow(WIN_MAP, TRUE); /* wait */
    docrt();
    }
}
void do_vicinity_map ()
Definition at line 961 of file detect.c.
References COLNO, display_nhwindow, docrt(), dlevel_t::flags, flush_screen(), level, ROWNO, show_map_spot(), TRUE, u, Underwater, you::ux, you::uy, and WIN_MAP.
Referenced by spelleffects().
{
    register int zx, zy;
    int lo_y = (u.uy-5 < 0 ? 0 : u.uy-5),
    hi_y = (u.uy+6 > ROWNO ? ROWNO : u.uy+6),
    lo_x = (u.ux-9 < 1 ? 1 : u.ux-9), /* avoid column 0 */
    hi_x = (u.ux+10 > COLNO ? COLNO : u.ux+10);
    for (zx = lo_x; zx < hi_x; zx++)
    for (zy = lo_y; zy < hi_y; zy++)
        show_map_spot(zx, zy);
    if (!level.flags.hero_memory || Underwater) {
    flush_screen(1); /* flush temp screen */
    display_nhwindow(WIN_MAP, TRUE); /* wait */
    docrt();
    }
}
int dosearch ()
Definition at line 1267 of file detect.c.
References dosearch0().
{
    return(dosearch0(0));
}
int dosearch0 (int aflag)
Definition at line 1159 of file detect.c.
References A_WIS, Blind, canspotmon, CORR, cvt_sdoor_to_door(), monst::data, FALSE, feel_location(), find_trap(), glyph_is_invisible, is_hider, levl, monst::m_ap_type, m_at, map_invisible(), permonst::mlet, newsym(), obj::oartifact, obj::otyp, S_EEL, SCORR, SDOOR, sensemon, obj::spe, SPFX_SEARCH, STATUE_TRAP, TRUE, u, ublindf, unblock_point(), unmap_object(), uwep, you::ux, and you::uy.
Referenced by dosearch().
{
#ifdef GCC_BUG
/* some versions of gcc seriously muck up nested loops. if you get strange
   crashes while searching in a version compiled with gcc, try putting
   #define GCC_BUG in *conf.h (or adding -DGCC_BUG to CFLAGS in the
   makefile).
 */
    volatile xchar x, y;
#else
    register xchar x, y;
#endif
    register struct trap *trap;
    register struct monst *mtmp;
    if(u.uswallow) {
        if (!aflag)
            pline("What are you looking for? The exit?");
    } else {
        int fund = (uwep && uwep->oartifact &&
            spec_ability(uwep, SPFX_SEARCH)) ?
            uwep->spe : 0;
        if (ublindf && ublindf->otyp == LENSES && !Blind)
            fund += 2; /* JDS: lenses help searching */
        if (fund > 5) fund = 5;
        for(x = u.ux-1; x < u.ux+2; x++)
          for(y = u.uy-1; y < u.uy+2; y++) {
        if(!isok(x,y)) continue;
        if(x != u.ux || y != u.uy) {
            if (Blind && !aflag) feel_location(x,y);
            if(levl[x][y].typ == SDOOR) {
            if(rnl(7-fund)) continue;
            cvt_sdoor_to_door(&levl[x][y]); /* .typ = DOOR */
            exercise(A_WIS, TRUE);
            nomul(0);
            if (Blind && !aflag)
                feel_location(x,y); /* make sure it shows up */
            else
                newsym(x,y);
            } else if(levl[x][y].typ == SCORR) {
            if(rnl(7-fund)) continue;
            levl[x][y].typ = CORR;
            unblock_point(x,y); /* vision */
            exercise(A_WIS, TRUE);
            nomul(0);
            newsym(x,y);
            } else {
        /* Be careful not to find anything in an SCORR or SDOOR */
            if((mtmp = m_at(x, y)) && !aflag) {
                if(mtmp->m_ap_type) {
                seemimic(mtmp);
        find: exercise(A_WIS, TRUE);
                if (!canspotmon(mtmp)) {
                    if (glyph_is_invisible(levl[x][y].glyph)) {
                    /* found invisible monster in a square
                     * which already has an 'I' in it.
                     * Logically, this should still take
                     * time and lead to a return(1), but if
                     * we did that the player would keep
                     * finding the same monster every turn.
                     */
                    continue;
                    } else {
                    You_feel("an unseen monster!");
                    map_invisible(x, y);
                    }
                } else if (!sensemon(mtmp))
                    You("find %s.", a_monnam(mtmp));
                return(1);
                }
                if(!canspotmon(mtmp)) {
                if (mtmp->mundetected &&
                   (is_hider(mtmp->data) || mtmp->data->mlet ==
      S_EEL))
                    mtmp->mundetected = 0;
                newsym(x,y);
                goto find;
                }
            }
            /* see if an invisible monster has moved--if Blind,
             * feel_location() already did it
             */
            if (!aflag && !mtmp && !Blind &&
                    glyph_is_invisible(levl[x][y].glyph)) {
                unmap_object(x,y);
                newsym(x,y);
            }
            if ((trap = t_at(x,y)) && !trap->tseen && !rnl(8)) {
                nomul(0);
                if (trap->ttyp == STATUE_TRAP) {
                if (activate_statue_trap(trap, x, y, FALSE))
                    exercise(A_WIS, TRUE);
                return(1);
                } else {
                find_trap(trap);
                }
            }
            }
        }
        }
    }
    return(1);
}
STATIC_DCL void FDECL (do_dknown_of , (struct obj *))
STATIC_DCL boolean FDECL (check_map_spot , (int, int, CHAR_P, unsigned))
STATIC_DCL boolean FDECL (clear_stale_map , (CHAR_P, unsigned))
STATIC_DCL void FDECL (sense_trap , (struct trap *, XCHAR_P, XCHAR_P, int))
STATIC_DCL void FDECL (show_map_spot , (int, int))
STATIC_PTR void FDECL (findone , (int, int, genericptr_t))
STATIC_PTR void FDECL (openone , (int, int, genericptr_t))
void find_trap (struct trap * trap)
Definition at line 1129 of file detect.c.
References A_WIS, Blind, cls(), defsyms, display_nhwindow, display_self, docrt(), FALSE, feel_location(), levl, map_trap(), newsym(), trap_to_defsym, trap_to_glyph, TRUE, what_trap, and WIN_MAP.
Referenced by dosearch0(), and kick_object().
{
    int tt = what_trap(trap->ttyp);
    boolean cleared = FALSE;
    trap->tseen = 1;
    exercise(A_WIS, TRUE);
    if (Blind)
    feel_location(trap->tx, trap->ty);
    else
    newsym(trap->tx, trap->ty);
    if (levl[trap->tx][trap->ty].glyph != trap_to_glyph(trap)) {
        /* There's too much clutter to see your find otherwise */
    cls();
    map_trap(trap, 1);
    display_self();
    cleared = TRUE;
    }
    You("find %s.", an(defsyms[trap_to_defsym(tt)].explanation));
    if (cleared) {
    display_nhwindow(WIN_MAP, TRUE); /* wait */
    docrt();
    }
}
int findit ()
Definition at line 1101 of file detect.c.
References BOLT_LIM, do_clear_area(), findone(), u, you::ux, and you::uy.
{
    int num = 0;
    if(u.uswallow) return(0);
    do_clear_area(u.ux, u.uy, BOLT_LIM, findone, (
      genericptr_t) &num);
    return(num);
}
STATIC_PTR void findone (int zx, int zy, genericptr_t num)
Definition at line 1002 of file detect.c.
References canspotmon, CORR, cvt_sdoor_to_door(), monst::data, glyph_is_invisible, is_hider, levl, monst::m_ap_type, m_at, magic_map_background(), map_invisible(), permonst::mlet, newsym(), S_EEL, SCORR, SDOOR, STATUE_TRAP, unblock_point(), and unmap_object().
Referenced by findit().
{
    register struct trap *ttmp;
    register struct monst *mtmp;
    if(levl[zx][zy].typ == SDOOR) {
        cvt_sdoor_to_door(&levl[zx][zy]); /* .typ = DOOR */
        magic_map_background(zx, zy, 0);
        newsym(zx, zy);
        (*(int*)num)++;
    } else if(levl[zx][zy].typ == SCORR) {
        levl[zx][zy].typ = CORR;
        unblock_point(zx,zy);
        magic_map_background(zx, zy, 0);
        newsym(zx, zy);
        (*(int*)num)++;
    } else if ((ttmp = t_at(zx, zy)) != 0) {
        if(!ttmp->tseen && ttmp->ttyp != STATUE_TRAP) {
            ttmp->tseen = 1;
            newsym(zx,zy);
            (*(int*)num)++;
        }
    } else if ((mtmp = m_at(zx, zy)) != 0) {
        if(mtmp->m_ap_type) {
            seemimic(mtmp);
            (*(int*)num)++;
        }
        if (mtmp->mundetected &&
            (is_hider(mtmp->data) || mtmp->data->mlet ==
      S_EEL)) {
            mtmp->mundetected = 0;
            newsym(zx, zy);
            (*(int*)num)++;
        }
        if (!canspotmon(mtmp) &&
                    !glyph_is_invisible(levl[zx][zy].glyph))
            map_invisible(zx, zy);
    } else if (glyph_is_invisible(levl[zx][zy].glyph)) {
        unmap_object(zx, zy);
        newsym(zx, zy);
        (*(int*)num)++;
    }
}
int food_detect (struct obj	* sobj)
Definition at line 294 of file detect.c.
References A_WIS, flag::beginner, buf, BUFSZ, clear_stale_map(), cls(), Confusion, display_nhwindow, docrt(), FALSE, flags, fmon, fobj, FOOD_CLASS, known, map_object(), monst::minvent, monst::mx, monst::my, newsym(), monst::nmon, obj::nobj, NOSE, o_in(), obj::ox, obj::oy, POTION_CLASS, something, Sprintf, temp, TRUE, u, under_ground(), under_water(), Underwater, you::ux, you::uy, what, and WIN_MAP.
{
    register struct obj *obj;
    register struct monst *mtmp;
    register int ct = 0, ctu = 0;
    boolean confused = (Confusion || (sobj && sobj->cursed)), stale;
    char oclass = confused ? POTION_CLASS : FOOD_CLASS;
    const char *what = confused ? something : "food";
    int uw = u.uinwater;
    stale = clear_stale_map(oclass, 0);
    for (obj = fobj; obj; obj = obj->nobj)
    if (o_in(obj, oclass)) {
        if (obj->ox == u.ux && obj->oy == u.uy) ctu++;
        else ct++;
    }
    for (mtmp = fmon; mtmp && !ct; mtmp = mtmp->nmon) {
    /* no DEADMONSTER(mtmp) check needed since dmons never have inventory */
    for (obj = mtmp->minvent; obj; obj = obj->nobj)
        if (o_in(obj, oclass)) {
        ct++;
        break;
        }
    }
    
    if (!ct && !ctu) {
    known = stale && !confused;
    if (stale) {
        docrt();
        You("sense a lack of %s nearby.", what);
        if (sobj && sobj->blessed) {
        if (!u.uedibility) Your("%s starts to tingle.", body_part(NOSE));
        u.uedibility = 1;
        }
    } else if (sobj) {
        char buf[BUFSZ];
        Sprintf(buf, "Your %s twitches%s.", body_part(NOSE),
            (sobj->blessed && !u.uedibility) ? " then starts to tingle" : "");
        if (sobj->blessed && !u.uedibility) {
        boolean savebeginner = flags.beginner; /* prevent non-delivery of */
        flags.beginner = FALSE; /* message */
        strange_feeling(sobj, buf);
        flags.beginner = savebeginner;
        u.uedibility = 1;
        } else
        strange_feeling(sobj, buf);
    }
    return !stale;
    } else if (!ct) {
    known = TRUE;
    You("%s %s nearby.", sobj ? "smell" : "sense", what);
    if (sobj && sobj->blessed) {
        if (!u.uedibility) pline("Your %s starts to tingle.", body_part(NOSE));
        u.uedibility = 1;
    }
    } else {
    struct obj *temp;
    known = TRUE;
    cls();
    u.uinwater = 0;
    for (obj = fobj; obj; obj = obj->nobj)
        if ((temp = o_in(obj, oclass)) != 0) {
        if (temp != obj) {
            temp->ox = obj->ox;
            temp->oy = obj->oy;
        }
        map_object(temp,1);
        }
    for (mtmp = fmon; mtmp; mtmp = mtmp->nmon)
        /* no DEADMONSTER(mtmp) check needed since dmons never have inventory */
        for (obj = mtmp->minvent; obj; obj = obj->nobj)
        if ((temp = o_in(obj, oclass)) != 0) {
            temp->ox = mtmp->mx;
            temp->oy = mtmp->my;
            map_object(temp,1);
            break; /* skip rest of this monster's inventory */
        }
    newsym(u.ux,u.uy);
    if (sobj) {
        if (sobj->blessed) {
            Your("%s %s to tingle and you smell %s.", body_part(NOSE),
                u.uedibility ? "continues" : "starts", what);
        u.uedibility = 1;
        } else
        Your("%s tingles and you smell %s.", body_part(NOSE), what);
    }
    else You("sense %s.", what);
    display_nhwindow(WIN_MAP, TRUE);
    exercise(A_WIS, TRUE);
    docrt();
    u.uinwater = uw;
    if (Underwater) under_water(2);
    if (u.uburied) under_ground(2);
    }
    return(0);
}
int gold_detect (struct obj * sobj)
Definition at line 163 of file detect.c.
References A_WIS, buf, BUFSZ, clear_stale_map(), cls(), COIN_CLASS, monst::data, DEADMONSTER, display_nhwindow, docrt(), fmon, fobj, FOOT, GOLD, invent, known, map_object(), monst::mgold, monst::minvent, mons, monst::mx, monst::my, newsym(), monst::nmon, obj::nobj, o_in(), o_material(), obj::otyp, obj::ox, obj::oy, Sprintf, Strcpy, temp, TRUE, u, you::ugold, under_ground(), under_water(), Underwater, you::ux, you::uy, WIN_MAP, and youmonst.
{
    register struct obj *obj;
    register struct monst *mtmp;
    int uw = u.uinwater;
    struct obj *temp;
    boolean stale;
    known = stale = clear_stale_map(COIN_CLASS,
                (unsigned)(sobj->blessed ? GOLD : 0));
    /* look for gold carried by monsters (might be in a container) */
    for (mtmp = fmon; mtmp; mtmp = mtmp->nmon) {
        if (DEADMONSTER(mtmp)) continue; /* probably not needed in this case but... */
#ifndef GOLDOBJ
    if (mtmp->mgold || monsndx(mtmp->data) == PM_GOLD_GOLEM) {
#else
    if (findgold(mtmp->minvent) || monsndx(mtmp->data) == PM_GOLD_GOLEM) {
#endif
        known = TRUE;
        goto outgoldmap; /* skip further searching */
    } else for (obj = mtmp->minvent; obj; obj = obj->nobj)
        if (sobj->blessed && o_material(obj, GOLD)) {
            known = TRUE;
            goto outgoldmap;
        } else if (o_in(obj, COIN_CLASS)) {
        known = TRUE;
        goto outgoldmap; /* skip further searching */
        }
    }
    
    /* look for gold objects */
    for (obj = fobj; obj; obj = obj->nobj) {
    if (sobj->blessed && o_material(obj, GOLD)) {
        known = TRUE;
        if (obj->ox != u.ux || obj->oy != u.uy) goto outgoldmap;
    } else if (o_in(obj, COIN_CLASS)) {
        known = TRUE;
        if (obj->ox != u.ux || obj->oy != u.uy) goto outgoldmap;
    }
    }
    if (!known) {
    /* no gold found on floor or monster's inventory.
       adjust message if you have gold in your inventory */
    if (sobj) {
        char buf[BUFSZ];
        if (youmonst.data == &mons[PM_GOLD_GOLEM]) {
            Sprintf(buf, "You feel like a million %s!",
                currency(2L));
        } else if (hidden_gold() ||
#ifndef GOLDOBJ
                u.ugold)
#else
                    money_cnt(invent))
#endif
            Strcpy(buf,
                "You feel worried about your future financial situation.");
        else
            Strcpy(buf, "You feel materially poor.");
        strange_feeling(sobj, buf);
        }
    return(1);
    }
    /* only under me - no separate display required */
    if (stale) docrt();
    You("notice some gold between your %s.", makeplural(body_part(FOOT)));
    return(0);
outgoldmap:
    cls();
    u.uinwater = 0;
    /* Discover gold locations. */
    for (obj = fobj; obj; obj = obj->nobj) {
        if (sobj->blessed && (temp = o_material(obj, GOLD))) {
        if (temp != obj) {
        temp->ox = obj->ox;
        temp->oy = obj->oy;
        }
        map_object(temp,1);
    } else if ((temp = o_in(obj, COIN_CLASS))) {
        if (temp != obj) {
        temp->ox = obj->ox;
        temp->oy = obj->oy;
        }
        map_object(temp,1);
    }
    }
    for (mtmp = fmon; mtmp; mtmp = mtmp->nmon) {
        if (DEADMONSTER(mtmp)) continue; /* probably overkill here */
#ifndef GOLDOBJ
    if (mtmp->mgold || monsndx(mtmp->data) == PM_GOLD_GOLEM) {
#else
    if (findgold(mtmp->minvent) || monsndx(mtmp->data) == PM_GOLD_GOLEM) {
#endif
        struct obj gold;
        gold.otyp = GOLD_PIECE;
        gold.ox = mtmp->mx;
        gold.oy = mtmp->my;
        map_object(&gold,1);
    } else for (obj = mtmp->minvent; obj; obj = obj->nobj)
        if (sobj->blessed && (temp = o_material(obj, GOLD))) {
        temp->ox = mtmp->mx;
        temp->oy = mtmp->my;
        map_object(temp,1);
        break;
        } else if ((temp = o_in(obj, COIN_CLASS))) {
        temp->ox = mtmp->mx;
        temp->oy = mtmp->my;
        map_object(temp,1);
        break;
        }
    }
    
    newsym(u.ux,u.uy);
    You_feel("very greedy, and sense gold!");
    exercise(A_WIS, TRUE);
    display_nhwindow(WIN_MAP, TRUE);
    docrt();
    u.uinwater = uw;
    if (Underwater) under_water(2);
    if (u.uburied) under_ground(2);
    return(0);
}
const char* level_distance (d_level * where)
Definition at line 748 of file detect.c.
References d_level::dnum, u, and you::uz.
Referenced by use_crystal_ball().
{
    register schar ll = depth(&u.uz) - depth(where);
    register boolean indun = (u.uz.dnum == where->dnum);
    if (ll < 0) {
    if (ll < (-8 - rn2(3)))
        if (!indun) return "far away";
        else return "far below";
    else if (ll < -1)
        if (!indun) return "away below you";
        else return "below you";
    else
        if (!indun) return "in the distance";
        else return "just below";
    } else if (ll > 0) {
    if (ll > (8 + rn2(3)))
        if (!indun) return "far away";
        else return "far above";
    else if (ll > 1)
        if (!indun) return "away above you";
        else return "above you";
    else
        if (!indun) return "in the distance";
        else return "just above";
    } else
        if (!indun) return "in the distance";
        else return "near you";
}
int monster_detect (struct obj * otmp, int mclass)
Definition at line 583 of file detect.c.
References cls(), monst::data, DEADMONSTER, def_monsyms, detect_wsegs(), detected_mon_to_glyph, display_nhwindow, display_self, docrt(), FALSE, fmon, Hallucination, permonst::mlet, mon_to_glyph, mons, monst::mx, monst::my, monst::nmon, S_WORM_TAIL, show_glyph(), TRUE, u, under_ground(), under_water(), Underwater, and WIN_MAP.
Referenced by drinkfountain(), and use_crystal_ball().
{
    register struct monst *mtmp;
    int mcnt = 0;
    /* Note: This used to just check fmon for a non-zero value
     * but in versions since 3.3.0 fmon can test TRUE due to the
     * presence of dmons, so we have to find at least one
     * with positive hit-points to know for sure.
     */
    for (mtmp = fmon; mtmp; mtmp = mtmp->nmon)
        if (!DEADMONSTER(mtmp)) {
        mcnt++;
        break;
    }
    if (!mcnt) {
    if (otmp)
        strange_feeling(otmp, Hallucination ?
                "You get the heebie jeebies." :
                "You feel threatened.");
    return 1;
    } else {
    boolean woken = FALSE;
    cls();
    for (mtmp = fmon; mtmp; mtmp = mtmp->nmon) {
        if (DEADMONSTER(mtmp)) continue;
        if (!mclass || mtmp->data->mlet == mclass ||
        (mtmp->data == &mons[PM_LONG_WORM] && mclass == S_WORM_TAIL))
            if (mtmp->mx > 0) {
                if (mclass && def_monsyms[mclass] == ' ')
                show_glyph(mtmp->mx,mtmp->my,
                    detected_mon_to_glyph(mtmp));
            else
                show_glyph(mtmp->mx,mtmp->my,mon_to_glyph(mtmp));
            /* don't be stingy - display entire worm */
            if (mtmp->data == &mons[PM_LONG_WORM]) detect_wsegs(mtmp,0);
            }
        if (otmp && otmp->cursed &&
        (mtmp->msleeping || !mtmp->mcanmove)) {
        mtmp->msleeping = mtmp->mfrozen = 0;
        mtmp->mcanmove = 1;
        woken = TRUE;
        }
    }
    display_self();
    You("sense the presence of monsters.");
    if (woken)
        pline("Monsters sense the presence of you.");
    display_nhwindow(WIN_MAP, TRUE);
    docrt();
    if (Underwater) under_water(2);
    if (u.uburied) under_ground(2);
    }
    return 0;
}
struct obj* o_in (struct obj* obj, char oclass)
Definition at line 25 of file detect.c.
References obj::cobj, Has_contents, obj::nobj, obj::oclass, otmp, and temp.
Referenced by check_map_spot(), food_detect(), gold_detect(), and object_detect().
{
    register struct obj* otmp;
    struct obj *temp;
    if (obj->oclass == oclass) return obj;
    if (Has_contents(obj)) {
    for (otmp = obj->cobj; otmp; otmp = otmp->nobj)
        if (otmp->oclass == oclass) return otmp;
        else if (Has_contents(otmp) && (temp = o_in(otmp, oclass)))
        return temp;
    }
    return (struct obj *) 0;
}
struct obj* o_material (struct obj* obj, unsigned material)
Definition at line 45 of file detect.c.
References obj::cobj, Has_contents, obj::nobj, objects, otmp, obj::otyp, and temp.
Referenced by check_map_spot(), and gold_detect().
{
    register struct obj* otmp;
    struct obj *temp;
    if (objects[obj->otyp].oc_material == material) return obj;
    if (Has_contents(obj)) {
    for (otmp = obj->cobj; otmp; otmp = otmp->nobj)
        if (objects[otmp->otyp].oc_material == material) return otmp;
        else if (Has_contents(otmp) && (temp = o_material(otmp, material)))
        return temp;
    }
    return (struct obj *) 0;
}
int object_detect (struct obj	* detector, int class)
Definition at line 400 of file detect.c.
References ALL_CLASSES, BUFSZ, dlevel_t::buriedobjlist, clear_stale_map(), cls(), COIN_CLASS, COLNO, obj::corpsenm, DEADMONSTER, def_oc_syms, display_nhwindow, do_dknown_of(), docrt(), fmon, level, M_AP_OBJECT, monst::m_ap_type, map_object(), monst::mappearance, MAXOCLASSES, monst::mgold, monst::minvent, monst::mx, monst::my, newsym(), monst::nmon, obj::nobj, nobj, o_in(), objects, dlevel_t::objects, objclass::oc_class, obj::oclass, otmp, obj::otyp, obj::ox, obj::oy, POTION_CLASS, ROCK_CLASS, ROWNO, SPBOOK_CLASS, Strcat, Strcpy, TRUE, u, under_ground(), under_water(), Underwater, you::ux, you::uy, and WIN_MAP.
Referenced by use_crystal_ball().
{
    register int x, y;
    char stuff[BUFSZ];
    int is_cursed = (detector && detector->cursed);
    int do_dknown = (detector && (detector->oclass == POTION_CLASS ||
                    detector->oclass == SPBOOK_CLASS) &&
            detector->blessed);
    int ct = 0, ctu = 0;
    register struct obj *obj, *otmp = (struct obj *)0;
    register struct monst *mtmp;
    int uw = u.uinwater;
    int sym, boulder = 0;
    if (class < 0 || class >= MAXOCLASSES) {
    impossible("object_detect: illegal class %d", class);
    class = 0;
    }
    /* Special boulder symbol check - does the class symbol happen
     * to match iflags.bouldersym which is a user-defined?
     * If so, that means we aren't sure what they really wanted to
     * detect. Rather than trump anything, show both possibilities.
     * We can exclude checking the buried obj chain for boulders below.
     */
    sym = class ? def_oc_syms[class] : 0;
    if (sym && iflags.bouldersym && sym == iflags.bouldersym)
        boulder = ROCK_CLASS;
    if (Hallucination || (Confusion && class == SCROLL_CLASS))
    Strcpy(stuff, something);
    else
        Strcpy(stuff, class ? oclass_names[class] : "objects");
    if (boulder && class != ROCK_CLASS) Strcat(stuff, " and/or large stones");
    if (do_dknown) for(obj = invent; obj; obj = obj->nobj) do_dknown_of(obj);
    for (obj = fobj; obj; obj = obj->nobj) {
    if ((!class && !boulder) || o_in(obj, class) || o_in(obj, boulder)) {
        if (obj->ox == u.ux && obj->oy == u.uy) ctu++;
        else ct++;
    }
    if (do_dknown) do_dknown_of(obj);
    }
    for (obj = level.buriedobjlist; obj; obj = obj->nobj) {
    if (!class || o_in(obj, class)) {
        if (obj->ox == u.ux && obj->oy == u.uy) ctu++;
        else ct++;
    }
    if (do_dknown) do_dknown_of(obj);
    }
    for (mtmp = fmon; mtmp; mtmp = mtmp->nmon) {
    if (DEADMONSTER(mtmp)) continue;
    for (obj = mtmp->minvent; obj; obj = obj->nobj) {
        if ((!class && !boulder) || o_in(obj, class) || o_in(obj, boulder)) ct++;
        if (do_dknown) do_dknown_of(obj);
    }
    if ((is_cursed && mtmp->m_ap_type == M_AP_OBJECT &&
        (!class || class == objects[mtmp->mappearance].
      oc_class)) ||
#ifndef GOLDOBJ
        (mtmp->mgold && (!class || class == COIN_CLASS))) {
#else
        (findgold(mtmp->minvent) && (!class || class == COIN_CLASS))) {
#endif
        ct++;
        break;
    }
    }
    if (!clear_stale_map(!class ? ALL_CLASSES : class, 0) && !ct) {
    if (!ctu) {
        if (detector)
        strange_feeling(detector, "You feel a lack of something.");
        return 1;
    }
    You("sense %s nearby.", stuff);
    return 0;
    }
    cls();
    u.uinwater = 0;
/*
 * Map all buried objects first.
 */
    for (obj = level.buriedobjlist; obj; obj = obj->nobj)
    if (!class || (otmp = o_in(obj, class))) {
        if (class) {
        if (otmp != obj) {
            otmp->ox = obj->ox;
            otmp->oy = obj->oy;
        }
        map_object(otmp, 1);
        } else
        map_object(obj, 1);
    }
    /*
     * If we are mapping all objects, map only the top object of a pile or
     * the first object in a monster's inventory. Otherwise, go looking
     * for a matching object class and display the first one encountered
     * at each location.
     *
     * Objects on the floor override buried objects.
     */
    for (x = 1; x < COLNO; x++)
    for (y = 0; y < ROWNO; y++)
        for (obj = level.objects[x][y]; obj; obj = obj->nexthere)
        if ((!class && !boulder) ||
            (otmp = o_in(obj, class)) || (otmp = o_in(obj, boulder))) {
            if (class || boulder) {
            if (otmp != obj) {
                otmp->ox = obj->ox;
                otmp->oy = obj->oy;
            }
            map_object(otmp, 1);
            } else
            map_object(obj, 1);
            break;
        }
    /* Objects in the monster's inventory override floor objects. */
    for (mtmp = fmon ; mtmp ; mtmp = mtmp->nmon) {
    if (DEADMONSTER(mtmp)) continue;
    for (obj = mtmp->minvent; obj; obj = obj->nobj)
        if ((!class && !boulder) ||
         (otmp = o_in(obj, class)) || (otmp = o_in(obj, boulder))) {
        if (!class && !boulder) otmp = obj;
        otmp->ox = mtmp->mx; /* at monster location */
        otmp->oy = mtmp->my;
        map_object(otmp, 1);
        break;
        }
    /* Allow a mimic to override the detected objects it is carrying. */
    if (is_cursed && mtmp->m_ap_type == M_AP_OBJECT &&
        (!class || class == objects[mtmp->mappearance].
      oc_class)) {
        struct obj temp;
        temp.otyp = mtmp->mappearance; /* needed for obj_to_glyph() */
        temp.ox = mtmp->mx;
        temp.oy = mtmp->my;
        temp.corpsenm = PM_TENGU; /* if mimicing a corpse */
        map_object(&temp, 1);
#ifndef GOLDOBJ
    } else if (mtmp->mgold && (!class || class == COIN_CLASS)) {
#else
    } else if (findgold(mtmp->minvent) && (!class || class == COIN_CLASS)) {
#endif
        struct obj gold;
        gold.otyp = GOLD_PIECE;
        gold.ox = mtmp->mx;
        gold.oy = mtmp->my;
        map_object(&gold, 1);
    }
    }
    newsym(u.ux,u.uy);
    You("detect the %s of %s.", ct ? "presence" : "absence", stuff);
    display_nhwindow(WIN_MAP, TRUE);
    /*
     * What are we going to do when the hero does an object detect while blind
     * and the detected object covers a known pool?
     */
    docrt(); /* this will correctly reset vision */
    u.uinwater = uw;
    if (Underwater) under_water(2);
    if (u.uburied) under_ground(2);
    return 0;
}
int openit ()
Definition at line 1111 of file detect.c.
References Blind, BOLT_LIM, monst::data, do_clear_area(), is_animal, openone(), TRUE, u, you::ustuck, you::ux, and you::uy.
{
    int num = 0;
    if(u.uswallow) {
        if (is_animal(u.ustuck->data)) {
            if (Blind) pline("Its mouth opens!");
            else pline("%s opens its mouth!", Monnam(u.ustuck));
        }
        expels(u.ustuck, u.ustuck->data, TRUE);
        return(-1);
    }
    do_clear_area(u.ux, u.uy, BOLT_LIM, openone, (
      genericptr_t) &num);
    return(num);
}
STATIC_PTR void openone (int zx, int zy, genericptr_t num)
Definition at line 1048 of file detect.c.
References cansee, CORR, cvt_sdoor_to_door(), D_CLOSED, D_ISOPEN, D_LOCKED, D_NODOOR, D_TRAPPED, distu, DOOR, doormask, flags, Is_box, level, levl, newsym(), OBJ_AT, dlevel_t::objects, otmp, SCORR, SDOOR, flag::soundok, STATUE_TRAP, and unblock_point().
Referenced by openit().
{
    register struct trap *ttmp;
    register struct obj *otmp;
    if(OBJ_AT(zx, zy)) {
        for(otmp = level.objects[zx][zy];
                otmp; otmp = otmp->nexthere) {
            if(Is_box(otmp) && otmp->olocked) {
            otmp->olocked = 0;
            (*(int*)num)++;
            }
        }
        /* let it fall to the next cases. could be on trap. */
    }
    if(levl[zx][zy].typ == SDOOR || (levl[zx][zy].typ == DOOR &&
              (levl[zx][zy].doormask & (D_CLOSED|D_LOCKED)))) {
        if(levl[zx][zy].typ == SDOOR)
            cvt_sdoor_to_door(&levl[zx][zy]); /* .typ = DOOR */
        if(levl[zx][zy].doormask & D_TRAPPED) {
            if(distu(zx, zy) < 3) b_trapped("door", 0);
            else Norep("You %s an explosion!",
                cansee(zx, zy) ? "see" :
                   (flags.soundok ? "hear" :
                        "feel the shock of"));
            wake_nearto(zx, zy, 11*11);
            levl[zx][zy].doormask = D_NODOOR;
        } else
            levl[zx][zy].doormask = D_ISOPEN;
        unblock_point(zx, zy);
        newsym(zx, zy);
        (*(int*)num)++;
    } else if(levl[zx][zy].typ == SCORR) {
        levl[zx][zy].typ = CORR;
        unblock_point(zx, zy);
        newsym(zx, zy);
        (*(int*)num)++;
    } else if ((ttmp = t_at(zx, zy)) != 0) {
        if (!ttmp->tseen && ttmp->ttyp != STATUE_TRAP) {
            ttmp->tseen = 1;
            newsym(zx,zy);
            (*(int*)num)++;
        }
    } else if (find_drawbridge(&zx, &zy)) {
        /* make sure it isn't an open drawbridge */
        open_drawbridge(zx, zy);
        (*(int*)num)++;
    }
}
STATIC_OVL void sense_trap (struct trap * trap, xchar x, xchar y, int src_cursed)
Definition at line 645 of file detect.c.
References BEAR_TRAP, obj::corpsenm, Hallucination, map_object(), map_trap(), obj::otyp, obj::ox, obj::oy, random_monster, random_object, trap::tx, trap::ty, trap::x, and trap::y.
Referenced by trap_detect().
{
    if (Hallucination || src_cursed) {
    struct obj obj; /* fake object */
    if (trap) {
        obj.ox = trap->tx;
        obj.oy = trap->ty;
    } else {
        obj.ox = x;
        obj.oy = y;
    }
    obj.otyp = (src_cursed) ? GOLD_PIECE : random_object();
    obj.corpsenm = random_monster(); /* if otyp == CORPSE */
    map_object(&obj,1);
    } else if (trap) {
    map_trap(trap,1);
    trap->tseen = 1;
    } else {
    struct trap temp_trap; /* fake trap */
    temp_trap.tx = x;
    temp_trap.ty = y;
    temp_trap.ttyp = BEAR_TRAP; /* some kind of trap */
    map_trap(&temp_trap,1);
    }
}
STATIC_OVL void show_map_spot (int x, int y)
Definition at line 911 of file detect.c.
References Confusion, CORR, dlevel_t::flags, rm::glyph, glyph_is_cmap, glyph_is_object, glyph_is_trap, glyph_to_cmap, level, levl, magic_map_background(), newsym(), ROOM, SCORR, rm::seenv, SVALL, rm::typ, and unblock_point().
Referenced by do_mapping(), and do_vicinity_map().
{
    register struct rm *lev;
    if (Confusion && rn2(7)) return;
    lev = &levl[x][y];
    lev->seenv = SVALL;
    /* Secret corridors are found, but not secret doors. */
    if (lev->typ == SCORR) {
    lev->typ = CORR;
    unblock_point(x,y);
    }
    /* if we don't remember an object or trap there, map it */
    if (lev->typ == ROOM ?
        (glyph_is_cmap(lev->glyph) && !glyph_is_trap(lev->
      glyph) &&
        glyph_to_cmap(lev->glyph) != ROOM) :
        (!glyph_is_object(lev->glyph) && !glyph_is_trap(lev->
      glyph))) {
    if (level.flags.hero_memory) {
        magic_map_background(x,y,0);
        newsym(x,y); /* show it, if not blocked */
    } else {
        magic_map_background(x,y,1); /* display it */
    }
    }
}
void sokoban_detect ()
Definition at line 1274 of file detect.c.
References COLNO, ftrap, level, levl, map_background(), map_object(), map_trap(), trap::ntrap, dlevel_t::objects, obj::otyp, ROWNO, SVALL, and TRUE.
Referenced by fixup_special().
{
    register int x, y;
    register struct trap *ttmp;
    register struct obj *obj;
    /* Map the background and boulders */
    for (x = 1; x < COLNO; x++)
        for (y = 0; y < ROWNO; y++) {
            levl[x][y].seenv = SVALL;
            levl[x][y].waslit = TRUE;
            map_background(x, y, 1);
            for (obj = level.objects[x][y]; obj; obj = obj->nexthere)
                if (obj->otyp == BOULDER)
                    map_object(obj, 1);
        }
    /* Map the traps */
    for (ttmp = ftrap; ttmp; ttmp = ttmp->ntrap) {
        ttmp->tseen = 1;
        map_trap(ttmp, 1);
    }
}
int trap_detect (struct obj * sobj)
Definition at line 680 of file detect.c.
References buf, cls(), D_TRAPPED, display_nhwindow, docrt(), doorindex, doors, FALSE, fobj, ftrap, levl, newsym(), obj::nobj, trap::ntrap, obj::otyp, obj::ox, obj::oy, sense_trap(), Sprintf, TOE, TRUE, trap::tx, trap::ty, u, under_ground(), under_water(), Underwater, you::ux, you::uy, WIN_MAP, coord::x, and coord::y.
Referenced by use_crystal_ball().
{
    register struct trap *ttmp;
    register struct obj *obj;
    register int door;
    int uw = u.uinwater;
    boolean found = FALSE;
    coord cc;
    for (ttmp = ftrap; ttmp; ttmp = ttmp->ntrap) {
    if (ttmp->tx != u.ux || ttmp->ty != u.uy)
        goto outtrapmap;
    else found = TRUE;
    }
    for (obj = fobj; obj; obj = obj->nobj) {
    if ((obj->otyp==LARGE_BOX || obj->otyp==CHEST) && obj->otrapped) {
        if (obj->ox != u.ux || obj->oy != u.uy)
        goto outtrapmap;
        else found = TRUE;
    }
    }
    for (door = 0; door < doorindex; door++) {
    cc = doors[door];
    if (levl[cc.x][cc.y].doormask & D_TRAPPED) {
        if (cc.x != u.ux || cc.y != u.uy)
        goto outtrapmap;
        else found = TRUE;
    }
    }
    if (!found) {
    char buf[42];
    Sprintf(buf, "Your %s stop itching.", makeplural(body_part(TOE)));
    strange_feeling(sobj,buf);
    return(1);
    }
    /* traps exist, but only under me - no separate display required */
    Your("%s itch.", makeplural(body_part(TOE)));
    return(0);
outtrapmap:
    cls();
    u.uinwater = 0;
    for (ttmp = ftrap; ttmp; ttmp = ttmp->ntrap)
    sense_trap(ttmp, 0, 0, sobj && sobj->cursed);
    for (obj = fobj; obj; obj = obj->nobj)
    if ((obj->otyp==LARGE_BOX || obj->otyp==CHEST) && obj->otrapped)
    sense_trap((struct trap *)0, obj->ox, obj->oy, sobj && sobj->cursed);
    for (door = 0; door < doorindex; door++) {
    cc = doors[door];
    if (levl[cc.x][cc.y].doormask & D_TRAPPED)
    sense_trap((struct trap *)0, cc.x, cc.y, sobj && sobj->cursed);
    }
    newsym(u.ux,u.uy);
    You_feel("%s.", sobj && sobj->cursed ? "very greedy" : "entrapped");
    display_nhwindow(WIN_MAP, TRUE);
    docrt();
    u.uinwater = uw;
    if (Underwater) under_water(2);
    if (u.uburied) under_ground(2);
    return(0);
}
void use_crystal_ball (struct obj * obj)
Definition at line 790 of file detect.c.
References A_INT, ACURR, Blind, Blinded, instance_flags::bouldersym, def_char_to_monclass(), def_char_to_objclass(), DEF_MIMIC, DEF_MIMIC_DEF, def_monsyms, FALSE, flags, Hallucination, HConfusion, HHallucination, iflags, index(), KILLED_BY_AN, level_detects, level_distance(), makeknown, MAXMCLASSES, MAXOCLASSES, monster_detect(), Never_mind, nomovemsg, object_detect(), quitchars, ROCK_CLASS, S_GHOST, SIZE, trap_detect(), TRUE, flag::verbose, vision_clears, what, where, and youmonst.
{
    char ch;
    int oops;
    if (Blind) {
    pline("Too bad you can't see %s.", the(xname(obj)));
    return;
    }
    oops = (rnd(20) > ACURR(A_INT) || obj->cursed);
    if (oops && (obj->spe > 0)) {
    switch (rnd(obj->oartifact ? 4 : 5)) {
    case 1 : pline("%s too much to comprehend!", Tobjnam(obj, "are"));
        break;
    case 2 : pline("%s you!", Tobjnam(obj, "confuse"));
        make_confused(HConfusion + rnd(100),FALSE);
        break;
    case 3 : if (!resists_blnd(&youmonst)) {
        pline("%s your vision!", Tobjnam(obj, "damage"));
        make_blinded(Blinded + rnd(100),FALSE);
        if (!Blind) Your(vision_clears);
        } else {
        pline("%s your vision.", Tobjnam(obj, "assault"));
        You("are unaffected!");
        }
        break;
    case 4 : pline("%s your mind!", Tobjnam(obj, "zap"));
        (void) make_hallucinated(HHallucination + rnd(100),FALSE,0L);
        break;
    case 5 : pline("%s!", Tobjnam(obj, "explode"));
        useup(obj);
        obj = 0; /* it's gone */
        losehp(rnd(30), "exploding crystal ball", KILLED_BY_AN);
        break;
    }
    if (obj) consume_obj_charge(obj, TRUE);
    return;
    }
    if (Hallucination) {
    if (!obj->spe) {
        pline("All you see is funky %s haze.", hcolor((char *)0));
    } else {
        switch(rnd(6)) {
        case 1 : You("grok some groovy globs of incandescent lava.");
        break;
        case 2 : pline("Whoa! Psychedelic colors, %s!",
               poly_gender() == 1 ? "babe" : "dude");
        break;
        case 3 : pline_The("crystal pulses with sinister %s light!",
                hcolor((char *)0));
        break;
        case 4 : You("see goldfish swimming above fluorescent rocks.");
        break;
        case 5 : You("see tiny snowflakes spinning around a miniature farmhouse.");
        break;
        default: pline("Oh wow... like a kaleidoscope!");
        break;
        }
        consume_obj_charge(obj, TRUE);
    }
    return;
    }
    /* read a single character */
    if (flags.verbose) You("may look for an object or monster symbol.");
    ch = yn_function("What do you look for?", (char *)0, '\0');
    /* Don't filter out ' ' here; it has a use */
    if ((ch != def_monsyms[S_GHOST]) && index(quitchars,ch)) {
    if (flags.verbose) pline(Never_mind);
    return;
    }
    You("peer into %s...", the(xname(obj)));
    nomul(-rnd(10));
    nomovemsg = "";
    if (obj->spe <= 0)
    pline_The("vision is unclear.");
    else {
    int class;
    int ret = 0;
    makeknown(CRYSTAL_BALL);
    consume_obj_charge(obj, TRUE);
    /* special case: accept ']' as synonym for mimic
     * we have to do this before the def_char_to_objclass check
     */
    if (ch == DEF_MIMIC_DEF) ch = DEF_MIMIC;
    if ((class = def_char_to_objclass(ch)) != MAXOCLASSES)
        ret = object_detect((struct obj *)0, class);
    else if ((class = def_char_to_monclass(ch)) !=
      MAXMCLASSES)
        ret = monster_detect((struct obj *)0, class);
    else if (iflags.bouldersym && (ch == iflags.bouldersym))
        ret = object_detect((struct obj *)0, ROCK_CLASS);
    else switch(ch) {
        case '^':
            ret = trap_detect((struct obj *)0);
            break;
        default:
            {
            int i = rn2(SIZE(level_detects));
            You("see %s, %s.",
            level_detects[i].what,
            level_distance(level_detects[i].where));
            }
            ret = 0;
            break;
    }
    if (ret) {
        if (!rn2(100)) /* make them nervous */
        You("see the Wizard of Yendor gazing out at you.");
        else pline_The("vision is unclear.");
    }
    }
    return;
}
Variable Documentation
boolean known
Referenced by food_detect(), gold_detect(), and use_defensive().
const { ... } level_detects[] [static]
Initial value:
= {
  { "Delphi", &oracle_level },
  { "Medusa's lair", &medusa_level },
  { "a castle", &stronghold_level },
  { "the Wizard of Yendor's tower", &wiz1_level },
}
Referenced by use_crystal_ball().
const char* what
Definition at line 780 of file detect.c.
Referenced by fix_worst_trouble(), food_detect(), hmon_hitmon(), impact_drop(), kickstr(), mar_set_rogue(), pickup(), stumble_onto_mimic(), use_crystal_ball(), and wield_tool().
d_level* where
Definition at line 781 of file detect.c.
Referenced by carry_count(), done(), eventLoop(), macClickTerm(), macCursorTerm(), obj_delivery(), open_levelfile(), query_classes(), and use_crystal_ball().