nethack/util/dgn_main.c File Reference
#include `config.h`
*
#include `dlb.h`
*
Macros
#define SpinCursor(x)
#define MAX_ERRORS 25
#define Fprintf (void)fprintf
Functions
int NDECL (yyparse)
int FDECL (main,(int, char **))
void FDECL (yyerror,(const char *))
void FDECL (yywarning,(const char *))
int NDECL (yywrap)
void FDECL (init_yyin,(FILE *))
void FDECL (init_yyout,(FILE *))
int main (int argc, char **argv)
void yyerror (char *s) const
void yywarning (char *s) const
int yywrap ()
Variables
int line_number
const char * fname = `(stdin)`
int fatal_error = 0
Macro Definition Documentation
#define Fprintf (void)fprintf
Definition at line 50 of file dgn_main.c.
Referenced by build_bmptile(), build_tibtile(), build_ximgtile(), copy_colormap(), DoExtension(), fopen_gif_file(), fopen_ppm_file(), fopen_text_file(), GetCode(), GetDataBlock(), LWZReadByte(), main(), merge_colormap(), merge_text_colormap(), pix_to_colormap(), process_file(), read_header(), read_txttile(), ReadInterleavedImage(), write_text_colormap(), write_thintile(), write_tibheader(), write_tibtile(), and write_txttile().
#define MAX_ERRORS 25
Definition at line 33 of file dgn_main.c.
Referenced by yyerror().
#define SpinCursor(x)
Definition at line 30 of file dgn_main.c.
Referenced by yywrap().
Function Documentation
int FDECL (main , (int, char **))
void FDECL (yyerror , (const char *))
void FDECL (yywarning , (const char *))
void FDECL (init_yyin , (FILE *))
void FDECL (init_yyout , (FILE *))
int main (int argc, char ** argv)
Definition at line 56 of file dgn_main.c.
References basename(), exit(), EXIT_FAILURE, EXIT_SUCCESS, FALSE, fatal_error, fname, Fprintf, freopen, infile, init_yyin(), init_yyout(), line_number, outfile, perror, PREFIX, SIZE, stdin, stdout, Strcpy, TRUE, WRBMODE, and yyparse().
{
    char infile[64], outfile[64], basename[64];
    FILE *fin, *fout;
    int i, len;
    boolean errors_encountered = FALSE;
#if defined(MAC) && (defined(THINK_C) || defined(__MWERKS__))
    char *mark;
    static char *mac_argv[] = { "dgn_comp", /* dummy argv[0] */
                ":dat:dungeon.pdf"
                };
    argc = SIZE(mac_argv);
    argv = mac_argv;
#endif
    Strcpy(infile, "(stdin)");
    fin = stdin;
    Strcpy(outfile, "(stdout)");
    fout = stdout;
    if (argc == 1) { /* Read standard input */
        init_yyin(fin);
        init_yyout(fout);
        (void) yyparse();
        if (fatal_error > 0)
        errors_encountered = TRUE;
    } else { /* Otherwise every argument is a filename */
        for(i=1; i<argc; i++) {
        fname = strcpy(infile, argv[i]);
        /* the input file had better be a .pdf file */
        len = strlen(fname) - 4; /* length excluding suffix */
        if (len < 0 || strncmp(".pdf", fname + len, 4)) {
            Fprintf(stderr,
                "Error - file name \"%s\" in wrong format.\n",
                fname);
            errors_encountered = TRUE;
            continue;
        }
        /* build output file name */
#if defined(MAC) && (defined(THINK_C) || defined(__MWERKS__))
        /* extract basename from path to infile */
        mark = strrchr(infile, ':');
        strcpy(basename, mark ? mark+1 : infile);
        mark = strchr(basename, '.');
        if (mark) *mark = '\0';
#else
        /* Use the whole name - strip off the last 3 or 4 chars. */
#ifdef VMS /* avoid possible interaction with logical name */
        len++; /* retain "." as trailing punctuation */
#endif
        (void) strncpy(basename, infile, len);
        basename[len] = '\0';
#endif
        outfile[0] = '\0';
#ifdef PREFIX
        (void) strcat(outfile, PREFIX);
#endif
        (void) strcat(outfile, basename);
        fin = freopen(infile, "r", stdin);
        if (!fin) {
            Fprintf(stderr, "Can't open %s for input.\n", infile);
            perror(infile);
            errors_encountered = TRUE;
            continue;
        }
        fout = freopen(outfile, WRBMODE, stdout);
        if (!fout) {
            Fprintf(stderr, "Can't open %s for output.\n", outfile);
            perror(outfile);
            errors_encountered = TRUE;
            continue;
        }
        init_yyin(fin);
        init_yyout(fout);
        (void) yyparse();
        line_number = 1;
        if (fatal_error > 0) {
            errors_encountered = TRUE;
            fatal_error = 0;
        }
        }
    }
    if (fout && fclose(fout) < 0) {
        Fprintf(stderr, "Can't finish output file.");
        perror(outfile);
        errors_encountered = TRUE;
    }
    exit(errors_encountered ? EXIT_FAILURE : EXIT_SUCCESS);
    /*NOTREACHED*/
    return 0;
}
int NDECL (yyparse)
int NDECL (yywrap)
void yyerror (char * s) const
Definition at line 161 of file dgn_main.c.
References exit(), EXIT_FAILURE, fatal_error, fname, line_number, and MAX_ERRORS.
Referenced by check_branch(), check_dungeon(), check_level(), getchain(), init_branch(), init_level(), output_dgn(), and yyparse().
{
    (void) fprintf(stderr,"%s : line %d : %s\n",fname,line_number, s);
    if (++fatal_error > MAX_ERRORS) {
        (void) fprintf(stderr,"Too many errors, good bye!\n");
        exit(EXIT_FAILURE);
    }
}
void yywarning (char * s) const
Definition at line 175 of file dgn_main.c.
References fname, and line_number.
Referenced by yyparse().
{
    (void) fprintf(stderr,"%s : line %d : WARNING : %s\n",fname,line_number,s);
}
int yywrap ()
Definition at line 181 of file dgn_main.c.
References SpinCursor.
Referenced by input(), and yylex().
{
    SpinCursor(3); /* Don't know if this is a good place to put it ?
                        Is it called for our grammar ? Often enough ?
                        Too often ? -- h+ */
       return 1;
}
Variable Documentation
int fatal_error = 0
Definition at line 38 of file dgn_main.c.
Referenced by main(), and yyerror().
const char* fname = `(stdin)`
Definition at line 37 of file dgn_main.c.
Referenced by main(), yyerror(), and yywarning().
int line_number
Definition at line 483 of file dgn_lex.c.
Referenced by main(), yyerror(), and yywarning().