nethack/sys/share/dgn_yacc.c File Reference
#include `config.h`
*
#include `date.h`
*
#include `dgn_file.h`
*
Data Structures
union YYSTYPE
Macros
#define YYBYACC 1
#define YYMAJOR 1
#define YYMINOR 9
#define yyclearin (yychar=(-1))
#define yyerrok (yyerrflag=0)
#define YYRECOVERING (yyerrflag!=0)
#define YYPREFIX `yy`
#define Free(ptr) free((genericptr_t)ptr)
#define ERR (-1)
#define INTEGER 257
#define A_DUNGEON 258
#define BRANCH 259
#define CHBRANCH 260
#define LEVEL 261
#define RNDLEVEL 262
#define CHLEVEL 263
#define RNDCHLEVEL 264
#define UP_OR_DOWN 265
#define PROTOFILE 266
#define DESCRIPTION 267
#define DESCRIPTOR 268
#define LEVELDESC 269
#define ALIGNMENT 270
#define LEVALIGN 271
#define ENTRY 272
#define STAIR 273
#define NO_UP 274
#define NO_DOWN 275
#define PORTAL 276
#define STRING 277
#define YYERRCODE 256
#define YYTABLESIZE 363
#define YYFINAL 14
#define YYDEBUG 0
#define YYMAXTOKEN 277
#define YYSTACKSIZE 500
#define YYMAXDEPTH 500
#define yystacksize YYSTACKSIZE
#define YYABORT goto yyabort
#define YYREJECT goto yyabort
#define YYACCEPT goto yyaccept
#define YYERROR goto yyerrlab
Functions
void FDECL (yyerror,(const char *))
void FDECL (yywarning,(const char *))
int NDECL (yylex)
int NDECL (yyparse)
int FDECL (getchain,(char *))
int NDECL (check_dungeon)
int NDECL (check_branch)
int NDECL (check_level)
void NDECL (init_dungeon)
void NDECL (init_branch)
void NDECL (init_level)
void NDECL (output_dgn)
void init_dungeon ()
void init_level ()
void init_branch ()
int getchain (char *s)
int check_dungeon ()
int check_level ()
int check_branch ()
void output_dgn ()
int yyparse ()
Variables
static char yysccsid [] = `@(#)yaccpar 1.9 (Berkeley) 02/21/93`
static struct couple couple
static struct tmpdungeon tmpdungeon [MAXDUNGEON]
static struct tmplevel tmplevel [LEV_LIMIT]
static struct tmpbranch tmpbranch [BRANCH_LIMIT]
static int in_dungeon = 0
static int n_dgns = -1
static int n_levs = -1
static int n_brs = -1
int fatal_error
const char * fname
FILE * yyin
FILE * yyout
short yylhs []
short yylen []
short yydefred []
short yydgoto []
short yysindex []
short yyrindex []
short yygindex []
short yytable []
short yycheck []
int yydebug
int yynerrs
int yyerrflag
int yychar
short * yyssp
YYSTYPE * yyvsp
YYSTYPE yyval
YYSTYPE yylval
short yyss [YYSTACKSIZE]
YYSTYPE yyvs [YYSTACKSIZE]
Macro Definition Documentation
#define A_DUNGEON 258
Definition at line 79 of file dgn_yacc.c.
#define ALIGNMENT 270
Definition at line 91 of file dgn_yacc.c.
#define BRANCH 259
Definition at line 80 of file dgn_yacc.c.
#define CHBRANCH 260
Definition at line 81 of file dgn_yacc.c.
#define CHLEVEL 263
Definition at line 84 of file dgn_yacc.c.
#define DESCRIPTION 267
Definition at line 88 of file dgn_yacc.c.
#define DESCRIPTOR 268
Definition at line 89 of file dgn_yacc.c.
#define ENTRY 272
Definition at line 93 of file dgn_yacc.c.
#define ERR (-1)
Definition at line 60 of file dgn_yacc.c.
#define Free(ptr) free((genericptr_t)ptr)
Definition at line 51 of file dgn_yacc.c.
Referenced by yyparse().
#define INTEGER 257
Definition at line 78 of file dgn_yacc.c.
#define LEVALIGN 271
Definition at line 92 of file dgn_yacc.c.
#define LEVEL 261
Definition at line 82 of file dgn_yacc.c.
#define LEVELDESC 269
Definition at line 90 of file dgn_yacc.c.
#define NO_DOWN 275
Definition at line 96 of file dgn_yacc.c.
#define NO_UP 274
Definition at line 95 of file dgn_yacc.c.
#define PORTAL 276
Definition at line 97 of file dgn_yacc.c.
#define PROTOFILE 266
Definition at line 87 of file dgn_yacc.c.
#define RNDCHLEVEL 264
Definition at line 85 of file dgn_yacc.c.
#define RNDLEVEL 262
Definition at line 83 of file dgn_yacc.c.
#define STAIR 273
Definition at line 94 of file dgn_yacc.c.
#define STRING 277
Definition at line 98 of file dgn_yacc.c.
#define UP_OR_DOWN 265
Definition at line 86 of file dgn_yacc.c.
#define YYABORT goto yyabort
Definition at line 580 of file dgn_yacc.c.
#define YYACCEPT goto yyaccept
Definition at line 582 of file dgn_yacc.c.
#define YYBYACC 1
Definition at line 4 of file dgn_yacc.c.
#define yyclearin (yychar=(-1))
Definition at line 7 of file dgn_yacc.c.
#define YYDEBUG 0
Definition at line 244 of file dgn_yacc.c.
#define YYERRCODE 256
Definition at line 99 of file dgn_yacc.c.
Referenced by yyparse().
#define yyerrok (yyerrflag=0)
Definition at line 8 of file dgn_yacc.c.
#define YYERROR goto yyerrlab
Definition at line 583 of file dgn_yacc.c.
#define YYFINAL 14
Definition at line 242 of file dgn_yacc.c.
Referenced by yyparse().
#define YYMAJOR 1
Definition at line 5 of file dgn_yacc.c.
#define YYMAXDEPTH 500
Definition at line 320 of file dgn_yacc.c.
#define YYMAXTOKEN 277
Definition at line 246 of file dgn_yacc.c.
Referenced by yyparse().
#define YYMINOR 9
Definition at line 6 of file dgn_yacc.c.
#define YYPREFIX `yy`
Definition at line 10 of file dgn_yacc.c.
Referenced by yyparse().
#define YYRECOVERING (yyerrflag!=0)
Definition at line 9 of file dgn_yacc.c.
#define YYREJECT goto yyabort
Definition at line 581 of file dgn_yacc.c.
#define YYSTACKSIZE 500
Definition at line 319 of file dgn_yacc.c.
#define yystacksize YYSTACKSIZE
Definition at line 333 of file dgn_yacc.c.
Referenced by yyparse().
#define YYTABLESIZE 363
Definition at line 163 of file dgn_yacc.c.
Referenced by yyparse().
Function Documentation
int check_branch ()
Definition at line 494 of file dgn_yacc.c.
References tmpbranch::chain, n_brs, n_dgns, name, and yyerror().
Referenced by yyparse().
{
    int i;
    if(!in_dungeon) {
        yyerror("Branch defined outside of dungeon.");
        return(0);
    }
    for(i = 0; i < n_dgns; i++)
        if(!strcmp(tmpdungeon[i].name, tmpbranch[n_brs].name)) {
        yyerror("Reverse branching not allowed.");
        return(0);
        }
    if(tmpbranch[i].chain == -2) {
        yyerror("Invaild branch chain reference.");
        return(0);
    } else if(tmpbranch[i].chain != -1) { /* it is chained */
        if(tmplevel[tmpbranch[i].chain].chance != 100) {
        yyerror("Branch cannot chain from a probabilistic level.");
        return(0);
        }
    }
    return(1); /* OK */
}
int check_dungeon ()
Definition at line 415 of file dgn_yacc.c.
References couple::base, tmpdungeon::branches, tmpdungeon::lev, tmpbranch::lev, n_brs, n_dgns, name, couple::rand, and yyerror().
{
    int i;
    for(i = 0; i < n_dgns; i++)
        if(!strcmp(tmpdungeon[i].name, tmpdungeon[n_dgns].name)) {
        yyerror("Duplicate dungeon name.");
        return(0);
        }
    if(n_dgns)
      for(i = 0; i < n_brs - tmpdungeon[n_dgns].branches; i++) {
        if(!strcmp(tmpbranch[i].name, tmpdungeon[n_dgns].name)) break;
        if(i >= n_brs - tmpdungeon[n_dgns].branches) {
        yyerror("Dungeon cannot be reached.");
        return(0);
        }
      }
    if(tmpdungeon[n_dgns].lev.base <= 0 ||
       tmpdungeon[n_dgns].lev.rand < 0) {
        yyerror("Invalid dungeon depth specified.");
        return(0);
    }
    return(1); /* OK */
}
int check_level ()
Definition at line 452 of file dgn_yacc.c.
References tmpbranch::chain, n_levs, name, and yyerror().
Referenced by yyparse().
{
    int i;
    if(!in_dungeon) {
        yyerror("Level defined outside of dungeon.");
        return(0);
    }
    for(i = 0; i < n_levs; i++)
        if(!strcmp(tmplevel[i].name, tmplevel[n_levs].name)) {
        yyerror("Duplicate level name.");
        return(0);
        }
    if(tmplevel[i].chain == -2) {
        yyerror("Invaild level chain reference.");
        return(0);
    } else if(tmplevel[i].chain != -1) { /* there is a chain */
        /* KMH -- tmplevel[tmpbranch[i].chain].chance was in error */
        if(tmplevel[tmplevel[i].chain].chance != 100) {
        yyerror("Level cannot chain from a probabilistic level.");
        return(0);
        } else if(tmplevel[i].chain == n_levs) {
        yyerror("A level cannot chain to itself!");
        return(0);
        }
    }
    return(1); /* OK */
}
void FDECL (yyerror , (const char *))
void FDECL (yywarning , (const char *))
int FDECL (getchain , (char *))
int getchain (char	* s)
Definition at line 389 of file dgn_yacc.c.
References levels, n_dgns, n_levs, name, and yyerror().
Referenced by yyparse().
{
    int i;
    if(strlen(s)) {
        for(i = n_levs - tmpdungeon[n_dgns].levels + 1; i <=
      n_levs; i++)
        if(!strcmp(tmplevel[i].name, s)) return i;
        yyerror("Can't locate the specified chain level.");
        return(-2);
    }
    return(-1);
}
void init_branch ()
Definition at line 375 of file dgn_yacc.c.
References couple::base, BRANCH_LIMIT, tmpbranch::chain, exit(), EXIT_FAILURE, tmpbranch::lev, n_brs, name, couple::rand, Strcpy, and yyerror().
Referenced by yyparse().
{
    if(++n_brs > BRANCH_LIMIT) {
        yyerror("FATAL - Too many special levels defined.");
        exit(EXIT_FAILURE);
    }
    tmpbranch[n_brs].lev.base = 0;
    tmpbranch[n_brs].lev.rand = 0;
    Strcpy(tmpbranch[n_brs].name, "");
    tmpbranch[n_brs].chain = -1;
}
void init_dungeon ()
Definition at line 336 of file dgn_yacc.c.
References couple::base, tmpdungeon::branches, tmpdungeon::chance, tmpdungeon::entry_lev, exit(), EXIT_FAILURE, tmpdungeon::flags, tmpdungeon::lev, tmpdungeon::levels, MAXDUNGEON, n_dgns, name, couple::rand, and Strcpy.
Referenced by yyparse().
{
    if(++n_dgns > MAXDUNGEON) {
        (void) fprintf(stderr, "FATAL - Too many dungeons (limit: %d).\n",
            MAXDUNGEON);
        (void) fprintf(stderr, "To increase the limit edit MAXDUNGEON in global.h\n");
        exit(EXIT_FAILURE);
    }
    in_dungeon = 1;
    tmpdungeon[n_dgns].lev.base = 0;
    tmpdungeon[n_dgns].lev.rand = 0;
    tmpdungeon[n_dgns].chance = 100;
    Strcpy(tmpdungeon[n_dgns].name, "");
    Strcpy(tmpdungeon[n_dgns].protoname, "");
    tmpdungeon[n_dgns].flags = 0;
    tmpdungeon[n_dgns].levels = 0;
    tmpdungeon[n_dgns].branches = 0;
    tmpdungeon[n_dgns].entry_lev = 0;
}
void init_level ()
Definition at line 358 of file dgn_yacc.c.
References couple::base, tmplevel::chain, tmplevel::chance, exit(), EXIT_FAILURE, tmplevel::flags, tmplevel::lev, LEV_LIMIT, n_levs, name, couple::rand, tmplevel::rndlevs, Strcpy, and yyerror().
Referenced by yyparse().
{
    if(++n_levs > LEV_LIMIT) {
        yyerror("FATAL - Too many special levels defined.");
        exit(EXIT_FAILURE);
    }
    tmplevel[n_levs].lev.base = 0;
    tmplevel[n_levs].lev.rand = 0;
    tmplevel[n_levs].chance = 100;
    tmplevel[n_levs].rndlevs = 0;
    tmplevel[n_levs].flags = 0;
    Strcpy(tmplevel[n_levs].name, "");
    tmplevel[n_levs].chain = -1;
}
int NDECL (yylex)
int NDECL (yyparse)
int NDECL (check_dungeon)
int NDECL (check_branch)
int NDECL (check_level)
void NDECL (init_dungeon)
void NDECL (init_branch)
void NDECL (init_level)
void NDECL (output_dgn)
void output_dgn ()
Definition at line 541 of file dgn_yacc.c.
References tmpdungeon::branches, exit(), EXIT_FAILURE, tmpdungeon::levels, n_dgns, and yyerror().
Referenced by yyparse().
{
    int nd, cl = 0, nl = 0,
            cb = 0, nb = 0;
    static struct version_info version_data = {
            VERSION_NUMBER, VERSION_FEATURES,
            VERSION_SANITY1, VERSION_SANITY2
    };
    if(++n_dgns <= 0) {
        yyerror("FATAL - no dungeons were defined.");
        exit(EXIT_FAILURE);
    }
    if (fwrite((char *)&version_data, sizeof version_data, 1, yyout) != 1) {
        yyerror("FATAL - output failure.");
        exit(EXIT_FAILURE);
    }
    (void) fwrite((char *)&n_dgns, sizeof(int), 1, yyout);
    for (nd = 0; nd < n_dgns; nd++) {
        (void) fwrite((char *)&tmpdungeon[nd], sizeof(struct
      tmpdungeon),
                            1, yyout);
        nl += tmpdungeon[nd].levels;
        for(; cl < nl; cl++)
        (void) fwrite((char *)&tmplevel[cl], sizeof(struct tmplevel),
                            1, yyout);
        nb += tmpdungeon[nd].branches;
        for(; cb < nb; cb++)
        (void) fwrite((char *)&tmpbranch[cb], sizeof(struct tmpbranch),
                            1, yyout);
    }
    /* apparently necessary for Think C 5.x, otherwise harmless */
    (void) fflush(yyout);
}
int yyparse ()
Definition at line 585 of file dgn_yacc.c.
References couple::base, tmpdungeon::boneschar, tmplevel::boneschar, tmpdungeon::branches, tmplevel::chain, tmpbranch::chain, tmpdungeon::chance, tmplevel::chance, check_branch(), check_level(), D_ALIGN_CHAOTIC, tmpdungeon::entry_lev, tmpdungeon::flags, tmplevel::flags, Free, getchain(), getenv, YYSTYPE::i, init_branch(), init_dungeon(), init_level(), tmpdungeon::lev, tmplevel::lev, tmpbranch::lev, tmpdungeon::levels, MAXLEVEL, n_brs, n_dgns, n_levs, name, output_dgn(), printf, tmpdungeon::protoname, couple::rand, tmplevel::rndlevs, YYSTYPE::str, Strcpy, TBR_NO_DOWN, TBR_NO_UP, TBR_PORTAL, TBR_STAIR, TOWN, tmpbranch::type, tmpbranch::up, yychar, YYERRCODE, yyerrflag, yyerror(), YYFINAL, yylex(), yylval, YYMAXTOKEN, yynerrs, YYPREFIX, yyss, yyssp, yystacksize, YYTABLESIZE, yyval, yyvs, and yyvsp.
Referenced by main().
{
    register int yym, yyn, yystate;
#if YYDEBUG
    register char *yys;
    extern char *getenv();
    if ((yys = getenv("YYDEBUG")) != 0)
    {
        yyn = *yys;
        if (yyn >= '0' && yyn <= '9')
            yydebug = yyn - '0';
    }
#endif
    yynerrs = 0;
    yyerrflag = 0;
    yychar = (-1);
    yyssp = yyss;
    yyvsp = yyvs;
    *yyssp = yystate = 0;
yyloop:
    if ((yyn = yydefred[yystate]) != 0) goto yyreduce;
    if (yychar < 0)
    {
        if ((yychar = yylex()) < 0) yychar = 0;
#if YYDEBUG
        if (yydebug)
        {
            yys = 0;
            if (yychar <= YYMAXTOKEN) yys = yyname[yychar];
            if (!yys) yys = "illegal-symbol";
            printf("%sdebug: state %d, reading %d (%s)\n",
                    YYPREFIX, yystate, yychar, yys);
        }
#endif
    }
    if ((yyn = yysindex[yystate]) != 0 && (yyn += yychar) >= 0 &&
            yyn <= YYTABLESIZE && yycheck[yyn] == yychar)
    {
#if YYDEBUG
        if (yydebug)
            printf("%sdebug: state %d, shifting to state %d\n",
                    YYPREFIX, yystate, yytable[yyn]);
#endif
        if (yyssp >= yyss + yystacksize - 1)
        {
            goto yyoverflow;
        }
        *++yyssp = yystate = yytable[yyn];
        *++yyvsp = yylval;
        yychar = (-1);
        if (yyerrflag > 0) --yyerrflag;
        goto yyloop;
    }
    if ((yyn = yyrindex[yystate]) != 0 && (yyn += yychar) >= 0 &&
            yyn <= YYTABLESIZE && yycheck[yyn] == yychar)
    {
        yyn = yytable[yyn];
        goto yyreduce;
    }
    if (yyerrflag) goto yyinrecovery;
#ifdef lint
    goto yynewerror;
#endif
yynewerror:
    yyerror("syntax error");
#ifdef lint
    goto yyerrlab;
#endif
yyerrlab:
    ++yynerrs;
yyinrecovery:
    if (yyerrflag < 3)
    {
        yyerrflag = 3;
        for (;;)
        {
            if ((yyn = yysindex[*yyssp]) != 0 && (yyn += YYERRCODE) >= 0 &&
                    yyn <= YYTABLESIZE && yycheck[yyn] ==
      YYERRCODE)
            {
#if YYDEBUG
                if (yydebug)
                    printf("%sdebug: state %d, error recovery shifting\
 to state %d\n", YYPREFIX, *yyssp, yytable[yyn]);
#endif
                if (yyssp >= yyss + yystacksize - 1)
                {
                    goto yyoverflow;
                }
                *++yyssp = yystate = yytable[yyn];
                *++yyvsp = yylval;
                goto yyloop;
            }
            else
            {
#if YYDEBUG
                if (yydebug)
                    printf("%sdebug: error recovery discarding state %d\n",
                            YYPREFIX, *yyssp);
#endif
                if (yyssp <= yyss) goto yyabort;
                --yyssp;
                --yyvsp;
            }
        }
    }
    else
    {
        if (yychar == 0) goto yyabort;
#if YYDEBUG
        if (yydebug)
        {
            yys = 0;
            if (yychar <= YYMAXTOKEN) yys = yyname[yychar];
            if (!yys) yys = "illegal-symbol";
            printf("%sdebug: state %d, error recovery discards token %d (%s)\n",
                    YYPREFIX, yystate, yychar, yys);
        }
#endif
        yychar = (-1);
        goto yyloop;
    }
yyreduce:
#if YYDEBUG
    if (yydebug)
        printf("%sdebug: state %d, reducing by rule %d (%s)\n",
                YYPREFIX, yystate, yyn, yyrule[yyn]);
#endif
    yym = yylen[yyn];
    yyval = yyvsp[1-yym];
    switch (yyn)
    {
case 2:
{
            output_dgn();
          }
break;
case 9:
{
            init_dungeon();
            Strcpy(tmpdungeon[n_dgns].name, yyvsp[-3].str);
            tmpdungeon[n_dgns].boneschar = (char)yyvsp[-2].i;
            tmpdungeon[n_dgns].lev.base = couple.
      base;
            tmpdungeon[n_dgns].lev.rand = couple.
      rand;
            tmpdungeon[n_dgns].chance = yyvsp[0].i;
            Free(yyvsp[-3].str);
          }
break;
case 10:
{
            yyval.i = 0;
          }
break;
case 11:
{
            yyval.i = yyvsp[0].i;
          }
break;
case 15:
{
            tmpdungeon[n_dgns].entry_lev = yyvsp[0].
      i;
          }
break;
case 17:
{
            if(yyvsp[0].i <= TOWN || yyvsp[0].i >= D_ALIGN_CHAOTIC)
                yyerror("Illegal description - ignoring!");
            else
                tmpdungeon[n_dgns].flags |= yyvsp[0].i ;
          }
break;
case 18:
{
            if(yyvsp[0].i && yyvsp[0].i < D_ALIGN_CHAOTIC)
                yyerror("Illegal alignment - ignoring!");
            else
                tmpdungeon[n_dgns].flags |= yyvsp[0].i ;
          }
break;
case 19:
{
            Strcpy(tmpdungeon[n_dgns].protoname,
      yyvsp[0].str);
            Free(yyvsp[0].str);
          }
break;
case 25:
{
            init_level();
            Strcpy(tmplevel[n_levs].name, yyvsp[-3].str);
            tmplevel[n_levs].boneschar = (char)yyvsp[-2].i;
            tmplevel[n_levs].lev.base = couple.base;
            tmplevel[n_levs].lev.rand = couple.rand;
            tmpdungeon[n_dgns].levels++;
            Free(yyvsp[-3].str);
          }
break;
case 26:
{
            init_level();
            Strcpy(tmplevel[n_levs].name, yyvsp[-4].str);
            tmplevel[n_levs].boneschar = (char)yyvsp[-3].i;
            tmplevel[n_levs].lev.base = couple.base;
            tmplevel[n_levs].lev.rand = couple.rand;
            tmplevel[n_levs].rndlevs = yyvsp[0].i;
            tmpdungeon[n_dgns].levels++;
            Free(yyvsp[-4].str);
          }
break;
case 27:
{
            init_level();
            Strcpy(tmplevel[n_levs].name, yyvsp[-4].str);
            tmplevel[n_levs].boneschar = (char)yyvsp[-3].i;
            tmplevel[n_levs].lev.base = couple.base;
            tmplevel[n_levs].lev.rand = couple.rand;
            tmplevel[n_levs].chance = yyvsp[0].i;
            tmpdungeon[n_dgns].levels++;
            Free(yyvsp[-4].str);
          }
break;
case 28:
{
            init_level();
            Strcpy(tmplevel[n_levs].name, yyvsp[-5].str);
            tmplevel[n_levs].boneschar = (char)yyvsp[-4].i;
            tmplevel[n_levs].lev.base = couple.base;
            tmplevel[n_levs].lev.rand = couple.rand;
            tmplevel[n_levs].chance = yyvsp[-1].i;
            tmplevel[n_levs].rndlevs = yyvsp[0].i;
            tmpdungeon[n_dgns].levels++;
            Free(yyvsp[-5].str);
          }
break;
case 29:
{
            if(yyvsp[0].i >= D_ALIGN_CHAOTIC)
                yyerror("Illegal description - ignoring!");
            else
                tmplevel[n_levs].flags |= yyvsp[0].i ;
          }
break;
case 30:
{
            if(yyvsp[0].i && yyvsp[0].i < D_ALIGN_CHAOTIC)
                yyerror("Illegal alignment - ignoring!");
            else
                tmplevel[n_levs].flags |= yyvsp[0].i ;
          }
break;
case 31:
{
            init_level();
            Strcpy(tmplevel[n_levs].name, yyvsp[-4].str);
            tmplevel[n_levs].boneschar = (char)yyvsp[-3].i;
            tmplevel[n_levs].chain = getchain(yyvsp[-2].str);
            tmplevel[n_levs].lev.base = couple.base;
            tmplevel[n_levs].lev.rand = couple.rand;
            if(!check_level()) n_levs--;
            else tmpdungeon[n_dgns].levels++;
            Free(yyvsp[-4].str);
            Free(yyvsp[-2].str);
          }
break;
case 32:
{
            init_level();
            Strcpy(tmplevel[n_levs].name, yyvsp[-5].str);
            tmplevel[n_levs].boneschar = (char)yyvsp[-4].i;
            tmplevel[n_levs].chain = getchain(yyvsp[-3].str);
            tmplevel[n_levs].lev.base = couple.base;
            tmplevel[n_levs].lev.rand = couple.rand;
            tmplevel[n_levs].rndlevs = yyvsp[0].i;
            if(!check_level()) n_levs--;
            else tmpdungeon[n_dgns].levels++;
            Free(yyvsp[-5].str);
            Free(yyvsp[-3].str);
          }
break;
case 33:
{
            init_level();
            Strcpy(tmplevel[n_levs].name, yyvsp[-5].str);
            tmplevel[n_levs].boneschar = (char)yyvsp[-4].i;
            tmplevel[n_levs].chain = getchain(yyvsp[-3].str);
            tmplevel[n_levs].lev.base = couple.base;
            tmplevel[n_levs].lev.rand = couple.rand;
            tmplevel[n_levs].chance = yyvsp[0].i;
            if(!check_level()) n_levs--;
            else tmpdungeon[n_dgns].levels++;
            Free(yyvsp[-5].str);
            Free(yyvsp[-3].str);
          }
break;
case 34:
{
            init_level();
            Strcpy(tmplevel[n_levs].name, yyvsp[-6].str);
            tmplevel[n_levs].boneschar = (char)yyvsp[-5].i;
            tmplevel[n_levs].chain = getchain(yyvsp[-4].str);
            tmplevel[n_levs].lev.base = couple.base;
            tmplevel[n_levs].lev.rand = couple.rand;
            tmplevel[n_levs].chance = yyvsp[-1].i;
            tmplevel[n_levs].rndlevs = yyvsp[0].i;
            if(!check_level()) n_levs--;
            else tmpdungeon[n_dgns].levels++;
            Free(yyvsp[-6].str);
            Free(yyvsp[-4].str);
          }
break;
case 37:
{
            init_branch();
            Strcpy(tmpbranch[n_brs].name, yyvsp[-4].str);
            tmpbranch[n_brs].lev.base = couple.base;
            tmpbranch[n_brs].lev.rand = couple.rand;
            tmpbranch[n_brs].type = yyvsp[-1].i;
            tmpbranch[n_brs].up = yyvsp[0].i;
            if(!check_branch()) n_brs--;
            else tmpdungeon[n_dgns].branches++;
            Free(yyvsp[-4].str);
          }
break;
case 38:
{
            init_branch();
            Strcpy(tmpbranch[n_brs].name, yyvsp[-5].str);
            tmpbranch[n_brs].chain = getchain(yyvsp[-4].str);
            tmpbranch[n_brs].lev.base = couple.base;
            tmpbranch[n_brs].lev.rand = couple.rand;
            tmpbranch[n_brs].type = yyvsp[-1].i;
            tmpbranch[n_brs].up = yyvsp[0].i;
            if(!check_branch()) n_brs--;
            else tmpdungeon[n_dgns].branches++;
            Free(yyvsp[-5].str);
            Free(yyvsp[-4].str);
          }
break;
case 39:
{
            yyval.i = TBR_STAIR; /* two way stair */
          }
break;
case 40:
{
            yyval.i = TBR_STAIR; /* two way stair */
          }
break;
case 41:
{
            yyval.i = TBR_NO_UP; /* no up staircase */
          }
break;
case 42:
{
            yyval.i = TBR_NO_DOWN; /* no down staircase */
          }
break;
case 43:
{
            yyval.i = TBR_PORTAL; /* portal connection */
          }
break;
case 44:
{
            yyval.i = 0; /* defaults to down */
          }
break;
case 45:
{
            yyval.i = yyvsp[0].i;
          }
break;
case 46:
{
            char *p = yyvsp[0].str;
            if (strlen(p) != 1) {
                if (strcmp(p, "none") != 0)
           yyerror("Bones marker must be a single char, or \"none\"!");
                *p = '\0';
            }
            yyval.i = *p;
            Free(p);
          }
break;
case 47:
{
            if (yyvsp[-3].i < -MAXLEVEL || yyvsp[-3].i >
      MAXLEVEL) {
                yyerror("Abs base out of dlevel range - zeroing!");
                couple.base = couple.rand = 0;
            } else if (yyvsp[-1].i < -1 ||
                ((yyvsp[-3].i < 0) ? (MAXLEVEL + yyvsp[-3].i +
      yyvsp[-1].i + 1) > MAXLEVEL :
                    (yyvsp[-3].i + yyvsp[-1].i) > MAXLEVEL)) {
                yyerror("Abs range out of dlevel range - zeroing!");
                couple.base = couple.rand = 0;
            } else {
                couple.base = yyvsp[-3].i;
                couple.rand = yyvsp[-1].i;
            }
          }
break;
case 48:
{
            if (yyvsp[-3].i < -MAXLEVEL || yyvsp[-3].i >
      MAXLEVEL) {
                yyerror("Rel base out of dlevel range - zeroing!");
                couple.base = couple.rand = 0;
            } else {
                couple.base = yyvsp[-3].i;
                couple.rand = yyvsp[-1].i;
            }
          }
break;
    }
    yyssp -= yym;
    yystate = *yyssp;
    yyvsp -= yym;
    yym = yylhs[yyn];
    if (yystate == 0 && yym == 0)
    {
#if YYDEBUG
        if (yydebug)
            printf("%sdebug: after reduction, shifting from state 0 to\
 state %d\n", YYPREFIX, YYFINAL);
#endif
        yystate = YYFINAL;
        *++yyssp = YYFINAL;
        *++yyvsp = yyval;
        if (yychar < 0)
        {
            if ((yychar = yylex()) < 0) yychar = 0;
#if YYDEBUG
            if (yydebug)
            {
                yys = 0;
                if (yychar <= YYMAXTOKEN) yys = yyname[yychar];
                if (!yys) yys = "illegal-symbol";
                printf("%sdebug: state %d, reading %d (%s)\n",
                        YYPREFIX, YYFINAL, yychar, yys);
            }
#endif
        }
        if (yychar == 0) goto yyaccept;
        goto yyloop;
    }
    if ((yyn = yygindex[yym]) != 0 && (yyn += yystate) >= 0 &&
            yyn <= YYTABLESIZE && yycheck[yyn] == yystate)
        yystate = yytable[yyn];
    else
        yystate = yydgoto[yym];
#if YYDEBUG
    if (yydebug)
        printf("%sdebug: after reduction, shifting from state %d \
to state %d\n", YYPREFIX, *yyssp, yystate);
#endif
    if (yyssp >= yyss + yystacksize - 1)
    {
        goto yyoverflow;
    }
    *++yyssp = yystate;
    *++yyvsp = yyval;
    goto yyloop;
yyoverflow:
    yyerror("yacc stack overflow");
yyabort:
    return (1);
yyaccept:
    return (0);
}
Variable Documentation
struct couple couple [static]
Definition at line 62 of file dgn_yacc.c.
int fatal_error
Definition at line 38 of file dgn_main.c.
const char* fname
Definition at line 37 of file dgn_main.c.
Referenced by amii_init_nhwindows(), main(), mar_gem_init(), open(), and unlink().
int in_dungeon = 0 [static]
Definition at line 67 of file dgn_yacc.c.
int n_brs = -1 [static]
Definition at line 67 of file dgn_yacc.c.
Referenced by check_branch(), check_dungeon(), init_branch(), and yyparse().
int n_dgns = -1 [static]
Definition at line 67 of file dgn_yacc.c.
Referenced by check_branch(), check_dungeon(), getchain(), init_dungeon(), output_dgn(), and yyparse().
int n_levs = -1 [static]
Definition at line 67 of file dgn_yacc.c.
Referenced by check_level(), getchain(), init_level(), and yyparse().
struct tmpbranch tmpbranch[BRANCH_LIMIT] [static]
Definition at line 65 of file dgn_yacc.c.
struct tmpdungeon tmpdungeon[MAXDUNGEON] [static]
Definition at line 63 of file dgn_yacc.c.
struct tmplevel tmplevel[LEV_LIMIT] [static]
Definition at line 64 of file dgn_yacc.c.
int yychar
Definition at line 326 of file dgn_yacc.c.
Referenced by yyparse().
short yycheck[]
Definition at line 203 of file dgn_yacc.c.
int yydebug
Definition at line 323 of file dgn_yacc.c.
short yydefred[]
Initial value:
= { 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 3, 5, 6, 7, 8,
   12, 13, 14, 16, 20, 21, 22, 23, 24, 35,
   36, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 4, 0, 0, 0, 0, 0,
    0, 0, 19, 17, 29, 18, 30, 15, 46, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 11, 9, 0, 40,
   41, 42, 43, 0, 0, 0, 0, 0, 0, 0,
    0, 45, 37, 0, 27, 0, 0, 0, 0, 0,
   38, 28, 33, 0, 48, 47, 34,
}
Definition at line 114 of file dgn_yacc.c.
short yydgoto[]
Initial value:
= { 14,
   78, 93, 84, 60, 15, 16, 17, 18, 19, 20,
   68, 21, 22, 23, 24, 25, 26, 27, 28, 29,
   70, 30, 31,
}
Definition at line 127 of file dgn_yacc.c.
int yyerrflag
Definition at line 325 of file dgn_yacc.c.
Referenced by yyparse().
short yygindex[]
Initial value:
= { 0,
    0, -6, 4, -43, 0, 75, 0, 0, 0, 0,
  -71, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  -62, 0, 0,
}
Definition at line 158 of file dgn_yacc.c.
FILE* yyin
short yylen[]
Initial value:
= { 2,
    0, 1, 1, 2, 1, 1, 1, 1, 6, 0,
    1, 1, 1, 1, 3, 1, 3, 3, 3, 1,
    1, 1, 1, 1, 6, 7, 7, 8, 3, 3,
    7, 8, 8, 9, 1, 1, 7, 8, 0, 1,
    1, 1, 1, 0, 1, 1, 5, 5,
}
Definition at line 107 of file dgn_yacc.c.
short yylhs[]
Initial value:
= { -1,
    0, 0, 5, 5, 6, 6, 6, 6, 7, 1,
    1, 8, 8, 8, 12, 13, 15, 15, 14, 10,
   10, 10, 10, 10, 16, 16, 17, 17, 18, 18,
   19, 19, 20, 20, 9, 9, 22, 23, 3, 3,
    3, 3, 3, 2, 2, 4, 21, 11,
}
Definition at line 100 of file dgn_yacc.c.
YYSTYPE yylval
Definition at line 330 of file dgn_yacc.c.
Referenced by yyparse().
int yynerrs
Definition at line 324 of file dgn_yacc.c.
Referenced by yyparse().
FILE * yyout
short yyrindex[]
Initial value:
= { 86,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 87, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 16, 0, 1,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 31, 1, 46, 0, 0, 0, 0,
    0, 0, 0, 31, 0, 61, 76, 0, 0, 0,
    0, 0, 0, 91, 0, 0, 0,
}
Definition at line 145 of file dgn_yacc.c.
char yysccsid[] = `@(#)yaccpar 1.9 (Berkeley) 02/21/93` [static]
Definition at line 2 of file dgn_yacc.c.
short yysindex[]
Initial value:
= { -237,
  -46, -45, -44, -39, -38, -30, -22, -21, -20, -19,
  -18, -17, -16, 0, -237, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, -262, -234, -233, -232, -230, -229, -228, -227, -217,
 -216, -215, -214, -202, 0, -221, -7, -219, -221, -221,
 -221, -221, 0, 0, 0, 0, 0, 0, 0, 19,
   20, 21, -2, -1, -212, -211, -190, -189, -188, -271,
   19, 20, 20, 27, 28, 29, 0, 0, 30, 0,
    0, 0, 0, -193, -271, -182, -180, 19, 19, -179,
 -178, 0, 0, -193, 0, -177, -176, -175, 42, 43,
    0, 0, 0, -172, 0, 0, 0,
}
Definition at line 132 of file dgn_yacc.c.
short yyss[YYSTACKSIZE]
Definition at line 331 of file dgn_yacc.c.
Referenced by yyparse().
short* yyssp
Definition at line 327 of file dgn_yacc.c.
Referenced by yyparse().
short yytable[]
Definition at line 164 of file dgn_yacc.c.
YYSTYPE yyval
Definition at line 329 of file dgn_yacc.c.
Referenced by yyparse().
YYSTYPE yyvs[YYSTACKSIZE]
Definition at line 332 of file dgn_yacc.c.
Referenced by yyparse().
YYSTYPE* yyvsp
Definition at line 328 of file dgn_yacc.c.
Referenced by yyparse().