nethack/win/X11/dialogs.c File Reference
#include <X11/Intrinsic.h>
*
#include <X11/StringDefs.h>
*
#include <X11/Xos.h>
*
#include <X11/Xaw/Cardinals.h>
*
#include <X11/Xaw/Form.h>
*
#include <X11/Xaw/Label.h>
*
#include <X11/Xaw/AsciiText.h>
*
#include <X11/Xaw/Command.h>
*
#include `config.h`
*
Macros
#define PRESERVE_NO_SYSV /* X11 include files may define SYSV */
#define max(a, b) (((a) > (b)) ? (a) : (b))
Functions
Widget CreateDialog (Widget parent, String name, XtCallbackProc okay_callback, XtCallbackProc cancel_callback)
void SetDialogPrompt (Widget w, String newprompt)
String GetDialogResponse (Widget w)
void SetDialogResponse (Widget w, String s)
void positionpopup (Widget w, boolean bottom)
Variables
static const char okay_accelerators []
static const char cancel_accelerators []
Macro Definition Documentation
#define max(a, b) (((a) > (b)) ? (a) : (b))
Definition at line 234 of file dialogs.c.
#define PRESERVE_NO_SYSV /* X11 include files may define SYSV */
Definition at line 45 of file dialogs.c.
Function Documentation
Widget CreateDialog (Widget parent, String name, XtCallbackProc okay_callback, XtCallbackProc cancel_callback)
Definition at line 85 of file dialogs.c.
References cancel_accelerators, okay(), and okay_accelerators.
Referenced by mswin_display_splash_window(), mswin_init_menu_window(), mswin_init_RIP_window(), mswin_init_text_window(), X11_askname(), and X11_getlin().
{
    Widget form, prompt, response, okay, cancel;
    Arg args[20];
    Cardinal num_args;
                            num_args = 0;
#ifdef SPECIAL_CMAP
    if (special_cmap) {
    XtSetArg(args[num_args], XtNbackground, white); num_args++;
    }
#endif
    form = XtCreateManagedWidget(name, formWidgetClass, parent, args, num_args);
                            num_args = 0;
#ifdef SPECIAL_CMAP
    if (special_cmap) {
    XtSetArg(args[num_args], XtNforeground, black); num_args++;
    XtSetArg(args[num_args], XtNbackground, white); num_args++;
    }
#endif
    XtSetArg(args[num_args], XtNtop, XtChainTop); num_args++;
    XtSetArg(args[num_args], XtNbottom, XtChainTop); num_args++;
    XtSetArg(args[num_args], XtNleft, XtChainLeft); num_args++;
    XtSetArg(args[num_args], XtNright, XtChainLeft); num_args++;
    XtSetArg(args[num_args], XtNresizable, True); num_args++;
    XtSetArg(args[num_args], XtNborderWidth, 0); num_args++;
    prompt = XtCreateManagedWidget("prompt", labelWidgetClass,
                   form, args, num_args);
                            num_args = 0;
#ifdef SPECIAL_CMAP
    if (special_cmap) {
    XtSetArg(args[num_args], XtNforeground, black); num_args++;
    XtSetArg(args[num_args], XtNbackground, white); num_args++;
    }
#endif
    XtSetArg(args[num_args], XtNfromVert, prompt); num_args++;
    XtSetArg(args[num_args], XtNtop, XtChainTop); num_args++;
    XtSetArg(args[num_args], XtNbottom, XtChainTop); num_args++;
    XtSetArg(args[num_args], XtNleft, XtChainLeft); num_args++;
    XtSetArg(args[num_args], XtNright, XtChainLeft); num_args++;
    XtSetArg(args[num_args], XtNresizable, True); num_args++;
    XtSetArg(args[num_args], XtNeditType, XawtextEdit); num_args++;
    XtSetArg(args[num_args], XtNresize, XawtextResizeWidth); num_args++;
    XtSetArg(args[num_args], XtNstring, ""); num_args++;
    response = XtCreateManagedWidget("response", asciiTextWidgetClass,
                     form, args, num_args);
                            num_args = 0;
#ifdef SPECIAL_CMAP
    if (special_cmap) {
    XtSetArg(args[num_args], XtNforeground, black); num_args++;
    XtSetArg(args[num_args], XtNbackground, white); num_args++;
    }
#endif
    XtSetArg(args[num_args], XtNfromVert, response); num_args++;
    XtSetArg(args[num_args], XtNtop, XtChainTop); num_args++;
    XtSetArg(args[num_args], XtNbottom, XtChainTop); num_args++;
    XtSetArg(args[num_args], XtNleft, XtChainLeft); num_args++;
    XtSetArg(args[num_args], XtNright, XtChainLeft); num_args++;
    XtSetArg(args[num_args], XtNresizable, True); num_args++;
    XtSetArg(args[num_args], XtNaccelerators,
         XtParseAcceleratorTable(okay_accelerators)); num_args++;
    okay = XtCreateManagedWidget("okay", commandWidgetClass,
                 form, args, num_args);
    XtAddCallback(okay, XtNcallback, okay_callback, form);
    /* Only create cancel button if there is a callback for it. */
    if (cancel_callback) {
                                num_args = 0;
#ifdef SPECIAL_CMAP
    if (special_cmap) {
        XtSetArg(args[num_args], XtNforeground, black); num_args++;
        XtSetArg(args[num_args], XtNbackground, white); num_args++;
    }
#endif
    XtSetArg(args[num_args], XtNfromVert, response); num_args++;
    XtSetArg(args[num_args], XtNfromHoriz, okay); num_args++;
    XtSetArg(args[num_args], XtNtop, XtChainTop); num_args++;
    XtSetArg(args[num_args], XtNbottom, XtChainTop); num_args++;
    XtSetArg(args[num_args], XtNleft, XtChainLeft); num_args++;
    XtSetArg(args[num_args], XtNright, XtChainLeft); num_args++;
    XtSetArg(args[num_args], XtNresizable, True); num_args++;
    XtSetArg(args[num_args], XtNaccelerators,
         XtParseAcceleratorTable(cancel_accelerators)); num_args++;
    cancel = XtCreateManagedWidget("cancel", commandWidgetClass,
                       form, args, num_args);
    XtAddCallback(cancel, XtNcallback, cancel_callback, form);
    XtInstallAccelerators(response, cancel);
    }
    XtInstallAccelerators(response, okay);
    XtSetKeyboardFocus(form, response);
    return form;
}
String GetDialogResponse (Widget w)
Definition at line 221 of file dialogs.c.
References String.
Referenced by askname_done(), and done_button().
{
    Arg args[1];
    Widget response;
    String s;
    response = XtNameToWidget(w, "response");
    XtSetArg(args[0], XtNstring, &s);
    XtGetValues(response, args, ONE);
    return XtNewString(s);
}
void positionpopup (Widget w, boolean bottom)
Definition at line 284 of file dialogs.c.
References height, toplevel, and width.
Referenced by display_text_window(), X11_askname(), X11_get_ext_cmd(), X11_getlin(), X11_player_selection(), X11_select_menu(), and X11_yn_function().
{
    Arg args[3];
    Cardinal num_args;
    Dimension width, height, b_width;
    int x, y, max_x, max_y;
    Window root, child;
    XSizeHints *hints;
    int dummyx, dummyy;
    unsigned int dummymask;
    extern Widget toplevel;
    /* following line deals with a race condition w/brain-damaged WM's -dlc */
    XtUnrealizeWidget(w);
    XQueryPointer(XtDisplay(toplevel), XtWindow(toplevel), &root, &child,
          &x, &y, &dummyx, &dummyy, &dummymask);
    num_args = 0;
    XtSetArg(args[num_args], XtNwidth, &width); num_args++;
    XtSetArg(args[num_args], XtNheight, &height); num_args++;
    XtSetArg(args[num_args], XtNborderWidth, &b_width); num_args++;
    XtGetValues(w, args, num_args);
    /* position so that the cursor is center,center or center,bottom */
    width += 2 * b_width;
    x -= ((Position) width/2);
    if (x < 0) x = 0;
    if (x > (max_x = (Position) (XtScreen(w)->width - width))) x = max_x;
    if (bottom) {
    y -= (height+b_width-1);
    height += 2 * b_width;
    } else {
    height += 2 * b_width;
    y -= ((Position) height/2);
    }
    if (y < 0) y = 0;
    if (y > (max_y = (Position) (XtScreen(w)->height - height))) y = max_y;
    num_args = 0;
    XtSetArg(args[num_args], XtNx, x); num_args++;
    XtSetArg(args[num_args], XtNy, y); num_args++;
    XtSetValues(w, args, num_args);
    /* Some older window managers ignore XtN{x,y}; hint the same values */
    /* The {x,y} are not used by newer window managers; older ones need them */
    XtRealizeWidget(w);
    hints = XAllocSizeHints();
    hints->flags = USPosition;
    hints->x = x;
    hints->y = y;
    XSetWMNormalHints(XtDisplay(w), XtWindow(w), hints);
    XFree(hints);
}
void SetDialogPrompt (Widget w, String newprompt)
Definition at line 207 of file dialogs.c.
Referenced by X11_askname(), and X11_getlin().
{
    Arg args[1];
    Widget label;
    label = XtNameToWidget(w, "prompt");
    XtSetArg(args[0], XtNlabel, newprompt);
    XtSetValues(label, args, ONE);
}
void SetDialogResponse (Widget w, String s)
Definition at line 237 of file dialogs.c.
References width.
Referenced by X11_askname(), and X11_getlin().
{
    Arg args[4];
    Widget response;
    XFontStruct *font;
    Dimension width, nwidth, leftMargin, rightMargin;
    response = XtNameToWidget(w, "response");
    XtSetArg(args[0], XtNfont, &font);
    XtSetArg(args[1], XtNleftMargin, &leftMargin);
    XtSetArg(args[2], XtNrightMargin, &rightMargin);
    XtSetArg(args[3], XtNwidth, &width);
    XtGetValues(response, args, FOUR);
    /* width includes margins as per Xaw documentation */
    nwidth = (font->max_bounds.width * strlen(s))+leftMargin+rightMargin;
    if (nwidth < width)
    nwidth = width;
    XtSetArg(args[0], XtNstring, s);
    XtSetArg(args[1], XtNwidth, nwidth);
    XtSetValues(response, args, TWO);
    XawTextSetInsertionPoint(response, strlen(s));
}
Variable Documentation
const char cancel_accelerators[] [static]
Initial value:
=
    "#override\n\
     :<Key>Escape: set() notify() unset()\n\
     :<Ctrl>[: set() notify() unset()\n"
Definition at line 72 of file dialogs.c.
Referenced by CreateDialog().
const char okay_accelerators[] [static]
Initial value:
=
    "#override\n\
     :<Key>Return: set() notify() unset()\n"
Definition at line 68 of file dialogs.c.
Referenced by CreateDialog().