nethack/src/display.c File Reference
#include `hack.h`
*
#include `region.h`
*
Data Structures
struct tmp_glyph
struct gbuf_entry
Macros
#define _map_location(x, y, show)
#define DETECTED 2
#define PHYSICALLY_SEEN 1
#define is_worm_tail(mon) ((mon) && ((x != (mon)->mx) || (y != (mon)->my)))
#define reset_glyph_bbox()
#define more_than_one(x, y, a, b, c) (((a) && ((b)|(c))) || ((b) && ((a)|(c))) || ((c) && ((a)|(b))))
#define sign(z) ((z) < 0 ? -1 : ((z) > 0 ? 1 : 0))
#define T_d 0
#define T_l 1
#define T_u 2
#define T_r 3
#define T_stone 0
#define T_tlcorn 1
#define T_trcorn 2
#define T_hwall 3
#define T_tdwall 4
#define C_bl 0
#define C_tl 1
#define C_tr 2
#define C_br 3
#define C_trcorn 0
#define C_brcorn 1
#define C_blcorn 2
#define C_tlwall 3
#define C_tuwall 4
#define C_crwall 5
#define only(sv, bits) (((sv) & (bits)) && ! ((sv) & ~(bits)))
#define set_corner(idx, lev, which, outer, inner, name)
Functions
STATIC_DCL void FDECL (display_monster,(XCHAR_P, XCHAR_P, struct monst *, int, XCHAR_P))
STATIC_DCL int FDECL (swallow_to_glyph,(int, int))
STATIC_DCL void FDECL (display_warning,(struct monst *))
STATIC_DCL int FDECL (check_pos,(int, int, int))
STATIC_DCL int FDECL (set_twall,(int, int, int, int, int, int, int, int))
STATIC_DCL int FDECL (set_wall,(int, int, int))
STATIC_DCL int FDECL (set_corn,(int, int, int, int, int, int, int, int))
STATIC_DCL int FDECL (set_crosswall,(int, int))
STATIC_DCL void FDECL (set_seenv,(struct rm *, int, int, int, int))
STATIC_DCL void FDECL (t_warn,(struct rm *))
STATIC_DCL int FDECL (wall_angle,(struct rm *))
void magic_map_background (xchar x, xchar y, int show)
void map_background (xchar x, xchar y, int show)
void map_trap (struct trap *trap, int show)
void map_object (struct obj *obj, int show)
void map_invisible (xchar x, xchar y)
void unmap_object (int x, int y)
void map_location (int x, int y, int show)
STATIC_OVL void display_monster (xchar x, xchar y, struct monst *mon, int sightflags, xchar worm_tail)
STATIC_OVL void display_warning (struct monst *mon)
void feel_location (xchar x, xchar y)
void newsym (int x, int y)
void shieldeff (xchar x, xchar y)
void tmp_at (int x, int y)
void swallowed (int first)
void under_water (int mode)
void under_ground (int mode)
void see_monsters ()
void set_mimic_blocking ()
void see_objects ()
void see_traps ()
void curs_on_u ()
int doredraw ()
void docrt ()
void show_glyph (int x, int y, int glyph)
void clear_glyph_buffer ()
void row_refresh (int start, int stop, int y)
void cls ()
void flush_screen (int cursor_on_u)
int back_to_glyph (xchar x, xchar y)
STATIC_OVL int swallow_to_glyph (int mnum, int loc)
int zapdir_to_glyph (int dx, int dy, int beam_type)
int glyph_at (xchar x, xchar y)
STATIC_OVL int check_pos (int x, int y, int which)
STATIC_OVL int set_twall (int x0, int y0, int x1, int y1, int x2, int y2, int x3, int y3)
STATIC_OVL int set_wall (int x, int y, int horiz)
STATIC_OVL int set_corn (int x1, int y1, int x2, int y2, int x3, int y3, int x4, int y4)
STATIC_OVL int set_crosswall (int x, int y)
void set_wall_state ()
STATIC_OVL void set_seenv (struct rm *lev, int x0, int y0, int x, int y)
STATIC_OVL void t_warn (struct rm *lev)
STATIC_OVL int wall_angle (struct rm *lev)
Variables
static struct tmp_glyph tgfirst
static gbuf_entry gbuf [ROWNO][COLNO]
static char gbuf_start [ROWNO]
static char gbuf_stop [ROWNO]
static gbuf_entry nul_gbuf = { 0, cmap_to_glyph(S_stone) }
unsigned char seenv_matrix [3][3]
static const int wall_matrix [4][5]
static const int cross_matrix [4][6]
Macro Definition Documentation
#define _map_location(x, y, show)
Value:
{ \
    register struct obj *obj; \
    register struct trap *trap; \
                                    \
    if ((obj = vobj_at(x,y)) && !covers_objects(x,y))
      \
    map_object(obj,show); \
    else if ((trap = t_at(x,y)) && trap->tseen && !covers_traps(x,
      y)) \
    map_trap(trap,show); \
    else \
    map_background(x,y,show); \
}
Definition at line 323 of file display.c.
Referenced by feel_location(), map_location(), and newsym().
#define C_bl 0
Definition at line 1845 of file display.c.
Referenced by wall_angle().
#define C_blcorn 2
Definition at line 1859 of file display.c.
Referenced by wall_angle().
#define C_br 3
Definition at line 1848 of file display.c.
Referenced by wall_angle().
#define C_brcorn 1
Definition at line 1858 of file display.c.
Referenced by wall_angle().
#define C_crwall 5
Definition at line 1862 of file display.c.
Referenced by wall_angle().
#define C_tl 1
Definition at line 1846 of file display.c.
Referenced by wall_angle().
#define C_tlwall 3
Definition at line 1860 of file display.c.
Referenced by wall_angle().
#define C_tr 2
Definition at line 1847 of file display.c.
Referenced by wall_angle().
#define C_trcorn 0
Definition at line 1857 of file display.c.
Referenced by wall_angle().
#define C_tuwall 4
Definition at line 1861 of file display.c.
Referenced by wall_angle().
#define DETECTED 2
Definition at line 343 of file display.c.
Referenced by display_monster(), feel_location(), and newsym().
#define is_worm_tail(mon) ((mon) && ((x != (mon)->mx) || (y != (mon)->my)))
Definition at line 345 of file display.c.
Referenced by feel_location(), and newsym().
#define more_than_one(x, y, a, b, c) (((a) && ((b)|(c))) || ((b) && ((a)|(c))) || ((c) && ((a)|(b))))
Definition at line 1614 of file display.c.
Referenced by do_makedefs(), set_twall(), and set_wall().
#define only(sv, bits) (((sv) & (bits)) && ! ((sv) & ~(bits)))
Referenced by wall_angle().
#define PHYSICALLY_SEEN 1
Definition at line 344 of file display.c.
Referenced by display_monster(), feel_location(), and newsym().
#define reset_glyph_bbox()
Value:
{ \
    int i; \
                        \
    for (i = 0; i < ROWNO; i++) { \
        gbuf_start[i] = COLNO-1; \
        gbuf_stop[i] = 0; \
    } \
    }
Definition at line 1282 of file display.c.
Referenced by clear_glyph_buffer(), and flush_screen().
#define set_corner(idx, lev, which, outer, inner, name)
Value:
switch ((lev)->wall_info & WM_MASK) { \
    case 0: idx = which; break; \
    case WM_C_OUTER: idx = seenv & (outer) ? which : S_stone; break; \
    case WM_C_INNER: idx = seenv & ~(inner) ? which : S_stone; break; \
    default: \
        impossible("wall_angle: unknown %s mode %d", name, \
        (lev)->wall_info & WM_MASK); \
        idx = S_stone; \
        break; \
    }
Referenced by wall_angle().
#define sign(z) ((z) < 0 ? -1 : ((z) > 0 ? 1 : 0))
Definition at line 1803 of file display.c.
Referenced by set_seenv().
#define T_d 0
Definition at line 1818 of file display.c.
Referenced by wall_angle().
#define T_hwall 3
Definition at line 1833 of file display.c.
Referenced by wall_angle().
#define T_l 1
Definition at line 1819 of file display.c.
Referenced by wall_angle().
#define T_r 3
Definition at line 1821 of file display.c.
Referenced by wall_angle().
#define T_stone 0
Definition at line 1830 of file display.c.
Referenced by wall_angle().
#define T_tdwall 4
Definition at line 1834 of file display.c.
Referenced by wall_angle().
#define T_tlcorn 1
Definition at line 1831 of file display.c.
Referenced by wall_angle().
#define T_trcorn 2
Definition at line 1832 of file display.c.
Referenced by wall_angle().
#define T_u 2
Definition at line 1820 of file display.c.
Referenced by wall_angle().
Function Documentation
int back_to_glyph (xchar x, xchar y)
Definition at line 1389 of file display.c.
References AIR, ALTAR, BLCORNER, BRCORNER, CLOUD, cmap_to_glyph, CORR, CROSSWALL, D_BROKEN, D_ISOPEN, DB_FLOOR, DB_ICE, DB_LAVA, DB_MOAT, DB_UNDER, DBWALL, DOOR, DRAWBRIDGE_DOWN, DRAWBRIDGE_UP, flags, dlevel_t::flags, FOUNTAIN, GRAVE, HWALL, ICE, IRONBARS, LA_DOWN, LADDER, LAVAPOOL, level, levl, flag::lit_corridor, MOAT, POOL, ROOM, S_air, S_altar, S_bars, S_cloud, S_corr, S_dnladder, S_dnstair, S_fountain, S_grave, S_hcdbridge, S_hcdoor, S_hodbridge, S_hodoor, S_ice, S_lava, S_litcorr, S_ndoor, S_pool, S_room, S_sink, S_stone, S_throne, S_tree, S_upladder, S_upstair, S_vcdbridge, S_vcdoor, S_vodbridge, S_vodoor, S_water, SCORR, SDOOR, rm::seenv, SINK, STAIRS, STONE, TDWALL, THRONE, TLCORNER, TLWALL, TRCORNER, TREE, TRWALL, TUWALL, rm::typ, VWALL, wall_angle(), and WATER.
Referenced by magic_map_background(), and map_background().
{
    int idx;
    struct rm *ptr = &(levl[x][y]);
    switch (ptr->typ) {
    case SCORR:
    case STONE:
        idx = level.flags.arboreal ? S_tree : S_stone;
        break;
    case ROOM: idx = S_room; break;
    case CORR:
        idx = (ptr->waslit || flags.lit_corridor) ? S_litcorr :
      S_corr;
        break;
    case HWALL:
    case VWALL:
    case TLCORNER:
    case TRCORNER:
    case BLCORNER:
    case BRCORNER:
    case CROSSWALL:
    case TUWALL:
    case TDWALL:
    case TLWALL:
    case TRWALL:
    case SDOOR:
        idx = ptr->seenv ? wall_angle(ptr) : S_stone;
        break;
    case DOOR:
        if (ptr->doormask) {
        if (ptr->doormask & D_BROKEN)
            idx = S_ndoor;
        else if (ptr->doormask & D_ISOPEN)
            idx = (ptr->horizontal) ? S_hodoor : S_vodoor;
        else /* else is closed */
            idx = (ptr->horizontal) ? S_hcdoor : S_vcdoor;
        } else
        idx = S_ndoor;
        break;
    case IRONBARS: idx = S_bars; break;
    case TREE: idx = S_tree; break;
    case POOL:
    case MOAT: idx = S_pool; break;
    case STAIRS:
        idx = (ptr->ladder & LA_DOWN) ? S_dnstair : S_upstair;
        break;
    case LADDER:
        idx = (ptr->ladder & LA_DOWN) ? S_dnladder : S_upladder;
        break;
    case FOUNTAIN: idx = S_fountain; break;
    case SINK: idx = S_sink; break;
    case ALTAR: idx = S_altar; break;
    case GRAVE: idx = S_grave; break;
    case THRONE: idx = S_throne; break;
    case LAVAPOOL: idx = S_lava; break;
    case ICE: idx = S_ice; break;
    case AIR: idx = S_air; break;
    case CLOUD: idx = S_cloud; break;
    case WATER: idx = S_water; break;
    case DBWALL:
        idx = (ptr->horizontal) ? S_hcdbridge : S_vcdbridge;
        break;
    case DRAWBRIDGE_UP:
        switch(ptr->drawbridgemask & DB_UNDER) {
        case DB_MOAT: idx = S_pool; break;
        case DB_LAVA: idx = S_lava; break;
        case DB_ICE: idx = S_ice; break;
        case DB_FLOOR: idx = S_room; break;
        default:
        impossible("Strange db-under: %d",
               ptr->drawbridgemask & DB_UNDER);
        idx = S_room; /* something is better than nothing */
        break;
        }
        break;
    case DRAWBRIDGE_DOWN:
        idx = (ptr->horizontal) ? S_hodbridge : S_vodbridge;
        break;
    default:
        impossible("back_to_glyph: unknown level type [ = %d ]",ptr->typ);
        idx = S_room;
        break;
    }
    return cmap_to_glyph(idx);
}
STATIC_OVL int check_pos (int x, int y, int which)
Definition at line 1590 of file display.c.
References CORR, IS_ROCK, levl, SCORR, and type.
Referenced by set_corn(), set_crosswall(), set_twall(), and set_wall().
{
    int type;
    if (!isok(x,y)) return which;
    type = levl[x][y].typ;
    if (IS_ROCK(type) || type == CORR || type == SCORR) return which;
    return 0;
}
void clear_glyph_buffer ()
Definition at line 1298 of file display.c.
References COLNO, nul_gbuf, reset_glyph_bbox, and ROWNO.
Referenced by cls().
{
    register int x, y;
    register gbuf_entry *gptr;
    for (y = 0; y < ROWNO; y++) {
    gptr = &gbuf[y][0];
    for (x = COLNO; x; x--) {
        *gptr++ = nul_gbuf;
    }
    }
    reset_glyph_bbox();
}
void cls ()
Definition at line 1327 of file display.c.
References flag::botlx, clear_glyph_buffer(), clear_nhwindow, display_nhwindow, FALSE, flags, WIN_MAP, and WIN_MESSAGE.
Referenced by docrt(), find_trap(), food_detect(), gold_detect(), monster_detect(), object_detect(), swallowed(), trap_detect(), under_ground(), under_water(), and you_aggravate().
{
    display_nhwindow(WIN_MESSAGE, FALSE); /* flush messages */
    flags.botlx = 1; /* force update of botl window */
    clear_nhwindow(WIN_MAP); /* clear physical screen */
    clear_glyph_buffer(); /* this is sort of an extra effort, but OK */
}
void curs_on_u ()
Definition at line 1137 of file display.c.
References flush_screen().
Referenced by done1(), done2(), and savelife().
{
    flush_screen(1); /* Flush waiting glyphs & put cursor on hero */
}
STATIC_OVL void display_monster (xchar x, xchar y, struct monst * mon, int sightflags, xchar worm_tail)
Definition at line 359 of file display.c.
References cmap_to_glyph, obj::corpsenm, DETECTED, detected_mon_to_glyph, detected_monnum_to_glyph, rm::glyph, Hallucination, levl, M_AP_FURNITURE, M_AP_MONSTER, M_AP_NOTHING, M_AP_OBJECT, map_object(), mon_to_glyph, monnum_to_glyph, obj::otyp, obj::ox, obj::oy, pet_to_glyph, petnum_to_glyph, PHYSICALLY_SEEN, Protection_from_shape_changers, sensemon, show_glyph(), and what_mon.
Referenced by feel_location(), and newsym().
{
    register boolean mon_mimic = (mon->m_ap_type != M_AP_NOTHING);
    register int sensed = mon_mimic &&
    (Protection_from_shape_changers || sensemon(mon));
    /*
     * We must do the mimic check first. If the mimic is mimicing something,
     * and the location is in sight, we have to change the hero's memory
     * so that when the position is out of sight, the hero remembers what
     * the mimic was mimicing.
     */
    if (mon_mimic && (sightflags == PHYSICALLY_SEEN)) {
    switch (mon->m_ap_type) {
        default:
        impossible("display_monster: bad m_ap_type value [ = %d ]",
                            (int) mon->m_ap_type);
        case M_AP_NOTHING:
        show_glyph(x, y, mon_to_glyph(mon));
        break;
        case M_AP_FURNITURE: {
        /*
         * This is a poor man's version of map_background(). I can't
         * use map_background() because we are overriding what is in
         * the 'typ' field. Maybe have map_background()'s parameters
         * be (x,y,glyph) instead of just (x,y).
         *
         * mappearance is currently set to an S_ index value in
         * makemon.c.
         */
        register int glyph = cmap_to_glyph(mon->mappearance);
        levl[x][y].glyph = glyph;
        if (!sensed) show_glyph(x,y, glyph);
        break;
        }
        case M_AP_OBJECT: {
        struct obj obj; /* Make a fake object to send */
                /* to map_object(). */
        obj.ox = x;
        obj.oy = y;
        obj.otyp = mon->mappearance;
        obj.corpsenm = PM_TENGU; /* if mimicing a corpse */
        map_object(&obj,!sensed);
        break;
        }
        case M_AP_MONSTER:
        show_glyph(x,y, monnum_to_glyph(what_mon((int)mon->
      mappearance)));
        break;
    }
    
    }
    /* If the mimic is unsucessfully mimicing something, display the monster */
    if (!mon_mimic || sensed) {
    int num;
    /* [ALI] Only use detected glyphs when monster wouldn't be
     * visible by any other means.
     */
    if (sightflags == DETECTED) {
        if (worm_tail)
        num = detected_monnum_to_glyph(what_mon(PM_LONG_WORM_TAIL));
        else
        num = detected_mon_to_glyph(mon);
    } else if (mon->mtame && !Hallucination) {
        if (worm_tail)
        num = petnum_to_glyph(PM_LONG_WORM_TAIL);
        else
        num = pet_to_glyph(mon);
    } else {
        if (worm_tail)
        num = monnum_to_glyph(what_mon(PM_LONG_WORM_TAIL));
        else
        num = mon_to_glyph(mon);
    }
    show_glyph(x,y,num);
    }
}
STATIC_OVL void display_warning (struct monst * mon)
Definition at line 456 of file display.c.
References Hallucination, MATCH_WARN_OF_MON, mon_to_glyph, mon_warning, monst::mx, rn1, show_glyph(), WARNCOUNT, and warning_to_glyph.
Referenced by newsym().
{
    int x = mon->mx, y = mon->my;
    int wl = (int) (mon->m_lev / 4);
    int glyph;
    if (mon_warning(mon)) {
        if (wl > WARNCOUNT - 1) wl = WARNCOUNT - 1;
    /* 3.4.1: this really ought to be rn2(WARNCOUNT), but value "0"
       isn't handled correctly by the what_is routine so avoid it */
    if (Hallucination) wl = rn1(WARNCOUNT-1,1);
        glyph = warning_to_glyph(wl);
    } else if (MATCH_WARN_OF_MON(mon)) {
    glyph = mon_to_glyph(mon);
    } else {
        impossible("display_warning did not match warning type?");
        return;
    }
    show_glyph(x, y, glyph);
}
void docrt ()
Definition at line 1150 of file display.c.
References flag::botlx, cls(), cmap_to_glyph, COLNO, flags, rm::glyph, Is_waterlevel, levl, ROWNO, S_stone, see_monsters(), show_glyph(), swallowed(), u, under_ground(), under_water(), Underwater, you::ux, you::uz, vision_recalc(), trap::x, and trap::y.
Referenced by do_mapping(), do_vicinity_map(), dorecover(), doredraw(), find_trap(), food_detect(), gold_detect(), monster_detect(), object_detect(), rloc_to(), teleds(), trap_detect(), and you_aggravate().
{
    register int x,y;
    register struct rm *lev;
    if (!u.ux) return; /* display isn't ready yet */
    if (u.uswallow) {
    swallowed(1);
    return;
    }
    if (Underwater && !Is_waterlevel(&u.uz)) {
    under_water(1);
    return;
    }
    if (u.uburied) {
    under_ground(1);
    return;
    }
    /* shut down vision */
    vision_recalc(2);
    /*
     * This routine assumes that cls() does the following:
     * + fills the physical screen with the symbol for rock
     * + clears the glyph buffer
     */
    cls();
    /* display memory */
    for (x = 1; x < COLNO; x++) {
    lev = &levl[x][0];
    for (y = 0; y < ROWNO; y++, lev++)
        if (lev->glyph != cmap_to_glyph(S_stone))
        show_glyph(x,y,lev->glyph);
    }
    /* see what is to be seen */
    vision_recalc(0);
    /* overlay with monsters */
    see_monsters();
    flags.botlx = 1; /* force a redraw of the bottom line */
}
int doredraw ()
Definition at line 1143 of file display.c.
References docrt().
Referenced by amii_cliparound(), dosave(), doset(), EditClipping(), ghack_reinit_map_window(), and ghack_save_game().
{
    docrt();
    return 0;
}
STATIC_DCL void FDECL (display_monster , (XCHAR_P, XCHAR_P, struct monst *, int, XCHAR_P))
STATIC_DCL int FDECL (swallow_to_glyph , (int, int))
STATIC_DCL void FDECL (display_warning , (struct monst *))
STATIC_DCL int FDECL (check_pos , (int, int, int))
STATIC_DCL int FDECL (set_twall , (int, int, int, int, int, int, int, int))
STATIC_DCL int FDECL (set_wall , (int, int, int))
STATIC_DCL int FDECL (set_corn , (int, int, int, int, int, int, int, int))
STATIC_DCL int FDECL (set_crosswall , (int, int))
STATIC_DCL void FDECL (set_seenv , (struct rm *, int, int, int, int))
STATIC_DCL void FDECL (t_warn , (struct rm *))
STATIC_DCL int FDECL (wall_angle , (struct rm *))
void feel_location (xchar x, xchar y)
Definition at line 489 of file display.c.
References _map_location, BC_BALL, BC_CHAIN, you::bc_felt, carried, cmap_to_glyph, CORR, D_CLOSED, D_LOCKED, DETECTED, display_monster(), rm::glyph, glyph_is_invisible, Is_airlevel, IS_DOOR, IS_POOL, IS_ROCK, IS_ROOM, Is_waterlevel, is_worm_tail, level, Levitation, levl, m_at, map_background(), map_object(), MATCH_WARN_OF_MON, dlevel_t::objects, objnum_to_glyph, obj::ox, obj::oy, PHYSICALLY_SEEN, Punished, ROOM, S_corr, S_litcorr, S_room, S_stone, rm::seenv, sensemon, set_seenv(), show_glyph(), tp_sensemon, rm::typ, u, uball, uchain, Underwater, you::ux, you::uy, and you::uz.
Referenced by dokick(), dosearch0(), find_trap(), and newsym().
{
    struct rm *lev = &(levl[x][y]);
    struct obj *boulder;
    register struct monst *mon;
    /* If the hero's memory of an invisible monster is accurate, we want to keep
     * him from detecting the same monster over and over again on each turn.
     * We must return (so we don't erase the monster). (We must also, in the
     * search function, be sure to skip over previously detected 'I's.)
     */
    if (glyph_is_invisible(levl[x][y].glyph) && m_at(x,y)) return;
    /* The hero can't feel non pool locations while under water. */
    if (Underwater && !Is_waterlevel(&u.uz) && ! is_pool(x,y))
    return;
    /* Set the seen vector as if the hero had seen it. It doesn't matter */
    /* if the hero is levitating or not. */
    set_seenv(lev, u.ux, u.uy, x, y);
    if (Levitation && !Is_airlevel(&u.uz) && !
      Is_waterlevel(&u.uz)) {
    /*
     * Levitation Rules. It is assumed that the hero can feel the state
     * of the walls around herself and can tell if she is in a corridor,
     * room, or doorway. Boulders are felt because they are large enough.
     * Anything else is unknown because the hero can't reach the ground.
     * This makes things difficult.
     *
     * Check (and display) in order:
     *
     * + Stone, walls, and closed doors.
     * + Boulders. [see a boulder before a doorway]
     * + Doors.
     * + Room/water positions
     * + Everything else (hallways!)
     */
    if (IS_ROCK(lev->typ) || (IS_DOOR(lev->typ) &&
                (lev->doormask & (D_LOCKED | D_CLOSED)))) {
        map_background(x, y, 1);
    } else if ((boulder = sobj_at(BOULDER,x,y)) != 0) {
        map_object(boulder, 1);
    } else if (IS_DOOR(lev->typ)) {
        map_background(x, y, 1);
    } else if (IS_ROOM(lev->typ) || IS_POOL(lev->typ)) {
        /*
         * An open room or water location. Normally we wouldn't touch
         * this, but we have to get rid of remembered boulder symbols.
         * This will only occur in rare occations when the hero goes
         * blind and doesn't find a boulder where expected (something
         * came along and picked it up). We know that there is not a
         * boulder at this location. Show fountains, pools, etc.
         * underneath if already seen. Otherwise, show the appropriate
         * floor symbol.
         *
         * Similarly, if the hero digs a hole in a wall or feels a location
         * that used to contain an unseen monster. In these cases,
         * there's no reason to assume anything was underneath, so
         * just show the appropriate floor symbol. If something was
         * embedded in the wall, the glyph will probably already
         * reflect that. Don't change the symbol in this case.
         *
         * This isn't quite correct. If the boulder was on top of some
         * other objects they should be seen once the boulder is removed.
         * However, we have no way of knowing that what is there now
         * was there then. So we let the hero have a lapse of memory.
         * We could also just display what is currently on the top of the
         * object stack (if anything).
         */
        if (lev->glyph == objnum_to_glyph(BOULDER)) {
        if (lev->typ != ROOM && lev->seenv) {
            map_background(x, y, 1);
        } else {
            lev->glyph = lev->waslit ? cmap_to_glyph(S_room) :
                           cmap_to_glyph(S_stone);
            show_glyph(x,y,lev->glyph);
        }
        } else if ((lev->glyph >= cmap_to_glyph(S_stone) &&
            lev->glyph < cmap_to_glyph(S_room)) ||
               glyph_is_invisible(levl[x][y].glyph)) {
        lev->glyph = lev->waslit ? cmap_to_glyph(S_room) :
                       cmap_to_glyph(S_stone);
        show_glyph(x,y,lev->glyph);
        }
    } else {
        /* We feel it (I think hallways are the only things left). */
        map_background(x, y, 1);
        /* Corridors are never felt as lit (unless remembered that way) */
        /* (lit_corridor only). */
        if (lev->typ == CORR &&
            lev->glyph == cmap_to_glyph(S_litcorr) && !lev->waslit)
        show_glyph(x, y, lev->glyph = cmap_to_glyph(
      S_corr));
    }
    } else {
    _map_location(x, y, 1);
    if (Punished) {
        /*
         * A ball or chain is only felt if it is first on the object
         * location list. Otherwise, we need to clear the felt bit ---
         * something has been dropped on the ball/chain. If the bit is
         * not cleared, then when the ball/chain is moved it will drop
         * the wrong glyph.
         */
        if (uchain->ox == x && uchain->oy == y) {
        if (level.objects[x][y] == uchain)
            u.bc_felt |= BC_CHAIN;
        else
            u.bc_felt &= ~BC_CHAIN; /* do not feel the chain */
        }
        if (!carried(uball) && uball->ox == x && uball->
      oy == y) {
        if (level.objects[x][y] == uball)
            u.bc_felt |= BC_BALL;
        else
            u.bc_felt &= ~BC_BALL; /* do not feel the ball */
        }
    }
    /* Floor spaces are dark if unlit. Corridors are dark if unlit. */
    if (lev->typ == ROOM &&
            lev->glyph == cmap_to_glyph(S_room) && !lev->waslit)
        show_glyph(x,y, lev->glyph = cmap_to_glyph(
      S_stone));
    else if (lev->typ == CORR &&
            lev->glyph == cmap_to_glyph(S_litcorr) && !lev->waslit)
        show_glyph(x,y, lev->glyph = cmap_to_glyph(
      S_corr));
    }
    /* draw monster on top if we can sense it */
    if ((x != u.ux || y != u.uy) && (mon = m_at(x,y)) && sensemon(mon))
    display_monster(x, y, mon,
        (tp_sensemon(mon) || MATCH_WARN_OF_MON(mon)) ?
      PHYSICALLY_SEEN : DETECTED,
        is_worm_tail(mon));
}
void flush_screen (int cursor_on_u)
Definition at line 1340 of file display.c.
References flag::botl, flag::botlx, curs, display_nhwindow, FALSE, flags, gbuf_entry::glyph, gbuf_entry::new, print_glyph, reset_glyph_bbox, ROWNO, u, you::ux, you::uy, and WIN_MAP.
Referenced by check_here(), curs_on_u(), do_mapping(), do_vicinity_map(), hurtle_step(), mkinvokearea(), shieldeff(), tmp_at(), and X11_getlin().
{
    /* Prevent infinite loops on errors:
     * flush_screen->print_glyph->impossible->pline->flush_screen
     */
    static boolean flushing = 0;
    static boolean delay_flushing = 0;
    register int x,y;
    if (cursor_on_u == -1) delay_flushing = !delay_flushing;
    if (delay_flushing) return;
    if (flushing) return; /* if already flushing then return */
    flushing = 1;
    for (y = 0; y < ROWNO; y++) {
    register gbuf_entry *gptr = &gbuf[y][x = gbuf_start[y]];
    for (; x <= gbuf_stop[y]; gptr++, x++)
        if (gptr->new) {
        print_glyph(WIN_MAP,x,y,gptr->glyph);
        gptr->new = 0;
        }
    }
    if (cursor_on_u) curs(WIN_MAP, u.ux,u.uy); /* move cursor to the hero */
    display_nhwindow(WIN_MAP, FALSE);
    reset_glyph_bbox();
    flushing = 0;
    if(flags.botl || flags.botlx) bot();
}
int glyph_at (xchar x, xchar y)
Definition at line 1532 of file display.c.
References cmap_to_glyph, COLNO, gbuf_entry::glyph, ROWNO, and S_room.
Referenced by attack_checks(), check_map_spot(), do_look(), ghack_map_print_glyph(), lookat(), and see_traps().
{
    if(x < 0 || y < 0 || x >= COLNO || y >= ROWNO)
    return cmap_to_glyph(S_room); /* XXX */
    return gbuf[y][x].glyph;
}
void magic_map_background (xchar x, xchar y, int show)
Definition at line 168 of file display.c.
References back_to_glyph(), cansee, cmap_to_glyph, CORR, dlevel_t::flags, rm::glyph, level, levl, ROOM, S_corr, S_litcorr, S_room, S_stone, show_glyph(), and rm::typ.
Referenced by findone(), and show_map_spot().
{
    int glyph = back_to_glyph(x,y); /* assumes hero can see x,y */
    struct rm *lev = &levl[x][y];
    /*
     * Correct for out of sight lit corridors and rooms that the hero
     * doesn't remember as lit.
     */
    if (!cansee(x,y) && !lev->waslit) {
    /* Floor spaces are dark if unlit. Corridors are dark if unlit. */
    if (lev->typ == ROOM && glyph == cmap_to_glyph(S_room))
        glyph = cmap_to_glyph(S_stone);
    else if (lev->typ == CORR && glyph == cmap_to_glyph(
      S_litcorr))
        glyph = cmap_to_glyph(S_corr);
    }
    if (level.flags.hero_memory)
    lev->glyph = glyph;
    if (show) show_glyph(x,y, glyph);
}
void map_background (xchar x, xchar y, int show)
Definition at line 213 of file display.c.
References back_to_glyph(), dlevel_t::flags, rm::glyph, level, levl, and show_glyph().
Referenced by feel_location(), sokoban_detect(), and unmap_object().
{
    register int glyph = back_to_glyph(x,y);
    if (level.flags.hero_memory)
    levl[x][y].glyph = glyph;
    if (show) show_glyph(x,y, glyph);
}
void map_invisible (xchar x, xchar y)
Definition at line 272 of file display.c.
References dlevel_t::flags, GLYPH_INVISIBLE, level, levl, show_glyph(), u, you::ux, and you::uy.
Referenced by attack(), attack_checks(), dokick(), dosearch0(), findone(), flash_hits_mon(), mbhit(), mbhitm(), newsym(), use_offensive(), and you_aggravate().
{
    if (x != u.ux || y != u.uy) { /* don't display I at hero's location */
    if (level.flags.hero_memory)
        levl[x][y].glyph = GLYPH_INVISIBLE;
    show_glyph(x, y, GLYPH_INVISIBLE);
    }
}
void map_location (int x, int y, int show)
Definition at line 337 of file display.c.
References _map_location.
Referenced by start_engulf().
{
    _map_location(x,y,show);
}
void map_object (struct obj * obj, int show)
Definition at line 250 of file display.c.
References dlevel_t::flags, rm::glyph, level, levl, obj_to_glyph, and show_glyph().
Referenced by display_monster(), feel_location(), food_detect(), gold_detect(), move_bc(), object_detect(), sense_trap(), and sokoban_detect().
{
    register int x = obj->ox, y = obj->oy;
    register int glyph = obj_to_glyph(obj);
    if (level.flags.hero_memory)
    levl[x][y].glyph = glyph;
    if (show) show_glyph(x, y, glyph);
}
void map_trap (struct trap * trap, int show)
Definition at line 231 of file display.c.
References dlevel_t::flags, rm::glyph, level, levl, show_glyph(), and trap_to_glyph.
Referenced by find_trap(), sense_trap(), sokoban_detect(), and unmap_object().
{
    register int x = trap->tx, y = trap->ty;
    register int glyph = trap_to_glyph(trap);
    if (level.flags.hero_memory)
    levl[x][y].glyph = glyph;
    if (show) show_glyph(x, y, glyph);
}
void newsym (int x, int y)
Definition at line 629 of file display.c.
References _map_location, ACCESSIBLE, BEAR_TRAP, cansee, cmap_to_glyph, CORR, Detect_monsters, DETECTED, display_monster(), display_self, display_warning(), feel_location(), rm::glyph, glyph_is_invisible, in_mklev, Is_waterlevel, is_worm_tail, levl, m_at, map_invisible(), MATCH_WARN_OF_MON, mon_visible, mon_warning, NO_TRAP, NULL, PHYSICALLY_SEEN, PIT, ROOM, S_corr, S_litcorr, S_room, S_stone, See_invisible, see_with_infrared, senseself, show_glyph(), show_region(), SPIKED_PIT, tp_sensemon, TRUE, rm::typ, u, Underwater, you::ux, you::uy, you::uz, visible_region_at(), and WEB.
Referenced by add_region(), attack_checks(), charm_snakes(), clear_bypasses(), demon_talk(), dipfountain(), do_earthquake(), dofindgem(), dokick(), dosacrifice(), dosearch0(), dosit(), dotele(), drag_ball(), drinkfountain(), drop_ball(), dryup(), end_engulf(), find_trap(), findone(), food_detect(), gold_detect(), gush(), hurtle_step(), kick_monster(), kick_object(), kickdmg(), level_tele_trap(), m_lose_armor(), mhurtle_step(), mkinvokearea(), mkinvpos(), mon_set_minvis(), move_bc(), movebubbles(), mv_bubble(), object_detect(), openone(), pick_obj(), pickup(), place_worm_tail_randomly(), remove_region(), remove_worm(), rloc_to(), rloco(), savebones(), see_monsters(), see_objects(), see_traps(), see_wsegs(), set_bc(), shieldeff(), ship_object(), show_map_spot(), tele_trap(), teleds(), throw_gold(), throwit(), tmp_at(), toss_wsegs(), trap_detect(), under_ground(), under_water(), unplacebc(), update_mon_intrinsics(), use_defensive(), use_misc(), use_offensive(), vision_recalc(), worm_move(), and you_aggravate().
{
    register struct monst *mon;
    register struct rm *lev = &(levl[x][y]);
    register int see_it;
    register xchar worm_tail;
    if (in_mklev) return;
    /* only permit updating the hero when swallowed */
    if (u.uswallow) {
    if (x == u.ux && y == u.uy) display_self();
    return;
    }
    if (Underwater && !Is_waterlevel(&u.uz)) {
    /* don't do anything unless (x,y) is an adjacent underwater position */
    int dx, dy;
    if (!is_pool(x,y)) return;
    dx = x - u.ux; if (dx < 0) dx = -dx;
    dy = y - u.uy; if (dy < 0) dy = -dy;
    if (dx > 1 || dy > 1) return;
    }
    /* Can physically see the location. */
    if (cansee(x,y)) {
        NhRegion* reg = visible_region_at(x,y);
    /*
     * Don't use templit here: E.g.
     *
     * lev->waslit = !!(lev->lit || templit(x,y));
     *
     * Otherwise we have the "light pool" problem, where non-permanently
     * lit areas just out of sight stay remembered as lit. They should
     * re-darken.
     *
     * Perhaps ALL areas should revert to their "unlit" look when
     * out of sight.
     */
    lev->waslit = (lev->lit!=0); /* remember lit condition */
    if (reg != NULL && ACCESSIBLE(lev->typ)) {
        show_region(reg,x,y);
        return;
    }
    if (x == u.ux && y == u.uy) {
        if (senseself()) {
        _map_location(x,y,0); /* map *under* self */
        display_self();
        } else
        /* we can see what is there */
        _map_location(x,y,1);
    }
    else {
        mon = m_at(x,y);
        worm_tail = is_worm_tail(mon);
        see_it = mon && (worm_tail
        ? (!mon->minvis || See_invisible)
        : (mon_visible(mon)) || tp_sensemon(mon) ||
      MATCH_WARN_OF_MON(mon));
        if (mon && (see_it || (!worm_tail && Detect_monsters))) {
        if (mon->mtrapped) {
            struct trap *trap = t_at(x, y);
            int tt = trap ? trap->ttyp : NO_TRAP;
            /* if monster is in a physical trap, you see the trap too */
            if (tt == BEAR_TRAP || tt == PIT ||
            tt == SPIKED_PIT ||tt == WEB) {
            trap->tseen = TRUE;
            }
        }
        _map_location(x,y,0); /* map under the monster */
        /* also gets rid of any invisibility glyph */
        display_monster(x, y, mon, see_it ? PHYSICALLY_SEEN :
      DETECTED, worm_tail);
        }
        else if (mon && mon_warning(mon) && !is_worm_tail(mon))
            display_warning(mon);
        else if (glyph_is_invisible(levl[x][y].glyph))
        map_invisible(x, y);
        else
        _map_location(x,y,1); /* map the location */
    }
    }
    /* Can't see the location. */
    else {
    if (x == u.ux && y == u.uy) {
        feel_location(u.ux, u.uy); /* forces an update */
        if (senseself()) display_self();
    }
    else if ((mon = m_at(x,y))
        && ((see_it = (tp_sensemon(mon) || MATCH_WARN_OF_MON(mon)
                    || (see_with_infrared(mon) && mon_visible(mon))))
            || Detect_monsters)
        && !is_worm_tail(mon)) {
        /* Monsters are printed every time. */
        /* This also gets rid of any invisibility glyph */
        display_monster(x, y, mon, see_it ? 0 : DETECTED, 0);
    }
    else if ((mon = m_at(x,y)) && mon_warning(mon) &&
         !is_worm_tail(mon)) {
            display_warning(mon);
    }
    /*
     * If the location is remembered as being both dark (waslit is false)
     * and lit (glyph is a lit room or lit corridor) then it was either:
     *
     * (1) A dark location that the hero could see through night
     * vision.
     *
     * (2) Darkened while out of the hero's sight. This can happen
     * when cursed scroll of light is read.
     *
     * In either case, we have to manually correct the hero's memory to
     * match waslit. Deciding when to change waslit is non-trivial.
     *
     * Note: If flags.lit_corridor is set, then corridors act like room
     * squares. That is, they light up if in night vision range.
     * If flags.lit_corridor is not set, then corridors will
     * remain dark unless lit by a light spell and may darken
     * again, as discussed above.
     *
     * These checks and changes must be here and not in back_to_glyph().
     * They are dependent on the position being out of sight.
     */
    else if (!lev->waslit) {
        if (lev->glyph == cmap_to_glyph(S_litcorr) && lev->
      typ == CORR)
        show_glyph(x, y, lev->glyph = cmap_to_glyph(
      S_corr));
        else if (lev->glyph == cmap_to_glyph(S_room) && lev->
      typ == ROOM)
        show_glyph(x, y, lev->glyph = cmap_to_glyph(
      S_stone));
        else
        goto show_mem;
    } else {
show_mem:
        show_glyph(x, y, lev->glyph);
    }
    }
}
void row_refresh (int start, int stop, int y)
Definition at line 1316 of file display.c.
References cmap_to_glyph, print_glyph, S_stone, and WIN_MAP.
{
    register int x;
    for (x = start; x <= stop; x++)
    if (gbuf[y][x].glyph != cmap_to_glyph(S_stone))
        print_glyph(WIN_MAP,x,y,gbuf[y][x].glyph);
}
void see_monsters ()
Definition at line 1065 of file display.c.
References DEADMONSTER, fmon, monst::mx, monst::my, newsym(), monst::nmon, see_wsegs(), u, you::ux, and you::uy.
Referenced by attrcurse(), docrt(), pleased(), and teleds().
{
    register struct monst *mon;
    for (mon = fmon; mon; mon = mon->nmon) {
    if (DEADMONSTER(mon)) continue;
    newsym(mon->mx,mon->my);
    if (mon->wormno) see_wsegs(mon);
    }
#ifdef STEED
    /* when mounted, hero's location gets caught by monster loop */
    if (!u.usteed)
#endif
    newsym(u.ux, u.uy);
}
void see_objects ()
Definition at line 1110 of file display.c.
References fobj, newsym(), obj::nobj, obj::ox, obj::oy, and vobj_at.
{
    register struct obj *obj;
    for(obj = fobj; obj; obj = obj->nobj)
    if (vobj_at(obj->ox,obj->oy) == obj) newsym(obj->ox, obj->
      oy);
}
void see_traps ()
Definition at line 1121 of file display.c.
References ftrap, glyph_at(), glyph_is_trap, newsym(), trap::ntrap, trap::tx, and trap::ty.
{
    struct trap *trap;
    int glyph;
    for (trap = ftrap; trap; trap = trap->ntrap) {
    glyph = glyph_at(trap->tx, trap->ty);
    if (glyph_is_trap(glyph))
        newsym(trap->tx, trap->ty);
    }
}
STATIC_OVL int set_corn (int x1, int y1, int x2, int y2, int x3, int y3, int x4, int y4)
Definition at line 1660 of file display.c.
References check_pos(), WM_C_INNER, and WM_C_OUTER.
Referenced by set_wall_state().
{
    int wmode, is_1, is_2, is_3, is_4;
    is_1 = check_pos(x1, y1, 1);
    is_2 = check_pos(x2, y2, 1);
    is_3 = check_pos(x3, y3, 1);
    is_4 = check_pos(x4, y4, 1); /* inner location */
    /*
     * All 4 should not be true. So if the inner location is rock,
     * use it. If all of the outer 3 are true, use outer. We currently
     * can't cover the case where only part of the outer is rock, so
     * we just say that all the walls are finished (if not overridden
     * by the inner section).
     */
    if (is_4) {
    wmode = WM_C_INNER;
    } else if (is_1 && is_2 && is_3)
    wmode = WM_C_OUTER;
     else
    wmode = 0; /* finished walls on all sides */
    return wmode;
}
STATIC_OVL int set_crosswall (int x, int y)
Definition at line 1689 of file display.c.
References check_pos(), WM_X_BL, WM_X_BLTR, WM_X_BR, WM_X_TL, WM_X_TLBR, and WM_X_TR.
Referenced by set_wall_state().
{
    int wmode, is_1, is_2, is_3, is_4;
    is_1 = check_pos(x-1, y-1, 1);
    is_2 = check_pos(x+1, y-1, 1);
    is_3 = check_pos(x+1, y+1, 1);
    is_4 = check_pos(x-1, y+1, 1);
    wmode = is_1+is_2+is_3+is_4;
    if (wmode > 1) {
    if (is_1 && is_3 && (is_2+is_4 == 0)) {
        wmode = WM_X_TLBR;
    } else if (is_2 && is_4 && (is_1+is_3 == 0)) {
        wmode = WM_X_BLTR;
    } else {
#ifdef WA_VERBOSE
        error4(x,y,is_1,is_2,is_3,is_4);
#endif
        wmode = 0;
    }
    } else if (is_1)
    wmode = WM_X_TL;
    else if (is_2)
    wmode = WM_X_TR;
    else if (is_3)
    wmode = WM_X_BR;
    else if (is_4)
    wmode = WM_X_BL;
    return wmode;
}
void set_mimic_blocking ()
Definition at line 1087 of file display.c.
References block_point(), DEADMONSTER, fmon, M_AP_FURNITURE, M_AP_OBJECT, monst::m_ap_type, monst::mappearance, monst::mx, monst::my, monst::nmon, S_hcdoor, S_vcdoor, See_invisible, and unblock_point().
{
    register struct monst *mon;
    for (mon = fmon; mon; mon = mon->nmon) {
    if (DEADMONSTER(mon)) continue;
    if (mon->minvis &&
       ((mon->m_ap_type == M_AP_FURNITURE &&
         (mon->mappearance == S_vcdoor || mon->mappearance ==
      S_hcdoor)) ||
        (mon->m_ap_type == M_AP_OBJECT && mon->mappearance == BOULDER))) {
        if(See_invisible)
        block_point(mon->mx, mon->my);
        else
        unblock_point(mon->mx, mon->my);
    }
    }
}
STATIC_OVL void set_seenv (struct rm * lev, int x0, int y0, int x, int y)
Definition at line 1807 of file display.c.
References rm::seenv, and sign.
Referenced by feel_location().
{
    int dx = x-x0, dy = y0-y;
    lev->seenv |= seenv_matrix[sign(dy)+1][sign(dx)+1];
}
STATIC_OVL int set_twall (int x0, int y0, int x1, int y1, int x2, int y2, int x3, int y3)
Definition at line 1619 of file display.c.
References check_pos(), more_than_one, WM_T_BL, WM_T_BR, and WM_T_LONG.
Referenced by set_wall_state().
{
    int wmode, is_1, is_2, is_3;
    is_1 = check_pos(x1, y1, WM_T_LONG);
    is_2 = check_pos(x2, y2, WM_T_BL);
    is_3 = check_pos(x3, y3, WM_T_BR);
    if (more_than_one(x0, y0, is_1, is_2, is_3)) {
    wmode = 0;
    } else {
    wmode = is_1 + is_2 + is_3;
    }
    return wmode;
}
STATIC_OVL int set_wall (int x, int y, int horiz)
Definition at line 1637 of file display.c.
References check_pos(), more_than_one, WM_W_BOTTOM, WM_W_LEFT, WM_W_RIGHT, and WM_W_TOP.
Referenced by set_wall_state().
{
    int wmode, is_1, is_2;
    if (horiz) {
    is_1 = check_pos(x,y-1, WM_W_TOP);
    is_2 = check_pos(x,y+1, WM_W_BOTTOM);
    } else {
    is_1 = check_pos(x-1,y, WM_W_LEFT);
    is_2 = check_pos(x+1,y, WM_W_RIGHT);
    }
    if (more_than_one(x, y, is_1, is_2, 0)) {
    wmode = 0;
    } else {
    wmode = is_1 + is_2;
    }
    return wmode;
}
void set_wall_state ()
Definition at line 1725 of file display.c.
References BLCORNER, BRCORNER, COLNO, CROSSWALL, HWALL, levl, MAX_TYPE, ROWNO, SDOOR, set_corn(), set_crosswall(), set_twall(), set_wall(), TDWALL, TLCORNER, TLWALL, TRCORNER, TRWALL, TUWALL, rm::typ, VWALL, and WM_MASK.
Referenced by mklev().
{
    int x, y;
    int wmode;
    struct rm *lev;
#ifdef WA_VERBOSE
    for (x = 0; x < MAX_TYPE; x++) bad_count[x] = 0;
#endif
    for (x = 0; x < COLNO; x++)
    for (lev = &levl[x][0], y = 0; y < ROWNO; y++, lev++) {
        switch (lev->typ) {
        case SDOOR:
            wmode = set_wall(x, y, (int) lev->horizontal);
            break;
        case VWALL:
            wmode = set_wall(x, y, 0);
            break;
        case HWALL:
            wmode = set_wall(x, y, 1);
            break;
        case TDWALL:
            wmode = set_twall(x,y, x,y-1, x-1,y+1, x+1,y+1);
            break;
        case TUWALL:
            wmode = set_twall(x,y, x,y+1, x+1,y-1, x-1,y-1);
            break;
        case TLWALL:
            wmode = set_twall(x,y, x+1,y, x-1,y-1, x-1,y+1);
            break;
        case TRWALL:
            wmode = set_twall(x,y, x-1,y, x+1,y+1, x+1,y-1);
            break;
        case TLCORNER:
            wmode = set_corn(x-1,y-1, x,y-1, x-1,y, x+1,y+1);
            break;
        case TRCORNER:
            wmode = set_corn(x,y-1, x+1,y-1, x+1,y, x-1,y+1);
            break;
        case BLCORNER:
            wmode = set_corn(x,y+1, x-1,y+1, x-1,y, x+1,y-1);
            break;
        case BRCORNER:
            wmode = set_corn(x+1,y, x+1,y+1, x,y+1, x-1,y-1);
            break;
        case CROSSWALL:
            wmode = set_crosswall(x, y);
            break;
        default:
            wmode = -1; /* don't set wall info */
            break;
        }
    if (wmode >= 0)
        lev->wall_info = (lev->wall_info & ~WM_MASK) | wmode;
    }
#ifdef WA_VERBOSE
    /* check if any bad positions found */
    for (x = y = 0; x < MAX_TYPE; x++)
    if (bad_count[x]) {
        if (y == 0) {
        y = 1; /* only print once */
        pline("set_wall_type: wall mode problems with: ");
        }
        pline("%s %d;", type_names[x], bad_count[x]);
    }
#endif /* WA_VERBOSE */
}
void shieldeff (xchar x, xchar y)
Definition at line 778 of file display.c.
References cansee, cmap_to_glyph, delay_output, flags, flush_screen(), newsym(), SHIELD_COUNT, shield_static, show_glyph(), and flag::sparkle.
Referenced by cursed_book(), damageum(), explum(), god_zaps_you(), level_tele_trap(), mbhitm(), passive(), rndcurse(), tele_trap(), and use_offensive().
{
    register int i;
    if (!flags.sparkle) return;
    if (cansee(x,y)) { /* Don't see anything if can't see the location */
    for (i = 0; i < SHIELD_COUNT; i++) {
        show_glyph(x, y, cmap_to_glyph(shield_static[i]));
        flush_screen(1); /* make sure the glyph shows up */
        delay_output();
    }
    newsym(x,y); /* restore the old information */
    }
}
void show_glyph (int x, int y, int glyph)
Definition at line 1214 of file display.c.
References gbuf_entry::glyph, GLYPH_BODY_OFF, GLYPH_CMAP_OFF, GLYPH_DETECT_OFF, GLYPH_EXPLODE_OFF, GLYPH_INVIS_OFF, GLYPH_OBJ_OFF, GLYPH_PET_OFF, GLYPH_RIDDEN_OFF, GLYPH_SWALLOW_OFF, GLYPH_WARNING_OFF, GLYPH_ZAP_OFF, MAX_GLYPH, gbuf_entry::new, and offset.
Referenced by detect_wsegs(), display_monster(), display_warning(), docrt(), feel_location(), magic_map_background(), map_background(), map_invisible(), map_object(), map_trap(), monster_detect(), newsym(), shieldeff(), show_region(), swallowed(), tmp_at(), under_water(), and you_aggravate().
{
    /*
     * Check for bad positions and glyphs.
     */
    if (!isok(x, y)) {
    const char *text;
    int offset;
    /* column 0 is invalid, but it's often used as a flag, so ignore it */
    if (x == 0) return;
    /*
     * This assumes an ordering of the offsets. See display.h for
     * the definition.
     */
    if (glyph >= GLYPH_WARNING_OFF) { /* a warning */
        text = "warning"; offset = glyph - GLYPH_WARNING_OFF;
    } else if (glyph >= GLYPH_SWALLOW_OFF) { /* swallow border */
        text = "swallow border"; offset = glyph - GLYPH_SWALLOW_OFF;
    } else if (glyph >= GLYPH_ZAP_OFF) { /* zap beam */
        text = "zap beam"; offset = glyph - GLYPH_ZAP_OFF;
    } else if (glyph >= GLYPH_EXPLODE_OFF) { /* explosion */
        text = "explosion"; offset = glyph - GLYPH_EXPLODE_OFF;
    } else if (glyph >= GLYPH_CMAP_OFF) { /* cmap */
        text = "cmap_index"; offset = glyph - GLYPH_CMAP_OFF;
    } else if (glyph >= GLYPH_OBJ_OFF) { /* object */
        text = "object"; offset = glyph - GLYPH_OBJ_OFF;
    } else if (glyph >= GLYPH_RIDDEN_OFF) { /* ridden mon */
        text = "ridden mon"; offset = glyph - GLYPH_RIDDEN_OFF;
    } else if (glyph >= GLYPH_BODY_OFF) { /* a corpse */
        text = "corpse"; offset = glyph - GLYPH_BODY_OFF;
    } else if (glyph >= GLYPH_DETECT_OFF) { /* detected mon */
        text = "detected mon"; offset = glyph - GLYPH_DETECT_OFF;
    } else if (glyph >= GLYPH_INVIS_OFF) { /* invisible mon */
        text = "invisible mon"; offset = glyph - GLYPH_INVIS_OFF;
    } else if (glyph >= GLYPH_PET_OFF) { /* a pet */
        text = "pet"; offset = glyph - GLYPH_PET_OFF;
    } else { /* a monster */
        text = "monster"; offset = glyph;
    }
    impossible("show_glyph: bad pos %d %d with glyph %d [%s %d].",
                        x, y, glyph, text, offset);
    return;
    }
    if (glyph >= MAX_GLYPH) {
    impossible("show_glyph: bad glyph %d [max %d] at (%d,%d).",
                    glyph, MAX_GLYPH, x, y);
    return;
    }
    if (gbuf[y][x].glyph != glyph) {
    gbuf[y][x].glyph = glyph;
    gbuf[y][x].new = 1;
    if (gbuf_start[y] > x) gbuf_start[y] = x;
    if (gbuf_stop[y] < x) gbuf_stop[y] = x;
    }
}
STATIC_OVL int swallow_to_glyph (int mnum, int loc)
Definition at line 1486 of file display.c.
References GLYPH_SWALLOW_OFF, S_sw_br, S_sw_tl, and what_mon.
Referenced by swallowed().
{
    if (loc < S_sw_tl || S_sw_br < loc) {
    impossible("swallow_to_glyph: bad swallow location");
    loc = S_sw_br;
    }
    return ((int) (what_mon(mnum)<<3) | (loc - S_sw_tl)) +
      GLYPH_SWALLOW_OFF;
}
void swallowed (int first)
Definition at line 921 of file display.c.
References cls(), cmap_to_glyph, monst::data, display_self, S_stone, S_sw_bc, S_sw_bl, S_sw_br, S_sw_ml, S_sw_mr, S_sw_tc, S_sw_tl, S_sw_tr, show_glyph(), swallow_to_glyph(), u, you::ustuck, you::ux, and you::uy.
Referenced by docrt().
{
    static xchar lastx, lasty; /* last swallowed position */
    int swallower, left_ok, rght_ok;
    if (first)
    cls();
    else {
    register int x, y;
    /* Clear old location */
    for (y = lasty-1; y <= lasty+1; y++)
        for (x = lastx-1; x <= lastx+1; x++)
        if (isok(x,y)) show_glyph(x,y,cmap_to_glyph(
      S_stone));
    }
    swallower = monsndx(u.ustuck->data);
    /* assume isok(u.ux,u.uy) */
    left_ok = isok(u.ux-1,u.uy);
    rght_ok = isok(u.ux+1,u.uy);
    /*
     * Display the hero surrounded by the monster's stomach.
     */
    if(isok(u.ux, u.uy-1)) {
    if (left_ok)
    show_glyph(u.ux-1, u.uy-1, swallow_to_glyph(swallower,
      S_sw_tl));
    show_glyph(u.ux , u.uy-1, swallow_to_glyph(swallower,
      S_sw_tc));
    if (rght_ok)
    show_glyph(u.ux+1, u.uy-1, swallow_to_glyph(swallower,
      S_sw_tr));
    }
    if (left_ok)
    show_glyph(u.ux-1, u.uy , swallow_to_glyph(swallower,
      S_sw_ml));
    display_self();
    if (rght_ok)
    show_glyph(u.ux+1, u.uy , swallow_to_glyph(swallower,
      S_sw_mr));
    if(isok(u.ux, u.uy+1)) {
    if (left_ok)
    show_glyph(u.ux-1, u.uy+1, swallow_to_glyph(swallower,
      S_sw_bl));
    show_glyph(u.ux , u.uy+1, swallow_to_glyph(swallower,
      S_sw_bc));
    if (rght_ok)
    show_glyph(u.ux+1, u.uy+1, swallow_to_glyph(swallower,
      S_sw_br));
    }
    /* Update the swallowed position. */
    lastx = u.ux;
    lasty = u.uy;
}
STATIC_OVL void t_warn (struct rm * lev)
Definition at line 1874 of file display.c.
References TDWALL, TLWALL, TRWALL, TUWALL, and WM_MASK.
Referenced by wall_angle().
{
    static const char warn_str[] = "wall_angle: %s: case %d: seenv = 0x%x";
    const char *wname;
    if (lev->typ == TUWALL) wname = "tuwall";
    else if (lev->typ == TLWALL) wname = "tlwall";
    else if (lev->typ == TRWALL) wname = "trwall";
    else if (lev->typ == TDWALL) wname = "tdwall";
    else wname = "unknown";
    impossible(warn_str, wname, lev->wall_info & WM_MASK,
    (unsigned int) lev->seenv);
}
void tmp_at (int x, int y)
Definition at line 829 of file display.c.
References alloc(), cansee, DISP_ALWAYS, DISP_BEAM, DISP_CHANGE, DISP_END, DISP_FLASH, DISP_FREEMEM, flush_screen(), free(), tmp_glyph::glyph, newsym(), panic(), tmp_glyph::prev, tmp_glyph::saved, show_glyph(), tmp_glyph::sidx, tmp_glyph::style, tgfirst, coord::x, and coord::y.
Referenced by end_engulf(), freedynamicdata(), sho_obj_return_to_u(), start_engulf(), and throwit().
{
    static struct tmp_glyph *tglyph = (struct tmp_glyph *)0;
    struct tmp_glyph *tmp;
    switch (x) {
    case DISP_BEAM:
    case DISP_FLASH:
    case DISP_ALWAYS:
        if (!tglyph)
        tmp = &tgfirst;
        else /* nested effect; we need dynamic memory */
        tmp = (struct tmp_glyph *)alloc(sizeof (struct tmp_glyph));
        tmp->prev = tglyph;
        tglyph = tmp;
        tglyph->sidx = 0;
        tglyph->style = x;
        tglyph->glyph = y;
        flush_screen(0); /* flush buffered glyphs */
        return;
    case DISP_FREEMEM: /* in case game ends with tmp_at() in progress */
        while (tglyph) {
        tmp = tglyph->prev;
        if (tglyph != &tgfirst) free((genericptr_t)tglyph);
        tglyph = tmp;
        }
        return;
    default:
        break;
    }
    if (!tglyph) panic("tmp_at: tglyph not initialized");
    switch (x) {
    case DISP_CHANGE:
        tglyph->glyph = y;
        break;
    case DISP_END:
        if (tglyph->style == DISP_BEAM) {
        register int i;
        /* Erase (reset) from source to end */
        for (i = 0; i < tglyph->sidx; i++)
            newsym(tglyph->saved[i].x, tglyph->saved[i].y);
        } else { /* DISP_FLASH or DISP_ALWAYS */
        if (tglyph->sidx) /* been called at least once */
            newsym(tglyph->saved[0].x, tglyph->saved[0].y);
        }
     /* tglyph->sidx = 0; -- about to be freed, so not necessary */
        tmp = tglyph->prev;
        if (tglyph != &tgfirst) free((genericptr_t)tglyph);
        tglyph = tmp;
        break;
    default: /* do it */
        if (tglyph->style == DISP_BEAM) {
        if (!cansee(x,y)) break;
        /* save pos for later erasing */
        tglyph->saved[tglyph->sidx].x = x;
        tglyph->saved[tglyph->sidx].y = y;
        tglyph->sidx += 1;
        } else { /* DISP_FLASH/ALWAYS */
        if (tglyph->sidx) { /* not first call, so reset previous pos */
            newsym(tglyph->saved[0].x, tglyph->saved[0].y);
            tglyph->sidx = 0; /* display is presently up to date */
        }
        if (!cansee(x,y) && tglyph->style != DISP_ALWAYS) break;
        tglyph->saved[0].x = x;
        tglyph->saved[0].y = y;
        tglyph->sidx = 1;
        }
        show_glyph(x, y, tglyph->glyph); /* show it */
        flush_screen(0); /* make sure it shows up */
        break;
    } /* end case */
}
void under_ground (int mode)
Definition at line 1024 of file display.c.
References cls(), FALSE, newsym(), TRUE, u, you::ux, and you::uy.
Referenced by docrt(), food_detect(), gold_detect(), monster_detect(), object_detect(), and trap_detect().
{
    static boolean dela;
    /* swallowing has a higher precedence than under ground */
    if (u.uswallow) return;
    /* full update */
    if (mode == 1 || dela) {
    cls();
    dela = FALSE;
    }
    /* delayed full update */
    else if (mode == 2) {
    dela = TRUE;
    return;
    }
    /* limited update */
    else
    newsym(u.ux,u.uy);
}
void under_water (int mode)
Definition at line 979 of file display.c.
References Blind, cls(), cmap_to_glyph, FALSE, Is_waterlevel, newsym(), S_stone, show_glyph(), TRUE, u, you::ux, you::uy, and you::uz.
Referenced by docrt(), food_detect(), gold_detect(), monster_detect(), object_detect(), and trap_detect().
{
    static xchar lastx, lasty;
    static boolean dela;
    register int x, y;
    /* swallowing has a higher precedence than under water */
    if (Is_waterlevel(&u.uz) || u.uswallow) return;
    /* full update */
    if (mode == 1 || dela) {
    cls();
    dela = FALSE;
    }
    /* delayed full update */
    else if (mode == 2) {
    dela = TRUE;
    return;
    }
    /* limited update */
    else {
    for (y = lasty-1; y <= lasty+1; y++)
        for (x = lastx-1; x <= lastx+1; x++)
        if (isok(x,y))
            show_glyph(x,y,cmap_to_glyph(S_stone));
    }
    for (x = u.ux-1; x <= u.ux+1; x++)
    for (y = u.uy-1; y <= u.uy+1; y++)
        if (isok(x,y) && is_pool(x,y)) {
        if (Blind && !(x == u.ux && y == u.uy))
            show_glyph(x,y,cmap_to_glyph(S_stone));
        else
            newsym(x,y);
        }
    lastx = u.ux;
    lasty = u.uy;
}
void unmap_object (int x, int y)
Definition at line 292 of file display.c.
References cmap_to_glyph, covers_traps, dlevel_t::flags, rm::glyph, level, levl, map_background(), map_trap(), ROOM, S_room, S_stone, and rm::typ.
Referenced by clear_stale_map(), dokick(), dosearch0(), findone(), and kick_monster().
{
    register struct trap *trap;
    if (!level.flags.hero_memory) return;
    if ((trap = t_at(x,y)) != 0 && trap->tseen && !covers_traps(x,
      y))
    map_trap(trap, 0);
    else if (levl[x][y].seenv) {
    struct rm *lev = &levl[x][y];
    map_background(x, y, 0);
    /* turn remembered dark room squares dark */
    if (!lev->waslit && lev->glyph == cmap_to_glyph(S_room) &&
                                lev->typ == ROOM)
        lev->glyph = cmap_to_glyph(S_stone);
    } else
    levl[x][y].glyph = cmap_to_glyph(S_stone); /* default val */
}
STATIC_OVL int wall_angle (struct rm * lev)
Definition at line 1903 of file display.c.
References BLCORNER, BRCORNER, C_bl, C_blcorn, C_br, C_brcorn, C_crwall, C_tl, C_tlwall, C_tr, C_trcorn, C_tuwall, CROSSWALL, HWALL, only, S_blcorn, S_brcorn, S_crwall, S_hwall, S_stone, S_tdwall, S_tlcorn, S_tlwall, S_trcorn, S_trwall, S_tuwall, S_vwall, SDOOR, rm::seenv, set_corner, SV0, SV1, SV2, SV3, SV4, SV5, SV6, SV7, T_d, T_hwall, T_l, T_r, T_stone, T_tdwall, T_tlcorn, T_trcorn, T_u, t_warn(), TDWALL, TLCORNER, TLWALL, TRCORNER, TRWALL, TUWALL, VWALL, WM_MASK, WM_T_BL, WM_T_BR, WM_T_LONG, WM_X_BL, WM_X_BLTR, WM_X_BR, WM_X_TL, WM_X_TLBR, and WM_X_TR.
Referenced by back_to_glyph().
{
    register unsigned int seenv = lev->seenv & 0xff;
    const int *row;
    int col, idx;
#define only(sv, bits) (((sv) & (bits)) && ! ((sv) & ~(bits)))
    switch (lev->typ) {
    case TUWALL:
        row = wall_matrix[T_u];
        seenv = (seenv >> 4 | seenv << 4) & 0xff;/* rotate to tdwall */
        goto do_twall;
    case TLWALL:
        row = wall_matrix[T_l];
        seenv = (seenv >> 2 | seenv << 6) & 0xff;/* rotate to tdwall */
        goto do_twall;
    case TRWALL:
        row = wall_matrix[T_r];
        seenv = (seenv >> 6 | seenv << 2) & 0xff;/* rotate to tdwall */
        goto do_twall;
    case TDWALL:
        row = wall_matrix[T_d];
do_twall:
        switch (lev->wall_info & WM_MASK) {
            case 0:
            if (seenv == SV4) {
                col = T_tlcorn;
            } else if (seenv == SV6) {
                col = T_trcorn;
            } else if (seenv & (SV3|SV5|SV7) ||
                        ((seenv & SV4) && (seenv & SV6))) {
                col = T_tdwall;
            } else if (seenv & (SV0|SV1|SV2)) {
                col = (seenv & (SV4|SV6) ? T_tdwall : T_hwall);
            } else {
                t_warn(lev);
                col = T_stone;
            }
            break;
            case WM_T_LONG:
            if (seenv & (SV3|SV4) && !(seenv & (SV5|SV6|SV7))) {
                col = T_tlcorn;
            } else if (seenv&(SV6|SV7) && !(seenv&(SV3|SV4|SV5))) {
                col = T_trcorn;
            } else if ((seenv & SV5) ||
                ((seenv & (SV3|SV4)) && (seenv & (SV6|SV7)))) {
                col = T_tdwall;
            } else {
                /* only SV0|SV1|SV2 */
                if (! only(seenv, SV0|SV1|SV2))
                t_warn(lev);
                col = T_stone;
            }
            break;
            case WM_T_BL:
#if 0 /* older method, fixed */
            if (only(seenv, SV4|SV5)) {
                col = T_tlcorn;
            } else if ((seenv & (SV0|SV1|SV2)) &&
                    only(seenv, SV0|SV1|SV2|SV6|SV7)) {
                col = T_hwall;
            } else if (seenv & SV3 ||
                ((seenv & (SV0|SV1|SV2)) && (seenv & (SV4|SV5)))) {
                col = T_tdwall;
            } else {
                if (seenv != SV6)
                t_warn(lev);
                col = T_stone;
            }
#endif /* 0 */
            if (only(seenv, SV4|SV5))
                col = T_tlcorn;
            else if ((seenv & (SV0|SV1|SV2|SV7)) &&
                    !(seenv & (SV3|SV4|SV5)))
                col = T_hwall;
            else if (only(seenv, SV6))
                col = T_stone;
            else
                col = T_tdwall;
            break;
            case WM_T_BR:
#if 0 /* older method, fixed */
            if (only(seenv, SV5|SV6)) {
                col = T_trcorn;
            } else if ((seenv & (SV0|SV1|SV2)) &&
                        only(seenv, SV0|SV1|SV2|SV3|SV4)) {
                col = T_hwall;
            } else if (seenv & SV7 ||
                ((seenv & (SV0|SV1|SV2)) && (seenv & (SV5|SV6)))) {
                col = T_tdwall;
            } else {
                if (seenv != SV4)
                t_warn(lev);
                col = T_stone;
            }
#endif /* 0 */
            if (only(seenv, SV5|SV6))
                col = T_trcorn;
            else if ((seenv & (SV0|SV1|SV2|SV3)) &&
                    !(seenv & (SV5|SV6|SV7)))
                col = T_hwall;
            else if (only(seenv, SV4))
                col = T_stone;
            else
                col = T_tdwall;
            break;
            default:
            impossible("wall_angle: unknown T wall mode %d",
                lev->wall_info & WM_MASK);
            col = T_stone;
            break;
        }
        idx = row[col];
        break;
    case SDOOR:
        if (lev->horizontal) goto horiz;
        /* fall through */
    case VWALL:
        switch (lev->wall_info & WM_MASK) {
            case 0: idx = seenv ? S_vwall : S_stone; break;
            case 1: idx = seenv & (SV1|SV2|SV3|SV4|SV5) ? S_vwall :
                                  S_stone;
                break;
            case 2: idx = seenv & (SV0|SV1|SV5|SV6|SV7) ? S_vwall :
                                  S_stone;
                break;
            default:
            impossible("wall_angle: unknown vwall mode %d",
                lev->wall_info & WM_MASK);
            idx = S_stone;
            break;
        }
        break;
    case HWALL:
horiz:
        switch (lev->wall_info & WM_MASK) {
            case 0: idx = seenv ? S_hwall : S_stone; break;
            case 1: idx = seenv & (SV3|SV4|SV5|SV6|SV7) ? S_hwall :
                                  S_stone;
                break;
            case 2: idx = seenv & (SV0|SV1|SV2|SV3|SV7) ? S_hwall :
                                  S_stone;
                break;
            default:
            impossible("wall_angle: unknown hwall mode %d",
                lev->wall_info & WM_MASK);
            idx = S_stone;
            break;
        }
        break;
#define set_corner(idx, lev, which, outer, inner, name) \
    switch ((lev)->wall_info & WM_MASK) { \
    case 0: idx = which; break; \
    case WM_C_OUTER: idx = seenv & (outer) ? which : S_stone; break; \
    case WM_C_INNER: idx = seenv & ~(inner) ? which : S_stone; break; \
    default: \
        impossible("wall_angle: unknown %s mode %d", name, \
        (lev)->wall_info & WM_MASK); \
        idx = S_stone; \
        break; \
    }
    case TLCORNER:
        set_corner(idx, lev, S_tlcorn, (SV3|SV4|SV5),
      SV4, "tlcorn");
        break;
    case TRCORNER:
        set_corner(idx, lev, S_trcorn, (SV5|SV6|SV7), SV6, "trcorn");
        break;
    case BLCORNER:
        set_corner(idx, lev, S_blcorn, (SV1|SV2|SV3),
      SV2, "blcorn");
        break;
    case BRCORNER:
        set_corner(idx, lev, S_brcorn, (SV7|SV0|SV1),
      SV0, "brcorn");
        break;
    case CROSSWALL:
        switch (lev->wall_info & WM_MASK) {
            case 0:
            if (seenv == SV0)
                idx = S_brcorn;
            else if (seenv == SV2)
                idx = S_blcorn;
            else if (seenv == SV4)
                idx = S_tlcorn;
            else if (seenv == SV6)
                idx = S_trcorn;
            else if (!(seenv & ~(SV0|SV1|SV2)) &&
                    (seenv & SV1 || seenv == (SV0|SV2)))
                idx = S_tuwall;
            else if (!(seenv & ~(SV2|SV3|SV4)) &&
                    (seenv & SV3 || seenv == (SV2|SV4)))
                idx = S_trwall;
            else if (!(seenv & ~(SV4|SV5|SV6)) &&
                    (seenv & SV5 || seenv == (SV4|SV6)))
                idx = S_tdwall;
            else if (!(seenv & ~(SV0|SV6|SV7)) &&
                    (seenv & SV7 || seenv == (SV0|SV6)))
                idx = S_tlwall;
            else
                idx = S_crwall;
            break;
            case WM_X_TL:
            row = cross_matrix[C_tl];
            seenv = (seenv >> 4 | seenv << 4) & 0xff;
            goto do_crwall;
            case WM_X_TR:
            row = cross_matrix[C_tr];
            seenv = (seenv >> 6 | seenv << 2) & 0xff;
            goto do_crwall;
            case WM_X_BL:
            row = cross_matrix[C_bl];
            seenv = (seenv >> 2 | seenv << 6) & 0xff;
            goto do_crwall;
            case WM_X_BR:
            row = cross_matrix[C_br];
do_crwall:
            if (seenv == SV4)
                idx = S_stone;
            else {
                seenv = seenv & ~SV4; /* strip SV4 */
                if (seenv == SV0) {
                col = C_brcorn;
                } else if (seenv & (SV2|SV3)) {
                if (seenv & (SV5|SV6|SV7))
                    col = C_crwall;
                else if (seenv & (SV0|SV1))
                    col = C_tuwall;
                else
                    col = C_blcorn;
                } else if (seenv & (SV5|SV6)) {
                if (seenv & (SV1|SV2|SV3))
                    col = C_crwall;
                else if (seenv & (SV0|SV7))
                    col = C_tlwall;
                else
                    col = C_trcorn;
                } else if (seenv & SV1) {
                col = seenv & SV7 ? C_crwall : C_tuwall;
                } else if (seenv & SV7) {
                col = seenv & SV1 ? C_crwall : C_tlwall;
                } else {
                impossible(
                    "wall_angle: bottom of crwall check");
                col = C_crwall;
                }
                idx = row[col];
            }
            break;
            case WM_X_TLBR:
            if (only(seenv, SV1|SV2|SV3))
                idx = S_blcorn;
            else if (only(seenv, SV5|SV6|SV7))
                idx = S_trcorn;
            else if (only(seenv, SV0|SV4))
                idx = S_stone;
            else
                idx = S_crwall;
            break;
            case WM_X_BLTR:
            if (only(seenv, SV0|SV1|SV7))
                idx = S_brcorn;
            else if (only(seenv, SV3|SV4|SV5))
                idx = S_tlcorn;
            else if (only(seenv, SV2|SV6))
                idx = S_stone;
            else
                idx = S_crwall;
            break;
            default:
            impossible("wall_angle: unknown crosswall mode");
            idx = S_stone;
            break;
        }
        break;
    default:
        impossible("wall_angle: unexpected wall type %d", lev->typ);
        idx = S_stone;
    }
    return idx;
}
int zapdir_to_glyph (int dx, int dy, int beam_type)
Definition at line 1512 of file display.c.
References GLYPH_ZAP_OFF, and NUM_ZAP.
{
    if (beam_type >= NUM_ZAP) {
    impossible("zapdir_to_glyph: illegal beam type");
    beam_type = 0;
    }
    dx = (dx == dy) ? 2 : (dx && dy) ? 3 : dx ? 1 : 0;
    return ((int) ((beam_type << 2) | dx)) + GLYPH_ZAP_OFF;
}
Variable Documentation
const int cross_matrix[4][6] [static]
Initial value:
= {
    { S_brcorn, S_blcorn, S_tlcorn, S_tuwall,
      S_trwall, S_crwall },
    { S_blcorn, S_tlcorn, S_trcorn, S_trwall,
      S_tdwall, S_crwall },
    { S_tlcorn, S_trcorn, S_brcorn, S_tdwall,
      S_tlwall, S_crwall },
    { S_trcorn, S_brcorn, S_blcorn, S_tlwall,
      S_tuwall, S_crwall },
}
Definition at line 1864 of file display.c.
gbuf_entry gbuf[ROWNO][COLNO] [static]
Definition at line 1206 of file display.c.
char gbuf_start[ROWNO] [static]
Definition at line 1207 of file display.c.
char gbuf_stop[ROWNO] [static]
Definition at line 1208 of file display.c.
gbuf_entry nul_gbuf = { 0, cmap_to_glyph(S_stone) } [static]
Definition at line 1293 of file display.c.
Referenced by clear_glyph_buffer().
unsigned char seenv_matrix[3][3]
Initial value:
= { {SV2, SV1, SV0},
                     {SV3, SVALL, SV7},
                     {SV4, SV5, SV6} }
Definition at line 1799 of file display.c.
Referenced by vision_recalc().
struct tmp_glyph tgfirst [static]
Referenced by tmp_at().
const int wall_matrix[4][5] [static]
Initial value:
= {
    { S_stone, S_tlcorn, S_trcorn, S_hwall,
      S_tdwall },
    { S_stone, S_trcorn, S_brcorn, S_vwall,
      S_tlwall },
    { S_stone, S_brcorn, S_blcorn, S_hwall,
      S_tuwall },
    { S_stone, S_blcorn, S_tlcorn, S_vwall,
      S_trwall },
}
Definition at line 1836 of file display.c.