nethack/util/dlb_main.c File Reference
#include `config.h`
*
#include `dlb.h`
*
#include <fcntl.h>
*
Functions
static void FDECL (xexit,(int))
int main (int argc, char **argv)
static void xexit (int retcd)
Function Documentation
static void FDECL (xexit , (int)) [static]
int main (int argc, char ** argv)
Definition at line 179 of file dlb_main.c.
References alloc(), BUFSIZ, chdir(), close(), eos(), EXIT_FAILURE, EXIT_SUCCESS, FALSE, FCMASK, FILENAME_CMP, fname, free(), getcwd(), lseek(), O_BINARY, O_CREAT, O_RDONLY, O_RDWR, O_TRUNC, O_WRONLY, open(), printf, read(), SEEK_END, SEEK_SET, Strcpy, TRUE, vms_basename(), write(), and xexit().
{
#ifdef DLB
#ifdef DLBLIB
    int i, r;
    int ap=2; /* argument pointer */
    int cp; /* command pointer */
    int iseen=0, fseen=0, verbose=0; /* flags */
    char action=' ';
    library lib;
    if (argc > 0 && argv[0] && *argv[0]) progname = argv[0];
#ifdef VMS
    progname = vms_basename(progname);
#endif
    if (argc<2) {
    usage();
    /* doesn't return */
    }
    for(cp=0;argv[1][cp];cp++){
    switch(argv[1][cp]){
        default:
        usage(); /* doesn't return */
        case '-': /* silently ignore */
        break;
        case '?':
        case 'h':
        verbose_help();
        break;
        case 'I':
        if (ap == argc) usage();
        list_file=argv[ap++];
        if(iseen)
            printf("Warning: multiple I options. Previous ignored.\n");
        iseen=1;
        break;
        case 'f':
        if (ap == argc) usage();
        library_file=argv[ap++];
        if(fseen)
            printf("Warning: multiple f options. Previous ignored.\n");
        fseen=1;
        break;
        case 'C':
        if (ap == argc) usage();
#ifdef AMIGA
        if(!getcwd(origdir,sizeof(origdir))){
            printf("Can't get current directory.\n");
            xexit(EXIT_FAILURE);
        }
#endif
        if(chdir(argv[ap++])){
            printf("Can't chdir to %s\n",argv[--ap]);
            xexit(EXIT_FAILURE);
        }
        break;
        case 'v':
        verbose=1;
        break;
        case 't':
        case 'c':
        case 'x':
        if(action != ' '){
            printf("Only one of t,x,c may be specified.\n");
            usage();
        }
        action=argv[1][cp];
        break;
    }
    }
    if(argv[ap] && iseen){
    printf("Too many arguments.\n");
    xexit(EXIT_FAILURE);
    }
    switch(action){
    default:
    printf("Internal error - action.\n");
    xexit(EXIT_FAILURE);
    break;
    case 't': /* list archive */
    if (!open_library(library_file, &lib)) {
        printf("Can't open dlb file\n");
        xexit(EXIT_FAILURE);
    }
    for (i = 0; i < lib.nentries; i++) {
        if (verbose)
        printf("%-14s %6ld %6ld\n",
            lib.dir[i].fname, lib.dir[i].foffset, lib.dir[i].fsize);
        else
        printf("%s\n", lib.dir[i].fname);
    }
    if (verbose)
        printf("Revision:%ld File count:%ld String size:%ld\n",
        lib.rev, lib.nentries, lib.strsize);
    close_library(&lib);
    xexit(EXIT_SUCCESS);
    case 'x': { /* extract archive contents */
    int f, n;
    long remainder, total_read;
    char buf[BUFSIZ];
    if (!open_library(library_file, &lib)) {
        printf("Can't open dlb file\n");
        xexit(EXIT_FAILURE);
    }
    for (i = 0; i < lib.nentries; i++) {
        if (argv[ap]) {
        /* if files are listed, see if current is wanted */
        int c;
        for (c = ap; c < argc; c++)
            if (!FILENAME_CMP(lib.dir[i].fname, argv[c])) break;
        if (c == argc) continue; /* skip */
        } else if (!FILENAME_CMP(lib.dir[i].fname, DLB_DIRECTORY)) {
        /*
         * Don't extract the directory unless the user
         * specifically asks for it.
         *
         * Perhaps we should never extract the directory???
         */
        continue;
        }
        fseek(lib.fdata, lib.dir[i].foffset, SEEK_SET);
        f = open(lib.dir[i].fname, O_WRONLY|O_TRUNC|O_BINARY|
      O_CREAT, 0640);
        if (f < 0) {
        printf("Can't create '%s'\n", lib.dir[i].fname);
        xexit(EXIT_FAILURE);
        }
        /* read chunks from library and write them out */
        total_read = 0;
        do {
        remainder = lib.dir[i].fsize - total_read;
        if (remainder > (long) sizeof(buf))
            r = (int) sizeof(buf);
        else
            r = remainder;
        n = fread(buf, 1, r, lib.fdata);
        if (n != r) {
            printf("Read Error in '%s'\n", lib.dir[i].fname);
            xexit(EXIT_FAILURE);
        }
        if (write(f, buf, n) != n) {
            printf("Write Error in '%s'\n", lib.dir[i].fname);
            xexit(EXIT_FAILURE);
        }
        total_read += n;
        } while (total_read != lib.dir[i].fsize);
        (void) close(f);
        if (verbose) printf("x %s\n", lib.dir[i].fname);
    }
    close_library(&lib);
    xexit(EXIT_SUCCESS);
    }
    case 'c': /* create archive */
    {
    libdir ld[MAX_DLB_FILES];
    char buf[BUFSIZ];
    int fd, out, nfiles = 0;
    long dir_size, slen, flen, fsiz;
    boolean rewrite_directory = FALSE;
    /*
     * Get names from either/both an argv list and a file
     * list. This does not do any duplicate checking
     */
    /* get file name in argv list */
    if (argv[ap]) {
        for (; ap < argc; ap++, nfiles++) {
        if (nfiles >= MAX_DLB_FILES) {
            printf("Too many dlb files! Stopping at %d.\n",
                                MAX_DLB_FILES);
            break;
        }
        ld[nfiles].fname = (char *) alloc(strlen(argv[ap]) + 1);
        Strcpy(ld[nfiles].fname, argv[ap]);
        }
    }
    if (iseen) {
        /* want to do a list file */
        FILE *list = fopen(list_file, "r");
        if (!list) {
        printf("Can't open %s\n",list_file);
        xexit(EXIT_FAILURE);
        }
        /* get file names, one per line */
        for (; fgets(buf, sizeof(buf), list); nfiles++) {
        if (nfiles >= MAX_DLB_FILES) {
            printf("Too many dlb files! Stopping at %d.\n",
                                MAX_DLB_FILES);
            break;
        }
        *(eos(buf)-1) = '\0'; /* strip newline */
        ld[nfiles].fname = (char *) alloc(strlen(buf) + 1);
        Strcpy(ld[nfiles].fname, buf);
        }
        fclose(list);
    }
    if (nfiles == 0) {
        printf("No files to archive\n");
        xexit(EXIT_FAILURE);
    }
    /*
     * Get file sizes and name string length. Don't include
     * the directory information yet.
     */
    for (i = 0, slen = 0, flen = 0; i < nfiles; i++) {
        fd = open(ld[i].fname, O_RDONLY|O_BINARY, 0);
        if (fd < 0) {
        printf("Can't open %s\n", ld[i].fname);
        xexit(EXIT_FAILURE);
        }
        ld[i].fsize = lseek(fd, 0, SEEK_END);
        ld[i].foffset = flen;
        slen += strlen(ld[i].fname); /* don't add null (yet) */
        flen += ld[i].fsize;
        close(fd);
    }
    /* open output file */
    out = open(library_file, O_RDWR|O_TRUNC|O_BINARY|
      O_CREAT, FCMASK);
    if (out < 0) {
        printf("Can't open %s for output\n", library_file);
        xexit(EXIT_FAILURE);
    }
    /* caculate directory size */
    dir_size = 40 /* header line (see below) */
           + ((nfiles+1)*11) /* handling+file offset+SP+newline */
           + slen+strlen(DLB_DIRECTORY); /* file names */
    /* write directory */
    write_dlb_directory(out, nfiles, ld, slen, dir_size, flen);
    flen = 0L;
    /* write each file */
    for (i = 0; i < nfiles; i++) {
        fd = open(ld[i].fname, O_RDONLY|O_BINARY, 0);
        if (fd < 0) {
        printf("Can't open input file '%s'\n", ld[i].fname);
        xexit(EXIT_FAILURE);
        }
        if (verbose) printf("%s\n",ld[i].fname);
        fsiz = 0L;
        while ((r = read(fd, buf, sizeof buf)) != 0) {
        if (r == -1) {
            printf("Read Error in '%s'\n", ld[i].fname);
            xexit(EXIT_FAILURE);
        }
        if (write(out, buf, r) != r) {
            printf("Write Error in '%s'\n", ld[i].fname);
            xexit(EXIT_FAILURE);
        }
        fsiz += r;
        }
        (void) close(fd);
        if (fsiz != ld[i].fsize) rewrite_directory = TRUE;
        /* in case directory rewrite is needed */
        ld[i].fsize = fsiz;
        ld[i].foffset = flen;
        flen += fsiz;
    }
    if (rewrite_directory) {
        if (verbose) printf("(rewriting dlb directory info)\n");
        (void) lseek(out, 0, SEEK_SET); /* rewind */
        write_dlb_directory(out, nfiles, ld, slen, dir_size, flen);
    }
    for (i = 0; i < nfiles; i++)
        free((genericptr_t) ld[i].fname), ld[i].fname = 0;
    (void) close(out);
    xexit(EXIT_SUCCESS);
    }
    }
#endif /* DLBLIB */
#endif /* DLB */
    xexit(EXIT_SUCCESS);
    /*NOTREACHED*/
    return 0;
}
static void xexit (int retcd) [static]
Definition at line 526 of file dlb_main.c.
References chdir(), and exit().
Referenced by main().
{
#ifdef DLB
#ifdef AMIGA
    if (origdir[0]) chdir(origdir);
#endif
#endif
    exit(retcd);
}