nethack/sys/mac/dprintf.c File Reference
#include `hack.h`
*
#include `macwin.h`
*
Macros
#define DO_DEBUGSTR 1
#define DO_PLINE 2
Functions
static Boolean KeyDown (unsigned short code)
void dprintf (char *format,...)
Macro Definition Documentation
#define DO_DEBUGSTR 1
Referenced by dprintf().
#define DO_PLINE 2
Referenced by dprintf().
Function Documentation
void dprintf (char * format, ...)
Definition at line 18 of file dprintf.c.
References flag::debug, DO_DEBUGSTR, DO_PLINE, flags, iflags, NhWindow::its_window, KeyDown(), macFlags, theWindows, WIN_MESSAGE, and instance_flags::window_inited.
Referenced by _mt_init_stuff(), allocate_offscreen_world(), force_tty_coordinate_system_recalc(), GetWinKind(), mac_create_nhwindow(), RetrievePosition(), SavePosition(), and SaveSize().
{
char buffer [500];
va_list list;
int doit;
#define DO_DEBUGSTR 1
#define DO_PLINE 2
    if (flags.debug) {
        doit = 0;
        if (macFlags.hasDebugger && KeyDown (0x39)) { /* Caps Lock */
            doit = DO_DEBUGSTR;
        } else if (KeyDown (0x3B) && iflags.window_inited && /* Control
      */
            (WIN_MESSAGE != -1) && theWindows [WIN_MESSAGE].
      its_window) {
            doit = DO_PLINE;
        }
        
        if (doit) {
            va_start (list, format);
            vsprintf (&buffer [1], format, list);
            va_end (list) ;
            if (doit == DO_DEBUGSTR) {
                buffer [0] = strlen (&buffer [1]);
                DebugStr ((uchar *) buffer);
            } else if (doit == DO_PLINE)
                pline ("%s", &buffer [1]);
        }
    }
}
static Boolean KeyDown (unsigned short code) [static]
Definition at line 9 of file dprintf.c.
Referenced by dprintf().
                              {
unsigned char keys [16];
    GetKeys ((void *) keys);
    return ((keys [code >> 3] >> (code & 7)) & 1) != 0;
}