nethack/src/drawing.c File Reference
#include `hack.h`
*
#include `tcap.h`
*
Macros
#define C(n)
#define g_FILLER(symbol) 0
Functions
int def_char_to_objclass (char ch)
int def_char_to_monclass (char ch)
void assign_graphics (uchar *graph_chars, int glth, int maxlen, int offset)
void switch_graphics (int gr_set_flag)
Variables
uchar oc_syms [MAXOCLASSES] = DUMMY
uchar showsyms [MAXPCHARS] = DUMMY
uchar monsyms [MAXMCLASSES] = DUMMY
uchar warnsyms [WARNCOUNT] = DUMMY
const char def_oc_syms [MAXOCLASSES]
const char invisexplain [] = `remembered, unseen, creature`
const char *const objexplain []
const char *const oclass_names []
const char def_monsyms [MAXMCLASSES]
const char *const monexplain [MAXMCLASSES]
const struct symdef def_warnsyms [WARNCOUNT]
const struct symdef defsyms [MAXPCHARS]
Macro Definition Documentation
#define C(n)
Definition at line 17 of file drawing.c.
#define g_FILLER(symbol) 0
Definition at line 20 of file drawing.c.
Function Documentation
void assign_graphics (uchar * graph_chars, int glth, int maxlen, int offset)
Definition at line 643 of file drawing.c.
References showsyms, and symdef::sym.
Referenced by graphics_opts(), parse_config_line(), and switch_graphics().
{
    register int i;
    for (i = 0; i < maxlen; i++)
    showsyms[i+offset] = (((i < glth) && graph_chars[i]) ?
               graph_chars[i] : defsyms[i+offset].sym);
}
int def_char_to_monclass (char ch)
Definition at line 633 of file drawing.c.
References def_monsyms, and MAXMCLASSES.
Referenced by choose_classes_menu(), parseoptions(), and use_crystal_ball().
{
    int i;
    for (i = 1; i < MAXMCLASSES; i++)
    if (def_monsyms[i] == ch) break;
    return i;
}
int def_char_to_objclass (char ch)
Definition at line 619 of file drawing.c.
References def_oc_syms, and MAXOCLASSES.
Referenced by change_inv_order(), choose_classes_menu(), create_object(), parseoptions(), query_classes(), and use_crystal_ball().
{
    int i;
    for (i = 1; i < MAXOCLASSES; i++)
    if (ch == def_oc_syms[i]) break;
    return i;
}
void switch_graphics (int gr_set_flag)
Definition at line 655 of file drawing.c.
References ASCII_GRAPHICS, assign_graphics(), DEC_GRAPHICS, instance_flags::DECgraphics, FALSE, IBM_GRAPHICS, instance_flags::IBMgraphics, iflags, MAC_GRAPHICS, MAXPCHARS, SIZE, and TRUE.
Referenced by initoptions(), parseoptions(), and process_options().
{
    switch (gr_set_flag) {
    default:
    case ASCII_GRAPHICS:
        assign_graphics((uchar *)0, 0, MAXPCHARS, 0);
#ifdef PC9800
        if (ascgraphics_mode_callback) (*ascgraphics_mode_callback)();
#endif
        break;
#ifdef ASCIIGRAPH
    case IBM_GRAPHICS:
/*
 * Use the nice IBM Extended ASCII line-drawing characters (codepage 437).
 *
 * OS/2 defaults to a multilingual character set (codepage 850, corresponding
 * to the ISO 8859 character set. We should probably do a VioSetCp() call to
 * set the codepage to 437.
 */
        iflags.IBMgraphics = TRUE;
        iflags.DECgraphics = FALSE;
        assign_graphics(ibm_graphics, SIZE(ibm_graphics),
      MAXPCHARS, 0);
#ifdef PC9800
        if (ibmgraphics_mode_callback) (*ibmgraphics_mode_callback)();
#endif
        break;
#endif /* ASCIIGRAPH */
#ifdef TERMLIB
    case DEC_GRAPHICS:
/*
 * Use the VT100 line drawing character set.
 */
        iflags.DECgraphics = TRUE;
        iflags.IBMgraphics = FALSE;
        assign_graphics(dec_graphics, SIZE(dec_graphics),
      MAXPCHARS, 0);
        if (decgraphics_mode_callback) (*decgraphics_mode_callback)();
        break;
#endif /* TERMLIB */
#ifdef MAC_GRAPHICS_ENV
    case MAC_GRAPHICS:
        assign_graphics(mac_graphics, SIZE(mac_graphics),
      MAXPCHARS, 0);
        break;
#endif
    }
    return;
}
Variable Documentation
const char def_monsyms[MAXMCLASSES]
Definition at line 96 of file drawing.c.
Referenced by def_char_to_monclass().
const char def_oc_syms[MAXOCLASSES]
Initial value:
= {
    '\0',
    ILLOBJ_SYM,
    WEAPON_SYM,
    ARMOR_SYM,
    RING_SYM,
    AMULET_SYM,
    TOOL_SYM,
    FOOD_SYM,
    POTION_SYM,
    SCROLL_SYM,
    SPBOOK_SYM,
    WAND_SYM,
    GOLD_SYM,
    GEM_SYM,
    ROCK_SYM,
    BALL_SYM,
    CHAIN_SYM,
    VENOM_SYM
}
Definition at line 28 of file drawing.c.
Referenced by def_char_to_objclass().
const struct symdef def_warnsyms[WARNCOUNT]
Initial value:
= {
    {'0', "unknown creature causing you worry", C(CLR_WHITE)},
    {'1', "unknown creature causing you concern", C(CLR_RED)},
    {'2', "unknown creature causing you anxiety", C(CLR_RED)},
    {'3', "unknown creature causing you disquiet", C(CLR_RED)},
    {'4', "unknown creature causing you alarm",
                        C(CLR_MAGENTA)},
    {'5', "unknown creature causing you dread",
                        C(CLR_BRIGHT_MAGENTA)}
}
Definition at line 191 of file drawing.c.
Referenced by do_look(), initoptions(), and warning_opts().
const struct symdef defsyms[MAXPCHARS]
Definition at line 206 of file drawing.c.
Referenced by create_monster(), do_look(), doidtrap(), dosit(), find_trap(), hurtle_step(), and lookat().
const char invisexplain[] = `remembered, unseen, creature`
Definition at line 49 of file drawing.c.
const char* const monexplain[MAXMCLASSES]
Initial value:
= {
    0,
    "ant or other insect", "blob", "cockatrice",
    "dog or other canine", "eye or sphere", "cat or other feline",
    "gremlin", "humanoid", "imp or minor demon",
    "jelly", "kobold", "leprechaun",
    "mimic", "nymph", "orc",
    "piercer", "quadruped", "rodent",
    "arachnid or centipede", "trapper or lurker above", "unicorn or horse",
    "vortex", "worm", "xan or other mythical/fantastic insect",
    "light", "zruty",
    "angelic being", "bat or bird", "centaur",
    "dragon", "elemental", "fungus or mold",
    "gnome", "giant humanoid", 0,
    "jabberwock", "Keystone Kop", "lich",
    "mummy", "naga", "ogre",
    "pudding or ooze", "quantum mechanic", "rust monster or disenchanter",
    "snake", "troll", "umber hulk",
    "vampire", "wraith", "xorn",
    "apelike creature", "zombie",
    "human or elf", "ghost", "golem",
    "major demon", "sea monster", "lizard",
    "long worm tail", "mimic"
}
Definition at line 164 of file drawing.c.
uchar monsyms[MAXMCLASSES] = DUMMY
Definition at line 24 of file drawing.c.
const char* const objexplain[]
Initial value:
= {
    0,
    "strange object",
    "weapon",
    "suit or piece of armor",
    "ring",
    "amulet",
    "useful item (pick-axe, key, lamp...)",
    "piece of food",
    "potion",
    "scroll",
    "spellbook",
    "wand",
    "pile of coins",
    "gem or rock",
    "boulder or statue",
    "iron ball",
    "iron chain",
    "splash of venom"
}
Definition at line 52 of file drawing.c.
uchar oc_syms[MAXOCLASSES] = DUMMY
Definition at line 22 of file drawing.c.
const char* const oclass_names[]
Initial value:
= {
    0,
    "illegal objects",
    "weapons",
    "armor",
    "rings",
    "amulets",
    "tools",
    "food",
    "potions",
    "scrolls",
    "spellbooks",
    "wands",
    "coins",
    "rocks",
    "large stones",
    "iron balls",
    "chains",
    "venoms"
}
Definition at line 74 of file drawing.c.
uchar showsyms[MAXPCHARS] = DUMMY
Definition at line 23 of file drawing.c.
Referenced by assign_graphics(), do_look(), is_swallow_sym(), mapglyph(), and nhglyph2charcolor().
uchar warnsyms[WARNCOUNT] = DUMMY
Definition at line 25 of file drawing.c.