nethack/src/exper.c File Reference
#include `hack.h`
*
Functions
STATIC_DCL long FDECL (newuexp,(int))
STATIC_DCL int FDECL (enermod,(int))
STATIC_OVL long newuexp (int lev)
STATIC_OVL int enermod (int en)
int experience (struct	monst *mtmp, int nk)
void more_experienced (int exp, int rexp)
void losexp (char *drainer) const
void newexplevel ()
void pluslvl (boolean incr)
long rndexp (boolean gaining)
Function Documentation
STATIC_OVL int enermod (int en)
Definition at line 20 of file exper.c.
References Role_switch.
Referenced by losexp(), and pluslvl().
{
    switch (Role_switch) {
    case PM_PRIEST:
    case PM_WIZARD:
        return(2 * en);
    case PM_HEALER:
    case PM_KNIGHT:
        return((3 * en) / 2);
    case PM_BARBARIAN:
    case PM_VALKYRIE:
        return((3 * en) / 4);
    default:
        return (en);
    }
}
int experience (struct	monst * mtmp, int nk)
Definition at line 39 of file exper.c.
References attack::aatyp, AD_BLND, AD_DRLI, AD_PHYS, AD_SLIM, AD_STON, AD_WRAP, attack::adtyp, Amphibious, AT_BUTT, AT_MAGC, AT_WEAP, attack::damd, attack::damn, extra_nasty, find_mac(), permonst::mattk, permonst::mlet, permonst::mmove, mons, NATTK, NORMAL_SPEED, and S_EEL.
{
    register struct permonst *ptr = mtmp->data;
    int i, tmp, tmp2;
    tmp = 1 + mtmp->m_lev * mtmp->m_lev;
/* For higher ac values, give extra experience */
    if ((i = find_mac(mtmp)) < 3) tmp += (7 - i) * ((i < 0) ? 2 : 1);
/* For very fast monsters, give extra experience */
    if (ptr->mmove > NORMAL_SPEED)
        tmp += (ptr->mmove > (3*NORMAL_SPEED/2)) ? 5 : 3;
/* For each "special" attack type give extra experience */
    for(i = 0; i < NATTK; i++) {
        tmp2 = ptr->mattk[i].aatyp;
        if(tmp2 > AT_BUTT) {
        if(tmp2 == AT_WEAP) tmp += 5;
        else if(tmp2 == AT_MAGC) tmp += 10;
        else tmp += 3;
        }
    }
/* For each "special" damage type give extra experience */
    for(i = 0; i < NATTK; i++) {
        tmp2 = ptr->mattk[i].adtyp;
        if(tmp2 > AD_PHYS && tmp2 < AD_BLND) tmp += 2*mtmp->m_lev;
        else if((tmp2 == AD_DRLI) || (tmp2 == AD_STON) ||
                (tmp2 == AD_SLIM)) tmp += 50;
        else if(tmp != AD_PHYS) tmp += mtmp->m_lev;
        /* extra heavy damage bonus */
        if((int)(ptr->mattk[i].damd * ptr->mattk[i].damn) > 23)
        tmp += mtmp->m_lev;
        if (tmp2 == AD_WRAP && ptr->mlet == S_EEL && !Amphibious)
        tmp += 1000;
    }
/* For certain "extra nasty" monsters, give even more */
    if (extra_nasty(ptr)) tmp += (7 * mtmp->m_lev);
/* For higher level monsters, an additional bonus is given */
    if(mtmp->m_lev > 8) tmp += 50;
#ifdef MAIL
    /* Mail daemons put up no fight. */
    if(mtmp->data == &mons[PM_MAIL_DAEMON]) tmp = 1;
#endif
    return(tmp);
}
STATIC_DCL long FDECL (newuexp , (int))
STATIC_DCL int FDECL (enermod , (int))
void losexp (char * drainer) const
Definition at line 114 of file exper.c.
References A_WIS, ACURR, flag::botl, DIED, done, Role::enadv, Race::enadv, enermod(), flags, Goodbye(), RoleAdvance::hifix, RoleAdvance::hirnd, KILLED_BY, killer, killer_format, RoleAdvance::lofix, RoleAdvance::lornd, newuexp(), NON_PM, rn1, u, you::uen, you::uenmax, you::uexp, you::uhp, you::uhpmax, you::ulevel, urace, urole, Role::xlev, and youmonst.
Referenced by angrygods().
{
    register int num;
#ifdef WIZARD
    /* override life-drain resistance when handling an explicit
       wizard mode request to reduce level; never fatal though */
    if (drainer && !strcmp(drainer, "#levelchange"))
        drainer = 0;
    else
#endif
        if (resists_drli(&youmonst)) return;
    if (u.ulevel > 1) {
        pline("%s level %d.", Goodbye(), u.ulevel--);
        /* remove intrinsic abilities */
        adjabil(u.ulevel + 1, u.ulevel);
        reset_rndmonst(NON_PM); /* new monster selection */
    } else {
        if (drainer) {
            killer_format = KILLED_BY;
            killer = drainer;
            done(DIED);
        }
        /* no drainer or lifesaved */
        u.uexp = 0;
    }
    num = newhp();
    u.uhpmax -= num;
    if (u.uhpmax < 1) u.uhpmax = 1;
    u.uhp -= num;
    if (u.uhp < 1) u.uhp = 1;
    else if (u.uhp > u.uhpmax) u.uhp = u.uhpmax;
    if (u.ulevel < urole.xlev)
        num = rn1((int)ACURR(A_WIS)/2 + urole.enadv.lornd +
      urace.enadv.lornd,
            urole.enadv.lofix + urace.enadv.lofix);
    else
        num = rn1((int)ACURR(A_WIS)/2 + urole.enadv.hirnd +
      urace.enadv.hirnd,
            urole.enadv.hifix + urace.enadv.hifix);
    num = enermod(num); /* M. Stephenson */
    u.uenmax -= num;
    if (u.uenmax < 0) u.uenmax = 0;
    u.uen -= num;
    if (u.uen < 0) u.uen = 0;
    else if (u.uen > u.uenmax) u.uen = u.uenmax;
    if (u.uexp > 0)
        u.uexp = newuexp(u.ulevel) - 1;
    flags.botl = 1;
}
void more_experienced (int exp, int rexp)
Definition at line 99 of file exper.c.
References flag::beginner, flag::botl, flags, Role_if, u, you::uexp, and you::urexp.
Referenced by doconsult().
{
    u.uexp += exp;
    u.urexp += 4*exp + rexp;
    if(exp
#ifdef SCORE_ON_BOTL
       || flags.showscore
#endif
       ) flags.botl = 1;
    if (u.urexp >= (Role_if(PM_WIZARD) ? 1000 : 2000))
        flags.beginner = 0;
}
void newexplevel ()
Definition at line 174 of file exper.c.
References MAXULEV, newuexp(), pluslvl(), TRUE, u, you::uexp, and you::ulevel.
Referenced by doconsult().
{
    if (u.ulevel < MAXULEV && u.uexp >= newuexp(u.
      ulevel))
        pluslvl(TRUE);
}
STATIC_OVL long newuexp (int lev)
Definition at line 11 of file exper.c.
Referenced by losexp(), newexplevel(), pluslvl(), and rndexp().
{
    if (lev < 10) return (10L * (1L << lev));
    if (lev < 20) return (10000L * (1L << (lev - 10)));
    return (10000000L * ((long)(lev - 19)));
}
void pluslvl (boolean incr)
Definition at line 181 of file exper.c.
References A_WIS, ACURR, flag::botl, Role::enadv, Race::enadv, enermod(), flags, RoleAdvance::hifix, RoleAdvance::hirnd, RoleAdvance::lofix, RoleAdvance::lornd, MAXULEV, you::mh, you::mhmax, newuexp(), NON_PM, rn1, u, you::uen, you::uenmax, you::uexp, you::uhp, you::uhpmax, you::ulevel, you::ulevelmax, Upolyd, urace, urole, and Role::xlev.
Referenced by newexplevel(), and pleased().
{ /* (false for potion of gain level) */
    register int num;
    if (!incr) You_feel("more experienced.");
    num = newhp();
    u.uhpmax += num;
    u.uhp += num;
    if (Upolyd) {
        num = rnd(8);
        u.mhmax += num;
        u.mh += num;
    }
    if (u.ulevel < urole.xlev)
        num = rn1((int)ACURR(A_WIS)/2 + urole.enadv.lornd +
      urace.enadv.lornd,
            urole.enadv.lofix + urace.enadv.lofix);
    else
        num = rn1((int)ACURR(A_WIS)/2 + urole.enadv.hirnd +
      urace.enadv.hirnd,
            urole.enadv.hifix + urace.enadv.hifix);
    num = enermod(num); /* M. Stephenson */
    u.uenmax += num;
    u.uen += num;
    if (u.ulevel < MAXULEV) {
        if (incr) {
        long tmp = newuexp(u.ulevel + 1);
        if (u.uexp >= tmp) u.uexp = tmp - 1;
        } else {
        u.uexp = newuexp(u.ulevel);
        }
        ++u.ulevel;
        if (u.ulevelmax < u.ulevel) u.ulevelmax = u.
      ulevel;
        pline("Welcome to experience level %d.", u.ulevel);
        adjabil(u.ulevel - 1, u.ulevel); /* give new intrinsics */
        reset_rndmonst(NON_PM); /* new monster selection */
    }
    flags.botl = 1;
}
long rndexp (boolean gaining)
Definition at line 224 of file exper.c.
References LARGEST_INT, MAXULEV, newuexp(), u, you::uexp, and you::ulevel.
{
    long minexp, maxexp, diff, factor, result;
    minexp = (u.ulevel == 1) ? 0L : newuexp(u.ulevel - 1);
    maxexp = newuexp(u.ulevel);
    diff = maxexp - minexp, factor = 1L;
    /* make sure that `diff' is an argument which rn2() can handle */
    while (diff >= (long)LARGEST_INT)
        diff /= 2L, factor *= 2L;
    result = minexp + factor * (long)rn2((int)diff);
    /* 3.4.1: if already at level 30, add to current experience
       points rather than to threshold needed to reach the current
       level; otherwise blessed potions of gain level can result
       in lowering the experience points instead of raising them */
    if (u.ulevel == MAXULEV && gaining) {
        result += (u.uexp - minexp);
        /* avoid wrapping (over 400 blessed potions needed for that...) */
        if (result < u.uexp) result = u.uexp;
    }
    return result;
}