nethack/src/files.c File Reference
#include `hack.h`
*
#include `dlb.h`
*
#include <ctype.h>
*
#include <fcntl.h>
*
#include <errno.h>
*
Macros
#define O_BINARY 0
#define SAVESIZE FILENAME	/* from macconf.h or pcconf.h */
#define HUP if (!program_state.done_hup)
#define fopenp fopen
#define match_varname(INP, NAM, LEN) match_optname(INP, NAM, LEN, TRUE)
#define tmp_levels (char *)0
#define tmp_ramdisk (char *)0
Functions
STATIC_DCL char * FDECL (set_bonesfile_name,(char *, d_level *))
STATIC_DCL char * NDECL (set_bonestemp_name)
STATIC_DCL char * FDECL (make_lockname,(const char *, char *))
STATIC_DCL FILE * FDECL (fopen_config_file,(const char *))
STATIC_DCL int FDECL (get_uchars,(FILE *, char *, char *, uchar *, BOOLEAN_P, int, const char *))
int FDECL (parse_config_line,(FILE *, char *, char *, char *))
char * fname_encode (char *legal, char quotechar, char *s, char *callerbuf, int bufsz) const
char * fname_decode (char quotechar, char *s, char *callerbuf, int bufsz)
const char * fqname (char *basename, int whichprefix, int buffnum) const
int validate_prefix_locations (char *reasonbuf)
FILE * fopen_datafile (char *filename, char *mode, int prefix) const
void set_levelfile_name (char *file, int lev)
int create_levelfile (int lev, errbuf)
int open_levelfile (int lev, errbuf)
void delete_levelfile (int lev)
void clearlocks ()
STATIC_OVL char * set_bonesfile_name (char *file, d_level *lev)
STATIC_OVL char * set_bonestemp_name ()
int create_bonesfile (d_level *lev, char **bonesid, errbuf)
void commit_bonesfile (d_level *lev)
int open_bonesfile (d_level *lev, char **bonesid)
int delete_bonesfile (d_level *lev)
void compress_bonesfile ()
void set_savefile_name ()
int create_savefile ()
int open_savefile ()
int delete_savefile ()
int restore_saved_game ()
char ** get_saved_games ()
void free_saved_games (char **saved)
void compress (char *filename) const
void uncompress (char *filename) const
STATIC_OVL char * make_lockname (char *filename, char *lockname) const
boolean lock_file (char *filename, int whichprefix, int retryct) const
void unlock_file (char *filename) const
STATIC_OVL FILE * fopen_config_file (char *filename) const
STATIC_OVL int get_uchars (FILE *fp, char *buf, char *bufp, uchar *list, boolean modlist, int size, const char *name)
int parse_config_line (FILE *fp, char *buf, char *tmp_ramdisk, char *tmp_levels)
void read_config_file (char *filename) const
void check_recordfile (char *dir) const
void paniclog (char *type, const char *reason) const
Variables
int errno
char bones [] = `bonesnn.xxx`
char lock [PL_NSIZ+14] = `1lock`
char SAVEF [SAVESIZE]
int n_dgns
static int nesting = 0
const char * configfile
Macro Definition Documentation
#define fopenp fopen
Definition at line 1478 of file files.c.
Referenced by fopen_config_file().
#define HUP if (!program_state.done_hup)
Definition at line 1250 of file files.c.
Referenced by lock_file(), and unlock_file().
#define match_varname(INP, NAM, LEN) match_optname(INP, NAM, LEN, TRUE)
Definition at line 1672 of file files.c.
Referenced by parse_config_line().
#define O_BINARY 0
Definition at line 51 of file files.c.
Referenced by create_bonesfile(), create_levelfile(), create_savefile(), open_bonesfile(), open_levelfile(), and open_savefile().
#define SAVESIZE FILENAME	/* from macconf.h or pcconf.h */
Definition at line 86 of file files.c.
Referenced by parse_config_line().
#define tmp_levels (char *)0
Referenced by read_config_file().
#define tmp_ramdisk (char *)0
Referenced by read_config_file().
Function Documentation
void check_recordfile (char * dir) const
Definition at line 2157 of file files.c.
References append_slash(), close(), FCMASK, file_is_stmlf(), fqname(), macclose(), macopen(), O_CREAT, O_RDWR, open(), PATHLEN, RECORD, S_IREAD, S_IWRITE, SCOREPREFIX, Strcat, Strcpy, and wait_synch.
Referenced by chdirx(), and InitMac().
{
#if (defined(macintosh) && (defined(__SC__) || defined(__MRC__))) || defined(__MWERKS__)
# pragma unused(dir)
#endif
    const char *fq_record;
    int fd;
#if defined(UNIX) || defined(VMS)
    fq_record = fqname(RECORD, SCOREPREFIX, 0);
    fd = open(fq_record, O_RDWR, 0);
    if (fd >= 0) {
# ifdef VMS /* must be stream-lf to use UPDATE_RECORD_IN_PLACE */
        if (!file_is_stmlf(fd)) {
            raw_printf(
          "Warning: scoreboard file %s is not in stream_lf format",
                fq_record);
            wait_synch();
        }
# endif
        (void) close(fd); /* RECORD is accessible */
    } else if ((fd = open(fq_record, O_CREAT|O_RDWR, FCMASK)) >= 0) {
        (void) close(fd); /* RECORD newly created */
# if defined(VMS) && !defined(SECURE)
        /* Re-protect RECORD with world:read+write+execute+delete access. */
        (void) chmod(fq_record, FCMASK | 007);
# endif /* VMS && !SECURE */
    } else {
        raw_printf("Warning: cannot write scoreboard file %s", fq_record);
        wait_synch();
    }
#endif /* !UNIX && !VMS */
#if defined(MICRO) || defined(WIN32)
    char tmp[PATHLEN];
# ifdef OS2_CODEVIEW /* explicit path on opening for OS/2 */
    /* how does this work when there isn't an explicit path or fopenp
     * for later access to the file via fopen_datafile? ? */
    (void) strncpy(tmp, dir, PATHLEN - 1);
    tmp[PATHLEN-1] = '\0';
    if ((strlen(tmp) + 1 + strlen(RECORD)) < (PATHLEN - 1)) {
        append_slash(tmp);
        Strcat(tmp, RECORD);
    }
    fq_record = tmp;
# else
    Strcpy(tmp, RECORD);
    fq_record = fqname(RECORD, SCOREPREFIX, 0);
# endif
    if ((fd = open(fq_record, O_RDWR)) < 0) {
        /* try to create empty record */
# if defined(AZTEC_C) || defined(_DCC) || (defined(__GNUC__) && defined(__AMIGA__))
        /* Aztec doesn't use the third argument */
        /* DICE doesn't like it */
        if ((fd = open(fq_record, O_CREAT|O_RDWR)) < 0) {
# else
        if ((fd = open(fq_record, O_CREAT|O_RDWR, S_IREAD|
      S_IWRITE)) < 0) {
# endif
    raw_printf("Warning: cannot write record %s", tmp);
        wait_synch();
        } else
        (void) close(fd);
    } else /* open succeeded */
        (void) close(fd);
#else /* MICRO || WIN32*/
# ifdef MAC
    /* Create the "record" file, if necessary */
    fq_record = fqname(RECORD, SCOREPREFIX, 0);
    fd = macopen (fq_record, O_RDWR | O_CREAT, TEXT_TYPE);
    if (fd != -1) macclose (fd);
# endif /* MAC */
#endif /* MICRO || WIN32*/
}
void clearlocks ()
Definition at line 522 of file files.c.
References alllevels, delete_levelfile(), levels, permbones, and ramdisk.
Referenced by bail(), done(), gnome_player_selection(), restlevelfile(), and X11_player_selection().
{
#if !defined(PC_LOCKING) && defined(MFLOPPY) && !defined(AMIGA)
    eraseall(levels, alllevels);
    if (ramdisk)
        eraseall(permbones, alllevels);
#else
    register int x;
# if defined(UNIX) || defined(VMS)
    (void) signal(SIGHUP, SIG_IGN);
# endif
    /* can't access maxledgerno() before dungeons are created -dlc */
    for (x = (n_dgns ? maxledgerno() : 0); x >= 0; x--)
        delete_levelfile(x); /* not all levels need be present */
#endif
}
void commit_bonesfile (d_level * lev)
Definition at line 711 of file files.c.
References bones, BONESPREFIX, fqname(), rename(), set_bonesfile_name(), set_bonestemp_name(), unlink(), and wizard.
Referenced by savebones().
{
    const char *fq_bones, *tempname;
    int ret;
    (void) set_bonesfile_name(bones, lev);
    fq_bones = fqname(bones, BONESPREFIX, 0);
    tempname = set_bonestemp_name();
    tempname = fqname(tempname, BONESPREFIX, 1);
#if (defined(SYSV) && !defined(SVR4)) || defined(GENIX)
    /* old SYSVs don't have rename. Some SVR3's may, but since they
     * also have link/unlink, it doesn't matter. :-)
     */
    (void) unlink(fq_bones);
    ret = link(tempname, fq_bones);
    ret += unlink(tempname);
#else
    ret = rename(tempname, fq_bones);
#endif
#ifdef WIZARD
    if (wizard && ret != 0)
        pline("couldn't rename %s to %s.", tempname, fq_bones);
#endif
}
void compress (char * filename) const
Definition at line 1212 of file files.c.
References FALSE.
Referenced by compress_bonesfile(), dosave0(), MAIN(), and main().
{
#ifndef COMPRESS
#if (defined(macintosh) && (defined(__SC__) || defined(__MRC__))) || defined(__MWERKS__)
# pragma unused(filename)
#endif
#else
    docompress_file(filename, FALSE);
#endif
}
void compress_bonesfile ()
Definition at line 771 of file files.c.
References bones, BONESPREFIX, compress(), and fqname().
Referenced by getbones(), and savebones().
{
    compress(fqname(bones, BONESPREFIX, 0));
}
int create_bonesfile (d_level * lev, char ** bonesid, errbuf)
Definition at line 651 of file files.c.
References bones, BONESPREFIX, creat(), errno, FCMASK, fqname(), lock, maccreat(), O_BINARY, O_CREAT, O_TRUNC, O_WRONLY, open(), set_bonesfile_name(), set_bonestemp_name(), and Sprintf.
Referenced by savebones().
{
    const char *file;
    int fd;
    if (errbuf) *errbuf = '\0';
    *bonesid = set_bonesfile_name(bones, lev);
    file = set_bonestemp_name();
    file = fqname(file, BONESPREFIX, 0);
#if defined(MICRO) || defined(WIN32)
    /* Use O_TRUNC to force the file to be shortened if it already
     * exists and is currently longer.
     */
    fd = open(file, O_WRONLY |O_CREAT | O_TRUNC |
      O_BINARY, FCMASK);
#else
# ifdef MAC
    fd = maccreat(file, BONE_TYPE);
# else
    fd = creat(file, FCMASK);
# endif
#endif
    if (fd < 0 && errbuf) /* failure explanation */
        Sprintf(errbuf,
            "Cannot create bones \"%s\", id %s (errno %d).",
            lock, *bonesid, errno);
# if defined(VMS) && !defined(SECURE)
    /*
       Re-protect bones file with world:read+write+execute+delete access.
       umask() doesn't seem very reliable; also, vaxcrtl won't let us set
       delete access without write access, which is what's really wanted.
       Can't simply create it with the desired protection because creat
       ANDs the mask with the user's default protection, which usually
       denies some or all access to world.
     */
    (void) chmod(file, FCMASK | 007); /* allow other users full access */
# endif /* VMS && !SECURE */
    return fd;
}
int create_levelfile (int lev, errbuf)
Definition at line 422 of file files.c.
References creat(), errno, FCMASK, linfo::flags, fqname(), level_info, LEVELPREFIX, LFILE_EXISTS, lock, maccreat(), O_BINARY, O_CREAT, O_TRUNC, O_WRONLY, open(), set_levelfile_name(), and Sprintf.
Referenced by restlevelfile().
{
    int fd;
    const char *fq_lock;
    if (errbuf) *errbuf = '\0';
    set_levelfile_name(lock, lev);
    fq_lock = fqname(lock, LEVELPREFIX, 0);
#if defined(MICRO) || defined(WIN32)
    /* Use O_TRUNC to force the file to be shortened if it already
     * exists and is currently longer.
     */
# ifdef HOLD_LOCKFILE_OPEN
    if (lev == 0)
        fd = open_levelfile_exclusively(fq_lock, lev,
                O_WRONLY |O_CREAT | O_TRUNC | O_BINARY);
    else
# endif
    fd = open(fq_lock, O_WRONLY |O_CREAT | O_TRUNC |
      O_BINARY, FCMASK);
#else
# ifdef MAC
    fd = maccreat(fq_lock, LEVL_TYPE);
# else
    fd = creat(fq_lock, FCMASK);
# endif
#endif /* MICRO || WIN32 */
    if (fd >= 0)
        level_info[lev].flags |= LFILE_EXISTS;
    else if (errbuf) /* failure explanation */
        Sprintf(errbuf,
            "Cannot create file \"%s\" for level %d (errno %d).",
            lock, lev, errno);
    return fd;
}
int create_savefile ()
Definition at line 860 of file files.c.
References creat(), FCMASK, fqname(), getuid(), maccreat(), O_BINARY, O_CREAT, O_TRUNC, O_WRONLY, open(), SAVEF, and SAVEPREFIX.
Referenced by dosave0().
{
    const char *fq_save;
    int fd;
    fq_save = fqname(SAVEF, SAVEPREFIX, 0);
#if defined(MICRO) || defined(WIN32)
    fd = open(fq_save, O_WRONLY | O_BINARY | O_CREAT |
      O_TRUNC, FCMASK);
#else
# ifdef MAC
    fd = maccreat(fq_save, SAVE_TYPE);
# else
    fd = creat(fq_save, FCMASK);
# endif
# if defined(VMS) && !defined(SECURE)
    /*
       Make sure the save file is owned by the current process. That's
       the default for non-privileged users, but for priv'd users the
       file will be owned by the directory's owner instead of the user.
     */
# ifdef getuid /*(see vmsunix.c)*/
# undef getuid
# endif
    (void) chown(fq_save, getuid(), getgid());
# endif /* VMS && !SECURE */
#endif /* MICRO */
    return fd;
}
int delete_bonesfile (d_level * lev)
Definition at line 760 of file files.c.
References bones, BONESPREFIX, fqname(), set_bonesfile_name(), and unlink().
Referenced by getbones(), and savebones().
{
    (void) set_bonesfile_name(bones, lev);
    return !(unlink(fqname(bones, BONESPREFIX, 0)) < 0);
}
void delete_levelfile (int lev)
Definition at line 503 of file files.c.
References linfo::flags, flags, fqname(), level_info, LEVELPREFIX, LFILE_EXISTS, lock, set_levelfile_name(), and unlink().
Referenced by clearlocks(), and dosave0().
{
    /*
     * Level 0 might be created by port specific code that doesn't
     * call create_levfile(), so always assume that it exists.
     */
    if (lev == 0 || (level_info[lev].flags & LFILE_EXISTS)) {
        set_levelfile_name(lock, lev);
#ifdef HOLD_LOCKFILE_OPEN
        if (lev == 0) really_close();
#endif
        (void) unlink(fqname(lock, LEVELPREFIX, 0));
        level_info[lev].flags &= ~LFILE_EXISTS;
    }
}
int delete_savefile ()
Definition at line 910 of file files.c.
References fqname(), SAVEF, SAVEPREFIX, and unlink().
Referenced by dorecover(), dosave0(), MAIN(), main(), mread(), and restore_saved_game().
{
    (void) unlink(fqname(SAVEF, SAVEPREFIX, 0));
    return 0; /* for restore_saved_game() (ex-xxxmain.c) test */
}
STATIC_DCL char* FDECL (set_bonesfile_name , (char *, d_level *))
STATIC_DCL char* FDECL (make_lockname , (const char *, char *))
STATIC_DCL FILE* FDECL (fopen_config_file , (const char *))
STATIC_DCL int FDECL (get_uchars , (FILE *, char *, char *, uchar *, BOOLEAN_P, int, const char *))
int FDECL (parse_config_line , (FILE *, char *, char *, char *))
char* fname_decode (char quotechar, char * s, char * callerbuf, int bufsz)
Definition at line 235 of file files.c.
{
    char *sp, *op;
    int k,calc,cnt = 0;
    static char hexdigits[] = "0123456789ABCDEF";
    sp = s;
    op = callerbuf;
    *op = '\0';
    calc = 0;
    while (*sp) {
        /* Do we have room for one more character? */
        if ((bufsz - cnt) <= 2) return callerbuf;
        if (*sp == quotechar) {
            sp++;
            for (k=0; k < 16; ++k) if (*sp == hexdigits[k]) break;
            if (k >= 16) return callerbuf; /* impossible, so bail */
            calc = k << 4;
            sp++;
            for (k=0; k < 16; ++k) if (*sp == hexdigits[k]) break;
            if (k >= 16) return callerbuf; /* impossible, so bail */
            calc += k;
            sp++;
            *op++ = calc;
            *op = '\0';
        } else {
            *op++ = *sp++;
            *op = '\0';
        }
        cnt++;
    }
    return callerbuf;
}
char* fname_encode (char * legal, char quotechar, char * s, char * callerbuf, int bufsz) const
Definition at line 189 of file files.c.
References index().
Referenced by set_savefile_name().
{
    char *sp, *op;
    int cnt = 0;
    static char hexdigits[] = "0123456789ABCDEF";
    sp = s;
    op = callerbuf;
    *op = '\0';
    
    while (*sp) {
        /* Do we have room for one more character or encoding? */
        if ((bufsz - cnt) <= 4) return callerbuf;
        if (*sp == quotechar) {
            (void)sprintf(op, "%c%02X", quotechar, *sp);
             op += 3;
             cnt += 3;
        } else if ((index(legal, *sp) != 0) || (index(hexdigits, *sp) != 0)) {
            *op++ = *sp;
            *op = '\0';
            cnt++;
        } else {
            (void)sprintf(op,"%c%02X", quotechar, *sp);
            op += 3;
            cnt += 3;
        }
        sp++;
    }
    return callerbuf;
}
STATIC_OVL FILE* fopen_config_file (char * filename) const
Definition at line 1482 of file files.c.
References access(), BUFSZ, CONFIGPREFIX, errno, filename, fopenp, fp, fqname(), nh_getenv(), Sprintf, Strcpy, and wait_synch.
Referenced by read_config_file().
{
    FILE *fp;
#if defined(UNIX) || defined(VMS)
    char tmp_config[BUFSZ];
    char *envp;
#endif
    /* "filename" is an environment variable, so it should hang around */
    /* if set, it is expected to be a full path name (if relevant) */
    if (filename) {
#ifdef UNIX
        if (access(filename, 4) == -1) {
            /* 4 is R_OK on newer systems */
            /* nasty sneaky attempt to read file through
             * NetHack's setuid permissions -- this is the only
             * place a file name may be wholly under the player's
             * control
             */
            raw_printf("Access to %s denied (%d).",
                    filename, errno);
            wait_synch();
            /* fall through to standard names */
        } else
#endif
        if ((fp = fopenp(filename, "r")) != (FILE *)0) {
            configfile = filename;
            return(fp);
#if defined(UNIX) || defined(VMS)
        } else {
            /* access() above probably caught most problems for UNIX */
            raw_printf("Couldn't open requested config file %s (%d).",
                    filename, errno);
            wait_synch();
            /* fall through to standard names */
#endif
        }
    }
#if defined(MICRO) || defined(MAC) || defined(__BEOS__) || defined(WIN32)
    if ((fp = fopenp(fqname(configfile, CONFIGPREFIX, 0), "r"))
                                != (FILE *)0)
        return(fp);
# ifdef MSDOS
    else if ((fp = fopenp(fqname(backward_compat_configfile,
                    CONFIGPREFIX, 0), "r")) != (FILE *)0)
        return(fp);
# endif
#else
    /* constructed full path names don't need fqname() */
# ifdef VMS
    if ((fp = fopenp(fqname("nethackini", CONFIGPREFIX, 0), "r"))
                                != (FILE *)0) {
        configfile = "nethackini";
        return(fp);
    }
    if ((fp = fopenp("sys$login:nethack.ini", "r")) != (FILE *)0) {
        configfile = "nethack.ini";
        return(fp);
    }
    envp = nh_getenv("HOME");
    if (!envp)
        Strcpy(tmp_config, "NetHack.cnf");
    else
        Sprintf(tmp_config, "%s%s", envp, "NetHack.cnf");
    if ((fp = fopenp(tmp_config, "r")) != (FILE *)0)
        return(fp);
# else /* should be only UNIX left */
    envp = nh_getenv("HOME");
    if (!envp)
        Strcpy(tmp_config, configfile);
    else
        Sprintf(tmp_config, "%s/%s", envp, configfile);
    if ((fp = fopenp(tmp_config, "r")) != (FILE *)0)
        return(fp);
# if defined(__APPLE__)
    /* try an alternative */
    if (envp) {
        Sprintf(tmp_config, "%s/%s", envp, "Library/Preferences/NetHack Defaults");
        if ((fp = fopenp(tmp_config, "r")) != (FILE *)0)
            return(fp);
        Sprintf(tmp_config, "%s/%s", envp, "Library/Preferences/NetHack Defaults.txt");
        if ((fp = fopenp(tmp_config, "r")) != (FILE *)0)
            return(fp);
    }
# endif
    if (errno != ENOENT) {
        char *details;
        /* e.g., problems when setuid NetHack can't search home
         * directory restricted to user */
#if defined (NHSTDC) && !defined(NOTSTDC)
        if ((details = strerror(errno)) == 0)
#endif
        details = "";
        raw_printf("Couldn't open default config file %s %s(%d).",
               tmp_config, details, errno);
        wait_synch();
    }
# endif
#endif
    return (FILE *)0;
}
FILE* fopen_datafile (char * filename, char * mode, int prefix) const
Definition at line 351 of file files.c.
References BUFSIZ, fp, fqname(), index(), and TROUBLEPREFIX.
Referenced by init_tiles(), paniclog(), prscore(), topten(), and tt_oname().
{
    FILE *fp;
    filename = fqname(filename, prefix, prefix ==
      TROUBLEPREFIX ? 3 : 0);
#ifdef VMS /* essential to have punctuation, to avoid logical names */
    {
    char tmp[BUFSIZ];
    if (!index(filename, '.') && !index(filename, ';'))
        filename = strcat(strcpy(tmp, filename), ";0");
    fp = fopen(filename, mode, "mbc=16");
    }
#else
    fp = fopen(filename, mode);
#endif
    return fp;
}
const char* fqname (char * basename, int whichprefix, int buffnum) const
Definition at line 277 of file files.c.
References basename(), FQN_MAX_FILENAME, fqn_prefix, PREFIX_COUNT, and Strcpy.
Referenced by check_recordfile(), commit_bonesfile(), compress_bonesfile(), create_bonesfile(), create_levelfile(), create_savefile(), delete_bonesfile(), delete_levelfile(), delete_savefile(), dosave0(), eraseoldlocks(), fopen_config_file(), fopen_datafile(), getlock(), lock_file(), MAIN(), main(), open_bonesfile(), open_levelfile(), open_savefile(), process_openfile(), restore_saved_game(), unlock_file(), and validate_prefix_locations().
{
#ifndef PREFIXES_IN_USE
    return basename;
#else
    if (!basename || whichprefix < 0 || whichprefix >= PREFIX_COUNT)
        return basename;
    if (!fqn_prefix[whichprefix])
        return basename;
    if (buffnum < 0 || buffnum >= FQN_NUMBUF) {
        impossible("Invalid fqn_filename_buffer specified: %d",
                                buffnum);
        buffnum = 0;
    }
    if (strlen(fqn_prefix[whichprefix]) + strlen(basename) >=
                            FQN_MAX_FILENAME) {
        impossible("fqname too long: %s + %s", fqn_prefix[whichprefix],
                        basename);
        return basename; /* XXX */
    }
    Strcpy(fqn_filename_buffer[buffnum], fqn_prefix[whichprefix]);
    return strcat(fqn_filename_buffer[buffnum], basename);
#endif
}
void free_saved_games (char** saved)
Definition at line 1030 of file files.c.
References free().
{
    if (saved) {
    int i=0;
    while (saved[i]) free((genericptr_t)saved[i++]);
    free((genericptr_t)saved);
    }
}
char** get_saved_games ()
Definition at line 997 of file files.c.
References alloc(), BUFSZ, getuid(), and Sprintf.
{
#if defined(UNIX) && defined(QT_GRAPHICS)
    int myuid=getuid();
    struct dirent **namelist;
    int n = scandir("save", &namelist, 0, alphasort);;
    if (n > 0) {
    int i,j=0;
    char** result = (char**)alloc((n+1)*sizeof(char*)); /* at most */
    for (i=0; i<n; i++) {
        int uid;
        char name[64]; /* more than PL_NSIZ */
        if (sscanf(namelist[i]->d_name, "%d%63s", &uid, name) == 2) {
        if (uid == myuid) {
            char filename[BUFSZ];
            char* r;
            Sprintf(filename,"save/%d%s",uid,name);
            r = plname_from_file(filename);
            if (r)
            result[j++] = r;
        }
        }
    }
    result[j++] = 0;
    return result;
    } else
#endif
    {
    return 0;
    }
}
STATIC_OVL int get_uchars (FILE * fp, char * buf, char * bufp, uchar * list, boolean modlist, int size, const char * name)
Definition at line 1598 of file files.c.
References buf, BUFSZ, count, FALSE, TRUE, and wait_synch.
Referenced by parse_config_line().
{
    unsigned int num = 0;
    int count = 0;
    boolean havenum = FALSE;
    while (1) {
    switch(*bufp) {
        case ' ': case '\0':
        case '\t': case '\n':
        if (havenum) {
            /* if modifying in place, don't insert zeros */
            if (num || !modlist) list[count] = num;
            count++;
            num = 0;
            havenum = FALSE;
        }
        if (count == size || !*bufp) return count;
        bufp++;
        break;
        case '0': case '1': case '2': case '3':
        case '4': case '5': case '6': case '7':
        case '8': case '9':
        havenum = TRUE;
        num = num*10 + (*bufp-'0');
        bufp++;
        break;
        case '\\':
        if (fp == (FILE *)0)
            goto gi_error;
        do {
            if (!fgets(buf, BUFSZ, fp)) goto gi_error;
        } while (buf[0] == '#');
        bufp = buf;
        break;
        default:
gi_error:
        raw_printf("Syntax error in %s", name);
        wait_synch();
        return count;
    }
    }
    /*NOTREACHED*/
}
boolean lock_file (char * filename, int whichprefix, int retryct) const
Definition at line 1289 of file files.c.
References BUFSZ, Delay(), DeleteFile, errno, FALSE, fqname(), HUP, LOCKPREFIX, make_lockname(), O_CREAT, O_EXCL, O_RDWR, open(), perror, raw_print, S_IWRITE, and TRUE.
Referenced by getlock(), and topten().
{
#if (defined(macintosh) && (defined(__SC__) || defined(__MRC__))) || defined(__MWERKS__)
# pragma unused(filename, retryct)
#endif
    char locknambuf[BUFSZ];
    const char *lockname;
    nesting++;
    if (nesting > 1) {
        impossible("TRIED TO NEST LOCKS");
        return TRUE;
    }
    lockname = make_lockname(filename, locknambuf);
    filename = fqname(filename, whichprefix, 0);
#ifndef NO_FILE_LINKS /* LOCKDIR should be subsumed by LOCKPREFIX */
    lockname = fqname(lockname, LOCKPREFIX, 2);
#endif
#if defined(UNIX) || defined(VMS)
# ifdef NO_FILE_LINKS
    while ((lockfd = open(lockname, O_RDWR|O_CREAT|O_EXCL, 0666)) == -1) {
# else
    while (link(filename, lockname) == -1) {
# endif
        register int errnosv = errno;
        switch (errnosv) { /* George Barbanis */
        case EEXIST:
        if (retryct--) {
            HUP raw_printf(
                "Waiting for access to %s. (%d retries left).",
                filename, retryct);
# if defined(SYSV) || defined(ULTRIX) || defined(VMS)
            (void)
# endif
            sleep(1);
        } else {
            HUP (void) raw_print("I give up. Sorry.");
            HUP raw_printf("Perhaps there is an old %s around?",
                    lockname);
            nesting--;
            return FALSE;
        }
        break;
        case ENOENT:
        HUP raw_printf("Can't find file %s to lock!", filename);
        nesting--;
        return FALSE;
        case EACCES:
        HUP raw_printf("No write permission to lock %s!", filename);
        nesting--;
        return FALSE;
# ifdef VMS /* c__translate(vmsfiles.c) */
        case EPERM:
        /* could be misleading, but usually right */
        HUP raw_printf("Can't lock %s due to directory protection.",
                   filename);
        nesting--;
        return FALSE;
# endif
        default:
        HUP perror(lockname);
        HUP raw_printf(
                 "Cannot lock %s for unknown reason (%d).",
                   filename, errnosv);
        nesting--;
        return FALSE;
        }
    }
#endif /* UNIX || VMS */
#if defined(AMIGA) || defined(WIN32) || defined(MSDOS)
# ifdef AMIGA
#define OPENFAILURE(fd) (!fd)
    lockptr = 0;
# else
#define OPENFAILURE(fd) (fd < 0)
    lockptr = -1;
# endif
    while (--retryct && OPENFAILURE(lockptr)) {
# if defined(WIN32) && !defined(WIN_CE)
    lockptr = sopen(lockname, O_RDWR|O_CREAT, SH_DENYRW, S_IWRITE);
# else
    (void)DeleteFile(lockname); /* in case dead process was here first */
# ifdef AMIGA
    lockptr = Open(lockname,MODE_NEWFILE);
# else
    lockptr = open(lockname, O_RDWR|O_CREAT|O_EXCL,
      S_IWRITE);
# endif
# endif
    if (OPENFAILURE(lockptr)) {
        raw_printf("Waiting for access to %s. (%d retries left).",
            filename, retryct);
        Delay(50);
    }
    }
    if (!retryct) {
    raw_printf("I give up. Sorry.");
    nesting--;
    return FALSE;
    }
#endif /* AMIGA || WIN32 || MSDOS */
    return TRUE;
}
STATIC_OVL char* make_lockname (char * filename, char * lockname) const
Definition at line 1253 of file files.c.
References rindex, Strcat, and Strcpy.
Referenced by lock_file(), and unlock_file().
{
#if (defined(macintosh) && (defined(__SC__) || defined(__MRC__))) || defined(__MWERKS__)
# pragma unused(filename,lockname)
    return (char*)0;
#else
# if defined(UNIX) || defined(VMS) || defined(AMIGA) || defined(WIN32) || defined(MSDOS)
# ifdef NO_FILE_LINKS
    Strcpy(lockname, LOCKDIR);
    Strcat(lockname, "/");
    Strcat(lockname, filename);
# else
    Strcpy(lockname, filename);
# endif
# ifdef VMS
      {
    char *semi_colon = rindex(lockname, ';');
    if (semi_colon) *semi_colon = '\0';
      }
    Strcat(lockname, ".lock;1");
# else
    Strcat(lockname, "_lock");
# endif
    return lockname;
# else
    lockname[0] = '\0';
    return (char*)0;
# endif /* UNIX || VMS || AMIGA || WIN32 || MSDOS */
#endif
}
STATIC_DCL char* NDECL (set_bonestemp_name)
int open_bonesfile (d_level * lev, char ** bonesid)
Definition at line 740 of file files.c.
References bones, BONESPREFIX, fqname(), macopen(), O_BINARY, O_RDONLY, open(), set_bonesfile_name(), and uncompress().
Referenced by getbones(), and savebones().
{
    const char *fq_bones;
    int fd;
    *bonesid = set_bonesfile_name(bones, lev);
    fq_bones = fqname(bones, BONESPREFIX, 0);
    uncompress(fq_bones); /* no effect if nonexistent */
#ifdef MAC
    fd = macopen(fq_bones, O_RDONLY | O_BINARY, BONE_TYPE);
#else
    fd = open(fq_bones, O_RDONLY | O_BINARY, 0);
#endif
    return fd;
}
int open_levelfile (int lev, errbuf)
Definition at line 464 of file files.c.
References errno, fqname(), level_info, LEVELPREFIX, lock, macopen(), O_BINARY, O_RDONLY, open(), set_levelfile_name(), Sprintf, and where.
Referenced by dosave0().
{
    int fd;
    const char *fq_lock;
    if (errbuf) *errbuf = '\0';
    set_levelfile_name(lock, lev);
    fq_lock = fqname(lock, LEVELPREFIX, 0);
#ifdef MFLOPPY
    /* If not currently accessible, swap it in. */
    if (level_info[lev].where != ACTIVE)
        swapin_file(lev);
#endif
#ifdef MAC
    fd = macopen(fq_lock, O_RDONLY | O_BINARY, LEVL_TYPE);
#else
# ifdef HOLD_LOCKFILE_OPEN
    if (lev == 0)
        fd = open_levelfile_exclusively(fq_lock, lev, O_RDONLY |
      O_BINARY);
    else
# endif
    fd = open(fq_lock, O_RDONLY | O_BINARY, 0);
#endif
    /* for failure, return an explanation that our caller can use;
       settle for `lock' instead of `fq_lock' because the latter
       might end up being too big for nethack's BUFSZ */
    if (fd < 0 && errbuf)
        Sprintf(errbuf,
            "Cannot open file \"%s\" for level %d (errno %d).",
            lock, lev, errno);
    return fd;
}
int open_savefile ()
Definition at line 893 of file files.c.
References fqname(), macopen(), O_BINARY, O_RDONLY, open(), SAVEF, and SAVEPREFIX.
Referenced by dosave0(), and restore_saved_game().
{
    const char *fq_save;
    int fd;
    fq_save = fqname(SAVEF, SAVEPREFIX, 0);
#ifdef MAC
    fd = macopen(fq_save, O_RDONLY | O_BINARY, SAVE_TYPE);
#else
    fd = open(fq_save, O_RDONLY | O_BINARY, 0);
#endif
    return fd;
}
void paniclog (char * type, const char * reason) const
Definition at line 2241 of file files.c.
References BUFSZ, fopen_datafile(), PANICLOG, program_state, TROUBLEPREFIX, type, and version_string().
Referenced by validate_prefix_locations().
{
#ifdef PANICLOG
    FILE *lfile;
    char buf[BUFSZ];
    if (!program_state.in_paniclog) {
        program_state.in_paniclog = 1;
        lfile = fopen_datafile(PANICLOG, "a",
      TROUBLEPREFIX);
        if (lfile) {
            (void) fprintf(lfile, "%s %08ld: %s %s\n",
                   version_string(buf), yyyymmdd((time_t)0L),
                   type, reason);
            (void) fclose(lfile);
        }
        program_state.in_paniclog = 0;
    }
#endif /* PANICLOG */
    return;
}
int parse_config_line (FILE		* fp, char		* buf, char		* tmp_ramdisk, char		* tmp_levels)
Definition at line 1676 of file files.c.
References amii_init_map, AMII_MAXCOLORS, amii_menuAPen, amii_menuBPen, amii_msgAPen, amii_msgBPen, amii_numcolors, amii_otherAPen, amii_otherBPen, amii_scrnmode, amii_set_text_font(), amii_setpens(), amii_statAPen, amii_statBPen, amii_textAPen, amii_textBPen, append_slash(), assign_graphics(), assign_warnings(), BONESPREFIX, instance_flags::bouldersym, catname, CONFIGPREFIX, DATAPREFIX, DEPTH, dogname, eos(), FALSE, flags, get_uchars(), hackdir, HACKPREFIX, iflags, index(), flag::initrole, LEVELPREFIX, LOCKPREFIX, match_varname, MAXDCHARS, MAXECHARS, MAXMCLASSES, MAXOCLASSES, MAXPCHARS, MAXTCHARS, min, monsyms, NULL, oc_syms, parseoptions(), PATH, PATHLEN, PL_NSIZ, PL_PSIZ, plname, plnamesuffix(), SAVEPREFIX, SAVESIZE, SCOREPREFIX, str2role(), strdup, TROUBLEPREFIX, TRUE, and WARNCOUNT.
Referenced by read_config_file().
{
#if (defined(macintosh) && (defined(__SC__) || defined(__MRC__))) || defined(__MWERKS__)
# pragma unused(tmp_ramdisk,tmp_levels)
#endif
    char *bufp, *altp;
    uchar translate[MAXPCHARS];
    int len;
    if (*buf == '#')
        return 1;
    /* remove trailing whitespace */
    bufp = eos(buf);
    while (--bufp > buf && isspace(*bufp))
        continue;
    if (bufp <= buf)
        return 1; /* skip all-blank lines */
    else
        *(bufp + 1) = '\0'; /* terminate line */
    /* find the '=' or ':' */
    bufp = index(buf, '=');
    altp = index(buf, ':');
    if (!bufp || (altp && altp < bufp)) bufp = altp;
    if (!bufp) return 0;
    /* skip whitespace between '=' and value */
    do { ++bufp; } while (isspace(*bufp));
    /* Go through possible variables */
    /* some of these (at least LEVELS and SAVE) should now set the
     * appropriate fqn_prefix[] rather than specialized variables
     */
    if (match_varname(buf, "OPTIONS", 4)) {
        parseoptions(bufp, TRUE, TRUE);
        if (plname[0]) /* If a name was given */
            plnamesuffix(); /* set the character class */
#ifdef AUTOPICKUP_EXCEPTIONS
    } else if (match_varname(buf, "AUTOPICKUP_EXCEPTION", 5)) {
        add_autopickup_exception(bufp);
#endif
#ifdef NOCWD_ASSUMPTIONS
    } else if (match_varname(buf, "HACKDIR", 4)) {
        adjust_prefix(bufp, HACKPREFIX);
    } else if (match_varname(buf, "LEVELDIR", 4) ||
           match_varname(buf, "LEVELS", 4)) {
        adjust_prefix(bufp, LEVELPREFIX);
    } else if (match_varname(buf, "SAVEDIR", 4)) {
        adjust_prefix(bufp, SAVEPREFIX);
    } else if (match_varname(buf, "BONESDIR", 5)) {
        adjust_prefix(bufp, BONESPREFIX);
    } else if (match_varname(buf, "DATADIR", 4)) {
        adjust_prefix(bufp, DATAPREFIX);
    } else if (match_varname(buf, "SCOREDIR", 4)) {
        adjust_prefix(bufp, SCOREPREFIX);
    } else if (match_varname(buf, "LOCKDIR", 4)) {
        adjust_prefix(bufp, LOCKPREFIX);
    } else if (match_varname(buf, "CONFIGDIR", 4)) {
        adjust_prefix(bufp, CONFIGPREFIX);
    } else if (match_varname(buf, "TROUBLEDIR", 4)) {
        adjust_prefix(bufp, TROUBLEPREFIX);
#else /*NOCWD_ASSUMPTIONS*/
# ifdef MICRO
    } else if (match_varname(buf, "HACKDIR", 4)) {
        (void) strncpy(hackdir, bufp, PATHLEN-1);
# ifdef MFLOPPY
    } else if (match_varname(buf, "RAMDISK", 3)) {
                /* The following ifdef is NOT in the wrong
                 * place. For now, we accept and silently
                 * ignore RAMDISK */
# ifndef AMIGA
        (void) strncpy(tmp_ramdisk, bufp, PATHLEN-1);
# endif
# endif
    } else if (match_varname(buf, "LEVELS", 4)) {
        (void) strncpy(tmp_levels, bufp, PATHLEN-1);
    } else if (match_varname(buf, "SAVE", 4)) {
# ifdef MFLOPPY
        extern int saveprompt;
# endif
        char *ptr;
        if ((ptr = index(bufp, ';')) != 0) {
            *ptr = '\0';
# ifdef MFLOPPY
            if (*(ptr+1) == 'n' || *(ptr+1) == 'N') {
                saveprompt = FALSE;
            }
# endif
        }
# ifdef MFLOPPY
        else
            saveprompt = flags.asksavedisk;
# endif
        (void) strncpy(SAVEP, bufp, SAVESIZE-1);
        append_slash(SAVEP);
# endif /* MICRO */
#endif /*NOCWD_ASSUMPTIONS*/
    } else if (match_varname(buf, "NAME", 4)) {
        (void) strncpy(plname, bufp, PL_NSIZ-1);
        plnamesuffix();
    } else if (match_varname(buf, "ROLE", 4) ||
           match_varname(buf, "CHARACTER", 4)) {
        if ((len = str2role(bufp)) >= 0)
            flags.initrole = len;
    } else if (match_varname(buf, "DOGNAME", 3)) {
        (void) strncpy(dogname, bufp, PL_PSIZ-1);
    } else if (match_varname(buf, "CATNAME", 3)) {
        (void) strncpy(catname, bufp, PL_PSIZ-1);
    } else if (match_varname(buf, "BOULDER", 3)) {
        (void) get_uchars(fp, buf, bufp, &iflags.bouldersym,
      TRUE,
                  1, "BOULDER");
    } else if (match_varname(buf, "GRAPHICS", 4)) {
        len = get_uchars(fp, buf, bufp, translate, FALSE,
                 MAXPCHARS, "GRAPHICS");
        assign_graphics(translate, len, MAXPCHARS, 0);
    } else if (match_varname(buf, "DUNGEON", 4)) {
        len = get_uchars(fp, buf, bufp, translate, FALSE,
                 MAXDCHARS, "DUNGEON");
        assign_graphics(translate, len, MAXDCHARS, 0);
    } else if (match_varname(buf, "TRAPS", 4)) {
        len = get_uchars(fp, buf, bufp, translate, FALSE,
                 MAXTCHARS, "TRAPS");
        assign_graphics(translate, len, MAXTCHARS,
      MAXDCHARS);
    } else if (match_varname(buf, "EFFECTS", 4)) {
        len = get_uchars(fp, buf, bufp, translate, FALSE,
                 MAXECHARS, "EFFECTS");
        assign_graphics(translate, len, MAXECHARS,
      MAXDCHARS+MAXTCHARS);
    } else if (match_varname(buf, "OBJECTS", 3)) {
        /* oc_syms[0] is the RANDOM object, unused */
        (void) get_uchars(fp, buf, bufp, &(oc_syms[1]),
      TRUE,
                    MAXOCLASSES-1, "OBJECTS");
    } else if (match_varname(buf, "MONSTERS", 3)) {
        /* monsyms[0] is unused */
        (void) get_uchars(fp, buf, bufp, &(monsyms[1]),
      TRUE,
                    MAXMCLASSES-1, "MONSTERS");
    } else if (match_varname(buf, "WARNINGS", 5)) {
        (void) get_uchars(fp, buf, bufp, translate, FALSE,
                    WARNCOUNT, "WARNINGS");
        assign_warnings(translate);
#ifdef WIZARD
    } else if (match_varname(buf, "WIZKIT", 6)) {
        (void) strncpy(wizkit, bufp, WIZKIT_MAX-1);
#endif
#ifdef AMIGA
    } else if (match_varname(buf, "FONT", 4)) {
        char *t;
        if(t = strchr(buf+5, ':'))
        {
            *t = 0;
            amii_set_text_font(buf+5, atoi(t + 1));
            *t = ':';
        }
    } else if (match_varname(buf, "PATH", 4)) {
        (void) strncpy(PATH, bufp, PATHLEN-1);
    } else if (match_varname(buf, "DEPTH", 5)) {
        extern int amii_numcolors;
        int val = atoi(bufp);
        amii_numcolors = 1L << min(DEPTH, val);
    } else if (match_varname(buf, "DRIPENS", 7)) {
        int i, val;
        char *t;
        for (i = 0, t = strtok(bufp, ",/"); t != (char *)0;
                i < 20 && (t = strtok((char*)0, ",/")), ++i) {
            sscanf(t, "%d", &val);
            flags.amii_dripens[i] = val;
        }
    } else if (match_varname(buf, "SCREENMODE", 10)) {
        extern long amii_scrnmode;
        if (!stricmp(bufp,"req"))
            amii_scrnmode = 0xffffffff; /* Requester */
        else if(sscanf(bufp, "%x", &amii_scrnmode) != 1)
            amii_scrnmode = 0;
    } else if (match_varname(buf, "MSGPENS", 7)) {
        extern int amii_msgAPen, amii_msgBPen;
        char *t = strtok(bufp, ",/");
        if(t)
        {
            sscanf(t, "%d", &amii_msgAPen);
            if(t = strtok((char*)0, ",/"))
                sscanf(t, "%d", &amii_msgBPen);
        }
    } else if (match_varname(buf, "TEXTPENS", 8)) {
        extern int amii_textAPen, amii_textBPen;
        char *t = strtok(bufp, ",/");
        if(t)
        {
            sscanf(t, "%d", &amii_textAPen);
            if(t = strtok((char*)0, ",/"))
                sscanf(t, "%d", &amii_textBPen);
        }
    } else if (match_varname(buf, "MENUPENS", 8)) {
        extern int amii_menuAPen, amii_menuBPen;
        char *t = strtok(bufp, ",/");
        if(t)
        {
            sscanf(t, "%d", &amii_menuAPen);
            if(t = strtok((char*)0, ",/"))
                sscanf(t, "%d", &amii_menuBPen);
        }
    } else if (match_varname(buf, "STATUSPENS", 10)) {
        extern int amii_statAPen, amii_statBPen;
        char *t = strtok(bufp, ",/");
        if(t)
        {
            sscanf(t, "%d", &amii_statAPen);
            if(t = strtok((char*)0, ",/"))
                sscanf(t, "%d", &amii_statBPen);
        }
    } else if (match_varname(buf, "OTHERPENS", 9)) {
        extern int amii_otherAPen, amii_otherBPen;
        char *t = strtok(bufp, ",/");
        if(t)
        {
            sscanf(t, "%d", &amii_otherAPen);
            if(t = strtok((char*)0, ",/"))
                sscanf(t, "%d", &amii_otherBPen);
        }
    } else if (match_varname(buf, "PENS", 4)) {
        extern unsigned short amii_init_map[ AMII_MAXCOLORS ];
        int i;
        char *t;
        for (i = 0, t = strtok(bufp, ",/");
            i < AMII_MAXCOLORS && t != (char *)0;
            t = strtok((char *)0, ",/"), ++i)
        {
            sscanf(t, "%hx", &amii_init_map[i]);
        }
        amii_setpens(amii_numcolors = i);
    } else if (match_varname(buf, "FGPENS", 6)) {
        extern int foreg[ AMII_MAXCOLORS ];
        int i;
        char *t;
        for (i = 0, t = strtok(bufp, ",/");
            i < AMII_MAXCOLORS && t != (char *)0;
            t = strtok((char *)0, ",/"), ++i)
        {
            sscanf(t, "%d", &foreg[i]);
        }
    } else if (match_varname(buf, "BGPENS", 6)) {
        extern int backg[ AMII_MAXCOLORS ];
        int i;
        char *t;
        for (i = 0, t = strtok(bufp, ",/");
            i < AMII_MAXCOLORS && t != (char *)0;
            t = strtok((char *)0, ",/"), ++i)
        {
            sscanf(t, "%d", &backg[i]);
        }
#endif
#ifdef USER_SOUNDS
    } else if (match_varname(buf, "SOUNDDIR", 8)) {
        sounddir = (char *)strdup(bufp);
    } else if (match_varname(buf, "SOUND", 5)) {
        add_sound_mapping(bufp);
#endif
#ifdef QT_GRAPHICS
    /* These should move to wc_ options */
    } else if (match_varname(buf, "QT_TILEWIDTH", 12)) {
        extern char *qt_tilewidth;
        if (qt_tilewidth == NULL)
            qt_tilewidth=(char *)strdup(bufp);
    } else if (match_varname(buf, "QT_TILEHEIGHT", 13)) {
        extern char *qt_tileheight;
        if (qt_tileheight == NULL)
            qt_tileheight=(char *)strdup(bufp);
    } else if (match_varname(buf, "QT_FONTSIZE", 11)) {
        extern char *qt_fontsize;
        if (qt_fontsize == NULL)
            qt_fontsize=(char *)strdup(bufp);
    } else if (match_varname(buf, "QT_COMPACT", 10)) {
        extern int qt_compact_mode;
        qt_compact_mode = atoi(bufp);
#endif
    } else
        return 0;
    return 1;
}
void read_config_file (char * filename) const
Definition at line 1979 of file files.c.
References bones, buf, BUFSZ, fopen_config_file(), fp, levels, parse_config_line(), PATHLEN, permbones, ramdisk, set_duplicate_opt_detection(), Strcpy, tmp_levels, tmp_ramdisk, TRUE, and wait_synch.
Referenced by initoptions().
{
#define tmp_levels (char *)0
#define tmp_ramdisk (char *)0
#if defined(MICRO) || defined(WIN32)
#undef tmp_levels
    char tmp_levels[PATHLEN];
# ifdef MFLOPPY
# ifndef AMIGA
#undef tmp_ramdisk
    char tmp_ramdisk[PATHLEN];
# endif
# endif
#endif
    char buf[4*BUFSZ];
    FILE *fp;
    if (!(fp = fopen_config_file(filename))) return;
#if defined(MICRO) || defined(WIN32)
# ifdef MFLOPPY
# ifndef AMIGA
    tmp_ramdisk[0] = 0;
# endif
# endif
    tmp_levels[0] = 0;
#endif
    /* begin detection of duplicate configfile options */
    set_duplicate_opt_detection(1);
    while (fgets(buf, 4*BUFSZ, fp)) {
        if (!parse_config_line(fp, buf, tmp_ramdisk, tmp_levels)) {
            raw_printf("Bad option line: \"%.50s\"", buf);
            wait_synch();
        }
    }
    (void) fclose(fp);
    
    /* turn off detection of duplicate configfile options */
    set_duplicate_opt_detection(0);
#if defined(MICRO) && !defined(NOCWD_ASSUMPTIONS)
    /* should be superseded by fqn_prefix[] */
# ifdef MFLOPPY
    Strcpy(permbones, tmp_levels);
# ifndef AMIGA
    if (tmp_ramdisk[0]) {
        Strcpy(levels, tmp_ramdisk);
        if (strcmp(permbones, levels)) /* if not identical */
            ramdisk = TRUE;
    } else
# endif /* AMIGA */
        Strcpy(levels, tmp_levels);
    Strcpy(bones, levels);
# endif /* MFLOPPY */
#endif /* MICRO */
    return;
}
int restore_saved_game ()
Definition at line 919 of file files.c.
References close(), delete_savefile(), fqname(), open_savefile(), SAVEF, SAVEPREFIX, set_savefile_name(), uncompress(), and uptodate().
Referenced by MAIN(), and main().
{
    const char *fq_save;
    int fd;
    set_savefile_name();
#ifdef MFLOPPY
    if (!saveDiskPrompt(1))
        return -1;
#endif /* MFLOPPY */
    fq_save = fqname(SAVEF, SAVEPREFIX, 0);
    uncompress(fq_save);
    if ((fd = open_savefile()) < 0) return fd;
    if (!uptodate(fd, fq_save)) {
        (void) close(fd), fd = -1;
        (void) delete_savefile();
    }
    return fd;
}
STATIC_OVL char* set_bonesfile_name (char * file, d_level * lev)
Definition at line 610 of file files.c.
References s_level::boneid, dungeon::boneid, d_level::dlevel, d_level::dnum, dungeons, eos(), Role::filecode, Sprintf, Strcat, and urole.
Referenced by commit_bonesfile(), create_bonesfile(), delete_bonesfile(), and open_bonesfile().
{
    s_level *sptr;
    char *dptr;
    Sprintf(file, "bon%c%s", dungeons[lev->dnum].boneid,
            In_quest(lev) ? urole.filecode : "0");
    dptr = eos(file);
    if ((sptr = Is_special(lev)) != 0)
        Sprintf(dptr, ".%c", sptr->boneid);
    else
        Sprintf(dptr, ".%d", lev->dlevel);
#ifdef VMS
    Strcat(dptr, ";1");
#endif
    return(dptr-2);
}
STATIC_OVL char* set_bonestemp_name ()
Definition at line 637 of file files.c.
References eos(), lock, rindex, Sprintf, and Strcat.
Referenced by commit_bonesfile(), and create_bonesfile().
{
    char *tf;
    tf = rindex(lock, '.');
    if (!tf) tf = eos(lock);
    Sprintf(tf, ".bn");
#ifdef VMS
    Strcat(tf, ";1");
#endif
    return lock;
}
void set_levelfile_name (char * file, int lev)
Definition at line 406 of file files.c.
References eos(), rindex, Sprintf, and Strcat.
Referenced by create_levelfile(), delete_levelfile(), eraseoldlocks(), getlock(), open_levelfile(), and veryold().
{
    char *tf;
    tf = rindex(file, '.');
    if (!tf) tf = eos(file);
    Sprintf(tf, ".%d", lev);
#ifdef VMS
    Strcat(tf, ";1");
#endif
    return;
}
void set_savefile_name ()
Definition at line 784 of file files.c.
References BUFSZ, FILENAME, fname_encode(), get_username(), getuid(), PATHLEN, plname, regularize, SAVEF, Sprintf, Strcat, and Strcpy.
Referenced by process_openfile(), and restore_saved_game().
{
#if defined(WIN32)
    char fnamebuf[BUFSZ], encodedfnamebuf[BUFSZ];
#endif
#ifdef VMS
    Sprintf(SAVEF, "[.save]%d%s", getuid(), plname);
    regularize(SAVEF+7);
    Strcat(SAVEF, ";1");
#else
# if defined(MICRO)
    Strcpy(SAVEF, SAVEP);
# ifdef AMIGA
    strncat(SAVEF, bbs_id, PATHLEN);
# endif
    {
        int i = strlen(SAVEP);
# ifdef AMIGA
        /* plname has to share space with SAVEP and ".sav" */
        (void)strncat(SAVEF, plname, FILENAME - i - 4);
# else
        (void)strncat(SAVEF, plname, 8);
# endif
        regularize(SAVEF+i);
    }
    Strcat(SAVEF, ".sav");
# else
# if defined(WIN32)
    /* Obtain the name of the logged on user and incorporate
     * it into the name. */
    Sprintf(fnamebuf, "%s-%s", get_username(0), plname);
    (void)fname_encode("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_-.",
                '%', fnamebuf, encodedfnamebuf, BUFSZ);
    Sprintf(SAVEF, "%s.NetHack-saved-game", encodedfnamebuf);
# else
    Sprintf(SAVEF, "save/%d%s", (int)getuid(), plname);
    regularize(SAVEF+5); /* avoid . or / in name */
# endif /* WIN32 */
# endif /* MICRO */
#endif /* VMS */
}
void uncompress (char * filename) const
Definition at line 1227 of file files.c.
References TRUE.
Referenced by dosave0(), open_bonesfile(), and restore_saved_game().
{
#ifndef COMPRESS
#if (defined(macintosh) && (defined(__SC__) || defined(__MRC__))) || defined(__MWERKS__)
# pragma unused(filename)
#endif
#else
    docompress_file(filename, TRUE);
#endif
}
void unlock_file (char * filename) const
Definition at line 1411 of file files.c.
References BUFSZ, Close, close(), DeleteFile, fqname(), HUP, LOCKPREFIX, make_lockname(), and unlink().
Referenced by getlock(), and topten().
{
    char locknambuf[BUFSZ];
    const char *lockname;
    if (nesting == 1) {
        lockname = make_lockname(filename, locknambuf);
#ifndef NO_FILE_LINKS /* LOCKDIR should be subsumed by LOCKPREFIX */
        lockname = fqname(lockname, LOCKPREFIX, 2);
#endif
#if defined(UNIX) || defined(VMS)
        if (unlink(lockname) < 0)
            HUP raw_printf("Can't unlink %s.", lockname);
# ifdef NO_FILE_LINKS
        (void) close(lockfd);
# endif
#endif /* UNIX || VMS */
#if defined(AMIGA) || defined(WIN32) || defined(MSDOS)
        if (lockptr) Close(lockptr);
        DeleteFile(lockname);
        lockptr = 0;
#endif /* AMIGA || WIN32 || MSDOS */
    }
    nesting--;
}
int validate_prefix_locations (char * reasonbuf)
Definition at line 307 of file files.c.
References BUFSZ, CONFIGPREFIX, DATAPREFIX, errno, filename, fp, fqn_prefix, fqname(), paniclog(), PREFIX_COUNT, Sprintf, Strcat, and unlink().
{
#if defined(NOCWD_ASSUMPTIONS)
    FILE *fp;
    const char *filename;
    int prefcnt, failcount = 0;
    char panicbuf1[BUFSZ], panicbuf2[BUFSZ], *details;
    if (reasonbuf) reasonbuf[0] = '\0';
    for (prefcnt = 1; prefcnt < PREFIX_COUNT; prefcnt++) {
        /* don't test writing to configdir or datadir; they're readonly */
        if (prefcnt == CONFIGPREFIX || prefcnt == DATAPREFIX) continue;
        filename = fqname("validate", prefcnt, 3);
        if ((fp = fopen(filename, "w"))) {
            fclose(fp);
            (void) unlink(filename);
        } else {
            if (reasonbuf) {
                if (failcount) Strcat(reasonbuf,", ");
                Strcat(reasonbuf, fqn_prefix_names[prefcnt]);
            }
            /* the paniclog entry gets the value of errno as well */
            Sprintf(panicbuf1,"Invalid %s", fqn_prefix_names[prefcnt]);
#if defined (NHSTDC) && !defined(NOTSTDC)
            if (!(details = strerror(errno)))
#endif
            details = "";
            Sprintf(panicbuf2,"\"%s\", (%d) %s",
                fqn_prefix[prefcnt], errno, details);
            paniclog(panicbuf1, panicbuf2);
            failcount++;
        }
    }
    if (failcount)
        return 0;
    else
#endif
    return 1;
}
Variable Documentation
char bones[] = `bonesnn.xxx`
Definition at line 60 of file files.c.
Referenced by commit_bonesfile(), compress_bonesfile(), create_bonesfile(), delete_bonesfile(), getbones(), open_bonesfile(), read_config_file(), and savebones().
const char* configfile
Initial value:
=
            "NetHack.cnf"
Definition at line 1450 of file files.c.
int errno
Definition at line 345 of file celib.c.
Referenced by bitmap_to_img(), c__translate(), create_bonesfile(), create_levelfile(), fopen_config_file(), getlock(), gettty(), lock_file(), open_levelfile(), ReadImageFiles(), restore_savefile(), setctty(), validate_prefix_locations(), and vms_open().
char lock[PL_NSIZ+14] = `1lock`
Definition at line 61 of file files.c.
Referenced by create_bonesfile(), create_levelfile(), delete_levelfile(), open_levelfile(), and set_bonestemp_name().
int n_dgns
Referenced by mk_knox_portal().
int nesting = 0 [static]
Definition at line 1244 of file files.c.
char SAVEF[SAVESIZE]
Definition at line 91 of file files.c.
Referenced by create_savefile(), delete_savefile(), open_savefile(), restore_saved_game(), and set_savefile_name().