nethack/src/fountain.c File Reference
#include `hack.h`
*
Functions
STATIC_DCL void NDECL (dowatersnakes)
STATIC_DCL void NDECL (dowaterdemon)
STATIC_DCL void NDECL (dowaternymph)
STATIC_PTR void FDECL (gush,(int, int, genericptr_t))
STATIC_DCL void NDECL (dofindgem)
void floating_above (char *what) const
STATIC_OVL void dowatersnakes ()
STATIC_OVL void dowaterdemon ()
STATIC_OVL void dowaternymph ()
void dogushforth (int drinking)
STATIC_PTR void gush (int x, int y, genericptr_t poolcnt)
STATIC_OVL void dofindgem ()
void dryup (xchar x, xchar y, boolean isyou)
void drinkfountain ()
void dipfountain (struct obj *obj)
Function Documentation
void dipfountain (struct obj * obj)
Definition at line 351 of file fountain.c.
References A_LAWFUL, A_WIS, ARM, Blind, CLEAR_FOUNTAIN_LOOTED, COIN_CLASS, dofindgem(), dogushforth(), dowaterdemon(), dowaternymph(), dowatersnakes(), dryup(), FALSE, dlevel_t::flags, floating_above(), FOUNTAIN_IS_LOOTED, invent, level, Levitation, levl, min, newsym(), levelflags::nfountains, obj::nobj, objects, objclass::oc_cost, obj::oclass, otmp, obj::otyp, obj::quan, ROOM, SET_FOUNTAIN_LOOTED, TRUE, align::type, u, you::ualign, you::ugold, you::ulevel, update_inventory, you::ux, you::uy, and you::uz.
{
    if (Levitation) {
        floating_above("fountain");
        return;
    }
    /* Don't grant Excalibur when there's more than one object. */
    /* (quantity could be > 1 if merged daggers got polymorphed) */
    if (obj->otyp == LONG_SWORD && obj->quan == 1L
        && u.ulevel >= 5 && !rn2(6)
        && !obj->oartifact
        && !exist_artifact(LONG_SWORD, artiname(ART_EXCALIBUR))) {
        if (u.ualign.type != A_LAWFUL) {
            /* Ha! Trying to cheat her. */
            pline("A freezing mist rises from the water and envelopes the sword.");
            pline_The("fountain disappears!");
            curse(obj);
            if (obj->spe > -6 && !rn2(3)) obj->spe--;
            obj->oerodeproof = FALSE;
            exercise(A_WIS, FALSE);
        } else {
            /* The lady of the lake acts! - Eric Backus */
            /* Be *REAL* nice */
      pline("From the murky depths, a hand reaches up to bless the sword.");
            pline("As the hand retreats, the fountain disappears!");
            obj = oname(obj, artiname(ART_EXCALIBUR));
            discover_artifact(ART_EXCALIBUR);
            bless(obj);
            obj->oeroded = obj->oeroded2 = 0;
            obj->oerodeproof = TRUE;
            exercise(A_WIS, TRUE);
        }
        update_inventory();
        levl[u.ux][u.uy].typ = ROOM;
        levl[u.ux][u.uy].looted = 0;
        newsym(u.ux, u.uy);
        level.flags.nfountains--;
        if(in_town(u.ux, u.uy))
            (void) angry_guards(FALSE);
        return;
    } else if (get_wet(obj) && !rn2(2))
        return;
    /* Acid and water don't mix */
    if (obj->otyp == POT_ACID) {
        useup(obj);
        return;
    }
    switch (rnd(30)) {
        case 16: /* Curse the item */
            curse(obj);
            break;
        case 17:
        case 18:
        case 19:
        case 20: /* Uncurse the item */
            if(obj->cursed) {
                if (!Blind)
                pline_The("water glows for a moment.");
                uncurse(obj);
            } else {
                pline("A feeling of loss comes over you.");
            }
            break;
        case 21: /* Water Demon */
            dowaterdemon();
            break;
        case 22: /* Water Nymph */
            dowaternymph();
            break;
        case 23: /* an Endless Stream of Snakes */
            dowatersnakes();
            break;
        case 24: /* Find a gem */
            if (!FOUNTAIN_IS_LOOTED(u.ux,u.uy)) {
                dofindgem();
                break;
            }
        case 25: /* Water gushes forth */
            dogushforth(FALSE);
            break;
        case 26: /* Strange feeling */
            pline("A strange tingling runs up your %s.",
                            body_part(ARM));
            break;
        case 27: /* Strange feeling */
            You_feel("a sudden chill.");
            break;
        case 28: /* Strange feeling */
            pline("An urge to take a bath overwhelms you.");
#ifndef GOLDOBJ
            if (u.ugold > 10) {
                u.ugold -= somegold() / 10;
                You("lost some of your gold in the fountain!");
                CLEAR_FOUNTAIN_LOOTED(u.ux,u.uy);
                exercise(A_WIS, FALSE);
            }
#else
            {
                long money = money_cnt(invent);
                struct obj *otmp;
                            if (money > 10) {
                /* Amount to loose. Might get rounded up as fountains don't pay change... */
                    money = somegold(money) / 10;
                    for (otmp = invent; otmp && money > 0; otmp = otmp->
      nobj) if (otmp->oclass == COIN_CLASS) {
                    int denomination = objects[otmp->otyp].oc_cost;
                    long coin_loss = (money + denomination - 1) / denomination;
                                    coin_loss = min(coin_loss, otmp->quan);
                    otmp->quan -= coin_loss;
                    money -= coin_loss * denomination;
                    if (!otmp->quan) delobj(otmp);
                }
                    You("lost some of your money in the fountain!");
                CLEAR_FOUNTAIN_LOOTED(u.ux,u.uy);
                    exercise(A_WIS, FALSE);
                            }
            }
#endif
            break;
        case 29: /* You see coins */
        /* We make fountains have more coins the closer you are to the
         * surface. After all, there will have been more people going
         * by. Just like a shopping mall! Chris Woodbury */
            if (FOUNTAIN_IS_LOOTED(u.ux,u.uy)) break;
            SET_FOUNTAIN_LOOTED(u.ux,u.uy);
            (void) mkgold((long)
            (rnd((dunlevs_in_dungeon(&u.uz)-dunlev(&u.uz)+1)*2)+5),
            u.ux, u.uy);
            if (!Blind)
        pline("Far below you, you see coins glistening in the water.");
            exercise(A_WIS, TRUE);
            newsym(u.ux,u.uy);
            break;
    }
    update_inventory();
    dryup(u.ux, u.uy, TRUE);
}
STATIC_OVL void dofindgem ()
Definition at line 137 of file fountain.c.
References A_WIS, Blind, FALSE, newsym(), SET_FOUNTAIN_LOOTED, TRUE, u, you::ux, and you::uy.
Referenced by dipfountain(), and drinkfountain().
{
    if (!Blind) You("spot a gem in the sparkling waters!");
    else You_feel("a gem here!");
    (void) mksobj_at(rnd_class(DILITHIUM_CRYSTAL, LUCKSTONE-1),
             u.ux, u.uy, FALSE, FALSE);
    SET_FOUNTAIN_LOOTED(u.ux,u.uy);
    newsym(u.ux, u.uy);
    exercise(A_WIS, TRUE); /* a discovery! */
}
void dogushforth (int drinking)
Definition at line 90 of file fountain.c.
References do_clear_area(), gush(), u, you::ux, and you::uy.
Referenced by dipfountain(), and drinkfountain().
{
    int madepool = 0;
    do_clear_area(u.ux, u.uy, 7, gush, (genericptr_t)&madepool);
    if (!madepool) {
        if (drinking)
        Your("thirst is quenched.");
        else
        pline("Water sprays all over you.");
    }
}
STATIC_OVL void dowaterdemon ()
Definition at line 44 of file fountain.c.
References Blind, G_GONE, mhe, mhis, mons, monst::mx, monst::my, NO_MM_FLAGS, u, you::ux, and you::uy.
Referenced by dipfountain(), and drinkfountain().
{
    register struct monst *mtmp;
    if(!(mvitals[PM_WATER_DEMON].mvflags & G_GONE)) {
    if((mtmp = makemon(&mons[PM_WATER_DEMON],u.ux,u.uy, NO_MM_FLAGS))) {
        if (!Blind)
        You("unleash %s!", a_monnam(mtmp));
        else
        You_feel("the presence of evil.");
    /* Give those on low levels a (slightly) better chance of survival */
        if (rnd(100) > (80 + level_difficulty())) {
        pline("Grateful for %s release, %s grants you a wish!",
              mhis(mtmp), mhe(mtmp));
        makewish();
        mongone(mtmp);
        } else if (t_at(mtmp->mx, mtmp->my))
        (void) mintrap(mtmp);
    }
    } else
    pline_The("fountain bubbles furiously for a moment, then calms.");
}
STATIC_OVL void dowaternymph ()
Definition at line 69 of file fountain.c.
References Blind, G_GONE, mons, monst::mx, monst::my, NO_MM_FLAGS, u, you::ux, and you::uy.
Referenced by dipfountain(), and drinkfountain().
{
    register struct monst *mtmp;
    if(!(mvitals[PM_WATER_NYMPH].mvflags & G_GONE) &&
       (mtmp = makemon(&mons[PM_WATER_NYMPH],u.ux,u.uy, NO_MM_FLAGS))) {
        if (!Blind)
           You("attract %s!", a_monnam(mtmp));
        else
           You_hear("a seductive voice.");
        mtmp->msleeping = 0;
        if (t_at(mtmp->mx, mtmp->my))
            (void) mintrap(mtmp);
    } else
        if (!Blind)
           pline("A large bubble rises to the surface and pops.");
        else
           You_hear("a loud pop.");
}
STATIC_OVL void dowatersnakes ()
Definition at line 23 of file fountain.c.
References Blind, G_GONE, Hallucination, mons, monst::mx, monst::my, NO_MM_FLAGS, rn1, something, u, you::ux, and you::uy.
Referenced by dipfountain(), and drinkfountain().
{
    register int num = rn1(5,2);
    struct monst *mtmp;
    if (!(mvitals[PM_WATER_MOCCASIN].mvflags & G_GONE)) {
    if (!Blind)
        pline("An endless stream of %s pours forth!",
          Hallucination ? makeplural(rndmonnam()) : "snakes");
    else
        You_hear("%s hissing!", something);
    while(num-- > 0)
        if((mtmp = makemon(&mons[PM_WATER_MOCCASIN],
            u.ux, u.uy, NO_MM_FLAGS)) && t_at(mtmp->mx, mtmp->
      my))
        (void) mintrap(mtmp);
    } else
    pline_The("fountain bubbles furiously for a moment, then calms.");
}
void drinkfountain ()
Definition at line 195 of file fountain.c.
References A_CON, A_MAX, A_WIS, ABASE, AMAX, Blind, flag::botl, DEADMONSTER, display_nhwindow, dofindgem(), dogushforth(), dowaterdemon(), dowaternymph(), dowatersnakes(), dryup(), FALSE, flags, floating_above(), fmon, FOUNTAIN_IS_LOOTED, FROMOUTSIDE, HSee_invisible, invent, Invisible, KILLED_BY, KILLED_BY_AN, Levitation, levl, monster_detect(), newsym(), monst::nmon, obj::nobj, Poison_resistance, rn1, TRUE, u, you::uhunger, you::uluck, you::ux, you::uy, and WIN_MESSAGE.
{
    /* What happens when you drink from a fountain? */
    register boolean mgkftn = (levl[u.ux][u.uy].blessedftn == 1);
    register int fate = rnd(30);
    if (Levitation) {
        floating_above("fountain");
        return;
    }
    if (mgkftn && u.uluck >= 0 && fate >= 10) {
        int i, ii, littleluck = (u.uluck < 4);
        pline("Wow! This makes you feel great!");
        /* blessed restore ability */
        for (ii = 0; ii < A_MAX; ii++)
            if (ABASE(ii) < AMAX(ii)) {
            ABASE(ii) = AMAX(ii);
            flags.botl = 1;
            }
        /* gain ability, blessed if "natural" luck is high */
        i = rn2(A_MAX); /* start at a random attribute */
        for (ii = 0; ii < A_MAX; ii++) {
            if (adjattrib(i, 1, littleluck ? -1 : 0) && littleluck)
            break;
            if (++i >= A_MAX) i = 0;
        }
        display_nhwindow(WIN_MESSAGE, FALSE);
        pline("A wisp of vapor escapes the fountain...");
        exercise(A_WIS, TRUE);
        levl[u.ux][u.uy].blessedftn = 0;
        return;
    }
    if (fate < 10) {
        pline_The("cool draught refreshes you.");
        u.uhunger += rnd(10); /* don't choke on water */
        newuhs(FALSE);
        if(mgkftn) return;
    } else {
        switch (fate) {
        case 19: /* Self-knowledge */
            You_feel("self-knowledgeable...");
            display_nhwindow(WIN_MESSAGE, FALSE);
            enlightenment(0);
            exercise(A_WIS, TRUE);
            pline_The("feeling subsides.");
            break;
        case 20: /* Foul water */
            pline_The("water is foul! You gag and vomit.");
            morehungry(rn1(20, 11));
            vomit();
            break;
        case 21: /* Poisonous */
            pline_The("water is contaminated!");
            if (Poison_resistance) {
               pline(
                  "Perhaps it is runoff from the nearby %s farm.",
                 fruitname(FALSE));
               losehp(rnd(4),"unrefrigerated sip of juice",
                KILLED_BY_AN);
               break;
            }
            losestr(rn1(4,3));
            losehp(rnd(10),"contaminated water", KILLED_BY);
            exercise(A_CON, FALSE);
            break;
        case 22: /* Fountain of snakes! */
            dowatersnakes();
            break;
        case 23: /* Water demon */
            dowaterdemon();
            break;
        case 24: /* Curse an item */ {
            register struct obj *obj;
            pline("This water's no good!");
            morehungry(rn1(20, 11));
            exercise(A_CON, FALSE);
            for(obj = invent; obj ; obj = obj->nobj)
                if (!rn2(5)) curse(obj);
            break;
            }
        case 25: /* See invisible */
            if (Blind) {
                if (Invisible) {
                You("feel transparent.");
                } else {
                    You("feel very self-conscious.");
                    pline("Then it passes.");
                }
            } else {
               You("see an image of someone stalking you.");
               pline("But it disappears.");
            }
            HSee_invisible |= FROMOUTSIDE;
            newsym(u.ux,u.uy);
            exercise(A_WIS, TRUE);
            break;
        case 26: /* See Monsters */
            (void) monster_detect((struct obj *)0, 0);
            exercise(A_WIS, TRUE);
            break;
        case 27: /* Find a gem in the sparkling waters. */
            if (!FOUNTAIN_IS_LOOTED(u.ux,u.uy)) {
                dofindgem();
                break;
            }
        case 28: /* Water Nymph */
            dowaternymph();
            break;
        case 29: /* Scare */ {
            register struct monst *mtmp;
            pline("This water gives you bad breath!");
            for(mtmp = fmon; mtmp; mtmp = mtmp->nmon)
                if(!DEADMONSTER(mtmp))
                monflee(mtmp, 0, FALSE, FALSE);
            }
            break;
        case 30: /* Gushing forth in this room */
            dogushforth(TRUE);
            break;
        default:
            pline("This tepid water is tasteless.");
            break;
        }
    }
    dryup(u.ux, u.uy, TRUE);
}
void dryup (xchar x, xchar y, boolean isyou)
Definition at line 149 of file fountain.c.
References cansee, couldsee, monst::data, DEADMONSTER, FALSE, dlevel_t::flags, fmon, FOUNTAIN_IS_WARNED, IS_FOUNTAIN, level, levl, mons, monst::mx, monst::my, newsym(), levelflags::nfountains, monst::nmon, ROOM, SET_FOUNTAIN_WARNED, wizard, and yn.
Referenced by dipfountain(), and drinkfountain().
{
    if (IS_FOUNTAIN(levl[x][y].typ) &&
        (!rn2(3) || FOUNTAIN_IS_WARNED(x,y))) {
        if(isyou && in_town(x, y) && !FOUNTAIN_IS_WARNED(x,y)) {
            struct monst *mtmp;
            SET_FOUNTAIN_WARNED(x,y);
            /* Warn about future fountain use. */
            for(mtmp = fmon; mtmp; mtmp = mtmp->nmon) {
                if (DEADMONSTER(mtmp)) continue;
                if ((mtmp->data == &mons[PM_WATCHMAN] ||
                mtmp->data == &mons[PM_WATCH_CAPTAIN]) &&
                   couldsee(mtmp->mx, mtmp->my) &&
                   mtmp->mpeaceful) {
                pline("%s yells:", Amonnam(mtmp));
                verbalize("Hey, stop using that fountain!");
                break;
                }
            }
            /* You can see or hear this effect */
            if(!mtmp) pline_The("flow reduces to a trickle.");
            return;
        }
#ifdef WIZARD
        if (isyou && wizard) {
            if (yn("Dry up fountain?") == 'n')
                return;
        }
#endif
        /* replace the fountain with ordinary floor */
        levl[x][y].typ = ROOM;
        levl[x][y].looted = 0;
        levl[x][y].blessedftn = 0;
        if (cansee(x,y)) pline_The("fountain dries up!");
        /* The location is seen if the hero/monster is invisible */
        /* or felt if the hero is blind. */
        newsym(x, y);
        level.flags.nfountains--;
        if(isyou && in_town(x, y))
            (void) angry_guards(FALSE);
    }
}
STATIC_PTR void FDECL (gush , (int, int, genericptr_t))
void floating_above (char * what) const
Definition at line 16 of file fountain.c.
Referenced by dipfountain(), and drinkfountain().
{
    You("are floating high above the %s.", what);
}
STATIC_PTR void gush (int x, int y, genericptr_t poolcnt)
Definition at line 105 of file fountain.c.
References FALSE, level, levl, m_at, newsym(), dlevel_t::objects, POOL, ROOM, TRUE, u, you::ux, you::uy, trap::x, and trap::y.
Referenced by dogushforth().
{
    register struct monst *mtmp;
    register struct trap *ttmp;
    if (((x+y)%2) || (x == u.ux && y == u.uy) ||
        (rn2(1 + distmin(u.ux, u.uy, x, y))) ||
        (levl[x][y].typ != ROOM) ||
        (sobj_at(BOULDER, x, y)) || nexttodoor(x, y))
        return;
    if ((ttmp = t_at(x, y)) != 0 && !delfloortrap(ttmp))
        return;
    if (!((*(int *)poolcnt)++))
        pline("Water gushes forth from the overflowing fountain!");
    /* Put a pool at x, y */
    levl[x][y].typ = POOL;
    /* No kelp! */
    del_engr_at(x, y);
    water_damage(level.objects[x][y], FALSE, TRUE);
    if ((mtmp = m_at(x, y)) != 0)
        (void) minliquid(mtmp);
    else
        newsym(x,y);
}
STATIC_DCL void NDECL (dowatersnakes)
STATIC_DCL void NDECL (dowaterdemon)
STATIC_DCL void NDECL (dowaternymph)
STATIC_DCL void NDECL (dofindgem)