nethack/win/gnome/gnaskstr.h File Reference
Functions
int ghack_ask_string_dialog (const char *szMessageStr, const char *szDefaultStr, const char *szTitleStr, char *buffer)
Function Documentation
int ghack_ask_string_dialog (const char * szMessageStr, const char * szDefaultStr, const char * szTitleStr, char * buffer)
Definition at line 21 of file gnaskstr.c.
References FALSE, ghack_ask_string_callback(), ghack_get_main_window(), NULL, and TRUE.
Referenced by gnome_askname(), and gnome_getlin().
{
    int i;
    GtkWidget* dialog;
    gchar *user_text = NULL;
    dialog = gnome_request_dialog(FALSE, szMessageStr,
                      szDefaultStr, 0,
                  ghack_ask_string_callback,
                  &user_text, NULL);
    g_assert(dialog != NULL);
    gtk_window_set_title(GTK_WINDOW(dialog), szTitleStr);
    gnome_dialog_set_default(GNOME_DIALOG(dialog), 0);
    gtk_window_set_modal(GTK_WINDOW(dialog), TRUE);
    gnome_dialog_set_parent (GNOME_DIALOG (dialog),
        GTK_WINDOW (ghack_get_main_window ()));
    i = gnome_dialog_run_and_close (GNOME_DIALOG (dialog));
    
    /* Quit */
    if (i != 0 || user_text == NULL) {
    if (user_text)
      g_free(user_text);
    return -1;
    }
    if (*user_text == 0) {
      g_free(user_text);
      return -1;
    }
    g_assert(strlen(user_text) > 0);
    strcpy (buffer, user_text);
    g_free(user_text);
    return 0;
}