nethack/win/gnome/gnbind.h File Reference
#include <gnome.h>
*
#include <gdk/gdkkeysyms.h>
*
#include `gnomeprv.h`
*
#include `gnmain.h`
*
#include `gnmap.h`
*
#include `gnmenu.h`
*
#include `gnplayer.h`
*
#include `gnsignal.h`
*
#include `gnstatus.h`
*
#include `gntext.h`
*
#include `gnmesg.h`
*
#include `gnyesno.h`
*
#include `gnglyph.h`
*
#include `gnworn.h`
*
Data Structures
struct gnome_nhwindow_data
Macros
#define MAXWINDOWS 15
Typedefs
typedef struct gnome_nhwindow_data GNHWinData
Functions
void gnome_init_nhwindows (int *argc, char **argv)
void gnome_player_selection (void)
void gnome_askname (void)
void gnome_get_nh_event (void)
void gnome_exit_nhwindows (const char *)
void gnome_suspend_nhwindows (const char *)
void gnome_resume_nhwindows (void)
winid gnome_create_nhwindow (int type)
void gnome_create_nhwindow_by_id (int type, winid i)
void gnome_clear_nhwindow (winid wid)
void gnome_display_nhwindow (winid wid, BOOLEAN_P block)
void gnome_destroy_nhwindow (winid wid)
void gnome_curs (winid wid, int x, int y)
void gnome_putstr (winid wid, int attr, const char *text)
void gnome_display_file (const char *filename, BOOLEAN_P must_exist)
void gnome_start_menu (winid wid)
void gnome_add_menu (winid wid, int glyph, const ANY_P *identifier, CHAR_P accelerator, CHAR_P group_accel, int attr, const char *str, BOOLEAN_P presel)
void gnome_end_menu (winid wid, const char *prompt)
int gnome_select_menu (winid wid, int how, MENU_ITEM_P **selected)
void gnome_update_inventory (void)
void gnome_mark_synch (void)
void gnome_wait_synch (void)
void gnome_cliparound (int x, int y)
void gnome_cliparound_proper (winid wid, int x, int y)
void gnome_print_glyph (winid wid, XCHAR_P x, XCHAR_P y, int glyph)
void gnome_raw_print (const char *str)
void gnome_raw_print_bold (const char *str)
int gnome_nhgetch (void)
int gnome_nh_poskey (int *x, int *y, int *mod)
void gnome_nhbell (void)
int gnome_doprev_message (void)
char gnome_yn_function (const char *question, const char *choices, CHAR_P def)
void gnome_getlin (const char *question, char *input)
int gnome_get_ext_cmd (void)
void gnome_number_pad (int state)
void gnome_delay_output (void)
void gnome_start_screen (void)
void gnome_end_screen (void)
void gnome_outrip (winid wid, int how)
void gnome_delete_nhwindow_by_reference (GtkWidget *menuWin)
Macro Definition Documentation
#define MAXWINDOWS 15
Definition at line 33 of file gnbind.h.
Typedef Documentation
typedef struct gnome_nhwindow_data GNHWinData
Function Documentation
void gnome_add_menu (winid wid, int glyph, const ANY_P * identifier, CHAR_P accelerator, CHAR_P group_accel, int attr, const char * str, BOOLEAN_P presel)
Definition at line 718 of file gnbind.c.
References _GHackMenuItem::accelerator, _GHackMenuItem::attr, ghack_signals, GHSIG_ADD_MENU, _GHackMenuItem::glyph, _GHackMenuItem::group_accel, _GHackMenuItem::identifier, NULL, _GHackMenuItem::presel, and _GHackMenuItem::str.
{
  GHackMenuItem item;
  item.glyph = glyph;
  item.identifier = identifier;
  item.accelerator = accelerator;
  item.group_accel = group_accel;
  item.attr = attr;
  item.str = str;
  item.presel = presel;
  if (wid != -1 && gnome_windowlist[wid].win != NULL)
    {
      gtk_signal_emit(GTK_OBJECT (gnome_windowlist[wid].win),
               ghack_signals[GHSIG_ADD_MENU],
               &item);
    }
}
void gnome_askname (void)
Definition at line 342 of file gnbind.c.
References ghack_ask_string_dialog(), gnome_exit_nhwindows(), and plname.
{
    int ret;
    g_message("Asking name....");
    /* Ask for a name and stuff the response into plname, a nethack global */
    ret = ghack_ask_string_dialog("What is your name?", "gandalf",
        "GnomeHack", plname);
    /* Quit if they want to quit... */
    if (ret==-1)
      {
        gnome_exit_nhwindows(0);
      }
}
void gnome_clear_nhwindow (winid wid)
Definition at line 483 of file gnbind.c.
References ghack_signals, GHSIG_CLEAR, and NULL.
{
  if (gnome_windowlist[wid].win != NULL)
    {
      gtk_signal_emit (GTK_OBJECT (gnome_windowlist[wid].win),
               ghack_signals[GHSIG_CLEAR]);
    }
}
void gnome_cliparound (int x, int y)
Definition at line 833 of file gnbind.c.
References gnome_cliparound_proper(), and WIN_MAP.
{
  /* FIXME!!! winid should be a parameter!!!
   * Call a function that Does The Right Thing(tm).
  */
    gnome_cliparound_proper(WIN_MAP,x,y);
}
void gnome_cliparound_proper (winid wid, int x, int y)
Definition at line 841 of file gnbind.c.
References ghack_signals, GHSIG_CLIPAROUND, and NULL.
Referenced by gnome_cliparound().
{
    if (wid != -1 && gnome_windowlist[wid].win != NULL)
      {
    gtk_signal_emit(GTK_OBJECT (gnome_windowlist[wid].win),
             ghack_signals[GHSIG_CLIPAROUND],
             (guint) x,
             (guint) y);
      }
}
winid gnome_create_nhwindow (int type)
Definition at line 401 of file gnbind.c.
References gnome_create_nhwindow_by_id(), MAXWINDOWS, and NULL.
Referenced by gnome_init_nhwindows().
{
  winid i = 0;
/* Return the next available winid
 */
  for (i=0; i<MAXWINDOWS; i++)
      if (gnome_windowlist[i].win == NULL)
          break;
  if (i == MAXWINDOWS)
      g_error ("ERROR: No windows available...\n");
  gnome_create_nhwindow_by_id(type, i);
  return i;
}
void gnome_create_nhwindow_by_id (int type, winid i)
Definition at line 419 of file gnbind.c.
References ghack_init_map_window(), ghack_init_menu_window(), ghack_init_message_window(), ghack_init_status_window(), ghack_init_text_window(), ghack_init_worn_window(), ghack_main_window_add_map_window(), ghack_main_window_add_message_window(), ghack_main_window_add_status_window(), ghack_main_window_add_worn_window(), NHW_MAP, NHW_MENU, NHW_MESSAGE, NHW_STATUS, NHW_TEXT, NHW_WORN, gnome_nhwindow_data::type, and gnome_nhwindow_data::win.
Referenced by gnome_create_nhwindow(), and gnome_start_menu().
{
    switch (type)
      {
      case NHW_MAP:
    {
      gnome_windowlist[i].win = ghack_init_map_window();
      gnome_windowlist[i].type = NHW_MAP;
      ghack_main_window_add_map_window(
      gnome_windowlist[i].win);
      break;
    }
      case NHW_MESSAGE:
    {
      gnome_windowlist[i].win = ghack_init_message_window();
      gnome_windowlist[i].type = NHW_MESSAGE;
      ghack_main_window_add_message_window(
      gnome_windowlist[i].win);
      break;
    }
      case NHW_STATUS:
    {
      gnome_windowlist[i].win = ghack_init_status_window();
      gnome_windowlist[i].type = NHW_STATUS;
      ghack_main_window_add_status_window(
      gnome_windowlist[i].win);
      break;
    }
      case NHW_WORN:
    {
      gnome_windowlist[i].win = ghack_init_worn_window();
      gnome_windowlist[i].type = NHW_WORN;
      ghack_main_window_add_worn_window(
      gnome_windowlist[i].win);
      break;
    }
      case NHW_MENU:
    {
      gnome_windowlist[i].type = NHW_MENU;
      gnome_windowlist[i].win = ghack_init_menu_window();
      break;
    }
      case NHW_TEXT:
    {
      gnome_windowlist[i].win = ghack_init_text_window();
      gnome_windowlist[i].type = NHW_TEXT;
      break;
    }
      }
}
void gnome_curs (winid wid, int x, int y)
Definition at line 538 of file gnbind.c.
References ghack_signals, GHSIG_CURS, and NULL.
{
  if (wid != -1 && gnome_windowlist[wid].win != NULL)
    {
      gtk_signal_emit(GTK_OBJECT (gnome_windowlist[wid].win),
               ghack_signals[GHSIG_CURS], x, y);
    }
}
void gnome_delay_output (void)
Definition at line 1118 of file gnbind.c.
References ghack_signals, GHSIG_DELAY, NULL, and WIN_MESSAGE.
{
    if (gnome_windowlist[WIN_MESSAGE].win != NULL) {
    gtk_signal_emit(GTK_OBJECT (gnome_windowlist[WIN_MESSAGE].win),
    ghack_signals[GHSIG_DELAY],
    (guint) 50);
    }
}
void gnome_delete_nhwindow_by_reference (GtkWidget * menuWin)
Definition at line 469 of file gnbind.c.
References MAXWINDOWS, NULL, gnome_nhwindow_data::type, and gnome_nhwindow_data::win.
Referenced by ghack_menu_destroy().
{
  int i;
  for (i = 0; i < MAXWINDOWS; i++) {
    if (gnome_windowlist[i].win == menuWin) {
      gnome_windowlist[i].win = NULL;
      gnome_windowlist[i].type = 0;
      break;
    }
  }
}
void gnome_destroy_nhwindow (winid wid)
Definition at line 517 of file gnbind.c.
References NULL, gnome_nhwindow_data::type, gnome_nhwindow_data::win, WIN_MAP, WIN_MESSAGE, and WIN_STATUS.
{
    if ((wid == WIN_MAP) ||
        (wid == WIN_MESSAGE) ||
        (wid == WIN_STATUS)) {
    /* no thanks, I'll do these myself */
    return;
    }
    if (wid != -1 && gnome_windowlist[wid].win != NULL)
      {
    gtk_widget_destroy(gnome_windowlist[wid].win);
    gnome_windowlist[wid].win = NULL;
    gnome_windowlist[wid].type = 0;
      }
}
void gnome_display_file (const char * filename, BOOLEAN_P must_exist)
Definition at line 586 of file gnbind.c.
References alloc(), dlb, dlb_fclose, dlb_fgets, dlb_fopen, FALSE, free(), ghack_get_main_window(), gless, LLEN, NULL, RDTMODE, and TRUE.
{
    /* Strange -- for some reason it makes us create a new text window
     * instead of reusing any existing ones -- perhaps we can work out
     * some way to reuse stuff -- but for now just make and destroy new
     * ones each time */
        
    dlb *f;
       
        f = dlb_fopen(filename, "r");
        if (!f) {
      if (must_exist) {
        GtkWidget *box;
            char message[90];
            sprintf(message, "Warning! Could not find file: %s\n",filename);
        box = gnome_message_box_new (_(message),
            GNOME_MESSAGE_BOX_ERROR,
            GNOME_STOCK_BUTTON_OK,
            NULL);
        gnome_dialog_set_default(GNOME_DIALOG(box), 0);
        gnome_dialog_set_parent (GNOME_DIALOG (box),
            GTK_WINDOW (ghack_get_main_window ()));
        gtk_window_set_modal(GTK_WINDOW(box), TRUE);
        gtk_widget_show (box);
      }
        }
    else {
          GtkWidget *txtwin, *gless, *frametxt;
#define LLEN 128
      char line[LLEN], *textlines;
      int num_lines, charcount;
      txtwin = gnome_dialog_new("Text Window", GNOME_STOCK_BUTTON_OK,
                    NULL);
          gtk_widget_set_usize(GTK_WIDGET(txtwin), 500, 400);
          gtk_window_set_policy(GTK_WINDOW(txtwin), TRUE, TRUE, FALSE);
          gtk_window_set_title(GTK_WINDOW(txtwin), "Text Window");
      gnome_dialog_set_default(GNOME_DIALOG(txtwin), 0);
      gtk_window_set_modal(GTK_WINDOW(txtwin), TRUE);
      frametxt = gtk_frame_new ("");
      gtk_widget_show (frametxt);
      /*
       * Count the number of lines and characters in the file.
       */
      num_lines = 0;
      charcount = 1;
      while (dlb_fgets(line, LLEN, f)) {
        num_lines++;
        charcount += strlen(line);
      }
      (void) dlb_fclose(f);
      
      /* Ignore empty files */
      if (num_lines == 0) return;
      /*
       * Re-open the file and read the data into a buffer.
       */
      textlines = (char *) alloc((unsigned int) charcount);
      textlines[0] = '\0';
      f = dlb_fopen(filename, RDTMODE);
      while (dlb_fgets(line, LLEN, f)) {
        (void) strcat(textlines, line);
      }
      (void) dlb_fclose(f);
      gless = gnome_less_new ();
      gnome_less_show_string (GNOME_LESS (gless), textlines);
      gtk_container_add (GTK_CONTAINER (frametxt), gless);
          gtk_box_pack_start(GTK_BOX (GNOME_DIALOG (txtwin)->vbox), frametxt,
                             TRUE, TRUE, 0);
      gtk_widget_show_all(txtwin);
      gtk_window_set_modal(GTK_WINDOW(txtwin), TRUE);
      gnome_dialog_set_parent (GNOME_DIALOG (txtwin),
          GTK_WINDOW (ghack_get_main_window ()));
      gnome_dialog_run_and_close (GNOME_DIALOG (txtwin));
      free(textlines);
        }
}
void gnome_display_nhwindow (winid wid, BOOLEAN_P block)
Definition at line 501 of file gnbind.c.
References ghack_signals, GHSIG_DISPLAY, gnome_nhgetch(), NHW_MAP, NULL, and type.
Referenced by ghack_main_window_update_inventory().
{
  if (gnome_windowlist[wid].win != NULL)
    {
      gtk_signal_emit(GTK_OBJECT (gnome_windowlist[wid].win),
               ghack_signals[GHSIG_DISPLAY],
               block);
      if (block && (gnome_windowlist[wid].type == NHW_MAP))
    (void) gnome_nhgetch();
    }
}
int gnome_doprev_message (void)
Definition at line 995 of file gnbind.c.
{
    /* Do Nothing. They can read old messages using the scrollbar. */
    return 0;
}
void gnome_end_menu (winid wid, const char * prompt)
Definition at line 748 of file gnbind.c.
References ghack_signals, GHSIG_END_MENU, and NULL.
{
    if (wid != -1 && gnome_windowlist[wid].win != NULL)
      {
    gtk_signal_emit(GTK_OBJECT (gnome_windowlist[wid].win),
             ghack_signals[GHSIG_END_MENU],
             prompt);
      }
}
void gnome_end_screen (void)
Definition at line 1143 of file gnbind.c.
{
    /* Do Nothing */
}
void gnome_exit_nhwindows (const char *)
Definition at line 372 of file gnbind.c.
References EXIT_SUCCESS, and terminate().
Referenced by ghack_quit_game(), ghack_save_game(), gnome_askname(), and gnome_player_selection().
{
    gtk_exit (0);
    terminate(EXIT_SUCCESS);
}
int gnome_get_ext_cmd (void)
Definition at line 1098 of file gnbind.c.
References ghack_menu_ext_cmd().
{
    return ghack_menu_ext_cmd();
}
void gnome_get_nh_event (void)
Definition at line 363 of file gnbind.c.
{
    /* We handle our own events. */
    return;
}
void gnome_getlin (const char * question, char * input)
Definition at line 1082 of file gnbind.c.
References ghack_ask_string_dialog().
{
    int ret;
    ret = ghack_ask_string_dialog(question, "", "nethack",
      input);
    if (ret == -1)
    input[0] = 0;
}
void gnome_init_nhwindows (int * argc, char ** argv)
Definition at line 93 of file gnbind.c.
References DISP_IN_GAME, flags, ghack_init_glyphs(), ghack_init_main_window(), ghack_init_signals(), gnome_create_nhwindow(), HACKDIR, iflags, flag::ignintr, NHW_WORN, set_option_mod_status(), TRUE, WIN_WORN, and instance_flags::window_inited.
{
    /* Main window */
    ghack_init_main_window(*argc, argv);
    ghack_init_signals();
#ifdef HACKDIR
    //if (ghack_init_glyphs(HACKDIR "/t32-1024.xpm"))
    if (ghack_init_glyphs(HACKDIR "/x11tiles"))
      g_error ("ERROR: Could not initialize glyphs.\n");
#else
# error HACKDIR is not defined!
#endif
  
    // gnome/gtk is not reentrant
    set_option_mod_status("ignintr", DISP_IN_GAME);
    flags.ignintr = TRUE;
    iflags.window_inited = TRUE;
    /* gnome-specific window creation */
    WIN_WORN = gnome_create_nhwindow(NHW_WORN);
}
void gnome_mark_synch (void)
Definition at line 812 of file gnbind.c.
{
    /* Do nothing */
}
int gnome_nh_poskey (int * x, int * y, int * mod)
Definition at line 942 of file gnbind.c.
References g_askingQuestion, g_clickBuffer, g_keyBuffer, g_numClicks, g_numKeys, ghack_signals, GHSIG_FADE_HIGHLIGHT, GHClick::mod, WIN_STATUS, GHClick::x, and GHClick::y.
{
    gtk_signal_emit (GTK_OBJECT (gnome_windowlist[WIN_STATUS].win),
               ghack_signals[GHSIG_FADE_HIGHLIGHT]);
    
    g_askingQuestion = 0;
    /* Process events until a key or map-click arrives. */
    while (g_numKeys == 0 && g_numClicks == 0)
    gtk_main_iteration();
    
    if (g_numKeys > 0) {
    int key;
    GList *theFirst;
    
    theFirst = g_list_first(g_keyBuffer);
    g_keyBuffer = g_list_remove_link(g_keyBuffer, theFirst);
    key = GPOINTER_TO_INT(theFirst->data);
    g_list_free_1(theFirst);
    g_numKeys--;
    return (key);
    }
    else {
    GHClick *click;
    GList *theFirst;
    
    theFirst = g_list_first(g_clickBuffer);
    g_clickBuffer = g_list_remove_link(g_clickBuffer, theFirst);
    click = (GHClick*) theFirst->data;
    *x=click->x;
        *y=click->y;
        *mod=click->mod;
    g_free(click);
    g_list_free_1(theFirst);
    g_numClicks--;
    return (0);
    }
}
void gnome_nhbell (void)
Definition at line 984 of file gnbind.c.
Referenced by gnome_yn_function().
{
    /* FIXME!!! Play a cool GNOME sound instead */
    gdk_beep();
}
int gnome_nhgetch (void)
Definition at line 906 of file gnbind.c.
References g_askingQuestion, g_keyBuffer, g_numKeys, ghack_signals, GHSIG_FADE_HIGHLIGHT, and WIN_STATUS.
Referenced by gnome_display_nhwindow(), and gnome_yn_function().
{
    int key;
    GList *theFirst;
    gtk_signal_emit (GTK_OBJECT (gnome_windowlist[WIN_STATUS].win),
               ghack_signals[GHSIG_FADE_HIGHLIGHT]);
    g_askingQuestion = 1;
    /* Process events until a key press event arrives. */
    while (g_numKeys == 0)
    gtk_main_iteration();
    
    theFirst = g_list_first(g_keyBuffer);
    g_keyBuffer = g_list_remove_link(g_keyBuffer, theFirst);
    key = GPOINTER_TO_INT(theFirst->data);
    g_list_free_1(theFirst);
    g_numKeys--;
    g_askingQuestion = 0;
    return (key);
}
void gnome_number_pad (int state)
Definition at line 1108 of file gnbind.c.
{
    /* Do Nothing */
}
void gnome_outrip (winid wid, int how)
Definition at line 1153 of file gnbind.c.
References buf, BUFSZ, ghack_text_window_rip_string(), KILLED_BY, KILLED_BY_AN, killed_by_prefix, killer, killer_format, NO_KILLER_PREFIX, plname, Sprintf, Strcat, Strcpy, u, and you::ugold.
{
    /* Follows roughly the same algorithm as genl_outrip() */
    char buf[BUFSZ];
    char ripString[BUFSZ]="\0";
    extern const char *killed_by_prefix[];
    
    /* Put name on stone */
    Sprintf(buf, "%s\n", plname);
    Strcat(ripString, buf);
    
    /* Put $ on stone */
    Sprintf(buf, "%ld Au\n",
#ifndef GOLDOBJ
        u.ugold);
#else
        done_money);
#endif
    Strcat(ripString, buf);
    /* Put together death description */
    switch (killer_format) {
        default: impossible("bad killer format?");
        case KILLED_BY_AN:
            Strcpy(buf, killed_by_prefix[how]);
            Strcat(buf, an(killer));
            break;
        case KILLED_BY:
            Strcpy(buf, killed_by_prefix[how]);
            Strcat(buf, killer);
            break;
        case NO_KILLER_PREFIX:
            Strcpy(buf, killer);
            break;
    }
    /* Put death type on stone */
    Strcat(ripString, buf);
    Strcat(ripString, "\n");
    /* Put year on stone */
    Sprintf(buf, "%4d\n", getyear());
    Strcat(ripString, buf);
    ghack_text_window_rip_string(ripString);
}
void gnome_player_selection (void)
Definition at line 123 of file gnbind.c.
References Gender::adj, Align::adj, aligns, alloc(), clearlocks(), RoleName::f, flag::female, flags, free(), genders, ghack_player_sel_dialog(), gnome_exit_nhwindows(), flag::initalign, flag::initgend, flag::initrace, flag::initrole, RoleName::m, Role::name, Race::noun, ok_align(), ok_gend(), ok_race(), ok_role(), panic(), pick_align(), pick_gend(), pick_race(), PICK_RANDOM, pick_role(), races, randalign(), randgend(), flag::randomall, randrace(), randrole(), rigid_role_checks(), ROLE_ALIGNS, ROLE_GENDERS, ROLE_NONE, ROLE_RANDOM, roles, validalign(), validgend(), and validrace().
{
    int n, i, sel;
    const char** choices;
    int* pickmap;
    /* prevent an unnecessary prompt */
    rigid_role_checks();
    if (!flags.randomall && flags.initrole < 0) {
    /* select a role */
    for (n = 0; roles[n].name.m; n++) continue;
    choices = (const char **)alloc(sizeof(char *) * (n+1));
    pickmap = (int*)alloc(sizeof(int) * (n+1));
    for (;;) {
        for (n = 0, i = 0; roles[i].name.m; i++) {
        if (ok_role(i, flags.initrace,
                flags.initgend, flags.initalign)) {
            if (flags.initgend >= 0 && flags.female &&
      roles[i].name.f)
            choices[n] = roles[i].name.f;
            else
            choices[n] = roles[i].name.m;
            pickmap[n++] = i;
        }
        }
        if (n > 0) break;
        else if (flags.initalign >= 0) flags.initalign = -1; /* reset */
        else if (flags.initgend >= 0) flags.initgend = -1;
        else if (flags.initrace >= 0) flags.initrace = -1;
        else panic("no available ROLE+race+gender+alignment combinations");
    }
    choices[n] = (const char *) 0;
    if (n > 1)
        sel = ghack_player_sel_dialog(choices,
        _("Player selection"), _("Choose one of the following roles:"));
    else sel = 0;
    if (sel >= 0) sel = pickmap[sel];
    else if (sel == ROLE_NONE) { /* Quit */
        clearlocks();
        gnome_exit_nhwindows(0);
    }
    free(choices);
    free(pickmap);
    } else if (flags.initrole < 0) sel = ROLE_RANDOM;
    else sel = flags.initrole;
  
    if (sel == ROLE_RANDOM) { /* Random role */
    sel = pick_role(flags.initrace, flags.initgend,
              flags.initalign, PICK_RANDOM);
    if (sel < 0) sel = randrole();
    }
    flags.initrole = sel;
    /* Select a race, if necessary */
    /* force compatibility with role, try for compatibility with
     * pre-selected gender/alignment */
    if (flags.initrace < 0 || !validrace(flags.
      initrole, flags.initrace)) {
    if (flags.initrace == ROLE_RANDOM || flags.
      randomall) {
        flags.initrace = pick_race(flags.initrole,
      flags.initgend,
                       flags.initalign, PICK_RANDOM);
        if (flags.initrace < 0) flags.initrace =
      randrace(flags.initrole);
    } else {
        /* Count the number of valid races */
        n = 0; /* number valid */
        for (i = 0; races[i].noun; i++) {
        if (ok_race(flags.initrole, i, flags.initgend,
      flags.initalign))
            n++;
        }
        if (n == 0) {
        for (i = 0; races[i].noun; i++) {
            if (validrace(flags.initrole, i)) n++;
        }
        }
        choices = (const char **)alloc(sizeof(char *) * (n+1));
        pickmap = (int*)alloc(sizeof(int) * (n + 1));
        for (n = 0, i = 0; races[i].noun; i++) {
        if (ok_race(flags.initrole, i, flags.initgend,
                flags.initalign)) {
            choices[n] = races[i].noun;
            pickmap[n++] = i;
        }
        }
        choices[n] = (const char *) 0;
        /* Permit the user to pick, if there is more than one */
        if (n > 1)
        sel = ghack_player_sel_dialog(choices, _("Race selection"),
            _("Choose one of the following races:"));
        else sel = 0;
        if (sel >= 0) sel = pickmap[sel];
        else if (sel == ROLE_NONE) { /* Quit */
        clearlocks();
        gnome_exit_nhwindows(0);
        }
        flags.initrace = sel;
        free(choices);
        free(pickmap);
    }
    if (flags.initrace == ROLE_RANDOM) { /* Random role */
        sel = pick_race(flags.initrole, flags.
      initgend,
                flags.initalign, PICK_RANDOM);
        if (sel < 0) sel = randrace(flags.initrole);
        flags.initrace = sel;
    }
    }
    /* Select a gender, if necessary */
    /* force compatibility with role/race, try for compatibility with
     * pre-selected alignment */
    if (flags.initgend < 0 ||
    !validgend(flags.initrole, flags.initrace,
      flags.initgend)) {
    if (flags.initgend == ROLE_RANDOM || flags.
      randomall) {
        flags.initgend = pick_gend(flags.initrole,
      flags.initrace,
                       flags.initalign, PICK_RANDOM);
        if (flags.initgend < 0)
        flags.initgend = randgend(flags.initrole,
      flags.initrace);
    } else {
        /* Count the number of valid genders */
        n = 0; /* number valid */
        for (i = 0; i < ROLE_GENDERS; i++) {
        if (ok_gend(flags.initrole, flags.initrace, i,
      flags.initalign))
            n++;
        }
        if (n == 0) {
        for (i = 0; i < ROLE_GENDERS; i++) {
            if (validgend(flags.initrole, flags.
      initrace, i)) n++;
        }
        }
        choices = (const char **)alloc(sizeof(char *) * (n+1));
        pickmap = (int*)alloc(sizeof(int) * (n + 1));
        for (n = 0, i = 0; i < ROLE_GENDERS; i++) {
        if (ok_gend(flags.initrole, flags.initrace, i,
                flags.initalign)) {
            choices[n] = genders[i].adj;
            pickmap[n++] = i;
        }
        }
        choices[n] = (const char *) 0;
        /* Permit the user to pick, if there is more than one */
        if (n > 1)
        sel = ghack_player_sel_dialog(choices, _("Gender selection"),
            _("Choose one of the following genders:"));
        else sel = 0;
        if (sel >= 0) sel = pickmap[sel];
        else if (sel == ROLE_NONE) { /* Quit */
        clearlocks();
        gnome_exit_nhwindows(0);
        }
        flags.initgend = sel;
        free(choices);
        free(pickmap);
    }
    if (flags.initgend == ROLE_RANDOM) { /* Random gender */
        sel = pick_gend(flags.initrole, flags.
      initrace,
                flags.initalign, PICK_RANDOM);
        if (sel < 0) sel = randgend(flags.initrole, flags.
      initrace);
        flags.initgend = sel;
    }
    }
    /* Select an alignment, if necessary */
    /* force compatibility with role/race/gender */
    if (flags.initalign < 0 ||
    !validalign(flags.initrole, flags.initrace,
      flags.initalign)) {
    if (flags.initalign == ROLE_RANDOM || flags.
      randomall) {
        flags.initalign = pick_align(flags.initrole,
      flags.initrace,
                     flags.initgend, PICK_RANDOM);
        if (flags.initalign < 0)
        flags.initalign = randalign(flags.initrole,
      flags.initrace);
    } else {
        /* Count the number of valid alignments */
        n = 0; /* number valid */
        for (i = 0; i < ROLE_ALIGNS; i++) {
        if (ok_align(flags.initrole, flags.initrace,
      flags.initgend, i))
            n++;
        }
        if (n == 0) {
        for (i = 0; i < ROLE_ALIGNS; i++)
            if (validalign(flags.initrole, flags.
      initrace, i)) n++;
        }
        choices = (const char **)alloc(sizeof(char *) * (n+1));
        pickmap = (int*)alloc(sizeof(int) * (n + 1));
        for (n = 0, i = 0; i < ROLE_ALIGNS; i++) {
        if (ok_align(flags.initrole,
                 flags.initrace, flags.initgend, i)) {
            choices[n] = aligns[i].adj;
            pickmap[n++] = i;
        }
        }
        choices[n] = (const char *) 0;
        /* Permit the user to pick, if there is more than one */
        if (n > 1)
        sel = ghack_player_sel_dialog(choices, _("Alignment selection"),
            _("Choose one of the following alignments:"));
        else sel = 0;
        if (sel >= 0) sel = pickmap[sel];
        else if (sel == ROLE_NONE) { /* Quit */
        clearlocks();
        gnome_exit_nhwindows(0);
        }
        flags.initalign = sel;
        free(choices);
        free(pickmap);
    }
    if (flags.initalign == ROLE_RANDOM) {
        sel = pick_align(flags.initrole, flags.
      initrace,
                 flags.initgend, PICK_RANDOM);
        if (sel < 0) sel = randalign(flags.initrole, flags.
      initrace);
        flags.initalign = sel;
    }
    }
}
void gnome_print_glyph (winid wid, XCHAR_P x, XCHAR_P y, int glyph)
Definition at line 859 of file gnbind.c.
References FALSE, ghack_image_from_glyph(), ghack_signals, GHSIG_PRINT_GLYPH, and NULL.
{
    if (wid != -1 && gnome_windowlist[wid].win != NULL)
      {
    GdkImlibImage *im;
    im = ghack_image_from_glyph(glyph, FALSE);
    gtk_signal_emit (GTK_OBJECT (gnome_windowlist[wid].win),
             ghack_signals[GHSIG_PRINT_GLYPH],
             (guint) x,
             (guint) y,
             im,
             NULL);
    }
}
void gnome_putstr (winid wid, int attr, const char * text)
Definition at line 570 of file gnbind.c.
References ghack_signals, GHSIG_PUTSTR, MAXWINDOWS, and NULL.
Referenced by gnome_yn_function().
{
    if ((wid >= 0) &&
        (wid < MAXWINDOWS) &&
        (gnome_windowlist[wid].win != NULL))
    {
      gtk_signal_emit(GTK_OBJECT (gnome_windowlist[wid].win),
               ghack_signals[GHSIG_PUTSTR],
               (guint) attr,
               text);
    }
}
void gnome_raw_print (const char * str)
Definition at line 885 of file gnbind.c.
References tty_raw_print().
{
    tty_raw_print(str);
}
void gnome_raw_print_bold (const char * str)
Definition at line 895 of file gnbind.c.
References tty_raw_print_bold().
{
    tty_raw_print_bold(str);
}
void gnome_resume_nhwindows (void)
Definition at line 387 of file gnbind.c.
{
    /* Do Nothing. Un-necessary since the GUI will refresh itself. */
    return;
}
int gnome_select_menu (winid wid, int how, MENU_ITEM_P ** selected)
Definition at line 783 of file gnbind.c.
References ghack_menu_window_select_menu(), NHW_MENU, NULL, and type.
{
    int nReturned = -1;
    if (wid != -1 && gnome_windowlist[wid].win != NULL &&
        gnome_windowlist[wid].type == NHW_MENU)
      {
    nReturned=ghack_menu_window_select_menu (
      gnome_windowlist[wid].win,
                       selected, how);
      }
    return nReturned;
}
void gnome_start_menu (winid wid)
Definition at line 674 of file gnbind.c.
References ghack_signals, GHSIG_START_MENU, gnome_create_nhwindow_by_id(), NULL, and type.
{
  if (wid != -1)
    {
      if (gnome_windowlist[wid].win == NULL &&
      gnome_windowlist[wid].type != 0)
    {
      gnome_create_nhwindow_by_id(gnome_windowlist[wid].
      type, wid);
    }
        gtk_signal_emit(GTK_OBJECT (gnome_windowlist[wid].win),
               ghack_signals[GHSIG_START_MENU]);
    }
}
void gnome_start_screen (void)
Definition at line 1134 of file gnbind.c.
{
    /* Do Nothing */
}
void gnome_suspend_nhwindows (const char *)
Definition at line 379 of file gnbind.c.
{
    /* I don't think we need to do anything here... */
    return;
}
void gnome_update_inventory (void)
Definition at line 802 of file gnbind.c.
References ghack_main_window_update_inventory().
{
    ghack_main_window_update_inventory();
}
void gnome_wait_synch (void)
Definition at line 823 of file gnbind.c.
{
    /* Do nothing */
}
char gnome_yn_function (const char * question, const char * choices, CHAR_P def)
Definition at line 1020 of file gnbind.c.
References ATR_BOLD, BUFSZ, eos(), ghack_get_main_window(), ghack_yes_no_dialog(), gnome_nhbell(), gnome_nhgetch(), gnome_putstr(), index(), NULL, QBUFSZ, Strcpy, WIN_MESSAGE, and yn_esc_map.
{
    int ch;
    int result=-1;
    char message[BUFSZ];
    char yn_esc_map='\033';
    GtkWidget *mainWnd = ghack_get_main_window();
    
    
    if (choices) {
    char *cb, choicebuf[QBUFSZ];
    Strcpy(choicebuf, choices);
    if ((cb = index(choicebuf, '\033')) != 0) {
        /* anything beyond <esc> is hidden */
        *cb = '\0';
    }
    sprintf(message, "%s [%s] ", question, choicebuf);
    if (def) sprintf(eos(message), "(%c) ", def);
    /* escape maps to 'q' or 'n' or default, in that order */
    yn_esc_map = (index(choices, 'q') ? 'q' :
         (index(choices, 'n') ? 'n' : def));
    } else {
    Strcpy(message, question);
    }
    
    
    gnome_putstr(WIN_MESSAGE, ATR_BOLD, message);
    if (mainWnd != NULL && choices && !index(choices,ch)) {
    return(ghack_yes_no_dialog(question, choices, def));
    }
    /* Only here if main window is not present */
    while (result<0) {
    ch=gnome_nhgetch();
    if (ch=='\033') {
        result=yn_esc_map;
    } else if (choices && !index(choices,ch)) {
        /* FYI: ch==-115 is for KP_ENTER */
        if (def && (ch==' ' || ch=='\r' || ch=='\n' || ch==-115)) {
        result=def;
        } else {
        gnome_nhbell();
        /* and try again... */
        }
    } else {
        result=ch;
    }
    }
    return result;
}