nethack/win/gnome/gnglyph.h File Reference
#include `config.h`
*
#include `global.h`
*
#include <gdk_imlib.h>
*
#include <gdk/gdk.h>
*
Data Structures
struct GHackGlyphs
Macros
#define index _hide_index_
#define time _hide_time_
#define index strchr
Functions
int ghack_init_glyphs (const char *)
void ghack_free_glyphs (void)
void ghack_dispose_glyphs (void)
int ghack_glyph_count (void)
GdkImlibImage * ghack_image_from_glyph (int, gboolean)
int ghack_glyph_height (void)
int ghack_glyph_width (void)
Variables
short glyph2tile []
Macro Definition Documentation
#define index _hide_index_
Definition at line 21 of file gnglyph.h.
#define index strchr
Definition at line 21 of file gnglyph.h.
#define time _hide_time_
Definition at line 15 of file gnglyph.h.
Referenced by do_date(), main(), u_init(), and veryold().
Function Documentation
void ghack_dispose_glyphs (void)
void ghack_free_glyphs (void)
Definition at line 84 of file gnglyph.c.
References GHackGlyphs::count, ghack_tiles, GHackGlyphs::im, and NULL.
Referenced by ghack_settings_dialog().
{
    int i;
    for (i=0 ; i<ghack_glyphs.count ; i++)
    gdk_imlib_destroy_image(ghack_tiles[i]);
    g_free(ghack_tiles);
    gdk_imlib_destroy_image(ghack_glyphs.im);
    ghack_glyphs.im=NULL;
}
int ghack_glyph_count (void)
Definition at line 109 of file gnglyph.c.
References GHackGlyphs::count.
{
  return ghack_glyphs.count;
}
int ghack_glyph_height (void)
Definition at line 129 of file gnglyph.c.
References GHackGlyphs::height.
Referenced by ghack_handle_button_press(), ghack_init_map_window(), ghack_map_cliparound(), ghack_map_cursor_to(), and ghack_reinit_map_window().
{
  return ghack_glyphs.height;
}
int ghack_glyph_width (void)
Definition at line 149 of file gnglyph.c.
References GHackGlyphs::width.
Referenced by ghack_handle_button_press(), ghack_init_map_window(), ghack_map_cliparound(), ghack_map_cursor_to(), and ghack_reinit_map_window().
{
  return ghack_glyphs.width;
}
GdkImlibImage* ghack_image_from_glyph (int , gboolean)
Definition at line 170 of file gnglyph.c.
References GHackGlyphs::count, ghack_tiles, glyph2tile, GHackGlyphs::height, GHackGlyphs::im, NULL, tile, TILES_PER_ROW, TRUE, and GHackGlyphs::width.
Referenced by ghack_menu_window_add_menu(), gnome_print_glyph(), and image_of_worn_object().
{
  int tile = glyph2tile[glyph];
  if (tile >= ghack_glyphs.count || tile < 0)
    {
      g_warning("Aiiee! I've was asked for a tile outside the allowed range!\n"
        "Email this to other-gnomehack@lists.debian.org");
      g_warning("Max tile: %d Tile asked for: %d",
        ghack_glyphs.count, tile);
      return NULL;
    }
  if (ghack_glyphs.im == NULL)
    {
    g_warning("Aiiee! I've been asked to clone from a null image.\n"
        "Email this to other-gnomehack@lists.debian.org");
    g_warning("making image from tile %d, force=%s\n", tile,
        (force==TRUE)? "TRUE": "FALSE");
    }
  if (force == TRUE)
    {
    g_warning("Aiiee! I've been asked to force rendering.\n"
        "Email this to other-gnomehack@lists.debian.org");
    g_warning("making image from tile %d, force=%s\n", tile,
        (force==TRUE)? "TRUE" : "FALSE");
    }
  if (!ghack_tiles[tile] || force) {
      int src_x, src_y;
#if 0
      fprintf(stderr, "crop_and_clone: glyph=%d, tile=%d, ptr=%p, x=%d, y=%d, w=%d, h=%d\n", glyph, tile,
          (void*)&(ghack_tiles[tile]), 0,
          tile * ghack_glyphs.width,
          ghack_glyphs.height,
          ghack_glyphs.width);
#endif
      if (ghack_glyphs.im->pixmap == NULL)
      g_warning("Aiiee! ghack_glyphs.im->pixmap==NULL!!!!\n");
      src_x = (tile % TILES_PER_ROW) * ghack_glyphs.
      width;
      src_y = (tile / TILES_PER_ROW) * ghack_glyphs.
      height;
      ghack_tiles[tile] = gdk_imlib_crop_and_clone_image(
      ghack_glyphs.im,
          src_x, src_y,
          ghack_glyphs.width,
          ghack_glyphs.height);
  }
  if (ghack_tiles[tile] && (!ghack_tiles[tile]->pixmap || force))
  {
      if (gdk_imlib_render(ghack_tiles[tile],
          ghack_tiles[tile]->rgb_width,
          ghack_tiles[tile]->rgb_height) == 0) {
      g_error("GLYPH: couldn't create tile # %d", tile);
      }
      if (!ghack_tiles[tile]->pixmap)
      g_error("Strange, tile # %d didn't get rendered???", tile);
  }
  return ghack_tiles[tile];
}
int ghack_init_glyphs (const char *)
Definition at line 51 of file gnglyph.c.
References GHackGlyphs::count, ghack_tiles, GHackGlyphs::height, GHackGlyphs::im, NULL, TILES_PER_ROW, total_tiles_used, and GHackGlyphs::width.
Referenced by ghack_settings_dialog(), and gnome_init_nhwindows().
{
    ghack_glyphs.im = gdk_imlib_load_image((char *) xpmFile);
    if (! ghack_glyphs.im) {
    g_error("Couldn't load required xpmFile!");
    return -1;
    }
    gdk_imlib_render(ghack_glyphs.im, ghack_glyphs.im->rgb_width,
             ghack_glyphs.im->rgb_height);
    if ((ghack_glyphs.im->rgb_width % TILES_PER_ROW) != 0 ||
    ghack_glyphs.im->rgb_width <= TILES_PER_ROW) {
    g_error("%s is not a multiple of %d (number of tiles/row) pixels wide",
        xpmFile, TILES_PER_ROW);
    return -1;
    }
    ghack_glyphs.count = total_tiles_used;
    if ((ghack_glyphs.count % TILES_PER_ROW) != 0) {
    ghack_glyphs.count +=
        TILES_PER_ROW - (ghack_glyphs.count %
      TILES_PER_ROW);
    }
    ghack_glyphs.width = ghack_glyphs.im->rgb_width /
      TILES_PER_ROW;
    ghack_glyphs.height =
    ghack_glyphs.im->rgb_height / (ghack_glyphs.count /
      TILES_PER_ROW);
    /* Assume the tiles are organized in rows of TILES_PER_ROW */
    ghack_tiles = g_new0(GdkImlibImage*, ghack_glyphs.
      count);
    return (ghack_tiles == NULL) ? -1 : 0;
}
Variable Documentation
short glyph2tile[]