nethack/win/gnome/gnmain.c File Reference
#include `gnmain.h`
*
#include `gnsignal.h`
*
#include `gnbind.h`
*
#include `gnopts.h`
*
#include <gnome.h>
*
#include <getopt.h>
*
#include <gdk/gdk.h>
*
#include <sys/time.h>
*
#include <unistd.h>
*
#include <signal.h>
*
#include `hack.h`
*
#include `date.h`
*
Macros
#define M(c) (0x80 | (c))
#define C(c) (0x1f & (c))
Functions
static void ghack_quit_game (GtkWidget *widget, int button)
static void ghack_quit_game_cb (GtkWidget *widget, gpointer data)
static void ghack_save_game (GtkWidget *widget, int button)
void ghack_save_game_cb (GtkWidget *widget, gpointer data)
static void ghack_new_game (GtkWidget *widget, int button)
static void ghack_new_game_cb (GtkWidget *widget, gpointer data)
static void about_destroy_callback (void)
static void ghack_about_cb (GtkWidget *widget, gpointer data)
static void ghack_settings_cb (GtkWidget *widget, gpointer data)
static void ghack_accelerator_selected (GtkWidget *widget, gpointer data)
static void ghack_main_window_key_press (GtkWidget *widget, GdkEventKey *event, gpointer data)
void parse_args (int argc, char *argv[])
static void ghack_sig_handler (int signum)
void ghack_init_main_window (int argc, char **argv)
void ghack_main_window_add_map_window (GtkWidget *win)
void ghack_main_window_add_message_window (GtkWidget *win)
void ghack_main_window_add_status_window (GtkWidget *win)
void ghack_main_window_add_worn_window (GtkWidget *win)
void ghack_main_window_add_text_window (GtkWidget *win)
void ghack_main_window_remove_window (GtkWidget *win)
void ghack_main_window_update_inventory ()
GtkWidget * ghack_get_main_window ()
Variables
static GtkWidget * mainWindow =NULL
static GtkWidget * about =NULL
static GtkWidget * hBoxFirstRow
static GtkWidget * vBoxMain
int restarted = 0
int os_x = 0
int os_y = 0
int os_w = 0
int os_h = 0
static GnomeClient * session_id
GnomeUIInfo game_tree []
GnomeUIInfo edit_menu []
GnomeUIInfo apparel_menu []
GnomeUIInfo action_menu []
GnomeUIInfo magic_menu []
GnomeUIInfo help_menu []
GnomeUIInfo mainmenu []
xx xx xx xx xx xx xx xx xx
struct {
 int signum
 void(* handler)(int)
} ghack_chain []
Macro Definition Documentation
#define C(c) (0x1f & (c))
Definition at line 177 of file gnmain.c.
#define M(c) (0x80 | (c))
Definition at line 171 of file gnmain.c.
Function Documentation
static void about_destroy_callback (void) [static]
Definition at line 117 of file gnmain.c.
References about, and NULL.
Referenced by ghack_about_cb().
{
    about = NULL;
}
static void ghack_about_cb (GtkWidget * widget, gpointer data) [static]
Definition at line 123 of file gnmain.c.
References about, about_destroy_callback(), buf, BUFSZ, getversionstring(), and NULL.
{
    char buf[BUFSZ]="\0";
    char buf1[BUFSZ]="\0";
    const gchar *authors[] = {"Erik Andersen", "Anthony Taylor",
    "Jeff Garzik", "The Nethack Dev Team", NULL};
    if (about) {
    gdk_window_raise (about->window);
    return;
    }
    getversionstring(buf);
    strcat(buf1, VERSION_STRING);
    strcat(buf,
      _("\nSend comments and bug reports to: nethack-bugs@nethack.org\n"
      "This game is free software. See License for details."));
    about = gnome_about_new(_("Nethack"),
        buf1, "Copyright (C) 1985-2002 Mike Stephenson",
        (const char **)authors, buf,
        NULL);
    gtk_signal_connect (GTK_OBJECT (about), "destroy",
    (GtkSignalFunc) about_destroy_callback, NULL);
    
    gtk_widget_show(about);
}
static void ghack_accelerator_selected (GtkWidget * widget, gpointer data) [static]
Definition at line 158 of file gnmain.c.
References ghack_handle_key_press(), and NULL.
{
    GdkEventKey event;
    int key = GPOINTER_TO_INT(data);
    /* g_message("An accelerator for \"%c\" was selected", key); */
    /* stuff a key directly into the keybuffer */
    event.state=0;
    event.keyval=key;
    ghack_handle_key_press(NULL, &event, NULL);
}
GtkWidget* ghack_get_main_window ()
Definition at line 836 of file gnmain.c.
References mainWindow.
Referenced by ghack_ask_string_dialog(), ghack_init_menu_window(), ghack_init_text_window(), ghack_menu_ext_cmd(), ghack_new_game_cb(), ghack_player_sel_dialog(), ghack_quit_game_cb(), ghack_save_game_cb(), ghack_settings_dialog(), ghack_yes_no_dialog(), gnome_display_file(), and gnome_yn_function().
{
      return(GTK_WIDGET(mainWindow));
}
void ghack_init_main_window (int argc, char ** argv)
Definition at line 708 of file gnmain.c.
References FALSE, getuid(), ghack_chain, ghack_main_window_key_press(), ghack_quit_game_cb(), ghack_sig_handler(), handler, hBoxFirstRow, mainmenu, mainWindow, NULL, os_h, os_w, os_x, os_y, parse_args(), restarted, signum, SIZE, TRUE, and vBoxMain.
Referenced by gnome_init_nhwindows().
{
    int i;
    struct timeval tv;
    uid_t uid, euid;
    /* It seems that the authors of gnome_score_init() drop group
     * priveledges. We need group priveledges, so until we change the
     * way we save games to do things the gnome way(???), this stays
     * commented out. (after hours of frusteration...)
     * -Erik
     */
    /* gnome_score_init("gnomehack"); */
    gettimeofday(&tv, NULL);
    srand(tv.tv_usec);
    uid = getuid();
    euid = geteuid();
    if (uid != euid)
      setuid(uid);
    hide_privileges(TRUE);
    /* XXX gnome_init must print nethack options for --help, but does not */
    gnome_init ("nethack", VERSION_STRING, argc, argv);
    hide_privileges(FALSE);
    parse_args (argc, argv);
    /* Initialize the i18n stuff (not that gnomehack supperts it yet...) */
#if 0
    textdomain (PACKAGE);
#endif
    gdk_imlib_init();
    /* Main window */
    mainWindow = gnome_app_new((char *) "nethack",
        (char *) N_("Nethack for Gnome"));
    gtk_widget_realize(mainWindow);
    if (restarted) {
    gtk_widget_set_uposition (mainWindow, os_x, os_y);
    gtk_widget_set_usize (mainWindow, os_w, os_h);
    }
    gtk_window_set_default_size(GTK_WINDOW(mainWindow), 800, 600);
    gtk_window_set_policy(GTK_WINDOW(mainWindow), FALSE, TRUE,
      TRUE);
    gnome_app_create_menus(GNOME_APP(mainWindow), mainmenu);
    gtk_signal_connect(GTK_OBJECT(mainWindow), "key_press_event",
        GTK_SIGNAL_FUNC(ghack_main_window_key_press),
      NULL);
    gtk_signal_connect(GTK_OBJECT(mainWindow), "delete_event",
        GTK_SIGNAL_FUNC(ghack_quit_game_cb), NULL);
    /* Put some stuff into our main window */
    vBoxMain = gtk_vbox_new (FALSE, 0);
    hBoxFirstRow = gtk_hbox_new (FALSE, 0);
   
    /* pack Boxes into other boxes to produce the right structure */
    gtk_box_pack_start (GTK_BOX (vBoxMain), hBoxFirstRow,
      FALSE, TRUE, 0);
    
    /* pack vBoxMain which contains all our widgets into the main window. */
    gnome_app_set_contents(GNOME_APP(mainWindow), vBoxMain);
    
    /* DONT show the main window yet, due to a Gtk bug that causes it
     * to not refresh the window when adding widgets after the window
     * has already been shown */
    if (uid != euid)
      setuid(euid);
    for(i = 0; i < SIZE(ghack_chain); i++)
    ghack_chain[i].handler =
      signal(ghack_chain[i].signum, ghack_sig_handler);
}
void ghack_main_window_add_map_window (GtkWidget * win)
Definition at line 777 of file gnmain.c.
References mainWindow, TRUE, and vBoxMain.
Referenced by gnome_create_nhwindow_by_id().
{
    GtkWidget *vBox;
    
    vBox= gtk_vbox_new (TRUE, 0);
    gtk_box_pack_start (GTK_BOX (vBox), win, TRUE, TRUE, 2);
    gtk_box_pack_start (GTK_BOX (vBoxMain), vBox, TRUE, TRUE, 2);
    gtk_widget_show_all(vBox);
    /* Ok, now show the main window -- now that we have added in
     * all the windows (relys on nethack displaying the map window last
     * (This is an ugly kludge, BTW)
     */
    gtk_widget_show_all(mainWindow);
}
void ghack_main_window_add_message_window (GtkWidget * win)
Definition at line 793 of file gnmain.c.
References hBoxFirstRow, and TRUE.
Referenced by gnome_create_nhwindow_by_id().
{
    gtk_box_pack_start (GTK_BOX (hBoxFirstRow), win, TRUE, TRUE, 2);
    gtk_widget_show_all(win);
}
void ghack_main_window_add_status_window (GtkWidget * win)
Definition at line 800 of file gnmain.c.
References FALSE, hBoxFirstRow, and TRUE.
Referenced by gnome_create_nhwindow_by_id().
{
    gtk_box_pack_start (GTK_BOX (hBoxFirstRow), win, FALSE,
      TRUE, 2);
    gtk_widget_show_all(win);
}
void ghack_main_window_add_text_window (GtkWidget * win)
Definition at line 814 of file gnmain.c.
{
  g_warning("Fixme!!! AddTextWindow is not yet implemented");
}
void ghack_main_window_add_worn_window (GtkWidget * win)
Definition at line 807 of file gnmain.c.
References FALSE, hBoxFirstRow, and TRUE.
Referenced by gnome_create_nhwindow_by_id().
{
    gtk_box_pack_end (GTK_BOX (hBoxFirstRow), win, FALSE, TRUE, 2);
    gtk_widget_show_all(win);
}
static void ghack_main_window_key_press (GtkWidget * widget, GdkEventKey * event, gpointer data) [static]
Definition at line 584 of file gnmain.c.
References ghack_handle_key_press(), and mainWindow.
Referenced by ghack_init_main_window().
{
    /* First, turn off the key press propogation. We've got the
     * key, but we don't wan't the underlying Gtk widgets to get it,
     * since they do the wrong thing with the arrow keys (shift focus)... */
    gtk_signal_emit_stop_by_name(GTK_OBJECT(mainWindow), "key_press_event");
    
    /* stuff the key event into the keybuffer */
    ghack_handle_key_press(widget, event, data);
}
void ghack_main_window_remove_window (GtkWidget * win)
Definition at line 820 of file gnmain.c.
{
  g_warning("Fixme!!! RemoveWindow is not yet implemented");
}
void ghack_main_window_update_inventory ()
Definition at line 826 of file gnmain.c.
References FALSE, gnome_display_nhwindow(), and WIN_WORN.
Referenced by gnome_update_inventory().
{
/* For now, do very little. Eventually we may allow the inv. window
     to stay active. When we do this, we'll need to implement this...
   g_warning("Fixme!!! updateInventory is not yet implemented");
*/
    gnome_display_nhwindow(WIN_WORN, FALSE);
}
static void ghack_new_game (GtkWidget * widget, int button) [static]
Definition at line 90 of file gnmain.c.
Referenced by ghack_new_game_cb().
{
    if (button == 0) {
    g_message("This feature is not yet implemented. Sorry.");
    }
}
static void ghack_new_game_cb (GtkWidget * widget, gpointer data) [static]
Definition at line 98 of file gnmain.c.
References ghack_get_main_window(), ghack_new_game(), NULL, and TRUE.
{
    GtkWidget *box;
    box = gnome_message_box_new(_("Start a new game?"),
        GNOME_MESSAGE_BOX_QUESTION, GNOME_STOCK_BUTTON_YES,
        GNOME_STOCK_BUTTON_NO, NULL);
    gnome_dialog_set_default(GNOME_DIALOG(box), 1);
    gnome_dialog_set_parent (GNOME_DIALOG (box),
        GTK_WINDOW (ghack_get_main_window ()));
    gnome_dialog_set_accelerator (GNOME_DIALOG(box), 1, 'n', 0);
    gnome_dialog_set_accelerator (GNOME_DIALOG(box), 0, 'y', 0);
    gtk_window_set_modal(GTK_WINDOW(box), TRUE);
    gtk_signal_connect(GTK_OBJECT(box), "clicked",
        (GtkSignalFunc)ghack_new_game, NULL);
    gtk_widget_show(box);
}
static void ghack_quit_game (GtkWidget * widget, int button) [static]
Definition at line 30 of file gnmain.c.
References gnome_exit_nhwindows(), and session_id.
Referenced by ghack_quit_game_cb().
{
    gtk_widget_hide(widget);
    if (button == 0) {
    gnome_exit_nhwindows(0);
    gtk_object_unref(GTK_OBJECT(session_id));
    }
}
static void ghack_quit_game_cb (GtkWidget * widget, gpointer data) [static]
Definition at line 40 of file gnmain.c.
References ghack_get_main_window(), ghack_quit_game(), NULL, and TRUE.
Referenced by ghack_init_main_window().
{
    GtkWidget *box;
    box = gnome_message_box_new(_("Do you really want to quit?"),
        GNOME_MESSAGE_BOX_QUESTION, GNOME_STOCK_BUTTON_YES,
        GNOME_STOCK_BUTTON_NO, NULL);
    gnome_dialog_set_default(GNOME_DIALOG(box), 1);
    gnome_dialog_set_parent (GNOME_DIALOG (box),
        GTK_WINDOW (ghack_get_main_window ()));
    gnome_dialog_set_accelerator (GNOME_DIALOG(box), 1, 'n', 0);
    gnome_dialog_set_accelerator (GNOME_DIALOG(box), 0, 'y', 0);
    gtk_window_set_modal(GTK_WINDOW(box), TRUE);
    gtk_signal_connect(GTK_OBJECT(box), "clicked",
        (GtkSignalFunc)ghack_quit_game, NULL);
    gtk_widget_show(box);
}
static void ghack_save_game (GtkWidget * widget, int button) [static]
Definition at line 59 of file gnmain.c.
References display_nhwindow, doredraw(), dosave0(), gnome_exit_nhwindows(), TRUE, and WIN_MESSAGE.
Referenced by ghack_save_game_cb().
{
    gtk_widget_hide(widget);
    if (button == 0) {
    if(dosave0()) {
        /* make sure they see the Saving message */
        display_nhwindow(WIN_MESSAGE, TRUE);
        gnome_exit_nhwindows("Be seeing you...");
    } else (void)doredraw();
    }
}
void ghack_save_game_cb (GtkWidget * widget, gpointer data)
Definition at line 71 of file gnmain.c.
References ghack_get_main_window(), ghack_save_game(), NULL, and TRUE.
Referenced by ghack_handle_key_press().
{
    GtkWidget *box;
    box = gnome_message_box_new(_("Quit and save the current game?"),
        GNOME_MESSAGE_BOX_QUESTION, GNOME_STOCK_BUTTON_YES,
        GNOME_STOCK_BUTTON_NO, NULL);
    gnome_dialog_set_default(GNOME_DIALOG(box), 1);
    gnome_dialog_set_parent (GNOME_DIALOG (box),
        GTK_WINDOW (ghack_get_main_window ()));
    gnome_dialog_set_accelerator (GNOME_DIALOG(box), 1, 'n', 0);
    gnome_dialog_set_accelerator (GNOME_DIALOG(box), 0, 'y', 0);
    gtk_window_set_modal(GTK_WINDOW(box), TRUE);
    gtk_signal_connect(GTK_OBJECT(box), "clicked",
        (GtkSignalFunc)ghack_save_game, NULL);
    gtk_widget_show(box);
}
static void ghack_settings_cb (GtkWidget * widget, gpointer data) [static]
Definition at line 152 of file gnmain.c.
References ghack_settings_dialog().
{
    ghack_settings_dialog();
}
static void ghack_sig_handler (int signum) [static]
Definition at line 681 of file gnmain.c.
References getuid(), ghack_chain, and SIZE.
Referenced by ghack_init_main_window().
{
    int i;
    uid_t uid, euid;
    gid_t gid, egid;
    uid = getuid();
    euid = geteuid();
    gid = getgid();
    egid = getegid();
    if (gid != egid)
    setgid(gid);
    if (uid != euid)
    setuid(uid);
    for(i = SIZE(ghack_chain) - 1; i >= 0; i--)
    if (ghack_chain[i].signum == signum) {
        ghack_chain[i].handler(signum);
        break;
    }
    if (i < 0)
    impossible("Unhandled ghack signal");
    if (uid != euid)
    setuid(euid);
    if (gid != egid)
    setgid(egid);
}
void parse_args (int argc, char * argv[])
Definition at line 599 of file gnmain.c.
References exit(), NULL, and session_id.
Referenced by ghack_init_main_window().
{
  gint ch;
  struct option options[] = {
    /* Default args */
    { "help", no_argument, NULL, 'h' },
    { "version", no_argument, NULL, 'v' },
    { NULL, 0, NULL, 0 }
    };
  gchar *id = NULL;
  /* initialize getopt */
  optarg = NULL;
  optind = 0;
  optopt = 0;
  while((ch = getopt_long(argc, argv, "hv", options, NULL)) != EOF)
  {
    switch(ch)
    {
      case 'h':
        g_print (
          _("%s: A gnomified 'Hello World' program\n\n"
            "Usage: %s [--help] [--version]\n\n"
            "Options:\n"
            " --help display this help and exit\n"
            " --version output version information and exit\n"),
            argv[0], argv[0]);
        exit(0);
        break;
      case 'v':
        g_print (_("NetHack %s.\n"), VERSION_STRING);
        exit(0);
        break;
      case ':':
      case '?':
        g_print (_("Options error\n"));
        exit(0);
        break;
    }
  }
  /* SM stuff */
  session_id = gnome_client_new ();
#if 0
  session_id = gnome_client_new (
    /* callback to save the state and parameter for it */
    save_state, argv[0],
    /* callback to die and parameter for it */
        NULL, NULL,
    /* id from the previous session if restarted, NULL otherwise */
        id);
#endif
  /* set the program name */
  gnome_client_set_program (session_id, argv[0]);
  g_free(id);
  return;
}
Variable Documentation
GtkWidget* about =NULL [static]
Definition at line 19 of file gnmain.c.
Referenced by about_destroy_callback(), and ghack_about_cb().
GnomeUIInfo action_menu[]
Definition at line 307 of file gnmain.c.
GnomeUIInfo apparel_menu[]
Definition at line 270 of file gnmain.c.
GnomeUIInfo edit_menu[]
Definition at line 227 of file gnmain.c.
GnomeUIInfo game_tree[]
Definition at line 181 of file gnmain.c.
struct { ... } ghack_chain[] [static]
Initial value:
= {
    {SIGBUS},
    {SIGFPE},
    {SIGSEGV},
    {SIGILL}
}
Referenced by ghack_init_main_window(), and ghack_sig_handler().
void(* handler)(int)
Definition at line 673 of file gnmain.c.
Referenced by ghack_init_main_window().
GtkWidget* hBoxFirstRow [static]
Definition at line 20 of file gnmain.c.
Referenced by ghack_init_main_window(), ghack_main_window_add_message_window(), ghack_main_window_add_status_window(), and ghack_main_window_add_worn_window().
GnomeUIInfo help_menu[]
Definition at line 533 of file gnmain.c.
GnomeUIInfo magic_menu[]
Definition at line 454 of file gnmain.c.
GnomeUIInfo mainmenu[]
Initial value:
= {
        GNOMEUIINFO_MENU_GAME_TREE(game_tree),
        GNOMEUIINFO_MENU_EDIT_TREE(edit_menu),
        { GNOME_APP_UI_SUBTREE, N_("Apparel"), NULL, apparel_menu,
      NULL,
        NULL, 0, NULL, 0, 0, NULL },
        { GNOME_APP_UI_SUBTREE, N_("Action"), NULL, action_menu,
      NULL,
        NULL, 0, NULL, 0, 0, NULL },
        { GNOME_APP_UI_SUBTREE, N_("Magic"), NULL, magic_menu,
      NULL,
        NULL, 0, NULL, 0, 0, NULL },
        GNOMEUIINFO_MENU_HELP_TREE(help_menu),
        GNOMEUIINFO_END
}
Definition at line 570 of file gnmain.c.
Referenced by ghack_init_main_window().
GtkWidget* mainWindow =NULL [static]
Definition at line 18 of file gnmain.c.
Referenced by ghack_get_main_window(), ghack_init_main_window(), ghack_main_window_add_map_window(), and ghack_main_window_key_press().
int os_h = 0
Definition at line 24 of file gnmain.c.
Referenced by ghack_init_main_window().
int os_w = 0
Definition at line 24 of file gnmain.c.
Referenced by ghack_init_main_window().
int os_x = 0
Definition at line 24 of file gnmain.c.
Referenced by ghack_init_main_window().
int os_y = 0
Definition at line 24 of file gnmain.c.
Referenced by ghack_init_main_window().
int restarted = 0
Definition at line 23 of file gnmain.c.
Referenced by ghack_init_main_window().
GnomeClient* session_id [static]
Definition at line 27 of file gnmain.c.
Referenced by ghack_quit_game(), and parse_args().
int signum
Definition at line 672 of file gnmain.c.
Referenced by ghack_init_main_window().
GtkWidget* vBoxMain [static]
Definition at line 21 of file gnmain.c.
Referenced by ghack_init_main_window(), and ghack_main_window_add_map_window().