nethack/win/gnome/gnmain.h File Reference
#include <gnome.h>
*
#include <gtk/gtk.h>
*
Functions
void ghack_init_main_window (int argc, char **argv)
void ghack_main_window_add_map_window (GtkWidget *win)
void ghack_main_window_add_message_window (GtkWidget *win)
void ghack_main_window_add_status_window (GtkWidget *win)
void ghack_main_window_add_text_window (GtkWidget *)
void ghack_main_window_add_worn_window (GtkWidget *win)
void ghack_main_window_remove_window (GtkWidget *)
void ghack_main_window_update_inventory ()
void ghack_save_game_cb (GtkWidget *widget, gpointer data)
GtkWidget * ghack_get_main_window ()
Function Documentation
GtkWidget* ghack_get_main_window ()
Definition at line 836 of file gnmain.c.
References mainWindow.
Referenced by ghack_ask_string_dialog(), ghack_init_menu_window(), ghack_init_text_window(), ghack_menu_ext_cmd(), ghack_new_game_cb(), ghack_player_sel_dialog(), ghack_quit_game_cb(), ghack_save_game_cb(), ghack_settings_dialog(), ghack_yes_no_dialog(), gnome_display_file(), and gnome_yn_function().
{
      return(GTK_WIDGET(mainWindow));
}
void ghack_init_main_window (int argc, char ** argv)
Definition at line 708 of file gnmain.c.
References FALSE, getuid(), ghack_chain, ghack_main_window_key_press(), ghack_quit_game_cb(), ghack_sig_handler(), handler, hBoxFirstRow, mainmenu, mainWindow, NULL, os_h, os_w, os_x, os_y, parse_args(), restarted, signum, SIZE, TRUE, and vBoxMain.
Referenced by gnome_init_nhwindows().
{
    int i;
    struct timeval tv;
    uid_t uid, euid;
    /* It seems that the authors of gnome_score_init() drop group
     * priveledges. We need group priveledges, so until we change the
     * way we save games to do things the gnome way(???), this stays
     * commented out. (after hours of frusteration...)
     * -Erik
     */
    /* gnome_score_init("gnomehack"); */
    gettimeofday(&tv, NULL);
    srand(tv.tv_usec);
    uid = getuid();
    euid = geteuid();
    if (uid != euid)
      setuid(uid);
    hide_privileges(TRUE);
    /* XXX gnome_init must print nethack options for --help, but does not */
    gnome_init ("nethack", VERSION_STRING, argc, argv);
    hide_privileges(FALSE);
    parse_args (argc, argv);
    /* Initialize the i18n stuff (not that gnomehack supperts it yet...) */
#if 0
    textdomain (PACKAGE);
#endif
    gdk_imlib_init();
    /* Main window */
    mainWindow = gnome_app_new((char *) "nethack",
        (char *) N_("Nethack for Gnome"));
    gtk_widget_realize(mainWindow);
    if (restarted) {
    gtk_widget_set_uposition (mainWindow, os_x, os_y);
    gtk_widget_set_usize (mainWindow, os_w, os_h);
    }
    gtk_window_set_default_size(GTK_WINDOW(mainWindow), 800, 600);
    gtk_window_set_policy(GTK_WINDOW(mainWindow), FALSE, TRUE,
      TRUE);
    gnome_app_create_menus(GNOME_APP(mainWindow), mainmenu);
    gtk_signal_connect(GTK_OBJECT(mainWindow), "key_press_event",
        GTK_SIGNAL_FUNC(ghack_main_window_key_press),
      NULL);
    gtk_signal_connect(GTK_OBJECT(mainWindow), "delete_event",
        GTK_SIGNAL_FUNC(ghack_quit_game_cb), NULL);
    /* Put some stuff into our main window */
    vBoxMain = gtk_vbox_new (FALSE, 0);
    hBoxFirstRow = gtk_hbox_new (FALSE, 0);
   
    /* pack Boxes into other boxes to produce the right structure */
    gtk_box_pack_start (GTK_BOX (vBoxMain), hBoxFirstRow,
      FALSE, TRUE, 0);
    
    /* pack vBoxMain which contains all our widgets into the main window. */
    gnome_app_set_contents(GNOME_APP(mainWindow), vBoxMain);
    
    /* DONT show the main window yet, due to a Gtk bug that causes it
     * to not refresh the window when adding widgets after the window
     * has already been shown */
    if (uid != euid)
      setuid(euid);
    for(i = 0; i < SIZE(ghack_chain); i++)
    ghack_chain[i].handler =
      signal(ghack_chain[i].signum, ghack_sig_handler);
}
void ghack_main_window_add_map_window (GtkWidget * win)
Definition at line 777 of file gnmain.c.
References mainWindow, TRUE, and vBoxMain.
Referenced by gnome_create_nhwindow_by_id().
{
    GtkWidget *vBox;
    
    vBox= gtk_vbox_new (TRUE, 0);
    gtk_box_pack_start (GTK_BOX (vBox), win, TRUE, TRUE, 2);
    gtk_box_pack_start (GTK_BOX (vBoxMain), vBox, TRUE, TRUE, 2);
    gtk_widget_show_all(vBox);
    /* Ok, now show the main window -- now that we have added in
     * all the windows (relys on nethack displaying the map window last
     * (This is an ugly kludge, BTW)
     */
    gtk_widget_show_all(mainWindow);
}
void ghack_main_window_add_message_window (GtkWidget * win)
Definition at line 793 of file gnmain.c.
References hBoxFirstRow, and TRUE.
Referenced by gnome_create_nhwindow_by_id().
{
    gtk_box_pack_start (GTK_BOX (hBoxFirstRow), win, TRUE, TRUE, 2);
    gtk_widget_show_all(win);
}
void ghack_main_window_add_status_window (GtkWidget * win)
Definition at line 800 of file gnmain.c.
References FALSE, hBoxFirstRow, and TRUE.
Referenced by gnome_create_nhwindow_by_id().
{
    gtk_box_pack_start (GTK_BOX (hBoxFirstRow), win, FALSE,
      TRUE, 2);
    gtk_widget_show_all(win);
}
void ghack_main_window_add_text_window (GtkWidget *)
Definition at line 814 of file gnmain.c.
{
  g_warning("Fixme!!! AddTextWindow is not yet implemented");
}
void ghack_main_window_add_worn_window (GtkWidget * win)
Definition at line 807 of file gnmain.c.
References FALSE, hBoxFirstRow, and TRUE.
Referenced by gnome_create_nhwindow_by_id().
{
    gtk_box_pack_end (GTK_BOX (hBoxFirstRow), win, FALSE, TRUE, 2);
    gtk_widget_show_all(win);
}
void ghack_main_window_remove_window (GtkWidget *)
Definition at line 820 of file gnmain.c.
{
  g_warning("Fixme!!! RemoveWindow is not yet implemented");
}
void ghack_main_window_update_inventory ()
Definition at line 826 of file gnmain.c.
References FALSE, gnome_display_nhwindow(), and WIN_WORN.
Referenced by gnome_update_inventory().
{
/* For now, do very little. Eventually we may allow the inv. window
     to stay active. When we do this, we'll need to implement this...
   g_warning("Fixme!!! updateInventory is not yet implemented");
*/
    gnome_display_nhwindow(WIN_WORN, FALSE);
}
void ghack_save_game_cb (GtkWidget * widget, gpointer data)
Definition at line 71 of file gnmain.c.
References ghack_get_main_window(), ghack_save_game(), NULL, and TRUE.
Referenced by ghack_handle_key_press().
{
    GtkWidget *box;
    box = gnome_message_box_new(_("Quit and save the current game?"),
        GNOME_MESSAGE_BOX_QUESTION, GNOME_STOCK_BUTTON_YES,
        GNOME_STOCK_BUTTON_NO, NULL);
    gnome_dialog_set_default(GNOME_DIALOG(box), 1);
    gnome_dialog_set_parent (GNOME_DIALOG (box),
        GTK_WINDOW (ghack_get_main_window ()));
    gnome_dialog_set_accelerator (GNOME_DIALOG(box), 1, 'n', 0);
    gnome_dialog_set_accelerator (GNOME_DIALOG(box), 0, 'y', 0);
    gtk_window_set_modal(GTK_WINDOW(box), TRUE);
    gtk_signal_connect(GTK_OBJECT(box), "clicked",
        (GtkSignalFunc)ghack_save_game, NULL);
    gtk_widget_show(box);
}