nethack/win/gnome/gnmesg.c File Reference
#include `gnmesg.h`
*
#include `gnsignal.h`
*
Macros
#define nCharsBeforeDeletingStuff 3200
Functions
void ghack_message_window_clear (GtkWidget *widget, gpointer data)
void ghack_message_window_destroy (GtkWidget *win, gpointer data)
void ghack_message_window_display (GtkWidget *widget, boolean block, gpointer data)
void ghack_message_window_put_string (GtkWidget *widget, int attr, const char *text, gpointer data)
void ghack_message_window_use_RIP (int how)
void ghack_message_window_scroll (int dx, int dy)
GtkWidget * ghack_init_message_window (void)
Variables
GtkWidget * MW_table
GtkWidget * MW_text
GtkWidget * MW_scrollbar
Macro Definition Documentation
#define nCharsBeforeDeletingStuff 3200
Definition at line 9 of file gnmesg.c.
Referenced by ghack_message_window_clear().
Function Documentation
GtkWidget* ghack_init_message_window (void)
Definition at line 68 of file gnmesg.c.
References FALSE, ghack_delay(), ghack_message_window_clear(), ghack_message_window_put_string(), MW_scrollbar, MW_table, MW_text, NULL, and TRUE.
Referenced by gnome_create_nhwindow_by_id().
{
    MW_table = gtk_table_new(2, 1, FALSE);
    gtk_table_set_row_spacing(GTK_TABLE(MW_table), 0, 2);
    MW_text = gtk_text_new(NULL, NULL);
    gtk_text_set_editable(GTK_TEXT(MW_text), FALSE);
    gtk_text_set_word_wrap(GTK_TEXT(MW_text), TRUE);
    gtk_table_attach(GTK_TABLE(MW_table), MW_text, 0, 1, 0, 1,
                     (GTK_EXPAND | GTK_FILL),
                     (GTK_EXPAND | GTK_FILL),
                     0, 0);
    MW_scrollbar = gtk_vscrollbar_new(GTK_TEXT(MW_text)->vadj);
    gtk_table_attach(GTK_TABLE(MW_table), MW_scrollbar, 1, 2, 0, 1,
                     GTK_FILL, (GTK_EXPAND | GTK_FILL), 0, 0);
    
    gtk_signal_connect(GTK_OBJECT(MW_table), "ghack_putstr",
            GTK_SIGNAL_FUNC(ghack_message_window_put_string),
            NULL);
    gtk_signal_connect(GTK_OBJECT(MW_table), "ghack_clear",
            GTK_SIGNAL_FUNC(ghack_message_window_clear),
            NULL);
    
    gtk_signal_connect(GTK_OBJECT(MW_table), "gnome_delay_output",
                    GTK_SIGNAL_FUNC(ghack_delay), NULL);
    gtk_widget_show_all(MW_table);
    return GTK_WIDGET(MW_table);
}
void ghack_message_window_clear (GtkWidget * widget, gpointer data)
Definition at line 17 of file gnmesg.c.
References MW_text, and nCharsBeforeDeletingStuff.
Referenced by ghack_init_message_window().
{
    /* Seems nethack calls this after every move -- we don't want
     * to really clear the window at all though. Ignore the request */
    gint len;
    len = gtk_text_get_length(GTK_TEXT(MW_text));
    
    if(len < nCharsBeforeDeletingStuff)
        return;
    
    gtk_text_freeze(GTK_TEXT(MW_text));
    gtk_text_set_point(GTK_TEXT(MW_text), 0);
    gtk_text_forward_delete(GTK_TEXT(MW_text), len-((guint)(
      nCharsBeforeDeletingStuff*0.5)));
    gtk_text_set_point(GTK_TEXT(MW_text), (guint)(
      nCharsBeforeDeletingStuff*0.5));
    gtk_text_thaw(GTK_TEXT(MW_text));
}
void ghack_message_window_destroy (GtkWidget * win, gpointer data)
Definition at line 35 of file gnmesg.c.
{
}
void ghack_message_window_display (GtkWidget * widget, boolean block, gpointer data)
Definition at line 40 of file gnmesg.c.
{
}
void ghack_message_window_put_string (GtkWidget * widget, int attr, const char * text, gpointer data)
Definition at line 46 of file gnmesg.c.
References MW_text, and NULL.
Referenced by ghack_init_message_window().
{
    if(text == NULL)
        return;
    
    /* Don't bother with attributes yet */
    gtk_text_insert(GTK_TEXT(MW_text), NULL, NULL, NULL, text, -1);
    gtk_text_insert(GTK_TEXT(MW_text), NULL, NULL, NULL, "\n", -1);
}
void ghack_message_window_scroll (int dx, int dy)
Definition at line 63 of file gnmesg.c.
{
}
void ghack_message_window_use_RIP (int how)
Definition at line 58 of file gnmesg.c.
{
}
Variable Documentation
GtkWidget* MW_scrollbar
Definition at line 14 of file gnmesg.c.
Referenced by ghack_init_message_window().
GtkWidget* MW_table
Definition at line 12 of file gnmesg.c.
Referenced by ghack_init_message_window().
GtkWidget* MW_text
Definition at line 13 of file gnmesg.c.
Referenced by ghack_init_message_window(), ghack_message_window_clear(), and ghack_message_window_put_string().