nethack/win/gnome/gnmenu.h File Reference
#include <gnome.h>
*
#include `config.h`
*
#include `global.h`
*
#include `gnomeprv.h`
*
Data Structures
struct _GHackMenuItem
Typedefs
typedef struct _GHackMenuItem GHackMenuItem
Functions
GtkWidget * ghack_init_menu_window (void)
int ghack_menu_window_select_menu (GtkWidget *menuWin, MENU_ITEM_P **_selected, gint how)
int ghack_menu_ext_cmd (void)
Typedef Documentation
typedef struct _GHackMenuItem GHackMenuItem
Definition at line 26 of file gnmenu.h.
Function Documentation
GtkWidget* ghack_init_menu_window (void)
Definition at line 576 of file gnmenu.c.
References ghack_get_main_window(), ghack_menu_destroy(), ghack_menu_hide(), ghack_menu_window_add_menu(), ghack_menu_window_clear(), ghack_menu_window_display(), ghack_menu_window_end_menu(), ghack_menu_window_key(), ghack_menu_window_put_string(), ghack_menu_window_select_menu(), ghack_menu_window_start_menu(), and NULL.
Referenced by gnome_create_nhwindow_by_id().
{
    GtkWidget *menuWin = NULL;
    GtkWidget *parent = ghack_get_main_window ();
    menuWin = gnome_dialog_new("GnomeHack", GNOME_STOCK_BUTTON_OK,
            GNOME_STOCK_BUTTON_CANCEL, NULL);
    
    gnome_dialog_set_default(GNOME_DIALOG(menuWin), 0);
    gtk_signal_connect(GTK_OBJECT(menuWin), "destroy",
            GTK_SIGNAL_FUNC(ghack_menu_destroy),
            NULL);
    gtk_signal_connect (GTK_OBJECT (menuWin), "delete_event",
            GTK_SIGNAL_FUNC (ghack_menu_hide),
            NULL);
          
    gtk_signal_connect(GTK_OBJECT(menuWin), "ghack_clear",
            GTK_SIGNAL_FUNC(ghack_menu_window_clear),
            NULL);
    gtk_signal_connect(GTK_OBJECT(menuWin), "ghack_display",
                       GTK_SIGNAL_FUNC(ghack_menu_window_display),
                       NULL);
    gtk_signal_connect(GTK_OBJECT(menuWin), "ghack_start_menu",
                       GTK_SIGNAL_FUNC(ghack_menu_window_start_menu),
                       NULL);
    gtk_signal_connect(GTK_OBJECT(menuWin), "ghack_add_menu",
                       GTK_SIGNAL_FUNC(ghack_menu_window_add_menu),
                       NULL);
    gtk_signal_connect(GTK_OBJECT(menuWin), "ghack_end_menu",
                       GTK_SIGNAL_FUNC(ghack_menu_window_end_menu),
                       NULL);
    gtk_signal_connect(GTK_OBJECT(menuWin), "ghack_select_menu",
                       GTK_SIGNAL_FUNC(ghack_menu_window_select_menu),
                       NULL);
    gtk_signal_connect(GTK_OBJECT(menuWin), "ghack_putstr",
                       GTK_SIGNAL_FUNC(ghack_menu_window_put_string),
                       NULL);
    gtk_signal_connect(GTK_OBJECT(menuWin), "key_press_event",
                       GTK_SIGNAL_FUNC(ghack_menu_window_key),
                       NULL);
    /* Center the dialog over parent */
    g_assert (parent != NULL);
    g_assert (menuWin != NULL);
    g_assert (GTK_IS_WINDOW (parent));
    g_assert (GNOME_IS_DIALOG (menuWin));
    gnome_dialog_set_parent (GNOME_DIALOG (menuWin), GTK_WINDOW (parent));
    
    return menuWin;
}
int ghack_menu_ext_cmd (void)
Definition at line 693 of file gnmenu.c.
References extMenu::charIdx, clist, extMenu::curItem, ext_func_tab::ef_desc, ext_func_tab::ef_txt, extcmdlist, FALSE, ghack_ext_key_hit(), ghack_get_main_window(), ghack_menu_row_selected(), extMenu::lastTime, NULL, extMenu::numRows, and TRUE.
Referenced by gnome_get_ext_cmd().
{
    int n;
    GtkWidget* dialog;
    GtkWidget* swin;
    GtkWidget* frame1;
    GtkWidget* clist;
    extMenu info;
    dialog = gnome_dialog_new("Extended Commands",
                  GNOME_STOCK_BUTTON_OK,
                  GNOME_STOCK_BUTTON_CANCEL,
                  NULL);
    gnome_dialog_close_hides(GNOME_DIALOG(dialog), FALSE);
    gtk_signal_connect(GTK_OBJECT(dialog), "key_press_event",
               GTK_SIGNAL_FUNC(ghack_ext_key_hit), &info);
    frame1 = gtk_frame_new("Make your selection");
    gtk_object_set_data(GTK_OBJECT(dialog), "frame1", frame1);
    gtk_widget_show(frame1);
    gtk_container_border_width(GTK_CONTAINER(frame1), 3);
    swin = gtk_scrolled_window_new(NULL, NULL);
    clist = gtk_clist_new(2);
    gtk_object_set_data(GTK_OBJECT(dialog), "clist", clist);
    gtk_widget_set_usize(clist, 500, 400);
    gtk_container_add(GTK_CONTAINER(swin), clist);
    gtk_scrolled_window_set_policy(GTK_SCROLLED_WINDOW(swin),
                   GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
    gtk_signal_connect(GTK_OBJECT(clist), "select_row",
               GTK_SIGNAL_FUNC(ghack_menu_row_selected),
      NULL);
    gtk_container_add(GTK_CONTAINER(frame1), swin);
    gtk_box_pack_start_defaults(GTK_BOX(GNOME_DIALOG(dialog)->vbox), frame1);
    /* Add the extended commands into the list here... */
    for (n = 0; extcmdlist[n].ef_txt; ++n) {
    const char *text[3]={extcmdlist[n].ef_txt,extcmdlist[n].
      ef_desc,NULL};
    gtk_clist_insert(GTK_CLIST(clist), n, (char**) text);
    }
    /* fill in starting info fields */
    info.curItem = -1;
    info.numRows = n;
    info.charIdx = 0;
    info.lastTime = 0;
    gtk_clist_columns_autosize(GTK_CLIST(clist));
    gtk_widget_show_all(swin);
    /* Center the dialog over over parent */
    gnome_dialog_set_default(GNOME_DIALOG(dialog), 0);
    gtk_window_set_modal(GTK_WINDOW(dialog), TRUE);
    gnome_dialog_set_parent(GNOME_DIALOG(dialog),
                GTK_WINDOW(ghack_get_main_window()));
    /* Run the dialog -- returning whichever button was pressed */
    n = gnome_dialog_run_and_close(GNOME_DIALOG(dialog));
    /* Quit on button 2 or error */
    return (n != 0) ? -1 : info.curItem;
}
int ghack_menu_window_select_menu (GtkWidget * menuWin, MENU_ITEM_P ** _selected, gint how)
Definition at line 211 of file gnmenu.c.
References clist, menuItem::identifier, MENU_ITEM_P, NULL, PICK_ANY, PICK_NONE, and TRUE.
Referenced by ghack_init_menu_window(), and gnome_select_menu().
{
   gint rc;
   guint num_sel, i, idx;
   GtkWidget *clist;
   GList *cur;
   MENU_ITEM_P *selected = NULL;
   menuItem* item;
   g_assert (_selected != NULL);
   *_selected = NULL;
   if (how == PICK_NONE) {
     gnome_dialog_close_hides (GNOME_DIALOG (menuWin), TRUE);
     rc = gnome_dialog_run_and_close (GNOME_DIALOG (menuWin));
     return(rc == 1 ? -1 : 0);
   }
   clist = GTK_WIDGET (gtk_object_get_data (GTK_OBJECT (menuWin), "clist"));
   g_assert (clist != NULL);
   gtk_object_set_data (GTK_OBJECT (clist), "selection_mode",
                   GINT_TO_POINTER ((how == PICK_ANY)?
               GTK_SELECTION_MULTIPLE : GTK_SELECTION_SINGLE));
   gtk_clist_set_selection_mode (GTK_CLIST (clist),
       (how == PICK_ANY)? GTK_SELECTION_MULTIPLE : GTK_SELECTION_SINGLE);
   gnome_dialog_close_hides (GNOME_DIALOG (menuWin), TRUE);
   rc = gnome_dialog_run_and_close (GNOME_DIALOG (menuWin));
   if ((rc == 1) || (GTK_CLIST (clist)->selection == NULL)) {
     return(-1);
   }
   num_sel = g_list_length (GTK_CLIST (clist)->selection);
   if (num_sel < 1) {
     return(-1);
   }
   /* fill in array with selections from clist */
   selected = g_new0(MENU_ITEM_P, num_sel);
   g_assert (selected != NULL);
   cur = GTK_CLIST (clist)->selection;
   i = 0;
   while (cur) {
     g_assert (i < num_sel);
     /* grab row number from clist selection list */
     idx = GPOINTER_TO_INT (cur->data);
     item = (menuItem*) gtk_clist_get_row_data(GTK_CLIST (clist), idx);
     selected[i].item = item->identifier;
     selected[i].count = -1;
     cur = g_list_next(cur);
     i++;
   }
   *_selected = selected;
   return((int) num_sel);
}