nethack/win/gnome/gnstatus.h File Reference
#include <gnome.h>
*
#include `config.h`
*
#include `global.h`
*
Functions
GtkWidget * ghack_init_status_window ()
Function Documentation
GtkWidget* ghack_init_status_window ()
Definition at line 146 of file gnstatus.c.
References A_NEUTRAL, acLabel, alignLabel, alignPix, bigGreenStyle, bigRedStyle, bigStyle, blind_xpm, blindLabel, blindPix, cha_xpm, chaLabel, chaPix, cns_xpm, color_green, color_red, confuLabel, confuPix, confused_xpm, conLabel, conPix, dex_xpm, dexLabel, dexPix, dgnLevelLabel, encumbLabel, encumbPix, expLabel, FALSE, ghack_delay(), ghack_fade_highlighting(), ghack_status_window_clear(), ghack_status_window_cursor_to(), ghack_status_window_put_string(), goldLabel, greenStyle, hallu_xpm, halluLabel, halluPix, hpLabel, hungerLabel, hungerPix, hungry_xpm, int_xpm, intLabel, intPix, lastAC, lastAlignment, lastAu, lastBlind, lastCha, lastCon, lastConf, lastDepth, lastDex, lastEncumb, lastExp, lastHalu, lastHP, lastHungr, lastInt, lastLevel, lastMHP, lastMPOW, lastPOW, lastSick, lastStr, lastStun, lastWis, levlLabel, neutral_xpm, normalStyle, NULL, powLabel, redStyle, scoreLabel, sick_fp_xpm, sickLabel, sickPix, slt_enc_xpm, statTable, str_xpm, strLabel, strPix, stunLabel, stunned_xpm, stunPix, timeLabel, titleLabel, TRUE, wis_xpm, wisLabel, and wisPix.
Referenced by gnome_create_nhwindow_by_id().
{
    GtkWidget *horizSep0, *horizSep1, *horizSep2, *horizSep3;
    GtkWidget *statsHBox, *strVBox, *dexVBox, *intVBox, *statHBox;
    GtkWidget *wisVBox, *conVBox, *chaVBox;
    GtkWidget *alignVBox, *hungerVBox, *sickVBox, *blindVBox;
    GtkWidget *stunVBox, *halluVBox, *confuVBox, *encumbVBox;
   
    /* Set up a (ridiculous) initial state */
    lastDepth = 9999;
    lastStr = 9999;
    lastInt = 9999;
    lastWis = 9999;
    lastDex = 9999;
    lastCon = 9999;
    lastCha = 9999;
    lastAu = 9999;
    lastHP = 9999;
    lastMHP = 9999;
    lastLevel = 9999;
    lastPOW = 9999;
    lastMPOW = 9999;
    lastAC = 9999;
    lastExp = 9999;
    lastAlignment = A_NEUTRAL; /* start off guessing neutral */
    lastHungr = 9999;
    lastConf = 9999;
    lastBlind = 9999;
    lastStun = 9999;
    lastHalu = 9999;
    lastSick = 9999;
    lastEncumb = 9999;
    statTable = gtk_table_new(10, 8, FALSE);
    gtk_table_set_row_spacings(GTK_TABLE(statTable), 1);
    gtk_table_set_col_spacings(GTK_TABLE(statTable), 1);
    /* Begin the first row of the table -- the title */
    titleLabel = gtk_label_new(_("GnomeHack!"));
    gtk_table_attach(GTK_TABLE(statTable), titleLabel,
        0, 8, 0, 1, GTK_FILL, 0, 0, 0);
    if (!normalStyle)
      normalStyle = gtk_style_copy (
            gtk_widget_get_style (GTK_WIDGET (titleLabel)));
    /* Set up some styles to draw stuff with */
    if (!redStyle) {
      g_assert (greenStyle == NULL);
      g_assert (bigStyle == NULL);
      g_assert (bigRedStyle == NULL);
      g_assert (bigGreenStyle == NULL);
      greenStyle = gtk_style_copy (normalStyle);
      redStyle = gtk_style_copy (normalStyle);
      bigRedStyle = gtk_style_copy (normalStyle);
      bigGreenStyle = gtk_style_copy (normalStyle);
      bigStyle = gtk_style_copy (normalStyle);
      greenStyle->fg[GTK_STATE_NORMAL] = color_green;
      redStyle->fg[GTK_STATE_NORMAL] = color_red;
      bigRedStyle->fg[GTK_STATE_NORMAL] = color_red;
      bigGreenStyle->fg[GTK_STATE_NORMAL] = color_green;
      gdk_font_unref (bigRedStyle->font);
      gdk_font_unref (bigGreenStyle->font);
      bigRedStyle->font = gdk_font_load("-misc-fixed-*-*-*-*-20-*-*-*-*-*-*-*");
      bigGreenStyle->font = gdk_font_load("-misc-fixed-*-*-*-*-20-*-*-*-*-*-*-*");
      gdk_font_unref (bigStyle->font);
      bigStyle->font = gdk_font_load ("-misc-fixed-*-*-*-*-20-*-*-*-*-*-*-*");
    }
    gtk_widget_set_style (GTK_WIDGET (titleLabel), bigStyle);
    
    /* Begin the second row */
    dgnLevelLabel = gtk_label_new (_ ("Nethack for Gnome"));
    gtk_table_attach (GTK_TABLE (statTable), dgnLevelLabel,
        0, 8, 1, 2, GTK_FILL, 0, 0, 0);
    gtk_widget_set_style (GTK_WIDGET (dgnLevelLabel), bigStyle);
    
    /* Begin the third row */
    horizSep0 = gtk_hseparator_new ();
    gtk_table_attach (GTK_TABLE (statTable), horizSep0,
        0, 8, 2, 3, GTK_FILL, GTK_FILL, 0, 0);
    /* Begin the fourth row */
    statsHBox = gtk_hbox_new (TRUE, 0);
    strVBox = gtk_vbox_new (FALSE, 0);
    strPix = gnome_pixmap_new_from_xpm_d(str_xpm);
    strLabel = gtk_label_new("STR: ");
    gtk_box_pack_start (GTK_BOX (strVBox), strPix, TRUE, TRUE, 2);
    gtk_box_pack_start (GTK_BOX (strVBox), strLabel, TRUE, TRUE, 2);
    gtk_box_pack_start (GTK_BOX(statsHBox), GTK_WIDGET(strVBox), TRUE, TRUE, 2);
    dexVBox = gtk_vbox_new (FALSE, 0);
    dexPix = gnome_pixmap_new_from_xpm_d(dex_xpm);
    dexLabel = gtk_label_new("DEX: ");
    gtk_box_pack_start (GTK_BOX (dexVBox), dexPix, TRUE, TRUE, 2);
    gtk_box_pack_start (GTK_BOX (dexVBox), dexLabel, TRUE, TRUE, 2);
    gtk_box_pack_start (GTK_BOX(statsHBox), GTK_WIDGET(dexVBox), TRUE, TRUE, 2);
    conVBox = gtk_vbox_new (FALSE, 0);
    conPix = gnome_pixmap_new_from_xpm_d(cns_xpm);
    conLabel = gtk_label_new("CON: ");
    gtk_box_pack_start (GTK_BOX (conVBox), conPix, TRUE, TRUE, 2);
    gtk_box_pack_start (GTK_BOX (conVBox), conLabel, TRUE, TRUE, 2);
    gtk_box_pack_start (GTK_BOX(statsHBox), GTK_WIDGET(conVBox), TRUE, TRUE, 2);
    intVBox = gtk_vbox_new (FALSE, 0);
    intPix = gnome_pixmap_new_from_xpm_d(int_xpm);
    intLabel = gtk_label_new("INT: ");
    gtk_box_pack_start (GTK_BOX (intVBox), intPix, TRUE, TRUE, 2);
    gtk_box_pack_start (GTK_BOX (intVBox), intLabel, TRUE, TRUE, 2);
    gtk_box_pack_start (GTK_BOX(statsHBox), GTK_WIDGET(intVBox), TRUE, TRUE, 2);
    wisVBox = gtk_vbox_new (FALSE, 0);
    wisPix = gnome_pixmap_new_from_xpm_d(wis_xpm);
    wisLabel = gtk_label_new("WIS: ");
    gtk_box_pack_start (GTK_BOX (wisVBox), wisPix, TRUE, TRUE, 2);
    gtk_box_pack_start (GTK_BOX (wisVBox), wisLabel, TRUE, TRUE, 2);
    gtk_box_pack_start (GTK_BOX(statsHBox), GTK_WIDGET(wisVBox), TRUE, TRUE, 2);
    chaVBox = gtk_vbox_new (FALSE, 0);
    chaPix = gnome_pixmap_new_from_xpm_d(cha_xpm);
    chaLabel = gtk_label_new("CHA: ");
    gtk_box_pack_start (GTK_BOX (chaVBox), chaPix, TRUE, TRUE, 2);
    gtk_box_pack_start (GTK_BOX (chaVBox), chaLabel, TRUE, TRUE, 2);
    gtk_box_pack_start (GTK_BOX(statsHBox), GTK_WIDGET(chaVBox), TRUE, TRUE, 2);
    
    gtk_table_attach(GTK_TABLE(statTable), GTK_WIDGET(statsHBox),
        0, 8, 3, 4, GTK_FILL, 0, 0, 0);
    /* Begin the fifth row */
    horizSep1 = gtk_hseparator_new();
    gtk_table_attach(GTK_TABLE(statTable), horizSep1,
        0, 8, 4, 5, GTK_FILL, GTK_FILL, 0, 0);
    /* Begin the sixth row */
    hpLabel = gtk_label_new("HP: ");
    gtk_table_attach(GTK_TABLE(statTable), hpLabel,
        0, 1, 5, 6, GTK_FILL, 0, 0, 0);
    
    acLabel = gtk_label_new("AC: ");
    gtk_table_attach(GTK_TABLE(statTable), acLabel,
        2, 3, 5, 6, GTK_FILL, 0, 0, 0);
    
    powLabel = gtk_label_new("Power: ");
    gtk_table_attach(GTK_TABLE(statTable), powLabel,
        4, 5, 5, 6, GTK_FILL, 0, 0, 0);
    
    goldLabel = gtk_label_new("Au: ");
    gtk_table_attach(GTK_TABLE(statTable), goldLabel,
        6, 7, 5, 6, GTK_FILL, 0, 0, 0);
    
    /* Begin the seventh row */
    horizSep2 = gtk_hseparator_new();
    gtk_table_attach(GTK_TABLE(statTable), horizSep2,
        0, 8, 6, 7, GTK_FILL, GTK_FILL, 0, 0);
    
    /* Begin the eigth row */
    levlLabel = gtk_label_new("Level: ");
    gtk_table_attach(GTK_TABLE(statTable), levlLabel,
        0, 1, 7, 8, GTK_FILL, 0, 0, 0);
    
    expLabel = gtk_label_new("Exp: ");
    gtk_table_attach(GTK_TABLE(statTable), expLabel,
        2, 3, 7, 8, GTK_FILL, 0, 0, 0);
   
    timeLabel = gtk_label_new("Time: ");
    gtk_table_attach(GTK_TABLE(statTable), timeLabel,
        4, 5, 7, 8, GTK_FILL, 0, 0, 0);
    
    scoreLabel = gtk_label_new("Score: ");
    gtk_table_attach(GTK_TABLE(statTable), scoreLabel,
        6, 7, 7, 8, GTK_FILL, 0, 0, 0);
    
    /* Begin the ninth row */
    horizSep3 = gtk_hseparator_new();
    gtk_table_attach(GTK_TABLE(statTable), horizSep3,
        0, 8, 8, 9, GTK_FILL, GTK_FILL, 0, 0);
    
    /* Begin the tenth and last row */
    statHBox = gtk_hbox_new (FALSE, 0);
    alignVBox = gtk_vbox_new (FALSE, 0);
    alignPix = gnome_pixmap_new_from_xpm_d(neutral_xpm);
    alignLabel = gtk_label_new("Neutral");
    gtk_box_pack_start (GTK_BOX (alignVBox), alignPix, TRUE, TRUE, 2);
    gtk_box_pack_start (GTK_BOX (alignVBox), alignLabel, TRUE,
      TRUE, 2);
    gtk_box_pack_start (GTK_BOX(statHBox), GTK_WIDGET(alignVBox), TRUE,
      FALSE, 2);
    
    hungerVBox = gtk_vbox_new (FALSE, 0);
    hungerPix = gnome_pixmap_new_from_xpm_d(hungry_xpm);
    hungerLabel = gtk_label_new("Hungry");
    gtk_box_pack_start (GTK_BOX (hungerVBox), hungerPix, TRUE, TRUE, 2);
    gtk_box_pack_start (GTK_BOX (hungerVBox), hungerLabel, TRUE,
      TRUE, 2);
    gtk_box_pack_start (GTK_BOX(statHBox), GTK_WIDGET(hungerVBox), TRUE,
      FALSE, 2);
    
    sickVBox = gtk_vbox_new (FALSE, 0);
    sickPix = gnome_pixmap_new_from_xpm_d(sick_fp_xpm);
    sickLabel = gtk_label_new("FoodPois");
    gtk_box_pack_start (GTK_BOX (sickVBox), sickPix, TRUE, TRUE, 2);
    gtk_box_pack_start (GTK_BOX (sickVBox), sickLabel, TRUE, TRUE, 2);
    gtk_box_pack_start (GTK_BOX(statHBox), GTK_WIDGET(sickVBox), TRUE, FALSE, 2);
    
    blindVBox = gtk_vbox_new (FALSE, 0);
    blindPix = gnome_pixmap_new_from_xpm_d(blind_xpm);
    blindLabel = gtk_label_new("Blind");
    gtk_box_pack_start (GTK_BOX (blindVBox), blindPix, TRUE, TRUE, 2);
    gtk_box_pack_start (GTK_BOX (blindVBox), blindLabel, TRUE,
      TRUE, 2);
    gtk_box_pack_start (GTK_BOX(statHBox), GTK_WIDGET(blindVBox), TRUE,
      FALSE, 2);
    
    stunVBox = gtk_vbox_new (FALSE, 0);
    stunPix = gnome_pixmap_new_from_xpm_d(stunned_xpm);
    stunLabel = gtk_label_new("Stun");
    gtk_box_pack_start (GTK_BOX (stunVBox), stunPix, TRUE, TRUE, 2);
    gtk_box_pack_start (GTK_BOX (stunVBox), stunLabel, TRUE, TRUE, 2);
    gtk_box_pack_start (GTK_BOX(statHBox), GTK_WIDGET(stunVBox), TRUE, FALSE, 2);
    
    confuVBox = gtk_vbox_new (FALSE, 0);
    confuPix = gnome_pixmap_new_from_xpm_d(confused_xpm);
    confuLabel = gtk_label_new("Confused");
    gtk_box_pack_start (GTK_BOX (confuVBox), confuPix, TRUE, TRUE, 2);
    gtk_box_pack_start (GTK_BOX (confuVBox), confuLabel, TRUE,
      TRUE, 2);
    gtk_box_pack_start (GTK_BOX(statHBox), GTK_WIDGET(confuVBox), TRUE,
      FALSE, 2);
    
    halluVBox = gtk_vbox_new (FALSE, 0);
    halluPix = gnome_pixmap_new_from_xpm_d(hallu_xpm);
    halluLabel = gtk_label_new("Hallu");
    gtk_box_pack_start (GTK_BOX (halluVBox), halluPix, TRUE, TRUE, 2);
    gtk_box_pack_start (GTK_BOX (halluVBox), halluLabel, TRUE,
      TRUE, 2);
    gtk_box_pack_start (GTK_BOX(statHBox), GTK_WIDGET(halluVBox), TRUE,
      FALSE, 2);
    
    encumbVBox = gtk_vbox_new (FALSE, 0);
    encumbPix = gnome_pixmap_new_from_xpm_d(slt_enc_xpm);
    encumbLabel = gtk_label_new("Burdened");
    gtk_box_pack_start (GTK_BOX (encumbVBox), encumbPix, TRUE, TRUE, 2);
    gtk_box_pack_start (GTK_BOX (encumbVBox), encumbLabel, TRUE,
      TRUE, 2);
    gtk_box_pack_start (GTK_BOX(statHBox), GTK_WIDGET(encumbVBox), TRUE,
      FALSE, 2);
    gtk_table_attach(GTK_TABLE(statTable), GTK_WIDGET(statHBox),
        0, 8, 9, 10, GTK_FILL, GTK_FILL, 0, 0);
    
    /* Set up the necessary signals */
    gtk_signal_connect (GTK_OBJECT (statTable),
        "ghack_fade_highlight",
        GTK_SIGNAL_FUNC (ghack_fade_highlighting),
        NULL);
    gtk_signal_connect (GTK_OBJECT (statTable),
        "ghack_putstr",
        GTK_SIGNAL_FUNC (ghack_status_window_put_string),
        NULL);
    gtk_signal_connect (GTK_OBJECT (statTable),
        "ghack_clear",
        GTK_SIGNAL_FUNC (ghack_status_window_clear),
        NULL);
    gtk_signal_connect (GTK_OBJECT (statTable),
        "ghack_curs",
        GTK_SIGNAL_FUNC (ghack_status_window_cursor_to),
        NULL);
    gtk_signal_connect(GTK_OBJECT (statTable),
        "gnome_delay_output",
        GTK_SIGNAL_FUNC(ghack_delay),
        NULL);
    /* Lastly, show the status window and everything in it */
    gtk_widget_show_all(statTable);
    return GTK_WIDGET(statTable);
}