nethack/win/gnome/gnworn.h File Reference
#include <gnome.h>
*
#include `config.h`
*
#include `global.h`
*
Functions
GtkWidget * ghack_init_worn_window ()
Function Documentation
GtkWidget* ghack_init_worn_window ()
Definition at line 40 of file gnworn.c.
References FALSE, ghack_worn_display(), image_of_worn_object(), NULL, TRUE, worn_contents, WORN_HEIGHT, and WORN_WIDTH.
Referenced by gnome_create_nhwindow_by_id().
{
    GtkWidget *top;
    GtkWidget *table;
    GtkWidget *tablealign;
    GtkWidget *label;
    int i,j;
    top = gtk_vbox_new(FALSE, 2);
    table = gtk_table_new(WORN_HEIGHT, WORN_WIDTH, TRUE);
    for (i = 0; i < WORN_HEIGHT; i++) {
    for (j = 0; j < WORN_WIDTH; j++) {
        worn_contents[i][j] =
        gnome_pixmap_new_from_imlib(image_of_worn_object(
      NULL));
        last_worn_objects[i][j] = NULL; /* a pointer that will never be */
        gtk_table_attach(GTK_TABLE(table), GTK_WIDGET(worn_contents[i][j]),
                 j, j+1, i, i+1, 0, 0, 0, 0);
    }
    }
    tablealign = gtk_alignment_new(0.5, 0.0, 0.0, 1.0);
    gtk_box_pack_start(GTK_BOX(top), tablealign, FALSE, FALSE, 0);
    gtk_container_add(GTK_CONTAINER(tablealign), table);
    label = gtk_label_new("Equipment");
    gtk_label_set_justify(GTK_LABEL(label), GTK_JUSTIFY_CENTER);
    gtk_box_pack_start(GTK_BOX(top), label, FALSE, FALSE, 0);
    gtk_signal_connect(GTK_OBJECT(top), "ghack_display",
               GTK_SIGNAL_FUNC(ghack_worn_display), NULL);
    return top;
}