nethack/win/gem/gr_rect.h File Reference
#include <e_gem.h>
*
Data Structures
struct dirty_rect
Functions
dirty_rect * new_dirty_rect (int size)
void delete_dirty_rect (dirty_rect *this)
int add_dirty_rect (dirty_rect *dr, GRECT *area)
int get_dirty_rect (dirty_rect *dr, GRECT *area)
int clear_dirty_rect (dirty_rect *dr)
int resize_dirty_rect (dirty_rect *dr, int new_size)
Function Documentation
int add_dirty_rect (dirty_rect * dr, GRECT * area)
Definition at line 40 of file gr_rect.c.
References cost(), FALSE, gc_area(), gc_combine(), gc_inside(), gc_touch(), dirty_rect::max, dirty_rect::rects, TRUE, and dirty_rect::used.
Referenced by mar_add_status_str(), and mar_display_nhwindow().
                                              {
    int cursor;
    long lowestcost=9999999L;
    int cheapest=-1;
    int cheapestmerge1=-1;
    int cheapestmerge2=-1;
    int merge1;
    int merge2;
    for (cursor=0; cursor<dr->used; cursor++) {
        if (gc_inside(&dr->rects[cursor],area)) {
            /* Wholly contained already. */
            return(TRUE);
        }
    }
    for (cursor=0; cursor<dr->used; cursor++) {
        if (gc_touch(&dr->rects[cursor],area)) {
            GRECT larger=dr->rects[cursor];
            long cost;
            gc_combine(&larger,area);
            cost=gc_area(&larger)-gc_area(&dr->rects[cursor]);
            if (cost < lowestcost) {
                int bad=FALSE,c;
                for (c=0; c<dr->used && !bad; c++) {
                    bad=gc_touch(&dr->rects[c],&larger) && c!=cursor;
                }
                if (!bad) {
                    cheapest=cursor;
                    lowestcost=cost;
                }
            }
        }
    }
    if (cheapest>=0) {
        gc_combine(&dr->rects[cheapest],area);
        return(TRUE);
    }
    if (dr->used < dr->max) {
        dr->rects[dr->used++]=*area;
        return(TRUE);
    }
    // Do cheapest of:
    // add to closest cluster
    // do cheapest cluster merge, add to new cluster
    lowestcost=9999999L;
    cheapest=-1;
    for (cursor=0; cursor<dr->used; cursor++) {
        GRECT larger=dr->rects[cursor];
        long cost;
        gc_combine(&larger,area);
        cost=gc_area(&larger)-gc_area(&dr->rects[cursor]);
        if (cost < lowestcost) {
            int bad=FALSE, c;
            for (c=0; c<dr->used && !bad; c++) {
                bad=gc_touch(&dr->rects[c],&larger) && c!=cursor;
            }
            if (!bad) {
                cheapest=cursor;
                lowestcost=cost;
            }
        }
    }
    // XXX could make an heuristic guess as to whether we
    // XXX need to bother looking for a cheap merge.
    for (merge1=0; merge1<dr->used; merge1++) {
        for (merge2=0; merge2<dr->used; merge2++) {
            if (merge1!=merge2) {
                GRECT larger=dr->rects[merge1];
                long cost;
                gc_combine(&larger,&dr->rects[merge2]);
                cost=gc_area(&larger)-gc_area(&dr->rects[merge1])-
      gc_area(&dr->rects[merge2]);
                if (cost < lowestcost) {
                    int bad=FALSE, c;
                    for (c=0; c<dr->used && !bad; c++) {
                        bad=gc_touch(&dr->rects[c],&larger) && c!=cursor;
                    }
                    if (!bad) {
                        cheapestmerge1=merge1;
                        cheapestmerge2=merge2;
                        lowestcost=cost;
                    }
                }
            }
        }
    }
    if (cheapestmerge1>=0) {
        gc_combine(&dr->rects[cheapestmerge1],&dr->rects[cheapestmerge2]);
        dr->rects[cheapestmerge2]=dr->rects[dr->used-1];
        dr->rects[dr->used-1]=*area;
    } else {
        gc_combine(&dr->rects[cheapest],area);
    }
    // NB: clusters do not intersect (or intersection will
    // overwrite). This is a result of the above algorithm,
    // given the assumption that (x,y) are ordered topleft
    // to bottomright.
    return(TRUE);
}
int clear_dirty_rect (dirty_rect * dr)
Definition at line 143 of file gr_rect.c.
References TRUE, and dirty_rect::used.
                                    {
    if(dr)
        dr->used=0;
    return(TRUE);
}
void delete_dirty_rect (dirty_rect * this)
Definition at line 25 of file gr_rect.c.
References free(), max, and NULL.
                                        {
    if(this==NULL)
        return;
    if(this->rects)
        free(this->rects);
    /* In case the Pointer is reused wrongly */
    this->rects=NULL;
    this->max=0;
    this->used=0;
    free(this);
}
int get_dirty_rect (dirty_rect * dr, GRECT * area)
Definition at line 137 of file gr_rect.c.
References FALSE, dirty_rect::max, NULL, dirty_rect::rects, TRUE, and dirty_rect::used.
Referenced by mar_display_nhwindow().
                                              {
    if(dr==NULL || area==NULL || dr->rects==NULL || dr->used<=0 || dr->
      max<=0)
        return(FALSE);
    *area=dr->rects[--dr->used];
    return(TRUE);
}
dirty_rect* new_dirty_rect (int size)
Definition at line 10 of file gr_rect.c.
References free(), and NULL.
Referenced by mar_create_window().
                                    {
    dirty_rect *new=NULL;
    if(size>0){
        new=(dirty_rect *)calloc(1L,sizeof(dirty_rect));
        if(new){
            new->rects=(GRECT *)calloc((long)size,sizeof(GRECT));
            if(new->rects==NULL){
                free(new);
                return(NULL);
            }
            new->max=size;
        }
    }
    return(new);
}
int resize_dirty_rect (dirty_rect * dr, int new_size)
Definition at line 148 of file gr_rect.c.
References FALSE.
                                                  {
    return(FALSE);
}