nethack/sys/share/ioctl.c File Reference
#include `hack.h`
*
#include <termio.h>
*
Functions
void getwindowsz ()
void getioctls ()
void setioctls ()
Variables
struct termio termio
Function Documentation
void getioctls ()
Definition at line 113 of file ioctl.c.
References getwindowsz(), stdin, and termio.
Referenced by gettty().
{
#ifdef BSD_JOB_CONTROL
    (void) ioctl(fileno(stdin), (int) TIOCGLTC, (char *) &ltchars);
    (void) ioctl(fileno(stdin), (int) TIOCSLTC, (char *) &ltchars0);
#else
# ifdef POSIX_TYPES
    (void) tcgetattr(fileno(stdin), &termio);
# else
# if defined(TCSETS) && !defined(AIX_31)
    (void) ioctl(fileno(stdin), (int) TCGETS, &termio);
# else
    (void) ioctl(fileno(stdin), (int) TCGETA, &termio);
# endif
# endif
#endif
    getwindowsz();
#ifdef AUX
    (void) signal (SIGTSTP , catch_stp) ;
#endif
}
void getwindowsz ()
Definition at line 90 of file ioctl.c.
References CO, LI, and stdin.
Referenced by getioctls().
{
#ifdef USE_WIN_IOCTL
    /*
     * ttysize is found on Suns and BSD
     * winsize is found on Suns, BSD, and Ultrix
     */
    struct winsize ttsz;
    if (ioctl(fileno(stdin), (int)TIOCGWINSZ, (char *)&ttsz) != -1) {
    /*
     * Use the kernel's values for lines and columns if it has
     * any idea.
     */
    if (ttsz.ws_row)
        LI = ttsz.ws_row;
    if (ttsz.ws_col)
        CO = ttsz.ws_col;
    }
#endif
}
void setioctls ()
Definition at line 136 of file ioctl.c.
References stdin, and termio.
Referenced by settty().
{
#ifdef BSD_JOB_CONTROL
    (void) ioctl(fileno(stdin), (int) TIOCSLTC, (char *) &ltchars);
#else
# ifdef POSIX_TYPES
    (void) tcsetattr(fileno(stdin), TCSADRAIN, &termio);
# else
# if defined(TCSETS) && !defined(AIX_31)
    (void) ioctl(fileno(stdin), (int) TCSETSW, &termio);
# else
    (void) ioctl(fileno(stdin), (int) TCSETAW, &termio);
# endif
# endif
#endif
}
Variable Documentation
struct termio termio
Definition at line 54 of file ioctl.c.
Referenced by getioctls(), and setioctls().