nethack/sys/share/lev_lex.c File Reference
#include `config.h`
*
#include `hack.h`
*
#include `lev_comp.h`
*
#include `sp_lev.h`
*
Data Structures
struct yy_buffer_state
Macros
#define FLEXHACK_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define yyconst const	/* some code inserted by flex will refer to yyconst */
#define YY_NULL 0
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
#define BEGIN yy_start = 1 + 2 *
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
#define YY_NEW_FILE yyrestart(yyin)
#define YY_END_OF_BUFFER_CHAR 0
#define YY_BUF_SIZE 16384
#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
#define yyless(n)
#define unput(c) yyunput(c, yytext_ptr)
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
#define YY_BUFFER_EOF_PENDING 2
#define YY_CURRENT_BUFFER yy_current_buffer
#define YY_FLUSH_BUFFER yy_flush_buffer(yy_current_buffer)
#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive)
#define yy_set_bol(at_bol)
#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)
#define yytext_ptr yytext
#define YY_DO_BEFORE_ACTION
#define YY_NUM_RULES 112
#define YY_END_OF_BUFFER 113
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define INITIAL 0
#define LEV_LEX_C
#define MAPC 1
#define YY_READ_BUF_SIZE 8192
#define ECHO (void) fwrite(yytext, yyleng, 1, yyout)
#define YY_INPUT(buf, result, max_size)
#define yyterminate() return YY_NULL
#define YY_START_STACK_INCR 25
#define YY_FATAL_ERROR(msg) yy_fatal_error(msg)
#define YY_USER_ACTION
#define YY_BREAK break;
#define YY_RULE_SETUP
#define YY_EXIT_FAILURE 2
#define yyless(n)
Typedefs
typedef struct yy_buffer_state * YY_BUFFER_STATE
typedef unsigned int yy_size_t
typedef unsigned char YY_CHAR
typedef int yy_state_type
Functions
void FDECL (yyrestart,(FILE *))
void FDECL (yy_switch_to_buffer,(YY_BUFFER_STATE))
void NDECL (yy_load_buffer_state)
YY_BUFFER_STATE FDECL (yy_create_buffer,(FILE *, int))
void FDECL (yy_delete_buffer,(YY_BUFFER_STATE))
void FDECL (yy_init_buffer,(YY_BUFFER_STATE, FILE *))
void FDECL (yy_flush_buffer,(YY_BUFFER_STATE))
static genericptr_t FDECL (yy_flex_alloc,(yy_size_t))
static genericptr_t FDECL (yy_flex_realloc2,(genericptr_t, yy_size_t, int))
static void FDECL (yy_flex_free,(genericptr_t))
static yy_state_type NDECL (yy_get_previous_state)
static yy_state_type FDECL (yy_try_NUL_trans,(yy_state_type))
static int NDECL (yy_get_next_buffer)
static void FDECL (yy_fatal_error,(const char *))
void FDECL (init_yyin,(FILE *))
void FDECL (init_yyout,(FILE *))
int NDECL (yywrap)
static void FDECL (yyunput,(int, char *))
static int NDECL (input)
int NDECL (yylex)
int yylex ()
static int yy_get_next_buffer ()
static yy_state_type yy_get_previous_state ()
static yy_state_type yy_try_NUL_trans (yy_state_type yy_current_state)
static void yyunput (int c, char *yy_bp)
static int input ()
void yyrestart (FILE *input_file)
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer)
void yy_load_buffer_state ()
YY_BUFFER_STATE yy_create_buffer (FILE *file, int size)
void yy_delete_buffer (YY_BUFFER_STATE b)
int FDECL (isatty,(int))
void yy_init_buffer (YY_BUFFER_STATE b, FILE *file)
void yy_flush_buffer (YY_BUFFER_STATE b)
static void yy_fatal_error (msg) const
static genericptr_t yy_flex_alloc (yy_size_t size)
static genericptr_t yy_flex_realloc2 (genericptr_t ptr, yy_size_t size, int old_size)
static void yy_flex_free (genericptr_t ptr)
void init_yyin (FILE *input_f)
void init_yyout (FILE *output_f)
Variables
int yyleng
FILE * yyin = (FILE *) 0
FILE * yyout = (FILE *) 0
static YY_BUFFER_STATE yy_current_buffer = 0
static char yy_hold_char
static int yy_n_chars
static char * yy_c_buf_p = (char *) 0
static int yy_init = 1
static int yy_start = 0
static int yy_did_buffer_switch_on_eof
char * yytext
static yyconst short int yy_accept [640]
static yyconst int yy_ec [256]
static yyconst int yy_meta [65]
static yyconst short int yy_base [645]
static yyconst short int yy_def [645]
static yyconst short int yy_nxt [862]
static yyconst short int yy_chk [862]
static yy_state_type yy_last_accepting_state
static char * yy_last_accepting_cpos
YYSTYPE yylval
int line_number = 1
int colon_line_number = 1
static char map [4096]
static int map_cnt = 0
Macro Definition Documentation
#define BEGIN yy_start = 1 + 2 *
Definition at line 27 of file lev_lex.c.
Referenced by yylex().
#define ECHO (void) fwrite(yytext, yyleng, 1, yyout)
Definition at line 798 of file lev_lex.c.
Referenced by yylex().
#define EOB_ACT_CONTINUE_SCAN 0
Definition at line 52 of file lev_lex.c.
Referenced by input(), yy_get_next_buffer(), and yylex().
#define EOB_ACT_END_OF_FILE 1
Definition at line 53 of file lev_lex.c.
Referenced by input(), yy_get_next_buffer(), and yylex().
#define EOB_ACT_LAST_MATCH 2
Definition at line 54 of file lev_lex.c.
Referenced by input(), yy_get_next_buffer(), and yylex().
#define FLEXHACK_SCANNER
Definition at line 6 of file lev_lex.c.
#define INITIAL 0
Definition at line 688 of file lev_lex.c.
Referenced by yylex().
#define LEV_LEX_C
Definition at line 693 of file lev_lex.c.
#define MAPC 1
Definition at line 764 of file lev_lex.c.
Referenced by yylex().
#define REJECT reject_used_but_not_detected
Definition at line 684 of file lev_lex.c.
#define unput(c) yyunput(c, yytext_ptr)
Definition at line 67 of file lev_lex.c.
#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)
Definition at line 188 of file lev_lex.c.
Referenced by yy_get_previous_state(), and yylex().
#define YY_BREAK break;
Definition at line 850 of file lev_lex.c.
Referenced by yylex().
#define YY_BUF_SIZE 16384
Definition at line 45 of file lev_lex.c.
Referenced by yylex(), and yyrestart().
#define YY_BUFFER_EOF_PENDING 2
Definition at line 130 of file lev_lex.c.
Referenced by yy_get_next_buffer().
#define YY_BUFFER_NEW 0
Definition at line 118 of file lev_lex.c.
Referenced by yy_flush_buffer(), and yylex().
#define YY_BUFFER_NORMAL 1
Definition at line 119 of file lev_lex.c.
Referenced by yylex().
#define YY_CURRENT_BUFFER yy_current_buffer
Definition at line 139 of file lev_lex.c.
#define YY_DO_BEFORE_ACTION
Value:
yytext_ptr = yy_bp; \
    yyleng = (int) (yy_cp - yy_bp); \
    yy_hold_char = *yy_cp; \
    *yy_cp = '\0'; \
    yy_c_buf_p = yy_cp;
Definition at line 204 of file lev_lex.c.
Referenced by yylex().
#define YY_END_OF_BUFFER 113
Definition at line 212 of file lev_lex.c.
Referenced by yylex().
#define YY_END_OF_BUFFER_CHAR 0
Definition at line 42 of file lev_lex.c.
Referenced by input(), yy_flush_buffer(), and yy_get_next_buffer().
#define YY_EXIT_FAILURE 2
Definition at line 1987 of file lev_lex.c.
Referenced by yy_fatal_error().
#define YY_FATAL_ERROR(msg) yy_fatal_error(msg)
Definition at line 838 of file lev_lex.c.
Referenced by input(), yy_create_buffer(), yy_get_next_buffer(), yylex(), and yyunput().
#define YY_FLEX_MAJOR_VERSION 2
Definition at line 7 of file lev_lex.c.
#define YY_FLEX_MINOR_VERSION 5
Definition at line 8 of file lev_lex.c.
#define YY_FLUSH_BUFFER yy_flush_buffer(yy_current_buffer)
Definition at line 166 of file lev_lex.c.
#define YY_INPUT(buf, result, max_size)
Value:
if (yy_current_buffer->yy_is_interactive) \
        { \
        int c = '*', n; \
        for (n = 0; n < max_size && \
                 (c = getc(yyin)) != EOF && c != '\n'; ++n) \
            buf[n] = (char) c; \
        if (c == '\n') \
            buf[n++] = (char) c; \
        if (c == EOF && ferror(yyin)) \
            YY_FATAL_ERROR("input in flex scanner failed"); \
        result = n; \
        } \
    else if (((result = fread(buf, 1, max_size, yyin)) == 0) \
          && ferror(yyin)) \
        YY_FATAL_ERROR("input in flex scanner failed");
Definition at line 805 of file lev_lex.c.
Referenced by yy_get_next_buffer().
#define YY_MORE_ADJ 0
Definition at line 686 of file lev_lex.c.
Referenced by input(), yy_get_next_buffer(), yy_get_previous_state(), and yylex().
#define yy_new_buffer yy_create_buffer
Definition at line 172 of file lev_lex.c.
#define YY_NEW_FILE yyrestart(yyin)
Definition at line 40 of file lev_lex.c.
Referenced by input(), and yylex().
#define YY_NULL 0
Definition at line 14 of file lev_lex.c.
#define YY_NUM_RULES 112
Definition at line 211 of file lev_lex.c.
#define YY_READ_BUF_SIZE 8192
Definition at line 789 of file lev_lex.c.
Referenced by yy_get_next_buffer().
#define YY_RULE_SETUP
Value:
if (yyleng > 0) \
        yy_current_buffer->yy_at_bol = \
                (yytext[yyleng - 1] == '\n'); \
    YY_USER_ACTION
Definition at line 853 of file lev_lex.c.
Referenced by yylex().
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
Definition at line 21 of file lev_lex.c.
Referenced by yy_get_previous_state(), and yylex().
#define yy_set_bol(at_bol)
Value:
{ \
    if (! yy_current_buffer) \
        yy_current_buffer = yy_create_buffer(
      yyin, YY_BUF_SIZE); \
    yy_current_buffer->yy_at_bol = at_bol; \
    }
Definition at line 181 of file lev_lex.c.
#define yy_set_interactive(is_interactive)
Value:
{ \
    if (! yy_current_buffer) \
        yy_current_buffer = yy_create_buffer(
      yyin, YY_BUF_SIZE); \
    yy_current_buffer->yy_is_interactive = is_interactive; \
    }
Definition at line 174 of file lev_lex.c.
#define YY_START ((yy_start - 1) / 2)
Definition at line 33 of file lev_lex.c.
Referenced by yylex().
#define YY_START_STACK_INCR 25
Definition at line 833 of file lev_lex.c.
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
Definition at line 37 of file lev_lex.c.
Referenced by yylex().
#define YY_USER_ACTION
Definition at line 845 of file lev_lex.c.
#define yyconst const	/* some code inserted by flex will refer to yyconst */
Definition at line 11 of file lev_lex.c.
#define yyless(n)
Value:
do \
        { \
        /* Undo effects of setting up yytext. */ \
        *yy_cp = yy_hold_char; \
        yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
        YY_DO_BEFORE_ACTION; /* set up yytext again */ \
        } \
    while (0)
Definition at line 2002 of file lev_lex.c.
#define yyless(n)
Value:
do \
        { \
        /* Undo effects of setting up yytext. */ \
        yytext[yyleng] = yy_hold_char; \
        yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
        yy_hold_char = *yy_c_buf_p; \
        *yy_c_buf_p = '\0'; \
        yyleng = n; \
        } \
    while (0)
Definition at line 2002 of file lev_lex.c.
#define yymore() yymore_used_but_not_detected
Definition at line 685 of file lev_lex.c.
#define YYSTATE YY_START
Definition at line 34 of file lev_lex.c.
#define yyterminate() return YY_NULL
Definition at line 828 of file lev_lex.c.
Referenced by yylex().
#define yytext_ptr yytext
Definition at line 194 of file lev_lex.c.
Referenced by input(), yy_get_next_buffer(), yy_get_previous_state(), yy_load_buffer_state(), yylex(), and yyunput().
Typedef Documentation
typedef struct yy_buffer_state* YY_BUFFER_STATE
Definition at line 47 of file lev_lex.c.
typedef unsigned char YY_CHAR
Definition at line 190 of file lev_lex.c.
typedef unsigned int yy_size_t
Definition at line 73 of file lev_lex.c.
typedef int yy_state_type
Definition at line 192 of file lev_lex.c.
Function Documentation
void FDECL (yyrestart , (FILE *))
void FDECL (yy_switch_to_buffer , (YY_BUFFER_STATE))
YY_BUFFER_STATE FDECL (yy_create_buffer , (FILE *, int))
void FDECL (yy_delete_buffer , (YY_BUFFER_STATE))
void FDECL (yy_init_buffer , (YY_BUFFER_STATE, FILE *))
void FDECL (yy_flush_buffer , (YY_BUFFER_STATE))
static genericptr_t FDECL (yy_flex_alloc , (yy_size_t)) [static]
static genericptr_t FDECL (yy_flex_realloc2 , (genericptr_t, yy_size_t, int)) [static]
static void FDECL (yy_flex_free , (genericptr_t)) [static]
static yy_state_type FDECL (yy_try_NUL_trans , (yy_state_type)) [static]
static void FDECL (yy_fatal_error , (const char *)) [static]
void FDECL (init_yyin , (FILE *))
void FDECL (init_yyout , (FILE *))
static void FDECL (yyunput , (int, char *)) [static]
int FDECL (isatty , (int))
void init_yyin (FILE * input_f)
Definition at line 2071 of file lev_lex.c.
References yyrestart().
{
#if defined(FLEX_SCANNER) || defined(FLEXHACK_SCANNER)
    if (yyin)
        yyrestart(input_f);
    else
#endif
        yyin = input_f;
}
void init_yyout (FILE * output_f)
Definition at line 2082 of file lev_lex.c.
References yyout.
{
    yyout = output_f;
}
static int input () [static]
Definition at line 1789 of file lev_lex.c.
References EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, yy_buffer_state::yy_at_bol, yy_c_buf_p, yy_did_buffer_switch_on_eof, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, yy_get_next_buffer(), yy_hold_char, YY_MORE_ADJ, yy_n_chars, YY_NEW_FILE, yytext_ptr, and yywrap().
    {
    int c;
    *yy_c_buf_p = yy_hold_char;
    if (*yy_c_buf_p == YY_END_OF_BUFFER_CHAR)
        {
        /* yy_c_buf_p now points to the character we want to return.
         * If this occurs *before* the EOB characters, then it's a
         * valid NUL; if not, then we've hit the end of the buffer.
         */
        if (yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars])
            /* This was really a NUL. */
            *yy_c_buf_p = '\0';
        else
            { /* need more input */
            yytext_ptr = yy_c_buf_p;
            ++yy_c_buf_p;
            switch (yy_get_next_buffer())
                {
                case EOB_ACT_END_OF_FILE:
                    {
                    if (yywrap())
                        {
                        yy_c_buf_p =
                        yytext_ptr + YY_MORE_ADJ;
                        return EOF;
                        }
                    if (! yy_did_buffer_switch_on_eof)
                        YY_NEW_FILE;
                    return input();
                    }
                case EOB_ACT_CONTINUE_SCAN:
                    yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
                    break;
                case EOB_ACT_LAST_MATCH:
                    YY_FATAL_ERROR(
                    "unexpected last match in input()");
                }
            }
        }
    c = *(unsigned char *) yy_c_buf_p; /* cast for 8-bit char's */
    *yy_c_buf_p = '\0'; /* preserve yytext */
    yy_hold_char = *++yy_c_buf_p;
    yy_current_buffer->yy_at_bol = (c == '\n');
    return c;
    }
void NDECL (yy_load_buffer_state)
static yy_state_type NDECL (yy_get_previous_state) [static]
static int NDECL (yy_get_next_buffer) [static]
int NDECL (yywrap)
static int NDECL (input) [static]
int NDECL (yylex)
YY_BUFFER_STATE yy_create_buffer (FILE * file, int size)
Definition at line 1893 of file lev_lex.c.
References yy_buffer_state::yy_buf_size, yy_buffer_state::yy_ch_buf, YY_FATAL_ERROR, yy_flex_alloc(), yy_init_buffer(), and yy_buffer_state::yy_is_our_buffer.
Referenced by yylex(), and yyrestart().
    {
    YY_BUFFER_STATE b;
    b = (YY_BUFFER_STATE) yy_flex_alloc(sizeof(struct
      yy_buffer_state));
    if (! b)
        YY_FATAL_ERROR("out of dynamic memory in yy_create_buffer()");
    b->yy_buf_size = size;
    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (char *) yy_flex_alloc(b->yy_buf_size + 2);
    if (! b->yy_ch_buf)
        YY_FATAL_ERROR("out of dynamic memory in yy_create_buffer()");
    b->yy_is_our_buffer = 1;
    yy_init_buffer(b, file);
    return b;
    }
void yy_delete_buffer (YY_BUFFER_STATE b)
Definition at line 1920 of file lev_lex.c.
References yy_flex_free().
    {
    if (! b)
        return;
    if (b == yy_current_buffer)
        yy_current_buffer = (YY_BUFFER_STATE) 0;
    if (b->yy_is_our_buffer)
        yy_flex_free((genericptr_t) b->yy_ch_buf);
    yy_flex_free((genericptr_t) b);
    }
static void yy_fatal_error (msg) const [static]
Definition at line 1990 of file lev_lex.c.
References exit(), and YY_EXIT_FAILURE.
    {
    (void) fprintf(stderr, "%s\n", msg);
    exit(YY_EXIT_FAILURE);
    }
static genericptr_t yy_flex_alloc (yy_size_t size) [static]
Definition at line 2030 of file lev_lex.c.
References alloc().
Referenced by yy_create_buffer(), and yy_flex_realloc2().
    {
    return (genericptr_t) alloc((unsigned)size);
    }
static void yy_flex_free (genericptr_t ptr) [static]
Definition at line 2054 of file lev_lex.c.
References free().
Referenced by yy_delete_buffer(), and yy_flex_realloc2().
    {
    free(ptr);
    }
static genericptr_t yy_flex_realloc2 (genericptr_t ptr, yy_size_t size, int old_size) [static]
Definition at line 2038 of file lev_lex.c.
References yy_flex_alloc(), and yy_flex_free().
Referenced by yy_get_next_buffer().
    {
    genericptr_t outptr = yy_flex_alloc(size);
    if (ptr) {
        char *p = (char *) outptr, *q = (char *) ptr;
        while (--old_size >= 0) *p++ = *q++;
        yy_flex_free(ptr);
    }
    return outptr;
    }
void yy_flush_buffer (YY_BUFFER_STATE b)
Definition at line 1963 of file lev_lex.c.
References YY_BUFFER_NEW, YY_END_OF_BUFFER_CHAR, yy_load_buffer_state(), and yy_buffer_state::yy_n_chars.
Referenced by yy_init_buffer().
    {
    b->yy_n_chars = 0;
    /* We always need two end-of-buffer characters. The first causes
     * a transition to the end-of-buffer state. The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
    b->yy_buf_pos = &b->yy_ch_buf[0];
    b->yy_at_bol = 1;
    b->yy_buffer_status = YY_BUFFER_NEW;
    if (b == yy_current_buffer)
        yy_load_buffer_state();
    }
static int yy_get_next_buffer () [static]
Definition at line 1558 of file lev_lex.c.
References EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, yy_buffer_state::yy_buf_size, YY_BUFFER_EOF_PENDING, yy_buffer_state::yy_buffer_status, yy_c_buf_p, yy_buffer_state::yy_ch_buf, yy_current_buffer, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, yy_buffer_state::yy_fill_buffer, yy_flex_realloc2(), YY_INPUT, yy_buffer_state::yy_is_our_buffer, YY_MORE_ADJ, yy_n_chars, YY_READ_BUF_SIZE, yyrestart(), and yytext_ptr.
Referenced by input(), and yylex().
    {
    register char *dest = yy_current_buffer->yy_ch_buf;
    register char *source = yytext_ptr;
    register int number_to_move, i;
    int ret_val;
    if (yy_c_buf_p > &yy_current_buffer->yy_ch_buf[
      yy_n_chars + 1])
        YY_FATAL_ERROR(
        "fatal flex scanner internal error--end of buffer missed");
    if (yy_current_buffer->yy_fill_buffer == 0)
        { /* Don't try to fill the buffer, so this is an EOF. */
        if (yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1)
            {
            /* We matched a singled characater, the EOB, so
             * treat this as a final EOF.
             */
            return EOB_ACT_END_OF_FILE;
            }
        else
            {
            /* We matched some text prior to the EOB, first
             * process it.
             */
            return EOB_ACT_LAST_MATCH;
            }
        }
    /* Try to read more data. */
    /* First move last chars to start of buffer. */
    number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;
    for (i = 0; i < number_to_move; ++i)
        *(dest++) = *(source++);
    if (yy_current_buffer->yy_buffer_status ==
      YY_BUFFER_EOF_PENDING)
        /* don't do the read, it's not guaranteed to return an EOF,
         * just force an EOF
         */
        yy_n_chars = 0;
    else
        {
        int num_to_read =
            yy_current_buffer->yy_buf_size - number_to_move - 1;
        while (num_to_read <= 0)
            { /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
            YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT");
#else
            /* just a shorter name for the current buffer */
            YY_BUFFER_STATE b = yy_current_buffer;
            int yy_c_buf_p_offset =
                (int) (yy_c_buf_p - b->yy_ch_buf);
            if (b->yy_is_our_buffer)
                {
                int old_size = b->yy_buf_size + 2;
                int new_size = b->yy_buf_size * 2;
                if (new_size <= 0)
                    b->yy_buf_size += b->yy_buf_size / 8;
                else
                    b->yy_buf_size *= 2;
                b->yy_ch_buf = (char *)
                    /* Include room in for 2 EOB chars. */
                    yy_flex_realloc2((genericptr_t) b->
      yy_ch_buf,
                             b->yy_buf_size + 2, old_size);
                }
            else
                /* Can't grow it, we don't own it. */
                b->yy_ch_buf = 0;
            if (! b->yy_ch_buf)
                YY_FATAL_ERROR(
                "fatal error - scanner input buffer overflow");
            yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];
            num_to_read = yy_current_buffer->yy_buf_size -
                        number_to_move - 1;
#endif
            }
        if (num_to_read > YY_READ_BUF_SIZE)
            num_to_read = YY_READ_BUF_SIZE;
        /* Read in more data. */
        YY_INPUT((&yy_current_buffer->yy_ch_buf[number_to_move]),
            yy_n_chars, num_to_read);
        }
    if (yy_n_chars == 0)
        {
        if (number_to_move == YY_MORE_ADJ)
            {
            ret_val = EOB_ACT_END_OF_FILE;
            yyrestart(yyin);
            }
        else
            {
            ret_val = EOB_ACT_LAST_MATCH;
            yy_current_buffer->yy_buffer_status =
                YY_BUFFER_EOF_PENDING;
            }
        }
    else
        ret_val = EOB_ACT_CONTINUE_SCAN;
    yy_n_chars += number_to_move;
    yy_current_buffer->yy_ch_buf[yy_n_chars] =
      YY_END_OF_BUFFER_CHAR;
    yy_current_buffer->yy_ch_buf[yy_n_chars + 1] =
      YY_END_OF_BUFFER_CHAR;
    yytext_ptr = &yy_current_buffer->yy_ch_buf[0];
    return ret_val;
    }
static yy_state_type yy_get_previous_state () [static]
Definition at line 1689 of file lev_lex.c.
References YY_AT_BOL, yy_c_buf_p, YY_MORE_ADJ, YY_SC_TO_UI, yy_start, and yytext_ptr.
Referenced by yylex().
    {
    register yy_state_type yy_current_state;
    register char *yy_cp;
    yy_current_state = yy_start;
    yy_current_state += YY_AT_BOL();
    for (yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp <
      yy_c_buf_p; ++yy_cp)
        {
        register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
        if (yy_accept[yy_current_state])
            {
            yy_last_accepting_state = yy_current_state;
            yy_last_accepting_cpos = yy_cp;
            }
        while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
            {
            yy_current_state = (int) yy_def[yy_current_state];
            if (yy_current_state >= 640)
                yy_c = yy_meta[(unsigned int) yy_c];
            }
        yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
        }
    return yy_current_state;
    }
void yy_init_buffer (YY_BUFFER_STATE b, FILE * file)
Definition at line 1942 of file lev_lex.c.
References isatty(), and yy_flush_buffer().
Referenced by yy_create_buffer(), and yyrestart().
    {
    yy_flush_buffer(b);
    b->yy_input_file = file;
    b->yy_fill_buffer = 1;
#ifdef YY_ALWAYS_INTERACTIVE
    b->yy_is_interactive = 1;
#else
#ifdef YY_NEVER_INTERACTIVE
    b->yy_is_interactive = 0;
#else
    b->yy_is_interactive = file ? (isatty(fileno(file)) > 0) : 0;
#endif
#endif
    }
void yy_load_buffer_state ()
Definition at line 1884 of file lev_lex.c.
References yy_buffer_state::yy_buf_pos, yy_c_buf_p, yy_hold_char, yy_buffer_state::yy_input_file, yy_buffer_state::yy_n_chars, yy_n_chars, and yytext_ptr.
Referenced by yy_flush_buffer(), yy_switch_to_buffer(), yylex(), and yyrestart().
    {
    yy_n_chars = yy_current_buffer->yy_n_chars;
    yytext_ptr = yy_c_buf_p = yy_current_buffer->
      yy_buf_pos;
    yyin = yy_current_buffer->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
    }
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer)
Definition at line 1858 of file lev_lex.c.
References yy_buffer_state::yy_buf_pos, yy_c_buf_p, yy_did_buffer_switch_on_eof, yy_hold_char, yy_load_buffer_state(), yy_buffer_state::yy_n_chars, and yy_n_chars.
    {
    if (yy_current_buffer == new_buffer)
        return;
    if (yy_current_buffer)
        {
        /* Flush out information for old buffer. */
        *yy_c_buf_p = yy_hold_char;
        yy_current_buffer->yy_buf_pos = yy_c_buf_p;
        yy_current_buffer->yy_n_chars = yy_n_chars;
        }
    yy_current_buffer = new_buffer;
    yy_load_buffer_state();
    /* We don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
    }
static yy_state_type yy_try_NUL_trans (yy_state_type yy_current_state) [static]
Definition at line 1724 of file lev_lex.c.
References yy_c_buf_p.
Referenced by yylex().
    {
    register int yy_is_jam;
    register char *yy_cp = yy_c_buf_p;
    register YY_CHAR yy_c = 1;
    if (yy_accept[yy_current_state])
        {
        yy_last_accepting_state = yy_current_state;
        yy_last_accepting_cpos = yy_cp;
        }
    while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
        {
        yy_current_state = (int) yy_def[yy_current_state];
        if (yy_current_state >= 640)
            yy_c = yy_meta[(unsigned int) yy_c];
        }
    yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
    yy_is_jam = (yy_current_state == 639);
    return yy_is_jam ? 0 : yy_current_state;
    }
int yylex ()
Definition at line 860 of file lev_lex.c.
References A_REGISTER, ALIGNMENT, alloc(), ALTAR_ID, ALTAR_TYPE, AM_CHAOTIC, AM_LAWFUL, AM_NEUTRAL, AM_NONE, AM_SPLEV_CO, AM_SPLEV_NONCO, ARBOREAL, BEGIN, BOOLEAN, BRANCH_ID, BURN, CENTER, CHANCE_ID, COBJECT_ID, colon_line_number, CONTAINED, CORRIDOR_ID, CURSE_TYPE, D_BROKEN, D_CLOSED, D_ISOPEN, D_LOCKED, D_NODOOR, DIRECTION, DOOR_ID, DOOR_STATE, DRAWBRIDGE_ID, DUST, ECHO, ENGRAVE, ENGRAVING_ID, ENGRAVING_TYPE, EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, FILLING, FLAG_TYPE, FLAGS_ID, FOUNTAIN_ID, GEOMETRY_ID, GOLD_ID, HARDFLOOR, YYSTYPE::i, INITIAL, INTEGER, LADDER_ID, LEFT_OR_RIGHT, LEV, LEV_INIT_ID, LEVEL_ID, LIGHT_STATE, line_number, M_AP_FURNITURE, M_AP_MONSTER, M_AP_OBJECT, M_REGISTER, YYSTYPE::map, map_cnt, MAP_ID, MAPC, MARK, MAZE_ID, MAZEWALK_ID, MESSAGE_ID, MON_ALERTNESS, MON_APPEARANCE, MON_ATTITUDE, MONSTER_ID, NAME_ID, NOMAP_ID, NOMMAP, NON_DIGGABLE_ID, NON_PASSWALL_ID, NONE, NOTELEPORT, O_REGISTER, OBJECT_ID, P_REGISTER, PERCENT, POOL_ID, PORTAL_ID, RAND_CORRIDOR_ID, RANDOM_MONSTERS_ID, RANDOM_OBJECTS_ID, RANDOM_PLACES_ID, RANDOM_TYPE, REGION_ID, ROOM_ID, SHORTSIGHTED, SINK_ID, STAIR_ID, stdin, stdout, Strcpy, STRING, SUBROOM_ID, TELEPRT_ID, TOP_OR_BOT, TRAP_ID, UP_OR_DOWN, W_EAST, W_NORTH, W_SOUTH, W_WEST, WALLIFY_ID, YY_AT_BOL, YY_BREAK, YY_BUF_SIZE, YY_BUFFER_NEW, YY_BUFFER_NORMAL, yy_buffer_state::yy_buffer_status, yy_c_buf_p, yy_buffer_state::yy_ch_buf, yy_create_buffer(), yy_did_buffer_switch_on_eof, YY_DO_BEFORE_ACTION, YY_END_OF_BUFFER, YY_FATAL_ERROR, yy_get_next_buffer(), yy_get_previous_state(), yy_hold_char, yy_init, yy_buffer_state::yy_input_file, yy_last_accepting_cpos, yy_last_accepting_state, yy_load_buffer_state(), YY_MORE_ADJ, yy_buffer_state::yy_n_chars, yy_n_chars, YY_NEW_FILE, YY_RULE_SETUP, YY_SC_TO_UI, YY_START, yy_start, YY_STATE_EOF, yy_try_NUL_trans(), yyin, yyleng, yyout, yyterminate, yytext_ptr, and yywrap().
    {
    register yy_state_type yy_current_state;
    register char *yy_cp, *yy_bp;
    register int yy_act;
    if (yy_init)
        {
        yy_init = 0;
#ifdef YY_USER_INIT
        YY_USER_INIT;
#endif
        if (! yy_start)
            yy_start = 1; /* first start state */
        if (! yyin)
            yyin = stdin;
        if (! yyout)
            yyout = stdout;
        if (! yy_current_buffer)
            yy_current_buffer =
                yy_create_buffer(yyin, YY_BUF_SIZE);
        yy_load_buffer_state();
        }
    while (1) /* loops until end-of-file is reached */
        {
        yy_cp = yy_c_buf_p;
        /* Support of yytext. */
        *yy_cp = yy_hold_char;
        /* yy_bp points to the position in yy_ch_buf of the start of
         * the current run.
         */
        yy_bp = yy_cp;
        yy_current_state = yy_start;
        yy_current_state += YY_AT_BOL();
yy_match:
        do
            {
            register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
            if (yy_accept[yy_current_state])
                {
                yy_last_accepting_state = yy_current_state;
                yy_last_accepting_cpos = yy_cp;
                }
            while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
                {
                yy_current_state = (int) yy_def[yy_current_state];
                if (yy_current_state >= 640)
                    yy_c = yy_meta[(unsigned int) yy_c];
                }
            yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
            ++yy_cp;
            }
        while (yy_base[yy_current_state] != 797);
yy_find_action:
        yy_act = yy_accept[yy_current_state];
        if (yy_act == 0)
            { /* have to back up */
            yy_cp = yy_last_accepting_cpos;
            yy_current_state = yy_last_accepting_state;
            yy_act = yy_accept[yy_current_state];
            }
        YY_DO_BEFORE_ACTION;
do_action: /* This label is used only to access EOF actions. */
        switch (yy_act)
    { /* beginning of action switch */
            case 0: /* must back up */
            /* undo the effects of YY_DO_BEFORE_ACTION */
            *yy_cp = yy_hold_char;
            yy_cp = yy_last_accepting_cpos;
            yy_current_state = yy_last_accepting_state;
            goto yy_find_action;
case 1:
YY_RULE_SETUP
{
          BEGIN(INITIAL);
          yylval.map = (char *) alloc(map_cnt + 1);
          (void) strncpy(yylval.map, map, map_cnt);
          yylval.map[map_cnt] = 0;
          map_cnt = 0;
          return MAP_ID;
        }
    YY_BREAK
case 2:
YY_RULE_SETUP
{
          int len = yyleng;
          /* convert \r\n to \n */
          if (len >= 2 && yytext[len - 2] == '\r') len -= 1;
          line_number++;
          (void) strncpy(map + map_cnt, yytext, len);
          map_cnt += len;
          map[map_cnt - 1] = '\n';
          map[map_cnt] = '\0';
        }
    YY_BREAK
case 3:
YY_RULE_SETUP
{ line_number++; }
    YY_BREAK
case 4:
YY_RULE_SETUP
{ colon_line_number = line_number; return ':'; }
    YY_BREAK
case 5:
YY_RULE_SETUP
return MESSAGE_ID;
    YY_BREAK
case 6:
YY_RULE_SETUP
return MAZE_ID;
    YY_BREAK
case 7:
YY_RULE_SETUP
return NOMAP_ID;
    YY_BREAK
case 8:
YY_RULE_SETUP
return LEVEL_ID;
    YY_BREAK
case 9:
YY_RULE_SETUP
return LEV_INIT_ID;
    YY_BREAK
case 10:
YY_RULE_SETUP
return FLAGS_ID;
    YY_BREAK
case 11:
YY_RULE_SETUP
return GEOMETRY_ID;
    YY_BREAK
case 12:
YY_RULE_SETUP
{ BEGIN(MAPC); line_number++; }
    YY_BREAK
case 13:
YY_RULE_SETUP
return OBJECT_ID;
    YY_BREAK
case 14:
YY_RULE_SETUP
return COBJECT_ID;
    YY_BREAK
case 15:
YY_RULE_SETUP
return MONSTER_ID;
    YY_BREAK
case 16:
YY_RULE_SETUP
return TRAP_ID;
    YY_BREAK
case 17:
YY_RULE_SETUP
return DOOR_ID;
    YY_BREAK
case 18:
YY_RULE_SETUP
return DRAWBRIDGE_ID;
    YY_BREAK
case 19:
YY_RULE_SETUP
return MAZEWALK_ID;
    YY_BREAK
case 20:
YY_RULE_SETUP
return WALLIFY_ID;
    YY_BREAK
case 21:
YY_RULE_SETUP
return REGION_ID;
    YY_BREAK
case 22:
YY_RULE_SETUP
return RANDOM_OBJECTS_ID;
    YY_BREAK
case 23:
YY_RULE_SETUP
return RANDOM_MONSTERS_ID;
    YY_BREAK
case 24:
YY_RULE_SETUP
return RANDOM_PLACES_ID;
    YY_BREAK
case 25:
YY_RULE_SETUP
return ALTAR_ID;
    YY_BREAK
case 26:
YY_RULE_SETUP
return LADDER_ID;
    YY_BREAK
case 27:
YY_RULE_SETUP
return STAIR_ID;
    YY_BREAK
case 28:
YY_RULE_SETUP
return PORTAL_ID;
    YY_BREAK
case 29:
YY_RULE_SETUP
return TELEPRT_ID;
    YY_BREAK
case 30:
YY_RULE_SETUP
return BRANCH_ID;
    YY_BREAK
case 31:
YY_RULE_SETUP
return FOUNTAIN_ID;
    YY_BREAK
case 32:
YY_RULE_SETUP
return SINK_ID;
    YY_BREAK
case 33:
YY_RULE_SETUP
return POOL_ID;
    YY_BREAK
case 34:
YY_RULE_SETUP
return NON_DIGGABLE_ID;
    YY_BREAK
case 35:
YY_RULE_SETUP
return NON_PASSWALL_ID;
    YY_BREAK
case 36:
YY_RULE_SETUP
return ROOM_ID;
    YY_BREAK
case 37:
YY_RULE_SETUP
return SUBROOM_ID;
    YY_BREAK
case 38:
YY_RULE_SETUP
return RAND_CORRIDOR_ID;
    YY_BREAK
case 39:
YY_RULE_SETUP
return CORRIDOR_ID;
    YY_BREAK
case 40:
YY_RULE_SETUP
return GOLD_ID;
    YY_BREAK
case 41:
YY_RULE_SETUP
return ENGRAVING_ID;
    YY_BREAK
case 42:
YY_RULE_SETUP
return NAME_ID;
    YY_BREAK
case 43:
YY_RULE_SETUP
return CHANCE_ID;
    YY_BREAK
case 44:
YY_RULE_SETUP
return LEV;
    YY_BREAK
case 45:
YY_RULE_SETUP
{ yylval.i=D_ISOPEN; return DOOR_STATE; }
    YY_BREAK
case 46:
YY_RULE_SETUP
{ yylval.i=D_CLOSED; return DOOR_STATE; }
    YY_BREAK
case 47:
YY_RULE_SETUP
{ yylval.i=D_LOCKED; return DOOR_STATE; }
    YY_BREAK
case 48:
YY_RULE_SETUP
{ yylval.i=D_NODOOR; return DOOR_STATE; }
    YY_BREAK
case 49:
YY_RULE_SETUP
{ yylval.i=D_BROKEN; return DOOR_STATE; }
    YY_BREAK
case 50:
YY_RULE_SETUP
{ yylval.i=W_NORTH; return DIRECTION; }
    YY_BREAK
case 51:
YY_RULE_SETUP
{ yylval.i=W_EAST; return DIRECTION; }
    YY_BREAK
case 52:
YY_RULE_SETUP
{ yylval.i=W_SOUTH; return DIRECTION; }
    YY_BREAK
case 53:
YY_RULE_SETUP
{ yylval.i=W_WEST; return DIRECTION; }
    YY_BREAK
case 54:
YY_RULE_SETUP
{ yylval.i = -1; return RANDOM_TYPE; }
    YY_BREAK
case 55:
YY_RULE_SETUP
{ yylval.i = -2; return NONE; }
    YY_BREAK
case 56:
YY_RULE_SETUP
return O_REGISTER;
    YY_BREAK
case 57:
YY_RULE_SETUP
return M_REGISTER;
    YY_BREAK
case 58:
YY_RULE_SETUP
return P_REGISTER;
    YY_BREAK
case 59:
YY_RULE_SETUP
return A_REGISTER;
    YY_BREAK
case 60:
YY_RULE_SETUP
{ yylval.i=1; return LEFT_OR_RIGHT; }
    YY_BREAK
case 61:
YY_RULE_SETUP
{ yylval.i=2; return LEFT_OR_RIGHT; }
    YY_BREAK
case 62:
YY_RULE_SETUP
{ yylval.i=3; return CENTER; }
    YY_BREAK
case 63:
YY_RULE_SETUP
{ yylval.i=4; return LEFT_OR_RIGHT; }
    YY_BREAK
case 64:
YY_RULE_SETUP
{ yylval.i=5; return LEFT_OR_RIGHT; }
    YY_BREAK
case 65:
YY_RULE_SETUP
{ yylval.i=1; return TOP_OR_BOT; }
    YY_BREAK
case 66:
YY_RULE_SETUP
{ yylval.i=5; return TOP_OR_BOT; }
    YY_BREAK
case 67:
YY_RULE_SETUP
{ yylval.i=1; return LIGHT_STATE; }
    YY_BREAK
case 68:
YY_RULE_SETUP
{ yylval.i=0; return LIGHT_STATE; }
    YY_BREAK
case 69:
YY_RULE_SETUP
{ yylval.i=0; return FILLING; }
    YY_BREAK
case 70:
YY_RULE_SETUP
{ yylval.i=1; return FILLING; }
    YY_BREAK
case 71:
YY_RULE_SETUP
{ yylval.i= AM_NONE; return ALIGNMENT; }
    YY_BREAK
case 72:
YY_RULE_SETUP
{ yylval.i= AM_LAWFUL; return ALIGNMENT; }
    YY_BREAK
case 73:
YY_RULE_SETUP
{ yylval.i= AM_NEUTRAL; return ALIGNMENT; }
    YY_BREAK
case 74:
YY_RULE_SETUP
{ yylval.i= AM_CHAOTIC; return ALIGNMENT; }
    YY_BREAK
case 75:
YY_RULE_SETUP
{ yylval.i= AM_SPLEV_CO; return ALIGNMENT; }
    YY_BREAK
case 76:
YY_RULE_SETUP
{ yylval.i= AM_SPLEV_NONCO; return ALIGNMENT; }
    YY_BREAK
case 77:
YY_RULE_SETUP
{ yylval.i=1; return MON_ATTITUDE; }
    YY_BREAK
case 78:
YY_RULE_SETUP
{ yylval.i=0; return MON_ATTITUDE; }
    YY_BREAK
case 79:
YY_RULE_SETUP
{ yylval.i=1; return MON_ALERTNESS; }
    YY_BREAK
case 80:
YY_RULE_SETUP
{ yylval.i=0; return MON_ALERTNESS; }
    YY_BREAK
case 81:
YY_RULE_SETUP
{ yylval.i= M_AP_FURNITURE; return MON_APPEARANCE; }
    YY_BREAK
case 82:
YY_RULE_SETUP
{ yylval.i= M_AP_MONSTER; return MON_APPEARANCE; }
    YY_BREAK
case 83:
YY_RULE_SETUP
{ yylval.i= M_AP_OBJECT; return MON_APPEARANCE; }
    YY_BREAK
case 84:
YY_RULE_SETUP
{ yylval.i=2; return ALTAR_TYPE; }
    YY_BREAK
case 85:
YY_RULE_SETUP
{ yylval.i=1; return ALTAR_TYPE; }
    YY_BREAK
case 86:
YY_RULE_SETUP
{ yylval.i=0; return ALTAR_TYPE; }
    YY_BREAK
case 87:
YY_RULE_SETUP
{ yylval.i=1; return UP_OR_DOWN; }
    YY_BREAK
case 88:
YY_RULE_SETUP
{ yylval.i=0; return UP_OR_DOWN; }
    YY_BREAK
case 89:
YY_RULE_SETUP
{ yylval.i=0; return BOOLEAN; }
    YY_BREAK
case 90:
YY_RULE_SETUP
{ yylval.i=1; return BOOLEAN; }
    YY_BREAK
case 91:
YY_RULE_SETUP
{ yylval.i=DUST; return ENGRAVING_TYPE; }
    YY_BREAK
case 92:
YY_RULE_SETUP
{ yylval.i=ENGRAVE; return ENGRAVING_TYPE; }
    YY_BREAK
case 93:
YY_RULE_SETUP
{ yylval.i=BURN; return ENGRAVING_TYPE; }
    YY_BREAK
case 94:
YY_RULE_SETUP
{ yylval.i=MARK; return ENGRAVING_TYPE; }
    YY_BREAK
case 95:
YY_RULE_SETUP
{ yylval.i=1; return CURSE_TYPE; }
    YY_BREAK
case 96:
YY_RULE_SETUP
{ yylval.i=2; return CURSE_TYPE; }
    YY_BREAK
case 97:
YY_RULE_SETUP
{ yylval.i=3; return CURSE_TYPE; }
    YY_BREAK
case 98:
YY_RULE_SETUP
{ return CONTAINED; }
    YY_BREAK
case 99:
YY_RULE_SETUP
{ yylval.i=NOTELEPORT; return FLAG_TYPE; }
    YY_BREAK
case 100:
YY_RULE_SETUP
{ yylval.i=HARDFLOOR; return FLAG_TYPE; }
    YY_BREAK
case 101:
YY_RULE_SETUP
{ yylval.i=NOMMAP; return FLAG_TYPE; }
    YY_BREAK
case 102:
YY_RULE_SETUP
{ yylval.i=ARBOREAL; return FLAG_TYPE; } /* KMH */
    YY_BREAK
case 103:
YY_RULE_SETUP
{ yylval.i=SHORTSIGHTED; return FLAG_TYPE; }
    YY_BREAK
case 104:
YY_RULE_SETUP
{ yylval.i = atoi(yytext + 1); return PERCENT; }
    YY_BREAK
case 105:
YY_RULE_SETUP
{ yylval.i=atoi(yytext); return INTEGER; }
    YY_BREAK
case 106:
YY_RULE_SETUP
{ yytext[yyleng-1] = 0; /* Discard the trailing \" */
          yylval.map = (char *) alloc(strlen(yytext+1)+1);
          Strcpy(yylval.map, yytext+1); /* Discard the first \" */
          return STRING; }
    YY_BREAK
case 107:
YY_RULE_SETUP
{ line_number++; }
    YY_BREAK
case 108:
YY_RULE_SETUP
;
    YY_BREAK
case 109:
YY_RULE_SETUP
{ yylval.i = yytext[2]; return CHAR; }
    YY_BREAK
case 110:
YY_RULE_SETUP
{ yylval.i = yytext[1]; return CHAR; }
    YY_BREAK
case 111:
YY_RULE_SETUP
{ return yytext[0]; }
    YY_BREAK
case 112:
YY_RULE_SETUP
ECHO;
    YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(MAPC):
    yyterminate();
    case YY_END_OF_BUFFER:
        {
        /* Amount of text matched not including the EOB char. */
        int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;
        /* Undo the effects of YY_DO_BEFORE_ACTION. */
        *yy_cp = yy_hold_char;
        if (yy_current_buffer->yy_buffer_status ==
      YY_BUFFER_NEW)
            {
            /* We're scanning a new file or input source. It's
             * possible that this happened because the user
             * just pointed yyin at a new source and called
             * yylex(). If so, then we have to assure
             * consistency between yy_current_buffer and our
             * globals. Here is the right place to do so, because
             * this is the first action (other than possibly a
             * back-up) that will match for the new input source.
             */
            yy_n_chars = yy_current_buffer->
      yy_n_chars;
            yy_current_buffer->yy_input_file =
      yyin;
            yy_current_buffer->yy_buffer_status =
      YY_BUFFER_NORMAL;
            }
        /* Note that here we test for yy_c_buf_p "<=" to the position
         * of the first EOB in the buffer, since yy_c_buf_p will
         * already have been incremented past the NUL character
         * (since all states make transitions on EOB to the
         * end-of-buffer state). Contrast this with the test
         * in input().
         */
        if (yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars])
            { /* This was really a NUL. */
            yy_state_type yy_next_state;
            yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;
            yy_current_state = yy_get_previous_state();
            /* Okay, we're now positioned to make the NUL
             * transition. We couldn't have
             * yy_get_previous_state() go ahead and do it
             * for us because it doesn't know how to deal
             * with the possibility of jamming (and we don't
             * want to build jamming into it because then it
             * will run more slowly).
             */
            yy_next_state = yy_try_NUL_trans(yy_current_state);
            yy_bp = yytext_ptr + YY_MORE_ADJ;
            if (yy_next_state)
                {
                /* Consume the NUL. */
                yy_cp = ++yy_c_buf_p;
                yy_current_state = yy_next_state;
                goto yy_match;
                }
            else
                {
                yy_cp = yy_c_buf_p;
                goto yy_find_action;
                }
            }
        else switch (yy_get_next_buffer())
            {
            case EOB_ACT_END_OF_FILE:
                {
                yy_did_buffer_switch_on_eof = 0;
                if (yywrap())
                    {
                    /* Note: because we've taken care in
                     * yy_get_next_buffer() to have set up
                     * yytext, we can now set up
                     * yy_c_buf_p so that if some total
                     * hoser (like flex itself) wants to
                     * call the scanner after we return the
                     * YY_NULL, it'll still work - another
                     * YY_NULL will get returned.
                     */
                    yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
                    yy_act = YY_STATE_EOF(YY_START);
                    goto do_action;
                    }
                else
                    {
                    if (! yy_did_buffer_switch_on_eof)
                        YY_NEW_FILE;
                    }
                break;
                }
            case EOB_ACT_CONTINUE_SCAN:
                yy_c_buf_p =
                    yytext_ptr + yy_amount_of_matched_text;
                yy_current_state = yy_get_previous_state();
                yy_cp = yy_c_buf_p;
                yy_bp = yytext_ptr + YY_MORE_ADJ;
                goto yy_match;
            case EOB_ACT_LAST_MATCH:
                yy_c_buf_p =
                &yy_current_buffer->yy_ch_buf[
      yy_n_chars];
                yy_current_state = yy_get_previous_state();
                yy_cp = yy_c_buf_p;
                yy_bp = yytext_ptr + YY_MORE_ADJ;
                goto yy_find_action;
            }
        break;
        }
    default:
        YY_FATAL_ERROR(
            "fatal flex scanner internal error--no action found");
    } /* end of action switch */
        } /* end of scanning one token */
    } /* end of yylex */
void yyrestart (FILE * input_file)
Definition at line 1847 of file lev_lex.c.
References YY_BUF_SIZE, yy_create_buffer(), yy_init_buffer(), and yy_load_buffer_state().
Referenced by init_yyin(), and yy_get_next_buffer().
    {
    if (! yy_current_buffer)
        yy_current_buffer = yy_create_buffer(
      yyin, YY_BUF_SIZE);
    yy_init_buffer(yy_current_buffer, input_file);
    yy_load_buffer_state();
    }
static void yyunput (int c, char * yy_bp) [static]
Definition at line 1750 of file lev_lex.c.
References yy_buffer_state::yy_buf_size, yy_c_buf_p, yy_buffer_state::yy_ch_buf, YY_FATAL_ERROR, yy_hold_char, yy_n_chars, and yytext_ptr.
    {
    register char *yy_cp = yy_c_buf_p;
    /* undo effects of setting up yytext */
    *yy_cp = yy_hold_char;
    if (yy_cp < yy_current_buffer->yy_ch_buf + 2)
        { /* need to shift things up to make room */
        /* +2 for EOB chars. */
        register int number_to_move = yy_n_chars + 2;
        register char *dest = &yy_current_buffer->yy_ch_buf[
                    yy_current_buffer->yy_buf_size + 2];
        register char *source =
                &yy_current_buffer->yy_ch_buf[number_to_move];
        while (source > yy_current_buffer->yy_ch_buf)
            *--dest = *--source;
        yy_cp += (int) (dest - source);
        yy_bp += (int) (dest - source);
        yy_n_chars = yy_current_buffer->yy_buf_size;
        if (yy_cp < yy_current_buffer->yy_ch_buf + 2)
            YY_FATAL_ERROR("flex scanner push-back overflow");
        }
    *--yy_cp = (char) c;
    yytext_ptr = yy_bp;
    yy_hold_char = *yy_cp;
    yy_c_buf_p = yy_cp;
    }
Variable Documentation
int colon_line_number = 1
Definition at line 760 of file lev_lex.c.
Referenced by yylex().
int line_number = 1
Definition at line 760 of file lev_lex.c.
Referenced by main(), yyerror(), yylex(), and yywarning().
char map[4096] [static]
Definition at line 761 of file lev_lex.c.
int map_cnt = 0 [static]
Definition at line 762 of file lev_lex.c.
Referenced by yylex().
yyconst short int yy_accept[640] [static]
Definition at line 213 of file lev_lex.c.
yyconst short int yy_base[645] [static]
Definition at line 330 of file lev_lex.c.
char* yy_c_buf_p = (char *) 0 [static]
Definition at line 149 of file lev_lex.c.
Referenced by input(), yy_get_next_buffer(), yy_get_previous_state(), yy_load_buffer_state(), yy_switch_to_buffer(), yy_try_NUL_trans(), yylex(), and yyunput().
yyconst short int yy_chk[862] [static]
Definition at line 579 of file lev_lex.c.
YY_BUFFER_STATE yy_current_buffer = 0 [static]
Definition at line 133 of file lev_lex.c.
Referenced by yy_get_next_buffer().
yyconst short int yy_def[645] [static]
Definition at line 405 of file lev_lex.c.
int yy_did_buffer_switch_on_eof [static]
Definition at line 156 of file lev_lex.c.
Referenced by input(), yy_switch_to_buffer(), and yylex().
yyconst int yy_ec[256] [static]
Definition at line 287 of file lev_lex.c.
char yy_hold_char [static]
Definition at line 142 of file lev_lex.c.
Referenced by input(), yy_load_buffer_state(), yy_switch_to_buffer(), yylex(), and yyunput().
int yy_init = 1 [static]
Definition at line 150 of file lev_lex.c.
Referenced by yylex().
char* yy_last_accepting_cpos [static]
Definition at line 679 of file lev_lex.c.
Referenced by yylex().
yy_state_type yy_last_accepting_state [static]
Definition at line 678 of file lev_lex.c.
Referenced by yylex().
yyconst int yy_meta[65] [static]
Initial value:
=
    { 0,
        1, 2, 3, 2, 2, 1, 2, 1, 1, 2,
        2, 2, 2, 1, 2, 2, 2, 1, 1, 2,
        1, 2, 2, 1, 2, 2, 1, 1, 1, 2,
        1, 2, 2, 1, 1, 2, 1, 1, 1, 2,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1
    }
Definition at line 319 of file lev_lex.c.
int yy_n_chars [static]
Definition at line 144 of file lev_lex.c.
Referenced by input(), yy_get_next_buffer(), yy_load_buffer_state(), yy_switch_to_buffer(), yylex(), and yyunput().
yyconst short int yy_nxt[862] [static]
Definition at line 480 of file lev_lex.c.
int yy_start = 0 [static]
Definition at line 151 of file lev_lex.c.
Referenced by yy_get_previous_state(), and yylex().
FILE* yyin = (FILE *) 0
Definition at line 191 of file lev_lex.c.
Referenced by yylex().
int yyleng
Definition at line 146 of file lev_lex.c.
Referenced by yylex().
YYSTYPE yylval
Definition at line 330 of file dgn_yacc.c.
Referenced by yyparse().
FILE * yyout = (FILE *) 0
Definition at line 191 of file lev_lex.c.
Referenced by init_yyout(), and yylex().
char* yytext
Definition at line 687 of file lev_lex.c.