nethack/sys/mac/maccurs.c File Reference
#include `hack.h`
*
#include `mactty.h`
*
#include `macwin.h`
*
#include <Folders.h>
*
#include <TextUtils.h>
*
#include <Resources.h>
*
Data Structures
struct WinPosSave
Typedefs
typedef struct WinPosSave WinPosSave
Functions
static void InitWinFile (void)
static void FlushWinFile (void)
Boolean RetrievePosition (short kind, short *top, short *left)
Boolean RetrieveSize (short kind, short top, short left, short *height, short *width)
static void SavePosition (short kind, short top, short left)
static void SaveSize (short kind, short height, short width)
static short GetWinKind (WindowPtr win)
Boolean RetrieveWinPos (WindowPtr win, short *top, short *left)
void SaveWindowPos (WindowPtr win)
void SaveWindowSize (WindowPtr win)
Variables
static Boolean winFileInit = 0
static unsigned char winFileName [32] = `\pNetHack Preferences`
static long winFileDir
static short winFileVol
static WinPosSave savePos [kLastWindowKind+1]
Typedef Documentation
typedef struct WinPosSave WinPosSave
Function Documentation
static void FlushWinFile (void) [static]
Definition at line 66 of file maccurs.c.
References savePos, winFileDir, winFileInit, winFileName, and winFileVol.
Referenced by SavePosition(), and SaveSize().
{
    short ref;
    long len;
    if (!winFileInit) {
        if (!winFileName [0]) {
            return;
        }
        HCreate (winFileVol, winFileDir, winFileName, MAC_CREATOR, PREF_TYPE
      );
        HCreateResFile (winFileVol, winFileDir, winFileName);
    }
    if (HOpen (winFileVol, winFileDir, winFileName, fsWrPerm, &ref)) {
        return;
    }
    winFileInit = 1;
    len = sizeof (savePos);
    (void) FSWrite (ref, &len, savePos); /* Don't care about error */
    FSClose (ref);
}
static short GetWinKind (WindowPtr win) [static]
Definition at line 161 of file maccurs.c.
References CheckNhWin(), dprintf(), kMapWindow, kMenuWindow, kMessageWindow, kTextWindow, NHW_BASE, NHW_MAP, NHW_MENU, NHW_MESSAGE, NHW_STATUS, NHW_TEXT, and WIN_BASE_KIND.
Referenced by RetrieveWinPos(), SaveWindowPos(), and SaveWindowSize().
{
    short kind;
    if (!CheckNhWin (win)) {
        return -1;
    }
    kind = GetWindowKind(win) - WIN_BASE_KIND;
    if (kind < 0 || kind > NHW_TEXT) {
        return -1;
    }
    dprintf ("In win kind %d (%lx)", kind, win);
    switch (kind) {
    case NHW_MAP :
    case NHW_STATUS :
    case NHW_BASE :
        kind = kMapWindow;
        break;
    case NHW_MESSAGE :
        kind = kMessageWindow;
        break;
    case NHW_MENU :
        kind = kMenuWindow;
        break;
    default :
        kind = kTextWindow;
        break;
    }
    dprintf ("Out kind %d", kind);
    return kind;
}
static void InitWinFile (void) [static]
Definition at line 34 of file maccurs.c.
References savePos, winFileDir, winFileInit, winFileName, and winFileVol.
Referenced by RetrievePosition(), RetrieveSize(), SavePosition(), and SaveSize().
{
    StringHandle sh;
    long len;
    short ref = 0;
    if (winFileInit) {
        return;
    }
/* We trust the glue. If there's an error, store in game dir. */
    if (FindFolder (kOnSystemDisk, kPreferencesFolderType, kCreateFolder ,
        &winFileVol, &winFileDir)) {
        winFileVol = 0;
        winFileDir = 0;
    }
    sh = GetString (128);
    if (sh && *sh) {
        BlockMove (*sh, winFileName, **sh + 1);
        ReleaseResource ((Handle) sh);
    }
    if (HOpen (winFileVol, winFileDir, winFileName, fsRdPerm, &ref)) {
        return;
    }
    len = sizeof (savePos);
    if (!FSRead (ref, &len, savePos)) {
        winFileInit = 1;
    }
    FSClose (ref);
}
Boolean RetrievePosition (short kind, short * top, short * left)
Definition at line 88 of file maccurs.c.
References dprintf(), InitWinFile(), kLastWindowKind, WinPosSave::left, and WinPosSave::top.
Referenced by _mt_init_stuff(), mac_init_nhwindows(), RetrieveWinPos(), and SanePositions().
                                                       {
Point p;
    if (kind < 0 || kind > kLastWindowKind) {
        dprintf ("Retrieve Bad kind %d", kind);
        return 0;
    }
    InitWinFile ();
    if (!savePos [kind].validPos) {
        dprintf ("Retrieve Not stored kind %d", kind);
        return 0;
    }
    p.v = savePos [kind].top;
    p.h = savePos [kind].left;
    *left = p.h;
    *top = p.v;
    dprintf ("Retrieve Kind %d Pt (%d,%d)", kind, p.h, p.v);
    return (PtInRgn (p, GetGrayRgn ()));
}
Boolean RetrieveSize (short kind, short top, short left, short * height, short * width)
Definition at line 110 of file maccurs.c.
References height, WinPosSave::height, InitWinFile(), kLastWindowKind, width, and WinPosSave::width.
Referenced by mac_init_nhwindows(), and SanePositions().
{
    Point p;
    if (kind < 0 || kind > kLastWindowKind) {
        return 0;
    }
    InitWinFile ();
    if (!savePos [kind].validSize) {
        return 0;
    }
    *width = savePos [kind].width;
    *height = savePos [kind].height;
    p.h = left + *width;
    p.v = top + *height;
    return PtInRgn (p, GetGrayRgn ());
}
Boolean RetrieveWinPos (WindowPtr win, short * top, short * left)
Definition at line 195 of file maccurs.c.
References GetWinKind(), and RetrievePosition().
Referenced by adjust_window_pos().
{
    return RetrievePosition(GetWinKind (win), top, left);
}
static void SavePosition (short kind, short top, short left) [static]
Definition at line 130 of file maccurs.c.
References dprintf(), FlushWinFile(), InitWinFile(), kLastWindowKind, WinPosSave::left, WinPosSave::top, and WinPosSave::validPos.
Referenced by SaveWindowPos().
{
    if (kind < 0 || kind > kLastWindowKind) {
        dprintf ("Save bad kind %d", kind);
        return;
    }
    InitWinFile();
    savePos[kind].validPos = 1;
    savePos[kind].top = top;
    savePos[kind].left = left;
    dprintf("Save kind %d pt (%d,%d)", kind, left, top);
    FlushWinFile();
}
static void SaveSize (short kind, short height, short width) [static]
Definition at line 146 of file maccurs.c.
References dprintf(), FlushWinFile(), height, WinPosSave::height, InitWinFile(), kLastWindowKind, WinPosSave::validSize, width, and WinPosSave::width.
Referenced by SaveWindowSize().
{
    if (kind < 0 || kind > kLastWindowKind) {
        dprintf ("Save bad kind %d", kind);
        return;
    }
    InitWinFile ();
    savePos [kind].validSize = 1;
    savePos [kind].width = width;
    savePos [kind].height = height;
    FlushWinFile ();
}
void SaveWindowPos (WindowPtr win)
Definition at line 202 of file maccurs.c.
References GetWinKind(), and SavePosition().
Referenced by HandleClick().
{
    Rect r;
    GetWindowBounds(win, kWindowContentRgn, &r);
    SavePosition(GetWinKind(win), r.top, r.left);
}
void SaveWindowSize (WindowPtr win)
Definition at line 213 of file maccurs.c.
References GetWinKind(), height, SaveSize(), and width.
Referenced by HandleClick().
{
    short width, height;
    Rect r;
    GetWindowBounds(win, kWindowContentRgn, &r);
    width = r.right - r.left;
    height = r.bottom - r.top;
    SaveSize(GetWinKind (win), height, width);
}
Variable Documentation
WinPosSave savePos[kLastWindowKind+1] [static]
Definition at line 30 of file maccurs.c.
Referenced by FlushWinFile(), and InitWinFile().
long winFileDir [static]
Definition at line 18 of file maccurs.c.
Referenced by FlushWinFile(), and InitWinFile().
Boolean winFileInit = 0 [static]
Definition at line 16 of file maccurs.c.
Referenced by FlushWinFile(), and InitWinFile().
unsigned char winFileName[32] = `\pNetHack Preferences` [static]
Definition at line 17 of file maccurs.c.
Referenced by FlushWinFile(), and InitWinFile().
short winFileVol [static]
Definition at line 19 of file maccurs.c.
Referenced by FlushWinFile(), and InitWinFile().