nethack/sys/mac/macfile.c File Reference
#include `hack.h`
*
#include `macwin.h`
*
#include <files.h>
*
#include <errors.h>
*
#include <resources.h>
*
#include <memory.h>
*
#include <TextUtils.h>
*
#include <ToolUtils.h>
*
#include `dlb.h`
*
Data Structures
struct handlefile
Macros
#define FIRST_HF 32000 /* file ID of first HandleFile */
#define MAX_HF 6		 /* Max # of open HandleFiles */
#define APP_NAME_RES_ID (-16396)
Typedefs
typedef struct handlefile HandleFile
Functions
static HandleFile * FDECL (IsHandleFile,(int))
static int FDECL (OpenHandleFile,(const unsigned char *, long))
static int FDECL (CloseHandleFile,(int))
static int FDECL (ReadHandleFile,(int, void *, unsigned))
static long FDECL (SetHandleFilePos,(int, short, long))
static HandleFile * IsHandleFile (int fd)
static int OpenHandleFile (const unsigned char *name, long fileType)
static int CloseHandleFile (int fd)
static int ReadHandleFile (int fd, void *ptr, unsigned len)
static long SetHandleFilePos (int fd, short whence, long pos)
void C2P (const char *c, unsigned char *p)
void P2C (const unsigned char *p, char *c)
static void replace_resource (Handle new_res, ResType its_type, short its_id, Str255 its_name)
int maccreat (const char *name, long fileType)
int macopen (const char *name, int flags, long fileType)
int macclose (int fd)
int macread (int fd, void *ptr, unsigned len)
int macwrite (int fd, void *ptr, unsigned len)
long macseek (int fd, long where, short whence)
int macunlink (const char *name)
boolean rsrc_dlb_init (void)
void rsrc_dlb_cleanup (void)
boolean rsrc_dlb_fopen (dlb *dp, const char *name, const char *mode)
int rsrc_dlb_fclose (dlb *dp)
int rsrc_dlb_fread (char *buf, int size, int quan, dlb *dp)
int rsrc_dlb_fseek (dlb *dp, long pos, int whence)
char * rsrc_dlb_fgets (char *buf, int len, dlb *dp)
int rsrc_dlb_fgetc (dlb *dp)
long rsrc_dlb_ftell (dlb *dp)
Variables
HandleFile theHandleFiles [MAX_HF]
MacDirs theDirs
Macro Definition Documentation
#define APP_NAME_RES_ID (-16396)
Definition at line 35 of file macfile.c.
Referenced by macopen().
#define FIRST_HF 32000 /* file ID of first HandleFile */
Definition at line 32 of file macfile.c.
Referenced by CloseHandleFile(), IsHandleFile(), OpenHandleFile(), ReadHandleFile(), and SetHandleFilePos().
#define MAX_HF 6		 /* Max # of open HandleFiles */
Definition at line 33 of file macfile.c.
Referenced by IsHandleFile(), and OpenHandleFile().
Typedef Documentation
typedef struct handlefile HandleFile
Function Documentation
void C2P (const char * c, unsigned char * p)
Definition at line 165 of file macfile.c.
Referenced by error(), mac_end_menu(), macopen(), macunlink(), process_openfile(), rsrc_dlb_fopen(), and set_tty_font_name().
{
    int len = strlen (c), i;
    if (len > 255) len = 255;
    for (i = len; i > 0; i--)
        p[i] = c[i-1];
    p[0] = len;
}
static int CloseHandleFile (int fd) [static]
Definition at line 96 of file macfile.c.
References handlefile::data, FIRST_HF, and IsHandleFile().
Referenced by macclose(), and rsrc_dlb_fclose().
{
    if (!IsHandleFile (fd)) {
       return -1;
    }
    fd -= FIRST_HF;
    ReleaseResource (theHandleFiles[fd].data);
    theHandleFiles[fd].data = 0L;
    return(0);
}
static HandleFile* FDECL (IsHandleFile , (int)) [static]
static int FDECL (OpenHandleFile , (const unsigned char *, long)) [static]
static int FDECL (CloseHandleFile , (int)) [static]
static int FDECL (ReadHandleFile , (int, void *, unsigned)) [static]
static long FDECL (SetHandleFilePos , (int, short, long)) [static]
static HandleFile* IsHandleFile (int fd) [static]
Definition at line 56 of file macfile.c.
References handlefile::data, FIRST_HF, MAX_HF, and NULL.
Referenced by CloseHandleFile(), macclose(), macread(), macseek(), macwrite(), ReadHandleFile(), rsrc_dlb_fgetc(), rsrc_dlb_fgets(), rsrc_dlb_ftell(), and SetHandleFilePos().
{
    HandleFile *hfp = NULL;
    if (fd >= FIRST_HF && fd < FIRST_HF+MAX_HF) {
        /* in valid range, check for data */
        hfp = &theHandleFiles[fd-FIRST_HF];
        if (!hfp->data) hfp = NULL;
    }
    return hfp;
}
int macclose (int fd)
Definition at line 279 of file macfile.c.
References CloseHandleFile(), and IsHandleFile().
Referenced by check_recordfile().
{
    if (IsHandleFile (fd)) {
        CloseHandleFile (fd);
    } else {
        if (FSClose (fd)) {
            return -1;
        }
        FlushVol ((StringPtr) 0, theDirs . dataRefNum);
    }
    return 0;
}
int maccreat (const char * name, long fileType)
Definition at line 204 of file macfile.c.
References macopen(), O_CREAT, O_RDWR, and O_TRUNC.
Referenced by create_bonesfile(), create_levelfile(), and create_savefile().
                                          {
    return macopen (name, O_RDWR | O_CREAT | O_TRUNC, fileType);
}
int macopen (const char * name, int flags, long fileType)
Definition at line 210 of file macfile.c.
References APP_NAME_RES_ID, C2P(), macdirs::dataDirID, macdirs::dataRefNum, name, O_CREAT, O_EXCL, O_RDONLY, O_RDWR, O_TRUNC, O_WRONLY, OpenHandleFile(), PLAYER_NAME_RES_ID, plname, and replace_resource().
Referenced by check_recordfile(), maccreat(), open_bonesfile(), open_levelfile(), and open_savefile().
{
    short refNum;
    short perm;
    Str255 s;
    C2P (name, s);
    if (flags & O_CREAT) {
        if (HCreate (theDirs.dataRefNum, theDirs.
      dataDirID, s ,
            TEXT_CREATOR, fileType) && (flags & O_EXCL)) {
            return -1;
        }
        if (fileType == SAVE_TYPE) {
            short resRef;
            HCreateResFile(theDirs.dataRefNum, theDirs.
      dataDirID, s);
            resRef = HOpenResFile(theDirs.dataRefNum, theDirs.
      dataDirID, s,
                                  fsRdWrPerm);
            if (resRef != -1) {
                Handle name;
                Str255 plnamep;
                C2P(plname, plnamep);
                name = (Handle)NewString(plnamep);
                if (name)
                    replace_resource(name, 'STR ',
      PLAYER_NAME_RES_ID,
                                    "\pPlayer Name");
                /* The application name resource. See IM VI, page 9-21. */
                name = (Handle)GetString(APP_NAME_RES_ID);
                if (name) {
                    DetachResource(name);
                    replace_resource(name, 'STR ',
      APP_NAME_RES_ID,
                                     "\pApplication Name");
                }
                CloseResFile(resRef);
            }
        }
    }
    /*
     * Here, we should check for file type, maybe a SFdialog if
     * we fail with default, etc. etc. Besides, we should use HOpen
     * and permissions.
     */
    if ((flags & O_RDONLY) == O_RDONLY) {
        perm = fsRdPerm;
    }
    if ((flags & O_WRONLY) == O_WRONLY) {
        perm = fsWrPerm;
    }
    if ((flags & O_RDWR) == O_RDWR) {
        perm = fsRdWrPerm;
    }
    if (HOpen (theDirs.dataRefNum, theDirs.dataDirID, s, perm, &refNum)) {
        return OpenHandleFile (s, fileType);
    }
    if (flags & O_TRUNC) {
        if (SetEOF (refNum, 0L)) {
            FSClose (refNum);
            return -1;
        }
    }
    return refNum;
}
int macread (int fd, void * ptr, unsigned len)
Definition at line 294 of file macfile.c.
References IsHandleFile(), and ReadHandleFile().
{
    long amt = len;
    
    if (IsHandleFile (fd)) {
        return ReadHandleFile (fd, ptr, amt);
    } else {
        short err = FSRead (fd, &amt, ptr);
        return ((err == noErr) || (err == eofErr && len)) ? amt : -1;
    }
}
long macseek (int fd, long where, short whence)
Definition at line 342 of file macfile.c.
References IsHandleFile(), SEEK_CUR, SEEK_END, and SetHandleFilePos().
{
    short posMode;
    long curPos;
    if (IsHandleFile (fd)) {
        return SetHandleFilePos (fd, whence, where);
    }
    switch (whence) {
        default :
            posMode = fsFromStart;
            break;
        case SEEK_CUR :
            posMode = fsFromMark;
            break;
        case SEEK_END :
            posMode = fsFromLEOF;
            break;
    }
    if (SetFPos(fd, posMode, where) == noErr && GetFPos(fd, &curPos) == noErr)
        return (curPos);
    else
        return(-1);
}
int macunlink (const char * name)
Definition at line 371 of file macfile.c.
References C2P(), macdirs::dataDirID, and macdirs::dataRefNum.
{
    Str255 pname;
    C2P(name, pname);
    return (HDelete(theDirs.dataRefNum, theDirs.
      dataDirID, pname) == noErr ? 0 : -1);
}
int macwrite (int fd, void * ptr, unsigned len)
Definition at line 329 of file macfile.c.
References IsHandleFile().
{
    long amt = len;
    if (IsHandleFile (fd)) return -1;
    if (FSWrite(fd, &amt, ptr) == noErr)
        return (amt);
    else
        return (-1);
}
static int OpenHandleFile (const unsigned char * name, long fileType) [static]
Definition at line 70 of file macfile.c.
References handlefile::data, FIRST_HF, handlefile::mark, MAX_HF, handlefile::size, and type.
Referenced by macopen(), and rsrc_dlb_fopen().
{
    int i;
    Handle h;
    Str255 s;
    for (i = 0; i < MAX_HF; i ++) {
        if (theHandleFiles[i].data == 0L) break;
    }
    
    if (i >= MAX_HF)
        return -1;
    h = GetNamedResource (fileType, name);
    if (!h) return (-1);
    
    theHandleFiles[i].data = h;
    theHandleFiles[i].size = GetHandleSize (h);
    GetResInfo (h, &theHandleFiles[i].id, (void*) &theHandleFiles[i].
      type, s);
    theHandleFiles[i].mark = 0L;
    return(i + FIRST_HF);
}
void P2C (const unsigned char * p, char * c)
Definition at line 177 of file macfile.c.
Referenced by process_openfile().
{
    int idx = *p++;
    for (; idx > 0; idx--)
        *c++ = *p++;
    *c = '\0';
}
static int ReadHandleFile (int fd, void * ptr, unsigned len) [static]
Definition at line 109 of file macfile.c.
References handlefile::data, FIRST_HF, IsHandleFile(), handlefile::mark, and handlefile::size.
Referenced by macread(), and rsrc_dlb_fread().
{
    unsigned maxBytes;
    Handle h;
    if (!IsHandleFile (fd)) return -1;
    
    fd -= FIRST_HF;
    maxBytes = theHandleFiles[fd].size - theHandleFiles[fd].
      mark;
    if (len > maxBytes) len = maxBytes;
    
    h = theHandleFiles[fd].data;
    
    HLock(h);
    BlockMove (*h + theHandleFiles[fd].mark, ptr, len);
    HUnlock(h);
    theHandleFiles[fd].mark += len;
    
    return(len);
}
static void replace_resource (Handle new_res, ResType its_type, short its_id, Str255 its_name) [static]
Definition at line 187 of file macfile.c.
Referenced by macopen().
{
    Handle old_res;
    SetResLoad(false);
    old_res = Get1Resource(its_type, its_id);
    SetResLoad(true);
    if (old_res) {
        RemoveResource(old_res);
        DisposeHandle(old_res);
    }
    AddResource(new_res, its_type, its_id, its_name);
}
void rsrc_dlb_cleanup (void)
Definition at line 388 of file macfile.c.
                            {
}
int rsrc_dlb_fclose (dlb * dp)
Definition at line 402 of file macfile.c.
References CloseHandleFile().
                             {
    return CloseHandleFile(dp->fd);
}
int rsrc_dlb_fgetc (dlb * dp)
Definition at line 448 of file macfile.c.
References handlefile::data, IsHandleFile(), handlefile::mark, and handlefile::size.
                            {
    HandleFile *hfp = IsHandleFile(dp->fd);
    int ret;
    if (!hfp || hfp->size <= hfp->mark) return EOF;
    ret = *(unsigned char *)(*hfp->data + hfp->mark);
    hfp->mark++;
    return ret;
}
char* rsrc_dlb_fgets (char * buf, int len, dlb * dp)
Definition at line 419 of file macfile.c.
References handlefile::data, IsHandleFile(), handlefile::mark, NULL, and handlefile::size.
                                                  {
    HandleFile *hfp = IsHandleFile(dp->fd);
    char *p;
    int bytesLeft, n = 0;
    if (hfp && hfp->mark < hfp->size) {
        bytesLeft = hfp->size - hfp->mark;
        if (bytesLeft < len)
            len = bytesLeft;
        HLock(hfp->data);
        for (n = 0, p = *hfp->data+hfp->mark; n < len; n++, p++) {
            buf[n] = *p;
            if (*p == '\r') buf[n] = '\n';
            if (buf[n] == '\n') {
                n++; /* we want the return in the buffer */
                break;
            }
        }
        HUnlock(hfp->data);
        hfp->mark += n;
        if (n != 0)
            buf[n] = '\0'; /* null terminate result */
    }
    return n ? buf : NULL;
}
boolean rsrc_dlb_fopen (dlb * dp, const char * name, const char * mode)
Definition at line 391 of file macfile.c.
References C2P(), and OpenHandleFile().
                                                                    {
#if defined(__SC__) || defined(__MRC__)
# pragma unused(mode)
#endif
    Str255 pname;
    
    C2P(name, pname);
    dp->fd = OpenHandleFile(pname, 'File'); /* automatically read-only */
    return dp->fd >= 0;
}
int rsrc_dlb_fread (char * buf, int size, int quan, dlb * dp)
Definition at line 406 of file macfile.c.
References ReadHandleFile().
                                                           {
    int nread;
    if (size < 0 || quan < 0) return 0;
    nread = ReadHandleFile(dp->fd, buf, (unsigned)size * (unsigned)quan);
    
    return nread/size; /* # of whole pieces (== quan in normal case) */
}
int rsrc_dlb_fseek (dlb * dp, long pos, int whence)
Definition at line 415 of file macfile.c.
References SetHandleFilePos().
                                                  {
    return SetHandleFilePos(dp->fd, whence, pos);
}
long rsrc_dlb_ftell (dlb * dp)
Definition at line 459 of file macfile.c.
References IsHandleFile(), and handlefile::mark.
                             {
    HandleFile *hfp = IsHandleFile(dp->fd);
    if (!hfp) return 0;
    return hfp->mark;
}
boolean rsrc_dlb_init (void)
Definition at line 384 of file macfile.c.
References TRUE.
                            {
    return TRUE;
}
static long SetHandleFilePos (int fd, short whence, long pos) [static]
Definition at line 132 of file macfile.c.
References FIRST_HF, IsHandleFile(), handlefile::mark, SEEK_CUR, SEEK_END, and handlefile::size.
Referenced by macseek(), and rsrc_dlb_fseek().
{
    long curpos;
    
    if (!IsHandleFile (fd)) return -1;
    
    fd -= FIRST_HF;
    
    curpos = theHandleFiles [fd].mark;
    switch (whence) {
        case SEEK_CUR :
            curpos += pos;
            break;
        case SEEK_END :
            curpos = theHandleFiles[fd].size - pos;
            break;
        default : /* set */
            curpos = pos;
            break;
    }
    if (curpos < 0)
        curpos = 0;
    else if (curpos > theHandleFiles [fd].size)
        curpos = theHandleFiles [fd].size;
    
    theHandleFiles [fd].mark = curpos;
    
    return curpos;
}
Variable Documentation
MacDirs theDirs
Definition at line 52 of file macfile.c.
Referenced by InitMac(), and process_openfile().
HandleFile theHandleFiles[MAX_HF]
Definition at line 51 of file macfile.c.