nethack/include/macpopup.h File Reference
Functions
void FlashButton (DialogRef, short)
char queued_resp (char *resp)
char topl_yn_function (const char *query, const char *resp, char def)
int get_line_from_key_queue (char *bufp)
Function Documentation
void FlashButton (DialogRef , short)
Definition at line 16 of file mmodal.c.
References Delay(), rect, and type.
Referenced by ask_filter().
                                        {
    short type;
    Handle handle;
    Rect rect;
    unsigned long ticks;
    /* Apple recommends 8 ticks */
    GetDialogItem(wind, item, &type, &handle, &rect);
    HiliteControl((ControlHandle)handle, kControlButtonPart);
    Delay(8, &ticks);
    HiliteControl((ControlHandle)handle, 0);
    return;
}
int get_line_from_key_queue (char * bufp)
Definition at line 16 of file mgetline.c.
References try_key_queue().
Referenced by topl_getlin().
                                      {
    * bufp = 0;
    if (try_key_queue (bufp)) {
        while (* bufp) {
            if (* bufp == 10 || * bufp == 13) {
                * bufp = 0;
            }
            bufp ++;
        }
        return true;
    }
    return false;
}
char queued_resp (char * resp)
Definition at line 11 of file mactopl.c.
References buf, try_key_queue(), and yn_number.
Referenced by topl_yn_function().
                        {
    char buf[30];
    if (try_key_queue(buf)) {
        if (!resp || strchr(resp, buf[0]))
            return buf[0];
        if (digit(buf[0]) && strchr(resp, '#')) {
            yn_number = atoi(buf);
            return '#';
        }
    }
    return '\0';
}
char topl_yn_function (const char * query, const char * resp, char def)
Definition at line 26 of file mactopl.c.
References buf, enter_topl_mode(), leave_topl_mode(), nhbell, queued_resp(), topl_set_resp(), and yn_number.
Referenced by mac_yn_function().
                                                                {
    char buf[30];
    char c = queued_resp((char *) resp);
    if (!c) {
        enter_topl_mode((char *) query);
        topl_set_resp((char *) resp, def);
        do {
            c = readchar();
            if (c && resp && !strchr(resp, c)) {
                nhbell();
                c = '\0';
            }
        } while (!c);
        topl_set_resp("", '\0');
        leave_topl_mode(buf);
        if (c == '#')
            yn_number = atoi(buf);
    }
    return c;
}