nethack/sys/mac/macsnd.c File Reference
#include `hack.h`
*
#include `mactty.h`
*
#include `macwin.h`
*
#include <Sound.h>
*
#include <Resources.h>
*
Macros
#define SND_BUFFER(s) (&(*s)[20])
#define SND_LEN(s) (GetHandleSize(s)-42)
Functions
void mac_speaker (struct obj *instr, char *melody)
void tty_nhbell (void)
Macro Definition Documentation
#define SND_BUFFER(s) (&(*s)[20])
Definition at line 27 of file macsnd.c.
Referenced by mac_speaker().
#define SND_LEN(s) (GetHandleSize(s)-42)
Definition at line 28 of file macsnd.c.
Referenced by mac_speaker().
Function Documentation
void mac_speaker (struct obj * instr, char * melody)
Definition at line 32 of file macsnd.c.
References flags, OBJ_NAME, objects, obj::otyp, flag::silent, SND_BUFFER, and SND_LEN.
Referenced by do_improvisation(), and do_play_instrument().
                                              {
    SndChannelPtr theChannel = (SndChannelPtr) 0;
    SndCommand theCmd;
    Handle theSound;
    unsigned char theName [32];
    char *n = (char *) &theName [1];
    int typ = instr->otyp;
    const char *actualn = OBJ_NAME (objects [typ]);
    /*
     * First: are we in the library ?
     */
    if (flags.silent) {
        return;
    }
    /*
     * Is this a known instrument ?
     */
    strcpy (n, actualn);
    theName [0] = strlen (n);
    theSound = GetNamedResource ('snd ', theName);
    if (! theSound) {
        return;
    }
    HLock (theSound);
    /*
     * Set up the synth
     */
    if (SndNewChannel(&theChannel, sampledSynth, initMono +
        initNoInterp, (void *) 0) == noErr) {
        char midi_note [] = {57, 59, 60, 62, 64, 65, 67};
        short err;
        short snd_len = SND_LEN (theSound) / 18;
        theCmd.cmd = soundCmd;
        theCmd.param1 = 0;
        theCmd.param2 = (long) SND_BUFFER (theSound);
        err = SndDoCommand (theChannel, &theCmd, false);
    /*
     * We rack 'em up all in a row
     * The mac will play them correctly and then end, since
     * we do a sync close below.
     *
     */
        while (*melody && ! err) {
            while (*melody > 'G') {
                *melody -= 8;
            }
            while (*melody < 'A') {
                *melody += 8;
            }
            theCmd.cmd = freqDurationCmd;
            theCmd.param1 = snd_len;
            theCmd.param2 = midi_note [*melody - 'A'];
            err = SndDoCommand (theChannel, &theCmd, false);
            melody ++;
        }
        SndDisposeChannel (theChannel, false); /* Sync wait for completion */
        ReleaseResource (theSound);
    }
}
void tty_nhbell (void)
Definition at line 98 of file macsnd.c.
Referenced by do_control().
                       {
    Handle h = GetNamedResource ('snd ', "\pNetHack Bell");
    if (h) {
        HLock (h);
        SndPlay ((SndChannelPtr) 0, (SndListHandle) h, 0);
        ReleaseResource (h);
    } else
        SysBeep (30);
}