nethack/sys/mac/mactty.c File Reference
#include `hack.h`
*
#include `mttypriv.h`
*
#include <Resources.h>
*
Macros
#define MEMORY_MARGIN 30000
#define RECORD_EXISTS(record)
#define DRAW_DIRECT (TA_ALWAYS_REFRESH & record->attribute [TTY_ATTRIB_FLAGS])
#define COOKED_CONTROLS 0X00002581
#define RAW_CONTROLS 1
Functions
void dprintf (char *,...)
static void select_onscreen_window (tty_record *record)
static void select_offscreen_port (tty_record *record)
static short mem_err (void)
static void empty_rect (Rect *r)
static void union_rect (Rect *r1, Rect *r2, Rect *dest)
static short dispose_ptr (void *ptr)
static short allocate_offscreen_world (tty_record *record)
static short deallocate_gworld (tty_record *record)
static short free_bits (tty_record *record)
short create_tty (WindowRef *window, short resource_id, Boolean in_color)
short init_tty_number (WindowPtr window, short font_number, short font_size, short x_size, short y_size)
short destroy_tty (WindowPtr window)
static void do_set_port_font (tty_record *record)
static void calc_font_sizes (tty_record *record)
static short alloc_bits (tty_record *record)
static void save_port (tty_record *record, void *save)
static void use_port (tty_record *record, void *port)
static void copy_bits (tty_record *record, Rect *bounds, short xfer_mode, RgnHandle mask_rgn)
static void erase_rect (tty_record *record, Rect *area)
short force_tty_coordinate_system_recalc (WindowPtr window)
short get_tty_metrics (WindowPtr window, short *x_size, short *y_size, short *x_size_pixels, short *y_size_pixels, short *font_number, short *font_size, short *char_width, short *row_height)
static void pos_rect (tty_record *record, Rect *r, short x_pos, short y_pos, short x_end, short y_end)
static void accumulate_rect (tty_record *record, Rect *rect)
short get_invalid_region (WindowPtr window, Rect *inval_rect)
short set_invalid_region (WindowPtr window, Rect *inval_rect)
static void curs_pos (tty_record *record, short x_pos, short y_pos, short to_state)
short move_tty_cursor (WindowPtr window, short x_pos, short y_pos)
short update_tty (WindowPtr window)
static void do_add_string (tty_record *record, char *str, short len)
static void do_add_cursor (tty_record *record, short x_pos)
static void do_control (tty_record *record, short character)
short add_tty_char (WindowPtr window, short character)
short add_tty_string (WindowPtr window, const char *string)
short get_tty_attrib (WindowPtr window, tty_attrib attrib, long *value)
short set_tty_attrib (WindowPtr window, tty_attrib attrib, long value)
short scroll_tty (WindowPtr window, short delta_x, short delta_y)
short clear_tty (WindowPtr window)
short blink_cursor (WindowPtr window, long when)
short image_tty (EventRecord *theEvent, WindowPtr window)
short clear_tty_window (WindowPtr window, short from_x, short from_y, short to_x, short to_y)
Variables
char game_active = 0
WindowPtr _mt_window
static unsigned long s_control = COOKED_CONTROLS
Macro Definition Documentation
#define COOKED_CONTROLS 0X00002581
Definition at line 53 of file mactty.c.
Referenced by set_tty_attrib().
#define DRAW_DIRECT (TA_ALWAYS_REFRESH & record->attribute [TTY_ATTRIB_FLAGS])
Definition at line 46 of file mactty.c.
Referenced by clear_tty_window(), curs_pos(), and do_add_string().
#define MEMORY_MARGIN 30000
Definition at line 32 of file mactty.c.
Referenced by allocate_offscreen_world().
#define RAW_CONTROLS 1
Definition at line 54 of file mactty.c.
Referenced by set_tty_attrib().
#define RECORD_EXISTS(record)
Value:
tty_record * record; \
    if (!window || !(record = (tty_record *) GetWRefCon (window))) \
        return general_failure;
Definition at line 37 of file mactty.c.
Referenced by add_tty_char(), add_tty_string(), blink_cursor(), clear_tty(), clear_tty_window(), destroy_tty(), force_tty_coordinate_system_recalc(), get_invalid_region(), get_tty_attrib(), get_tty_metrics(), image_tty(), init_tty_number(), move_tty_cursor(), scroll_tty(), set_invalid_region(), set_tty_attrib(), and update_tty().
Function Documentation
static void accumulate_rect (tty_record * record, Rect * rect) [static]
Definition at line 598 of file mactty.c.
References tty_record::invalid_rect, and union_rect().
Referenced by clear_tty(), clear_tty_window(), curs_pos(), do_add_string(), and set_invalid_region().
                                                 {
#if CLIP_RECT_ONLY
    union_rect (rect, &(record->invalid_rect), &(record->
      invalid_rect));
#else
RgnHandle rh = NewRgn ();
    RectRgn (rh, rect);
    UnionRgn (record->invalid_part, rh, record->invalid_part);
    DisposeRgn (rh);
#endif
}
short add_tty_char (WindowPtr window, short character)
Definition at line 832 of file mactty.c.
References tty_record::attribute, curs_pos(), tty_record::curs_state, do_add_cursor(), do_add_string(), do_control(), RECORD_EXISTS, s_control, TA_WRAP_AROUND, TTY_ATTRIB_FLAGS, tty_record::x_curs, tty_record::x_size, and tty_record::y_curs.
Referenced by term_putc().
                                                 {
register char is_control;
char ch;
RECORD_EXISTS (record);
    if (!(record->attribute [TTY_ATTRIB_FLAGS] & TA_WRAP_AROUND) &&
        record->x_curs >= record->x_size)
        return noErr; /* Optimize away drawing across border without wrap */
    if (record->curs_state != 0)
        curs_pos (record, record->x_curs, record->y_curs, 0);
    ch = character;
    is_control = (ch < sizeof(long) * 8) && ((s_control & (1 << ch)) != 0L);
    if (is_control)
        do_control (record, ch);
    else {
        do_add_string (record, (char *)&ch, 1);
        do_add_cursor (record, record->x_curs + 1);
    }
    return noErr;
}
short add_tty_string (WindowPtr window, const char * string)
Definition at line 861 of file mactty.c.
References tty_record::attribute, curs_pos(), tty_record::curs_state, do_add_cursor(), do_add_string(), do_control(), RECORD_EXISTS, s_control, TA_WRAP_AROUND, TTY_ATTRIB_FLAGS, tty_record::x_curs, tty_record::x_size, and tty_record::y_curs.
Referenced by backsp(), and xputs().
{
    register const unsigned char * start_c;
    register const unsigned char * the_c;
    register unsigned char ch, is_control = 0, tty_wrap;
    register short max_x, pos_x;
    RECORD_EXISTS (record);
    if (record->curs_state != 0)
        curs_pos (record, record->x_curs, record->y_curs, 0);
    the_c = (const unsigned char *) string;
    max_x = record->x_size;
    tty_wrap = (record->attribute [TTY_ATTRIB_FLAGS] &
      TA_WRAP_AROUND);
    for (;;) {
        pos_x = record->x_curs;
        if (!tty_wrap && pos_x >= max_x)
            break; /* Optimize away drawing across border without wrap */
        start_c = the_c;
        ch = *the_c;
        while (pos_x < max_x) {
            is_control = (ch < sizeof(long) * 8) && ((s_control & (1 << ch)) != 0L);
            if (is_control)
                break;
            the_c ++; ch = *the_c;
            pos_x ++;
        }
        do_add_string (record, (char *) start_c, the_c - start_c);
        do_add_cursor (record, pos_x);
        if (!ch)
            break;
        if (is_control) {
            do_control (record, ch);
            the_c ++;
        }
    }
    return noErr;
}
static short alloc_bits (tty_record * record) [static]
Definition at line 352 of file mactty.c.
References allocate_offscreen_world(), tty_record::char_width, tty_record::its_bits, tty_record::offscreen_port, tty_record::row_height, tty_record::uses_gworld, tty_record::x_size, and tty_record::y_size.
Referenced by force_tty_coordinate_system_recalc().
                                {
short s_err;
    SetRect (&record->its_bits.bounds, 0, 0,
        record->char_width * record->x_size,
        record->row_height * record->y_size);
/*
 * Clear two highest and lowest bit - not a color pixMap, and even in size
 */
    record->its_bits.rowBytes = ((record->its_bits.bounds.right + 15)
        >> 3) & 0x1ffe;
    if (record->uses_gworld) {
        s_err = allocate_offscreen_world (record);
#if !TARGET_API_MAC_CARBON
    } else {
        s_err = alloc_ptr ((void **) &(record->its_bits.baseAddr),
            record->its_bits.rowBytes * record->its_bits.bounds.bottom);
        if (!s_err) {
            s_err = alloc_ptr ((void **) &(record->offscreen_port),
                sizeof (GrafPort));
        }
        if (!s_err) {
            OpenPort (record->offscreen_port);
            SetPort (record->offscreen_port);
            ClipRect (&(record->its_bits.bounds));
            SetPortBits (&(record->its_bits));
        }
#endif
    }
    return s_err;
}
static short allocate_offscreen_world (tty_record * record) [static]
Definition at line 124 of file mactty.c.
References dprintf(), tty_record::its_bits, MEMORY_MARGIN, tty_record::offscreen_world, select_offscreen_port(), and select_onscreen_window().
Referenced by alloc_bits().
                                              {
GWorldPtr gw = (GWorldPtr)0;
GWorldFlags world_flags = 0;
long mem_here, mem_there, other, required_mem;
Point p = {0, 0};
Rect r_screen;
GDHandle gdh;
short s_err;
    select_onscreen_window (record);
    LocalToGlobal (&p);
    r_screen = record->its_bits.bounds;
    OffsetRect (&r_screen, p.h, p.v);
    gdh = GetMaxDevice (&r_screen);
    required_mem = (long) (*((*gdh)->gdPMap))->pixelSize *
        ((long) record->its_bits.bounds.right *
        record->its_bits.bounds.bottom) >> 3;
    PurgeSpace (&other, &mem_here);
    if (other < mem_here + MEMORY_MARGIN) {
        mem_here = other - MEMORY_MARGIN;
    }
    dprintf ("Heap %ld Required %ld", mem_here, required_mem);
    if (required_mem > mem_here) {
        mem_there = required_mem;
        if (required_mem > TempMaxMem (&mem_there)) {
            dprintf ("No memory");
            return memFullErr;
        }
        world_flags |= useTempMem;
    }
    s_err = NewGWorld (&gw, 0, &r_screen, (CTabHandle) 0, (GDHandle) 0, world_flags);
    if (!s_err) {
        record->offscreen_world = gw;
        select_offscreen_port (record);
        SetOrigin (0, 0);
        select_onscreen_window (record);
        dprintf ("New GWorld @ %lx;dm", gw);
    }
    return s_err;
}
short blink_cursor (WindowPtr window, long when)
Definition at line 1028 of file mactty.c.
References tty_record::attribute, curs_pos(), tty_record::curs_state, tty_record::last_cursor, RECORD_EXISTS, TA_BLINKING_CURSOR, TTY_ATTRIB_CURSOR, update_tty(), tty_record::x_curs, and tty_record::y_curs.
Referenced by tgetch(), and tty_delay_output().
                                                 {
    RECORD_EXISTS (record);
    if ((record->attribute [TTY_ATTRIB_CURSOR] &
      TA_BLINKING_CURSOR)) {
        if (when > record->last_cursor + GetCaretTime ()) {
            curs_pos (record, record->x_curs, record->y_curs, !record->curs_state);
            record->last_cursor = when;
            update_tty (window);
        }
    }
    return 0;
}
static void calc_font_sizes (tty_record * record) [static]
Definition at line 336 of file mactty.c.
References tty_record::ascent_height, tty_record::char_width, do_set_port_font(), and tty_record::row_height.
Referenced by force_tty_coordinate_system_recalc().
                                     {
FontInfo font_info;
    do_set_port_font (record);
    GetFontInfo (&font_info);
    record->char_width = font_info.widMax;
    record->ascent_height = font_info.ascent + font_info.leading;
    record->row_height = record->ascent_height + font_info.descent;
}
short clear_tty (WindowPtr window)
Definition at line 1012 of file mactty.c.
References accumulate_rect(), tty_record::curs_state, erase_rect(), tty_record::its_bits, RECORD_EXISTS, select_offscreen_port(), and update_tty().
Referenced by _mt_init_stuff(), clear_screen(), and force_tty_coordinate_system_recalc().
                                   {
RECORD_EXISTS (record);
    record->curs_state = 0;
    select_offscreen_port (record);
    erase_rect (record, &(record->its_bits.bounds));
    accumulate_rect (record, &(record->its_bits.bounds));
    update_tty (window);
    return noErr;
}
short clear_tty_window (WindowPtr window, short from_x, short from_y, short to_x, short to_y)
Definition at line 1070 of file mactty.c.
References accumulate_rect(), DRAW_DIRECT, erase_rect(), general_failure, pos_rect(), RECORD_EXISTS, select_offscreen_port(), select_onscreen_window(), and update_tty().
Referenced by cl_end(), and cl_eos().
                            {
Rect r;
RECORD_EXISTS (record);
    if (from_x > to_x || from_y > to_y) {
        return general_failure;
    }
    pos_rect (record, &r, from_x, from_y, to_x, to_y);
    select_offscreen_port (record);
    erase_rect (record, &r);
    accumulate_rect (record, &r);
    if (DRAW_DIRECT) {
        update_tty (window);
    } else
        select_onscreen_window (record);
    return noErr;
}
static void copy_bits (tty_record * record, Rect * bounds, short xfer_mode, RgnHandle mask_rgn) [static]
Definition at line 459 of file mactty.c.
References tty_record::its_bits, tty_record::its_window, tty_record::offscreen_world, and tty_record::uses_gworld.
Referenced by do_add_string(), and update_tty().
{
    GWorldFlags pix_state;
    BitMap * source;
    if (record->uses_gworld) {
        pix_state = GetPixelsState (GetGWorldPixMap (record->offscreen_world));
        LockPixels (GetGWorldPixMap (record->offscreen_world));
        source = (BitMapPtr) *GetGWorldPixMap(record->offscreen_world);
    }
    else source = &record->its_bits;
    SetPortWindowPort(record->its_window);
    CopyBits(source, GetPortBitMapForCopyBits(GetWindowPort(record->its_window)),
        bounds, bounds, xfer_mode, mask_rgn);
    if (record->uses_gworld) {
        SetPixelsState (GetGWorldPixMap (record->offscreen_world), pix_state);
    }
}
short create_tty (WindowRef * window, short resource_id, Boolean in_color)
Definition at line 217 of file mactty.c.
References destroy_tty(), empty_rect(), tty_record::its_window, mem_err(), and TRUE.
{
    tty_record * record;
    Boolean was_allocated = !!*window;
    if (in_color) {
        *window = GetNewCWindow (resource_id, (Ptr) *window, (WindowRef) -1L);
    } else {
        *window = GetNewWindow (resource_id, (Ptr) *window, (WindowRef) -1L);
    }
    if (!*window) {
        return mem_err ();
    }
    record = (tty_record *) NewPtrClear (sizeof (tty_record));
    if (!record) {
#if !TARGET_API_MAC_CARBON
        if (was_allocated) {
            CloseWindow (*window);
        } else {
#endif
            DisposeWindow (*window);
#if !TARGET_API_MAC_CARBON
        }
#endif
        return mem_err ();
    }
    record->its_window = *window;
    SetWRefCon (*window, (long) record);
    record->was_allocated = was_allocated;
    record->its_bits.baseAddr = (char *)0;
    record->curs_state = TRUE;
/*
 * We need to keep the window world around if we switch worlds
 */
    record->offscreen_world = (GWorldPtr) 0;
    record->uses_gworld = in_color;
    if (in_color) {
    GDHandle gh;
        SetPortWindowPort(*window);
        GetGWorld(&(record->its_window_world), &gh);
    } else {
        record->its_window_world = (GWorldPtr)0;
    }
#if CLIP_RECT_ONLY
    empty_rect (&(record->invalid_rect));
#else
    record->invalid_part = NewRgn ();
    if (!record->invalid_part) {
        return destroy_tty (*window);
    }
#endif
    return noErr;
}
static void curs_pos (tty_record * record, short x_pos, short y_pos, short to_state) [static]
Definition at line 644 of file mactty.c.
References accumulate_rect(), tty_record::curs_state, DRAW_DIRECT, pos_rect(), save_port(), select_onscreen_window(), and use_port().
Referenced by add_tty_char(), add_tty_string(), blink_cursor(), and move_tty_cursor().
                                                                        {
Rect r;
    if (record->curs_state == to_state) {
        return;
    }
    record->curs_state = to_state;
    pos_rect (record, &r, x_pos, y_pos, x_pos, y_pos);
    if (DRAW_DIRECT) {
    void *old_port;
        save_port (record, &old_port);
        select_onscreen_window (record);
        InvertRect (&r);
        use_port (record, old_port);
    } else {
        accumulate_rect (record, &r);
    }
}
static short deallocate_gworld (tty_record * record) [static]
Definition at line 172 of file mactty.c.
References tty_record::offscreen_world.
Referenced by free_bits().
                                       {
    if (record->offscreen_world) {
        DisposeGWorld (record->offscreen_world);
        record->offscreen_world = (GWorldPtr) 0;
    }
    return noErr;
}
short destroy_tty (WindowPtr window)
Definition at line 296 of file mactty.c.
References dispose_ptr(), free_bits(), and RECORD_EXISTS.
Referenced by create_tty().
                               {
short s_err;
RECORD_EXISTS (record);
    s_err = free_bits (record);
    if (!s_err) {
#if !TARGET_API_MAC_CARBON
        if (record->was_allocated) {
            CloseWindow (window);
        } else {
#endif
            DisposeWindow (window);
#if !TARGET_API_MAC_CARBON
        }
#endif
        s_err = dispose_ptr (record);
    }
    
    return s_err;
}
static short dispose_ptr (void * ptr) [static]
Definition at line 99 of file mactty.c.
Referenced by destroy_tty(), and free_bits().
                        {
    if (!ptr) {
        return noErr; /* Silently accept disposing nulls */
    }
    DisposePtr (ptr);
    return MemError ();
}
static void do_add_cursor (tty_record * record, short x_pos) [static]
Definition at line 759 of file mactty.c.
References tty_record::attribute, tty_record::its_window, scroll_tty(), TA_INHIBIT_VERT_SCROLL, TA_WRAP_AROUND, TTY_ATTRIB_FLAGS, tty_record::x_curs, tty_record::x_size, tty_record::y_curs, and tty_record::y_size.
Referenced by add_tty_char(), and add_tty_string().
                                                {
    record->x_curs = x_pos;
    if (record->x_curs >= record->x_size) {
        if (0L != (record->attribute [TTY_ATTRIB_FLAGS] &
      TA_WRAP_AROUND)) {
            record->y_curs ++;
            record->x_curs = 0;
            if (record->y_curs >= record->y_size) {
                if (0L != (record->attribute [TTY_ATTRIB_FLAGS] &
                    TA_INHIBIT_VERT_SCROLL)) {
                    record->y_curs = record->y_size;
                } else {
                    scroll_tty (record->its_window, 0, 1 + record->
      y_curs -
                        record->y_size);
                }
            }
        } else {
            record->x_curs = record->x_size;
        }
    }
}
static void do_add_string (tty_record * record, char * str, short len) [static]
Definition at line 732 of file mactty.c.
References accumulate_rect(), tty_record::ascent_height, tty_record::char_width, copy_bits(), DRAW_DIRECT, pos_rect(), tty_record::row_height, select_offscreen_port(), select_onscreen_window(), tty_record::x_curs, and tty_record::y_curs.
Referenced by add_tty_char(), and add_tty_string().
                                                         {
Rect r;
    if (len < 1) {
        return;
    }
    select_offscreen_port (record);
    MoveTo (record->x_curs * record->char_width, record->y_curs *
        record->row_height + record->ascent_height);
    DrawText (str, 0, len);
    pos_rect (record, &r, record->x_curs, record->y_curs,
        record->x_curs + len - 1, record->y_curs);
    select_onscreen_window (record);
    if (DRAW_DIRECT) {
        copy_bits (record, &r, srcCopy, (RgnHandle)0);
    } else {
        accumulate_rect (record, &r);
    }
}
static void do_control (tty_record * record, short character) [static]
Definition at line 786 of file mactty.c.
References tty_record::attribute, CHAR_BELL, CHAR_BS, CHAR_CR, CHAR_LF, tty_record::its_window, scroll_tty(), TA_CR_ADD_NL, TA_NL_ADD_CR, TTY_ATTRIB_CURSOR, tty_nhbell(), tty_record::x_curs, tty_record::y_curs, and tty_record::y_size.
Referenced by add_tty_char(), and add_tty_string().
                                                 {
    int recurse = 0;
/*
 * Check recursion because nl_add_cr and cr_add_nl may both be set and invoke each other
 */
    do {
        switch (character) {
        case CHAR_CR :
            record->x_curs = 0;
            if (!recurse && (record->attribute [TTY_ATTRIB_CURSOR] &
      TA_CR_ADD_NL)) {
                recurse = 1;
            }
            else {
                recurse = 0;
                break;
            } /* FALL-THROUGH: if CR-LF, don't bother with loop */
        case CHAR_LF :
            record->y_curs++;
            if (record->y_curs >= record->y_size) {
                scroll_tty (record->its_window, 0, 1 + record->
      y_curs - record->y_size);
            }
            if (!recurse && (record->attribute [TTY_ATTRIB_CURSOR] &
      TA_NL_ADD_CR)) {
                character = CHAR_CR;
                recurse = 1;
            }
            else recurse = 0;
            break;
        case CHAR_BELL :
            tty_nhbell();
            break;
        case CHAR_BS :
            if (record->x_curs > 0)
                record->x_curs --;
        default :
            break;
        }
    } while (recurse);
}
static void do_set_port_font (tty_record * record) [static]
Definition at line 319 of file mactty.c.
References tty_record::attribute, tty_record::font_number, tty_record::font_size, TA_OVERSTRIKE, and TTY_ATTRIB_FLAGS.
Referenced by calc_font_sizes(), and force_tty_coordinate_system_recalc().
                                      {
    PenNormal ();
    TextFont (record->font_number);
    TextSize (record->font_size);
    if (0L != (record->attribute [TTY_ATTRIB_FLAGS] &
      TA_OVERSTRIKE)) {
        TextMode (srcOr);
    } else {
        TextMode (srcCopy);
    }
}
void dprintf (char * , ...)
Definition at line 18 of file dprintf.c.
References flag::debug, DO_DEBUGSTR, DO_PLINE, flags, iflags, NhWindow::its_window, KeyDown(), macFlags, theWindows, WIN_MESSAGE, and instance_flags::window_inited.
Referenced by allocate_offscreen_world(), and force_tty_coordinate_system_recalc().
{
char buffer [500];
va_list list;
int doit;
#define DO_DEBUGSTR 1
#define DO_PLINE 2
    if (flags.debug) {
        doit = 0;
        if (macFlags.hasDebugger && KeyDown (0x39)) { /* Caps Lock */
            doit = DO_DEBUGSTR;
        } else if (KeyDown (0x3B) && iflags.window_inited && /* Control
      */
            (WIN_MESSAGE != -1) && theWindows [WIN_MESSAGE].
      its_window) {
            doit = DO_PLINE;
        }
        
        if (doit) {
            va_start (list, format);
            vsprintf (&buffer [1], format, list);
            va_end (list) ;
            if (doit == DO_DEBUGSTR) {
                buffer [0] = strlen (&buffer [1]);
                DebugStr ((uchar *) buffer);
            } else if (doit == DO_PLINE)
                pline ("%s", &buffer [1]);
        }
    }
}
static void empty_rect (Rect * r) [static]
Definition at line 75 of file mactty.c.
Referenced by create_tty(), and update_tty().
                     {
    r->right = -20000;
    r->left = 20000;
    r->top = 20000;
    r->bottom = -20000;
}
static void erase_rect (tty_record * record, Rect * area) [static]
Definition at line 485 of file mactty.c.
References _mt_window, game_active, iflags, tty_record::its_window, u, and you::uhp.
Referenced by clear_tty(), and clear_tty_window().
                                            {
    if (game_active && u.uhp > 0 && iflags.use_stone && record->
      its_window == _mt_window) {
        PixPatHandle ppat;
        
        ppat = GetPixPat(iflags.use_stone + 127); /* find which pat to get */
        if (ppat) { /* in game window, using backgroung pattern, and have pattern */
            FillCRect (area, ppat);
            DisposePixPat (ppat);
            return;
        }
    }
    EraseRect (area);
}
short force_tty_coordinate_system_recalc (WindowPtr window)
Definition at line 505 of file mactty.c.
References alloc_bits(), calc_font_sizes(), clear_tty(), do_set_port_font(), dprintf(), free_bits(), RECORD_EXISTS, and select_offscreen_port().
Referenced by init_tty_number().
                                                      {
short s_err;
RECORD_EXISTS (record);
    s_err = free_bits (record);
    if (s_err) {
        return s_err;
    }
    calc_font_sizes (record);
    s_err = alloc_bits (record);
    if (s_err) {
/*
 * Catastrophe! We could not allocate memory for the bitmap! Things may go very
 * much downhill from here!
 */
        dprintf ("alloc_bits returned null in force_tty_coordinate_system_recalc!");
        return s_err;
    }
    select_offscreen_port (record);
    do_set_port_font (record);
    return clear_tty (window);
}
static short free_bits (tty_record * record) [static]
Definition at line 187 of file mactty.c.
References deallocate_gworld(), dispose_ptr(), tty_record::its_bits, tty_record::offscreen_port, and tty_record::uses_gworld.
Referenced by destroy_tty(), and force_tty_coordinate_system_recalc().
                               {
    short s_err;
    if (record->uses_gworld) {
        s_err = deallocate_gworld (record);
#if !TARGET_API_MAC_CARBON
    } else {
        s_err = dispose_ptr (record->its_bits.baseAddr);
        if (!s_err) {
            record->its_bits.baseAddr = (char *)0;
            if (record->offscreen_port) {
                ClosePort (record->offscreen_port);
                s_err = dispose_ptr (record->offscreen_port);
                if (!s_err) {
                    record->offscreen_port = (GrafPtr) 0;
                }
            }
        }
#endif
    }
    return s_err;
}
short get_invalid_region (WindowPtr window, Rect * inval_rect)
Definition at line 616 of file mactty.c.
References general_failure, tty_record::invalid_rect, and RECORD_EXISTS.
Referenced by HandleUpdate().
                                                              {
    RECORD_EXISTS (record);
#if CLIP_RECT_ONLY
    if (record->invalid_rect.right <= record->invalid_rect.left ||
        record->invalid_rect.bottom <= record->invalid_rect.top) {
        return general_failure;
    }
    *inval_rect = record->invalid_rect;
#else
    if (EmptyRgn (record->invalid_part)) {
        return general_failure;
    }
    *inval_rect = (*(record->invalid_part))->rgnBBox;
#endif
    return noErr;
}
short get_tty_attrib (WindowPtr window, tty_attrib attrib, long * value)
Definition at line 909 of file mactty.c.
References tty_record::attribute, general_failure, RECORD_EXISTS, and TTY_NUMBER_ATTRIBUTES.
Referenced by _mt_init_stuff(), setftty(), and settty().
                                                                        {
RECORD_EXISTS (record);
    if (attrib < 0 || attrib >= TTY_NUMBER_ATTRIBUTES) {
        return general_failure;
    }
    *value = record->attribute [attrib];
    return noErr;
}
short get_tty_metrics (WindowPtr window, short * x_size, short * y_size, short * x_size_pixels, short * y_size_pixels, short * font_number, short * font_size, short * char_width, short * row_height)
Definition at line 558 of file mactty.c.
References tty_record::char_width, tty_record::font_number, tty_record::font_size, general_failure, tty_record::its_bits, tty_record::offscreen_world, RECORD_EXISTS, tty_record::row_height, tty_record::uses_gworld, tty_record::x_size, and tty_record::y_size.
Referenced by _mt_init_stuff(), and mac_create_nhwindow().
                                                            {
RECORD_EXISTS (record);
/*
 * First, test that we actually have something to draw to...
 */
    if ((((char *)0 == record->its_bits.baseAddr) && !record->uses_gworld) ||
        (((GWorldPtr)0 == record->offscreen_world) && record->uses_gworld)) {
        return general_failure;
    }
    *x_size = record->x_size;
    *y_size = record->y_size;
    *x_size_pixels = record->its_bits.bounds.right;
    *y_size_pixels = record->its_bits.bounds.bottom;
    *font_number = record->font_number;
    *font_size = record->font_size;
    *char_width = record->char_width;
    *row_height = record->row_height;
    return noErr;
}
short image_tty (EventRecord * theEvent, WindowPtr window)
Definition at line 1047 of file mactty.c.
References tty_record::invalid_rect, tty_record::its_bits, RECORD_EXISTS, and update_tty().
                                                    {
#if defined(__SC__) || defined(__MRC__)
# pragma unused(theEvent)
#endif
RECORD_EXISTS (record);
#if CLIP_RECT_ONLY
    record->invalid_rect = record->its_bits.bounds;
#else
RgnHandle rh = NewRgn ();
    RectRgn (rh, record ->its_bits.bounds);
    UnionRgn (record->invalid_part, rh, record->invalid_part);
    DisposeRgn (rh);
#endif
    return update_tty (window);
}
short init_tty_number (WindowPtr window, short font_number, short font_size, short x_size, short y_size)
Definition at line 278 of file mactty.c.
References force_tty_coordinate_system_recalc(), and RECORD_EXISTS.
Referenced by _mt_init_stuff().
                                {
RECORD_EXISTS (record);
    record->font_number = font_number;
    record->font_size = font_size;
    record->x_size = x_size;
    record->y_size = y_size;
    return force_tty_coordinate_system_recalc (window);
}
static short mem_err (void) [static]
Definition at line 62 of file mactty.c.
References general_failure.
Referenced by create_tty().
               {
    short ret_val = MemError();
    if (!ret_val) {
        ret_val = general_failure;
    }
    return ret_val;
}
short move_tty_cursor (WindowPtr window, short x_pos, short y_pos)
Definition at line 671 of file mactty.c.
References curs_pos(), general_failure, RECORD_EXISTS, tty_record::x_curs, tty_record::x_size, tty_record::y_curs, and tty_record::y_size.
Referenced by cmov().
                                                             {
RECORD_EXISTS (record);
    if (record->x_curs == x_pos && record->y_curs == y_pos) {
        return noErr;
    }
    if (record->x_size <= x_pos || x_pos < 0 ||
        record->y_size <= y_pos || y_pos < 0) {
        return general_failure;
    }
    curs_pos (record, record->x_curs, record->y_curs, 0);
    record->x_curs = x_pos;
    record->y_curs = y_pos;
    curs_pos (record, x_pos, y_pos, 1);
    return noErr;
}
static void pos_rect (tty_record * record, Rect * r, short x_pos, short y_pos, short x_end, short y_end) [static]
Definition at line 588 of file mactty.c.
References tty_record::char_width, and tty_record::row_height.
Referenced by clear_tty_window(), curs_pos(), do_add_string(), and update_tty().
                              {
 
    SetRect (r, x_pos * (record->char_width), y_pos * (record->
      row_height),
        (1 + x_end) * (record->char_width) , (1 + y_end) *
        (record->row_height));
}
static void save_port (tty_record * record, void * save) [static]
Definition at line 391 of file mactty.c.
References tty_record::uses_gworld.
Referenced by curs_pos().
                                           {
GWorldPtr gw;
GDHandle gh;
GrafPtr gp;
    if (record->uses_gworld) {
        GetGWorld (&gw, &gh);
        *(GWorldPtr *) save = gw;
    } else {
        GetPort (&gp);
        *(GrafPtr *) save = gp;
    }
}
short scroll_tty (WindowPtr window, short delta_x, short delta_y)
Definition at line 981 of file mactty.c.
References tty_record::char_width, tty_record::its_bits, RECORD_EXISTS, tty_record::row_height, select_offscreen_port(), select_onscreen_window(), update_tty(), tty_record::x_curs, and tty_record::y_curs.
Referenced by do_add_cursor(), and do_control().
                                                                  {
RgnHandle rgn;
short s_err;
RECORD_EXISTS (record);
    s_err = update_tty (window);
    rgn = NewRgn ();
    select_offscreen_port (record);
    ScrollRect (&(record->its_bits.bounds), -delta_x * record->char_width,
        -delta_y * record->row_height, rgn);
    EraseRgn (rgn);
    SetEmptyRgn (rgn);
    select_onscreen_window (record);
    ScrollRect (&(record->its_bits.bounds), -delta_x * record->char_width,
        -delta_y*record->row_height, rgn);
    EraseRgn (rgn);
    DisposeRgn (rgn);
    record->y_curs -= delta_y;
    record->x_curs -= delta_x;
    return noErr;
}
static void select_offscreen_port (tty_record * record) [static]
Definition at line 432 of file mactty.c.
References tty_record::offscreen_port, tty_record::offscreen_world, use_port(), and tty_record::uses_gworld.
Referenced by allocate_offscreen_world(), clear_tty(), clear_tty_window(), do_add_string(), force_tty_coordinate_system_recalc(), scroll_tty(), and set_tty_attrib().
                                           {
    if (record->uses_gworld) {
        use_port (record, record->offscreen_world);
    } else {
        use_port (record, record->offscreen_port);
    }
}
static void select_onscreen_window (tty_record * record) [static]
Definition at line 445 of file mactty.c.
References tty_record::its_window, tty_record::its_window_world, use_port(), and tty_record::uses_gworld.
Referenced by allocate_offscreen_world(), clear_tty_window(), curs_pos(), do_add_string(), scroll_tty(), set_tty_attrib(), and update_tty().
                                            {
    if (record->uses_gworld) {
        use_port (record, record->its_window_world);
        SetPortWindowPort(record->its_window);
    } else {
        use_port(record, record->its_window);
    }
}
short set_invalid_region (WindowPtr window, Rect * inval_rect)
Definition at line 633 of file mactty.c.
References accumulate_rect(), and RECORD_EXISTS.
Referenced by HandleUpdate().
                                                              {
    RECORD_EXISTS (record);
    accumulate_rect (record, inval_rect);
    return noErr;
}
short set_tty_attrib (WindowPtr window, tty_attrib attrib, long value)
Definition at line 921 of file mactty.c.
References tty_record::attribute, COOKED_CONTROLS, general_failure, RAW_CONTROLS, RECORD_EXISTS, s_control, select_offscreen_port(), select_onscreen_window(), TA_ALWAYS_REFRESH, TA_RAW_OUTPUT, TA_TO_RGB, TTY_ATTRIB_BACKGROUND, TTY_ATTRIB_CURSOR, TTY_ATTRIB_FLAGS, TTY_ATTRIB_FOREGROUND, TTY_NUMBER_ATTRIBUTES, and update_tty().
Referenced by _mt_init_stuff(), _mt_set_colors(), setftty(), and settty().
                                                                       {
RGBColor rgb_color;
RECORD_EXISTS (record);
    if (attrib < 0 || attrib >= TTY_NUMBER_ATTRIBUTES) {
        return general_failure;
    }
    record->attribute [attrib] = value;
    /*
     * Presently, no attributes generate a new bitmap.
     */
    switch (attrib) {
    case TTY_ATTRIB_CURSOR :
/*
 * Check if we should change tables
 */
        if (0L != (value & TA_RAW_OUTPUT)) {
            s_control = RAW_CONTROLS;
        } else {
            s_control = COOKED_CONTROLS;
        }
        break;
    case TTY_ATTRIB_FLAGS :
/*
 * Check if we should flush the output going from cached to draw-direct
 */
        if (0L != (value & TA_ALWAYS_REFRESH)) {
            update_tty (window);
        }
        break;
    case TTY_ATTRIB_FOREGROUND :
/*
 * Set foreground color
 */
        TA_TO_RGB (value, rgb_color);
        select_offscreen_port (record);
        RGBForeColor (&rgb_color);
        select_onscreen_window (record);
        break;
    case TTY_ATTRIB_BACKGROUND :
/*
 * Set background color
 */
        TA_TO_RGB (value, rgb_color);
        select_offscreen_port (record);
        RGBBackColor (&rgb_color);
        select_onscreen_window (record);
        break;
    default :
        break;
    }
    return noErr;
}
static void union_rect (Rect * r1, Rect * r2, Rect * dest) [static]
Definition at line 87 of file mactty.c.
References max, and min.
Referenced by accumulate_rect().
                                            {
    dest->left = min (r1->left, r2->left);
    dest->top = min (r1->top, r2 ->top);
    dest->bottom = max (r1->bottom, r2->bottom);
    dest->right = max (r1->right, r2->right);
}
short update_tty (WindowPtr window)
Definition at line 695 of file mactty.c.
References copy_bits(), tty_record::curs_state, empty_rect(), tty_record::invalid_rect, pos_rect(), RECORD_EXISTS, select_onscreen_window(), tty_record::x_curs, and tty_record::y_curs.
Referenced by backsp(), blink_cursor(), clear_tty(), clear_tty_window(), image_tty(), scroll_tty(), set_tty_attrib(), settty(), and term_flush().
                              {
Rect r;
RECORD_EXISTS (record);
#if CLIP_RECT_ONLY
    if (record->invalid_rect.right <= record->invalid_rect.left ||
        record->invalid_rect.bottom <= record->invalid_rect.top) {
        return noErr;
    }
    r = record->invalid_rect;
#else
    if (EmptyRgn (record->invalid_part)) {
        return noErr;
    }
    r = (*(record->invalid_part))->rgnBBox;
#endif
    select_onscreen_window (record);
    copy_bits (record, &r, srcCopy, (RgnHandle) 0);
#if CLIP_RECT_ONLY
    empty_rect (&(record->invalid_rect));
#else
    SetEmptyRgn (record->invalid_part);
#endif
    if (record->curs_state) {
        pos_rect (record, &r, record->x_curs, record->y_curs,
            record->x_curs, record->y_curs);
        InvertRect (&r);
    }
    return noErr;
}
static void use_port (tty_record * record, void * port) [static]
Definition at line 410 of file mactty.c.
References tty_record::offscreen_world, and tty_record::uses_gworld.
Referenced by curs_pos(), select_offscreen_port(), and select_onscreen_window().
                                          {
    if (record->uses_gworld) {
        PixMapHandle pix_map;
        SetGWorld ((GWorldPtr) port, (GDHandle) 0);
        pix_map = GetGWorldPixMap (record->offscreen_world);
        if (pix_map) {
            if (port == record->offscreen_world)
                LockPixels (pix_map);
            else
                UnlockPixels (pix_map);
        }
    } else {
        SetPort ((GrafPtr) port);
    }
}
Variable Documentation
WindowPtr _mt_window
Definition at line 188 of file mttymain.c.
Referenced by erase_rect().
char game_active = 0
Definition at line 19 of file mactty.c.
Referenced by erase_rect(), and main().
unsigned long s_control = COOKED_CONTROLS [static]
Definition at line 55 of file mactty.c.
Referenced by add_tty_char(), add_tty_string(), and set_tty_attrib().