nethack/sys/mac/mactopl.c File Reference
#include `hack.h`
*
#include `mactty.h`
*
#include `macwin.h`
*
#include `macpopup.h`
*
Functions
char queued_resp (char *resp)
char topl_yn_function (const char *query, const char *resp, char def)
char mac_yn_function (char *query, char *resp, char def) const
Function Documentation
char mac_yn_function (char * query, char* resp, char def) const
Definition at line 51 of file mactopl.c.
References topl_yn_function().
{
        return topl_yn_function(query, resp, def);
}
char queued_resp (char * resp)
Definition at line 11 of file mactopl.c.
References buf, try_key_queue(), and yn_number.
Referenced by topl_yn_function().
                        {
    char buf[30];
    if (try_key_queue(buf)) {
        if (!resp || strchr(resp, buf[0]))
            return buf[0];
        if (digit(buf[0]) && strchr(resp, '#')) {
            yn_number = atoi(buf);
            return '#';
        }
    }
    return '\0';
}
char topl_yn_function (const char * query, const char * resp, char def)
Definition at line 26 of file mactopl.c.
References buf, enter_topl_mode(), leave_topl_mode(), nhbell, queued_resp(), topl_set_resp(), and yn_number.
Referenced by mac_yn_function().
                                                                {
    char buf[30];
    char c = queued_resp((char *) resp);
    if (!c) {
        enter_topl_mode((char *) query);
        topl_set_resp((char *) resp, def);
        do {
            c = readchar();
            if (c && resp && !strchr(resp, c)) {
                nhbell();
                c = '\0';
            }
        } while (!c);
        topl_set_resp("", '\0');
        leave_topl_mode(buf);
        if (c == '#')
            yn_number = atoi(buf);
    }
    return c;
}