nethack/include/mactty.h File Reference
#include <windows.h>
*
Macros
#define general_failure 1
#define WIN_BASE_RES 128
#define WIN_BASE_KIND 128
#define CHAR_ENTER ((char)3)
#define CHAR_BELL ((char)7)
#define CHAR_BS ((char)8)
#define CHAR_LF ((char)10)
#define CHAR_CR ((char)13)
#define CHAR_ESC ((char)27)
#define CHAR_BLANK ((char)32)
#define CHAR_DELETE ((char)127)
#define EXTENDED_SUPPORT 0
#define CLIP_RECT_ONLY 1
#define TA_MOVE_EACH_CHAR 1L
#define TA_ALWAYS_REFRESH 2L
#define TA_WRAP_AROUND 4L
#define TA_OVERSTRIKE 8L
#define TA_INHIBIT_VERT_SCROLL 16L
#define TA_RGB_TO_TTY(r)
#define TA_BLINKING_CURSOR 1L
#define TA_ECHO_INPUT 2L
#define TA_RAW_INPUT 4L
#define TA_RAW_OUTPUT 8L
#define TA_NL_ADD_CR 16L
#define TA_CR_ADD_NL 32L
#define TA_NONBLOCKING_IO 64L
#define TA_ATTRIB_FUNC(x) ((long)(x))
#define TTY_EOF -1
Typedefs
typedef enum tty_attrib tty_attrib
Enumerations
enum tty_attrib {
*
TTY_ATTRIB_FLAGS,
TTY_ATTRIB_FOREGROUND,
TTY_ATTRIB_BACKGROUND,
TTY_ATTRIB_CURSOR,
*
TTY_NUMBER_ATTRIBUTES
 }
Functions
short create_tty (WindowPtr *window, short resource_id, Boolean in_color)
short init_tty_number (WindowPtr window, short font_number, short font_size, short x_size, short y_size)
short destroy_tty (WindowPtr window)
short set_tty_font_name (winid window_type, char *name)
short force_tty_coordinate_system_recalc (WindowPtr window)
short get_tty_metrics (WindowPtr window, short *x_size, short *y_size, short *x_size_pixels, short *y_size_pixels, short *font_number, short *font_size, short *char_width, short *row_height)
short move_tty_cursor (WindowPtr window, short x_pos, short y_pos)
short update_tty (WindowPtr window)
short add_tty_char (WindowPtr window, short character)
short add_tty_string (WindowPtr window, const char *string)
short get_tty_attrib (WindowPtr window, tty_attrib attrib, long *value)
short set_tty_attrib (WindowPtr window, tty_attrib attrib, long value)
short scroll_tty (WindowPtr window, short delta_x, short delta_y)
short clear_tty (WindowPtr window)
short blink_cursor (WindowPtr window, long when)
short image_tty (EventRecord *theEvent, WindowPtr window)
short clear_tty_window (WindowPtr window, short from_row, short from_col, short to_row, short to_col)
short get_invalid_region (WindowPtr window, Rect *inval_rect)
short set_invalid_region (WindowPtr window, Rect *inval_rect)
void tty_nhbell ()
Variables
char game_active
Macro Definition Documentation
#define CHAR_BELL ((char)7)
Definition at line 67 of file mactty.h.
Referenced by do_control().
#define CHAR_BLANK ((char)32)
Definition at line 72 of file mactty.h.
Referenced by backsp(), ClosingWindowChar(), filter_scroll_key(), and topl_resp_key().
#define CHAR_BS ((char)8)
Definition at line 68 of file mactty.h.
Referenced by backsp(), do_control(), topl_key(), and topl_resp_key().
#define CHAR_CR ((char)13)
Definition at line 70 of file mactty.h.
Referenced by ClosingWindowChar(), do_control(), filter_scroll_key(), leave_topl_mode(), mac_clear_nhwindow(), mac_display_nhwindow(), mac_putstr(), macClickMenu(), macKeyMenu(), tgetch(), topl_key(), topl_resp_key(), try_key_queue(), and WindowGoAway().
#define CHAR_DELETE ((char)127)
Definition at line 73 of file mactty.h.
#define CHAR_ENTER ((char)3)
Definition at line 66 of file mactty.h.
Referenced by topl_key(), and topl_resp_key().
#define CHAR_ESC ((char)27)
Definition at line 71 of file mactty.h.
Referenced by ClosingWindowChar(), mac_select_menu(), topl_key(), and topl_resp_key().
#define CHAR_LF ((char)10)
Definition at line 69 of file mactty.h.
Referenced by ClosingWindowChar(), do_control(), filter_scroll_key(), mac_putstr(), tgetch(), topl_key(), topl_resp_key(), and try_key_queue().
#define CLIP_RECT_ONLY 1
Definition at line 88 of file mactty.h.
#define EXTENDED_SUPPORT 0
Definition at line 82 of file mactty.h.
#define general_failure 1
Definition at line 55 of file mactty.h.
Referenced by clear_tty_window(), get_invalid_region(), get_tty_attrib(), get_tty_metrics(), mem_err(), move_tty_cursor(), set_tty_attrib(), and set_tty_font_name().
#define TA_ALWAYS_REFRESH 2L
Definition at line 108 of file mactty.h.
Referenced by _mt_init_stuff(), set_tty_attrib(), setftty(), and settty().
#define TA_ATTRIB_FUNC(x) ((long)(x))
Definition at line 176 of file mactty.h.
#define TA_BLINKING_CURSOR 1L
Definition at line 143 of file mactty.h.
Referenced by _mt_init_stuff(), and blink_cursor().
#define TA_CR_ADD_NL 32L
Definition at line 166 of file mactty.h.
Referenced by do_control().
#define TA_ECHO_INPUT 2L
Definition at line 147 of file mactty.h.
#define TA_INHIBIT_VERT_SCROLL 16L
Definition at line 123 of file mactty.h.
Referenced by do_add_cursor(), setftty(), and settty().
#define TA_MOVE_EACH_CHAR 1L
Definition at line 103 of file mactty.h.
#define TA_NL_ADD_CR 16L
Definition at line 162 of file mactty.h.
Referenced by _mt_init_stuff(), and do_control().
#define TA_NONBLOCKING_IO 64L
Definition at line 170 of file mactty.h.
#define TA_OVERSTRIKE 8L
Definition at line 118 of file mactty.h.
Referenced by do_set_port_font().
#define TA_RAW_INPUT 4L
Definition at line 153 of file mactty.h.
#define TA_RAW_OUTPUT 8L
Definition at line 158 of file mactty.h.
Referenced by set_tty_attrib().
#define TA_RGB_TO_TTY(r)
Value:
((((long)((r).red>>8)&0xff)<<16)+\
    (((long)((r).green>>8)&0xff)<<8)+((long)((r).blue>>8)&0xff))
Definition at line 133 of file mactty.h.
#define TA_WRAP_AROUND 4L
Definition at line 113 of file mactty.h.
Referenced by _mt_init_stuff(), add_tty_char(), add_tty_string(), and do_add_cursor().
#define TTY_EOF -1
Definition at line 188 of file mactty.h.
#define WIN_BASE_KIND 128
Definition at line 61 of file mactty.h.
Referenced by _mt_init_stuff(), DoOsEvt(), GetWinKind(), HandleClick(), HandleKey(), HandleUpdate(), mac_clear_nhwindow(), mac_create_nhwindow(), mac_destroy_nhwindow(), MoveScrollBar(), and SanePositions().
#define WIN_BASE_RES 128
Definition at line 60 of file mactty.h.
Referenced by mac_create_nhwindow().
Typedef Documentation
typedef enum tty_attrib tty_attrib
Enumeration Type Documentation
enum tty_attrib
Enumerator
TTY_ATTRIB_FLAGS
TTY_ATTRIB_FOREGROUND
TTY_ATTRIB_BACKGROUND
TTY_ATTRIB_CURSOR
TTY_NUMBER_ATTRIBUTES
Definition at line 90 of file mactty.h.
                        {
/*
 * Flags relating to the general functioning of the window.
 * These flags are passed at create_tty time, and changing them
 * later will clear the screen.
 */
    TTY_ATTRIB_FLAGS ,
/*
 * When using proportional fonts, this will place each character
 * separately, ensuring aligned columns (but looking ugly and taking
 * time)
 */
# define TA_MOVE_EACH_CHAR 1L
/*
 * This means draw each change as it occurs instead of collecting the area
 * and draw it all at once at update_tty() - slower, but more reliable.
 */
# define TA_ALWAYS_REFRESH 2L
/*
 * When reaching the right end, we either just stop drawing, or wrap to the
 * next line.
 */
# define TA_WRAP_AROUND 4L
/*
 * Overstrike means that characters are added on top of each other; i e don't
 * clear the letter beneath. This is faster, using srcOr under QuickDraw
 */
# define TA_OVERSTRIKE 8L
/*
 * We may want the window not to scroll when we reach the end line,
 * but stop drawing instead.
 */
# define TA_INHIBIT_VERT_SCROLL 16L
/*
 * Foreground and background colors. These only affect characters
 * drawn by subsequent calls; not what's already there (but it does
 * affect clears)
 * On b/w screens these do nothing.
 */
    TTY_ATTRIB_FOREGROUND ,
    TTY_ATTRIB_BACKGROUND ,
# define TA_RGB_TO_TTY(r) ((((long)((r).red>>8)&0xff)<<16)+\
    (((long)((r).green>>8)&0xff)<<8)+((long)((r).blue>>8)&0xff))
/*
 * Attributes relating to the cursor, and character set mappings
 */
    TTY_ATTRIB_CURSOR ,
/*
 * Blinking cursor is more noticeable when it's idle
 */
# define TA_BLINKING_CURSOR 1L
/*
 * When handling input, do we echo characters as they are typed?
 */
# define TA_ECHO_INPUT 2L
/*
 * Do we return each character code separately, or map delete etc? Note
 * that non-raw input means getchar won't return anything until the user
 * has typed a return.
 */
# define TA_RAW_INPUT 4L
/*
 * Do we print every character as it is (including BS, NL and CR!) or do
 * do we interpret characters such as NL, BS and CR?
 */
# define TA_RAW_OUTPUT 8L
/*
 * When getting a NL, do we also move to the left?
 */
# define TA_NL_ADD_CR 16L
/*
 * When getting a CR, do we also move down?
 */
# define TA_CR_ADD_NL 32L
/*
 * Wait for input or return what we've got?
 */
# define TA_NONBLOCKING_IO 64L
/*
 * Use this macro to cast a function pointer to a tty attribute; this will help
 * portability to systems where a function pointer doesn't fit in a long
 */
# define TA_ATTRIB_FUNC(x) ((long)(x))
/*
 * This symbolic constant is used to check the number of attributes
 */
    TTY_NUMBER_ATTRIBUTES
} tty_attrib ;
Function Documentation
short add_tty_char (WindowPtr window, short character)
Definition at line 832 of file mactty.c.
References tty_record::attribute, curs_pos(), tty_record::curs_state, do_add_cursor(), do_add_string(), do_control(), RECORD_EXISTS, s_control, TA_WRAP_AROUND, TTY_ATTRIB_FLAGS, tty_record::x_curs, tty_record::x_size, and tty_record::y_curs.
Referenced by term_putc().
                                                 {
register char is_control;
char ch;
RECORD_EXISTS (record);
    if (!(record->attribute [TTY_ATTRIB_FLAGS] & TA_WRAP_AROUND) &&
        record->x_curs >= record->x_size)
        return noErr; /* Optimize away drawing across border without wrap */
    if (record->curs_state != 0)
        curs_pos (record, record->x_curs, record->y_curs, 0);
    ch = character;
    is_control = (ch < sizeof(long) * 8) && ((s_control & (1 << ch)) != 0L);
    if (is_control)
        do_control (record, ch);
    else {
        do_add_string (record, (char *)&ch, 1);
        do_add_cursor (record, record->x_curs + 1);
    }
    return noErr;
}
short add_tty_string (WindowPtr window, const char * string)
Definition at line 861 of file mactty.c.
References tty_record::attribute, curs_pos(), tty_record::curs_state, do_add_cursor(), do_add_string(), do_control(), RECORD_EXISTS, s_control, TA_WRAP_AROUND, TTY_ATTRIB_FLAGS, tty_record::x_curs, tty_record::x_size, and tty_record::y_curs.
Referenced by backsp(), and xputs().
{
    register const unsigned char * start_c;
    register const unsigned char * the_c;
    register unsigned char ch, is_control = 0, tty_wrap;
    register short max_x, pos_x;
    RECORD_EXISTS (record);
    if (record->curs_state != 0)
        curs_pos (record, record->x_curs, record->y_curs, 0);
    the_c = (const unsigned char *) string;
    max_x = record->x_size;
    tty_wrap = (record->attribute [TTY_ATTRIB_FLAGS] &
      TA_WRAP_AROUND);
    for (;;) {
        pos_x = record->x_curs;
        if (!tty_wrap && pos_x >= max_x)
            break; /* Optimize away drawing across border without wrap */
        start_c = the_c;
        ch = *the_c;
        while (pos_x < max_x) {
            is_control = (ch < sizeof(long) * 8) && ((s_control & (1 << ch)) != 0L);
            if (is_control)
                break;
            the_c ++; ch = *the_c;
            pos_x ++;
        }
        do_add_string (record, (char *) start_c, the_c - start_c);
        do_add_cursor (record, pos_x);
        if (!ch)
            break;
        if (is_control) {
            do_control (record, ch);
            the_c ++;
        }
    }
    return noErr;
}
short blink_cursor (WindowPtr window, long when)
Definition at line 1028 of file mactty.c.
References tty_record::attribute, curs_pos(), tty_record::curs_state, tty_record::last_cursor, RECORD_EXISTS, TA_BLINKING_CURSOR, TTY_ATTRIB_CURSOR, update_tty(), tty_record::x_curs, and tty_record::y_curs.
Referenced by tgetch(), and tty_delay_output().
                                                 {
    RECORD_EXISTS (record);
    if ((record->attribute [TTY_ATTRIB_CURSOR] &
      TA_BLINKING_CURSOR)) {
        if (when > record->last_cursor + GetCaretTime ()) {
            curs_pos (record, record->x_curs, record->y_curs, !record->curs_state);
            record->last_cursor = when;
            update_tty (window);
        }
    }
    return 0;
}
short clear_tty (WindowPtr window)
Definition at line 1012 of file mactty.c.
References accumulate_rect(), tty_record::curs_state, erase_rect(), tty_record::its_bits, RECORD_EXISTS, select_offscreen_port(), and update_tty().
Referenced by _mt_init_stuff(), clear_screen(), and force_tty_coordinate_system_recalc().
                                   {
RECORD_EXISTS (record);
    record->curs_state = 0;
    select_offscreen_port (record);
    erase_rect (record, &(record->its_bits.bounds));
    accumulate_rect (record, &(record->its_bits.bounds));
    update_tty (window);
    return noErr;
}
short clear_tty_window (WindowPtr window, short from_row, short from_col, short to_row, short to_col)
Definition at line 1070 of file mactty.c.
References accumulate_rect(), DRAW_DIRECT, erase_rect(), general_failure, pos_rect(), RECORD_EXISTS, select_offscreen_port(), select_onscreen_window(), and update_tty().
Referenced by cl_end(), and cl_eos().
                            {
Rect r;
RECORD_EXISTS (record);
    if (from_x > to_x || from_y > to_y) {
        return general_failure;
    }
    pos_rect (record, &r, from_x, from_y, to_x, to_y);
    select_offscreen_port (record);
    erase_rect (record, &r);
    accumulate_rect (record, &r);
    if (DRAW_DIRECT) {
        update_tty (window);
    } else
        select_onscreen_window (record);
    return noErr;
}
short create_tty (WindowPtr * window, short resource_id, Boolean in_color)
Referenced by _mt_init_stuff().
short destroy_tty (WindowPtr window)
Definition at line 296 of file mactty.c.
References dispose_ptr(), free_bits(), and RECORD_EXISTS.
Referenced by create_tty().
                               {
short s_err;
RECORD_EXISTS (record);
    s_err = free_bits (record);
    if (!s_err) {
#if !TARGET_API_MAC_CARBON
        if (record->was_allocated) {
            CloseWindow (window);
        } else {
#endif
            DisposeWindow (window);
#if !TARGET_API_MAC_CARBON
        }
#endif
        s_err = dispose_ptr (record);
    }
    
    return s_err;
}
short force_tty_coordinate_system_recalc (WindowPtr window)
Definition at line 505 of file mactty.c.
References alloc_bits(), calc_font_sizes(), clear_tty(), do_set_port_font(), dprintf(), free_bits(), RECORD_EXISTS, and select_offscreen_port().
Referenced by init_tty_number().
                                                      {
short s_err;
RECORD_EXISTS (record);
    s_err = free_bits (record);
    if (s_err) {
        return s_err;
    }
    calc_font_sizes (record);
    s_err = alloc_bits (record);
    if (s_err) {
/*
 * Catastrophe! We could not allocate memory for the bitmap! Things may go very
 * much downhill from here!
 */
        dprintf ("alloc_bits returned null in force_tty_coordinate_system_recalc!");
        return s_err;
    }
    select_offscreen_port (record);
    do_set_port_font (record);
    return clear_tty (window);
}
short get_invalid_region (WindowPtr window, Rect * inval_rect)
Definition at line 616 of file mactty.c.
References general_failure, tty_record::invalid_rect, and RECORD_EXISTS.
Referenced by HandleUpdate().
                                                              {
    RECORD_EXISTS (record);
#if CLIP_RECT_ONLY
    if (record->invalid_rect.right <= record->invalid_rect.left ||
        record->invalid_rect.bottom <= record->invalid_rect.top) {
        return general_failure;
    }
    *inval_rect = record->invalid_rect;
#else
    if (EmptyRgn (record->invalid_part)) {
        return general_failure;
    }
    *inval_rect = (*(record->invalid_part))->rgnBBox;
#endif
    return noErr;
}
short get_tty_attrib (WindowPtr window, tty_attrib attrib, long * value)
Definition at line 909 of file mactty.c.
References tty_record::attribute, general_failure, RECORD_EXISTS, and TTY_NUMBER_ATTRIBUTES.
Referenced by _mt_init_stuff(), setftty(), and settty().
                                                                        {
RECORD_EXISTS (record);
    if (attrib < 0 || attrib >= TTY_NUMBER_ATTRIBUTES) {
        return general_failure;
    }
    *value = record->attribute [attrib];
    return noErr;
}
short get_tty_metrics (WindowPtr window, short * x_size, short * y_size, short * x_size_pixels, short * y_size_pixels, short * font_number, short * font_size, short * char_width, short * row_height)
Definition at line 558 of file mactty.c.
References tty_record::char_width, tty_record::font_number, tty_record::font_size, general_failure, tty_record::its_bits, tty_record::offscreen_world, RECORD_EXISTS, tty_record::row_height, tty_record::uses_gworld, tty_record::x_size, and tty_record::y_size.
Referenced by _mt_init_stuff(), and mac_create_nhwindow().
                                                            {
RECORD_EXISTS (record);
/*
 * First, test that we actually have something to draw to...
 */
    if ((((char *)0 == record->its_bits.baseAddr) && !record->uses_gworld) ||
        (((GWorldPtr)0 == record->offscreen_world) && record->uses_gworld)) {
        return general_failure;
    }
    *x_size = record->x_size;
    *y_size = record->y_size;
    *x_size_pixels = record->its_bits.bounds.right;
    *y_size_pixels = record->its_bits.bounds.bottom;
    *font_number = record->font_number;
    *font_size = record->font_size;
    *char_width = record->char_width;
    *row_height = record->row_height;
    return noErr;
}
short image_tty (EventRecord * theEvent, WindowPtr window)
Definition at line 1047 of file mactty.c.
References tty_record::invalid_rect, tty_record::its_bits, RECORD_EXISTS, and update_tty().
                                                    {
#if defined(__SC__) || defined(__MRC__)
# pragma unused(theEvent)
#endif
RECORD_EXISTS (record);
#if CLIP_RECT_ONLY
    record->invalid_rect = record->its_bits.bounds;
#else
RgnHandle rh = NewRgn ();
    RectRgn (rh, record ->its_bits.bounds);
    UnionRgn (record->invalid_part, rh, record->invalid_part);
    DisposeRgn (rh);
#endif
    return update_tty (window);
}
short init_tty_number (WindowPtr window, short font_number, short font_size, short x_size, short y_size)
Definition at line 278 of file mactty.c.
References force_tty_coordinate_system_recalc(), and RECORD_EXISTS.
Referenced by _mt_init_stuff().
                                {
RECORD_EXISTS (record);
    record->font_number = font_number;
    record->font_size = font_size;
    record->x_size = x_size;
    record->y_size = y_size;
    return force_tty_coordinate_system_recalc (window);
}
short move_tty_cursor (WindowPtr window, short x_pos, short y_pos)
Definition at line 671 of file mactty.c.
References curs_pos(), general_failure, RECORD_EXISTS, tty_record::x_curs, tty_record::x_size, tty_record::y_curs, and tty_record::y_size.
Referenced by cmov().
                                                             {
RECORD_EXISTS (record);
    if (record->x_curs == x_pos && record->y_curs == y_pos) {
        return noErr;
    }
    if (record->x_size <= x_pos || x_pos < 0 ||
        record->y_size <= y_pos || y_pos < 0) {
        return general_failure;
    }
    curs_pos (record, record->x_curs, record->y_curs, 0);
    record->x_curs = x_pos;
    record->y_curs = y_pos;
    curs_pos (record, x_pos, y_pos, 1);
    return noErr;
}
short scroll_tty (WindowPtr window, short delta_x, short delta_y)
Definition at line 981 of file mactty.c.
References tty_record::char_width, tty_record::its_bits, RECORD_EXISTS, tty_record::row_height, select_offscreen_port(), select_onscreen_window(), update_tty(), tty_record::x_curs, and tty_record::y_curs.
Referenced by do_add_cursor(), and do_control().
                                                                  {
RgnHandle rgn;
short s_err;
RECORD_EXISTS (record);
    s_err = update_tty (window);
    rgn = NewRgn ();
    select_offscreen_port (record);
    ScrollRect (&(record->its_bits.bounds), -delta_x * record->char_width,
        -delta_y * record->row_height, rgn);
    EraseRgn (rgn);
    SetEmptyRgn (rgn);
    select_onscreen_window (record);
    ScrollRect (&(record->its_bits.bounds), -delta_x * record->char_width,
        -delta_y*record->row_height, rgn);
    EraseRgn (rgn);
    DisposeRgn (rgn);
    record->y_curs -= delta_y;
    record->x_curs -= delta_x;
    return noErr;
}
short set_invalid_region (WindowPtr window, Rect * inval_rect)
Definition at line 633 of file mactty.c.
References accumulate_rect(), and RECORD_EXISTS.
Referenced by HandleUpdate().
                                                              {
    RECORD_EXISTS (record);
    accumulate_rect (record, inval_rect);
    return noErr;
}
short set_tty_attrib (WindowPtr window, tty_attrib attrib, long value)
Definition at line 921 of file mactty.c.
References tty_record::attribute, COOKED_CONTROLS, general_failure, RAW_CONTROLS, RECORD_EXISTS, s_control, select_offscreen_port(), select_onscreen_window(), TA_ALWAYS_REFRESH, TA_RAW_OUTPUT, TA_TO_RGB, TTY_ATTRIB_BACKGROUND, TTY_ATTRIB_CURSOR, TTY_ATTRIB_FLAGS, TTY_ATTRIB_FOREGROUND, TTY_NUMBER_ATTRIBUTES, and update_tty().
Referenced by _mt_init_stuff(), _mt_set_colors(), setftty(), and settty().
                                                                       {
RGBColor rgb_color;
RECORD_EXISTS (record);
    if (attrib < 0 || attrib >= TTY_NUMBER_ATTRIBUTES) {
        return general_failure;
    }
    record->attribute [attrib] = value;
    /*
     * Presently, no attributes generate a new bitmap.
     */
    switch (attrib) {
    case TTY_ATTRIB_CURSOR :
/*
 * Check if we should change tables
 */
        if (0L != (value & TA_RAW_OUTPUT)) {
            s_control = RAW_CONTROLS;
        } else {
            s_control = COOKED_CONTROLS;
        }
        break;
    case TTY_ATTRIB_FLAGS :
/*
 * Check if we should flush the output going from cached to draw-direct
 */
        if (0L != (value & TA_ALWAYS_REFRESH)) {
            update_tty (window);
        }
        break;
    case TTY_ATTRIB_FOREGROUND :
/*
 * Set foreground color
 */
        TA_TO_RGB (value, rgb_color);
        select_offscreen_port (record);
        RGBForeColor (&rgb_color);
        select_onscreen_window (record);
        break;
    case TTY_ATTRIB_BACKGROUND :
/*
 * Set background color
 */
        TA_TO_RGB (value, rgb_color);
        select_offscreen_port (record);
        RGBBackColor (&rgb_color);
        select_onscreen_window (record);
        break;
    default :
        break;
    }
    return noErr;
}
short set_tty_font_name (winid window_type, char * name)
Definition at line 400 of file macwin.c.
References C2P(), general_failure, and NHW_TEXT.
                                                     {
    short fnum;
    Str255 new_font;
    
    if (window_type < NHW_BASE || window_type > NHW_TEXT)
        return general_failure;
        
    C2P (font_name, new_font);
    GetFNum (new_font, &(fnum));
    if (!fnum)
        return general_failure;
    win_fonts [window_type] = fnum;
    return noErr;
}
void tty_nhbell ()
Definition at line 98 of file macsnd.c.
Referenced by do_control().
                       {
    Handle h = GetNamedResource ('snd ', "\pNetHack Bell");
    if (h) {
        HLock (h);
        SndPlay ((SndChannelPtr) 0, (SndListHandle) h, 0);
        ReleaseResource (h);
    } else
        SysBeep (30);
}
short update_tty (WindowPtr window)
Definition at line 695 of file mactty.c.
References copy_bits(), tty_record::curs_state, empty_rect(), tty_record::invalid_rect, pos_rect(), RECORD_EXISTS, select_onscreen_window(), tty_record::x_curs, and tty_record::y_curs.
Referenced by backsp(), blink_cursor(), clear_tty(), clear_tty_window(), image_tty(), scroll_tty(), set_tty_attrib(), settty(), and term_flush().
                              {
Rect r;
RECORD_EXISTS (record);
#if CLIP_RECT_ONLY
    if (record->invalid_rect.right <= record->invalid_rect.left ||
        record->invalid_rect.bottom <= record->invalid_rect.top) {
        return noErr;
    }
    r = record->invalid_rect;
#else
    if (EmptyRgn (record->invalid_part)) {
        return noErr;
    }
    r = (*(record->invalid_part))->rgnBBox;
#endif
    select_onscreen_window (record);
    copy_bits (record, &r, srcCopy, (RgnHandle) 0);
#if CLIP_RECT_ONLY
    empty_rect (&(record->invalid_rect));
#else
    SetEmptyRgn (record->invalid_part);
#endif
    if (record->curs_state) {
        pos_rect (record, &r, record->x_curs, record->y_curs,
            record->x_curs, record->y_curs);
        InvertRect (&r);
    }
    return noErr;
}
Variable Documentation
char game_active
Definition at line 19 of file mactty.c.
Referenced by erase_rect(), and main().