nethack/sys/mac/macunix.c File Reference
#include `hack.h`
*
Functions
void regularize (char *s)
void getlock (void)
Function Documentation
void getlock (void)
Definition at line 21 of file macunix.c.
References close(), lock, O_CREAT, O_EXCL, O_RDWR, open(), panic(), set_levelfile_name(), and write().
{
    int fd;
    int pid = getpid(); /* Process ID */
    
    set_levelfile_name (lock, 0);
    if ((fd = open (lock, O_RDWR | O_EXCL | O_CREAT, LEVL_TYPE)) == -1) {
        raw_printf ("Could not lock the game %s.", lock);
        panic ("Another game in progress?");
    }
    if (write (fd, (char *)&pid, sizeof (pid)) != sizeof (pid)) {
        raw_printf ("Could not lock the game %s.", lock);
        panic("Disk locked?");
    }
    close (fd);
}
void regularize (char * s)
Definition at line 10 of file macunix.c.
{
    register char *lp;
    for (lp = s; *lp; lp++) {
        if (*lp == '.' || *lp == ':')
            *lp = '_';
    }
}