nethack/include/macwin.h File Reference
#include <windows.h>
*
#include <dialogs.h>
*
Data Structures
struct macdirs
struct macflags
struct MacMHMenuItem
struct NhWindow
Macros
#define PLAYER_NAME_RES_ID 1001
#define NUM_MACWINDOWS 15
#define TEXT_BLOCK 512L
#define kMapWindow 0
#define kStatusWindow 1
#define kMessageWindow 2
#define kTextWindow 3
#define kMenuWindow 4
#define kLastWindowKind kMenuWindow
#define MIN_RIGHT 350
#define NUM_STAT_ROWS 2
#define NUM_ROWS 22
#define NUM_COLS 80 /* We shouldn't use column 0 */
#define QUEUE_LEN 24
#define NHW_BASE 0
#define E extern
#define DimMenuBar() AdjustMenus(1)
#define UndimMenuBar() AdjustMenus(0)
Typedefs
typedef struct macdirs MacDirs
typedef struct macflags MacFlags
typedef struct NhWindow NhWindow
Functions
Boolean CheckNhWin (WindowPtr mac_win)
void dprintf (char *,...)
Boolean RetrievePosition (short, short *, short *)
Boolean RetrieveSize (short, short, short, short *, short *)
void SaveWindowPos (WindowPtr)
void SaveWindowSize (WindowPtr)
Boolean FDECL (RetrieveWinPos,(WindowPtr, short *, short *))
void showerror (char *, const char *)
Boolean itworked (short)
void mustwork (short)
void attemptingto (char *)
void FDECL (C2P,(const char *c, unsigned char *p))
void FDECL (P2C,(const unsigned char *p, char *c))
void DoMenuEvt (long)
void InitMenuRes (void)
void AdjustMenus (short)
void FDECL (process_openfile,(short s_vol, long s_dir, Str255 fNm, OSType ft))
void AddToKeyQueue (unsigned char, Boolean)
unsigned char GetFromKeyQueue (void)
void trans_num_keys (EventRecord *)
void NDECL (InitMac)
int FDECL (try_key_queue,(char *))
void FDECL (enter_topl_mode,(char *))
void FDECL (leave_topl_mode,(char *))
void FDECL (topl_set_resp,(char *, char))
Boolean FDECL (topl_key,(unsigned char, Boolean))
E void FDECL (HandleEvent,(EventRecord *))
void NDECL (port_help)
E void FDECL (mac_init_nhwindows,(int *, char **))
E void NDECL (mac_askname)
E void NDECL (mac_get_nh_event)
E void FDECL (mac_exit_nhwindows,(const char *))
E winid FDECL (mac_create_nhwindow,(int))
E void FDECL (mac_clear_nhwindow,(winid))
E void FDECL (mac_display_nhwindow,(winid, BOOLEAN_P))
E void FDECL (mac_destroy_nhwindow,(winid))
E void FDECL (mac_curs,(winid, int, int))
E void FDECL (mac_putstr,(winid, int, const char *))
E void FDECL (mac_start_menu,(winid))
E void FDECL (mac_add_menu,(winid, int, const anything *, CHAR_P, CHAR_P, int, const char *, BOOLEAN_P))
E void FDECL (mac_end_menu,(winid, const char *))
E int FDECL (mac_select_menu,(winid, int, menu_item **))
E int NDECL (mac_nhgetch)
E int FDECL (mac_nh_poskey,(int *, int *, int *))
E int NDECL (mac_doprev_message)
E char FDECL (mac_yn_function,(const char *, const char *, CHAR_P))
E void FDECL (mac_getlin,(const char *, char *))
E int NDECL (mac_get_ext_cmd)
E void FDECL (mac_number_pad,(int))
E void NDECL (mac_delay_output)
Variables
MacDirs theDirs
MacFlags macFlags
NhWindow * theWindows
struct window_procs mac_procs
winid BASE_WINDOW
winid WIN_MAP
winid WIN_MESSAGE
winid WIN_INVEN
winid WIN_STATUS
Boolean small_screen
Macro Definition Documentation
#define DimMenuBar() AdjustMenus(1)
Definition at line 194 of file macwin.h.
Referenced by enter_topl_mode(), mac_display_nhwindow(), and mac_init_nhwindows().
#define E extern
Definition at line 158 of file macwin.h.
#define kLastWindowKind kMenuWindow
Definition at line 89 of file macwin.h.
Referenced by RetrievePosition(), RetrieveSize(), SavePosition(), and SaveSize().
#define kMapWindow 0
Definition at line 84 of file macwin.h.
Referenced by _mt_init_stuff(), GetWinKind(), and SanePositions().
#define kMenuWindow 4
Definition at line 88 of file macwin.h.
Referenced by GetWinKind(), and SanePositions().
#define kMessageWindow 2
Definition at line 86 of file macwin.h.
Referenced by GetWinKind(), mac_init_nhwindows(), and SanePositions().
#define kStatusWindow 1
Definition at line 85 of file macwin.h.
#define kTextWindow 3
Definition at line 87 of file macwin.h.
Referenced by GetWinKind(), and SanePositions().
#define MIN_RIGHT 350
Definition at line 97 of file macwin.h.
Referenced by GeneralUpdate(), and macUpdateMessage().
#define NHW_BASE 0
Definition at line 150 of file macwin.h.
Referenced by amii_create_nhwindow(), amii_curs(), amii_init_nhwindows(), amii_putstr(), amii_set_text_font(), amii_setdrawpens(), amii_setfillpens(), dismiss_nhwindow(), GetWinKind(), and kill_nhwindows().
#define NUM_COLS 80 /* We shouldn't use column 0 */
Definition at line 143 of file macwin.h.
#define NUM_MACWINDOWS 15
Definition at line 80 of file macwin.h.
Referenced by GetNhWin(), mac_clear_nhwindow(), mac_create_nhwindow(), mac_destroy_nhwindow(), mac_display_nhwindow(), mac_init_nhwindows(), mac_putstr(), and SanePositions().
#define NUM_ROWS 22
Definition at line 142 of file macwin.h.
#define NUM_STAT_ROWS 2
Definition at line 141 of file macwin.h.
#define PLAYER_NAME_RES_ID 1001
Definition at line 22 of file macwin.h.
Referenced by macopen(), and process_openfile().
#define QUEUE_LEN 24
Definition at line 144 of file macwin.h.
Referenced by AddToKeyQueue(), DoMenuEvt(), and GetFromKeyQueue().
#define TEXT_BLOCK 512L
Definition at line 81 of file macwin.h.
Referenced by mac_clear_nhwindow(), and mac_create_nhwindow().
#define UndimMenuBar() AdjustMenus(0)
Definition at line 195 of file macwin.h.
Referenced by HandleKey(), leave_topl_mode(), mac_display_nhwindow(), and main().
Typedef Documentation
typedef struct macdirs MacDirs
typedef struct macflags MacFlags
typedef struct NhWindow NhWindow
Function Documentation
void AddToKeyQueue (unsigned char, Boolean)
Definition at line 82 of file macwin.c.
References keyQueue, keyQueueCount, keyQueueRead, keyQueueWrite, and QUEUE_LEN.
Referenced by AppleEventHandler(), askQuit(), askSave(), DoMenuEvt(), GeneralKey(), macClickMenu(), macClickMessage(), macKeyMenu(), and WindowGoAway().
                                                {
    if (keyQueueCount < QUEUE_LEN) {
        keyQueue [keyQueueWrite++] = ch;
        keyQueueCount++;
    }
    else if (force) {
        keyQueue [keyQueueWrite++] = ch;
        keyQueueRead++;
        if (keyQueueRead >= QUEUE_LEN)
            keyQueueRead = 0;
        keyQueueCount = QUEUE_LEN;
    }
    if (keyQueueWrite >= QUEUE_LEN)
        keyQueueWrite = 0;
}
void AdjustMenus (short)
Definition at line 913 of file macmenu.c.
References _mt_window, discover, kAdjustWizardMenu, mbarDA, mbarDim, MBARHND, mbarNoMap, mbarNoWindows, mbarRegular, mbarSpecial, menuEdit, menuFile, menuFileEnterExplore, menuFilePlayMode, menuFileRedraw, menuWizardAttributes, MHND_EDIT, MHND_FILE, MHND_WIZ, NUM_MBAR, theMenubar, and wizard.
{
    short newMenubar = mbarRegular;
    WindowRef win = FrontWindow();
    short i;
    /*
     * if (windowprocs != mac_procs) {
     * return;
     * }
     */
    /* determine the new menubar state */
    if (dimMenubar)
        newMenubar = mbarDim;
    else if (!win)
        newMenubar = mbarNoWindows;
    else if (GetWindowKind(win) < 0)
        newMenubar = mbarDA;
    else if (!IsWindowVisible(_mt_window))
        newMenubar = mbarNoMap;
    if (newMenubar != mbarRegular)
        ; /* we've already found its state */
#ifdef WIZARD
    else if (wizard)
    {
        newMenubar = mbarSpecial;
        if (kAdjustWizardMenu)
        {
            kAdjustWizardMenu = 0;
            SetMenuItemText(MHND_FILE, menuFilePlayMode, "\pDebug");
        }
    }
#endif
    else if (discover)
    {
        newMenubar = mbarSpecial;
        if (kAdjustWizardMenu)
        {
            kAdjustWizardMenu = 0;
            SetMenuItemText(MHND_FILE, menuFilePlayMode, "\pExplore");
            for (i = CountMenuItems(MHND_WIZ); i > menuWizardAttributes; i--)
                DeleteMenuItem(MHND_WIZ, i);
        }
    }
    /* adjust the menubar, if there's a state change */
    if (theMenubar != newMenubar)
    {
        switch(theMenubar = newMenubar)
        {
        case mbarDim:
            /* disable all menus (except the apple menu) */
            for (i = menuFile; i < NUM_MBAR; i++)
                DisableMenuItem(MBARHND(i), 0);
            break;
        case mbarNoWindows:
        case mbarDA:
        case mbarNoMap:
            /* enable the file menu, but ... */
            EnableMenuItem(MHND_FILE, 0);
            /* ... disable the window commands! */
            for (i = menuFileRedraw; i <= menuFileEnterExplore; i++)
                DisableMenuItem(MHND_FILE, i);
            /* ... and disable the rest of the menus */
            for (i = menuEdit; i < NUM_MBAR; i++)
                DisableMenuItem(MBARHND(i), 0);
            if (theMenubar == mbarDA)
                EnableMenuItem(MHND_EDIT, 0);
            break;
        case mbarRegular:
        case mbarSpecial:
            /* enable all menus ... */
            for (i = menuFile; i < NUM_MBAR; i++)
                EnableMenuItem(MBARHND(i), 0);
            /* ... except the unused Edit menu */
            DisableMenuItem(MHND_EDIT, 0);
            /* ... enable the window commands */
            for (i = menuFileRedraw; i <= menuFileEnterExplore; i++)
                EnableMenuItem(MHND_FILE, i);
            if (theMenubar == mbarRegular)
                DisableMenuItem(MHND_FILE, menuFilePlayMode);
            else
                DisableMenuItem(MHND_FILE, menuFileEnterExplore);
            break;
        }
        DrawMenuBar();
    }
}
void attemptingto (char *)
Boolean CheckNhWin (WindowPtr mac_win)
Definition at line 199 of file macwin.c.
References GetNhWin().
Referenced by GetWinKind().
                                       {
    return GetNhWin (mac_win) != nil;
}
void DoMenuEvt (long)
Definition at line 1021 of file macmenu.c.
References aboutNetHack(), AddToKeyQueue(), askQuit(), askSave(), ID1_MBAR, menuApple, menuAppleAboutBox, menuEdit, menuFile, menuFileCleanup, menuFileEnterExplore, menuFilePrevMsg, menuFileQuit, menuFileRedraw, menuFileSave, MHND_APPLE, mstrEndChar, QUEUE_LEN, and SanePositions().
Referenced by HandleClick(), and HandleKey().
{
    short menuID = HiWord(menuEntry);
    short menuItem = LoWord(menuEntry);
    switch(menuID - ID1_MBAR) /* all submenus are default case */
    {
    case menuApple:
        if (menuItem == menuAppleAboutBox)
            aboutNetHack();
#if !TARGET_API_MAC_CARBON
        else
        {
            unsigned char daName[32];
            GetMenuItemText(MHND_APPLE, menuItem, * (Str255 *) daName);
            (void) OpenDeskAcc(daName);
        }
#endif
        break;
    /*
     * Those direct calls are ugly: they should be installed into cmd.c .
     * Those AddToKeyQueue() calls are also ugly: they should be put into
     * the 'STR#' resource.
     */
    case menuFile:
        switch(menuItem)
        {
        case menuFileRedraw:
            AddToKeyQueue ('R' & 0x1f, 1);
            break;
        case menuFilePrevMsg:
            AddToKeyQueue ('P' & 0x1f, 1);
            break;
        case menuFileCleanup:
            (void) SanePositions();
            break;
        case menuFileEnterExplore:
            AddToKeyQueue ('X', 1);
            break;
        case menuFileSave:
            askSave();
            break;
        case menuFileQuit:
            askQuit();
            break;
        }
        break;
    case menuEdit:
#if !TARGET_API_MAC_CARBON
        (void) SystemEdit(menuItem - 1);
#endif
        break;
    default: /* get associated string and add to key queue */
        {
            Str255 mstr;
            short i;
            GetIndString(mstr, menuID, menuItem);
            if (mstr[0] > QUEUE_LEN)
                mstr[0] = QUEUE_LEN;
            for (i = 1; ((i <= mstr[0]) && (mstr[i] != mstrEndChar)); i++)
                AddToKeyQueue(mstr[i], false);
        }
        break;
    }
    HiliteMenu(0);
}
void dprintf (char * , ...)
Definition at line 18 of file dprintf.c.
Referenced by _mt_init_stuff(), GetWinKind(), mac_create_nhwindow(), RetrievePosition(), SavePosition(), and SaveSize().
{
char buffer [500];
va_list list;
int doit;
#define DO_DEBUGSTR 1
#define DO_PLINE 2
    if (flags.debug) {
        doit = 0;
        if (macFlags.hasDebugger && KeyDown (0x39)) { /* Caps Lock */
            doit = DO_DEBUGSTR;
        } else if (KeyDown (0x3B) && iflags.window_inited && /* Control
      */
            (WIN_MESSAGE != -1) && theWindows [WIN_MESSAGE].
      its_window) {
            doit = DO_PLINE;
        }
        
        if (doit) {
            va_start (list, format);
            vsprintf (&buffer [1], format, list);
            va_end (list) ;
            if (doit == DO_DEBUGSTR) {
                buffer [0] = strlen (&buffer [1]);
                DebugStr ((uchar *) buffer);
            } else if (doit == DO_PLINE)
                pline ("%s", &buffer [1]);
        }
    }
}
Boolean FDECL (RetrieveWinPos , (WindowPtr, short *, short *))
void FDECL (C2P , (const char *c, unsigned char *p))
void FDECL (P2C , (const unsigned char *p, char *c))
void FDECL (process_openfile , (short s_vol, long s_dir, Str255 fNm, OSType ft))
int FDECL (try_key_queue , (char *))
void FDECL (enter_topl_mode , (char *))
void FDECL (leave_topl_mode , (char *))
void FDECL (topl_set_resp , (char *, char))
Boolean FDECL (topl_key , (unsigned char, Boolean))
E void FDECL (HandleEvent , (EventRecord *))
E void FDECL (mac_init_nhwindows , (int *, char **))
E void FDECL (mac_exit_nhwindows , (const char *))
E winid FDECL (mac_create_nhwindow , (int))
E void FDECL (mac_clear_nhwindow , (winid))
E void FDECL (mac_display_nhwindow , (winid, BOOLEAN_P))
E void FDECL (mac_destroy_nhwindow , (winid))
E void FDECL (mac_curs , (winid, int, int))
E void FDECL (mac_putstr , (winid, int, const char *))
E void FDECL (mac_start_menu , (winid))
E void FDECL (mac_add_menu , (winid, int, const anything *, CHAR_P, CHAR_P, int, const char *, BOOLEAN_P))
E void FDECL (mac_end_menu , (winid, const char *))
E int FDECL (mac_select_menu , (winid, int, menu_item **))
E int FDECL (mac_nh_poskey , (int *, int *, int *))
E char FDECL (mac_yn_function , (const char *, const char *, CHAR_P))
E void FDECL (mac_getlin , (const char *, char *))
E void FDECL (mac_number_pad , (int))
unsigned char GetFromKeyQueue (void)
Definition at line 103 of file macwin.c.
References keyQueue, keyQueueCount, keyQueueRead, and QUEUE_LEN.
Referenced by mac_nhgetch(), tgetch(), and try_key_queue().
                       {
    unsigned char ret;
    if (keyQueueCount) {
        ret = keyQueue [keyQueueRead++];
        keyQueueCount--;
        if (keyQueueRead >= QUEUE_LEN)
            keyQueueRead = 0;
    }
    else
        ret = 0;
    return ret;
}
void InitMenuRes (void)
Definition at line 869 of file macmenu.c.
References errGetMenu, errGetMenuList, listMenubar, listSubmenu, menuApple, menuBarListID, menuError(), menuRefUnn::mhnd, menuListRec::mref, mustGetMenuAlerts(), and menuListRec::numMenus.
Referenced by _mt_init_stuff(), and mac_init_nhwindows().
{
    static Boolean was_inited = 0;
    short i, j;
    menuListHandle mlHnd;
    MenuHandle menu;
    if (was_inited)
        return;
    was_inited = 1;
    mustGetMenuAlerts();
    for (i = listMenubar; i <= listSubmenu; i++) {
        if (! (mlHnd = (menuListHandle) GetResource('MNU#', (
      menuBarListID + i))))
            menuError(errGetMenuList);
        pMenuList[i] = (menuListPtr) NewPtr(GetHandleSize((Handle) mlHnd));
        *pMenuList[i] = **mlHnd;
        for (j = 0; j < pMenuList[i]->numMenus; j++)
        {
            if (! (menu = (MenuHandle) GetMenu((**mlHnd).mref[j].mresID))) {
            Str31 d;
                NumToString ((**mlHnd).mref[j].mresID, d);
                menuError(errGetMenu);
            }
            pMenuList[i]->mref[j].mhnd = menu;
            SetMenuID(menu, j + (**mlHnd).firstMenuID); /* consecutive IDs */
            /* expand apple menu */
            if ((i == listMenubar) && (j == menuApple)) {
                AppendResMenu(menu, 'DRVR');
            }
            InsertMenu(menu, ((i == listSubmenu) ? hierMenu : 0));
        }
    }
    DrawMenuBar();
    return;
}
Boolean itworked (short)
void mustwork (short)
void NDECL (InitMac)
void NDECL (port_help)
E void NDECL (mac_askname)
E void NDECL (mac_get_nh_event)
E int NDECL (mac_nhgetch)
E int NDECL (mac_doprev_message)
E int NDECL (mac_get_ext_cmd)
E void NDECL (mac_delay_output)
Boolean RetrievePosition (short , short * , short *)
Definition at line 88 of file maccurs.c.
References dprintf(), InitWinFile(), kLastWindowKind, WinPosSave::left, and WinPosSave::top.
Referenced by _mt_init_stuff(), mac_init_nhwindows(), RetrieveWinPos(), and SanePositions().
                                                       {
Point p;
    if (kind < 0 || kind > kLastWindowKind) {
        dprintf ("Retrieve Bad kind %d", kind);
        return 0;
    }
    InitWinFile ();
    if (!savePos [kind].validPos) {
        dprintf ("Retrieve Not stored kind %d", kind);
        return 0;
    }
    p.v = savePos [kind].top;
    p.h = savePos [kind].left;
    *left = p.h;
    *top = p.v;
    dprintf ("Retrieve Kind %d Pt (%d,%d)", kind, p.h, p.v);
    return (PtInRgn (p, GetGrayRgn ()));
}
Boolean RetrieveSize (short , short , short , short * , short *)
Definition at line 110 of file maccurs.c.
References height, WinPosSave::height, InitWinFile(), kLastWindowKind, width, and WinPosSave::width.
Referenced by mac_init_nhwindows(), and SanePositions().
{
    Point p;
    if (kind < 0 || kind > kLastWindowKind) {
        return 0;
    }
    InitWinFile ();
    if (!savePos [kind].validSize) {
        return 0;
    }
    *width = savePos [kind].width;
    *height = savePos [kind].height;
    p.h = left + *width;
    p.v = top + *height;
    return PtInRgn (p, GetGrayRgn ());
}
void SaveWindowPos (WindowPtr)
Definition at line 202 of file maccurs.c.
References GetWinKind(), and SavePosition().
Referenced by HandleClick().
{
    Rect r;
    GetWindowBounds(win, kWindowContentRgn, &r);
    SavePosition(GetWinKind(win), r.top, r.left);
}
void SaveWindowSize (WindowPtr)
Definition at line 213 of file maccurs.c.
References GetWinKind(), height, SaveSize(), and width.
Referenced by HandleClick().
{
    short width, height;
    Rect r;
    GetWindowBounds(win, kWindowContentRgn, &r);
    width = r.right - r.left;
    height = r.bottom - r.top;
    SaveSize(GetWinKind (win), height, width);
}
void showerror (char * , const char *)
void trans_num_keys (EventRecord *)
Definition at line 1233 of file macwin.c.
References iflags, and instance_flags::num_pad.
Referenced by GeneralKey().
                                      {
#if defined(__SC__) || defined(__MRC__)
# pragma unused(theEvent)
#endif
/* KMH -- Removed this translation.
 * Number pad keys should always emit digit characters.
 * That's consistent with the default MacOS behavior.
 * The number_pad option controls how digits are interpreted.
 */
#if 0
    if (iflags.num_pad) {
        Handle h = GetResource('Nump', theEvent->modifiers & shiftKey ? 129 : 128);
        if (h) {
            short inkey = (theEvent->message & keyCodeMask), *ab = (short *)*h;
            int i = ab[0];
            for (; i; i--) {
                if (inkey == (ab[i] & keyCodeMask)) {
                    theEvent->message = ab[i];
                    break;
                }
            }
        }
    }
#endif
}
Variable Documentation
winid BASE_WINDOW
Referenced by SanePositions(), and WindowGoAway().
struct window_procs mac_procs
Definition at line 2591 of file macwin.c.
Referenced by main().
MacFlags macFlags
Definition at line 127 of file macwin.c.
Referenced by ask_redraw(), dprintf(), finder_file_request(), and process_openfile().
Boolean small_screen
Definition at line 132 of file macwin.c.
Referenced by _mt_init_stuff(), mac_init_nhwindows(), and SanePositions().
MacDirs theDirs
Definition at line 52 of file macfile.c.
Referenced by InitMac(), and process_openfile().
NhWindow* theWindows
Definition at line 20 of file macwin.c.
Referenced by dprintf(), and GetNhWin().
winid WIN_INVEN
Definition at line 332 of file decl.h.
winid WIN_MAP
Definition at line 332 of file decl.h.
winid WIN_MESSAGE
Definition at line 331 of file decl.h.
winid WIN_STATUS
Definition at line 331 of file decl.h.