nethack/util/makedefs.c File Reference
#include `config.h`
*
#include `permonst.h`
*
#include `objclass.h`
*
#include `monsym.h`
*
#include `artilist.h`
*
#include `dungeon.h`
*
#include `obj.h`
*
#include `monst.h`
*
#include `you.h`
*
#include `flag.h`
*
#include `dlb.h`
*
#include `patchlevel.h`
*
#include `qtext.h`
*
Data Structures
struct deflist
Macros
#define MAKEDEFS_C /* use to conditionally include file sections */
#define SpinCursor(x)
#define Fprintf (void) fprintf
#define Fclose (void) fclose
#define Unlink (void) unlink
#define rewind(fp) fseek((fp),0L,SEEK_SET)	/* guarantee a return value */
#define DATE_FILE `date.h`
#define MONST_FILE `pm.h`
#define ONAME_FILE `onames.h`
#define OPTIONS_FILE `options`
#define ORACLE_FILE `oracles`
#define DATA_FILE `data`
#define RUMOR_FILE `rumors`
#define DGN_I_FILE `dungeon.def`
#define DGN_O_FILE `dungeon.pdf`
#define MON_STR_C `monstr.c`
#define QTXT_I_FILE `quest.txt`
#define QTXT_O_FILE `quest.dat`
#define VIS_TAB_H `vis_tab.h`
#define VIS_TAB_C `vis_tab.c`
#define INCLUDE_TEMPLATE `../include/%s`
#define SOURCE_TEMPLATE `../src/%s`
#define DGN_TEMPLATE `../dat/%s` /* where dungeon.pdf file goes */
#define DATA_TEMPLATE `../dat/%s`
#define DATA_IN_TEMPLATE `../dat/%s`
#define TEST_WIDTH COLNO
#define TEST_HEIGHT ROWNO
#define BLOCK_WIDTH (TEST_WIDTH + 10)
#define BLOCK_HEIGHT TEST_HEIGHT	/* don't need extra spaces */
#define MAX_ROW (BLOCK_HEIGHT + TEST_HEIGHT)
#define MAX_COL (BLOCK_WIDTH + TEST_WIDTH)
#define CLOSE_OFF_TABLE_STRING `99`	/* for the close table */
#define FAR_OFF_TABLE_STRING `0xff`	/* for the far table */
#define sign(z) ((z) < 0 ? -1 : ((z) ? 1 : 0))
#define IGNORED_FEATURES
#define NO_MSG 1	/* strlen of a null line returned by fgets() */
Functions
int FDECL (main,(int, char **))
void FDECL (do_makedefs,(char *))
void NDECL (do_objs)
void NDECL (do_data)
void NDECL (do_dungeon)
void NDECL (do_date)
void NDECL (do_options)
void NDECL (do_monstr)
void NDECL (do_permonst)
void NDECL (do_questtxt)
void NDECL (do_rumors)
void NDECL (do_oracles)
void NDECL (do_vision)
void NDECL (monst_init)
void NDECL (objects_init)
static void NDECL (make_version)
static char * FDECL (version_string,(char *))
static char * FDECL (version_id_string,(char *, const char *))
static char * FDECL (xcrypt,(const char *))
static int FDECL (check_control,(char *))
static char * FDECL (without_control,(char *))
static boolean FDECL (d_filter,(char *))
static boolean FDECL (h_filter,(char *))
static boolean FDECL (ranged_attk,(struct permonst *))
static int FDECL (mstrength,(struct permonst *))
static void NDECL (build_savebones_compat_string)
static boolean FDECL (qt_comment,(char *))
static boolean FDECL (qt_control,(char *))
static int FDECL (get_hdr,(char *))
static boolean FDECL (new_id,(char *))
static boolean FDECL (known_msg,(int, int))
static void FDECL (new_msg,(char *, int, int))
static void FDECL (do_qt_control,(char *))
static void FDECL (do_qt_text,(char *))
static void NDECL (adjust_qt_hdrs)
static void NDECL (put_qt_hdrs)
static char * FDECL (tmpdup,(const char *))
static char * FDECL (limit,(char *, int))
static char * FDECL (eos,(char *))
int main (int argc, argv)
void do_makedefs (char *options)
static char * xcrypt (char *str) const
void do_rumors ()
static void make_version ()
static char * version_string (char *outbuf)
static char * version_id_string (char *outbuf, const char *build_date)
void do_date ()
static void build_savebones_compat_string ()
void do_options ()
static boolean d_filter (char *line)
void do_data ()
static boolean h_filter (char *line)
void do_oracles ()
static int check_control (char *s)
static char * without_control (char *s)
void do_dungeon ()
static boolean ranged_attk (struct permonst *ptr)
static int mstrength (struct permonst *ptr)
void do_monstr ()
void do_permonst ()
static boolean qt_comment (char *s)
static boolean qt_control (char *s)
static int get_hdr (char *code)
static boolean new_id (char *code)
static boolean known_msg (int num, int id)
static void new_msg (char *s, int num, int id)
static void do_qt_control (char *s)
static void do_qt_text (char *s)
static void adjust_qt_hdrs ()
static void put_qt_hdrs ()
void do_questtxt ()
static char * limit (char *name, int pref)
void do_objs ()
static char * tmpdup (char *str) const
static char * eos (char *str)
void do_vision ()
Variables
static const char * Dont_Edit_Code
static const char * Dont_Edit_Data
static struct version_info version
static char in_line [256]
static char filename [60]
static FILE * ifp
static FILE * ofp
static FILE * tfp
static char save_bones_compat_buf [BUFSZ]
static const char * build_opts []
static const char * window_opts []
static const char * special_oracle []
static struct deflist deflist []
static struct qthdr qt_hdr
static struct msghdr msg_hdr [N_HDR]
static struct qtmsg * curr_msg
static int qt_line
static boolean in_msg
static char temp [32]
Macro Definition Documentation
#define BLOCK_HEIGHT TEST_HEIGHT	/* don't need extra spaces */
Definition at line 121 of file makedefs.c.
Referenced by do_vision().
#define BLOCK_WIDTH (TEST_WIDTH + 10)
Definition at line 120 of file makedefs.c.
Referenced by do_vision().
#define CLOSE_OFF_TABLE_STRING `99`	/* for the close table */
Definition at line 125 of file makedefs.c.
#define DATA_FILE `data`
Definition at line 63 of file makedefs.c.
Referenced by do_data().
#define DATA_IN_TEMPLATE `../dat/%s`
Definition at line 104 of file makedefs.c.
Referenced by do_data(), do_dungeon(), do_oracles(), do_questtxt(), and do_rumors().
#define DATA_TEMPLATE `../dat/%s`
Definition at line 103 of file makedefs.c.
Referenced by do_data(), do_options(), do_oracles(), do_questtxt(), and do_rumors().
#define DATE_FILE `date.h`
Definition at line 56 of file makedefs.c.
Referenced by do_date().
#define DGN_I_FILE `dungeon.def`
Definition at line 65 of file makedefs.c.
Referenced by do_dungeon().
#define DGN_O_FILE `dungeon.pdf`
Definition at line 66 of file makedefs.c.
Referenced by do_dungeon().
#define DGN_TEMPLATE `../dat/%s` /* where dungeon.pdf file goes */
Definition at line 102 of file makedefs.c.
Referenced by do_dungeon().
#define FAR_OFF_TABLE_STRING `0xff`	/* for the far table */
Definition at line 126 of file makedefs.c.
#define Fclose (void) fclose
Definition at line 45 of file makedefs.c.
Referenced by clipbrd_save(), do_data(), do_date(), do_dungeon(), do_monstr(), do_objs(), do_options(), do_oracles(), do_permonst(), do_questtxt(), do_rumors(), and do_vision().
#define Fprintf (void) fprintf
Definition at line 44 of file makedefs.c.
Referenced by do_data(), do_date(), do_dungeon(), do_makedefs(), do_monstr(), do_objs(), do_options(), do_oracles(), do_permonst(), do_qt_control(), do_qt_text(), do_questtxt(), do_rumors(), do_vision(), main(), new_id(), new_msg(), and put_qt_hdrs().
#define IGNORED_FEATURES
Value:
(0L \
                | (1L << 23) /* TIMED_DELAY */ \
                )
Definition at line 419 of file makedefs.c.
Referenced by check_version(), and do_date().
#define INCLUDE_TEMPLATE `../include/%s`
Definition at line 100 of file makedefs.c.
Referenced by do_date(), do_objs(), do_permonst(), and do_vision().
#define MAKEDEFS_C /* use to conditionally include file sections */
Definition at line 7 of file makedefs.c.
#define MAX_COL (BLOCK_WIDTH + TEST_WIDTH)
Definition at line 123 of file makedefs.c.
Referenced by do_vision().
#define MAX_ROW (BLOCK_HEIGHT + TEST_HEIGHT)
Definition at line 122 of file makedefs.c.
Referenced by do_vision().
#define MON_STR_C `monstr.c`
Definition at line 67 of file makedefs.c.
Referenced by do_monstr().
#define MONST_FILE `pm.h`
Definition at line 57 of file makedefs.c.
Referenced by do_permonst().
#define NO_MSG 1	/* strlen of a null line returned by fgets() */
Definition at line 1430 of file makedefs.c.
Referenced by qt_comment().
#define ONAME_FILE `onames.h`
Definition at line 58 of file makedefs.c.
Referenced by do_objs().
#define OPTIONS_FILE `options`
Definition at line 60 of file makedefs.c.
Referenced by do_options().
#define ORACLE_FILE `oracles`
Definition at line 62 of file makedefs.c.
Referenced by do_oracles().
#define QTXT_I_FILE `quest.txt`
Definition at line 68 of file makedefs.c.
Referenced by do_questtxt().
#define QTXT_O_FILE `quest.dat`
Definition at line 69 of file makedefs.c.
Referenced by do_questtxt().
#define rewind(fp) fseek((fp),0L,SEEK_SET)	/* guarantee a return value */
Definition at line 48 of file makedefs.c.
Referenced by do_data(), do_oracles(), and do_questtxt().
#define RUMOR_FILE `rumors`
Definition at line 64 of file makedefs.c.
Referenced by do_rumors().
#define sign(z) ((z) < 0 ? -1 : ((z) ? 1 : 0))
Definition at line 128 of file makedefs.c.
#define SOURCE_TEMPLATE `../src/%s`
Definition at line 101 of file makedefs.c.
Referenced by do_monstr(), and do_vision().
#define SpinCursor(x)
Definition at line 41 of file makedefs.c.
Referenced by do_dungeon(), do_monstr(), do_objs(), do_oracles(), do_permonst(), do_questtxt(), do_vision(), and h_filter().
#define TEST_HEIGHT ROWNO
Definition at line 119 of file makedefs.c.
#define TEST_WIDTH COLNO
Definition at line 118 of file makedefs.c.
#define Unlink (void) unlink
Definition at line 46 of file makedefs.c.
Referenced by do_data(), do_oracles(), do_rumors(), and do_vision().
#define VIS_TAB_C `vis_tab.c`
Definition at line 71 of file makedefs.c.
Referenced by do_vision().
#define VIS_TAB_H `vis_tab.h`
Definition at line 70 of file makedefs.c.
Referenced by do_vision().
Function Documentation
static void adjust_qt_hdrs () [static]
Definition at line 1557 of file makedefs.c.
References count, LEN_HDR, msg_hdr, and qt_hdr.
Referenced by do_questtxt().
{
    int i, j;
    long count = 0L, hdr_offset = sizeof(int) +
            (sizeof(char)*LEN_HDR + sizeof(long)) * qt_hdr.n_hdr;
    for(i = 0; i < qt_hdr.n_hdr; i++) {
        qt_hdr.offset[i] = hdr_offset;
        hdr_offset += sizeof(int) + sizeof(struct qtmsg) * msg_hdr[i].n_msg;
    }
    for(i = 0; i < qt_hdr.n_hdr; i++)
        for(j = 0; j < msg_hdr[i].n_msg; j++) {
        msg_hdr[i].qt_msg[j].offset = hdr_offset + count;
        count += msg_hdr[i].qt_msg[j].size;
        }
    return;
}
static void build_savebones_compat_string () [static]
Definition at line 612 of file makedefs.c.
References eos(), PATCHLEVEL, Sprintf, Strcpy, VERSION_COMPATIBILITY, VERSION_MAJOR, and VERSION_MINOR.
Referenced by do_options().
{
#ifdef VERSION_COMPATIBILITY
    unsigned long uver = VERSION_COMPATIBILITY;
#endif
    Strcpy(save_bones_compat_buf,
        "save and bones files accepted from version");
#ifdef VERSION_COMPATIBILITY
    Sprintf(eos(save_bones_compat_buf), "s %lu.%lu.%lu through %d.%d.%d",
        ((uver & 0xFF000000L) >> 24), ((uver & 0x00FF0000L) >> 16),
        ((uver & 0x0000FF00L) >> 8),
        VERSION_MAJOR, VERSION_MINOR, PATCHLEVEL);
#else
    Sprintf(eos(save_bones_compat_buf), " %d.%d.%d only",
        VERSION_MAJOR, VERSION_MINOR, PATCHLEVEL);
#endif
}
static int check_control (char	* s) [static]
Definition at line 1192 of file makedefs.c.
References deflist::defname.
Referenced by do_dungeon(), and without_control().
{
    int i;
    if(s[0] != '%') return(-1);
    for(i = 0; deflist[i].defname; i++)
        if(!strncmp(deflist[i].defname, s+1, strlen(deflist[i].defname)))
        return(i);
    return(-1);
}
static boolean d_filter (char * line) [static]
Definition at line 871 of file makedefs.c.
References FALSE, and TRUE.
Referenced by do_data().
{
    if (*line == '#') return TRUE; /* ignore comment lines */
    return FALSE;
}
void do_data ()
Definition at line 901 of file makedefs.c.
References d_filter(), DATA_FILE, DATA_IN_TEMPLATE, DATA_TEMPLATE, Dont_Edit_Data, eos(), exit(), EXIT_FAILURE, Fclose, filename, Fprintf, in_line, infile, perror, RDTMODE, rewind, Sprintf, Strcat, Unlink, and WRTMODE.
Referenced by do_makedefs().
{
    char infile[60], tempfile[60];
    boolean ok;
    long txt_offset;
    int entry_cnt, line_cnt;
    Sprintf(tempfile, DATA_TEMPLATE, "database.tmp");
    filename[0]='\0';
#ifdef FILE_PREFIX
    Strcat(filename,file_prefix);
#endif
    Sprintf(eos(filename), DATA_TEMPLATE,
      DATA_FILE);
    Sprintf(infile, DATA_IN_TEMPLATE, DATA_FILE);
    Strcat(infile,
#ifdef SHORT_FILENAMES
        ".bas"
#else
        ".base"
#endif
        );
    if (!(ifp = fopen(infile, RDTMODE))) { /* data.base */
        perror(infile);
        exit(EXIT_FAILURE);
    }
    if (!(ofp = fopen(filename, WRTMODE))) { /* data */
        perror(filename);
        Fclose(ifp);
        exit(EXIT_FAILURE);
    }
    if (!(tfp = fopen(tempfile, WRTMODE))) { /* database.tmp */
        perror(tempfile);
        Fclose(ifp);
        Fclose(ofp);
        Unlink(filename);
        exit(EXIT_FAILURE);
    }
    /* output a dummy header record; we'll rewind and overwrite it later */
    Fprintf(ofp, "%s%08lx\n", Dont_Edit_Data, 0L);
    entry_cnt = line_cnt = 0;
    /* read through the input file and split it into two sections */
    while (fgets(in_line, sizeof in_line, ifp)) {
        if (d_filter(in_line)) continue;
        if (*in_line > ' ') { /* got an entry name */
        /* first finish previous entry */
        if (line_cnt) Fprintf(ofp, "%d\n", line_cnt), line_cnt = 0;
        /* output the entry name */
        (void) fputs(in_line, ofp);
        entry_cnt++; /* update number of entries */
        } else if (entry_cnt) { /* got some descriptive text */
        /* update previous entry with current text offset */
        if (!line_cnt) Fprintf(ofp, "%ld,", ftell(tfp));
        /* save the text line in the scratch file */
        (void) fputs(in_line, tfp);
        line_cnt++; /* update line counter */
        }
    }
    /* output an end marker and then record the current position */
    if (line_cnt) Fprintf(ofp, "%d\n", line_cnt);
    Fprintf(ofp, ".\n%ld,%d\n", ftell(tfp), 0);
    txt_offset = ftell(ofp);
    Fclose(ifp); /* all done with original input file */
    /* reprocess the scratch file; 1st format an error msg, just in case */
    Sprintf(in_line, "rewind of \"%s\"", tempfile);
    if (rewind(tfp) != 0) goto dead_data;
    /* copy all lines of text from the scratch file into the output file */
    while (fgets(in_line, sizeof in_line, tfp))
        (void) fputs(in_line, ofp);
    /* finished with scratch file */
    Fclose(tfp);
    Unlink(tempfile); /* remove it */
    /* update the first record of the output file; prepare error msg 1st */
    Sprintf(in_line, "rewind of \"%s\"", filename);
    ok = (rewind(ofp) == 0);
    if (ok) {
       Sprintf(in_line, "header rewrite of \"%s\"", filename);
       ok = (fprintf(ofp, "%s%08lx\n", Dont_Edit_Data, txt_offset) >= 0);
    }
    if (!ok) {
dead_data: perror(in_line); /* report the problem */
        /* close and kill the aborted output file, then give up */
        Fclose(ofp);
        Unlink(filename);
        exit(EXIT_FAILURE);
    }
    /* all done */
    Fclose(ofp);
    return;
}
void do_date ()
Definition at line 544 of file makedefs.c.
References buf, BUFSZ, DATE_FILE, Dont_Edit_Code, version_info::entity_count, eos(), exit(), EXIT_FAILURE, Fclose, version_info::feature_set, filename, Fprintf, IGNORED_FEATURES, version_info::incarnation, INCLUDE_TEMPLATE, localtime(), PATCHLEVEL, perror, Sprintf, Strcat, Strcpy, version_info::struct_sizes, time, tm::tm_mday, tm::tm_mon, tm::tm_year, version, version_id_string(), VERSION_MAJOR, VERSION_MINOR, version_string(), and WRTMODE.
Referenced by do_makedefs().
{
    long clocktim = 0;
    char *c, cbuf[60], buf[BUFSZ];
    const char *ul_sfx;
    filename[0]='\0';
#ifdef FILE_PREFIX
    Strcat(filename,file_prefix);
#endif
    Sprintf(eos(filename), INCLUDE_TEMPLATE,
      DATE_FILE);
    if (!(ofp = fopen(filename, WRTMODE))) {
        perror(filename);
        exit(EXIT_FAILURE);
    }
    Fprintf(ofp,"/*\tSCCS Id: @(#)date.h\t3.4\t2002/02/03 */\n\n");
    Fprintf(ofp,Dont_Edit_Code);
#ifdef KR1ED
    (void) time(&clocktim);
    Strcpy(cbuf, ctime(&clocktim));
#else
    (void) time((time_t *)&clocktim);
    Strcpy(cbuf, ctime((time_t *)&clocktim));
#endif
    for (c = cbuf; *c; c++) if (*c == '\n') break;
    *c = '\0'; /* strip off the '\n' */
    Fprintf(ofp,"#define BUILD_DATE \"%s\"\n", cbuf);
    Fprintf(ofp,"#define BUILD_TIME (%ldL)\n", clocktim);
    Fprintf(ofp,"\n");
#ifdef NHSTDC
    ul_sfx = "UL";
#else
    ul_sfx = "L";
#endif
    Fprintf(ofp,"#define VERSION_NUMBER 0x%08lx%s\n",
        version.incarnation, ul_sfx);
    Fprintf(ofp,"#define VERSION_FEATURES 0x%08lx%s\n",
        version.feature_set, ul_sfx);
#ifdef IGNORED_FEATURES
    Fprintf(ofp,"#define IGNORED_FEATURES 0x%08lx%s\n",
        (unsigned long) IGNORED_FEATURES, ul_sfx);
#endif
    Fprintf(ofp,"#define VERSION_SANITY1 0x%08lx%s\n",
        version.entity_count, ul_sfx);
    Fprintf(ofp,"#define VERSION_SANITY2 0x%08lx%s\n",
        version.struct_sizes, ul_sfx);
    Fprintf(ofp,"\n");
    Fprintf(ofp,"#define VERSION_STRING \"%s\"\n", version_string(buf));
    Fprintf(ofp,"#define VERSION_ID \\\n \"%s\"\n",
        version_id_string(buf, cbuf));
    Fprintf(ofp,"\n");
#ifdef AMIGA
    {
    struct tm *tm = localtime((time_t *) &clocktim);
    Fprintf(ofp,"#define AMIGA_VERSION_STRING ");
    Fprintf(ofp,"\"\\0$VER: NetHack %d.%d.%d (%d.%d.%d)\"\n",
        VERSION_MAJOR, VERSION_MINOR, PATCHLEVEL,
        tm->tm_mday, tm->tm_mon+1, tm->tm_year+1900);
    }
#endif
    Fclose(ofp);
    return;
}
void do_dungeon ()
Definition at line 1214 of file makedefs.c.
References check_control(), DATA_IN_TEMPLATE, DGN_I_FILE, DGN_O_FILE, DGN_TEMPLATE, Dont_Edit_Data, eos(), exit(), EXIT_FAILURE, Fclose, filename, Fprintf, in_line, perror, RDTMODE, SpinCursor, Sprintf, Strcat, without_control(), and WRTMODE.
Referenced by do_makedefs().
{
    int rcnt = 0;
    Sprintf(filename, DATA_IN_TEMPLATE,
      DGN_I_FILE);
    if (!(ifp = fopen(filename, RDTMODE))) {
        perror(filename);
        exit(EXIT_FAILURE);
    }
    filename[0]='\0';
#ifdef FILE_PREFIX
    Strcat(filename, file_prefix);
#endif
    Sprintf(eos(filename), DGN_TEMPLATE,
      DGN_O_FILE);
    if (!(ofp = fopen(filename, WRTMODE))) {
        perror(filename);
        exit(EXIT_FAILURE);
    }
    Fprintf(ofp,Dont_Edit_Data);
    while (fgets(in_line, sizeof in_line, ifp) != 0) {
        SpinCursor(3);
        rcnt++;
        if(in_line[0] == '#') continue; /* discard comments */
recheck:
        if(in_line[0] == '%') {
        int i = check_control(in_line);
        if(i >= 0) {
            if(!deflist[i].true_or_false) {
            while (fgets(in_line, sizeof in_line, ifp) != 0)
                if(check_control(in_line) != i) goto recheck;
            } else
            (void) fputs(without_control(in_line),ofp);
        } else {
            Fprintf(stderr, "Unknown control option '%s' in file %s at line %d.\n",
                in_line, DGN_I_FILE, rcnt);
            exit(EXIT_FAILURE);
        }
        } else
        (void) fputs(in_line,ofp);
    }
    Fclose(ifp);
    Fclose(ofp);
    return;
}
void do_makedefs (char	* options)
Definition at line 261 of file makedefs.c.
References do_data(), do_date(), do_dungeon(), do_monstr(), do_objs(), do_options(), do_oracles(), do_permonst(), do_questtxt(), do_rumors(), do_vision(), exit(), EXIT_FAILURE, Fprintf, make_version(), monst_init(), more_than_one, and objects_init().
Referenced by main().
{
    boolean more_than_one;
    /* Note: these initializers don't do anything except guarantee that
        we're linked properly.
    */
    monst_init();
    objects_init();
    /* construct the current version number */
    make_version();
    more_than_one = strlen(options) > 1;
    while (*options) {
        if (more_than_one)
        Fprintf(stderr, "makedefs -%c\n", *options);
        switch (*options) {
        case 'o':
        case 'O': do_objs();
                break;
        case 'd':
        case 'D': do_data();
                break;
        case 'e':
        case 'E': do_dungeon();
                break;
        case 'm':
        case 'M': do_monstr();
                break;
        case 'v':
        case 'V': do_date();
                do_options();
                break;
        case 'p':
        case 'P': do_permonst();
                break;
        case 'q':
        case 'Q': do_questtxt();
                break;
        case 'r':
        case 'R': do_rumors();
                break;
        case 'h':
        case 'H': do_oracles();
                break;
        case 'z':
        case 'Z': do_vision();
                break;
        default: Fprintf(stderr, "Unknown option '%c'.\n",
                    *options);
                (void) fflush(stderr);
                exit(EXIT_FAILURE);
        
        }
        options++;
    }
    if (more_than_one) Fprintf(stderr, "Completed.\n"); /* feedback */
}
void do_monstr ()
Definition at line 1337 of file makedefs.c.
References Dont_Edit_Code, eos(), exit(), EXIT_FAILURE, Fclose, filename, Fprintf, permonst::mlet, MON_STR_C, mons, mstrength(), perror, SOURCE_TEMPLATE, SpinCursor, Sprintf, Strcat, and WRTMODE.
Referenced by do_makedefs().
{
    register struct permonst *ptr;
    register int i, j;
    /*
     * create the source file, "monstr.c"
     */
    filename[0]='\0';
#ifdef FILE_PREFIX
    Strcat(filename, file_prefix);
#endif
    Sprintf(eos(filename), SOURCE_TEMPLATE,
      MON_STR_C);
    if (!(ofp = fopen(filename, WRTMODE))) {
    perror(filename);
    exit(EXIT_FAILURE);
    }
    Fprintf(ofp,Dont_Edit_Code);
    Fprintf(ofp,"#include \"config.h\"\n");
    Fprintf(ofp,"\nconst int monstr[] = {\n");
    for (ptr = &mons[0], j = 0; ptr->mlet; ptr++) {
    SpinCursor(3);
    i = mstrength(ptr);
    Fprintf(ofp,"%2d,%c", i, (++j & 15) ? ' ' : '\n');
    }
    /* might want to insert a final 0 entry here instead of just newline */
    Fprintf(ofp,"%s};\n", (j & 15) ? "\n" : "");
    Fprintf(ofp,"\nvoid NDECL(monstr_init);\n");
    Fprintf(ofp,"\nvoid\n");
    Fprintf(ofp,"monstr_init()\n");
    Fprintf(ofp,"{\n");
    Fprintf(ofp," return;\n");
    Fprintf(ofp,"}\n");
    Fprintf(ofp,"\n/*monstr.c*/\n");
    Fclose(ofp);
    return;
}
void do_objs ()
Definition at line 1692 of file makedefs.c.
References AMULET_CLASS, Dont_Edit_Code, eos(), exit(), EXIT_FAILURE, FALSE, Fclose, filename, Fprintf, GEM_CLASS, GLASS, ILLOBJ_CLASS, INCLUDE_TEMPLATE, limit(), OBJ_NAME, objects, objclass::oc_class, objclass::oc_descr_idx, objclass::oc_name_idx, objclass::oc_prob, ONAME_FILE, perror, PLASTIC, POTION_CLASS, RING_CLASS, SCROLL_CLASS, SPBOOK_CLASS, SpinCursor, Sprintf, Strcat, tmpdup(), TRUE, WAND_CLASS, and WRTMODE.
Referenced by do_makedefs().
{
    int i, sum = 0;
    char *c, *objnam;
    int nspell = 0;
    int prefix = 0;
    char class = '\0';
    boolean sumerr = FALSE;
    filename[0]='\0';
#ifdef FILE_PREFIX
    Strcat(filename, file_prefix);
#endif
    Sprintf(eos(filename), INCLUDE_TEMPLATE,
      ONAME_FILE);
    if (!(ofp = fopen(filename, WRTMODE))) {
        perror(filename);
        exit(EXIT_FAILURE);
    }
    Fprintf(ofp,"/*\tSCCS Id: @(#)onames.h\t3.4\t2002/02/03 */\n\n");
    Fprintf(ofp,Dont_Edit_Code);
    Fprintf(ofp,"#ifndef ONAMES_H\n#define ONAMES_H\n\n");
    for(i = 0; !i || objects[i].oc_class != ILLOBJ_CLASS; i++) {
        SpinCursor(3);
        objects[i].oc_name_idx = objects[i].
      oc_descr_idx = i; /* init */
        if (!(objnam = tmpdup(OBJ_NAME(objects[i])))) continue;
        /* make sure probabilities add up to 1000 */
        if(objects[i].oc_class != class) {
            if (sum && sum != 1000) {
                Fprintf(stderr, "prob error for class %d (%d%%)",
                    class, sum);
                (void) fflush(stderr);
                sumerr = TRUE;
            }
            class = objects[i].oc_class;
            sum = 0;
        }
        for (c = objnam; *c; c++)
            if (*c >= 'a' && *c <= 'z') *c -= (char)('a' - 'A');
            else if (*c < 'A' || *c > 'Z') *c = '_';
        switch (class) {
            case WAND_CLASS:
            Fprintf(ofp,"#define\tWAN_"); prefix = 1; break;
            case RING_CLASS:
            Fprintf(ofp,"#define\tRIN_"); prefix = 1; break;
            case POTION_CLASS:
            Fprintf(ofp,"#define\tPOT_"); prefix = 1; break;
            case SPBOOK_CLASS:
            Fprintf(ofp,"#define\tSPE_"); prefix = 1; nspell++; break;
            case SCROLL_CLASS:
            Fprintf(ofp,"#define\tSCR_"); prefix = 1; break;
            case AMULET_CLASS:
            /* avoid trouble with stupid C preprocessors */
            Fprintf(ofp,"#define\t");
            if(objects[i].oc_material == PLASTIC) {
                Fprintf(ofp,"FAKE_AMULET_OF_YENDOR\t%d\n", i);
                prefix = -1;
                break;
            }
            break;
            case GEM_CLASS:
            /* avoid trouble with stupid C preprocessors */
            if(objects[i].oc_material == GLASS) {
                Fprintf(ofp,"/* #define\t%s\t%d */\n",
                            objnam, i);
                prefix = -1;
                break;
            }
            default:
            Fprintf(ofp,"#define\t");
        }
        if (prefix >= 0)
            Fprintf(ofp,"%s\t%d\n", limit(objnam, prefix), i);
        prefix = 0;
        sum += objects[i].oc_prob;
    }
    /* check last set of probabilities */
    if (sum && sum != 1000) {
        Fprintf(stderr, "prob error for class %d (%d%%)", class, sum);
        (void) fflush(stderr);
        sumerr = TRUE;
    }
    Fprintf(ofp,"#define\tLAST_GEM\t(JADE)\n");
    Fprintf(ofp,"#define\tMAXSPELL\t%d\n", nspell+1);
    Fprintf(ofp,"#define\tNUM_OBJECTS\t%d\n", i);
    Fprintf(ofp, "\n/* Artifacts (unique objects) */\n\n");
    for (i = 1; artifact_names[i]; i++) {
        SpinCursor(3);
        for (c = objnam = tmpdup(artifact_names[i]); *c; c++)
            if (*c >= 'a' && *c <= 'z') *c -= (char)('a' - 'A');
            else if (*c < 'A' || *c > 'Z') *c = '_';
        if (!strncmp(objnam, "THE_", 4))
            objnam += 4;
#ifdef TOURIST
        /* fudge _platinum_ YENDORIAN EXPRESS CARD */
        if (!strncmp(objnam, "PLATINUM_", 9))
            objnam += 9;
#endif
        Fprintf(ofp,"#define\tART_%s\t%d\n", limit(objnam, 1), i);
    }
    Fprintf(ofp, "#define\tNROFARTIFACTS\t%d\n", i-1);
    Fprintf(ofp,"\n#endif /* ONAMES_H */\n");
    Fclose(ofp);
    if (sumerr) exit(EXIT_FAILURE);
    return;
}
void do_options ()
Definition at line 813 of file makedefs.c.
References build_savebones_compat_string(), COLNO, DATA_TEMPLATE, DEFAULT_WINDOW_SYS, eos(), exit(), EXIT_FAILURE, Fclose, filename, Fprintf, OPTIONS_FILE, PATCHLEVEL, perror, SIZE, Sprintf, Strcat, VERSION_MAJOR, VERSION_MINOR, and WRTMODE.
Referenced by do_makedefs().
{
    register int i, length;
    register const char *str, *indent = " ";
    filename[0]='\0';
#ifdef FILE_PREFIX
    Strcat(filename,file_prefix);
#endif
    Sprintf(eos(filename), DATA_TEMPLATE,
      OPTIONS_FILE);
    if (!(ofp = fopen(filename, WRTMODE))) {
        perror(filename);
        exit(EXIT_FAILURE);
    }
    build_savebones_compat_string();
    Fprintf(ofp,
#ifdef BETA
        "\n NetHack version %d.%d.%d [beta]\n",
#else
        "\n NetHack version %d.%d.%d\n",
#endif
        VERSION_MAJOR, VERSION_MINOR, PATCHLEVEL);
    Fprintf(ofp,"\nOptions compiled into this edition:\n");
    length = COLNO + 1; /* force 1st item onto new line */
    for (i = 0; i < SIZE(build_opts); i++) {
        str = build_opts[i];
        if (length + strlen(str) > COLNO - 5)
        Fprintf(ofp,"\n%s", indent), length = strlen(indent);
        else
        Fprintf(ofp," "), length++;
        Fprintf(ofp,"%s", str), length += strlen(str);
        Fprintf(ofp,(i < SIZE(build_opts) - 1) ? "," : "."), length++;
    }
    Fprintf(ofp,"\n\nSupported windowing systems:\n");
    length = COLNO + 1; /* force 1st item onto new line */
    for (i = 0; i < SIZE(window_opts) - 1; i++) {
        str = window_opts[i];
        if (length + strlen(str) > COLNO - 5)
        Fprintf(ofp,"\n%s", indent), length = strlen(indent);
        else
        Fprintf(ofp," "), length++;
        Fprintf(ofp,"%s", str), length += strlen(str);
        Fprintf(ofp, ","), length++;
    }
    Fprintf(ofp, "\n%swith a default of %s.", indent,
      DEFAULT_WINDOW_SYS);
    Fprintf(ofp,"\n\n");
    Fclose(ofp);
    return;
}
void do_oracles ()
Definition at line 1044 of file makedefs.c.
References DATA_IN_TEMPLATE, DATA_TEMPLATE, Dont_Edit_Data, eos(), exit(), EXIT_FAILURE, FALSE, Fclose, filename, Fprintf, h_filter(), in_line, infile, offset, oracle_cnt, ORACLE_FILE, perror, RDTMODE, rewind, SEEK_SET, SIZE, SpinCursor, Sprintf, Strcat, tfp, TRUE, Unlink, WRTMODE, and xcrypt().
Referenced by do_makedefs().
{
    char infile[60], tempfile[60];
    boolean in_oracle, ok;
    long txt_offset, offset, fpos;
    int oracle_cnt;
    register int i;
    Sprintf(tempfile, DATA_TEMPLATE, "oracles.tmp");
    filename[0]='\0';
#ifdef FILE_PREFIX
    Strcat(filename, file_prefix);
#endif
    Sprintf(eos(filename), DATA_TEMPLATE,
      ORACLE_FILE);
    Sprintf(infile, DATA_IN_TEMPLATE, ORACLE_FILE);
    Strcat(infile, ".txt");
    if (!(ifp = fopen(infile, RDTMODE))) {
        perror(infile);
        exit(EXIT_FAILURE);
    }
    if (!(ofp = fopen(filename, WRTMODE))) {
        perror(filename);
        Fclose(ifp);
        exit(EXIT_FAILURE);
    }
    if (!(tfp = fopen(tempfile, WRTMODE))) { /* oracles.tmp */
        perror(tempfile);
        Fclose(ifp);
        Fclose(ofp);
        Unlink(filename);
        exit(EXIT_FAILURE);
    }
    /* output a dummy header record; we'll rewind and overwrite it later */
    Fprintf(ofp, "%s%5d\n", Dont_Edit_Data, 0);
    /* handle special oracle; it must come first */
    (void) fputs("---\n", tfp);
    Fprintf(ofp, "%05lx\n", ftell(tfp)); /* start pos of special oracle */
    for (i = 0; i < SIZE(special_oracle); i++) {
        (void) fputs(xcrypt(special_oracle[i]), tfp);
        (void) fputc('\n', tfp);
    }
    SpinCursor(3);
    oracle_cnt = 1;
    (void) fputs("---\n", tfp);
    Fprintf(ofp, "%05lx\n", ftell(tfp)); /* start pos of first oracle */
    in_oracle = FALSE;
    while (fgets(in_line, sizeof in_line, ifp)) {
        SpinCursor(3);
        if (h_filter(in_line)) continue;
        if (!strncmp(in_line, "-----", 5)) {
        if (!in_oracle) continue;
        in_oracle = FALSE;
        oracle_cnt++;
        (void) fputs("---\n", tfp);
        Fprintf(ofp, "%05lx\n", ftell(tfp));
        /* start pos of this oracle */
        } else {
        in_oracle = TRUE;
        (void) fputs(xcrypt(in_line), tfp);
        }
    }
    if (in_oracle) { /* need to terminate last oracle */
        oracle_cnt++;
        (void) fputs("---\n", tfp);
        Fprintf(ofp, "%05lx\n", ftell(tfp)); /* eof position */
    }
    /* record the current position */
    txt_offset = ftell(ofp);
    Fclose(ifp); /* all done with original input file */
    /* reprocess the scratch file; 1st format an error msg, just in case */
    Sprintf(in_line, "rewind of \"%s\"", tempfile);
    if (rewind(tfp) != 0) goto dead_data;
    /* copy all lines of text from the scratch file into the output file */
    while (fgets(in_line, sizeof in_line, tfp))
        (void) fputs(in_line, ofp);
    /* finished with scratch file */
    Fclose(tfp);
    Unlink(tempfile); /* remove it */
    /* update the first record of the output file; prepare error msg 1st */
    Sprintf(in_line, "rewind of \"%s\"", filename);
    ok = (rewind(ofp) == 0);
    if (ok) {
        Sprintf(in_line, "header rewrite of \"%s\"", filename);
        ok = (fprintf(ofp, "%s%5d\n", Dont_Edit_Data, oracle_cnt) >=0);
    }
    if (ok) {
        Sprintf(in_line, "data rewrite of \"%s\"", filename);
        for (i = 0; i <= oracle_cnt; i++) {
#ifndef VMS /* alpha/vms v1.0; this fflush seems to confuse ftell */
        if (!(ok = (fflush(ofp) == 0))) break;
#endif
        if (!(ok = (fpos = ftell(ofp)) >= 0)) break;
        if (!(ok = (fseek(ofp, fpos, SEEK_SET) >= 0))) break;
        if (!(ok = (fscanf(ofp, "%5lx", &offset) == 1))) break;
#ifdef MAC
# ifdef __MWERKS__
        /*
        MetroWerks CodeWarrior Pro 1's (AKA CW12) version of MSL
        (ANSI C Libraries) needs this rewind or else the fprintf
        stops working. This may also be true for CW11, but has
        never been checked.
        */
        rewind(ofp);
# endif
#endif
        if (!(ok = (fseek(ofp, fpos, SEEK_SET) >= 0))) break;
        if (!(ok = (fprintf(ofp, "%05lx\n", offset + txt_offset) >= 0)))
            break;
        }
    }
    if (!ok) {
dead_data: perror(in_line); /* report the problem */
        /* close and kill the aborted output file, then give up */
        Fclose(ofp);
        Unlink(filename);
        exit(EXIT_FAILURE);
    }
    /* all done */
    Fclose(ofp);
    return;
}
void do_permonst ()
Definition at line 1380 of file makedefs.c.
References Dont_Edit_Code, eos(), exit(), EXIT_FAILURE, Fclose, filename, Fprintf, INCLUDE_TEMPLATE, permonst::mlet, permonst::mname, mons, MONST_FILE, perror, S_HUMAN, SpinCursor, Sprintf, Strcat, tmpdup(), and WRTMODE.
Referenced by do_makedefs().
{
    int i;
    char *c, *nam;
    filename[0]='\0';
#ifdef FILE_PREFIX
    Strcat(filename, file_prefix);
#endif
    Sprintf(eos(filename), INCLUDE_TEMPLATE,
      MONST_FILE);
    if (!(ofp = fopen(filename, WRTMODE))) {
        perror(filename);
        exit(EXIT_FAILURE);
    }
    Fprintf(ofp,"/*\tSCCS Id: @(#)pm.h\t3.4\t2002/02/03 */\n\n");
    Fprintf(ofp,Dont_Edit_Code);
    Fprintf(ofp,"#ifndef PM_H\n#define PM_H\n");
    if (strcmp(mons[0].mname, "playermon") != 0)
        Fprintf(ofp,"\n#define\tPM_PLAYERMON\t(-1)");
    for (i = 0; mons[i].mlet; i++) {
        SpinCursor(3);
        Fprintf(ofp,"\n#define\tPM_");
        if (mons[i].mlet == S_HUMAN &&
                !strncmp(mons[i].mname, "were", 4))
            Fprintf(ofp, "HUMAN_");
        for (nam = c = tmpdup(mons[i].mname); *c; c++)
            if (*c >= 'a' && *c <= 'z') *c -= (char)('a' - 'A');
            else if (*c < 'A' || *c > 'Z') *c = '_';
        Fprintf(ofp,"%s\t%d", nam, i);
    }
    Fprintf(ofp,"\n\n#define\tNUMMONS\t%d\n", i);
    Fprintf(ofp,"\n#endif /* PM_H */\n");
    Fclose(ofp);
    return;
}
static void do_qt_control (char * s) [static]
Definition at line 1507 of file makedefs.c.
References BUFSZ, FALSE, Fprintf, get_hdr(), known_msg(), new_id(), new_msg(), and TRUE.
Referenced by do_questtxt().
{
    char code[BUFSZ];
    int num, id = 0;
    switch(s[1]) {
        case 'C': if(in_msg) {
                Fprintf(stderr, CREC_IN_MSG, qt_line);
                break;
            } else {
                in_msg = TRUE;
                if (sscanf(&s[4], "%s %5d", code, &id) != 2) {
                    Fprintf(stderr, UNREC_CREC, qt_line);
                    break;
                }
                num = get_hdr(code);
                if (!num && !new_id(code))
                    break;
                num = get_hdr(code)-1;
                if(known_msg(num, id))
                    Fprintf(stderr, DUP_MSG, qt_line);
                else new_msg(s, num, id);
            }
            break;
        case 'E': if(!in_msg) {
                Fprintf(stderr, END_NOT_IN_MSG, qt_line);
                break;
            } else in_msg = FALSE;
            break;
        default: Fprintf(stderr, UNREC_CREC, qt_line);
            break;
    }
}
static void do_qt_text (char * s) [static]
Definition at line 1546 of file makedefs.c.
References Fprintf, and qtmsg::size.
Referenced by do_questtxt().
{
    if (!in_msg) {
        Fprintf(stderr, TEXT_NOT_IN_MSG, qt_line);
    }
    curr_msg->size += strlen(s);
    return;
}
void do_questtxt ()
Definition at line 1626 of file makedefs.c.
References adjust_qt_hdrs(), DATA_IN_TEMPLATE, DATA_TEMPLATE, do_qt_control(), do_qt_text(), eos(), exit(), EXIT_FAILURE, FALSE, Fclose, filename, Fprintf, in_line, ofp, perror, put_qt_hdrs(), qt_comment(), qt_control(), qt_hdr, QTXT_I_FILE, QTXT_O_FILE, RDTMODE, rewind, SpinCursor, Sprintf, stdout, Strcat, WRBMODE, and xcrypt().
Referenced by do_makedefs().
{
    Sprintf(filename, DATA_IN_TEMPLATE,
      QTXT_I_FILE);
    if(!(ifp = fopen(filename, RDTMODE))) {
        perror(filename);
        exit(EXIT_FAILURE);
    }
    filename[0]='\0';
#ifdef FILE_PREFIX
    Strcat(filename, file_prefix);
#endif
    Sprintf(eos(filename), DATA_TEMPLATE,
      QTXT_O_FILE);
    if(!(ofp = fopen(filename, WRBMODE))) {
        perror(filename);
        Fclose(ifp);
        exit(EXIT_FAILURE);
    }
    qt_hdr.n_hdr = 0;
    qt_line = 0;
    in_msg = FALSE;
    while (fgets(in_line, 80, ifp) != 0) {
        SpinCursor (3);
        qt_line++;
        if(qt_control(in_line)) do_qt_control(
      in_line);
        else if(qt_comment(in_line)) continue;
        else do_qt_text(in_line);
    }
    (void) rewind(ifp);
    in_msg = FALSE;
    adjust_qt_hdrs();
    put_qt_hdrs();
    while (fgets(in_line, 80, ifp) != 0) {
        if(qt_control(in_line)) {
            in_msg = (in_line[1] == 'C');
            continue;
        } else if(qt_comment(in_line)) continue;
#ifdef DEBUG
        Fprintf(stderr, "%ld: %s", ftell(stdout), in_line);
#endif
        (void) fputs(xcrypt(in_line), ofp);
    }
    Fclose(ifp);
    Fclose(ofp);
    return;
}
void do_rumors ()
Definition at line 347 of file makedefs.c.
References DATA_IN_TEMPLATE, DATA_TEMPLATE, Dont_Edit_Data, eos(), exit(), EXIT_FAILURE, Fclose, filename, Fprintf, in_line, infile, ofp, perror, RDTMODE, RUMOR_FILE, SEEK_END, SEEK_SET, Sprintf, Strcat, true_rumor_size, Unlink, WRTMODE, and xcrypt().
Referenced by do_makedefs().
{
    char infile[60];
    long true_rumor_size;
    filename[0]='\0';
#ifdef FILE_PREFIX
    Strcat(filename,file_prefix);
#endif
    Sprintf(eos(filename), DATA_TEMPLATE,
      RUMOR_FILE);
    if (!(ofp = fopen(filename, WRTMODE))) {
        perror(filename);
        exit(EXIT_FAILURE);
    }
    Fprintf(ofp,Dont_Edit_Data);
    Sprintf(infile, DATA_IN_TEMPLATE, RUMOR_FILE);
    Strcat(infile, ".tru");
    if (!(ifp = fopen(infile, RDTMODE))) {
        perror(infile);
        Fclose(ofp);
        Unlink(filename); /* kill empty output file */
        exit(EXIT_FAILURE);
    }
    /* get size of true rumors file */
#ifndef VMS
    (void) fseek(ifp, 0L, SEEK_END);
    true_rumor_size = ftell(ifp);
#else
    /* seek+tell is only valid for stream format files; since rumors.%%%
       might be in record format, count the actual data bytes instead.
     */
    true_rumor_size = 0;
    while (fgets(in_line, sizeof in_line, ifp) != 0)
        true_rumor_size += strlen(in_line); /* includes newline */
#endif /* VMS */
    Fprintf(ofp,"%06lx\n", true_rumor_size);
    (void) fseek(ifp, 0L, SEEK_SET);
    /* copy true rumors */
    while (fgets(in_line, sizeof in_line, ifp) != 0)
        (void) fputs(xcrypt(in_line), ofp);
    Fclose(ifp);
    Sprintf(infile, DATA_IN_TEMPLATE, RUMOR_FILE);
    Strcat(infile, ".fal");
    if (!(ifp = fopen(infile, RDTMODE))) {
        perror(infile);
        Fclose(ofp);
        Unlink(filename); /* kill incomplete output file */
        exit(EXIT_FAILURE);
    }
    /* copy false rumors */
    while (fgets(in_line, sizeof in_line, ifp) != 0)
        (void) fputs(xcrypt(in_line), ofp);
    Fclose(ifp);
    Fclose(ofp);
    return;
}
void do_vision ()
Definition at line 1836 of file makedefs.c.
References BLOCK_HEIGHT, BLOCK_WIDTH, Dont_Edit_Code, exit(), EXIT_FAILURE, Fclose, filename, Fprintf, INCLUDE_TEMPLATE, MAX_COL, MAX_ROW, perror, SOURCE_TEMPLATE, SpinCursor, Sprintf, Strcat, Unlink, VIS_TAB_C, VIS_TAB_H, and WRTMODE.
Referenced by do_makedefs().
{
#ifdef VISION_TABLES
    int i, j;
    /* Everything is clear. xclear may be malloc'ed.
     * Block the upper left corner (BLOCK_HEIGHTxBLOCK_WIDTH)
     */
    for (i = 0; i < MAX_ROW; i++)
    for (j = 0; j < MAX_COL; j++)
        if (i < BLOCK_HEIGHT && j < BLOCK_WIDTH)
        xclear[i][j] = '\000';
        else
        xclear[i][j] = '\001';
#endif /* VISION_TABLES */
    SpinCursor(3);
    /*
     * create the include file, "vis_tab.h"
     */
    filename[0]='\0';
#ifdef FILE_PREFIX
    Strcat(filename, file_prefix);
#endif
    Sprintf(filename, INCLUDE_TEMPLATE, VIS_TAB_H);
    if (!(ofp = fopen(filename, WRTMODE))) {
    perror(filename);
    exit(EXIT_FAILURE);
    }
    Fprintf(ofp,Dont_Edit_Code);
    Fprintf(ofp,"#ifdef VISION_TABLES\n");
#ifdef VISION_TABLES
    H_close_gen();
    H_far_gen();
#endif /* VISION_TABLES */
    Fprintf(ofp,"\n#endif /* VISION_TABLES */\n");
    Fclose(ofp);
    SpinCursor(3);
    /*
     * create the source file, "vis_tab.c"
     */
    filename[0]='\0';
#ifdef FILE_PREFIX
    Strcat(filename, file_prefix);
#endif
    Sprintf(filename, SOURCE_TEMPLATE, VIS_TAB_C);
    if (!(ofp = fopen(filename, WRTMODE))) {
    perror(filename);
    Sprintf(filename, INCLUDE_TEMPLATE, VIS_TAB_H);
    Unlink(filename);
    exit(EXIT_FAILURE);
    }
    Fprintf(ofp,Dont_Edit_Code);
    Fprintf(ofp,"#include \"config.h\"\n");
    Fprintf(ofp,"#ifdef VISION_TABLES\n");
    Fprintf(ofp,"#include \"vis_tab.h\"\n");
    SpinCursor(3);
#ifdef VISION_TABLES
    C_close_gen();
    C_far_gen();
    Fprintf(ofp,"\nvoid vis_tab_init() { return; }\n");
#endif /* VISION_TABLES */
    SpinCursor(3);
    Fprintf(ofp,"\n#endif /* VISION_TABLES */\n");
    Fprintf(ofp,"\n/*vis_tab.c*/\n");
    Fclose(ofp);
    return;
}
static char* eos (char * str) [static]
Definition at line 1823 of file makedefs.c.
Referenced by append_port_id(), build_plselection_prompt(), build_savebones_compat_string(), choose_classes_menu(), do_data(), do_date(), do_dungeon(), do_monstr(), do_objs(), do_options(), do_oracles(), do_permonst(), do_questtxt(), do_rumors(), dodiscovered(), done(), done_in_by(), FormatStatusString(), fruitadd(), getversionstring(), gnome_yn_function(), lift_object(), list_vanquished(), lookat(), main(), mswin_yn_function(), next_opt(), otransit_msg(), outentry(), outheader(), parse_config_line(), parseoptions(), set_bonesfile_name(), set_bonestemp_name(), set_levelfile_name(), split(), update_val(), use_container(), version_string(), and X11_yn_function().
{
    while (*str) str++;
    return str;
}
int FDECL (main , (int, char **))
void FDECL (do_makedefs , (char *))
static char* FDECL (version_string , (char *)) [static]
static char* FDECL (version_id_string , (char *, const char *)) [static]
static char* FDECL (xcrypt , (const char *)) [static]
static int FDECL (check_control , (char *)) [static]
static char* FDECL (without_control , (char *)) [static]
static boolean FDECL (d_filter , (char *)) [static]
static boolean FDECL (h_filter , (char *)) [static]
static boolean FDECL (ranged_attk , (struct permonst *)) [static]
static int FDECL (mstrength , (struct permonst *)) [static]
static boolean FDECL (qt_comment , (char *)) [static]
static boolean FDECL (qt_control , (char *)) [static]
static int FDECL (get_hdr , (char *)) [static]
static boolean FDECL (new_id , (char *)) [static]
static boolean FDECL (known_msg , (int, int)) [static]
static void FDECL (new_msg , (char *, int, int)) [static]
static void FDECL (do_qt_control , (char *)) [static]
static void FDECL (do_qt_text , (char *)) [static]
static char* FDECL (tmpdup , (const char *)) [static]
static char* FDECL (limit , (char *, int)) [static]
static char* FDECL (eos , (char *)) [static]
static int get_hdr (char * code) [static]
Definition at line 1448 of file makedefs.c.
References LEN_HDR, and qt_hdr.
Referenced by do_qt_control().
{
    int i;
    for(i = 0; i < qt_hdr.n_hdr; i++)
        if(!strncmp(code, qt_hdr.id[i], LEN_HDR)) return (++i);
    return(0);
}
static boolean h_filter (char * line) [static]
Definition at line 1000 of file makedefs.c.
References FALSE, in_line, SpinCursor, and TRUE.
Referenced by do_oracles().
{
    static boolean skip = FALSE;
    char tag[sizeof in_line];
    SpinCursor(3);
    if (*line == '#') return TRUE; /* ignore comment lines */
    if (sscanf(line, "----- %s", tag) == 1) {
    skip = FALSE;
#ifndef SINKS
    if (!strcmp(tag, "SINKS")) skip = TRUE;
#endif
#ifndef ELBERETH
    if (!strcmp(tag, "ELBERETH")) skip = TRUE;
#endif
    } else if (skip && !strncmp(line, "-----", 5))
    skip = FALSE;
    return skip;
}
static boolean known_msg (int num, int id) [static]
Definition at line 1475 of file makedefs.c.
References FALSE, msg_hdr, qtmsg::msgnum, and TRUE.
Referenced by do_qt_control().
{
    int i;
    for(i = 0; i < msg_hdr[num].n_msg; i++)
        if(msg_hdr[num].qt_msg[i].msgnum == id) return(TRUE);
    return(FALSE);
}
static char* limit (char	* name, int pref) [static]
Definition at line 1682 of file makedefs.c.
References temp.
Referenced by do_objs(), and init_fill().
{
    (void) strncpy(temp, name, pref ? 26 : 30);
    temp[pref ? 26 : 30] = 0;
    return temp;
}
int main (int argc, argv)
Definition at line 232 of file makedefs.c.
References do_makedefs(), exit(), EXIT_SUCCESS, and Fprintf.
{
    if ((argc != 2)
#ifdef FILE_PREFIX
        && (argc != 3)
#endif
    ) {
        Fprintf(stderr, "Bad arg count (%d).\n", argc-1);
        (void) fflush(stderr);
        return 1;
    }
#ifdef FILE_PREFIX
    if(argc >=2 && argv[1][0]!='-'){
        file_prefix=argv[1];
        argc--;argv++;
    }
#endif
    do_makedefs(&argv[1][1]);
    exit(EXIT_SUCCESS);
    /*NOTREACHED*/
    return 0;
}
static void make_version () [static]
Definition at line 424 of file makedefs.c.
References EDITLEVEL, version_info::entity_count, EXP_ON_BOTL, version_info::feature_set, ILLOBJ_CLASS, version_info::incarnation, INSURANCE, KOPS, permonst::mlet, mons, objects, objclass::oc_class, PATCHLEVEL, REINCARNATION, version_info::struct_sizes, TOURIST, version, VERSION_MAJOR, and VERSION_MINOR.
Referenced by do_makedefs().
{
    register int i;
    /*
     * integer version number
     */
    version.incarnation = ((unsigned long)VERSION_MAJOR << 24) |
                ((unsigned long)VERSION_MINOR << 16) |
                ((unsigned long)PATCHLEVEL << 8) |
                ((unsigned long)EDITLEVEL);
    /*
     * encoded feature list
     * Note: if any of these magic numbers are changed or reassigned,
     * EDITLEVEL in patchlevel.h should be incremented at the same time.
     * The actual values have no special meaning, and the category
     * groupings are just for convenience.
     */
    version.feature_set = (unsigned long)(0L
        /* levels and/or topology (0..4) */
#ifdef REINCARNATION
            | (1L << 1)
#endif
#ifdef SINKS
            | (1L << 2)
#endif
        /* monsters (5..9) */
#ifdef KOPS
            | (1L << 6)
#endif
#ifdef MAIL
            | (1L << 7)
#endif
        /* objects (10..14) */
#ifdef TOURIST
            | (1L << 10)
#endif
#ifdef STEED
            | (1L << 11)
#endif
#ifdef GOLDOBJ
            | (1L << 12)
#endif
        /* flag bits and/or other global variables (15..26) */
#ifdef TEXTCOLOR
            | (1L << 17)
#endif
#ifdef INSURANCE
            | (1L << 18)
#endif
#ifdef ELBERETH
            | (1L << 19)
#endif
#ifdef EXP_ON_BOTL
            | (1L << 20)
#endif
#ifdef SCORE_ON_BOTL
            | (1L << 21)
#endif
        /* data format [COMPRESS excluded] (27..31) */
#ifdef ZEROCOMP
            | (1L << 27)
#endif
#ifdef RLECOMP
            | (1L << 28)
#endif
            );
    /*
     * Value used for object & monster sanity check.
     * (NROFARTIFACTS<<24) | (NUM_OBJECTS<<12) | (NUMMONS<<0)
     */
    for (i = 1; artifact_names[i]; i++) continue;
    version.entity_count = (unsigned long)(i - 1);
    for (i = 1; objects[i].oc_class != ILLOBJ_CLASS; i++) continue;
    version.entity_count = (version.entity_count << 12) | (unsigned
      long)i;
    for (i = 0; mons[i].mlet; i++) continue;
    version.entity_count = (version.entity_count << 12) | (unsigned
      long)i;
    /*
     * Value used for compiler (word size/field alignment/padding) check.
     */
    version.struct_sizes = (((unsigned long)sizeof (struct
      flag) << 24) |
                ((unsigned long)sizeof (struct obj) << 17) |
                ((unsigned long)sizeof (struct monst) << 10) |
                ((unsigned long)sizeof (struct you)));
    return;
}
static int mstrength (struct permonst * ptr) [static]
Definition at line 1282 of file makedefs.c.
References AD_DRCO, AD_DRDX, AD_DRLI, AD_DRST, AD_PHYS, AD_STON, AD_WERE, AT_MAGC, AT_WEAP, G_LGROUP, G_SGROUP, M2_STRONG, permonst::mlevel, NATTK, and ranged_attk().
Referenced by do_monstr().
{
    int i, tmp2, n, tmp = ptr->mlevel;
    if(tmp > 49) /* special fixed hp monster */
        tmp = 2*(tmp - 6) / 4;
/* For creation in groups */
    n = (!!(ptr->geno & G_SGROUP));
    n += (!!(ptr->geno & G_LGROUP)) << 1;
/* For ranged attacks */
    if (ranged_attk(ptr)) n++;
/* For higher ac values */
    n += (ptr->ac < 4);
    n += (ptr->ac < 0);
/* For very fast monsters */
    n += (ptr->mmove >= 18);
/* For each attack and "special" attack */
    for(i = 0; i < NATTK; i++) {
        tmp2 = ptr->mattk[i].aatyp;
        n += (tmp2 > 0);
        n += (tmp2 == AT_MAGC);
        n += (tmp2 == AT_WEAP && (ptr->mflags2 & M2_STRONG));
    }
/* For each "special" damage type */
    for(i = 0; i < NATTK; i++) {
        tmp2 = ptr->mattk[i].adtyp;
        if ((tmp2 == AD_DRLI) || (tmp2 == AD_STON) || (tmp2 ==
      AD_DRST)
        || (tmp2 == AD_DRDX) || (tmp2 == AD_DRCO) || (tmp2 ==
      AD_WERE))
            n += 2;
        else if (strcmp(ptr->mname, "grid bug")) n += (tmp2 != AD_PHYS);
        n += ((int) (ptr->mattk[i].damd * ptr->mattk[i].damn) > 23);
    }
/* Leprechauns are special cases. They have many hit dice so they
    can hit and are hard to kill, but they don't really do much damage. */
    if (!strcmp(ptr->mname, "leprechaun")) n -= 2;
/* Finally, adjust the monster level 0 <= n <= 24 (approx.) */
    if(n == 0) tmp--;
    else if(n >= 6) tmp += (n / 2);
    else tmp += (n / 3 + 1);
    return((tmp >= 0) ? tmp : 0);
}
void NDECL (do_objs)
void NDECL (do_data)
void NDECL (do_dungeon)
void NDECL (do_date)
void NDECL (do_options)
void NDECL (do_monstr)
void NDECL (do_permonst)
void NDECL (do_questtxt)
void NDECL (do_rumors)
void NDECL (do_oracles)
void NDECL (do_vision)
void NDECL (monst_init)
void NDECL (objects_init)
static void NDECL (make_version) [static]
static void NDECL (build_savebones_compat_string) [static]
static void NDECL (adjust_qt_hdrs) [static]
static void NDECL (put_qt_hdrs) [static]
static boolean new_id (char * code) [static]
Definition at line 1460 of file makedefs.c.
References FALSE, Fprintf, LEN_HDR, msg_hdr, N_HDR, qt_hdr, and TRUE.
Referenced by do_qt_control().
{
    if(qt_hdr.n_hdr >= N_HDR) {
        Fprintf(stderr, OUT_OF_HEADERS, qt_line);
        return(FALSE);
    }
    strncpy(&qt_hdr.id[qt_hdr.n_hdr][0], code, LEN_HDR);
    msg_hdr[qt_hdr.n_hdr].n_msg = 0;
    qt_hdr.offset[qt_hdr.n_hdr++] = 0L;
    return(TRUE);
}
static void new_msg (char * s, int num, int id) [static]
Definition at line 1488 of file makedefs.c.
References qtmsg::delivery, Fprintf, msg_hdr, qtmsg::msgnum, qtmsg::offset, and qtmsg::size.
Referenced by do_qt_control().
{
    struct qtmsg *qt_msg;
    if(msg_hdr[num].n_msg >= N_MSG) {
        Fprintf(stderr, OUT_OF_MESSAGES, qt_line);
    } else {
        qt_msg = &(msg_hdr[num].qt_msg[msg_hdr[num].n_msg++]);
        qt_msg->msgnum = id;
        qt_msg->delivery = s[2];
        qt_msg->offset = qt_msg->size = 0L;
        curr_msg = qt_msg;
    }
}
static void put_qt_hdrs () [static]
Definition at line 1578 of file makedefs.c.
References Fprintf, LEN_HDR, msg_hdr, qtmsg::msgnum, offset, ofp, and qt_hdr.
Referenced by do_questtxt().
{
    int i;
    /*
     * The main header record.
     */
#ifdef DEBUG
    Fprintf(stderr, "%ld: header info.\n", ftell(ofp));
#endif
    (void) fwrite((genericptr_t)&(qt_hdr.n_hdr), sizeof(int), 1,
      ofp);
    (void) fwrite((genericptr_t)&(qt_hdr.id[0][0]), sizeof(char)*
      LEN_HDR,
                            qt_hdr.n_hdr, ofp);
    (void) fwrite((genericptr_t)&(qt_hdr.offset[0]), sizeof(long),
                            qt_hdr.n_hdr, ofp);
#ifdef DEBUG
    for(i = 0; i < qt_hdr.n_hdr; i++)
        Fprintf(stderr, "%c @ %ld, ", qt_hdr.id[i], qt_hdr.offset[i]);
    Fprintf(stderr, "\n");
#endif
    /*
     * The individual class headers.
     */
    for(i = 0; i < qt_hdr.n_hdr; i++) {
#ifdef DEBUG
        Fprintf(stderr, "%ld: %c header info.\n", ftell(ofp),
            qt_hdr.id[i]);
#endif
        (void) fwrite((genericptr_t)&(msg_hdr[i].n_msg), sizeof(int),
                            1, ofp);
        (void) fwrite((genericptr_t)&(msg_hdr[i].qt_msg[0]),
                sizeof(struct qtmsg), msg_hdr[i].n_msg, ofp);
#ifdef DEBUG
        { int j;
          for(j = 0; j < msg_hdr[i].n_msg; j++)
        Fprintf(stderr, "msg %d @ %ld (%ld)\n",
            msg_hdr[i].qt_msg[j].msgnum,
            msg_hdr[i].qt_msg[j].offset,
            msg_hdr[i].qt_msg[j].size);
        }
#endif
    }
}
static boolean qt_comment (char * s) [static]
Definition at line 1433 of file makedefs.c.
References NO_MSG, and TRUE.
Referenced by do_questtxt().
{
    if(s[0] == '#') return(TRUE);
    return((boolean)(!in_msg && strlen(s) == NO_MSG));
}
static boolean qt_control (char * s) [static]
Definition at line 1441 of file makedefs.c.
Referenced by do_questtxt().
{
    return((boolean)(s[0] == '%' && (s[1] == 'C' || s[1] == 'E')));
}
static boolean ranged_attk (struct permonst * ptr) [static]
Definition at line 1263 of file makedefs.c.
References AT_BREA, AT_GAZE, AT_SPIT, AT_WEAP, FALSE, NATTK, and TRUE.
Referenced by mstrength().
{
    register int i, j;
    register int atk_mask = (1<<AT_BREA) | (1<<AT_SPIT) | (1<<
      AT_GAZE);
    for(i = 0; i < NATTK; i++) {
        if((j=ptr->mattk[i].aatyp) >= AT_WEAP || (atk_mask & (1<<j)))
        return TRUE;
    }
    return(FALSE);
}
static char* tmpdup (char * str) const [static]
Definition at line 1812 of file makedefs.c.
References buf.
Referenced by do_objs(), and do_permonst().
{
    static char buf[128];
    if (!str) return (char *)0;
    (void)strncpy(buf, str, 127);
    return buf;
}
static char* version_id_string (char * outbuf, const char * build_date) [static]
Definition at line 523 of file makedefs.c.
References PORT_ID, Sprintf, Strcat, Strcpy, and version_string().
Referenced by do_date().
{
    char subbuf[64], versbuf[64];
    subbuf[0] = '\0';
#ifdef PORT_SUB_ID
    subbuf[0] = ' ';
    Strcpy(&subbuf[1], PORT_SUB_ID);
#endif
#ifdef BETA
    Strcat(subbuf, " Beta");
#endif
    Sprintf(outbuf, "%s NetHack%s Version %s - last build %s.",
        PORT_ID, subbuf, version_string(versbuf), build_date);
    return outbuf;
}
static char* version_string (char * outbuf) [static]
Definition at line 512 of file makedefs.c.
References EDITLEVEL, eos(), PATCHLEVEL, Sprintf, VERSION_MAJOR, and VERSION_MINOR.
Referenced by do_date(), and version_id_string().
{
    Sprintf(outbuf, "%d.%d.%d", VERSION_MAJOR, VERSION_MINOR,
      PATCHLEVEL);
#ifdef BETA
    Sprintf(eos(outbuf), "-%d", EDITLEVEL);
#endif
    return outbuf;
}
static char* without_control (char * s) [static]
Definition at line 1207 of file makedefs.c.
References check_control(), and in_line.
Referenced by do_dungeon().
{
    return(s + 1 + strlen(deflist[check_control(in_line)].defname));
}
static char* xcrypt (char * str) const [static]
Definition at line 329 of file makedefs.c.
References buf, and BUFSZ.
Referenced by convert_line(), do_oracles(), do_questtxt(), do_rumors(), getrumor(), and outoracle().
{ /* duplicated in src/hacklib.c */
    static char buf[BUFSZ];
    register const char *p;
    register char *q;
    register int bitmask;
    for (bitmask = 1, p = str, q = buf; *p; q++) {
        *q = *p++;
        if (*q & (32|64)) *q ^= bitmask;
        if ((bitmask <<= 1) >= 32) bitmask = 1;
    }
    *q = '\0';
    return buf;
}
Variable Documentation
const char* build_opts[] [static]
Definition at line 630 of file makedefs.c.
struct qtmsg* curr_msg [static]
Definition at line 1425 of file makedefs.c.
struct deflist deflist[] [static]
Initial value:
= {
          { "REINCARNATION", FALSE },
          { 0, 0 } }
const char* Dont_Edit_Code [static]
Initial value:
=
    "/* This source file is generated by 'makedefs'. Do not edit. */\n"
Definition at line 110 of file makedefs.c.
Referenced by do_date(), do_monstr(), do_objs(), do_permonst(), and do_vision().
const char * Dont_Edit_Data [static]
Initial value:
=
    "#\tThis data file is generated by 'makedefs'. Do not edit. \n"
Definition at line 112 of file makedefs.c.
Referenced by do_data(), do_dungeon(), do_oracles(), and do_rumors().
char filename[60] [static]
Definition at line 134 of file makedefs.c.
Referenced by do_data(), do_date(), do_dungeon(), do_monstr(), do_objs(), do_options(), do_oracles(), do_permonst(), do_questtxt(), do_rumors(), do_vision(), fopen_config_file(), fopen_text_file(), main(), and validate_prefix_locations().
FILE* ifp [static]
Definition at line 200 of file makedefs.c.
char in_line[256] [static]
Definition at line 134 of file makedefs.c.
Referenced by do_data(), do_dungeon(), do_oracles(), do_questtxt(), do_rumors(), h_filter(), and without_control().
boolean in_msg [static]
Definition at line 1429 of file makedefs.c.
struct msghdr msg_hdr[N_HDR] [static]
Definition at line 1424 of file makedefs.c.
Referenced by adjust_qt_hdrs(), known_msg(), new_id(), new_msg(), and put_qt_hdrs().
FILE * ofp [static]
Definition at line 200 of file makedefs.c.
Referenced by do_questtxt(), do_rumors(), main(), and put_qt_hdrs().
struct qthdr qt_hdr [static]
Definition at line 1423 of file makedefs.c.
Referenced by adjust_qt_hdrs(), do_questtxt(), get_hdr(), new_id(), and put_qt_hdrs().
int qt_line [static]
Definition at line 1427 of file makedefs.c.
char save_bones_compat_buf[BUFSZ] [static]
Definition at line 609 of file makedefs.c.
const char* special_oracle[] [static]
Initial value:
= {
    "\"...it is rather disconcerting to be confronted with the",
    "following theorem from [Baker, Gill, and Solovay, 1975].",
    "",
    "Theorem 7.18 There exist recursive languages A and B such that",
    " (1) P(A) == NP(A), and",
    " (2) P(B) != NP(B)",
    "",
    "This provides impressive evidence that the techniques that are",
    "currently available will not suffice for proving that P != NP or ",
    "that P == NP.\" [Garey and Johnson, p. 185.]"
}
Definition at line 1022 of file makedefs.c.
char temp[32] [static]
Definition at line 1679 of file makedefs.c.
Referenced by food_detect(), fopen_xpm_file(), gold_detect(), limit(), o_in(), o_material(), rest_worm(), and save_worm().
FILE * tfp [static]
Definition at line 200 of file makedefs.c.
Referenced by do_oracles().
struct version_info version [static]
Definition at line 115 of file makedefs.c.
Referenced by do_date(), make_version(), and read_header().
const char* window_opts[] [static]
Initial value:
= {
        0
    }
Definition at line 781 of file makedefs.c.