nethack/sys/mac/mgetline.c File Reference
#include `hack.h`
*
#include `mactty.h`
*
#include `macwin.h`
*
#include `macpopup.h`
*
#include `func_tab.h`
*
Typedefs
typedef Boolean FDECL ((*key_func),(unsigned char))
Functions
int NDECL (extcmd_via_menu)
int get_line_from_key_queue (char *bufp)
static void topl_getlin (const char *query, char *bufp, Boolean ext)
void mac_getlin (const char *query, char *bufp)
int mac_get_ext_cmd ()
Typedef Documentation
typedef Boolean FDECL((*key_func),(unsigned char))
Definition at line 13 of file mgetline.c.
Function Documentation
int get_line_from_key_queue (char * bufp)
Definition at line 16 of file mgetline.c.
References try_key_queue().
Referenced by topl_getlin().
                                      {
    * bufp = 0;
    if (try_key_queue (bufp)) {
        while (* bufp) {
            if (* bufp == 10 || * bufp == 13) {
                * bufp = 0;
            }
            bufp ++;
        }
        return true;
    }
    return false;
}
int mac_get_ext_cmd ()
Definition at line 60 of file mgetline.c.
References BUFSZ, ext_func_tab::ef_txt, extcmdlist, iflags, and topl_getlin().
                  {
    char bufp[BUFSZ];
    int i;
    if (iflags.extmenu) return extcmd_via_menu();
    topl_getlin("# ", bufp, true);
    for (i = 0; extcmdlist[i].ef_txt != (char *)0; i++)
        if (!strcmp(bufp, extcmdlist[i].ef_txt)) break;
    if (extcmdlist[i].ef_txt == (char *)0) i = -1; /* not found */
    return i;
}
void mac_getlin (const char * query, char * bufp)
Definition at line 50 of file mgetline.c.
References topl_getlin().
                                          {
    topl_getlin (query, bufp, false);
}
int NDECL (extcmd_via_menu)
static void topl_getlin (const char * query, char * bufp, Boolean ext) [static]
Definition at line 32 of file mgetline.c.
References enter_topl_mode(), get_line_from_key_queue(), leave_topl_mode(), nhgetch, and topl_key().
Referenced by mac_get_ext_cmd(), and mac_getlin().
                                                        {
    if (get_line_from_key_queue (bufp))
        return;
    enter_topl_mode((char *) query);
    while (topl_key(nhgetch(), ext))
        ;
    leave_topl_mode(bufp);
}