nethack/sys/wince/mhcmd.c File Reference
#include `winMS.h`
*
#include <assert.h>
*
#include `mhcmd.h`
*
#include `mhinput.h`
*
#include `mhcolor.h`
*
Data Structures
struct t_NHCmdPadCell
struct t_NHCmdLayout
struct t_NHCmdSet
struct t_NHCmdSet::t_NHCmdSetElem
struct t_NHCmdPadLayoutCell
struct mswin_nethack_cmd_window
Macros
#define C(c) (0x1f & (c))
#define NH_CST_CHECKED 1
#define NH_CMDPAD_FONT_NORMAL 0
#define NH_CMDPAD_FONT_MAX 0
#define NH_CELL_REG 0
#define NH_CELL_CTRL 1
#define NH_CELL_CAP 2
#define NH_CELL_SHIFT 3
#define NH_CELL_LAYOUT_NEW 4
#define NH_CELL_LAYOUT_MENU 5
#define NH_CMDSET_MAXSIZE 64
#define nhcmdlayout_rows(p) ((p)->rows)
#define nhcmdlayout_columns(p) ((p)->columns)
#define nhcmdlayout_row(p, x) (&((p)->cells[(p)->columns*(x)]))
#define nhcmdlayout_cell(p, x, y) (&((p)->cells[(p)->columns*(x)+(y)]))
#define nhcmdlayout_cell_direct(p, i) (&((p)->cells[(i)]))
#define NH_CMDPAD_ROWS 4
#define NH_CMDPAD_COLS 14
#define NH_CMDPAD_CELLNUM (NH_CMDPAD_COLS*NH_CMDPAD_ROWS)
Typedefs
typedef struct t_NHCmdPadCell NHCmdPadCell
typedef struct t_NHCmdPadCell * PNHCmdPadCell
typedef struct t_NHCmdLayout NHCmdLayout
typedef struct t_NHCmdLayout * PNHCmdLayout
typedef struct t_NHCmdSet NHCmdSet
typedef struct t_NHCmdSet * PNHCmdSet
typedef struct t_NHCmdPadLayoutCell NHCmdPadLayoutCell
typedef struct
*
t_NHCmdPadLayoutCell * PNHCmdPadLayoutCell
typedef struct
*
mswin_nethack_cmd_window NHCmdWindow
typedef struct
*
mswin_nethack_cmd_window * PNHCmdWindow
Functions
LRESULT CALLBACK NHCommandWndProc (HWND, UINT, WPARAM, LPARAM)
static void register_command_window_class ()
static void LayoutCmdWindow (HWND hWnd)
static void SetCmdWindowLayout (HWND hWnd, PNHCmdLayout layout)
static int CellFromPoint (PNHCmdWindow data, POINT pt)
static void CalculateCellSize (HWND hWnd, LPSIZE pSize, LPSIZE windowSize)
static void HighlightCell (HWND hWnd, int cell, BOOL isSelected)
static void ActivateCell (HWND hWnd, int cell)
static void PushNethackCommand (const char *cmd_char_str, int is_ctrl)
PNHCmdLayout nhcmdlayout_create (const char *name, int rows, int columns)
void nhcmdlayout_init (PNHCmdLayout p, PNHCmdPadCell cells)
void nhcmdlayout_destroy (PNHCmdLayout p)
PNHCmdSet nhcmdset_create ()
int nhcmdset_count (PNHCmdSet p)
PNHCmdLayout nhcmdset_get (PNHCmdSet p, int index)
const char * nhcmdset_get_name (PNHCmdSet p, int index)
void nhcmdset_add (PNHCmdSet p, PNHCmdLayout layout)
void nhcmdset_destroy (PNHCmdSet p)
static void onPaint (HWND hWnd)
static void onCreate (HWND hWnd, WPARAM wParam, LPARAM lParam)
static void onMouseDown (HWND hWnd, WPARAM wParam, LPARAM lParam)
static void onMouseMove (HWND hWnd, WPARAM wParam, LPARAM lParam)
static void onMouseUp (HWND hWnd, WPARAM wParam, LPARAM lParam)
HWND mswin_init_command_window ()
void mswin_command_window_size (HWND hwnd, LPSIZE sz)
Variables
static TCHAR szNHCmdWindowClass [] = TEXT(`MSNethackCmdWndClass`)
static PNHCmdSet nhcmdset_current = 0
static PNHCmdSet nhcmdset_default = 0
NHCmdPadCell cells_layout_mod1 [NH_CMDPAD_ROWS *NH_CMDPAD_COLS]
NHCmdPadCell cells_layout_mod2 [-NH_CMDPAD_ROWS *-NH_CMDPAD_COLS]
Macro Definition Documentation
#define C(c) (0x1f & (c))
Definition at line 12 of file mhcmd.c.
Referenced by PushNethackCommand().
#define NH_CELL_CAP 2
Definition at line 25 of file mhcmd.c.
Referenced by ActivateCell(), LayoutCmdWindow(), and onMouseMove().
#define NH_CELL_CTRL 1
Definition at line 24 of file mhcmd.c.
Referenced by ActivateCell(), LayoutCmdWindow(), and onMouseMove().
#define NH_CELL_LAYOUT_MENU 5
Definition at line 28 of file mhcmd.c.
Referenced by ActivateCell().
#define NH_CELL_LAYOUT_NEW 4
Definition at line 27 of file mhcmd.c.
Referenced by ActivateCell().
#define NH_CELL_REG 0
Definition at line 23 of file mhcmd.c.
#define NH_CELL_SHIFT 3
Definition at line 26 of file mhcmd.c.
Referenced by ActivateCell(), and LayoutCmdWindow().
#define NH_CMDPAD_CELLNUM (NH_CMDPAD_COLS*NH_CMDPAD_ROWS)
Definition at line 283 of file mhcmd.c.
#define NH_CMDPAD_COLS 14
Definition at line 282 of file mhcmd.c.
Referenced by register_command_window_class().
#define NH_CMDPAD_FONT_MAX 0
Definition at line 20 of file mhcmd.c.
Referenced by LayoutCmdWindow(), and NHCommandWndProc().
#define NH_CMDPAD_FONT_NORMAL 0
Definition at line 19 of file mhcmd.c.
Referenced by LayoutCmdWindow(), nhcmdlayout_create(), and onPaint().
#define NH_CMDPAD_ROWS 4
Definition at line 281 of file mhcmd.c.
Referenced by register_command_window_class().
#define NH_CMDSET_MAXSIZE 64
Definition at line 30 of file mhcmd.c.
Referenced by nhcmdset_add().
#define NH_CST_CHECKED 1
Definition at line 16 of file mhcmd.c.
Referenced by ActivateCell(), HighlightCell(), LayoutCmdWindow(), onMouseDown(), and onPaint().
#define nhcmdlayout_cell(p, x, y) (&((p)->cells[(p)->columns*(x)+(y)]))
Definition at line 120 of file mhcmd.c.
#define nhcmdlayout_cell_direct(p, i) (&((p)->cells[(i)]))
Definition at line 121 of file mhcmd.c.
Referenced by ActivateCell(), CellFromPoint(), HighlightCell(), LayoutCmdWindow(), onMouseMove(), and onPaint().
#define nhcmdlayout_columns(p) ((p)->columns)
Definition at line 118 of file mhcmd.c.
Referenced by ActivateCell(), CalculateCellSize(), CellFromPoint(), LayoutCmdWindow(), mswin_command_window_size(), onPaint(), and SetCmdWindowLayout().
#define nhcmdlayout_row(p, x) (&((p)->cells[(p)->columns*(x)]))
Definition at line 119 of file mhcmd.c.
#define nhcmdlayout_rows(p) ((p)->rows)
Definition at line 117 of file mhcmd.c.
Referenced by ActivateCell(), CalculateCellSize(), CellFromPoint(), LayoutCmdWindow(), mswin_command_window_size(), onPaint(), and SetCmdWindowLayout().
Typedef Documentation
typedef struct t_NHCmdLayout NHCmdLayout
typedef struct t_NHCmdPadCell NHCmdPadCell
typedef struct t_NHCmdPadLayoutCell NHCmdPadLayoutCell
typedef struct t_NHCmdSet NHCmdSet
typedef struct mswin_nethack_cmd_window NHCmdWindow
typedef struct t_NHCmdLayout * PNHCmdLayout
typedef struct t_NHCmdPadCell * PNHCmdPadCell
typedef struct t_NHCmdPadLayoutCell * PNHCmdPadLayoutCell
typedef struct t_NHCmdSet * PNHCmdSet
typedef struct mswin_nethack_cmd_window * PNHCmdWindow
Function Documentation
void ActivateCell (HWND hWnd, int cell) [static]
Definition at line 902 of file mhcmd.c.
References any::a_void, ATR_NONE, mswin_nethack_cmd_window::cells, t_NHCmdPadCell::data, t_NHCmdPadCell::f_char, FALSE, HighlightCell(), mswin_nethack_cmd_window::is_caps, mswin_nethack_cmd_window::is_ctrl, mswin_nethack_cmd_window::is_shift, mi::item, mswin_nethack_cmd_window::layout_current, mswin_nethack_cmd_window::layout_save, mswin_add_menu(), mswin_create_nhwindow(), mswin_destroy_nhwindow(), mswin_end_menu(), mswin_start_menu(), NH_CELL_CAP, NH_CELL_CTRL, NH_CELL_LAYOUT_MENU, NH_CELL_LAYOUT_NEW, NH_CELL_SHIFT, NH_CST_CHECKED, nhcmdlayout_cell_direct, nhcmdlayout_columns, nhcmdlayout_rows, nhcmdset_count(), nhcmdset_default, nhcmdset_get(), nhcmdset_get_name(), NHW_MENU, NO_GLYPH, NULL, PICK_ONE, PushNethackCommand(), select_menu, SetCmdWindowLayout(), t_NHCmdPadLayoutCell::state, TRUE, and t_NHCmdPadCell::type.
Referenced by onMouseUp().
{
    PNHCmdWindow data;
    PNHCmdPadCell p_cell_data;
    int i;
    data = (PNHCmdWindow)GetWindowLong(hWnd, GWL_USERDATA);
    if(!data) return;
    p_cell_data = nhcmdlayout_cell_direct(data->
      layout_current, cell);
    /* act depending on the cell type:
        CAPS - change layout
        CTRL - modify CTRL status
        REG - place keyboard event on the nethack input queue
    */
    switch(p_cell_data->type) {
    case NH_CELL_REG:
        if(data->is_ctrl) {
            PushNethackCommand(p_cell_data->f_char, 1);
            data->is_ctrl = 0;
            for(i=0; i<nhcmdlayout_rows(data->layout_current)*
      nhcmdlayout_columns(data->layout_current); i++) {
                if(nhcmdlayout_cell_direct(data->
      layout_current, i)->type == NH_CELL_CTRL) {
                    HighlightCell(hWnd, i, data->is_ctrl);
                }
            }
        } else {
            PushNethackCommand(p_cell_data->f_char, 0);
        }
        HighlightCell(hWnd, cell, FALSE);
        // select a new layout if present
        i = (int)p_cell_data->data;
        if(i==-1) {
            if(data->layout_save) SetCmdWindowLayout(hWnd, data->
      layout_save);
            data->layout_save = NULL;
        } else {
            if(!data->layout_save) data->layout_save = data->
      layout_current;
            SetCmdWindowLayout(hWnd, nhcmdset_get(
      nhcmdset_current, i));
        }
        if(!data->is_shift) break;
        // else fall through and reset the shift
    case NH_CELL_SHIFT:
        data->is_shift = !data->is_shift;
        SetCmdWindowLayout(
            hWnd,
            (data->is_shift ^ data->is_caps)? nhcmdset_get(
      nhcmdset_current, 1) : nhcmdset_get(nhcmdset_current, 0)
        );
        data->cells[cell].state = data->is_shift?
      NH_CST_CHECKED : 0;
        InvalidateRect(hWnd, NULL, TRUE);
        break;
    case NH_CELL_CTRL:
        data->is_ctrl = !data->is_ctrl;
        HighlightCell(hWnd, cell, data->is_ctrl);
        break;
    case NH_CELL_CAP:
        data->is_caps = !data->is_caps;
        SetCmdWindowLayout(
            hWnd,
            (data->is_shift ^ data->is_caps)? nhcmdset_get(
      nhcmdset_current, 1) : nhcmdset_get(nhcmdset_current, 0)
        );
        data->cells[cell].state = data->is_caps? NH_CST_CHECKED : 0;
        InvalidateRect(hWnd, NULL, TRUE);
        break;
    case NH_CELL_LAYOUT_NEW: {
        PNHCmdLayout pLayout;
        HighlightCell(hWnd, cell, FALSE);
        pLayout = (PNHCmdLayout)p_cell_data->data;
        if(pLayout) {
            SetCmdWindowLayout(hWnd, pLayout);
        }
    } break;
    
    case NH_CELL_LAYOUT_MENU: {
        winid wid;
        int i;
        anything any;
        menu_item* selected = 0;
        PNHCmdSet pSet;
        HighlightCell(hWnd, cell, FALSE);
        pSet = (PNHCmdSet)p_cell_data->data;
        if(!pSet) pSet = nhcmdset_default;
        wid = mswin_create_nhwindow(NHW_MENU);
        mswin_start_menu(wid);
        for(i=0; i<nhcmdset_count(pSet); i++) {
            any.a_void = nhcmdset_get(pSet, i);
            mswin_add_menu(wid, NO_GLYPH, &any, 'a'+i, 0,
      ATR_NONE,
                nhcmdset_get_name(pSet, i), FALSE);
        }
        mswin_end_menu(wid, "Select keypad layout");
        i = select_menu(wid, PICK_ONE, &selected);
        mswin_destroy_nhwindow(wid);
        if(i==1) {
#if defined(WIN_CE_SMARTPHONE)
            data->layout_selected = (PNHCmdLayout)selected[0].item.a_void;
#endif
            SetCmdWindowLayout(hWnd, (PNHCmdLayout)selected[0].
      item.a_void);
        }
    } break;
    
    }
}
void CalculateCellSize (HWND hWnd, LPSIZE pSize, LPSIZE windowSize) [static]
Definition at line 1030 of file mhcmd.c.
References mswin_nethack_cmd_window::layout_current, min, nhcmdlayout_columns, and nhcmdlayout_rows.
Referenced by LayoutCmdWindow(), and mswin_command_window_size().
{
    HDC hdc;
    PNHCmdWindow data;
    data = (PNHCmdWindow)GetWindowLong(hWnd, GWL_USERDATA);
    if(!data) return;
    hdc = GetDC(hWnd);
    
    /* if windows size is specified - attempt ro stretch cells across
       the the window size. If not - make default cell size based on
       10 points font. Make sure that cell cesize does not exceeds 20 points */
    if(pWindowSize->cx>0)
        pSize->cx = pWindowSize->cx/nhcmdlayout_columns(data->
      layout_current);
    else
        pSize->cx = 10*GetDeviceCaps(hdc, LOGPIXELSX)/72;
    pSize->cx = min(pSize->cx, 20*GetDeviceCaps(hdc, LOGPIXELSX)/72);
    if(pWindowSize->cy>0)
        pSize->cy = pWindowSize->cy/nhcmdlayout_rows(data->
      layout_current);
    else
        pSize->cy = 10*GetDeviceCaps(hdc, LOGPIXELSY)/72;
    pSize->cy = min(pSize->cy, 20*GetDeviceCaps(hdc, LOGPIXELSY)/72);
    ReleaseDC(hWnd, hdc);
}
int CellFromPoint (PNHCmdWindow data, POINT pt) [static]
Definition at line 1016 of file mhcmd.c.
References mswin_nethack_cmd_window::cell_size, mswin_nethack_cmd_window::cells, mswin_nethack_cmd_window::layout_current, nhcmdlayout_cell_direct, nhcmdlayout_columns, nhcmdlayout_rows, and t_NHCmdPadLayoutCell::orig.
Referenced by onMouseDown(), and onMouseMove().
{
    int i;
    for(i=0; i<nhcmdlayout_rows(data->layout_current)*
      nhcmdlayout_columns(data->layout_current); i++) {
        RECT cell_rt;
        cell_rt.left = data->cells[i].orig.x;
        cell_rt.top = data->cells[i].orig.y;
        cell_rt.right = data->cells[i].orig.x + data->cell_size.cx*
      nhcmdlayout_cell_direct(data->layout_current, i)->mult;
        cell_rt.bottom = data->cells[i].orig.y + data->cell_size.cy;
        if(PtInRect(&cell_rt, pt)) return i;
    }
    return -1;
}
void HighlightCell (HWND hWnd, int cell, BOOL isSelected) [static]
Definition at line 1057 of file mhcmd.c.
References mswin_nethack_cmd_window::cell_size, mswin_nethack_cmd_window::cells, mswin_nethack_cmd_window::layout_current, NH_CST_CHECKED, nhcmdlayout_cell_direct, t_NHCmdPadLayoutCell::orig, and t_NHCmdPadLayoutCell::state.
Referenced by ActivateCell(), onMouseDown(), and onMouseMove().
{
    HDC hDC;
    PNHCmdWindow data;
    int prevState;
    data = (PNHCmdWindow)GetWindowLong(hWnd, GWL_USERDATA);
    prevState = data->cells[cell].state;
    data->cells[cell].state = (isSelected)? NH_CST_CHECKED : 0;
    if(prevState!=data->cells[cell].state) {
        hDC = GetDC(hWnd);
        PatBlt(hDC,
            data->cells[cell].orig.x+1,
            data->cells[cell].orig.y+1,
            data->cell_size.cx*nhcmdlayout_cell_direct(data->
      layout_current, cell)->mult - 2,
            data->cell_size.cy - 2,
            DSTINVERT
            );
        ReleaseDC(hWnd, hDC);
    }
}
void LayoutCmdWindow (HWND hWnd) [static]
Definition at line 736 of file mhcmd.c.
References CalculateCellSize(), mswin_nethack_cmd_window::cell_size, mswin_nethack_cmd_window::cells, FALSE, mswin_nethack_cmd_window::font, iflags, index(), mswin_nethack_cmd_window::is_caps, mswin_nethack_cmd_window::is_ctrl, mswin_nethack_cmd_window::is_shift, mswin_nethack_cmd_window::layout_current, NH_A2W, NH_CELL_CAP, NH_CELL_CTRL, NH_CELL_SHIFT, NH_CMDPAD_FONT_MAX, NH_CMDPAD_FONT_NORMAL, NH_CST_CHECKED, nhcmdlayout_cell_direct, nhcmdlayout_columns, nhcmdlayout_rows, NULL, t_NHCmdPadLayoutCell::orig, SIZE, t_NHCmdPadLayoutCell::state, TRUE, t_NHCmdPadLayoutCell::type, and instance_flags::wc_font_message.
Referenced by NHCommandWndProc(), and SetCmdWindowLayout().
{
    RECT clrt;
    SIZE windowSize;
    PNHCmdWindow data;
    int i, j;
    int x, y;
    LOGFONT lgfnt;
    int index;
    GetClientRect(hWnd, &clrt);
    if(IsRectEmpty(&clrt)) return;
    data = (PNHCmdWindow)GetWindowLong(hWnd, GWL_USERDATA);
    if(!data->layout_current) return;
    /* calculate cell size */
    windowSize.cx = clrt.right-clrt.left;
    windowSize.cy = clrt.bottom-clrt.top;
    CalculateCellSize(hWnd, &data->cell_size, &windowSize);
     
    /* initialize display cells aray */
    x = 0;
    y = 0;
    for(i=0, index=0; i<nhcmdlayout_rows(data->layout_current); i++) {
        for(j=0; j<nhcmdlayout_columns(data->layout_current); j++, index+
      +) {
            data->cells[index].orig.x = x;
            data->cells[index].orig.y = y;
            data->cells[index].type = nhcmdlayout_cell_direct(data->
      layout_current, index)->type;
            switch(data->cells[index].type) {
            case NH_CELL_CTRL:
                data->cells[index].state = data->is_ctrl?
      NH_CST_CHECKED : 0;
                break;
            case NH_CELL_CAP:
                data->cells[index].state = data->is_caps?
      NH_CST_CHECKED : 0;
                break;
            case NH_CELL_SHIFT:
                data->cells[index].state = data->is_shift?
      NH_CST_CHECKED : 0;
                break;
            default:
                data->cells[index].state = 0;
            }
            x += data->cell_size.cx * nhcmdlayout_cell_direct(data->
      layout_current, index)->mult;
        }
        x = 0;
        y += data->cell_size.cy;
    }
    /* create font for display cell text */
    for(i=0; i<=NH_CMDPAD_FONT_MAX; i++)
        if(data->font[i]) DeleteObject(data->font[i]);
    ZeroMemory(&lgfnt, sizeof(lgfnt));
    lgfnt.lfHeight = data->cell_size.cy; // height of font
    lgfnt.lfWidth = 0; // average character width
    lgfnt.lfEscapement = 0; // angle of escapement
    lgfnt.lfOrientation = 0; // base-line orientation angle
    lgfnt.lfWeight = FW_NORMAL; // font weight
    lgfnt.lfItalic = FALSE; // italic attribute option
    lgfnt.lfUnderline = FALSE; // underline attribute option
    lgfnt.lfStrikeOut = FALSE; // strikeout attribute option
    lgfnt.lfCharSet = ANSI_CHARSET; // character set identifier
    lgfnt.lfOutPrecision = OUT_DEFAULT_PRECIS; // output precision
    lgfnt.lfClipPrecision = CLIP_CHARACTER_PRECIS; // clipping precision
    lgfnt.lfQuality = DEFAULT_QUALITY; // output quality
    if(iflags.wc_font_message &&
        *iflags.wc_font_message) {
        lgfnt.lfPitchAndFamily = DEFAULT_PITCH; // pitch and family
        NH_A2W(iflags.wc_font_message, lgfnt.lfFaceName, LF_FACESIZE);
    } else {
        lgfnt.lfPitchAndFamily = VARIABLE_PITCH; // pitch and family
    }
    data->font[NH_CMDPAD_FONT_NORMAL] = CreateFontIndirect(&lgfnt);
    InvalidateRect(hWnd, NULL, TRUE);
}
void mswin_command_window_size (HWND hwnd, LPSIZE sz)
Definition at line 446 of file mhcmd.c.
References CalculateCellSize(), mswin_nethack_cmd_window::layout_current, max, nhcmdlayout_columns, nhcmdlayout_rows, and SIZE.
Referenced by mswin_layout_main_window().
{
    SIZE cell_size;
    PNHCmdWindow data;
    data = (PNHCmdWindow)GetWindowLong(hwnd, GWL_USERDATA);
    if(!data) {
        sz->cx = sz->cy = 0;
    } else {
        CalculateCellSize(hwnd, &cell_size, sz);
        sz->cx = max(
                    cell_size.cx*nhcmdlayout_columns(data->
      layout_current)+2*GetSystemMetrics(SM_CXBORDER),
                    sz->cx
                    );
        sz->cy = max(
                    cell_size.cy*nhcmdlayout_rows(data->
      layout_current)+2*GetSystemMetrics(SM_CYBORDER),
                    sz->cy
                    );
    }
}
HWND mswin_init_command_window ()
Definition at line 416 of file mhcmd.c.
References GetNHApp(), NULL, panic(), register_command_window_class(), and szNHCmdWindowClass.
Referenced by MainWndProc().
                                  {
    static int run_once = 0;
    HWND ret;
    /* register window class */
    if(!run_once) {
        register_command_window_class();
        run_once = 1;
    }
    /* create window */
    ret = CreateWindow(
            szNHCmdWindowClass, /* registered class name */
            NULL, /* window name */
            WS_CHILD | WS_CLIPSIBLINGS, /* window style */
            0, /* horizontal position of window - set it later */
            0, /* vertical position of window - set it later */
            0, /* window width - set it later */
            0, /* window height - set it later*/
            GetNHApp()->hMainWnd, /* handle to parent or owner window */
            NULL, /* menu handle or child identifier */
            GetNHApp()->hApp, /* handle to application instance */
            NULL); /* window-creation data */
    if(!ret) {
        panic("Cannot create command window");
    }
    return ret;
}
PNHCmdLayout nhcmdlayout_create (const char * name, int rows, int columns)
Definition at line 1092 of file mhcmd.c.
References t_NHCmdLayout::cells, t_NHCmdPadCell::cmd_code, t_NHCmdLayout::columns, t_NHCmdPadCell::image, malloc(), t_NHCmdPadCell::mult, t_NHCmdLayout::name, NH_CMDPAD_FONT_NORMAL, t_NHCmdLayout::rows, and t_NHCmdPadCell::type.
Referenced by register_command_window_class().
{
    PNHCmdLayout p;
    int i;
    i = sizeof(NHCmdLayout)+rows*columns*sizeof(NHCmdPadCell);
    p = (PNHCmdLayout)malloc(i);
    ZeroMemory(p, i);
    p->rows = rows;
    p->columns = columns;
    strncpy(p->name, name, sizeof(p->name)-1);
    for(i=0; i<rows*columns; i++) {
        p->cells[i].cmd_code = -1;
        p->cells[i].image = -NH_CMDPAD_FONT_NORMAL;
        p->cells[i].type = 1;
        p->cells[i].mult = 1;
    }
    return p;
}
void nhcmdlayout_destroy (PNHCmdLayout p)
Definition at line 1117 of file mhcmd.c.
References free().
Referenced by nhcmdset_destroy().
{
    free(p);
}
void nhcmdlayout_init (PNHCmdLayout p, PNHCmdPadCell cells)
Definition at line 1112 of file mhcmd.c.
References t_NHCmdLayout::cells, t_NHCmdLayout::columns, and t_NHCmdLayout::rows.
Referenced by register_command_window_class().
{
    memcpy(p->cells, cells, p->rows*p->columns*sizeof(
      NHCmdPadCell));
}
void nhcmdset_add (PNHCmdSet p, PNHCmdLayout layout)
Definition at line 1153 of file mhcmd.c.
References assert, t_NHCmdSet::count, t_NHCmdSet::elements, t_NHCmdSet::t_NHCmdSetElem::free_on_destroy, t_NHCmdSet::t_NHCmdSetElem::layout, and NH_CMDSET_MAXSIZE.
Referenced by register_command_window_class().
{
    assert(p);
    assert(p->count<NH_CMDSET_MAXSIZE);
    p->elements[p->count].layout = layout;
    p->elements[p->count].free_on_destroy = 0;
    p->count++;
}
int nhcmdset_count (PNHCmdSet p)
Definition at line 1133 of file mhcmd.c.
References assert, and t_NHCmdSet::count.
Referenced by ActivateCell().
{
    assert(p);
    return p->count;
}
PNHCmdSet nhcmdset_create ()
Definition at line 1125 of file mhcmd.c.
References malloc().
Referenced by register_command_window_class().
{
    PNHCmdSet p;
    p = (PNHCmdSet)malloc(sizeof(NHCmdSet));
    ZeroMemory(p, sizeof(NHCmdSet));
    return p;
}
void nhcmdset_destroy (PNHCmdSet p)
Definition at line 1162 of file mhcmd.c.
References assert, t_NHCmdSet::count, t_NHCmdSet::elements, free(), t_NHCmdSet::t_NHCmdSetElem::free_on_destroy, t_NHCmdSet::t_NHCmdSetElem::layout, and nhcmdlayout_destroy().
{
    int i=0;
    assert(p);
    for(i=0; i<p->count; i++) {
        if(p->elements[i].free_on_destroy) {
            nhcmdlayout_destroy(p->elements[i].
      layout);
        }
    }
    free(p);
}
PNHCmdLayout nhcmdset_get (PNHCmdSet p, int index)
Definition at line 1139 of file mhcmd.c.
References assert, count, t_NHCmdSet::elements, index(), and t_NHCmdSet::t_NHCmdSetElem::layout.
Referenced by ActivateCell(), and onCreate().
{
    assert(p);
    assert(index>=0 && index<p->count);
    return p->elements[index].layout;
}
const char * nhcmdset_get_name (PNHCmdSet p, int index)
Definition at line 1146 of file mhcmd.c.
References assert, count, t_NHCmdSet::elements, index(), t_NHCmdSet::t_NHCmdSetElem::layout, and t_NHCmdLayout::name.
Referenced by ActivateCell().
{
    assert(p);
    assert(index>=0 && index<p->count);
    return p->elements[index].layout->name;
}
LRESULT CALLBACK NHCommandWndProc (HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam)
Definition at line 526 of file mhcmd.c.
References FALSE, mswin_nethack_cmd_window::font, free(), LayoutCmdWindow(), NH_CMDPAD_FONT_MAX, onCreate(), onMouseDown(), onMouseMove(), onMouseUp(), and onPaint().
Referenced by register_command_window_class().
{
    PNHCmdWindow data;
    int i;
    switch (message)
    {
    case WM_CREATE:
        onCreate(hWnd, wParam, lParam);
        break;
    case WM_PAINT:
        onPaint(hWnd);
        break;
    case WM_SIZE:
        LayoutCmdWindow(hWnd);
        break;
    case WM_LBUTTONDOWN:
        onMouseDown(hWnd, wParam, lParam);
        return 0;
    case WM_MOUSEMOVE:
        /* proceed only if if have mouse focus (set in onMouseDown() -
           left mouse button is pressed) */
        if(GetCapture()==hWnd) {
            onMouseMove(hWnd, wParam, lParam);
            return 0;
        } else {
            return 1;
        }
        break;
        
    case WM_LBUTTONUP:
        /* proceed only if if have mouse focus (set in onMouseDown()) */
        if(GetCapture()==hWnd) {
            onMouseUp(hWnd, wParam, lParam);
            return 0;
        } else {
            return 1;
        }
        break;
    case WM_DESTROY:
        data = (PNHCmdWindow)GetWindowLong(hWnd, GWL_USERDATA);
        for(i=0; i<=NH_CMDPAD_FONT_MAX; i++)
            if(data->font[i]) DeleteObject(data->font[i]);
        free(data);
        SetWindowLong(hWnd, GWL_USERDATA, (LONG)0);
        break;
    default:
        return DefWindowProc(hWnd, message, wParam, lParam);
    }
    return FALSE;
}
void onCreate (HWND hWnd, WPARAM wParam, LPARAM lParam) [static]
Definition at line 706 of file mhcmd.c.
References GetNHApp(), IDB_KEYPAD, malloc(), nhcmdset_get(), panic(), and SetCmdWindowLayout().
Referenced by NHCommandWndProc().
{
    PNHCmdWindow data;
    /* set window data */
    data = (PNHCmdWindow)malloc(sizeof(NHCmdWindow));
    if(!data) panic("out of memory");
    ZeroMemory(data, sizeof(NHCmdWindow));
    SetWindowLong(hWnd, GWL_USERDATA, (LONG)data);
    data->active_cell = -1;
    /* load images bitmap */
    data->images = LoadBitmap(GetNHApp()->hApp, MAKEINTRESOURCE(
      IDB_KEYPAD));
    if(!data->images) panic("cannot load keypad bitmap");
    /* create default layouts */
    data->layout_current = 0;
    data->layout_save = 0;
    data->cells = 0;
#if defined(WIN_CE_SMARTPHONE)
    data->layout_selected = nhcmdset_get(nhcmdset_current, 0);
#endif
    /* set default layout */
    SetCmdWindowLayout(hWnd, nhcmdset_get(
      nhcmdset_current, 0));
}
void onMouseDown (HWND hWnd, WPARAM wParam, LPARAM lParam) [static]
Definition at line 830 of file mhcmd.c.
References mswin_nethack_cmd_window::active_cell, CellFromPoint(), mswin_nethack_cmd_window::cells, HighlightCell(), NH_CST_CHECKED, and t_NHCmdPadLayoutCell::state.
Referenced by NHCommandWndProc().
{
    PNHCmdWindow data;
    POINT mpt;
    /* get mouse coordinates */
    mpt.x = LOWORD(lParam);
    mpt.y = HIWORD(lParam);
    /* map mouse coordinates to the display cell */
    data = (PNHCmdWindow)GetWindowLong(hWnd, GWL_USERDATA);
    data->active_cell = CellFromPoint(data, mpt);
    if(data->active_cell==-1) return;
    /* set mouse focus to the current window */
    SetCapture(hWnd);
    /* invert the selection */
    HighlightCell(hWnd, data->active_cell, (data->cells[data->
      active_cell].state!=NH_CST_CHECKED));
}
void onMouseMove (HWND hWnd, WPARAM wParam, LPARAM lParam) [static]
Definition at line 851 of file mhcmd.c.
References mswin_nethack_cmd_window::active_cell, CellFromPoint(), HighlightCell(), mswin_nethack_cmd_window::is_caps, mswin_nethack_cmd_window::is_ctrl, mswin_nethack_cmd_window::layout_current, NH_CELL_CAP, NH_CELL_CTRL, and nhcmdlayout_cell_direct.
Referenced by NHCommandWndProc().
{
    PNHCmdWindow data;
    POINT mpt;
    int newActiveCell;
    /* get mouse coordinates */
    mpt.x = LOWORD(lParam);
    mpt.y = HIWORD(lParam);
    /* map mouse coordinates to the display cell */
    data = (PNHCmdWindow)GetWindowLong(hWnd, GWL_USERDATA);
    newActiveCell = CellFromPoint(data, mpt);
    if(data->active_cell == -1) return;
    /* if mouse is within orginal display cell - select the cell otherwise
       clear the selection */
    switch(nhcmdlayout_cell_direct(data->layout_current, data->
      active_cell)->type) {
    case NH_CELL_REG:
        HighlightCell(hWnd, data->active_cell,
                   (newActiveCell==data->active_cell));
        break;
    case NH_CELL_CTRL:
        HighlightCell(hWnd, data->active_cell,
            ((newActiveCell==data->active_cell)? !data->is_ctrl : data->
      is_ctrl));
        break;
    case NH_CELL_CAP:
        HighlightCell(hWnd, data->active_cell,
            ((newActiveCell==data->active_cell)? !data->is_caps : data->
      is_caps));
        break;
    }
}
void onMouseUp (HWND hWnd, WPARAM wParam, LPARAM lParam) [static]
Definition at line 886 of file mhcmd.c.
References ActivateCell(), and mswin_nethack_cmd_window::active_cell.
Referenced by NHCommandWndProc().
{
    PNHCmdWindow data;
    /* release mouse capture */
    ReleaseCapture();
    /* get active display cell */
    data = (PNHCmdWindow)GetWindowLong(hWnd, GWL_USERDATA);
    if(data->active_cell == -1) return;
    ActivateCell(hWnd, data->active_cell);
    data->active_cell = -1;
}
void onPaint (HWND hWnd) [static]
Definition at line 584 of file mhcmd.c.
References BUFSZ, mswin_nethack_cmd_window::cell_size, mswin_nethack_cmd_window::cells, mswin_nethack_cmd_window::font, t_NHCmdPadCell::image, mswin_nethack_cmd_window::images, mswin_nethack_cmd_window::layout_current, min, MSWIN_COLOR_BG, MSWIN_COLOR_FG, mswin_get_color(), t_NHCmdPadCell::mult, NH_A2W, NH_CMDPAD_FONT_NORMAL, NH_CST_CHECKED, nhcmdlayout_cell_direct, nhcmdlayout_columns, nhcmdlayout_rows, NHW_KEYPAD, NULL, t_NHCmdPadLayoutCell::orig, t_NHCmdPadLayoutCell::state, and t_NHCmdPadCell::text.
Referenced by NHCommandWndProc().
{
    PNHCmdWindow data;
    PAINTSTRUCT ps;
    HDC hDC;
    int x, y;
    TCHAR wbuf[BUFSZ];
    HGDIOBJ saveFont;
    BITMAP bm;
    int cell_index;
    /* get window data */
    data = (PNHCmdWindow)GetWindowLong(hWnd, GWL_USERDATA);
    hDC = BeginPaint(hWnd, &ps);
    if(!IsRectEmpty(&ps.rcPaint)) {
        HGDIOBJ oldBr;
        HBRUSH hbrPattern;
        COLORREF OldBg, OldFg;
        HPEN hPen;
        HGDIOBJ hOldPen;
        saveFont = SelectObject(hDC, data->font[NH_CMDPAD_FONT_NORMAL]);
        OldBg = SetBkColor(hDC, mswin_get_color(NHW_KEYPAD,
      MSWIN_COLOR_BG));
        OldFg = SetTextColor(hDC, mswin_get_color(NHW_KEYPAD,
      MSWIN_COLOR_FG));
        GetObject(data->images, sizeof(BITMAP), (LPVOID)&bm);
        hbrPattern = CreatePatternBrush(data->images);
        hPen = CreatePen(PS_SOLID, 1, mswin_get_color(NHW_KEYPAD,
      MSWIN_COLOR_FG));
        for(x=0, cell_index = 0; x<nhcmdlayout_rows(data->
      layout_current); x++)
        for(y=0; y<nhcmdlayout_columns(data->layout_current); y++,
      cell_index++) {
            RECT cell_rt;
            POINT pt[5];
            PNHCmdPadCell p_cell_data;
            p_cell_data = nhcmdlayout_cell_direct(data->
      layout_current, cell_index);
            /* calculate the cell rectangle */
            cell_rt.left = data->cells[cell_index].orig.x;
            cell_rt.top = data->cells[cell_index].orig.y;
            cell_rt.right = data->cells[cell_index].orig.x + data->
      cell_size.cx*p_cell_data->mult;
            cell_rt.bottom = data->cells[cell_index].orig.y + data->
      cell_size.cy;
            /* draw border */
            hOldPen = SelectObject(hDC, hPen);
            pt[0].x = cell_rt.left;
            pt[0].y = cell_rt.top;
            pt[1].x = cell_rt.right;
            pt[1].y = cell_rt.top;
            pt[2].x = cell_rt.right;
            pt[2].y = cell_rt.bottom;
            pt[3].x = cell_rt.left;
            pt[3].y = cell_rt.bottom;
            pt[4].x = cell_rt.left;
            pt[4].y = cell_rt.top;
            Polyline(hDC, pt, 5);
            SelectObject(hDC, hOldPen);
            /* calculate clipping rectangle for the text */
            cell_rt.left++;
            cell_rt.top ++;
            cell_rt.right--;
            cell_rt.bottom--;
            /* draw the cell text */
            if(p_cell_data->image<=0) {
                SelectObject(hDC, data->font[ -p_cell_data->image ]);
                DrawText(hDC,
                        NH_A2W(p_cell_data->text, wbuf, BUFSZ),
                        strlen(p_cell_data->text),
                        &cell_rt,
                        DT_CENTER | DT_VCENTER | DT_SINGLELINE | DT_NOPREFIX
                        );
            } else {
                /* draw bitmap */
                int bmOffset;
                RECT bitmap_rt;
                bmOffset = (p_cell_data->image - 1)*bm.bmHeight;
                bitmap_rt.left = ((cell_rt.left+cell_rt.right) - min(bm.bmHeight, (cell_rt.right-cell_rt
      .left)))/2;
                bitmap_rt.top = ((cell_rt.bottom+cell_rt.top) - min(bm.bmHeight, (cell_rt.bottom-cell_rt
      .top)))/2;
                bitmap_rt.right = bitmap_rt.left + min(bm.bmHeight, (cell_rt.right-cell_rt.left));
                bitmap_rt.bottom = bitmap_rt.top + min(bm.bmHeight, (cell_rt.bottom-cell_rt.top));
                SetBrushOrgEx(hDC, bitmap_rt.left-bmOffset, bitmap_rt.top, NULL);
                oldBr = SelectObject(hDC, hbrPattern);
                PatBlt(
                    hDC,
                    bitmap_rt.left,
                    bitmap_rt.top,
                    bitmap_rt.right-bitmap_rt.left,
                    bitmap_rt.bottom-bitmap_rt.top,
                    PATCOPY);
                SelectObject(hDC, oldBr);
            }
            /* invert the cell if it is selected */
            if(data->cells[cell_index].state == NH_CST_CHECKED) {
                IntersectRect(&cell_rt, &cell_rt, &ps.rcPaint);
                PatBlt(hDC,
                        cell_rt.left,
                        cell_rt.top,
                        cell_rt.right - cell_rt.left,
                        cell_rt.bottom - cell_rt.top,
                        DSTINVERT
                        );
            }
        }
        SetTextColor(hDC, OldFg);
        SetBkColor(hDC, OldBg);
        SelectObject(hDC, saveFont);
        DeleteObject(hbrPattern);
        DeleteObject(hPen);
    }
    EndPaint(hWnd, &ps);
}
void PushNethackCommand (const char * cmd_char_str, int is_ctrl) [static]
Definition at line 1080 of file mhcmd.c.
References C, and NHEVENT_KBD.
Referenced by ActivateCell().
{
    while(*cmd_char_str) {
        if(is_ctrl) { NHEVENT_KBD(C(*cmd_char_str)); }
        else { NHEVENT_KBD(*cmd_char_str); }
        cmd_char_str++;
    }
}
void register_command_window_class () [static]
Definition at line 466 of file mhcmd.c.
References GetNHApp(), mswin_nhwindow_app::hApp, MSWIN_COLOR_BG, mswin_get_brush(), NH_CMDPAD_COLS, NH_CMDPAD_ROWS, nhcmdlayout_create(), nhcmdlayout_init(), nhcmdset_add(), nhcmdset_create(), NHCommandWndProc(), NHW_KEYPAD, NULL, panic(), and szNHCmdWindowClass.
Referenced by mswin_init_command_window().
{
    WNDCLASS wcex;
    PNHCmdLayout plt;
    ZeroMemory(&wcex, sizeof(wcex));
    /* window class */
    wcex.style = CS_NOCLOSE;
    wcex.lpfnWndProc = (WNDPROC)NHCommandWndProc;
    wcex.cbClsExtra = 0;
    wcex.cbWndExtra = 0;
    wcex.hInstance = GetNHApp()->hApp;
    wcex.hIcon = NULL;
    wcex.hCursor = LoadCursor(NULL, IDC_ARROW);
    wcex.hbrBackground = mswin_get_brush(NHW_KEYPAD,
      MSWIN_COLOR_BG);
    wcex.lpszMenuName = NULL;
    wcex.lpszClassName = szNHCmdWindowClass;
    if(!RegisterClass(&wcex)) {
        panic("cannot register Map window class");
    }
    /* create default command set */
    nhcmdset_current = nhcmdset_default =
      nhcmdset_create();
#ifdef WIN_CE_SMARTPHONE
    plt = nhcmdlayout_create("General", NH_CMDPAD_ROWS,
      NH_CMDPAD_COLS);
    nhcmdlayout_init(plt, cells_layout_general);
    nhcmdset_add(nhcmdset_current, plt);
    plt = nhcmdlayout_create("Movement", NH_CMDPAD_ROWS,
      NH_CMDPAD_COLS);
    nhcmdlayout_init(plt, cells_layout_movement);
    nhcmdset_add(nhcmdset_current, plt);
    plt = nhcmdlayout_create("Attack", NH_CMDPAD_ROWS,
      NH_CMDPAD_COLS);
    nhcmdlayout_init(plt, cells_layout_attack);
    nhcmdset_add(nhcmdset_current, plt);
    plt = nhcmdlayout_create("Item Handling", NH_CMDPAD_ROWS,
      NH_CMDPAD_COLS);
    nhcmdlayout_init(plt, cells_layout_item_handling);
    nhcmdset_add(nhcmdset_current, plt);
    plt = nhcmdlayout_create("Game Controls", NH_CMDPAD_ROWS,
      NH_CMDPAD_COLS);
    nhcmdlayout_init(plt, cells_layout_game);
    nhcmdset_add(nhcmdset_current, plt);
    plt = nhcmdlayout_create("Advanced Movement",
      NH_CMDPAD_ROWS, NH_CMDPAD_COLS);
    nhcmdlayout_init(plt, cells_layout_adv_movement);
    nhcmdset_add(nhcmdset_current, plt);
#else /* ! WIN_CE_SMARTPHONE */
    plt = nhcmdlayout_create("lowercase", NH_CMDPAD_ROWS,
      NH_CMDPAD_COLS);
    nhcmdlayout_init(plt, cells_layout_mod1);
    nhcmdset_add(nhcmdset_current, plt);
    plt = nhcmdlayout_create("uppercase", NH_CMDPAD_ROWS,
      NH_CMDPAD_COLS);
    nhcmdlayout_init(plt, cells_layout_mod2);
    nhcmdset_add(nhcmdset_current, plt);
#endif /* WIN_CE_SMARTPHONE */
}
void SetCmdWindowLayout (HWND hWnd, PNHCmdLayout layout) [static]
Definition at line 815 of file mhcmd.c.
References mswin_nethack_cmd_window::cells, mswin_nethack_cmd_window::layout_current, LayoutCmdWindow(), nhcmdlayout_columns, and nhcmdlayout_rows.
Referenced by ActivateCell(), and onCreate().
{
    PNHCmdWindow data;
    int size;
    data = (PNHCmdWindow)GetWindowLong(hWnd, GWL_USERDATA);
    if(data->layout_current == layout) return;
    data->layout_current = layout;
    size = sizeof(NHCmdPadLayoutCell)*nhcmdlayout_rows(layout)*
      nhcmdlayout_columns(layout);
    data->cells = (PNHCmdPadLayoutCell)realloc(data->
      cells, size);
    ZeroMemory(data->cells, size);
    LayoutCmdWindow(hWnd);
}
Variable Documentation
NHCmdPadCell cells_layout_mod1[NH_CMDPAD_ROWS *NH_CMDPAD_COLS]
Definition at line 286 of file mhcmd.c.
NHCmdPadCell cells_layout_mod2[-NH_CMDPAD_ROWS *-NH_CMDPAD_COLS]
Definition at line 350 of file mhcmd.c.
PNHCmdSet nhcmdset_current = 0 [static]
Definition at line 140 of file mhcmd.c.
PNHCmdSet nhcmdset_default = 0 [static]
Definition at line 141 of file mhcmd.c.
Referenced by ActivateCell().
TCHAR szNHCmdWindowClass[] = TEXT(`MSNethackCmdWndClass`) [static]
Definition at line 9 of file mhcmd.c.
Referenced by mswin_init_command_window(), and register_command_window_class().