nethack/sys/wince/mhcmd.h File Reference
#include `winMS.h`
*
#include `config.h`
*
#include `global.h`
*
Functions
HWND mswin_init_command_window ()
void mswin_command_window_size (HWND hwnd, LPSIZE sz)
Function Documentation
void mswin_command_window_size (HWND hwnd, LPSIZE sz)
Definition at line 446 of file mhcmd.c.
References CalculateCellSize(), mswin_nethack_cmd_window::layout_current, max, nhcmdlayout_columns, nhcmdlayout_rows, and SIZE.
Referenced by mswin_layout_main_window().
{
    SIZE cell_size;
    PNHCmdWindow data;
    data = (PNHCmdWindow)GetWindowLong(hwnd, GWL_USERDATA);
    if(!data) {
        sz->cx = sz->cy = 0;
    } else {
        CalculateCellSize(hwnd, &cell_size, sz);
        sz->cx = max(
                    cell_size.cx*nhcmdlayout_columns(data->
      layout_current)+2*GetSystemMetrics(SM_CXBORDER),
                    sz->cx
                    );
        sz->cy = max(
                    cell_size.cy*nhcmdlayout_rows(data->
      layout_current)+2*GetSystemMetrics(SM_CYBORDER),
                    sz->cy
                    );
    }
}
HWND mswin_init_command_window ()
Definition at line 416 of file mhcmd.c.
References GetNHApp(), NULL, panic(), register_command_window_class(), and szNHCmdWindowClass.
Referenced by MainWndProc().
                                  {
    static int run_once = 0;
    HWND ret;
    /* register window class */
    if(!run_once) {
        register_command_window_class();
        run_once = 1;
    }
    /* create window */
    ret = CreateWindow(
            szNHCmdWindowClass, /* registered class name */
            NULL, /* window name */
            WS_CHILD | WS_CLIPSIBLINGS, /* window style */
            0, /* horizontal position of window - set it later */
            0, /* vertical position of window - set it later */
            0, /* window width - set it later */
            0, /* window height - set it later*/
            GetNHApp()->hMainWnd, /* handle to parent or owner window */
            NULL, /* menu handle or child identifier */
            GetNHApp()->hApp, /* handle to application instance */
            NULL); /* window-creation data */
    if(!ret) {
        panic("Cannot create command window");
    }
    return ret;
}