nethack/sys/wince/mhcolor.h File Reference
Macros
#define MSWIN_COLOR_BG 0
#define MSWIN_COLOR_FG 1
#define SYSCLR_TO_BRUSH(x) ((HBRUSH)((x) + 1))
Functions
void mswin_init_color_table ()
HBRUSH mswin_get_brush (int win_type, int color_index)
COLORREF mswin_get_color (int win_type, int color_index)
Macro Definition Documentation
#define MSWIN_COLOR_BG 0
Definition at line 9 of file mhcolor.h.
Referenced by MenuWndProc(), mswin_init_color_table(), onDrawItem(), onPaint(), register_command_window_class(), register_message_window_class(), register_status_window_class(), SetMenuListType(), StatusWndProc(), and TextWndProc().
#define MSWIN_COLOR_FG 1
Definition at line 10 of file mhcolor.h.
Referenced by MenuWndProc(), mswin_init_color_table(), onDrawItem(), onPaint(), SetMenuListType(), StatusWndProc(), and TextWndProc().
#define SYSCLR_TO_BRUSH(x) ((HBRUSH)((x) + 1))
Definition at line 11 of file mhcolor.h.
Referenced by MenuWndProc(), mswin_color_from_string(), NHTextWndProc(), onDrawItem(), register_message_window_class(), and register_status_window_class().
Function Documentation
HBRUSH mswin_get_brush (int win_type, int color_index)
Definition at line 156 of file mhcolor.c.
References t_brush_table::brush, brush_table, t_brush_table::code, max_brush, NHBRUSH_CODE, and NULL.
Referenced by MenuWndProc(), register_command_window_class(), register_message_window_class(), register_status_window_class(), and TextWndProc().
{
    int i;
    for(i=0; i<max_brush; i++)
        if(brush_table[i].code == NHBRUSH_CODE(win_type,
      color_index))
            return brush_table[i].brush;
    return NULL;
}
COLORREF mswin_get_color (int win_type, int color_index)
Definition at line 165 of file mhcolor.c.
References brush_table, t_brush_table::code, t_brush_table::color, max_brush, NHBRUSH_CODE, and RGB.
Referenced by MenuWndProc(), onDrawItem(), onPaint(), SetMenuListType(), StatusWndProc(), and TextWndProc().
{
    int i;
    for(i=0; i<max_brush; i++)
        if(brush_table[i].code == NHBRUSH_CODE(win_type,
      color_index))
            return brush_table[i].color;
    return RGB(0, 0, 0);
}
void mswin_init_color_table ()
Definition at line 114 of file mhcolor.c.
References t_brush_table::brush, brush_table, BRUSHTABLE_ENTRY, t_brush_table::code, t_brush_table::color, iflags, max_brush, MSWIN_COLOR_BG, MSWIN_COLOR_FG, NHW_KEYPAD, NHW_MENU, NHW_MESSAGE, NHW_STATUS, NHW_TEXT, instance_flags::wc_backgrnd_menu, instance_flags::wc_backgrnd_message, instance_flags::wc_backgrnd_status, instance_flags::wc_backgrnd_text, instance_flags::wc_foregrnd_menu, instance_flags::wc_foregrnd_message, instance_flags::wc_foregrnd_status, and instance_flags::wc_foregrnd_text.
Referenced by mswin_init_nhwindows().
{
    int i;
    struct t_brush_table* p;
    /* cleanup */
    for(i=0; i<max_brush; i++)
        DeleteObject(brush_table[i].brush);
    max_brush = 0;
    /* initialize brush table */
#define BRUSHTABLE_ENTRY(opt, win, type) \
    brush_table[max_brush].code = NHBRUSH_CODE((win), (type)); \
    mswin_color_from_string((opt), &brush_table[max_brush].brush, &brush_table[max_brush].color); \
    max_brush++;
    BRUSHTABLE_ENTRY(iflags.wc_foregrnd_menu,
      NHW_MENU, MSWIN_COLOR_FG);
    BRUSHTABLE_ENTRY(iflags.wc_foregrnd_message,
      NHW_MESSAGE, MSWIN_COLOR_FG);
    BRUSHTABLE_ENTRY(iflags.wc_foregrnd_status,
      NHW_STATUS, MSWIN_COLOR_FG);
    BRUSHTABLE_ENTRY(iflags.wc_foregrnd_text,
      NHW_TEXT, MSWIN_COLOR_FG);
    BRUSHTABLE_ENTRY(iflags.wc_foregrnd_message,
      NHW_KEYPAD, MSWIN_COLOR_FG);
    BRUSHTABLE_ENTRY(iflags.wc_backgrnd_menu,
      NHW_MENU, MSWIN_COLOR_BG);
    BRUSHTABLE_ENTRY(iflags.wc_backgrnd_message,
      NHW_MESSAGE, MSWIN_COLOR_BG);
    BRUSHTABLE_ENTRY(iflags.wc_backgrnd_status,
      NHW_STATUS, MSWIN_COLOR_BG);
    BRUSHTABLE_ENTRY(iflags.wc_backgrnd_text,
      NHW_TEXT, MSWIN_COLOR_BG);
    BRUSHTABLE_ENTRY(iflags.wc_backgrnd_message,
      NHW_KEYPAD, MSWIN_COLOR_BG);
#undef BRUSHTABLE_ENTRY
    /* go through the values and fill in "blanks" (use default values) */
    for(i=0; i<max_brush; i++) {
        if(!brush_table[i].brush) {
            for(p = default_brush_table; p->code != -1; p++) {
                if(p->code==brush_table[i].code) {
                    brush_table[i].brush = CreateSolidBrush(p->
      color);
                    brush_table[i].color = p->color;
                }
            }
        }
    }
}