nethack/sys/wince/mhcolor.c File Reference
#include `winMS.h`
*
#include `mhcolor.h`
*
Data Structures
struct t_brush_table
struct ctv
struct ctbv
Macros
#define TOTAL_BRUSHES 10
#define NHBRUSH_CODE(win, type) ((((win)&0xFF)<<8)|((type)&0xFF))
#define BRUSHTABLE_ENTRY(opt, win, type)
Typedefs
typedef struct ctv color_table_value
typedef struct ctbv color_table_brush_value
Functions
static void mswin_color_from_string (char *colorstring, HBRUSH *brushptr, COLORREF *colorptr)
void mswin_init_color_table ()
HBRUSH mswin_get_brush (int win_type, int color_index)
COLORREF mswin_get_color (int win_type, int color_index)
Variables
static struct t_brush_table brush_table [TOTAL_BRUSHES]
static int max_brush = 0
static struct t_brush_table default_brush_table []
static color_table_value color_table []
static color_table_brush_value color_table_brush []
Macro Definition Documentation
#define BRUSHTABLE_ENTRY(opt, win, type)
Value:
brush_table[max_brush].code = NHBRUSH_CODE((win), (
      type)); \
    mswin_color_from_string((opt), &brush_table[
      max_brush].brush, &brush_table[max_brush].color); \
    max_brush++;
Referenced by mswin_init_color_table().
#define NHBRUSH_CODE(win, type) ((((win)&0xFF)<<8)|((type)&0xFF))
Definition at line 10 of file mhcolor.c.
Referenced by mswin_get_brush(), and mswin_get_color().
#define TOTAL_BRUSHES 10
Definition at line 9 of file mhcolor.c.
Referenced by mswin_color_from_string().
Typedef Documentation
typedef struct ctbv color_table_brush_value
typedef struct ctv color_table_value
Function Documentation
static void mswin_color_from_string (char * colorstring, HBRUSH * brushptr, COLORREF * colorptr) [static]
Definition at line 174 of file mhcolor.c.
References color_table, color_table_brush, ctv::colorstring, ctbv::colorstring, ctv::colorvalue, index(), max_brush, NULL, panic(), RGB, SYSCLR_TO_BRUSH, ctbv::syscolorvalue, and TOTAL_BRUSHES.
{
    color_table_value *ctv_ptr = color_table;
    color_table_brush_value *ctbv_ptr = color_table_brush;
    int red_value, blue_value, green_value;
    static char *hexadecimals = "0123456789abcdef";
    *brushptr = NULL;
    *colorptr = RGB(0, 0, 0);
    if (colorstring == NULL) return;
    if (*colorstring == '#') {
        if (strlen(++colorstring) != 6) return;
        red_value = index(hexadecimals, tolower(*colorstring++)) - hexadecimals;
        red_value *= 16;
        red_value += index(hexadecimals, tolower(*colorstring++)) - hexadecimals;
        green_value = index(hexadecimals, tolower(*colorstring++)) - hexadecimals;
        green_value *= 16;
        green_value += index(hexadecimals, tolower(*colorstring++)) - hexadecimals;
        blue_value = index(hexadecimals, tolower(*colorstring++)) - hexadecimals;
        blue_value *= 16;
        blue_value += index(hexadecimals, tolower(*colorstring++)) - hexadecimals;
        *colorptr = RGB(red_value, blue_value, green_value);
    } else {
        while (*ctv_ptr->colorstring && _stricmp(ctv_ptr->colorstring, colorstring))
        ++ctv_ptr;
        if (*ctv_ptr->colorstring) {
        *colorptr = ctv_ptr->colorvalue;
        } else {
          while (*ctbv_ptr->colorstring && _stricmp(ctbv_ptr->
      colorstring, colorstring))
            ++ctbv_ptr;
        if (*ctbv_ptr->colorstring) {
            *brushptr = SYSCLR_TO_BRUSH(ctbv_ptr->syscolorvalue);
            *colorptr = GetSysColor(ctbv_ptr->syscolorvalue);
        }
        }
    }
    if (max_brush > TOTAL_BRUSHES) panic("Too many colors!");
    *brushptr = CreateSolidBrush(*colorptr);
}
HBRUSH mswin_get_brush (int win_type, int color_index)
Definition at line 156 of file mhcolor.c.
References t_brush_table::brush, brush_table, t_brush_table::code, max_brush, NHBRUSH_CODE, and NULL.
Referenced by MenuWndProc(), register_command_window_class(), register_message_window_class(), register_status_window_class(), and TextWndProc().
{
    int i;
    for(i=0; i<max_brush; i++)
        if(brush_table[i].code == NHBRUSH_CODE(win_type,
      color_index))
            return brush_table[i].brush;
    return NULL;
}
COLORREF mswin_get_color (int win_type, int color_index)
Definition at line 165 of file mhcolor.c.
References brush_table, t_brush_table::code, t_brush_table::color, max_brush, NHBRUSH_CODE, and RGB.
Referenced by MenuWndProc(), onDrawItem(), onPaint(), SetMenuListType(), StatusWndProc(), and TextWndProc().
{
    int i;
    for(i=0; i<max_brush; i++)
        if(brush_table[i].code == NHBRUSH_CODE(win_type,
      color_index))
            return brush_table[i].color;
    return RGB(0, 0, 0);
}
void mswin_init_color_table ()
Definition at line 114 of file mhcolor.c.
References t_brush_table::brush, brush_table, BRUSHTABLE_ENTRY, t_brush_table::code, t_brush_table::color, iflags, max_brush, MSWIN_COLOR_BG, MSWIN_COLOR_FG, NHW_KEYPAD, NHW_MENU, NHW_MESSAGE, NHW_STATUS, NHW_TEXT, instance_flags::wc_backgrnd_menu, instance_flags::wc_backgrnd_message, instance_flags::wc_backgrnd_status, instance_flags::wc_backgrnd_text, instance_flags::wc_foregrnd_menu, instance_flags::wc_foregrnd_message, instance_flags::wc_foregrnd_status, and instance_flags::wc_foregrnd_text.
Referenced by mswin_init_nhwindows().
{
    int i;
    struct t_brush_table* p;
    /* cleanup */
    for(i=0; i<max_brush; i++)
        DeleteObject(brush_table[i].brush);
    max_brush = 0;
    /* initialize brush table */
#define BRUSHTABLE_ENTRY(opt, win, type) \
    brush_table[max_brush].code = NHBRUSH_CODE((win), (type)); \
    mswin_color_from_string((opt), &brush_table[max_brush].brush, &brush_table[max_brush].color); \
    max_brush++;
    BRUSHTABLE_ENTRY(iflags.wc_foregrnd_menu,
      NHW_MENU, MSWIN_COLOR_FG);
    BRUSHTABLE_ENTRY(iflags.wc_foregrnd_message,
      NHW_MESSAGE, MSWIN_COLOR_FG);
    BRUSHTABLE_ENTRY(iflags.wc_foregrnd_status,
      NHW_STATUS, MSWIN_COLOR_FG);
    BRUSHTABLE_ENTRY(iflags.wc_foregrnd_text,
      NHW_TEXT, MSWIN_COLOR_FG);
    BRUSHTABLE_ENTRY(iflags.wc_foregrnd_message,
      NHW_KEYPAD, MSWIN_COLOR_FG);
    BRUSHTABLE_ENTRY(iflags.wc_backgrnd_menu,
      NHW_MENU, MSWIN_COLOR_BG);
    BRUSHTABLE_ENTRY(iflags.wc_backgrnd_message,
      NHW_MESSAGE, MSWIN_COLOR_BG);
    BRUSHTABLE_ENTRY(iflags.wc_backgrnd_status,
      NHW_STATUS, MSWIN_COLOR_BG);
    BRUSHTABLE_ENTRY(iflags.wc_backgrnd_text,
      NHW_TEXT, MSWIN_COLOR_BG);
    BRUSHTABLE_ENTRY(iflags.wc_backgrnd_message,
      NHW_KEYPAD, MSWIN_COLOR_BG);
#undef BRUSHTABLE_ENTRY
    /* go through the values and fill in "blanks" (use default values) */
    for(i=0; i<max_brush; i++) {
        if(!brush_table[i].brush) {
            for(p = default_brush_table; p->code != -1; p++) {
                if(p->code==brush_table[i].code) {
                    brush_table[i].brush = CreateSolidBrush(p->
      color);
                    brush_table[i].color = p->color;
                }
            }
        }
    }
}
Variable Documentation
struct t_brush_table brush_table[TOTAL_BRUSHES] [static]
Definition at line 17 of file mhcolor.c.
Referenced by mswin_get_brush(), mswin_get_color(), and mswin_init_color_table().
color_table_value color_table[] [static]
Definition at line 52 of file mhcolor.c.
Referenced by mswin_color_from_string().
color_table_brush_value color_table_brush[] [static]
Initial value:
= {
    { "activeborder", COLOR_ACTIVEBORDER },
    { "activecaption", COLOR_ACTIVECAPTION },
    { "appworkspace", COLOR_APPWORKSPACE },
    { "background", COLOR_BACKGROUND },
    { "btnface", COLOR_BTNFACE },
    { "btnshadow", COLOR_BTNSHADOW },
    { "btntext", COLOR_BTNTEXT },
    { "captiontext", COLOR_CAPTIONTEXT },
    { "graytext", COLOR_GRAYTEXT },
    { "greytext", COLOR_GRAYTEXT },
    { "highlight", COLOR_HIGHLIGHT },
    { "highlighttext", COLOR_HIGHLIGHTTEXT },
    { "inactiveborder", COLOR_INACTIVEBORDER },
    { "inactivecaption", COLOR_INACTIVECAPTION },
    { "menu", COLOR_MENU },
    { "menutext", COLOR_MENUTEXT },
    { "scrollbar", COLOR_SCROLLBAR },
    { "window", COLOR_WINDOW },
    { "windowframe", COLOR_WINDOWFRAME },
    { "windowtext", COLOR_WINDOWTEXT },
    { "", -1 },
}
Definition at line 90 of file mhcolor.c.
Referenced by mswin_color_from_string().
struct t_brush_table default_brush_table[] [static]
Initial value:
=
{
    { NHBRUSH_CODE(NHW_STATUS, MSWIN_COLOR_FG),
      NULL, RGB(0, 0, 0) },
    { NHBRUSH_CODE(NHW_MESSAGE, MSWIN_COLOR_FG),
      NULL, RGB(0, 0, 0) },
    { NHBRUSH_CODE(NHW_STATUS, MSWIN_COLOR_FG),
      NULL, RGB(0, 0, 0) },
    { NHBRUSH_CODE(NHW_TEXT, MSWIN_COLOR_FG),
      NULL, RGB(0, 0, 0) },
    { NHBRUSH_CODE(NHW_KEYPAD, MSWIN_COLOR_FG),
      NULL, RGB(0, 0, 0) },
    { NHBRUSH_CODE(NHW_MAP, MSWIN_COLOR_FG),
      NULL, RGB(96, 96, 96) },
    { NHBRUSH_CODE(NHW_MENU, MSWIN_COLOR_BG),
      NULL, RGB(255, 255, 255) },
    { NHBRUSH_CODE(NHW_MESSAGE, MSWIN_COLOR_BG),
      NULL, RGB(192, 192, 192) },
    { NHBRUSH_CODE(NHW_STATUS, MSWIN_COLOR_BG),
      NULL, RGB(192, 192, 192) },
    { NHBRUSH_CODE(NHW_TEXT, MSWIN_COLOR_BG),
      NULL, RGB(255, 255, 255) },
    { NHBRUSH_CODE(NHW_KEYPAD, MSWIN_COLOR_BG),
      NULL, RGB(255, 255, 255) },
    { NHBRUSH_CODE(NHW_MAP, MSWIN_COLOR_BG),
      NULL, RGB(192, 192, 192) },
    { -1, NULL, RGB(0, 0, 0) }
}
Definition at line 20 of file mhcolor.c.
int max_brush = 0 [static]
Definition at line 18 of file mhcolor.c.
Referenced by mswin_color_from_string(), mswin_get_brush(), mswin_get_color(), and mswin_init_color_table().