nethack/sys/wince/mhtxtbuf.h File Reference
#include `winMS.h`
*
Typedefs
typedef struct
*
mswin_nethack_text_buffer * PNHTextBuffer
Functions
PNHTextBuffer mswin_init_text_buffer (BOOL wrap_text)
void mswin_free_text_buffer (PNHTextBuffer pb)
void mswin_add_text (PNHTextBuffer pb, int attr, const char *text)
void mswin_render_text (PNHTextBuffer pb, HWND edit_control)
Typedef Documentation
typedef struct mswin_nethack_text_buffer* PNHTextBuffer
Definition at line 9 of file mhtxtbuf.h.
Function Documentation
void mswin_add_text (PNHTextBuffer pb, int attr, const char * text)
Definition at line 62 of file mhtxtbuf.c.
References text_buffer_line::attr, text_buffer_line::beg_padding, text_buffer_line::end_padding, FALSE, text_buffer_line::formatted, mswin_nethack_text_buffer::n_size, mswin_nethack_text_buffer::n_used, NHTEXT_BUFFER_INCREMENT, NHTextLine, NULL, panic(), strdup, text_buffer_line::text, and mswin_nethack_text_buffer::text_buffer_line.
Referenced by onMSNHCommand().
{
    char* p;
    struct text_buffer_line* new_line;
    /* grow buffer */
    if(pb->n_used >= pb->n_size) {
        pb->n_size += NHTEXT_BUFFER_INCREMENT;
        pb->text_buffer_line =
            (struct text_buffer_line*)realloc(pb->
      text_buffer_line, pb->n_size*sizeof(struct
      text_buffer_line));
        if(!pb->text_buffer_line) panic("Memory allocation error");
    }
    /* analyze the new line of text */
    new_line = &NHTextLine(pb, pb->n_used);
    new_line->attr = attr;
    new_line->beg_padding = 0;
    new_line->text = strdup(text);
    for(p = new_line->text; *p && isspace(*p); p++) {
        new_line->beg_padding++;
    }
    if(*p) {
        memmove(new_line->text,
                new_line->text + new_line->beg_padding,
                strlen(new_line->text) - new_line->beg_padding + 1
                );
        for(p = new_line->text+strlen(new_line->text);
             p>=new_line->text && isspace(*p);
             p--) {
            new_line->end_padding++;
            *p = 0;
        }
        /* if there are 3 (or more) consecutive spaces inside the string
           consider it formatted */
        new_line->formatted = (strstr(new_line->text, " ")!=NULL);
    } else {
        new_line->end_padding = 0;
        new_line->text[0] = 0;
        new_line->formatted = FALSE;
    }
    pb->n_used++;
}
void mswin_free_text_buffer (PNHTextBuffer pb)
Definition at line 49 of file mhtxtbuf.c.
References free(), mswin_nethack_text_buffer::n_used, text_buffer_line::text, and mswin_nethack_text_buffer::text_buffer_line.
Referenced by MenuWndProc(), and TextWndProc().
{
    int i;
    
    if(!pb) return;
    for(i=0; i<pb->n_used; i++) {
        free(pb->text_buffer_line[i].text);
    }
    free(pb->text_buffer_line);
    free(pb);
}
PNHTextBuffer mswin_init_text_buffer (BOOL wrap_text)
Definition at line 36 of file mhtxtbuf.c.
References mswin_nethack_text_buffer::b_wrap_text, malloc(), mswin_nethack_text_buffer::n_size, mswin_nethack_text_buffer::n_used, NULL, panic(), and mswin_nethack_text_buffer::text_buffer_line.
Referenced by mswin_init_text_window(), and onMSNHCommand().
{
    PNHTextBuffer pb = (PNHTextBuffer)malloc(sizeof(
      NHTextBuffer));
    if(!pb) panic("Out of memory");
    
    ZeroMemory(pb, sizeof(NHTextBuffer));
    pb->b_wrap_text = wrap_text;
    pb->n_size = 0;
    pb->n_used = 0;
    pb->text_buffer_line = NULL;
    return pb;
}
void mswin_render_text (PNHTextBuffer pb, HWND edit_control)
Definition at line 130 of file mhtxtbuf.c.
References mswin_nethack_text_buffer::b_wrap_text, buf, BUFSZ, text_buffer_line::formatted, free(), mswin_nethack_text_buffer::n_used, NH_A2W, nh_append(), NHTextLine, NULL, SIZE, and text_buffer_line::text.
Referenced by LayoutMenu(), mswin_display_text_window(), and onMSNHCommand().
{
    RECT rt_client; /* boundaries of the client area of the edit control */
    SIZE size_text; /* size of the edit control */
    RECT rt_text; /* calculated text rectangle for the visible line */
    char buf[BUFSZ]; /* buffer for the visible line */
    TCHAR tbuf[BUFSZ]; /* temp buffer for DrawText */
    TCHAR* pText = NULL; /* resulting text (formatted) */
    int pTextSize = 0; /* resulting text size */
    char* p_cur = NULL; /* current position in the NHTextBuffer->text_buffer_line->text */
    char* p_buf_cur = NULL; /* current position in the visible line buffer */
    int i;
    HDC hdcEdit; /* device context for the edit control */
    HFONT hFont, hOldFont; /* edit control font */
    GetClientRect(edit_control, &rt_client);
    size_text.cx = rt_client.right - rt_client.left;
    size_text.cy = rt_client.bottom - rt_client.top;
    size_text.cx -= GetSystemMetrics(SM_CXVSCROLL); /* add a slight right margin - the text looks better
       that way */
    hdcEdit = GetDC(edit_control);
    hFont = (HFONT)SendMessage(edit_control, WM_GETFONT, 0, 0);
    if(hFont) hOldFont = SelectObject(hdcEdit, hFont);
    /* loop through each line (outer loop) and wrap it around (inner loop) */
    ZeroMemory(buf, sizeof(buf));
    p_buf_cur = buf;
    for(i=0; i<pb->n_used; i++) {
        if(pb->b_wrap_text) {
            p_cur = NHTextLine(pb,i).text;
            /* insert an line break for the empty string */
            if(!NHTextLine(pb,i).text[0]) {
                pText = nh_append(pText, &pTextSize, "\r\n");
                continue;
            }
            /* add margin to the "formatted" line of text */
            if(NHTextLine(pb,i).formatted) {
                strcpy(buf, " ");
                p_buf_cur += 3;
            }
            /* scroll thourgh the current line of text and wrap it
               so it fits to width of the edit control */
            while(*p_cur) {
                char *p_word_pos = p_buf_cur;
                /* copy one word into the buffer */
                while(*p_cur && isspace(*p_cur))
                    if(p_buf_cur!=buf) *p_buf_cur++ = *p_cur++;
                    else p_cur++;
                while(*p_cur && !isspace(*p_cur))
                    *p_buf_cur++ = *p_cur++;
                /* check if it fits */
                SetRect(&rt_text, 0, 0, size_text.cx, size_text.cy);
                DrawText(hdcEdit, NH_A2W(buf, tbuf, p_buf_cur-buf), p_buf_cur-buf, &rt_text,
      DT_CALCRECT | DT_LEFT | DT_SINGLELINE | DT_NOCLIP);
                if((rt_text.right - rt_text.left)>=size_text.cx) {
                    /* Backtrack.
                       Only backtrack if the last word caused the overflow -
                       do not backtrack if the entire current line does not fit the visible area.
                       Otherwise it is a infinite loop.
                    */
                    if(p_word_pos>buf) {
                        p_cur -= (p_buf_cur-p_word_pos);
                        p_buf_cur = p_word_pos;
                    }
                    *p_buf_cur = 0; /* break the line */
                    /* append the calculated line to the text buffer */
                    pText = nh_append(pText, &pTextSize, buf);
                    pText = nh_append(pText, &pTextSize, "\r\n");
                    ZeroMemory(buf, sizeof(buf));
                    p_buf_cur = buf;
                }
            }
            /* always break the line at the end of the buffer text */
            if(p_buf_cur != buf) {
                /* flush the current buffrer */
                *p_buf_cur = 0; /* break the line */
                pText = nh_append(pText, &pTextSize, buf);
                pText = nh_append(pText, &pTextSize, "\r\n");
                ZeroMemory(buf, sizeof(buf));
                p_buf_cur = buf;
            }
        } else { /* do not wrap text */
            int j;
            for(j=0; j<NHTextLine(pb,i).beg_padding; j++)
                pText = nh_append(pText, &pTextSize, " ");
            pText = nh_append(pText, &pTextSize, NHTextLine(pb,i).text);
            pText = nh_append(pText, &pTextSize, "\r\n");
        }
    }
    
    /* cleanup */
    if(hFont) SelectObject(hdcEdit, hOldFont);
    ReleaseDC(edit_control, hdcEdit);
    /* update edit control text */
    if(pText) {
        SendMessage(edit_control, EM_FMTLINES, 1, 0);
        SetWindowText(edit_control, pText);
        free(pText);
    }
}