nethack/sys/mac/mrecover.c File Reference
#include `config.h`
*
#include <Errors.h>
*
#include <OSUtils.h>
*
#include <Resources.h>
*
#include <Files.h>
*
#include <Menus.h>
*
#include <Devices.h>
*
#include <Events.h>
*
#include <DiskInit.h>
*
#include <Notification.h>
*
#include <Packages.h>
*
#include <Script.h>
*
#include <StandardFile.h>
*
#include <ToolUtils.h>
*
#include <Processes.h>
*
#include <Fonts.h>
*
#include <TextUtils.h>
*
Data Structures
struct memBytes
struct notifRec
struct modeFlags
struct versXRec
Macros
#define membID 128				/* 'memB' resource ID */
#define CURS_FRAME 4L				/* 1/15 second - spin cursor */
#define CURS_LATENT 60L				/* pause before spin cursor */
#define curs_Init (-1)			/* token for set arrow */
#define curs_Total 8				/* maybe 'acur' would be better */
#define cursorOffset 128				/* GetCursor(cursorOffset + i) */
#define aboutBufSize 80				/* i.e. 2 lines of 320 pixels */
#define nmBufSize (32 + aboutBufSize + 32)
#define nmPending nmRefCon			/* &in.Notify */
#define iconNotifyID 128
#define ics_1_and_4 0x00000300
#define DLGTHM ((DialogPtr) &dlgThermo)
#define WNDTHM ((WindowPtr) &dlgThermo)
#define GRFTHM ((GrafPtr) &dlgThermo)
#define MAX_RECOVER_COUNT 256
#define APP_NAME_RES_ID (-16396)	/* macfile.h */
#define PLAYER_NAME_RES_ID 1001		/* macfile.h */
#define SAVESIZE FILENAME
Typedefs
typedef struct memBytes memBytes
typedef struct memBytes * memBytesPtr
typedef struct memBytes ** memBytesHandle
typedef struct notifRec notifRec
typedef struct notifRec * notifPtr
typedef struct modeFlags modeFlags
typedef struct versXRec versXRec
typedef struct versXRec * versXPtr
typedef struct versXRec ** versXHandle
Enumerations
enum { mbar_Init = -1,
mbarAppl,
mbarRecover,
mbarDA
 }
enum {
*
menuApple,
menuFile,
menuEdit,
menu_Total,
*
muidApple = 128,
muidFile,
muidEdit
 }
enum {
*
mitmAbout = 1,
mitmHelp,
____128_1,
mitmOpen = 1,
*
____129_1,
mitmClose_DA,
____129_2,
mitmQuit
 }
enum {
*
alrtNote,
alrtHelp,
alrt_Total,
alertAppleMenu = 127,
*
alidNote,
alidHelp
 }
enum { dlogProgress = 256
 }
enum { uitmThermo = 1
 }
enum { initItem,
invalItem,
drawItem
 }
Functions
static void warmup (void)
static Handle alignTemplate (ResType, short, short, short, Point *)
pascal void nmCompletion (NMRec *)
static void noteErrorMessage (unsigned char *, unsigned char *)
static void note (short, short, unsigned char *)
static void adjustGUI (void)
static void adjustMemory (void)
static void optionMemStats (void)
static void RecoverMenuEvent (long)
static void eventLoop (void)
static void cooldown (void)
pascal void drawThermo (WindowPtr, short)
static void itemizeThermo (short)
pascal Boolean basenameFileFilter (ParmBlkPtr)
static void beginRecover (void)
static void continueRecover (void)
static void endRecover (void)
static short saveRezStrings (void)
static void set_levelfile_name (long)
static short open_levelfile (long)
static short create_savefile (unsigned char *)
static void copy_bytes (short, short)
static void restore_savefile (void)
static long read_levelfile (short, Ptr, long)
static long write_savefile (short, Ptr, long)
static void close_file (short *)
static void unlink_file (unsigned char *)
main ()
Variables
modeFlags in = {1}
EventRecord wnEvt
SysEnvRec sysEnv
unsigned char aboutBuf [aboutBufSize]
memBytesPtr pBytes
unsigned short memActivity
MenuHandle mHnd [menu_Total]
CursPtr cPtr [curs_Total]
unsigned long timeCursor
short oldCursor = curs_Init
notifPtr pNMQ
notifRec nmt
DialogTHndl thermoTHnd
DialogRecord dlgThermo
Point sfGetWhere
Ptr pIOBuf
short vRefNum
long dirID
NMUPP nmCompletionUPP
FileFilterUPP basenameFileFilterUPP
UserItemUPP drawThermoUPP
unsigned char savename [SAVESIZE]
unsigned char lock [256]
int hpid
short saveRefNum
short gameRefNum
short levRefNum
Macro Definition Documentation
#define aboutBufSize 80				/* i.e. 2 lines of 320 pixels */
Definition at line 143 of file mrecover.c.
#define APP_NAME_RES_ID (-16396)	/* macfile.h */
Definition at line 225 of file mrecover.c.
Referenced by saveRezStrings().
#define CURS_FRAME 4L				/* 1/15 second - spin cursor */
Definition at line 87 of file mrecover.c.
Referenced by adjustGUI().
#define curs_Init (-1)			/* token for set arrow */
Definition at line 89 of file mrecover.c.
Referenced by adjustGUI(), and endRecover().
#define CURS_LATENT 60L				/* pause before spin cursor */
Definition at line 88 of file mrecover.c.
Referenced by beginRecover().
#define curs_Total 8				/* maybe 'acur' would be better */
Definition at line 90 of file mrecover.c.
#define cursorOffset 128				/* GetCursor(cursorOffset + i) */
Definition at line 91 of file mrecover.c.
#define DLGTHM ((DialogPtr) &dlgThermo)
Definition at line 211 of file mrecover.c.
Referenced by endRecover(), and itemizeThermo().
#define GRFTHM ((GrafPtr) &dlgThermo)
Definition at line 213 of file mrecover.c.
Referenced by itemizeThermo().
#define iconNotifyID 128
Definition at line 157 of file mrecover.c.
#define ics_1_and_4 0x00000300
Definition at line 158 of file mrecover.c.
#define MAX_RECOVER_COUNT 256
Definition at line 223 of file mrecover.c.
Referenced by continueRecover(), and restore_savefile().
#define membID 128				/* 'memB' resource ID */
Definition at line 83 of file mrecover.c.
#define nmBufSize (32 + aboutBufSize + 32)
Definition at line 147 of file mrecover.c.
#define nmPending nmRefCon			/* &in.Notify */
Definition at line 156 of file mrecover.c.
#define PLAYER_NAME_RES_ID 1001		/* macfile.h */
Definition at line 226 of file mrecover.c.
Referenced by saveRezStrings().
#define SAVESIZE FILENAME
Definition at line 229 of file mrecover.c.
#define WNDTHM ((WindowPtr) &dlgThermo)
Definition at line 212 of file mrecover.c.
Referenced by beginRecover().
Typedef Documentation
typedef struct memBytes memBytes
typedef struct memBytes ** memBytesHandle
typedef struct memBytes * memBytesPtr
typedef struct modeFlags modeFlags
typedef struct notifRec * notifPtr
typedef struct notifRec notifRec
typedef struct versXRec ** versXHandle
typedef struct versXRec * versXPtr
typedef struct versXRec versXRec
Enumeration Type Documentation
anonymous enum
Enumerator
mbar_Init
mbarAppl
mbarRecover
mbarDA
Definition at line 95 of file mrecover.c.
{
    mbar_Init = -1,
    mbarAppl, /* normal mode */
    mbarRecover, /* in recovery mode */
    mbarDA /* DA in front mode */
};
anonymous enum
Enumerator
menuApple
menuFile
menuEdit
menu_Total
muidApple
muidFile
muidEdit
Definition at line 102 of file mrecover.c.
{
    menuApple,
    menuFile,
    menuEdit,
    menu_Total,
    muidApple = 128,
    muidFile,
    muidEdit
};
anonymous enum
Enumerator
mitmAbout
mitmHelp
____128_1
mitmOpen
____129_1
mitmClose_DA
____129_2
mitmQuit
Definition at line 113 of file mrecover.c.
{
    /* Apple menu */
    mitmAbout = 1,
    mitmHelp,
    ____128_1,
    /* File menu */
    mitmOpen = 1,
    ____129_1,
    mitmClose_DA,
    ____129_2,
    mitmQuit
    /* standard minimum required Edit menu */
};
anonymous enum
Enumerator
alrtNote
alrtHelp
alrt_Total
alertAppleMenu
alidNote
alidHelp
Definition at line 132 of file mrecover.c.
{
    alrtNote, /* general messages */
    alrtHelp, /* help message */
    alrt_Total,
    alertAppleMenu = 127, /* menuItem to alert ID offset */
    alidNote,
    alidHelp
};
anonymous enum
Enumerator
dlogProgress
Definition at line 161 of file mrecover.c.
{
    dlogProgress = 256
};
anonymous enum
Enumerator
uitmThermo
Definition at line 165 of file mrecover.c.
{
    uitmThermo = 1
};
anonymous enum
Enumerator
initItem
invalItem
drawItem
Definition at line 169 of file mrecover.c.
{
    initItem,
    invalItem,
    drawItem
};
Function Documentation
static void adjustGUI (void) [static]
Definition at line 591 of file mrecover.c.
References cPtr, CURS_FRAME, curs_Init, mbar_Init, mbarAppl, mbarDA, mbarRecover, menuEdit, menuFile, mHnd, mitmClose_DA, mitmOpen, oldCursor, modeFlags::Recover, and timeCursor.
Referenced by eventLoop().
{
    static short oldMenubar = mbar_Init; /* force initial update */
    short newMenubar;
    WindowPeek frontWindow;
    /* oldCursor is external so it can be reset in endRecover() */
    static short newCursor = curs_Init;
    unsigned long timeNow;
    short useArrow;
    /* adjust menubar 1st */
    newMenubar = in.Recover ? mbarRecover : mbarAppl;
    /* desk accessories take precedence */
    if (frontWindow = (WindowPeek) FrontWindow())
        if (frontWindow->windowKind < 0)
            newMenubar = mbarDA;
    if (newMenubar != oldMenubar)
    {
        /* adjust menus */
        switch (oldMenubar = newMenubar)
        {
        case mbarAppl:
            EnableItem(mHnd[menuFile], mitmOpen);
            SetItemMark(mHnd[menuFile], mitmOpen, noMark);
            DisableItem(mHnd[menuFile], mitmClose_DA);
            DisableItem(mHnd[menuEdit], 0);
            break;
        case mbarRecover:
            DisableItem(mHnd[menuFile], mitmOpen);
            SetItemMark(mHnd[menuFile], mitmOpen, checkMark);
            DisableItem(mHnd[menuFile], mitmClose_DA);
            DisableItem(mHnd[menuEdit], 0);
            break;
        case mbarDA:
            DisableItem(mHnd[menuFile], mitmOpen);
            EnableItem(mHnd[menuFile], mitmClose_DA);
            EnableItem(mHnd[menuEdit], 0);
            break;
        }
        DrawMenuBar();
    }
    /* now adjust the cursor */
    if (useArrow = (!in.Recover || (newMenubar == mbarDA)))
        newCursor = curs_Init;
    else if ((timeNow = TickCount()) >= timeCursor) /* spin cursor */
    {
        timeCursor = timeNow + CURS_FRAME;
        if (++newCursor >= curs_Total)
            newCursor = 0;
    }
    if (newCursor != oldCursor)
    {
        oldCursor = newCursor;
        SetCursor(useArrow ? &qd.arrow : cPtr[newCursor]);
    }
}
static void adjustMemory (void) [static]
Definition at line 658 of file mrecover.c.
References alidNote, memActivity, memBytes::memWarning, and note().
Referenced by eventLoop(), and optionMemStats().
{
    Size grow;
    memActivity = 0;
    if (MaxMem(&grow) < pBytes->memWarning)
        note(noErr, alidNote, "\pWarning: Memory is running low");
    (void) ResrvMem((Size) FreeMem()); /* move all handles high */
}
static Handle alignTemplate (ResType rezType, short rezID, short vOff, short vDenom, Point * pPt) [static]
Definition at line 461 of file mrecover.c.
References note().
{
    Handle rtnHnd;
    Rect *pRct;
    vOff += GetMBarHeight();
    if (! (rtnHnd = GetResource(rezType, rezID)))
        note(nilHandleErr, 0, "\pNil Template Handle");
    pRct = (Rect *) *rtnHnd;
    /* don't move memory while aligning rect */
    pRct->right -= pRct->left; /* width */
    pRct->bottom -= pRct->top; /* height */
    pRct->left = (qd.screenBits.bounds.right - pRct->right) / 2;
    pRct->top = (qd.screenBits.bounds.bottom - pRct->bottom - vOff) / vDenom;
    pRct->top += vOff;
    pRct->right += pRct->left;
    pRct->bottom += pRct->top;
    if (pPt)
        *pPt = * (Point *) pRct; /* top left corner */
    return rtnHnd;
}
pascal Boolean basenameFileFilter (ParmBlkPtr pPB)
Definition at line 976 of file mrecover.c.
Referenced by main().
{
    unsigned char *pC;
    if (! (pC = (unsigned char *) pPB->fileParam.ioNamePtr))
        return true;
    if ((*pC < 4) || (*pC > 28)) /* save/ 1name .0 */
        return true;
    if ((pC[*pC - 1] == '.') && (pC[*pC] == '0')) /* bingo! */
        return false;
    return true;
}
static void beginRecover (void) [static]
Definition at line 993 of file mrecover.c.
References alidNote, basenameFileFilterUPP, CURS_LATENT, modeFlags::Dialog, dirID, dlgThermo, dlogProgress, gameRefNum, initItem, itemizeThermo(), levRefNum, lock, memActivity, note(), modeFlags::Recover, saveRefNum, sfGetWhere, timeCursor, vRefNum, and WNDTHM.
Referenced by RecoverMenuEvent().
{
    SFTypeList levlType = {'LEVL'};
    SFReply sfGetReply;
    SFGetFile(sfGetWhere, "\p", basenameFileFilterUPP, 1, levlType,
                (DlgHookUPP) 0L, &sfGetReply);
    memActivity++;
    if (! sfGetReply.good)
        return;
    /* get volume (working directory) refnum, basename, and directory i.d. */
    vRefNum = sfGetReply.vRefNum;
    BlockMove(sfGetReply.fName, lock, sfGetReply.fName[0] + 1);
    {
        static CInfoPBRec catInfo;
        catInfo.hFileInfo.ioNamePtr = (StringPtr) sfGetReply.fName;
        catInfo.hFileInfo.ioVRefNum = sfGetReply.vRefNum;
        catInfo.hFileInfo.ioDirID = 0L;
        if (PBGetCatInfoSync(&catInfo))
        {
            note(noErr, alidNote, "\pSorry: Bad File Info");
            return;
        }
        dirID = catInfo.hFileInfo.ioFlParID;
    }
    /* open the progress thermometer dialog */
    (void) GetNewDialog(dlogProgress, (Ptr) &dlgThermo, (WindowPtr) -1L);
    if (ResError() || MemError())
        note(noErr, alidNote, "\pOops: Progress thermometer unavailable");
    else
    {
        in.Dialog = 1;
        memActivity++;
        itemizeThermo(initItem);
        ShowWindow(WNDTHM);
    }
    timeCursor = TickCount() + CURS_LATENT;
    saveRefNum = gameRefNum = levRefNum = -1;
    in.Recover = 1;
}
static void close_file (short * pFRefNum) [static]
Definition at line 1397 of file mrecover.c.
References alidNote, endRecover(), note(), and vRefNum.
Referenced by restore_savefile().
{
    if (FSClose(*pFRefNum) || FlushVol((StringPtr) 0L, vRefNum))
    {
        endRecover();
        note(noErr, alidNote, "\pSorry: File Close Error");
        return;
    }
    *pFRefNum = -1;
}
static void continueRecover (void) [static]
Definition at line 1045 of file mrecover.c.
References alidNote, modeFlags::Dialog, endRecover(), invalItem, itemizeThermo(), MAX_RECOVER_COUNT, note(), modeFlags::Recover, restore_savefile(), and saveRezStrings().
Referenced by eventLoop().
{
    restore_savefile();
    /* update the thermometer */
    if (in.Dialog && ! (in.Recover % 4))
        itemizeThermo(invalItem);
    if (in.Recover <= MAX_RECOVER_COUNT)
        return;
    endRecover();
    if (saveRezStrings())
        return;
    note(noErr, alidNote, "\pOK: Recovery succeeded");
}
static void cooldown (void) [static]
Definition at line 910 of file mrecover.c.
References endRecover(), modeFlags::Notify, modeFlags::Recover, and wnEvt.
Referenced by main(), note(), and RecoverMenuEvent().
{
    if (in.Recover)
        endRecover();
    /* wait for pending notifications to complete */
    while (in.Notify)
        (void) WaitNextEvent(0, &wnEvt, 3L, (RgnHandle) 0L);
    ExitToShell();
}
static void copy_bytes (short inRefNum, short outRefNum) [static]
Definition at line 1236 of file mrecover.c.
References alidNote, buf, endRecover(), memBytes::memIOBuf, note(), pIOBuf, read_levelfile(), modeFlags::Recover, and write_savefile().
Referenced by restore_savefile().
{
    char *buf = (char *) pIOBuf;
    long bufSiz = pBytes->memIOBuf;
    long nfrom, nto;
    do
    {
        nfrom = read_levelfile(inRefNum, buf, bufSiz);
        if (! in.Recover)
            return;
        nto = write_savefile(outRefNum, buf, nfrom);
        if (! in.Recover)
            return;
        if (nto != nfrom)
        {
            endRecover();
            note(noErr, alidNote, "\pSorry: File Copy Error");
            return;
        }
    }
    while (nfrom == bufSiz);
}
static short create_savefile (unsigned char * savename) [static]
Definition at line 1205 of file mrecover.c.
References alidNote, dirID, endRecover(), note(), savename, and vRefNum.
Referenced by restore_savefile().
{
    short fRefNum;
    /* translate savename to a pascal string (in place) */
    {
        unsigned char *pC;
        short nameLen;
        for (pC = savename; *pC; pC++);
        nameLen = pC - savename;
        for (; pC > savename; pC--)
            *pC = *(pC - 1);
        *savename = nameLen;
    }
    if (HCreate(vRefNum, dirID, savename, MAC_CREATOR, SAVE_TYPE)
        || HOpen(vRefNum, dirID, savename, fsRdWrPerm, &fRefNum))
    {
        endRecover();
        note(noErr, alidNote, "\pSorry: File Create Error");
        return (-1);
    }
    return fRefNum;
}
pascal void drawThermo (WindowPtr wPtr, short inum)
Definition at line 924 of file mrecover.c.
References drawItem, and itemizeThermo().
Referenced by main().
{
    itemizeThermo(drawItem);
}
static void endRecover (void) [static]
Definition at line 1066 of file mrecover.c.
References curs_Init, modeFlags::Dialog, dirID, dlgThermo, DLGTHM, gameRefNum, levRefNum, memActivity, oldCursor, modeFlags::Recover, savename, saveRefNum, and vRefNum.
Referenced by close_file(), continueRecover(), cooldown(), copy_bytes(), create_savefile(), eventLoop(), open_levelfile(), read_levelfile(), restore_savefile(), set_levelfile_name(), unlink_file(), and write_savefile().
{
    in.Recover = 0;
    oldCursor = curs_Init;
    SetCursor(&qd.arrow);
    /* clean up abandoned files */
    if (gameRefNum >= 0)
        (void) FSClose(gameRefNum);
    if (levRefNum >= 0)
        (void) FSClose(levRefNum);
    if (saveRefNum >= 0)
    {
        (void) FSClose(saveRefNum);
        (void) FlushVol((StringPtr) 0L, vRefNum);
        /* its corrupted so trash it ... */
        (void) HDelete(vRefNum, dirID, savename);
    }
    saveRefNum = gameRefNum = levRefNum = -1;
    /* close the progress thermometer dialog */
    in.Dialog = 0;
    CloseDialog(DLGTHM);
    DisposHandle(dlgThermo.items);
    memActivity++;
}
static void eventLoop (void) [static]
Definition at line 784 of file mrecover.c.
References adjustGUI(), adjustMemory(), alidNote, continueRecover(), modeFlags::Dialog, endRecover(), modeFlags::Front, memActivity, memBytes::memCleanup, notifRec::nmDispose, notifRec::nmNext, note(), modeFlags::Recover, RecoverMenuEvent(), thermoTHnd, where, and wnEvt.
Referenced by main().
{
    short wneMask = (in.Front ? everyEvent : (osMask + updateMask));
    long wneSleep = (in.Front ? 0L : 3L);
    while (1)
    {
        if (in.Front)
            adjustGUI();
        if (memActivity >= pBytes->memCleanup)
            adjustMemory();
        (void) WaitNextEvent(wneMask, &wnEvt, wneSleep, (RgnHandle) 0L);
        if (in.Dialog)
            (void) IsDialogEvent(&wnEvt);
        switch (wnEvt.what)
        {
        case osEvt:
            if (((wnEvt.message & osEvtMessageMask) >> 24) == suspendResumeMessage)
            {
                in.Front = (wnEvt.message & resumeFlag);
                wneMask = (in.Front ? everyEvent : (osMask + updateMask));
                wneSleep = (in.Front ? 0L : 3L);
            }
            break;
        case nullEvent:
            /* adjust the FIFO notification queue */
            if (pNMQ && pNMQ->nmDispose)
            {
                notifPtr pNMX = pNMQ->nmNext;
                DisposPtr((Ptr) pNMQ);
                pNMQ = pNMX;
                memActivity++;
            }
            if (in.Recover)
                continueRecover();
            break;
        case mouseDown:
            {
                WindowPtr whichWindow;
                
                switch(FindWindow(wnEvt . where , &whichWindow))
                {
                case inMenuBar:
                    RecoverMenuEvent(MenuSelect(wnEvt . where));
                    break;
                case inSysWindow:
                    SystemClick(&wnEvt, whichWindow);
                    break;
                case inDrag:
                    {
                        Rect boundsRect = qd.screenBits.bounds;
                        Point offsetPt;
                        InsetRect(&boundsRect, 4, 4);
                        boundsRect.top += GetMBarHeight();
                        DragWindow(whichWindow, * ((Point *) &wnEvt.where), &boundsRect);
                        boundsRect = whichWindow->portRect;
                        offsetPt = * (Point *) &(whichWindow->portBits.bounds);
                        OffsetRect(&boundsRect, -offsetPt.h, -offsetPt.v);
                        * (Rect *) *thermoTHnd = boundsRect;
                    }
                    break;
                }
            }
            break;
        case keyDown:
            {
                char key = (wnEvt.message & charCodeMask);
                if (wnEvt.modifiers & cmdKey)
                {
                    if (key == '.')
                    {
                        if (in.Recover)
                        {
                            endRecover();
                            note(noErr, alidNote, "\pSorry: Recovery aborted");
                        }
                    }
                    else
                        RecoverMenuEvent(MenuKey(key));
                }
            }
            break;
        /* without windows these events belong to our thermometer */
        case updateEvt:
        case activateEvt:
        {
            DialogPtr dPtr;
            short itemHit;
            (void) DialogSelect(&wnEvt, &dPtr, &itemHit);
        }
        case diskEvt:
            if (HiWord(wnEvt.message))
            {
                Point pt = {60, 60};
                (void) DIBadMount(pt, wnEvt.message);
                DIUnload();
                memActivity++;
            }
            break;
        } /* switch (wnEvt.what) */
    } /* while (1) */
}
static void itemizeThermo (short itemMode) [static]
Definition at line 931 of file mrecover.c.
References DLGTHM, drawItem, drawThermoUPP, GRFTHM, initItem, invalItem, modeFlags::Recover, and uitmThermo.
Referenced by beginRecover(), continueRecover(), and drawThermo().
{
    short iTyp, iTmp;
    Handle iHnd;
    Rect iRct;
    GetDItem(DLGTHM, uitmThermo, &iTyp, &iHnd, &iRct);
    switch(itemMode)
    {
    case initItem:
        SetDItem(DLGTHM, uitmThermo, iTyp, (Handle)
      drawThermoUPP, &iRct);
        break;
    case invalItem:
        {
            GrafPtr oldPort;
            GetPort(&oldPort);
            SetPort(GRFTHM);
            InsetRect(&iRct, 1, 1);
            InvalRect(&iRct);
            SetPort(oldPort);
        }
        break;
    case drawItem:
            FrameRect(&iRct);
            InsetRect(&iRct, 1, 1);
            iTmp = iRct.right;
            iRct.right = iRct.left + in.Recover;
            PaintRect(&iRct);
            iRct.left = iRct.right;
            iRct.right = iTmp;
            EraseRect(&iRct);
        break;
    }
}
main (void)
Definition at line 276 of file mrecover.c.
References alidNote, basenameFileFilter(), basenameFileFilterUPP, cooldown(), drawThermo(), drawThermoUPP, eventLoop(), nmCompletion(), nmCompletionUPP, sysEnv, and warmup().
{
    /* heap adjust */
    MaxApplZone();
    MoreMasters();
    MoreMasters();
    /* manager initialization */
    InitGraf(&qd.thePort);
    InitFonts();
    InitWindows();
    InitMenus();
    TEInit();
    InitDialogs(0L);
    InitCursor();
    nmCompletionUPP = NewNMProc(nmCompletion);
    basenameFileFilterUPP = NewFileFilterProc(
      basenameFileFilter);
    drawThermoUPP = NewUserItemProc(drawThermo);
    /* get system environment, notification requires 6.0 or better */
    (void) SysEnvirons(curSysEnvVers, &sysEnv);
    if (sysEnv.systemVersion < 0x0600)
    {
        ParamText("\pAbort: System 6.0 is required", "\p", "\p", "\p");
        (void) Alert(alidNote, (ModalFilterUPP) 0L);
        ExitToShell();
    }
    warmup();
    eventLoop();
    /* normally these routines are never reached from here */
    cooldown();
    ExitToShell();
    return 0;
}
pascal void nmCompletion (NMRec * pNMR)
Definition at line 490 of file mrecover.c.
Referenced by main().
{
    (void) NMRemove(pNMR);
    (* (short *) (pNMR->nmPending))--; /* decrement pending note level */
    ((notifPtr) pNMR)->nmDispose = 1; /* allow DisposPtr() */
}
static void note (short errorSignal, short alertID, unsigned char * msg) [static]
Definition at line 520 of file mrecover.c.
References cooldown(), modeFlags::Front, memBytes::memAbort, memActivity, notifRec::nmBuf, notifRec::nmNext, notifRec::nmr, nmt, noteErrorMessage(), and modeFlags::Notify.
Referenced by adjustMemory(), alignTemplate(), beginRecover(), close_file(), continueRecover(), copy_bytes(), create_savefile(), eventLoop(), noteErrorMessage(), open_levelfile(), optionMemStats(), read_levelfile(), RecoverMenuEvent(), restore_savefile(), saveRezStrings(), set_levelfile_name(), unlink_file(), and write_savefile().
{
    if (! errorSignal)
    {
        Size grow;
        if (MaxMem(&grow) < pBytes->memAbort)
            noteErrorMessage(msg, "\pOut of Memory");
    }
    if (errorSignal || !in.Front)
    {
        notifPtr pNMR;
        short i = nmt.nmBuf[0] + 1; /* insertion point */
        if (errorSignal) /* use notification template */
        {
            pNMR = &nmt;
            /* we're going to abort so add in this prefix */
            BlockMove("Abort: ", &nmt.nmBuf[i], 7);
            i += 7;
            nmt.nmBuf[0] += 7;
        }
        else /* allocate a notification record */
        {
            if (! (pNMR = (notifPtr) NewPtr(sizeof(notifRec))))
                noteErrorMessage(msg, "\pNil New Pointer");
            /* initialize it */
            *pNMR = nmt;
            pNMR->nmr.nmStr = (StringPtr) &(pNMR->nmBuf);
            /* update the notification queue */
            if (!pNMQ)
                pNMQ = pNMR;
            else
            {
                notifPtr pNMX;
                /* find the end of the queue */
                for (pNMX = pNMQ; pNMX->nmNext; pNMX = pNMX->nmNext)
                    ;
                pNMX->nmNext = pNMR;
            }
        }
        /* concatenate the message */
        BlockMove(&msg[1], &((pNMR->nmBuf)[i]), msg[0]);
        (pNMR->nmBuf)[0] += msg[0];
        in.Notify++; /* increase note pending level */
        NMInstall((NMRec *) pNMR);
        if (errorSignal)
            cooldown();
        return;
    }
    /* in front and no error so use an alert */
    ParamText(msg, "\p", "\p", "\p");
    (void) Alert(alertID, (ModalFilterUPP) 0L);
    ResetAlrtStage();
    memActivity++;
}
static void noteErrorMessage (unsigned char * msg, unsigned char * errMsg) [static]
Definition at line 503 of file mrecover.c.
References notifRec::nmBuf, and note().
Referenced by note().
{
    short i = nmt.nmBuf[0] + 1; /* insertion point */
    BlockMove(&msg[1], &nmt.nmBuf[i], msg[0]);
    nmt.nmBuf[i + msg[0]] = '\r';
    nmt.nmBuf[0] += (msg[0] + 1);
    note(memFullErr, 0, errMsg);
}
static short open_levelfile (long lev) [static]
Definition at line 1184 of file mrecover.c.
References alidNote, dirID, endRecover(), lock, note(), modeFlags::Recover, set_levelfile_name(), and vRefNum.
Referenced by restore_savefile().
{
    OSErr openErr;
    short fRefNum;
    set_levelfile_name(lev);
    if (! in.Recover)
        return (-1);
    if ((openErr = HOpen(vRefNum, dirID, lock, fsRdWrPerm, &fRefNum))
            && (openErr != fnfErr))
    {
        endRecover();
        note(noErr, alidNote, "\pSorry: File Open Error");
        return (-1);
    }
    return (openErr ? -1 : fRefNum);
}
static void optionMemStats (void) [static]
Definition at line 672 of file mrecover.c.
References adjustMemory(), alidNote, note(), and wnEvt.
Referenced by RecoverMenuEvent().
{
    unsigned char *pFormat = "\pFree:#k Max:#k Purge:#k Stack:#k";
    char *pSub = "#"; /* not a pascal string */
    unsigned char nBuf[16];
    long nStat, contig;
    Handle strHnd;
    long nOffset;
    short i;
    if (wnEvt.modifiers & shiftKey)
        adjustMemory();
    if (! (strHnd = NewHandle((Size) 128)))
    {
        note(noErr, alidNote, "\pOops: Memory stats unavailable!");
        return;
    }
    
    SetString((StringHandle) strHnd, pFormat);
    nOffset = 1L;
    for (i = 1; i <= 4; i++)
    {
        /* get the replacement number stat */
        switch (i)
        {
        case 1: nStat = FreeMem(); break;
        case 2: nStat = MaxBlock(); break;
        case 3: PurgeSpace(&nStat, &contig); break;
        case 4: nStat = StackSpace(); break;
        }
        NumToString((nStat >> 10), * (Str255 *) &nBuf);
        **strHnd += nBuf[0] - 1;
        nOffset = Munger(strHnd, nOffset, (Ptr) pSub, 1L, (Ptr) &nBuf[1], nBuf[0]);
    }
    MoveHHi(strHnd);
    HLock(strHnd);
    note(noErr, alidNote, (unsigned char *) *strHnd);
    DisposHandle(strHnd);
}
static long read_levelfile (short rdRefNum, Ptr bufPtr, long count) [static]
Definition at line 1366 of file mrecover.c.
References alidNote, count, endRecover(), and note().
Referenced by copy_bytes(), and restore_savefile().
{
    OSErr rdErr;
    long rdCount = count;
    if ((rdErr = FSRead(rdRefNum, &rdCount, bufPtr)) && (rdErr != eofErr))
    {
        endRecover();
        note(noErr, alidNote, "\pSorry: File Read Error");
        return (-1L);
    }
    return rdCount;
}
static void RecoverMenuEvent (long menuEntry) [static]
Definition at line 718 of file mrecover.c.
References aboutBuf, alertAppleMenu, beginRecover(), cooldown(), memActivity, menuApple, mHnd, mitmAbout, mitmClose_DA, mitmHelp, mitmOpen, mitmQuit, muidApple, muidEdit, muidFile, note(), optionMemStats(), and wnEvt.
Referenced by eventLoop().
{
    short menuID = HiWord(menuEntry);
    short menuItem = LoWord(menuEntry);
    switch (menuID)
    {
    case muidApple:
        switch (menuItem)
        {
        case mitmAbout:
            if (wnEvt.modifiers & optionKey)
                optionMemStats();
            /* fall thru */
        case mitmHelp:
            note(noErr, (alertAppleMenu + menuItem), aboutBuf);
            break;
        default: /* DA's or apple menu items */
            {
                unsigned char daName[32];
                GetItem(mHnd[menuApple], menuItem, * (Str255 *) &daName);
                (void) OpenDeskAcc(daName);
                memActivity++;
            }
            break;
        }
        break;
    case muidFile:
        switch (menuItem)
        {
        case mitmOpen:
            beginRecover();
            break;
        case mitmClose_DA:
            {
                WindowPeek frontWindow;
                short refNum;
                if (frontWindow = (WindowPeek) FrontWindow())
                    if ((refNum = frontWindow->windowKind) < 0)
                        CloseDeskAcc(refNum);
                memActivity++;
            }
            break;
        case mitmQuit:
            cooldown();
            break;
        }
        break;
    case muidEdit:
        (void) SystemEdit(menuItem - 1);
        break;
    }
    HiliteMenu(0);
}
static void restore_savefile (void) [static]
Definition at line 1264 of file mrecover.c.
References alidNote, close_file(), copy_bytes(), create_savefile(), endRecover(), gameRefNum, hpid, levRefNum, lock, MAX_RECOVER_COUNT, note(), open_levelfile(), read_levelfile(), modeFlags::Recover, savelev(), savename, saveRefNum, set_levelfile_name(), unlink_file(), and write_savefile().
Referenced by continueRecover().
{
    static int savelev;
    long saveTemp, lev;
    xchar levc;
    struct version_info version_data;
    /* level 0 file contains:
     * pid of creating process (ignored here)
     * level number for current level of save file
     * name of save file nethack would have created
     * and game state
     */
    lev = in.Recover - 1;
    if (lev == 0L)
    {
        gameRefNum = open_levelfile(0L);
        if (in.Recover)
            (void) read_levelfile(gameRefNum, (Ptr) &
      hpid, sizeof(hpid));
        if (in.Recover)
            saveTemp = read_levelfile(gameRefNum, (Ptr) &savelev, sizeof(savelev));
        if (in.Recover && (saveTemp != sizeof(savelev)))
        {
            endRecover();
            note(noErr, alidNote, "\pSorry: \"checkpoint\" was not enabled");
            return;
        }
        if (in.Recover)
            (void) read_levelfile(gameRefNum, (Ptr)
      savename, sizeof(savename));
        if (in.Recover)
            (void) read_levelfile(gameRefNum,
                    (Ptr) &version_data, sizeof version_data);
        /* save file should contain:
         * current level (including pets)
         * (non-level-based) game state
         * other levels
         */
        if (in.Recover)
            saveRefNum = create_savefile(savename);
        if (in.Recover)
            levRefNum = open_levelfile(savelev);
        if (in.Recover)
            (void) write_savefile(saveRefNum,
                    (Ptr) &version_data, sizeof version_data);
        if (in.Recover)
            copy_bytes(levRefNum, saveRefNum);
        if (in.Recover)
            close_file(&levRefNum);
        if (in.Recover)
            unlink_file(lock);
        if (in.Recover)
            copy_bytes(gameRefNum, saveRefNum);
        if (in.Recover)
            close_file(&gameRefNum);
        if (in.Recover)
            set_levelfile_name(0L);
        if (in.Recover)
            unlink_file(lock);
    }
    else if (lev != savelev)
    {
        levRefNum = open_levelfile(lev);
        if (levRefNum >= 0)
        {
            /* any or all of these may not exist */
            levc = (xchar) lev;
            (void) write_savefile(saveRefNum, (Ptr) &levc, sizeof(levc));
            if (in.Recover)
                copy_bytes(levRefNum, saveRefNum);
            if (in.Recover)
                close_file(&levRefNum);
            if (in.Recover)
                unlink_file(lock);
        }
    }
    if (in.Recover == MAX_RECOVER_COUNT)
        close_file(&saveRefNum);
    if (in.Recover)
        in.Recover++;
}
static short saveRezStrings (void) [static]
Definition at line 1099 of file mrecover.c.
References alidNote, APP_NAME_RES_ID, dirID, hpid, memActivity, note(), PLAYER_NAME_RES_ID, savename, and vRefNum.
Referenced by continueRecover().
{
    short sRefNum;
    StringHandle strHnd;
    short i, rezID;
    unsigned char *plName;
    HCreateResFile(vRefNum, dirID, savename);
    sRefNum = HOpenResFile(vRefNum, dirID, savename, fsRdWrPerm);
    if (sRefNum <= 0)
    {
        note(noErr, alidNote, "\pOK: Minor resource map error");
        return 1;
    }
    /* savename and hpid get mutilated here... */
    plName = savename + 5; /* save/ */
    *savename -= 5;
    do
    {
        plName++;
        (*savename)--;
        hpid /= 10;
    }
    while (hpid);
    *plName = *savename;
    for (i = 1; i <= 2; i++)
    {
        switch (i)
        {
        case 1:
            rezID = PLAYER_NAME_RES_ID;
            strHnd = NewString(* (Str255 *) plName);
            break;
        case 2:
            rezID = APP_NAME_RES_ID;
            strHnd = NewString(* (Str255 *) "\pNetHack");
            break;
        }
        if (! strHnd)
        {
            note(noErr, alidNote, "\pOK: Minor \'STR \' resource error");
            CloseResFile(sRefNum);
            return 1;
        }
        /* should check for errors... */
        AddResource((Handle) strHnd, 'STR ', rezID, * (Str255 *) "\p");
    }
    memActivity++;
    /* should check for errors... */
    CloseResFile(sRefNum);
    return 0;
}
static void set_levelfile_name (long lev) [static]
Definition at line 1161 of file mrecover.c.
References alidNote, endRecover(), lock, and note().
Referenced by open_levelfile(), and restore_savefile().
{
    unsigned char *tf;
    /* find the dot. this is guaranteed to happen. */
    for (tf = (lock + *lock); *tf != '.'; tf--, lock[0]--)
        ;
    /* append the level number string (pascal) */
    if (tf > lock)
    {
        NumToString(lev, * (Str255 *) tf);
        lock[0] += *tf;
        *tf = '.';
    }
    else /* huh??? */
    {
        endRecover();
        note(noErr, alidNote, "\pSorry: File Name Error");
    }
}
static void unlink_file (unsigned char * filename) [static]
Definition at line 1410 of file mrecover.c.
References alidNote, dirID, endRecover(), note(), and vRefNum.
Referenced by restore_savefile().
{
    if (HDelete(vRefNum, dirID, filename))
    {
        endRecover();
        note(noErr, alidNote, "\pSorry: File Delete Error");
        return;
    }
}
static void warmup (void) [static]
Definition at line 314 of file mrecover.c.
References count, modeFlags::Front, notifRec::nmBuf, nmCompletionUPP, notifRec::nmr, modeFlags::Notify, NULL, and wnEvt.
Referenced by main().
{
    short i;
    /* pre-System 7 MultiFinder hack for smooth launch */
    for (i = 0; i < 10; i++)
    {
        if (WaitNextEvent(osMask, &wnEvt, 2L, (RgnHandle) 0L))
            if (((wnEvt.message & osEvtMessageMask) >> 24) == suspendResumeMessage)
                in.Front = (wnEvt.message & resumeFlag);
    }
#if 0 // ???
    /* clear out the Finder info */
    {
        short message, count;
        CountAppFiles(&message, &count);
        while(count)
            ClrAppFiles(count--);
    }
#endif
    /* fill out the notification template */
    nmt.nmr.qType = nmType;
    nmt.nmr.nmMark = 1;
    nmt.nmr.nmSound = (Handle) -1L; /* system beep */
    nmt.nmr.nmStr = nmt.nmBuf;
    nmt.nmr.nmResp = nmCompletionUPP;
    nmt.nmr.nmPending = (long) &in.Notify;
#if 1
    {
        /* get the app name */
        ProcessInfoRec info;
        ProcessSerialNumber psn;
        info.processInfoLength = sizeof(info);
        info.processName = nmt.nmBuf;
        info.processAppSpec = NULL;
        GetCurrentProcess(&psn);
        GetProcessInformation(&psn, &info);
    }
#else
    /* prepend app name (31 chars or less) to notification buffer */
    {
        short apRefNum;
        Handle apParams;
        GetAppParms(* (Str255 *) &nmt.nmBuf, &apRefNum, &apParams);
    }
#endif
    /* add formatting (two line returns) */
    nmt.nmBuf[++(nmt.nmBuf[0])] = '\r';
    nmt.nmBuf[++(nmt.nmBuf[0])] = '\r';
    /**** note() is usable now but not aesthetically complete ****/
    /* get notification icon */
    if (sysEnv.systemVersion < 0x0700)
    {
        if (! (nmt.nmr.nmIcon = GetResource('SICN', iconNotifyID)))
            note(nilHandleErr, 0, "\pNil SICN Handle");
    }
    else
    {
        if (GetIconSuite(&nmt.nmr.nmIcon, iconNotifyID,
      ics_1_and_4))
            note(nilHandleErr, 0, "\pBad Icon Family");
    }
    /* load and align various dialog/alert templates */
    (void) alignTemplate('ALRT', alidNote, 0, 4, (Point *) 0L);
    (void) alignTemplate('ALRT', alidHelp, 0, 4, (Point *) 0L);
    thermoTHnd = (DialogTHndl) alignTemplate('DLOG',
      dlogProgress, 20, 8, (Point *) 0L);
    (void) alignTemplate('DLOG', getDlgID, 0, 6, (Point *) &
      sfGetWhere);
    /* get the "busy cursors" (preloaded/locked) */
    for (i = 0; i < curs_Total; i++)
    {
        CursHandle cHnd;
        if (! (cHnd = GetCursor(i + cursorOffset)))
            note(nilHandleErr, 0, "\pNil CURS Handle");
        cPtr[i] = *cHnd;
    }
    /* get the 'vers' 1 long (Get Info) string - About Recover... */
    {
        versXHandle vHnd;
        if (! (vHnd = (versXHandle) GetResource('vers', 1)))
            note(nilHandleErr, 0, "\pNil vers Handle");
        i = (**vHnd).versStr[0] + 1; /* offset to Get Info pascal string */
        if ((aboutBuf[0] = (**vHnd).versStr[i]) > (aboutBufSize - 1))
            aboutBuf[0] = aboutBufSize - 1;
        i++;
        MoveHHi((Handle) vHnd); /* DEE - Fense ... */
        HLock((Handle) vHnd);
        BlockMove(&((**vHnd).versStr[i]), &(aboutBuf[1]), aboutBuf[0]);
        ReleaseResource((Handle) vHnd);
    }
    /* form the menubar */
    for (i = 0; i < menu_Total; i++)
    {
        if (! (mHnd[i] = GetMenu(i + muidApple)))
            note(nilHandleErr, 0, "\pNil MENU Handle");
        /* expand the apple menu */
        if (i == menuApple)
            AddResMenu(mHnd[menuApple], 'DRVR');
        InsertMenu(mHnd[i], 0);
    }
    /* pre-emptive memory check */
    {
        memBytesHandle hBytes;
        Size grow;
        if (! (hBytes = (memBytesHandle) GetResource('memB',
      membID)))
            note(nilHandleErr, 0, "\pNil Memory Handle");
        pBytes = *hBytes;
        if (MaxMem(&grow) < pBytes->memPreempt)
            note(memFullErr, 0, "\pMore Memory Required\rTry adding 16k");
        memActivity = pBytes->memCleanup; /* force initial cleanup */
    }
    /* get the I/O buffer */
    if (! (pIOBuf = NewPtr(pBytes->memIOBuf)))
        note(memFullErr, 0, "\pNil I/O Pointer");
}
static long write_savefile (short wrRefNum, Ptr bufPtr, long count) [static]
Definition at line 1382 of file mrecover.c.
References alidNote, count, endRecover(), and note().
Referenced by copy_bytes(), and restore_savefile().
{
    long wrCount = count;
    if (FSWrite(wrRefNum, &wrCount, bufPtr))
    {
        endRecover();
        note(noErr, alidNote, "\pSorry: File Write Error");
        return (-1L);
    }
    return wrCount;
}
Variable Documentation
unsigned char aboutBuf[aboutBufSize]
Definition at line 200 of file mrecover.c.
Referenced by RecoverMenuEvent().
FileFilterUPP basenameFileFilterUPP
Definition at line 220 of file mrecover.c.
Referenced by beginRecover(), and main().
CursPtr cPtr[curs_Total]
Definition at line 204 of file mrecover.c.
Referenced by adjustGUI().
long dirID
Definition at line 218 of file mrecover.c.
Referenced by beginRecover(), create_savefile(), endRecover(), open_levelfile(), saveRezStrings(), and unlink_file().
DialogRecord dlgThermo
Definition at line 210 of file mrecover.c.
Referenced by beginRecover(), and endRecover().
UserItemUPP drawThermoUPP
Definition at line 221 of file mrecover.c.
Referenced by itemizeThermo(), and main().
short gameRefNum
Definition at line 235 of file mrecover.c.
Referenced by beginRecover(), endRecover(), and restore_savefile().
int hpid
Definition at line 233 of file mrecover.c.
Referenced by getlev(), restore_savefile(), and saveRezStrings().
modeFlags in = {1}
Definition at line 197 of file mrecover.c.
Referenced by main(), restore_savefile(), and tc_find().
short levRefNum
Definition at line 236 of file mrecover.c.
Referenced by beginRecover(), endRecover(), and restore_savefile().
unsigned char lock[256]
Definition at line 231 of file mrecover.c.
Referenced by beginRecover(), open_levelfile(), restore_savefile(), and set_levelfile_name().
unsigned short memActivity
Definition at line 202 of file mrecover.c.
Referenced by adjustMemory(), beginRecover(), endRecover(), eventLoop(), note(), RecoverMenuEvent(), and saveRezStrings().
MenuHandle mHnd[menu_Total]
Definition at line 203 of file mrecover.c.
Referenced by adjustGUI(), and RecoverMenuEvent().
NMUPP nmCompletionUPP
Definition at line 219 of file mrecover.c.
Referenced by main(), and warmup().
notifRec nmt
Definition at line 208 of file mrecover.c.
Referenced by note().
short oldCursor = curs_Init
Definition at line 206 of file mrecover.c.
Referenced by adjustGUI(), and endRecover().
memBytesPtr pBytes
Definition at line 201 of file mrecover.c.
Ptr pIOBuf
Definition at line 216 of file mrecover.c.
Referenced by copy_bytes().
notifPtr pNMQ
Definition at line 207 of file mrecover.c.
unsigned char savename[SAVESIZE]
Definition at line 230 of file mrecover.c.
Referenced by create_savefile(), endRecover(), restore_savefile(), and saveRezStrings().
short saveRefNum
Definition at line 234 of file mrecover.c.
Referenced by beginRecover(), endRecover(), and restore_savefile().
Point sfGetWhere
Definition at line 215 of file mrecover.c.
Referenced by beginRecover().
SysEnvRec sysEnv
Definition at line 199 of file mrecover.c.
Referenced by main().
DialogTHndl thermoTHnd
Definition at line 209 of file mrecover.c.
Referenced by eventLoop().
unsigned long timeCursor
Definition at line 205 of file mrecover.c.
Referenced by adjustGUI(), and beginRecover().
short vRefNum
Definition at line 217 of file mrecover.c.
Referenced by beginRecover(), close_file(), create_savefile(), endRecover(), open_levelfile(), saveRezStrings(), and unlink_file().
EventRecord wnEvt
Definition at line 198 of file mrecover.c.
Referenced by cooldown(), eventLoop(), optionMemStats(), RecoverMenuEvent(), and warmup().