nethack/sys/mac/mttymain.c File Reference
#include `hack.h`
*
#include `macwin.h`
*
#include `mttypriv.h`
*
#include `mactty.h`
*
#include `wintty.h`
*
#include <Palettes.h>
*
Macros
#define MT_WINDOW 135
#define MT_WIDTH 80
#define MT_HEIGHT 24
Functions
static void _mt_init_stuff (void)
int tgetch (void)
void getreturn (char *str)
int has_color (int color)
void tty_delay_output (void)
void cmov (int x, int y)
void nocmov (int x, int y)
static void _mt_set_colors (long *colors)
void term_end_attr (int attr)
void term_start_attr (int attr)
void standoutend (void)
void standoutbeg (void)
void term_end_color (void)
void cl_end (void)
void clear_screen (void)
void cl_eos (void)
void home (void)
void backsp (void)
void msmsg (const char *str,...)
void term_end_raw_bold (void)
void term_start_raw_bold (void)
void term_start_color (int color)
void setftty (void)
void tty_startup (int *width, int *height)
void gettty (void)
void settty (const char *str)
void tty_number_pad (int arg)
void tty_start_screen (void)
void tty_end_screen (void)
void xputs (const char *str)
int term_puts (const char *str)
int term_putc (int c)
int term_flush (void *desc)
Variables
static long _mt_attrs [5][2]
static char _attrs_inverse [5]
static long _mt_colors [CLR_MAX][2]
static char _colors_inverse [CLR_MAX]
struct DisplayDesc * ttyDisplay
char kill_char = CHAR_ESC
char erase_char = CHAR_BS
WindowRef _mt_window = (WindowRef) 0
static Boolean _mt_in_color = 0
short win_fonts [NHW_TEXT+1]
Macro Definition Documentation
#define MT_HEIGHT 24
Definition at line 17 of file mttymain.c.
Referenced by _mt_init_stuff().
#define MT_WIDTH 80
Definition at line 16 of file mttymain.c.
Referenced by _mt_init_stuff().
#define MT_WINDOW 135
Definition at line 15 of file mttymain.c.
Function Documentation
static void _mt_init_stuff (void) [static]
Definition at line 193 of file mttymain.c.
References _mt_colors, clear_tty(), CO, create_tty(), dprintf(), error(), get_tty_attrib(), get_tty_metrics(), iflags, init_tty_number(), InitMenuRes(), kMapWindow, LI, MT_HEIGHT, MT_WIDTH, window_procs::name, NHW_MAP, NO_COLOR, RetrievePosition(), set_tty_attrib(), small_screen, TA_ALWAYS_REFRESH, TA_BLINKING_CURSOR, TA_NL_ADD_CR, TA_WRAP_AROUND, TTY_ATTRIB_BACKGROUND, TTY_ATTRIB_CURSOR, TTY_ATTRIB_FLAGS, TTY_ATTRIB_FOREGROUND, instance_flags::wc_fontsiz_map, WIN_BASE_KIND, and windowprocs.
Referenced by tty_startup().
                      {
long resp, flag;
short num_cols, num_rows, win_width, win_height, font_num, font_size;
short char_width, row_height;
short hor, vert;
    LI = MT_HEIGHT;
    CO = MT_WIDTH;
    if (!strcmp(windowprocs.name, "mac")) {
        dprintf ("Mac Windows");
        LI -= 1;
    } else {
        dprintf ("TTY Windows");
    }
    
    /*
     * If there is at least one screen CAPABLE of color, and if
     * 32-bit QD is there, we use color. 32-bit QD is needed for the
     * offscreen GWorld
     */
    if (!Gestalt (gestaltQuickdrawVersion, &resp) && resp > 0x1ff) {
        GDHandle gdh = GetDeviceList ();
        while (gdh) {
            if (TestDeviceAttribute (gdh, screenDevice)) {
                if (HasDepth (gdh, 4, 1, 1) ||
                    HasDepth (gdh, 8, 1, 1) ||
                    HasDepth (gdh, 16, 1, 1) ||
                    HasDepth (gdh, 32, 1, 1)) {
                    _mt_in_color = 1;
                    break;
                }
            }
            gdh = GetNextDevice (gdh);
        }
    }
    if (create_tty (&_mt_window, WIN_BASE_KIND +
      NHW_MAP, _mt_in_color) != noErr)
        error("_mt_init_stuff: Couldn't create tty.");
    SetWindowKind(_mt_window, WIN_BASE_KIND + NHW_MAP);
    SelectWindow(_mt_window);
    SetPortWindowPort(_mt_window);
    SetOrigin(-1, -1);
    font_size = iflags.wc_fontsiz_map ? iflags.
      wc_fontsiz_map :
        (iflags.large_font && !small_screen) ? 12 : 9;
    if (init_tty_number (_mt_window, win_fonts [
      NHW_MAP], font_size, CO, LI) != noErr)
        error("_mt_init_stuff: Couldn't init tty.");
    if (get_tty_metrics (_mt_window, &num_cols, &num_rows, &win_width ,
        &win_height, &font_num, &font_size, &char_width, &row_height))
        error("_mt_init_stuff: Couldn't get tty metrics.");
    SizeWindow (_mt_window, win_width + 2, win_height + 2, 1);
    if (RetrievePosition (kMapWindow, &vert, &hor)) {
        dprintf ("Moving window to (%d,%d)", hor, vert);
        MoveWindow (_mt_window, hor, vert, 1);
    }
    ShowWindow (_mt_window);
    /* Start in raw, always flushing mode */
    get_tty_attrib(_mt_window, TTY_ATTRIB_FLAGS, &flag);
    flag |= TA_ALWAYS_REFRESH | TA_WRAP_AROUND;
    set_tty_attrib(_mt_window, TTY_ATTRIB_FLAGS, flag);
    get_tty_attrib(_mt_window, TTY_ATTRIB_CURSOR, &flag);
    flag |= (TA_BLINKING_CURSOR | TA_NL_ADD_CR);
    set_tty_attrib(_mt_window, TTY_ATTRIB_CURSOR, flag);
    set_tty_attrib(_mt_window, TTY_ATTRIB_FOREGROUND,
      _mt_colors[NO_COLOR][0]);
    set_tty_attrib(_mt_window, TTY_ATTRIB_BACKGROUND,
      _mt_colors[NO_COLOR][1]);
    clear_tty (_mt_window);
    InitMenuRes ();
}
static void _mt_set_colors (long * colors) [static]
Definition at line 357 of file mttymain.c.
References set_tty_attrib(), TTY_ATTRIB_BACKGROUND, and TTY_ATTRIB_FOREGROUND.
Referenced by cl_end(), cl_eos(), clear_screen(), term_end_attr(), term_end_color(), term_start_attr(), and term_start_color().
                              {
short err;
    if (!_mt_in_color) {
        return;
    }
    err = set_tty_attrib (_mt_window,
      TTY_ATTRIB_FOREGROUND, colors [0]);
    err = set_tty_attrib (_mt_window,
      TTY_ATTRIB_BACKGROUND, colors [1]);
}
void backsp (void)
Definition at line 447 of file mttymain.c.
References add_tty_string(), CHAR_BLANK, CHAR_BS, and update_tty().
              {
char eraser [] = { CHAR_BS, CHAR_BLANK, CHAR_BS, 0 };
short err;
    err = add_tty_string (_mt_window, eraser);
    err = update_tty (_mt_window);
}
void cl_end (void)
Definition at line 418 of file mttymain.c.
References _mt_attrs, _mt_set_colors(), clear_tty_window(), CO, DisplayDesc::curx, and DisplayDesc::cury.
              {
    _mt_set_colors (_mt_attrs [0]);
    clear_tty_window (_mt_window, ttyDisplay->
      curx, ttyDisplay->cury,
        CO - 1, ttyDisplay->cury);
}
void cl_eos (void)
Definition at line 433 of file mttymain.c.
References _mt_attrs, _mt_set_colors(), clear_tty_window(), CO, DisplayDesc::curx, DisplayDesc::cury, and LI.
              {
    _mt_set_colors (_mt_attrs [0]);
    clear_tty_window (_mt_window, ttyDisplay->
      curx, ttyDisplay->cury, CO - 1,
        LI - 1);
}
void clear_screen (void)
Definition at line 426 of file mttymain.c.
References _mt_attrs, _mt_set_colors(), and clear_tty().
Referenced by mac_exit_nhwindows().
                    {
    _mt_set_colors (_mt_attrs [0]);
    clear_tty (_mt_window);
}
void cmov (int x, int y)
Definition at line 343 of file mttymain.c.
References DisplayDesc::curx, DisplayDesc::cury, and move_tty_cursor().
Referenced by home(), and nocmov().
                    {
    move_tty_cursor (_mt_window, x, y);
    ttyDisplay->cury = y;
    ttyDisplay->curx = x;
}
void getreturn (char * str)
Definition at line 293 of file mttymain.c.
References msmsg(), and tgetch().
Referenced by terminate().
                      {
    FlushEvents (-1, 0);
    msmsg ("Press space %s", str);
    (void) tgetch ();
}
void gettty (void)
Definition at line 512 of file mttymain.c.
              {
}
int has_color (int color)
Definition at line 301 of file mttymain.c.
                      {
#if defined(__SC__) || defined(__MRC__)
# pragma unused(color)
#endif
    Rect r;
// Point p = {0, 0};
    GDHandle gh;
    if (!_mt_in_color)
        return 0;
    GetWindowBounds(_mt_window, kWindowContentRgn, &r);
// SetPortWindowPort(_mt_window);
// LocalToGlobal (&p);
// OffsetRect (&r, p.h, p.v);
    gh = GetMaxDevice (&r);
    if (!gh) {
        return 0;
    }
    return (*((*gh)->gdPMap))->pixelSize > 4; /* > 4 bpp */
}
void home (void)
Definition at line 441 of file mttymain.c.
References cmov().
            {
    cmov (0,0);
}
void msmsg (const char * str, ...)
Definition at line 457 of file mttymain.c.
References buf, and xputs().
Referenced by getreturn().
                             {
va_list args;
char buf [1000];
    va_start (args, str);
    vsprintf (buf, str, args);
    va_end (args);
    xputs (buf);
}
void nocmov (int x, int y)
Definition at line 351 of file mttymain.c.
References cmov().
                      {
    cmov (x, y);
}
void setftty (void)
Definition at line 490 of file mttymain.c.
References instance_flags::cbreak, get_tty_attrib(), iflags, set_tty_attrib(), TA_ALWAYS_REFRESH, TA_INHIBIT_VERT_SCROLL, and TTY_ATTRIB_FLAGS.
{
    long flag;
    /* Buffered output for the game */
    get_tty_attrib (_mt_window, TTY_ATTRIB_FLAGS, &flag);
    flag &= ~ TA_ALWAYS_REFRESH;
    flag |= TA_INHIBIT_VERT_SCROLL; /* don't scroll */
    set_tty_attrib (_mt_window, TTY_ATTRIB_FLAGS, flag);
    iflags.cbreak = 1;
}
void settty (const char * str)
Definition at line 517 of file mttymain.c.
References get_tty_attrib(), set_tty_attrib(), TA_ALWAYS_REFRESH, TA_INHIBIT_VERT_SCROLL, TTY_ATTRIB_FLAGS, tty_raw_print(), and update_tty().
{
    long flag;
    update_tty (_mt_window);
    /* Buffered output for the game, raw in "raw" mode */
    get_tty_attrib(_mt_window, TTY_ATTRIB_FLAGS, &flag);
    flag &= ~ TA_INHIBIT_VERT_SCROLL; /* scroll */
    flag |= TA_ALWAYS_REFRESH;
    set_tty_attrib(_mt_window, TTY_ATTRIB_FLAGS, flag);
    tty_raw_print ("\n");
    if (str) {
        tty_raw_print (str);
    }
}
void standoutbeg (void)
Definition at line 406 of file mttymain.c.
References ATR_INVERSE, and term_start_attr().
                   {
    term_start_attr (ATR_INVERSE);
}
void standoutend (void)
Definition at line 400 of file mttymain.c.
References ATR_INVERSE, and term_end_attr().
                   {
    term_end_attr (ATR_INVERSE);
}
void term_end_attr (int attr)
Definition at line 369 of file mttymain.c.
References _mt_attrs, and _mt_set_colors().
Referenced by standoutend(), and term_end_raw_bold().
                         {
#if defined(__SC__) || defined(__MRC__)
# pragma unused (attr)
#endif
    _mt_set_colors (_mt_attrs [0]);
}
void term_end_color (void)
Definition at line 412 of file mttymain.c.
References _mt_colors, _mt_set_colors(), and NO_COLOR.
                      {
    _mt_set_colors (_mt_colors [NO_COLOR]);
}
void term_end_raw_bold (void)
Definition at line 470 of file mttymain.c.
References ATR_INVERSE, and term_end_attr().
                         {
    term_end_attr (ATR_INVERSE);
}
int term_flush (void * desc)
Definition at line 578 of file mttymain.c.
References stdout, and update_tty().
                        {
    if (desc == stdout || desc == stderr) {
        update_tty (_mt_window);
    } else {
        impossible ("Substituted flush for file");
        return fflush (desc);
    }
    return 0;
}
int term_putc (int c)
Definition at line 569 of file mttymain.c.
References add_tty_char().
                  {
short err;
    err = add_tty_char (_mt_window, c);
    return err ? EOF : c;
}
int term_puts (const char * str)
Definition at line 562 of file mttymain.c.
References xputs().
                            {
    xputs (str);
    return strlen (str);
}
void term_start_attr (int attr)
Definition at line 378 of file mttymain.c.
References _mt_attrs, _mt_set_colors(), ATR_BLINK, ATR_BOLD, ATR_INVERSE, and ATR_ULINE.
Referenced by standoutbeg(), and term_start_raw_bold().
                           {
    switch (attr) {
        case ATR_ULINE:
            _mt_set_colors (_mt_attrs [1]);
            break;
        case ATR_BOLD:
            _mt_set_colors (_mt_attrs [2]);
            break;
        case ATR_BLINK:
            _mt_set_colors (_mt_attrs [3]);
            break;
        case ATR_INVERSE:
            _mt_set_colors (_mt_attrs [4]);
            break;
        default:
            _mt_set_colors (_mt_attrs [0]);
            break;
    }
}
void term_start_color (int color)
Definition at line 482 of file mttymain.c.
References _mt_colors, and _mt_set_colors().
                             {
    if (color >= 0 && color < CLR_MAX) {
        _mt_set_colors (_mt_colors [color]);
    }
}
void term_start_raw_bold (void)
Definition at line 476 of file mttymain.c.
References ATR_INVERSE, and term_start_attr().
                           {
    term_start_attr (ATR_INVERSE);
}
int tgetch (void)
Definition at line 271 of file mttymain.c.
References blink_cursor(), CHAR_CR, CHAR_LF, GetFromKeyQueue(), and HandleEvent().
Referenced by getreturn().
              {
EventRecord event;
long sleepTime = 0;
int ret = 0;
    for (;!ret;) {
        WaitNextEvent (-1, &event, sleepTime, 0);
        HandleEvent (&event);
        blink_cursor (_mt_window, event.when);
        if (event.what == nullEvent) {
            sleepTime = GetCaretTime ();
        } else {
            sleepTime = 0;
        }
        ret = GetFromKeyQueue ();
        if (ret == CHAR_CR) ret = CHAR_LF;
    }
    return ret;
}
void tty_delay_output (void)
Definition at line 328 of file mttymain.c.
References blink_cursor(), and HandleEvent().
                        {
EventRecord event;
long toWhen = TickCount () + 3;
    while (TickCount () < toWhen) {
        WaitNextEvent (updateMask, &event, 3L, 0);
        if (event.what == updateEvt) {
            HandleEvent (&event);
            blink_cursor (_mt_window, event.when);
        }
    }
}
void tty_end_screen (void)
Definition at line 551 of file mttymain.c.
                      {
}
void tty_number_pad (int arg)
Definition at line 537 of file mttymain.c.
                         {
#if defined(__SC__) || defined(__MRC__)
# pragma unused(arg)
#endif
}
void tty_start_screen (void)
Definition at line 545 of file mttymain.c.
References instance_flags::cbreak, and iflags.
                        {
    iflags.cbreak = 1;
}
void tty_startup (int * width, int * height)
Definition at line 504 of file mttymain.c.
References _mt_init_stuff(), CO, and LI.
                                       {
    _mt_init_stuff ();
    *width = CO;
    *height = LI;
}
void xputs (const char * str)
Definition at line 556 of file mttymain.c.
References add_tty_string().
Referenced by msmsg(), and term_puts().
                        {
    add_tty_string (_mt_window, str);
}
Variable Documentation
char _attrs_inverse[5] [static]
Initial value:
= {
    0, 0, 0, 0, 0 ,
}
Definition at line 36 of file mttymain.c.
char _colors_inverse[CLR_MAX] [static]
Initial value:
= {
    1, 0, 0, 0 ,
    0, 0, 0, 0 ,
    0, 0, 0, 0 ,
    0, 0, 0, 0 ,
}
Definition at line 62 of file mttymain.c.
long _mt_attrs[5][2] [static]
Initial value:
= {
    { 0x000000, 0xffffff },
    { 0xff8080, 0xffffff },
    { 0x40c020, 0xe0e0e0 },
    { 0x003030, 0xff0060 },
    { 0xff8888, 0x000000 },
}
Definition at line 27 of file mttymain.c.
Referenced by cl_end(), cl_eos(), clear_screen(), term_end_attr(), and term_start_attr().
long _mt_colors[CLR_MAX][2] [static]
Initial value:
= {
    { 0x000000, 0x808080 },
    { 0x880000, 0xffffff },
    { 0x008800, 0xffffff },
    { 0x553300, 0xffffff },
    { 0x000088, 0xffffff },
    { 0x880088, 0xffffff },
    { 0x008888, 0xffffff },
    { 0x888888, 0xffffff },
    { 0x000000, 0xffffff },
    { 0xff4400, 0xffffff },
    { 0x00ff00, 0xffffff },
    { 0xffff00, 0x606060 },
    { 0x0033ff, 0xffffff },
    { 0xff00ff, 0xffffff },
    { 0x00ffff, 0xffffff },
    { 0xffffff, 0x505050 },
}
Definition at line 43 of file mttymain.c.
Referenced by _mt_init_stuff(), term_end_color(), and term_start_color().
Boolean _mt_in_color = 0 [static]
Definition at line 189 of file mttymain.c.
WindowRef _mt_window = (WindowRef) 0
Definition at line 188 of file mttymain.c.
Referenced by AdjustMenus(), erase_rect(), GetNhWin(), HandleUpdate(), mac_clear_nhwindow(), mac_create_nhwindow(), mac_curs(), mac_destroy_nhwindow(), mac_display_nhwindow(), mac_putstr(), and SanePositions().
char erase_char = CHAR_BS
Definition at line 186 of file mttymain.c.
char kill_char = CHAR_ESC
Definition at line 185 of file mttymain.c.
struct DisplayDesc* ttyDisplay
short win_fonts[NHW_TEXT+1]
Definition at line 283 of file macwin.c.