nethack/src/music.c File Reference
#include `hack.h`
*
Functions
STATIC_DCL void FDECL (awaken_monsters,(int))
STATIC_DCL void FDECL (put_monsters_to_sleep,(int))
STATIC_DCL void FDECL (charm_snakes,(int))
STATIC_DCL void FDECL (calm_nymphs,(int))
STATIC_DCL void FDECL (charm_monsters,(int))
STATIC_DCL void FDECL (do_earthquake,(int))
STATIC_DCL int FDECL (do_improvisation,(struct obj *))
STATIC_OVL void awaken_monsters (int distance)
STATIC_OVL void put_monsters_to_sleep (int distance)
STATIC_OVL void charm_snakes (int distance)
STATIC_OVL void calm_nymphs (int distance)
void awaken_soldiers ()
STATIC_OVL void charm_monsters (int distance)
STATIC_OVL void do_earthquake (int force)
STATIC_OVL int do_improvisation (struct obj *instr)
int do_play_instrument (struct obj *instr)
Function Documentation
STATIC_OVL void awaken_monsters (int distance)
Definition at line 61 of file music.c.
References DEADMONSTER, distu, FALSE, fmon, monst::mx, monst::my, monst::nmon, NOTELL, TOOL_CLASS, and TRUE.
Referenced by do_improvisation().
{
    register struct monst *mtmp = fmon;
    register int distm;
    while(mtmp) {
        if (!DEADMONSTER(mtmp)) {
        distm = distu(mtmp->mx, mtmp->my);
        if (distm < distance) {
            mtmp->msleeping = 0;
            mtmp->mcanmove = 1;
            mtmp->mfrozen = 0;
            /* May scare some monsters */
            if (distm < distance/3 &&
                !resist(mtmp, TOOL_CLASS, 0, NOTELL))
            monflee(mtmp, 0, FALSE, TRUE);
        }
        }
        mtmp = mtmp->nmon;
    }
}
void awaken_soldiers ()
Definition at line 166 of file music.c.
References canseemon, monst::data, DEADMONSTER, fmon, is_mercenary, mons, and monst::nmon.
Referenced by do_improvisation(), and use_defensive().
{
    register struct monst *mtmp = fmon;
    while(mtmp) {
        if (!DEADMONSTER(mtmp) &&
            is_mercenary(mtmp->data) && mtmp->data != &mons[PM_GUARD]) {
        mtmp->mpeaceful = mtmp->msleeping = mtmp->mfrozen = 0;
        mtmp->mcanmove = 1;
        if (canseemon(mtmp))
            pline("%s is now ready for battle!", Monnam(mtmp));
        else
            Norep("You hear the rattle of battle gear being readied.");
        }
        mtmp = mtmp->nmon;
    }
}
STATIC_OVL void calm_nymphs (int distance)
Definition at line 143 of file music.c.
References canseemon, monst::data, DEADMONSTER, distu, fmon, permonst::mlet, monst::mx, monst::my, monst::nmon, and S_NYMPH.
Referenced by do_improvisation().
{
    register struct monst *mtmp = fmon;
    while (mtmp) {
        if (!DEADMONSTER(mtmp) && mtmp->data->mlet == S_NYMPH && mtmp->mcanmove
      &&
            distu(mtmp->mx, mtmp->my) < distance) {
        mtmp->msleeping = 0;
        mtmp->mpeaceful = 1;
        mtmp->mavenge = 0;
        if (canseemon(mtmp))
            pline(
             "%s listens cheerfully to the music, then seems quieter.",
              Monnam(mtmp));
        }
        mtmp = mtmp->nmon;
    }
}
STATIC_OVL void charm_monsters (int distance)
Definition at line 189 of file music.c.
References DEADMONSTER, distu, fmon, monst::mx, monst::my, monst::nmon, NOTELL, TOOL_CLASS, u, and you::ustuck.
Referenced by do_improvisation().
{
    struct monst *mtmp, *mtmp2;
    if (u.uswallow) {
        if (!resist(u.ustuck, TOOL_CLASS, 0, NOTELL))
        (void) tamedog(u.ustuck, (struct obj *) 0);
    } else {
        for (mtmp = fmon; mtmp; mtmp = mtmp2) {
        mtmp2 = mtmp->nmon;
        if (DEADMONSTER(mtmp)) continue;
        if (distu(mtmp->mx, mtmp->my) <= distance) {
            if (!resist(mtmp, TOOL_CLASS, 0, NOTELL))
            (void) tamedog(mtmp, (struct obj *) 0);
        }
        }
    }
}
STATIC_OVL void charm_snakes (int distance)
Definition at line 109 of file music.c.
References canseemon, monst::data, DEADMONSTER, distu, fmon, permonst::mlet, monst::mx, monst::my, newsym(), monst::nmon, and S_SNAKE.
Referenced by do_improvisation().
{
    register struct monst *mtmp = fmon;
    int could_see_mon, was_peaceful;
    while (mtmp) {
        if (!DEADMONSTER(mtmp) && mtmp->data->mlet == S_SNAKE && mtmp->mcanmove
      &&
            distu(mtmp->mx, mtmp->my) < distance) {
        was_peaceful = mtmp->mpeaceful;
        mtmp->mpeaceful = 1;
        mtmp->mavenge = 0;
        could_see_mon = canseemon(mtmp);
        mtmp->mundetected = 0;
        newsym(mtmp->mx, mtmp->my);
        if (canseemon(mtmp)) {
            if (!could_see_mon)
            You("notice %s, swaying with the music.",
                a_monnam(mtmp));
            else
            pline("%s freezes, then sways with the music%s.",
                  Monnam(mtmp),
                  was_peaceful ? "" : ", and now seems quieter");
        }
        }
        mtmp = mtmp->nmon;
    }
}
STATIC_OVL void do_earthquake (int force)
Definition at line 216 of file music.c.
References ALTAR, ARTICLE_THE, cansee, COLNO, CORR, D_NODOOR, monst::data, DOOR, doormask, FALSE, flags, Flying, FOUNTAIN, GRAVE, humanoid, Is_astralevel, is_clinger, is_flyer, is_hider, Is_sanctum, Levitation, levl, m_at, monst::mhp, monst::mnamelth, monst::mtame, newsym(), NO_KILLER_PREFIX, otmp, PIT, rn1, ROOM, ROWNO, SHOPBASE, SINK, flag::soundok, SUPPRESS_SADDLE, THRONE, TRUE, TT_PIT, u, unblock_point(), you::utrap, you::utraptype, you::ux, you::uy, you::uz, trap::x, trap::y, and youmonst.
Referenced by do_improvisation().
{
    register int x,y;
    struct monst *mtmp;
    struct obj *otmp;
    struct trap *chasm;
    int start_x, start_y, end_x, end_y;
    start_x = u.ux - (force * 2);
    start_y = u.uy - (force * 2);
    end_x = u.ux + (force * 2);
    end_y = u.uy + (force * 2);
    if (start_x < 1) start_x = 1;
    if (start_y < 1) start_y = 1;
    if (end_x >= COLNO) end_x = COLNO - 1;
    if (end_y >= ROWNO) end_y = ROWNO - 1;
    for (x=start_x; x<=end_x; x++) for (y=start_y; y<=end_y; y++) {
        if ((mtmp = m_at(x,y)) != 0) {
        wakeup(mtmp); /* peaceful monster will become hostile */
        if (mtmp->mundetected && is_hider(mtmp->data)) {
            mtmp->mundetected = 0;
            if (cansee(x,y))
            pline("%s is shaken loose from the ceiling!",
                                Amonnam(mtmp));
            else
            You_hear("a thumping sound.");
            if (x==u.ux && y==u.uy)
            You("easily dodge the falling %s.",
                                mon_nam(mtmp));
            newsym(x,y);
        }
        }
        if (!rn2(14 - force)) switch (levl[x][y].typ) {
          case FOUNTAIN : /* Make the fountain disappear */
            if (cansee(x,y))
                pline_The("fountain falls into a chasm.");
            goto do_pit;
#ifdef SINKS
          case SINK :
            if (cansee(x,y))
                pline_The("kitchen sink falls into a chasm.");
            goto do_pit;
#endif
          case ALTAR :
            if (Is_astralevel(&u.uz) || Is_sanctum(&u.
      uz)) break;
            if (cansee(x,y))
                pline_The("altar falls into a chasm.");
            goto do_pit;
          case GRAVE :
            if (cansee(x,y))
                pline_The("headstone topples into a chasm.");
            goto do_pit;
          case THRONE :
            if (cansee(x,y))
                pline_The("throne falls into a chasm.");
            /* Falls into next case */
          case ROOM :
          case CORR : /* Try to make a pit */
do_pit: chasm = maketrap(x,y,PIT);
            if (!chasm) break; /* no pit if portal at that location */
            chasm->tseen = 1;
            levl[x][y].doormask = 0;
            mtmp = m_at(x,y);
            if ((otmp = sobj_at(BOULDER, x, y)) != 0) {
            if (cansee(x, y))
               pline("KADOOM! The boulder falls into a chasm%s!",
                  ((x == u.ux) && (y == u.uy)) ? " below you" : "");
            if (mtmp)
                mtmp->mtrapped = 0;
            obj_extract_self(otmp);
            (void) flooreffects(otmp, x, y, "");
            break;
            }
            /* We have to check whether monsters or player
               falls in a chasm... */
            if (mtmp) {
            if(!is_flyer(mtmp->data) && !is_clinger(mtmp->
      data)) {
                mtmp->mtrapped = 1;
                if(cansee(x,y))
                pline("%s falls into a chasm!", Monnam(mtmp));
                else if (flags.soundok && humanoid(mtmp->
      data))
                You_hear("a scream!");
                mselftouch(mtmp, "Falling, ", TRUE);
                if (mtmp->mhp > 0)
                if ((mtmp->mhp -= rnd(6)) <= 0) {
                    if(!cansee(x,y))
                    pline("It is destroyed!");
                    else {
                    You("destroy %s!", mtmp->mtame ?
                        x_monnam(mtmp, ARTICLE_THE, "poor",
                mtmp->mnamelth ? SUPPRESS_SADDLE : 0,
      FALSE):
                        mon_nam(mtmp));
                    }
                    xkilled(mtmp,0);
                }
            }
            } else if (x == u.ux && y == u.uy) {
                if (Levitation || Flying ||
                        is_clinger(youmonst.data)) {
                    pline("A chasm opens up under you!");
                    You("don't fall in!");
                } else {
                    You("fall into a chasm!");
                    u.utrap = rn1(6,2);
                    u.utraptype = TT_PIT;
                    losehp(rnd(6),"fell into a chasm",
                    NO_KILLER_PREFIX);
                    selftouch("Falling, you");
                }
            } else newsym(x,y);
            break;
          case DOOR : /* Make the door collapse */
            if (levl[x][y].doormask == D_NODOOR) goto do_pit;
            if (cansee(x,y))
            pline_The("door collapses.");
            if (*in_rooms(x, y, SHOPBASE))
            add_damage(x, y, 0L);
            levl[x][y].doormask = D_NODOOR;
            unblock_point(x,y);
            newsym(x,y);
            break;
        }
    }
}
STATIC_OVL int do_improvisation (struct obj * instr)
Definition at line 353 of file music.c.
References A_DEX, A_WIS, ACURR, AD_COLD, AD_FIRE, AMII_OKAY_VOLUME, amii_speaker(), awaken_monsters(), awaken_soldiers(), buf, BUFSZ, calm_nymphs(), charm_monsters(), charm_snakes(), COLNO, Confusion, do_earthquake(), you::dx, you::dy, you::dz, FALSE, KILLED_BY, mac_speaker(), makeknown, objects, obj::otyp, put_monsters_to_sleep(), rn1, ROWNO, Sprintf, TRUE, u, uhim, you::ulevel, you::ux, and you::uy.
Referenced by do_play_instrument().
{
    int damage, do_spec = !Confusion;
#if defined(MAC) || defined(AMIGA) || defined(VPIX_MUSIC) || defined (PCMUSIC)
    struct obj itmp;
    itmp = *instr;
    /* if won't yield special effect, make sound of mundane counterpart */
    if (!do_spec || instr->spe <= 0)
        while (objects[itmp.otyp].oc_magic) itmp.otyp -= 1;
# ifdef MAC
    mac_speaker(&itmp, "C");
# endif
# ifdef AMIGA
    amii_speaker(&itmp, "Cw", AMII_OKAY_VOLUME);
# endif
# ifdef VPIX_MUSIC
    if (sco_flag_console)
        speaker(&itmp, "C");
# endif
#ifdef PCMUSIC
      pc_speaker (&itmp, "C");
#endif
#endif /* MAC || AMIGA || VPIX_MUSIC || PCMUSIC */
    if (!do_spec)
        pline("What you produce is quite far from music...");
    else
        You("start playing %s.", the(xname(instr)));
    switch (instr->otyp) {
    case MAGIC_FLUTE: /* Make monster fall asleep */
        if (do_spec && instr->spe > 0) {
        consume_obj_charge(instr, TRUE);
        You("produce soft music.");
        put_monsters_to_sleep(u.ulevel * 5);
        exercise(A_DEX, TRUE);
        break;
        } /* else FALLTHRU */
    case WOODEN_FLUTE: /* May charm snakes */
        do_spec &= (rn2(ACURR(A_DEX)) + u.ulevel > 25);
        pline("%s.", Tobjnam(instr, do_spec ? "trill" : "toot"));
        if (do_spec) charm_snakes(u.ulevel * 3);
        exercise(A_DEX, TRUE);
        break;
    case FROST_HORN: /* Idem wand of cold */
    case FIRE_HORN: /* Idem wand of fire */
        if (do_spec && instr->spe > 0) {
        consume_obj_charge(instr, TRUE);
        if (!getdir((char *)0)) {
            pline("%s.", Tobjnam(instr, "vibrate"));
            break;
        } else if (!u.dx && !u.dy && !u.dz) {
            if ((damage = zapyourself(instr, TRUE)) != 0) {
            char buf[BUFSZ];
            Sprintf(buf, "using a magical horn on %sself", uhim());
            losehp(damage, buf, KILLED_BY);
            }
        } else {
            buzz((instr->otyp == FROST_HORN) ? AD_COLD-1 : AD_FIRE-1,
             rn1(6,6), u.ux, u.uy, u.dx, u.dy);
        }
        makeknown(instr->otyp);
        break;
        } /* else FALLTHRU */
    case TOOLED_HORN: /* Awaken or scare monsters */
        You("produce a frightful, grave sound.");
        awaken_monsters(u.ulevel * 30);
        exercise(A_WIS, FALSE);
        break;
    case BUGLE: /* Awaken & attract soldiers */
        You("extract a loud noise from %s.", the(xname(instr)));
        awaken_soldiers();
        exercise(A_WIS, FALSE);
        break;
    case MAGIC_HARP: /* Charm monsters */
        if (do_spec && instr->spe > 0) {
        consume_obj_charge(instr, TRUE);
        pline("%s very attractive music.", Tobjnam(instr, "produce"));
        charm_monsters((u.ulevel - 1) / 3 + 1);
        exercise(A_DEX, TRUE);
        break;
        } /* else FALLTHRU */
    case WOODEN_HARP: /* May calm Nymph */
        do_spec &= (rn2(ACURR(A_DEX)) + u.ulevel > 25);
        pline("%s %s.", The(xname(instr)),
          do_spec ? "produces a lilting melody" : "twangs");
        if (do_spec) calm_nymphs(u.ulevel * 3);
        exercise(A_DEX, TRUE);
        break;
    case DRUM_OF_EARTHQUAKE: /* create several pits */
        if (do_spec && instr->spe > 0) {
        consume_obj_charge(instr, TRUE);
        You("produce a heavy, thunderous rolling!");
        pline_The("entire dungeon is shaking around you!");
        do_earthquake((u.ulevel - 1) / 3 + 1);
        /* shake up monsters in a much larger radius... */
        awaken_monsters(ROWNO * COLNO);
        makeknown(DRUM_OF_EARTHQUAKE);
        break;
        } /* else FALLTHRU */
    case LEATHER_DRUM: /* Awaken monsters */
        You("beat a deafening row!");
        awaken_monsters(u.ulevel * 40);
        exercise(A_WIS, FALSE);
        break;
    default:
        impossible("What a weird instrument (%d)!", instr->otyp);
        break;
    }
    return 2; /* That takes time */
}
int do_play_instrument (struct obj * instr)
Definition at line 476 of file music.c.
References A_WIS, AMII_OKAY_VOLUME, amii_speaker(), buf, BUFSZ, do_improvisation(), DRAWBRIDGE_DOWN, FALSE, flags, getlin, IS_DRAWBRIDGE, Is_stronghold, levl, mac_speaker(), plur, flag::soundok, Strcpy, TRUE, tune, u, you::uevent, Underwater, you::ux, you::uy, you::uz, and yn.
{
    char buf[BUFSZ], c = 'y';
    char *s;
    int x,y;
    boolean ok;
    if (Underwater) {
    You_cant("play music underwater!");
    return(0);
    }
    if (instr->otyp != LEATHER_DRUM && instr->otyp != DRUM_OF_EARTHQUAKE) {
    c = yn("Improvise?");
    }
    if (c == 'n') {
    if (u.uevent.uheard_tune == 2 && yn("Play the passtune?") == 'y') {
        Strcpy(buf, tune);
    } else {
        getlin("What tune are you playing? [5 notes, A-G]", buf);
        (void)mungspaces(buf);
        /* convert to uppercase and change any "H" to the expected "B" */
        for (s = buf; *s; s++) {
#ifndef AMIGA
        *s = highc(*s);
#else
        /* The AMIGA supports two octaves of notes */
        if (*s == 'h') *s = 'b';
#endif
        if (*s == 'H') *s = 'B';
        }
    }
    You("extract a strange sound from %s!", the(xname(instr)));
#ifdef UNIX386MUSIC
    /* if user is at the console, play through the console speaker */
    if (atconsole())
        speaker(instr, buf);
#endif
#ifdef VPIX_MUSIC
    if (sco_flag_console)
        speaker(instr, buf);
#endif
#ifdef MAC
    mac_speaker (instr , buf) ;
#endif
#ifdef PCMUSIC
    pc_speaker (instr, buf);
#endif
#ifdef AMIGA
    {
        char nbuf[ 20 ];
        int i;
        for(i = 0; buf[i] && i < 5; ++i)
        {
            nbuf[ i*2 ] = buf[ i ];
            nbuf[ (i*2)+1 ] = 'h';
        }
        nbuf[ i*2 ] = 0;
        amii_speaker (instr , nbuf, AMII_OKAY_VOLUME) ;
    }
#endif
    /* Check if there was the Stronghold drawbridge near
     * and if the tune conforms to what we're waiting for.
     */
    if(Is_stronghold(&u.uz)) {
        exercise(A_WIS, TRUE); /* just for trying */
        if(!strcmp(buf,tune)) {
        /* Search for the drawbridge */
        for(y=u.uy-1; y<=u.uy+1; y++)
            for(x=u.ux-1;x<=u.ux+1;x++)
            if(isok(x,y))
            if(find_drawbridge(&x,&y)) {
                u.uevent.uheard_tune = 2; /* tune now fully known */
                if(levl[x][y].typ == DRAWBRIDGE_DOWN)
                close_drawbridge(x,y);
                else
                open_drawbridge(x,y);
                return 0;
            }
        } else if(flags.soundok) {
        if (u.uevent.uheard_tune < 1) u.uevent.uheard_tune = 1;
        /* Okay, it wasn't the right tune, but perhaps
         * we can give the player some hints like in the
         * Mastermind game */
        ok = FALSE;
        for(y = u.uy-1; y <= u.uy+1 && !ok; y++)
            for(x = u.ux-1; x <= u.ux+1 && !ok; x++)
            if(isok(x,y))
            if(IS_DRAWBRIDGE(levl[x][y].typ) ||
               is_drawbridge_wall(x,y) >= 0)
                ok = TRUE;
        if(ok) { /* There is a drawbridge near */
            int tumblers, gears;
            boolean matched[5];
            tumblers = gears = 0;
            for(x=0; x < 5; x++)
            matched[x] = FALSE;
            for(x=0; x < (int)strlen(buf); x++)
            if(x < 5) {
                if(buf[x] == tune[x]) {
                gears++;
                matched[x] = TRUE;
                } else
                for(y=0; y < 5; y++)
                    if(!matched[y] &&
                       buf[x] == tune[y] &&
                       buf[y] != tune[y]) {
                    tumblers++;
                    matched[y] = TRUE;
                    break;
                    }
            }
            if(tumblers)
            if(gears)
                You_hear("%d tumbler%s click and %d gear%s turn.",
                tumblers, plur(tumblers), gears, plur(gears));
            else
                You_hear("%d tumbler%s click.",
                tumblers, plur(tumblers));
            else if(gears) {
            You_hear("%d gear%s turn.", gears, plur(gears));
            /* could only get `gears == 5' by playing five
               correct notes followed by excess; otherwise,
               tune would have matched above */
            if (gears == 5) u.uevent.uheard_tune = 2;
            }
        }
        }
      }
    return 1;
    } else
        return do_improvisation(instr);
}
STATIC_DCL void FDECL (awaken_monsters , (int))
STATIC_DCL void FDECL (put_monsters_to_sleep , (int))
STATIC_DCL void FDECL (charm_snakes , (int))
STATIC_DCL void FDECL (calm_nymphs , (int))
STATIC_DCL void FDECL (charm_monsters , (int))
STATIC_DCL void FDECL (do_earthquake , (int))
STATIC_DCL int FDECL (do_improvisation , (struct obj *))
STATIC_OVL void put_monsters_to_sleep (int distance)
Definition at line 89 of file music.c.
References DEADMONSTER, distu, fmon, monst::mx, monst::my, monst::nmon, and TOOL_CLASS.
Referenced by do_improvisation().
{
    register struct monst *mtmp = fmon;
    while(mtmp) {
        if (!DEADMONSTER(mtmp) && distu(mtmp->mx, mtmp->my) < distance &&
            sleep_monst(mtmp, d(10,10), TOOL_CLASS)) {
            mtmp->msleeping = 1; /* 10d10 turns + wake_nearby to rouse */
            slept_monst(mtmp);
        }
        mtmp = mtmp->nmon;
    }
}