nethack/src/options.c File Reference
#include `hack.h`
*
#include `tcap.h`
*
#include <ctype.h>
*
Data Structures
struct Bool_Opt
struct Comp_Opt
struct menu_cmd_t
Macros
#define WINTYPELEN 16
#define PREFER_TILED FALSE
#define NUM_MENU_CMDS 11
#define MAX_MENU_MAPPED_CMDS 32	/* some number */
#define OPTIONS_HEADING `NETHACKOPTIONS`
#define rolestring(val, array, field)
#define CONFIG_SLOT 3	/* fill in next value at run-time */
Functions
STATIC_DCL void FDECL (doset_add_menu,(winid, const char *, int))
STATIC_DCL void FDECL (nmcpy,(char *, const char *, int))
STATIC_DCL void FDECL (escapes,(const char *, char *))
STATIC_DCL void FDECL (rejectoption,(const char *))
STATIC_DCL void FDECL (badoption,(const char *))
STATIC_DCL char * FDECL (string_for_opt,(char *, BOOLEAN_P))
STATIC_DCL char * FDECL (string_for_env_opt,(const char *, char *, BOOLEAN_P))
STATIC_DCL void FDECL (bad_negation,(const char *, BOOLEAN_P))
STATIC_DCL int FDECL (change_inv_order,(char *))
STATIC_DCL void FDECL (oc_to_str,(char *, char *))
STATIC_DCL void FDECL (graphics_opts,(char *, const char *, int, int))
STATIC_DCL int FDECL (feature_alert_opts,(char *, const char *))
STATIC_DCL const char * FDECL (get_compopt_value,(const char *, char *))
STATIC_DCL boolean FDECL (special_handling,(const char *, BOOLEAN_P, BOOLEAN_P))
STATIC_DCL void FDECL (warning_opts,(char *, const char *))
STATIC_DCL void FDECL (duplicate_opt_detection,(const char *, int))
STATIC_OVL void FDECL (wc_set_font_name,(int, char *))
STATIC_OVL int FDECL (wc_set_window_colors,(char *))
STATIC_OVL boolean FDECL (is_wc_option,(const char *))
STATIC_OVL boolean FDECL (wc_supported,(const char *))
STATIC_OVL boolean FDECL (is_wc2_option,(const char *))
STATIC_OVL boolean FDECL (wc2_supported,(const char *))
boolean match_optname (char *user_string, char *opt_name, int min_length, boolean val_allowed) const
char * nh_getenv (char *ev) const
void initoptions ()
STATIC_OVL void nmcpy (char *dest, const char *src, int maxlen)
STATIC_OVL void escapes (char *cp, char *tp) const
STATIC_OVL void rejectoption (char *optname) const
STATIC_OVL void badoption (char *opts) const
STATIC_OVL char * string_for_opt (char *opts, boolean val_optional)
STATIC_OVL char * string_for_env_opt (char *optname, char *opts, boolean val_optional) const
STATIC_OVL void bad_negation (char *optname, boolean with_parameter) const
STATIC_OVL int change_inv_order (char *op)
STATIC_OVL void graphics_opts (char *opts, const char *optype, int maxlen, int offset)
STATIC_OVL void warning_opts (char *opts, const char *optype)
void assign_warnings (uchar *graph_chars)
STATIC_OVL int feature_alert_opts (char *op, const char *optn)
void set_duplicate_opt_detection (int on_or_off)
STATIC_OVL void duplicate_opt_detection (char *opts, int bool_or_comp) const
void parseoptions (char *opts, boolean tinitial, boolean tfrom_file)
STATIC_OVL void oc_to_str (char *src, char *dest)
void add_menu_cmd_alias (char from_ch, char to_ch)
char map_menu_cmd (char ch)
STATIC_OVL void doset_add_menu (winid win, const char *option, int indexoffset)
int doset ()
STATIC_OVL boolean special_handling (char *optname, boolean setinitial, boolean setfromfile) const
STATIC_OVL const char * get_compopt_value (char *optname, char *buf) const
int dotogglepickup ()
void option_help ()
void next_opt (winid datawin, const char *str)
int fruitadd (char *str)
int choose_classes_menu (char *prompt, int category, boolean way, char *class_list, char *class_select) const
void set_option_mod_status (char *optnam, int status) const
void set_wc_option_mod_status (unsigned long optmask, int status)
STATIC_OVL boolean is_wc_option (char *optnam) const
STATIC_OVL boolean wc_supported (char *optnam) const
void set_wc2_option_mod_status (unsigned long optmask, int status)
STATIC_OVL boolean is_wc2_option (char *optnam) const
STATIC_OVL boolean wc2_supported (char *optnam) const
STATIC_OVL void wc_set_font_name (int wtype, char *fontname)
STATIC_OVL int wc_set_window_colors (char *op)
Variables
static struct Bool_Opt boolopt []
static struct Comp_Opt compopt []
static boolean need_redraw
static char def_inv_order [MAXOCLASSES]
static const menu_cmd_t default_menu_cmd_info [NUM_MENU_CMDS]
char mapped_menu_cmds [MAX_MENU_MAPPED_CMDS+1]
static char mapped_menu_op [MAX_MENU_MAPPED_CMDS+1]
static short n_menu_mapped = 0
static boolean initial
static boolean from_file
static NEARDATA const char * menutype []
static NEARDATA const char * burdentype []
static NEARDATA const char * runmodes []
static char fmtstr_doset_add_menu [] = `%s%-15s [%s] `
static char fmtstr_doset_add_menu_tab [] = `%s\t[%s]`
static const char * opt_intro []
static const char * opt_epilog []
struct wc_Opt wc_options []
struct wc_Opt wc2_options []
Macro Definition Documentation
#define CONFIG_SLOT 3	/* fill in next value at run-time */
Referenced by option_help().
#define MAX_MENU_MAPPED_CMDS 32	/* some number */
Definition at line 410 of file options.c.
Referenced by add_menu_cmd_alias().
#define NUM_MENU_CMDS 11
Definition at line 391 of file options.c.
Referenced by parseoptions().
#define OPTIONS_HEADING `NETHACKOPTIONS`
Definition at line 2324 of file options.c.
#define PREFER_TILED FALSE
Definition at line 23 of file options.c.
#define rolestring(val, array, field)
Value:
((val >= 0) ? array[val].field : \
                     (val == ROLE_RANDOM) ? randomrole : none)
Definition at line 2881 of file options.c.
Referenced by get_compopt_value().
#define WINTYPELEN 16
Definition at line 18 of file options.c.
Referenced by parseoptions().
Function Documentation
void add_menu_cmd_alias (char from_ch, char to_ch)
Definition at line 2290 of file options.c.
References MAX_MENU_MAPPED_CMDS, and n_menu_mapped.
Referenced by parseoptions().
{
    if (n_menu_mapped >= MAX_MENU_MAPPED_CMDS)
    pline("out of menu map space.");
    else {
    mapped_menu_cmds[n_menu_mapped] = from_ch;
    mapped_menu_op[n_menu_mapped] = to_ch;
    n_menu_mapped++;
    mapped_menu_cmds[n_menu_mapped] = 0;
    mapped_menu_op[n_menu_mapped] = 0;
    }
}
void assign_warnings (uchar * graph_chars)
Definition at line 853 of file options.c.
References WARNCOUNT, and warnsyms.
Referenced by parse_config_line(), and warning_opts().
{
    int i;
    for (i = 0; i < WARNCOUNT; i++)
        if (graph_chars[i]) warnsyms[i] = graph_chars[i];
}
STATIC_OVL void bad_negation (char * optname, boolean with_parameter) const
Definition at line 754 of file options.c.
Referenced by parseoptions().
{
    pline_The("%s option may not %sbe negated.",
        optname,
        with_parameter ? "both have a value and " : "");
}
STATIC_OVL void badoption (char * opts) const
Definition at line 700 of file options.c.
References configfile, option_help(), and wait_synch.
Referenced by feature_alert_opts(), parseoptions(), and string_for_opt().
{
    if (!initial) {
        if (!strncmp(opts, "h", 1) || !strncmp(opts, "?", 1))
        option_help();
        else
        pline("Bad syntax: %s. Enter \"?g\" for help.", opts);
        return;
    }
#ifdef MAC
    else return;
#endif
    if(from_file)
        raw_printf("Bad syntax in OPTIONS in %s: %s.", configfile, opts);
    else
        raw_printf("Bad syntax in NETHACKOPTIONS: %s.", opts);
    wait_synch();
}
STATIC_OVL int change_inv_order (char * op)
Definition at line 773 of file options.c.
References buf, BUFSZ, COIN_CLASS, def_char_to_objclass(), flags, GOLD_SYM, ILLOBJ_CLASS, index(), flag::inv_order, MAXOCLASSES, RANDOM_CLASS, and Strcpy.
Referenced by parseoptions().
{
    int oc_sym, num;
    char *sp, buf[BUFSZ];
    num = 0;
#ifndef GOLDOBJ
    if (!index(op, GOLD_SYM))
    buf[num++] = COIN_CLASS;
#else
    /* !!!! probably unnecessary with gold as normal inventory */
#endif
    for (sp = op; *sp; sp++) {
    oc_sym = def_char_to_objclass(*sp);
    /* reject bad or duplicate entries */
    if (oc_sym == MAXOCLASSES ||
        oc_sym == RANDOM_CLASS || oc_sym == ILLOBJ_CLASS ||
        !index(flags.inv_order, oc_sym) || index(sp+1, *sp))
        return 0;
    /* retain good ones */
    buf[num++] = (char) oc_sym;
    }
    buf[num] = '\0';
    /* fill in any omitted classes, using previous ordering */
    for (sp = flags.inv_order; *sp; sp++)
    if (!index(buf, *sp)) {
        buf[num++] = *sp;
        buf[num] = '\0'; /* explicitly terminate for next index() */
    }
    Strcpy(flags.inv_order, buf);
    return 1;
}
int choose_classes_menu (char * prompt, int category, boolean way, char * class_list, char * class_select) const
Definition at line 3479 of file options.c.
References any::a_int, any::a_void, add_menu, ATR_NONE, buf, BUFSZ, create_nhwindow, def_char_to_monclass(), def_char_to_objclass(), destroy_nhwindow, end_menu, eos(), FALSE, free(), index(), mi::item, monexplain, NHW_MENU, NO_GLYPH, objexplain, PICK_ANY, PICK_ONE, select_menu, Sprintf, start_menu, and TRUE.
Referenced by parseoptions().
{
    menu_item *pick_list = (menu_item *)0;
    winid win;
    anything any;
    char buf[BUFSZ];
    int i, n;
    int ret;
    int next_accelerator, accelerator;
    if (class_list == (char *)0 || class_select == (char *)0) return 0;
    accelerator = 0;
    next_accelerator = 'a';
    any.a_void = 0;
    win = create_nhwindow(NHW_MENU);
    start_menu(win);
    while (*class_list) {
    const char *text;
    boolean selected;
    text = (char *)0;
    selected = FALSE;
    switch (category) {
        case 0:
            text = monexplain[def_char_to_monclass(*class_list)];
            accelerator = *class_list;
            Sprintf(buf, "%s", text);
            break;
        case 1:
            text = objexplain[def_char_to_objclass(*class_list)];
            accelerator = next_accelerator;
            Sprintf(buf, "%c %s", *class_list, text);
            break;
        default:
            impossible("choose_classes_menu: invalid category %d",
                    category);
    }
    if (way && *class_select) { /* Selections there already */
        if (index(class_select, *class_list)) {
            selected = TRUE;
        }
    }
    any.a_int = *class_list;
    add_menu(win, NO_GLYPH, &any, accelerator,
          category ? *class_list : 0,
          ATR_NONE, buf, selected);
    ++class_list;
    if (category > 0) {
        ++next_accelerator;
        if (next_accelerator == ('z' + 1)) next_accelerator = 'A';
        if (next_accelerator == ('Z' + 1)) break;
    }
    }
    end_menu(win, prompt);
    n = select_menu(win, way ? PICK_ANY : PICK_ONE, &pick_list);
    destroy_nhwindow(win);
    if (n > 0) {
    for (i = 0; i < n; ++i)
        *class_select++ = (char)pick_list[i].item.a_int;
    free((genericptr_t)pick_list);
    ret = n;
    } else if (n == -1) {
    class_select = eos(class_select);
    ret = -1;
    } else
    ret = 0;
    *class_select = '\0';
    return ret;
}
int doset ()
Definition at line 2370 of file options.c.
References any::a_int, any::a_void, add_menu, ATR_NONE, boolopt, buf, BUFSZ, compopt, create_nhwindow, destroy_nhwindow, DISP_IN_GAME, doredraw(), doset_add_menu(), end_menu, FALSE, flag::female, flags, free(), getlin, iflags, is_wc2_option(), is_wc_option(), mi::item, instance_flags::menu_headings, instance_flags::menu_tab_sep, MENU_UNSELECTED, Bool_Opt::name, name, Comp_Opt::name, NHW_MENU, NO_GLYPH, parseoptions(), PICK_ANY, preference_update, PREFIX_COUNT, select_menu, SET_IN_GAME, special_handling(), Sprintf, start_menu, wc2_supported(), wc_supported(), and wizard.
Referenced by onWMCommand().
{
    char buf[BUFSZ], buf2[BUFSZ];
    int i, pass, boolcount, pick_cnt, pick_idx, opt_indx;
    boolean *bool_p;
    winid tmpwin;
    anything any;
    menu_item *pick_list;
    int indexoffset, startpass, endpass;
    boolean setinitial = FALSE, fromfile = FALSE;
    int biggest_name = 0;
    tmpwin = create_nhwindow(NHW_MENU);
    start_menu(tmpwin);
    any.a_void = 0;
 add_menu(tmpwin, NO_GLYPH, &any, 0, 0, iflags.
      menu_headings,
         "Booleans (selecting will toggle value):", MENU_UNSELECTED);
    any.a_int = 0;
    /* first list any other non-modifiable booleans, then modifiable ones */
    for (pass = 0; pass <= 1; pass++)
        for (i = 0; boolopt[i].name; i++)
        if ((bool_p = boolopt[i].addr) != 0 &&
            ((boolopt[i].optflags == DISP_IN_GAME && pass == 0) ||
             (boolopt[i].optflags == SET_IN_GAME && pass == 1))) {
            if (bool_p == &flags.female) continue; /* obsolete */
#ifdef WIZARD
            if (bool_p == &iflags.sanity_check && !wizard) continue;
            if (bool_p == &iflags.menu_tab_sep && !wizard) continue;
#endif
            if (is_wc_option(boolopt[i].name) &&
            !wc_supported(boolopt[i].name)) continue;
            if (is_wc2_option(boolopt[i].name) &&
            !wc2_supported(boolopt[i].name)) continue;
            any.a_int = (pass == 0) ? 0 : i + 1;
            if (!iflags.menu_tab_sep)
            Sprintf(buf, "%s%-13s [%s]",
                pass == 0 ? " " : "",
                boolopt[i].name, *bool_p ? "true" : "false");
            else
            Sprintf(buf, "%s\t[%s]",
                boolopt[i].name, *bool_p ? "true" : "false");
            add_menu(tmpwin, NO_GLYPH, &any, 0, 0,
                 ATR_NONE, buf, MENU_UNSELECTED);
        }
    boolcount = i;
    indexoffset = boolcount;
    any.a_void = 0;
    add_menu(tmpwin, NO_GLYPH, &any, 0, 0, ATR_NONE, "",
      MENU_UNSELECTED);
 add_menu(tmpwin, NO_GLYPH, &any, 0, 0, iflags.
      menu_headings,
         "Compounds (selecting will prompt for new value):",
         MENU_UNSELECTED);
    startpass = DISP_IN_GAME;
    endpass = SET_IN_GAME;
    /* spin through the options to find the biggest name
           and adjust the format string accordingly if needed */
    biggest_name = 0;
    for (i = 0; compopt[i].name; i++)
        if (compopt[i].optflags >= startpass && compopt[i].optflags <= endpass &&
            strlen(compopt[i].name) > (unsigned) biggest_name)
            biggest_name = (int) strlen(compopt[i].name);
    if (biggest_name > 30) biggest_name = 30;
    if (!iflags.menu_tab_sep)
        Sprintf(fmtstr_doset_add_menu, "%%s%%-%ds [%%s]", biggest_name);
    
    /* deliberately put `name', `role', `race', `gender' first */
    doset_add_menu(tmpwin, "name", 0);
    doset_add_menu(tmpwin, "role", 0);
    doset_add_menu(tmpwin, "race", 0);
    doset_add_menu(tmpwin, "gender", 0);
    for (pass = startpass; pass <= endpass; pass++)
        for (i = 0; compopt[i].name; i++)
        if (compopt[i].optflags == pass) {
                if (!strcmp(compopt[i].name, "name") ||
                    !strcmp(compopt[i].name, "role") ||
                    !strcmp(compopt[i].name, "race") ||
                    !strcmp(compopt[i].name, "gender"))
                        continue;
                else if (is_wc_option(compopt[i].name) &&
                    !wc_supported(compopt[i].name))
                    continue;
                else if (is_wc2_option(compopt[i].name) &&
                    !wc2_supported(compopt[i].name))
                    continue;
                else
                doset_add_menu(tmpwin, compopt[i].name,
                    (pass == DISP_IN_GAME) ? 0 : indexoffset);
        }
#ifdef AUTOPICKUP_EXCEPTIONS
    any.a_int = -1;
    Sprintf(buf, "autopickup exceptions (%d currently set)",
        count_ape_maps((int *)0, (int *)0));
    add_menu(tmpwin, NO_GLYPH, &any, 0, 0, ATR_NONE, buf,
      MENU_UNSELECTED);
#endif /* AUTOPICKUP_EXCEPTIONS */
#ifdef PREFIXES_IN_USE
    any.a_void = 0;
    add_menu(tmpwin, NO_GLYPH, &any, 0, 0, ATR_NONE, "",
      MENU_UNSELECTED);
    add_menu(tmpwin, NO_GLYPH, &any, 0, 0, iflags.
      menu_headings,
         "Variable playground locations:", MENU_UNSELECTED);
    for (i = 0; i < PREFIX_COUNT; i++)
        doset_add_menu(tmpwin, fqn_prefix_names[i], 0);
#endif
    end_menu(tmpwin, "Set what options?");
    need_redraw = FALSE;
    if ((pick_cnt = select_menu(tmpwin, PICK_ANY, &pick_list)) > 0) {
        /*
         * Walk down the selection list and either invert the booleans
         * or prompt for new values. In most cases, call parseoptions()
         * to take care of options that require special attention, like
         * redraws.
         */
        for (pick_idx = 0; pick_idx < pick_cnt; ++pick_idx) {
        opt_indx = pick_list[pick_idx].item.a_int - 1;
#ifdef AUTOPICKUP_EXCEPTIONS
        if (opt_indx == -2) {
            special_handling("autopickup_exception",
                        setinitial, fromfile);
        } else
#endif
        if (opt_indx < boolcount) {
            /* boolean option */
            Sprintf(buf, "%s%s", *boolopt[opt_indx].addr ? "!" : "",
                boolopt[opt_indx].name);
            parseoptions(buf, setinitial, fromfile);
            if (wc_supported(boolopt[opt_indx].name) ||
                wc2_supported(boolopt[opt_indx].name))
            preference_update(boolopt[opt_indx].name);
        } else {
            /* compound option */
            opt_indx -= boolcount;
            if (!special_handling(compopt[opt_indx].name,
                            setinitial, fromfile)) {
            Sprintf(buf, "Set %s to what?", compopt[opt_indx].name);
            getlin(buf, buf2);
            if (buf2[0] == '\033')
                continue;
            Sprintf(buf, "%s:%s", compopt[opt_indx].name, buf2);
            /* pass the buck */
            parseoptions(buf, setinitial, fromfile);
            }
            if (wc_supported(compopt[opt_indx].name) ||
            wc2_supported(compopt[opt_indx].name))
            preference_update(compopt[opt_indx].name);
        }
        }
        free((genericptr_t)pick_list);
        pick_list = (menu_item *)0;
    }
    destroy_nhwindow(tmpwin);
    if (need_redraw)
        (void) doredraw();
    return 0;
}
STATIC_OVL void doset_add_menu (winid win, const char * option, int indexoffset)
Definition at line 2331 of file options.c.
References any::a_int, any::a_void, add_menu, ATR_NONE, buf, BUFSZ, compopt, get_compopt_value(), iflags, instance_flags::menu_tab_sep, MENU_UNSELECTED, name, Comp_Opt::name, NO_GLYPH, and Sprintf.
Referenced by doset().
{
    const char *value = "unknown"; /* current value */
    char buf[BUFSZ], buf2[BUFSZ];
    anything any;
    int i;
    any.a_void = 0;
    if (indexoffset == 0) {
    any.a_int = 0;
    value = get_compopt_value(option, buf2);
    } else {
    for (i=0; compopt[i].name; i++)
        if (strcmp(option, compopt[i].name) == 0) break;
    if (compopt[i].name) {
        any.a_int = i + 1 + indexoffset;
        value = get_compopt_value(option, buf2);
    } else {
        /* We are trying to add an option not found in compopt[].
           This is almost certainly bad, but we'll let it through anyway
           (with a zero value, so it can't be selected). */
        any.a_int = 0;
    }
    }
    /* " " replaces "a - " -- assumes menus follow that style */
    if (!iflags.menu_tab_sep)
    Sprintf(buf, fmtstr_doset_add_menu, any.a_int ? "" : " ", option,
      value);
    else
    Sprintf(buf, fmtstr_doset_add_menu_tab, option, value);
    add_menu(win, NO_GLYPH, &any, 0, 0, ATR_NONE, buf,
      MENU_UNSELECTED);
}
int dotogglepickup ()
Definition at line 3148 of file options.c.
References AUTOPICKUP_EXCEPTIONS, buf, BUFSZ, flags, iflags, MAXOCLASSES, oc_to_str(), flag::pickup, flag::pickup_types, Sprintf, and Strcpy.
{
    char buf[BUFSZ], ocl[MAXOCLASSES+1];
    flags.pickup = !flags.pickup;
    if (flags.pickup) {
        oc_to_str(flags.pickup_types, ocl);
        Sprintf(buf, "ON, for %s objects%s", ocl[0] ? ocl : "all",
#ifdef AUTOPICKUP_EXCEPTIONS
            (iflags.autopickup_exceptions[AP_LEAVE] ||
             iflags.autopickup_exceptions[AP_GRAB]) ?
             ((count_ape_maps((int *)0, (int *)0) == 1) ?
                ", with one exception" : ", with some exceptions") :
#endif
            "");
    } else {
        Strcpy(buf, "OFF");
    }
    pline("Autopickup: %s.", buf);
    return 0;
}
STATIC_OVL void duplicate_opt_detection (char * opts, int bool_or_comp) const
Definition at line 924 of file options.c.
References boolopt, compopt, FALSE, iflags, match_optname(), Bool_Opt::name, name, Comp_Opt::name, instance_flags::opt_booldup, instance_flags::opt_compdup, TRUE, and wait_synch.
Referenced by parseoptions().
{
    int i, *optptr;
#if defined(MAC)
    /* the Mac has trouble dealing with the output of messages while
     * processing the config file. That should get fixed one day.
     * For now just return.
     */
    return;
#endif
    if ((bool_or_comp == 0) && iflags.opt_booldup && initial &&
      from_file) {
        for (i = 0; boolopt[i].name; i++) {
        if (match_optname(opts, boolopt[i].name, 3,
      FALSE)) {
            optptr = iflags.opt_booldup + i;
            if (*optptr == 1) {
                raw_printf(
                "\nWarning - Boolean option specified multiple times: %s.\n",
                    opts);
                    wait_synch();
            }
            *optptr += 1;
            break; /* don't match multiple options */
        }
        }
    } else if ((bool_or_comp == 1) && iflags.opt_compdup &&
      initial && from_file) {
        for (i = 0; compopt[i].name; i++) {
        if (match_optname(opts, compopt[i].name, strlen(
      compopt[i].name), TRUE)) {
            optptr = iflags.opt_compdup + i;
            if (*optptr == 1) {
                raw_printf(
                "\nWarning - compound option specified multiple times: %s.\n",
                    compopt[i].name);
                    wait_synch();
            }
            *optptr += 1;
            break; /* don't match multiple options */
        }
        }
    }
}
STATIC_OVL void escapes (char	* cp, char * tp) const
Definition at line 632 of file options.c.
References index().
Referenced by graphics_opts(), parseoptions(), and warning_opts().
{
    while (*cp)
    {
    int cval = 0, meta = 0;
    if (*cp == '\\' && index("mM", cp[1])) {
        meta = 1;
        cp += 2;
    }
    if (*cp == '\\' && index("0123456789xXoO", cp[1]))
    {
        const char *dp, *hex = "00112233445566778899aAbBcCdDeEfF";
        int dcount = 0;
        cp++;
        if (*cp == 'x' || *cp == 'X')
        for (++cp; (dp = index(hex, *cp)) && (dcount++ < 2); cp++)
            cval = (cval * 16) + (dp - hex) / 2;
        else if (*cp == 'o' || *cp == 'O')
        for (++cp; (index("01234567",*cp)) && (dcount++ < 3); cp++)
            cval = (cval * 8) + (*cp - '0');
        else
        for (; (index("0123456789",*cp)) && (dcount++ < 3); cp++)
            cval = (cval * 10) + (*cp - '0');
    }
    else if (*cp == '\\') /* C-style character escapes */
    {
        switch (*++cp)
        {
        case '\\': cval = '\\'; break;
        case 'n': cval = '\n'; break;
        case 't': cval = '\t'; break;
        case 'b': cval = '\b'; break;
        case 'r': cval = '\r'; break;
        default: cval = *cp;
        }
        cp++;
    }
    else if (*cp == '^') /* expand control-character syntax */
    {
        cval = (*++cp & 0x1f);
        cp++;
    }
    else
        cval = *cp++;
    if (meta)
        cval |= 0x80;
    *tp++ = cval;
    }
    *tp = '\0';
}
STATIC_DCL void FDECL (doset_add_menu , (winid, const char *, int))
STATIC_DCL void FDECL (nmcpy , (char *, const char *, int))
STATIC_DCL void FDECL (escapes , (const char *, char *))
STATIC_DCL void FDECL (rejectoption , (const char *))
STATIC_DCL void FDECL (badoption , (const char *))
STATIC_DCL char* FDECL (string_for_opt , (char *, BOOLEAN_P))
STATIC_DCL char* FDECL (string_for_env_opt , (const char *, char *, BOOLEAN_P))
STATIC_DCL void FDECL (bad_negation , (const char *, BOOLEAN_P))
STATIC_DCL int FDECL (change_inv_order , (char *))
STATIC_DCL void FDECL (oc_to_str , (char *, char *))
STATIC_DCL void FDECL (graphics_opts , (char *, const char *, int, int))
STATIC_DCL int FDECL (feature_alert_opts , (char *, const char *))
STATIC_DCL const char* FDECL (get_compopt_value , (const char *, char *))
STATIC_DCL boolean FDECL (special_handling , (const char *, BOOLEAN_P, BOOLEAN_P))
STATIC_DCL void FDECL (warning_opts , (char *, const char *))
STATIC_DCL void FDECL (duplicate_opt_detection , (const char *, int))
STATIC_OVL void FDECL (wc_set_font_name , (int, char *))
STATIC_OVL int FDECL (wc_set_window_colors , (char *))
STATIC_OVL boolean FDECL (is_wc_option , (const char *))
STATIC_OVL boolean FDECL (wc_supported , (const char *))
STATIC_OVL boolean FDECL (is_wc2_option , (const char *))
STATIC_OVL boolean FDECL (wc2_supported , (const char *))
STATIC_OVL int feature_alert_opts (char * op, const char * optn)
Definition at line 862 of file options.c.
References badoption(), buf, BUFSZ, FALSE, FEATURE_NOTICE_VER_MAJ, FEATURE_NOTICE_VER_MIN, FEATURE_NOTICE_VER_PATCH, flags, get_current_feature_ver(), get_feature_notice_ver(), Sprintf, flag::suppress_alert, and TRUE.
Referenced by parseoptions().
{
    char buf[BUFSZ];
    boolean rejectver = FALSE;
    unsigned long fnv = get_feature_notice_ver(op); /* version.c */
    if (fnv == 0L) return 0;
    if (fnv > get_current_feature_ver())
        rejectver = TRUE;
    else
        flags.suppress_alert = fnv;
    if (rejectver) {
        if (!initial)
            You_cant("disable new feature alerts for future versions.");
        else {
            Sprintf(buf,
                "\n%s=%s Invalid reference to a future version ignored",
                optn, op);
            badoption(buf);
        }
        return 0;
    }
    if (!initial) {
        Sprintf(buf, "%lu.%lu.%lu", FEATURE_NOTICE_VER_MAJ,
            FEATURE_NOTICE_VER_MIN,
      FEATURE_NOTICE_VER_PATCH);
        pline("Feature change alerts disabled for NetHack %s features and prior.",
            buf);
    }
    return 1;
}
int fruitadd (char * str)
Definition at line 3377 of file options.c.
References bases, buf, current_fruit, eos(), FALSE, ffruit, fruit::fid, fruit::fname, FOOD_CLASS, LOW_PM, newfruit, fruit::nextf, nmcpy(), OBJ_NAME, objects, objclass::oc_class, pl_fruit, PL_FSIZ, Strcpy, and TRUE.
Referenced by ghostfruit(), initoptions(), and parseoptions().
{
    register int i;
    register struct fruit *f;
    struct fruit *lastf = 0;
    int highest_fruit_id = 0;
    char buf[PL_FSIZ];
    boolean user_specified = (str == pl_fruit);
    /* if not user-specified, then it's a fruit name for a fruit on
     * a bones level...
     */
    /* Note: every fruit has an id (spe for fruit objects) of at least
     * 1; 0 is an error.
     */
    if (user_specified) {
        /* disallow naming after other foods (since it'd be impossible
         * to tell the difference)
         */
        boolean found = FALSE, numeric = FALSE;
        for (i = bases[FOOD_CLASS]; objects[i].oc_class ==
      FOOD_CLASS;
                        i++) {
            if (!strcmp(OBJ_NAME(objects[i]), pl_fruit)) {
                found = TRUE;
                break;
            }
        }
        {
            char *c;
            c = pl_fruit;
            for(c = pl_fruit; *c >= '0' && *c <= '9'; c++)
            ;
            if (isspace(*c) || *c == 0) numeric = TRUE;
        }
        if (found || numeric ||
            !strncmp(str, "cursed ", 7) ||
            !strncmp(str, "uncursed ", 9) ||
            !strncmp(str, "blessed ", 8) ||
            !strncmp(str, "partly eaten ", 13) ||
            (!strncmp(str, "tin of ", 7) &&
            (!strcmp(str+7, "spinach") ||
             name_to_mon(str+7) >= LOW_PM)) ||
            !strcmp(str, "empty tin") ||
            ((!strncmp(eos(str)-7," corpse",7) ||
                !strncmp(eos(str)-4, " egg",4)) &&
            name_to_mon(str) >= LOW_PM))
            {
                Strcpy(buf, pl_fruit);
                Strcpy(pl_fruit, "candied ");
                nmcpy(pl_fruit+8, buf, PL_FSIZ-8);
        }
    }
    for(f=ffruit; f; f = f->nextf) {
        lastf = f;
        if(f->fid > highest_fruit_id) highest_fruit_id = f->fid;
        if(!strncmp(str, f->fname, PL_FSIZ))
            goto nonew;
    }
    /* if adding another fruit would overflow spe, use a random
       fruit instead... we've got a lot to choose from. */
    if (highest_fruit_id >= 127) return rnd(127);
    highest_fruit_id++;
    f = newfruit();
    if (ffruit) lastf->nextf = f;
    else ffruit = f;
    Strcpy(f->fname, str);
    f->fid = highest_fruit_id;
    f->nextf = 0;
nonew:
    if (user_specified) current_fruit = highest_fruit_id;
    return f->fid;
}
STATIC_OVL const char* get_compopt_value (char * optname, char * buf) const
Definition at line 2887 of file options.c.
References ALIGN_BOTTOM, ALIGN_LEFT, ALIGN_RIGHT, ALIGN_TOP, aligns, ATR_BOLD, ATR_INVERSE, ATR_ULINE, instance_flags::bouldersym, buf, catname, CLR_BLUE, CLR_BRIGHT_BLUE, CLR_BRIGHT_CYAN, CLR_BRIGHT_GREEN, CLR_BRIGHT_MAGENTA, CLR_BROWN, CLR_CYAN, CLR_GREEN, CLR_MAGENTA, CLR_ORANGE, CLR_RED, CLR_YELLOW, disclosure_options, dogname, flag::end_around, flag::end_disclose, flag::end_own, flag::end_top, FEATURE_NOTICE_VER_MAJ, FEATURE_NOTICE_VER_MIN, FEATURE_NOTICE_VER_PATCH, flags, fqn_prefix, genders, horsename, iflags, flag::initalign, flag::initgend, flag::initrace, flag::initrole, flag::inv_order, MAP_MODE_ASCII10x18, MAP_MODE_ASCII12x16, MAP_MODE_ASCII16x12, MAP_MODE_ASCII16x8, MAP_MODE_ASCII4x6, MAP_MODE_ASCII6x8, MAP_MODE_ASCII7x12, MAP_MODE_ASCII8x12, MAP_MODE_ASCII8x8, MAP_MODE_ASCII_FIT_TO_SCREEN, MAP_MODE_TILES, MAXOCLASSES, instance_flags::menu_headings, flag::menu_style, instance_flags::msg_history, window_procs::name, name, NUM_DISCLOSURE_OPTIONS, instance_flags::num_pad, instance_flags::num_pad_mode, objects, objclass::oc_class, oc_syms, oc_to_str(), flag::pickup_burden, flag::pickup_types, pl_fruit, plname, preferred_pet, PREFIX_COUNT, races, roles, rolestring, instance_flags::runmode, Sprintf, Strcat, Strcpy, flag::suppress_alert, instance_flags::wc_align_message, instance_flags::wc_align_status, instance_flags::wc_backgrnd_menu, instance_flags::wc_backgrnd_message, instance_flags::wc_backgrnd_status, instance_flags::wc_backgrnd_text, instance_flags::wc_font_map, instance_flags::wc_font_menu, instance_flags::wc_font_message, instance_flags::wc_font_status, instance_flags::wc_font_text, instance_flags::wc_fontsiz_map, instance_flags::wc_fontsiz_menu, instance_flags::wc_fontsiz_message, instance_flags::wc_fontsiz_status, instance_flags::wc_fontsiz_text, instance_flags::wc_foregrnd_menu, instance_flags::wc_foregrnd_message, instance_flags::wc_foregrnd_status, instance_flags::wc_foregrnd_text, instance_flags::wc_map_mode, instance_flags::wc_player_selection, instance_flags::wc_scroll_amount, instance_flags::wc_scroll_margin, instance_flags::wc_tile_file, instance_flags::wc_tile_height, instance_flags::wc_tile_width, instance_flags::wc_vary_msgcount, and windowprocs.
Referenced by doset_add_menu().
{
    char ocl[MAXOCLASSES+1];
    static const char none[] = "(none)", randomrole[] = "random",
             to_be_done[] = "(to be done)",
             defopt[] = "default",
             defbrief[] = "def";
    int i;
    buf[0] = '\0';
    if (!strcmp(optname,"align_message"))
        Sprintf(buf, "%s", iflags.wc_align_message ==
      ALIGN_TOP ? "top" :
                   iflags.wc_align_message == ALIGN_LEFT ? "left" :
                   iflags.wc_align_message == ALIGN_BOTTOM ? "bottom" :
                   iflags.wc_align_message == ALIGN_RIGHT ? "right" :
                   defopt);
    else if (!strcmp(optname,"align_status"))
        Sprintf(buf, "%s", iflags.wc_align_status ==
      ALIGN_TOP ? "top" :
                   iflags.wc_align_status == ALIGN_LEFT ? "left" :
                   iflags.wc_align_status == ALIGN_BOTTOM ? "bottom" :
                   iflags.wc_align_status == ALIGN_RIGHT ? "right" :
                   defopt);
    else if (!strcmp(optname,"align"))
        Sprintf(buf, "%s", rolestring(flags.initalign,
      aligns, adj));
#ifdef WIN32CON
    else if (!strcmp(optname,"altkeyhandler"))
        Sprintf(buf, "%s", iflags.altkeyhandler[0] ?
            iflags.altkeyhandler : "default");
#endif
    else if (!strcmp(optname, "boulder"))
        Sprintf(buf, "%c", iflags.bouldersym ?
            iflags.bouldersym : oc_syms[(int)objects[BOULDER].
      oc_class]);
    else if (!strcmp(optname, "catname"))
        Sprintf(buf, "%s", catname[0] ? catname : none);
    else if (!strcmp(optname, "disclose")) {
        for (i = 0; i < NUM_DISCLOSURE_OPTIONS; i++) {
            char topt[2];
            if (i) Strcat(buf," ");
            topt[1] = '\0';
            topt[0] = flags.end_disclose[i];
            Strcat(buf, topt);
            topt[0] = disclosure_options[i];
            Strcat(buf, topt);
        }
    }
    else if (!strcmp(optname, "dogname"))
        Sprintf(buf, "%s", dogname[0] ? dogname : none);
    else if (!strcmp(optname, "dungeon"))
        Sprintf(buf, "%s", to_be_done);
    else if (!strcmp(optname, "effects"))
        Sprintf(buf, "%s", to_be_done);
    else if (!strcmp(optname, "font_map"))
        Sprintf(buf, "%s", iflags.wc_font_map ?
      iflags.wc_font_map : defopt);
    else if (!strcmp(optname, "font_message"))
        Sprintf(buf, "%s", iflags.wc_font_message ?
      iflags.wc_font_message : defopt);
    else if (!strcmp(optname, "font_status"))
        Sprintf(buf, "%s", iflags.wc_font_status ?
      iflags.wc_font_status : defopt);
    else if (!strcmp(optname, "font_menu"))
        Sprintf(buf, "%s", iflags.wc_font_menu ?
      iflags.wc_font_menu : defopt);
    else if (!strcmp(optname, "font_text"))
        Sprintf(buf, "%s", iflags.wc_font_text ?
      iflags.wc_font_text : defopt);
    else if (!strcmp(optname, "font_size_map")) {
        if (iflags.wc_fontsiz_map) Sprintf(buf, "%d",
      iflags.wc_fontsiz_map);
        else Strcpy(buf, defopt);
    }
    else if (!strcmp(optname, "font_size_message")) {
        if (iflags.wc_fontsiz_message) Sprintf(
      buf, "%d",
                            iflags.wc_fontsiz_message);
        else Strcpy(buf, defopt);
    }
    else if (!strcmp(optname, "font_size_status")) {
        if (iflags.wc_fontsiz_status) Sprintf(buf, "%d",
      iflags.wc_fontsiz_status);
        else Strcpy(buf, defopt);
    }
    else if (!strcmp(optname, "font_size_menu")) {
        if (iflags.wc_fontsiz_menu) Sprintf(buf, "%d",
      iflags.wc_fontsiz_menu);
        else Strcpy(buf, defopt);
    }
    else if (!strcmp(optname, "font_size_text")) {
        if (iflags.wc_fontsiz_text) Sprintf(buf, "%d",
      iflags.wc_fontsiz_text);
        else Strcpy(buf, defopt);
    }
    else if (!strcmp(optname, "fruit"))
        Sprintf(buf, "%s", pl_fruit);
    else if (!strcmp(optname, "gender"))
        Sprintf(buf, "%s", rolestring(flags.initgend,
      genders, adj));
    else if (!strcmp(optname, "horsename"))
        Sprintf(buf, "%s", horsename[0] ? horsename : none);
    else if (!strcmp(optname, "map_mode"))
        Sprintf(buf, "%s",
            iflags.wc_map_mode == MAP_MODE_TILES ? "tiles" :
            iflags.wc_map_mode == MAP_MODE_ASCII4x6 ? "ascii4x6" :
            iflags.wc_map_mode == MAP_MODE_ASCII6x8 ? "ascii6x8" :
            iflags.wc_map_mode == MAP_MODE_ASCII8x8 ? "ascii8x8" :
            iflags.wc_map_mode == MAP_MODE_ASCII16x8 ? "ascii16x8" :
            iflags.wc_map_mode == MAP_MODE_ASCII7x12 ? "ascii7x12" :
            iflags.wc_map_mode == MAP_MODE_ASCII8x12 ? "ascii8x12" :
            iflags.wc_map_mode == MAP_MODE_ASCII16x12 ? "ascii16x12" :
            iflags.wc_map_mode == MAP_MODE_ASCII12x16 ? "ascii12x16" :
            iflags.wc_map_mode == MAP_MODE_ASCII10x18 ? "ascii10x18" :
            iflags.wc_map_mode == MAP_MODE_ASCII_FIT_TO_SCREEN
       ?
            "fit_to_screen" : defopt);
    else if (!strcmp(optname, "menustyle"))
        Sprintf(buf, "%s", menutype[(int)flags.menu_style]);
    else if (!strcmp(optname, "menu_deselect_all"))
        Sprintf(buf, "%s", to_be_done);
    else if (!strcmp(optname, "menu_deselect_page"))
        Sprintf(buf, "%s", to_be_done);
    else if (!strcmp(optname, "menu_first_page"))
        Sprintf(buf, "%s", to_be_done);
    else if (!strcmp(optname, "menu_invert_all"))
        Sprintf(buf, "%s", to_be_done);
    else if (!strcmp(optname, "menu_headings")) {
        Sprintf(buf, "%s", (iflags.menu_headings ==
      ATR_BOLD) ?
            "bold" : (iflags.menu_headings == ATR_INVERSE) ?
            "inverse" : (iflags.menu_headings == ATR_ULINE) ?
            "underline" : "unknown");
    }
    else if (!strcmp(optname, "menu_invert_page"))
        Sprintf(buf, "%s", to_be_done);
    else if (!strcmp(optname, "menu_last_page"))
        Sprintf(buf, "%s", to_be_done);
    else if (!strcmp(optname, "menu_next_page"))
        Sprintf(buf, "%s", to_be_done);
    else if (!strcmp(optname, "menu_previous_page"))
        Sprintf(buf, "%s", to_be_done);
    else if (!strcmp(optname, "menu_search"))
        Sprintf(buf, "%s", to_be_done);
    else if (!strcmp(optname, "menu_select_all"))
        Sprintf(buf, "%s", to_be_done);
    else if (!strcmp(optname, "menu_select_page"))
        Sprintf(buf, "%s", to_be_done);
    else if (!strcmp(optname, "monsters"))
        Sprintf(buf, "%s", to_be_done);
    else if (!strcmp(optname, "msghistory"))
        Sprintf(buf, "%u", iflags.msg_history);
#ifdef TTY_GRAPHICS
    else if (!strcmp(optname, "msg_window"))
        Sprintf(buf, "%s", (iflags.prevmsg_window=='s') ? "single" :
                    (iflags.prevmsg_window=='c') ? "combination" :
                    (iflags.prevmsg_window=='f') ? "full" : "reversed");
#endif
    else if (!strcmp(optname, "name"))
        Sprintf(buf, "%s", plname);
    else if (!strcmp(optname, "number_pad"))
        Sprintf(buf, "%s",
            (!iflags.num_pad) ? "0=off" :
            (iflags.num_pad_mode) ? "2=on, DOS compatible" : "1=on");
    else if (!strcmp(optname, "objects"))
        Sprintf(buf, "%s", to_be_done);
    else if (!strcmp(optname, "packorder")) {
        oc_to_str(flags.inv_order, ocl);
        Sprintf(buf, "%s", ocl);
         }
#ifdef CHANGE_COLOR
    else if (!strcmp(optname, "palette"))
        Sprintf(buf, "%s", get_color_string());
#endif
    else if (!strcmp(optname, "pettype"))
        Sprintf(buf, "%s", (preferred_pet == 'c') ? "cat" :
                (preferred_pet == 'd') ? "dog" :
                (preferred_pet == 'n') ? "none" : "random");
    else if (!strcmp(optname, "pickup_burden"))
        Sprintf(buf, "%s", burdentype[flags.
      pickup_burden]);
    else if (!strcmp(optname, "pickup_types")) {
        oc_to_str(flags.pickup_types, ocl);
        Sprintf(buf, "%s", ocl[0] ? ocl : "all");
         }
    else if (!strcmp(optname, "race"))
        Sprintf(buf, "%s", rolestring(flags.initrace,
      races, noun));
    else if (!strcmp(optname, "role"))
        Sprintf(buf, "%s", rolestring(flags.initrole,
      roles, name.m));
    else if (!strcmp(optname, "runmode"))
        Sprintf(buf, "%s", runmodes[iflags.runmode]);
    else if (!strcmp(optname, "scores")) {
        Sprintf(buf, "%d top/%d around%s", flags.end_top,
                flags.end_around, flags.end_own ? "/own" : "");
    }
    else if (!strcmp(optname, "scroll_amount")) {
        if (iflags.wc_scroll_amount) Sprintf(buf, "%d",
      iflags.wc_scroll_amount);
        else Strcpy(buf, defopt);
    }
    else if (!strcmp(optname, "scroll_margin")) {
        if (iflags.wc_scroll_margin) Sprintf(buf, "%d",
      iflags.wc_scroll_margin);
        else Strcpy(buf, defopt);
    }
    else if (!strcmp(optname, "player_selection"))
        Sprintf(buf, "%s", iflags.wc_player_selection ? "prompts" : "
      dialog");
#ifdef MSDOS
    else if (!strcmp(optname, "soundcard"))
        Sprintf(buf, "%s", to_be_done);
#endif
    else if (!strcmp(optname, "suppress_alert")) {
        if (flags.suppress_alert == 0L)
        Strcpy(buf, none);
        else
        Sprintf(buf, "%lu.%lu.%lu",
            FEATURE_NOTICE_VER_MAJ,
            FEATURE_NOTICE_VER_MIN,
            FEATURE_NOTICE_VER_PATCH);
    }
    else if (!strcmp(optname, "tile_file"))
        Sprintf(buf, "%s", iflags.wc_tile_file ?
      iflags.wc_tile_file : defopt);
    else if (!strcmp(optname, "tile_height")) {
        if (iflags.wc_tile_height) Sprintf(buf, "%d",
      iflags.wc_tile_height);
        else Strcpy(buf, defopt);
    }
    else if (!strcmp(optname, "tile_width")) {
        if (iflags.wc_tile_width) Sprintf(buf, "%d",
      iflags.wc_tile_width);
        else Strcpy(buf, defopt);
    }
    else if (!strcmp(optname, "traps"))
        Sprintf(buf, "%s", to_be_done);
    else if (!strcmp(optname, "vary_msgcount")) {
        if (iflags.wc_vary_msgcount) Sprintf(buf, "%d",
      iflags.wc_vary_msgcount);
        else Strcpy(buf, defopt);
    }
#ifdef MSDOS
    else if (!strcmp(optname, "video"))
        Sprintf(buf, "%s", to_be_done);
#endif
#ifdef VIDEOSHADES
    else if (!strcmp(optname, "videoshades"))
        Sprintf(buf, "%s-%s-%s", shade[0],shade[1],shade[2]);
    else if (!strcmp(optname, "videocolors"))
        Sprintf(buf, "%d-%d-%d-%d-%d-%d-%d-%d-%d-%d-%d-%d",
            ttycolors[CLR_RED], ttycolors[CLR_GREEN],
            ttycolors[CLR_BROWN], ttycolors[CLR_BLUE],
            ttycolors[CLR_MAGENTA], ttycolors[CLR_CYAN],
            ttycolors[CLR_ORANGE], ttycolors[CLR_BRIGHT_GREEN],
            ttycolors[CLR_YELLOW], ttycolors[CLR_BRIGHT_BLUE],
            ttycolors[CLR_BRIGHT_MAGENTA],
            ttycolors[CLR_BRIGHT_CYAN]);
#endif /* VIDEOSHADES */
    else if (!strcmp(optname, "windowtype"))
        Sprintf(buf, "%s", windowprocs.name);
    else if (!strcmp(optname, "windowcolors"))
        Sprintf(buf, "%s/%s %s/%s %s/%s %s/%s",
            iflags.wc_foregrnd_menu ? iflags.
      wc_foregrnd_menu : defbrief,
            iflags.wc_backgrnd_menu ? iflags.
      wc_backgrnd_menu : defbrief,
            iflags.wc_foregrnd_message ? iflags.
      wc_foregrnd_message : defbrief,
            iflags.wc_backgrnd_message ? iflags.
      wc_backgrnd_message : defbrief,
            iflags.wc_foregrnd_status ? iflags.
      wc_foregrnd_status : defbrief,
            iflags.wc_backgrnd_status ? iflags.
      wc_backgrnd_status : defbrief,
            iflags.wc_foregrnd_text ? iflags.
      wc_foregrnd_text : defbrief,
            iflags.wc_backgrnd_text ? iflags.
      wc_backgrnd_text : defbrief);
#ifdef PREFIXES_IN_USE
    else {
        for (i = 0; i < PREFIX_COUNT; ++i)
        if (!strcmp(optname, fqn_prefix_names[i]) && fqn_prefix[i])
            Sprintf(buf, "%s", fqn_prefix[i]);
    }
#endif
    if (buf[0]) return buf;
    else return "unknown";
}
STATIC_OVL void graphics_opts (char * opts, const char * optype, int maxlen, int offset)
Definition at line 811 of file options.c.
References assign_graphics(), escapes(), FALSE, MAXPCHARS, and string_for_env_opt().
Referenced by parseoptions().
{
    uchar translate[MAXPCHARS+1];
    int length, i;
    if (!(opts = string_for_env_opt(optype, opts, FALSE)))
        return;
    escapes(opts, opts);
    length = strlen(opts);
    if (length > maxlen) length = maxlen;
    /* match the form obtained from PC configuration files */
    for (i = 0; i < length; i++)
        translate[i] = (uchar) opts[i];
    assign_graphics(translate, length, maxlen, offset);
}
void initoptions ()
Definition at line 489 of file options.c.
References Bool_Opt::addr, AE, AS, ASCII_GRAPHICS, ATR_INVERSE, boolopt, instance_flags::bouldersym, BUFSZ, DEC_GRAPHICS, def_monsyms, def_oc_syms, def_warnsyms, DISCLOSE_PROMPT_DEFAULT_NO, flag::end_around, flag::end_disclose, flag::end_own, flag::end_top, FALSE, flags, fruitadd(), getenv, IBM_GRAPHICS, iflags, index(), flag::initalign, flag::initgend, flag::initrace, flag::initrole, flag::inv_order, MAC_GRAPHICS, MAXMCLASSES, MAXOCLASSES, MENU_FULL, instance_flags::menu_headings, flag::menu_style, MOD_ENCUMBER, monsyms, instance_flags::msg_history, Bool_Opt::name, nh_getenv(), nmcpy(), NUM_DISCLOSURE_OPTIONS, obj_descr, OBJ_NAME, objects, objdescr::oc_name, objclass::oc_name_idx, oc_syms, instance_flags::opt_booldup, instance_flags::opt_compdup, parseoptions(), flag::pickup_burden, flag::pickup_types, pl_fruit, PL_FSIZ, read_config_file(), RUN_LEAP, instance_flags::runmode, strncmpi(), switch_graphics(), instance_flags::travelcc, TRUE, WARNCOUNT, flag::warnlevel, warnsyms, flag::warntype, coord::x, and coord::y.
Referenced by MAIN(), and main().
{
#ifndef MAC
    char *opts;
#endif
    int i;
    /* initialize the random number generator */
    setrandom();
    /* for detection of configfile options specified multiple times */
    iflags.opt_booldup = iflags.opt_compdup = (int *)0;
    
    for (i = 0; boolopt[i].name; i++) {
        if (boolopt[i].addr)
            *(boolopt[i].addr) = boolopt[i].initvalue;
    }
    flags.end_own = FALSE;
    flags.end_top = 3;
    flags.end_around = 2;
    iflags.runmode = RUN_LEAP;
    iflags.msg_history = 20;
#ifdef TTY_GRAPHICS
    iflags.prevmsg_window = 's';
#endif
    iflags.menu_headings = ATR_INVERSE;
    /* Use negative indices to indicate not yet selected */
    flags.initrole = -1;
    flags.initrace = -1;
    flags.initgend = -1;
    flags.initalign = -1;
    /* Set the default monster and object class symbols. Don't use */
    /* memcpy() --- sizeof char != sizeof uchar on some machines. */
    for (i = 0; i < MAXOCLASSES; i++)
        oc_syms[i] = (uchar) def_oc_syms[i];
    for (i = 0; i < MAXMCLASSES; i++)
        monsyms[i] = (uchar) def_monsyms[i];
    for (i = 0; i < WARNCOUNT; i++)
        warnsyms[i] = def_warnsyms[i].sym;
    iflags.bouldersym = 0;
    iflags.travelcc.x = iflags.travelcc.y = -1;
    flags.warnlevel = 1;
    flags.warntype = 0L;
     /* assert(sizeof flags.inv_order == sizeof def_inv_order); */
    (void)memcpy((genericptr_t)flags.inv_order,
             (genericptr_t)def_inv_order, sizeof flags.
      inv_order);
    flags.pickup_types[0] = '\0';
    flags.pickup_burden = MOD_ENCUMBER;
    for (i = 0; i < NUM_DISCLOSURE_OPTIONS; i++)
        flags.end_disclose[i] = DISCLOSE_PROMPT_DEFAULT_NO;
    switch_graphics(ASCII_GRAPHICS); /* set default characters */
#if defined(UNIX) && defined(TTY_GRAPHICS)
    /*
     * Set defaults for some options depending on what we can
     * detect about the environment's capabilities.
     * This has to be done after the global initialization above
     * and before reading user-specific initialization via
     * config file/environment variable below.
     */
    /* this detects the IBM-compatible console on most 386 boxes */
    if ((opts = nh_getenv("TERM")) && !strncmp(opts, "AT", 2)) {
        switch_graphics(IBM_GRAPHICS);
# ifdef TEXTCOLOR
        iflags.use_color = TRUE;
# endif
    }
#endif /* UNIX && TTY_GRAPHICS */
#if defined(UNIX) || defined(VMS)
# ifdef TTY_GRAPHICS
    /* detect whether a "vt" terminal can handle alternate charsets */
    if ((opts = nh_getenv("TERM")) &&
        !strncmpi(opts, "vt", 2) && AS && AE &&
        index(AS, '\016') && index(AE, '\017')) {
        switch_graphics(DEC_GRAPHICS);
    }
# endif
#endif /* UNIX || VMS */
#ifdef MAC_GRAPHICS_ENV
    switch_graphics(MAC_GRAPHICS);
#endif /* MAC_GRAPHICS_ENV */
    flags.menu_style = MENU_FULL;
    /* since this is done before init_objects(), do partial init here */
    objects[SLIME_MOLD].oc_name_idx = SLIME_MOLD;
    nmcpy(pl_fruit, OBJ_NAME(objects[SLIME_MOLD]),
      PL_FSIZ);
#ifndef MAC
    opts = getenv("NETHACKOPTIONS");
    if (!opts) opts = getenv("HACKOPTIONS");
    if (opts) {
        if (*opts == '/' || *opts == '\\' || *opts == '@') {
            if (*opts == '@') opts++; /* @filename */
            /* looks like a filename */
            if (strlen(opts) < BUFSZ/2)
                read_config_file(opts);
        } else {
            read_config_file((char *)0);
            /* let the total length of options be long;
             * parseoptions() will check each individually
             */
            parseoptions(opts, TRUE, FALSE);
        }
    } else
#endif
        read_config_file((char *)0);
    (void)fruitadd(pl_fruit);
    /* Remove "slime mold" from list of object names; this will */
    /* prevent it from being wished unless it's actually present */
    /* as a named (or default) fruit. Wishing for "fruit" will */
    /* result in the player's preferred fruit [better than "\033"]. */
    obj_descr[SLIME_MOLD].oc_name = "fruit";
    return;
}
STATIC_OVL boolean is_wc2_option (char * optnam) const
Definition at line 3716 of file options.c.
References FALSE, TRUE, and wc_Opt::wc_name.
Referenced by doset().
{
    int k = 0;
    while (wc2_options[k].wc_name) {
        if (strcmp(wc2_options[k].wc_name, optnam) == 0)
            return TRUE;
        k++;
    }
    return FALSE;
}
STATIC_OVL boolean is_wc_option (char * optnam) const
Definition at line 3660 of file options.c.
References FALSE, TRUE, and wc_Opt::wc_name.
Referenced by doset().
{
    int k = 0;
    while (wc_options[k].wc_name) {
        if (strcmp(wc_options[k].wc_name, optnam) == 0)
            return TRUE;
        k++;
    }
    return FALSE;
}
char map_menu_cmd (char ch)
Definition at line 2309 of file options.c.
References index(), and mapped_menu_cmds.
Referenced by DoMenuScroll(), mac_select_menu(), and menu_key().
{
    char *found = index(mapped_menu_cmds, ch);
    if (found) {
    int idx = found - mapped_menu_cmds;
    ch = mapped_menu_op[idx];
    }
    return ch;
}
boolean match_optname (char * user_string, char * opt_name, int min_length, boolean val_allowed) const
Definition at line 450 of file options.c.
References index(), and strncmpi().
Referenced by duplicate_opt_detection(), and parseoptions().
{
    int len = (int)strlen(user_string);
    if (val_allowed) {
        const char *p = index(user_string, ':'),
               *q = index(user_string, '=');
        if (!p || (q && q < p)) p = q;
        while(p && p > user_string && isspace(*(p-1))) p--;
        if (p) len = (int)(p - user_string);
    }
    return (len >= min_length) && !strncmpi(opt_name, user_string, len);
}
void next_opt (winid datawin, const char * str)
Definition at line 3339 of file options.c.
References alloc(), buf, BUFSZ, COLNO, eos(), free(), putstr, Strcat, and Strcpy.
Referenced by option_help().
{
    static char *buf = 0;
    int i;
    char *s;
    if (!buf) *(buf = (char *)alloc(BUFSZ)) = '\0';
    if (!*str) {
        s = eos(buf);
        if (s > &buf[1] && s[-2] == ',')
            Strcpy(s - 2, "."); /* replace last ", " */
        i = COLNO; /* (greater than COLNO - 2) */
    } else {
        i = strlen(buf) + strlen(str) + 2;
    }
    if (i > COLNO - 2) { /* rule of thumb */
        putstr(datawin, 0, buf);
        buf[0] = 0;
    }
    if (*str) {
        Strcat(buf, str);
        Strcat(buf, ", ");
    } else {
        putstr(datawin, 0, str);
        free(buf), buf = 0;
    }
    return;
}
char* nh_getenv (char * ev) const
Definition at line 477 of file options.c.
References BUFSZ, and getenv.
Referenced by fopen_config_file(), initoptions(), MAIN(), main(), makelevel(), process_options(), and whoami().
{
    char *getev = getenv(ev);
    if (getev && strlen(getev) <= (BUFSZ / 2))
        return getev;
    else
        return (char *)0;
}
STATIC_OVL void nmcpy (char	* dest, const char * src, int maxlen)
Definition at line 610 of file options.c.
References count.
Referenced by fruitadd(), initoptions(), and parseoptions().
{
    int count;
    for(count = 1; count < maxlen; count++) {
        if(*src == ',' || *src == '\0') break; /*exit on \0 terminator*/
        *dest++ = *src++;
    }
    *dest = 0;
}
STATIC_OVL void oc_to_str (char * src, char * dest)
Definition at line 2271 of file options.c.
References def_oc_syms, and MAXOCLASSES.
Referenced by dotogglepickup(), get_compopt_value(), and parseoptions().
{
    int i;
    while ((i = (int) *src++) != 0) {
    if (i < 0 || i >= MAXOCLASSES)
        impossible("oc_to_str: illegal object class %d", i);
    else
        *dest++ = def_oc_syms[i];
    }
    *dest = '\0';
}
void option_help ()
Definition at line 3293 of file options.c.
References boolopt, buf, BUFSZ, compopt, CONFIG_SLOT, configfile, create_nhwindow, destroy_nhwindow, display_nhwindow, FALSE, iflags, instance_flags::menu_tab_sep, Bool_Opt::name, name, Comp_Opt::name, next_opt(), NHW_TEXT, putstr, Sprintf, and wizard.
Referenced by badoption(), dohelp(), and onWMCommand().
{
    char buf[BUFSZ], buf2[BUFSZ];
    register int i;
    winid datawin;
    datawin = create_nhwindow(NHW_TEXT);
    Sprintf(buf, "Set options as OPTIONS=<options> in %s", configfile);
    opt_intro[CONFIG_SLOT] = (const char *) buf;
    for (i = 0; opt_intro[i]; i++)
    putstr(datawin, 0, opt_intro[i]);
    /* Boolean options */
    for (i = 0; boolopt[i].name; i++) {
    if (boolopt[i].addr) {
#ifdef WIZARD
        if (boolopt[i].addr == &iflags.sanity_check && !wizard) continue;
        if (boolopt[i].addr == &iflags.menu_tab_sep && !
      wizard) continue;
#endif
        next_opt(datawin, boolopt[i].name);
    }
    }
    next_opt(datawin, "");
    /* Compound options */
    putstr(datawin, 0, "Compound options:");
    for (i = 0; compopt[i].name; i++) {
    Sprintf(buf2, "`%s'", compopt[i].name);
    Sprintf(buf, "%-20s - %s%c", buf2, compopt[i].descr,
        compopt[i+1].name ? ',' : '.');
    putstr(datawin, 0, buf);
    }
    for (i = 0; opt_epilog[i]; i++)
    putstr(datawin, 0, opt_epilog[i]);
    display_nhwindow(datawin, FALSE);
    destroy_nhwindow(datawin);
    return;
}
void parseoptions (char * opts, boolean tinitial, boolean tfrom_file)
Definition at line 968 of file options.c.
References add_menu_cmd_alias(), Bool_Opt::addr, ALIGN_BOTTOM, ALIGN_LEFT, ALIGN_RIGHT, ALIGN_TOP, alloc(), ASCII_GRAPHICS, ASCIIGRAPH, assign_soundcard(), ATR_BOLD, ATR_INVERSE, ATR_ULINE, bad_negation(), badoption(), boolopt, flag::botl, instance_flags::bouldersym, buf, BUFSZ, catname, change_inv_order(), choose_classes_menu(), choose_windows(), CLR_MAX, DEC_GRAPHICS, instance_flags::DECgraphics, def_char_to_monclass(), def_char_to_objclass(), def_oc_syms, DISCLOSE_NO_WITHOUT_PROMPT, DISCLOSE_PROMPT_DEFAULT_NO, DISCLOSE_PROMPT_DEFAULT_YES, DISCLOSE_YES_WITHOUT_PROMPT, disclosure_options, dogname, duplicate_opt_detection(), flag::end_around, flag::end_disclose, flag::end_own, flag::end_top, eos(), escapes(), EXP_ON_BOTL, EXT_ENCUMBER, FALSE, feature_alert_opts(), flag::female, ffruit, flags, fruit::fname, free(), fruitadd(), getlin, goodfruit(), graphics_opts(), horsename, HVY_ENCUMBER, IBM_GRAPHICS, instance_flags::IBMgraphics, iflags, index(), flag::initalign, flag::initgend, flag::initrace, flag::initrole, flag::inv_order, flag::invlet_constant, Is_rogue_level, flag::lit_corridor, lowc(), MAC, MAC_GRAPHICS, MAP_MODE_ASCII10x18, MAP_MODE_ASCII12x16, MAP_MODE_ASCII16x12, MAP_MODE_ASCII16x8, MAP_MODE_ASCII4x6, MAP_MODE_ASCII6x8, MAP_MODE_ASCII7x12, MAP_MODE_ASCII8x12, MAP_MODE_ASCII8x8, MAP_MODE_ASCII_FIT_TO_SCREEN, MAP_MODE_TILES, match_optname(), MAXDCHARS, MAXECHARS, MAXMCLASSES, MAXOCLASSES, MAXPCHARS, MAXTCHARS, MENU_COMBINATION, MENU_FULL, instance_flags::menu_headings, MENU_PARTIAL, flag::menu_style, MENU_TRADITIONAL, MOD_ENCUMBER, monsyms, instance_flags::msg_history, Bool_Opt::name, name, menu_cmd_t::name, fruit::nextf, NHW_MAP, NHW_MENU, NHW_MESSAGE, NHW_STATUS, NHW_TEXT, nmcpy(), NUM_DISCLOSURE_OPTIONS, NUM_MENU_CMDS, instance_flags::num_pad, instance_flags::num_pad_mode, number_pad, oc_syms, oc_to_str(), OVERLOADED, flag::pickup, flag::pickup_burden, flag::pickup_types, pl_character, pl_fruit, PL_FSIZ, PL_NSIZ, PL_PSIZ, pl_race, plname, preferred_pet, QBUFSZ, rejectoption(), ROLE_NONE, RUN_CRAWL, RUN_LEAP, RUN_STEP, RUN_TPORT, instance_flags::runmode, SET_IN_FILE, instance_flags::showrace, SLT_ENCUMBER, Sprintf, str2align(), str2gend(), str2race(), str2role(), strcmpi, Strcpy, string_for_env_opt(), string_for_opt(), strncmpi(), switch_graphics(), TERMLIB, flag::time, TRUE, u, UNENCUMBERED, you::uz, VIA_DIALOG, VIA_PROMPTS, vision_full_recalc, vision_recalc(), warning_opts(), instance_flags::wc_align_message, instance_flags::wc_align_status, instance_flags::wc_fontsiz_map, instance_flags::wc_fontsiz_menu, instance_flags::wc_fontsiz_message, instance_flags::wc_fontsiz_status, instance_flags::wc_fontsiz_text, instance_flags::wc_map_mode, instance_flags::wc_player_selection, instance_flags::wc_scroll_amount, instance_flags::wc_scroll_margin, wc_set_font_name(), wc_set_window_colors(), instance_flags::wc_tile_file, instance_flags::wc_tile_height, instance_flags::wc_tile_width, instance_flags::wc_vary_msgcount, and WINTYPELEN.
Referenced by doset(), initoptions(), parse_config_line(), and special_handling().
{
    register char *op;
    unsigned num;
    boolean negated;
    int i;
    const char *fullname;
    initial = tinitial;
    from_file = tfrom_file;
    if ((op = index(opts, ',')) != 0) {
        *op++ = 0;
        parseoptions(op, initial, from_file);
    }
    if (strlen(opts) > BUFSZ/2) {
        badoption("option too long");
        return;
    }
    /* strip leading and trailing white space */
    while (isspace(*opts)) opts++;
    op = eos(opts);
    while (--op >= opts && isspace(*op)) *op = '\0';
    if (!*opts) return;
    negated = FALSE;
    while ((*opts == '!') || !strncmpi(opts, "no", 2)) {
        if (*opts == '!') opts++; else opts += 2;
        negated = !negated;
    }
    /* variant spelling */
    if (match_optname(opts, "colour", 5, FALSE))
        Strcpy(opts, "color"); /* fortunately this isn't longer */
    if (!match_optname(opts, "subkeyvalue", 11, TRUE)) /* allow multiple */
    duplicate_opt_detection(opts, 1); /* 1 means compound opts */
    /* special boolean options */
    if (match_optname(opts, "female", 3, FALSE)) {
        if(!initial && flags.female == negated)
            pline("That is not anatomically possible.");
        else
            flags.initgend = flags.female = !negated;
        return;
    }
    if (match_optname(opts, "male", 4, FALSE)) {
        if(!initial && flags.female != negated)
            pline("That is not anatomically possible.");
        else
            flags.initgend = flags.female = negated;
        return;
    }
#if defined(MICRO) && !defined(AMIGA)
    /* included for compatibility with old NetHack.cnf files */
    if (match_optname(opts, "IBM_", 4, FALSE)) {
        iflags.BIOS = !negated;
        return;
    }
#endif /* MICRO */
    /* compound options */
    fullname = "pettype";
    if (match_optname(opts, fullname, 3, TRUE)) {
        if ((op = string_for_env_opt(fullname, opts, negated)) != 0) {
            if (negated) bad_negation(fullname, TRUE);
            else switch (*op) {
            case 'd': /* dog */
            case 'D':
                preferred_pet = 'd';
                break;
            case 'c': /* cat */
            case 'C':
            case 'f': /* feline */
            case 'F':
                preferred_pet = 'c';
                break;
            case 'n': /* no pet */
            case 'N':
                preferred_pet = 'n';
                break;
            default:
                pline("Unrecognized pet type '%s'.", op);
                break;
            }
        } else if (negated) preferred_pet = 'n';
        return;
    }
    fullname = "catname";
    if (match_optname(opts, fullname, 3, TRUE)) {
        if (negated) bad_negation(fullname, FALSE);
        else if ((op = string_for_env_opt(fullname, opts,
      FALSE)) != 0)
            nmcpy(catname, op, PL_PSIZ);
        return;
    }
    fullname = "dogname";
    if (match_optname(opts, fullname, 3, TRUE)) {
        if (negated) bad_negation(fullname, FALSE);
        else if ((op = string_for_env_opt(fullname, opts,
      FALSE)) != 0)
            nmcpy(dogname, op, PL_PSIZ);
        return;
    }
    fullname = "horsename";
    if (match_optname(opts, fullname, 5, TRUE)) {
        if (negated) bad_negation(fullname, FALSE);
        else if ((op = string_for_env_opt(fullname, opts,
      FALSE)) != 0)
            nmcpy(horsename, op, PL_PSIZ);
        return;
    }
    fullname = "number_pad";
    if (match_optname(opts, fullname, 10, TRUE)) {
        boolean compat = (strlen(opts) <= 10);
        number_pad(iflags.num_pad ? 1 : 0);
        op = string_for_opt(opts, (compat || !initial));
        if (!op) {
            if (compat || negated || initial) {
            /* for backwards compatibility, "number_pad" without a
               value is a synonym for number_pad:1 */
            iflags.num_pad = !negated;
            if (iflags.num_pad) iflags.num_pad_mode = 0;
            }
            return;
        }
        if (negated) {
            bad_negation("number_pad", TRUE);
            return;
        }
        if (*op == '1' || *op == '2') {
            iflags.num_pad = 1;
            if (*op == '2') iflags.num_pad_mode = 1;
            else iflags.num_pad_mode = 0;
        } else if (*op == '0') {
            iflags.num_pad = 0;
            iflags.num_pad_mode = 0;
        } else badoption(opts);
        return;
    }
    fullname = "runmode";
    if (match_optname(opts, fullname, 4, TRUE)) {
        if (negated) {
            iflags.runmode = RUN_TPORT;
        } else if ((op = string_for_opt(opts, FALSE)) != 0) {
            if (!strncmpi(op, "teleport", strlen(op)))
            iflags.runmode = RUN_TPORT;
            else if (!strncmpi(op, "run", strlen(op)))
            iflags.runmode = RUN_LEAP;
            else if (!strncmpi(op, "walk", strlen(op)))
            iflags.runmode = RUN_STEP;
            else if (!strncmpi(op, "crawl", strlen(op)))
            iflags.runmode = RUN_CRAWL;
            else
            badoption(opts);
        }
        return;
    }
    fullname = "msghistory";
    if (match_optname(opts, fullname, 3, TRUE)) {
        op = string_for_env_opt(fullname, opts, negated);
        if ((negated && !op) || (!negated && op)) {
            iflags.msg_history = negated ? 0 : atoi(op);
        } else if (negated) bad_negation(fullname, TRUE);
        return;
    }
    fullname="msg_window";
    /* msg_window:single, combo, full or reversed */
    if (match_optname(opts, fullname, 4, TRUE)) {
    /* allow option to be silently ignored by non-tty ports */
#ifdef TTY_GRAPHICS
        int tmp;
        if (!(op = string_for_opt(opts, TRUE))) {
            tmp = negated ? 's' : 'f';
        } else {
              if (negated) {
                bad_negation(fullname, TRUE);
                return;
                  }
            tmp = tolower(*op);
        }
        switch (tmp) {
            case 's': /* single message history cycle (default if negated) */
                iflags.prevmsg_window = 's';
                break;
            case 'c': /* combination: two singles, then full page reversed */
                iflags.prevmsg_window = 'c';
                break;
            case 'f': /* full page (default if no opts) */
                iflags.prevmsg_window = 'f';
                break;
            case 'r': /* full page (reversed) */
                iflags.prevmsg_window = 'r';
                break;
            default:
                badoption(opts);
        }
#endif
        return;
    }
    /* WINCAP
     * setting font options */
    fullname = "font";
    if (!strncmpi(opts, fullname, 4))
    {
        int wintype = -1;
        char *fontopts = opts + 4;
        if (!strncmpi(fontopts, "map", 3) ||
            !strncmpi(fontopts, "_map", 4))
            wintype = NHW_MAP;
        else if (!strncmpi(fontopts, "message", 7) ||
             !strncmpi(fontopts, "_message", 8))
            wintype = NHW_MESSAGE;
        else if (!strncmpi(fontopts, "text", 4) ||
             !strncmpi(fontopts, "_text", 5))
            wintype = NHW_TEXT;
        else if (!strncmpi(fontopts, "menu", 4) ||
             !strncmpi(fontopts, "_menu", 5))
            wintype = NHW_MENU;
        else if (!strncmpi(fontopts, "status", 6) ||
             !strncmpi(fontopts, "_status", 7))
            wintype = NHW_STATUS;
        else if (!strncmpi(fontopts, "_size", 5)) {
            if (!strncmpi(fontopts, "_size_map", 8))
                wintype = NHW_MAP;
            else if (!strncmpi(fontopts, "_size_message", 12))
                wintype = NHW_MESSAGE;
            else if (!strncmpi(fontopts, "_size_text", 9))
                wintype = NHW_TEXT;
            else if (!strncmpi(fontopts, "_size_menu", 9))
                wintype = NHW_MENU;
            else if (!strncmpi(fontopts, "_size_status", 11))
                wintype = NHW_STATUS;
            else {
                badoption(opts);
                return;
            }
            if (wintype > 0 && !negated &&
                (op = string_for_opt(opts, FALSE)) != 0) {
                switch(wintype) {
                    case NHW_MAP:
                    iflags.wc_fontsiz_map = atoi(op);
                    break;
                    case NHW_MESSAGE:
                    iflags.wc_fontsiz_message = atoi(op);
                    break;
                    case NHW_TEXT:
                    iflags.wc_fontsiz_text = atoi(op);
                    break;
                    case NHW_MENU:
                    iflags.wc_fontsiz_menu = atoi(op);
                    break;
                    case NHW_STATUS:
                    iflags.wc_fontsiz_status = atoi(op);
                    break;
                }
            }
            return;
        } else {
            badoption(opts);
        }
        if (wintype > 0 &&
            (op = string_for_opt(opts, FALSE)) != 0) {
            wc_set_font_name(wintype, op);
#ifdef MAC
            set_font_name (wintype, op);
#endif
            return;
        } else if (negated) bad_negation(fullname, TRUE);
        return;
    }
#ifdef CHANGE_COLOR
    if (match_optname(opts, "palette", 3, TRUE)
# ifdef MAC
        || match_optname(opts, "hicolor", 3, TRUE)
# endif
                            ) {
        int color_number, color_incr;
# ifdef MAC
        if (match_optname(opts, "hicolor", 3, TRUE)) {
        if (negated) {
            bad_negation("hicolor", FALSE);
            return;
        }
        color_number = CLR_MAX + 4; /* HARDCODED inverse number */
        color_incr = -1;
        } else {
# endif
        if (negated) {
            bad_negation("palette", FALSE);
            return;
        }
        color_number = 0;
        color_incr = 1;
# ifdef MAC
        }
# endif
        if ((op = string_for_opt(opts, FALSE)) != (char *)0) {
        char *pt = op;
        int cnt, tmp, reverse;
        long rgb;
        while (*pt && color_number >= 0) {
            cnt = 3;
            rgb = 0L;
            if (*pt == '-') {
            reverse = 1;
            pt++;
            } else {
            reverse = 0;
            }
            while (cnt-- > 0) {
            if (*pt && *pt != '/') {
# ifdef AMIGA
                rgb <<= 4;
# else
                rgb <<= 8;
# endif
                tmp = *(pt++);
                if (isalpha(tmp)) {
                tmp = (tmp + 9) & 0xf; /* Assumes ASCII... */
                } else {
                tmp &= 0xf; /* Digits in ASCII too... */
                }
# ifndef AMIGA
                /* Add an extra so we fill f -> ff and 0 -> 00 */
                rgb += tmp << 4;
# endif
                rgb += tmp;
            }
            }
            if (*pt == '/') {
            pt++;
            }
            change_color(color_number, rgb, reverse);
            color_number += color_incr;
        }
        }
        if (!initial) {
        need_redraw = TRUE;
        }
        return;
    }
#endif /* CHANGE_COLOR */
    if (match_optname(opts, "fruit", 2, TRUE)) {
        char empty_str = '\0';
        op = string_for_opt(opts, negated);
        if (negated) {
            if (op) {
            bad_negation("fruit", TRUE);
            return;
            }
            op = &empty_str;
            goto goodfruit;
        }
        if (!op) return;
        if (!initial) {
            struct fruit *f;
            num = 0;
            for(f=ffruit; f; f=f->nextf) {
            if (!strcmp(op, f->fname)) goto goodfruit;
            num++;
            }
            if (num >= 100) {
            pline("Doing that so many times isn't very fruitful.");
            return;
            }
        }
goodfruit:
        nmcpy(pl_fruit, op, PL_FSIZ);
    /* OBJ_NAME(objects[SLIME_MOLD]) won't work after initialization */
        if (!*pl_fruit)
            nmcpy(pl_fruit, "slime mold", PL_FSIZ);
        if (!initial)
            (void)fruitadd(pl_fruit);
        /* If initial, then initoptions is allowed to do it instead
         * of here (initoptions always has to do it even if there's
         * no fruit option at all. Also, we don't want people
         * setting multiple fruits in their options.)
         */
        return;
    }
    /* graphics:string */
    fullname = "graphics";
    if (match_optname(opts, fullname, 2, TRUE)) {
        if (negated) bad_negation(fullname, FALSE);
        else graphics_opts(opts, fullname, MAXPCHARS, 0);
        return;
    }
    fullname = "dungeon";
    if (match_optname(opts, fullname, 2, TRUE)) {
        if (negated) bad_negation(fullname, FALSE);
        else graphics_opts(opts, fullname, MAXDCHARS, 0);
        return;
    }
    fullname = "traps";
    if (match_optname(opts, fullname, 2, TRUE)) {
        if (negated) bad_negation(fullname, FALSE);
        else graphics_opts(opts, fullname, MAXTCHARS,
      MAXDCHARS);
        return;
    }
    fullname = "effects";
    if (match_optname(opts, fullname, 2, TRUE)) {
        if (negated) bad_negation(fullname, FALSE);
        else
         graphics_opts(opts, fullname, MAXECHARS,
      MAXDCHARS+MAXTCHARS);
        return;
    }
    /* objects:string */
    fullname = "objects";
    if (match_optname(opts, fullname, 7, TRUE)) {
        int length;
        if (negated) {
            bad_negation(fullname, FALSE);
            return;
        }
        if (!(opts = string_for_env_opt(fullname, opts, FALSE)))
            return;
        escapes(opts, opts);
        /*
         * Override the default object class symbols. The first
         * object in the object class is the "random object". I
         * don't want to use 0 as an object class, so the "random
         * object" is basically a place holder.
         *
         * The object class symbols have already been initialized in
         * initoptions().
         */
        length = strlen(opts);
        if (length >= MAXOCLASSES)
            length = MAXOCLASSES-1; /* don't count RANDOM_OBJECT */
        for (i = 0; i < length; i++)
            oc_syms[i+1] = (uchar) opts[i];
        return;
    }
    /* monsters:string */
    fullname = "monsters";
    if (match_optname(opts, fullname, 8, TRUE)) {
        int length;
        if (negated) {
            bad_negation(fullname, FALSE);
            return;
        }
        if (!(opts = string_for_env_opt(fullname, opts, FALSE)))
            return;
        escapes(opts, opts);
        /* Override default mon class symbols set in initoptions(). */
        length = strlen(opts);
        if (length >= MAXMCLASSES)
            length = MAXMCLASSES-1; /* mon class 0 unused */
        for (i = 0; i < length; i++)
            monsyms[i+1] = (uchar) opts[i];
        return;
    }
    fullname = "warnings";
    if (match_optname(opts, fullname, 5, TRUE)) {
        if (negated) bad_negation(fullname, FALSE);
        else warning_opts(opts, fullname);
        return;
    }
    /* boulder:symbol */
    fullname = "boulder";
    if (match_optname(opts, fullname, 7, TRUE)) {
        int clash = 0;
        if (negated) {
            bad_negation(fullname, FALSE);
            return;
        }
/* if (!(opts = string_for_env_opt(fullname, opts, FALSE))) */
        if (!(opts = string_for_opt(opts, FALSE)))
            return;
        escapes(opts, opts);
        if (def_char_to_monclass(opts[0]) != MAXMCLASSES)
            clash = 1;
        else if (opts[0] >= '1' && opts[0] <= '5')
            clash = 2;
        if (clash) {
            /* symbol chosen matches a used monster or warning
               symbol which is not good - reject it*/
            pline(
          "Badoption - boulder symbol '%c' conflicts with a %s symbol.",
                opts[0], (clash == 1) ? "monster" : "warning");
        } else {
            /*
             * Override the default boulder symbol.
             */
            iflags.bouldersym = (uchar) opts[0];
        }
        if (!initial) need_redraw = TRUE;
        return;
    }
    /* name:string */
    fullname = "name";
    if (match_optname(opts, fullname, 4, TRUE)) {
        if (negated) bad_negation(fullname, FALSE);
        else if ((op = string_for_env_opt(fullname, opts,
      FALSE)) != 0)
            nmcpy(plname, op, PL_NSIZ);
        return;
    }
    /* role:string or character:string */
    fullname = "role";
    if (match_optname(opts, fullname, 4, TRUE) ||
        match_optname(opts, (fullname = "character"), 4, TRUE)) {
        if (negated) bad_negation(fullname, FALSE);
        else if ((op = string_for_env_opt(fullname, opts,
      FALSE)) != 0) {
            if ((flags.initrole = str2role(op)) ==
      ROLE_NONE)
                badoption(opts);
            else /* Backwards compatibility */
                nmcpy(pl_character, op, PL_NSIZ);
        }
        return;
    }
    /* race:string */
    fullname = "race";
    if (match_optname(opts, fullname, 4, TRUE)) {
        if (negated) bad_negation(fullname, FALSE);
        else if ((op = string_for_env_opt(fullname, opts,
      FALSE)) != 0) {
            if ((flags.initrace = str2race(op)) ==
      ROLE_NONE)
                badoption(opts);
            else /* Backwards compatibility */
                pl_race = *op;
        }
        return;
    }
    /* gender:string */
    fullname = "gender";
    if (match_optname(opts, fullname, 4, TRUE)) {
        if (negated) bad_negation(fullname, FALSE);
        else if ((op = string_for_env_opt(fullname, opts,
      FALSE)) != 0) {
            if ((flags.initgend = str2gend(op)) ==
      ROLE_NONE)
                badoption(opts);
            else
                flags.female = flags.initgend;
        }
        return;
    }
    /* altkeyhandler:string */
    fullname = "altkeyhandler";
    if (match_optname(opts, fullname, 4, TRUE)) {
        if (negated) bad_negation(fullname, FALSE);
        else if ((op = string_for_opt(opts, negated))) {
#ifdef WIN32CON
            (void)strncpy(iflags.altkeyhandler, op, MAX_ALTKEYHANDLER - 5);
            load_keyboard_handler();
#endif
        }
        return;
    }
    /* WINCAP
     * align_status:[left|top|right|bottom] */
    fullname = "align_status";
    if (match_optname(opts, fullname, sizeof("align_status")-1,
      TRUE)) {
        op = string_for_opt(opts, negated);
        if (op && !negated) {
            if (!strncmpi (op, "left", sizeof("left")-1))
            iflags.wc_align_status = ALIGN_LEFT;
            else if (!strncmpi (op, "top", sizeof("top")-1))
            iflags.wc_align_status = ALIGN_TOP;
            else if (!strncmpi (op, "right", sizeof("right")-1))
            iflags.wc_align_status = ALIGN_RIGHT;
            else if (!strncmpi (op, "bottom", sizeof("bottom")-1))
            iflags.wc_align_status = ALIGN_BOTTOM;
            else
            badoption(opts);
        } else if (negated) bad_negation(fullname, TRUE);
        return;
    }
    /* WINCAP
     * align_message:[left|top|right|bottom] */
    fullname = "align_message";
    if (match_optname(opts, fullname, sizeof("align_message")-1,
      TRUE)) {
        op = string_for_opt(opts, negated);
        if (op && !negated) {
            if (!strncmpi (op, "left", sizeof("left")-1))
            iflags.wc_align_message = ALIGN_LEFT;
            else if (!strncmpi (op, "top", sizeof("top")-1))
            iflags.wc_align_message = ALIGN_TOP;
            else if (!strncmpi (op, "right", sizeof("right")-1))
            iflags.wc_align_message = ALIGN_RIGHT;
            else if (!strncmpi (op, "bottom", sizeof("bottom")-1))
            iflags.wc_align_message = ALIGN_BOTTOM;
            else
            badoption(opts);
        } else if (negated) bad_negation(fullname, TRUE);
        return;
    }
    /* align:string */
    fullname = "align";
    if (match_optname(opts, fullname, sizeof("align")-1, TRUE)) {
        if (negated) bad_negation(fullname, FALSE);
        else if ((op = string_for_env_opt(fullname, opts,
      FALSE)) != 0)
            if ((flags.initalign = str2align(op)) ==
      ROLE_NONE)
                badoption(opts);
        return;
    }
    /* the order to list the pack */
    fullname = "packorder";
    if (match_optname(opts, fullname, 4, TRUE)) {
        if (negated) {
            bad_negation(fullname, FALSE);
            return;
        } else if (!(op = string_for_opt(opts, FALSE))) return;
        if (!change_inv_order(op))
            badoption(opts);
        return;
    }
    /* maximum burden picked up before prompt (Warren Cheung) */
    fullname = "pickup_burden";
    if (match_optname(opts, fullname, 8, TRUE)) {
        if (negated) {
            bad_negation(fullname, FALSE);
            return;
        } else if ((op = string_for_env_opt(fullname, opts,
      FALSE)) != 0) {
            switch (tolower(*op)) {
                /* Unencumbered */
                case 'u':
                    flags.pickup_burden = UNENCUMBERED;
                    break;
                /* Burdened (slight encumbrance) */
                case 'b':
                    flags.pickup_burden = SLT_ENCUMBER;
                    break;
                /* streSsed (moderate encumbrance) */
                case 's':
                    flags.pickup_burden = MOD_ENCUMBER;
                    break;
                /* straiNed (heavy encumbrance) */
                case 'n':
                    flags.pickup_burden = HVY_ENCUMBER;
                    break;
                /* OverTaxed (extreme encumbrance) */
                case 'o':
                case 't':
                    flags.pickup_burden = EXT_ENCUMBER;
                    break;
                /* overLoaded */
                case 'l':
                    flags.pickup_burden = OVERLOADED;
                    break;
                default:
                badoption(opts);
            }
        }
        return;
    }
    /* types of objects to pick up automatically */
    if (match_optname(opts, "pickup_types", 8, TRUE)) {
        char ocl[MAXOCLASSES + 1], tbuf[MAXOCLASSES + 1],
             qbuf[QBUFSZ], abuf[BUFSZ];
        int oc_sym;
        boolean badopt = FALSE, compat = (strlen(opts) <= 6), use_menu;
        oc_to_str(flags.pickup_types, tbuf);
        flags.pickup_types[0] = '\0'; /* all */
        op = string_for_opt(opts, (compat || !initial));
        if (!op) {
            if (compat || negated || initial) {
            /* for backwards compatibility, "pickup" without a
               value is a synonym for autopickup of all types
               (and during initialization, we can't prompt yet) */
            flags.pickup = !negated;
            return;
            }
            oc_to_str(flags.inv_order, ocl);
            use_menu = TRUE;
            if (flags.menu_style == MENU_TRADITIONAL ||
                flags.menu_style == MENU_COMBINATION) {
            use_menu = FALSE;
            Sprintf(qbuf, "New pickup_types: [%s am] (%s)",
                ocl, *tbuf ? tbuf : "all");
            getlin(qbuf, abuf);
            op = mungspaces(abuf);
            if (abuf[0] == '\0' || abuf[0] == '\033')
                op = tbuf; /* restore */
            else if (abuf[0] == 'm')
                use_menu = TRUE;
            }
            if (use_menu) {
            (void) choose_classes_menu("Auto-Pickup what?", 1,
                           TRUE, ocl, tbuf);
            op = tbuf;
            }
        }
        if (negated) {
            bad_negation("pickup_types", TRUE);
            return;
        }
        while (*op == ' ') op++;
        if (*op != 'a' && *op != 'A') {
            num = 0;
            while (*op) {
            oc_sym = def_char_to_objclass(*op);
            /* make sure all are valid obj symbols occuring once */
            if (oc_sym != MAXOCLASSES &&
                !index(flags.pickup_types, oc_sym)) {
                flags.pickup_types[num] = (char)oc_sym;
                flags.pickup_types[++num] = '\0';
            } else
                badopt = TRUE;
            op++;
            }
            if (badopt) badoption(opts);
        }
        return;
    }
    /* WINCAP
     * player_selection: dialog | prompts */
    fullname = "player_selection";
    if (match_optname(opts, fullname, sizeof("player_selection")-1,
      TRUE)) {
        op = string_for_opt(opts, negated);
        if (op && !negated) {
            if (!strncmpi (op, "dialog", sizeof("dialog")-1))
            iflags.wc_player_selection = VIA_DIALOG;
            else if (!strncmpi (op, "prompt", sizeof("prompt")-1))
            iflags.wc_player_selection = VIA_PROMPTS;
            else
                badoption(opts);
        } else if (negated) bad_negation(fullname, TRUE);
        return;
    }
    /* things to disclose at end of game */
    if (match_optname(opts, "disclose", 7, TRUE)) {
        /*
         * The order that the end_disclore options are stored:
         * inventory, attribs, vanquished, genocided, conduct
         * There is an array in flags:
         * end_disclose[NUM_DISCLOSURE_OPT];
         * with option settings for the each of the following:
         * iagvc [see disclosure_options in decl.c]:
         * Legal setting values in that array are:
         * DISCLOSE_PROMPT_DEFAULT_YES ask with default answer yes
         * DISCLOSE_PROMPT_DEFAULT_NO ask with default answer no
         * DISCLOSE_YES_WITHOUT_PROMPT always disclose and don't ask
         * DISCLOSE_NO_WITHOUT_PROMPT never disclose and don't ask
         *
         * Those setting values can be used in the option
         * string as a prefix to get the desired behaviour.
         *
         * For backward compatibility, no prefix is required,
         * and the presence of a i,a,g,v, or c without a prefix
         * sets the corresponding value to DISCLOSE_YES_WITHOUT_PROMPT.
         */
        boolean badopt = FALSE;
        int idx, prefix_val;
        op = string_for_opt(opts, TRUE);
        if (op && negated) {
            bad_negation("disclose", TRUE);
            return;
        }
        /* "disclose" without a value means "all with prompting"
           and negated means "none without prompting" */
        if (!op || !strcmpi(op, "all") || !strcmpi(op, "none")) {
            if (op && !strcmpi(op, "none")) negated = TRUE;
            for (num = 0; num < NUM_DISCLOSURE_OPTIONS; num++)
                flags.end_disclose[num] = negated ?
                        DISCLOSE_NO_WITHOUT_PROMPT :
                        DISCLOSE_PROMPT_DEFAULT_YES;
            return;
        }
        num = 0;
        prefix_val = -1;
        while (*op && num < sizeof flags.end_disclose - 1) {
            register char c, *dop;
            static char valid_settings[] = {
                DISCLOSE_PROMPT_DEFAULT_YES,
                DISCLOSE_PROMPT_DEFAULT_NO,
                DISCLOSE_YES_WITHOUT_PROMPT,
                DISCLOSE_NO_WITHOUT_PROMPT,
                '\0'
            };
            c = lowc(*op);
            if (c == 'k') c = 'v'; /* killed -> vanquished */
            dop = index(disclosure_options, c);
            if (dop) {
                idx = dop - disclosure_options;
                if (idx < 0 || idx > NUM_DISCLOSURE_OPTIONS - 1) {
                    impossible("bad disclosure index %d %c",
                            idx, c);
                    continue;
                }
                if (prefix_val != -1) {
                    flags.end_disclose[idx] = prefix_val;
                    prefix_val = -1;
                } else
                    flags.end_disclose[idx] =
      DISCLOSE_YES_WITHOUT_PROMPT;
            } else if (index(valid_settings, c)) {
                prefix_val = c;
            } else if (c == ' ') {
                /* do nothing */
            } else
                badopt = TRUE;
            op++;
        }
        if (badopt) badoption(opts);
        return;
    }
    /* scores:5t[op] 5a[round] o[wn] */
    if (match_optname(opts, "scores", 4, TRUE)) {
        if (negated) {
        bad_negation("scores", FALSE);
        return;
        }
        if (!(op = string_for_opt(opts, FALSE))) return;
        while (*op) {
        int inum = 1;
        if (digit(*op)) {
            inum = atoi(op);
            while (digit(*op)) op++;
        } else if (*op == '!') {
            negated = !negated;
            op++;
        }
        while (*op == ' ') op++;
        switch (*op) {
         case 't':
         case 'T': flags.end_top = inum;
                break;
         case 'a':
         case 'A': flags.end_around = inum;
                break;
         case 'o':
         case 'O': flags.end_own = !negated;
                break;
         default: badoption(opts);
                return;
        }
        while (letter(*++op) || *op == ' ') continue;
        if (*op == '/') op++;
        }
        return;
    }
    fullname = "suppress_alert";
    if (match_optname(opts, fullname, 4, TRUE)) {
        op = string_for_opt(opts, negated);
        if (negated) bad_negation(fullname, FALSE);
        else if (op) (void) feature_alert_opts(op,fullname);
        return;
    }
    
#ifdef VIDEOSHADES
    /* videocolors:string */
    fullname = "videocolors";
    if (match_optname(opts, fullname, 6, TRUE) ||
        match_optname(opts, "videocolours", 10, TRUE)) {
        if (negated) {
            bad_negation(fullname, FALSE);
            return;
        }
        else if (!(opts = string_for_env_opt(fullname, opts,
      FALSE))) {
            return;
        }
        if (!assign_videocolors(opts))
            badoption(opts);
        return;
    }
    /* videoshades:string */
    fullname = "videoshades";
    if (match_optname(opts, fullname, 6, TRUE)) {
        if (negated) {
            bad_negation(fullname, FALSE);
            return;
        }
        else if (!(opts = string_for_env_opt(fullname, opts,
      FALSE))) {
            return;
        }
        if (!assign_videoshades(opts))
            badoption(opts);
        return;
    }
#endif /* VIDEOSHADES */
#ifdef MSDOS
# ifdef NO_TERMS
    /* video:string -- must be after longer tests */
    fullname = "video";
    if (match_optname(opts, fullname, 5, TRUE)) {
        if (negated) {
            bad_negation(fullname, FALSE);
            return;
        }
        else if (!(opts = string_for_env_opt(fullname, opts,
      FALSE))) {
            return;
        }
        if (!assign_video(opts))
            badoption(opts);
        return;
    }
# endif /* NO_TERMS */
    /* soundcard:string -- careful not to match boolean 'sound' */
    fullname = "soundcard";
    if (match_optname(opts, fullname, 6, TRUE)) {
        if (negated) {
            bad_negation(fullname, FALSE);
            return;
        }
        else if (!(opts = string_for_env_opt(fullname, opts,
      FALSE))) {
            return;
        }
        if (!assign_soundcard(opts))
            badoption(opts);
        return;
    }
#endif /* MSDOS */
    /* WINCAP
     * map_mode:[tiles|ascii4x6|ascii6x8|ascii8x8|ascii16x8|ascii7x12|ascii8x12|
            ascii16x12|ascii12x16|ascii10x18|fit_to_screen] */
    fullname = "map_mode";
    if (match_optname(opts, fullname, sizeof("map_mode")-1, TRUE)) {
        op = string_for_opt(opts, negated);
        if (op && !negated) {
            if (!strncmpi (op, "tiles", sizeof("tiles")-1))
            iflags.wc_map_mode = MAP_MODE_TILES;
            else if (!strncmpi (op, "ascii4x6", sizeof("ascii4x6")-1))
            iflags.wc_map_mode = MAP_MODE_ASCII4x6;
            else if (!strncmpi (op, "ascii6x8", sizeof("ascii6x8")-1))
            iflags.wc_map_mode = MAP_MODE_ASCII6x8;
            else if (!strncmpi (op, "ascii8x8", sizeof("ascii8x8")-1))
            iflags.wc_map_mode = MAP_MODE_ASCII8x8;
            else if (!strncmpi (op, "ascii16x8", sizeof("ascii16x8")-1))
            iflags.wc_map_mode = MAP_MODE_ASCII16x8;
            else if (!strncmpi (op, "ascii7x12", sizeof("ascii7x12")-1))
            iflags.wc_map_mode = MAP_MODE_ASCII7x12;
            else if (!strncmpi (op, "ascii8x12", sizeof("ascii8x12")-1))
            iflags.wc_map_mode = MAP_MODE_ASCII8x12;
            else if (!strncmpi (op, "ascii16x12", sizeof("ascii16x12")-1))
            iflags.wc_map_mode = MAP_MODE_ASCII16x12;
            else if (!strncmpi (op, "ascii12x16", sizeof("ascii12x16")-1))
            iflags.wc_map_mode = MAP_MODE_ASCII12x16;
            else if (!strncmpi (op, "ascii10x18", sizeof("ascii10x18")-1))
            iflags.wc_map_mode = MAP_MODE_ASCII10x18;
            else if (!strncmpi (op, "fit_to_screen", sizeof("fit_to_screen")-1))
            iflags.wc_map_mode = MAP_MODE_ASCII_FIT_TO_SCREEN;
            else
                badoption(opts);
        } else if (negated) bad_negation(fullname, TRUE);
        return;
    }
    /* WINCAP
     * scroll_amount:nn */
    fullname = "scroll_amount";
    if (match_optname(opts, fullname, sizeof("scroll_amount")-1,
      TRUE)) {
        op = string_for_opt(opts, negated);
        if ((negated && !op) || (!negated && op)) {
            iflags.wc_scroll_amount = negated ? 1 : atoi(op);
        } else if (negated) bad_negation(fullname, TRUE);
        return;
    }
    /* WINCAP
     * scroll_margin:nn */
    fullname = "scroll_margin";
    if (match_optname(opts, fullname, sizeof("scroll_margin")-1,
      TRUE)) {
        op = string_for_opt(opts, negated);
        if ((negated && !op) || (!negated && op)) {
            iflags.wc_scroll_margin = negated ? 5 : atoi(op);
        } else if (negated) bad_negation(fullname, TRUE);
        return;
    }
    fullname = "subkeyvalue";
    if (match_optname(opts, fullname, 5, TRUE)) {
        if (negated) bad_negation(fullname, FALSE);
        else {
#if defined(WIN32CON)
            op = string_for_opt(opts, 0);
            map_subkeyvalue(op);
#endif
        }
        return;
    }
    /* WINCAP
     * tile_width:nn */
    fullname = "tile_width";
    if (match_optname(opts, fullname, sizeof("tile_width")-1, TRUE)) {
        op = string_for_opt(opts, negated);
        if ((negated && !op) || (!negated && op)) {
            iflags.wc_tile_width = negated ? 0 : atoi(op);
        } else if (negated) bad_negation(fullname, TRUE);
        return;
    }
    /* WINCAP
     * tile_file:name */
    fullname = "tile_file";
    if (match_optname(opts, fullname, sizeof("tile_file")-1, TRUE)) {
        if ((op = string_for_opt(opts, FALSE)) != 0) {
            if (iflags.wc_tile_file) free(iflags.
      wc_tile_file);
            iflags.wc_tile_file = (char *)alloc(strlen(op) + 1);
            Strcpy(iflags.wc_tile_file, op);
        }
        return;
    }
    /* WINCAP
     * tile_height:nn */
    fullname = "tile_height";
    if (match_optname(opts, fullname, sizeof("tile_height")-1, TRUE)) {
        op = string_for_opt(opts, negated);
        if ((negated && !op) || (!negated && op)) {
            iflags.wc_tile_height = negated ? 0 : atoi(op);
        } else if (negated) bad_negation(fullname, TRUE);
        return;
    }
    /* WINCAP
     * vary_msgcount:nn */
    fullname = "vary_msgcount";
    if (match_optname(opts, fullname, sizeof("vary_msgcount")-1,
      TRUE)) {
        op = string_for_opt(opts, negated);
        if ((negated && !op) || (!negated && op)) {
            iflags.wc_vary_msgcount = negated ? 0 : atoi(op);
        } else if (negated) bad_negation(fullname, TRUE);
        return;
    }
    fullname = "windowtype";
    if (match_optname(opts, fullname, 3, TRUE)) {
        if (negated) {
        bad_negation(fullname, FALSE);
        return;
        } else if ((op = string_for_env_opt(fullname, opts,
      FALSE)) != 0) {
        char buf[WINTYPELEN];
        nmcpy(buf, op, WINTYPELEN);
        choose_windows(buf);
        }
        return;
    }
    /* WINCAP
     * setting window colors
         * syntax: windowcolors=menu foregrnd/backgrnd text foregrnd/backgrnd
         */
    fullname = "windowcolors";
    if (match_optname(opts, fullname, 7, TRUE)) {
        if ((op = string_for_opt(opts, FALSE)) != 0) {
            if (!wc_set_window_colors(op))
                badoption(opts);
        } else if (negated) bad_negation(fullname, TRUE);
        return;
    }
    /* menustyle:traditional or combo or full or partial */
    if (match_optname(opts, "menustyle", 4, TRUE)) {
        int tmp;
        boolean val_required = (strlen(opts) > 5 && !negated);
        if (!(op = string_for_opt(opts, !val_required))) {
            if (val_required) return; /* string_for_opt gave feedback */
            tmp = negated ? 'n' : 'f';
        } else {
            tmp = tolower(*op);
        }
        switch (tmp) {
            case 'n': /* none */
            case 't': /* traditional */
                flags.menu_style = MENU_TRADITIONAL;
                break;
            case 'c': /* combo: trad.class sel+menu */
                flags.menu_style = MENU_COMBINATION;
                break;
            case 'p': /* partial: no class menu */
                flags.menu_style = MENU_PARTIAL;
                break;
            case 'f': /* full: class menu + menu */
                flags.menu_style = MENU_FULL;
                break;
            default:
                badoption(opts);
        }
        return;
    }
    fullname = "menu_headings";
    if (match_optname(opts, fullname, 12, TRUE)) {
        if (negated) {
            bad_negation(fullname, FALSE);
            return;
        }
        else if (!(opts = string_for_env_opt(fullname, opts,
      FALSE))) {
            return;
        }
        if (!strcmpi(opts,"bold"))
            iflags.menu_headings = ATR_BOLD;
        else if (!strcmpi(opts,"inverse"))
            iflags.menu_headings = ATR_INVERSE;
        else if (!strcmpi(opts,"underline"))
            iflags.menu_headings = ATR_ULINE;
        else
            badoption(opts);
        return;
    }
    /* check for menu command mapping */
    for (i = 0; i < NUM_MENU_CMDS; i++) {
        fullname = default_menu_cmd_info[i].name;
        if (match_optname(opts, fullname, (int)strlen(fullname),
      TRUE)) {
        if (negated)
            bad_negation(fullname, FALSE);
        else if ((op = string_for_opt(opts, FALSE)) != 0) {
            int j;
            char c, op_buf[BUFSZ];
            boolean isbad = FALSE;
            escapes(op, op_buf);
            c = *op_buf;
            if (c == 0 || c == '\r' || c == '\n' || c == '\033' ||
                c == ' ' || digit(c) || (letter(c) && c != '@'))
            isbad = TRUE;
            else /* reject default object class symbols */
            for (j = 1; j < MAXOCLASSES; j++)
                if (c == def_oc_syms[i]) {
                isbad = TRUE;
                break;
                }
            if (isbad)
            badoption(opts);
            else
            add_menu_cmd_alias(c, default_menu_cmd_info[i].cmd);
        }
        return;
        }
    }
    /* OK, if we still haven't recognized the option, check the boolean
     * options list
     */
    for (i = 0; boolopt[i].name; i++) {
        if (match_optname(opts, boolopt[i].name, 3,
      FALSE)) {
            /* options that don't exist */
            if (!boolopt[i].addr) {
                if (!initial && !negated)
                pline_The("\"%s\" option is not available.",
                    boolopt[i].name);
                return;
            }
            /* options that must come from config file */
            if (!initial && (boolopt[i].optflags == SET_IN_FILE)) {
                rejectoption(boolopt[i].name);
                return;
            }
            *(boolopt[i].addr) = !negated;
            duplicate_opt_detection(boolopt[i].name, 0);
#if defined(TERMLIB) || defined(ASCIIGRAPH) || defined(MAC_GRAPHICS_ENV)
            if (FALSE
# ifdef TERMLIB
                 || (boolopt[i].addr) == &iflags.DECgraphics
# endif
# ifdef ASCIIGRAPH
                 || (boolopt[i].addr) == &iflags.IBMgraphics
# endif
# ifdef MAC_GRAPHICS_ENV
                 || (boolopt[i].addr) == &iflags.MACgraphics
# endif
                ) {
# ifdef REINCARNATION
                if (!initial && Is_rogue_level(&u.uz))
                assign_rogue_graphics(FALSE);
# endif
                need_redraw = TRUE;
# ifdef TERMLIB
                if ((boolopt[i].addr) == &iflags.DECgraphics)
                switch_graphics(iflags.DECgraphics ?
                        DEC_GRAPHICS : ASCII_GRAPHICS);
# endif
# ifdef ASCIIGRAPH
                if ((boolopt[i].addr) == &iflags.IBMgraphics)
                switch_graphics(iflags.IBMgraphics ?
                        IBM_GRAPHICS : ASCII_GRAPHICS);
# endif
# ifdef MAC_GRAPHICS_ENV
                if ((boolopt[i].addr) == &iflags.MACgraphics)
                switch_graphics(iflags.MACgraphics ?
                        MAC_GRAPHICS : ASCII_GRAPHICS);
# endif
# ifdef REINCARNATION
                if (!initial && Is_rogue_level(&u.uz))
                assign_rogue_graphics(TRUE);
# endif
            }
#endif /* TERMLIB || ASCIIGRAPH || MAC_GRAPHICS_ENV */
            /* only do processing below if setting with doset() */
            if (initial) return;
            if ((boolopt[i].addr) == &flags.time
#ifdef EXP_ON_BOTL
             || (boolopt[i].addr) == &flags.showexp
#endif
#ifdef SCORE_ON_BOTL
             || (boolopt[i].addr) == &flags.showscore
#endif
                )
                flags.botl = TRUE;
            else if ((boolopt[i].addr) == &flags.invlet_constant) {
                if (flags.invlet_constant) reassign();
            }
#ifdef LAN_MAIL
            else if ((boolopt[i].addr) == &flags.biff) {
                if (flags.biff) lan_mail_init();
                else lan_mail_finish();
            }
#endif
            else if ((boolopt[i].addr) == &flags.lit_corridor) {
                /*
                 * All corridor squares seen via night vision or
                 * candles & lamps change. Update them by calling
                 * newsym() on them. Don't do this if we are
                 * initializing the options --- the vision system
                 * isn't set up yet.
                 */
                vision_recalc(2); /* shut down vision */
                vision_full_recalc = 1; /* delayed recalc */
            }
            else if ((boolopt[i].addr) == &iflags.use_inverse ||
                    (boolopt[i].addr) == &iflags.showrace ||
                    (boolopt[i].addr) == &iflags.hilite_pet) {
                need_redraw = TRUE;
            }
#ifdef TEXTCOLOR
            else if ((boolopt[i].addr) == &iflags.use_color) {
                need_redraw = TRUE;
# ifdef TOS
                if ((boolopt[i].addr) == &iflags.use_color
                && iflags.BIOS) {
                if (colors_changed)
                    restore_colors();
                else
                    set_colors();
                }
# endif
            }
#endif
            return;
        }
    }
    /* out of valid options */
    badoption(opts);
}
STATIC_OVL void rejectoption (char * optname) const
Definition at line 688 of file options.c.
References configfile.
Referenced by parseoptions(), and string_for_env_opt().
{
#ifdef MICRO
    pline("\"%s\" settable only from %s.", optname, configfile);
#else
    pline("%s can be set only from NETHACKOPTIONS or %s.", optname,
            configfile);
#endif
}
void set_duplicate_opt_detection (int on_or_off)
Definition at line 895 of file options.c.
References alloc(), boolopt, compopt, free(), iflags, instance_flags::opt_booldup, instance_flags::opt_compdup, and SIZE.
Referenced by read_config_file().
{
    int k, *optptr;
    if (on_or_off != 0) {
        /*-- ON --*/
        if (iflags.opt_booldup)
            impossible("iflags.opt_booldup already on (memory leak)");
        iflags.opt_booldup = (int *)alloc(SIZE(boolopt) * sizeof(int));
        optptr = iflags.opt_booldup;
        for (k = 0; k < SIZE(boolopt); ++k)
            *optptr++ = 0;
            
        if (iflags.opt_compdup)
            impossible("iflags.opt_compdup already on (memory leak)");
        iflags.opt_compdup = (int *)alloc(SIZE(compopt) * sizeof(int));
        optptr = iflags.opt_compdup;
        for (k = 0; k < SIZE(compopt); ++k)
            *optptr++ = 0;
    } else {
        /*-- OFF --*/
        if (iflags.opt_booldup) free((genericptr_t)
      iflags.opt_booldup);
        iflags.opt_booldup = (int *)0;
        if (iflags.opt_compdup) free((genericptr_t)
      iflags.opt_compdup);
        iflags.opt_compdup = (int *)0;
    }
}
void set_option_mod_status (char * optnam, int status) const
Definition at line 3608 of file options.c.
References boolopt, compopt, Bool_Opt::name, name, Comp_Opt::name, Bool_Opt::optflags, Comp_Opt::optflags, SET_IN_GAME, and strncmpi().
Referenced by gnome_init_nhwindows(), mswin_init_nhwindows(), set_wc2_option_mod_status(), and set_wc_option_mod_status().
{
    int k;
    if (status < SET_IN_FILE || status > SET_IN_GAME) {
        impossible("set_option_mod_status: status out of range %d.",
               status);
        return;
    }
    for (k = 0; boolopt[k].name; k++) {
        if (!strncmpi(boolopt[k].name, optnam, strlen(optnam))) {
            boolopt[k].optflags = status;
            return;
        }
    }
    for (k = 0; compopt[k].name; k++) {
        if (!strncmpi(compopt[k].name, optnam, strlen(optnam))) {
            compopt[k].optflags = status;
            return;
        }
    }
}
void set_wc2_option_mod_status (unsigned long optmask, int status)
Definition at line 3697 of file options.c.
References SET_IN_GAME, set_option_mod_status(), wc_Opt::wc_bit, and wc_Opt::wc_name.
Referenced by mswin_init_nhwindows().
{
    int k = 0;
    if (status < SET_IN_FILE || status > SET_IN_GAME) {
        impossible("set_wc2_option_mod_status: status out of range %d.",
               status);
        return;
    }
    while (wc2_options[k].wc_name) {
        if (optmask & wc2_options[k].wc_bit) {
            set_option_mod_status(wc2_options[k].wc_name, status);
        }
        k++;
    }
}
void set_wc_option_mod_status (unsigned long optmask, int status)
Definition at line 3641 of file options.c.
References SET_IN_GAME, set_option_mod_status(), wc_Opt::wc_bit, and wc_Opt::wc_name.
Referenced by mswin_init_nhwindows().
{
    int k = 0;
    if (status < SET_IN_FILE || status > SET_IN_GAME) {
        impossible("set_wc_option_mod_status: status out of range %d.",
               status);
        return;
    }
    while (wc_options[k].wc_name) {
        if (optmask & wc_options[k].wc_bit) {
            set_option_mod_status(wc_options[k].wc_name, status);
        }
        k++;
    }
}
STATIC_OVL boolean special_handling (char * optname, boolean setinitial, boolean setfromfile) const
Definition at line 2532 of file options.c.
References any::a_char, any::a_int, any::a_void, add_menu, ALIGN_BOTTOM, ALIGN_LEFT, ALIGN_RIGHT, ALIGN_TOP, ATR_BOLD, ATR_INVERSE, ATR_NONE, ATR_ULINE, buf, BUFSZ, create_nhwindow, destroy_nhwindow, DISCLOSE_NO_WITHOUT_PROMPT, DISCLOSE_PROMPT_DEFAULT_NO, DISCLOSE_PROMPT_DEFAULT_YES, DISCLOSE_YES_WITHOUT_PROMPT, disclosure_options, flag::end_disclose, end_menu, FALSE, flags, free(), getlin, iflags, mi::item, instance_flags::menu_headings, flag::menu_style, MENU_UNSELECTED, NHW_MENU, NO_GLYPH, NUM_DISCLOSURE_OPTIONS, instance_flags::num_pad, instance_flags::num_pad_mode, parseoptions(), PICK_ANY, PICK_NONE, PICK_ONE, flag::pickup_burden, instance_flags::runmode, select_menu, SIZE, Sprintf, start_menu, Strcat, TRUE, instance_flags::wc_align_message, and instance_flags::wc_align_status.
Referenced by doset().
{
    winid tmpwin;
    anything any;
    int i;
    char buf[BUFSZ];
    boolean retval = FALSE;
    
    /* Special handling of menustyle, pickup_burden, pickup_types,
     * disclose, runmode, msg_window, menu_headings, and number_pad options.
#ifdef AUTOPICKUP_EXCEPTIONS
     * Also takes care of interactive autopickup_exception_handling changes.
#endif
     */
    if (!strcmp("menustyle", optname)) {
    const char *style_name;
    menu_item *style_pick = (menu_item *)0;
        tmpwin = create_nhwindow(NHW_MENU);
    start_menu(tmpwin);
    for (i = 0; i < SIZE(menutype); i++) {
        style_name = menutype[i];
            /* note: separate `style_name' variable used
           to avoid an optimizer bug in VAX C V2.3 */
        any.a_int = i + 1;
        add_menu(tmpwin, NO_GLYPH, &any, *style_name, 0,
             ATR_NONE, style_name, MENU_UNSELECTED);
        }
    end_menu(tmpwin, "Select menustyle:");
    if (select_menu(tmpwin, PICK_ONE, &style_pick) > 0) {
        flags.menu_style = style_pick->item.a_int - 1;
        free((genericptr_t)style_pick);
        }
    destroy_nhwindow(tmpwin);
        retval = TRUE;
    } else if (!strcmp("pickup_burden", optname)) {
    const char *burden_name, *burden_letters = "ubsntl";
    menu_item *burden_pick = (menu_item *)0;
        tmpwin = create_nhwindow(NHW_MENU);
    start_menu(tmpwin);
    for (i = 0; i < SIZE(burdentype); i++) {
        burden_name = burdentype[i];
        any.a_int = i + 1;
        add_menu(tmpwin, NO_GLYPH, &any, burden_letters[i], 0,
             ATR_NONE, burden_name, MENU_UNSELECTED);
        }
    end_menu(tmpwin, "Select encumbrance level:");
    if (select_menu(tmpwin, PICK_ONE, &burden_pick) > 0) {
        flags.pickup_burden = burden_pick->item.a_int - 1;
        free((genericptr_t)burden_pick);
    }
    destroy_nhwindow(tmpwin);
    retval = TRUE;
    } else if (!strcmp("pickup_types", optname)) {
    /* parseoptions will prompt for the list of types */
    parseoptions(strcpy(buf, "pickup_types"), setinitial, setfromfile);
    retval = TRUE;
    } else if (!strcmp("disclose", optname)) {
    int pick_cnt, pick_idx, opt_idx;
    menu_item *disclosure_category_pick = (menu_item *)0;
    /*
     * The order of disclose_names[]
         * must correspond to disclosure_options in decl.h
         */
    static const char *disclosure_names[] = {
        "inventory", "attributes", "vanquished", "genocides", "conduct"
    };
    int disc_cat[NUM_DISCLOSURE_OPTIONS];
    const char *disclosure_name;
        tmpwin = create_nhwindow(NHW_MENU);
    start_menu(tmpwin);
    for (i = 0; i < NUM_DISCLOSURE_OPTIONS; i++) {
        disclosure_name = disclosure_names[i];
        any.a_int = i + 1;
        add_menu(tmpwin, NO_GLYPH, &any, disclosure_options[i], 0,
             ATR_NONE, disclosure_name, MENU_UNSELECTED);
        disc_cat[i] = 0;
        }
    end_menu(tmpwin, "Change which disclosure options categories:");
    if ((pick_cnt = select_menu(tmpwin, PICK_ANY, &disclosure_category_pick)) > 0) {
        for (pick_idx = 0; pick_idx < pick_cnt; ++pick_idx) {
        opt_idx = disclosure_category_pick[pick_idx].item.a_int - 1;
        disc_cat[opt_idx] = 1;
        }
        free((genericptr_t)disclosure_category_pick);
        disclosure_category_pick = (menu_item *)0;
    }
    destroy_nhwindow(tmpwin);
    for (i = 0; i < NUM_DISCLOSURE_OPTIONS; i++) {
        if (disc_cat[i]) {
            char dbuf[BUFSZ];
        menu_item *disclosure_option_pick = (menu_item *)0;
        Sprintf(dbuf, "Disclosure options for %s:", disclosure_names[i]);
            tmpwin = create_nhwindow(NHW_MENU);
        start_menu(tmpwin);
        any.a_char = DISCLOSE_NO_WITHOUT_PROMPT;
        add_menu(tmpwin, NO_GLYPH, &any, 'a', 0,
            ATR_NONE,"Never disclose and don't prompt", MENU_UNSELECTED);
        any.a_void = 0;
        any.a_char = DISCLOSE_YES_WITHOUT_PROMPT;
        add_menu(tmpwin, NO_GLYPH, &any, 'b', 0,
            ATR_NONE,"Always disclose and don't prompt", MENU_UNSELECTED);
        any.a_void = 0;
        any.a_char = DISCLOSE_PROMPT_DEFAULT_NO;
        add_menu(tmpwin, NO_GLYPH, &any, 'c', 0,
            ATR_NONE,"Prompt and default answer to \"No\"",
      MENU_UNSELECTED);
        any.a_void = 0;
        any.a_char = DISCLOSE_PROMPT_DEFAULT_YES;
        add_menu(tmpwin, NO_GLYPH, &any, 'd', 0,
            ATR_NONE,"Prompt and default answer to \"Yes\"",
      MENU_UNSELECTED);
        end_menu(tmpwin, dbuf);
        if (select_menu(tmpwin, PICK_ONE, &disclosure_option_pick) > 0) {
            flags.end_disclose[i] = disclosure_option_pick->
      item.a_char;
            free((genericptr_t)disclosure_option_pick);
        }
        destroy_nhwindow(tmpwin);
        }
    }
    retval = TRUE;
    } else if (!strcmp("runmode", optname)) {
    const char *mode_name;
    menu_item *mode_pick = (menu_item *)0;
    tmpwin = create_nhwindow(NHW_MENU);
    start_menu(tmpwin);
    for (i = 0; i < SIZE(runmodes); i++) {
        mode_name = runmodes[i];
        any.a_int = i + 1;
        add_menu(tmpwin, NO_GLYPH, &any, *mode_name, 0,
             ATR_NONE, mode_name, MENU_UNSELECTED);
    }
    end_menu(tmpwin, "Select run/travel display mode:");
    if (select_menu(tmpwin, PICK_ONE, &mode_pick) > 0) {
        iflags.runmode = mode_pick->item.a_int - 1;
        free((genericptr_t)mode_pick);
    }
    destroy_nhwindow(tmpwin);
    retval = TRUE;
    }
#ifdef TTY_GRAPHICS
      else if (!strcmp("msg_window", optname)) {
    /* by Christian W. Cooper */
    menu_item *window_pick = (menu_item *)0;
    tmpwin = create_nhwindow(NHW_MENU);
    start_menu(tmpwin);
    any.a_char = 's';
    add_menu(tmpwin, NO_GLYPH, &any, 's', 0,
        ATR_NONE, "single", MENU_UNSELECTED);
    any.a_char = 'c';
    add_menu(tmpwin, NO_GLYPH, &any, 'c', 0,
        ATR_NONE, "combination", MENU_UNSELECTED);
    any.a_char = 'f';
    add_menu(tmpwin, NO_GLYPH, &any, 'f', 0,
        ATR_NONE, "full", MENU_UNSELECTED);
    any.a_char = 'r';
    add_menu(tmpwin, NO_GLYPH, &any, 'r', 0,
        ATR_NONE, "reversed", MENU_UNSELECTED);
    end_menu(tmpwin, "Select message history display type:");
    if (select_menu(tmpwin, PICK_ONE, &window_pick) > 0) {
        iflags.prevmsg_window = window_pick->item.a_char;
        free((genericptr_t)window_pick);
    }
    destroy_nhwindow(tmpwin);
        retval = TRUE;
    }
#endif
     else if (!strcmp("align_message", optname) ||
        !strcmp("align_status", optname)) {
    menu_item *window_pick = (menu_item *)0;
    char abuf[BUFSZ];
    boolean msg = (*(optname+6) == 'm');
    tmpwin = create_nhwindow(NHW_MENU);
    start_menu(tmpwin);
    any.a_int = ALIGN_TOP;
    add_menu(tmpwin, NO_GLYPH, &any, 't', 0,
        ATR_NONE, "top", MENU_UNSELECTED);
    any.a_int = ALIGN_BOTTOM;
    add_menu(tmpwin, NO_GLYPH, &any, 'b', 0,
        ATR_NONE, "bottom", MENU_UNSELECTED);
    any.a_int = ALIGN_LEFT;
    add_menu(tmpwin, NO_GLYPH, &any, 'l', 0,
        ATR_NONE, "left", MENU_UNSELECTED);
    any.a_int = ALIGN_RIGHT;
    add_menu(tmpwin, NO_GLYPH, &any, 'r', 0,
        ATR_NONE, "right", MENU_UNSELECTED);
    Sprintf(abuf, "Select %s window placement relative to the map:",
        msg ? "message" : "status");
    end_menu(tmpwin, abuf);
    if (select_menu(tmpwin, PICK_ONE, &window_pick) > 0) {
        if (msg) iflags.wc_align_message = window_pick->
      item.a_int;
        else iflags.wc_align_status = window_pick->item.
      a_int;
        free((genericptr_t)window_pick);
    }
    destroy_nhwindow(tmpwin);
        retval = TRUE;
    } else if (!strcmp("number_pad", optname)) {
    static const char *npchoices[3] =
        {"0 (off)", "1 (on)", "2 (on, DOS compatible)"};
    const char *npletters = "abc";
    menu_item *mode_pick = (menu_item *)0;
    tmpwin = create_nhwindow(NHW_MENU);
    start_menu(tmpwin);
    for (i = 0; i < SIZE(npchoices); i++) {
        any.a_int = i + 1;
        add_menu(tmpwin, NO_GLYPH, &any, npletters[i], 0,
             ATR_NONE, npchoices[i], MENU_UNSELECTED);
        }
    end_menu(tmpwin, "Select number_pad mode:");
    if (select_menu(tmpwin, PICK_ONE, &mode_pick) > 0) {
        int mode = mode_pick->item.a_int - 1;
        switch(mode) {
            case 2:
                iflags.num_pad = 1;
                iflags.num_pad_mode = 1;
                break;
            case 1:
                iflags.num_pad = 1;
                iflags.num_pad_mode = 0;
                break;
            case 0:
            default:
                iflags.num_pad = 0;
                iflags.num_pad_mode = 0;
        }
        free((genericptr_t)mode_pick);
        }
    destroy_nhwindow(tmpwin);
        retval = TRUE;
    } else if (!strcmp("menu_headings", optname)) {
    static const char *mhchoices[3] = {"bold", "inverse", "underline"};
    const char *npletters = "biu";
    menu_item *mode_pick = (menu_item *)0;
    tmpwin = create_nhwindow(NHW_MENU);
    start_menu(tmpwin);
    for (i = 0; i < SIZE(mhchoices); i++) {
        any.a_int = i + 1;
        add_menu(tmpwin, NO_GLYPH, &any, npletters[i], 0,
             ATR_NONE, mhchoices[i], MENU_UNSELECTED);
        }
    end_menu(tmpwin, "How to highlight menu headings:");
    if (select_menu(tmpwin, PICK_ONE, &mode_pick) > 0) {
        int mode = mode_pick->item.a_int - 1;
        switch(mode) {
            case 2:
                iflags.menu_headings = ATR_ULINE;
                break;
            case 0:
                iflags.menu_headings = ATR_BOLD;
                break;
            case 1:
            default:
                iflags.menu_headings = ATR_INVERSE;
        }
        free((genericptr_t)mode_pick);
        }
    destroy_nhwindow(tmpwin);
        retval = TRUE;
#ifdef AUTOPICKUP_EXCEPTIONS
    } else if (!strcmp("autopickup_exception", optname)) {
        boolean retval;
    int pick_cnt, pick_idx, opt_idx, pass;
    int totalapes = 0, numapes[2] = {0,0};
    menu_item *pick_list = (menu_item *)0;
    anything any;
    char apebuf[BUFSZ];
    struct autopickup_exception *ape;
    static const char *action_titles[] = {
        "a", "add new autopickup exception",
        "l", "list autopickup exceptions",
        "r", "remove existing autopickup exception",
        "e", "exit this menu",
    };
ape_again:
    opt_idx = 0;
    totalapes = count_ape_maps(&numapes[AP_LEAVE], &numapes[AP_GRAB]);
    tmpwin = create_nhwindow(NHW_MENU);
    start_menu(tmpwin);
    any.a_int = 0;
    for (i = 0; i < SIZE(action_titles) ; i += 2) {
        any.a_int++;
        if (!totalapes && (i >= 2 && i < 6)) continue;
        add_menu(tmpwin, NO_GLYPH, &any, *action_titles[i],
              0, ATR_NONE, action_titles[i+1], MENU_UNSELECTED);
        }
    end_menu(tmpwin, "Do what?");
    if ((pick_cnt = select_menu(tmpwin, PICK_ONE, &pick_list)) > 0) {
        for (pick_idx = 0; pick_idx < pick_cnt; ++pick_idx) {
            opt_idx = pick_list[pick_idx].item.a_int - 1;
        }
        free((genericptr_t)pick_list);
        pick_list = (menu_item *)0;
    }
    destroy_nhwindow(tmpwin);
    if (pick_cnt < 1) return FALSE;
    if (opt_idx == 0) { /* add new */
        getlin("What new autopickup exception pattern?", &apebuf[1]);
        if (apebuf[1] == '\033') return FALSE;
        apebuf[0] = '"';
        Strcat(apebuf,"\"");
        add_autopickup_exception(apebuf);
        goto ape_again;
    } else if (opt_idx == 3) {
        retval = TRUE;
    } else { /* remove */
        tmpwin = create_nhwindow(NHW_MENU);
        start_menu(tmpwin);
        for (pass = AP_LEAVE; pass <= AP_GRAB; ++pass) {
            if (numapes[pass] == 0) continue;
            ape = iflags.autopickup_exceptions[pass];
            any.a_void = 0;
            add_menu(tmpwin, NO_GLYPH, &any, 0, 0, iflags.
      menu_headings,
                (pass == 0) ? "Never pickup" : "Always pickup",
                MENU_UNSELECTED);
            for (i = 0; i < numapes[pass] && ape; i++) {
            any.a_void = (opt_idx == 1) ? 0 : ape;
            Sprintf(apebuf, "\"%s\"", ape->pattern);
            add_menu(tmpwin, NO_GLYPH, &any,
                0, 0, ATR_NONE, apebuf, MENU_UNSELECTED);
            ape = ape->next;
            }
        }
        Sprintf(apebuf, "%s autopickup exceptions",
            (opt_idx == 1) ? "List of" : "Remove which");
        end_menu(tmpwin, apebuf);
        pick_cnt = select_menu(tmpwin,
                    (opt_idx == 1) ? PICK_NONE : PICK_ANY,
                    &pick_list);
        if (pick_cnt > 0) {
                for (pick_idx = 0; pick_idx < pick_cnt; ++pick_idx)
            remove_autopickup_exception(
             (struct autopickup_exception *)pick_list[pick_idx].item.a_void);
            }
            free((genericptr_t)pick_list);
            pick_list = (menu_item *)0;
        destroy_nhwindow(tmpwin);
        goto ape_again;
    }
    retval = TRUE;
#endif /* AUTOPICKUP_EXCEPTIONS */
    }
    return retval;
}
STATIC_OVL char* string_for_env_opt (char * optname, char * opts, boolean val_optional) const
Definition at line 741 of file options.c.
References rejectoption(), and string_for_opt().
Referenced by graphics_opts(), parseoptions(), and warning_opts().
{
    if(!initial) {
        rejectoption(optname);
        return (char *)0;
    }
    return string_for_opt(opts, val_optional);
}
STATIC_OVL char* string_for_opt (char * opts, boolean val_optional)
Definition at line 723 of file options.c.
References badoption(), and index().
Referenced by parseoptions(), and string_for_env_opt().
{
    char *colon, *equals;
    colon = index(opts, ':');
    equals = index(opts, '=');
    if (!colon || (equals && equals < colon)) colon = equals;
    if (!colon || !*++colon) {
        if (!val_optional) badoption(opts);
        return (char *)0;
    }
    return colon;
}
STATIC_OVL void warning_opts (char * opts, const char * optype)
Definition at line 832 of file options.c.
References assign_warnings(), def_warnsyms, escapes(), FALSE, MAXPCHARS, string_for_env_opt(), and WARNCOUNT.
Referenced by parseoptions().
{
    uchar translate[MAXPCHARS+1];
    int length, i;
    if (!(opts = string_for_env_opt(optype, opts, FALSE)))
        return;
    escapes(opts, opts);
    length = strlen(opts);
    if (length > WARNCOUNT) length = WARNCOUNT;
    /* match the form obtained from PC configuration files */
    for (i = 0; i < length; i++)
         translate[i] = (((i < WARNCOUNT) && opts[i]) ?
               (uchar) opts[i] : def_warnsyms[i].sym);
    assign_warnings(translate);
}
STATIC_OVL boolean wc2_supported (char * optnam) const
Definition at line 3729 of file options.c.
References FALSE, TRUE, wc_Opt::wc_bit, wc_Opt::wc_name, window_procs::wincap2, and windowprocs.
Referenced by doset().
{
    int k = 0;
    while (wc2_options[k].wc_name) {
        if (!strcmp(wc2_options[k].wc_name, optnam) &&
            (windowprocs.wincap2 & wc2_options[k].
      wc_bit))
            return TRUE;
        k++;
    }
    return FALSE;
}
STATIC_OVL void wc_set_font_name (int wtype, char * fontname)
Definition at line 3744 of file options.c.
References alloc(), free(), iflags, NHW_MAP, NHW_MENU, NHW_MESSAGE, NHW_STATUS, NHW_TEXT, Strcpy, instance_flags::wc_font_map, instance_flags::wc_font_menu, instance_flags::wc_font_message, instance_flags::wc_font_status, and instance_flags::wc_font_text.
Referenced by parseoptions().
{
    char **fn = (char **)0;
    if (!fontname) return;
    switch(wtype) {
        case NHW_MAP:
                fn = &iflags.wc_font_map;
            break;
        case NHW_MESSAGE:
                fn = &iflags.wc_font_message;
            break;
        case NHW_TEXT:
                fn = &iflags.wc_font_text;
            break;
        case NHW_MENU:
                fn = &iflags.wc_font_menu;
            break;
        case NHW_STATUS:
                fn = &iflags.wc_font_status;
            break;
        default:
                return;
    }
    if (fn) {
        if (*fn) free(*fn);
        *fn = (char *)alloc(strlen(fontname) + 1);
        Strcpy(*fn, fontname);
    }
    return;
}
STATIC_OVL int wc_set_window_colors (char * op)
Definition at line 3778 of file options.c.
References alloc(), buf, BUFSZ, free(), iflags, strcmpi, Strcpy, instance_flags::wc_backgrnd_menu, instance_flags::wc_backgrnd_message, instance_flags::wc_backgrnd_status, instance_flags::wc_backgrnd_text, instance_flags::wc_foregrnd_menu, instance_flags::wc_foregrnd_message, instance_flags::wc_foregrnd_status, and instance_flags::wc_foregrnd_text.
Referenced by parseoptions().
{
    /* syntax:
     * menu white/black message green/yellow status white/blue text white/black
     */
    int j;
    char buf[BUFSZ];
    char *wn, *tfg, *tbg, *newop;
    static const char *wnames[] = { "menu", "message", "status", "text" };
    static const char *shortnames[] = { "mnu", "msg", "sts", "txt" };
    static char **fgp[] = {
        &iflags.wc_foregrnd_menu,
        &iflags.wc_foregrnd_message,
        &iflags.wc_foregrnd_status,
        &iflags.wc_foregrnd_text
    };
    static char **bgp[] = {
        &iflags.wc_backgrnd_menu,
        &iflags.wc_backgrnd_message,
        &iflags.wc_backgrnd_status,
        &iflags.wc_backgrnd_text
    };
    Strcpy(buf, op);
    newop = mungspaces(buf);
    while (newop && *newop) {
        wn = tfg = tbg = (char *)0;
        /* until first non-space in case there's leading spaces - before colorname*/
        while(*newop && isspace(*newop)) newop++;
        if (*newop) wn = newop;
        else return 0;
        /* until first space - colorname*/
        while(*newop && !isspace(*newop)) newop++;
        if (*newop) *newop = '\0';
        else return 0;
        newop++;
        /* until first non-space - before foreground*/
        while(*newop && isspace(*newop)) newop++;
        if (*newop) tfg = newop;
        else return 0;
        /* until slash - foreground */
        while(*newop && *newop != '/') newop++;
        if (*newop) *newop = '\0';
        else return 0;
        newop++;
        /* until first non-space (in case there's leading space after slash) - before background */
        while(*newop && isspace(*newop)) newop++;
        if (*newop) tbg = newop;
        else return 0;
        /* until first space - background */
        while(*newop && !isspace(*newop)) newop++;
        if (*newop) *newop++ = '\0';
        for (j = 0; j < 4; ++j) {
            if (!strcmpi(wn, wnames[j]) ||
                !strcmpi(wn, shortnames[j])) {
                if (tfg && !strstri(tfg, " ")) {
                    if (*fgp[j]) free(*fgp[j]);
                    *fgp[j] = (char *)alloc(strlen(tfg) + 1);
                    Strcpy(*fgp[j], tfg);
                }
                if (tbg && !strstri(tbg, " ")) {
                    if (*bgp[j]) free(*bgp[j]);
                    *bgp[j] = (char *)alloc(strlen(tbg) + 1);
                    Strcpy(*bgp[j], tbg);
                }
                break;
            }
        }
    }
    return 1;
}
STATIC_OVL boolean wc_supported (char * optnam) const
Definition at line 3673 of file options.c.
References FALSE, TRUE, wc_Opt::wc_bit, wc_Opt::wc_name, window_procs::wincap, and windowprocs.
Referenced by doset().
{
    int k = 0;
    while (wc_options[k].wc_name) {
        if (!strcmp(wc_options[k].wc_name, optnam) &&
            (windowprocs.wincap & wc_options[k].
      wc_bit))
            return TRUE;
        k++;
    }
    return FALSE;
}
Variable Documentation
struct Bool_Opt boolopt[] [static]
Referenced by doset(), duplicate_opt_detection(), initoptions(), option_help(), parseoptions(), set_duplicate_opt_detection(), and set_option_mod_status().
NEARDATA const char* burdentype[] [static]
Initial value:
= {
    "unencumbered", "burdened", "stressed",
    "strained", "overtaxed", "overloaded"
}
Definition at line 2257 of file options.c.
struct Comp_Opt compopt[] [static]
Referenced by doset(), doset_add_menu(), duplicate_opt_detection(), option_help(), set_duplicate_opt_detection(), and set_option_mod_status().
char def_inv_order[MAXOCLASSES] [static]
Initial value:
= {
    COIN_CLASS, AMULET_CLASS, WEAPON_CLASS,
      ARMOR_CLASS, FOOD_CLASS,
    SCROLL_CLASS, SPBOOK_CLASS, POTION_CLASS,
      RING_CLASS, WAND_CLASS,
    TOOL_CLASS, GEM_CLASS, ROCK_CLASS, BALL_CLASS,
      CHAIN_CLASS, 0,
}
Definition at line 354 of file options.c.
const menu_cmd_t default_menu_cmd_info[NUM_MENU_CMDS] [static]
Initial value:
= {
    { "menu_first_page", MENU_FIRST_PAGE },
    { "menu_last_page", MENU_LAST_PAGE },
    { "menu_next_page", MENU_NEXT_PAGE },
    { "menu_previous_page", MENU_PREVIOUS_PAGE },
    { "menu_select_all", MENU_SELECT_ALL },
    { "menu_deselect_all", MENU_UNSELECT_ALL },
    { "menu_invert_all", MENU_INVERT_ALL },
    { "menu_select_page", MENU_SELECT_PAGE },
    { "menu_deselect_page", MENU_UNSELECT_PAGE },
    { "menu_invert_page", MENU_INVERT_PAGE },
    { "menu_search", MENU_SEARCH },
}
Definition at line 392 of file options.c.
char fmtstr_doset_add_menu[] = `%s%-15s [%s] ` [static]
Definition at line 2327 of file options.c.
char fmtstr_doset_add_menu_tab[] = `%s\t[%s]` [static]
Definition at line 2328 of file options.c.
boolean from_file [static]
Definition at line 416 of file options.c.
boolean initial [static]
Definition at line 416 of file options.c.
char mapped_menu_cmds[MAX_MENU_MAPPED_CMDS+1]
Definition at line 411 of file options.c.
Referenced by map_menu_cmd().
char mapped_menu_op[MAX_MENU_MAPPED_CMDS+1] [static]
Definition at line 412 of file options.c.
NEARDATA const char* menutype[] [static]
Initial value:
= {
    "traditional", "combination", "partial", "full"
}
Definition at line 2253 of file options.c.
short n_menu_mapped = 0 [static]
Definition at line 413 of file options.c.
Referenced by add_menu_cmd_alias().
boolean need_redraw [static]
Definition at line 343 of file options.c.
const char* opt_epilog[] [static]
Initial value:
= {
    "",
 "Some of the options can be set only before the game is started; those",
    "items will not be selectable in the 'O' command's menu.",
    (char *)0
}
Definition at line 3285 of file options.c.
const char* opt_intro[] [static]
Initial value:
= {
    "",
    " NetHack Options Help:",
    "",
#define CONFIG_SLOT
    (char *)0,
    "or use `NETHACKOPTIONS=\"<options>\"' in your environment",
    "(<options> is a list of options separated by commas)",
    "or press \"O\" while playing and use the menu.",
    "",
 "Boolean options (which can be negated by prefixing them with '!' or \"no\"):",
    (char *)0
}
Definition at line 3266 of file options.c.
NEARDATA const char* runmodes[] [static]
Initial value:
= {
    "teleport", "run", "walk", "crawl"
}
Definition at line 2262 of file options.c.
struct wc_Opt wc2_options[]
Initial value:
= {
    {"fullscreen", WC2_FULLSCREEN},
    {"softkeyboard", WC2_SOFTKEYBOARD},
    {"wraptext", WC2_WRAPTEXT},
    {(char *)0, 0L}
}
Definition at line 3592 of file options.c.
struct wc_Opt wc_options[]
Definition at line 3554 of file options.c.