nethack/sys/share/pcsys.c File Reference
#include `hack.h`
*
#include `wintty.h`
*
#include <ctype.h>
*
#include <fcntl.h>
*
#include <process.h>
*
Macros
#define NEED_VARARGS
#define nethack_exit exit
#define PATHSEP ';'
Functions
static void NDECL (msexit)
void append_slash (char *name)
void getreturn (char *str) const
void msmsg VA_DECL (const char *, VA_INIT(fmt)
Macro Definition Documentation
#define NEED_VARARGS
Definition at line 8 of file pcsys.c.
#define nethack_exit exit
Definition at line 34 of file pcsys.c.
#define PATHSEP ';'
Function Documentation
void append_slash (char * name)
Definition at line 376 of file pcsys.c.
Referenced by check_recordfile(), and parse_config_line().
{
    char *ptr;
    if (!*name)
        return;
    ptr = name + (strlen(name) - 1);
    if (*ptr != '\\' && *ptr != '/' && *ptr != ':') {
        *++ptr = '\\';
        *++ptr = '\0';
    }
    return;
}
void getreturn (char * str) const
Definition at line 396 of file pcsys.c.
References Getchar, and msmsg().
{
#ifdef WIN32
    if (!getreturn_enabled) return;
#endif
#ifdef TOS
    msmsg("Hit <Return> %s.", str);
#else
    msmsg("Hit <Enter> %s.", str);
#endif
    while (Getchar() != '\n') ;
    return;
}
static void NDECL (msexit) [static]
void msmsg VA_DECL (const char * , VA_INIT(fmt)
Definition at line 413 of file pcsys.c.
                 :'
# else
#define PATHSEP ','
# endif
#else
#define PATHSEP ';'
#endif
FILE *
fopenp(name, mode)
const char *name, *mode;
{
    char buf[BUFSIZ], *bp, *pp, lastch = 0;
    FILE *fp;
    /* Try the default directory first. Then look along PATH.
     */
    (void) strncpy(buf, name, BUFSIZ - 1);
    buf[BUFSIZ-1] = '\0';
    if ((fp = fopen(buf, mode)))
        return fp;
    else {
        int ccnt = 0;
        pp = getenv("PATH");
        while (pp && *pp) {
            bp = buf;
            while (*pp && *pp != PATHSEP) {
                lastch = *bp++ = *pp++;
                ccnt++;
            }
            if (lastch != '\\' && lastch != '/') {
                *bp++ = '\\';
                ccnt++;
            }
            (void) strncpy(bp, name, (BUFSIZ - ccnt) - 2);
            bp[BUFSIZ - ccnt - 1] = '\0';
            if ((fp = fopen(buf, mode)))
                return fp;
            if (*pp)
                pp++;
        }
    }
#ifdef OS2_CODEVIEW /* one more try for hackdir */
    (void) strncpy(buf, hackdir, BUFSZ);
    buf[BUFSZ-1] = '\0';
    if ((strlen(name) + 1 + strlen(buf)) < BUFSZ - 1) {
        append_slash(buf);
        Strcat(buf,name);
    } else
        impossible("fopenp() buffer too small for complete filename!");
    if(fp = fopen(buf,mode))
        return fp;
#endif
    return (FILE *)0;
}