nethack/win/share/ppmwrite.c File Reference
#include `config.h`
*
#include `tile.h`
*
Data Structures
struct ppmscreen
Functions
long * FDECL (alloc,(unsigned int))
static void NDECL (write_header)
static void NDECL (WriteTileStrip)
static void write_header ()
static void WriteTileStrip ()
boolean fopen_ppm_file (char *filename, const char *type) const
boolean write_ppm_tile (pixel *pixels)
int fclose_ppm_file ()
int main (int argc, argv)
Variables
FILE * ppm_file
struct ppmscreen PpmScreen
static int tiles_across
static int tiles_down
static int curr_tiles_across
static pixel ** image
Function Documentation
int fclose_ppm_file ()
Definition at line 106 of file ppmwrite.c.
References pixel::b, CM_BLUE, CM_GREEN, CM_RED, free(), pixel::g, ppmscreen::Height, MainColorMap, PpmScreen, pixel::r, rewind, TILE_X, TILE_Y, ppmscreen::Width, write_header(), and WriteTileStrip().
Referenced by main().
{
    int i, j;
    if (curr_tiles_across) { /* partial row */
        /* fill with checkerboard, for lack of a better idea */
        for (j = 0; j < TILE_Y; j++) {
            for (i = curr_tiles_across * TILE_X;
                        i < PpmScreen.Width; i += 2) {
                image[j][i].r = MainColorMap[CM_RED][0];
                image[j][i].g = MainColorMap[CM_GREEN][0];
                image[j][i].b = MainColorMap[CM_BLUE][0];
                image[j][i+1].r = MainColorMap[CM_RED][1];
                image[j][i+1].g = MainColorMap[CM_GREEN][1];
                image[j][i+1].b = MainColorMap[CM_BLUE][1];
            }
        }
        WriteTileStrip();
        curr_tiles_across = 0;
        tiles_down++;
    }
    for (i = 0; i < TILE_Y; i++) {
        free((genericptr_t)image[i]);
    }
    free((genericptr_t)image);
    PpmScreen.Height = tiles_down * TILE_Y;
    rewind(ppm_file);
    write_header(); /* update size */
    return(fclose(ppm_file));
}
long* FDECL (alloc , (unsigned int))
boolean fopen_ppm_file (char * filename, const char * type) const
Definition at line 47 of file ppmwrite.c.
References alloc(), colorsinmainmap, FALSE, Fprintf, ppmscreen::Height, PpmScreen, TILE_X, TILE_Y, TRUE, ppmscreen::Width, WRBMODE, and write_header().
Referenced by main().
{
    int i;
    if (strcmp(type, WRBMODE)) {
        Fprintf(stderr, "using writing routine for non-writing?\n");
        return FALSE;
    }
    ppm_file = fopen(filename, type);
    if (ppm_file == (FILE *)0) {
        Fprintf(stderr, "cannot open ppm file %s\n", filename);
        return FALSE;
    }
    if (!colorsinmainmap) {
        Fprintf(stderr, "no colormap set yet\n");
        return FALSE;
    }
    tiles_across = 20;
    curr_tiles_across = 0;
    PpmScreen.Width = 20 * TILE_X;
    tiles_down = 0;
    PpmScreen.Height = 0; /* will be rewritten later */
    write_header();
    image = (pixel **)alloc(TILE_Y * sizeof(pixel *));
    for (i = 0; i < TILE_Y; i++) {
        image[i] = (pixel *) alloc(PpmScreen.Width * sizeof(
      pixel));
    }
    return TRUE;
}
int main (int argc, argv)
Definition at line 142 of file ppmwrite.c.
References exit(), EXIT_FAILURE, EXIT_SUCCESS, fclose_ppm_file(), fclose_text_file(), fopen_ppm_file(), fopen_text_file(), Fprintf, init_colormap(), pixels, RDTMODE, read_text_tile(), TILE_X, TILE_Y, WRBMODE, and write_ppm_tile().
{
    pixel pixels[TILE_Y][TILE_X];
    if (argc != 3) {
        Fprintf(stderr, "usage: txt2ppm txtfile ppmfile\n");
        exit(EXIT_FAILURE);
    }
    if (!fopen_text_file(argv[1], RDTMODE))
        exit(EXIT_FAILURE);
    init_colormap();
    if (!fopen_ppm_file(argv[2], WRBMODE)) {
        (void) fclose_text_file();
        exit(EXIT_FAILURE);
    }
    while (read_text_tile(pixels))
        (void) write_ppm_tile(pixels);
    (void) fclose_text_file();
    (void) fclose_ppm_file();
    exit(EXIT_SUCCESS);
    /*NOTREACHED*/
    return 0;
}
static void NDECL (write_header) [static]
static void NDECL (WriteTileStrip) [static]
static void write_header () [static]
Definition at line 26 of file ppmwrite.c.
References ppmscreen::Height, PpmScreen, and ppmscreen::Width.
Referenced by fclose_ppm_file(), and fopen_ppm_file().
{
    (void) fprintf(ppm_file, "P6 %03d %03d 255\n",
                PpmScreen.Width, PpmScreen.Height);
}
boolean write_ppm_tile (pixel * pixels)
Definition at line 86 of file ppmwrite.c.
References pixels, TILE_X, TILE_Y, TRUE, and WriteTileStrip().
Referenced by main().
{
    int i, j;
    for (j = 0; j < TILE_Y; j++) {
        for (i = 0; i < TILE_X; i++) {
            image[j][curr_tiles_across*TILE_X + i] = pixels[j][i];
        }
    }
    curr_tiles_across++;
    if (curr_tiles_across == tiles_across) {
        WriteTileStrip();
        curr_tiles_across = 0;
        tiles_down++;
    }
    return TRUE;
}
static void WriteTileStrip () [static]
Definition at line 33 of file ppmwrite.c.
References pixel::b, pixel::g, ppm_file, PpmScreen, pixel::r, TILE_Y, and ppmscreen::Width.
Referenced by fclose_ppm_file(), and write_ppm_tile().
{
    int i, j;
    for (j = 0; j < TILE_Y; j++) {
        for (i = 0; i < PpmScreen.Width; i++) {
            (void) fputc((char)image[j][i].r, ppm_file);
            (void) fputc((char)image[j][i].g, ppm_file);
            (void) fputc((char)image[j][i].b, ppm_file);
        }
    }
}
Variable Documentation
int curr_tiles_across [static]
Definition at line 19 of file ppmwrite.c.
pixel** image [static]
Definition at line 20 of file ppmwrite.c.
FILE* ppm_file
Definition at line 12 of file ppmwrite.c.
Referenced by WriteTileStrip().
struct ppmscreen PpmScreen
Referenced by fclose_ppm_file(), fopen_ppm_file(), write_header(), and WriteTileStrip().
int tiles_across [static]
Definition at line 19 of file ppmwrite.c.
int tiles_down [static]
Definition at line 19 of file ppmwrite.c.