nethack/src/quest.c File Reference
#include `hack.h`
*
#include `quest.h`
*
#include `qtext.h`
*
Macros
#define Not_firsttime (on_level(&u.uz0, &u.uz))
#define Qstat(x) (quest_status.x)
Functions
STATIC_DCL void NDECL (on_start)
STATIC_DCL void NDECL (on_locate)
STATIC_DCL void NDECL (on_goal)
STATIC_DCL boolean NDECL (not_capable)
STATIC_DCL int FDECL (is_pure,(BOOLEAN_P))
STATIC_DCL void FDECL (expulsion,(BOOLEAN_P))
STATIC_DCL void NDECL (chat_with_leader)
STATIC_DCL void NDECL (chat_with_nemesis)
STATIC_DCL void NDECL (chat_with_guardian)
STATIC_DCL void FDECL (prisoner_speaks,(struct monst *))
STATIC_OVL void on_start ()
STATIC_OVL void on_locate ()
STATIC_OVL void on_goal ()
void onquest ()
void nemdead ()
void artitouch ()
boolean ok_to_quest ()
STATIC_OVL boolean not_capable ()
STATIC_OVL int is_pure (boolean talk)
STATIC_OVL void expulsion (boolean seal)
void finish_quest (struct obj *obj)
STATIC_OVL void chat_with_leader ()
void leader_speaks (struct monst *mtmp)
STATIC_OVL void chat_with_nemesis ()
void nemesis_speaks ()
STATIC_OVL void chat_with_guardian ()
STATIC_OVL void prisoner_speaks (struct monst *mtmp)
void quest_chat (struct monst *mtmp)
void quest_talk (struct monst *mtmp)
void quest_stat_check (struct monst *mtmp)
Macro Definition Documentation
#define Not_firsttime (on_level(&u.uz0, &u.uz))
Definition at line 12 of file quest.c.
Referenced by onquest().
#define Qstat(x) (quest_status.x)
Definition at line 13 of file quest.c.
Referenced by artitouch(), chat_with_guardian(), chat_with_leader(), chat_with_nemesis(), finish_quest(), leader_speaks(), nemdead(), nemesis_speaks(), ok_to_quest(), on_goal(), on_locate(), on_start(), quest_chat(), quest_stat_check(), and quest_talk().
Function Documentation
void artitouch ()
Definition at line 85 of file quest.c.
References A_WIS, Qstat, QT_GOTIT, qt_pager(), and TRUE.
{
    if(!Qstat(touched_artifact)) {
        Qstat(touched_artifact) = TRUE;
        qt_pager(QT_GOTIT);
        exercise(A_WIS, TRUE);
    }
}
STATIC_OVL void chat_with_guardian ()
Definition at line 316 of file quest.c.
References Qstat, QT_GUARDTALK, QT_GUARDTALK2, qt_pager(), rn1, u, and you::uhave.
Referenced by quest_chat().
{
/* These guys/gals really don't have much to say... */
    if (u.uhave.questart && Qstat(killed_nemesis))
        qt_pager(rn1(5, QT_GUARDTALK2));
    else
        qt_pager(rn1(5, QT_GUARDTALK));
}
STATIC_OVL void chat_with_leader ()
Definition at line 206 of file quest.c.
References A_WIS, com_pager(), expulsion(), FALSE, finish_quest(), invent, is_pure(), is_quest_artifact(), MAX_QUEST_TRIES, obj::nobj, not_capable(), otmp, qstart_level, Qstat, QT_ASSIGNQUEST, QT_BADALIGN, QT_BADLEVEL, QT_BANISHED, QT_ENCOURAGE, QT_FIRSTLEADER, QT_LASTLEADER, QT_NEXTLEADER, qt_pager(), QT_POSTHANKS, rn1, TRUE, u, you::uhave, and you::uz.
Referenced by leader_speaks(), and quest_chat().
{
/* Rule 0: Cheater checks. */
    if(u.uhave.questart && !Qstat(met_nemesis))
        Qstat(cheater) = TRUE;
/* It is possible for you to get the amulet without completing
 * the quest. If so, try to induce the player to quest.
 */
    if(Qstat(got_thanks)) {
/* Rule 1: You've gone back with/without the amulet. */
        if(u.uhave.amulet) finish_quest((struct obj *)0);
/* Rule 2: You've gone back before going for the amulet. */
        else qt_pager(QT_POSTHANKS);
    }
/* Rule 3: You've got the artifact and are back to return it. */
      else if(u.uhave.questart) {
        struct obj *otmp;
        for (otmp = invent; otmp; otmp = otmp->nobj)
        if (is_quest_artifact(otmp)) break;
        finish_quest(otmp);
/* Rule 4: You haven't got the artifact yet. */
    } else if(Qstat(got_quest)) {
        qt_pager(rn1(10, QT_ENCOURAGE));
/* Rule 5: You aren't yet acceptable - or are you? */
    } else {
      if(!Qstat(met_leader)) {
        qt_pager(QT_FIRSTLEADER);
        Qstat(met_leader) = TRUE;
        Qstat(not_ready) = 0;
      } else qt_pager(QT_NEXTLEADER);
      /* the quest leader might have passed through the portal into
         the regular dungeon; none of the remaining make sense there */
      if (!on_level(&u.uz, &qstart_level)) return;
      if(not_capable()) {
        qt_pager(QT_BADLEVEL);
        exercise(A_WIS, TRUE);
        expulsion(FALSE);
      } else if(is_pure(TRUE) < 0) {
        com_pager(QT_BANISHED);
        expulsion(TRUE);
      } else if(is_pure(TRUE) == 0) {
        qt_pager(QT_BADALIGN);
        if(Qstat(not_ready) == MAX_QUEST_TRIES) {
          qt_pager(QT_LASTLEADER);
          expulsion(TRUE);
        } else {
          Qstat(not_ready)++;
          exercise(A_WIS, TRUE);
          expulsion(FALSE);
        }
      } else { /* You are worthy! */
        qt_pager(QT_ASSIGNQUEST);
        exercise(A_WIS, TRUE);
        Qstat(got_quest) = TRUE;
      }
    }
}
STATIC_OVL void chat_with_nemesis ()
Definition at line 292 of file quest.c.
References Qstat, QT_DISCOURAGE, qt_pager(), and rn1.
Referenced by quest_chat().
{
/* The nemesis will do most of the talking, but... */
    qt_pager(rn1(10, QT_DISCOURAGE));
    if(!Qstat(met_nemesis)) Qstat(met_nemesis++);
}
STATIC_OVL void expulsion (boolean seal)
Definition at line 144 of file quest.c.
References d_level::dnum, branch::end1, branch::end2, FALSE, ftrap, MAGIC_PORTAL, trap::ntrap, u, you::uevent, and you::uz.
Referenced by chat_with_leader(), and leader_speaks().
{
    branch *br;
    d_level *dest;
    struct trap *t;
    int portal_flag;
    br = dungeon_branch("The Quest");
    dest = (br->end1.dnum == u.uz.dnum) ? &br->end2 : &br->
      end1;
    portal_flag = u.uevent.qexpelled ? 0 : /* returned via artifact? */
          !seal ? 1 : -1;
    schedule_goto(dest, FALSE, FALSE, portal_flag, (char *)0, (char *)0);
    if (seal) { /* remove the portal to the quest - sealing it off */
    int reexpelled = u.uevent.qexpelled;
    u.uevent.qexpelled = 1;
    /* Delete the near portal now; the far (main dungeon side)
       portal will be deleted as part of arrival on that level.
       If monster movement is in progress, any who haven't moved
       yet will now miss out on a chance to wander through it... */
    for (t = ftrap; t; t = t->ntrap)
        if (t->ttyp == MAGIC_PORTAL) break;
    if (t) deltrap(t); /* (display might be briefly out of sync) */
    else if (!reexpelled) impossible("quest portal already gone?");
    }
}
STATIC_DCL int FDECL (is_pure , (BOOLEAN_P))
STATIC_DCL void FDECL (expulsion , (BOOLEAN_P))
STATIC_DCL void FDECL (prisoner_speaks , (struct monst *))
void finish_quest (struct obj * obj)
Definition at line 177 of file quest.c.
References com_pager(), otmp, Qstat, QT_HASAMULET, QT_OFFEREDIT, QT_OFFEREDIT2, qt_pager(), TRUE, u, you::uevent, you::uhave, and update_inventory.
Referenced by chat_with_leader(), and thitmonst().
{
    struct obj *otmp;
    if (u.uhave.amulet) { /* unlikely but not impossible */
        qt_pager(QT_HASAMULET);
        /* leader IDs the real amulet but ignores any fakes */
        if ((otmp = carrying(AMULET_OF_YENDOR)) != 0)
        fully_identify_obj(otmp);
    } else {
        qt_pager(!Qstat(got_thanks) ? QT_OFFEREDIT :
      QT_OFFEREDIT2);
        /* should have obtained bell during quest;
           if not, suggest returning for it now */
        if ((otmp = carrying(BELL_OF_OPENING)) == 0)
        com_pager(5);
    }
    Qstat(got_thanks) = TRUE;
    if (obj) {
        u.uevent.qcompleted = 1; /* you did it! */
        /* behave as if leader imparts sufficient info about the
           quest artifact */
        fully_identify_obj(obj);
        update_inventory();
    }
}
STATIC_OVL int is_pure (boolean talk)
Definition at line 109 of file quest.c.
References A_CURRENT, A_ORIGINAL, MIN_QUEST_ALIGN, align::record, align::type, u, you::ualign, you::ualignbase, and wizard.
Referenced by chat_with_leader(), and ok_to_quest().
{
    int purity;
    aligntyp original_alignment = u.ualignbase[A_ORIGINAL];
#ifdef WIZARD
    if (wizard && talk) {
    if (u.ualign.type != original_alignment) {
        You("are currently %s instead of %s.",
        align_str(u.ualign.type), align_str(original_alignment));
    } else if (u.ualignbase[A_CURRENT] != original_alignment) {
        You("have converted.");
    } else if (u.ualign.record < MIN_QUEST_ALIGN) {
        You("are currently %d and require %d.",
        u.ualign.record, MIN_QUEST_ALIGN);
        if (yn_function("adjust?", (char *)0, 'y') == 'y')
        u.ualign.record = MIN_QUEST_ALIGN;
    }
    }
#endif
    purity = (u.ualign.record >= MIN_QUEST_ALIGN &&
          u.ualign.type == original_alignment &&
          u.ualignbase[A_CURRENT] == original_alignment) ? 1 :
         (u.ualignbase[A_CURRENT] != original_alignment) ? -1 : 0;
    return purity;
}
void leader_speaks (struct monst * mtmp)
Definition at line 273 of file quest.c.
References chat_with_leader(), expulsion(), qstart_level, Qstat, QT_LASTLEADER, qt_pager(), STRAT_WAITMASK, TRUE, u, and you::uz.
Referenced by quest_talk().
{
    /* maybe you attacked leader? */
    if(!mtmp->mpeaceful) {
        Qstat(pissed_off) = TRUE;
        mtmp->mstrategy &= ~STRAT_WAITMASK; /* end the inaction */
    }
    /* the quest leader might have passed through the portal into the
       regular dungeon; if so, mustn't perform "backwards expulsion" */
    if (!on_level(&u.uz, &qstart_level)) return;
    if(Qstat(pissed_off)) {
      qt_pager(QT_LASTLEADER);
      expulsion(TRUE);
    } else chat_with_leader();
}
STATIC_DCL void NDECL (on_start)
STATIC_DCL void NDECL (on_locate)
STATIC_DCL void NDECL (on_goal)
STATIC_DCL boolean NDECL (not_capable)
STATIC_DCL void NDECL (chat_with_leader)
STATIC_DCL void NDECL (chat_with_nemesis)
STATIC_DCL void NDECL (chat_with_guardian)
void nemdead ()
Definition at line 76 of file quest.c.
References Qstat, QT_KILLEDNEM, qt_pager(), and TRUE.
{
    if(!Qstat(killed_nemesis)) {
        Qstat(killed_nemesis) = TRUE;
        qt_pager(QT_KILLEDNEM);
    }
}
void nemesis_speaks ()
Definition at line 300 of file quest.c.
References Qstat, QT_DISCOURAGE, QT_FIRSTNEMESIS, QT_NEMWANTSIT, QT_NEXTNEMESIS, QT_OTHERNEMESIS, qt_pager(), rn1, TRUE, u, and you::uhave.
Referenced by quest_talk().
{
    if(!Qstat(in_battle)) {
      if(u.uhave.questart) qt_pager(QT_NEMWANTSIT);
      else if(Qstat(made_goal) == 1 || !Qstat(met_nemesis))
          qt_pager(QT_FIRSTNEMESIS);
      else if(Qstat(made_goal) < 4) qt_pager(QT_NEXTNEMESIS);
      else if(Qstat(made_goal) < 7) qt_pager(QT_OTHERNEMESIS);
      else if(!rn2(5)) qt_pager(rn1(10, QT_DISCOURAGE));
      if(Qstat(made_goal) < 7) Qstat(made_goal)++;
      Qstat(met_nemesis) = TRUE;
    } else /* he will spit out random maledictions */
      if(!rn2(5)) qt_pager(rn1(10, QT_DISCOURAGE));
}
STATIC_OVL boolean not_capable ()
Definition at line 103 of file quest.c.
References MIN_QUEST_LEVEL, u, and you::ulevel.
Referenced by chat_with_leader().
{
    return((boolean)(u.ulevel < MIN_QUEST_LEVEL));
}
boolean ok_to_quest ()
Definition at line 96 of file quest.c.
References FALSE, is_pure(), and Qstat.
Referenced by down_gate().
{
    return((boolean)((Qstat(got_quest) || Qstat(got_thanks)))
            && (is_pure(FALSE) > 0));
}
STATIC_OVL void on_goal ()
Definition at line 50 of file quest.c.
References Qstat, QT_FIRSTGOAL, QT_NEXTGOAL, and qt_pager().
Referenced by onquest().
{
  if (Qstat(killed_nemesis)) {
    return;
  } else if (!Qstat(made_goal)) {
    qt_pager(QT_FIRSTGOAL);
    Qstat(made_goal) = 1;
  } else {
    qt_pager(QT_NEXTGOAL);
    if(Qstat(made_goal) < 7) Qstat(made_goal)++;
  }
}
STATIC_OVL void on_locate ()
Definition at line 40 of file quest.c.
References d_level::dlevel, Qstat, QT_FIRSTLOCATE, QT_NEXTLOCATE, qt_pager(), TRUE, u, you::uz, and you::uz0.
Referenced by onquest().
{
  if(!Qstat(first_locate)) {
    qt_pager(QT_FIRSTLOCATE);
    Qstat(first_locate) = TRUE;
  } else if(u.uz0.dlevel < u.uz.dlevel && !Qstat(killed_nemesis))
    qt_pager(QT_NEXTLOCATE);
}
STATIC_OVL void on_start ()
Definition at line 28 of file quest.c.
References d_level::dlevel, d_level::dnum, Qstat, QT_FIRSTTIME, QT_NEXTTIME, QT_OTHERTIME, qt_pager(), TRUE, u, you::uz, and you::uz0.
Referenced by onquest().
{
  if(!Qstat(first_start)) {
    qt_pager(QT_FIRSTTIME);
    Qstat(first_start) = TRUE;
  } else if((u.uz0.dnum != u.uz.dnum) || (u.uz0.dlevel <
      u.uz.dlevel)) {
    if(Qstat(not_ready) <= 2) qt_pager(QT_NEXTTIME);
    else qt_pager(QT_OTHERTIME);
  }
}
void onquest ()
Definition at line 64 of file quest.c.
References d_level::dlevel, Is_nemesis, Is_qlocate, Is_qstart, Not_firsttime, on_goal(), on_locate(), on_start(), u, you::uevent, you::uz, and you::uz0.
{
    if(u.uevent.qcompleted || Not_firsttime) return;
    if(!Is_special(&u.uz)) return;
    if(Is_qstart(&u.uz)) on_start();
    else if(Is_qlocate(&u.uz) && u.uz.dlevel > u.uz0.
      dlevel) on_locate();
    else if(Is_nemesis(&u.uz)) on_goal();
    return;
}
STATIC_OVL void prisoner_speaks (struct monst * mtmp)
Definition at line 326 of file quest.c.
References canseemon, FALSE, mons, and STRAT_WAITMASK.
Referenced by quest_talk().
{
    if (mtmp->data == &mons[PM_PRISONER] &&
            (mtmp->mstrategy & STRAT_WAITMASK)) {
        /* Awaken the prisoner */
        if (canseemon(mtmp))
            pline("%s speaks:", Monnam(mtmp));
        verbalize("I'm finally free!");
        mtmp->mstrategy &= ~STRAT_WAITMASK;
        mtmp->mpeaceful = 1;
        /* Your god is happy... */
        adjalign(3);
        /* ...But the guards are not */
        (void) angry_guards(FALSE);
    }
    return;
}
void quest_chat (struct monst * mtmp)
Definition at line 348 of file quest.c.
References chat_with_guardian(), chat_with_leader(), chat_with_nemesis(), MS_GUARDIAN, MS_NEMESIS, and Qstat.
{
    if (mtmp->m_id == Qstat(leader_m_id)) {
    chat_with_leader();
    return;
    }
    switch(mtmp->data->msound) {
        case MS_NEMESIS: chat_with_nemesis(); break;
        case MS_GUARDIAN: chat_with_guardian(); break;
        default: impossible("quest_chat: Unknown quest character %s.",
                   mon_nam(mtmp));
    }
}
void quest_stat_check (struct monst * mtmp)
Definition at line 379 of file quest.c.
References MS_NEMESIS, Qstat, u, you::ux, and you::uy.
{
    if(mtmp->data->msound == MS_NEMESIS)
    Qstat(in_battle) = (mtmp->mcanmove && !mtmp->msleeping &&
                monnear(mtmp, u.ux, u.uy));
}
void quest_talk (struct monst * mtmp)
Definition at line 364 of file quest.c.
References leader_speaks(), MS_DJINNI, MS_NEMESIS, nemesis_speaks(), prisoner_speaks(), and Qstat.
{
    if (mtmp->m_id == Qstat(leader_m_id)) {
    leader_speaks(mtmp);
    return;
    }
    switch(mtmp->data->msound) {
        case MS_NEMESIS: nemesis_speaks(); break;
        case MS_DJINNI: prisoner_speaks(mtmp); break;
        default: break;
    }
}