nethack/src/questpgr.c File Reference
#include `hack.h`
*
#include `dlb.h`
*
#include `qtext.h`
*
Macros
#define QTEXT_FILE `quest.dat`
Functions
static void FDECL (Fread,(genericptr_t, int, int, dlb *))
STATIC_DCL struct qtmsg * FDECL (construct_qtlist,(long))
STATIC_DCL const char * NDECL (intermed)
STATIC_DCL const char * NDECL (neminame)
STATIC_DCL const char * NDECL (guardname)
STATIC_DCL const char * NDECL (homebase)
STATIC_DCL struct qtmsg * FDECL (msg_in,(struct qtmsg *, int))
STATIC_DCL void FDECL (convert_arg,(CHAR_P))
STATIC_DCL void NDECL (convert_line)
STATIC_DCL void FDECL (deliver_by_pline,(struct qtmsg *))
STATIC_DCL void FDECL (deliver_by_window,(struct qtmsg *, int))
static void Fread (genericptr_t ptr, int size, int nitems, dlb *stream)
STATIC_OVL struct qtmsg * construct_qtlist (long hdr_offset)
void load_qtlist ()
void unload_qtlist ()
short quest_info (int typ)
const char * ldrname ()
STATIC_OVL const char * intermed ()
boolean is_quest_artifact (struct obj *otmp)
STATIC_OVL const char * neminame ()
STATIC_OVL const char * guardname ()
STATIC_OVL const char * homebase ()
STATIC_OVL struct qtmsg * msg_in (struct qtmsg *qtm_list, int msgnum)
STATIC_OVL void convert_arg (char c)
STATIC_OVL void convert_line ()
STATIC_OVL void deliver_by_pline (struct qtmsg *qt_msg)
STATIC_OVL void deliver_by_window (struct qtmsg *qt_msg, int how)
void com_pager (int msgnum)
void qt_pager (int msgnum)
struct permonst * qt_montype ()
Variables
static char in_line [80]
static char cvt_buf [64]
static char out_line [128]
static struct qtlists qt_list
static dlb * msg_file
static char nambuf [sizeof cvt_buf]
Macro Definition Documentation
#define QTEXT_FILE `quest.dat`
Definition at line 12 of file questpgr.c.
Referenced by load_qtlist().
Function Documentation
void com_pager (int msgnum)
Definition at line 390 of file questpgr.c.
References qtlists::common, deliver_by_pline(), deliver_by_window(), qtmsg::delivery, dlb_fseek, msg_in(), NHW_MENU, NHW_TEXT, qtmsg::offset, qt_list, and SEEK_SET.
Referenced by chat_with_leader(), and finish_quest().
{
    struct qtmsg *qt_msg;
    if (!(qt_msg = msg_in(qt_list.common, msgnum))) {
        impossible("com_pager: message %d not found.", msgnum);
        return;
    }
    (void) dlb_fseek(msg_file, qt_msg->offset, SEEK_SET);
    if (qt_msg->delivery == 'p') deliver_by_pline(qt_msg);
    else if (msgnum == 1) deliver_by_window(qt_msg,
      NHW_MENU);
    else deliver_by_window(qt_msg, NHW_TEXT);
    return;
}
STATIC_OVL struct qtmsg* construct_qtlist (long hdr_offset)
Definition at line 69 of file questpgr.c.
References alloc(), dlb_fseek, Fread(), and SEEK_SET.
Referenced by load_qtlist().
{
    struct qtmsg *msg_list;
    int n_msgs;
    (void) dlb_fseek(msg_file, hdr_offset, SEEK_SET);
    Fread(&n_msgs, sizeof(int), 1, msg_file);
    msg_list = (struct qtmsg *)
        alloc((unsigned)(n_msgs+1)*sizeof(struct qtmsg));
    /*
     * Load up the list.
     */
    Fread((genericptr_t)msg_list, n_msgs*sizeof(struct qtmsg), 1,
      msg_file);
    msg_list[n_msgs].msgnum = -1;
    return(msg_list);
}
STATIC_OVL void convert_arg (char c)
Definition at line 226 of file questpgr.c.
References A_LAWFUL, A_ORIGINAL, align_gname(), align_gtitle(), Blind, dungeon::dname, dungeons, RoleName::f, flag::female, flags, guardname(), homebase(), intermed(), ldrname(), RoleName::m, MIN_QUEST_LEVEL, Role::name, neminame(), plname, Role::questarti, Role_switch, Strcpy, align::type, u, you::ualign, you::ualignbase, you::ulevel, and urole.
Referenced by convert_line().
{
    register const char *str;
    switch (c) {
        case 'p': str = plname;
            break;
        case 'c': str = (flags.female && urole.name.f) ?
                    urole.name.f : urole.name.m;
            break;
        case 'r': str = rank_of(u.ulevel, Role_switch, flags.
      female);
            break;
        case 'R': str = rank_of(MIN_QUEST_LEVEL, Role_switch,
                    flags.female);
            break;
        case 's': str = (flags.female) ? "sister" : "brother";
            break;
        case 'S': str = (flags.female) ? "daughter" : "son";
            break;
        case 'l': str = ldrname();
            break;
        case 'i': str = intermed();
            break;
        case 'o': str = the(artiname(urole.questarti));
            break;
        case 'n': str = neminame();
            break;
        case 'g': str = guardname();
            break;
        case 'G': str = align_gtitle(u.ualignbase[
      A_ORIGINAL]);
            break;
        case 'H': str = homebase();
            break;
        case 'a': str = align_str(u.ualignbase[A_ORIGINAL]);
            break;
        case 'A': str = align_str(u.ualign.type);
            break;
        case 'd': str = align_gname(u.ualignbase[
      A_ORIGINAL]);
            break;
        case 'D': str = align_gname(A_LAWFUL);
            break;
        case 'C': str = "chaotic";
            break;
        case 'N': str = "neutral";
            break;
        case 'L': str = "lawful";
            break;
        case 'x': str = Blind ? "sense" : "see";
            break;
        case 'Z': str = dungeons[0].dname;
            break;
        case '%': str = "%";
            break;
         default: str = "";
            break;
    }
    Strcpy(cvt_buf, str);
}
STATIC_OVL void convert_line ()
Definition at line 288 of file questpgr.c.
References BUFSZ, convert_arg(), out_line, panic(), Strcat, Strcpy, strncmpi(), and xcrypt().
Referenced by deliver_by_pline(), and deliver_by_window().
{
    char *c, *cc;
    char xbuf[BUFSZ];
    cc = out_line;
    for (c = xcrypt(in_line, xbuf); *c; c++) {
        *cc = 0;
        switch(*c) {
        case '\r':
        case '\n':
            *(++cc) = 0;
            return;
        case '%':
            if (*(c+1)) {
                convert_arg(*(++c));
                switch (*(++c)) {
                    /* insert "a"/"an" prefix */
                case 'A': Strcat(cc, An(cvt_buf));
                    cc += strlen(cc);
                    continue; /* for */
                case 'a': Strcat(cc, an(cvt_buf));
                    cc += strlen(cc);
                    continue; /* for */
                    /* capitalize */
                case 'C': cvt_buf[0] = highc(cvt_buf[0]);
                    break;
                    /* pluralize */
                case 'P': cvt_buf[0] = highc(cvt_buf[0]);
                case 'p': Strcpy(cvt_buf, makeplural(cvt_buf));
                    break;
                    /* append possessive suffix */
                case 'S': cvt_buf[0] = highc(cvt_buf[0]);
                case 's': Strcpy(cvt_buf, s_suffix(cvt_buf));
                    break;
                    /* strip any "the" prefix */
                case 't': if (!strncmpi(cvt_buf, "the ", 4)) {
                    Strcat(cc, &cvt_buf[4]);
                    cc += strlen(cc);
                    continue; /* for */
                    }
                    break;
                default: --c; /* undo switch increment */
                    break;
                }
                Strcat(cc, cvt_buf);
                cc += strlen(cvt_buf);
                break;
            } /* else fall through */
        default:
            *cc++ = *c;
            break;
        }
    }
    if (cc >= out_line + sizeof out_line)
        panic("convert_line: overflow");
    *cc = 0;
    return;
}
STATIC_OVL void deliver_by_pline (struct qtmsg * qt_msg)
Definition at line 359 of file questpgr.c.
References convert_line(), dlb_fgets, and qtmsg::size.
Referenced by com_pager(), and qt_pager().
{
    long size;
    for (size = 0; size < qt_msg->size; size += (long)strlen(in_line)) {
        (void) dlb_fgets(in_line, 80, msg_file);
        convert_line();
        pline(out_line);
    }
}
STATIC_OVL void deliver_by_window (struct qtmsg * qt_msg, int how)
Definition at line 373 of file questpgr.c.
References convert_line(), create_nhwindow, destroy_nhwindow, display_nhwindow, dlb_fgets, putstr, qtmsg::size, and TRUE.
Referenced by com_pager(), and qt_pager().
{
    long size;
    winid datawin = create_nhwindow(how);
    for (size = 0; size < qt_msg->size; size += (long)strlen(in_line)) {
        (void) dlb_fgets(in_line, 80, msg_file);
        convert_line();
        putstr(datawin, 0, out_line);
    }
    display_nhwindow(datawin, TRUE);
    destroy_nhwindow(datawin);
}
static void FDECL (Fread , (genericptr_t, int, int, dlb *)) [static]
STATIC_DCL struct qtmsg* FDECL (construct_qtlist , (long))
STATIC_DCL struct qtmsg* FDECL (msg_in , (struct qtmsg *, int))
STATIC_DCL void FDECL (convert_arg , (CHAR_P))
STATIC_DCL void FDECL (deliver_by_pline , (struct qtmsg *))
STATIC_DCL void FDECL (deliver_by_window , (struct qtmsg *, int))
static void Fread (genericptr_t ptr, int size, int nitems, dlb	* stream) [static]
Definition at line 54 of file questpgr.c.
References dlb_fread, and panic().
Referenced by construct_qtlist(), and load_qtlist().
{
    int cnt;
    if ((cnt = dlb_fread(ptr, size, nitems, stream)) != nitems) {
        panic("PREMATURE EOF ON QUEST TEXT FILE! Expected %d bytes, got %d",
            (size * nitems), (size * cnt));
    }
}
STATIC_OVL const char* guardname ()
Definition at line 199 of file questpgr.c.
References Role::guardnum, mons, and urole.
Referenced by convert_arg().
{
    int i = urole.guardnum;
    return(mons[i].mname);
}
STATIC_OVL const char* homebase ()
Definition at line 207 of file questpgr.c.
References Role::homebase, and urole.
Referenced by convert_arg().
{
    return(urole.homebase);
}
STATIC_OVL const char* intermed ()
Definition at line 175 of file questpgr.c.
References Role::intermed, and urole.
Referenced by convert_arg().
{
    return (urole.intermed);
}
boolean is_quest_artifact (struct obj * otmp)
Definition at line 181 of file questpgr.c.
References Role::questarti, and urole.
Referenced by chat_with_leader(), and resetobjs().
{
    return((boolean)(otmp->oartifact == urole.questarti));
}
const char* ldrname ()
Definition at line 164 of file questpgr.c.
References Role::ldrnum, mons, nambuf, Sprintf, type_is_pname, and urole.
Referenced by convert_arg().
{
    int i = urole.ldrnum;
    Sprintf(nambuf, "%s%s",
        type_is_pname(&mons[i]) ? "" : "the ",
        mons[i].mname);
    return nambuf;
}
void load_qtlist ()
Definition at line 90 of file questpgr.c.
References qtlists::chrole, qtlists::common, COMMON_ID, construct_qtlist(), dlb_fopen, Role::filecode, Race::filecode, Fread(), LEN_HDR, N_HDR, panic(), qt_list, QTEXT_FILE, RDBMODE, urace, and urole.
Referenced by dorecover().
{
    int n_classes, i;
    char qt_classes[N_HDR][LEN_HDR];
    long qt_offsets[N_HDR];
    msg_file = dlb_fopen(QTEXT_FILE, RDBMODE);
    if (!msg_file)
        panic("CANNOT OPEN QUEST TEXT FILE %s.", QTEXT_FILE);
    /*
     * Read in the number of classes, then the ID's & offsets for
     * each header.
     */
    Fread(&n_classes, sizeof(int), 1, msg_file);
    Fread(&qt_classes[0][0], sizeof(char)*LEN_HDR, n_classes,
      msg_file);
    Fread(qt_offsets, sizeof(long), n_classes, msg_file);
    /*
     * Now construct the message lists for quick reference later
     * on when we are actually paging the messages out.
     */
    qt_list.common = qt_list.chrole = (struct qtmsg *)0;
    for (i = 0; i < n_classes; i++) {
        if (!strncmp(COMMON_ID, qt_classes[i], LEN_HDR))
            qt_list.common = construct_qtlist(qt_offsets[i]);
        else if (!strncmp(urole.filecode, qt_classes[i], LEN_HDR))
            qt_list.chrole = construct_qtlist(qt_offsets[i]);
#if 0 /* UNUSED but available */
        else if (!strncmp(urace.filecode, qt_classes[i], LEN_HDR))
            qt_list.chrace = construct_qtlist(qt_offsets[i]);
#endif
    }
    if (!qt_list.common || !qt_list.chrole)
        impossible("load_qtlist: cannot load quest text.");
#ifdef DEBUG
    dump_qtlist();
#endif
    return; /* no ***DON'T*** close the msg_file */
}
STATIC_OVL struct qtmsg* msg_in (struct qtmsg * qtm_list, int msgnum)
Definition at line 213 of file questpgr.c.
References qtmsg::msgnum.
Referenced by com_pager(), and qt_pager().
{
    struct qtmsg *qt_msg;
    for (qt_msg = qtm_list; qt_msg->msgnum > 0; qt_msg++)
        if (qt_msg->msgnum == msgnum) return(qt_msg);
    return((struct qtmsg *)0);
}
STATIC_DCL const char* NDECL (intermed)
STATIC_DCL const char* NDECL (neminame)
STATIC_DCL const char* NDECL (guardname)
STATIC_DCL const char* NDECL (homebase)
STATIC_DCL void NDECL (convert_line)
STATIC_OVL const char* neminame ()
Definition at line 188 of file questpgr.c.
References mons, nambuf, Role::neminum, Sprintf, type_is_pname, and urole.
Referenced by convert_arg().
{
    int i = urole.neminum;
    Sprintf(nambuf, "%s%s",
        type_is_pname(&mons[i]) ? "" : "the ",
        mons[i].mname);
    return nambuf;
}
struct permonst* qt_montype ()
Definition at line 426 of file questpgr.c.
References Role::enemy1num, Role::enemy1sym, Role::enemy2num, Role::enemy2sym, G_GENOD, mons, NON_PM, and urole.
{
    int qpm;
    if (rn2(5)) {
        qpm = urole.enemy1num;
        if (qpm != NON_PM && rn2(5) && !(mvitals[qpm].mvflags &
      G_GENOD))
            return (&mons[qpm]);
        return (mkclass(urole.enemy1sym, 0));
    }
    qpm = urole.enemy2num;
    if (qpm != NON_PM && rn2(5) && !(mvitals[qpm].mvflags & G_GENOD))
        return (&mons[qpm]);
    return (mkclass(urole.enemy2sym, 0));
}
void qt_pager (int msgnum)
Definition at line 408 of file questpgr.c.
References qtlists::chrole, deliver_by_pline(), deliver_by_window(), qtmsg::delivery, dlb_fseek, msg_in(), window_procs::name, NHW_TEXT, qtmsg::offset, qt_list, SEEK_SET, and windowprocs.
Referenced by artitouch(), chat_with_guardian(), chat_with_leader(), chat_with_nemesis(), finish_quest(), leader_speaks(), nemdead(), nemesis_speaks(), on_goal(), on_locate(), and on_start().
{
    struct qtmsg *qt_msg;
    if (!(qt_msg = msg_in(qt_list.chrole, msgnum))) {
        impossible("qt_pager: message %d not found.", msgnum);
        return;
    }
    (void) dlb_fseek(msg_file, qt_msg->offset, SEEK_SET);
    if (qt_msg->delivery == 'p' && strcmp(windowprocs.name, "X11"))
        deliver_by_pline(qt_msg);
    else deliver_by_window(qt_msg, NHW_TEXT);
    return;
}
short quest_info (int typ)
Definition at line 150 of file questpgr.c.
References Role::guardnum, Role::ldrnum, MS_GUARDIAN, MS_LEADER, MS_NEMESIS, Role::neminum, Role::questarti, and urole.
{
    switch (typ) {
        case 0: return (urole.questarti);
        case MS_LEADER: return (urole.ldrnum);
        case MS_NEMESIS: return (urole.neminum);
        case MS_GUARDIAN: return (urole.guardnum);
        default: impossible("quest_info(%d)", typ);
    }
    return 0;
}
void unload_qtlist ()
Definition at line 138 of file questpgr.c.
References qtlists::chrole, qtlists::common, dlb_fclose, free(), and qt_list.
Referenced by freedynamicdata().
{
    if (msg_file)
        (void) dlb_fclose(msg_file), msg_file = 0;
    if (qt_list.common)
        free((genericptr_t) qt_list.common),
      qt_list.common = 0;
    if (qt_list.chrole)
        free((genericptr_t) qt_list.chrole),
      qt_list.chrole = 0;
    return;
}
Variable Documentation
char cvt_buf[64] [static]
Definition at line 28 of file questpgr.c.
char in_line[80] [static]
Definition at line 28 of file questpgr.c.
dlb* msg_file [static]
Definition at line 30 of file questpgr.c.
char nambuf[sizeof cvt_buf] [static]
Definition at line 32 of file questpgr.c.
Referenced by damageum(), ldrname(), m_dowear_type(), neminame(), and use_misc().
char out_line[128] [static]
Definition at line 28 of file questpgr.c.
Referenced by convert_line().
struct qtlists qt_list [static]
Definition at line 29 of file questpgr.c.
Referenced by com_pager(), load_qtlist(), qt_pager(), and unload_qtlist().