nethack/src/rect.c File Reference
#include `hack.h`
*
Macros
#define MAXRECT 50
#define XLIM 4
#define YLIM 3
Functions
int FDECL (get_rect_ind,(NhRect *))
static boolean FDECL (intersect,(NhRect *, NhRect *, NhRect *))
void init_rect ()
int get_rect_ind (NhRect *r)
NhRect * get_rect (NhRect *r)
NhRect * rnd_rect ()
static boolean intersect (NhRect *r1, NhRect *r2, NhRect *r3)
void remove_rect (NhRect *r)
void add_rect (NhRect *r)
void split_rects (NhRect *r1, NhRect *r2)
Variables
static NhRect rect [MAXRECT+1]
static int rect_cnt
Macro Definition Documentation
#define MAXRECT 50
Definition at line 16 of file rect.c.
Referenced by add_rect().
#define XLIM 4
Definition at line 17 of file rect.c.
Referenced by split_rects().
#define YLIM 3
Definition at line 18 of file rect.c.
Referenced by split_rects().
Function Documentation
void add_rect (NhRect * r)
Definition at line 134 of file rect.c.
References get_rect(), MAXRECT, rect_cnt, and wizard.
Referenced by split_rects().
{
    if (rect_cnt >= MAXRECT) {
#ifdef WIZARD
        if (wizard) pline("MAXRECT may be too small.");
#endif
        return;
    }
    /* Check that this NhRect is not included in another one */
    if (get_rect(r))
        return;
    rect[rect_cnt] = *r;
    rect_cnt++;
}
int FDECL (get_rect_ind , (NhRect *))
static boolean FDECL (intersect , (NhRect *, NhRect *, NhRect *)) [static]
NhRect* get_rect (NhRect * r)
Definition at line 64 of file rect.c.
References nhrect::lx, nhrect::ly, and rect_cnt.
Referenced by add_rect(), and create_room().
{
    register NhRect *rectp;
    register int lx, ly, hx, hy;
    register int i;
    lx = r->lx; ly = r->ly;
    hx = r->hx; hy = r->hy;
    for (i=0,rectp = &rect[0];i<rect_cnt;i++,rectp++)
        if (lx >= rectp->lx && ly >= rectp->ly &&
         hx <= rectp->hx && hy <= rectp->hy)
        return rectp;
    return 0;
}
int get_rect_ind (NhRect * r)
Definition at line 43 of file rect.c.
References nhrect::hx, nhrect::hy, nhrect::lx, nhrect::ly, and rect_cnt.
Referenced by remove_rect().
{
    register NhRect *rectp;
    register int lx, ly, hx, hy;
    register int i;
    lx = r->lx; ly = r->ly;
    hx = r->hx; hy = r->hy;
    for (i=0,rectp = &rect[0];i<rect_cnt;i++,rectp++)
        if (lx == rectp->lx && ly == rectp->ly &&
         hx == rectp->hx && hy == rectp->hy)
        return i;
    return -1;
}
void init_rect ()
Definition at line 29 of file rect.c.
References COLNO, nhrect::hx, nhrect::hy, nhrect::lx, nhrect::ly, and ROWNO.
Referenced by clear_level_structures().
{
    rect_cnt = 1;
    rect[0].lx = rect[0].ly = 0;
    rect[0].hx = COLNO - 1;
    rect[0].hy = ROWNO - 1;
}
static boolean intersect (NhRect * r1, NhRect * r2, NhRect * r3) [static]
Definition at line 97 of file rect.c.
References FALSE, and TRUE.
Referenced by split_rects().
{
    if (r2->lx > r1->hx || r2->ly > r1->hy ||
        r2->hx < r1->lx || r2->hy < r1->ly)
        return FALSE;
    r3->lx = (r2->lx > r1->lx ? r2->lx : r1->lx);
    r3->ly = (r2->ly > r1->ly ? r2->ly : r1->ly);
    r3->hx = (r2->hx > r1->hx ? r1->hx : r2->hx);
    r3->hy = (r2->hy > r1->hy ? r1->hy : r2->hy);
    if (r3->lx > r3->hx || r3->ly > r3->hy)
        return FALSE;
    return TRUE;
}
void remove_rect (NhRect * r)
Definition at line 119 of file rect.c.
References get_rect_ind(), and rect_cnt.
Referenced by split_rects().
{
    int ind;
    ind = get_rect_ind(r);
    if (ind >=0)
        rect[ind] = rect[--rect_cnt];
}
NhRect* rnd_rect ()
Definition at line 85 of file rect.c.
Referenced by create_room(), makelevel(), and makerooms().
{
        return rect_cnt > 0 ? &rect[rn2(rect_cnt)] : 0;
}
void split_rects (NhRect * r1, NhRect * r2)
Definition at line 158 of file rect.c.
References add_rect(), COLNO, nhrect::hx, nhrect::hy, intersect(), nhrect::lx, nhrect::ly, remove_rect(), ROWNO, XLIM, and YLIM.
Referenced by create_room().
{
    NhRect r, old_r;
    int i;
    old_r = *r1;
    remove_rect(r1);
    /* Walk down since rect_cnt & rect[] will change... */
    for (i=rect_cnt-1; i>=0; i--)
        if (intersect(&rect[i], r2, &r))
        split_rects(&rect[i], &r);
    
    if (r2->ly - old_r.ly-1 > (old_r.hy < ROWNO - 1 ? 2*YLIM :
      YLIM+1)+4) {
        r = old_r;
        r.hy = r2->ly - 2;
        add_rect(&r);
    }
    if (r2->lx - old_r.lx-1 > (old_r.hx < COLNO - 1 ? 2*XLIM :
      XLIM+1)+4) {
        r = old_r;
        r.hx = r2->lx - 2;
        add_rect(&r);
    }
    if (old_r.hy - r2->hy-1 > (old_r.ly > 0 ? 2*YLIM : YLIM+1)+4) {
        r = old_r;
        r.ly = r2->hy + 2;
        add_rect(&r);
    }
    if (old_r.hx - r2->hx-1 > (old_r.lx > 0 ? 2*XLIM : XLIM+1)+4) {
        r = old_r;
        r.lx = r2->hx + 2;
        add_rect(&r);
    }
}
Variable Documentation
NhRect rect[MAXRECT+1] [static]
Definition at line 20 of file rect.c.
Referenced by add_rect_to_reg(), ask_enable(), ask_redraw(), DoScrollBar(), FlashButton(), HandleUpdate(), in_topl_mode(), mac_askname(), and topl_resp_rect().
int rect_cnt [static]
Definition at line 21 of file rect.c.
Referenced by add_rect(), get_rect(), get_rect_ind(), and remove_rect().