nethack/src/region.c File Reference
#include `hack.h`
*
#include `lev.h`
*
Macros
#define NO_CALLBACK (-1)
#define INSIDE_GAS_CLOUD 0
#define EXPIRE_GAS_CLOUD 1
Functions
boolean FDECL (inside_gas_cloud,(genericptr, genericptr))
boolean FDECL (expire_gas_cloud,(genericptr, genericptr))
boolean FDECL (inside_rect,(NhRect *, int, int))
boolean FDECL (inside_region,(NhRegion *, int, int))
NhRegion * FDECL (create_region,(NhRect *, int))
void FDECL (add_rect_to_reg,(NhRegion *, NhRect *))
void FDECL (add_mon_to_reg,(NhRegion *, struct monst *))
void FDECL (remove_mon_from_reg,(NhRegion *, struct monst *))
boolean FDECL (mon_in_region,(NhRegion *, struct monst *))
void FDECL (free_region,(NhRegion *))
void FDECL (add_region,(NhRegion *))
void FDECL (remove_region,(NhRegion *))
static void FDECL (reset_region_mids,(NhRegion *))
boolean inside_rect (NhRect *r, int x, int y)
boolean inside_region (NhRegion *reg, int x, int y)
NhRegion * create_region (NhRect *rects, int nrect)
void add_rect_to_reg (NhRegion *reg, NhRect *rect)
void add_mon_to_reg (NhRegion *reg, struct monst *mon)
void remove_mon_from_reg (NhRegion *reg, struct monst *mon)
boolean mon_in_region (NhRegion *reg, struct monst *mon)
void free_region (NhRegion *reg)
void add_region (NhRegion *reg)
void remove_region (NhRegion *reg)
void clear_regions ()
void run_regions ()
boolean in_out_region (xchar x, xchar y)
boolean m_in_out_region (struct monst *mon, xchar x, xchar y)
void update_player_regions ()
void update_monster_region (struct monst *mon)
NhRegion * visible_region_at (xchar x, xchar y)
void show_region (NhRegion *reg, xchar x, xchar y)
void save_regions (int fd, int mode)
void rest_regions (int fd, boolean ghostly)
static void reset_region_mids (NhRegion *reg)
boolean expire_gas_cloud (genericptr_t p1, genericptr_t p2)
boolean inside_gas_cloud (genericptr_t p1, genericptr_t p2)
NhRegion * create_gas_cloud (xchar x, xchar y, int radius, int damage)
Variables
static NhRegion ** regions
static int n_regions = 0
static int max_regions = 0
static callback_proc callbacks []
Macro Definition Documentation
#define EXPIRE_GAS_CLOUD 1
Referenced by create_gas_cloud().
#define INSIDE_GAS_CLOUD 0
Referenced by create_gas_cloud().
#define NO_CALLBACK (-1)
Definition at line 18 of file region.c.
Referenced by create_region(), in_out_region(), m_in_out_region(), and run_regions().
Function Documentation
void add_mon_to_reg (NhRegion * reg, struct monst * mon)
Definition at line 171 of file region.c.
References alloc(), free(), monst::m_id, and MONST_INC.
Referenced by add_region(), m_in_out_region(), and update_monster_region().
{
    int i;
    unsigned *tmp_m;
    if (reg->max_monst <= reg->n_monst) {
    tmp_m = (unsigned *)
            alloc(sizeof (unsigned) * (reg->max_monst + MONST_INC));
    if (reg->max_monst > 0) {
        for (i = 0; i < reg->max_monst; i++)
        tmp_m[i] = reg->monsters[i];
        free((genericptr_t) reg->monsters);
    }
    reg->monsters = tmp_m;
    reg->max_monst += MONST_INC;
    }
    reg->monsters[reg->n_monst++] = mon->m_id;
}
void add_rect_to_reg (NhRegion * reg, NhRect * rect)
Definition at line 141 of file region.c.
References alloc(), free(), nhrect::hx, nhrect::hy, nhrect::lx, nhrect::ly, and rect.
Referenced by create_gas_cloud().
{
    NhRect *tmp_rect;
    tmp_rect = (NhRect *) alloc(sizeof (NhRect) * (reg->nrects + 1));
    if (reg->nrects > 0) {
    (void) memcpy((genericptr_t) tmp_rect, (genericptr_t) reg->
      rects,
              (sizeof (NhRect) * reg->nrects));
    free((genericptr_t) reg->rects);
    }
    tmp_rect[reg->nrects] = *rect;
    reg->nrects++;
    reg->rects = tmp_rect;
    /* Update bounding box if needed */
    if (reg->bounding_box.lx > rect->lx)
    reg->bounding_box.lx = rect->lx;
    if (reg->bounding_box.ly > rect->ly)
    reg->bounding_box.ly = rect->ly;
    if (reg->bounding_box.hx < rect->hx)
    reg->bounding_box.hx = rect->hx;
    if (reg->bounding_box.hy < rect->hy)
    reg->bounding_box.hy = rect->hy;
}
void add_region (NhRegion * reg)
Definition at line 285 of file region.c.
References add_mon_to_reg(), alloc(), cansee, clear_hero_inside, free(), inside_region(), level, max_regions, MON_AT, dlevel_t::monsters, n_regions, newsym(), regions, set_hero_inside, u, you::ux, and you::uy.
Referenced by create_gas_cloud().
{
    NhRegion **tmp_reg;
    int i, j;
    if (max_regions <= n_regions) {
    tmp_reg = regions;
    regions = (NhRegion **)alloc(sizeof (NhRegion *) * (
      max_regions + 10));
    if (max_regions > 0) {
        (void) memcpy((genericptr_t) regions, (genericptr_t) tmp_reg,
              max_regions * sizeof (NhRegion *));
        free((genericptr_t) tmp_reg);
    }
    max_regions += 10;
    }
    regions[n_regions] = reg;
    n_regions++;
    /* Check for monsters inside the region */
    for (i = reg->bounding_box.lx; i <= reg->bounding_box.hx; i++)
    for (j = reg->bounding_box.ly; j <= reg->bounding_box.hy; j++) {
        /* Some regions can cross the level boundaries */
        if (!isok(i,j))
        continue;
        if (MON_AT(i, j) && inside_region(reg, i, j))
        add_mon_to_reg(reg, level.monsters[i][j]);
        if (reg->visible && cansee(i, j))
        newsym(i, j);
    }
    /* Check for player now... */
    if (inside_region(reg, u.ux, u.uy))
    set_hero_inside(reg);
    else
    clear_hero_inside(reg);
}
void clear_regions ()
Definition at line 354 of file region.c.
References free(), free_region(), max_regions, n_regions, and NULL.
Referenced by clear_level_structures(), rest_regions(), and save_regions().
{
    register int i;
    for (i = 0; i < n_regions; i++)
    free_region(regions[i]);
    n_regions = 0;
    if (max_regions > 0)
    free((genericptr_t) regions);
    max_regions = 0;
    regions = NULL;
}
NhRegion* create_gas_cloud (xchar x, xchar y, int radius, int damage)
Definition at line 951 of file region.c.
References add_rect_to_reg(), add_region(), NhRegion::arg, cmap_to_glyph, create_region(), NhRegion::expire_f, EXPIRE_GAS_CLOUD, flags, NhRegion::glyph, nhrect::hx, nhrect::hy, in_mklev, NhRegion::inside_f, INSIDE_GAS_CLOUD, nhrect::lx, nhrect::ly, flag::mon_moving, rn1, S_cloud, set_heros_fault, TRUE, NhRegion::ttl, and NhRegion::visible.
{
    NhRegion *cloud;
    int i, nrect;
    NhRect tmprect;
    cloud = create_region((NhRect *) 0, 0);
    nrect = radius;
    tmprect.lx = x;
    tmprect.hx = x;
    tmprect.ly = y - (radius - 1);
    tmprect.hy = y + (radius - 1);
    for (i = 0; i < nrect; i++) {
    add_rect_to_reg(cloud, &tmprect);
    tmprect.lx--;
    tmprect.hx++;
    tmprect.ly++;
    tmprect.hy--;
    }
    cloud->ttl = rn1(3,4);
    if (!in_mklev && !flags.mon_moving)
    set_heros_fault(cloud); /* assume player has created it */
    cloud->inside_f = INSIDE_GAS_CLOUD;
    cloud->expire_f = EXPIRE_GAS_CLOUD;
    cloud->arg = (genericptr_t) damage;
    cloud->visible = TRUE;
    cloud->glyph = cmap_to_glyph(S_cloud);
    add_region(cloud);
    return cloud;
}
NhRegion* create_region (NhRect * rects, int nrect)
Definition at line 86 of file region.c.
References alloc(), NhRegion::arg, NhRegion::attach_2_m, NhRegion::attach_2_u, NhRegion::bounding_box, NhRegion::can_enter_f, NhRegion::can_leave_f, clear_hero_inside, clear_heros_fault, NhRegion::enter_f, NhRegion::enter_msg, NhRegion::expire_f, FALSE, nhrect::hx, nhrect::hy, NhRegion::inside_f, NhRegion::leave_f, NhRegion::leave_msg, nhrect::lx, nhrect::ly, NhRegion::max_monst, NhRegion::monsters, NhRegion::n_monst, NO_CALLBACK, NhRegion::nrects, NULL, NhRegion::rects, and NhRegion::ttl.
Referenced by create_gas_cloud().
{
    int i;
    NhRegion *reg;
    reg = (NhRegion *) alloc(sizeof (NhRegion));
    /* Determines bounding box */
    if (nrect > 0) {
    reg->bounding_box = rects[0];
    } else {
    reg->bounding_box.lx = 99;
    reg->bounding_box.ly = 99;
    reg->bounding_box.hx = 0;
    reg->bounding_box.hy = 0;
    }
    reg->nrects = nrect;
    reg->rects = nrect > 0 ? (NhRect *)alloc((sizeof (NhRect)) * nrect) :
      NULL;
    for (i = 0; i < nrect; i++) {
    if (rects[i].lx < reg->bounding_box.lx)
        reg->bounding_box.lx = rects[i].lx;
    if (rects[i].ly < reg->bounding_box.ly)
        reg->bounding_box.ly = rects[i].ly;
    if (rects[i].hx > reg->bounding_box.hx)
        reg->bounding_box.hx = rects[i].hx;
    if (rects[i].hy > reg->bounding_box.hy)
        reg->bounding_box.hy = rects[i].hy;
    reg->rects[i] = rects[i];
    }
    reg->ttl = -1; /* Defaults */
    reg->attach_2_u = FALSE;
    reg->attach_2_m = 0;
    /* reg->attach_2_o = NULL; */
    reg->enter_msg = NULL;
    reg->leave_msg = NULL;
    reg->expire_f = NO_CALLBACK;
    reg->enter_f = NO_CALLBACK;
    reg->can_enter_f = NO_CALLBACK;
    reg->leave_f = NO_CALLBACK;
    reg->can_leave_f = NO_CALLBACK;
    reg->inside_f = NO_CALLBACK;
    clear_hero_inside(reg);
    clear_heros_fault(reg);
    reg->n_monst = 0;
    reg->max_monst = 0;
    reg->monsters = NULL;
    reg->arg = NULL;
    return reg;
}
boolean expire_gas_cloud (genericptr_t p1, genericptr_t p2)
Definition at line 876 of file region.c.
References NhRegion::arg, FALSE, TRUE, and NhRegion::ttl.
{
    NhRegion *reg;
    int damage;
    reg = (NhRegion *) p1;
    damage = (int) reg->arg;
    /* If it was a thick cloud, it dissipates a little first */
    if (damage >= 5) {
    damage /= 2; /* It dissipates, let's do less damage */
    reg->arg = (genericptr_t) damage;
    reg->ttl = 2; /* Here's the trick : reset ttl */
    return FALSE; /* THEN return FALSE, means "still there" */
    }
    return TRUE; /* OK, it's gone, you can free it! */
}
boolean FDECL (inside_gas_cloud , (genericptr, genericptr))
boolean FDECL (expire_gas_cloud , (genericptr, genericptr))
boolean FDECL (inside_rect , (NhRect *, int, int))
boolean FDECL (inside_region , (NhRegion *, int, int))
NhRegion* FDECL (create_region , (NhRect *, int))
void FDECL (add_rect_to_reg , (NhRegion *, NhRect *))
void FDECL (add_mon_to_reg , (NhRegion *, struct monst *))
void FDECL (remove_mon_from_reg , (NhRegion *, struct monst *))
boolean FDECL (mon_in_region , (NhRegion *, struct monst *))
void FDECL (free_region , (NhRegion *))
void FDECL (add_region , (NhRegion *))
void FDECL (remove_region , (NhRegion *))
static void FDECL (reset_region_mids , (NhRegion *)) [static]
void free_region (NhRegion * reg)
Definition at line 268 of file region.c.
References free().
Referenced by clear_regions(), and remove_region().
{
    if (reg) {
    if (reg->rects)
        free((genericptr_t) reg->rects);
    if (reg->monsters)
        free((genericptr_t) reg->monsters);
    free((genericptr_t) reg);
    }
}
boolean in_out_region (xchar x, xchar y)
Definition at line 419 of file region.c.
References NhRegion::attach_2_u, clear_hero_inside, FALSE, hero_inside, inside_region(), n_regions, NO_CALLBACK, NULL, set_hero_inside, and TRUE.
Referenced by hurtle_step(), and teleok().
{
    int i, f_indx;
    /* First check if we can do the move */
    for (i = 0; i < n_regions; i++) {
    if (inside_region(regions[i], x, y)
        && !hero_inside(regions[i]) && !regions[i]->attach_2_u) {
        if ((f_indx = regions[i]->can_enter_f) != NO_CALLBACK)
        if (!(*callbacks[f_indx])(regions[i], (genericptr_t) 0))
            return FALSE;
    } else
        if (hero_inside(regions[i])
        && !inside_region(regions[i], x, y)
        && !regions[i]->attach_2_u) {
        if ((f_indx = regions[i]->can_leave_f) != NO_CALLBACK)
        if (!(*callbacks[f_indx])(regions[i], (genericptr_t) 0))
            return FALSE;
    }
    }
    /* Callbacks for the regions we do leave */
    for (i = 0; i < n_regions; i++)
    if (hero_inside(regions[i]) &&
        !regions[i]->attach_2_u && !inside_region(regions[i], x, y)) {
        clear_hero_inside(regions[i]);
        if (regions[i]->leave_msg != NULL)
        pline(regions[i]->leave_msg);
        if ((f_indx = regions[i]->leave_f) != NO_CALLBACK)
        (void) (*callbacks[f_indx])(regions[i], (genericptr_t) 0);
    }
    /* Callbacks for the regions we do enter */
    for (i = 0; i < n_regions; i++)
    if (!hero_inside(regions[i]) &&
        !regions[i]->attach_2_u && inside_region(
      regions[i], x, y)) {
        set_hero_inside(regions[i]);
        if (regions[i]->enter_msg != NULL)
        pline(regions[i]->enter_msg);
        if ((f_indx = regions[i]->enter_f) != NO_CALLBACK)
        (void) (*callbacks[f_indx])(regions[i], (genericptr_t) 0);
    }
    return TRUE;
}
boolean inside_gas_cloud (genericptr_t p1, genericptr_t p2)
Definition at line 897 of file region.c.
References AD_DRST, NhRegion::arg, Blind, breathless, Breathless, cansee, monst::data, FALSE, haseyes, heros_fault, KILLED_BY_AN, LUNG, monst::mhp, monst::mx, monst::my, nonliving, NULL, Poison_resistance, resists_poison, Something, TRUE, and youmonst.
{
    NhRegion *reg;
    struct monst *mtmp;
    int dam;
    reg = (NhRegion *) p1;
    dam = (int) reg->arg;
    if (p2 == NULL) { /* This means *YOU* Bozo! */
    if (nonliving(youmonst.data) || Breathless)
        return FALSE;
    if (!Blind)
        make_blinded(1L, FALSE);
    if (!Poison_resistance) {
        pline("%s is burning your %s!", Something, makeplural(body_part(
      LUNG)));
        You("cough and spit blood!");
        losehp(rnd(dam) + 5, "gas cloud", KILLED_BY_AN);
        return FALSE;
    } else {
        You("cough!");
        return FALSE;
    }
    } else { /* A monster is inside the cloud */
    mtmp = (struct monst *) p2;
    /* Non living and non breathing monsters are not concerned */
    if (!nonliving(mtmp->data) && !breathless(mtmp->data)) {
        if (cansee(mtmp->mx, mtmp->my))
        pline("%s coughs!", Monnam(mtmp));
        setmangry(mtmp);
        if (haseyes(mtmp->data) && mtmp->mcansee) {
        mtmp->mblinded = 1;
        mtmp->mcansee = 0;
        }
        if (resists_poison(mtmp))
        return FALSE;
        mtmp->mhp -= rnd(dam) + 5;
        if (mtmp->mhp <= 0) {
        if (heros_fault(reg))
            killed(mtmp);
        else
            monkilled(mtmp, "gas cloud", AD_DRST);
        if (mtmp->mhp <= 0) { /* not lifesaved */
            return TRUE;
        }
        }
    }
    }
    return FALSE; /* Monster is still alive */
}
boolean inside_rect (NhRect * r, int x, int y)
Definition at line 57 of file region.c.
Referenced by inside_region().
{
    return (x >= r->lx && x <= r->hx && y >= r->ly && y <= r->hy);
}
boolean inside_region (NhRegion * reg, int x, int y)
Definition at line 68 of file region.c.
References FALSE, inside_rect(), NULL, and TRUE.
Referenced by add_region(), in_out_region(), m_in_out_region(), remove_region(), update_monster_region(), update_player_regions(), and visible_region_at().
{
    int i;
    if (reg == NULL || !inside_rect(&(reg->bounding_box), x, y))
    return FALSE;
    for (i = 0; i < reg->nrects; i++)
    if (inside_rect(&(reg->rects[i]), x, y))
        return TRUE;
    return FALSE;
}
boolean m_in_out_region (struct monst * mon, xchar x, xchar y)
Definition at line 470 of file region.c.
References add_mon_to_reg(), NhRegion::attach_2_u, FALSE, hero_inside, inside_region(), mon_in_region(), n_regions, NO_CALLBACK, remove_mon_from_reg(), and TRUE.
Referenced by kickdmg(), and mhurtle_step().
{
    int i, f_indx;
    /* First check if we can do the move */
    for (i = 0; i < n_regions; i++) {
    if (inside_region(regions[i], x, y) &&
        !mon_in_region(regions[i], mon) &&
        regions[i]->attach_2_m != mon->m_id) {
        if ((f_indx = regions[i]->can_enter_f) != NO_CALLBACK)
        if (!(*callbacks[f_indx])(regions[i], mon))
            return FALSE;
    } else if (mon_in_region(regions[i], mon) &&
        !inside_region(regions[i], x, y) &&
        regions[i]->attach_2_m != mon->m_id) {
        if ((f_indx = regions[i]->can_leave_f) != NO_CALLBACK)
        if (!(*callbacks[f_indx])(regions[i], mon))
            return FALSE;
    }
    }
    /* Callbacks for the regions we do leave */
    for (i = 0; i < n_regions; i++)
    if (mon_in_region(regions[i], mon) &&
        regions[i]->attach_2_m != mon->m_id &&
        !inside_region(regions[i], x, y)) {
        remove_mon_from_reg(regions[i], mon);
        if ((f_indx = regions[i]->leave_f) != NO_CALLBACK)
        (void) (*callbacks[f_indx])(regions[i], mon);
    }
    /* Callbacks for the regions we do enter */
    for (i = 0; i < n_regions; i++)
    if (!hero_inside(regions[i]) &&
        !regions[i]->attach_2_u && inside_region(
      regions[i], x, y)) {
        add_mon_to_reg(regions[i], mon);
        if ((f_indx = regions[i]->enter_f) != NO_CALLBACK)
        (void) (*callbacks[f_indx])(regions[i], mon);
    }
    return TRUE;
}
boolean mon_in_region (NhRegion * reg, struct monst * mon)
Definition at line 216 of file region.c.
References FALSE, monst::m_id, and TRUE.
Referenced by m_in_out_region(), and update_monster_region().
{
    int i;
    for (i = 0; i < reg->n_monst; i++)
    if (reg->monsters[i] == mon->m_id)
        return TRUE;
    return FALSE;
}
void remove_mon_from_reg (NhRegion * reg, struct monst * mon)
Definition at line 196 of file region.c.
References monst::m_id.
Referenced by m_in_out_region(), and update_monster_region().
{
    register int i;
    for (i = 0; i < reg->n_monst; i++)
    if (reg->monsters[i] == mon->m_id) {
        reg->n_monst--;
        reg->monsters[i] = reg->monsters[reg->n_monst];
        return;
    }
}
void remove_region (NhRegion * reg)
Definition at line 325 of file region.c.
References cansee, free_region(), inside_region(), n_regions, and newsym().
Referenced by rest_regions(), and run_regions().
{
    register int i, x, y;
    for (i = 0; i < n_regions; i++)
    if (regions[i] == reg)
        break;
    if (i == n_regions)
    return;
    /* Update screen if necessary */
    if (reg->visible)
    for (x = reg->bounding_box.lx; x <= reg->bounding_box.hx; x++)
        for (y = reg->bounding_box.ly; y <= reg->bounding_box.hy; y++)
        if (isok(x,y) && inside_region(reg, x, y) && cansee(x, y))
            newsym(x, y);
    free_region(reg);
    regions[i] = regions[n_regions - 1];
    regions[n_regions - 1] = (NhRegion *) 0;
    n_regions--;
}
static void reset_region_mids (NhRegion * reg) [static]
Definition at line 754 of file region.c.
References lookup_id_mapping(), and NhRegion::n_monst.
Referenced by rest_regions().
{
    int i = 0, n = reg->n_monst;
    unsigned *mid_list = reg->monsters;
    while (i < n)
    if (!lookup_id_mapping(mid_list[i], &mid_list[i])) {
        /* shrink list to remove missing monster; order doesn't matter */
        mid_list[i] = mid_list[--n];
    } else {
        /* move on to next monster */
        ++i;
    }
    reg->n_monst = n;
    return;
}
void rest_regions (int fd, boolean ghostly)
Definition at line 665 of file region.c.
References alloc(), clear_hero_inside, clear_heros_fault, clear_regions(), NhRegion::enter_msg, NhRegion::leave_msg, NhRegion::max_monst, max_regions, NhRegion::monsters, moves, mread(), NhRegion::n_monst, n_regions, NhRegion::nrects, NULL, NhRegion::rects, remove_region(), reset_region_mids(), and NhRegion::ttl.
Referenced by getlev().
{
    int i, j;
    unsigned n;
    long tmstamp;
    char *msg_buf;
    clear_regions(); /* Just for security */
    mread(fd, (genericptr_t) &tmstamp, sizeof (tmstamp));
    if (ghostly) tmstamp = 0;
    else tmstamp = (moves - tmstamp);
    mread(fd, (genericptr_t) &n_regions, sizeof (n_regions));
    max_regions = n_regions;
    if (n_regions > 0)
    regions = (NhRegion **) alloc(sizeof (NhRegion *) *
      n_regions);
    for (i = 0; i < n_regions; i++) {
    regions[i] = (NhRegion *) alloc(sizeof (NhRegion));
    mread(fd, (genericptr_t) &regions[i]->bounding_box, sizeof (
      NhRect));
    mread(fd, (genericptr_t) &regions[i]->nrects, sizeof (short));
    if (regions[i]->nrects > 0)
        regions[i]->rects = (NhRect *)
                  alloc(sizeof (NhRect) * regions[i]->nrects);
    for (j = 0; j < regions[i]->nrects; j++)
        mread(fd, (genericptr_t) &regions[i]->rects[j], sizeof (
      NhRect));
    mread(fd, (genericptr_t) &regions[i]->attach_2_u, sizeof (boolean));
    mread(fd, (genericptr_t) &regions[i]->attach_2_m, sizeof (unsigned));
    mread(fd, (genericptr_t) &n, sizeof n);
    if (n > 0) {
        msg_buf = (char *) alloc(n + 1);
        mread(fd, (genericptr_t) msg_buf, n);
        msg_buf[n] = '\0';
        regions[i]->enter_msg = (const char *) msg_buf;
    } else
        regions[i]->enter_msg = NULL;
    mread(fd, (genericptr_t) &n, sizeof n);
    if (n > 0) {
        msg_buf = (char *) alloc(n + 1);
        mread(fd, (genericptr_t) msg_buf, n);
        msg_buf[n] = '\0';
        regions[i]->leave_msg = (const char *) msg_buf;
    } else
        regions[i]->leave_msg = NULL;
    mread(fd, (genericptr_t) &regions[i]->ttl, sizeof (short));
    /* check for expired region */
    if (regions[i]->ttl >= 0)
        regions[i]->ttl =
        (regions[i]->ttl > tmstamp) ? regions[i]->ttl - tmstamp : 0;
    mread(fd, (genericptr_t) &regions[i]->expire_f, sizeof (short));
    mread(fd, (genericptr_t) &regions[i]->can_enter_f, sizeof (short));
    mread(fd, (genericptr_t) &regions[i]->enter_f, sizeof (short));
    mread(fd, (genericptr_t) &regions[i]->can_leave_f, sizeof (short));
    mread(fd, (genericptr_t) &regions[i]->leave_f, sizeof (short));
    mread(fd, (genericptr_t) &regions[i]->inside_f, sizeof (short));
    mread(fd, (genericptr_t) &regions[i]->player_flags, sizeof (boolean));
    if (ghostly) { /* settings pertained to old player */
        clear_hero_inside(regions[i]);
        clear_heros_fault(regions[i]);
    }
    mread(fd, (genericptr_t) &regions[i]->n_monst, sizeof (short));
    if (regions[i]->n_monst > 0)
        regions[i]->monsters =
        (unsigned *) alloc(sizeof (unsigned) * regions[i]->n_monst);
    else
        regions[i]->monsters = NULL;
    regions[i]->max_monst = regions[i]->n_monst;
    for (j = 0; j < regions[i]->n_monst; j++)
        mread(fd, (genericptr_t) &regions[i]->monsters[j],
          sizeof (unsigned));
    mread(fd, (genericptr_t) &regions[i]->visible, sizeof (boolean));
    mread(fd, (genericptr_t) &regions[i]->glyph, sizeof (int));
    mread(fd, (genericptr_t) &regions[i]->arg, sizeof (
      genericptr_t));
    }
    /* remove expired regions, do not trigger the expire_f callback (yet!);
       also update monster lists if this data is coming from a bones file */
    for (i = n_regions - 1; i >= 0; i--)
    if (regions[i]->ttl == 0)
        remove_region(regions[i]);
    else if (ghostly && regions[i]->n_monst > 0)
        reset_region_mids(regions[i]);
}
void run_regions ()
Definition at line 373 of file region.c.
References FM_FMON, hero_inside, NhRegion::inside_f, monst::mhp, NhRegion::monsters, NhRegion::n_monst, n_regions, NO_CALLBACK, remove_region(), and NhRegion::ttl.
{
    register int i, j, k;
    int f_indx;
    /* End of life ? */
    /* Do it backward because the array will be modified */
    for (i = n_regions - 1; i >= 0; i--) {
    if (regions[i]->ttl == 0) {
        if ((f_indx = regions[i]->expire_f) == NO_CALLBACK ||
        (*callbacks[f_indx])(regions[i], (genericptr_t) 0))
        remove_region(regions[i]);
    }
    }
    /* Process remaining regions */
    for (i = 0; i < n_regions; i++) {
    /* Make the region age */
    if (regions[i]->ttl > 0)
        regions[i]->ttl--;
    /* Check if player is inside region */
    f_indx = regions[i]->inside_f;
    if (f_indx != NO_CALLBACK && hero_inside(regions[i]))
        (void) (*callbacks[f_indx])(regions[i], (genericptr_t) 0);
    /* Check if any monster is inside region */
    if (f_indx != NO_CALLBACK) {
        for (j = 0; j < regions[i]->n_monst; j++) {
        struct monst *mtmp = find_mid(regions[i]->monsters[j],
      FM_FMON);
        if (!mtmp || mtmp->mhp <= 0 ||
                (*callbacks[f_indx])(regions[i], mtmp)) {
            /* The monster died, remove it from list */
            k = (regions[i]->n_monst -= 1);
            regions[i]->monsters[j] = regions[i]->monsters[k];
            regions[i]->monsters[k] = 0;
            --j; /* current slot has been reused; recheck it next */
        }
        }
    }
    }
}
void save_regions (int fd, int mode)
save_regions :
Definition at line 615 of file region.c.
References bwrite(), clear_regions(), NhRegion::enter_msg, NhRegion::leave_msg, moves, NhRegion::n_monst, n_regions, NhRegion::nrects, NULL, perform_bwrite, and release_data.
Referenced by savelev().
{
    int i, j;
    unsigned n;
    if (!perform_bwrite(mode)) goto skip_lots;
    bwrite(fd, (genericptr_t) &moves, sizeof (moves)); /* timestamp */
    bwrite(fd, (genericptr_t) &n_regions, sizeof (n_regions));
    for (i = 0; i < n_regions; i++) {
    bwrite(fd, (genericptr_t) &regions[i]->bounding_box, sizeof (
      NhRect));
    bwrite(fd, (genericptr_t) &regions[i]->nrects, sizeof (short));
    for (j = 0; j < regions[i]->nrects; j++)
        bwrite(fd, (genericptr_t) &regions[i]->rects[j], sizeof (
      NhRect));
    bwrite(fd, (genericptr_t) &regions[i]->attach_2_u, sizeof (boolean));
    n = 0;
    bwrite(fd, (genericptr_t) &regions[i]->attach_2_m, sizeof (unsigned));
    n = regions[i]->enter_msg != NULL ? strlen(regions[i]->enter_msg) : 0;
    bwrite(fd, (genericptr_t) &n, sizeof n);
    if (n > 0)
        bwrite(fd, (genericptr_t) regions[i]->enter_msg, n);
    n = regions[i]->leave_msg != NULL ? strlen(regions[i]->leave_msg) : 0;
    bwrite(fd, (genericptr_t) &n, sizeof n);
    if (n > 0)
        bwrite(fd, (genericptr_t) regions[i]->leave_msg, n);
    bwrite(fd, (genericptr_t) &regions[i]->ttl, sizeof (short));
    bwrite(fd, (genericptr_t) &regions[i]->expire_f, sizeof (short));
    bwrite(fd, (genericptr_t) &regions[i]->can_enter_f, sizeof (short));
    bwrite(fd, (genericptr_t) &regions[i]->enter_f, sizeof (short));
    bwrite(fd, (genericptr_t) &regions[i]->can_leave_f, sizeof (short));
    bwrite(fd, (genericptr_t) &regions[i]->leave_f, sizeof (short));
    bwrite(fd, (genericptr_t) &regions[i]->inside_f, sizeof (short));
    bwrite(fd, (genericptr_t) &regions[i]->player_flags, sizeof (boolean));
    bwrite(fd, (genericptr_t) &regions[i]->n_monst, sizeof (short));
    for (j = 0; j < regions[i]->n_monst; j++)
        bwrite(fd, (genericptr_t) &regions[i]->monsters[j],
         sizeof (unsigned));
    bwrite(fd, (genericptr_t) &regions[i]->visible, sizeof (boolean));
    bwrite(fd, (genericptr_t) &regions[i]->glyph, sizeof (int));
    bwrite(fd, (genericptr_t) &regions[i]->arg, sizeof (
      genericptr_t));
    }
skip_lots:
    if (release_data(mode))
    clear_regions();
}
void show_region (NhRegion * reg, xchar x, xchar y)
Definition at line 604 of file region.c.
References show_glyph().
Referenced by newsym().
{
    show_glyph(x, y, reg->glyph);
}
void update_monster_region (struct monst * mon)
Definition at line 533 of file region.c.
References add_mon_to_reg(), inside_region(), mon_in_region(), n_regions, and remove_mon_from_reg().
Referenced by rloc_to().
{
    register int i;
    for (i = 0; i < n_regions; i++) {
    if (inside_region(regions[i], mon->mx, mon->my)) {
        if (!mon_in_region(regions[i], mon))
        add_mon_to_reg(regions[i], mon);
    } else {
        if (mon_in_region(regions[i], mon))
        remove_mon_from_reg(regions[i], mon);
    }
    }
}
void update_player_regions ()
Definition at line 518 of file region.c.
References clear_hero_inside, inside_region(), n_regions, set_hero_inside, u, you::ux, and you::uy.
Referenced by teleds().
{
    register int i;
    for (i = 0; i < n_regions; i++)
    if (!regions[i]->attach_2_u && inside_region(regions[i],
      u.ux, u.uy))
        set_hero_inside(regions[i]);
    else
        clear_hero_inside(regions[i]);
}
NhRegion* visible_region_at (xchar x, xchar y)
Definition at line 591 of file region.c.
References inside_region(), and n_regions.
Referenced by newsym().
{
    register int i;
    for (i = 0; i < n_regions; i++)
    if (inside_region(regions[i], x, y) && regions[i]->visible &&
        regions[i]->ttl != 0)
        return regions[i];
    return (NhRegion *) 0;
}
Variable Documentation
callback_proc callbacks[] [static]
Initial value:
= {
#define INSIDE_GAS_CLOUD
    inside_gas_cloud,
#define EXPIRE_GAS_CLOUD
    expire_gas_cloud
}
Definition at line 48 of file region.c.
int max_regions = 0 [static]
Definition at line 16 of file region.c.
Referenced by add_region(), clear_regions(), and rest_regions().
int n_regions = 0 [static]
Definition at line 15 of file region.c.
Referenced by add_region(), clear_regions(), in_out_region(), m_in_out_region(), remove_region(), rest_regions(), run_regions(), save_regions(), update_monster_region(), update_player_regions(), and visible_region_at().
NhRegion** regions [static]
Definition at line 14 of file region.c.
Referenced by add_region(), and store_part().