nethack/src/role.c File Reference
#include `hack.h`
*
Macros
#define BP_ALIGN 0
#define BP_GEND 1
#define BP_RACE 2
#define BP_ROLE 3
#define NUM_BP 4
Functions
STATIC_DCL char * FDECL (promptsep,(char *, int))
STATIC_DCL int FDECL (role_gendercount,(int))
STATIC_DCL int FDECL (race_alignmentcount,(int))
boolean validrole (int rolenum)
int randrole ()
int str2role (char *str)
boolean validrace (int rolenum, int racenum)
int randrace (int rolenum)
int str2race (char *str)
boolean validgend (int rolenum, int racenum, int gendnum)
int randgend (int rolenum, int racenum)
int str2gend (char *str)
boolean validalign (int rolenum, int racenum, int alignnum)
int randalign (int rolenum, int racenum)
int str2align (char *str)
boolean ok_role (int rolenum, int racenum, int gendnum, int alignnum)
int pick_role (int racenum, int gendnum, int alignnum, int pickhow)
boolean ok_race (int rolenum, int racenum, int gendnum, int alignnum)
int pick_race (int rolenum, int gendnum, int alignnum, int pickhow)
boolean ok_gend (int rolenum, int racenum, int gendnum, int alignnum)
int pick_gend (int rolenum, int racenum, int alignnum, int pickhow)
boolean ok_align (int rolenum, int racenum, int gendnum, int alignnum)
int pick_align (int rolenum, int racenum, int gendnum, int pickhow)
void rigid_role_checks ()
STATIC_OVL char * promptsep (char *buf, int num_post_attribs)
STATIC_OVL int role_gendercount (int rolenum)
STATIC_OVL int race_alignmentcount (int racenum)
char * root_plselection_prompt (char *suppliedbuf, int buflen, int rolenum, int racenum, int gendnum, int alignnum)
char * build_plselection_prompt (char *buf, int buflen, int rolenum, int racenum, int gendnum, int alignnum)
void plnamesuffix ()
void role_init ()
const char * Hello (struct monst *mtmp)
const char * Goodbye ()
Variables
const struct Role roles []
struct Role urole
const struct Race races []
struct Race urace
const struct Gender genders []
const struct Align aligns []
static char NEARDATA randomstr [] = `random`
STATIC_VAR char pa [NUM_BP]
STATIC_VAR char post_attribs
Macro Definition Documentation
#define BP_ALIGN 0
Definition at line 1047 of file role.c.
Referenced by build_plselection_prompt(), and root_plselection_prompt().
#define BP_GEND 1
Definition at line 1048 of file role.c.
Referenced by build_plselection_prompt(), and root_plselection_prompt().
#define BP_RACE 2
Definition at line 1049 of file role.c.
Referenced by build_plselection_prompt(), and root_plselection_prompt().
#define BP_ROLE 3
Definition at line 1050 of file role.c.
Referenced by build_plselection_prompt(), and root_plselection_prompt().
#define NUM_BP 4
Definition at line 1051 of file role.c.
Referenced by root_plselection_prompt().
Function Documentation
char* build_plselection_prompt (char * buf, int buflen, int rolenum, int racenum, int gendnum, int alignnum)
Definition at line 1232 of file role.c.
References BP_ALIGN, BP_GEND, BP_RACE, BP_ROLE, buf, BUFSZ, eos(), post_attribs, promptsep(), QBUFSZ, ROLE_NONE, root_plselection_prompt(), Sprintf, Strcat, Strcpy, and validrole().
Referenced by prompt_for_player_selection().
{
    const char *defprompt = "Shall I pick a character for you? [ynq] ";
    int num_post_attribs = 0;
    char tmpbuf[BUFSZ];
    
    if (buflen < QBUFSZ)
        return (char *)defprompt;
    Strcpy(tmpbuf, "Shall I pick ");
    if (racenum != ROLE_NONE || validrole(rolenum))
        Strcat(tmpbuf, "your ");
    else {
        Strcat(tmpbuf, "a ");
    }
    /* <your> */
    (void) root_plselection_prompt(eos(tmpbuf), buflen - strlen(tmpbuf),
                    rolenum, racenum, gendnum, alignnum);
    Sprintf(buf, "%s", s_suffix(tmpbuf));
    /* buf should now be:
     * < your lawful female gnomish cavewoman's> || <your lawful female gnome's>
     * || <your lawful female character's>
     *
         * Now append the post attributes to it
     */
    num_post_attribs = post_attribs;
    if (post_attribs) {
        if (pa[BP_RACE]) {
            (void) promptsep(eos(buf), num_post_attribs);
            Strcat(buf, "race");
        }
        if (pa[BP_ROLE]) {
            (void) promptsep(eos(buf), num_post_attribs);
            Strcat(buf, "role");
        }
        if (pa[BP_GEND]) {
            (void) promptsep(eos(buf), num_post_attribs);
            Strcat(buf, "gender");
        }
        if (pa[BP_ALIGN]) {
            (void) promptsep(eos(buf), num_post_attribs);
            Strcat(buf, "alignment");
        }
    }
    Strcat(buf, " for you? [ynq] ");
    return buf;
}
STATIC_DCL char* FDECL (promptsep , (char *, int))
STATIC_DCL int FDECL (role_gendercount , (int))
STATIC_DCL int FDECL (race_alignmentcount , (int))
const char* Goodbye ()
Definition at line 1473 of file role.c.
References Role_switch.
Referenced by done(), and losexp().
{
    switch (Role_switch) {
    case PM_KNIGHT:
        return ("Fare thee well"); /* Olde English */
    case PM_SAMURAI:
        return ("Sayonara"); /* Japanese */
#ifdef TOURIST
    case PM_TOURIST:
        return ("Aloha"); /* Hawaiian */
#endif
    case PM_VALKYRIE:
        return ("Farvel"); /* Norse */
    default:
        return ("Goodbye");
    }
}
const char* Hello (struct monst * mtmp)
Definition at line 1448 of file role.c.
References MAIL, mons, and Role_switch.
{
    switch (Role_switch) {
    case PM_KNIGHT:
        return ("Salutations"); /* Olde English */
    case PM_SAMURAI:
        return (mtmp && mtmp->data == &mons[PM_SHOPKEEPER] ?
                "Irasshaimase" : "Konnichi wa"); /* Japanese */
#ifdef TOURIST
    case PM_TOURIST:
        return ("Aloha"); /* Hawaiian */
#endif
    case PM_VALKYRIE:
        return (
#ifdef MAIL
                mtmp && mtmp->data == &mons[PM_MAIL_DAEMON] ? "Hallo" :
#endif
                "Velkommen"); /* Norse */
    default:
        return ("Hello");
    }
}
boolean ok_align (int rolenum, int racenum, int gendnum, int alignnum)
Definition at line 954 of file role.c.
References Race::allow, Align::allow, FALSE, ROLE_ALIGNMASK, ROLE_ALIGNS, SIZE, and TRUE.
Referenced by gnome_player_selection(), pick_align(), plselAdjustLists(), plselInitDialog(), prompt_for_player_selection(), and X11_player_selection().
{
    int i;
    short allow;
    if (alignnum >= 0 && alignnum < ROLE_ALIGNS) {
    allow = aligns[alignnum].allow;
    if (rolenum >= 0 && rolenum < SIZE(roles)-1 &&
        !(allow & roles[rolenum].allow & ROLE_ALIGNMASK))
        return FALSE;
    if (racenum >= 0 && racenum < SIZE(races)-1 &&
        !(allow & races[racenum].allow & ROLE_ALIGNMASK))
        return FALSE;
    return TRUE;
    } else {
    for (i = 0; i < ROLE_ALIGNS; i++) {
        allow = races[i].allow;
        if (rolenum >= 0 && rolenum < SIZE(roles)-1 &&
            !(allow & roles[rolenum].allow & ROLE_ALIGNMASK))
        continue;
        if (racenum >= 0 && racenum < SIZE(races)-1 &&
            !(allow & races[racenum].allow & ROLE_ALIGNMASK))
        continue;
        return TRUE;
    }
    return FALSE;
    }
}
boolean ok_gend (int rolenum, int racenum, int gendnum, int alignnum)
Definition at line 892 of file role.c.
References Gender::allow, Align::allow, FALSE, ROLE_GENDERS, ROLE_GENDMASK, SIZE, and TRUE.
Referenced by gnome_player_selection(), pick_gend(), plselAdjustLists(), plselInitDialog(), prompt_for_player_selection(), and X11_player_selection().
{
    int i;
    short allow;
    if (gendnum >= 0 && gendnum < ROLE_GENDERS) {
    allow = genders[gendnum].allow;
    if (rolenum >= 0 && rolenum < SIZE(roles)-1 &&
        !(allow & roles[rolenum].allow & ROLE_GENDMASK))
        return FALSE;
    if (racenum >= 0 && racenum < SIZE(races)-1 &&
        !(allow & races[racenum].allow & ROLE_GENDMASK))
        return FALSE;
    return TRUE;
    } else {
    for (i = 0; i < ROLE_GENDERS; i++) {
        allow = genders[i].allow;
        if (rolenum >= 0 && rolenum < SIZE(roles)-1 &&
            !(allow & roles[rolenum].allow & ROLE_GENDMASK))
        continue;
        if (racenum >= 0 && racenum < SIZE(races)-1 &&
            !(allow & races[racenum].allow & ROLE_GENDMASK))
        continue;
        return TRUE;
    }
    return FALSE;
    }
}
boolean ok_race (int rolenum, int racenum, int gendnum, int alignnum)
Definition at line 825 of file role.c.
References Role::allow, Race::allow, Align::allow, FALSE, ROLE_ALIGNMASK, ROLE_ALIGNS, ROLE_GENDERS, ROLE_GENDMASK, ROLE_RACEMASK, SIZE, and TRUE.
Referenced by gnome_player_selection(), pick_race(), plselAdjustLists(), plselInitDialog(), prompt_for_player_selection(), root_plselection_prompt(), and X11_player_selection().
{
    int i;
    short allow;
    if (racenum >= 0 && racenum < SIZE(races)-1) {
    allow = races[racenum].allow;
    if (rolenum >= 0 && rolenum < SIZE(roles)-1 &&
        !(allow & roles[rolenum].allow & ROLE_RACEMASK))
        return FALSE;
    if (gendnum >= 0 && gendnum < ROLE_GENDERS &&
        !(allow & genders[gendnum].allow & ROLE_GENDMASK))
        return FALSE;
    if (alignnum >= 0 && alignnum < ROLE_ALIGNS &&
        !(allow & aligns[alignnum].allow & ROLE_ALIGNMASK))
        return FALSE;
    return TRUE;
    } else {
    for (i = 0; i < SIZE(races)-1; i++) {
        allow = races[i].allow;
        if (rolenum >= 0 && rolenum < SIZE(roles)-1 &&
            !(allow & roles[rolenum].allow & ROLE_RACEMASK))
        continue;
        if (gendnum >= 0 && gendnum < ROLE_GENDERS &&
            !(allow & genders[gendnum].allow & ROLE_GENDMASK))
        continue;
        if (alignnum >= 0 && alignnum < ROLE_ALIGNS &&
            !(allow & aligns[alignnum].allow & ROLE_ALIGNMASK))
        continue;
        return TRUE;
    }
    return FALSE;
    }
}
boolean ok_role (int rolenum, int racenum, int gendnum, int alignnum)
Definition at line 759 of file role.c.
References Role::allow, Race::allow, Align::allow, FALSE, ROLE_ALIGNMASK, ROLE_ALIGNS, ROLE_GENDERS, ROLE_GENDMASK, ROLE_RACEMASK, SIZE, and TRUE.
Referenced by gnome_player_selection(), pick_role(), plselAdjustLists(), plselInitDialog(), prompt_for_player_selection(), and X11_player_selection().
{
    int i;
    short allow;
    if (rolenum >= 0 && rolenum < SIZE(roles)-1) {
    allow = roles[rolenum].allow;
    if (racenum >= 0 && racenum < SIZE(races)-1 &&
        !(allow & races[racenum].allow & ROLE_RACEMASK))
        return FALSE;
    if (gendnum >= 0 && gendnum < ROLE_GENDERS &&
        !(allow & genders[gendnum].allow & ROLE_GENDMASK))
        return FALSE;
    if (alignnum >= 0 && alignnum < ROLE_ALIGNS &&
        !(allow & aligns[alignnum].allow & ROLE_ALIGNMASK))
        return FALSE;
    return TRUE;
    } else {
    for (i = 0; i < SIZE(roles)-1; i++) {
        allow = roles[i].allow;
        if (racenum >= 0 && racenum < SIZE(races)-1 &&
            !(allow & races[racenum].allow & ROLE_RACEMASK))
        continue;
        if (gendnum >= 0 && gendnum < ROLE_GENDERS &&
            !(allow & genders[gendnum].allow & ROLE_GENDMASK))
        continue;
        if (alignnum >= 0 && alignnum < ROLE_ALIGNS &&
            !(allow & aligns[alignnum].allow & ROLE_ALIGNMASK))
        continue;
        return TRUE;
    }
    return FALSE;
    }
}
int pick_align (int rolenum, int racenum, int gendnum, int pickhow)
Definition at line 989 of file role.c.
References ok_align(), PICK_RIGID, ROLE_ALIGNS, and ROLE_NONE.
Referenced by gnome_player_selection(), mswin_player_selection(), plselFinalSelection(), prompt_for_player_selection(), rigid_role_checks(), and X11_player_selection().
{
    int i;
    int aligns_ok = 0;
    for (i = 0; i < ROLE_ALIGNS; i++) {
    if (ok_align(rolenum, racenum, gendnum, i))
        aligns_ok++;
    }
    if (aligns_ok == 0 || (aligns_ok > 1 && pickhow == PICK_RIGID))
    return ROLE_NONE;
    aligns_ok = rn2(aligns_ok);
    for (i = 0; i < ROLE_ALIGNS; i++) {
    if (ok_align(rolenum, racenum, gendnum, i)) {
        if (aligns_ok == 0)
        return i;
        else
        aligns_ok--;
    }
    }
    return ROLE_NONE;
}
int pick_gend (int rolenum, int racenum, int alignnum, int pickhow)
Definition at line 927 of file role.c.
References ok_gend(), PICK_RIGID, ROLE_GENDERS, and ROLE_NONE.
Referenced by gnome_player_selection(), mswin_player_selection(), plselFinalSelection(), prompt_for_player_selection(), rigid_role_checks(), and X11_player_selection().
{
    int i;
    int gends_ok = 0;
    for (i = 0; i < ROLE_GENDERS; i++) {
    if (ok_gend(rolenum, racenum, i, alignnum))
        gends_ok++;
    }
    if (gends_ok == 0 || (gends_ok > 1 && pickhow == PICK_RIGID))
    return ROLE_NONE;
    gends_ok = rn2(gends_ok);
    for (i = 0; i < ROLE_GENDERS; i++) {
    if (ok_gend(rolenum, racenum, i, alignnum)) {
        if (gends_ok == 0)
        return i;
        else
        gends_ok--;
    }
    }
    return ROLE_NONE;
}
int pick_race (int rolenum, int gendnum, int alignnum, int pickhow)
Definition at line 865 of file role.c.
References ok_race(), PICK_RIGID, ROLE_NONE, and SIZE.
Referenced by gnome_player_selection(), mswin_player_selection(), plselFinalSelection(), prompt_for_player_selection(), rigid_role_checks(), and X11_player_selection().
{
    int i;
    int races_ok = 0;
    for (i = 0; i < SIZE(races)-1; i++) {
    if (ok_race(rolenum, i, gendnum, alignnum))
        races_ok++;
    }
    if (races_ok == 0 || (races_ok > 1 && pickhow == PICK_RIGID))
    return ROLE_NONE;
    races_ok = rn2(races_ok);
    for (i = 0; i < SIZE(races)-1; i++) {
    if (ok_race(rolenum, i, gendnum, alignnum)) {
        if (races_ok == 0)
        return i;
        else
        races_ok--;
    }
    }
    return ROLE_NONE;
}
int pick_role (int racenum, int gendnum, int alignnum, int pickhow)
Definition at line 799 of file role.c.
References ok_role(), PICK_RIGID, ROLE_NONE, and SIZE.
Referenced by gnome_player_selection(), mswin_player_selection(), plselFinalSelection(), prompt_for_player_selection(), rigid_role_checks(), and X11_player_selection().
{
    int i;
    int roles_ok = 0;
    for (i = 0; i < SIZE(roles)-1; i++) {
    if (ok_role(i, racenum, gendnum, alignnum))
        roles_ok++;
    }
    if (roles_ok == 0 || (roles_ok > 1 && pickhow == PICK_RIGID))
    return ROLE_NONE;
    roles_ok = rn2(roles_ok);
    for (i = 0; i < SIZE(roles)-1; i++) {
    if (ok_role(i, racenum, gendnum, alignnum)) {
        if (roles_ok == 0)
        return i;
        else
        roles_ok--;
    }
    }
    return ROLE_NONE;
}
void plnamesuffix ()
Definition at line 1292 of file role.c.
References askname, flags, index(), flag::initalign, flag::initgend, flag::initrace, flag::initrole, plname, ROLE_NONE, str2align(), str2gend(), str2race(), and str2role().
Referenced by MAIN(), main(), parse_config_line(), and role_init().
{
    char *sptr, *eptr;
    int i;
    /* Look for tokens delimited by '-' */
    if ((eptr = index(plname, '-')) != (char *) 0)
        *eptr++ = '\0';
    while (eptr) {
        /* Isolate the next token */
        sptr = eptr;
        if ((eptr = index(sptr, '-')) != (char *)0)
        *eptr++ = '\0';
        /* Try to match it to something */
        if ((i = str2role(sptr)) != ROLE_NONE)
        flags.initrole = i;
        else if ((i = str2race(sptr)) != ROLE_NONE)
        flags.initrace = i;
        else if ((i = str2gend(sptr)) != ROLE_NONE)
        flags.initgend = i;
        else if ((i = str2align(sptr)) != ROLE_NONE)
        flags.initalign = i;
    }
    if(!plname[0]) {
        askname();
        plnamesuffix();
    }
    /* commas in the plname confuse the record file, convert to spaces */
    for (sptr = plname; *sptr; sptr++) {
        if (*sptr == ',') *sptr = ' ';
    }
}
STATIC_OVL char* promptsep (char * buf, int num_post_attribs)
Definition at line 1056 of file role.c.
References buf, post_attribs, and Strcat.
Referenced by build_plselection_prompt().
{
    const char *conj = "and ";
    if (num_post_attribs > 1
        && post_attribs < num_post_attribs && post_attribs > 1)
        Strcat(buf, ",");
    Strcat(buf, " ");
    --post_attribs;
    if (!post_attribs && num_post_attribs > 1) Strcat(buf, conj);
    return buf;
}
STATIC_OVL int race_alignmentcount (int racenum)
Definition at line 1084 of file role.c.
References Align::allow, ROLE_CHAOTIC, ROLE_LAWFUL, ROLE_NEUTRAL, ROLE_NONE, and ROLE_RANDOM.
Referenced by root_plselection_prompt().
{
    int aligncount = 0;
    if (racenum != ROLE_NONE && racenum != ROLE_RANDOM) {
        if (races[racenum].allow & ROLE_CHAOTIC) ++aligncount;
        if (races[racenum].allow & ROLE_LAWFUL) ++aligncount;
        if (races[racenum].allow & ROLE_NEUTRAL) ++aligncount;
    }
    return aligncount;
}
int randalign (int rolenum, int racenum)
Definition at line 704 of file role.c.
References Align::allow, ROLE_ALIGNMASK, and ROLE_ALIGNS.
Referenced by gnome_player_selection(), mac_askname(), mswin_player_selection(), prompt_for_player_selection(), and role_init().
{
    int i, n = 0;
    /* Count the number of valid alignments */
    for (i = 0; i < ROLE_ALIGNS; i++)
        if (roles[rolenum].allow & races[racenum].allow &
                aligns[i].allow & ROLE_ALIGNMASK)
            n++;
    /* Pick a random alignment */
    if (n) n = rn2(n);
    for (i = 0; i < ROLE_ALIGNS; i++)
        if (roles[rolenum].allow & races[racenum].allow &
                aligns[i].allow & ROLE_ALIGNMASK) {
            if (n) n--;
            else return (i);
        }
    /* This role/race has no permitted alignments? */
    return (rn2(ROLE_ALIGNS));
}
int randgend (int rolenum, int racenum)
Definition at line 638 of file role.c.
References Align::allow, ROLE_GENDERS, and ROLE_GENDMASK.
Referenced by gnome_player_selection(), mac_askname(), mswin_player_selection(), and prompt_for_player_selection().
{
    int i, n = 0;
    /* Count the number of valid genders */
    for (i = 0; i < ROLE_GENDERS; i++)
        if (roles[rolenum].allow & races[racenum].allow &
                genders[i].allow & ROLE_GENDMASK)
            n++;
    /* Pick a random gender */
    if (n) n = rn2(n);
    for (i = 0; i < ROLE_GENDERS; i++)
        if (roles[rolenum].allow & races[racenum].allow &
                genders[i].allow & ROLE_GENDMASK) {
            if (n) n--;
            else return (i);
        }
    /* This role/race has no permitted genders? */
    return (rn2(ROLE_GENDERS));
}
int randrace (int rolenum)
Definition at line 572 of file role.c.
References Align::allow, Race::noun, ROLE_RACEMASK, and SIZE.
Referenced by gnome_player_selection(), mac_askname(), mswin_player_selection(), prompt_for_player_selection(), and role_init().
{
    int i, n = 0;
    /* Count the number of valid races */
    for (i = 0; races[i].noun; i++)
        if (roles[rolenum].allow & races[i].allow & ROLE_RACEMASK)
            n++;
    /* Pick a random race */
    /* Use a factor of 100 in case of bad random number generators */
    if (n) n = rn2(n*100)/100;
    for (i = 0; races[i].noun; i++)
        if (roles[rolenum].allow & races[i].allow & ROLE_RACEMASK) {
            if (n) n--;
            else return (i);
        }
    /* This role has no permitted races? */
    return (rn2(SIZE(races)-1));
}
int randrole ()
Definition at line 522 of file role.c.
References SIZE.
Referenced by gnome_player_selection(), halu_gname(), mac_askname(), mswin_player_selection(), prompt_for_player_selection(), rigid_role_checks(), and role_init().
{
    return (rn2(SIZE(roles)-1));
}
void rigid_role_checks ()
Definition at line 1014 of file role.c.
References flags, flag::initalign, flag::initgend, flag::initrace, flag::initrole, pick_align(), pick_gend(), pick_race(), PICK_RANDOM, PICK_RIGID, pick_role(), randrole(), ROLE_NONE, and ROLE_RANDOM.
Referenced by gnome_player_selection(), prompt_for_player_selection(), and X11_player_selection().
{
    /* Some roles are limited to a single race, alignment, or gender and
     * calling this routine prior to XXX_player_selection() will help
     * prevent an extraneous prompt that actually doesn't allow
     * you to choose anything further. Note the use of PICK_RIGID which
     * causes the pick_XX() routine to return a value only if there is one
     * single possible selection, otherwise it returns ROLE_NONE.
     *
     */
    if (flags.initrole == ROLE_RANDOM) {
    /* If the role was explicitly specified as ROLE_RANDOM
     * via -uXXXX-@ then choose the role in here to narrow down
     * later choices. Pick a random role in this case.
     */
    flags.initrole = pick_role(flags.initrace,
      flags.initgend,
                    flags.initalign, PICK_RANDOM);
    if (flags.initrole < 0)
        flags.initrole = randrole();
    }
    if (flags.initrole != ROLE_NONE) {
    if (flags.initrace == ROLE_NONE)
         flags.initrace = pick_race(flags.initrole,
      flags.initgend,
                        flags.initalign, PICK_RIGID);
    if (flags.initalign == ROLE_NONE)
         flags.initalign = pick_align(flags.
      initrole, flags.initrace,
                        flags.initgend, PICK_RIGID);
    if (flags.initgend == ROLE_NONE)
         flags.initgend = pick_gend(flags.initrole,
      flags.initrace,
                        flags.initalign, PICK_RIGID);
    }
}
STATIC_OVL int role_gendercount (int rolenum)
Definition at line 1071 of file role.c.
References Align::allow, ROLE_FEMALE, ROLE_MALE, ROLE_NEUTER, and validrole().
Referenced by root_plselection_prompt().
{
    int gendcount = 0;
    if (validrole(rolenum)) {
        if (roles[rolenum].allow & ROLE_MALE) ++gendcount;
        if (roles[rolenum].allow & ROLE_FEMALE) ++gendcount;
        if (roles[rolenum].allow & ROLE_NEUTER) ++gendcount;
    }
    return gendcount;
}
void role_init ()
Definition at line 1345 of file role.c.
References Role::cgod, flag::female, Role::femalenum, flags, Role::guardnum, flag::initalign, flag::initgend, flag::initrace, flag::initrole, Role::ldrnum, Role::lgod, RoleName::m, M2_HOSTILE, M2_NASTY, M2_PEACEFUL, M2_STALK, M3_CLOSE, M3_INFRAVISION, M3_WAITFORU, M3_WANTSARTI, Role::malenum, Race::malenum, permonst::maligntyp, permonst::mflags2, permonst::mflags3, mons, MS_LEADER, MS_NEMESIS, permonst::msound, Role::name, Role::neminum, Role::ngod, NON_PM, flag::pantheon, pl_character, PL_CSIZ, plnamesuffix(), randalign(), randrace(), randrole(), str2role(), Strcpy, validalign(), validgend(), validrace(), validrole(), and Align::value.
Referenced by restgamestate().
{
    int alignmnt;
    /* Strip the role letter out of the player name.
     * This is included for backwards compatibility.
     */
    plnamesuffix();
    /* Check for a valid role. Try flags.initrole first. */
    if (!validrole(flags.initrole)) {
        /* Try the player letter second */
        if ((flags.initrole = str2role(pl_character)) < 0)
            /* None specified; pick a random role */
            flags.initrole = randrole();
    }
    /* We now have a valid role index. Copy the role name back. */
    /* This should become OBSOLETE */
    Strcpy(pl_character, roles[flags.initrole].
      name.m);
    pl_character[PL_CSIZ-1] = '\0';
    /* Check for a valid race */
    if (!validrace(flags.initrole, flags.initrace))
        flags.initrace = randrace(flags.initrole);
    /* Check for a valid gender. If new game, check both initgend
     * and female. On restore, assume flags.female is correct. */
    if (flags.pantheon == -1) { /* new game */
        if (!validgend(flags.initrole, flags.initrace,
      flags.female))
        flags.female = !flags.female;
    }
    if (!validgend(flags.initrole, flags.initrace,
      flags.initgend))
        /* Note that there is no way to check for an unspecified gender. */
        flags.initgend = flags.female;
    /* Check for a valid alignment */
    if (!validalign(flags.initrole, flags.initrace,
      flags.initalign))
        /* Pick a random alignment */
        flags.initalign = randalign(flags.initrole,
      flags.initrace);
    alignmnt = aligns[flags.initalign].value;
    /* Initialize urole and urace */
    urole = roles[flags.initrole];
    urace = races[flags.initrace];
    /* Fix up the quest leader */
    if (urole.ldrnum != NON_PM) {
        mons[urole.ldrnum].msound = MS_LEADER;
        mons[urole.ldrnum].mflags2 |= (M2_PEACEFUL);
        mons[urole.ldrnum].mflags3 |= M3_CLOSE;
        mons[urole.ldrnum].maligntyp = alignmnt * 3;
    }
    /* Fix up the quest guardians */
    if (urole.guardnum != NON_PM) {
        mons[urole.guardnum].mflags2 |= (M2_PEACEFUL);
        mons[urole.guardnum].maligntyp = alignmnt * 3;
    }
    /* Fix up the quest nemesis */
    if (urole.neminum != NON_PM) {
        mons[urole.neminum].msound = MS_NEMESIS;
        mons[urole.neminum].mflags2 &= ~(M2_PEACEFUL);
        mons[urole.neminum].mflags2 |= (M2_NASTY|
      M2_STALK|M2_HOSTILE);
        mons[urole.neminum].mflags3 |= M3_WANTSARTI |
      M3_WAITFORU;
    }
    /* Fix up the god names */
    if (flags.pantheon == -1) { /* new game */
        flags.pantheon = flags.initrole; /* use own gods */
        while (!roles[flags.pantheon].lgod) /* unless they're missing */
        flags.pantheon = randrole();
    }
    if (!urole.lgod) {
        urole.lgod = roles[flags.pantheon].lgod;
        urole.ngod = roles[flags.pantheon].ngod;
        urole.cgod = roles[flags.pantheon].cgod;
    }
    /* Fix up infravision */
    if (mons[urace.malenum].mflags3 & M3_INFRAVISION) {
        /* although an infravision intrinsic is possible, infravision
         * is purely a property of the physical race. This means that we
         * must put the infravision flag in the player's current race
         * (either that or have separate permonst entries for
         * elven/non-elven members of each class). The side effect is that
         * all NPCs of that class will have (probably bogus) infravision,
         * but since infravision has no effect for NPCs anyway we can
         * ignore this.
         */
        mons[urole.malenum].mflags3 |= M3_INFRAVISION;
        if (urole.femalenum != NON_PM)
            mons[urole.femalenum].mflags3 |=
      M3_INFRAVISION;
    }
    /* Artifacts are fixed in hack_artifacts() */
    /* Success! */
    return;
}
char* root_plselection_prompt (char * suppliedbuf, int buflen, int rolenum, int racenum, int gendnum, int alignnum)
Definition at line 1097 of file role.c.
References Align::adj, BP_ALIGN, BP_GEND, BP_RACE, BP_ROLE, buf, BUFSZ, FALSE, name, Align::noun, NUM_BP, ok_race(), race_alignmentcount(), role_gendercount(), ROLE_NONE, ROLE_RANDOM, Strcat, Strcpy, TRUE, and validrole().
Referenced by build_plselection_prompt(), prompt_for_player_selection(), and X11_player_selection().
{
    int k, gendercount = 0, aligncount = 0;
    char buf[BUFSZ];
    static char err_ret[] = " character's";
    boolean donefirst = FALSE;
    if (!suppliedbuf || buflen < 1) return err_ret;
    /* initialize these static variables each time this is called */
    post_attribs = 0;
    for (k=0; k < NUM_BP; ++k)
        pa[k] = 0;
    buf[0] = '\0';
    *suppliedbuf = '\0';
    
    /* How many alignments are allowed for the desired race? */
    if (racenum != ROLE_NONE && racenum != ROLE_RANDOM)
        aligncount = race_alignmentcount(racenum);
    if (alignnum != ROLE_NONE && alignnum != ROLE_RANDOM) {
        /* if race specified, and multiple choice of alignments for it */
        if ((racenum >= 0) && (aligncount > 1)) {
            if (donefirst) Strcat(buf, " ");
            Strcat(buf, aligns[alignnum].adj);
            donefirst = TRUE;
        } else {
            if (donefirst) Strcat(buf, " ");
            Strcat(buf, aligns[alignnum].adj);
            donefirst = TRUE;
        }
    } else {
        /* if alignment not specified, but race is specified
            and only one choice of alignment for that race then
            don't include it in the later list */
        if ((((racenum != ROLE_NONE && racenum != ROLE_RANDOM) &&
            ok_race(rolenum, racenum, gendnum, alignnum))
              && (aligncount > 1))
             || (racenum == ROLE_NONE || racenum == ROLE_RANDOM)) {
            pa[BP_ALIGN] = 1;
            post_attribs++;
        }
    }
    /* <your lawful> */
    /* How many genders are allowed for the desired role? */
    if (validrole(rolenum))
        gendercount = role_gendercount(rolenum);
    if (gendnum != ROLE_NONE && gendnum != ROLE_RANDOM) {
        if (validrole(rolenum)) {
             /* if role specified, and multiple choice of genders for it,
            and name of role itself does not distinguish gender */
            if ((rolenum != ROLE_NONE) && (gendercount > 1)
                        && !roles[rolenum].name.f) {
                if (donefirst) Strcat(buf, " ");
                Strcat(buf, genders[gendnum].adj);
                donefirst = TRUE;
            }
            } else {
            if (donefirst) Strcat(buf, " ");
                Strcat(buf, genders[gendnum].adj);
            donefirst = TRUE;
            }
    } else {
        /* if gender not specified, but role is specified
            and only one choice of gender then
            don't include it in the later list */
        if ((validrole(rolenum) && (gendercount > 1)) || !validrole(rolenum)) {
            pa[BP_GEND] = 1;
            post_attribs++;
        }
    }
    /* <your lawful female> */
    if (racenum != ROLE_NONE && racenum != ROLE_RANDOM) {
        if (validrole(rolenum) && ok_race(rolenum, racenum, gendnum, alignnum)) {
            if (donefirst) Strcat(buf, " ");
            Strcat(buf, (rolenum == ROLE_NONE) ?
                races[racenum].noun :
                races[racenum].adj);
            donefirst = TRUE;
        } else if (!validrole(rolenum)) {
            if (donefirst) Strcat(buf, " ");
            Strcat(buf, races[racenum].noun);
            donefirst = TRUE;
        } else {
            pa[BP_RACE] = 1;
            post_attribs++;
        }
    } else {
        pa[BP_RACE] = 1;
        post_attribs++;
    }
    /* <your lawful female gnomish> || <your lawful female gnome> */
    if (validrole(rolenum)) {
        if (donefirst) Strcat(buf, " ");
        if (gendnum != ROLE_NONE) {
            if (gendnum == 1 && roles[rolenum].name.f)
            Strcat(buf, roles[rolenum].name.f);
            else
            Strcat(buf, roles[rolenum].name.m);
        } else {
            if (roles[rolenum].name.f) {
                Strcat(buf, roles[rolenum].name.m);
                Strcat(buf, "/");
                Strcat(buf, roles[rolenum].name.f);
            } else
                Strcat(buf, roles[rolenum].name.m);
        }
        donefirst = TRUE;
    } else if (rolenum == ROLE_NONE) {
        pa[BP_ROLE] = 1;
        post_attribs++;
    }
    
    if ((racenum == ROLE_NONE || racenum == ROLE_RANDOM) && !
      validrole(rolenum)) {
        if (donefirst) Strcat(buf, " ");
        Strcat(buf, "character");
        donefirst = TRUE;
    }
    /* <your lawful female gnomish cavewoman> || <your lawful female gnome>
     * || <your lawful female character>
     */
    if (buflen > (int) (strlen(buf) + 1)) {
        Strcpy(suppliedbuf, buf);
        return suppliedbuf;
    } else
        return err_ret;
}
int str2align (char * str)
Definition at line 730 of file role.c.
References Align::adj, Align::filecode, ROLE_ALIGNS, ROLE_NONE, ROLE_RANDOM, strcmpi, and strncmpi().
Referenced by parseoptions(), and plnamesuffix().
{
    int i, len;
    /* Is str valid? */
    if (!str || !str[0])
        return ROLE_NONE;
    /* Match as much of str as is provided */
    len = strlen(str);
    for (i = 0; i < ROLE_ALIGNS; i++) {
        /* Does it match the adjective? */
        if (!strncmpi(str, aligns[i].adj, len))
        return i;
        /* Or the filecode? */
        if (!strcmpi(str, aligns[i].filecode))
        return i;
    }
    if ((len == 1 && (*str == '*' || *str == '@')) ||
        !strncmpi(str, randomstr, len))
        return ROLE_RANDOM;
    /* Couldn't find anything appropriate */
    return ROLE_NONE;
}
int str2gend (char * str)
Definition at line 664 of file role.c.
References Align::adj, Align::filecode, ROLE_GENDERS, ROLE_NONE, ROLE_RANDOM, strcmpi, and strncmpi().
Referenced by parseoptions(), and plnamesuffix().
{
    int i, len;
    /* Is str valid? */
    if (!str || !str[0])
        return ROLE_NONE;
    /* Match as much of str as is provided */
    len = strlen(str);
    for (i = 0; i < ROLE_GENDERS; i++) {
        /* Does it match the adjective? */
        if (!strncmpi(str, genders[i].adj, len))
        return i;
        /* Or the filecode? */
        if (!strcmpi(str, genders[i].filecode))
        return i;
    }
    if ((len == 1 && (*str == '*' || *str == '@')) ||
        !strncmpi(str, randomstr, len))
        return ROLE_RANDOM;
    /* Couldn't find anything appropriate */
    return ROLE_NONE;
}
int str2race (char * str)
Definition at line 597 of file role.c.
References Align::filecode, Race::noun, Align::noun, ROLE_NONE, ROLE_RANDOM, strcmpi, and strncmpi().
Referenced by parseoptions(), plnamesuffix(), process_options(), and score_wanted().
{
    int i, len;
    /* Is str valid? */
    if (!str || !str[0])
        return ROLE_NONE;
    /* Match as much of str as is provided */
    len = strlen(str);
    for (i = 0; races[i].noun; i++) {
        /* Does it match the noun? */
        if (!strncmpi(str, races[i].noun, len))
        return i;
        /* Or the filecode? */
        if (!strcmpi(str, races[i].filecode))
        return i;
    }
    if ((len == 1 && (*str == '*' || *str == '@')) ||
        !strncmpi(str, randomstr, len))
        return ROLE_RANDOM;
    /* Couldn't find anything appropriate */
    return ROLE_NONE;
}
int str2role (char * str)
Definition at line 529 of file role.c.
References Align::filecode, RoleName::m, Role::name, name, ROLE_NONE, ROLE_RANDOM, strcmpi, and strncmpi().
Referenced by mac_askname(), parse_config_line(), parseoptions(), plnamesuffix(), process_options(), readentry(), role_init(), and score_wanted().
{
    int i, len;
    /* Is str valid? */
    if (!str || !str[0])
        return ROLE_NONE;
    /* Match as much of str as is provided */
    len = strlen(str);
    for (i = 0; roles[i].name.m; i++) {
        /* Does it match the male name? */
        if (!strncmpi(str, roles[i].name.m, len))
        return i;
        /* Or the female name? */
        if (roles[i].name.f && !strncmpi(str, roles[i].
      name.f, len))
        return i;
        /* Or the filecode? */
        if (!strcmpi(str, roles[i].filecode))
        return i;
    }
    if ((len == 1 && (*str == '*' || *str == '@')) ||
        !strncmpi(str, randomstr, len))
        return ROLE_RANDOM;
    /* Couldn't find anything appropriate */
    return ROLE_NONE;
}
boolean validalign (int rolenum, int racenum, int alignnum)
Definition at line 693 of file role.c.
References Align::allow, ROLE_ALIGNMASK, and ROLE_ALIGNS.
Referenced by gnome_player_selection(), mac_askname(), mswin_player_selection(), plselFinalSelection(), plselInitDialog(), prompt_for_player_selection(), role_init(), and X11_player_selection().
{
    /* Assumes validrole and validrace */
    return (alignnum >= 0 && alignnum < ROLE_ALIGNS &&
        (roles[rolenum].allow & races[racenum].allow &
         aligns[alignnum].allow & ROLE_ALIGNMASK));
}
boolean validgend (int rolenum, int racenum, int gendnum)
Definition at line 627 of file role.c.
References Align::allow, ROLE_GENDERS, and ROLE_GENDMASK.
Referenced by gnome_player_selection(), mac_askname(), mswin_player_selection(), plselFinalSelection(), plselInitDialog(), prompt_for_player_selection(), role_init(), and X11_player_selection().
{
    /* Assumes validrole and validrace */
    return (gendnum >= 0 && gendnum < ROLE_GENDERS &&
        (roles[rolenum].allow & races[racenum].allow &
         genders[gendnum].allow & ROLE_GENDMASK));
}
boolean validrace (int rolenum, int racenum)
Definition at line 562 of file role.c.
References Align::allow, ROLE_RACEMASK, and SIZE.
Referenced by gnome_player_selection(), mac_askname(), mswin_player_selection(), plselFinalSelection(), plselInitDialog(), prompt_for_player_selection(), role_init(), and X11_player_selection().
{
    /* Assumes validrole */
    return (racenum >= 0 && racenum < SIZE(races)-1 &&
        (roles[rolenum].allow & races[racenum].allow & ROLE_RACEMASK));
}
boolean validrole (int rolenum)
Definition at line 514 of file role.c.
References SIZE.
Referenced by build_plselection_prompt(), role_gendercount(), role_init(), and root_plselection_prompt().
{
    return (rolenum >= 0 && rolenum < SIZE(roles)-1);
}
Variable Documentation
const struct Align aligns[]
Initial value:
= {
    {"law", "lawful", "Law", ROLE_LAWFUL, A_LAWFUL},
    {"balance", "neutral", "Neu", ROLE_NEUTRAL, A_NEUTRAL},
    {"chaos", "chaotic", "Cha", ROLE_CHAOTIC, A_CHAOTIC},
    {"evil", "unaligned", "Una", 0, A_NONE}
}
Definition at line 498 of file role.c.
Referenced by ask_redraw(), get_compopt_value(), gnome_player_selection(), mac_askname(), plselAdjustLists(), prompt_for_player_selection(), topten(), u_init(), and X11_player_selection().
const struct Gender genders[]
Initial value:
= {
    {"male", "he", "him", "his", "Mal", ROLE_MALE},
    {"female", "she", "her", "her", "Fem", ROLE_FEMALE},
    {"neuter", "it", "it", "its", "Ntr", ROLE_NEUTER}
}
Definition at line 490 of file role.c.
Referenced by ask_redraw(), get_compopt_value(), gnome_player_selection(), mac_askname(), plselAdjustLists(), prompt_for_player_selection(), topten(), and X11_player_selection().
STATIC_VAR char pa[NUM_BP]
Definition at line 1053 of file role.c.
STATIC_VAR char post_attribs
Definition at line 1053 of file role.c.
Referenced by build_plselection_prompt(), and promptsep().
const struct Race races[]
Definition at line 406 of file role.c.
Referenced by ask_redraw(), get_compopt_value(), gnome_player_selection(), mac_askname(), plselAdjustLists(), prompt_for_player_selection(), race_key(), and X11_player_selection().
char NEARDATA randomstr[] = `random` [static]
Definition at line 510 of file role.c.
const struct Role roles[]
Definition at line 27 of file role.c.
Referenced by ask_redraw(), classmon(), get_compopt_value(), gnome_player_selection(), halu_gname(), mac_askname(), player_sel_key_hit(), plselAdjustLists(), prompt_for_player_selection(), ps_key(), readentry(), and X11_player_selection().
struct Race urace
Initial value:
=
{ "something", "undefined", "something", "Xxx",
    {0, 0},
    NON_PM, NON_PM, NON_PM, NON_PM,
    0, 0, 0, 0,
    
    { 3, 3, 3, 3, 3, 3 },
    { STR18(100), 18, 18, 18, 18, 18 },
    
    { 2, 0, 0, 2, 1, 0 },
    { 1, 0, 2, 0, 2, 0 }
}
Definition at line 475 of file role.c.
Referenced by done(), done_in_by(), dosacrifice(), ini_inv(), load_qtlist(), lookat(), losexp(), pluslvl(), topten(), and u_init().
struct Role urole
Initial value:
=
{ {"Undefined", 0}, { {0, 0}, {0, 0}, {0, 0},
    {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0} },
    "L", "N", "C", "Xxx", "home", "locate",
    NON_PM, NON_PM, NON_PM, NON_PM, NON_PM, NON_PM,
    NON_PM, NON_PM, 0, 0, 0, 0,
    
    { 7, 7, 7, 7, 7, 7 },
    { 20, 15, 15, 20, 20, 10 },
    
    { 10, 0, 0, 8, 1, 0 },
    { 2, 0, 0, 2, 0, 3 },14,
    0, 10, 0, 0, 4, A_INT, 0, -3
}
Definition at line 388 of file role.c.
Referenced by align_gname(), align_gtitle(), can_twoweapon(), convert_arg(), done(), find_roll_to_hit(), guardname(), homebase(), intermed(), is_quest_artifact(), ldrname(), load_qtlist(), losexp(), makelevel(), mplayer_talk(), neminame(), percent_success(), pluslvl(), qt_montype(), quest_info(), set_bonesfile_name(), topten(), and u_init().