nethack/src/save.c File Reference
#include `hack.h`
*
#include `lev.h`
*
#include `quest.h`
*
#include <signal.h>
*
#include <fcntl.h>
*
Macros
#define nulls nul
#define HUP
Functions
STATIC_DCL void FDECL (savelevchn,(int, int))
STATIC_DCL void FDECL (savedamage,(int, int))
STATIC_DCL void FDECL (saveobjchn,(int, struct obj *, int))
STATIC_DCL void FDECL (savemonchn,(int, struct monst *, int))
STATIC_DCL void FDECL (savetrapchn,(int, struct trap *, int))
STATIC_DCL void FDECL (savegamestate,(int, int))
int dosave ()
int dosave0 ()
STATIC_OVL void savegamestate (int fd, int mode)
void savelev (int fd, xchar lev, int mode)
void bufon (int fd)
void bufoff (int fd)
void bflush (int fd)
void bwrite (int fd, genericptr_t loc, unsigned num)
void bclose (int fd)
STATIC_OVL void savelevchn (int fd, int mode)
STATIC_OVL void savedamage (int fd, int mode)
STATIC_OVL void saveobjchn (int fd, struct obj *otmp, int mode)
STATIC_OVL void savemonchn (int fd, struct monst *mtmp, int mode)
STATIC_OVL void savetrapchn (int fd, struct trap *trap, int mode)
void savefruitchn (int fd, int mode)
void free_dungeons ()
void freedynamicdata ()
Variables
static unsigned ustuck_id = 0
static unsigned usteed_id = 0
static int bw_fd = -1
static FILE * bw_FILE = 0
static boolean buffering = FALSE
Macro Definition Documentation
#define HUP
Definition at line 48 of file save.c.
Referenced by dosave0().
#define nulls nul
Definition at line 42 of file save.c.
Function Documentation
void bclose (int fd)
Definition at line 775 of file save.c.
References bufoff(), and close().
Referenced by dosave0(), restlevelfile(), and savebones().
{
    bufoff(fd);
#ifdef UNIX
    if (fd == bw_fd) {
    (void) fclose(bw_FILE);
    bw_fd = -1;
    bw_FILE = 0;
    } else
#endif
    (void) close(fd);
    return;
}
void bflush (int fd)
Definition at line 722 of file save.c.
References panic().
Referenced by bufoff(), savebones(), savegamestate(), and savelev().
{
#ifdef UNIX
    if(fd == bw_fd) {
    if(fflush(bw_FILE) == EOF)
        panic("flush of savefile failed!");
    }
#endif
    return;
}
void bufoff (int fd)
Definition at line 714 of file save.c.
References bflush(), and FALSE.
Referenced by bclose(), and store_version().
{
    bflush(fd);
    buffering = FALSE;
}
void bufon (int fd)
Definition at line 700 of file save.c.
References panic(), and TRUE.
Referenced by restlevelfile(), and store_version().
{
#ifdef UNIX
    if(bw_fd >= 0)
    panic("double buffering unexpected");
    bw_fd = fd;
    if((bw_FILE = fdopen(fd, "w")) == 0)
    panic("buffering of file %d failed", fd);
#endif
    buffering = TRUE;
}
void bwrite (int fd, genericptr_t loc, unsigned num)
Definition at line 735 of file save.c.
References EXIT_FAILURE, panic(), program_state, terminate(), and write().
Referenced by dosave0(), save_oracles(), save_regions(), save_waterlevel(), save_worm(), savebones(), savedamage(), savefruitchn(), savegamestate(), savelev(), savelevchn(), savemonchn(), savenames(), saveobjchn(), savetrapchn(), and store_version().
{
    boolean failed;
#ifdef MFLOPPY
    bytes_counted += num;
    if (count_only) return;
#endif
#ifdef UNIX
    if (buffering) {
        if(fd != bw_fd)
        panic("unbuffered write to fd %d (!= %d)", fd, bw_fd);
        failed = (fwrite(loc, (int)num, 1, bw_FILE) != 1);
    } else
#endif /* UNIX */
    {
/* lint wants the 3rd arg of write to be an int; lint -p an unsigned */
#if defined(BSD) || defined(ULTRIX)
        failed = (write(fd, loc, (int)num) != (int)num);
#else /* e.g. SYSV, __TURBOC__ */
        failed = (write(fd, loc, num) != num);
#endif
    }
    if (failed) {
#if defined(UNIX) || defined(VMS) || defined(__EMX__)
        if (program_state.done_hup)
        terminate(EXIT_FAILURE);
        else
#endif
        panic("cannot write %u bytes to file #%d", num, fd);
    }
}
int dosave ()
Definition at line 55 of file save.c.
References clear_nhwindow, display_nhwindow, doredraw(), dosave0(), exit_nhwindows, EXIT_SUCCESS, multi, program_state, sinfo::something_worth_saving, terminate(), TRUE, u, you::uhp, WIN_MESSAGE, and yn.
Referenced by MainWndProc(), and onWMCommand().
{
    clear_nhwindow(WIN_MESSAGE);
    if(yn("Really save?") == 'n') {
        clear_nhwindow(WIN_MESSAGE);
        if(multi > 0) nomul(0);
    } else {
        clear_nhwindow(WIN_MESSAGE);
        pline("Saving...");
#if defined(UNIX) || defined(VMS) || defined(__EMX__)
        program_state.done_hup = 0;
#endif
        if(dosave0()) {
            program_state.something_worth_saving = 0;
            u.uhp = -1; /* universal game's over indicator */
            /* make sure they see the Saving message */
            display_nhwindow(WIN_MESSAGE, TRUE);
            exit_nhwindows("Be seeing you...");
            terminate(EXIT_SUCCESS);
        } else (void)doredraw();
    }
    return 0;
}
int dosave0 ()
Definition at line 113 of file save.c.
References bclose(), BUFSZ, bwrite(), clear_nhwindow, close(), COLNO, compress(), COUNT_SAVE, create_savefile(), curs, delete_levelfile(), delete_savefile(), d_level::dlevel, d_level::dnum, done, FALSE, flags, flushout(), fqname(), FREE_SAVE, flag::friday13, FULL_MOON, getlev(), hackpid, HUP, iflags, killer, level_info, LFILE_EXISTS, monst::m_id, mark_synch, minit(), flag::moonphase, window_procs::name, open_levelfile(), open_savefile(), PL_NSIZ, plname, putstr, SAVEF, savegamestate(), savelev(), SAVEPREFIX, store_version(), strncmpi(), TRICKED, u, uncompress(), usteed_id, you::ustuck, you::uz, vision_recalc(), WIN_MAP, WIN_MESSAGE, instance_flags::window_inited, windowprocs, WRITE_SAVE, and yn.
Referenced by dosave(), ghack_save_game(), and MainWndProc().
{
    const char *fq_save;
    register int fd, ofd;
    xchar ltmp;
    d_level uz_save;
    char whynot[BUFSZ];
    if (!SAVEF[0])
        return 0;
    fq_save = fqname(SAVEF, SAVEPREFIX, 1); /* level files take 0 */
#if defined(UNIX) || defined(VMS)
    (void) signal(SIGHUP, SIG_IGN);
#endif
#ifndef NO_SIGNAL
    (void) signal(SIGINT, SIG_IGN);
#endif
#if defined(MICRO) && defined(MFLOPPY)
    if (!saveDiskPrompt(0)) return 0;
#endif
    HUP if (iflags.window_inited) {
        uncompress(fq_save);
        fd = open_savefile();
        if (fd > 0) {
        (void) close(fd);
        clear_nhwindow(WIN_MESSAGE);
        There("seems to be an old save file.");
        if (yn("Overwrite the old file?") == 'n') {
            compress(fq_save);
            return 0;
        }
        }
    }
    HUP mark_synch(); /* flush any buffered screen output */
    fd = create_savefile();
    if(fd < 0) {
        HUP pline("Cannot open save file.");
        (void) delete_savefile(); /* ab@unido */
        return(0);
    }
    vision_recalc(2); /* shut down vision to prevent problems
                   in the event of an impossible() call */
    
    /* undo date-dependent luck adjustments made at startup time */
    if(flags.moonphase == FULL_MOON) /* ut-sally!fletcher */
        change_luck(-1); /* and unido!ab */
    if(flags.friday13)
        change_luck(1);
    if(iflags.window_inited)
        HUP clear_nhwindow(WIN_MESSAGE);
#ifdef MICRO
    dotcnt = 0;
    dotrow = 2;
    curs(WIN_MAP, 1, 1);
    if (strncmpi("X11", windowprocs.name, 3))
      putstr(WIN_MAP, 0, "Saving:");
#endif
#ifdef MFLOPPY
    /* make sure there is enough disk space */
    if (iflags.checkspace) {
        long fds, needed;
        savelev(fd, ledger_no(&u.uz), COUNT_SAVE);
        savegamestate(fd, COUNT_SAVE);
        needed = bytes_counted;
        for (ltmp = 1; ltmp <= maxledgerno(); ltmp++)
        if (ltmp != ledger_no(&u.uz) && level_info[ltmp].where)
            needed += level_info[ltmp].size + (sizeof ltmp);
        fds = freediskspace(fq_save);
        if (needed > fds) {
        HUP {
            There("is insufficient space on SAVE disk.");
            pline("Require %ld bytes but only have %ld.", needed, fds);
        }
        flushout();
        (void) close(fd);
        (void) delete_savefile();
        return 0;
        }
        co_false();
    }
#endif /* MFLOPPY */
    store_version(fd);
#ifdef STORE_PLNAME_IN_FILE
    bwrite(fd, (genericptr_t) plname, PL_NSIZ);
#endif
    ustuck_id = (u.ustuck ? u.ustuck->m_id : 0);
#ifdef STEED
    usteed_id = (u.usteed ? u.usteed->m_id : 0);
#endif
    savelev(fd, ledger_no(&u.uz), WRITE_SAVE | FREE_SAVE);
    savegamestate(fd, WRITE_SAVE | FREE_SAVE);
    /* While copying level files around, zero out u.uz to keep
     * parts of the restore code from completely initializing all
     * in-core data structures, since all we're doing is copying.
     * This also avoids at least one nasty core dump.
     */
    uz_save = u.uz;
    u.uz.dnum = u.uz.dlevel = 0;
    /* these pointers are no longer valid, and at least u.usteed
     * may mislead place_monster() on other levels
     */
    u.ustuck = (struct monst *)0;
#ifdef STEED
    u.usteed = (struct monst *)0;
#endif
    for(ltmp = (xchar)1; ltmp <= maxledgerno(); ltmp++) {
        if (ltmp == ledger_no(&uz_save)) continue;
        if (!(level_info[ltmp].flags & LFILE_EXISTS)) continue;
#ifdef MICRO
        curs(WIN_MAP, 1 + dotcnt++, dotrow);
        if (dotcnt >= (COLNO - 1)) {
            dotrow++;
            dotcnt = 0;
        }
        if (strncmpi("X11", windowprocs.name, 3)){
          putstr(WIN_MAP, 0, ".");
        }
        mark_synch();
#endif
        ofd = open_levelfile(ltmp, whynot);
        if (ofd < 0) {
            HUP pline("%s", whynot);
            (void) close(fd);
            (void) delete_savefile();
            HUP killer = whynot;
            HUP done(TRICKED);
            return(0);
        }
        minit(); /* ZEROCOMP */
        getlev(ofd, hackpid, ltmp, FALSE);
        (void) close(ofd);
        bwrite(fd, (genericptr_t) &ltmp, sizeof ltmp); /* level number*/
        savelev(fd, ltmp, WRITE_SAVE | FREE_SAVE); /* actual level*/
        delete_levelfile(ltmp);
    }
    bclose(fd);
    u.uz = uz_save;
    /* get rid of current level --jgm */
    delete_levelfile(ledger_no(&u.uz));
    delete_levelfile(0);
    compress(fq_save);
    return(1);
}
STATIC_DCL void FDECL (savelevchn , (int, int))
STATIC_DCL void FDECL (savedamage , (int, int))
STATIC_DCL void FDECL (saveobjchn , (int, struct obj *, int))
STATIC_DCL void FDECL (savemonchn , (int, struct monst *, int))
STATIC_DCL void FDECL (savetrapchn , (int, struct trap *, int))
STATIC_DCL void FDECL (savegamestate , (int, int))
void free_dungeons ()
Definition at line 947 of file save.c.
References FALSE, FREE_SAVE, savelevchn(), and TRUE.
Referenced by freedynamicdata(), and prscore().
{
#ifdef FREE_ALL_MEMORY
    savelevchn(0, FREE_SAVE);
    save_dungeon(0, FALSE, TRUE);
#endif
    return;
}
void freedynamicdata ()
Definition at line 957 of file save.c.
References billobjs, dlevel_t::buriedobjlist, DISP_FREEMEM, fmon, fobj, free(), free_dungeons(), freefruitchn(), ftrap, iflags, invent, level, migrating_mons, migrating_objs, mydogs, RANGE_GLOBAL, RANGE_LEVEL, tmp_at(), unload_qtlist(), instance_flags::wc_font_map, instance_flags::wc_font_menu, instance_flags::wc_font_message, instance_flags::wc_font_status, instance_flags::wc_font_text, and instance_flags::wc_tile_file.
Referenced by terminate().
{
    unload_qtlist();
    free_invbuf(); /* let_to_name (invent.c) */
    free_youbuf(); /* You_buf,&c (pline.c) */
    tmp_at(DISP_FREEMEM, 0); /* temporary display effects */
#ifdef FREE_ALL_MEMORY
# define freeobjchn(X) (saveobjchn(0, X, FREE_SAVE), X = 0)
# define freemonchn(X) (savemonchn(0, X, FREE_SAVE), X = 0)
# define freetrapchn(X) (savetrapchn(0, X, FREE_SAVE), X = 0)
# define freefruitchn() savefruitchn(0, FREE_SAVE)
# define freenames() savenames(0, FREE_SAVE)
# define free_oracles() save_oracles(0, FREE_SAVE)
# define free_waterlevel() save_waterlevel(0, FREE_SAVE)
# define free_worm() save_worm(0, FREE_SAVE)
# define free_timers(R) save_timers(0, FREE_SAVE, R)
# define free_light_sources(R) save_light_sources(0, FREE_SAVE, R);
# define free_engravings() save_engravings(0, FREE_SAVE)
# define freedamage() savedamage(0, FREE_SAVE)
# define free_animals() mon_animal_list(FALSE)
    /* move-specific data */
    dmonsfree(); /* release dead monsters */
    /* level-specific data */
    free_timers(RANGE_LEVEL);
    free_light_sources(RANGE_LEVEL);
    freemonchn(fmon);
    free_worm(); /* release worm segment information */
    freetrapchn(ftrap);
    freeobjchn(fobj);
    freeobjchn(level.buriedobjlist);
    freeobjchn(billobjs);
    free_engravings();
    freedamage();
    /* game-state data */
    free_timers(RANGE_GLOBAL);
    free_light_sources(RANGE_GLOBAL);
    freeobjchn(invent);
    freeobjchn(migrating_objs);
    freemonchn(migrating_mons);
    freemonchn(mydogs); /* ascension or dungeon escape */
     /* freelevchn(); [folded into free_dungeons()] */
    free_animals();
    free_oracles();
    freefruitchn();
    freenames();
    free_waterlevel();
    free_dungeons();
    /* some pointers in iflags */
    if (iflags.wc_font_map) free(iflags.wc_font_map);
    if (iflags.wc_font_message) free(iflags.
      wc_font_message);
    if (iflags.wc_font_text) free(iflags.
      wc_font_text);
    if (iflags.wc_font_menu) free(iflags.
      wc_font_menu);
    if (iflags.wc_font_status) free(iflags.
      wc_font_status);
    if (iflags.wc_tile_file) free(iflags.
      wc_tile_file);
#ifdef AUTOPICKUP_EXCEPTIONS
    free_autopickup_exceptions();
#endif
#endif /* FREE_ALL_MEMORY */
    return;
}
STATIC_OVL void savedamage (int fd, int mode)
Definition at line 814 of file save.c.
References bwrite(), dlevel_t::damagelist, free(), level, damage::next, perform_bwrite, and release_data.
Referenced by savelev().
{
    register struct damage *damageptr, *tmp_dam;
    unsigned int xl = 0;
    damageptr = level.damagelist;
    for (tmp_dam = damageptr; tmp_dam; tmp_dam = tmp_dam->next)
        xl++;
    if (perform_bwrite(mode))
        bwrite(fd, (genericptr_t) &xl, sizeof(xl));
    while (xl--) {
        if (perform_bwrite(mode))
        bwrite(fd, (genericptr_t) damageptr, sizeof(*damageptr));
        tmp_dam = damageptr;
        damageptr = damageptr->next;
        if (release_data(mode))
        free((genericptr_t)tmp_dam);
    }
    if (release_data(mode))
        level.damagelist = 0;
}
void savefruitchn (int fd, int mode)
Definition at line 925 of file save.c.
References bwrite(), dealloc_fruit, ffruit, fruit::fid, fruit::nextf, perform_bwrite, and release_data.
Referenced by savebones(), and savegamestate().
{
    register struct fruit *f2, *f1;
    f1 = ffruit;
    while (f1) {
        f2 = f1->nextf;
        if (f1->fid >= 0 && perform_bwrite(mode))
        bwrite(fd, (genericptr_t) f1, sizeof(struct fruit));
        if (release_data(mode))
        dealloc_fruit(f1);
        f1 = f2;
    }
    if (perform_bwrite(mode))
        bwrite(fd, (genericptr_t)nulls, sizeof(struct
      fruit));
    if (release_data(mode))
        ffruit = 0;
}
STATIC_OVL void savegamestate (int fd, int mode)
Definition at line 273 of file save.c.
References bflush(), bwrite(), COUNT_SAVE, current_fruit, flags, getuid(), invent, migrating_mons, migrating_objs, monstermoves, moves, perform_bwrite, pl_character, pl_fruit, quest_status, RANGE_GLOBAL, release_data, save_oracles(), save_waterlevel(), savefruitchn(), savelevchn(), savemonchn(), savenames(), saveobjchn(), spl_book, u, and usteed_id.
Referenced by dosave0().
{
    int uid;
#ifdef MFLOPPY
    count_only = (mode & COUNT_SAVE);
#endif
    uid = getuid();
    bwrite(fd, (genericptr_t) &uid, sizeof uid);
    bwrite(fd, (genericptr_t) &flags, sizeof(struct flag));
    bwrite(fd, (genericptr_t) &u, sizeof(struct you));
    /* must come before migrating_objs and migrating_mons are freed */
    save_timers(fd, mode, RANGE_GLOBAL);
    save_light_sources(fd, mode, RANGE_GLOBAL);
    saveobjchn(fd, invent, mode);
    saveobjchn(fd, migrating_objs, mode);
    savemonchn(fd, migrating_mons, mode);
    if (release_data(mode)) {
        invent = 0;
        migrating_objs = 0;
        migrating_mons = 0;
    }
    bwrite(fd, (genericptr_t) mvitals, sizeof(mvitals));
    save_dungeon(fd, (boolean)!!perform_bwrite(mode),
             (boolean)!!release_data(mode));
    savelevchn(fd, mode);
    bwrite(fd, (genericptr_t) &moves, sizeof moves);
    bwrite(fd, (genericptr_t) &monstermoves, sizeof monstermoves);
    bwrite(fd, (genericptr_t) &quest_status, sizeof(struct
      q_score));
    bwrite(fd, (genericptr_t) spl_book,
                sizeof(struct spell) * (MAXSPELL + 1));
    save_artifacts(fd);
    save_oracles(fd, mode);
    if(ustuck_id)
        bwrite(fd, (genericptr_t) &ustuck_id, sizeof ustuck_id);
#ifdef STEED
    if(usteed_id)
        bwrite(fd, (genericptr_t) &usteed_id, sizeof usteed_id);
#endif
    bwrite(fd, (genericptr_t) pl_character, sizeof pl_character);
    bwrite(fd, (genericptr_t) pl_fruit, sizeof pl_fruit);
    bwrite(fd, (genericptr_t) &current_fruit, sizeof current_fruit);
    savefruitchn(fd, mode);
    savenames(fd, mode);
    save_waterlevel(fd, mode);
    bflush(fd);
}
void savelev (int fd, xchar lev, int mode)
Definition at line 435 of file save.c.
References bflush(), billobjs, dlevel_t::buriedobjlist, bwrite(), COLNO, COUNT_SAVE, dndest, dnladder, dnstair, doors, flags, dlevel_t::flags, fmon, fobj, FREE_SAVE, ftrap, rm::glyph, hackpid, iflags, level, level_info, levl, monstermoves, panic(), instance_flags::purge_monsters, RANGE_LEVEL, release_data, ROWNO, save_regions(), save_worm(), savedamage(), savemonchn(), saveobjchn(), savetrapchn(), rm::seenv, sstairs, rm::typ, updest, upladder, upstair, and VISITED.
Referenced by dorecover(), dosave0(), restlevelfile(), restore_savefile(), and savebones().
{
#ifdef TOS
    short tlev;
#endif
    /* if we're tearing down the current level without saving anything
       (which happens upon entrance to the endgame or after an aborted
       restore attempt) then we don't want to do any actual I/O */
    if (mode == FREE_SAVE) goto skip_lots;
    if (iflags.purge_monsters) {
        /* purge any dead monsters (necessary if we're starting
         * a panic save rather than a normal one, or sometimes
         * when changing levels without taking time -- e.g.
         * create statue trap then immediately level teleport) */
        dmonsfree();
    }
    if(fd < 0) panic("Save on bad file!"); /* impossible */
#ifdef MFLOPPY
    count_only = (mode & COUNT_SAVE);
#endif
    if (lev >= 0 && lev <= maxledgerno())
        level_info[lev].flags |= VISITED;
    bwrite(fd,(genericptr_t) &hackpid,sizeof(hackpid));
#ifdef TOS
    tlev=lev; tlev &= 0x00ff;
    bwrite(fd,(genericptr_t) &tlev,sizeof(tlev));
#else
    bwrite(fd,(genericptr_t) &lev,sizeof(lev));
#endif
#ifdef RLECOMP
    {
        /* perform run-length encoding of rm structs */
        struct rm *prm, *rgrm;
        int x, y;
        uchar match;
        rgrm = &levl[0][0]; /* start matching at first rm */
        match = 0;
        for (y = 0; y < ROWNO; y++) {
        for (x = 0; x < COLNO; x++) {
            prm = &levl[x][y];
            if (prm->glyph == rgrm->glyph
            && prm->typ == rgrm->typ
            && prm->seenv == rgrm->seenv
            && prm->horizontal == rgrm->horizontal
            && prm->flags == rgrm->flags
            && prm->lit == rgrm->lit
            && prm->waslit == rgrm->waslit
            && prm->roomno == rgrm->roomno
            && prm->edge == rgrm->edge) {
            match++;
            if (match > 254) {
                match = 254; /* undo this match */
                goto writeout;
            }
            } else {
            /* the run has been broken,
             * write out run-length encoding */
            writeout:
            bwrite(fd, (genericptr_t)&match, sizeof(uchar));
            bwrite(fd, (genericptr_t)rgrm, sizeof(struct rm));
            /* start encoding again. we have at least 1 rm
             * in the next run, viz. this one. */
            match = 1;
            rgrm = prm;
            }
        }
        }
        if (match > 0) {
        bwrite(fd, (genericptr_t)&match, sizeof(uchar));
        bwrite(fd, (genericptr_t)rgrm, sizeof(struct rm));
        }
    }
#else
    bwrite(fd,(genericptr_t) levl,sizeof(levl));
#endif /* RLECOMP */
    bwrite(fd,(genericptr_t) &monstermoves,sizeof(monstermoves));
    bwrite(fd,(genericptr_t) &upstair,sizeof(stairway));
    bwrite(fd,(genericptr_t) &dnstair,sizeof(stairway));
    bwrite(fd,(genericptr_t) &upladder,sizeof(stairway));
    bwrite(fd,(genericptr_t) &dnladder,sizeof(stairway));
    bwrite(fd,(genericptr_t) &sstairs,sizeof(stairway));
    bwrite(fd,(genericptr_t) &updest,sizeof(dest_area));
    bwrite(fd,(genericptr_t) &dndest,sizeof(dest_area));
    bwrite(fd,(genericptr_t) &level.flags,sizeof(
      level.flags));
    bwrite(fd, (genericptr_t) doors, sizeof(doors));
    save_rooms(fd); /* no dynamic memory to reclaim */
    /* from here on out, saving also involves allocated memory cleanup */
 skip_lots:
    /* must be saved before mons, objs, and buried objs */
    save_timers(fd, mode, RANGE_LEVEL);
    save_light_sources(fd, mode, RANGE_LEVEL);
    savemonchn(fd, fmon, mode);
    save_worm(fd, mode); /* save worm information */
    savetrapchn(fd, ftrap, mode);
    saveobjchn(fd, fobj, mode);
    saveobjchn(fd, level.buriedobjlist, mode);
    saveobjchn(fd, billobjs, mode);
    if (release_data(mode)) {
        fmon = 0;
        ftrap = 0;
        fobj = 0;
        level.buriedobjlist = 0;
        billobjs = 0;
    }
    save_engravings(fd, mode);
    savedamage(fd, mode);
    save_regions(fd, mode);
    if (mode != FREE_SAVE) bflush(fd);
}
STATIC_OVL void savelevchn (int fd, int mode)
Definition at line 792 of file save.c.
References bwrite(), free(), s_level::next, perform_bwrite, release_data, and sp_levchn.
Referenced by free_dungeons(), and savegamestate().
{
    s_level *tmplev, *tmplev2;
    int cnt = 0;
    for (tmplev = sp_levchn; tmplev; tmplev = tmplev->next) cnt++;
    if (perform_bwrite(mode))
        bwrite(fd, (genericptr_t) &cnt, sizeof(int));
    for (tmplev = sp_levchn; tmplev; tmplev = tmplev2) {
        tmplev2 = tmplev->next;
        if (perform_bwrite(mode))
        bwrite(fd, (genericptr_t) tmplev, sizeof(s_level));
        if (release_data(mode))
        free((genericptr_t) tmplev);
    }
    if (release_data(mode))
        sp_levchn = 0;
}
STATIC_OVL void savemonchn (int fd, struct monst * mtmp, int mode)
Definition at line 871 of file save.c.
References bwrite(), dealloc_monst, mons, monst::mxlth, monst::nmon, perform_bwrite, release_data, and saveobjchn().
Referenced by savegamestate(), and savelev().
{
    register struct monst *mtmp2;
    unsigned int xl;
    int minusone = -1;
    struct permonst *monbegin = &mons[0];
    if (perform_bwrite(mode))
        bwrite(fd, (genericptr_t) &monbegin, sizeof(monbegin));
    while (mtmp) {
        mtmp2 = mtmp->nmon;
        if (perform_bwrite(mode)) {
        xl = mtmp->mxlth + mtmp->mnamelth;
        bwrite(fd, (genericptr_t) &xl, sizeof(int));
        bwrite(fd, (genericptr_t) mtmp, xl + sizeof(struct
      monst));
        }
        if (mtmp->minvent)
        saveobjchn(fd,mtmp->minvent,mode);
        if (release_data(mode))
        dealloc_monst(mtmp);
        mtmp = mtmp2;
    }
    if (perform_bwrite(mode))
        bwrite(fd, (genericptr_t) &minusone, sizeof(int));
}
STATIC_OVL void saveobjchn (int fd, struct obj * otmp, int mode)
Definition at line 839 of file save.c.
References book_disappears(), bwrite(), FOOD_CLASS, Has_contents, obj::nobj, OBJ_FREE, obj::oxlth, perform_bwrite, release_data, and SPBOOK_CLASS.
Referenced by savegamestate(), savelev(), and savemonchn().
{
    register struct obj *otmp2;
    unsigned int xl;
    int minusone = -1;
    while(otmp) {
        otmp2 = otmp->nobj;
        if (perform_bwrite(mode)) {
        xl = otmp->oxlth + otmp->onamelth;
        bwrite(fd, (genericptr_t) &xl, sizeof(int));
        bwrite(fd, (genericptr_t) otmp, xl + sizeof(struct obj));
        }
        if (Has_contents(otmp))
        saveobjchn(fd,otmp->cobj,mode);
        if (release_data(mode)) {
        if (otmp->oclass == FOOD_CLASS) food_disappears(otmp);
        if (otmp->oclass == SPBOOK_CLASS) book_disappears(otmp);
        otmp->where = OBJ_FREE; /* set to free so dealloc will work */
        otmp->timed = 0; /* not timed any more */
        otmp->lamplit = 0; /* caller handled lights */
        dealloc_obj(otmp);
        }
        otmp = otmp2;
    }
    if (perform_bwrite(mode))
        bwrite(fd, (genericptr_t) &minusone, sizeof(int));
}
STATIC_OVL void savetrapchn (int fd, struct trap * trap, int mode)
Definition at line 901 of file save.c.
References bwrite(), dealloc_trap, trap::ntrap, perform_bwrite, and release_data.
Referenced by savelev().
{
    register struct trap *trap2;
    while (trap) {
        trap2 = trap->ntrap;
        if (perform_bwrite(mode))
        bwrite(fd, (genericptr_t) trap, sizeof(struct trap));
        if (release_data(mode))
        dealloc_trap(trap);
        trap = trap2;
    }
    if (perform_bwrite(mode))
        bwrite(fd, (genericptr_t)nulls, sizeof(struct trap));
}
Variable Documentation
boolean buffering = FALSE [static]
Definition at line 697 of file save.c.
int bw_fd = -1 [static]
Definition at line 695 of file save.c.
FILE* bw_FILE = 0 [static]
Definition at line 696 of file save.c.
unsigned usteed_id = 0 [static]
Definition at line 52 of file save.c.
Referenced by dosave0(), and savegamestate().
unsigned ustuck_id = 0 [static]
Definition at line 52 of file save.c.