nethack/sys/wince/winhack.c File Reference
#include `winMS.h`
*
#include `hack.h`
*
#include `dlb.h`
*
#include `mhmain.h`
*
#include `mhmap.h`
*
Macros
#define SHARED_DCL extern
#define MAX_CMDLINE_PARAM 255
Functions
void FDECL (nethack_exit,(int))
static TCHAR * _get_cmd_arg (TCHAR *pCmdLine)
BOOL InitInstance (HINSTANCE, int)
static void win_hack_init (int, char **)
static void __cdecl mswin_moveloop (void *)
static BOOL setMapTiles (const char *fname)
void FDECL (pcmain,(int, char **))
int APIENTRY WinMain (HINSTANCE hInstance, HINSTANCE hPrevInstance, LPWSTR lpCmdLine, int nCmdShow)
PNHWinApp GetNHApp ()
static int eraseoldlocks ()
void getlock ()
void error VA_DECL (const char *, VA_INIT(s)
VA_END ()
MessageBox (NULL, wbuf, TEXT(`Error`), MB_OK|MB_ICONERROR)
exit (EXIT_FAILURE)
void nt_regularize (char *s)
void win32_abort ()
void append_port_id (char *buf)
Variables
SHARED_DCL char orgdir [PATHLEN]
NHWinApp _nethack_app
Macro Definition Documentation
#define MAX_CMDLINE_PARAM 255
Definition at line 34 of file winhack.c.
Referenced by WinMain().
#define SHARED_DCL extern
Definition at line 14 of file winhack.c.
Function Documentation
TCHAR * _get_cmd_arg (TCHAR * pCmdLine) [static]
Definition at line 290 of file winhack.c.
References NULL, and TRUE.
Referenced by WinMain().
{
    static TCHAR* pArgs = NULL;
    TCHAR *pRetArg;
    BOOL bQuoted;
    if(!pCmdLine && !pArgs) return NULL;
    if(!pArgs) pArgs = pCmdLine;
    /* skip whitespace */
    for(pRetArg = pArgs; *pRetArg && _istspace(*pRetArg); pRetArg = CharNext(pRetArg));
    if(!*pRetArg) {
        pArgs = NULL;
        return NULL;
    }
    /* check for quote */
    if(*pRetArg==TEXT('"')) {
            bQuoted = TRUE;
            pRetArg = CharNext(pRetArg);
            pArgs = _tcschr(pRetArg, TEXT('"'));
    } else {
        /* skip to whitespace */
        for(pArgs = pRetArg; *pArgs && !_istspace(*pArgs); pArgs = CharNext(pArgs));
    }
    
    if(pArgs && *pArgs) {
        TCHAR* p;
        p = pArgs;
        pArgs = CharNext(pArgs);
        *p = (TCHAR)0;
    } else {
        pArgs = NULL;
    }
    return pRetArg;
}
void append_port_id (char * buf)
Definition at line 356 of file winhack.c.
References eos(), and Sprintf.
Referenced by getversionstring().
{
    char *portstr = PORT_CE_PLATFORM " " PORT_CE_CPU;
    Sprintf(eos(buf), " %s", portstr);
}
static int eraseoldlocks () [static]
Definition at line 160 of file winhack.c.
References fqname(), LEVELPREFIX, lock, MAXDUNGEON, MAXLEVEL, set_levelfile_name(), and unlink().
{
    register int i;
    /* cannot use maxledgerno() here, because we need to find a lock name
     * before starting everything (including the dungeon initialization
     * that sets astral_level, needed for maxledgerno()) up
     */
    for(i = 1; i <= MAXDUNGEON*MAXLEVEL + 1; i++) {
        /* try to remove all */
        set_levelfile_name(lock, i);
        (void) unlink(fqname(lock, LEVELPREFIX, 0));
    }
    set_levelfile_name(lock, 0);
    if(unlink(fqname(lock, LEVELPREFIX, 0)))
        return 0; /* cannot remove it */
    return(1); /* success! */
}
exit (EXIT_FAILURE)
void FDECL (nethack_exit , (int))
void FDECL (pcmain , (int, char **))
void getlock (void)
Definition at line 180 of file winhack.c.
References BUFSZ, close(), creat(), error(), FCMASK, fqname(), GetNHApp(), hackpid, HLOCK, LEVELPREFIX, lock, MessageBox(), NH_A2W, NULL, set_levelfile_name(), Sprintf, unlock_file(), and write().
{
    const char *fq_lock;
    char tbuf[BUFSZ];
    TCHAR wbuf[BUFSZ];
    HANDLE f;
    int fd;
    int choice;
    /* regularize(lock); */ /* already done in pcmain */
    Sprintf(tbuf, "%s", fqname(lock, LEVELPREFIX, 0));
    set_levelfile_name(lock, 0);
    fq_lock = fqname(lock, LEVELPREFIX, 1);
    f = CreateFile(
            NH_A2W(fq_lock, wbuf, BUFSZ),
            GENERIC_READ,
            0,
            NULL,
            OPEN_EXISTING,
            FILE_ATTRIBUTE_NORMAL,
            NULL);
    if(f==INVALID_HANDLE_VALUE) {
        if(GetLastError()==ERROR_FILE_NOT_FOUND) goto gotlock; /* no such file */
        error("Cannot open %s", fq_lock);
    }
    CloseHandle(f);
    /* prompt user that the game alredy exist */
    choice = MessageBox(
        GetNHApp()->hMainWnd,
        TEXT("There are files from a game in progress under your name. Recover?"),
        TEXT("Nethack"),
        MB_YESNO | MB_DEFBUTTON1
        );
    switch(choice) {
    case IDYES:
        if(recover_savefile()) {
            goto gotlock;
        } else {
            error("Couldn't recover old game.");
        }
        break;
    case IDNO:
        unlock_file(HLOCK);
        error("%s", "Cannot start a new game.");
        break;
    };
gotlock:
    fd = creat(fq_lock, FCMASK);
    if(fd == -1) {
        error("cannot creat lock file (%s.)", fq_lock);
    } else {
        if(write(fd, (char *) &hackpid, sizeof(hackpid))
            != sizeof(hackpid)){
            error("cannot write lock (%s)", fq_lock);
        }
        if(close(fd) == -1) {
            error("cannot close lock (%s)", fq_lock);
        }
    }
}
PNHWinApp GetNHApp (void)
Definition at line 154 of file winhack.c.
Referenced by _get_main_menu(), About(), CheckInputDialog(), ExtCmdDlgProc(), GetlinDlgProc(), getlock(), initMapTiles(), MainWndProc(), MapWndProc(), MenuWndProc(), mswin_add_menu(), mswin_clear_nhwindow(), mswin_cliparound(), mswin_create_nhwindow(), mswin_curs(), mswin_destroy_nhwindow(), mswin_destroy_reg(), mswin_display_file(), mswin_display_nhwindow(), mswin_end_menu(), mswin_ext_cmd_window(), mswin_get_nh_event(), mswin_getlin_window(), mswin_hwnd_from_winid(), mswin_init_command_window(), mswin_init_main_window(), mswin_init_map_window(), mswin_init_menu_window(), mswin_init_message_window(), mswin_init_nhwindows(), mswin_init_status_window(), mswin_layout_main_window(), mswin_main_loop(), mswin_map_mode(), mswin_map_stretch(), mswin_menu_check_intf_mode(), mswin_outrip(), mswin_player_selection_window(), mswin_popup_destroy(), mswin_popup_display(), mswin_preference_update(), mswin_print_glyph(), mswin_putstr_ex(), mswin_raw_print(), mswin_raw_print_bold(), mswin_read_reg(), mswin_select_map_mode(), mswin_select_menu(), mswin_set_fullscreen(), mswin_start_menu(), mswin_window_mark_dead(), mswin_winid_from_handle(), mswin_winid_from_type(), mswin_write_reg(), mswin_yn_function(), NHMenuTextWndProc(), NHMessageBox(), NHMessageWndProc(), onCreate(), onDrawItem(), onListChar(), onMSNH_HScroll(), onMSNH_VScroll(), onMSNHCommand(), onPaint(), onWMCommand(), PlayerSelectorDlgProc(), register_command_window_class(), register_main_window_class(), register_map_window_class(), register_message_window_class(), register_status_window_class(), SetMenuListType(), and StatusWndProc().
{
    return &_nethack_app;
}
BOOL InitInstance (HINSTANCE hInstance, int nCmdShow)
Definition at line 149 of file winhack.c.
References TRUE.
Referenced by WinMain().
{
   return TRUE;
}
MessageBox (NULL , wbuf , TEXT(`Error`) , MB_OK| MB_ICONERROR)
Referenced by alloc_file_handle(), getlock(), mswin_display_file(), mswin_raw_print(), mswin_raw_print_bold(), NHMessageBox(), PlayerSelectorDlgProc(), plselFinalSelection(), prompt_for_player_selection(), and WinMain().
static void __cdecl mswin_moveloop (void *) [static]
void nt_regularize (char * s)
Definition at line 333 of file winhack.c.
{
    register unsigned char *lp;
    for (lp = s; *lp; lp++)
        if (*lp == '?' || *lp == '"' || *lp == '\\' ||
         *lp == '/' || *lp == '>' || *lp == '<' ||
         *lp == '*' || *lp == '|' || *lp == ':' || (*lp > 127))
            *lp = '_';
}
static BOOL setMapTiles (const char * fname) [static]
void error VA_DECL (const char * , VA_INIT(s)
Definition at line 248 of file winhack.c.
References NULL.
                       {
        LPVOID lpMsgBuf;
        if(FormatMessage(
                FORMAT_MESSAGE_ALLOCATE_BUFFER |
                FORMAT_MESSAGE_FROM_SYSTEM |
                FORMAT_MESSAGE_IGNORE_INSERTS,
                NULL,
                last_error,
                0, // Default language
                (LPTSTR) &lpMsgBuf,
                0,
                NULL
            )
            )
        {
            
            _tcsncat(wbuf, TEXT("\nSystem Error: "), sizeof(wbuf)/sizeof(wbuf[0]) - _tcslen(wbuf));
            _tcsncat(wbuf, lpMsgBuf, sizeof(wbuf)/sizeof(wbuf[0]) - _tcslen(wbuf));
            // Free the buffer.
            LocalFree(lpMsgBuf);
        }
    }
VA_END ()
void win32_abort ()
Definition at line 345 of file winhack.c.
References abort, and wizard.
{
#ifdef WIZARD
    if (wizard)
        DebugBreak();
#endif
    abort();
}
static void win_hack_init (int , char **) [static]
int APIENTRY WinMain (HINSTANCE hInstance, HINSTANCE hPrevInstance, LPWSTR lpCmdLine, int nCmdShow)
Definition at line 36 of file winhack.c.
References _get_cmd_arg(), mswin_nhwindow_app::bCmdPad, mswin_nhwindow_app::bFullScreen, mswin_nhwindow_app::bHideScrollBars, mswin_nhwindow_app::bmpMapTiles, mswin_nhwindow_app::bmpPetMark, mswin_nhwindow_app::bmpTiles, mswin_nhwindow_app::bNoHScroll, mswin_nhwindow_app::bNoVScroll, buf, BUFSZ, mswin_nhwindow_app::bUseSIP, mswin_nhwindow_app::bWrapText, FALSE, mswin_nhwindow_app::hAccelTable, mswin_nhwindow_app::hApp, mswin_nhwindow_app::hMainWnd, mswin_nhwindow_app::hMenuBar, mswin_nhwindow_app::hPopupWnd, IDB_PETMARK, IDB_TILES, IDC_WINHACK, InitInstance(), mswin_nhwindow_app::mapTile_X, mswin_nhwindow_app::mapTile_Y, mswin_nhwindow_app::mapTilesPerLine, MAX_CMDLINE_PARAM, MessageBox(), mswin_raw_print(), mswin_raw_print_bold(), mswin_nhwindow_app::nCmdShow, NH_W2A, NHSTR_BUFSIZE, NULL, panic(), szMainWindowClass, TILE_X, TILE_Y, TILES_PER_LINE, TRUE, and windowprocs.
{
    INITCOMMONCONTROLSEX InitCtrls;
    HWND nethackWnd;
    int argc;
    char* argv[MAX_CMDLINE_PARAM];
    size_t len;
    TCHAR* p;
    TCHAR wbuf[NHSTR_BUFSIZE];
    char buf[NHSTR_BUFSIZE];
    /* ensure that we don't access violate on a panic() */
    windowprocs.win_raw_print = mswin_raw_print;
    windowprocs.win_raw_print_bold = mswin_raw_print_bold;
    /* init applicatio structure */
    _nethack_app.hApp = hInstance;
    _nethack_app.nCmdShow = nCmdShow;
    _nethack_app.hAccelTable = LoadAccelerators(hInstance, (LPCTSTR)
      IDC_WINHACK);
    _nethack_app.hMainWnd = NULL;
    _nethack_app.hPopupWnd = NULL;
    _nethack_app.hMenuBar = NULL;
    _nethack_app.bmpTiles = LoadBitmap(hInstance, MAKEINTRESOURCE(
      IDB_TILES));
    if(_nethack_app.bmpTiles==NULL) panic("cannot load tiles bitmap");
    _nethack_app.bmpPetMark = LoadBitmap(hInstance, MAKEINTRESOURCE(
      IDB_PETMARK));
    if(_nethack_app.bmpPetMark==NULL) panic("cannot load pet mark bitmap")
      ;
    _nethack_app.bmpMapTiles = _nethack_app.
      bmpTiles;
    _nethack_app.mapTile_X = TILE_X;
    _nethack_app.mapTile_Y = TILE_Y;
    _nethack_app.mapTilesPerLine = TILES_PER_LINE;
    _nethack_app.bNoHScroll = FALSE;
    _nethack_app.bNoVScroll = FALSE;
#if defined(WIN_CE_PS2xx) || defined(WIN_CE_POCKETPC) || defined(WIN_CE_SMARTPHONE)
    _nethack_app.bCmdPad = TRUE;
#else
    _nethack_app.bCmdPad = FALSE;
#endif
    _nethack_app.bWrapText = TRUE;
    _nethack_app.bFullScreen = TRUE;
#if defined(WIN_CE_SMARTPHONE)
    _nethack_app.bHideScrollBars = TRUE;
#else
    _nethack_app.bHideScrollBars = FALSE;
#endif
    _nethack_app.bUseSIP = TRUE;
    // check for running nethack programs
    nethackWnd = FindWindow(szMainWindowClass, NULL);
    if(nethackWnd) {
        // bring on top
        SetForegroundWindow(nethackWnd);
        return FALSE;
    }
    // init controls
    ZeroMemory(&InitCtrls, sizeof(InitCtrls));
    InitCtrls.dwSize = sizeof(InitCtrls);
    InitCtrls.dwICC = ICC_LISTVIEW_CLASSES;
    if(!InitCommonControlsEx(&InitCtrls)) {
        MessageBox(NULL, TEXT("Cannot init common controls"), TEXT("ERROR"), MB_OK |
      MB_ICONSTOP);
        return FALSE;
    }
    // Perform application initialization:
    if (!InitInstance (hInstance, nCmdShow))
    {
        return FALSE;
    }
    /* get command line parameters */
    p = _get_cmd_arg(
#if defined(WIN_CE_PS2xx) || defined(WIN32_PLATFORM_HPCPRO)
        lpCmdLine
#else
        GetCommandLine()
#endif
        );
    for(argc = 1; p && argc<MAX_CMDLINE_PARAM; argc++) {
        len = _tcslen(p);
        if(len>0) {
            argv[argc] = _strdup(NH_W2A(p, buf, BUFSZ));
        } else {
            argv[argc] = "";
        }
        p = _get_cmd_arg(NULL);
    }
    GetModuleFileName(NULL, wbuf, BUFSZ);
    argv[0] = _strdup(NH_W2A(wbuf, buf, BUFSZ));
    pcmain(argc,argv);
    moveloop();
    return 0;
}
Variable Documentation
NHWinApp _nethack_app
Definition at line 23 of file winhack.c.
Referenced by GetNHApp().
SHARED_DCL char orgdir[PATHLEN]
Definition at line 17 of file winhack.c.