nethack/sys/wince/mswproc.c File Reference
#include `hack.h`
*
#include `dlb.h`
*
#include `winMS.h`
*
#include `mhmap.h`
*
#include `mhstatus.h`
*
#include `mhtext.h`
*
#include `mhmsgwnd.h`
*
#include `mhmenu.h`
*
#include `mhmsg.h`
*
#include `mhcmd.h`
*
#include `mhinput.h`
*
#include `mhaskyn.h`
*
#include `mhdlg.h`
*
#include `mhrip.h`
*
#include `mhmain.h`
*
#include `mhfont.h`
*
#include `mhcolor.h`
*
Macros
#define LLEN 128
Functions
void logDebug (const char *fmt,...)
static void mswin_main_loop ()
static BOOL initMapTiles (void)
static void prompt_for_player_selection (void)
void mswin_init_nhwindows (int *argc, char **argv)
void mswin_player_selection (void)
void mswin_askname (void)
void mswin_get_nh_event (void)
void mswin_exit_nhwindows (const char *str)
void mswin_suspend_nhwindows (const char *str)
void mswin_resume_nhwindows ()
winid mswin_create_nhwindow (int type)
void mswin_clear_nhwindow (winid wid)
void mswin_display_nhwindow (winid wid, BOOLEAN_P block)
HWND mswin_hwnd_from_winid (winid wid)
winid mswin_winid_from_handle (HWND hWnd)
winid mswin_winid_from_type (int type)
void mswin_window_mark_dead (winid wid)
void mswin_destroy_nhwindow (winid wid)
void mswin_curs (winid wid, int x, int y)
void mswin_putstr (winid wid, int attr, const char *text)
void mswin_putstr_ex (winid wid, int attr, const char *text, boolean app)
void mswin_display_file (const char *filename, BOOLEAN_P must_exist)
void mswin_start_menu (winid wid)
void mswin_add_menu (winid wid, int glyph, const ANY_P *identifier, CHAR_P accelerator, CHAR_P group_accel, int attr, const char *str, BOOLEAN_P presel)
void mswin_end_menu (winid wid, const char *prompt)
int mswin_select_menu (winid wid, int how, MENU_ITEM_P **selected)
void mswin_update_inventory ()
void mswin_mark_synch ()
void mswin_wait_synch ()
void mswin_cliparound (int x, int y)
void mswin_print_glyph (winid wid, XCHAR_P x, XCHAR_P y, int glyph)
void mswin_raw_print (const char *str)
void mswin_raw_print_bold (const char *str)
int mswin_nhgetch ()
int mswin_nh_poskey (int *x, int *y, int *mod)
void mswin_nhbell ()
int mswin_doprev_message ()
char mswin_yn_function (const char *question, const char *choices, CHAR_P def)
void mswin_getlin (const char *question, char *input)
int mswin_get_ext_cmd ()
void mswin_number_pad (int state)
void mswin_delay_output ()
void mswin_change_color ()
char * mswin_get_color_string ()
void mswin_start_screen ()
void mswin_end_screen ()
void mswin_outrip (winid wid, int how)
void mswin_preference_update (const char *pref)
void bail (const char *mesg)
void mswin_popup_display (HWND hWnd, int *done_indicator)
void mswin_popup_destroy (HWND hWnd)
void mswin_set_fullscreen (BOOL is_fullscreen)
void mswin_read_reg (void)
void mswin_destroy_reg (void)
void mswin_write_reg (void)
Variables
struct window_procs mswin_procs
Macro Definition Documentation
#define LLEN 128
Definition at line 27 of file mswproc.c.
Referenced by mswin_display_file().
Function Documentation
void bail (const char * mesg)
Definition at line 1709 of file mswproc.c.
Referenced by MainWndProc(), mswin_askname(), mswin_player_selection(), and prompt_for_player_selection().
{
    clearlocks();
    mswin_exit_nhwindows(mesg);
    terminate(EXIT_SUCCESS);
    /*NOTREACHED*/
}
BOOL initMapTiles (void) [static]
Definition at line 1717 of file mswproc.c.
References mswin_nhwindow_app::bmpMapTiles, COLNO, FALSE, GetNHApp(), iflags, mswin_nhwindow_app::mapTile_X, mswin_nhwindow_app::mapTile_Y, mswin_nhwindow_app::mapTilesPerLine, mswin_hwnd_from_winid(), mswin_map_stretch(), NH_A2W, NULL, raw_print, ROWNO, SIZE, total_tiles_used, TRUE, instance_flags::wc_tile_file, instance_flags::wc_tile_height, instance_flags::wc_tile_width, and WIN_MAP.
Referenced by mswin_init_nhwindows().
{
    HBITMAP hBmp;
    BITMAP bm;
    TCHAR wbuf[MAX_PATH];
    int tl_num;
    SIZE map_size;
    extern int total_tiles_used;
    /* no file - no tile */
    if(!(iflags.wc_tile_file && *iflags.wc_tile_file))
        return TRUE;
    /* load bitmap */
    hBmp = SHLoadDIBitmap(NH_A2W(iflags.wc_tile_file, wbuf, MAX_PATH));
    if(hBmp==NULL) {
        raw_print("Cannot load tiles from the file. Reverting back to default.");
        return FALSE;
    }
    /* calculate tile dimensions */
    GetObject(hBmp, sizeof(BITMAP), (LPVOID)&bm);
    if(bm.bmWidth%iflags.wc_tile_width ||
        bm.bmHeight%iflags.wc_tile_height) {
        DeleteObject(hBmp);
        raw_print("Tiles bitmap does not match tile_width and tile_height options. Reverting back
       to default.");
        return FALSE;
    }
    tl_num = (bm.bmWidth/iflags.wc_tile_width)*
             (bm.bmHeight/iflags.wc_tile_height);
    if(tl_num<total_tiles_used) {
        DeleteObject(hBmp);
        raw_print("Number of tiles in the bitmap is less than required by the game. Reverting back
       to default.");
        return FALSE;
    }
    /* set the tile information */
    if(GetNHApp()->bmpMapTiles!=GetNHApp()->bmpTiles) {
        DeleteObject(GetNHApp()->bmpMapTiles);
    }
    GetNHApp()->bmpMapTiles = hBmp;
    GetNHApp()->mapTile_X = iflags.wc_tile_width;
    GetNHApp()->mapTile_Y = iflags.wc_tile_height;
    GetNHApp()->mapTilesPerLine = bm.bmWidth / iflags.
      wc_tile_width;
    map_size.cx = GetNHApp()->mapTile_X * COLNO;
    map_size.cy = GetNHApp()->mapTile_Y * ROWNO;
    mswin_map_stretch(
        mswin_hwnd_from_winid(WIN_MAP),
        &map_size,
        TRUE
    );
    return TRUE;
}
void logDebug (const char * fmt, ...)
Definition at line 32 of file mswproc.c.
Referenced by mswin_add_menu(), mswin_askname(), mswin_change_color(), mswin_clear_nhwindow(), mswin_cliparound(), mswin_create_nhwindow(), mswin_curs(), mswin_delay_output(), mswin_destroy_nhwindow(), mswin_display_file(), mswin_display_nhwindow(), mswin_doprev_message(), mswin_end_menu(), mswin_end_screen(), mswin_exit_nhwindows(), mswin_get_color_string(), mswin_get_ext_cmd(), mswin_get_nh_event(), mswin_getlin(), mswin_init_nhwindows(), mswin_mark_synch(), mswin_nh_poskey(), mswin_nhbell(), mswin_nhgetch(), mswin_number_pad(), mswin_outrip(), mswin_player_selection(), mswin_print_glyph(), mswin_putstr(), mswin_raw_print(), mswin_raw_print_bold(), mswin_resume_nhwindows(), mswin_select_menu(), mswin_start_menu(), mswin_start_screen(), mswin_suspend_nhwindows(), mswin_update_inventory(), mswin_wait_synch(), mswin_yn_function(), and prompt_for_player_selection().
{ }
void mswin_add_menu (winid wid, int glyph, const ANY_P * identifier, CHAR_P accelerator, CHAR_P group_accel, int attr, const char * str, BOOLEAN_P presel)
Definition at line 1061 of file mswproc.c.
Referenced by ActivateCell().
{
    logDebug("mswin_add_menu(%d, %d, %p, %c, %c, %d, %s, %d)\n",
             wid, glyph, identifier, (char)accelerator, (char)group_accel,
             attr, str, presel);
    if ((wid >= 0) &&
        (wid < MAXWINDOWS) &&
        (GetNHApp()->windowlist[wid].win != NULL))
    {
        MSNHMsgAddMenu data;
        ZeroMemory(&data, sizeof(data));
        data.glyph = glyph;
        data.identifier = identifier;
        data.accelerator = accelerator;
        data.group_accel = group_accel;
        data.attr = attr;
        data.str = str;
        data.presel = presel;
        SendMessage(
             GetNHApp()->windowlist[wid].win,
             WM_MSNH_COMMAND, (WPARAM)MSNH_MSG_ADDMENU, (LPARAM)&data
        );
    }
}
void mswin_askname (void)
Definition at line 651 of file mswproc.c.
{
    logDebug("mswin_askname()\n");
    if(mswin_getlin_window("who are you?", plname,
      PL_NSIZ)==IDCANCEL) {
        bail("bye-bye");
        /* not reached */
    }
}
void mswin_change_color (void)
Definition at line 1515 of file mswproc.c.
{
    logDebug("mswin_change_color()\n");
}
void mswin_clear_nhwindow (winid wid)
Definition at line 773 of file mswproc.c.
Referenced by mswin_get_ext_cmd(), mswin_getlin(), and mswin_yn_function().
{
    logDebug("mswin_clear_nhwindow(%d)\n", wid);
    if ((wid >= 0) &&
        (wid < MAXWINDOWS) &&
        (GetNHApp()->windowlist[wid].win != NULL))
    {
#ifdef REINCARNATION
        if(GetNHApp()->windowlist[wid].type == NHW_MAP) {
            if(Is_rogue_level(&u.uz))
                mswin_map_mode(mswin_hwnd_from_winid(
      WIN_MAP), ROGUE_LEVEL_MAP_MODE);
            else
                mswin_map_mode(mswin_hwnd_from_winid(
      WIN_MAP), iflags.wc_map_mode);
        }
#endif
         SendMessage(
             GetNHApp()->windowlist[wid].win,
             WM_MSNH_COMMAND, (WPARAM)MSNH_MSG_CLEAR_WINDOW, (LPARAM)
      NULL);
    }
}
void mswin_cliparound (int x, int y)
Definition at line 1192 of file mswproc.c.
Referenced by mswin_map_stretch(), and mswin_preference_update().
{
    winid wid = WIN_MAP;
    logDebug("mswin_cliparound(%d, %d)\n", x, y);
    if ((wid >= 0) &&
        (wid < MAXWINDOWS) &&
        (GetNHApp()->windowlist[wid].win != NULL))
    {
         MSNHMsgClipAround data;
         data.x = x;
         data.y = y;
         SendMessage(
             GetNHApp()->windowlist[wid].win,
             WM_MSNH_COMMAND, (WPARAM)MSNH_MSG_CLIPAROUND, (LPARAM)&data
      );
    }
}
winid mswin_create_nhwindow (int type)
Definition at line 710 of file mswproc.c.
Referenced by ActivateCell(), and mswin_display_file().
{
    winid i = 0;
    MSNHMsgAddWnd data;
    logDebug("mswin_create_nhwindow(%d)\n", type);
    /* Return the next available winid
     */
    for (i=1; i<MAXWINDOWS; i++)
      if (GetNHApp()->windowlist[i].win == NULL &&
          !GetNHApp()->windowlist[i].dead)
          break;
    if (i == MAXWINDOWS)
      panic ("ERROR: No windows available...\n");
    switch (type) {
    case NHW_MAP:
    {
        GetNHApp()->windowlist[i].win =
      mswin_init_map_window();
        GetNHApp()->windowlist[i].type = type;
        GetNHApp()->windowlist[i].dead = 0;
        break;
    }
    case NHW_MESSAGE:
    {
        GetNHApp()->windowlist[i].win =
      mswin_init_message_window();
        GetNHApp()->windowlist[i].type = type;
        GetNHApp()->windowlist[i].dead = 0;
        break;
    }
    case NHW_STATUS:
    {
        GetNHApp()->windowlist[i].win =
      mswin_init_status_window();
        GetNHApp()->windowlist[i].type = type;
        GetNHApp()->windowlist[i].dead = 0;
        break;
    }
    case NHW_MENU:
    {
        GetNHApp()->windowlist[i].win = NULL; //will create later
        GetNHApp()->windowlist[i].type = type;
        GetNHApp()->windowlist[i].dead = 1;
        break;
    }
    case NHW_TEXT:
    {
        GetNHApp()->windowlist[i].win =
      mswin_init_text_window();
        GetNHApp()->windowlist[i].type = type;
        GetNHApp()->windowlist[i].dead = 0;
        break;
    }
    }
    ZeroMemory(&data, sizeof(data));
    data.wid = i;
    SendMessage(GetNHApp()->hMainWnd,
                 WM_MSNH_COMMAND, (WPARAM)MSNH_MSG_ADDWND, (LPARAM)&data);
    return i;
}
void mswin_curs (winid wid, int x, int y)
Definition at line 897 of file mswproc.c.
{
    logDebug("mswin_curs(%d, %d, %d)\n", wid, x, y);
    if ((wid >= 0) &&
        (wid < MAXWINDOWS) &&
        (GetNHApp()->windowlist[wid].win != NULL))
    {
         MSNHMsgCursor data;
         data.x = x;
         data.y = y;
         SendMessage(
             GetNHApp()->windowlist[wid].win,
             WM_MSNH_COMMAND, (WPARAM)MSNH_MSG_CURSOR, (LPARAM)&data);
    }
}
void mswin_delay_output (void)
Definition at line 1509 of file mswproc.c.
{
    logDebug("mswin_delay_output()\n");
    Sleep(50);
}
void mswin_destroy_nhwindow (winid wid)
Definition at line 871 of file mswproc.c.
Referenced by ActivateCell(), and mswin_display_file().
{
    logDebug("mswin_destroy_nhwindow(%d)\n", wid);
    if ((GetNHApp()->windowlist[wid].type == NHW_MAP) ||
        (GetNHApp()->windowlist[wid].type == NHW_MESSAGE) ||
        (GetNHApp()->windowlist[wid].type == NHW_STATUS)) {
        /* main windows is going to take care of those */
        return;
    }
    if (wid != -1) {
        if(!GetNHApp()->windowlist[wid].dead &&
            GetNHApp()->windowlist[wid].win != NULL)
            DestroyWindow(GetNHApp()->windowlist[wid].win);
        GetNHApp()->windowlist[wid].win = NULL;
        GetNHApp()->windowlist[wid].type = 0;
        GetNHApp()->windowlist[wid].dead = 0;
    }
}
void mswin_destroy_reg (void)
Definition at line 1939 of file mswproc.c.
Referenced by onWMCommand().
{
}
void mswin_display_file (const char * filename, BOOLEAN_P must_exist)
Definition at line 972 of file mswproc.c.
{
    dlb *f;
    TCHAR wbuf[BUFSZ];
    logDebug("mswin_display_file(%s, %d)\n", filename, must_exist);
    f = dlb_fopen(filename, RDTMODE);
    if (!f) {
        if (must_exist) {
            TCHAR message[90];
            _stprintf(message, TEXT("Warning! Could not find file: %s\n"),
      NH_A2W(filename, wbuf, sizeof(wbuf)));
            MessageBox(GetNHApp()->hMainWnd, message, TEXT("ERROR"), MB_OK | MB_ICONERROR
       );
        }
    } else {
        winid text;
        char line[LLEN];
        text = mswin_create_nhwindow(NHW_TEXT);
        while (dlb_fgets(line, LLEN, f)) {
             size_t len;
             len = strlen(line);
             if(line[len-1]=='\n') line[len-1]='\x0';
                mswin_putstr(text, ATR_NONE, line);
        }
        (void) dlb_fclose(f);
        mswin_display_nhwindow(text, 1);
        mswin_destroy_nhwindow(text);
    }
}
void mswin_display_nhwindow (winid wid, BOOLEAN_P block)
Definition at line 805 of file mswproc.c.
Referenced by mswin_display_file().
{
    logDebug("mswin_display_nhwindow(%d, %d)\n", wid, block);
    if (GetNHApp()->windowlist[wid].win != NULL)
    {
        if (GetNHApp()->windowlist[wid].type == NHW_MENU) {
            MENU_ITEM_P* p;
            mswin_menu_window_select_menu(GetNHApp()->windowlist[wid].
      win, PICK_NONE, &p);
        } if (GetNHApp()->windowlist[wid].type == NHW_TEXT) {
            mswin_display_text_window(GetNHApp()->windowlist[wid].win);
        } if (GetNHApp()->windowlist[wid].type == NHW_RIP) {
            mswin_display_RIP_window(GetNHApp()->windowlist[wid].win);
        } else {
            if(!block) {
                UpdateWindow(GetNHApp()->windowlist[wid].win);
            } else {
                if (GetNHApp()->windowlist[wid].type == NHW_MAP) {
                    (void) mswin_nhgetch();
                }
            }
        }
        SetFocus(GetNHApp()->hMainWnd);
    }
}
int mswin_doprev_message (void)
Definition at line 1338 of file mswproc.c.
{
    logDebug("mswin_doprev_message()\n");
    SendMessage(mswin_hwnd_from_winid(WIN_MESSAGE), WM_VSCROLL, MAKEWPARAM(
      SB_LINEUP, 0), (LPARAM)NULL);
    return 0;
}
void mswin_end_menu (winid wid, const char * prompt)
Definition at line 1098 of file mswproc.c.
Referenced by ActivateCell().
{
    logDebug("mswin_end_menu(%d, %s)\n", wid, prompt);
    if ((wid >= 0) &&
        (wid < MAXWINDOWS) &&
        (GetNHApp()->windowlist[wid].win != NULL))
    {
        MSNHMsgEndMenu data;
        ZeroMemory(&data, sizeof(data));
        data.text = prompt;
        SendMessage(
             GetNHApp()->windowlist[wid].win,
             WM_MSNH_COMMAND, (WPARAM)MSNH_MSG_ENDMENU, (LPARAM)&data
        );
    }
}
void mswin_end_screen (void)
Definition at line 1543 of file mswproc.c.
{
    /* Do Nothing */
    logDebug("mswin_end_screen()\n");
}
void mswin_exit_nhwindows (const char * str)
Definition at line 674 of file mswproc.c.
Referenced by bail().
{
    logDebug("mswin_exit_nhwindows(%s)\n", str);
    /* Write Window settings to the registry */
    mswin_write_reg();
    // Don't do any of this (?) - exit_nhwindows does not terminate
    // the application
    // DestroyWindow(GetNHApp()->hMainWnd);
    // terminate(EXIT_SUCCESS);
}
char* mswin_get_color_string (void)
Definition at line 1520 of file mswproc.c.
{
    logDebug("mswin_get_color_string()\n");
    return("");
}
int mswin_get_ext_cmd (void)
Definition at line 1482 of file mswproc.c.
{
    int ret;
    logDebug("mswin_get_ext_cmd()\n");
    if(mswin_ext_cmd_window (&ret) == IDCANCEL)
        return -1;
    else
        return ret;
}
void mswin_get_nh_event (void)
Definition at line 665 of file mswproc.c.
Referenced by mswin_putstr_ex().
{
    logDebug("mswin_get_nh_event()\n");
    return;
}
void mswin_getlin (const char * question, char * input)
Definition at line 1468 of file mswproc.c.
Referenced by onListChar().
{
    logDebug("mswin_getlin(%s, %p)\n", question, input);
    if(mswin_getlin_window(question, input, BUFSZ)==IDCANCEL) {
        strcpy(input, "\033");
    }
}
HWND mswin_hwnd_from_winid (winid wid)
Definition at line 831 of file mswproc.c.
Referenced by GetlinDlgProc(), initMapTiles(), MainWndProc(), mswin_clear_nhwindow(), mswin_display_RIP_window(), mswin_display_splash_window(), mswin_doprev_message(), mswin_finish_rip_text(), mswin_get_ext_cmd(), mswin_getlin(), mswin_layout_main_window(), mswin_preference_update(), mswin_select_map_mode(), and mswin_yn_function().
{
    if(wid>=0 && wid<MAXWINDOWS) {
        return GetNHApp()->windowlist[wid].win;
    } else {
        return NULL;
    }
}
void mswin_init_nhwindows (int * argc, char ** argv)
Definition at line 114 of file mswproc.c.
{
    HWND hWnd;
    logDebug("mswin_init_nhwindows()\n");
#ifdef _DEBUG
    {
        /* truncate trace file */
        FILE *dfp = fopen("nhtrace.log", "w");
        fclose(dfp);
    }
#endif
    /* intialize input subsystem */
    mswin_nh_input_init();
    /* read registry settings */
    mswin_read_reg();
    /* set it to WIN_ERR so we can detect attempts to
       use this ID before it is inialized */
    WIN_MAP = WIN_ERR;
    /* check default values */
    if(iflags.wc_fontsiz_status<NHFONT_SIZE_MIN ||
        iflags.wc_fontsiz_status>NHFONT_SIZE_MAX)
        iflags.wc_fontsiz_status =
      NHFONT_STATUS_DEFAULT_SIZE;
    if(iflags.wc_fontsiz_message<NHFONT_SIZE_MIN ||
        iflags.wc_fontsiz_message>NHFONT_SIZE_MAX)
        iflags.wc_fontsiz_message = NHFONT_DEFAULT_SIZE;
    if(iflags.wc_fontsiz_text<NHFONT_SIZE_MIN ||
        iflags.wc_fontsiz_text>NHFONT_SIZE_MAX)
        iflags.wc_fontsiz_text = NHFONT_DEFAULT_SIZE;
    if(iflags.wc_fontsiz_menu<NHFONT_SIZE_MIN ||
        iflags.wc_fontsiz_menu>NHFONT_SIZE_MAX)
        iflags.wc_fontsiz_menu = NHFONT_DEFAULT_SIZE;
    if(iflags.wc_align_message==0) iflags.
      wc_align_message = ALIGN_BOTTOM;
    if(iflags.wc_align_status==0) iflags.
      wc_align_status = ALIGN_TOP;
    if(iflags.wc_scroll_margin==0) iflags.
      wc_scroll_margin = DEF_CLIPAROUND_MARGIN;
    if(iflags.wc_tile_width==0) iflags.wc_tile_width =
      TILE_X;
    if(iflags.wc_tile_height==0) iflags.
      wc_tile_height = TILE_Y;
    if(iflags.wc_vary_msgcount==0) iflags.
      wc_vary_msgcount = 3;
    /* force tabs in menus */
    iflags.menu_tab_sep = 1;
    /* force toptenwin to be true. toptenwin is the option that decides whether to
     * write output to a window or stdout. stdout doesn't make sense on Windows
     * non-console applications
     */
    flags.toptenwin = 1;
    set_option_mod_status("toptenwin", SET_IN_FILE);
    /* initialize map tiles bitmap */
    initMapTiles();
    /* set tile-related options to readonly */
    set_wc_option_mod_status(
       WC_TILE_WIDTH|WC_TILE_HEIGHT|WC_TILE_FILE,
       DISP_IN_GAME);
    /* init color table */
    mswin_init_color_table();
    /* set font-related options to change in the game */
    set_wc_option_mod_status(
        WC_HILITE_PET |
        WC_ALIGN_MESSAGE |
        WC_ALIGN_STATUS |
        WC_SCROLL_MARGIN |
        WC_MAP_MODE |
        WC_FONT_MESSAGE |
        WC_FONT_STATUS |
        WC_FONT_MENU |
        WC_FONT_TEXT |
        WC_FONTSIZ_MESSAGE |
        WC_FONTSIZ_STATUS |
        WC_FONTSIZ_MENU |
        WC_FONTSIZ_TEXT |
        WC_VARY_MSGCOUNT,
        SET_IN_GAME
    );
    /* WC2 options */
    set_wc2_option_mod_status(
        WC2_FULLSCREEN|
        WC2_SOFTKEYBOARD,
        SET_IN_FILE
    );
    GetNHApp()->bFullScreen = iflags.wc2_fullscreen;
    GetNHApp()->bUseSIP = iflags.wc2_softkeyboard;
    
    set_wc2_option_mod_status(
        WC2_WRAPTEXT,
        SET_IN_GAME
    );
    GetNHApp()->bWrapText = iflags.wc2_wraptext;
    /* create the main nethack window */
    hWnd = mswin_init_main_window();
    if (!hWnd) panic("Cannot create the main window.");
    ShowWindow(hWnd, GetNHApp()->nCmdShow);
    UpdateWindow(hWnd);
    GetNHApp()->hMainWnd = hWnd;
    /* set Full screen if requested */
    mswin_set_fullscreen(GetNHApp()->bFullScreen);
    /* let nethack code know that the window subsystem is ready */
    iflags.window_inited = TRUE;
}
void mswin_main_loop (void) [static]
Definition at line 1695 of file mswproc.c.
References GetNHApp(), mswin_have_input(), and NULL.
Referenced by mswin_nh_poskey(), and mswin_nhgetch().
{
    MSG msg;
    while(!mswin_have_input() &&
           GetMessage(&msg, NULL, 0, 0)!=0) {
        if (!TranslateAccelerator(msg.hwnd, GetNHApp()->hAccelTable, &msg)) {
            TranslateMessage(&msg);
            DispatchMessage(&msg);
        }
    }
}
void mswin_mark_synch (void)
Definition at line 1171 of file mswproc.c.
{
    logDebug("mswin_mark_synch()\n");
}
int mswin_nh_poskey (int * x, int * y, int * mod)
Definition at line 1304 of file mswproc.c.
Referenced by onMSNHCommand().
{
    PMSNHEvent event;
    int key;
    logDebug("mswin_nh_poskey()\n");
    while((event = mswin_input_pop())==NULL)
      mswin_main_loop();
    if(event->type==NHEVENT_MOUSE) {
        *mod = event->ms.mod;
        *x = event->ms.x;
        *y = event->ms.y;
        key = 0;
    } else {
        key = event->kbd.ch;
    }
    return (key);
}
void mswin_nhbell (void)
Definition at line 1328 of file mswproc.c.
Referenced by mswin_yn_function(), and onListChar().
{
    logDebug("mswin_nhbell()\n");
}
int mswin_nhgetch (void)
Definition at line 1273 of file mswproc.c.
Referenced by mswin_display_nhwindow(), mswin_get_ext_cmd(), mswin_getlin(), mswin_yn_function(), and onPaint().
{
    PMSNHEvent event;
    int key = 0;
    logDebug("mswin_nhgetch()\n");
    
    while((event = mswin_input_pop()) == NULL ||
           event->type != NHEVENT_CHAR)
        mswin_main_loop();
    key = event->kbd.ch;
    return (key);
}
void mswin_number_pad (int state)
Definition at line 1498 of file mswproc.c.
{
    /* Do Nothing */
    logDebug("mswin_number_pad(%d)\n", state);
}
void mswin_outrip (winid wid, int how)
Definition at line 1554 of file mswproc.c.
{
    logDebug("mswin_outrip(%d)\n", wid, how);
    if ((wid >= 0) && (wid < MAXWINDOWS)) {
        DestroyWindow(GetNHApp()->windowlist[wid].win);
        GetNHApp()->windowlist[wid].win =
      mswin_init_RIP_window();
        GetNHApp()->windowlist[wid].type = NHW_RIP;
        GetNHApp()->windowlist[wid].dead = 0;
    }
    genl_outrip(wid, how);
}
void mswin_player_selection (void)
Definition at line 236 of file mswproc.c.
{
    logDebug("mswin_player_selection()\n");
#if defined(WIN_CE_SMARTPHONE)
    /* SmartPhone does not supprt combo-boxes therefor we cannot
       use dialog for player selection */
    prompt_for_player_selection();
#else
    if (iflags.wc_player_selection == VIA_DIALOG) {
        int nRole;
        /* pick player type randomly (use pre-selected role/race/gender/alignment) */
        if(flags.randomall) {
        if (flags.initrole < 0) {
            flags.initrole = pick_role(flags.initrace,
      flags.initgend,
                            flags.initalign, PICK_RANDOM);
            if (flags.initrole < 0) {
                raw_print("Incompatible role!");
                flags.initrole = randrole();
            }
        }
        if (flags.initrace < 0 || !validrace(flags.
      initrole, flags.initrace)) {
            flags.initrace = pick_race(flags.initrole,
      flags.initgend,
                                flags.initalign, PICK_RANDOM);
            if (flags.initrace < 0) {
                raw_print("Incompatible race!");
                flags.initrace = randrace(flags.
      initrole);
            }
        }
        if (flags.initgend < 0 || !validgend(flags.
      initrole, flags.initrace,
                        flags.initgend)) {
            flags.initgend = pick_gend(flags.initrole,
      flags.initrace,
                            flags.initalign, PICK_RANDOM);
            if (flags.initgend < 0) {
                raw_print("Incompatible gender!");
                flags.initgend = randgend(flags.
      initrole, flags.initrace);
            }
        }
        if (flags.initalign < 0 || !validalign(flags.
      initrole, flags.initrace,
                                flags.initalign)) {
            flags.initalign = pick_align(flags.
      initrole, flags.initrace,
                                flags.initgend, PICK_RANDOM);
            if (flags.initalign < 0) {
                raw_print("Incompatible alignment!");
                flags.initalign = randalign(flags.
      initrole, flags.initrace);
            }
        }
        } else {
        /* select a role */
        if(mswin_player_selection_window(&nRole) == IDCANCEL) {
            bail(0);
        }
        }
    } else { /* iflags.wc_player_selection == VIA_PROMPTS */
        prompt_for_player_selection();
    }
#endif /* defined(WIN_CE_SMARTPHONE) */
}
void mswin_popup_destroy (HWND hWnd)
Definition at line 1814 of file mswproc.c.
Referenced by mswin_display_text_window(), and mswin_menu_window_select_menu().
{
    HWND hChild;
    /* enable game windows */
    for(hChild=GetWindow(GetNHApp()->hMainWnd, GW_CHILD);
         hChild;
         hChild = GetWindow(hChild, GW_HWNDNEXT)) {
        if(hChild!= hWnd) {
            EnableWindow(hChild, TRUE);
        }
    }
#if defined(WIN_CE_SMARTPHONE)
    ShowWindow(SHFindMenuBar(hWnd), SW_HIDE);
    ShowWindow(GetNHApp()->hMenuBar, SW_SHOW);
#else
    EnableWindow(GetNHApp()->hMenuBar, TRUE);
#endif
    SetWindowPos(hWnd, HWND_BOTTOM, 0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE | SWP_HIDEWINDOW);
    GetNHApp()->hPopupWnd = NULL;
    mswin_window_mark_dead(mswin_winid_from_handle(hWnd));
    DestroyWindow(hWnd);
    mswin_layout_main_window(hWnd);
    SetFocus(GetNHApp()->hMainWnd);
}
void mswin_popup_display (HWND hWnd, int * done_indicator)
Definition at line 1774 of file mswproc.c.
Referenced by mswin_display_text_window(), and mswin_menu_window_select_menu().
{
    MSG msg;
    HWND hChild;
    /* activate the menu window */
    GetNHApp()->hPopupWnd = hWnd;
    mswin_layout_main_window(hWnd);
    /* disable game windows */
    for(hChild=GetWindow(GetNHApp()->hMainWnd, GW_CHILD);
         hChild;
         hChild = GetWindow(hChild, GW_HWNDNEXT)) {
        if(hChild!=hWnd) EnableWindow(hChild, FALSE);
    }
#if defined(WIN_CE_SMARTPHONE)
    ShowWindow(GetNHApp()->hMenuBar, SW_HIDE);
    ShowWindow(SHFindMenuBar(hWnd), SW_SHOW);
#else
    EnableWindow(GetNHApp()->hMenuBar, FALSE);
#endif
    /* bring menu window on top */
    SetWindowPos(hWnd, HWND_TOP, 0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE | SWP_SHOWWINDOW);
    /* go into message loop */
    if(done_indicator) *done_indicator = 0;
    while(IsWindow(hWnd) &&
           (done_indicator==NULL || !*done_indicator) &&
           GetMessage(&msg, NULL, 0, 0)!=0) {
        if(!IsDialogMessage(hWnd, &msg)) {
            if (!TranslateAccelerator(msg.hwnd, GetNHApp()->hAccelTable, &msg)) {
                TranslateMessage(&msg);
                DispatchMessage(&msg);
            }
        }
    }
}
void mswin_preference_update (const char * pref)
Definition at line 1568 of file mswproc.c.
{
    HDC hdc;
    if(_stricmp(pref, "font_menu")==0 ||
        _stricmp(pref, "font_size_menu")==0) {
        if(iflags.wc_fontsiz_menu<NHFONT_SIZE_MIN ||
            iflags.wc_fontsiz_menu>NHFONT_SIZE_MAX)
            iflags.wc_fontsiz_menu = NHFONT_DEFAULT_SIZE;
        hdc = GetDC(GetNHApp()->hMainWnd);
        mswin_get_font(NHW_MENU, ATR_NONE, hdc,
      TRUE);
        mswin_get_font(NHW_MENU, ATR_BOLD, hdc,
      TRUE);
        mswin_get_font(NHW_MENU, ATR_DIM, hdc, TRUE);
        mswin_get_font(NHW_MENU, ATR_ULINE, hdc,
      TRUE);
        mswin_get_font(NHW_MENU, ATR_BLINK, hdc,
      TRUE);
        mswin_get_font(NHW_MENU, ATR_INVERSE, hdc,
      TRUE);
        ReleaseDC(GetNHApp()->hMainWnd, hdc);
        mswin_layout_main_window(NULL);
        return;
    }
    if(_stricmp(pref, "font_status")==0 ||
        _stricmp(pref, "font_size_status")==0) {
        if(iflags.wc_fontsiz_status<NHFONT_SIZE_MIN ||
            iflags.wc_fontsiz_status>NHFONT_SIZE_MAX)
            iflags.wc_fontsiz_status =
      NHFONT_DEFAULT_SIZE;
        hdc = GetDC(GetNHApp()->hMainWnd);
        mswin_get_font(NHW_STATUS, ATR_NONE, hdc,
      TRUE);
        mswin_get_font(NHW_STATUS, ATR_BOLD, hdc,
      TRUE);
        mswin_get_font(NHW_STATUS, ATR_DIM, hdc,
      TRUE);
        mswin_get_font(NHW_STATUS, ATR_ULINE, hdc,
      TRUE);
        mswin_get_font(NHW_STATUS, ATR_BLINK, hdc,
      TRUE);
        mswin_get_font(NHW_STATUS, ATR_INVERSE, hdc,
      TRUE);
        ReleaseDC(GetNHApp()->hMainWnd, hdc);
        mswin_layout_main_window(NULL);
        return;
    }
    if(_stricmp(pref, "font_message")==0 ||
        _stricmp(pref, "font_size_message")==0) {
        if(iflags.wc_fontsiz_message<NHFONT_SIZE_MIN ||
            iflags.wc_fontsiz_message>NHFONT_SIZE_MAX)
            iflags.wc_fontsiz_message =
      NHFONT_DEFAULT_SIZE;
        hdc = GetDC(GetNHApp()->hMainWnd);
        mswin_get_font(NHW_MESSAGE, ATR_NONE, hdc,
      TRUE);
        mswin_get_font(NHW_MESSAGE, ATR_BOLD, hdc,
      TRUE);
        mswin_get_font(NHW_MESSAGE, ATR_DIM, hdc,
      TRUE);
        mswin_get_font(NHW_MESSAGE, ATR_ULINE, hdc,
      TRUE);
        mswin_get_font(NHW_MESSAGE, ATR_BLINK, hdc,
      TRUE);
        mswin_get_font(NHW_MESSAGE, ATR_INVERSE, hdc,
      TRUE);
        ReleaseDC(GetNHApp()->hMainWnd, hdc);
        mswin_layout_main_window(NULL);
        return;
    }
    if(_stricmp(pref, "font_text")==0 ||
        _stricmp(pref, "font_size_text")==0) {
        if(iflags.wc_fontsiz_text<NHFONT_SIZE_MIN ||
            iflags.wc_fontsiz_text>NHFONT_SIZE_MAX)
            iflags.wc_fontsiz_text = NHFONT_DEFAULT_SIZE;
        hdc = GetDC(GetNHApp()->hMainWnd);
        mswin_get_font(NHW_TEXT, ATR_NONE, hdc,
      TRUE);
        mswin_get_font(NHW_TEXT, ATR_BOLD, hdc,
      TRUE);
        mswin_get_font(NHW_TEXT, ATR_DIM, hdc, TRUE);
        mswin_get_font(NHW_TEXT, ATR_ULINE, hdc,
      TRUE);
        mswin_get_font(NHW_TEXT, ATR_BLINK, hdc,
      TRUE);
        mswin_get_font(NHW_TEXT, ATR_INVERSE, hdc,
      TRUE);
        ReleaseDC(GetNHApp()->hMainWnd, hdc);
        mswin_layout_main_window(NULL);
        return;
    }
    if(_stricmp(pref, "scroll_margin")==0) {
        mswin_cliparound(u.ux, u.uy);
        return;
    }
    if(_stricmp(pref, "map_mode")==0) {
        mswin_select_map_mode(iflags.wc_map_mode);
        return;
    }
    if(_stricmp(pref, "hilite_pet")==0) {
        InvalidateRect(mswin_hwnd_from_winid(WIN_MAP),
      NULL, TRUE);
        return;
    }
    if(_stricmp(pref, "align_message")==0 ||
        _stricmp(pref, "align_status")==0) {
        mswin_layout_main_window(NULL);
        return;
    }
    if(_stricmp(pref, "vary_msgcount")==0) {
        InvalidateRect(mswin_hwnd_from_winid(WIN_MESSAGE),
      NULL, TRUE);
        mswin_layout_main_window(NULL);
        return;
    }
    if(_stricmp(pref, "fullscreen")==0) {
        mswin_set_fullscreen(iflags.wc2_fullscreen);
        return;
    }
    if(_stricmp(pref, "softkeyboard")==0) {
        GetNHApp()->bUseSIP = iflags.wc2_softkeyboard;
        return;
    }
    if(_stricmp(pref, "wraptext")==0) {
        GetNHApp()->bWrapText = iflags.wc2_wraptext;
        return;
    }
}
void mswin_print_glyph (winid wid, XCHAR_P x, XCHAR_P y, int glyph)
Definition at line 1218 of file mswproc.c.
{
    logDebug("mswin_print_glyph(%d, %d, %d, %d)\n", wid, x, y, glyph);
    if ((wid >= 0) &&
        (wid < MAXWINDOWS) &&
        (GetNHApp()->windowlist[wid].win != NULL))
    {
        MSNHMsgPrintGlyph data;
        ZeroMemory(&data, sizeof(data));
        data.x = x;
        data.y = y;
        data.glyph = glyph;
        SendMessage(GetNHApp()->windowlist[wid].win,
                 WM_MSNH_COMMAND, (WPARAM)MSNH_MSG_PRINT_GLYPH, (LPARAM)
      &data);
    }
}
void mswin_putstr (winid wid, int attr, const char * text)
Definition at line 937 of file mswproc.c.
Referenced by mswin_display_file(), and mswin_yn_function().
{
    logDebug("mswin_putstr(%d, %d, %s)\n", wid, attr, text);
    mswin_putstr_ex(wid, attr, text, 0);
}
void mswin_putstr_ex (winid wid, int attr, const char * text, boolean app)
Definition at line 944 of file mswproc.c.
References mswin_nhmsg_putstr::append, mswin_nhmsg_putstr::attr, mswin_nhwindow_data::dead, GetNHApp(), MAXWINDOWS, MENU_TYPE_TEXT, MSNH_MSG_PUTSTR, mswin_init_menu_window(), NHW_MENU, NULL, mswin_nhmsg_putstr::text, type, mswin_nhwindow_data::win, mswin_nhwindow_app::windowlist, and WM_MSNH_COMMAND.
Referenced by mswin_get_ext_cmd(), mswin_getlin(), mswin_putstr(), and mswin_yn_function().
{
    if((wid >= 0) &&
        (wid < MAXWINDOWS))
    {
        if(GetNHApp()->windowlist[wid].win==NULL &&
            GetNHApp()->windowlist[wid].type==NHW_MENU) {
            GetNHApp()->windowlist[wid].win =
      mswin_init_menu_window(MENU_TYPE_TEXT);
            GetNHApp()->windowlist[wid].dead = 0;
        }
        if (GetNHApp()->windowlist[wid].win != NULL)
        {
             MSNHMsgPutstr data;
             ZeroMemory(&data, sizeof(data));
             data.attr = attr;
             data.text = text;
             data.append = app;
             SendMessage(
                 GetNHApp()->windowlist[wid].win,
                 WM_MSNH_COMMAND, (WPARAM)MSNH_MSG_PUTSTR, (LPARAM)&data);
        }
    }
}
void mswin_raw_print (const char * str)
Definition at line 1246 of file mswproc.c.
Referenced by WinMain().
{
    TCHAR wbuf[255];
    logDebug("mswin_raw_print(%s)\n", str);
    if(str && *str)
        MessageBox(GetNHApp()->hMainWnd, NH_A2W(str, wbuf, sizeof(wbuf)), TEXT("
      NetHack"), MB_OK);
}
void mswin_raw_print_bold (const char * str)
Definition at line 1259 of file mswproc.c.
Referenced by WinMain().
{
    TCHAR wbuf[255];
    logDebug("mswin_raw_print_bold(%s)\n", str);
    if(str && *str)
        MessageBox(GetNHApp()->hMainWnd, NH_A2W(str, wbuf, sizeof(wbuf)), TEXT("
      NetHack"), MB_OK);
}
void mswin_read_reg (void)
Definition at line 1935 of file mswproc.c.
Referenced by mswin_init_nhwindows().
{
}
void mswin_resume_nhwindows (void)
Definition at line 696 of file mswproc.c.
{
    logDebug("mswin_resume_nhwindows()\n");
    return;
}
int mswin_select_menu (winid wid, int how, MENU_ITEM_P ** selected)
Definition at line 1141 of file mswproc.c.
{
    int nReturned = -1;
    logDebug("mswin_select_menu(%d, %d)\n", wid, how);
    if ((wid >= 0) &&
        (wid < MAXWINDOWS) &&
        (GetNHApp()->windowlist[wid].win != NULL))
    {
        nReturned = mswin_menu_window_select_menu(
      GetNHApp()->windowlist[wid].win, how, selected);
    }
    return nReturned;
}
void mswin_set_fullscreen (BOOL is_fullscreen)
Definition at line 1843 of file mswproc.c.
References mswin_nhwindow_app::bFullScreen, FALSE, and GetNHApp().
Referenced by mswin_init_nhwindows(), and mswin_preference_update().
{
#if defined(WIN_CE_POCKETPC) || defined(WIN_CE_SMARTPHONE)
    SetForegroundWindow(GetNHApp()->hMainWnd);
    if(is_fullscreen) {
        SHFullScreen(GetNHApp()->hMainWnd, SHFS_HIDETASKBAR | SHFS_HIDESTARTICON);
        MoveWindow(
            GetNHApp()->hMainWnd,
            0,
            0,
            GetSystemMetrics(SM_CXSCREEN),
            GetSystemMetrics(SM_CYSCREEN),
            FALSE
        );
    } else {
        RECT rc;
        SystemParametersInfo(SPI_GETWORKAREA, 0, &rc, 0);
        SHFullScreen(GetNHApp()->hMainWnd, SHFS_SHOWTASKBAR | SHFS_SHOWSTARTICON);
        MoveWindow(
            GetNHApp()->hMainWnd,
            rc.left,
            rc.top,
            rc.right - rc.left,
            rc.bottom - rc.top,
            FALSE
        );
    }
    GetNHApp()->bFullScreen = is_fullscreen;
#else
    GetNHApp()->bFullScreen = FALSE;
#endif
}
void mswin_start_menu (winid wid)
Definition at line 1010 of file mswproc.c.
Referenced by ActivateCell().
{
    logDebug("mswin_start_menu(%d)\n", wid);
    if((wid >= 0) &&
        (wid < MAXWINDOWS)) {
        if(GetNHApp()->windowlist[wid].win==NULL &&
            GetNHApp()->windowlist[wid].type==NHW_MENU) {
            GetNHApp()->windowlist[wid].win =
      mswin_init_menu_window(MENU_TYPE_MENU);
            GetNHApp()->windowlist[wid].dead = 0;
        }
        if(GetNHApp()->windowlist[wid].win != NULL) {
            SendMessage(
                 GetNHApp()->windowlist[wid].win,
                 WM_MSNH_COMMAND, (WPARAM)MSNH_MSG_STARTMENU, (LPARAM)
      NULL
            );
        }
    }
}
void mswin_start_screen (void)
Definition at line 1533 of file mswproc.c.
{
    /* Do Nothing */
    logDebug("mswin_start_screen()\n");
}
void mswin_suspend_nhwindows (const char * str)
Definition at line 688 of file mswproc.c.
{
    logDebug("mswin_suspend_nhwindows(%s)\n", str);
    return;
}
void mswin_update_inventory (void)
Definition at line 1161 of file mswproc.c.
{
    logDebug("mswin_update_inventory()\n");
}
void mswin_wait_synch (void)
Definition at line 1182 of file mswproc.c.
{
    logDebug("mswin_wait_synch()\n");
}
void mswin_window_mark_dead (winid wid)
Definition at line 860 of file mswproc.c.
Referenced by mswin_popup_destroy(), NHRIPWndProc(), NHSplashWndProc(), and NHTextWndProc().
{
    if(wid>=0 && wid<MAXWINDOWS) {
        GetNHApp()->windowlist[wid].win = NULL;
        GetNHApp()->windowlist[wid].dead = 1;
    }
}
winid mswin_winid_from_handle (HWND hWnd)
Definition at line 840 of file mswproc.c.
Referenced by mswin_popup_destroy(), NHRIPWndProc(), NHSplashWndProc(), and NHTextWndProc().
{
    winid i = 0;
    for (i=1; i<MAXWINDOWS; i++)
      if (GetNHApp()->windowlist[i].win == hWnd)
          return i;
    return -1;
}
winid mswin_winid_from_type (int type)
Definition at line 850 of file mswproc.c.
Referenced by mswin_select_map_mode().
{
    winid i = 0;
    for (i=1; i<MAXWINDOWS; i++)
      if (GetNHApp()->windowlist[i].type == type)
          return i;
    return -1;
}
void mswin_write_reg (void)
Definition at line 1943 of file mswproc.c.
Referenced by mswin_exit_nhwindows().
{
}
char mswin_yn_function (const char * question, const char * choices, CHAR_P def)
Definition at line 1364 of file mswproc.c.
{
    int result=-1;
    char ch;
    char yn_esc_map='\033';
    char message[BUFSZ];
    char res_ch[2];
    logDebug("mswin_yn_function(%s, %s, %d)\n", question, choices, def);
    if (choices) {
        char *cb, choicebuf[QBUFSZ];
        Strcpy(choicebuf, choices);
        if ((cb = index(choicebuf, '\033')) != 0) {
            /* anything beyond <esc> is hidden */
            *cb = '\0';
        }
        sprintf(message, "%s [%s] ", question, choicebuf);
        if (def) sprintf(eos(message), "(%c) ", def);
        /* escape maps to 'q' or 'n' or default, in that order */
        yn_esc_map = (index(choices, 'q') ? 'q' :
             (index(choices, 'n') ? 'n' : def));
    } else {
        Strcpy(message, question);
    }
#if defined(WIN_CE_SMARTPHONE)
    {
    char buf[BUFSZ];
    ZeroMemory(buf, sizeof(buf));
    if(choices) {
        if(!index(choices, '\033')) buf[0]='\033'; /* make sure ESC is always available */
        strncat(buf, choices, sizeof(buf)-2);
        NHSPhoneSetKeypadFromString(buf);
    } else {
        /* sometimes choices are included in the message itself, e.g. "what? [abcd]" */
        char *p1, *p2;
        p1 = strchr(question, '[');
        p2 = strrchr(question, ']');
        if(p1 && p2 && p1<p2) {
            buf[0]='\033'; /* make sure ESC is always available */
            strncat(buf, p1+1, p2-p1-1);
            NHSPhoneSetKeypadFromString(buf);
        } else if(strstr(question, "direction")) {
            /* asking for direction here */
            NHSPhoneSetKeypadDirection();
        } else {
            /* anything goes */
            NHSPhoneSetKeypadFromString("\0330-9a-zA-Z");
        }
    }
    }
#endif /* defined(WIN_CE_SMARTPHONE) */
    mswin_putstr(WIN_MESSAGE, ATR_BOLD, message);
    /* Only here if main window is not present */
    while (result<0) {
    ch=mswin_nhgetch();
    if (ch=='\033') {
        result=yn_esc_map;
    } else if (choices && !index(choices,ch)) {
        /* FYI: ch==-115 is for KP_ENTER */
        if (def && (ch==' ' || ch=='\r' || ch=='\n' || ch==-115)) {
        result=def;
        } else {
        mswin_nhbell();
        /* and try again... */
        }
    } else {
        result=ch;
    }
    }
    /* display selection in the message window */
    if(isprint(ch)) {
        res_ch[0] = ch;
        res_ch[1] = '\x0';
        mswin_putstr_ex(WIN_MESSAGE, ATR_BOLD, res_ch, 1);
    }
    /* prevent "--more--" prompt from appearing when several
       questions being asked in the same loop (like selling
       something in the shop)
       It does not really clears the window - mhmsgwnd.c */
    mswin_clear_nhwindow(WIN_MESSAGE);
#if defined(WIN_CE_SMARTPHONE)
    NHSPhoneSetKeypadDefault();
#endif
    return result;
}
void prompt_for_player_selection (void) [static]
Definition at line 299 of file mswproc.c.
References any::a_int, any::a_void, add_menu, aligns, ATR_NONE, bail(), BUFSZ, build_plselection_prompt(), CO, create_nhwindow, destroy_nhwindow, end_menu, RoleName::f, flags, free(), genders, index(), flag::initalign, flag::initgend, flag::initrace, flag::initrole, mi::item, logDebug(), lowc(), RoleName::m, MENU_UNSELECTED, MessageBox(), Role::name, name, NH_A2W, NHW_MENU, NO_GLYPH, Race::noun, NULL, ok_align(), ok_gend(), ok_race(), ok_role(), pick_align(), pick_gend(), PICK_ONE, pick_race(), PICK_RANDOM, pick_role(), QBUFSZ, quitchars, races, randalign(), randgend(), flag::randomall, randrace(), randrole(), rigid_role_checks(), ROLE_ALIGNS, ROLE_GENDERS, ROLE_NONE, ROLE_RANDOM, roles, root_plselection_prompt(), select_menu, Sprintf, start_menu, Strcat, Strcpy, validalign(), validgend(), validrace(), and ynqchars.
Referenced by mswin_player_selection().
{
    int i, k, n;
    char pick4u = 'n', thisch, lastch = 0;
    char pbuf[QBUFSZ], plbuf[QBUFSZ];
    winid win;
    anything any;
    menu_item *selected = 0;
    int box_result;
    TCHAR wbuf[BUFSZ];
    logDebug("prompt_for_player_selection()\n");
    /* prevent an unnecessary prompt */
    rigid_role_checks();
    /* Should we randomly pick for the player? */
    if (!flags.randomall &&
        (flags.initrole == ROLE_NONE || flags.
      initrace == ROLE_NONE ||
         flags.initgend == ROLE_NONE || flags.
      initalign == ROLE_NONE)) {
        /* int echoline; */
        char *prompt = build_plselection_prompt(pbuf,
      QBUFSZ, flags.initrole,
                flags.initrace, flags.initgend, flags.
      initalign);
        /* tty_putstr(BASE_WINDOW, 0, ""); */
        /* echoline = wins[BASE_WINDOW]->cury; */
        box_result = MessageBox(NULL,
                    NH_A2W(prompt, wbuf, BUFSZ),
                    TEXT("NetHack for Windows"),
#if defined(WIN_CE_SMARTPHONE)
                    MB_YESNO | MB_DEFBUTTON1
#else
                    MB_YESNOCANCEL | MB_DEFBUTTON1
#endif
                    );
        pick4u = (box_result == IDYES) ? 'y' : (box_result == IDNO) ? 'n' : '\033';
        /* tty_putstr(BASE_WINDOW, 0, prompt); */
        do {
        /* pick4u = lowc(readchar()); */
        if (index(quitchars, pick4u)) pick4u = 'y';
        } while(!index(ynqchars, pick4u));
        if ((int)strlen(prompt) + 1 < CO) {
        /* Echo choice and move back down line */
        /* tty_putsym(BASE_WINDOW, (int)strlen(prompt)+1, echoline, pick4u); */
        /* tty_putstr(BASE_WINDOW, 0, ""); */
        } else
        /* Otherwise it's hard to tell where to echo, and things are
         * wrapping a bit messily anyway, so (try to) make sure the next
         * question shows up well and doesn't get wrapped at the
         * bottom of the window.
         */
        /* tty_clear_nhwindow(BASE_WINDOW) */ ;
        
        if (pick4u != 'y' && pick4u != 'n') {
give_up: /* Quit */
        if (selected) free((genericptr_t) selected);
        bail((char *)0);
        /*NOTREACHED*/
        return;
        }
    }
    (void) root_plselection_prompt(plbuf, QBUFSZ - 1,
            flags.initrole, flags.initrace, flags.
      initgend, flags.initalign);
    /* Select a role, if necessary */
    /* we'll try to be compatible with pre-selected race/gender/alignment,
     * but may not succeed */
    if (flags.initrole < 0) {
        char rolenamebuf[QBUFSZ];
        /* Process the choice */
        if (pick4u == 'y' || flags.initrole == ROLE_RANDOM ||
      flags.randomall) {
        /* Pick a random role */
        flags.initrole = pick_role(flags.initrace,
      flags.initgend,
                        flags.initalign, PICK_RANDOM);
        if (flags.initrole < 0) {
            /* tty_putstr(BASE_WINDOW, 0, "Incompatible role!"); */
            flags.initrole = randrole();
        }
        } else {
            /* tty_clear_nhwindow(BASE_WINDOW); */
        /* tty_putstr(BASE_WINDOW, 0, "Choosing Character's Role"); */
        /* Prompt for a role */
        win = create_nhwindow(NHW_MENU);
        start_menu(win);
        any.a_void = 0; /* zero out all bits */
        for (i = 0; roles[i].name.m; i++) {
            if (ok_role(i, flags.initrace, flags.
      initgend,
                            flags.initalign)) {
            any.a_int = i+1; /* must be non-zero */
            thisch = lowc(roles[i].name.m[0]);
            if (thisch == lastch) thisch = highc(thisch);
            if (flags.initgend != ROLE_NONE && flags.
      initgend != ROLE_RANDOM) {
                if (flags.initgend == 1 && roles[i].name.
      f)
                    Strcpy(rolenamebuf, roles[i].name.f);
                else
                    Strcpy(rolenamebuf, roles[i].name.m);
            } else {
                if (roles[i].name.f) {
                    Strcpy(rolenamebuf, roles[i].name.m);
                    Strcat(rolenamebuf, "/");
                    Strcat(rolenamebuf, roles[i].name.f);
                } else
                    Strcpy(rolenamebuf, roles[i].name.m);
            }
            add_menu(win, NO_GLYPH, &any, thisch,
                0, ATR_NONE, an(rolenamebuf), MENU_UNSELECTED);
            lastch = thisch;
            }
        }
        any.a_int = pick_role(flags.initrace, flags.
      initgend,
                    flags.initalign, PICK_RANDOM)+1;
        if (any.a_int == 0) /* must be non-zero */
            any.a_int = randrole()+1;
        add_menu(win, NO_GLYPH, &any , '*', 0, ATR_NONE,
                "Random", MENU_UNSELECTED);
        any.a_int = i+1; /* must be non-zero */
        add_menu(win, NO_GLYPH, &any , 'q', 0, ATR_NONE,
                "Quit", MENU_UNSELECTED);
        Sprintf(pbuf, "Pick a role for your %s", plbuf);
        end_menu(win, pbuf);
        n = select_menu(win, PICK_ONE, &selected);
        destroy_nhwindow(win);
        /* Process the choice */
        if (n != 1 || selected[0].item.a_int == any.a_int)
            goto give_up; /* Selected quit */
        flags.initrole = selected[0].item.a_int - 1;
        free((genericptr_t) selected), selected = 0;
        }
        (void) root_plselection_prompt(plbuf, QBUFSZ - 1,
            flags.initrole, flags.initrace, flags.
      initgend, flags.initalign);
    }
    
    /* Select a race, if necessary */
    /* force compatibility with role, try for compatibility with
     * pre-selected gender/alignment */
    if (flags.initrace < 0 || !validrace(flags.
      initrole, flags.initrace)) {
        /* pre-selected race not valid */
        if (pick4u == 'y' || flags.initrace == ROLE_RANDOM ||
      flags.randomall) {
        flags.initrace = pick_race(flags.initrole,
      flags.initgend,
                            flags.initalign, PICK_RANDOM);
        if (flags.initrace < 0) {
            /* tty_putstr(BASE_WINDOW, 0, "Incompatible race!"); */
            flags.initrace = randrace(flags.initrole);
        }
        } else { /* pick4u == 'n' */
        /* Count the number of valid races */
        n = 0; /* number valid */
        k = 0; /* valid race */
        for (i = 0; races[i].noun; i++) {
            if (ok_race(flags.initrole, i, flags.
      initgend,
                            flags.initalign)) {
            n++;
            k = i;
            }
        }
        if (n == 0) {
            for (i = 0; races[i].noun; i++) {
            if (validrace(flags.initrole, i)) {
                n++;
                k = i;
            }
            }
        }
        /* Permit the user to pick, if there is more than one */
        if (n > 1) {
            /* tty_clear_nhwindow(BASE_WINDOW); */
            /* tty_putstr(BASE_WINDOW, 0, "Choosing Race"); */
            win = create_nhwindow(NHW_MENU);
            start_menu(win);
            any.a_void = 0; /* zero out all bits */
            for (i = 0; races[i].noun; i++)
            if (ok_race(flags.initrole, i, flags.
      initgend,
                            flags.initalign)) {
                any.a_int = i+1; /* must be non-zero */
                add_menu(win, NO_GLYPH, &any, races[i].noun[0],
                0, ATR_NONE, races[i].noun, MENU_UNSELECTED);
            }
            any.a_int = pick_race(flags.initrole,
      flags.initgend,
                    flags.initalign, PICK_RANDOM)+1;
            if (any.a_int == 0) /* must be non-zero */
            any.a_int = randrace(flags.initrole)+1;
            add_menu(win, NO_GLYPH, &any , '*', 0, ATR_NONE,
                    "Random", MENU_UNSELECTED);
            any.a_int = i+1; /* must be non-zero */
            add_menu(win, NO_GLYPH, &any , 'q', 0, ATR_NONE,
                    "Quit", MENU_UNSELECTED);
            Sprintf(pbuf, "Pick the race of your %s", plbuf);
            end_menu(win, pbuf);
            n = select_menu(win, PICK_ONE, &selected);
            destroy_nhwindow(win);
            if (n != 1 || selected[0].item.a_int == any.a_int)
            goto give_up; /* Selected quit */
            k = selected[0].item.a_int - 1;
            free((genericptr_t) selected), selected = 0;
        }
        flags.initrace = k;
        }
        (void) root_plselection_prompt(plbuf, QBUFSZ - 1,
            flags.initrole, flags.initrace, flags.
      initgend, flags.initalign);
    }
    /* Select a gender, if necessary */
    /* force compatibility with role/race, try for compatibility with
     * pre-selected alignment */
    if (flags.initgend < 0 || !validgend(flags.
      initrole, flags.initrace,
                        flags.initgend)) {
        /* pre-selected gender not valid */
        if (pick4u == 'y' || flags.initgend == ROLE_RANDOM ||
      flags.randomall) {
        flags.initgend = pick_gend(flags.initrole,
      flags.initrace,
                        flags.initalign, PICK_RANDOM);
        if (flags.initgend < 0) {
            /* tty_putstr(BASE_WINDOW, 0, "Incompatible gender!"); */
            flags.initgend = randgend(flags.initrole,
      flags.initrace);
        }
        } else { /* pick4u == 'n' */
        /* Count the number of valid genders */
        n = 0; /* number valid */
        k = 0; /* valid gender */
        for (i = 0; i < ROLE_GENDERS; i++) {
            if (ok_gend(flags.initrole, flags.initrace, i,
                            flags.initalign)) {
            n++;
            k = i;
            }
        }
        if (n == 0) {
            for (i = 0; i < ROLE_GENDERS; i++) {
            if (validgend(flags.initrole, flags.
      initrace, i)) {
                n++;
                k = i;
            }
            }
        }
        /* Permit the user to pick, if there is more than one */
        if (n > 1) {
            /* tty_clear_nhwindow(BASE_WINDOW); */
            /* tty_putstr(BASE_WINDOW, 0, "Choosing Gender"); */
            win = create_nhwindow(NHW_MENU);
            start_menu(win);
            any.a_void = 0; /* zero out all bits */
            for (i = 0; i < ROLE_GENDERS; i++)
            if (ok_gend(flags.initrole, flags.initrace, i,
                                flags.initalign)) {
                any.a_int = i+1;
                add_menu(win, NO_GLYPH, &any, genders[i].adj[0],
                0, ATR_NONE, genders[i].adj, MENU_UNSELECTED);
            }
            any.a_int = pick_gend(flags.initrole,
      flags.initrace,
                        flags.initalign, PICK_RANDOM)+1;
            if (any.a_int == 0) /* must be non-zero */
            any.a_int = randgend(flags.initrole, flags.
      initrace)+1;
            add_menu(win, NO_GLYPH, &any , '*', 0, ATR_NONE,
                    "Random", MENU_UNSELECTED);
            any.a_int = i+1; /* must be non-zero */
            add_menu(win, NO_GLYPH, &any , 'q', 0, ATR_NONE,
                    "Quit", MENU_UNSELECTED);
            Sprintf(pbuf, "Pick the gender of your %s", plbuf);
            end_menu(win, pbuf);
            n = select_menu(win, PICK_ONE, &selected);
            destroy_nhwindow(win);
            if (n != 1 || selected[0].item.a_int == any.a_int)
            goto give_up; /* Selected quit */
            k = selected[0].item.a_int - 1;
            free((genericptr_t) selected), selected = 0;
        }
        flags.initgend = k;
        }
        (void) root_plselection_prompt(plbuf, QBUFSZ - 1,
            flags.initrole, flags.initrace, flags.
      initgend, flags.initalign);
    }
    /* Select an alignment, if necessary */
    /* force compatibility with role/race/gender */
    if (flags.initalign < 0 || !validalign(flags.
      initrole, flags.initrace,
                            flags.initalign)) {
        /* pre-selected alignment not valid */
        if (pick4u == 'y' || flags.initalign == ROLE_RANDOM ||
      flags.randomall) {
        flags.initalign = pick_align(flags.initrole,
      flags.initrace,
                            flags.initgend, PICK_RANDOM);
        if (flags.initalign < 0) {
            /* tty_putstr(BASE_WINDOW, 0, "Incompatible alignment!"); */
            flags.initalign = randalign(flags.
      initrole, flags.initrace);
        }
        } else { /* pick4u == 'n' */
        /* Count the number of valid alignments */
        n = 0; /* number valid */
        k = 0; /* valid alignment */
        for (i = 0; i < ROLE_ALIGNS; i++) {
            if (ok_align(flags.initrole, flags.
      initrace, flags.initgend,
                            i)) {
            n++;
            k = i;
            }
        }
        if (n == 0) {
            for (i = 0; i < ROLE_ALIGNS; i++) {
            if (validalign(flags.initrole, flags.
      initrace, i)) {
                n++;
                k = i;
            }
            }
        }
        /* Permit the user to pick, if there is more than one */
        if (n > 1) {
            /* tty_clear_nhwindow(BASE_WINDOW); */
            /* tty_putstr(BASE_WINDOW, 0, "Choosing Alignment"); */
            win = create_nhwindow(NHW_MENU);
            start_menu(win);
            any.a_void = 0; /* zero out all bits */
            for (i = 0; i < ROLE_ALIGNS; i++)
            if (ok_align(flags.initrole, flags.
      initrace,
                            flags.initgend, i)) {
                any.a_int = i+1;
                add_menu(win, NO_GLYPH, &any, aligns[i].adj[0],
                 0, ATR_NONE, aligns[i].adj, MENU_UNSELECTED);
            }
            any.a_int = pick_align(flags.initrole,
      flags.initrace,
                        flags.initgend, PICK_RANDOM)+1;
            if (any.a_int == 0) /* must be non-zero */
            any.a_int = randalign(flags.initrole,
      flags.initrace)+1;
            add_menu(win, NO_GLYPH, &any , '*', 0, ATR_NONE,
                    "Random", MENU_UNSELECTED);
            any.a_int = i+1; /* must be non-zero */
            add_menu(win, NO_GLYPH, &any , 'q', 0, ATR_NONE,
                    "Quit", MENU_UNSELECTED);
            Sprintf(pbuf, "Pick the alignment of your %s", plbuf);
            end_menu(win, pbuf);
            n = select_menu(win, PICK_ONE, &selected);
            destroy_nhwindow(win);
            if (n != 1 || selected[0].item.a_int == any.a_int)
            goto give_up; /* Selected quit */
            k = selected[0].item.a_int - 1;
            free((genericptr_t) selected), selected = 0;
        }
        flags.initalign = k;
        }
    }
    /* Success! */
    /* tty_display_nhwindow(BASE_WINDOW, FALSE); */
}
Variable Documentation
struct window_procs mswin_procs
Definition at line 40 of file mswproc.c.