nethack/win/share/tile2bmp.c File Reference
#include `hack.h`
*
#include `tile.h`
*
#include `win32api.h`
*
Data Structures
struct tagBMP
Macros
#define COLORS_IN_USE 16 /* 16 colors */
#define BITCOUNT 8
#define MAX_X 640		/* 1 per byte, 8 bits per pixel */
#define MAX_Y 480
#define PACK
#define RGBQUAD_COUNT 16
#define BMPFILESIZE (sizeof(struct tagBMP))
Functions
char * FDECL (tilename,(int, int))
static short leshort (short x)
static long lelong (long x)
static void FDECL (build_bmfh,(BITMAPFILEHEADER *))
static void FDECL (build_bmih,(BITMAPINFOHEADER *))
static void FDECL (build_bmptile,(pixel(*)[TILE_X]))
int main (int argc, argv)
static void build_bmfh (BITMAPFILEHEADER *pbmfh)
static void build_bmih (BITMAPINFOHEADER *pbmih)
static void build_bmptile (pixel *pixels)
Variables
struct tagBMP bmp
FILE * tibfile2
pixel tilepixels [TILE_Y][TILE_X]
char * tilefiles []
int num_colors = 0
int tilecount
int max_tiles_in_row = 40
int tiles_in_row
int filenum
int initflag
int yoffset
int xoffset
char bmpname [128]
FILE * fp
Macro Definition Documentation
#define BITCOUNT 8
Definition at line 27 of file tile2bmp.c.
#define BMPFILESIZE (sizeof(struct tagBMP))
Definition at line 133 of file tile2bmp.c.
Referenced by build_bmfh().
#define COLORS_IN_USE 16 /* 16 colors */
Definition at line 24 of file tile2bmp.c.
#define MAX_X 640		/* 1 per byte, 8 bits per pixel */
Definition at line 39 of file tile2bmp.c.
Referenced by build_bmih(), and main().
#define MAX_Y 480
Definition at line 40 of file tile2bmp.c.
Referenced by build_bmih(), build_bmptile(), and main().
#define PACK
Definition at line 48 of file tile2bmp.c.
#define RGBQUAD_COUNT 16
Definition at line 120 of file tile2bmp.c.
Referenced by build_bmfh(), and build_bmih().
Function Documentation
static void build_bmfh (BITMAPFILEHEADER * pbmfh) [static]
Definition at line 250 of file tile2bmp.c.
References BMPFILESIZE, lelong(), leshort(), and RGBQUAD_COUNT.
Referenced by main().
{
    pbmfh->bfType = leshort(0x4D42);
    pbmfh->bfSize = lelong(BMPFILESIZE);
    pbmfh->bfReserved1 = (UINT)0;
    pbmfh->bfReserved2 = (UINT)0;
    pbmfh->bfOffBits = lelong(sizeof(bmp.bmfh) + sizeof(bmp.bmih) +
               (RGBQUAD_COUNT * sizeof(RGBQUAD)));
}
static void build_bmih (BITMAPINFOHEADER * pbmih) [static]
Definition at line 262 of file tile2bmp.c.
References lelong(), leshort(), MAX_X, MAX_Y, and RGBQUAD_COUNT.
Referenced by main().
{
    WORD cClrBits;
    int w,h;
    pbmih->biSize = lelong(sizeof(bmp.bmih));
#if BITCOUNT==4
    pbmih->biWidth = lelong(w = MAX_X * 2);
#else
    pbmih->biWidth = lelong(w = MAX_X);
#endif
    pbmih->biHeight = lelong(h = MAX_Y);
    pbmih->biPlanes = leshort(1);
#if BITCOUNT==4
    pbmih->biBitCount = leshort(4);
    cClrBits = 4;
#else
    pbmih->biBitCount = leshort(8);
    cClrBits = 8;
#endif
    if (cClrBits == 1)
            cClrBits = 1;
    else if (cClrBits <= 4)
        cClrBits = 4;
    else if (cClrBits <= 8)
        cClrBits = 8;
    else if (cClrBits <= 16)
        cClrBits = 16;
    else if (cClrBits <= 24)
        cClrBits = 24;
    else cClrBits = 32;
    pbmih->biCompression = lelong(BI_RGB);
    pbmih->biXPelsPerMeter = lelong(0);
    pbmih->biYPelsPerMeter = lelong(0);
#if (TILE_X==32)
    if (cClrBits < 24)
            pbmih->biClrUsed = lelong(1<<cClrBits);
#else
    pbmih->biClrUsed = lelong(RGBQUAD_COUNT);
#endif
#if (TILE_X==16)
    pbmih->biSizeImage = lelong(0);
#else
    pbmih->biSizeImage = lelong(((w * cClrBits +31) & ~31) /8 * h);
#endif
    pbmih->biClrImportant = (DWORD)0;
}
static void build_bmptile (pixel * pixels) [static]
Definition at line 312 of file tile2bmp.c.
References CM_BLUE, CM_GREEN, CM_RED, ColorMap, Fprintf, MAX_Y, num_colors, pixels, TILE_X, TILE_Y, and xoffset.
Referenced by main().
{
    int cur_x, cur_y, cur_color;
    int x,y;
    for (cur_y = 0; cur_y < TILE_Y; cur_y++) {
     for (cur_x = 0; cur_x < TILE_X; cur_x++) {
      for (cur_color = 0; cur_color < num_colors; cur_color++) {
       if (ColorMap[CM_RED][cur_color] == pixels[cur_y][cur_x].r &&
          ColorMap[CM_GREEN][cur_color]== pixels[cur_y][cur_x].g &&
          ColorMap[CM_BLUE][cur_color] == pixels[cur_y][cur_x].b)
        break;
      }
      if (cur_color >= num_colors)
        Fprintf(stderr, "color not in colormap!\n");
      y = (MAX_Y - 1) - (cur_y + yoffset);
#if BITCOUNT==4
      x = (cur_x / 2) + xoffset;
      bmp.packtile[y][x] = cur_x%2 ?
        (uchar)(bmp.packtile[y][x] | cur_color) :
        (uchar)(cur_color<<4);
#else
      x = cur_x + xoffset;
      bmp.packtile[y][x] = (uchar)cur_color;
#endif
     }
    }
}
char* FDECL (tilename , (int, int))
static void FDECL (build_bmfh , (BITMAPFILEHEADER *)) [static]
static void FDECL (build_bmih , (BITMAPINFOHEADER *)) [static]
static void FDECL (build_bmptile , (pixel(*)[TILE_X])) [static]
static long lelong (long x) [static]
Definition at line 61 of file tile2bmp.c.
Referenced by build_bmfh(), and build_bmih().
{
#ifdef __BIG_ENDIAN__
    return ((x&0xff)<<24)|((x&0xff00)<<8)|((x>>8)&0xff00)|((x>>24)&0xff);
#else
    return x;
#endif
}
static short leshort (short x) [static]
Definition at line 51 of file tile2bmp.c.
Referenced by build_bmfh(), and build_bmih().
{
#ifdef __BIG_ENDIAN__
    return ((x&0xff)<<8)|((x>>8)&0xff);
#else
    return x;
#endif
}
int main (int argc, argv)
Definition at line 166 of file tile2bmp.c.
References build_bmfh(), build_bmih(), build_bmptile(), CM_BLUE, CM_GREEN, CM_RED, ColorMap, colorsinmap, exit(), EXIT_FAILURE, EXIT_SUCCESS, fclose_text_file(), filenum, fopen_text_file(), Fprintf, MAX_X, MAX_Y, num_colors, printf, RDTMODE, read_text_tile(), TILE_X, TILE_Y, and WRBMODE.
{
    int i, j;
    if (argc != 2) {
        Fprintf(stderr, "usage: %s outfile.bmp\n", argv[0]);
        exit(EXIT_FAILURE);
    } else
        strcpy(bmpname, argv[1]);
#ifdef OBSOLETE
    bmpfile2 = fopen(NETHACK_PACKED_TILEFILE, WRBMODE);
    if (bmpfile2 == (FILE *)0) {
        Fprintf(stderr, "Unable to open output file %s\n",
                NETHACK_PACKED_TILEFILE);
        exit(EXIT_FAILURE);
    }
#endif
    tilecount = 0;
    xoffset = yoffset = 0;
    initflag = 0;
    filenum = 0;
    fp = fopen(bmpname,"wb");
    if (!fp) {
        printf("Error creating tile file %s, aborting.\n",bmpname);
        exit(1);
    }
    while (filenum < (sizeof(tilefiles) / sizeof(char *))) {
        if (!fopen_text_file(tilefiles[filenum],
      RDTMODE)) {
            Fprintf(stderr,
                "usage: tile2bmp (from the util directory)\n");
            exit(EXIT_FAILURE);
        }
        num_colors = colorsinmap;
        if (num_colors > 62) {
            Fprintf(stderr, "too many colors (%d)\n", num_colors);
            exit(EXIT_FAILURE);
        }
        if (!initflag) {
            build_bmfh(&bmp.bmfh);
            build_bmih(&bmp.bmih);
            for (i = 0; i < MAX_Y; ++i)
                for (j = 0; j < MAX_X; ++j)
                    bmp.packtile[i][j] = (uchar)0;
            for (i = 0; i < num_colors; i++) {
                bmp.bmaColors[i].rgbRed = ColorMap[CM_RED][i];
                bmp.bmaColors[i].rgbGreen = ColorMap[
      CM_GREEN][i];
                bmp.bmaColors[i].rgbBlue = ColorMap[CM_BLUE][i];
                bmp.bmaColors[i].rgbReserved = 0;
            }
            initflag = 1;
        }
/* printf("Colormap initialized\n"); */
        while (read_text_tile(tilepixels)) {
            build_bmptile(tilepixels);
            tilecount++;
#if BITCOUNT==4
            xoffset += (TILE_X / 2);
#else
            xoffset += TILE_X;
#endif
            if (xoffset >= MAX_X) {
                yoffset += TILE_Y;
                xoffset = 0;
            }
        }
        (void) fclose_text_file();
        ++filenum;
    }
    fwrite(&bmp, sizeof(bmp), 1, fp);
    fclose(fp);
    Fprintf(stderr, "Total of %d tiles written to %s.\n",
        tilecount, bmpname);
    exit(EXIT_SUCCESS);
    /*NOTREACHED*/
    return 0;
}
Variable Documentation
struct tagBMP bmp
char bmpname[128]
Definition at line 162 of file tile2bmp.c.
int filenum
Definition at line 159 of file tile2bmp.c.
Referenced by main().
FILE* fp
Definition at line 163 of file tile2bmp.c.
int initflag
Definition at line 160 of file tile2bmp.c.
int max_tiles_in_row = 40
Definition at line 157 of file tile2bmp.c.
int num_colors = 0
Definition at line 155 of file tile2bmp.c.
Referenced by build_bmptile(), and main().
FILE* tibfile2
Definition at line 135 of file tile2bmp.c.
int tilecount
Definition at line 156 of file tile2bmp.c.
char* tilefiles[]
Initial value:
= {
        "../win/share/monsters.txt",
        "../win/share/objects.txt",
        "../win/share/other.txt"
}
Definition at line 143 of file tile2bmp.c.
pixel tilepixels[TILE_Y][TILE_X]
Definition at line 137 of file tile2bmp.c.
int tiles_in_row
Definition at line 158 of file tile2bmp.c.
int xoffset
Definition at line 161 of file tile2bmp.c.
Referenced by build_bmptile().
int yoffset
Definition at line 161 of file tile2bmp.c.