nethack/win/X11/tile2x11.c File Reference
#include `hack.h`
*
#include `tile.h`
*
#include `tile2x11.h`
*
Macros
#define OUTNAME `x11tiles`	/* output file name */
Functions
static unsigned char pix_to_colormap (pixel pix)
static unsigned long convert_tiles (unsigned char **tb_ptr, unsigned long total)
static void merge_text_colormap ()
static void process_file (char *fname)
int main (int argc, char **argv)
Variables
x11_header header
unsigned char tile_bytes [TILE_X *TILE_Y *(MAX_GLYPH+TILES_PER_ROW)]
unsigned char * curr_tb = tile_bytes
unsigned char x11_colormap [MAXCOLORMAPSIZE][3]
Macro Definition Documentation
#define OUTNAME `x11tiles`	/* output file name */
Definition at line 13 of file tile2x11.c.
Referenced by main().
Function Documentation
static unsigned long convert_tiles (unsigned char ** tb_ptr, unsigned long total) [static]
Definition at line 47 of file tile2x11.c.
References count, x11_header::per_row, pix_to_colormap(), read_text_tile(), tile, TILE_X, and TILE_Y.
Referenced by process_file().
{
    unsigned char *tb = *tb_ptr;
    unsigned long count = 0;
    pixel tile[TILE_Y][TILE_X];
    int x, y;
    while (read_text_tile(tile)) {
    count++;
    total++;
    for (y = 0; y < TILE_Y; y++) {
        for (x = 0; x < TILE_X; x++)
        tb[x] = pix_to_colormap(tile[y][x]);
        tb += TILE_X * header.per_row;
    }
    /* repoint at the upper-left corner of the next tile */
    *tb_ptr += TILE_X;
    if (header.per_row == 1 || (total % header.per_row) == 0)
        *tb_ptr += TILE_X * (TILE_Y - 1) * header.per_row;
    tb = *tb_ptr;
    }
    return count;
}
int main (int argc, char ** argv)
Definition at line 172 of file tile2x11.c.
References IFF::_8SVX, IFF::blen, IFF::BODY, buf, IFF::compress, exit(), IFF::flen, IFF::FORM, fp, Fprintf, IFF::freq, in, AIFF::name, IFF::NAME, IFF::name, AIFF::namelen, x11_header::ncolors, IFF::nlen, x11_header::ntiles, IFF::octaves, IFF::oneshot, OUTNAME, x11_header::per_row, process_file(), IFF::repeat, IFF::samples, AIFF::sndlen, tile_bytes, x11_header::tile_height, x11_header::tile_width, TILE_X, TILE_Y, TILES_PER_ROW, x11_header::version, IFF::VHDR, IFF::vhlen, IFF::volume, and x11_colormap.
{
    FILE *fp;
    int i;
    header.version = 2; /* version 1 had no per_row field */
    header.ncolors = 0;
    header.tile_width = TILE_X;
    header.tile_height = TILE_Y;
    header.ntiles = 0; /* updated as we read in files */
    header.per_row = TILES_PER_ROW;
    if (argc == 1) {
    Fprintf(stderr, "usage: %s txt_file1 [txt_file2 ...]\n", argv[0]);
    exit(1);
    }
    fp = fopen(OUTNAME, "w");
    if (!fp) {
    Fprintf(stderr, "can't open output file\n");
    exit(1);
    }
    /* don't leave garbage at end of partial row */
    (void) memset((genericptr_t)tile_bytes, 0, sizeof(
      tile_bytes));
    for (i = 1; i < argc; i++)
    process_file(argv[i]);
    Fprintf(stderr, "Total tiles: %ld\n", header.ntiles);
    /* round size up to the end of the row */
    if ((header.ntiles % header.per_row) != 0) {
    header.ntiles += header.per_row - (header.
      ntiles % header.per_row);
    }
#ifdef USE_XPM
    if (xpm_write(fp) == 0) {
    Fprintf(stderr, "can't write XPM file\n");
    exit(1);
    }
#else
    if (fwrite((char *)&header, sizeof(x11_header), 1, fp) == 0) {
    Fprintf(stderr, "can't open output header\n");
    exit(1);
    }
    if (fwrite((char *)x11_colormap, 1, header.ncolors*3, fp) == 0) {
    Fprintf(stderr, "can't write output colormap\n");
    exit(1);
    }
    if (fwrite((char *)tile_bytes, 1,
    (int) header.ntiles*header.tile_width*header.
      tile_height, fp) == 0) {
    Fprintf(stderr, "can't write tile bytes\n");
    exit(1);
    }
#endif
    fclose(fp);
    return 0;
}
static void merge_text_colormap () [static]
Definition at line 78 of file tile2x11.c.
References CM_BLUE, CM_GREEN, CM_RED, ColorMap, colorsinmap, exit(), Fprintf, MAXCOLORMAPSIZE, x11_header::ncolors, printf, and x11_colormap.
Referenced by process_file().
{
    int i, j;
    for (i = 0; i < colorsinmap; i++) {
    for (j = 0; j < header.ncolors; j++)
        if (x11_colormap[j][CM_RED] == ColorMap[CM_RED][i] &&
            x11_colormap[j][CM_GREEN] == ColorMap[
      CM_GREEN][i] &&
            x11_colormap[j][CM_BLUE] == ColorMap[
      CM_BLUE][i])
        break;
    if (j >= MAXCOLORMAPSIZE) {
        Fprintf(stderr, "colormap overflow\n");
        exit(1);
    }
    if (j == header.ncolors) { /* couldn't find it */
#ifdef PRINT_COLORMAP
        printf("color %2d: %3d %3d %3d\n", header.ncolors,
            ColorMap[CM_RED][i], ColorMap[CM_GREEN][i],
            ColorMap[CM_BLUE][i]);
#endif
        x11_colormap[j][CM_RED] = ColorMap[CM_RED][i];
        x11_colormap[j][CM_GREEN] = ColorMap[
      CM_GREEN][i];
        x11_colormap[j][CM_BLUE] = ColorMap[CM_BLUE][i];
        header.ncolors++;
    }
    }
}
static unsigned char pix_to_colormap (pixel pix) [static]
Definition at line 25 of file tile2x11.c.
References CM_BLUE, CM_GREEN, CM_RED, ColorMap, exit(), Fprintf, and x11_header::ncolors.
Referenced by convert_tiles().
{
    int i;
    for (i = 0; i < header.ncolors; i++) {
    if (pix.r == ColorMap[CM_RED][i] &&
        pix.g == ColorMap[CM_GREEN][i] &&
        pix.b == ColorMap[CM_BLUE][i])
        break;
    }
    if (i == header.ncolors) {
    Fprintf(stderr, "can't find color: [%u,%u,%u]\n", pix.r, pix.g, pix.
      b);
    exit(1);
    }
    return (unsigned char) (i & 0xFF);
}
static void process_file (char * fname) [static]
Definition at line 112 of file tile2x11.c.
References convert_tiles(), count, curr_tb, exit(), fclose_text_file(), fopen_text_file(), Fprintf, merge_text_colormap(), x11_header::ntiles, and RDTMODE.
Referenced by main().
{
    unsigned long count;
    if (!fopen_text_file(fname, RDTMODE)) {
    Fprintf(stderr, "can't open file \"%s\"\n", fname);
    exit(1);
    }
    merge_text_colormap();
    count = convert_tiles(&curr_tb, header.ntiles);
    Fprintf(stderr, "%s: %lu tiles\n", fname, count);
    header.ntiles += count;
    fclose_text_file();
}
Variable Documentation
unsigned char* curr_tb = tile_bytes
Definition at line 19 of file tile2x11.c.
Referenced by process_file().
x11_header header
Definition at line 17 of file tile2x11.c.
Referenced by bitmap_to_img(), and init_tiles().
unsigned char tile_bytes[TILE_X *TILE_Y *(MAX_GLYPH+TILES_PER_ROW)]
Definition at line 18 of file tile2x11.c.
Referenced by init_tiles(), and main().
unsigned char x11_colormap[MAXCOLORMAPSIZE][3]
Definition at line 20 of file tile2x11.c.
Referenced by main(), and merge_text_colormap().