nethack/sys/msdos/tile2bin.c File Reference
#include `hack.h`
*
#include `pcvideo.h`
*
#include `tile.h`
*
#include `pctiles.h`
*
#include <dos.h>
*
#include <stdlib.h>
*
#include <time.h>
*
Functions
char * FDECL (tilename,(int, int))
static void FDECL (write_tibtile,(int))
static void FDECL (write_tibheader,(FILE *, struct tibhdr_struct *))
static void FDECL (build_tibtile,(pixel(*)[TILE_X]))
int main (int argc, argv)
static void write_tibheader (FILE *fileptr, struct tibhdr_struct *tibhdr)
static void build_tibtile (pixel *pixels)
static void write_tibtile (int recnum)
Variables
int num_colors
pixel pixels [TILE_Y][TILE_X]
struct tibhdr_struct tibheader
char * tilefiles []
int tilecount
int filenum
int paletteflag
Function Documentation
static void build_tibtile (pixel * pixels) [static]
Definition at line 217 of file tile2bin.c.
References CM_BLUE, CM_GREEN, CM_RED, ColorMap, Fprintf, num_colors, TILE_X, and TILE_Y.
Referenced by main().
{
    int i, j, k, co_off;
    unsigned char co_mask,tmp;
#ifndef OVERVIEW_FILE
    memset((void *)&planetile,0,sizeof(struct planar_cell_struct));
#else
    memset((void *)&planetile,0,
        sizeof(struct overview_planar_cell_struct));
#endif
    for (j = 0; j < TILE_Y; j++) {
        for (i = 0; i < TILE_X; i++) {
            for (k = 0; k < num_colors; k++) {
                if (ColorMap[CM_RED][k] == pixels[j][i].r &&
                    ColorMap[CM_GREEN][k] == pixels[j][i].g &&
                    ColorMap[CM_BLUE][k] == pixels[j][i].b)
                    break;
            }
            if (k >= num_colors)
                Fprintf(stderr, "color not in colormap!\n");
#ifdef PACKED_FILE
            packtile[j][i] = k;
#endif
#ifdef PLANAR_FILE
            if (i > 7) {
                co_off = 1;
                co_mask = masktable[i - 8];
            } else {
                co_off = 0;
                co_mask = masktable[i];
            }
            tmp = planetile.plane[0].image[j][co_off];
            planetile.plane[0].image[j][co_off] = (k & 0x0008) ?
                (tmp | co_mask) :
                (tmp & ~co_mask);
            tmp = planetile.plane[1].image[j][co_off];
            planetile.plane[1].image[j][co_off] = (k & 0x0004) ?
                (tmp | co_mask) :
                (tmp & ~co_mask);
            tmp = planetile.plane[2].image[j][co_off];
            planetile.plane[2].image[j][co_off] = (k & 0x0002) ?
                (tmp | co_mask) :
                (tmp & ~co_mask);
            tmp = planetile.plane[3].image[j][co_off];
            planetile.plane[3].image[j][co_off] = (k & 0x0001) ?
                (tmp | co_mask) :
                (tmp & ~co_mask);
#endif /* PLANAR_FILE */
        }
    }
}
char* FDECL (tilename , (int, int))
static void FDECL (write_tibtile , (int)) [static]
static void FDECL (write_tibheader , (FILE *, struct tibhdr_struct *)) [static]
static void FDECL (build_tibtile , (pixel(*)[TILE_X])) [static]
int main (int argc, argv)
Definition at line 83 of file tile2bin.c.
References build_tibtile(), CM_BLUE, CM_GREEN, CM_RED, ColorMap, colorsinmap, exit(), EXIT_FAILURE, EXIT_SUCCESS, fclose_text_file(), filenum, fopen_text_file(), Fprintf, localtime(), num_colors, RDTMODE, read_text_tile(), tibheader, tilecount, time, WRBMODE, write_tibheader(), and write_tibtile().
{
    int i;
    struct tm *newtime;
    time_t aclock;
    char *paletteptr;
    if (argc != 1) {
        Fprintf(stderr, "usage: tile2bin (from the util directory)\n");
        exit(EXIT_FAILURE);
    }
#ifdef PLANAR_FILE
# ifndef OVERVIEW_FILE
    tibfile1 = fopen(NETHACK_PLANAR_TILEFILE, WRBMODE);
# else
    tibfile1 = fopen(NETHACK_OVERVIEW_TILEFILE, WRBMODE);
# endif
    if (tibfile1 == (FILE *)0) {
        Fprintf(stderr, "Unable to open output file %s\n",
# ifndef OVERVIEW_FILE
                NETHACK_PLANAR_TILEFILE);
#else
                NETHACK_OVERVIEW_TILEFILE);
#endif
        exit(EXIT_FAILURE);
    }
#endif
#ifdef PACKED_FILE
    tibfile2 = fopen(NETHACK_PACKED_TILEFILE, WRBMODE);
    if (tibfile2 == (FILE *)0) {
        Fprintf(stderr, "Unable to open output file %s\n",
                NETHACK_PACKED_TILEFILE);
        exit(EXIT_FAILURE);
    }
#endif
    time(&aclock);
    newtime = localtime(&aclock);
    tilecount = 0;
    paletteflag = 0;
    filenum = 0;
    while (filenum < 3) {
        if (!fopen_text_file(tilefiles[filenum],
      RDTMODE)) {
            Fprintf(stderr,
             "usage: tile2bin (from the util or src directory)\n");
            exit(EXIT_FAILURE);
        }
        num_colors = colorsinmap;
        if (num_colors > 62) {
            Fprintf(stderr, "too many colors (%d)\n", num_colors);
            exit(EXIT_FAILURE);
        }
        if (!paletteflag) {
            paletteptr = tibheader.palette;
            for (i = 0; i < num_colors; i++) {
                *paletteptr++ = ColorMap[CM_RED][i],
                *paletteptr++ = ColorMap[CM_GREEN][i],
                *paletteptr++ = ColorMap[CM_BLUE][i];
            }
            paletteflag++;
        }
                
        while (read_text_tile(pixels)) {
            build_tibtile(pixels);
            write_tibtile(tilecount);
            tilecount++;
        }
        (void) fclose_text_file();
        ++filenum;
    }
# if defined(_MSC_VER)
    tibheader.compiler = MSC_COMP;
# elif defined(__BORLANDC__)
    tibheader.compiler = BC_COMP;
# elif defined(__GO32__)
    tibheader.compiler = DJGPP_COMP;
# else
    tibheader.compiler = OTHER_COMP;
# endif
    
    strncpy(tibheader.ident,
        "NetHack 3.4 MSDOS Port binary tile file", 80);
    strncpy(tibheader.timestamp, asctime(newtime), 24);
    tibheader.timestamp[25] = '\0';
    tibheader.tilecount = tilecount;
    tibheader.numcolors = num_colors;
# ifdef PLANAR_FILE
    tibheader.tilestyle = PLANAR_STYLE;
    write_tibheader(tibfile1, &tibheader);
    (void) fclose(tibfile1);
# ifndef OVERVIEW_FILE
    Fprintf(stderr, "Total of %d planar tiles written to %s.\n",
        tilecount, NETHACK_PLANAR_TILEFILE);
# else
    Fprintf(stderr, "Total of %d planar tiles written to %s.\n",
        tilecount, NETHACK_OVERVIEW_TILEFILE);
# endif
# endif
# ifdef PACKED_FILE
    tibheader.tilestyle = PACKED_STYLE;
    write_tibheader(tibfile2, &tibheader);
    Fprintf(stderr, "Total of %d packed tiles written to %s.\n",
        tilecount, NETHACK_PACKED_TILEFILE);
    (void) fclose(tibfile2);
# endif
    exit(EXIT_SUCCESS);
    /*NOTREACHED*/
    return 0;
}
static void write_tibheader (FILE * fileptr, struct tibhdr_struct * tibhdr) [static]
Definition at line 205 of file tile2bin.c.
References Fprintf, and SEEK_SET.
Referenced by main().
{
    if (fseek(fileptr,0L,SEEK_SET)) {
        Fprintf(stderr, "Error writing header to tile file\n");
    }
    fwrite(tibhdr, sizeof(struct tibhdr_struct), 1, fileptr);
}
static void write_tibtile (int recnum) [static]
Definition at line 277 of file tile2bin.c.
References Fprintf, and SEEK_SET.
Referenced by main().
{
    long fpos;
#ifdef PLANAR_FILE
# ifndef OVERVIEW_FILE
    fpos = ((long)(recnum) * (long)sizeof(struct planar_cell_struct)) +
        (long)TIBHEADER_SIZE;
# else
    fpos = ((long)(recnum) *
            (long)sizeof(struct overview_planar_cell_struct)) +
            (long)TIBHEADER_SIZE;
# endif
    if (fseek(tibfile1,fpos,SEEK_SET)) {
        Fprintf(stderr, "Error seeking before planar tile write %d\n",
            recnum);
    }
# ifndef OVERVIEW_FILE
    fwrite(&planetile, sizeof(struct planar_cell_struct), 1, tibfile1);
# else
    fwrite(&planetile,
        sizeof(struct overview_planar_cell_struct), 1, tibfile1);
# endif
#endif
#ifdef PACKED_FILE
    fpos = ((long)(recnum) * (long)sizeof(packtile)) +
        (long)TIBHEADER_SIZE;
    if (fseek(tibfile2,fpos,SEEK_SET)) {
        Fprintf(stderr, "Error seeking before packed tile write %d\n",
            recnum);
    }
    fwrite(&packtile, sizeof(packtile), 1, tibfile2);
#endif
}
Variable Documentation
int filenum
Definition at line 79 of file tile2bin.c.
Referenced by main().
int num_colors
Definition at line 60 of file tile2bin.c.
Referenced by build_tibtile(), and main().
int paletteflag
Definition at line 80 of file tile2bin.c.
pixel pixels[TILE_Y][TILE_X]
Definition at line 61 of file tile2bin.c.
struct tibhdr_struct tibheader
Definition at line 62 of file tile2bin.c.
Referenced by main().
int tilecount
Definition at line 78 of file tile2bin.c.
Referenced by main().
char* tilefiles[]
Initial value:
= { "../win/share/monsters.txt",
            "../win/share/objects.txt",
            "../win/share/other.txt"}
Definition at line 69 of file tile2bin.c.