nethack/win/share/tilemap.c File Reference
#include `hack.h`
*
Data Structures
struct conditionals
struct substitute
Macros
#define MON_GLYPH 1
#define OBJ_GLYPH 2
#define OTH_GLYPH 3	/* fortunately unnecessary */
#define TILE_FILE `tile.c`
#define SOURCE_TEMPLATE `../src/%s`
#define NUM_INVIS_TILES 1
Functions
const char * FDECL (tilename,(int, int))
void NDECL (init_tilemap)
void FDECL (process_substitutions,(FILE *))
void init_tilemap ()
void process_substitutions (FILE *ofp)
int main ()
Variables
struct conditionals conditionals []
struct substitute substitutes []
short tilemap [MAX_GLYPH]
int lastmontile
int lastobjtile
int lastothtile
const char * prolog []
const char * epilog []
Macro Definition Documentation
#define MON_GLYPH 1
Definition at line 23 of file tilemap.c.
Referenced by init_tilemap().
#define NUM_INVIS_TILES 1
Definition at line 282 of file tilemap.c.
Referenced by init_tilemap().
#define OBJ_GLYPH 2
Definition at line 24 of file tilemap.c.
Referenced by init_tilemap().
#define OTH_GLYPH 3	/* fortunately unnecessary */
Definition at line 25 of file tilemap.c.
Referenced by init_tilemap().
#define SOURCE_TEMPLATE `../src/%s`
Definition at line 274 of file tilemap.c.
Referenced by main().
#define TILE_FILE `tile.c`
Definition at line 266 of file tilemap.c.
Referenced by main().
Function Documentation
const char* FDECL (tilename , (int, int))
void FDECL (process_substitutions , (FILE *))
void init_tilemap ()
Definition at line 295 of file tilemap.c.
References EXPL_MAX, GLYPH_BODY_OFF, GLYPH_CMAP_OFF, GLYPH_DETECT_OFF, GLYPH_EXPLODE_OFF, GLYPH_INVISIBLE, GLYPH_MON_OFF, GLYPH_OBJ_OFF, GLYPH_PET_OFF, GLYPH_RIDDEN_OFF, GLYPH_SWALLOW_OFF, GLYPH_WARNING_OFF, GLYPH_ZAP_OFF, MAX_GLYPH, MAXEXPCHARS, MAXPCHARS, MON_GLYPH, NUM_INVIS_TILES, NUM_ZAP, OBJ_GLYPH, OTH_GLYPH, S_sw_tl, conditionals::sequence, and WARNCOUNT.
Referenced by main().
{
    int i, j, condnum, tilenum;
    int corpsetile, swallowbase;
    for (i = 0; i < MAX_GLYPH; i++) {
        tilemap[i] = -1;
    }
    corpsetile = NUMMONS + NUM_INVIS_TILES + CORPSE;
    swallowbase= NUMMONS + NUM_INVIS_TILES + NUM_OBJECTS +
      S_sw_tl;
    /* add number compiled out */
    for (i = 0; conditionals[i].sequence; i++) {
        switch (conditionals[i].sequence) {
            case MON_GLYPH:
                corpsetile++;
                swallowbase++;
                break;
            case OBJ_GLYPH:
                if (conditionals[i].predecessor < CORPSE)
                    corpsetile++;
                swallowbase++;
                break;
            case OTH_GLYPH:
                if (conditionals[i].predecessor < S_sw_tl)
                    swallowbase++;
                break;
        }
    }
    condnum = tilenum = 0;
    for (i = 0; i < NUMMONS; i++) {
        tilemap[GLYPH_MON_OFF+i] = tilenum;
        tilemap[GLYPH_PET_OFF+i] = tilenum;
        tilemap[GLYPH_DETECT_OFF+i] = tilenum;
        tilemap[GLYPH_RIDDEN_OFF+i] = tilenum;
        tilemap[GLYPH_BODY_OFF+i] = corpsetile;
        j = GLYPH_SWALLOW_OFF + 8*i;
        tilemap[j] = swallowbase;
        tilemap[j+1] = swallowbase+1;
        tilemap[j+2] = swallowbase+2;
        tilemap[j+3] = swallowbase+3;
        tilemap[j+4] = swallowbase+4;
        tilemap[j+5] = swallowbase+5;
        tilemap[j+6] = swallowbase+6;
        tilemap[j+7] = swallowbase+7;
        tilenum++;
        while (conditionals[condnum].sequence == MON_GLYPH &&
            conditionals[condnum].predecessor == i) {
            condnum++;
            tilenum++;
        }
    }
    tilemap[GLYPH_INVISIBLE] = tilenum++;
    lastmontile = tilenum - 1;
    for (i = 0; i < NUM_OBJECTS; i++) {
        tilemap[GLYPH_OBJ_OFF+i] = tilenum;
        tilenum++;
        while (conditionals[condnum].sequence == OBJ_GLYPH &&
            conditionals[condnum].predecessor == i) {
            condnum++;
            tilenum++;
        }
    }
    lastobjtile = tilenum - 1;
    for (i = 0; i < (MAXPCHARS - MAXEXPCHARS); i++) {
        tilemap[GLYPH_CMAP_OFF+i] = tilenum;
        tilenum++;
        while (conditionals[condnum].sequence == OTH_GLYPH &&
            conditionals[condnum].predecessor == i) {
            condnum++;
            tilenum++;
        }
    }
    for (i = 0; i < (MAXEXPCHARS * EXPL_MAX); i++) {
        tilemap[GLYPH_EXPLODE_OFF+i] = tilenum;
        tilenum++;
        while (conditionals[condnum].sequence == OTH_GLYPH &&
            conditionals[condnum].predecessor == (i + MAXPCHARS)) {
            condnum++;
            tilenum++;
        }
    }
    for (i = 0; i < NUM_ZAP << 2; i++) {
        tilemap[GLYPH_ZAP_OFF+i] = tilenum;
        tilenum++;
        while (conditionals[condnum].sequence == OTH_GLYPH &&
            conditionals[condnum].predecessor == (i + MAXEXPCHARS)) {
            condnum++;
            tilenum++;
        }
    }
    for (i = 0; i < WARNCOUNT; i++) {
        tilemap[GLYPH_WARNING_OFF+i] = tilenum;
        tilenum++;
    }
    lastothtile = tilenum - 1;
}
int main (void)
Definition at line 490 of file tilemap.c.
References exit(), EXIT_FAILURE, EXIT_SUCCESS, filename, init_tilemap(), MAX_GLYPH, ofp, perror, process_substitutions(), SOURCE_TEMPLATE, Sprintf, and TILE_FILE.
{
    register int i;
    char filename[30];
    FILE *ofp;
    init_tilemap();
    /*
     * create the source file, "tile.c"
     */
    Sprintf(filename, SOURCE_TEMPLATE, TILE_FILE);
    if (!(ofp = fopen(filename, "w"))) {
        perror(filename);
        exit(EXIT_FAILURE);
    }
    fprintf(ofp,"/* This file is automatically generated. Do not edit. */\n");
    fprintf(ofp,"\n#include \"hack.h\"\n\n");
    fprintf(ofp,"short glyph2tile[MAX_GLYPH] = {\n");
    for (i = 0; i < MAX_GLYPH; i++) {
    fprintf(ofp,"%2d,%c", tilemap[i], (i % 12) ? ' ' : '\n');
    }
    fprintf(ofp,"%s};\n", (i % 12) ? "\n" : "");
    process_substitutions(ofp);
    fprintf(ofp,"\n#define MAXMONTILE %d\n", lastmontile);
    fprintf(ofp,"#define MAXOBJTILE %d\n", lastobjtile);
    fprintf(ofp,"#define MAXOTHTILE %d\n", lastothtile);
    fprintf(ofp,"\n/*tile.c*/\n");
    fclose(ofp);
    exit(EXIT_SUCCESS);
    /*NOTREACHED*/
    return 0;
}
void NDECL (init_tilemap)
void process_substitutions (FILE * ofp)
Definition at line 418 of file tilemap.c.
References substitute::first_glyph, substitute::last_glyph, SIZE, and substitutes.
Referenced by main().
{
    int i, j, k, span, start;
    fprintf(ofp, "\n\n");
    j = 0; /* unnecessary */
    span = -1;
    for (i = 0; i < SIZE(substitutes); i++) {
        if (i == 0
        || substitutes[i].first_glyph != substitutes[j].first_glyph
        || substitutes[i].last_glyph != substitutes[j].last_glyph) {
            j = i;
            span++;
            fprintf(ofp, "short std_tiles%d[] = { ", span);
            for (k = substitutes[i].first_glyph;
                k < substitutes[i].last_glyph; k++)
                    fprintf(ofp, "%d, ", tilemap[k]);
            fprintf(ofp, "%d };\n",
                tilemap[substitutes[i].last_glyph]);
        }
    }
    for (i = 0; i < SIZE(prolog); i++) {
        fprintf(ofp, "%s\n", prolog[i]);
    }
    j = -1;
    span = -1;
    start = lastothtile + 1;
    for (i = 0; i < SIZE(substitutes); i++) {
        if (i == 0
            || substitutes[i].first_glyph != substitutes[j].first_glyph
            || substitutes[i].last_glyph != substitutes[j].last_glyph) {
        if (i != 0) { /* finish previous span */
            fprintf(ofp, "\t} else {\n");
            fprintf(ofp, "\t\tfor (i = %d; i <= %d; i++)\n",
                    substitutes[j].first_glyph,
                    substitutes[j].last_glyph);
            fprintf(ofp, "\t\t\tglyph2tile[i] = std_tiles%d[i - %d];\n",
                    span, substitutes[j].first_glyph);
            fprintf(ofp, "\t}\n\n");
        }
        j = i;
        span++;
        }
        if (i != j) fprintf(ofp, "\t} else ");
        fprintf(ofp, "\tif (%s) {\n", substitutes[i].level_test);
        fprintf(ofp, "\t\tfor (i = %d; i <= %d; i++)\n",
                substitutes[i].first_glyph,
                substitutes[i].last_glyph);
        fprintf(ofp, "\t\t\tglyph2tile[i] = %d + i - %d;\n",
                start, substitutes[i].first_glyph);
        start += substitutes[i].last_glyph - substitutes[i].
      first_glyph + 1;
    }
    /* finish last span */
    fprintf(ofp, "\t} else {\n");
    fprintf(ofp, "\t\tfor (i = %d; i <= %d; i++)\n",
                substitutes[j].first_glyph,
                substitutes[j].last_glyph);
    fprintf(ofp, "\t\t\tglyph2tile[i] = std_tiles%d[i - %d];\n",
                span, substitutes[j].first_glyph);
    fprintf(ofp, "\t}\n\n");
    for (i = 0; i < SIZE(epilog); i++) {
        fprintf(ofp, "%s\n", epilog[i]);
    }
    fprintf(ofp, "\nint total_tiles_used = %d;\n", start);
    lastothtile = start - 1;
}
Variable Documentation
struct conditionals conditionals[]
const char* epilog[]
Initial value:
= {
    "}"
}
Definition at line 412 of file tilemap.c.
int lastmontile
Definition at line 279 of file tilemap.c.
int lastobjtile
Definition at line 279 of file tilemap.c.
int lastothtile
Definition at line 279 of file tilemap.c.
const char* prolog[]
Initial value:
= {
    "",
    "",
    "void",
    "substitute_tiles(plev)",
    "d_level *plev;",
    "{",
    "\tint i;",
    ""
}
Definition at line 401 of file tilemap.c.
struct substitute substitutes[]
Initial value:
= {
    { GLYPH_CMAP_OFF + S_vwall, GLYPH_CMAP_OFF +
      S_trwall,
                    "mine walls", "In_mines(plev)" },
    { GLYPH_CMAP_OFF + S_vwall, GLYPH_CMAP_OFF +
      S_trwall,
                    "gehennom walls", "In_hell(plev)" },
    { GLYPH_CMAP_OFF + S_vwall, GLYPH_CMAP_OFF +
      S_trwall,
                    "knox walls", "Is_knox(plev)" },
    { GLYPH_CMAP_OFF + S_vwall, GLYPH_CMAP_OFF +
      S_trwall,
                    "sokoban walls", "In_sokoban(plev)" }
}
Referenced by process_substitutions().
short tilemap[MAX_GLYPH]
Definition at line 278 of file tilemap.c.