nethack/win/gem/tile2img.c File Reference
#include `hack.h`
*
#include `tile.h`
*
#include `bitmfile.h`
*
Macros
#define COLORS_IN_USE 16 /* 16 colors */
#define MAX_X 320		/* 2 per byte, 4 bits per pixel */
#define MAX_Y 1200
Functions
char * FDECL (tilename,(int, int))
static void FDECL (build_ximgtile,(pixel(*)[TILE_X]))
void get_color (unsigned int colind, struct RGB *rgb)
void get_pixel (int x, int y, unsigned int *colind)
int main (int argc, argv)
static void build_ximgtile (pixel *pixels)
Variables
FILE * tibfile2
pixel tilepixels [TILE_Y][TILE_X]
char * tilefiles []
unsigned int ** Bild_daten
int num_colors = 0
int tilecount
int max_tiles_in_row = 40
int tiles_in_row
int filenum
int initflag
int yoffset
int xoffset
char bmpname [128]
FILE * fp
Macro Definition Documentation
#define COLORS_IN_USE 16 /* 16 colors */
Definition at line 19 of file tile2img.c.
#define MAX_X 320		/* 2 per byte, 4 bits per pixel */
Definition at line 28 of file tile2img.c.
Referenced by main().
#define MAX_Y 1200
Definition at line 32 of file tile2img.c.
Referenced by main().
Function Documentation
static void build_ximgtile (pixel * pixels) [static]
Definition at line 135 of file tile2img.c.
References CM_BLUE, CM_GREEN, CM_RED, ColorMap, Fprintf, num_colors, pixels, TILE_X, TILE_Y, xoffset, and yoffset.
Referenced by main().
{
    int cur_x, cur_y, cur_color;
    int x,y;
    for (cur_y = 0; cur_y < TILE_Y; cur_y++) {
        for (cur_x = 0; cur_x < TILE_X; cur_x++) {
            for (cur_color = 0; cur_color < num_colors; cur_color++) {
                if (ColorMap[CM_RED][cur_color] == pixels[cur_y][cur_x].r &&
                    ColorMap[CM_GREEN][cur_color] == pixels[cur_y][cur_x].g &&
                    ColorMap[CM_BLUE][cur_color] == pixels[cur_y][cur_x].b)
                    break;
            }
            if (cur_color >= num_colors)
                Fprintf(stderr, "color not in colormap!\n");
            y = cur_y + yoffset;
            x = cur_x + xoffset;
            Bild_daten[y][x] =cur_color;
        }
    }
}
char* FDECL (tilename , (int, int))
static void FDECL (build_ximgtile , (pixel(*)[TILE_X])) [static]
void get_color (unsigned int colind, struct RGB * rgb)
Definition at line 124 of file tile2img.c.
References RGB::b, CM_BLUE, CM_GREEN, CM_RED, ColorMap, RGB::g, and RGB::r.
Referenced by bitmap_to_file(), bitmap_to_img(), and main().
                                                    {
    rgb->r=(1000L*(long)ColorMap[CM_RED][colind])/0xFF;
    rgb->g=(1000L*(long)ColorMap[CM_GREEN][colind])/0xFF;
    rgb->b=(1000L*(long)ColorMap[CM_BLUE][colind])/0xFF;
}
void get_pixel (int x, int y, unsigned int * colind)
Definition at line 130 of file tile2img.c.
Referenced by bitmap_to_file(), bitmap_to_img(), and main().
                                                  {
    *colind=Bild_daten[y][x];
}
int main (int argc, argv)
Definition at line 54 of file tile2img.c.
References bitmap_to_file(), build_ximgtile(), colorsinmap, exit(), EXIT_FAILURE, EXIT_SUCCESS, fclose_text_file(), filenum, fopen_text_file(), Fprintf, get_color(), get_pixel(), malloc(), MAX_X, MAX_Y, printf, RDTMODE, read_text_tile(), TILE_X, TILE_Y, WRBMODE, and XIMG.
{
    int i;
    if (argc != 2) {
        Fprintf(stderr, "usage: tile2img outfile.img\n");
        exit(EXIT_FAILURE);
    } else
        strcpy(bmpname, argv[1]);
#ifdef OBSOLETE
    bmpfile2 = fopen(NETHACK_PACKED_TILEFILE, WRBMODE);
    if (bmpfile2 == (FILE *)0) {
        Fprintf(stderr, "Unable to open output file %s\n",
                NETHACK_PACKED_TILEFILE);
        exit(EXIT_FAILURE);
    }
#endif
    tilecount = 0;
    xoffset = yoffset = 0;
    initflag = 0;
    filenum = 0;
    fp = fopen(bmpname,"wb");
    if (!fp) {
        printf("Error creating tile file %s, aborting.\n",bmpname);
        exit(1);
    }
    fclose(fp);
    Bild_daten=(unsigned int **)malloc(MAX_Y*sizeof(unsigned int *));
    for(i=0;i<MAX_Y;i++)
        Bild_daten[i]=(unsigned int *)malloc(MAX_X*sizeof(unsigned int));
    while (filenum < 3) {
        if (!fopen_text_file(tilefiles[filenum],
      RDTMODE)) {
            Fprintf(stderr,
                "usage: tile2img (from the util directory)\n");
            exit(EXIT_FAILURE);
        }
        num_colors = colorsinmap;
        if (num_colors > 62) {
            Fprintf(stderr, "too many colors (%d)\n", num_colors);
            exit(EXIT_FAILURE);
        }
        while (read_text_tile(tilepixels)) {
            build_ximgtile(tilepixels);
            tilecount++;
            xoffset += TILE_X;
            if (xoffset >= MAX_X) {
                yoffset += TILE_Y;
                xoffset = 0;
            }
        }
        (void) fclose_text_file();
        ++filenum;
    }
    Fprintf(stderr, "Total of %d tiles in memory.\n",tilecount);
    bitmap_to_file(XIMG, MAX_X, (tilecount/20+1)*16, 372, 372, 4, 16,
      bmpname, get_color, get_pixel) ;
    Fprintf(stderr, "Total of %d tiles written to %s.\n",tilecount,
      bmpname);
    exit(EXIT_SUCCESS);
    /*NOTREACHED*/
    return 0;
}
Variable Documentation
unsigned int** Bild_daten
Definition at line 42 of file tile2img.c.
char bmpname[128]
Definition at line 50 of file tile2img.c.
int filenum
Definition at line 47 of file tile2img.c.
Referenced by main().
FILE* fp
Definition at line 51 of file tile2img.c.
Referenced by checkfile(), depack_img(), dowhatdoes_core(), EditColor(), fopen_config_file(), fopen_datafile(), init_tiles(), mac_display_file(), main(), read_config_file(), tgetent(), validate_prefix_locations(), and X11_display_file().
int initflag
Definition at line 48 of file tile2img.c.
int max_tiles_in_row = 40
Definition at line 45 of file tile2img.c.
int num_colors = 0
Definition at line 43 of file tile2img.c.
Referenced by build_ximgtile().
FILE* tibfile2
Definition at line 34 of file tile2img.c.
int tilecount
Definition at line 44 of file tile2img.c.
char* tilefiles[]
Initial value:
= { "..\\win\\share\\monsters.txt",
            "..\\win\\share\\objects.txt",
            "..\\win\\share\\other.txt"}
Definition at line 38 of file tile2img.c.
pixel tilepixels[TILE_Y][TILE_X]
Definition at line 36 of file tile2img.c.
int tiles_in_row
Definition at line 46 of file tile2img.c.
int xoffset
Definition at line 49 of file tile2img.c.
Referenced by build_ximgtile().
int yoffset
Definition at line 49 of file tile2img.c.
Referenced by build_ximgtile().