nethack/sys/amiga/txt2iff.c File Reference
#include <stdlib.h>
*
#include `config.h`
*
#include `tile.h`
*
#include <dos/dos.h>
*
#include <dos/dosextens.h>
*
#include <graphics/gfx.h>
*
#include <graphics/gfxbase.h>
*
#include <graphics/view.h>
*
#include <libraries/iffparse.h>
*
#include <libraries/dos.h>
*
#include <clib/dos_protos.h>
*
#include <clib/iffparse_protos.h>
*
#include <proto/exec.h>
*
#include <proto/iffparse.h>
*
#include <proto/dos.h>
*
Data Structures
struct BitMapHeader
struct AmiColorMap
Macros
#define ID_BMAP MAKE_ID('B', 'M', 'A', 'P')	/* instead of ILBM */
#define ID_BMHD MAKE_ID('B', 'M', 'H', 'D')	/* Same as ILBM */
#define ID_CAMG MAKE_ID('C', 'A', 'M', 'G')	/* Same as ILBM */
#define ID_CMAP MAKE_ID('C', 'M', 'A', 'P')	/* Same as ILBM */
#define ID_PDAT
#define ID_PLNE MAKE_ID('P', 'L', 'N', 'E')	/* The planes of the image */
#define COLS 20
#define ROWS ((tiles + COLS-1) / COLS)
#define CX_BLACK 0
#define CX_WHITE 1
#define CX_BROWN 11
#define CX_CYAN 2
#define CX_GREEN 5
#define CX_MAGENTA 10
#define CX_BLUE 4
#define CX_RED 7
Functions
void panic (const char *)
void map_colors (void)
int BestMatch (int, int, int)
int findcolor (register pixel *pix)
void packwritebody (pixel(*tile)[TILE_X], char **planes, int tileno)
void error (char *str)
main (int argc, char **argv)
long * alloc (unsigned int n)
Variables
pixval ColorMap [3][MAXCOLORMAPSIZE]
int colorsinmap
xx xx xx xx xx xx xx xx xx
struct {
 int Height
 int Width
} IFFScreen
struct Library * IFFParseBase
int nplanes
pixel pixels [TILE_Y][TILE_X]
AmiColorMap * cmap
int colrmap [] = { 0, 6, 9, 15, 4, 10, 2, 3, 5, 11, 7, 13, 8, 1, 14, 12 }
Macro Definition Documentation
#define COLS 20
Definition at line 109 of file txt2iff.c.
Referenced by main(), and packwritebody().
#define CX_BLACK 0
Definition at line 370 of file txt2iff.c.
Referenced by map_colors().
#define CX_BLUE 4
Definition at line 376 of file txt2iff.c.
Referenced by map_colors().
#define CX_BROWN 11
Definition at line 372 of file txt2iff.c.
#define CX_CYAN 2
Definition at line 373 of file txt2iff.c.
#define CX_GREEN 5
Definition at line 374 of file txt2iff.c.
Referenced by map_colors().
#define CX_MAGENTA 10
Definition at line 375 of file txt2iff.c.
#define CX_RED 7
Definition at line 377 of file txt2iff.c.
Referenced by map_colors().
#define CX_WHITE 1
Definition at line 371 of file txt2iff.c.
Referenced by map_colors().
#define ID_BMAP MAKE_ID('B', 'M', 'A', 'P')	/* instead of ILBM */
Definition at line 51 of file txt2iff.c.
Referenced by main().
#define ID_BMHD MAKE_ID('B', 'M', 'H', 'D')	/* Same as ILBM */
Definition at line 52 of file txt2iff.c.
Referenced by main().
#define ID_CAMG MAKE_ID('C', 'A', 'M', 'G')	/* Same as ILBM */
Definition at line 53 of file txt2iff.c.
Referenced by main().
#define ID_CMAP MAKE_ID('C', 'M', 'A', 'P')	/* Same as ILBM */
Definition at line 54 of file txt2iff.c.
Referenced by main().
#define ID_PDAT
Value:
MAKE_ID('P', 'D', 'A', 'T') /* Extra data describing plane
                         * size due to graphics.library
                         * rounding requirements.
                         */
Definition at line 55 of file txt2iff.c.
Referenced by main().
#define ID_PLNE MAKE_ID('P', 'L', 'N', 'E')	/* The planes of the image */
Definition at line 59 of file txt2iff.c.
Referenced by main().
#define ROWS ((tiles + COLS-1) / COLS)
Definition at line 110 of file txt2iff.c.
Referenced by main().
Function Documentation
long* alloc (unsigned int n)
Definition at line 443 of file txt2iff.c.
References error(), exit(), and malloc().
Referenced by add_id_mapping(), add_line(), add_mon_to_reg(), add_rect_to_reg(), add_region(), amii_add_menu(), amii_create_nhwindow(), amii_init_nhwindows(), amii_putstr(), append_text_buffer(), autopick(), construct_qtlist(), copy_of(), create_map_window(), create_menu_window(), create_message_window(), create_region(), create_status_window(), create_text_window(), create_widget(), filecopy(), fopen_gif_file(), fopen_ppm_file(), get_saved_games(), gnome_display_file(), gnome_player_selection(), init_extended_commands_popup(), init_oracles(), init_text(), init_text_buffer(), init_tiles(), load_common_data(), load_maze(), load_one_engraving(), load_one_monster(), load_one_object(), load_rooms(), mac_select_menu(), main(), make_menu(), make_menu_items(), mk_bubble(), mkmap(), movebubbles(), MyAllocBitMap(), next_opt(), parseoptions(), query_category(), query_objlist(), rest_regions(), restdamage(), restlevchn(), restnames(), restore_oracles(), restore_waterlevel(), set_circle_buf(), set_duplicate_opt_detection(), tmp_at(), wc_set_font_name(), wc_set_window_colors(), X11_add_menu(), X11_display_file(), X11_player_selection(), X11_select_menu(), yy_flex_alloc(), yylex(), and yyparse().
{
    long *ret = malloc(n);
    if(!ret){
    error("Can't allocate memory");
    exit(1);
    }
    return(ret);
}
BestMatch (int r, int g, int b)
Definition at line 419 of file txt2iff.c.
References CM_BLUE, CM_GREEN, CM_RED, ColorMap, and printf.
Referenced by map_colors().
{
    int x;
    int bestslot;
    int bestrate=99999999L;
    for(x=0;x<16;x++){
        int rr = r-ColorMap[CM_RED][x];
        int gg = g-ColorMap[CM_GREEN][x];
        int bb = b-ColorMap[CM_BLUE][x];
        int rate = rr*rr + gg*gg + bb*bb;
        if(bestrate > rate){
            bestrate = rate;
            bestslot = x;
        }
    }
#ifdef DBG
    printf("map (%d,%d,%d) -> %d (error=%d)\n",r,g,b,bestslot,bestrate);
#endif
    return bestslot;
}
void error (char * str)
Definition at line 96 of file txt2iff.c.
Referenced by _mt_init_stuff(), alloc(), bitmap_to_img(), chdirx(), depack_img(), getlock(), init_objects(), mac_add_menu(), mac_clear_nhwindow(), mac_create_nhwindow(), mac_destroy_nhwindow(), mac_display_file(), mac_display_nhwindow(), mac_init_nhwindows(), mac_putstr(), main(), mread(), mswin_select_map_mode(), and packwritebody().
{
    fprintf(stderr, "ERROR: %s\n", str);
}
findcolor (register pixel * pix)
Definition at line 291 of file txt2iff.c.
References pixel::b, CM_BLUE, CM_GREEN, CM_RED, ColorMap, pixel::g, MAXCOLORMAPSIZE, and pixel::r.
Referenced by packwritebody().
{
    register int i;
    for(i = 0; i < MAXCOLORMAPSIZE; ++i)
    {
    if((pix->r == ColorMap[ CM_RED ][i]) &&
        (pix->g == ColorMap[ CM_GREEN ][i]) &&
        (pix->b == ColorMap[ CM_BLUE ][i]))
    {
        return(i);
    }
    }
    return(-1);
}
main (int argc, char ** argv)
Definition at line 112 of file txt2iff.c.
References AmiColorMap::b, Close, CM_BLUE, CM_GREEN, CM_RED, ColorMap, colorsinmap, COLS, BitMapHeader::compression, error(), exit(), fclose_text_file(), fopen_text_file(), AmiColorMap::g, BitMapHeader::h, ID_BMAP, ID_BMHD, ID_CAMG, ID_CMAP, ID_PDAT, ID_PLNE, IFFParseBase, IFFScreen, malloc(), map_colors(), BitMapHeader::masking, nplanes, BitMapHeader::nPlanes, packwritebody(), BitMapHeader::pageHeight, BitMapHeader::pageWidth, perror, planes, printf, AmiColorMap::r, read_text_tile(), BitMapHeader::reserved1, ROWS, stdout, TILE_X, TILE_Y, BitMapHeader::transparentColor, TRUE, BitMapHeader::w, BitMapHeader::x, BitMapHeader::xAspect, xsize, BitMapHeader::y, BitMapHeader::yAspect, and ysize.
{
    int colors;
    struct {
    long nplanes;
    long pbytes;
    long across;
    long down;
    long npics;
    long xsize;
    long ysize;
    } pdat;
    long pbytes; /* Bytes of data in a plane */
    int i, cnt;
    BitMapHeader bmhd;
    struct IFFHandle *iff;
    long camg = HIRES|LACE;
    int tiles=0;
    char **planes;
    if(argc != 3){
    fprintf(stderr, "Usage: %s source destination\n", argv[0]);
    exit(1);
    }
#if defined(_DCC) || defined(__GNUC__)
    IFFParseBase = OpenLibrary("iffparse.library", 0);
    if(!IFFParseBase) {
    error("unable to open iffparse.library");
    exit(1);
    }
#endif
    /* First, count the files in the file */
    if(fopen_text_file(argv[1], "r") != TRUE)
    {
    perror(argv[1]);
    return(1);
    }
    nplanes = 0;
    i = colorsinmap-1; /*IFFScreen.Colors - 1; */
    while(i != 0)
    {
    nplanes++;
    i >>= 1;
    }
    planes = malloc(nplanes * sizeof(char *));
    if(planes == 0)
    {
    error("can not allocate planes pointer");
    exit(1);
    }
    while(read_text_tile(pixels) == TRUE)
    ++tiles;
    fclose_text_file();
    IFFScreen.Width = COLS * TILE_X;
    IFFScreen.Height = ROWS * TILE_Y;
    pbytes = (COLS * ROWS * TILE_X + 15) / 16 * 2 * TILE_Y;
    for(i = 0; i < nplanes; ++i)
    {
    planes[ i ] = calloc(1, pbytes);
    if(planes[ i ] == 0)
    {
        error("can not allocate planes pointer");
        exit(1);
    }
    }
    /* Now, process it */
    if(fopen_text_file(argv[1], "r") != TRUE)
    {
    perror(argv[1]);
    return(1);
    }
    iff = AllocIFF();
    if(!iff)
    {
    error("Can not allocate IFFHandle");
    return(1);
    }
    iff->iff_Stream = Open(argv[2], MODE_NEWFILE);
    if(!iff->iff_Stream)
    {
    error("Can not open output file");
    return(1);
    }
    InitIFFasDOS(iff);
    OpenIFF(iff, IFFF_WRITE);
    PushChunk(iff, ID_BMAP, ID_FORM, IFFSIZE_UNKNOWN);
    bmhd.w = IFFScreen.Width;
    bmhd.h = IFFScreen.Height;
    bmhd.x = 0;
    bmhd.y = 0;
    bmhd.nPlanes = nplanes;
    bmhd.masking = 0;
    bmhd.compression = 0;
    bmhd.reserved1 = 0;
    bmhd.transparentColor = 0;
    bmhd.xAspect = 100;
    bmhd.yAspect = 100;
    bmhd.pageWidth = TILE_X;
    bmhd.pageHeight = TILE_Y;
    PushChunk(iff, ID_BMAP, ID_BMHD, sizeof(bmhd));
    WriteChunkBytes(iff, &bmhd, sizeof(bmhd));
    PopChunk(iff);
    PushChunk(iff, ID_BMAP, ID_CAMG, sizeof(camg));
    WriteChunkBytes(iff, &camg, sizeof(camg));
    PopChunk(iff);
    /* We need to reorder the colors to get reasonable default pens but
     * we also need to know where some of the colors are - so go find out.
     */
    map_colors();
    cmap = malloc((colors = (1L<<nplanes)) * sizeof(AmiColorMap));
    for(i = 0; i < colors; ++i)
    {
    cmap[ colrmap[ i ] ].r = ColorMap[ CM_RED ][ i ];
    cmap[ colrmap[ i ] ].g = ColorMap[ CM_GREEN ][ i ];
    cmap[ colrmap[ i ] ].b = ColorMap[ CM_BLUE ][ i ];
    }
    PushChunk(iff, ID_BMAP, ID_CMAP, IFFSIZE_UNKNOWN);
    for (i = 0; i < colors; ++i)
    WriteChunkBytes(iff, &cmap[i], 3);
    PopChunk(iff);
    cnt = 0;
    while(read_text_tile(pixels) == TRUE)
    {
    packwritebody(pixels, planes, cnt);
    if(cnt % 20 == 0)
        printf("%d..", cnt);
    ++cnt;
    fflush(stdout);
    }
    pdat.nplanes = nplanes;
    pdat.pbytes = pbytes;
    pdat.xsize = TILE_X;
    pdat.ysize = TILE_Y;
    pdat.across = COLS;
    pdat.down = ROWS;
    pdat.npics = cnt;
    PushChunk(iff, ID_BMAP, ID_PDAT, IFFSIZE_UNKNOWN);
    WriteChunkBytes(iff, &pdat, sizeof(pdat));
    PopChunk(iff);
    PushChunk(iff, ID_BMAP, ID_PLNE, IFFSIZE_UNKNOWN);
    for(i = 0; i < nplanes; ++i)
    WriteChunkBytes(iff, planes[i], pbytes);
    PopChunk(iff);
    CloseIFF(iff);
    Close(iff->iff_Stream);
    FreeIFF(iff);
    printf("\n%d tiles converted\n", cnt);
#if defined(_DCC) || defined(__GNUC__)
    CloseLibrary(IFFParseBase);
#endif
    exit(0);
}
void map_colors (void)
Definition at line 381 of file txt2iff.c.
References BestMatch(), CX_BLACK, CX_BLUE, CX_GREEN, CX_RED, CX_WHITE, panic(), printf, and tmpmap.
Referenced by main().
            {
    int x;
#if 1
int tmpmap[]={0,2,3,7,4,5,8,9,10,11,13,15,12,1,14,6};
/* still not right: gray green yellow lost somewhere? */
#else
    int tmpmap[16];
    int x,y;
    for(x=0;x<16;x++)tmpmap[x]=-1; /* set not assigned yet */
    tmpmap[BestMatch(0,0,0)] = CX_BLACK;
    tmpmap[BestMatch(255,255,255)] = CX_WHITE;
    tmpmap[BestMatch(255,0,0)] = CX_RED;
    tmpmap[BestMatch(0,255,0)] = CX_GREEN;
    tmpmap[BestMatch(0,0,255)] = CX_BLUE;
        /* clean up the rest */
    for(x=0;x<16;x++){
        for(y=0;y<16;y++)
            if(tmpmap[y]==x)goto outer_cont;
        for(y=0;y<16;y++)
            if(tmpmap[y]==-1){
                tmpmap[y]=x;
                break;
            }
        if(y==16)panic("too many colors?");
outer_cont: ;
    }
    for(x=0;x<16;x++)
        if(tmpmap[y]==-1)panic("lost color?");
#endif
    for(x=0;x<16;x++){
#ifdef DBG
        printf("final: c[%d]=%d (target: %d)\n",x,tmpmap[x],colrmap[x]);
#endif
        colrmap[x]=tmpmap[x];
    }
}
void packwritebody (pixel(*) tile[TILE_X], char ** planes, int tileno)
Definition at line 308 of file txt2iff.c.
References buf, COLS, error(), findcolor(), IFFScreen, nplanes, tile, TILE_X, and TILE_Y.
Referenced by main().
{
    register int i, j, k, col;
    register char *buf;
    register int across, rowbytes, xoff, yoff;
    /* how many tiles fit across? */
    across = COLS;
    /* How many bytes per pixel row */
    rowbytes = ((IFFScreen.Width + 15)/16)*2;
    /* How many bytes to account for y distance in planes */
    yoff = ((tileno / across) * TILE_Y) * rowbytes;
    /* How many bytes to account for x distance in planes */
    xoff = (tileno % across) * (TILE_X/8);
    /* For each row... */
    for(i = 0; i < TILE_Y; ++i)
    {
    /* For each bitplane... */
    for(k = 0; k < nplanes; ++k)
    {
        const int mask = 1l<<k;
        /* Go across the row */
        for(j = 0; j < TILE_X; j++)
        {
        col = findcolor(&tile[ i ][ j ]);
        if(col == -1)
        {
            error("can not convert pixel color to colormap index");
            return;
        }
        /* Shift the colors around to have good complements and to
         * know the dripen values.
         */
        col = colrmap[ col ];
        /* To top left corner of tile */
        buf = planes[ k ] + yoff + xoff;
        /*To i'th row of tile and the correct byte for the j'th pixel*/
        buf += (i * rowbytes) + (j/8);
        /* Or in the bit for this color */
        *buf |= (((col & mask)!=0)<<(7-(j%8)));
        }
    }
    }
}
void panic (const char * msg)
Definition at line 454 of file txt2iff.c.
References exit().
Referenced by amii_add_menu(), amii_cl_end(), amii_clear_nhwindow(), amii_create_nhwindow(), amii_curs(), amii_destroy_nhwindow(), amii_display_nhwindow(), amii_doprev_message(), amii_end_glyphout(), amii_end_menu(), amii_init_nhwindows(), amii_nh_poskey(), amii_print_glyph(), amii_putstr(), amii_select_menu(), amii_start_menu(), amiv_lprint_glyph(), amiv_start_glyphout(), append_text_buffer(), bflush(), bufon(), bwrite(), convert_line(), CountLines(), create_door(), create_monster(), create_object(), create_status_window(), create_widget(), cursor_off(), cursor_on(), dismiss_nhwindow(), DisplayData(), do_clear_area(), DoMenuScroll(), find_free_window(), find_widget(), FindLine(), fix_stair_rooms(), Fread(), get_free_room_loc(), get_location(), get_room_loc(), get_widths(), getlev(), getlock(), gnome_player_selection(), in_container(), load_maze(), load_qtlist(), MainWndProc(), makemaz(), map_colors(), mazexy(), menu_select(), mkinvpos(), move(), movebubbles(), mread(), mswin_add_text(), mswin_color_from_string(), mswin_create_nhwindow(), mswin_display_splash_window(), mswin_ext_cmd_window(), mswin_get_font(), mswin_getlin_window(), mswin_init_command_window(), mswin_init_main_window(), mswin_init_map_window(), mswin_init_menu_window(), mswin_init_message_window(), mswin_init_nhwindows(), mswin_init_RIP_window(), mswin_init_status_window(), mswin_init_text_buffer(), mswin_init_text_window(), mswin_menu_window_select_menu(), mswin_player_selection_window(), mswin_select_map_mode(), nh_append(), NHTextWndProc(), onCreate(), onMSNHCommand(), ReadTileImageFiles(), register_command_window_class(), register_map_window_class(), restlevelfile(), restlevelstate(), savelev(), search_door(), set_circle_buf(), set_widths(), SetMenuListType(), split(), steal_it(), TextWndProc(), tmp_at(), VDECL(), view_from(), wallification(), WinMain(), write_level_file(), X11_clear_nhwindow(), X11_create_nhwindow(), X11_destroy_nhwindow(), X11_display_nhwindow(), X11_player_selection(), X11_yn_function(), and x_event().
                      {
    fprintf(stderr,"PANIC: %s\n",msg);
    exit(1);
}
Variable Documentation
AmiColorMap* cmap
Definition at line 88 of file txt2iff.c.
Referenced by DoExtension(), and ReadImageFiles().
pixval ColorMap[3][MAXCOLORMAPSIZE]
Definition at line 42 of file xpm2iff.c.
Referenced by BestMatch(), build_bmptile(), build_tibtile(), build_ximgtile(), findcolor(), get_color(), main(), merge_text_colormap(), pix_to_colormap(), read_gif_tile(), ReadColorMap(), ReadInterleavedImage(), and ReadTileStrip().
int colorsinmap
Definition at line 43 of file xpm2iff.c.
Referenced by main(), merge_text_colormap(), and ReadColorMap().
int colrmap[] = { 0, 6, 9, 15, 4, 10, 2, 3, 5, 11, 7, 13, 8, 1, 14, 12 }
Definition at line 105 of file txt2iff.c.
int Height
Definition at line 40 of file txt2iff.c.
Referenced by amii_create_nhwindow().
struct Library* IFFParseBase
Referenced by main(), and ReadImageFiles().
struct { ... } IFFScreen
Referenced by main(), and packwritebody().
int nplanes
Definition at line 67 of file txt2iff.c.
Referenced by main(), and packwritebody().
pixel pixels[TILE_Y][TILE_X]
Definition at line 87 of file txt2iff.c.
Referenced by build_bmptile(), build_ximgtile(), main(), read_gif_tile(), read_text_tile(), read_txttile(), write_ppm_tile(), write_text_tile(), and write_txttile().
int Width
Definition at line 41 of file txt2iff.c.