nethack/src/u_init.c File Reference
#include `hack.h`
*
Data Structures
struct trobj
struct inv_sub
Macros
#define UNDEF_TYP 0
#define UNDEF_SPE '\177'
#define UNDEF_BLESS 2
#define B_MAJOR 0	/* two-handed sword or battle-axe */
#define B_MINOR 1	/* matched with axe or short sword */
#define C_AMMO 2
#define M_BOOK 2
#define RAN_BOW 1
#define RAN_TWO_ARROWS 2
#define RAN_ZERO_ARROWS 3
#define R_DAGGERS 1
#define S_ARROWS 3
#define W_MULTSTART 2
#define W_MULTEND 6
Functions
STATIC_DCL void FDECL (ini_inv,(struct trobj *))
STATIC_DCL void FDECL (knows_object,(int))
STATIC_DCL void FDECL (knows_class,(CHAR_P))
STATIC_DCL boolean FDECL (restricted_spell_discipline,(int))
STATIC_OVL void knows_object (int obj)
STATIC_OVL void knows_class (char sym)
void u_init ()
STATIC_OVL boolean restricted_spell_discipline (int otyp)
STATIC_OVL void ini_inv (struct trobj *trop)
Variables
static struct trobj Archeologist []
static struct trobj Barbarian []
static struct trobj Cave_man []
static struct trobj Healer []
static struct trobj Knight []
static struct trobj Monk []
static struct trobj Priest []
static struct trobj Ranger []
static struct trobj Rogue []
static struct trobj Samurai []
static struct trobj Valkyrie []
static struct trobj Wizard []
static struct trobj Tinopener []
static struct trobj Magicmarker []
static struct trobj Lamp []
static struct trobj Blindfold []
static struct trobj Instrument []
static struct trobj Xtra_food []
static struct trobj Wishing []
static struct inv_sub inv_subs []
static const struct def_skill Skill_A []
static const struct def_skill Skill_B []
static const struct def_skill Skill_C []
static const struct def_skill Skill_H []
static const struct def_skill Skill_K []
static const struct def_skill Skill_Mon []
static const struct def_skill Skill_P []
static const struct def_skill Skill_R []
static const struct def_skill Skill_Ran []
static const struct def_skill Skill_S []
static const struct def_skill Skill_V []
static const struct def_skill Skill_W []
Macro Definition Documentation
#define B_MAJOR 0	/* two-handed sword or battle-axe */
Referenced by u_init().
#define B_MINOR 1	/* matched with axe or short sword */
Referenced by u_init().
#define C_AMMO 2
Referenced by u_init().
#define M_BOOK 2
Referenced by u_init().
#define R_DAGGERS 1
Referenced by u_init().
#define RAN_BOW 1
#define RAN_TWO_ARROWS 2
Referenced by u_init().
#define RAN_ZERO_ARROWS 3
Referenced by u_init().
#define S_ARROWS 3
Referenced by u_init().
#define UNDEF_BLESS 2
Definition at line 22 of file u_init.c.
Referenced by ini_inv().
#define UNDEF_SPE '\177'
Definition at line 21 of file u_init.c.
Referenced by ini_inv().
#define UNDEF_TYP 0
Definition at line 20 of file u_init.c.
Referenced by ini_inv().
#define W_MULTEND 6
#define W_MULTSTART 2
Function Documentation
STATIC_DCL void FDECL (ini_inv , (struct trobj *))
STATIC_DCL void FDECL (knows_object , (int))
STATIC_DCL void FDECL (knows_class , (CHAR_P))
STATIC_DCL boolean FDECL (restricted_spell_discipline , (int))
STATIC_OVL void ini_inv (struct trobj * trop)
Definition at line 883 of file u_init.c.
References A_CHAOTIC, ARMOR_CLASS, COIN_CLASS, discover_object(), ELBERETH, FALSE, GEM_CLASS, initialspell(), inv_subs, is_ammo, is_boots, is_cloak, is_gloves, is_graystone, is_helmet, is_missile, is_shield, is_shirt, is_suit, is_weptool, inv_sub::item_otyp, Race::malenum, NEARDATA, NON_PM, OBJ_DESCR, objects, obj::oclass, obj::otyp, obj::owt, obj::quan, inv_sub::race_pm, restricted_spell_discipline(), RING_CLASS, ROCK, Role_if, setuqwep(), setuswapwep(), setuwep(), setworn(), SPBOOK_CLASS, obj::spe, inv_sub::subs_otyp, TOOL_CLASS, TRUE, align::type, u, you::ualign, uarm, uarmc, uarmf, uarmg, uarmh, uarms, UNDEF_BLESS, UNDEF_SPE, UNDEF_TYP, uquiver, urace, uswapwep, uwep, W_ARM, W_ARMC, W_ARMF, W_ARMG, W_ARMH, W_ARMS, and WEAPON_CLASS.
Referenced by u_init().
{
    struct obj *obj;
    int otyp, i;
    while (trop->trclass) {
        if (trop->trotyp != UNDEF_TYP) {
            otyp = (int)trop->trotyp;
            if (urace.malenum != PM_HUMAN) {
                /* substitute specific items for generic ones */
                for (i = 0; inv_subs[i].race_pm != NON_PM; ++i)
                if (inv_subs[i].race_pm == urace.malenum &&
                    otyp == inv_subs[i].item_otyp) {
                    otyp = inv_subs[i].subs_otyp;
                    break;
                }
            }
            obj = mksobj(otyp, TRUE, FALSE);
        } else { /* UNDEF_TYP */
            static NEARDATA short nocreate = STRANGE_OBJECT;
            static NEARDATA short nocreate2 = STRANGE_OBJECT;
            static NEARDATA short nocreate3 = STRANGE_OBJECT;
            static NEARDATA short nocreate4 = STRANGE_OBJECT;
        /*
         * For random objects, do not create certain overly powerful
         * items: wand of wishing, ring of levitation, or the
         * polymorph/polymorph control combination. Specific objects,
         * i.e. the discovery wishing, are still OK.
         * Also, don't get a couple of really useless items. (Note:
         * punishment isn't "useless". Some players who start out with
         * one will immediately read it and use the iron ball as a
         * weapon.)
         */
            obj = mkobj(trop->trclass, FALSE);
            otyp = obj->otyp;
            while (otyp == WAN_WISHING
                || otyp == nocreate
                || otyp == nocreate2
                || otyp == nocreate3
                || otyp == nocreate4
#ifdef ELBERETH
                || otyp == RIN_LEVITATION
#endif
                /* 'useless' items */
                || otyp == POT_HALLUCINATION
                || otyp == POT_ACID
                || otyp == SCR_AMNESIA
                || otyp == SCR_FIRE
                || otyp == SCR_BLANK_PAPER
                || otyp == SPE_BLANK_PAPER
                || otyp == RIN_AGGRAVATE_MONSTER
                || otyp == RIN_HUNGER
                || otyp == WAN_NOTHING
                /* Monks don't use weapons */
                || (otyp == SCR_ENCHANT_WEAPON &&
                    Role_if(PM_MONK))
                /* wizard patch -- they already have one */
                || (otyp == SPE_FORCE_BOLT &&
                    Role_if(PM_WIZARD))
                /* powerful spells are either useless to
                   low level players or unbalancing; also
                   spells in restricted skill categories */
                || (obj->oclass == SPBOOK_CLASS &&
                    (objects[otyp].oc_level > 3 ||
                    restricted_spell_discipline(otyp)))
                            ) {
                dealloc_obj(obj);
                obj = mkobj(trop->trclass, FALSE);
                otyp = obj->otyp;
            }
            /* Don't start with +0 or negative rings */
            if (objects[otyp].oc_charged && obj->spe <= 0)
                obj->spe = rne(3);
            /* Heavily relies on the fact that 1) we create wands
             * before rings, 2) that we create rings before
             * spellbooks, and that 3) not more than 1 object of a
             * particular symbol is to be prohibited. (For more
             * objects, we need more nocreate variables...)
             */
            switch (otyp) {
                case WAN_POLYMORPH:
                case RIN_POLYMORPH:
                case POT_POLYMORPH:
                nocreate = RIN_POLYMORPH_CONTROL;
                break;
                case RIN_POLYMORPH_CONTROL:
                nocreate = RIN_POLYMORPH;
                nocreate2 = SPE_POLYMORPH;
                nocreate3 = POT_POLYMORPH;
            }
            /* Don't have 2 of the same ring or spellbook */
            if (obj->oclass == RING_CLASS ||
                obj->oclass == SPBOOK_CLASS)
                nocreate4 = otyp;
        }
#ifdef GOLDOBJ
        if (trop->trclass == COIN_CLASS) {
            /* no "blessed" or "identified" money */
            obj->quan = u.umoney0;
        } else {
#endif
            obj->dknown = obj->bknown = obj->rknown = 1;
            if (objects[otyp].oc_uses_known) obj->known = 1;
            obj->cursed = 0;
            if (obj->opoisoned && u.ualign.type != A_CHAOTIC)
                obj->opoisoned = 0;
            if (obj->oclass == WEAPON_CLASS ||
                obj->oclass == TOOL_CLASS) {
                obj->quan = (long) trop->trquan;
                trop->trquan = 1;
            } else if (obj->oclass == GEM_CLASS &&
                is_graystone(obj) && obj->otyp != FLINT) {
                obj->quan = 1L;
            }
            if (trop->trspe != UNDEF_SPE)
                obj->spe = trop->trspe;
            if (trop->trbless != UNDEF_BLESS)
                obj->blessed = trop->trbless;
#ifdef GOLDOBJ
        }
#endif
        /* defined after setting otyp+quan + blessedness */
        obj->owt = weight(obj);
        obj = addinv(obj);
        /* Make the type known if necessary */
        if (OBJ_DESCR(objects[otyp]) && obj->known)
            discover_object(otyp, TRUE, FALSE);
        if (otyp == OIL_LAMP)
            discover_object(POT_OIL, TRUE, FALSE);
        if(obj->oclass == ARMOR_CLASS){
            if (is_shield(obj) && !uarms) {
                setworn(obj, W_ARMS);
                if (uswapwep) setuswapwep((struct obj *) 0);
            } else if (is_helmet(obj) && !uarmh)
                setworn(obj, W_ARMH);
            else if (is_gloves(obj) && !uarmg)
                setworn(obj, W_ARMG);
#ifdef TOURIST
            else if (is_shirt(obj) && !uarmu)
                setworn(obj, W_ARMU);
#endif
            else if (is_cloak(obj) && !uarmc)
                setworn(obj, W_ARMC);
            else if (is_boots(obj) && !uarmf)
                setworn(obj, W_ARMF);
            else if (is_suit(obj) && !uarm)
                setworn(obj, W_ARM);
        }
        if (obj->oclass == WEAPON_CLASS || is_weptool(obj) ||
            otyp == TIN_OPENER || otyp == FLINT || otyp == ROCK) {
            if (is_ammo(obj) || is_missile(obj)) {
            if (!uquiver) setuqwep(obj);
            } else if (!uwep) setuwep(obj);
            else if (!uswapwep) setuswapwep(obj);
        }
        if (obj->oclass == SPBOOK_CLASS &&
                obj->otyp != SPE_BLANK_PAPER)
            initialspell(obj);
#if !defined(PYRAMID_BUG) && !defined(MAC)
        if(--trop->trquan) continue; /* make a similar object */
#else
        if(trop->trquan) { /* check if zero first */
            --trop->trquan;
            if(trop->trquan)
                continue; /* make a similar object */
        }
#endif
        trop++;
    }
}
STATIC_OVL void knows_class (char sym)
Definition at line 507 of file u_init.c.
References knows_object(), and objects.
Referenced by u_init().
{
    register int ct;
    for (ct = 1; ct < NUM_OBJECTS; ct++)
        if (objects[ct].oc_class == sym && !objects[ct].oc_magic)
            knows_object(ct);
}
STATIC_OVL void knows_object (int obj)
Definition at line 496 of file u_init.c.
References discover_object(), FALSE, objects, and TRUE.
Referenced by knows_class(), and u_init().
{
    discover_object(obj,TRUE,FALSE);
    objects[obj].oc_pre_discovered = 1; /* not a "discovery" */
}
STATIC_OVL boolean restricted_spell_discipline (int otyp)
Definition at line 850 of file u_init.c.
References FALSE, P_NONE, Role_switch, def_skill::skill, Skill_A, Skill_B, Skill_C, Skill_H, Skill_K, Skill_Mon, Skill_P, Skill_R, Skill_Ran, Skill_S, Skill_V, Skill_W, spell_skilltype(), and TRUE.
Referenced by ini_inv().
{
    const struct def_skill *skills;
    int this_skill = spell_skilltype(otyp);
    switch (Role_switch) {
     case PM_ARCHEOLOGIST: skills = Skill_A; break;
     case PM_BARBARIAN: skills = Skill_B; break;
     case PM_CAVEMAN: skills = Skill_C; break;
     case PM_HEALER: skills = Skill_H; break;
     case PM_KNIGHT: skills = Skill_K; break;
     case PM_MONK: skills = Skill_Mon; break;
     case PM_PRIEST: skills = Skill_P; break;
     case PM_RANGER: skills = Skill_Ran; break;
     case PM_ROGUE: skills = Skill_R; break;
     case PM_SAMURAI: skills = Skill_S; break;
#ifdef TOURIST
     case PM_TOURIST: skills = Skill_T; break;
#endif
     case PM_VALKYRIE: skills = Skill_V; break;
     case PM_WIZARD: skills = Skill_W; break;
     default: skills = 0; break; /* lint suppression */
    }
    while (skills->skill != P_NONE) {
    if (skills->skill == this_skill) return FALSE;
    ++skills;
    }
    return TRUE;
}
void u_init ()
Definition at line 517 of file u_init.c.
References A_CON, A_CURRENT, A_MAX, A_ORIGINAL, A_STR, ABASE, aligns, AMAX, ARMOR_CLASS, B_MAJOR, B_MINOR, flag::beginner, C_AMMO, discover, d_level::dlevel, d_level::dnum, Role::enadv, Race::enadv, FALSE, flag::female, Role::femalenum, flags, FROMOUTSIDE, HJumping, RoleAdvance::infix, ini_inv(), flag::initalign, flag::initgend, RoleAdvance::inrnd, knows_class(), knows_object(), M_BOOK, Role::malenum, you::mh, you::mhmax, you::moreluck, you::mtimedone, NO_SPELL, NON_PM, you::nv_range, R_DAGGERS, Race_switch, RAN_TWO_ARROWS, RAN_ZERO_ARROWS, rn1, Role_if, Role_switch, S_ARROWS, SIZE, spl_book, time, trobj::trotyp, TRUE, you::twoweap, align::type, u, you::ualign, you::ualignbase, uarm, uarmc, uarmf, uarmg, uarmh, uarms, uball, you::ubirthday, you::ublesscnt, you::ublessed, uchain, you::udg_cnt, you::uen, you::uenmax, you::uevent, you::ugangr, you::ugifts, you::ugold, you::ugold0, you::ugrave_arise, you::uhp, you::uhpmax, uleft, you::ulevel, you::ulevelmax, you::uluck, you::ulycn, you::umonnum, you::umonster, you::umortality, you::umoved, uquiver, urace, uright, urole, you::usick_cause, you::uspellprot, you::ustuck, uswapwep, you::utolev, you::utotype, uwep, you::uz, you::uz0, Align::value, WEAPON_CLASS, wizard, and you::xray_range.
{
    register int i;
    flags.female = flags.initgend;
    flags.beginner = 1;
    /* zero u, including pointer values --
     * necessary when aborting from a failed restore */
    (void) memset((genericptr_t)&u, 0, sizeof(u));
    u.ustuck = (struct monst *)0;
#if 0 /* documentation of more zero values as desirable */
    u.usick_cause[0] = 0;
    u.uluck = u.moreluck = 0;
# ifdef TOURIST
    uarmu = 0;
# endif
    uarm = uarmc = uarmh = uarms = uarmg = uarmf = 0;
    uwep = uball = uchain = uleft = uright = 0;
    uswapwep = uquiver = 0;
    u.twoweap = 0;
    u.ublessed = 0; /* not worthy yet */
    u.ugangr = 0; /* gods not angry */
    u.ugifts = 0; /* no divine gifts bestowed */
# ifdef ELBERETH
    u.uevent.uhand_of_elbereth = 0;
# endif
    u.uevent.uheard_tune = 0;
    u.uevent.uopened_dbridge = 0;
    u.uevent.udemigod = 0; /* not a demi-god yet... */
    u.udg_cnt = 0;
    u.mh = u.mhmax = u.mtimedone = 0;
    u.uz.dnum = u.uz0.dnum = 0;
    u.utotype = 0;
#endif /* 0 */
    u.uz.dlevel = 1;
    u.uz0.dlevel = 0;
    u.utolev = u.uz;
    u.umoved = FALSE;
    u.umortality = 0;
    u.ugrave_arise = NON_PM;
    u.umonnum = u.umonster = (flags.female &&
            urole.femalenum != NON_PM) ? urole.
      femalenum :
            urole.malenum;
    set_uasmon();
    u.ulevel = 0; /* set up some of the initial attributes */
    u.uhp = u.uhpmax = newhp();
    u.uenmax = urole.enadv.infix + urace.enadv.
      infix;
    if (urole.enadv.inrnd > 0)
        u.uenmax += rnd(urole.enadv.inrnd);
    if (urace.enadv.inrnd > 0)
        u.uenmax += rnd(urace.enadv.inrnd);
    u.uen = u.uenmax;
    u.uspellprot = 0;
    adjabil(0,1);
    u.ulevel = u.ulevelmax = 1;
    init_uhunger();
    for (i = 0; i <= MAXSPELL; i++) spl_book[i].sp_id = NO_SPELL;
    u.ublesscnt = 300; /* no prayers just yet */
    u.ualignbase[A_CURRENT] = u.ualignbase[
      A_ORIGINAL] = u.ualign.type =
            aligns[flags.initalign].value;
    u.ulycn = NON_PM;
#if defined(BSD) && !defined(POSIX_TYPES)
    (void) time((long *)&u.ubirthday);
#else
    (void) time(&u.ubirthday);
#endif
    /*
     * For now, everyone starts out with a night vision range of 1 and
     * their xray range disabled.
     */
    u.nv_range = 1;
    u.xray_range = -1;
    /*** Role-specific initializations ***/
    switch (Role_switch) {
    /* rn2(100) > 50 necessary for some choices because some
     * random number generators are bad enough to seriously
     * skew the results if we use rn2(2)... --KAA
     */
    case PM_ARCHEOLOGIST:
        ini_inv(Archeologist);
        if(!rn2(10)) ini_inv(Tinopener);
        else if(!rn2(4)) ini_inv(Lamp);
        else if(!rn2(10)) ini_inv(Magicmarker);
        knows_object(SACK);
        knows_object(TOUCHSTONE);
        skill_init(Skill_A);
        break;
    case PM_BARBARIAN:
        if (rn2(100) >= 50) { /* see above comment */
            Barbarian[B_MAJOR].trotyp = BATTLE_AXE;
            Barbarian[B_MINOR].trotyp = SHORT_SWORD;
        }
        ini_inv(Barbarian);
        if(!rn2(6)) ini_inv(Lamp);
        knows_class(WEAPON_CLASS);
        knows_class(ARMOR_CLASS);
        skill_init(Skill_B);
        break;
    case PM_CAVEMAN:
        Cave_man[C_AMMO].trquan = rn1(11, 10); /* 10..20 */
        ini_inv(Cave_man);
        skill_init(Skill_C);
        break;
    case PM_HEALER:
#ifndef GOLDOBJ
        u.ugold = u.ugold0 = rn1(1000, 1001);
#else
        u.umoney0 = rn1(1000, 1001);
#endif
        ini_inv(Healer);
        if(!rn2(25)) ini_inv(Lamp);
        knows_object(POT_FULL_HEALING);
        skill_init(Skill_H);
        break;
    case PM_KNIGHT:
        ini_inv(Knight);
        knows_class(WEAPON_CLASS);
        knows_class(ARMOR_CLASS);
        /* give knights chess-like mobility
         * -- idea from wooledge@skybridge.scl.cwru.edu */
        HJumping |= FROMOUTSIDE;
        skill_init(Skill_K);
        break;
    case PM_MONK:
        switch (rn2(90) / 30) {
        case 0: Monk[M_BOOK].trotyp = SPE_HEALING; break;
        case 1: Monk[M_BOOK].trotyp = SPE_PROTECTION; break;
        case 2: Monk[M_BOOK].trotyp = SPE_SLEEP; break;
        }
        ini_inv(Monk);
        if(!rn2(5)) ini_inv(Magicmarker);
        else if(!rn2(10)) ini_inv(Lamp);
        knows_class(ARMOR_CLASS);
        skill_init(Skill_Mon);
        break;
    case PM_PRIEST:
        ini_inv(Priest);
        if(!rn2(10)) ini_inv(Magicmarker);
        else if(!rn2(10)) ini_inv(Lamp);
        knows_object(POT_WATER);
        skill_init(Skill_P);
        /* KMH, conduct --
         * Some may claim that this isn't agnostic, since they
         * are literally "priests" and they have holy water.
         * But we don't count it as such. Purists can always
         * avoid playing priests and/or confirm another player's
         * role in their YAAP.
         */
        break;
    case PM_RANGER:
        Ranger[RAN_TWO_ARROWS].trquan = rn1(10, 50);
        Ranger[RAN_ZERO_ARROWS].trquan = rn1(10, 30);
        ini_inv(Ranger);
        skill_init(Skill_Ran);
        break;
    case PM_ROGUE:
        Rogue[R_DAGGERS].trquan = rn1(10, 6);
#ifndef GOLDOBJ
        u.ugold = u.ugold0 = 0;
#else
        u.umoney0 = 0;
#endif
        ini_inv(Rogue);
        if(!rn2(5)) ini_inv(Blindfold);
        knows_object(SACK);
        skill_init(Skill_R);
        break;
    case PM_SAMURAI:
        Samurai[S_ARROWS].trquan = rn1(20, 26);
        ini_inv(Samurai);
        if(!rn2(5)) ini_inv(Blindfold);
        knows_class(WEAPON_CLASS);
        knows_class(ARMOR_CLASS);
        skill_init(Skill_S);
        break;
#ifdef TOURIST
    case PM_TOURIST:
        Tourist[T_DARTS].trquan = rn1(20, 21);
#ifndef GOLDOBJ
        u.ugold = u.ugold0 = rnd(1000);
#else
        u.umoney0 = rnd(1000);
#endif
        ini_inv(Tourist);
        if(!rn2(25)) ini_inv(Tinopener);
        else if(!rn2(25)) ini_inv(Leash);
        else if(!rn2(25)) ini_inv(Towel);
        else if(!rn2(25)) ini_inv(Magicmarker);
        skill_init(Skill_T);
        break;
#endif
    case PM_VALKYRIE:
        ini_inv(Valkyrie);
        if(!rn2(6)) ini_inv(Lamp);
        knows_class(WEAPON_CLASS);
        knows_class(ARMOR_CLASS);
        skill_init(Skill_V);
        break;
    case PM_WIZARD:
        ini_inv(Wizard);
        if(!rn2(5)) ini_inv(Magicmarker);
        if(!rn2(5)) ini_inv(Blindfold);
        skill_init(Skill_W);
        break;
    default: /* impossible */
        break;
    }
    /*** Race-specific initializations ***/
    switch (Race_switch) {
    case PM_HUMAN:
        /* Nothing special */
        break;
    case PM_ELF:
        /*
         * Elves are people of music and song, or they are warriors.
         * Non-warriors get an instrument. We use a kludge to
         * get only non-magic instruments.
         */
        if (Role_if(PM_PRIEST) || Role_if(PM_WIZARD)) {
        static int trotyp[] = {
            WOODEN_FLUTE, TOOLED_HORN, WOODEN_HARP,
            BELL, BUGLE, LEATHER_DRUM
        };
        Instrument[0].trotyp = trotyp[rn2(SIZE(trotyp))];
        ini_inv(Instrument);
        }
        /* Elves can recognize all elvish objects */
        knows_object(ELVEN_SHORT_SWORD);
        knows_object(ELVEN_ARROW);
        knows_object(ELVEN_BOW);
        knows_object(ELVEN_SPEAR);
        knows_object(ELVEN_DAGGER);
        knows_object(ELVEN_BROADSWORD);
        knows_object(ELVEN_MITHRIL_COAT);
        knows_object(ELVEN_LEATHER_HELM);
        knows_object(ELVEN_SHIELD);
        knows_object(ELVEN_BOOTS);
        knows_object(ELVEN_CLOAK);
        break;
    case PM_DWARF:
        /* Dwarves can recognize all dwarvish objects */
        knows_object(DWARVISH_SPEAR);
        knows_object(DWARVISH_SHORT_SWORD);
        knows_object(DWARVISH_MATTOCK);
        knows_object(DWARVISH_IRON_HELM);
        knows_object(DWARVISH_MITHRIL_COAT);
        knows_object(DWARVISH_CLOAK);
        knows_object(DWARVISH_ROUNDSHIELD);
        break;
    case PM_GNOME:
        break;
    case PM_ORC:
        /* compensate for generally inferior equipment */
        if (!Role_if(PM_WIZARD))
        ini_inv(Xtra_food);
        /* Orcs can recognize all orcish objects */
        knows_object(ORCISH_SHORT_SWORD);
        knows_object(ORCISH_ARROW);
        knows_object(ORCISH_BOW);
        knows_object(ORCISH_SPEAR);
        knows_object(ORCISH_DAGGER);
        knows_object(ORCISH_CHAIN_MAIL);
        knows_object(ORCISH_RING_MAIL);
        knows_object(ORCISH_HELM);
        knows_object(ORCISH_SHIELD);
        knows_object(URUK_HAI_SHIELD);
        knows_object(ORCISH_CLOAK);
        break;
    default: /* impossible */
        break;
    }
    if (discover)
        ini_inv(Wishing);
#ifdef WIZARD
    if (wizard)
        read_wizkit();
#endif
#ifndef GOLDOBJ
    u.ugold0 += hidden_gold(); /* in case sack has gold in it */
#else
    if (u.umoney0) ini_inv(Money);
    u.umoney0 += hidden_gold(); /* in case sack has gold in it */
#endif
    find_ac(); /* get initial ac value */
    init_attr(75); /* init attribute values */
    max_rank_sz(); /* set max str size for class ranks */
/*
 * Do we really need this?
 */
    for(i = 0; i < A_MAX; i++)
        if(!rn2(20)) {
        register int xd = rn2(7) - 2; /* biased variation */
        (void) adjattrib(i, xd, TRUE);
        if (ABASE(i) < AMAX(i)) AMAX(i) = ABASE(i);
        }
    /* make sure you can carry all you have - especially for Tourists */
    while (inv_weight() > 0) {
        if (adjattrib(A_STR, 1, TRUE)) continue;
        if (adjattrib(A_CON, 1, TRUE)) continue;
        /* only get here when didn't boost strength or constitution */
        break;
    }
    return;
}
Variable Documentation
struct trobj Archeologist[] [static]
Initial value:
= {
    
    { BULLWHIP, 2, WEAPON_CLASS, 1, UNDEF_BLESS },
    { LEATHER_JACKET, 0, ARMOR_CLASS, 1, UNDEF_BLESS },
    { FEDORA, 0, ARMOR_CLASS, 1, UNDEF_BLESS },
    { FOOD_RATION, 0, FOOD_CLASS, 3, 0 },
    { PICK_AXE, UNDEF_SPE, TOOL_CLASS, 1, UNDEF_BLESS },
    { TINNING_KIT, UNDEF_SPE, TOOL_CLASS, 1, UNDEF_BLESS },
    { TOUCHSTONE, 0, GEM_CLASS, 1, 0 },
    { SACK, 0, TOOL_CLASS, 1, 0 },
    { 0, 0, 0, 0, 0 }
}
Definition at line 28 of file u_init.c.
struct trobj Barbarian[] [static]
Initial value:
= {
#define B_MAJOR
#define B_MINOR
    { TWO_HANDED_SWORD, 0, WEAPON_CLASS, 1, UNDEF_BLESS },
    { AXE, 0, WEAPON_CLASS, 1, UNDEF_BLESS },
    { RING_MAIL, 0, ARMOR_CLASS, 1, UNDEF_BLESS },
    { FOOD_RATION, 0, FOOD_CLASS, 1, 0 },
    { 0, 0, 0, 0, 0 }
}
Definition at line 40 of file u_init.c.
struct trobj Blindfold[] [static]
Initial value:
= {
    { BLINDFOLD, 0, TOOL_CLASS, 1, 0 },
    { 0, 0, 0, 0, 0 }
}
Definition at line 190 of file u_init.c.
struct trobj Cave_man[] [static]
Initial value:
= {
#define C_AMMO
    { CLUB, 1, WEAPON_CLASS, 1, UNDEF_BLESS },
    { SLING, 2, WEAPON_CLASS, 1, UNDEF_BLESS },
    { FLINT, 0, GEM_CLASS, 15, UNDEF_BLESS },
    { ROCK, 0, GEM_CLASS, 3, 0 },
    { LEATHER_ARMOR, 0, ARMOR_CLASS, 1, UNDEF_BLESS },
    { 0, 0, 0, 0, 0 }
}
Definition at line 49 of file u_init.c.
struct trobj Healer[] [static]
Initial value:
= {
    { SCALPEL, 0, WEAPON_CLASS, 1, UNDEF_BLESS },
    { LEATHER_GLOVES, 1, ARMOR_CLASS, 1, UNDEF_BLESS },
    { STETHOSCOPE, 0, TOOL_CLASS, 1, 0 },
    { POT_HEALING, 0, POTION_CLASS, 4, UNDEF_BLESS },
    { POT_EXTRA_HEALING, 0, POTION_CLASS, 4, UNDEF_BLESS },
    { WAN_SLEEP, UNDEF_SPE, WAND_CLASS, 1, UNDEF_BLESS },
    
    { SPE_HEALING, 0, SPBOOK_CLASS, 1, 1 },
    { SPE_EXTRA_HEALING, 0, SPBOOK_CLASS, 1, 1 },
    { SPE_STONE_TO_FLESH, 0, SPBOOK_CLASS, 1, 1 },
    { APPLE, 0, FOOD_CLASS, 5, 0 },
    { 0, 0, 0, 0, 0 }
}
Definition at line 58 of file u_init.c.
struct trobj Instrument[] [static]
Initial value:
= {
    { WOODEN_FLUTE, 0, TOOL_CLASS, 1, 0 },
    { 0, 0, 0, 0, 0 }
}
Definition at line 194 of file u_init.c.
struct inv_sub inv_subs[] [static]
Initial value:
= {
    { PM_ELF, DAGGER, ELVEN_DAGGER },
    { PM_ELF, SPEAR, ELVEN_SPEAR },
    { PM_ELF, SHORT_SWORD, ELVEN_SHORT_SWORD },
    { PM_ELF, BOW, ELVEN_BOW },
    { PM_ELF, ARROW, ELVEN_ARROW },
    { PM_ELF, HELMET, ELVEN_LEATHER_HELM },
 
    { PM_ELF, CLOAK_OF_DISPLACEMENT, ELVEN_CLOAK },
    { PM_ELF, CRAM_RATION, LEMBAS_WAFER },
    { PM_ORC, DAGGER, ORCISH_DAGGER },
    { PM_ORC, SPEAR, ORCISH_SPEAR },
    { PM_ORC, SHORT_SWORD, ORCISH_SHORT_SWORD },
    { PM_ORC, BOW, ORCISH_BOW },
    { PM_ORC, ARROW, ORCISH_ARROW },
    { PM_ORC, HELMET, ORCISH_HELM },
    { PM_ORC, SMALL_SHIELD, ORCISH_SHIELD },
    { PM_ORC, RING_MAIL, ORCISH_RING_MAIL },
    { PM_ORC, CHAIN_MAIL, ORCISH_CHAIN_MAIL },
    { PM_DWARF, SPEAR, DWARVISH_SPEAR },
    { PM_DWARF, SHORT_SWORD, DWARVISH_SHORT_SWORD },
    { PM_DWARF, HELMET, DWARVISH_IRON_HELM },
 
 
    { PM_GNOME, BOW, CROSSBOW },
    { PM_GNOME, ARROW, CROSSBOW_BOLT },
    { NON_PM, STRANGE_OBJECT, STRANGE_OBJECT }
}
Referenced by ini_inv().
struct trobj Knight[] [static]
Initial value:
= {
    { LONG_SWORD, 1, WEAPON_CLASS, 1, UNDEF_BLESS },
    { LANCE, 1, WEAPON_CLASS, 1, UNDEF_BLESS },
    { RING_MAIL, 1, ARMOR_CLASS, 1, UNDEF_BLESS },
    { HELMET, 0, ARMOR_CLASS, 1, UNDEF_BLESS },
    { SMALL_SHIELD, 0, ARMOR_CLASS, 1, UNDEF_BLESS },
    { LEATHER_GLOVES, 0, ARMOR_CLASS, 1, UNDEF_BLESS },
    { APPLE, 0, FOOD_CLASS, 10, 0 },
    { CARROT, 0, FOOD_CLASS, 10, 0 },
    { 0, 0, 0, 0, 0 }
}
Definition at line 72 of file u_init.c.
struct trobj Lamp[] [static]
Initial value:
= {
    { OIL_LAMP, 1, TOOL_CLASS, 1, 0 },
    { 0, 0, 0, 0, 0 }
}
Definition at line 186 of file u_init.c.
struct trobj Magicmarker[] [static]
Initial value:
= {
    { MAGIC_MARKER, UNDEF_SPE, TOOL_CLASS, 1, 0 },
    { 0, 0, 0, 0, 0 }
}
Definition at line 182 of file u_init.c.
struct trobj Monk[] [static]
Initial value:
= {
#define M_BOOK
    { LEATHER_GLOVES, 2, ARMOR_CLASS, 1, UNDEF_BLESS },
    { ROBE, 1, ARMOR_CLASS, 1, UNDEF_BLESS },
    { UNDEF_TYP, UNDEF_SPE, SPBOOK_CLASS, 1, 1 },
    { UNDEF_TYP, UNDEF_SPE, SCROLL_CLASS, 1,
      UNDEF_BLESS },
    { POT_HEALING, 0, POTION_CLASS, 3, UNDEF_BLESS },
    { FOOD_RATION, 0, FOOD_CLASS, 3, 0 },
    { APPLE, 0, FOOD_CLASS, 5, UNDEF_BLESS },
    { ORANGE, 0, FOOD_CLASS, 5, UNDEF_BLESS },
    
    { FORTUNE_COOKIE, 0, FOOD_CLASS, 3, UNDEF_BLESS },
    { 0, 0, 0, 0, 0 }
}
Definition at line 83 of file u_init.c.
struct trobj Priest[] [static]
Initial value:
= {
    { MACE, 1, WEAPON_CLASS, 1, 1 },
    { ROBE, 0, ARMOR_CLASS, 1, UNDEF_BLESS },
    { SMALL_SHIELD, 0, ARMOR_CLASS, 1, UNDEF_BLESS },
    { POT_WATER, 0, POTION_CLASS, 4, 1 },
    { CLOVE_OF_GARLIC, 0, FOOD_CLASS, 1, 0 },
    { SPRIG_OF_WOLFSBANE, 0, FOOD_CLASS, 1, 0 },
    { UNDEF_TYP, UNDEF_SPE, SPBOOK_CLASS, 2,
      UNDEF_BLESS },
    { 0, 0, 0, 0, 0 }
}
Definition at line 99 of file u_init.c.
struct trobj Ranger[] [static]
Initial value:
= {
#define RAN_BOW
#define RAN_TWO_ARROWS
#define RAN_ZERO_ARROWS
    { DAGGER, 1, WEAPON_CLASS, 1, UNDEF_BLESS },
    { BOW, 1, WEAPON_CLASS, 1, UNDEF_BLESS },
    { ARROW, 2, WEAPON_CLASS, 50, UNDEF_BLESS },
    { ARROW, 0, WEAPON_CLASS, 30, UNDEF_BLESS },
    { CLOAK_OF_DISPLACEMENT, 2, ARMOR_CLASS, 1, UNDEF_BLESS },
    { CRAM_RATION, 0, FOOD_CLASS, 4, 0 },
    { 0, 0, 0, 0, 0 }
}
Definition at line 109 of file u_init.c.
struct trobj Rogue[] [static]
Initial value:
= {
#define R_DAGGERS
    { SHORT_SWORD, 0, WEAPON_CLASS, 1, UNDEF_BLESS },
    { DAGGER, 0, WEAPON_CLASS, 10, 0 },
    { LEATHER_ARMOR, 1, ARMOR_CLASS, 1, UNDEF_BLESS },
    { POT_SICKNESS, 0, POTION_CLASS, 1, 0 },
    { LOCK_PICK, 9, TOOL_CLASS, 1, 0 },
    { SACK, 0, TOOL_CLASS, 1, 0 },
    { 0, 0, 0, 0, 0 }
}
Definition at line 121 of file u_init.c.
struct trobj Samurai[] [static]
Initial value:
= {
#define S_ARROWS
    { KATANA, 0, WEAPON_CLASS, 1, UNDEF_BLESS },
    { SHORT_SWORD, 0, WEAPON_CLASS, 1, UNDEF_BLESS },
    { YUMI, 0, WEAPON_CLASS, 1, UNDEF_BLESS },
    { YA, 0, WEAPON_CLASS, 25, UNDEF_BLESS },
    { SPLINT_MAIL, 0, ARMOR_CLASS, 1, UNDEF_BLESS },
    { 0, 0, 0, 0, 0 }
}
Definition at line 131 of file u_init.c.
const struct def_skill Skill_A[] [static]
Initial value:
= {
    { P_DAGGER, P_BASIC }, { P_KNIFE, P_BASIC },
    { P_PICK_AXE, P_EXPERT }, { P_SHORT_SWORD,
      P_BASIC },
    { P_SCIMITAR, P_SKILLED }, { P_SABER,
      P_EXPERT },
    { P_CLUB, P_SKILLED }, { P_QUARTERSTAFF,
      P_SKILLED },
    { P_SLING, P_SKILLED }, { P_DART, P_BASIC },
    { P_BOOMERANG, P_EXPERT }, { P_WHIP, P_EXPERT },
    { P_UNICORN_HORN, P_SKILLED },
    { P_ATTACK_SPELL, P_BASIC }, { P_HEALING_SPELL,
      P_BASIC },
    { P_DIVINATION_SPELL, P_EXPERT}, { P_MATTER_SPELL,
      P_BASIC},
    { P_TWO_WEAPON_COMBAT, P_BASIC },
    { P_BARE_HANDED_COMBAT, P_EXPERT },
    { P_NONE, 0 }
}
Definition at line 254 of file u_init.c.
Referenced by restricted_spell_discipline().
const struct def_skill Skill_B[] [static]
Initial value:
= {
    { P_DAGGER, P_BASIC }, { P_AXE, P_EXPERT },
    { P_PICK_AXE, P_SKILLED }, { P_SHORT_SWORD,
      P_EXPERT },
    { P_BROAD_SWORD, P_SKILLED }, { P_LONG_SWORD,
      P_SKILLED },
    { P_TWO_HANDED_SWORD, P_EXPERT }, { P_SCIMITAR,
      P_SKILLED },
    { P_SABER, P_BASIC }, { P_CLUB, P_SKILLED },
    { P_MACE, P_SKILLED }, { P_MORNING_STAR,
      P_SKILLED },
    { P_FLAIL, P_BASIC }, { P_HAMMER, P_EXPERT },
    { P_QUARTERSTAFF, P_BASIC }, { P_SPEAR,
      P_SKILLED },
    { P_TRIDENT, P_SKILLED }, { P_BOW, P_BASIC },
    { P_ATTACK_SPELL, P_SKILLED },
    { P_TWO_WEAPON_COMBAT, P_BASIC },
    { P_BARE_HANDED_COMBAT, P_MASTER },
    { P_NONE, 0 }
}
Definition at line 272 of file u_init.c.
Referenced by restricted_spell_discipline().
const struct def_skill Skill_C[] [static]
Initial value:
= {
    { P_DAGGER, P_BASIC }, { P_KNIFE, P_SKILLED },
    { P_AXE, P_SKILLED }, { P_PICK_AXE, P_BASIC },
    { P_CLUB, P_EXPERT }, { P_MACE, P_EXPERT },
    { P_MORNING_STAR, P_BASIC }, { P_FLAIL,
      P_SKILLED },
    { P_HAMMER, P_SKILLED }, { P_QUARTERSTAFF,
      P_EXPERT },
    { P_POLEARMS, P_SKILLED }, { P_SPEAR,
      P_EXPERT },
    { P_JAVELIN, P_SKILLED }, { P_TRIDENT,
      P_SKILLED },
    { P_BOW, P_SKILLED }, { P_SLING, P_EXPERT },
    { P_ATTACK_SPELL, P_BASIC }, { P_MATTER_SPELL,
      P_SKILLED },
    { P_BOOMERANG, P_EXPERT }, { P_UNICORN_HORN,
      P_BASIC },
    { P_BARE_HANDED_COMBAT, P_MASTER },
    { P_NONE, 0 }
}
Definition at line 291 of file u_init.c.
Referenced by restricted_spell_discipline().
const struct def_skill Skill_H[] [static]
Initial value:
= {
    { P_DAGGER, P_SKILLED }, { P_KNIFE, P_EXPERT },
    { P_SHORT_SWORD, P_SKILLED }, { P_SCIMITAR,
      P_BASIC },
    { P_SABER, P_BASIC }, { P_CLUB, P_SKILLED },
    { P_MACE, P_BASIC }, { P_QUARTERSTAFF,
      P_EXPERT },
    { P_POLEARMS, P_BASIC }, { P_SPEAR, P_BASIC },
    { P_JAVELIN, P_BASIC }, { P_TRIDENT, P_BASIC },
    { P_SLING, P_SKILLED }, { P_DART, P_EXPERT },
    { P_SHURIKEN, P_SKILLED }, { P_UNICORN_HORN,
      P_EXPERT },
    { P_HEALING_SPELL, P_EXPERT },
    { P_BARE_HANDED_COMBAT, P_BASIC },
    { P_NONE, 0 }
}
Definition at line 306 of file u_init.c.
Referenced by restricted_spell_discipline().
const struct def_skill Skill_K[] [static]
Initial value:
= {
    { P_DAGGER, P_BASIC }, { P_KNIFE, P_BASIC },
    { P_AXE, P_SKILLED }, { P_PICK_AXE, P_BASIC },
    { P_SHORT_SWORD, P_SKILLED }, { P_BROAD_SWORD,
      P_SKILLED },
    { P_LONG_SWORD, P_EXPERT }, { P_TWO_HANDED_SWORD,
      P_SKILLED },
    { P_SCIMITAR, P_BASIC }, { P_SABER, P_SKILLED },
    { P_CLUB, P_BASIC }, { P_MACE, P_SKILLED },
    { P_MORNING_STAR, P_SKILLED }, { P_FLAIL,
      P_BASIC },
    { P_HAMMER, P_BASIC }, { P_POLEARMS,
      P_SKILLED },
    { P_SPEAR, P_SKILLED }, { P_JAVELIN, P_SKILLED },
    { P_TRIDENT, P_BASIC }, { P_LANCE, P_EXPERT },
    { P_BOW, P_BASIC }, { P_CROSSBOW, P_SKILLED },
    { P_ATTACK_SPELL, P_SKILLED }, { P_HEALING_SPELL,
      P_SKILLED },
    { P_CLERIC_SPELL, P_SKILLED },
    { P_TWO_WEAPON_COMBAT, P_SKILLED },
    { P_BARE_HANDED_COMBAT, P_EXPERT },
    { P_NONE, 0 }
}
Definition at line 320 of file u_init.c.
Referenced by restricted_spell_discipline().
const struct def_skill Skill_Mon[] [static]
Initial value:
= {
    { P_QUARTERSTAFF, P_BASIC }, { P_SPEAR,
      P_BASIC },
    { P_JAVELIN, P_BASIC }, { P_CROSSBOW,
      P_BASIC },
    { P_SHURIKEN, P_BASIC },
    { P_ATTACK_SPELL, P_BASIC }, { P_HEALING_SPELL,
      P_EXPERT },
    { P_DIVINATION_SPELL, P_BASIC },{
      P_ENCHANTMENT_SPELL, P_BASIC },
    { P_CLERIC_SPELL, P_SKILLED }, { P_ESCAPE_SPELL,
      P_BASIC },
    { P_MATTER_SPELL, P_BASIC },
    { P_MARTIAL_ARTS, P_GRAND_MASTER },
    { P_NONE, 0 }
}
Definition at line 342 of file u_init.c.
Referenced by restricted_spell_discipline().
const struct def_skill Skill_P[] [static]
Initial value:
= {
    { P_CLUB, P_EXPERT }, { P_MACE, P_EXPERT },
    { P_MORNING_STAR, P_EXPERT }, { P_FLAIL,
      P_EXPERT },
    { P_HAMMER, P_EXPERT }, { P_QUARTERSTAFF,
      P_EXPERT },
    { P_POLEARMS, P_SKILLED }, { P_SPEAR,
      P_SKILLED },
    { P_JAVELIN, P_SKILLED }, { P_TRIDENT,
      P_SKILLED },
    { P_LANCE, P_BASIC }, { P_BOW, P_BASIC },
    { P_SLING, P_BASIC }, { P_CROSSBOW, P_BASIC },
    { P_DART, P_BASIC }, { P_SHURIKEN, P_BASIC },
    { P_BOOMERANG, P_BASIC }, { P_UNICORN_HORN,
      P_SKILLED },
    { P_HEALING_SPELL, P_EXPERT }, { P_DIVINATION_SPELL,
      P_EXPERT },
    { P_CLERIC_SPELL, P_EXPERT },
    { P_BARE_HANDED_COMBAT, P_BASIC },
    { P_NONE, 0 }
}
Definition at line 354 of file u_init.c.
Referenced by restricted_spell_discipline().
const struct def_skill Skill_R[] [static]
Initial value:
= {
    { P_DAGGER, P_EXPERT }, { P_KNIFE, P_EXPERT },
    { P_SHORT_SWORD, P_EXPERT }, { P_BROAD_SWORD,
      P_SKILLED },
    { P_LONG_SWORD, P_SKILLED }, { P_TWO_HANDED_SWORD,
      P_BASIC },
    { P_SCIMITAR, P_SKILLED }, { P_SABER,
      P_SKILLED },
    { P_CLUB, P_SKILLED }, { P_MACE, P_SKILLED },
    { P_MORNING_STAR, P_BASIC }, { P_FLAIL,
      P_BASIC },
    { P_HAMMER, P_BASIC }, { P_POLEARMS, P_BASIC },
    { P_SPEAR, P_BASIC }, { P_CROSSBOW, P_EXPERT },
    { P_DART, P_EXPERT }, { P_SHURIKEN, P_SKILLED },
    { P_DIVINATION_SPELL, P_SKILLED }, {
      P_ESCAPE_SPELL, P_SKILLED },
    { P_MATTER_SPELL, P_SKILLED },
    { P_TWO_WEAPON_COMBAT, P_EXPERT },
    { P_BARE_HANDED_COMBAT, P_EXPERT },
    { P_NONE, 0 }
}
Definition at line 370 of file u_init.c.
Referenced by restricted_spell_discipline().
const struct def_skill Skill_Ran[] [static]
Initial value:
= {
    { P_DAGGER, P_EXPERT }, { P_KNIFE, P_SKILLED },
    { P_AXE, P_SKILLED }, { P_PICK_AXE, P_BASIC },
    { P_SHORT_SWORD, P_BASIC }, { P_MORNING_STAR,
      P_BASIC },
    { P_FLAIL, P_SKILLED }, { P_HAMMER, P_BASIC },
    { P_QUARTERSTAFF, P_BASIC }, { P_POLEARMS,
      P_SKILLED },
    { P_SPEAR, P_SKILLED }, { P_JAVELIN, P_EXPERT },
    { P_TRIDENT, P_BASIC }, { P_BOW, P_EXPERT },
    { P_SLING, P_EXPERT }, { P_CROSSBOW, P_EXPERT },
    { P_DART, P_EXPERT }, { P_SHURIKEN, P_SKILLED },
    { P_BOOMERANG, P_EXPERT }, { P_WHIP, P_BASIC },
    { P_HEALING_SPELL, P_BASIC },
    { P_DIVINATION_SPELL, P_EXPERT },
    { P_ESCAPE_SPELL, P_BASIC },
    { P_BARE_HANDED_COMBAT, P_BASIC },
    { P_NONE, 0 }
}
Definition at line 390 of file u_init.c.
Referenced by restricted_spell_discipline().
const struct def_skill Skill_S[] [static]
Initial value:
= {
    { P_DAGGER, P_BASIC }, { P_KNIFE, P_SKILLED },
    { P_SHORT_SWORD, P_EXPERT }, { P_BROAD_SWORD,
      P_SKILLED },
    { P_LONG_SWORD, P_EXPERT }, { P_TWO_HANDED_SWORD,
      P_EXPERT },
    { P_SCIMITAR, P_BASIC }, { P_SABER, P_BASIC },
    { P_FLAIL, P_SKILLED }, { P_QUARTERSTAFF,
      P_BASIC },
    { P_POLEARMS, P_SKILLED }, { P_SPEAR,
      P_BASIC },
    { P_JAVELIN, P_BASIC }, { P_LANCE, P_SKILLED },
    { P_BOW, P_EXPERT }, { P_SHURIKEN, P_EXPERT },
    { P_ATTACK_SPELL, P_SKILLED }, { P_CLERIC_SPELL,
      P_SKILLED },
    { P_TWO_WEAPON_COMBAT, P_EXPERT },
    { P_MARTIAL_ARTS, P_MASTER },
    { P_NONE, 0 }
}
Definition at line 411 of file u_init.c.
Referenced by restricted_spell_discipline().
const struct def_skill Skill_V[] [static]
Initial value:
= {
    { P_DAGGER, P_EXPERT }, { P_AXE, P_EXPERT },
    { P_PICK_AXE, P_SKILLED }, { P_SHORT_SWORD,
      P_SKILLED },
    { P_BROAD_SWORD, P_SKILLED }, { P_LONG_SWORD,
      P_EXPERT },
    { P_TWO_HANDED_SWORD, P_EXPERT }, { P_SCIMITAR,
      P_BASIC },
    { P_SABER, P_BASIC }, { P_HAMMER, P_EXPERT },
    { P_QUARTERSTAFF, P_BASIC }, { P_POLEARMS,
      P_SKILLED },
    { P_SPEAR, P_SKILLED }, { P_JAVELIN, P_BASIC },
    { P_TRIDENT, P_BASIC }, { P_LANCE, P_SKILLED },
    { P_SLING, P_BASIC },
    { P_ATTACK_SPELL, P_BASIC }, { P_ESCAPE_SPELL,
      P_BASIC },
    { P_TWO_WEAPON_COMBAT, P_SKILLED },
    { P_BARE_HANDED_COMBAT, P_EXPERT },
    { P_NONE, 0 }
}
Definition at line 456 of file u_init.c.
Referenced by restricted_spell_discipline().
const struct def_skill Skill_W[] [static]
Initial value:
= {
    { P_DAGGER, P_EXPERT }, { P_KNIFE, P_SKILLED },
    { P_AXE, P_SKILLED }, { P_SHORT_SWORD,
      P_BASIC },
    { P_CLUB, P_SKILLED }, { P_MACE, P_BASIC },
    { P_QUARTERSTAFF, P_EXPERT }, { P_POLEARMS,
      P_SKILLED },
    { P_SPEAR, P_BASIC }, { P_JAVELIN, P_BASIC },
    { P_TRIDENT, P_BASIC }, { P_SLING, P_SKILLED },
    { P_DART, P_EXPERT }, { P_SHURIKEN, P_BASIC },
    { P_ATTACK_SPELL, P_EXPERT }, { P_HEALING_SPELL,
      P_SKILLED },
    { P_DIVINATION_SPELL, P_EXPERT }, {
      P_ENCHANTMENT_SPELL, P_SKILLED },
    { P_CLERIC_SPELL, P_SKILLED }, { P_ESCAPE_SPELL,
      P_EXPERT },
    { P_MATTER_SPELL, P_EXPERT },
    { P_BARE_HANDED_COMBAT, P_BASIC },
    { P_NONE, 0 }
}
Definition at line 475 of file u_init.c.
Referenced by restricted_spell_discipline().
struct trobj Tinopener[] [static]
Initial value:
= {
    { TIN_OPENER, 0, TOOL_CLASS, 1, 0 },
    { 0, 0, 0, 0, 0 }
}
Definition at line 178 of file u_init.c.
struct trobj Valkyrie[] [static]
Initial value:
= {
    { LONG_SWORD, 1, WEAPON_CLASS, 1, UNDEF_BLESS },
    { DAGGER, 0, WEAPON_CLASS, 1, UNDEF_BLESS },
    { SMALL_SHIELD, 3, ARMOR_CLASS, 1, UNDEF_BLESS },
    { FOOD_RATION, 0, FOOD_CLASS, 1, 0 },
    { 0, 0, 0, 0, 0 }
}
Definition at line 153 of file u_init.c.
struct trobj Wishing[] [static]
Initial value:
= {
    { WAN_WISHING, 3, WAND_CLASS, 1, 0 },
    { 0, 0, 0, 0, 0 }
}
Definition at line 212 of file u_init.c.
struct trobj Wizard[] [static]
Initial value:
= {
#define W_MULTSTART
#define W_MULTEND
    { QUARTERSTAFF, 1, WEAPON_CLASS, 1, 1 },
    { CLOAK_OF_MAGIC_RESISTANCE, 0, ARMOR_CLASS, 1, UNDEF_BLESS },
    { UNDEF_TYP, UNDEF_SPE, WAND_CLASS, 1,
      UNDEF_BLESS },
    { UNDEF_TYP, UNDEF_SPE, RING_CLASS, 2,
      UNDEF_BLESS },
    { UNDEF_TYP, UNDEF_SPE, POTION_CLASS, 3,
      UNDEF_BLESS },
    { UNDEF_TYP, UNDEF_SPE, SCROLL_CLASS, 3,
      UNDEF_BLESS },
    { SPE_FORCE_BOLT, 0, SPBOOK_CLASS, 1, 1 },
    { UNDEF_TYP, UNDEF_SPE, SPBOOK_CLASS, 1,
      UNDEF_BLESS },
    { 0, 0, 0, 0, 0 }
}
Definition at line 160 of file u_init.c.
struct trobj Xtra_food[] [static]
Initial value:
= {
    { UNDEF_TYP, UNDEF_SPE, FOOD_CLASS, 2, 0 },
    { 0, 0, 0, 0, 0 }
}
Definition at line 198 of file u_init.c.