nethack/sys/unix/unixunix.c File Reference
#include `hack.h`
*
#include <errno.h>
*
#include <sys/stat.h>
*
#include <signal.h>
*
Functions
static int veryold (int fd)
static int eraseoldlocks ()
void getlock ()
void regularize (char *s)
Variables
int errno
static struct stat buf
Function Documentation
static int eraseoldlocks () [static]
Definition at line 70 of file unixunix.c.
References fqname(), LEVELPREFIX, lock, MAXDUNGEON, MAXLEVEL, set_levelfile_name(), and unlink().
Referenced by getlock().
{
    register int i;
    /* cannot use maxledgerno() here, because we need to find a lock name
     * before starting everything (including the dungeon initialization
     * that sets astral_level, needed for maxledgerno()) up
     */
    for(i = 1; i <= MAXDUNGEON*MAXLEVEL + 1; i++) {
        /* try to remove all */
        set_levelfile_name(lock, i);
        (void) unlink(fqname(lock, LEVELPREFIX, 0));
    }
    set_levelfile_name(lock, 0);
    if (unlink(fqname(lock, LEVELPREFIX, 0)))
        return(0); /* cannot remove it */
    return(1); /* success! */
}
void getlock (void)
Definition at line 90 of file unixunix.c.
References close(), creat(), eraseoldlocks(), errno, error(), FCMASK, fqname(), hackpid, HLOCK, iflags, isatty(), LEVELPREFIX, lock, lock_file(), LOCKPREFIX, window_procs::name, open(), perror, printf, regularize(), set_levelfile_name(), stdout, unlock_file(), veryold(), wait_synch, instance_flags::window_inited, windowprocs, write(), and yn.
{
    register int i = 0, fd, c;
    const char *fq_lock;
#ifdef TTY_GRAPHICS
    /* idea from rpick%ucqais@uccba.uc.edu
     * prevent automated rerolling of characters
     * test input (fd0) so that tee'ing output to get a screen dump still
     * works
     * also incidentally prevents development of any hack-o-matic programs
     */
    /* added check for window-system type -dlc */
    if (!strcmp(windowprocs.name, "tty"))
        if (!isatty(0))
        error("You must play from a terminal.");
#endif
    /* we ignore QUIT and INT at this point */
    if (!lock_file(HLOCK, LOCKPREFIX, 10)) {
        wait_synch();
        error("%s", "");
    }
    regularize(lock);
    set_levelfile_name(lock, 0);
    if(locknum) {
        if(locknum > 25) locknum = 25;
        do {
            lock[0] = 'a' + i++;
            fq_lock = fqname(lock, LEVELPREFIX, 0);
            if((fd = open(fq_lock, 0)) == -1) {
                if(errno == ENOENT) goto gotlock; /* no such file */
                perror(fq_lock);
                unlock_file(HLOCK);
                error("Cannot open %s", fq_lock);
            }
            if(veryold(fd) /* closes fd if true */
                            && eraseoldlocks())
                goto gotlock;
            (void) close(fd);
        } while(i < locknum);
        unlock_file(HLOCK);
        error("Too many hacks running now.");
    } else {
        fq_lock = fqname(lock, LEVELPREFIX, 0);
        if((fd = open(fq_lock, 0)) == -1) {
            if(errno == ENOENT) goto gotlock; /* no such file */
            perror(fq_lock);
            unlock_file(HLOCK);
            error("Cannot open %s", fq_lock);
        }
        if(veryold(fd) /* closes fd if true */ && eraseoldlocks())
            goto gotlock;
        (void) close(fd);
        if(iflags.window_inited) {
            c = yn("There is already a game in progress under your name. Destroy old game?");
        } else {
            (void) printf("\nThere is already a game in progress under your name.");
            (void) printf(" Destroy old game? [yn] ");
            (void) fflush(stdout);
            c = getchar();
            (void) putchar(c);
            (void) fflush(stdout);
            while (getchar() != '\n') ; /* eat rest of line and newline */
        }
        if(c == 'y' || c == 'Y')
            if(eraseoldlocks())
                goto gotlock;
            else {
                unlock_file(HLOCK);
                error("Couldn't destroy old game.");
            }
        else {
            unlock_file(HLOCK);
            error("%s", "");
        }
    }
gotlock:
    fd = creat(fq_lock, FCMASK);
    unlock_file(HLOCK);
    if(fd == -1) {
        error("cannot creat lock file (%s).", fq_lock);
    } else {
        if(write(fd, (genericptr_t) &hackpid, sizeof(hackpid))
            != sizeof(hackpid)){
            error("cannot write lock (%s)", fq_lock);
        }
        if(close(fd) == -1) {
            error("cannot close lock (%s)", fq_lock);
        }
    }
}
void regularize (char * s)
Definition at line 193 of file unixunix.c.
References COMPRESS_EXTENSION, and index().
Referenced by getlock().
{
    register char *lp;
    while((lp=index(s, '.')) || (lp=index(s, '/')) || (lp=index(s,' ')))
        *lp = '_';
#if defined(SYSV) && !defined(AIX_31) && !defined(SVR4) && !defined(LINUX) && !defined(__APPLE__)
    /* avoid problems with 14 character file name limit */
# ifdef COMPRESS
    /* leave room for .e from error and .Z from compress appended to
     * save files */
    {
# ifdef COMPRESS_EXTENSION
        int i = 12 - strlen(COMPRESS_EXTENSION);
# else
        int i = 10; /* should never happen... */
# endif
        if(strlen(s) > i)
        s[i] = '\0';
    }
# else
    if(strlen(s) > 11)
        /* leave room for .nn appended to level files */
        s[11] = '\0';
# endif
#endif
}
static int veryold (int fd) [static]
Definition at line 33 of file unixunix.c.
References buf, close(), errno, read(), and time.
Referenced by getlock().
{
    time_t date;
    if(fstat(fd, &buf)) return(0); /* cannot get status */
#ifndef INSURANCE
    if(buf.st_size != sizeof(int)) return(0); /* not an xlock file */
#endif
#if defined(BSD) && !defined(POSIX_TYPES)
    (void) time((long *)(&date));
#else
    (void) time(&date);
#endif
    if(date - buf.st_mtime < 3L*24L*60L*60L) { /* recent */
        int lockedpid; /* should be the same size as hackpid */
        if(read(fd, (genericptr_t)&lockedpid, sizeof(lockedpid)) !=
            sizeof(lockedpid))
            /* strange ... */
            return(0);
        /* From: Rick Adams <seismo!rick> */
        /* This will work on 4.1cbsd, 4.2bsd and system 3? & 5. */
        /* It will do nothing on V7 or 4.1bsd. */
#ifndef NETWORK
        /* It will do a VERY BAD THING if the playground is shared
           by more than one machine! -pem */
        if(!(kill(lockedpid, 0) == -1 && errno == ESRCH))
#endif
            return(0);
    }
    (void) close(fd);
    return(1);
}
Variable Documentation
struct stat buf [static]
Definition at line 29 of file unixunix.c.
Referenced by veryold().
int errno
Definition at line 345 of file celib.c.
Referenced by getlock(), and veryold().