nethack/sys/share/uudecode.c File Reference
#include <stdio.h>
*
#include <pwd.h>
*
#include <sys/types.h>
*
#include <sys/stat.h>
*
#include <string.h>
*
#include <stdlib.h>
*
Macros
#define DEC(c) (((c) - ' ') & 077)
#define NULL 0
Functions
static void decode (FILE *, FILE *)
static void outdec (char *, FILE *, int)
int main (int argc, char **argv)
char * index (char *sp, char c)
Variables
static char sccsid [] = `@(#)uudecode.c 5.5 (Berkeley) 7/6/88`
Macro Definition Documentation
#define DEC(c) (((c) - ' ') & 077)
Definition at line 83 of file uudecode.c.
Referenced by decode(), and outdec().
#define NULL 0
Definition at line 238 of file uudecode.c.
Referenced by decode(), index(), and main().
Function Documentation
void decode (FILE * in, FILE * out) [static]
Definition at line 175 of file uudecode.c.
References buf, DEC, exit(), NULL, outdec(), and printf.
Referenced by main().
{
    char buf[80];
    char *bp;
    int n, i, expected;
    for (;;) {
        /* for each input line */
        if (fgets(buf, sizeof buf, in) == NULL) {
            printf("Short file\n");
            exit(10);
        }
        n = DEC(buf[0]);
        if ((n <= 0) || (buf[0] == '\n'))
            break;
        /* Calculate expected # of chars and pad if necessary */
        expected = ((n+2)/3)<<2;
        for (i = strlen(buf)-1; i <= expected; i++) buf[i] = ' ';
        bp = &buf[1];
        while (n > 0) {
            outdec(bp, out, n);
            bp += 4;
            n -= 3;
        }
    }
}
char* index (char * sp, char c)
Definition at line 242 of file uudecode.c.
References NULL.
Referenced by algn_key(), allow_category(), append_text_buffer(), AppleEventHandler(), autopick(), change_inv_order(), checkfile(), choose_classes_menu(), collect_obj_classes(), dodiscovered(), DoExtension(), dowhatdoes_core(), ec_key(), escapes(), fixup_special(), fname_encode(), fopen_datafile(), fopen_xpm_file(), gend_key(), get_feature_notice_ver(), getrumor(), getspell(), gnome_yn_function(), impact_drop(), initoptions(), is_worn_by_type(), kick_object(), LayoutCmdWindow(), main(), MainWndProc(), makemaz(), map_menu_cmd(), match_optname(), menu_key(), mswin_color_from_string(), mswin_yn_function(), nhcmdset_get(), nhcmdset_get_name(), outentry(), outoracle(), parse_config_line(), parseoptions(), pick_obj(), pickup(), plnamesuffix(), prompt_for_player_selection(), prscore(), ps_key(), query_classes(), race_key(), regularize(), rloco(), score_wanted(), setComboBoxValue(), ship_object(), should_query_disclose_option(), string_for_opt(), tc_field(), tc_find(), tc_name(), tc_store(), tgetstr(), throwit(), tparam(), use_crystal_ball(), vms_creat(), X11_select_menu(), X11_yn_function(), yn_key(), and yyparse().
{
    do {
        if (*sp == c)
            return(sp);
    } while (*sp++);
    return(NULL);
}
int main (int argc, char ** argv)
Definition at line 85 of file uudecode.c.
References buf, decode(), exit(), in, index(), NULL, perror, printf, and stdin.
{
    FILE *in, *out;
    int mode;
    char dest[128];
    char buf[80];
    /* optional input arg */
    if (argc > 1) {
        if ((in = fopen(argv[1], "r")) == NULL) {
            perror(argv[1]);
            exit(1);
        }
        argv++; argc--;
    } else
        in = stdin;
    if (argc != 1) {
        printf("Usage: uudecode [infile]\n");
        exit(2);
    }
    /* search for header line */
    for (;;) {
        if (fgets(buf, sizeof buf, in) == NULL) {
            fprintf(stderr, "No begin line\n");
            exit(3);
        }
        if (strncmp(buf, "begin ", 6) == 0)
            break;
    }
    (void)sscanf(buf, "begin %o %s", &mode, dest);
#if !defined(MSDOS) && !defined(VMS) && !defined(WIN32)
    /* handle ~user/file format */
    if (dest[0] == '~') {
        char *sl;
        struct passwd *getpwnam();
        struct passwd *user;
        char dnbuf[100], *index(), *strcat(), *strcpy();
        sl = index(dest, '/');
        if (sl == NULL) {
            fprintf(stderr, "Illegal ~user\n");
            exit(3);
        }
        *sl++ = 0;
        user = getpwnam(dest+1);
        if (user == NULL) {
            fprintf(stderr, "No such user as %s\n", dest);
            exit(4);
        }
        strcpy(dnbuf, user->pw_dir);
        strcat(dnbuf, "/");
        strcat(dnbuf, sl);
        strcpy(dest, dnbuf);
    }
#endif /* !defined(MSDOS) && !defined(VMS) */
    /* create output file */
#if defined(MSDOS) || defined(WIN32)
    out = fopen(dest, "wb"); /* Binary file */
#else
    out = fopen(dest, "w");
#endif
    if (out == NULL) {
        perror(dest);
        exit(4);
    }
#if !defined(MSDOS) && !defined(VMS) && !defined(WIN32) /* i.e., UNIX */
    chmod(dest, mode);
#endif
    decode(in, out);
    if (fgets(buf, sizeof buf, in) == NULL || strcmp(buf, "end\n")) {
        fprintf(stderr, "No end line\n");
        exit(5);
    }
    exit(0);
    /*NOTREACHED*/
    return 0;
}
void outdec (char * p, FILE * f, int n) [static]
Definition at line 213 of file uudecode.c.
References DEC.
Referenced by decode().
{
    int c1, c2, c3;
    c1 = DEC(*p) << 2 | DEC(p[1]) >> 4;
    c2 = DEC(p[1]) << 4 | DEC(p[2]) >> 2;
    c3 = DEC(p[2]) << 6 | DEC(p[3]);
    if (n >= 1)
        putc(c1, f);
    if (n >= 2)
        putc(c2, f);
    if (n >= 3)
        putc(c3, f);
}
Variable Documentation
char sccsid[] = `@(#)uudecode.c 5.5 (Berkeley) 7/6/88` [static]
Definition at line 43 of file uudecode.c.