nethack/src/version.c File Reference
#include `hack.h`
*
#include `date.h`
*
#include `patchlevel.h`
*
Functions
char * version_string (char *buf)
char * getversionstring (char *buf)
int doversion ()
int doextversion ()
boolean check_version (struct version_info *version_data, const char *filename, boolean complain)
boolean uptodate (int fd, const char *name)
void store_version (int fd)
unsigned long get_feature_notice_ver (char *str)
unsigned long get_current_feature_ver ()
Function Documentation
boolean check_version (struct version_info * version_data, const char * filename, boolean complain)
Definition at line 68 of file version.c.
References FALSE, IGNORED_FEATURES, TRUE, and VERSION_COMPATIBILITY.
Referenced by load_special(), and uptodate().
{
    if (
#ifdef VERSION_COMPATIBILITY
        version_data->incarnation < VERSION_COMPATIBILITY ||
        version_data->incarnation > VERSION_NUMBER
#else
        version_data->incarnation != VERSION_NUMBER
#endif
      ) {
        if (complain)
        pline("Version mismatch for file \"%s\".", filename);
        return FALSE;
    } else if (
#ifndef IGNORED_FEATURES
           version_data->feature_set != VERSION_FEATURES ||
#else
           (version_data->feature_set & ~IGNORED_FEATURES) !=
              (VERSION_FEATURES & ~IGNORED_FEATURES) ||
#endif
           version_data->entity_count != VERSION_SANITY1 ||
           version_data->struct_sizes != VERSION_SANITY2) {
        if (complain)
        pline("Configuration incompatibility for file \"%s\".",
              filename);
        return FALSE;
    }
    return TRUE;
}
int doextversion ()
Definition at line 52 of file version.c.
References display_file, OPTIONS_USED, and TRUE.
{
    display_file(OPTIONS_USED, TRUE);
    return 0;
}
int doversion ()
Definition at line 43 of file version.c.
References buf, BUFSZ, and getversionstring().
Referenced by aboutNetHack().
{
    char buf[BUFSZ];
    pline("%s", getversionstring(buf));
    return 0;
}
unsigned long get_current_feature_ver ()
Definition at line 180 of file version.c.
References FEATURE_NOTICE_VER, PATCHLEVEL, VERSION_MAJOR, and VERSION_MINOR.
Referenced by feature_alert_opts().
{
    return FEATURE_NOTICE_VER(VERSION_MAJOR,
      VERSION_MINOR,PATCHLEVEL);
}
unsigned long get_feature_notice_ver (char * str)
Definition at line 149 of file version.c.
References buf, BUFSZ, FEATURE_NOTICE_VER, and index().
Referenced by feature_alert_opts().
{
    char buf[BUFSZ];
    int ver_maj, ver_min, patch;
    char *istr[3];
    int j = 0;
    if (!str) return 0L;
    str = strcpy(buf, str);
    istr[j] = str;
    while (*str) {
        if (*str == '.') {
            *str++ = '\0';
            j++;
            istr[j] = str;
            if (j == 2) break;
        } else if (index("0123456789", *str) != 0) {
            str++;
        } else
            return 0L;
    }
    if (j != 2) return 0L;
    ver_maj = atoi(istr[0]);
    ver_min = atoi(istr[1]);
    patch = atoi(istr[2]);
    return FEATURE_NOTICE_VER(ver_maj,ver_min,patch);
    /* macro from hack.h */
}
char* getversionstring (char * buf)
Definition at line 29 of file version.c.
References append_port_id(), buf, eos(), Sprintf, and Strcpy.
Referenced by About(), doversion(), ghack_about_cb(), and mswin_display_splash_window().
{
    Strcpy(buf, VERSION_ID);
#if defined(BETA) && defined(BETA_INFO)
    Sprintf(eos(buf), " %s", BETA_INFO);
#endif
#if defined(RUNTIME_PORT_ID)
    append_port_id(buf);
#endif
    return buf;
}
void store_version (int fd)
Definition at line 129 of file version.c.
References bufoff(), bufon(), and bwrite().
Referenced by dosave0(), and savebones().
{
    const static struct version_info version_data = {
            VERSION_NUMBER, VERSION_FEATURES,
            VERSION_SANITY1, VERSION_SANITY2
    };
    bufoff(fd);
    /* bwrite() before bufon() uses plain write() */
    bwrite(fd,(genericptr_t)&version_data,(unsigned)(sizeof version_data));
    bufon(fd);
    return;
}
boolean uptodate (int fd, const char * name)
Definition at line 104 of file version.c.
References check_version(), FALSE, minit(), read(), TRUE, and wait_synch.
Referenced by dorecover(), getbones(), restlevelfile(), and restore_saved_game().
{
    int rlen;
    struct version_info vers_info;
    boolean verbose = name ? TRUE : FALSE;
    rlen = read(fd, (genericptr_t) &vers_info, sizeof vers_info);
    minit(); /* ZEROCOMP */
    if (rlen == 0) {
    if (verbose) {
        pline("File \"%s\" is empty?", name);
        wait_synch();
    }
    return FALSE;
    }
    if (!check_version(&vers_info, name, verbose)) {
    if (verbose) wait_synch();
    return FALSE;
    }
    return TRUE;
}
char* version_string (char * buf)
Definition at line 21 of file version.c.
Referenced by paniclog().
{
    return strcpy(buf, VERSION_STRING);
}