nethack/sys/vms/vmsfiles.c File Reference
#include `config.h`
*
#include <ctype.h>
*
#include <rms.h>
*
#include <errno.h>
*
#include <ssdef.h>
*
#include <rmsdef.h>
*
Macros
#define PSL $C_EXEC 1	/* executive mode, for priv'd logical name handling */
#define C $$TRANSLATE(status) (errno = EVMSERR, vaxc$errno = (status))
#define vms_success(sts) ((sts)&1)		/* odd, */
#define vms_failure(sts) (!vms_success(sts))	/* even */
#define VALUE(U) trans = U; break
#define CASE1(V) case (V >> 3)
#define CASE2(V, W) CASE1(V): CASE1(W)
Functions
int FDECL (vms_link,(const char *, const char *))
int FDECL (vms_unlink,(const char *))
int FDECL (vms_creat,(const char *, unsigned int))
int FDECL (vms_open,(const char *, int, unsigned int))
boolean FDECL (same_dir,(const char *, const char *))
int FDECL (c__translate,(int))
char * FDECL (vms_basename,(const char *))
unsigned long sys $parse ()
unsigned long sys sys $search ()
unsigned long sys sys sys $enter ()
unsigned long sys sys sys sys $remove ()
int VDECL (lib $match_cond,(int, int,...))
int vms_link (char *file, char *new) const
int vms_unlink (char *file) const
int vms_creat (char *file, unsigned int mode) const
int vms_open (char *file, int flags, unsigned int mode) const
boolean same_dir (char *d1, char *d2) const
int c__translate (int code)
char * vms_basename (char *name) const
Variables
static char base_name [NAM $C_MAXRSS+1]
Macro Definition Documentation
#define C $$TRANSLATE(status) (errno = EVMSERR, vaxc$errno = (status))
Definition at line 29 of file vmsfiles.c.
Referenced by vms_link(), and vms_unlink().
#define CASE1(V) case (V >> 3)
Definition at line 206 of file vmsfiles.c.
Referenced by c__translate().
#define CASE2(V, W) CASE1(V): CASE1(W)
Definition at line 207 of file vmsfiles.c.
Referenced by c__translate().
#define PSL $C_EXEC 1	/* executive mode, for priv'd logical name handling */
Definition at line 25 of file vmsfiles.c.
Referenced by same_dir().
#define VALUE(U) trans = U; break
Definition at line 205 of file vmsfiles.c.
Referenced by c__translate().
#define vms_failure(sts) (!vms_success(sts))	/* even */
Definition at line 35 of file vmsfiles.c.
Referenced by vms_link(), and vms_unlink().
#define vms_success(sts) ((sts)&1)		/* odd, */
Definition at line 34 of file vmsfiles.c.
Referenced by same_dir(), and vms_link().
Function Documentation
unsigned long sys sys sys $enter ()
Referenced by vms_link().
unsigned long sys $parse ()
Referenced by same_dir(), vms_link(), and vms_unlink().
unsigned long sys sys sys sys $remove ()
Referenced by vms_unlink().
unsigned long sys sys $search ()
Referenced by vms_link().
int c__translate (int code)
Definition at line 209 of file vmsfiles.c.
References CASE1, CASE2, errno, and VALUE.
{
    register int trans;
    switch ((code & 0x0FFFFFF8) >> 3) { /* strip upper 4 and bottom 3 bits */
    CASE2(RMS$_PRV,SS$_NOPRIV):
                VALUE(EPERM); /* not owner */
    CASE2(RMS$_DNF,RMS$_DIR):
    CASE2(RMS$_FNF,RMS$_FND):
    CASE1(SS$_NOSUCHFILE):
                VALUE(ENOENT); /* no such file or directory */
    CASE2(RMS$_IFI,RMS$_ISI):
                VALUE(EIO); /* i/o error */
    CASE1(RMS$_DEV):
    CASE2(SS$_NOSUCHDEV,SS$_DEVNOTMOUNT):
                VALUE(ENXIO); /* no such device or address codes */
    CASE1(RMS$_DME):
     /* CASE1(LIB$INSVIRMEM): */
    CASE2(SS$_VASFULL,SS$_INSFWSL):
                VALUE(ENOMEM); /* not enough core */
    CASE1(SS$_ACCVIO):
                VALUE(EFAULT); /* bad address */
    CASE2(RMS$_DNR,SS$_DEVASSIGN):
    CASE2(SS$_DEVALLOC,SS$_DEVALRALLOC):
    CASE2(SS$_DEVMOUNT,SS$_DEVACTIVE):
                VALUE(EBUSY); /* mount device busy codes to name a few */
    CASE2(RMS$_FEX,SS$_FILALRACC):
                VALUE(EEXIST); /* file exists */
    CASE2(RMS$_IDR,SS$_BADIRECTORY):
                VALUE(ENOTDIR); /* not a directory */
    CASE1(SS$_NOIOCHAN):
                VALUE(EMFILE); /* too many open files */
    CASE1(RMS$_FUL):
    CASE2(SS$_DEVICEFULL,SS$_EXDISKQUOTA):
                VALUE(ENOSPC); /* no space left on disk codes */
    CASE2(RMS$_WLK,SS$_WRITLCK):
                VALUE(EROFS); /* read-only file system */
    default:
                VALUE(EVMSERR);
    };
    errno = trans;
    vaxc$errno = code;
    return code; /* (not very useful) */
}
int FDECL (vms_link , (const char *, const char *))
int FDECL (vms_unlink , (const char *))
int FDECL (vms_creat , (const char *, unsigned int))
int FDECL (vms_open , (const char *, int, unsigned int))
boolean FDECL (same_dir , (const char *, const char *))
int FDECL (c__translate , (int))
char* FDECL (vms_basename , (const char *))
boolean same_dir (char * d1, char * d2) const
Definition at line 157 of file vmsfiles.c.
References $parse(), FAB, FALSE, PSL, TRUE, and vms_success.
{
    if (!d1 || !*d1 || !d2 || !*d2)
    return FALSE;
    else if (!strcmp(d1, d2)) /* strcmpi() would be better, but that leads */
    return TRUE; /* to linking problems for the utilities */
    else {
    struct FAB f1, f2;
    struct NAM n1, n2;
    f1 = f2 = cc$rms_fab; /* initialize file access block */
    n1 = n2 = cc$rms_nam; /* initialize name block */
    f1.fab$b_acmodes = PSL$C_EXEC << FAB$V_LNM_MODE;
    f1.fab$b_fns = strlen(f1.fab$l_fna = (char *)d1);
    f2.fab$b_fns = strlen(f2.fab$l_fna = (char *)d2);
    f1.fab$l_nam = (genericptr_t)&n1; /* link nam to fab */
    f2.fab$l_nam = (genericptr_t)&n2;
    n1.nam$b_nop = n2.nam$b_nop = NAM$M_NOCONCEAL; /* want true device name */
    return (vms_success(sys$parse(&f1)) && vms_success(sys
      $parse(&f2))
         && n1.nam$t_dvi[0] == n2.nam$t_dvi[0]
         && !strncmp(&n1.nam$t_dvi[1], &n2.nam$t_dvi[1], n1.nam$t_dvi[0])
         && !memcmp((genericptr_t)n1.nam$w_did,
            (genericptr_t)n2.nam$w_did,
            sizeof n1.nam$w_did)); /*{ short nam$w_did[3]; }*/
    }
}
int VDECL (lib $match_cond, (int, int,...))
char* vms_basename (char * name) const
Definition at line 264 of file vmsfiles.c.
References name.
Referenced by main().
{
    unsigned len;
    char *base, *base_p;
    register const char *name_p;
    /* skip directory/path */
    if ((name_p = strrchr(name, ']')) != 0) name = name_p + 1;
    if ((name_p = strrchr(name, '>')) != 0) name = name_p + 1;
    if ((name_p = strrchr(name, ':')) != 0) name = name_p + 1;
    if ((name_p = strrchr(name, '/')) != 0) name = name_p + 1;
    if (!*name) name = "."; /* this should never happen */
    /* find extension/version and derive length of basename */
    if ((name_p = strchr(name, '.')) == 0 || name_p == name)
    name_p = strchr(name, ';');
    len = (name_p && name_p > name) ? name_p - name : strlen(name);
    /* return a lowercase copy of the name in a private static buffer */
    base = strncpy(base_name, name, len);
    base[len] = '\0';
    /* we don't use lcase() so that utilities won't need hacklib.c */
    for (base_p = base; base_p < &base[len]; base_p++)
    if (isupper(*base_p)) *base_p = tolower(*base_p);
    return base;
}
int vms_creat (char * file, unsigned int mode) const
Definition at line 116 of file vmsfiles.c.
References creat(), index(), and unlink().
{
    if (index(file, ';')) {
    /* assumes remove or delete, not vms_unlink */
    if (!unlink(file)) {
        (void)sleep(1);
        (void)unlink(file);
    }
    }
    return creat(file, mode, "shr=nil", "mbc=32", "mbf=2", "rop=wbh");
}
int vms_link (char * file, char * new) const
Definition at line 38 of file vmsfiles.c.
References $enter(), $parse(), $search(), C, FAB, vms_failure, and vms_success.
{
    struct FAB fab;
    struct NAM nam;
    unsigned short fid[3];
    char esa[NAM$C_MAXRSS];
    fab = cc$rms_fab; /* set block ID and length, zero the rest */
    fab.fab$l_fop = FAB$M_OFP;
    fab.fab$l_fna = (char *) file;
    fab.fab$b_fns = strlen(file);
    fab.fab$l_nam = &nam;
    nam = cc$rms_nam;
    nam.nam$l_esa = esa;
    nam.nam$b_ess = sizeof esa;
    if (vms_success(sys$parse(&fab)) && vms_success(sys
      $search(&fab))) {
    fid[0] = nam.nam$w_fid[0];
    fid[1] = nam.nam$w_fid[1];
    fid[2] = nam.nam$w_fid[2];
    fab.fab$l_fna = (char *) new;
    fab.fab$b_fns = strlen(new);
    if (vms_success(sys$parse(&fab))) {
        nam.nam$w_fid[0] = fid[0];
        nam.nam$w_fid[1] = fid[1];
        nam.nam$w_fid[2] = fid[2];
        nam.nam$l_esa = nam.nam$l_name;
        nam.nam$b_esl = nam.nam$b_name + nam.nam$b_type + nam.nam$b_ver;
        (void) sys$enter(&fab);
    }
    }
    if (vms_failure(fab.fab$l_sts)) {
    C$$TRANSLATE(fab.fab$l_sts);
    return -1;
    }
    return 0; /* success */
}
int vms_open (char * file, int flags, unsigned int mode) const
Definition at line 136 of file vmsfiles.c.
References errno, and open().
{
    int fd = open(file, flags, mode, "mbc=32", "mbf=2", "rop=rah");
    if (fd < 0 && errno == EVMSERR && lib$match_cond(vaxc$errno, RMS$_FLK)) {
    (void)sleep(1);
    fd = open(file, flags, mode, "mbc=32", "mbf=2", "rop=rah");
    }
    return fd;
}
int vms_unlink (char * file) const
Definition at line 85 of file vmsfiles.c.
References $parse(), $remove(), C, FAB, and vms_failure.
{
    struct FAB fab;
    struct NAM nam;
    char esa[NAM$C_MAXRSS];
    fab = cc$rms_fab; /* set block ID and length, zero the rest */
    fab.fab$l_fop = FAB$M_DLT;
    fab.fab$l_fna = (char *) file;
    fab.fab$b_fns = strlen(file);
    fab.fab$l_nam = &nam;
    nam = cc$rms_nam;
    nam.nam$l_esa = esa;
    nam.nam$b_ess = sizeof esa;
    if (vms_failure(sys$parse(&fab)) || vms_failure(sys
      $remove(&fab))) {
    C$$TRANSLATE(fab.fab$l_sts);
    return -1;
    }
    return 0;
}
Variable Documentation
char base_name[NAM $C_MAXRSS+1] [static]
Definition at line 260 of file vmsfiles.c.