nethack/sys/vms/vmsmisc.c File Reference
#include <ssdef.h>
*
#include <stsdef.h>
*
Functions
void vms_exit ()
void vms_abort ()
void exit ()
void lib $signal ()
void vms_exit (int status)
Function Documentation
void lib $signal ()
Referenced by vms_abort().
void exit ()
Referenced by Abort(), alloc(), copy_bytes(), decode(), do_data(), do_date(), do_dungeon(), do_makedefs(), do_monstr(), do_objs(), do_options(), do_oracles(), do_permonst(), do_questtxt(), do_rumors(), do_vision(), fopen_gif_file(), fopen_xpm_file(), init_branch(), init_dungeon(), init_level(), LWZReadByte(), main(), MainWndProc(), merge_text_colormap(), nethack_exit(), output_dgn(), panic(), parse_args(), pix_to_colormap(), process_file(), read_header(), vms_exit(), xexit(), yy_fatal_error(), yyerror(), and yyparse().
void vms_abort ()
Definition at line 21 of file vmsmisc.c.
References $signal().
{
    lib$signal(SS$_DEBUG);
}
void vms_exit ()
void vms_exit (int status)
Definition at line 14 of file vmsmisc.c.
References exit().
{
    exit(status ? (SS$_ABORT | STS$M_INHIB_MSG) : SS$_NORMAL);
}