nethack/sys/vms/vmsmail.c File Reference
#include `config.h`
*
#include `mail.h`
*
Functions
unsigned long NDECL (init_broadcast_trapping)
unsigned long NDECL (enable_broadcast_trapping)
unsigned long NDECL (disable_broadcast_trapping)
struct mail_info * NDECL (parse_next_broadcast)
unsigned long init_broadcast_trapping ()
unsigned long enable_broadcast_trapping ()
unsigned long disable_broadcast_trapping ()
struct mail_info * parse_next_broadcast ()
Function Documentation
unsigned long disable_broadcast_trapping ()
Definition at line 420 of file vmsmail.c.
Referenced by settty().
{ return 1; }
unsigned long enable_broadcast_trapping ()
Definition at line 419 of file vmsmail.c.
Referenced by setftty().
{ return 1; }
unsigned long init_broadcast_trapping ()
Definition at line 418 of file vmsmail.c.
Referenced by setftty().
{ return 1; }
unsigned long NDECL (init_broadcast_trapping)
unsigned long NDECL (enable_broadcast_trapping)
unsigned long NDECL (disable_broadcast_trapping)
struct mail_info* NDECL (parse_next_broadcast)
struct mail_info* parse_next_broadcast ()
Definition at line 421 of file vmsmail.c.
{ return 0; }