nethack/sys/vms/vmstty.c File Reference
#include `hack.h`
*
#include `wintty.h`
*
#include `tcap.h`
*
#include <descrip.h>
*
#include <iodef.h>
*
#include <smgdef.h>
*
#include <ttdef.h>
*
#include <tt2def.h>
*
#include <errno.h>
*
#include <signal.h>
*
Data Structures
struct _rd_iosb
struct _wr_iosb
struct _sm_iosb
struct _sm_bufr
Macros
#define NEED_VARARGS
#define vms_ok(sts) ((sts)&1)
#define META(c) ((c)|0x80)	/* 8th bit */
#define CTRL(c) ((c)&0x1F)
#define CMASK(c) (1<<CTRL(c))
#define LIB $M_CLI_CTRLT CMASK('T')	/* 0x00100000 */
#define LIB $M_CLI_CTRLY CMASK('Y')	/* 0x02000000 */
#define ESC '\033'
#define CSI META(ESC)		/* '\233' */
#define SS3 META(CTRL('O'))	/* '\217' */
#define QIO_FUNC IO$_TTYREADALL|IO$M_NOECHO|IO$M_TRMNOECHO
#define TT_SPECIAL_HANDLING (TT$M_MECHTAB|TT$M_MECHFORM)
#define TT2_SPECIAL_HANDLING (0)
#define Uword unsigned short
#define Ubyte unsigned char
#define page_width buf_siz		/* number of columns */
Functions
unsigned long lib $disable_ctrl ()
unsigned long lib lib $enable_ctrl ()
unsigned long sys $assign ()
unsigned long sys sys $dassgn ()
unsigned long sys sys sys $qiow ()
unsigned long smg $create_virtual_keyboard ()
unsigned long smg smg $delete_virtual_keyboard ()
unsigned long smg smg smg $read_keystroke ()
unsigned long smg smg smg smg $cancel_input ()
static void NDECL (setctty)
static void NDECL (resettty)
int vms_getchar ()
static void setctty ()
static void resettty ()
void gettty ()
void settty (char *s) const
void shuttty (char *s) const
void setftty ()
void intron ()
void introff ()
Variables
short ospeed
char erase_char
char intr_char
char kill_char
static boolean settty_needed = FALSE
static boolean bombing = FALSE
static unsigned long kb = 0
xx xx xx xx xx xx xx xx xx
struct {
 struct _sm_iosb io
 struct _sm_bufr sm
} sg = {{0},{0}}
static unsigned short tt_chan = 0
static unsigned long tt_char_restore = 0
static unsigned long tt_char_active = 0
static unsigned long tt2_char_restore = 0
static unsigned long tt2_char_active = 0
static unsigned long ctrl_mask = 0
Macro Definition Documentation
#define CMASK(c) (1<<CTRL(c))
Definition at line 48 of file vmstty.c.
#define CSI META(ESC)		/* '\233' */
Definition at line 52 of file vmstty.c.
Referenced by vms_getchar().
#define CTRL(c) ((c)&0x1F)
Definition at line 47 of file vmstty.c.
Referenced by gettty(), intron(), and vms_getchar().
#define ESC '\033'
Definition at line 51 of file vmstty.c.
Referenced by vms_getchar().
#define LIB $M_CLI_CTRLT CMASK('T')	/* 0x00100000 */
Definition at line 50 of file vmstty.c.
Referenced by setftty().
#define LIB $M_CLI_CTRLY CMASK('Y')	/* 0x02000000 */
Definition at line 50 of file vmstty.c.
#define META(c) ((c)|0x80)	/* 8th bit */
Definition at line 46 of file vmstty.c.
#define NEED_VARARGS
Definition at line 6 of file vmstty.c.
#define page_width buf_siz		/* number of columns */
Definition at line 91 of file vmstty.c.
#define QIO_FUNC IO$_TTYREADALL|IO$M_NOECHO|IO$M_TRMNOECHO
Definition at line 64 of file vmstty.c.
Referenced by vms_getchar().
#define SS3 META(CTRL('O'))	/* '\217' */
Definition at line 53 of file vmstty.c.
Referenced by vms_getchar().
#define TT2_SPECIAL_HANDLING (0)
Definition at line 70 of file vmstty.c.
Referenced by gettty().
#define TT_SPECIAL_HANDLING (TT$M_MECHTAB|TT$M_MECHFORM)
Definition at line 69 of file vmstty.c.
Referenced by gettty().
#define Ubyte unsigned char
Definition at line 73 of file vmstty.c.
#define Uword unsigned short
Definition at line 72 of file vmstty.c.
#define vms_ok(sts) ((sts)&1)
Definition at line 45 of file vmstty.c.
Referenced by gettty(), setctty(), and vms_getchar().
Function Documentation
unsigned long sys $assign ()
Referenced by gettty().
unsigned long smg smg smg smg $cancel_input ()
unsigned long smg $create_virtual_keyboard ()
unsigned long sys sys $dassgn ()
Referenced by resettty().
unsigned long smg smg $delete_virtual_keyboard ()
Referenced by settty().
unsigned long lib $disable_ctrl ()
Referenced by setftty().
unsigned long lib lib $enable_ctrl ()
Referenced by gettty(), and settty().
unsigned long sys sys sys $qiow ()
Referenced by gettty(), setctty(), and vms_getchar().
unsigned long smg smg smg $read_keystroke ()
Referenced by vms_getchar().
void gettty (void)
Definition at line 326 of file vmstty.c.
References $assign(), $enable_ctrl(), $qiow(), instance_flags::cbreak, CO, CTRL, instance_flags::echo, errno, iflags, LI, OFF, ON, perror, raw_print, resettty(), setctty(), sg, _sm_iosb::status, tt2_char_active, tt2_char_restore, TT2_SPECIAL_HANDLING, tt_char_active, TT_SPECIAL_HANDLING, vms_ok, and wait_synch.
{
    static char dev_tty[] = "TT:";
    static $DESCRIPTOR(tty_dsc, dev_tty);
    int err = 0;
    unsigned long status, zero = 0;
    if (tt_chan == 0) { /* do this stuff once only */
    iflags.cbreak = OFF, iflags.echo = ON; /* until setup is complete */
    status = sys$assign(&tty_dsc, &tt_chan, 0, 0);
    if (!vms_ok(status)) {
        raw_print(""), err++;
        errno = EVMSERR, vaxc$errno = status;
        perror("NetHack(gettty: $assign)");
    }
    atexit(resettty); /* register an exit handler to reset things */
    }
    status = sys$qiow(0, tt_chan, IO$_SENSEMODE, &sg.io, (void(*)())0, 0,
              &sg.sm, sizeof sg.sm, 0, 0, 0, 0);
    if (vms_ok(status)) status = sg.io.status;
    if (!vms_ok(status)) {
    raw_print(""), err++;
    errno = EVMSERR, vaxc$errno = status;
    perror("NetHack(gettty: sensemode)");
    }
    ospeed = sg.io.xmt_speed;
    erase_char = '\177'; /* <rubout>, aka <delete> */
    kill_char = CTRL('U');
    intr_char = CTRL('C');
    (void) lib$enable_ctrl(&zero, &ctrl_mask);
    /* Use the systems's values for lines and columns if it has any idea. */
    if (sg.sm.page_length)
    LI = sg.sm.page_length;
    if (sg.sm.page_width)
    CO = sg.sm.page_width;
    /* suppress tab and form-feed expansion, in case termcap uses them */
    tt_char_restore = sg.sm.tt_char;
    tt_char_active = sg.sm.tt_char |= TT_SPECIAL_HANDLING;
    tt2_char_restore = sg.sm.tt2_char;
    tt2_char_active = sg.sm.tt2_char |= TT2_SPECIAL_HANDLING;
#if 0 /*[ defer until setftty() ]*/
    setctty();
#endif
    if (err) wait_synch();
}
void introff ()
Definition at line 440 of file vmstty.c.
{
    intr_char = 0;
}
void intron ()
Definition at line 434 of file vmstty.c.
References CTRL.
{
    intr_char = CTRL('C');
}
static void NDECL (setctty) [static]
static void NDECL (resettty) [static]
static void resettty () [static]
Definition at line 310 of file vmstty.c.
References $dassgn(), settty(), and TRUE.
Referenced by gettty().
{
    if (settty_needed) {
    bombing = TRUE; /* don't clear screen; preserve traceback info */
    settty((char *)0);
    }
    (void) sys$dassgn(tt_chan), tt_chan = 0;
}
static void setctty () [static]
Definition at line 290 of file vmstty.c.
References $qiow(), errno, number_pad, perror, raw_print, sg, _sm_iosb::status, vms_ok, and wait_synch.
Referenced by gettty(), setftty(), and settty().
{
    struct _sm_iosb iosb;
    unsigned long status;
    status = sys$qiow(0, tt_chan, IO$_SETMODE, &iosb, (void(*)())0, 0,
              &sg.sm, sizeof sg.sm, 0, 0, 0, 0);
    if (vms_ok(status)) status = iosb.status;
    if (vms_ok(status)) {
    /* try to force terminal into synch with TTDRIVER's setting */
    number_pad((sg.sm.tt2_char & TT2$M_APP_KEYPAD) ? -1 : 1);
    } else {
    raw_print("");
    errno = EVMSERR, vaxc$errno = status;
    perror("NetHack(setctty: setmode)");
    wait_synch();
    }
}
void setftty (void)
USE_QIO_INPUT
Definition at line 408 of file vmstty.c.
References $disable_ctrl(), instance_flags::cbreak, instance_flags::echo, enable_broadcast_trapping(), iflags, init_broadcast_trapping(), LIB, OFF, ON, setctty(), sg, start_screen, TRUE, tt2_char_active, tt_chan, and tt_char_active.
{
    unsigned long mask = LIB$M_CLI_CTRLT | LIB$M_CLI_CTRLY;
    (void) lib$disable_ctrl(&mask, 0);
    if (kb == 0) { /* do this stuff once only */
#ifdef USE_QIO_INPUT
        kb = tt_chan;
#else
        smg$create_virtual_keyboard(&kb);
#endif /*USE_QIO_INPUT*/
        init_broadcast_trapping();
    }
    enable_broadcast_trapping(); /* no-op if !defined(MAIL) */
    iflags.cbreak = (kb != 0) ? ON : OFF;
    iflags.echo = (kb != 0) ? OFF : ON;
    /* disable tab & form-feed expansion; prepare for broadcast trapping */
    sg.sm.tt_char = tt_char_active;
    sg.sm.tt2_char = tt2_char_active;
    setctty();
    start_screen();
    settty_needed = TRUE;
}
void settty (char * s) const
Definition at line 375 of file vmstty.c.
References $delete_virtual_keyboard(), $enable_ctrl(), instance_flags::cbreak, disable_broadcast_trapping(), instance_flags::echo, end_screen, FALSE, iflags, OFF, ON, raw_print, setctty(), sg, tt2_char_restore, and tt_char_restore.
Referenced by resettty(), and shuttty().
{
    if (!bombing) end_screen();
    if (s) raw_print(s);
    disable_broadcast_trapping();
#if 0 /* let SMG's exit handler do the cleanup (as per doc) */
/* #ifndef USE_QIO_INPUT */
    if (kb) smg$delete_virtual_keyboard(&kb), kb = 0;
#endif /* 0 (!USE_QIO_INPUT) */
    if (ctrl_mask)
        (void) lib$enable_ctrl(&ctrl_mask, 0);
    iflags.echo = ON;
    iflags.cbreak = OFF;
    /* reset original tab, form-feed, broadcast settings */
    sg.sm.tt_char = tt_char_restore;
    sg.sm.tt2_char = tt2_char_restore;
    setctty();
    settty_needed = FALSE;
}
void shuttty (char * s) const
Definition at line 399 of file vmstty.c.
References FALSE, settty(), and TRUE.
{
    bombing = TRUE;
    settty(s);
    bombing = FALSE;
}
int vms_getchar ()
USE_QIO_INPUT
Definition at line 106 of file vmstty.c.
References $qiow(), $read_keystroke(), CSI, CTRL, ESC, iflags, instance_flags::num_pad, program_state, QIO_FUNC, SS3, _rd_iosb::status, and vms_ok.
{
    short key;
#ifdef USE_QIO_INPUT
    struct _rd_iosb iosb;
    unsigned long sts;
    unsigned char kb_buf;
#else /* SMG input */
    static volatile int recurse = 0; /* SMG is not AST re-entrant! */
#endif
    if (program_state.done_hup) {
    /* hangup has occurred; do not attempt to get further user input */
    return ESC;
    }
#ifdef USE_QIO_INPUT
    if (inc > 0) {
    /* we have buffered character(s) from previous read */
    kb_buf = *inp++;
    --inc;
    sts = SS$_NORMAL;
    } else {
    sts = sys$qiow(0, tt_chan, QIO_FUNC, &iosb, (void(*)())0, 0,
               &kb_buf, sizeof kb_buf, 0, 0, 0, 0);
    }
    if (vms_ok(sts)) {
    if (kb_buf == CTRL('C')) {
        if (intr_char) gsignal(SIGINT);
        key = (short)kb_buf;
    } else if (kb_buf == '\r') { /* <return> */
        key = (short)'\n';
    } else if (kb_buf == ESC || kb_buf == CSI || kb_buf == SS3) {
        switch(parse_function_key((int)kb_buf)) {
          case SMG$K_TRM_UP: key = iflags.num_pad ? '8' : 'k'; break;
          case SMG$K_TRM_DOWN: key = iflags.num_pad ? '2' : 'j'; break;
          case SMG$K_TRM_LEFT: key = iflags.num_pad ? '4' : 'h'; break;
          case SMG$K_TRM_RIGHT: key = iflags.num_pad ? '6' : 'l'; break;
          default: key = ESC; break;
        }
    } else {
        key = (short)kb_buf;
    }
    } else if (sts == SS$_HANGUP || iosb.status == SS$_HANGUP
        || sts == SS$_DEVOFFLINE) {
    gsignal(SIGHUP);
    key = ESC;
    } else /*(this should never happen)*/
    key = getchar();
#else
    if (recurse++ == 0 && kb != 0) {
    smg$read_keystroke(&kb, &key);
    switch (key) {
      case SMG$K_TRM_UP: iflags.num_pad ? '8' : key = 'k'; break;
      case SMG$K_TRM_DOWN: iflags.num_pad ? '2' : key = 'j'; break;
      case SMG$K_TRM_LEFT: iflags.num_pad ? '4' : key = 'h'; break;
      case SMG$K_TRM_RIGHT: iflags.num_pad ? '6' : key = 'l'; break;
      case '\r': key = '\n'; break;
      default: if (key > 255) key = ESC;
                break;
    }
    } else {
    /* abnormal input--either SMG didn't initialize properly or
       vms_getchar() has been called recursively (via SIGINT handler).
     */
    if (kb != 0) /* must have been a recursive call */
        smg$cancel_input(&kb); /* from an interrupt handler */
    key = getchar();
    }
    --recurse;
#endif /* USE_QIO_INPUT */
    return (int)key;
}
Variable Documentation
boolean bombing = FALSE [static]
Definition at line 57 of file vmstty.c.
unsigned long ctrl_mask = 0 [static]
Definition at line 103 of file vmstty.c.
char erase_char
Definition at line 56 of file vmstty.c.
char intr_char
Definition at line 56 of file vmstty.c.
struct _sm_iosb io
Definition at line 97 of file vmstty.c.
unsigned long kb = 0 [static]
Definition at line 58 of file vmstty.c.
char kill_char
Definition at line 56 of file vmstty.c.
short ospeed
Definition at line 21 of file tclib.c.
Referenced by gettty(), tc_store(), and tputs().
boolean settty_needed = FALSE [static]
Definition at line 57 of file vmstty.c.
struct { ... } sg [static]
Referenced by gettty(), setctty(), setftty(), and settty().
struct _sm_bufr sm
Definition at line 98 of file vmstty.c.
Referenced by join_map().
unsigned long tt2_char_active = 0 [static]
Definition at line 102 of file vmstty.c.
Referenced by gettty(), and setftty().
unsigned long tt2_char_restore = 0 [static]
Definition at line 102 of file vmstty.c.
Referenced by gettty(), and settty().
unsigned short tt_chan = 0 [static]
Definition at line 100 of file vmstty.c.
Referenced by setftty().
unsigned long tt_char_active = 0 [static]
Definition at line 101 of file vmstty.c.
Referenced by gettty(), and setftty().
unsigned long tt_char_restore = 0 [static]
Definition at line 101 of file vmstty.c.
Referenced by settty().