nethack/sys/vms/vmsunix.c File Reference
#include `hack.h`
*
#include <descrip.h>
*
#include <dvidef.h>
*
#include <jpidef.h>
*
#include <ssdef.h>
*
#include <errno.h>
*
#include <signal.h>
*
#include <stat.h>
*
#include <ctype.h>
*
#include <lnmdef.h>
*
Macros
#define umask hide_umask_dummy /* DEC C: avoid conflict with system.h */
#define vms_ok(sts) ((sts) & 1) /* odd => success */
#define FAB $C_STMLF 5
#define ENVSIZ LNM$C_NAMLENGTH /*255*/
#define ENV_USR 0	/* user-mode */
#define ENV_SUP 1	/* supervisor-mode */
#define ENV_JOB 2	/* job-wide entry */
#define GNU_DEFAULT_TERMCAP `emacs_library:[etc]termcap.dat`
#define NETHACK_DEF_TERMCAP `nethackdir:termcap`
#define HACK_DEF_TERMCAP `hackdir:termcap`
Functions
unsigned long sys $setprv ()
unsigned long lib $getdvi ()
unsigned long lib lib $getjpi ()
unsigned long lib lib lib $spawn ()
unsigned long lib lib lib lib $attach ()
unsigned long smg $init_term_table_by_type ()
unsigned long smg smg $del_term_table ()
static int FDECL (veryold,(int))
static char * NDECL (verify_term)
static int veryold (int fd)
void getlock ()
void regularize (char *s)
int vms_getuid ()
boolean file_is_stmlf (int fd)
int vms_define (char *name, const char *value, int flag) const
int vms_putenv (char *string) const
static char * verify_term ()
char * verify_termcap ()
Macro Definition Documentation
#define ENV_JOB 2	/* job-wide entry */
Definition at line 183 of file vmsunix.c.
Referenced by vms_define().
#define ENV_SUP 1	/* supervisor-mode */
Definition at line 182 of file vmsunix.c.
Referenced by vms_define().
#define ENV_USR 0	/* user-mode */
Definition at line 181 of file vmsunix.c.
Referenced by verify_termcap(), vms_define(), and vms_putenv().
#define ENVSIZ LNM$C_NAMLENGTH /*255*/
Definition at line 179 of file vmsunix.c.
Referenced by vms_putenv().
#define FAB $C_STMLF 5
Definition at line 155 of file vmsunix.c.
Referenced by file_is_stmlf(), same_dir(), vms_link(), and vms_unlink().
#define GNU_DEFAULT_TERMCAP `emacs_library:[etc]termcap.dat`
Definition at line 286 of file vmsunix.c.
Referenced by verify_termcap().
#define HACK_DEF_TERMCAP `hackdir:termcap`
Definition at line 288 of file vmsunix.c.
Referenced by verify_termcap().
#define NETHACK_DEF_TERMCAP `nethackdir:termcap`
Definition at line 287 of file vmsunix.c.
Referenced by verify_termcap().
#define umask hide_umask_dummy /* DEC C: avoid conflict with system.h */
Definition at line 19 of file vmsunix.c.
Referenced by main().
#define vms_ok(sts) ((sts) & 1) /* odd => success */
Definition at line 28 of file vmsunix.c.
Referenced by verify_term(), and veryold().
Function Documentation
unsigned long lib lib lib lib $attach ()
unsigned long smg smg $del_term_table ()
unsigned long lib $getdvi ()
Referenced by verify_term().
unsigned long lib lib $getjpi ()
Referenced by veryold().
unsigned long smg $init_term_table_by_type ()
Referenced by verify_term().
unsigned long sys $setprv ()
unsigned long lib lib lib $spawn ()
static int FDECL (veryold , (int)) [static]
boolean file_is_stmlf (int fd)
Definition at line 159 of file vmsunix.c.
References FAB, and FALSE.
Referenced by check_recordfile().
{
    int rfm;
    struct stat buf;
    if (fstat(fd, &buf)) return FALSE; /* cannot get status? */
#ifdef stat_alignment_fix /* gcc-vms alignment kludge */
    rfm = stat_alignment_fix(&buf)->st_fab_rfm;
#else
    rfm = buf.st_fab_rfm;
#endif
    return rfm == FAB$C_STMLF;
}
void getlock (void)
Definition at line 78 of file vmsunix.c.
References close(), creat(), errno, error(), FCMASK, hackpid, HLOCK, isatty(), lock, lock_file(), LOCKPREFIX, open(), perror, regularize(), set_levelfile_name(), unlock_file(), veryold(), wait_synch, and write().
{
    register int i = 0, fd;
    /* idea from rpick%ucqais@uccba.uc.edu
     * prevent automated rerolling of characters
     * test input (fd0) so that tee'ing output to get a screen dump still
     * works
     * also incidentally prevents development of any hack-o-matic programs
     */
    if (isatty(0) <= 0)
        error("You must play from a terminal.");
    /* we ignore QUIT and INT at this point */
    if (!lock_file(HLOCK, LOCKPREFIX, 10)) {
        wait_synch();
        error("Quitting.");
    }
    regularize(lock);
    set_levelfile_name(lock, 0);
    if(locknum > 25) locknum = 25;
    do {
        if(locknum) lock[0] = 'a' + i++;
        if((fd = open(lock, 0, 0)) == -1) {
            if(errno == ENOENT) goto gotlock; /* no such file */
            perror(lock);
            unlock_file(HLOCK);
            error("Cannot open %s", lock);
        }
        if(veryold(fd)) /* if true, this closes fd and unlinks lock */
            goto gotlock;
        (void) close(fd);
    } while(i < locknum);
    unlock_file(HLOCK);
    error(locknum ? "Too many hacks running now."
              : "There is a game in progress under your name.");
gotlock:
    fd = creat(lock, FCMASK);
    unlock_file(HLOCK);
    if(fd == -1) {
        error("cannot creat lock file.");
    } else {
        if(write(fd, (char *) &hackpid, sizeof(hackpid))
            != sizeof(hackpid)){
            error("cannot write lock");
        }
        if(close(fd) == -1) {
            error("cannot close lock");
        }
    }
}
static char* NDECL (verify_term) [static]
void regularize (char * s)
Definition at line 137 of file vmsunix.c.
Referenced by getlock().
{
    register char *lp;
    for (lp = s; *lp; lp++) /* note: '-' becomes '_' */
        if (!(isalpha(*lp) || isdigit(*lp) || *lp == '$'))
            *lp = '_';
}
static char* verify_term () [static]
Definition at line 251 of file vmsunix.c.
References $getdvi(), $init_term_table_by_type(), getenv, strcmpi, and vms_ok.
Referenced by verify_termcap().
{
    char *term = getenv("NETHACK_TERM");
    if (!term) term = getenv("HACK_TERM");
    if (!term) term = getenv("EMACS_TERM");
    if (!term) term = getenv("TERM");
    if (!term || !*term
    || !strcmpi(term, "undefined") || !strcmpi(term, "unknown")) {
    static char smgdevtyp[31+1]; /* size is somewhat arbitrary */
    static char dev_tty[] = "TT:";
    static $DESCRIPTOR(smgdsc, smgdevtyp);
    static $DESCRIPTOR(tt, dev_tty);
    unsigned short dvicode = DVI$_DEVTYPE;
    unsigned long devtype = 0L, termtab = 0L;
    (void)lib$getdvi(&dvicode, (unsigned short *)0, &tt, &devtype,
             (genericptr_t)0, (unsigned short *)0);
    if (devtype &&
        vms_ok(smg$init_term_table_by_type(&devtype, &termtab, &smgdsc))) {
        register char *p = &smgdevtyp[smgdsc.dsc$w_length];
        /* strip trailing blanks */
        while (p > smgdevtyp && *--p == ' ') *p = '\0';
        /* (void)smg$del_term_table(); */
        term = smgdevtyp;
    }
    }
    return term;
}
char* verify_termcap ()
Definition at line 291 of file vmsunix.c.
References ENV_USR, getenv, GNU_DEFAULT_TERMCAP, HACK_DEF_TERMCAP, NETHACK_DEF_TERMCAP, verify_term(), and vms_define().
{
    struct stat dummy;
    const char *tc = getenv("TERMCAP");
    if (tc) return verify_term(); /* no termcap fixups needed */
    if (!tc && !stat(NETHACK_DEF_TERMCAP, &dummy)) tc =
      NETHACK_DEF_TERMCAP;
    if (!tc && !stat(HACK_DEF_TERMCAP, &dummy)) tc =
      HACK_DEF_TERMCAP;
    if (!tc && !stat(GNU_DEFAULT_TERMCAP, &dummy)) tc =
      GNU_DEFAULT_TERMCAP;
    if (!tc && !stat("[]termcap", &dummy)) tc = "[]termcap"; /* current dir */
    if (!tc && !stat("$TERMCAP", &dummy)) tc = "$TERMCAP"; /* alt environ */
    if (tc) {
    /* putenv(strcat(strcpy(buffer,"TERMCAP="),tc)); */
    vms_define("TERMCAP", tc, ENV_USR);
    } else {
    /* perhaps someday we'll construct a termcap entry string */
    }
    return verify_term();
}
static int veryold (int fd) [static]
Definition at line 38 of file vmsunix.c.
References $getjpi(), close(), lock, MAXDUNGEON, MAXLEVEL, read(), set_levelfile_name(), time, and vms_ok.
Referenced by getlock().
{
    register int i;
    time_t date;
    struct stat buf;
    if(fstat(fd, &buf)) return(0); /* cannot get status */
#ifndef INSURANCE
    if(buf.st_size != sizeof(int)) return(0); /* not an xlock file */
#endif
    (void) time(&date);
    if(date - buf.st_mtime < 3L*24L*60L*60L) { /* recent */
        int lockedpid; /* should be the same size as hackpid */
        unsigned long status, dummy, code = JPI$_PID;
        if (read(fd, (genericptr_t)&lockedpid, sizeof(lockedpid)) !=
                sizeof(lockedpid)) /* strange ... */
            return 0;
        status = lib$getjpi(&code, &lockedpid, 0, &dummy);
        if (vms_ok(status) || status != SS$_NONEXPR)
            return 0;
    }
    (void) close(fd);
    /* cannot use maxledgerno() here, because we need to find a lock name
     * before starting everything (including the dungeon initialization
     * that sets astral_level, needed for maxledgerno()) up
     */
    for(i = 1; i <= MAXDUNGEON*MAXLEVEL + 1; i++) {
        /* try to remove all */
        set_levelfile_name(lock, i);
        (void) delete(lock);
    }
    set_levelfile_name(lock, 0);
    if(delete(lock)) return(0); /* cannot remove it */
    return(1); /* success! */
}
int vms_define (char * name, const char * value, int flag) const
Definition at line 187 of file vmsunix.c.
References ENV_JOB, ENV_SUP, and ENV_USR.
Referenced by verify_termcap(), and vms_putenv().
{
    struct dsc { unsigned short len, mbz; const char *adr; }; /* descriptor */
    struct itm3 { short buflen, itmcode; const char *bufadr; short *retlen; };
    static struct itm3 itm_lst[] = { {0,LNM$_STRING,0,0}, {0,0} };
    struct dsc nam_dsc, val_dsc, tbl_dsc;
    unsigned long result, sys$crelnm(), lib$set_logical();
    /* set up string descriptors */
    nam_dsc.mbz = val_dsc.mbz = tbl_dsc.mbz = 0;
    nam_dsc.len = strlen(nam_dsc.adr = name);
    val_dsc.len = strlen(val_dsc.adr = value);
    tbl_dsc.len = strlen(tbl_dsc.adr = "LNM$PROCESS");
    switch (flag) {
    case ENV_JOB: /* job logical name */
        tbl_dsc.len = strlen(tbl_dsc.adr = "LNM$JOB");
        /*FALLTHRU*/
    case ENV_SUP: /* supervisor-mode process logical name */
        result = lib$set_logical(&nam_dsc, &val_dsc, &tbl_dsc);
        break;
    case ENV_USR: /* user-mode process logical name */
        itm_lst[0].buflen = val_dsc.len;
        itm_lst[0].bufadr = val_dsc.adr;
        result = sys$crelnm(0, &tbl_dsc, &nam_dsc, 0, itm_lst);
        break;
    default: /*[ bad input ]*/
        result = 0;
        break;
    }
    result &= 1; /* odd => success (== 1), even => failure (== 0) */
    return !result; /* 0 == success, 1 == failure */
}
int vms_getuid ()
Definition at line 149 of file vmsunix.c.
References getuid().
{
    return (getgid() << 16) | getuid();
}
int vms_putenv (char * string) const
Definition at line 226 of file vmsunix.c.
References ENV_USR, ENVSIZ, name, and vms_define().
{
    char name[ENVSIZ+1], value[ENVSIZ+1], *p; /* [255+1] */
    p = strchr(string, '=');
    if (p > string && p < string + sizeof name && strlen(p+1) < sizeof value) {
    (void)strncpy(name, string, p - string), name[p - string] = '\0';
    (void)strcpy(value, p+1);
    return vms_define(name, value, ENV_USR);
    } else
    return 1; /* failure */
}