nethack/include/wceconf.h File Reference
#include <windows.h>
*
#include <string.h>
*
#include <stdlib.h>
*
Data Structures
struct tm
Macros
#define WIN32_LEAN_AND_MEAN
#define RANDOM /* have Berkeley random(3) */
#define TEXTCOLOR /* Color text */
#define EXEPATH /* Allow .exe location to be used as HACKDIR */
#define TRADITIONAL_GLYPHMAP /* Store glyph mappings at level change time */
#define PC_LOCKING /* Prevent overwrites of aborted or in-progress games */
#define SELF_RECOVER /* Allow the game itself to recover from an aborted game */
#define NOTSTDC /* no strerror() */
#define USER_SOUNDS
#define AUTOPICKUP_EXCEPTIONS
#define NOCWD_ASSUMPTIONS
#define NO_TERMS
#define ASCIIGRAPH
#define OPTIONS_USED `ttyoptions`
#define OPTIONS_FILE OPTIONS_USED
#define PORT_HELP `porthelp`
#define RUNTIME_PORT_ID
#define PATHLEN BUFSZ /* maximum pathlength */
#define FILENAME BUFSZ /* maximum filename length (conservative) */
#define NO_SIGNAL
#define index strchr
#define rindex strrchr
#define USE_STDARG
#define Rand() random()
#define FCMASK 0660	/* file creation mask */
#define regularize nt_regularize
#define HLOCK `NHPERM`
#define M(c) ((char) (0x80 | (c)))
#define C(c) (0x1f & (c))
#define ABORT C('a')
#define getuid() 1
#define getlogin() ((char *)0)
#define ALLOCA_HACK /* used in util/panic.c */
#define Getchar nhgetch
#define NHSTR_BUFSIZE 255
#define NH_W2A(w, a, cb) (strncpy((a), (w), (cb)))
#define NH_A2W(a, w, cb) (strncpy((w), (a), (cb)))
#define interject_assistance(_1, _2, _3, _4)
#define interject(_1)
#define kbhit mswin_have_input
#define getenv(a) ((char*)NULL)
#define perror(a)
#define freopen(a, b, c) fopen(a, b)
#define _TIME_T_DEFINED /* avoid multiple def's of time_t */
#define _TM_DEFINED
#define BUFSIZ 255
#define rewind(stream) (void)fseek(stream, 0L, SEEK_SET)
#define DeleteFile(a) unlink(a)
#define abort() (void)TerminateProcess(GetCurrentProcess(), 0)
#define strdup _strdup
#define S_IWRITE GENERIC_WRITE
#define S_IREAD GENERIC_READ
Typedefs
typedef __int64 time_t
typedef long off_t
Functions
void NDECL (win32_abort)
int FDECL (set_win32_option,(const char *, const char *))
int mswin_have_input ()
int isatty (int)
struct tm *__cdecl localtime (const time_t *)
time_t __cdecl time (time_t *)
int __cdecl close (int)
int __cdecl creat (const char *, int)
int __cdecl eof (int)
long __cdecl lseek (int, long, int)
int __cdecl open (const char *, int,...)
int __cdecl read (int, void *, unsigned int)
int __cdecl unlink (const char *)
int __cdecl write (int, const void *, unsigned int)
int __cdecl rename (const char *, const char *)
int __cdecl access (const char *, int)
int chdir (const char *dirname)
char * getcwd (char *buffer, int maxlen)
Variables
const char * alllevels
const char * allbones
char hackdir []
Macro Definition Documentation
#define _TIME_T_DEFINED /* avoid multiple def's of time_t */
Definition at line 248 of file wceconf.h.
#define _TM_DEFINED
Definition at line 263 of file wceconf.h.
#define ABORT C('a')
Definition at line 170 of file wceconf.h.
#define abort() (void)TerminateProcess(GetCurrentProcess(), 0)
Definition at line 299 of file wceconf.h.
Referenced by alloc_file_handle(), vms_handler(), and win32_abort().
#define ALLOCA_HACK /* used in util/panic.c */
Definition at line 180 of file wceconf.h.
#define ASCIIGRAPH
Definition at line 65 of file wceconf.h.
#define AUTOPICKUP_EXCEPTIONS
Definition at line 46 of file wceconf.h.
Referenced by autopick(), and dotogglepickup().
#define BUFSIZ 255
Definition at line 271 of file wceconf.h.
Referenced by copy_bytes(), depack_img(), fopen_datafile(), main(), and tc_find().
#define C(c) (0x1f & (c))
Definition at line 156 of file wceconf.h.
#define DeleteFile(a) unlink(a)
Definition at line 293 of file wceconf.h.
Referenced by lock_file(), and unlock_file().
#define EXEPATH /* Allow .exe location to be used as HACKDIR */
Definition at line 34 of file wceconf.h.
#define FCMASK 0660	/* file creation mask */
Definition at line 146 of file wceconf.h.
#define FILENAME BUFSZ /* maximum filename length (conservative) */
Definition at line 123 of file wceconf.h.
#define freopen(a, b, c) fopen(a, b)
Definition at line 242 of file wceconf.h.
Referenced by main().
#define Getchar nhgetch
Definition at line 185 of file wceconf.h.
#define getenv(a) ((char*)NULL)
Definition at line 238 of file wceconf.h.
Referenced by byebye(), initoptions(), main(), makemaz(), nh_getenv(), tgetent(), verify_term(), verify_termcap(), and yyparse().
#define getlogin() ((char *)0)
Definition at line 172 of file wceconf.h.
#define getuid() 1
Definition at line 171 of file wceconf.h.
#define HLOCK `NHPERM`
Definition at line 148 of file wceconf.h.
#define index strchr
Definition at line 136 of file wceconf.h.
#define interject(_1)
Definition at line 232 of file wceconf.h.
#define interject_assistance(_1, _2, _3, _4)
Definition at line 231 of file wceconf.h.
#define kbhit mswin_have_input
Definition at line 236 of file wceconf.h.
#define M(c) ((char) (0x80 | (c)))
Definition at line 151 of file wceconf.h.
#define NH_A2W(a, w, cb) (strncpy((w), (a), (cb)))
Definition at line 222 of file wceconf.h.
Referenced by About(), chdir(), creat(), ExtCmdDlgProc(), GetlinDlgProc(), getlock(), initMapTiles(), LayoutCmdWindow(), mswin_display_file(), mswin_get_font(), mswin_init_splashfonts(), mswin_map_stretch(), mswin_menu_window_size(), mswin_raw_print(), mswin_raw_print_bold(), mswin_render_text(), nh_append(), onDrawItem(), onMSNHCommand(), onPaint(), open(), plselAdjustLists(), plselInitDialog(), prompt_for_player_selection(), SetMenuListType(), StatusWndProc(), and unlink().
#define NH_W2A(w, a, cb) (strncpy((a), (w), (cb)))
Definition at line 220 of file wceconf.h.
Referenced by getcwd(), GetlinDlgProc(), mswin_yn_function(), and WinMain().
#define NHSTR_BUFSIZE 255
Definition at line 200 of file wceconf.h.
Referenced by About(), and WinMain().
#define NO_SIGNAL
Definition at line 135 of file wceconf.h.
#define NO_TERMS
Definition at line 64 of file wceconf.h.
#define NOCWD_ASSUMPTIONS
Value:
/* Always define this. There are assumptions that
                                   it is defined for WIN32.
                   Allow paths to be specified for HACKDIR,
                   LEVELDIR, SAVEDIR, BONESDIR, DATADIR,
                   SCOREDIR, LOCKDIR, CONFIGDIR, and TROUBLEDIR */
Definition at line 59 of file wceconf.h.
#define NOTSTDC /* no strerror() */
Definition at line 42 of file wceconf.h.
#define OPTIONS_FILE OPTIONS_USED
Definition at line 75 of file wceconf.h.
#define OPTIONS_USED `ttyoptions`
Definition at line 73 of file wceconf.h.
#define PATHLEN BUFSZ /* maximum pathlength */
Definition at line 122 of file wceconf.h.
#define PC_LOCKING /* Prevent overwrites of aborted or in-progress games */
Definition at line 37 of file wceconf.h.
#define perror(a)
Definition at line 241 of file wceconf.h.
Referenced by do_data(), do_date(), do_dungeon(), do_monstr(), do_objs(), do_options(), do_oracles(), do_permonst(), do_questtxt(), do_rumors(), do_vision(), getlock(), gettty(), lock_file(), main(), makesound(), setctty(), and settty().
#define PORT_HELP `porthelp`
Definition at line 77 of file wceconf.h.
#define Rand() random()
Definition at line 141 of file wceconf.h.
#define RANDOM /* have Berkeley random(3) */
Definition at line 31 of file wceconf.h.
#define regularize nt_regularize
Definition at line 147 of file wceconf.h.
#define rewind(stream) (void)fseek(stream, 0L, SEEK_SET)
Definition at line 274 of file wceconf.h.
Referenced by fclose_ppm_file(), tc_find(), and tt_oname().
#define rindex strrchr
Definition at line 137 of file wceconf.h.
#define RUNTIME_PORT_ID
Value:
/* trigger run-time port identification since
               Makedefs is bootstrapped on a cross-platform. */
Definition at line 107 of file wceconf.h.
#define S_IREAD GENERIC_READ
Definition at line 306 of file wceconf.h.
Referenced by check_recordfile().
#define S_IWRITE GENERIC_WRITE
Definition at line 305 of file wceconf.h.
Referenced by check_recordfile(), and lock_file().
#define SELF_RECOVER /* Allow the game itself to recover from an aborted game */
Definition at line 40 of file wceconf.h.
#define strdup _strdup
Definition at line 301 of file wceconf.h.
Referenced by amii_end_menu(), mswin_add_text(), mswin_yn_function(), parse_config_line(), and WinMain().
#define TEXTCOLOR /* Color text */
Definition at line 32 of file wceconf.h.
#define TRADITIONAL_GLYPHMAP /* Store glyph mappings at level change time */
Definition at line 35 of file wceconf.h.
#define USE_STDARG
Definition at line 138 of file wceconf.h.
#define USER_SOUNDS
Definition at line 44 of file wceconf.h.
#define WIN32_LEAN_AND_MEAN
Definition at line 10 of file wceconf.h.
Typedef Documentation
typedef long off_t
Definition at line 277 of file wceconf.h.
typedef __int64 time_t
Definition at line 247 of file wceconf.h.
Function Documentation
int __cdecl access (const char * , int)
Definition at line 314 of file celib.c.
Referenced by fopen_config_file().
{
    DWORD attr;
    WCHAR f[MAX_PATH+1];
    ZeroMemory(f, sizeof(f));
    MultiByteToWideChar(CP_ACP, 0, path, -1, f, MAX_PATH);
    
    attr = GetFileAttributes(f);
    if(attr == (DWORD)-1) return -1;
    if ((attr & FILE_ATTRIBUTE_READONLY) && (mode & 2))
        return -1;
    else
        return 0;
}
int chdir (const char * dirname)
Definition at line 330 of file celib.c.
References _nh_cwd, and NH_A2W.
Referenced by Abort(), byebye(), chdirx(), main(), nethack_exit(), and xexit().
{
    ZeroMemory(_nh_cwd, sizeof(_nh_cwd));
    NH_A2W(dirname, _nh_cwd, MAX_PATH);
    return 0;
}
int __cdecl close (int)
Definition at line 110 of file celib.c.
References _nh_file_table, FILE_TABLE_SIZE, and MAGIC_OFFSET.
Referenced by bclose(), bitmap_to_img(), check_recordfile(), dorecover(), dosave0(), getbones(), getlock(), main(), mread(), restlevelfile(), restore_saved_game(), restore_savefile(), savebones(), unlock_file(), veryold(), and write_level_file().
                         {
    int retval;
    f -= MAGIC_OFFSET;
    if(f<0 || f>=FILE_TABLE_SIZE) return -1;
    retval = (CloseHandle(_nh_file_table[f])? 0 : -1);
    _nh_file_table[f] = INVALID_HANDLE_VALUE;
    return retval;
}
int __cdecl creat (const char * , int)
Definition at line 119 of file celib.c.
References alloc_file_handle(), NH_A2W, and NULL.
Referenced by create_bonesfile(), create_levelfile(), create_savefile(), getlock(), and vms_creat().
{
    HANDLE f;
    TCHAR wbuf[MAX_PATH+1];
    ZeroMemory(wbuf, sizeof(wbuf));
    NH_A2W(fname, wbuf, MAX_PATH);
    f = CreateFile(
        wbuf,
        GENERIC_READ | GENERIC_WRITE,
        0,
        NULL,
        CREATE_ALWAYS,
        FILE_ATTRIBUTE_NORMAL,
        NULL);
    if(f==INVALID_HANDLE_VALUE) return -1;
    else return alloc_file_handle(f);
}
int __cdecl eof (int)
Definition at line 139 of file celib.c.
References get_file_handle(), and NULL.
{
    DWORD fpos, fsize;
    HANDLE p = get_file_handle(f);
    if(f==-1) return -1;
    fpos = SetFilePointer(p, 0, NULL, FILE_CURRENT);
    fsize = SetFilePointer(p, 0, NULL, FILE_END);
    if(fpos==0xFFFFFFFF || fsize==0xFFFFFFFF) return -1;
    if(fpos==fsize) return 1;
    else {
        SetFilePointer(p, fpos, NULL, FILE_BEGIN);
        return 0;
    }
}
int FDECL (set_win32_option , (const char *, const char *))
char* getcwd (char * buffer, int maxlen)
Definition at line 337 of file celib.c.
References _nh_cwd, NH_W2A, and NULL.
Referenced by main().
{
    if(maxlen<(int)_tcslen(_nh_cwd)) return NULL;
    else return NH_W2A(_nh_cwd, buffer, maxlen);
}
int isatty (int)
Definition at line 378 of file celib.c.
Referenced by getlock(), and yy_init_buffer().
{
    return 0;
}
struct tm* __cdecl localtime (const time_t *)
Definition at line 26 of file celib.c.
References _day_mo, _day_mo_leap, _t_cnv, IS_LEAP, NULL, tm::tm_hour, tm::tm_isdst, tm::tm_mday, tm::tm_min, tm::tm_mon, tm::tm_sec, tm::tm_wday, tm::tm_yday, and tm::tm_year.
Referenced by do_date(), and main().
{
    static struct tm ptm;
    int i;
    if(!ptime) return NULL;
    _t_cnv.t_val = *ptime;
    ptm.tm_sec = _t_cnv.tm_val.ss ; /* seconds after the minute - [0,59] */
    ptm.tm_min = _t_cnv.tm_val.mm; /* minutes after the hour - [0,59] */
    ptm.tm_hour = _t_cnv.tm_val.hh; /* hours since midnight - [0,23] */
    ptm.tm_mday = _t_cnv.tm_val.dd; /* day of the month - [1,31] */
    ptm.tm_mon = _t_cnv.tm_val.mo-1; /* months since January - [0,11] */
    ptm.tm_year = _t_cnv.tm_val.yr; /* years since 1900 */
    ptm.tm_wday = _t_cnv.tm_val.wd; /* days since Sunday - [0,6] */
    ptm.tm_yday = _t_cnv.tm_val.dd; /* days since January 1 - [0,365] */
    for(i=0; i<ptm.tm_mon; i++)
        ptm.tm_yday += IS_LEAP(_t_cnv.tm_val.yr+1900)?_day_mo_leap[i] :
      _day_mo[i] ;
    ptm.tm_isdst = 0; /* daylight savings time flag - NOT IMPLEMENTED */
    return &ptm;
}
long __cdecl lseek (int , long , int)
Definition at line 156 of file celib.c.
References get_file_handle(), NULL, SEEK_CUR, SEEK_END, and SEEK_SET.
Referenced by dorecover(), main(), and restlevelfile().
{
    HANDLE p = get_file_handle(f);
    DWORD fpos;
    switch(origin) {
    case SEEK_SET:
        fpos = SetFilePointer(p, offset, NULL, FILE_BEGIN);
        break;
    case SEEK_CUR:
        fpos = SetFilePointer(p, offset, NULL, FILE_CURRENT);
        break;
    case SEEK_END:
        fpos = SetFilePointer(p, offset, NULL, FILE_END);
        break;
    default:
        fpos = 0xFFFFFFFF;
        break;
    }
    if(fpos==0xFFFFFFFF) return -1;
    else return (long)fpos;
}
int mswin_have_input ()
Definition at line 34 of file mhinput.c.
Referenced by mswin_main_loop(), and NHMenuListWndProc().
{
    return (nhi_read_pos!=nhi_write_pos);
}
void NDECL (win32_abort)
int __cdecl open (const char * , int , ...)
Definition at line 178 of file celib.c.
References _nh_cwd, _O_CREAT, _O_EXCL, _O_RDONLY, _O_RDWR, _O_TRUNC, _O_WRONLY, alloc_file_handle(), fname, NH_A2W, NULL, and O_APPEND.
Referenced by bitmap_to_img(), check_recordfile(), create_bonesfile(), create_levelfile(), create_savefile(), getlock(), lock_file(), main(), open_bonesfile(), open_levelfile(), open_savefile(), restore_savefile(), vms_open(), and write_level_file().
{
    TCHAR fname[MAX_PATH+1];
    TCHAR path[MAX_PATH+1];
    HANDLE f;
    DWORD fileaccess;
    DWORD filecreate;
    /* O_TEXT is not supported */
    /*
     * decode the access flags
     */
    switch(oflag & (_O_RDONLY | _O_WRONLY | _O_RDWR)) {
        case _O_RDONLY: /* read access */
                fileaccess = GENERIC_READ;
                break;
        case _O_WRONLY: /* write access */
                fileaccess = GENERIC_READ | GENERIC_WRITE;
                break;
        case _O_RDWR: /* read and write access */
                fileaccess = GENERIC_READ | GENERIC_WRITE;
                break;
        default: /* error, bad oflag */
                return -1;
    }
    /*
     * decode open/create method flags
     */
    switch (oflag & (_O_CREAT | _O_EXCL | _O_TRUNC)) {
        case 0:
        case _O_EXCL: // ignore EXCL w/o CREAT
            filecreate = OPEN_EXISTING;
            break;
        case _O_CREAT:
            filecreate = OPEN_ALWAYS;
            break;
        case _O_CREAT | _O_EXCL:
        case _O_CREAT | _O_TRUNC | _O_EXCL:
            filecreate = CREATE_NEW;
            break;
        case _O_TRUNC:
        case _O_TRUNC | _O_EXCL: // ignore EXCL w/o CREAT
            filecreate = TRUNCATE_EXISTING;
            break;
        case _O_CREAT | _O_TRUNC:
            filecreate = CREATE_ALWAYS;
            break;
        default:
            return -1;
    }
    /* assemple the file name */
    ZeroMemory(fname, sizeof(fname));
    ZeroMemory(path, sizeof(path));
    NH_A2W(filename, fname, MAX_PATH);
    if(*filename!='\\' && *filename!='/') {
        _tcscpy(path, _nh_cwd);
        _tcsncat(path, _T("\\"), MAX_PATH - _tcslen(path));
    }
    _tcsncat(path, fname, MAX_PATH - _tcslen(path));
    /*
     * try to open/create the file
     */
    if ((f = CreateFile(path,
                         fileaccess,
                         0,
                         NULL,
                         filecreate,
                         FILE_ATTRIBUTE_NORMAL,
                         NULL))
         == INVALID_HANDLE_VALUE)
    {
        return -1;
    }
    if(!(oflag & O_APPEND)) SetFilePointer(f, 0, NULL, FILE_BEGIN);
    return alloc_file_handle(f);
}
int __cdecl read (int , void * , unsigned int)
Definition at line 266 of file celib.c.
References get_file_handle(), and NULL.
Referenced by copy_bytes(), dorecover(), main(), mread(), restore_savefile(), uptodate(), and veryold().
{
    HANDLE p = get_file_handle(f);
    DWORD bytes_read;
    if(!ReadFile(p, buffer, count, &bytes_read, NULL))
        return -1;
    else
        return (int)bytes_read;
}
int __cdecl rename (const char * , const char *)
Definition at line 303 of file celib.c.
Referenced by commit_bonesfile().
{
    WCHAR f1[MAX_PATH+1];
    WCHAR f2[MAX_PATH+1];
    ZeroMemory(f1, sizeof(f1));
    ZeroMemory(f2, sizeof(f2));
    MultiByteToWideChar(CP_ACP, 0, oldname, -1, f1, MAX_PATH);
    MultiByteToWideChar(CP_ACP, 0, newname, -1, f2, MAX_PATH);
    return !MoveFile(f1, f2);
}
time_t __cdecl time (time_t *)
Definition at line 50 of file celib.c.
References _t_cnv.
{
    SYSTEMTIME stm;
    GetLocalTime(&stm);
    _t_cnv.tm_val.yr = stm.wYear-1900;
    _t_cnv.tm_val.mo = stm.wMonth;
    _t_cnv.tm_val.dd = stm.wDay;
    _t_cnv.tm_val.hh = stm.wHour;
    _t_cnv.tm_val.mm = stm.wMinute;
    _t_cnv.tm_val.ss = stm.wSecond;
    _t_cnv.tm_val.wd = stm.wDayOfWeek;
    if(timeptr)
        *timeptr = _t_cnv.t_val;
    return _t_cnv.t_val;
}
int __cdecl unlink (const char *)
Definition at line 276 of file celib.c.
References _nh_cwd, fname, and NH_A2W.
Referenced by commit_bonesfile(), delete_bonesfile(), delete_levelfile(), delete_savefile(), EditColor(), eraseoldlocks(), restore_savefile(), unlock_file(), validate_prefix_locations(), and vms_creat().
{
    TCHAR wbuf[MAX_PATH+1];
    TCHAR fname[MAX_PATH+1];
    
    ZeroMemory(wbuf, sizeof(wbuf));
    ZeroMemory(fname, sizeof(fname));
    NH_A2W(filename, wbuf, MAX_PATH);
    if(*filename!='\\' && *filename!='/') {
        _tcscpy(fname, _nh_cwd);
        _tcsncat(fname, _T("\\"), MAX_PATH - _tcslen(fname));
    }
    _tcsncat(fname, wbuf, MAX_PATH - _tcslen(fname));
    return !DeleteFileW(fname);
}
int __cdecl write (int , const void * , unsigned int)
Definition at line 293 of file celib.c.
References get_file_handle(), and NULL.
Referenced by bitmap_to_img(), bwrite(), copy_bytes(), getlock(), main(), restore_savefile(), and write_maze().
{
    HANDLE p = get_file_handle(f);
    DWORD bytes_written;
    if(!WriteFile(p, buffer, count, &bytes_written, NULL))
        return -1;
    else
        return (int)bytes_written;
}
Variable Documentation
const char * allbones
const char* alllevels
char hackdir[]