nethack/win/win32/mhstatus.h File Reference
#include `winMS.h`
*
#include `config.h`
*
#include `global.h`
*
Functions
HWND mswin_init_status_window (void)
void mswin_status_window_size (HWND hWnd, LPSIZE sz)
Function Documentation
HWND mswin_init_status_window (void)
Definition at line 24 of file mhstatus.c.
References FALSE, GetNHApp(), malloc(), mswin_nethack_status_window::nhstat_format, NHSTAT_LINES_4, NULL, panic(), register_status_window_class(), and szStatusWindowClass.
Referenced by mswin_create_nhwindow().
                                 {
    static int run_once = 0;
    HWND ret;
    NHStatusWindow* data;
    if(!run_once) {
        register_status_window_class();
        run_once = 1;
    }
    
    ret = CreateWindow(
            szStatusWindowClass,
            NULL,
            WS_CHILD | WS_DISABLED | WS_CLIPSIBLINGS,
            0, /* x position */
            0, /* y position */
            0, /* x-size - we will set it later */
            0, /* y-size - we will set it later */
            GetNHApp()->hMainWnd,
            NULL,
            GetNHApp()->hApp,
            NULL);
    if(!ret) panic("Cannot create status window");
    
    EnableWindow(ret, FALSE);
    data = (PNHStatusWindow)malloc(sizeof(NHStatusWindow));
    if(!data) panic("out of memory");
    ZeroMemory(data, sizeof(NHStatusWindow));
    data->nhstat_format = NHSTAT_LINES_4;
    SetWindowLong(ret, GWL_USERDATA, (LONG)data);
    return ret;
}
void mswin_status_window_size (HWND hWnd, LPSIZE sz)
Definition at line 146 of file mhstatus.c.
References ATR_NONE, FALSE, mswin_get_font(), mswin_nethack_status_window::nhstat_format, NHSTAT_LINES_2, NHSTAT_LINES_4, NHSW_LINES, and NHW_STATUS.
Referenced by mswin_layout_main_window().
{
    TEXTMETRIC tm;
    HGDIOBJ saveFont;
    HDC hdc;
    PNHStatusWindow data;
    RECT rt;
    GetWindowRect(hWnd, &rt);
    sz->cx = rt.right - rt.left;
    sz->cy = rt.bottom - rt.top;
    data = (PNHStatusWindow)GetWindowLong(hWnd, GWL_USERDATA);
    if(data) {
        hdc = GetDC(hWnd);
        saveFont = SelectObject(hdc, mswin_get_font(NHW_STATUS,
      ATR_NONE, hdc, FALSE));
        GetTextMetrics(hdc, &tm);
        /* see if the status window can fit 80 characters per line */
        if((80*tm.tmMaxCharWidth)>=sz->cx) data->nhstat_format =
      NHSTAT_LINES_4;
        else data->nhstat_format =
      NHSTAT_LINES_2;
        /* set height of the status box */
        sz->cy = tm.tmHeight * data->nhstat_format;
        SelectObject(hdc, saveFont);
        ReleaseDC(hWnd, hdc);
    }
}