nethack/win/win32/mhinput.h File Reference
#include `winMS.h`
*
Data Structures
struct mswin_event
Macros
#define NHEVENT_CHAR 1
#define NHEVENT_MOUSE 2
#define NHEVENT_KBD(c) { MSNHEvent e; e.type=NHEVENT_CHAR; e.kbd.ch=(c); mswin_input_push(&e); }
#define NHEVENT_MS(_mod, _x, _y) { MSNHEvent e; e.type=NHEVENT_MOUSE; e.ms.mod = (_mod); e.ms.x=(_x); e.ms.y=(_y); mswin_input_push(&e); }
Typedefs
typedef struct mswin_event MSNHEvent
typedef struct mswin_event * PMSNHEvent
Functions
void mswin_nh_input_init (void)
int mswin_have_input (void)
void mswin_input_push (PMSNHEvent event)
PMSNHEvent mswin_input_pop (void)
PMSNHEvent mswin_input_peek (void)
Macro Definition Documentation
#define NHEVENT_CHAR 1
Definition at line 10 of file mhinput.h.
#define NHEVENT_KBD(c) { MSNHEvent e; e.type=NHEVENT_CHAR; e.kbd.ch=(c); mswin_input_push(&e); }
Definition at line 26 of file mhinput.h.
#define NHEVENT_MOUSE 2
Definition at line 11 of file mhinput.h.
#define NHEVENT_MS(_mod, _x, _y) { MSNHEvent e; e.type=NHEVENT_MOUSE; e.ms.mod = (_mod); e.ms.x=(_x); e.ms.y=(_y); mswin_input_push(&e); }
Definition at line 27 of file mhinput.h.
Typedef Documentation
typedef struct mswin_event MSNHEvent
typedef struct mswin_event * PMSNHEvent
Function Documentation
int mswin_have_input (void)
Definition at line 34 of file mhinput.c.
References nhi_read_pos, and nhi_write_pos.
{
    return (nhi_read_pos!=nhi_write_pos);
}
PMSNHEvent mswin_input_peek (void)
Definition at line 73 of file mhinput.c.
References mswin_nh_input_init(), nhi_init_input, nhi_read_pos, nhi_write_pos, and NULL.
{
    PMSNHEvent retval;
    if(!nhi_init_input) mswin_nh_input_init();
    if(nhi_read_pos!=nhi_write_pos) {
        retval = &nhi_input_buffer[nhi_read_pos];
    } else {
        retval = NULL;
    }
    return retval;
}
PMSNHEvent mswin_input_pop (void)
Definition at line 56 of file mhinput.c.
References mswin_nh_input_init(), NH_INPUT_BUFFER_SIZE, nhi_init_input, nhi_read_pos, nhi_write_pos, and NULL.
Referenced by mswin_nh_poskey(), mswin_nhgetch(), and NHMenuListWndProc().
{
    PMSNHEvent retval;
    if(!nhi_init_input) mswin_nh_input_init();
    if(nhi_read_pos!=nhi_write_pos) {
        retval = &nhi_input_buffer[nhi_read_pos];
        nhi_read_pos = (nhi_read_pos+1) %
      NH_INPUT_BUFFER_SIZE;
    } else {
        retval = NULL;
    }
    return retval;
}
void mswin_input_push (PMSNHEvent event)
Definition at line 40 of file mhinput.c.
References mswin_nh_input_init(), NH_INPUT_BUFFER_SIZE, nhi_init_input, nhi_read_pos, and nhi_write_pos.
{
    int new_write_pos;
    if(!nhi_init_input) mswin_nh_input_init();
    new_write_pos = (nhi_write_pos+1) % NH_INPUT_BUFFER_SIZE;
    
    if(new_write_pos!=nhi_read_pos) {
        memcpy(nhi_input_buffer+nhi_write_pos, event, sizeof(*event));
        nhi_write_pos = new_write_pos;
    }
}
void mswin_nh_input_init (void)
Definition at line 22 of file mhinput.c.
References nhi_init_input, nhi_read_pos, and nhi_write_pos.
Referenced by mswin_init_nhwindows(), mswin_input_peek(), mswin_input_pop(), and mswin_input_push().
{
    if(!nhi_init_input) {
        nhi_init_input = 1;
        ZeroMemory(nhi_input_buffer, sizeof(nhi_input_buffer));
        nhi_read_pos = 0;
        nhi_write_pos = 0;
    }
}