nethack/win/win32/mhtext.h File Reference
#include `winMS.h`
*
#include `config.h`
*
#include `global.h`
*
Functions
HWND mswin_init_text_window (void)
void mswin_display_text_window (HWND hwnd)
Function Documentation
void mswin_display_text_window (HWND hwnd)
Definition at line 46 of file mhtext.c.
References mswin_nethack_text_window::done, IDC_TEXT_CONTROL, mswin_popup_destroy(), mswin_popup_display(), mswin_render_text(), NULL, and mswin_nethack_text_window::window_text.
Referenced by mswin_display_nhwindow(), and mswin_display_RIP_window().
{
    PNHTextWindow data;
    
    data = (PNHTextWindow)GetWindowLong(hWnd, GWL_USERDATA);
    if(data) {
        HWND control;
        control = GetDlgItem(hWnd, IDC_TEXT_CONTROL);
        SendMessage(control, EM_FMTLINES, 1, 0);
        mswin_render_text(data->window_text, GetDlgItem(hWnd,
      IDC_TEXT_CONTROL));
        data->done = 0;
        mswin_popup_display(hWnd, &data->done);
        mswin_popup_destroy(hWnd);
    }
}
HWND mswin_init_text_window (void)
Definition at line 23 of file mhtext.c.
References CreateDialog(), FALSE, sinfo::gameover, GetNHApp(), IDD_NHTEXT, malloc(), mswin_init_text_buffer(), NHTextWndProc(), panic(), program_state, TextWndProc(), and mswin_nethack_text_window::window_text.
Referenced by mswin_create_nhwindow(), and mswin_init_RIP_window().
                               {
    HWND ret;
    PNHTextWindow data;
    ret = CreateDialog(
            GetNHApp()->hApp,
            MAKEINTRESOURCE(IDD_NHTEXT),
            GetNHApp()->hMainWnd,
            TextWndProc
    );
    if(!ret) panic("Cannot create text window");
    data = (PNHTextWindow)malloc(sizeof(NHTextWindow));
    if(!data) panic("out of memory");
    ZeroMemory(data, sizeof(NHTextWindow));
    data->window_text = mswin_init_text_buffer(
            program_state.gameover? FALSE : GetNHApp()->bWrapText
        );
    SetWindowLong(ret, GWL_USERDATA, (LONG)data);
    return ret;
}