nethack/win/win32/mhmenu.h File Reference
#include `winMS.h`
*
#include `config.h`
*
#include `global.h`
*
Macros
#define MENU_TYPE_TEXT 1
#define MENU_TYPE_MENU 2
Functions
HWND mswin_init_menu_window (int type)
int mswin_menu_window_select_menu (HWND hwnd, int how, MENU_ITEM_P **)
void mswin_menu_window_size (HWND hwnd, LPSIZE sz)
Macro Definition Documentation
#define MENU_TYPE_MENU 2
Definition at line 12 of file mhmenu.h.
#define MENU_TYPE_TEXT 1
Definition at line 11 of file mhmenu.h.
Function Documentation
HWND mswin_init_menu_window (int type)
Definition at line 84 of file mhmenu.c.
References CreateDialog(), GetNHApp(), IDD_MENU, MenuWndProc(), panic(), and SetMenuType().
Referenced by mswin_putstr_ex(), and mswin_start_menu().
                                       {
    HWND ret;
    ret = CreateDialog(
            GetNHApp()->hApp,
            MAKEINTRESOURCE(IDD_MENU),
            GetNHApp()->hMainWnd,
            MenuWndProc
    );
    if(!ret) {
        panic("Cannot create menu window");
    }
    
    SetMenuType(ret, type);
    return ret;
}
int mswin_menu_window_select_menu (HWND hwnd, int how, MENU_ITEM_P **)
Definition at line 102 of file mhmenu.c.
References assert, mswin_nethack_menu_window::done, mswin_nethack_menu_window::how, malloc(), mswin_nethack_menu_window::menu, MENU_FIRST_PAGE, MENU_INVERT_ALL, MENU_INVERT_PAGE, MENU_ITEM_P, MENU_LAST_PAGE, MENU_NEXT_PAGE, MENU_PREVIOUS_PAGE, MENU_SEARCH, MENU_SELECT_ALL, MENU_SELECT_PAGE, MENU_TYPE_MENU, MENU_UNSELECT_ALL, MENU_UNSELECT_PAGE, mswin_popup_destroy(), mswin_popup_display(), NHMENU_IS_SELECTABLE, NHMENU_IS_SELECTED, NULL, panic(), PICK_ANY, PICK_NONE, PICK_ONE, reset_menu_count(), mswin_nethack_menu_window::result, SetMenuListType(), and mswin_nethack_menu_window::type.
Referenced by mswin_display_nhwindow(), and mswin_select_menu().
{
    PNHMenuWindow data;
    int ret_val;
    MENU_ITEM_P *selected = NULL;
    int i;
    char* ap;
    char accell_str[256];
    assert(_selected!=NULL);
    *_selected = NULL;
    ret_val = -1;
    data = (PNHMenuWindow)GetWindowLong(hWnd, GWL_USERDATA);
    /* set menu type */
    SetMenuListType(hWnd, how);
    /* Ok, now give items a unique accelerators */
    ZeroMemory(accell_str, sizeof(accell_str));
    ap = accell_str;
#if defined(WIN_CE_SMARTPHONE)
    if(data->menu.size>10) {
        *ap++ = MENU_FIRST_PAGE;
        *ap++ = MENU_LAST_PAGE;
        *ap++ = MENU_NEXT_PAGE;
        *ap++ = MENU_PREVIOUS_PAGE;
        if(data->how == PICK_ANY) {
            *ap++ = MENU_SELECT_ALL;
            *ap++ = MENU_UNSELECT_ALL;
            *ap++ = MENU_INVERT_ALL;
            *ap++ = MENU_SELECT_PAGE;
            *ap++ = MENU_UNSELECT_PAGE;
            *ap++ = MENU_INVERT_PAGE;
        }
        *ap++ = MENU_SEARCH;
    }
#endif
    if(data->type == MENU_TYPE_MENU) {
        char next_char = 'a';
        for(i=0; i<data->menu.size; i++) {
            if(data->menu.items[i].accelerator!=0) {
                *ap++ = data->menu.items[i].accelerator;
                next_char = (char)(data->menu.items[i].accelerator+1);
            } else if(NHMENU_IS_SELECTABLE(data->menu.items[i])) {
                if ((next_char>='a' && next_char<='z') ||
                     (next_char>='A' && next_char<='Z')) {
                     data->menu.items[i].accelerator = next_char;
                     *ap++ = data->menu.items[i].accelerator;
                } else {
                    if(next_char > 'z') next_char = 'A';
                    else if (next_char > 'Z') break;
                    data->menu.items[i].accelerator = next_char;
                    *ap++ = data->menu.items[i].accelerator;
                }
                next_char ++;
            }
        }
        /* collect group accelerators */
        data->menu.gacc[0] = '\0';
        ap = data->menu.gacc;
        if(data->how != PICK_NONE) {
            for(i=0; i<data->menu.size; i++) {
                if(data->menu.items[i].group_accel &&
                    !strchr(data->menu.gacc, data->menu.items[i].group_accel)) {
                    *ap++ = data->menu.items[i].group_accel;
                    *ap = '\x0';
                }
            }
        }
        reset_menu_count(NULL, data);
    }
#if defined(WIN_CE_SMARTPHONE)
    if(data->type==MENU_TYPE_MENU) NHSPhoneSetKeypadFromString(accell_str);
#endif
    mswin_popup_display(hWnd, &data->done);
    /* get the result */
    if(data->result != -1) {
        if(how==PICK_NONE) {
            if(data->result>=0) ret_val=0;
            else ret_val=-1;
        } else if(how==PICK_ONE || how==PICK_ANY) {
            /* count selected items */
            ret_val = 0;
            for(i=0; i<data->menu.size; i++) {
                if(NHMENU_IS_SELECTABLE(data->menu.items[i]) &&
                    NHMENU_IS_SELECTED(data->menu.items[i])) {
                    ret_val++;
                }
            }
            if(ret_val > 0) {
                int sel_ind;
                selected = (MENU_ITEM_P*)malloc(ret_val*sizeof(
      MENU_ITEM_P));
                if(!selected) panic("out of memory");
                sel_ind = 0;
                for(i=0; i<data->menu.size; i++) {
                    if(NHMENU_IS_SELECTABLE(data->menu.items[i]) &&
                        NHMENU_IS_SELECTED(data->menu.items[i])) {
                        selected[sel_ind].item = data->menu.items[i].identifier;
                        selected[sel_ind].count = data->menu.items[i].count;
                        sel_ind++;
                    }
                }
                ret_val = sel_ind;
                *_selected = selected;
            }
        }
    }
    mswin_popup_destroy(hWnd);
#if defined(WIN_CE_SMARTPHONE)
    if(data->type==MENU_TYPE_MENU) NHSPhoneSetKeypadDefault();
#endif
    return ret_val;
}
void mswin_menu_window_size (HWND hwnd, LPSIZE sz)
Definition at line 1317 of file mhmenu.c.
References ATR_NONE, BUFSZ, FALSE, GetMenuControl(), max, mswin_nethack_menu_window::menu, MENU_TYPE_MENU, mswin_get_font(), NH_A2W, NHW_MENU, NULL, TAB_SEPARATION, mswin_nethack_menu_window::text, TILE_X, and mswin_nethack_menu_window::type.
Referenced by mswin_layout_main_window(), and SetMenuListType().
{
    TEXTMETRIC tm;
    HWND control;
    HGDIOBJ saveFont;
    HDC hdc;
    PNHMenuWindow data;
    int i;
    RECT rt, wrt;
    int extra_cx;
    GetClientRect(hWnd, &rt);
    sz->cx = rt.right - rt.left;
    sz->cy = rt.bottom - rt.top;
    GetWindowRect(hWnd, &wrt);
    extra_cx = (wrt.right-wrt.left) - sz->cx;
    data = (PNHMenuWindow)GetWindowLong(hWnd, GWL_USERDATA);
    if(data) {
        control = GetMenuControl(hWnd);
        hdc = GetDC(control);
        if(data->type==MENU_TYPE_MENU) {
            /* Calculate the width of the list box. */
            saveFont = SelectObject(hdc, mswin_get_font(NHW_MENU,
      ATR_NONE, hdc, FALSE));
            GetTextMetrics(hdc, &tm);
            for(i=0; i<data->menu.size; i++) {
                LONG menuitemwidth = 0;
                int column;
                char *p, *p1;
                p1 = data->menu.items[i].str;
                p = strchr(data->menu.items[i].str, '\t');
                column = 0;
                for (;;) {
                    TCHAR wbuf[BUFSZ];
                    RECT tabRect;
                    SetRect (&tabRect, 0, 0, 1, 1);
                    if (p != NULL) *p = '\0'; /* for time being, view tab field as zstring */
                    DrawText(hdc,
                        NH_A2W(p1, wbuf, BUFSZ),
                        strlen(p1),
                        &tabRect,
                        DT_CALCRECT | DT_LEFT | DT_VCENTER | DT_SINGLELINE
                    );
                    /* it probably isn't necessary to recompute the tab width now, but do so
                     * just in case, honoring the previously computed value
                     */
                    menuitemwidth += max(data->menu.tab_stop_size[column],
                        tabRect.right - tabRect.left);
                    if (p != NULL) *p = '\t';
                    else /* last string so, */ break;
                    /* add the separation only when not the last item */
                    /* in the last item, we break out of the loop, in the statement just above */
                    menuitemwidth += TAB_SEPARATION;
                    ++column;
                    p1 = p + 1;
                    p = strchr(p1, '\t');
                }
                sz->cx = max(sz->cx,
                    (LONG)(2*TILE_X + menuitemwidth + tm.tmAveCharWidth*12 + tm.tmOverhang));
            }
            SelectObject(hdc, saveFont);
        } else {
            /* do not change size for text output - the text will be formatted to
               fit any window */
        }
        sz->cx += extra_cx;
        ReleaseDC(control, hdc);
    }
}