nethack/win/win32/mhmsgwnd.h File Reference
#include `winMS.h`
*
#include `config.h`
*
#include `global.h`
*
Functions
HWND mswin_init_message_window (void)
void mswin_message_window_size (HWND hWnd, LPSIZE sz)
Function Documentation
HWND mswin_init_message_window (void)
Definition at line 54 of file mhmsgwnd.c.
References GetNHApp(), NULL, panic(), register_message_window_class(), and szMessageWindowClass.
Referenced by mswin_create_nhwindow().
                                  {
    static int run_once = 0;
    HWND ret;
    DWORD style;
    if(!run_once) {
        register_message_window_class();
        run_once = 1;
    }
#ifdef MSG_WRAP_TEXT
    style = WS_BORDER | WS_CHILD | WS_CLIPSIBLINGS | WS_VSCROLL;
#else
    style = WS_BORDER | WS_CHILD | WS_CLIPSIBLINGS | WS_VSCROLL | WS_HSCROLL;
#endif
    ret = CreateWindow(
            szMessageWindowClass, /* registered class name */
            NULL, /* window name */
            style, /* window style */
            0, /* horizontal position of window */
            0, /* vertical position of window */
            0, /* window width */
            0, /* window height - set it later */
            GetNHApp()->hMainWnd, /* handle to parent or owner window */
            NULL, /* menu handle or child identifier */
            GetNHApp()->hApp, /* handle to application instance */
            NULL); /* window-creation data */
    if(!ret) panic("Cannot create message window");
    return ret;
}
void mswin_message_window_size (HWND hWnd, LPSIZE sz)
Definition at line 572 of file mhmsgwnd.c.
References ATR_NONE, FALSE, MSG_VISIBLE_LINES, mswin_get_font(), NHW_MESSAGE, mswin_nethack_message_window::xChar, mswin_nethack_message_window::xPage, mswin_nethack_message_window::xUpper, and mswin_nethack_message_window::yChar.
Referenced by mswin_layout_main_window(), and onCreate().
{
    PNHMessageWindow data;
    RECT rt, client_rt;
    GetWindowRect(hWnd, &rt);
    sz->cx = rt.right - rt.left;
    sz->cy = rt.bottom - rt.top;
    data = (PNHMessageWindow)GetWindowLong(hWnd, GWL_USERDATA);
    if(data) {
        /* set size to accomodate MSG_VISIBLE_LINES, highligh rectangle and
           horizontal scroll bar (difference between window rect and client rect */
        GetClientRect(hWnd, &client_rt);
        sz->cy = sz->cy-(client_rt.bottom - client_rt.top) +
                 data->yChar * MSG_VISIBLE_LINES + 4;
    }
}