nethack/win/win32/mswproc.c File Reference
#include `hack.h`
*
#include `dlb.h`
*
#include `func_tab.h`
*
#include `winMS.h`
*
#include `mhmap.h`
*
#include `mhstatus.h`
*
#include `mhtext.h`
*
#include `mhmsgwnd.h`
*
#include `mhmenu.h`
*
#include `mhsplash.h`
*
#include `mhmsg.h`
*
#include `mhinput.h`
*
#include `mhaskyn.h`
*
#include `mhdlg.h`
*
#include `mhrip.h`
*
#include `mhmain.h`
*
#include `mhfont.h`
*
#include `resource.h`
*
Data Structures
struct ctv
struct ctbv
Macros
#define LLEN 128
#define TOTAL_BRUSHES 10
#define STONE_LINE_LEN 16
#define CATEGORYKEY `Software`
#define COMPANYKEY `NetHack`
#define PRODUCTKEY `NetHack 3.4.3`
#define SETTINGSKEY `Settings`
#define MAINSHOWSTATEKEY `MainShowState`
#define MAINMINXKEY `MainMinX`
#define MAINMINYKEY `MainMinY`
#define MAINMAXXKEY `MainMaxX`
#define MAINMAXYKEY `MainMaxY`
#define MAINLEFTKEY `MainLeft`
#define MAINRIGHTKEY `MainRight`
#define MAINTOPKEY `MainTop`
#define MAINBOTTOMKEY `MainBottom`
#define INTFKEY `Interface`
Typedefs
typedef struct ctv color_table_value
typedef struct ctbv color_table_brush_value
Functions
void logDebug (const char *fmt,...)
static void mswin_main_loop (void)
static BOOL initMapTiles (void)
static void mswin_color_from_string (char *colorstring, HBRUSH *brushptr, COLORREF *colorptr)
static void prompt_for_player_selection (void)
void mswin_init_nhwindows (int *argc, char **argv)
void mswin_player_selection (void)
void mswin_askname (void)
void mswin_get_nh_event (void)
void mswin_exit_nhwindows (const char *str)
void mswin_suspend_nhwindows (const char *str)
void mswin_resume_nhwindows ()
winid mswin_create_nhwindow (int type)
void mswin_clear_nhwindow (winid wid)
void mswin_display_nhwindow (winid wid, BOOLEAN_P block)
HWND mswin_hwnd_from_winid (winid wid)
winid mswin_winid_from_handle (HWND hWnd)
winid mswin_winid_from_type (int type)
void mswin_window_mark_dead (winid wid)
void mswin_destroy_nhwindow (winid wid)
void mswin_curs (winid wid, int x, int y)
void mswin_putstr (winid wid, int attr, const char *text)
void mswin_putstr_ex (winid wid, int attr, const char *text, int app)
void mswin_display_file (const char *filename, BOOLEAN_P must_exist)
void mswin_start_menu (winid wid)
void mswin_add_menu (winid wid, int glyph, const ANY_P *identifier, CHAR_P accelerator, CHAR_P group_accel, int attr, const char *str, BOOLEAN_P presel)
void mswin_end_menu (winid wid, const char *prompt)
int mswin_select_menu (winid wid, int how, MENU_ITEM_P **selected)
void mswin_update_inventory ()
void mswin_mark_synch ()
void mswin_wait_synch ()
void mswin_cliparound (int x, int y)
void mswin_print_glyph (winid wid, XCHAR_P x, XCHAR_P y, int glyph)
void mswin_raw_print (const char *str)
void mswin_raw_print_bold (const char *str)
int mswin_nhgetch ()
int mswin_nh_poskey (int *x, int *y, int *mod)
void mswin_nhbell ()
int mswin_doprev_message ()
char mswin_yn_function (const char *question, const char *choices, CHAR_P def)
void mswin_getlin (const char *question, char *input)
int mswin_get_ext_cmd ()
void mswin_number_pad (int state)
void mswin_delay_output ()
void mswin_change_color ()
char * mswin_get_color_string ()
void mswin_start_screen ()
void mswin_end_screen ()
void mswin_outrip (winid wid, int how)
void mswin_preference_update (const char *pref)
void bail (const char *mesg)
void mswin_popup_display (HWND hWnd, int *done_indicator)
void mswin_popup_destroy (HWND hWnd)
void mswin_read_reg ()
void mswin_write_reg ()
void mswin_destroy_reg ()
int NHMessageBox (HWND hWnd, LPCTSTR text, UINT type)
Variables
const char * killed_by_prefix []
HBRUSH brush_table [TOTAL_BRUSHES]
int max_brush = 0
HBRUSH menu_bg_brush = NULL
HBRUSH menu_fg_brush = NULL
HBRUSH text_bg_brush = NULL
HBRUSH text_fg_brush = NULL
HBRUSH status_bg_brush = NULL
HBRUSH status_fg_brush = NULL
HBRUSH message_bg_brush = NULL
HBRUSH message_fg_brush = NULL
COLORREF menu_bg_color = RGB(0, 0, 0)
COLORREF menu_fg_color = RGB(0xFF, 0xFF, 0xFF)
COLORREF text_bg_color = RGB(0, 0, 0)
COLORREF text_fg_color = RGB(0xFF, 0xFF, 0xFF)
COLORREF status_bg_color = RGB(0, 0, 0)
COLORREF status_fg_color = RGB(0xFF, 0xFF, 0xFF)
COLORREF message_bg_color = RGB(0, 0, 0)
COLORREF message_fg_color = RGB(0xFF, 0xFF, 0xFF)
struct window_procs mswin_procs
static color_table_value color_table []
static color_table_brush_value color_table_brush []
Macro Definition Documentation
#define CATEGORYKEY `Software`
Definition at line 2108 of file mswproc.c.
Referenced by mswin_destroy_reg(), mswin_read_reg(), and mswin_write_reg().
#define COMPANYKEY `NetHack`
Definition at line 2109 of file mswproc.c.
Referenced by mswin_destroy_reg(), mswin_read_reg(), and mswin_write_reg().
#define INTFKEY `Interface`
Definition at line 2123 of file mswproc.c.
Referenced by mswin_read_reg(), and mswin_write_reg().
#define LLEN 128
Definition at line 28 of file mswproc.c.
Referenced by mswin_display_file().
#define MAINBOTTOMKEY `MainBottom`
Definition at line 2120 of file mswproc.c.
Referenced by mswin_read_reg(), and mswin_write_reg().
#define MAINLEFTKEY `MainLeft`
Definition at line 2117 of file mswproc.c.
Referenced by mswin_read_reg(), and mswin_write_reg().
#define MAINMAXXKEY `MainMaxX`
Definition at line 2115 of file mswproc.c.
Referenced by mswin_read_reg(), and mswin_write_reg().
#define MAINMAXYKEY `MainMaxY`
Definition at line 2116 of file mswproc.c.
Referenced by mswin_read_reg(), and mswin_write_reg().
#define MAINMINXKEY `MainMinX`
Definition at line 2113 of file mswproc.c.
Referenced by mswin_read_reg(), and mswin_write_reg().
#define MAINMINYKEY `MainMinY`
Definition at line 2114 of file mswproc.c.
Referenced by mswin_read_reg(), and mswin_write_reg().
#define MAINRIGHTKEY `MainRight`
Definition at line 2118 of file mswproc.c.
Referenced by mswin_read_reg(), and mswin_write_reg().
#define MAINSHOWSTATEKEY `MainShowState`
Definition at line 2112 of file mswproc.c.
Referenced by mswin_read_reg(), and mswin_write_reg().
#define MAINTOPKEY `MainTop`
Definition at line 2119 of file mswproc.c.
Referenced by mswin_read_reg(), and mswin_write_reg().
#define PRODUCTKEY `NetHack 3.4.3`
Definition at line 2110 of file mswproc.c.
Referenced by mswin_destroy_reg(), mswin_read_reg(), and mswin_write_reg().
#define SETTINGSKEY `Settings`
Definition at line 2111 of file mswproc.c.
Referenced by mswin_destroy_reg(), mswin_read_reg(), and mswin_write_reg().
#define STONE_LINE_LEN 16
Definition at line 1747 of file mswproc.c.
Referenced by mswin_outrip().
#define TOTAL_BRUSHES 10
Definition at line 43 of file mswproc.c.
Referenced by mswin_color_from_string().
Typedef Documentation
typedef struct ctbv color_table_brush_value
typedef struct ctv color_table_value
Function Documentation
void bail (const char * mesg)
Definition at line 1936 of file mswproc.c.
References clearlocks(), EXIT_SUCCESS, mswin_exit_nhwindows(), and terminate().
{
    clearlocks();
    mswin_exit_nhwindows(mesg);
    terminate(EXIT_SUCCESS);
    /*NOTREACHED*/
}
BOOL initMapTiles (void) [static]
Definition at line 1944 of file mswproc.c.
References mswin_nhwindow_app::bmpMapTiles, COLNO, FALSE, GetNHApp(), iflags, mswin_nhwindow_app::mapTile_X, mswin_nhwindow_app::mapTile_Y, mswin_nhwindow_app::mapTilesPerLine, mswin_hwnd_from_winid(), mswin_map_stretch(), NH_A2W, NULL, raw_print, ROWNO, SIZE, total_tiles_used, TRUE, instance_flags::wc_tile_file, instance_flags::wc_tile_height, instance_flags::wc_tile_width, and WIN_MAP.
Referenced by mswin_init_nhwindows().
{
    HBITMAP hBmp;
    BITMAP bm;
    TCHAR wbuf[MAX_PATH];
    int tl_num;
    SIZE map_size;
    extern int total_tiles_used;
    /* no file - no tile */
    if(!(iflags.wc_tile_file && *iflags.wc_tile_file))
        return TRUE;
    /* load bitmap */
    hBmp = LoadImage(
                GetNHApp()->hApp,
                NH_A2W(iflags.wc_tile_file, wbuf, MAX_PATH),
                IMAGE_BITMAP,
                0,
                0,
                LR_LOADFROMFILE | LR_DEFAULTSIZE
            );
    if(hBmp==NULL) {
        raw_print("Cannot load tiles from the file. Reverting back to default.");
        return FALSE;
    }
    /* calculate tile dimensions */
    GetObject(hBmp, sizeof(BITMAP), (LPVOID)&bm);
    if(bm.bmWidth%iflags.wc_tile_width ||
        bm.bmHeight%iflags.wc_tile_height) {
        DeleteObject(hBmp);
        raw_print("Tiles bitmap does not match tile_width and tile_height options. Reverting back
       to default.");
        return FALSE;
    }
    tl_num = (bm.bmWidth/iflags.wc_tile_width)*
             (bm.bmHeight/iflags.wc_tile_height);
    if(tl_num<total_tiles_used) {
        DeleteObject(hBmp);
        raw_print("Number of tiles in the bitmap is less than required by the game. Reverting back
       to default.");
        return FALSE;
    }
    /* set the tile information */
    if(GetNHApp()->bmpMapTiles!=GetNHApp()->bmpTiles) {
        DeleteObject(GetNHApp()->bmpMapTiles);
    }
    GetNHApp()->bmpMapTiles = hBmp;
    GetNHApp()->mapTile_X = iflags.wc_tile_width;
    GetNHApp()->mapTile_Y = iflags.wc_tile_height;
    GetNHApp()->mapTilesPerLine = bm.bmWidth / iflags.
      wc_tile_width;
    map_size.cx = GetNHApp()->mapTile_X * COLNO;
    map_size.cy = GetNHApp()->mapTile_Y * ROWNO;
    mswin_map_stretch(
        mswin_hwnd_from_winid(WIN_MAP),
        &map_size,
        TRUE
    );
    return TRUE;
}
void logDebug (const char * fmt, ...)
Definition at line 35 of file mswproc.c.
{ }
void mswin_add_menu (winid wid, int glyph, const ANY_P * identifier, CHAR_P accelerator, CHAR_P group_accel, int attr, const char * str, BOOLEAN_P presel)
Definition at line 1078 of file mswproc.c.
References mswin_nhmsg_add_menu::accelerator, mswin_nhmsg_add_menu::attr, GetNHApp(), mswin_nhmsg_add_menu::glyph, mswin_nhmsg_add_menu::group_accel, mswin_nhmsg_add_menu::identifier, logDebug(), MAXWINDOWS, MSNH_MSG_ADDMENU, NULL, mswin_nhmsg_add_menu::presel, mswin_nhmsg_add_menu::str, and WM_MSNH_COMMAND.
{
    logDebug("mswin_add_menu(%d, %d, %p, %c, %c, %d, %s, %d)\n",
             wid, glyph, identifier, (char)accelerator, (char)group_accel,
             attr, str, presel);
    if ((wid >= 0) &&
        (wid < MAXWINDOWS) &&
        (GetNHApp()->windowlist[wid].win != NULL))
    {
        MSNHMsgAddMenu data;
        ZeroMemory(&data, sizeof(data));
        data.glyph = glyph;
        data.identifier = identifier;
        data.accelerator = accelerator;
        data.group_accel = group_accel;
        data.attr = attr;
        data.str = str;
        data.presel = presel;
        SendMessage(
             GetNHApp()->windowlist[wid].win,
             WM_MSNH_COMMAND, (WPARAM)MSNH_MSG_ADDMENU, (LPARAM)&data
        );
    }
}
void mswin_askname (void)
Definition at line 655 of file mswproc.c.
References bail(), logDebug(), mswin_getlin_window(), PL_NSIZ, and plname.
{
    logDebug("mswin_askname()\n");
    if(mswin_getlin_window("Who are you?", plname,
      PL_NSIZ)==IDCANCEL) {
        bail("bye-bye");
        /* not reached */
    }
}
void mswin_change_color (void)
Definition at line 1708 of file mswproc.c.
References logDebug().
{
    logDebug("mswin_change_color()\n");
}
void mswin_clear_nhwindow (winid wid)
Definition at line 781 of file mswproc.c.
References GetNHApp(), iflags, Is_rogue_level, logDebug(), MAXWINDOWS, MSNH_MSG_CLEAR_WINDOW, mswin_hwnd_from_winid(), mswin_map_mode(), NHW_MAP, NULL, ROGUE_LEVEL_MAP_MODE, type, u, you::uz, instance_flags::wc_map_mode, WIN_MAP, and WM_MSNH_COMMAND.
{
    logDebug("mswin_clear_nhwindow(%d)\n", wid);
    if ((wid >= 0) &&
        (wid < MAXWINDOWS) &&
        (GetNHApp()->windowlist[wid].win != NULL))
    {
#ifdef REINCARNATION
        if(GetNHApp()->windowlist[wid].type == NHW_MAP) {
            if(Is_rogue_level(&u.uz))
                mswin_map_mode(mswin_hwnd_from_winid(
      WIN_MAP), ROGUE_LEVEL_MAP_MODE);
            else
                mswin_map_mode(mswin_hwnd_from_winid(
      WIN_MAP), iflags.wc_map_mode);
        }
#endif
        SendMessage(
             GetNHApp()->windowlist[wid].win,
             WM_MSNH_COMMAND, (WPARAM)MSNH_MSG_CLEAR_WINDOW, (LPARAM)
      NULL);
    }
}
void mswin_cliparound (int x, int y)
Definition at line 1209 of file mswproc.c.
References GetNHApp(), logDebug(), MAXWINDOWS, MSNH_MSG_CLIPAROUND, NULL, WIN_MAP, WM_MSNH_COMMAND, mswin_nhmsg_cliparound::x, and mswin_nhmsg_cliparound::y.
{
    winid wid = WIN_MAP;
    logDebug("mswin_cliparound(%d, %d)\n", x, y);
    if ((wid >= 0) &&
        (wid < MAXWINDOWS) &&
        (GetNHApp()->windowlist[wid].win != NULL))
    {
         MSNHMsgClipAround data;
         data.x = x;
         data.y = y;
         SendMessage(
             GetNHApp()->windowlist[wid].win,
             WM_MSNH_COMMAND, (WPARAM)MSNH_MSG_CLIPAROUND, (LPARAM)&data
      );
    }
}
static void mswin_color_from_string (char * colorstring, HBRUSH * brushptr, COLORREF * colorptr) [static]
Definition at line 2303 of file mswproc.c.
References brush_table, color_table, color_table_brush, ctv::colorstring, ctbv::colorstring, ctv::colorvalue, index(), max_brush, NULL, panic(), RGB, SYSCLR_TO_BRUSH, ctbv::syscolorvalue, and TOTAL_BRUSHES.
Referenced by mswin_init_nhwindows().
{
    color_table_value *ctv_ptr = color_table;
    color_table_brush_value *ctbv_ptr = color_table_brush;
    int red_value, blue_value, green_value;
    static char *hexadecimals = "0123456789abcdef";
    if (colorstring == NULL) return;
    if (*colorstring == '#') {
        if (strlen(++colorstring) != 6) return;
        red_value = index(hexadecimals, tolower(*colorstring++)) - hexadecimals;
        red_value *= 16;
        red_value += index(hexadecimals, tolower(*colorstring++)) - hexadecimals;
        green_value = index(hexadecimals, tolower(*colorstring++)) - hexadecimals;
        green_value *= 16;
        green_value += index(hexadecimals, tolower(*colorstring++)) - hexadecimals;
        blue_value = index(hexadecimals, tolower(*colorstring++)) - hexadecimals;
        blue_value *= 16;
        blue_value += index(hexadecimals, tolower(*colorstring++)) - hexadecimals;
        *colorptr = RGB(red_value, green_value, blue_value);
    } else {
        while (*ctv_ptr->colorstring && stricmp(ctv_ptr->colorstring, colorstring))
        ++ctv_ptr;
        if (*ctv_ptr->colorstring) {
        *colorptr = ctv_ptr->colorvalue;
        } else {
          while (*ctbv_ptr->colorstring && stricmp(ctbv_ptr->
      colorstring, colorstring))
            ++ctbv_ptr;
        if (*ctbv_ptr->colorstring) {
            *brushptr = SYSCLR_TO_BRUSH(ctbv_ptr->syscolorvalue);
            *colorptr = GetSysColor(ctbv_ptr->syscolorvalue);
        }
        }
    }
    if (max_brush > TOTAL_BRUSHES) panic("Too many colors!");
    *brushptr = CreateSolidBrush(*colorptr);
    brush_table[max_brush++] = *brushptr;
}
winid mswin_create_nhwindow (int type)
Definition at line 718 of file mswproc.c.
References mswin_nhwindow_data::dead, GetNHApp(), logDebug(), MAXWINDOWS, MSNH_MSG_ADDWND, mswin_init_map_window(), mswin_init_message_window(), mswin_init_status_window(), mswin_init_text_window(), NHW_MAP, NHW_MENU, NHW_MESSAGE, NHW_STATUS, NHW_TEXT, NULL, panic(), mswin_nhwindow_data::type, type, mswin_nhmsg_add_wnd::wid, mswin_nhwindow_data::win, mswin_nhwindow_app::windowlist, and WM_MSNH_COMMAND.
{
    winid i = 0;
    MSNHMsgAddWnd data;
    logDebug("mswin_create_nhwindow(%d)\n", type);
    /* Return the next available winid
     */
    for (i=1; i<MAXWINDOWS; i++)
      if (GetNHApp()->windowlist[i].win == NULL &&
          !GetNHApp()->windowlist[i].dead)
          break;
    if (i == MAXWINDOWS)
      panic ("ERROR: No windows available...\n");
    switch (type) {
    case NHW_MAP:
    {
        GetNHApp()->windowlist[i].win =
      mswin_init_map_window();
        GetNHApp()->windowlist[i].type = type;
        GetNHApp()->windowlist[i].dead = 0;
        break;
    }
    case NHW_MESSAGE:
    {
        GetNHApp()->windowlist[i].win =
      mswin_init_message_window();
        GetNHApp()->windowlist[i].type = type;
        GetNHApp()->windowlist[i].dead = 0;
        break;
    }
    case NHW_STATUS:
    {
        GetNHApp()->windowlist[i].win =
      mswin_init_status_window();
        GetNHApp()->windowlist[i].type = type;
        GetNHApp()->windowlist[i].dead = 0;
        break;
    }
    case NHW_MENU:
    {
        GetNHApp()->windowlist[i].win = NULL; //will create later
        GetNHApp()->windowlist[i].type = type;
        GetNHApp()->windowlist[i].dead = 1;
        break;
    }
    case NHW_TEXT:
    {
        GetNHApp()->windowlist[i].win =
      mswin_init_text_window();
        GetNHApp()->windowlist[i].type = type;
        GetNHApp()->windowlist[i].dead = 0;
        break;
    }
    }
    ZeroMemory(&data, sizeof(data));
    data.wid = i;
    SendMessage(GetNHApp()->hMainWnd,
                 WM_MSNH_COMMAND, (WPARAM)MSNH_MSG_ADDWND, (LPARAM)&data);
    return i;
}
void mswin_curs (winid wid, int x, int y)
Definition at line 905 of file mswproc.c.
References GetNHApp(), logDebug(), MAXWINDOWS, MSNH_MSG_CURSOR, NULL, WM_MSNH_COMMAND, mswin_nhmsg_cursor::x, and mswin_nhmsg_cursor::y.
{
    logDebug("mswin_curs(%d, %d, %d)\n", wid, x, y);
    if ((wid >= 0) &&
        (wid < MAXWINDOWS) &&
        (GetNHApp()->windowlist[wid].win != NULL))
    {
         MSNHMsgCursor data;
         data.x = x;
         data.y = y;
         SendMessage(
             GetNHApp()->windowlist[wid].win,
             WM_MSNH_COMMAND, (WPARAM)MSNH_MSG_CURSOR, (LPARAM)&data);
    }
}
void mswin_delay_output (void)
Definition at line 1702 of file mswproc.c.
References logDebug().
{
    logDebug("mswin_delay_output()\n");
    Sleep(50);
}
void mswin_destroy_nhwindow (winid wid)
Definition at line 879 of file mswproc.c.
References mswin_nhwindow_data::dead, GetNHApp(), logDebug(), NHW_MAP, NHW_MESSAGE, NHW_STATUS, NULL, mswin_nhwindow_data::type, type, mswin_nhwindow_data::win, and mswin_nhwindow_app::windowlist.
{
    logDebug("mswin_destroy_nhwindow(%d)\n", wid);
    if ((GetNHApp()->windowlist[wid].type == NHW_MAP) ||
        (GetNHApp()->windowlist[wid].type == NHW_MESSAGE) ||
        (GetNHApp()->windowlist[wid].type == NHW_STATUS)) {
        /* main windows is going to take care of those */
        return;
    }
    if (wid != -1) {
        if(!GetNHApp()->windowlist[wid].dead &&
            GetNHApp()->windowlist[wid].win != NULL)
            DestroyWindow(GetNHApp()->windowlist[wid].win);
        GetNHApp()->windowlist[wid].win = NULL;
        GetNHApp()->windowlist[wid].type = 0;
        GetNHApp()->windowlist[wid].dead = 0;
    }
}
void mswin_destroy_reg (void)
Definition at line 2198 of file mswproc.c.
References CATEGORYKEY, COMPANYKEY, GetNHApp(), NULL, PRODUCTKEY, mswin_nhwindow_app::saveRegistrySettings, and SETTINGSKEY.
{
    char keystring[MAX_PATH];
    HKEY key;
    DWORD nrsubkeys;
    /* Delete keys one by one, as NT does not delete trees */
    sprintf(keystring, "%s\\%s\\%s\\%s",
        CATEGORYKEY, COMPANYKEY, PRODUCTKEY,
      SETTINGSKEY);
    RegDeleteKey(HKEY_CURRENT_USER, keystring);
    sprintf(keystring, "%s\\%s\\%s",
        CATEGORYKEY, COMPANYKEY, PRODUCTKEY);
    RegDeleteKey(HKEY_CURRENT_USER, keystring);
    /* The company key will also contain information about newer versions
       of nethack (e.g. a subkey called NetHack 4.0), so only delete that
       if it's empty now. */
    sprintf(keystring, "%s\\%s", CATEGORYKEY, COMPANYKEY);
    /* If we cannot open it, we probably cannot delete it either... Just
       go on and see what happens. */
    RegOpenKeyEx(HKEY_CURRENT_USER, keystring, 0, KEY_READ, &key);
    nrsubkeys = 0;
    RegQueryInfoKey(key, NULL, NULL, NULL, &nrsubkeys, NULL,
      NULL, NULL,
        NULL, NULL, NULL, NULL);
    RegCloseKey(key);
    if (nrsubkeys == 0)
        RegDeleteKey(HKEY_CURRENT_USER, keystring);
    /* Prevent saving on exit */
    GetNHApp()->saveRegistrySettings = 0;
}
void mswin_display_file (const char * filename, BOOLEAN_P must_exist)
Definition at line 989 of file mswproc.c.
References ATR_NONE, BUFSZ, dlb, dlb_fclose, dlb_fgets, dlb_fopen, GetNHApp(), LLEN, logDebug(), MessageBox(), mswin_create_nhwindow(), mswin_destroy_nhwindow(), mswin_display_nhwindow(), mswin_putstr(), NH_A2W, NHMessageBox(), NHW_TEXT, and RDTMODE.
{
    dlb *f;
    TCHAR wbuf[BUFSZ];
    logDebug("mswin_display_file(%s, %d)\n", filename, must_exist);
    f = dlb_fopen(filename, RDTMODE);
    if (!f) {
        if (must_exist) {
            TCHAR message[90];
            _stprintf(message, TEXT("Warning! Could not find file: %s\n"),
      NH_A2W(filename, wbuf, sizeof(wbuf)));
            NHMessageBox(GetNHApp()->hMainWnd, message, MB_OK | MB_ICONEXCLAMATION);
        }
    } else {
        winid text;
        char line[LLEN];
        text = mswin_create_nhwindow(NHW_TEXT);
        while (dlb_fgets(line, LLEN, f)) {
             size_t len;
             len = strlen(line);
             if(line[len-1]=='\n') line[len-1]='\x0';
                mswin_putstr(text, ATR_NONE, line);
        }
        (void) dlb_fclose(f);
        mswin_display_nhwindow(text, 1);
        mswin_destroy_nhwindow(text);
    }
}
void mswin_display_nhwindow (winid wid, BOOLEAN_P block)
Definition at line 813 of file mswproc.c.
References GetNHApp(), logDebug(), MENU_ITEM_P, mswin_display_RIP_window(), mswin_display_text_window(), mswin_menu_window_select_menu(), mswin_nhgetch(), NHW_MAP, NHW_MENU, NHW_RIP, NHW_TEXT, NULL, PICK_NONE, and type.
{
    logDebug("mswin_display_nhwindow(%d, %d)\n", wid, block);
    if (GetNHApp()->windowlist[wid].win != NULL)
    {
        if (GetNHApp()->windowlist[wid].type == NHW_MENU) {
            MENU_ITEM_P* p;
            mswin_menu_window_select_menu(GetNHApp()->windowlist[wid].
      win, PICK_NONE, &p);
        } if (GetNHApp()->windowlist[wid].type == NHW_TEXT) {
            mswin_display_text_window(GetNHApp()->windowlist[wid].win);
        } if (GetNHApp()->windowlist[wid].type == NHW_RIP) {
            mswin_display_RIP_window(GetNHApp()->windowlist[wid].win);
        } else {
            if(!block) {
                UpdateWindow(GetNHApp()->windowlist[wid].win);
            } else {
                if (GetNHApp()->windowlist[wid].type == NHW_MAP) {
                    (void) mswin_nhgetch();
                }
            }
        }
        SetFocus(GetNHApp()->hMainWnd);
    }
}
int mswin_doprev_message (void)
Definition at line 1357 of file mswproc.c.
References logDebug(), mswin_hwnd_from_winid(), NULL, and WIN_MESSAGE.
{
    logDebug("mswin_doprev_message()\n");
    SendMessage(mswin_hwnd_from_winid(WIN_MESSAGE), WM_VSCROLL, MAKEWPARAM(
      SB_LINEUP, 0), (LPARAM)NULL);
    return 0;
}
void mswin_end_menu (winid wid, const char * prompt)
Definition at line 1115 of file mswproc.c.
References GetNHApp(), logDebug(), MAXWINDOWS, MSNH_MSG_ENDMENU, NULL, mswin_nhmsg_end_menu::text, and WM_MSNH_COMMAND.
{
    logDebug("mswin_end_menu(%d, %s)\n", wid, prompt);
    if ((wid >= 0) &&
        (wid < MAXWINDOWS) &&
        (GetNHApp()->windowlist[wid].win != NULL))
    {
        MSNHMsgEndMenu data;
        ZeroMemory(&data, sizeof(data));
        data.text = prompt;
        SendMessage(
             GetNHApp()->windowlist[wid].win,
             WM_MSNH_COMMAND, (WPARAM)MSNH_MSG_ENDMENU, (LPARAM)&data
        );
    }
}
void mswin_end_screen (void)
Definition at line 1736 of file mswproc.c.
References logDebug().
{
    /* Do Nothing */
    logDebug("mswin_end_screen()\n");
}
void mswin_exit_nhwindows (const char * str)
Definition at line 686 of file mswproc.c.
References brush_table, logDebug(), max_brush, and mswin_write_reg().
{
    logDebug("mswin_exit_nhwindows(%s)\n", str);
    /* Write Window settings to the registry */
    mswin_write_reg();
    while (max_brush)
    DeleteObject(brush_table[--max_brush]);
}
char* mswin_get_color_string (void)
Definition at line 1713 of file mswproc.c.
References logDebug().
{
    logDebug("mswin_get_color_string()\n");
    return("");
}
int mswin_get_ext_cmd (void)
Definition at line 1598 of file mswproc.c.
References ATR_BOLD, BUFSZ, ext_func_tab::ef_txt, extcmdlist, iflags, logDebug(), MSNH_MSG_CARET, mswin_clear_nhwindow(), mswin_ext_cmd_window(), mswin_hwnd_from_winid(), mswin_nhgetch(), mswin_putstr_ex(), strcmpi, Strcpy, strncmpi(), instance_flags::wc_popup_dialog, WIN_MESSAGE, and WM_MSNH_COMMAND.
{
    int ret;
    logDebug("mswin_get_ext_cmd()\n");
    if (!iflags.wc_popup_dialog)
    {
        char c;
        char cmd[BUFSZ];
        int i, len;
        int createcaret;
        createcaret = 1;
        SendMessage(mswin_hwnd_from_winid(WIN_MESSAGE),
            WM_MSNH_COMMAND, (WPARAM)MSNH_MSG_CARET, (LPARAM)&createcaret);
        cmd[0] = '\0';
        i = -2;
 mswin_clear_nhwindow(WIN_MESSAGE);
        mswin_putstr_ex(WIN_MESSAGE, ATR_BOLD, "#", 0);
        len = 0;
        ShowCaret(mswin_hwnd_from_winid(WIN_MESSAGE));
        while (i == -2)
        {
            int oindex, com_index;
            c = mswin_nhgetch();
            switch (c)
            {
                case VK_ESCAPE:
                    i = -1;
                    break;
                case '\n':
                case '\r':
                case -115:
                    for (i = 0; extcmdlist[i].ef_txt != (char *)0; i++)
                        if (!strcmpi(cmd, extcmdlist[i].ef_txt)) break;
                    if (extcmdlist[i].ef_txt == (char *)0) {
                        pline("%s: unknown extended command.", cmd);
                        i = -1;
                    }
                    break;
                default:
                    if (cmd[0])
                        mswin_putstr_ex(WIN_MESSAGE,
      ATR_BOLD, cmd, -(int)strlen(cmd));
                    if (c == VK_BACK)
                    {
                        if (len > 0) len--;
                        cmd[len] = '\0';
                    }
                    else
                    {
                        cmd[len++] = c;
                        cmd[len] = '\0';
                        /* Find a command with this prefix in extcmdlist */
                        com_index = -1;
                        for (oindex = 0; extcmdlist[oindex].ef_txt != (char *)0; oindex++)
      {
                            if (!strncmpi(cmd, extcmdlist[oindex].ef_txt, len)) {
                                if (com_index == -1) /* no matches yet */
                                    com_index = oindex;
                                else
                                    com_index = -2; /* two matches, don't complete */
                            }
                        }
                        if (com_index >= 0) {
                            Strcpy(cmd, extcmdlist[com_index].ef_txt);
                        }
                    }
                    mswin_putstr_ex(WIN_MESSAGE,
      ATR_BOLD, cmd, 1);
                    break;
            }
        }
        HideCaret(mswin_hwnd_from_winid(WIN_MESSAGE));
        createcaret = 0;
        SendMessage(mswin_hwnd_from_winid(WIN_MESSAGE),
            WM_MSNH_COMMAND, (WPARAM)MSNH_MSG_CARET, (LPARAM)&createcaret);
        return i;
    }
    else
    {
        if(mswin_ext_cmd_window (&ret) == IDCANCEL)
            return -1;
        else
            return ret;
    }
}
void mswin_get_nh_event (void)
Definition at line 669 of file mswproc.c.
References GetNHApp(), logDebug(), and NULL.
{
    MSG msg;
    logDebug("mswin_get_nh_event()\n");
    while (PeekMessage(&msg, NULL, 0, 0, PM_REMOVE)!=0) {
        if (!TranslateAccelerator(msg.hwnd, GetNHApp()->hAccelTable, &msg)) {
            TranslateMessage(&msg);
            DispatchMessage(&msg);
        }
    }
    return;
}
void mswin_getlin (const char * question, char * input)
Definition at line 1527 of file mswproc.c.
References ATR_BOLD, ATR_NONE, BUFSZ, done, FALSE, iflags, logDebug(), MSNH_MSG_CARET, mswin_clear_nhwindow(), mswin_getlin_window(), mswin_hwnd_from_winid(), mswin_nhgetch(), mswin_putstr_ex(), TRUE, instance_flags::wc_popup_dialog, WIN_MESSAGE, and WM_MSNH_COMMAND.
{
    logDebug("mswin_getlin(%s, %p)\n", question, input);
    if (!iflags.wc_popup_dialog)
    {
        char c;
        int len;
        int done;
        int createcaret;
        createcaret = 1;
        SendMessage(mswin_hwnd_from_winid(WIN_MESSAGE),
            WM_MSNH_COMMAND, (WPARAM)MSNH_MSG_CARET, (LPARAM)&createcaret);
 mswin_clear_nhwindow(WIN_MESSAGE);
        mswin_putstr_ex(WIN_MESSAGE, ATR_BOLD, question, 0);
        mswin_putstr_ex(WIN_MESSAGE, ATR_BOLD, " ", 1);
        input[0] = '\0';
        len = 0;
        ShowCaret(mswin_hwnd_from_winid(WIN_MESSAGE));
        done = FALSE;
        while (!done)
        {
            c = mswin_nhgetch();
            switch (c)
            {
                case VK_ESCAPE:
                    strcpy(input, "\033");
                    done = TRUE;
                    break;
                case '\n':
                case '\r':
                case -115:
                    done = TRUE;
                    break;
                default:
                    if (input[0])
                        mswin_putstr_ex(WIN_MESSAGE,
      ATR_NONE, input, -len);
                    if (c == VK_BACK) {
                        if (len > 0) len--;
                        input[len] = '\0';
                    } else {
                        input[len++] = c;
                        input[len] = '\0';
                    }
                    mswin_putstr_ex(WIN_MESSAGE,
      ATR_NONE, input, 1);
                    break;
            }
        }
        HideCaret(mswin_hwnd_from_winid(WIN_MESSAGE));
        createcaret = 0;
        SendMessage(mswin_hwnd_from_winid(WIN_MESSAGE),
            WM_MSNH_COMMAND, (WPARAM)MSNH_MSG_CARET, (LPARAM)&createcaret);
    }
    else
    {
        if(mswin_getlin_window(question, input, BUFSZ)==IDCANCEL) {
            strcpy(input, "\033");
        }
    }
}
HWND mswin_hwnd_from_winid (winid wid)
Definition at line 839 of file mswproc.c.
References GetNHApp(), MAXWINDOWS, NULL, mswin_nhwindow_data::win, and mswin_nhwindow_app::windowlist.
{
    if(wid>=0 && wid<MAXWINDOWS) {
        return GetNHApp()->windowlist[wid].win;
    } else {
        return NULL;
    }
}
void mswin_init_nhwindows (int * argc, char ** argv)
Definition at line 141 of file mswproc.c.
References ALIGN_BOTTOM, ALIGN_TOP, mswin_nhwindow_app::bFullScreen, mswin_nhwindow_app::bUseSIP, mswin_nhwindow_app::bWrapText, DEF_CLIPAROUND_AMOUNT, DEF_CLIPAROUND_MARGIN, DISP_IN_GAME, FALSE, flags, GetNHApp(), mswin_nhwindow_app::hMainWnd, iflags, initMapTiles(), logDebug(), menu_bg_brush, menu_bg_color, menu_fg_brush, menu_fg_color, instance_flags::menu_tab_sep, message_bg_brush, message_bg_color, message_fg_brush, message_fg_color, mswin_color_from_string(), mswin_display_splash_window(), mswin_init_color_table(), mswin_init_main_window(), mswin_menu_check_intf_mode(), mswin_nh_input_init(), mswin_read_reg(), mswin_set_fullscreen(), NHFONT_DEFAULT_SIZE, NHFONT_SIZE_MAX, NHFONT_SIZE_MIN, NHFONT_STATUS_DEFAULT_SIZE, panic(), mswin_nhwindow_app::regMainMinX, SET_IN_FILE, SET_IN_GAME, set_option_mod_status(), set_wc2_option_mod_status(), set_wc_option_mod_status(), status_bg_brush, status_bg_color, status_fg_brush, status_fg_color, text_bg_brush, text_bg_color, text_fg_brush, text_fg_color, TILE_X, TILE_Y, flag::toptenwin, TRUE, WC2_FULLSCREEN, instance_flags::wc2_fullscreen, WC2_SOFTKEYBOARD, instance_flags::wc2_softkeyboard, WC2_WRAPTEXT, instance_flags::wc2_wraptext, WC_ALIGN_MESSAGE, instance_flags::wc_align_message, WC_ALIGN_STATUS, instance_flags::wc_align_status, instance_flags::wc_backgrnd_menu, instance_flags::wc_backgrnd_message, instance_flags::wc_backgrnd_status, instance_flags::wc_backgrnd_text, WC_FONT_MENU, WC_FONT_MESSAGE, WC_FONT_STATUS, WC_FONT_TEXT, WC_FONTSIZ_MENU, instance_flags::wc_fontsiz_menu, WC_FONTSIZ_MESSAGE, instance_flags::wc_fontsiz_message, WC_FONTSIZ_STATUS, instance_flags::wc_fontsiz_status, WC_FONTSIZ_TEXT, instance_flags::wc_fontsiz_text, instance_flags::wc_foregrnd_menu, instance_flags::wc_foregrnd_message, instance_flags::wc_foregrnd_status, instance_flags::wc_foregrnd_text, WC_HILITE_PET, WC_MAP_MODE, WC_SCROLL_AMOUNT, instance_flags::wc_scroll_amount, WC_SCROLL_MARGIN, instance_flags::wc_scroll_margin, instance_flags::wc_splash_screen, WC_TILE_FILE, WC_TILE_HEIGHT, instance_flags::wc_tile_height, WC_TILE_WIDTH, instance_flags::wc_tile_width, WC_VARY_MSGCOUNT, instance_flags::wc_vary_msgcount, WIN_ERR, WIN_MAP, and instance_flags::window_inited.
{
    logDebug("mswin_init_nhwindows()\n");
#ifdef _DEBUG
    {
        /* truncate trace file */
        FILE *dfp = fopen("nhtrace.log", "w");
        fclose(dfp);
    }
#endif
    mswin_nh_input_init();
    /* set it to WIN_ERR so we can detect attempts to
       use this ID before it is inialized */
    WIN_MAP = WIN_ERR;
    /* Read Windows settings from the reqistry */
    /* First set safe defaults */
    GetNHApp()->regMainMinX = CW_USEDEFAULT;
    mswin_read_reg();
    /* Create the main window */
    GetNHApp()->hMainWnd = mswin_init_main_window();
    if (!GetNHApp()->hMainWnd)
    {
        panic("Cannot create main window");
    }
    /* Set menu check mark for interface mode */
    mswin_menu_check_intf_mode();
    /* check default values */
    if(iflags.wc_fontsiz_status<NHFONT_SIZE_MIN ||
        iflags.wc_fontsiz_status>NHFONT_SIZE_MAX)
        iflags.wc_fontsiz_status = NHFONT_DEFAULT_SIZE;
    if(iflags.wc_fontsiz_message<NHFONT_SIZE_MIN ||
        iflags.wc_fontsiz_message>NHFONT_SIZE_MAX)
        iflags.wc_fontsiz_message = NHFONT_DEFAULT_SIZE;
    if(iflags.wc_fontsiz_text<NHFONT_SIZE_MIN ||
        iflags.wc_fontsiz_text>NHFONT_SIZE_MAX)
        iflags.wc_fontsiz_text = NHFONT_DEFAULT_SIZE;
    if(iflags.wc_fontsiz_menu<NHFONT_SIZE_MIN ||
        iflags.wc_fontsiz_menu>NHFONT_SIZE_MAX)
        iflags.wc_fontsiz_menu = NHFONT_DEFAULT_SIZE;
    if(iflags.wc_align_message==0) iflags.
      wc_align_message = ALIGN_TOP;
    if(iflags.wc_align_status==0) iflags.
      wc_align_status = ALIGN_BOTTOM;
    if(iflags.wc_scroll_margin==0) iflags.
      wc_scroll_margin = DEF_CLIPAROUND_MARGIN;
    if(iflags.wc_scroll_amount==0) iflags.
      wc_scroll_amount = DEF_CLIPAROUND_AMOUNT;
    if(iflags.wc_tile_width==0) iflags.wc_tile_width =
      TILE_X;
    if(iflags.wc_tile_height==0) iflags.
      wc_tile_height = TILE_Y;
    if(iflags.wc_vary_msgcount==0) iflags.
      wc_vary_msgcount = 4;
    /* force tabs in menus */
    iflags.menu_tab_sep = 1;
    /* force toptenwin to be true. toptenwin is the option that decides whether to
     * write output to a window or stdout. stdout doesn't make sense on Windows
     * non-console applications
     */
    flags.toptenwin = 1;
    set_option_mod_status("toptenwin", SET_IN_FILE);
    set_option_mod_status("perm_invent", SET_IN_FILE);
    /* initialize map tiles bitmap */
    initMapTiles();
    /* set tile-related options to readonly */
    set_wc_option_mod_status(
       WC_TILE_WIDTH|WC_TILE_HEIGHT|WC_TILE_FILE,
       DISP_IN_GAME);
    /* set font-related options to change in the game */
    set_wc_option_mod_status(
        WC_HILITE_PET |
        WC_ALIGN_MESSAGE |
        WC_ALIGN_STATUS |
        WC_SCROLL_AMOUNT |
        WC_SCROLL_MARGIN |
        WC_MAP_MODE |
        WC_FONT_MESSAGE |
        WC_FONT_STATUS |
        WC_FONT_MENU |
        WC_FONT_TEXT |
        WC_FONTSIZ_MESSAGE |
        WC_FONTSIZ_STATUS |
        WC_FONTSIZ_MENU |
        WC_FONTSIZ_TEXT |
        WC_VARY_MSGCOUNT,
        SET_IN_GAME
    );
    mswin_color_from_string(iflags.wc_foregrnd_menu, &
      menu_fg_brush, &menu_fg_color);
    mswin_color_from_string(iflags.
      wc_foregrnd_message, &message_fg_brush, &
      message_fg_color);
    mswin_color_from_string(iflags.
      wc_foregrnd_status, &status_fg_brush, &
      status_fg_color);
    mswin_color_from_string(iflags.wc_foregrnd_text, &
      text_fg_brush, &text_fg_color);
    mswin_color_from_string(iflags.wc_backgrnd_menu, &
      menu_bg_brush, &menu_bg_color);
    mswin_color_from_string(iflags.
      wc_backgrnd_message, &message_bg_brush, &
      message_bg_color);
    mswin_color_from_string(iflags.
      wc_backgrnd_status, &status_bg_brush, &
      status_bg_color);
    mswin_color_from_string(iflags.wc_backgrnd_text, &
      text_bg_brush, &text_bg_color);
 if (iflags.wc_splash_screen) mswin_display_splash_window(
      FALSE);
    iflags.window_inited = TRUE;
}
void mswin_main_loop (void) [static]
Definition at line 1920 of file mswproc.c.
References GetNHApp(), mswin_have_input(), and NULL.
Referenced by mswin_nh_poskey(), and mswin_nhgetch().
{
    MSG msg;
    while(!mswin_have_input() &&
           GetMessage(&msg, NULL, 0, 0)!=0) {
        if (GetNHApp()->regNetHackMode ||
            !TranslateAccelerator(msg.hwnd, GetNHApp()->hAccelTable, &msg))
        {
            TranslateMessage(&msg);
            DispatchMessage(&msg);
        }
    }
}
void mswin_mark_synch (void)
Definition at line 1188 of file mswproc.c.
References logDebug().
{
    logDebug("mswin_mark_synch()\n");
}
int mswin_nh_poskey (int * x, int * y, int * mod)
Definition at line 1323 of file mswproc.c.
References logDebug(), mswin_input_pop(), mswin_main_loop(), NHEVENT_MOUSE, NULL, and mswin_event::type.
{
    PMSNHEvent event;
    int key;
    logDebug("mswin_nh_poskey()\n");
    while((event = mswin_input_pop())==NULL)
      mswin_main_loop();
    if(event->type==NHEVENT_MOUSE) {
        *mod = event->ms.mod;
        *x = event->ms.x;
        *y = event->ms.y;
        key = 0;
    } else {
        key = event->kbd.ch;
    }
    return (key);
}
void mswin_nhbell (void)
Definition at line 1347 of file mswproc.c.
References logDebug().
{
    logDebug("mswin_nhbell()\n");
}
int mswin_nhgetch (void)
Definition at line 1292 of file mswproc.c.
References logDebug(), mswin_input_pop(), mswin_main_loop(), NHEVENT_CHAR, NULL, and mswin_event::type.
{
    PMSNHEvent event;
    int key = 0;
    logDebug("mswin_nhgetch()\n");
    
    while((event = mswin_input_pop()) == NULL ||
           event->type != NHEVENT_CHAR)
        mswin_main_loop();
    key = event->kbd.ch;
    return (key);
}
void mswin_number_pad (int state)
Definition at line 1691 of file mswproc.c.
References logDebug().
{
    /* Do Nothing */
    logDebug("mswin_number_pad(%d)\n", state);
}
void mswin_outrip (winid wid, int how)
Definition at line 1748 of file mswproc.c.
References buf, BUFSZ, mswin_nhwindow_data::dead, GetNHApp(), KILLED_BY, KILLED_BY_AN, killed_by_prefix, killer, killer_format, logDebug(), MAXWINDOWS, mswin_finish_rip_text(), mswin_init_RIP_window(), NHW_RIP, NO_KILLER_PREFIX, plname, putstr, Sprintf, STONE_LINE_LEN, Strcat, Strcpy, mswin_nhwindow_data::type, u, you::ugold, mswin_nhwindow_data::win, and mswin_nhwindow_app::windowlist.
{
    char buf[BUFSZ];
    logDebug("mswin_outrip(%d)\n", wid, how);
    if ((wid >= 0) && (wid < MAXWINDOWS)) {
        DestroyWindow(GetNHApp()->windowlist[wid].win);
        GetNHApp()->windowlist[wid].win =
      mswin_init_RIP_window();
        GetNHApp()->windowlist[wid].type = NHW_RIP;
        GetNHApp()->windowlist[wid].dead = 0;
    }
    /* Put name on stone */
    Sprintf(buf, "%s", plname);
    buf[STONE_LINE_LEN] = 0;
    putstr(wid, 0, buf);
    /* Put $ on stone */
#ifndef GOLDOBJ
    Sprintf(buf, "%ld Au", u.ugold);
#else
    Sprintf(buf, "%ld Au", done_money);
#endif
    buf[STONE_LINE_LEN] = 0; /* It could be a *lot* of gold :-) */
    putstr(wid, 0, buf);
    /* Put together death description */
    switch (killer_format) {
        default: impossible("bad killer format?");
        case KILLED_BY_AN:
            Strcpy(buf, killed_by_prefix[how]);
            Strcat(buf, an(killer));
            break;
        case KILLED_BY:
            Strcpy(buf, killed_by_prefix[how]);
            Strcat(buf, killer);
            break;
        case NO_KILLER_PREFIX:
            Strcpy(buf, killer);
            break;
    }
    /* Put death type on stone */
    putstr(wid, 0, buf);
    /* Put year on stone */
    Sprintf(buf, "%4d", getyear());
    putstr(wid, 0, buf);
    mswin_finish_rip_text(wid);
}
void mswin_player_selection (void)
Definition at line 255 of file mswproc.c.
References bail(), flags, iflags, flag::initalign, flag::initgend, flag::initrace, flag::initrole, logDebug(), mswin_player_selection_window(), pick_align(), pick_gend(), pick_race(), PICK_RANDOM, pick_role(), prompt_for_player_selection(), randalign(), randgend(), flag::randomall, randrace(), randrole(), raw_print, validalign(), validgend(), validrace(), VIA_DIALOG, and instance_flags::wc_player_selection.
{
    int nRole;
    logDebug("mswin_player_selection()\n");
    if (iflags.wc_player_selection == VIA_DIALOG) {
        /* pick player type randomly (use pre-selected role/race/gender/alignment) */
        if(flags.randomall) {
        if (flags.initrole < 0) {
            flags.initrole = pick_role(flags.initrace,
      flags.initgend,
                            flags.initalign, PICK_RANDOM);
            if (flags.initrole < 0) {
                raw_print("Incompatible role!");
                flags.initrole = randrole();
            }
        }
        if (flags.initrace < 0 || !validrace(flags.
      initrole, flags.initrace)) {
            flags.initrace = pick_race(flags.initrole,
      flags.initgend,
                                flags.initalign, PICK_RANDOM);
            if (flags.initrace < 0) {
                raw_print("Incompatible race!");
                flags.initrace = randrace(flags.
      initrole);
            }
        }
        if (flags.initgend < 0 || !validgend(flags.
      initrole, flags.initrace,
                        flags.initgend)) {
            flags.initgend = pick_gend(flags.initrole,
      flags.initrace,
                            flags.initalign, PICK_RANDOM);
            if (flags.initgend < 0) {
                raw_print("Incompatible gender!");
                flags.initgend = randgend(flags.
      initrole, flags.initrace);
            }
        }
        if (flags.initalign < 0 || !validalign(flags.
      initrole, flags.initrace,
                                flags.initalign)) {
            flags.initalign = pick_align(flags.
      initrole, flags.initrace,
                                flags.initgend, PICK_RANDOM);
            if (flags.initalign < 0) {
                raw_print("Incompatible alignment!");
                flags.initalign = randalign(flags.
      initrole, flags.initrace);
            }
        }
        } else {
        /* select a role */
        if(mswin_player_selection_window(&nRole) == IDCANCEL) {
            bail(0);
        }
        }
    } else { /* iflags.wc_player_selection == VIA_PROMPTS */
        prompt_for_player_selection();
    }
}
void mswin_popup_destroy (HWND hWnd)
Definition at line 2052 of file mswproc.c.
References GetNHApp(), mswin_nhwindow_app::hPopupWnd, mswin_layout_main_window(), mswin_window_mark_dead(), mswin_winid_from_handle(), NULL, and TRUE.
{
    HWND hChild;
    HMENU hMenu;
    int mi_count;
    int i;
    /* enable game windows */
    for(hChild=GetWindow(GetNHApp()->hMainWnd, GW_CHILD);
         hChild;
         hChild = GetWindow(hChild, GW_HWNDNEXT)) {
        if(hChild!= hWnd) {
            EnableWindow(hChild, TRUE);
        }
    }
    /* enable menu */
    hMenu = GetMenu(GetNHApp()->hMainWnd);
    mi_count = GetMenuItemCount(hMenu);
    for(i=0; i<mi_count; i++) {
        EnableMenuItem(hMenu, i, MF_BYPOSITION | MF_ENABLED);
    }
    DrawMenuBar(GetNHApp()->hMainWnd);
    SetWindowPos(hWnd, HWND_BOTTOM, 0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE | SWP_HIDEWINDOW);
    GetNHApp()->hPopupWnd = NULL;
    mswin_window_mark_dead(mswin_winid_from_handle(hWnd));
    DestroyWindow(hWnd);
    mswin_layout_main_window(hWnd);
    SetFocus(GetNHApp()->hMainWnd);
}
void mswin_popup_display (HWND hWnd, int * done_indicator)
Definition at line 2008 of file mswproc.c.
References FALSE, GetNHApp(), mswin_nhwindow_app::hPopupWnd, mswin_layout_main_window(), and NULL.
{
    MSG msg;
    HWND hChild;
    HMENU hMenu;
    int mi_count;
    int i;
    /* activate the menu window */
    GetNHApp()->hPopupWnd = hWnd;
    mswin_layout_main_window(hWnd);
    /* disable game windows */
    for(hChild=GetWindow(GetNHApp()->hMainWnd, GW_CHILD);
         hChild;
         hChild = GetWindow(hChild, GW_HWNDNEXT)) {
        if(hChild!= hWnd) EnableWindow(hChild, FALSE);
    }
    /* disable menu */
    hMenu = GetMenu(GetNHApp()->hMainWnd);
    mi_count = GetMenuItemCount(hMenu);
    for(i=0; i<mi_count; i++) {
        EnableMenuItem(hMenu, i, MF_BYPOSITION | MF_GRAYED);
    }
    DrawMenuBar(GetNHApp()->hMainWnd);
    /* bring menu window on top */
    SetWindowPos(hWnd, HWND_TOP, 0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE | SWP_SHOWWINDOW);
    /* go into message loop */
    while(IsWindow(hWnd) &&
           (done_indicator==NULL || !*done_indicator) &&
           GetMessage(&msg, NULL, 0, 0)!=0) {
        if(!IsDialogMessage(hWnd, &msg)) {
            if (!TranslateAccelerator(msg.hwnd, GetNHApp()->hAccelTable, &msg)) {
                TranslateMessage(&msg);
                DispatchMessage(&msg);
            }
        }
    }
}
void mswin_preference_update (const char * pref)
Definition at line 1800 of file mswproc.c.
References ATR_BLINK, ATR_BOLD, ATR_DIM, ATR_INVERSE, ATR_NONE, ATR_ULINE, mswin_nhwindow_app::bUseSIP, mswin_nhwindow_app::bWrapText, GetNHApp(), iflags, mswin_cliparound(), mswin_get_font(), mswin_hwnd_from_winid(), mswin_layout_main_window(), mswin_select_map_mode(), mswin_set_fullscreen(), NHFONT_DEFAULT_SIZE, NHFONT_SIZE_MAX, NHFONT_SIZE_MIN, NHW_MENU, NHW_MESSAGE, NHW_STATUS, NHW_TEXT, NULL, TRUE, u, you::ux, you::uy, instance_flags::wc2_fullscreen, instance_flags::wc2_softkeyboard, instance_flags::wc2_wraptext, instance_flags::wc_fontsiz_menu, instance_flags::wc_fontsiz_message, instance_flags::wc_fontsiz_status, instance_flags::wc_fontsiz_text, instance_flags::wc_map_mode, WIN_MAP, WIN_MESSAGE, and WIN_STATUS.
{
    HDC hdc;
    if(stricmp(pref, "font_menu")==0 ||
        stricmp(pref, "font_size_menu")==0) {
        if(iflags.wc_fontsiz_menu<NHFONT_SIZE_MIN ||
            iflags.wc_fontsiz_menu>NHFONT_SIZE_MAX)
            iflags.wc_fontsiz_menu = NHFONT_DEFAULT_SIZE;
        hdc = GetDC(GetNHApp()->hMainWnd);
        mswin_get_font(NHW_MENU, ATR_NONE, hdc,
      TRUE);
        mswin_get_font(NHW_MENU, ATR_BOLD, hdc,
      TRUE);
        mswin_get_font(NHW_MENU, ATR_DIM, hdc, TRUE);
        mswin_get_font(NHW_MENU, ATR_ULINE, hdc,
      TRUE);
        mswin_get_font(NHW_MENU, ATR_BLINK, hdc,
      TRUE);
        mswin_get_font(NHW_MENU, ATR_INVERSE, hdc,
      TRUE);
        ReleaseDC(GetNHApp()->hMainWnd, hdc);
        mswin_layout_main_window(NULL);
        return;
    }
    if(stricmp(pref, "font_status")==0 ||
        stricmp(pref, "font_size_status")==0) {
        if(iflags.wc_fontsiz_status<NHFONT_SIZE_MIN ||
            iflags.wc_fontsiz_status>NHFONT_SIZE_MAX)
            iflags.wc_fontsiz_status =
      NHFONT_DEFAULT_SIZE;
        hdc = GetDC(GetNHApp()->hMainWnd);
        mswin_get_font(NHW_STATUS, ATR_NONE, hdc,
      TRUE);
        mswin_get_font(NHW_STATUS, ATR_BOLD, hdc,
      TRUE);
        mswin_get_font(NHW_STATUS, ATR_DIM, hdc,
      TRUE);
        mswin_get_font(NHW_STATUS, ATR_ULINE, hdc,
      TRUE);
        mswin_get_font(NHW_STATUS, ATR_BLINK, hdc,
      TRUE);
        mswin_get_font(NHW_STATUS, ATR_INVERSE, hdc,
      TRUE);
        ReleaseDC(GetNHApp()->hMainWnd, hdc);
        InvalidateRect(mswin_hwnd_from_winid(WIN_STATUS),
      NULL, TRUE);
        mswin_layout_main_window(NULL);
        return;
    }
    if(stricmp(pref, "font_message")==0 ||
        stricmp(pref, "font_size_message")==0) {
        if(iflags.wc_fontsiz_message<NHFONT_SIZE_MIN ||
            iflags.wc_fontsiz_message>NHFONT_SIZE_MAX)
            iflags.wc_fontsiz_message =
      NHFONT_DEFAULT_SIZE;
        hdc = GetDC(GetNHApp()->hMainWnd);
        mswin_get_font(NHW_MESSAGE, ATR_NONE, hdc,
      TRUE);
        mswin_get_font(NHW_MESSAGE, ATR_BOLD, hdc,
      TRUE);
        mswin_get_font(NHW_MESSAGE, ATR_DIM, hdc,
      TRUE);
        mswin_get_font(NHW_MESSAGE, ATR_ULINE, hdc,
      TRUE);
        mswin_get_font(NHW_MESSAGE, ATR_BLINK, hdc,
      TRUE);
        mswin_get_font(NHW_MESSAGE, ATR_INVERSE, hdc,
      TRUE);
        ReleaseDC(GetNHApp()->hMainWnd, hdc);
        InvalidateRect(mswin_hwnd_from_winid(WIN_MESSAGE),
      NULL, TRUE);
        mswin_layout_main_window(NULL);
        return;
    }
    if(stricmp(pref, "font_text")==0 ||
        stricmp(pref, "font_size_text")==0) {
        if(iflags.wc_fontsiz_text<NHFONT_SIZE_MIN ||
            iflags.wc_fontsiz_text>NHFONT_SIZE_MAX)
            iflags.wc_fontsiz_text = NHFONT_DEFAULT_SIZE;
        hdc = GetDC(GetNHApp()->hMainWnd);
        mswin_get_font(NHW_TEXT, ATR_NONE, hdc,
      TRUE);
        mswin_get_font(NHW_TEXT, ATR_BOLD, hdc,
      TRUE);
        mswin_get_font(NHW_TEXT, ATR_DIM, hdc, TRUE);
        mswin_get_font(NHW_TEXT, ATR_ULINE, hdc,
      TRUE);
        mswin_get_font(NHW_TEXT, ATR_BLINK, hdc,
      TRUE);
        mswin_get_font(NHW_TEXT, ATR_INVERSE, hdc,
      TRUE);
        ReleaseDC(GetNHApp()->hMainWnd, hdc);
        mswin_layout_main_window(NULL);
        return;
    }
    if(stricmp(pref, "scroll_amount")==0) {
        mswin_cliparound(u.ux, u.uy);
        return;
    }
    if(stricmp(pref, "scroll_margin")==0) {
        mswin_cliparound(u.ux, u.uy);
        return;
    }
    if(stricmp(pref, "map_mode")==0) {
        mswin_select_map_mode(iflags.wc_map_mode);
        return;
    }
    if(stricmp(pref, "hilite_pet")==0) {
        InvalidateRect(mswin_hwnd_from_winid(WIN_MAP),
      NULL, TRUE);
        return;
    }
    if(stricmp(pref, "align_message")==0 ||
        stricmp(pref, "align_status")==0) {
        mswin_layout_main_window(NULL);
        return;
    }
    if(stricmp(pref, "vary_msgcount")==0) {
        InvalidateRect(mswin_hwnd_from_winid(WIN_MESSAGE),
      NULL, TRUE);
        mswin_layout_main_window(NULL);
        return;
    }
}
void mswin_print_glyph (winid wid, XCHAR_P x, XCHAR_P y, int glyph)
Definition at line 1235 of file mswproc.c.
References GetNHApp(), mswin_nhmsg_print_glyph::glyph, logDebug(), MAXWINDOWS, MSNH_MSG_PRINT_GLYPH, NULL, WM_MSNH_COMMAND, mswin_nhmsg_print_glyph::x, and mswin_nhmsg_print_glyph::y.
{
    logDebug("mswin_print_glyph(%d, %d, %d, %d)\n", wid, x, y, glyph);
    if ((wid >= 0) &&
        (wid < MAXWINDOWS) &&
        (GetNHApp()->windowlist[wid].win != NULL))
    {
        MSNHMsgPrintGlyph data;
        ZeroMemory(&data, sizeof(data));
        data.x = x;
        data.y = y;
        data.glyph = glyph;
        SendMessage(GetNHApp()->windowlist[wid].win,
                 WM_MSNH_COMMAND, (WPARAM)MSNH_MSG_PRINT_GLYPH, (LPARAM)
      &data);
    }
}
void mswin_putstr (winid wid, int attr, const char * text)
Definition at line 945 of file mswproc.c.
References logDebug(), and mswin_putstr_ex().
{
    logDebug("mswin_putstr(%d, %d, %s)\n", wid, attr, text);
    
    mswin_putstr_ex(wid, attr, text, 0);
}
void mswin_putstr_ex (winid wid, int attr, const char * text, int app)
Definition at line 952 of file mswproc.c.
References mswin_nhmsg_putstr::append, mswin_nhmsg_putstr::attr, mswin_nhwindow_data::dead, GetNHApp(), MAXWINDOWS, MENU_TYPE_TEXT, MSNH_MSG_PUTSTR, mswin_get_nh_event(), mswin_init_menu_window(), NHW_MENU, NULL, mswin_nhwindow_app::saved_text, mswin_nhmsg_putstr::text, type, mswin_nhwindow_data::win, mswin_nhwindow_app::windowlist, and WM_MSNH_COMMAND.
{
    if((wid >= 0) &&
        (wid < MAXWINDOWS))
    {
        if(GetNHApp()->windowlist[wid].win==NULL &&
            GetNHApp()->windowlist[wid].type==NHW_MENU) {
            GetNHApp()->windowlist[wid].win =
      mswin_init_menu_window(MENU_TYPE_TEXT);
            GetNHApp()->windowlist[wid].dead = 0;
        }
        if (GetNHApp()->windowlist[wid].win != NULL)
        {
             MSNHMsgPutstr data;
             ZeroMemory(&data, sizeof(data));
             data.attr = attr;
             data.text = text;
             data.append = app;
             SendMessage(
                 GetNHApp()->windowlist[wid].win,
                 WM_MSNH_COMMAND, (WPARAM)MSNH_MSG_PUTSTR, (LPARAM)&data);
        }
        /* yield a bit so it gets done immediately */
        mswin_get_nh_event();
    }
    else
    {
        // build text to display later in message box
        GetNHApp()->saved_text = realloc(GetNHApp()->saved_text, strlen(
      text) +
            strlen(GetNHApp()->saved_text) + 1);
        strcat(GetNHApp()->saved_text, text);
    }
}
void mswin_raw_print (const char * str)
Definition at line 1263 of file mswproc.c.
References GetNHApp(), logDebug(), MessageBox(), NH_A2W, and NHMessageBox().
{
    TCHAR wbuf[255];
    logDebug("mswin_raw_print(%s)\n", str);
    if(str && *str)
        NHMessageBox(GetNHApp()->hMainWnd, NH_A2W(str, wbuf, sizeof(wbuf)),
            MB_ICONINFORMATION | MB_OK);
}
void mswin_raw_print_bold (const char * str)
Definition at line 1277 of file mswproc.c.
References GetNHApp(), logDebug(), MessageBox(), NH_A2W, and NHMessageBox().
{
    TCHAR wbuf[255];
    logDebug("mswin_raw_print_bold(%s)\n", str);
    if(str && *str)
        NHMessageBox(GetNHApp()->hMainWnd, NH_A2W(str, wbuf, sizeof(wbuf)),
            MB_ICONINFORMATION | MB_OK);
}
void mswin_read_reg (void)
Definition at line 2126 of file mswproc.c.
References CATEGORYKEY, COMPANYKEY, GetNHApp(), INTFKEY, MAINBOTTOMKEY, MAINLEFTKEY, MAINMAXXKEY, MAINMAXYKEY, MAINMINXKEY, MAINMINYKEY, MAINRIGHTKEY, MAINSHOWSTATEKEY, MAINTOPKEY, NULL, PRODUCTKEY, mswin_nhwindow_app::regNetHackMode, mswin_nhwindow_app::saveRegistrySettings, and SETTINGSKEY.
{
    HKEY key;
    DWORD size;
    char keystring[MAX_PATH];
    sprintf(keystring, "%s\\%s\\%s\\%s",
        CATEGORYKEY, COMPANYKEY, PRODUCTKEY,
      SETTINGSKEY);
    /* Set the defaults here. The very first time the app is started, nothing is
       read from the registry, so these defaults apply. */
    GetNHApp()->saveRegistrySettings = 1; /* Normally, we always save */
    GetNHApp()->regNetHackMode = 0;
    if (RegOpenKeyEx(HKEY_CURRENT_USER, keystring, 0, KEY_READ, &key)
            != ERROR_SUCCESS)
        return;
    size = sizeof(DWORD);
    /* Read the keys here. */
    RegQueryValueEx(key, INTFKEY, 0, NULL, (unsigned char *)(&(
      GetNHApp()->regNetHackMode)), &size);
    /* Main window placement */
    RegQueryValueEx(key, MAINSHOWSTATEKEY, 0, NULL, (unsigned char *)(&(
      GetNHApp()->regMainShowState)), &size);
    RegQueryValueEx(key, MAINMINXKEY, 0, NULL, (unsigned char *)(&(
      GetNHApp()->regMainMinX)), &size);
    RegQueryValueEx(key, MAINMINYKEY, 0, NULL, (unsigned char *)(&(
      GetNHApp()->regMainMinY)), &size);
    RegQueryValueEx(key, MAINMAXXKEY, 0, NULL, (unsigned char *)(&(
      GetNHApp()->regMainMaxX)), &size);
    RegQueryValueEx(key, MAINMAXYKEY, 0, NULL, (unsigned char *)(&(
      GetNHApp()->regMainMaxY)), &size);
    RegQueryValueEx(key, MAINLEFTKEY, 0, NULL, (unsigned char *)(&(
      GetNHApp()->regMainLeft)), &size);
    RegQueryValueEx(key, MAINRIGHTKEY, 0, NULL, (unsigned char *)(&(
      GetNHApp()->regMainRight)), &size);
    RegQueryValueEx(key, MAINTOPKEY, 0, NULL, (unsigned char *)(&(
      GetNHApp()->regMainTop)), &size);
    RegQueryValueEx(key, MAINBOTTOMKEY, 0, NULL, (unsigned char *)(&(
      GetNHApp()->regMainBottom)), &size);
    
    RegCloseKey(key);
}
void mswin_resume_nhwindows (void)
Definition at line 704 of file mswproc.c.
References logDebug().
{
    logDebug("mswin_resume_nhwindows()\n");
    return;
}
int mswin_select_menu (winid wid, int how, MENU_ITEM_P ** selected)
Definition at line 1158 of file mswproc.c.
References GetNHApp(), logDebug(), MAXWINDOWS, mswin_menu_window_select_menu(), and NULL.
{
    int nReturned = -1;
    logDebug("mswin_select_menu(%d, %d)\n", wid, how);
    if ((wid >= 0) &&
        (wid < MAXWINDOWS) &&
        (GetNHApp()->windowlist[wid].win != NULL))
    {
        nReturned = mswin_menu_window_select_menu(
      GetNHApp()->windowlist[wid].win, how, selected);
    }
    return nReturned;
}
void mswin_start_menu (winid wid)
Definition at line 1027 of file mswproc.c.
References mswin_nhwindow_data::dead, GetNHApp(), logDebug(), MAXWINDOWS, MENU_TYPE_MENU, MSNH_MSG_STARTMENU, mswin_init_menu_window(), NHW_MENU, NULL, type, mswin_nhwindow_data::win, mswin_nhwindow_app::windowlist, and WM_MSNH_COMMAND.
{
    logDebug("mswin_start_menu(%d)\n", wid);
    if((wid >= 0) &&
        (wid < MAXWINDOWS)) {
        if(GetNHApp()->windowlist[wid].win==NULL &&
            GetNHApp()->windowlist[wid].type==NHW_MENU) {
            GetNHApp()->windowlist[wid].win =
      mswin_init_menu_window(MENU_TYPE_MENU);
            GetNHApp()->windowlist[wid].dead = 0;
        }
        if(GetNHApp()->windowlist[wid].win != NULL) {
            SendMessage(
                 GetNHApp()->windowlist[wid].win,
                 WM_MSNH_COMMAND, (WPARAM)MSNH_MSG_STARTMENU, (LPARAM)
      NULL
            );
        }
    }
}
void mswin_start_screen (void)
Definition at line 1726 of file mswproc.c.
References logDebug().
{
    /* Do Nothing */
    logDebug("mswin_start_screen()\n");
}
void mswin_suspend_nhwindows (const char * str)
Definition at line 696 of file mswproc.c.
References logDebug().
{
    logDebug("mswin_suspend_nhwindows(%s)\n", str);
    return;
}
void mswin_update_inventory (void)
Definition at line 1178 of file mswproc.c.
References logDebug().
{
    logDebug("mswin_update_inventory()\n");
}
void mswin_wait_synch (void)
Definition at line 1199 of file mswproc.c.
References logDebug().
{
    logDebug("mswin_wait_synch()\n");
}
void mswin_window_mark_dead (winid wid)
Definition at line 868 of file mswproc.c.
References mswin_nhwindow_data::dead, GetNHApp(), MAXWINDOWS, NULL, mswin_nhwindow_data::win, and mswin_nhwindow_app::windowlist.
{
    if(wid>=0 && wid<MAXWINDOWS) {
        GetNHApp()->windowlist[wid].win = NULL;
        GetNHApp()->windowlist[wid].dead = 1;
    }
}
winid mswin_winid_from_handle (HWND hWnd)
Definition at line 848 of file mswproc.c.
References GetNHApp(), and MAXWINDOWS.
{
    winid i = 0;
    for (i=1; i<MAXWINDOWS; i++)
      if (GetNHApp()->windowlist[i].win == hWnd)
          return i;
    return -1;
}
winid mswin_winid_from_type (int type)
Definition at line 858 of file mswproc.c.
References GetNHApp(), and MAXWINDOWS.
{
    winid i = 0;
    for (i=1; i<MAXWINDOWS; i++)
      if (GetNHApp()->windowlist[i].type == type)
          return i;
    return -1;
}
void mswin_write_reg (void)
Definition at line 2162 of file mswproc.c.
References CATEGORYKEY, COMPANYKEY, GetNHApp(), INTFKEY, MAINBOTTOMKEY, MAINLEFTKEY, MAINMAXXKEY, MAINMAXYKEY, MAINMINXKEY, MAINMINYKEY, MAINRIGHTKEY, MAINSHOWSTATEKEY, MAINTOPKEY, NULL, PRODUCTKEY, and SETTINGSKEY.
{
    HKEY key;
    DWORD disposition;
    if (GetNHApp()->saveRegistrySettings)
    {
        char keystring[MAX_PATH];
        sprintf(keystring, "%s\\%s\\%s\\%s",
            CATEGORYKEY, COMPANYKEY, PRODUCTKEY,
      SETTINGSKEY);
        if (RegOpenKeyEx(HKEY_CURRENT_USER, keystring, 0, KEY_WRITE, &key) != ERROR_SUCCESS)
        {
            RegCreateKeyEx(HKEY_CURRENT_USER, keystring, 0, "",
                REG_OPTION_NON_VOLATILE, KEY_ALL_ACCESS, NULL, &key, &disposition);
        }
        /* Write the keys here */
        RegSetValueEx(key, INTFKEY, 0, REG_DWORD, (unsigned char *)(&(
      GetNHApp()->regNetHackMode)), sizeof(DWORD));
        /* Main window placement */
        RegSetValueEx(key, MAINSHOWSTATEKEY, 0, REG_DWORD, (unsigned char *)(&(
      GetNHApp()->regMainShowState)), sizeof(DWORD));
        RegSetValueEx(key, MAINMINXKEY, 0, REG_DWORD, (unsigned char *)(&(
      GetNHApp()->regMainMinX)), sizeof(DWORD));
        RegSetValueEx(key, MAINMINYKEY, 0, REG_DWORD, (unsigned char *)(&(
      GetNHApp()->regMainMinY)), sizeof(DWORD));
        RegSetValueEx(key, MAINMAXXKEY, 0, REG_DWORD, (unsigned char *)(&(
      GetNHApp()->regMainMaxX)), sizeof(DWORD));
        RegSetValueEx(key, MAINMAXYKEY, 0, REG_DWORD, (unsigned char *)(&(
      GetNHApp()->regMainMaxY)), sizeof(DWORD));
        RegSetValueEx(key, MAINLEFTKEY, 0, REG_DWORD, (unsigned char *)(&(
      GetNHApp()->regMainLeft)), sizeof(DWORD));
        RegSetValueEx(key, MAINRIGHTKEY, 0, REG_DWORD, (unsigned char *)(&(
      GetNHApp()->regMainRight)), sizeof(DWORD));
        RegSetValueEx(key, MAINTOPKEY, 0, REG_DWORD, (unsigned char *)(&(
      GetNHApp()->regMainTop)), sizeof(DWORD));
        RegSetValueEx(key, MAINBOTTOMKEY, 0, REG_DWORD, (unsigned char *)(&(
      GetNHApp()->regMainBottom)), sizeof(DWORD));
        RegCloseKey(key);
    }
}
char mswin_yn_function (const char * question, const char * choices, CHAR_P def)
Definition at line 1383 of file mswproc.c.
References ATR_BOLD, buf, BUFSZ, eos(), free(), GetNHApp(), index(), logDebug(), lowc(), MSNH_MSG_CARET, mswin_clear_nhwindow(), mswin_hwnd_from_winid(), mswin_nhbell(), mswin_nhgetch(), mswin_putstr(), mswin_putstr_ex(), NH_W2A, NHMessageBox(), NULL, QBUFSZ, quitchars, mswin_nhwindow_app::saved_text, Strcat, Strcpy, strdup, WIN_ERR, WIN_MESSAGE, WM_MSNH_COMMAND, yn_esc_map, yn_number, and ynchars.
{
    char ch;
    char yn_esc_map='\033';
    char message[BUFSZ];
    char res_ch[2];
    int createcaret;
    boolean digit_ok, allow_num;
    logDebug("mswin_yn_function(%s, %s, %d)\n", question, choices, def);
    if (WIN_MESSAGE == WIN_ERR && choices == ynchars) {
        char *text = realloc(strdup(GetNHApp()->saved_text), strlen(question)
            + strlen(GetNHApp()->saved_text) + 1);
        DWORD box_result;
        strcat(text, question);
        box_result = NHMessageBox(NULL,
             NH_W2A(text, message, sizeof(message)),
             MB_YESNOCANCEL | MB_ICONQUESTION |
             ((def == 'y') ? MB_DEFBUTTON1 :
              (def == 'n') ? MB_DEFBUTTON2 : MB_DEFBUTTON3));
        free(text);
        GetNHApp()->saved_text = strdup("");
        return box_result == IDYES ? 'y' : box_result == IDNO ? 'n' : '\033';
    }
    if (choices) {
        char *cb, choicebuf[QBUFSZ];
        allow_num = (index(choices, '#') != 0);
        Strcpy(choicebuf, choices);
        if ((cb = index(choicebuf, '\033')) != 0) {
            /* anything beyond <esc> is hidden */
            *cb = '\0';
        }
        sprintf(message, "%s [%s] ", question, choicebuf);
        if (def) sprintf(eos(message), "(%c) ", def);
        /* escape maps to 'q' or 'n' or default, in that order */
        yn_esc_map = (index(choices, 'q') ? 'q' :
            (index(choices, 'n') ? 'n' : def));
    } else {
        Strcpy(message, question);
        Strcat(message, " ");
    }
    createcaret = 1;
    SendMessage(mswin_hwnd_from_winid(WIN_MESSAGE),
        WM_MSNH_COMMAND, (WPARAM)MSNH_MSG_CARET, (LPARAM)&createcaret);
    mswin_clear_nhwindow(WIN_MESSAGE);
    mswin_putstr(WIN_MESSAGE, ATR_BOLD, message);
    /* Only here if main window is not present */
    ch = 0;
    do {
        ShowCaret(mswin_hwnd_from_winid(WIN_MESSAGE));
        ch=mswin_nhgetch();
        HideCaret(mswin_hwnd_from_winid(WIN_MESSAGE));
        if (choices) ch = lowc(ch);
        else break; /* If choices is NULL, all possible inputs are accepted and returned. */
        digit_ok = allow_num && digit(ch);
        if (ch=='\033') {
            if (index(choices, 'q'))
                ch = 'q';
            else if (index(choices, 'n'))
                ch = 'n';
            else
                ch = def;
            break;
        } else if (index(quitchars, ch)) {
            ch = def;
            break;
        } else if (!index(choices, ch) && !digit_ok) {
            mswin_nhbell();
            ch = (char)0;
            /* and try again... */
        } else if (ch == '#' || digit_ok) {
            char z, digit_string[2];
            int n_len = 0;
            long value = 0;
            mswin_putstr_ex(WIN_MESSAGE, ATR_BOLD, ("#"), 1); n_len++;
            digit_string[1] = '\0';
            if (ch != '#') {
                digit_string[0] = ch;
                mswin_putstr_ex(WIN_MESSAGE, ATR_BOLD, digit_string, 1);
      n_len++;
                value = ch - '0';
                ch = '#';
            }
            do { /* loop until we get a non-digit */
                z = lowc(readchar());
                if (digit(z)) {
                    value = (10 * value) + (z - '0');
                    if (value < 0) break; /* overflow: try again */
                    digit_string[0] = z;
                    mswin_putstr_ex(WIN_MESSAGE,
      ATR_BOLD, digit_string, 1);
                    n_len++;
                } else if (z == 'y' || index(quitchars, z)) {
                    if (z == '\033') value = -1; /* abort */
                    z = '\n'; /* break */
                } else if (z == '\b') {
                    if (n_len <= 1) { value = -1; break; }
                    else { value /= 10; mswin_putstr_ex(
      WIN_MESSAGE, ATR_BOLD, digit_string, -1); n_len--; }
                } else {
                    value = -1; /* abort */
                    mswin_nhbell();
                    break;
                }
            } while (z != '\n');
            if (value > 0) yn_number = value;
            else if (value == 0) ch = 'n'; /* 0 => "no" */
            else { /* remove number from top line, then try again */
                mswin_putstr_ex(WIN_MESSAGE, ATR_BOLD, digit_string, -
      n_len); n_len = 0;
                ch = (char)0;
            }
        }
    } while(!ch);
    createcaret = 0;
    SendMessage(mswin_hwnd_from_winid(WIN_MESSAGE),
        WM_MSNH_COMMAND, (WPARAM)MSNH_MSG_CARET, (LPARAM)&createcaret);
    /* display selection in the message window */
    if(isprint(ch) && ch!='#') {
        res_ch[0] = ch;
        res_ch[1] = '\x0';
        mswin_putstr_ex(WIN_MESSAGE, ATR_BOLD, res_ch, 1);
    }
    return ch;
}
int NHMessageBox (HWND hWnd, LPCTSTR text, UINT type)
Definition at line 2346 of file mswproc.c.
References GetNHApp(), IDS_APP_TITLE_SHORT, MAX_LOADSTRING, and MessageBox().
Referenced by MainWndProc(), mswin_display_file(), mswin_raw_print(), mswin_raw_print_bold(), mswin_yn_function(), onWMCommand(), PlayerSelectorDlgProc(), plselFinalSelection(), and prompt_for_player_selection().
{
    TCHAR title[MAX_LOADSTRING];
    
    LoadString(GetNHApp()->hApp, IDS_APP_TITLE_SHORT, title,
      MAX_LOADSTRING);
    return MessageBox(hWnd, text, title, type);
}
void prompt_for_player_selection (void) [static]
Definition at line 312 of file mswproc.c.
References any::a_int, any::a_void, add_menu, aligns, ATR_NONE, bail(), build_plselection_prompt(), CO, create_nhwindow, destroy_nhwindow, end_menu, RoleName::f, flags, free(), genders, index(), flag::initalign, flag::initgend, flag::initrace, flag::initrole, mi::item, logDebug(), lowc(), RoleName::m, MENU_UNSELECTED, Role::name, name, NHMessageBox(), NHW_MENU, NO_GLYPH, Race::noun, NULL, ok_align(), ok_gend(), ok_race(), ok_role(), pick_align(), pick_gend(), PICK_ONE, pick_race(), PICK_RANDOM, pick_role(), QBUFSZ, quitchars, races, randalign(), randgend(), flag::randomall, randrace(), randrole(), rigid_role_checks(), ROLE_ALIGNS, ROLE_GENDERS, ROLE_NONE, ROLE_RANDOM, roles, root_plselection_prompt(), select_menu, Sprintf, start_menu, Strcat, Strcpy, validalign(), validgend(), validrace(), and ynqchars.
Referenced by mswin_player_selection().
{
    int i, k, n;
    char pick4u = 'n', thisch, lastch = 0;
    char pbuf[QBUFSZ], plbuf[QBUFSZ];
    winid win;
    anything any;
    menu_item *selected = 0;
        DWORD box_result;
    logDebug("prompt_for_player_selection()\n");
    /* prevent an unnecessary prompt */
    rigid_role_checks();
    /* Should we randomly pick for the player? */
    if (!flags.randomall &&
        (flags.initrole == ROLE_NONE || flags.
      initrace == ROLE_NONE ||
         flags.initgend == ROLE_NONE || flags.
      initalign == ROLE_NONE)) {
        /* int echoline; */
        char *prompt = build_plselection_prompt(pbuf,
      QBUFSZ, flags.initrole,
                flags.initrace, flags.initgend, flags.
      initalign);
        /* tty_putstr(BASE_WINDOW, 0, ""); */
        /* echoline = wins[BASE_WINDOW]->cury; */
            box_result = NHMessageBox(NULL, prompt,
                    MB_ICONQUESTION | MB_YESNOCANCEL | MB_DEFBUTTON1);
            pick4u = (box_result == IDYES) ? 'y' : (box_result == IDNO) ? 'n' : '\033';
        /* tty_putstr(BASE_WINDOW, 0, prompt); */
        do {
        /* pick4u = lowc(readchar()); */
        if (index(quitchars, pick4u)) pick4u = 'y';
        } while(!index(ynqchars, pick4u));
        if ((int)strlen(prompt) + 1 < CO) {
        /* Echo choice and move back down line */
        /* tty_putsym(BASE_WINDOW, (int)strlen(prompt)+1, echoline, pick4u); */
        /* tty_putstr(BASE_WINDOW, 0, ""); */
        } else
        /* Otherwise it's hard to tell where to echo, and things are
         * wrapping a bit messily anyway, so (try to) make sure the next
         * question shows up well and doesn't get wrapped at the
         * bottom of the window.
         */
        /* tty_clear_nhwindow(BASE_WINDOW) */ ;
        
        if (pick4u != 'y' && pick4u != 'n') {
give_up: /* Quit */
        if (selected) free((genericptr_t) selected);
        bail((char *)0);
        /*NOTREACHED*/
        return;
        }
    }
    (void) root_plselection_prompt(plbuf, QBUFSZ - 1,
            flags.initrole, flags.initrace, flags.
      initgend, flags.initalign);
    /* Select a role, if necessary */
    /* we'll try to be compatible with pre-selected race/gender/alignment,
     * but may not succeed */
    if (flags.initrole < 0) {
        char rolenamebuf[QBUFSZ];
        /* Process the choice */
        if (pick4u == 'y' || flags.initrole == ROLE_RANDOM ||
      flags.randomall) {
        /* Pick a random role */
        flags.initrole = pick_role(flags.initrace,
      flags.initgend,
                        flags.initalign, PICK_RANDOM);
        if (flags.initrole < 0) {
            /* tty_putstr(BASE_WINDOW, 0, "Incompatible role!"); */
            flags.initrole = randrole();
        }
        } else {
            /* tty_clear_nhwindow(BASE_WINDOW); */
        /* tty_putstr(BASE_WINDOW, 0, "Choosing Character's Role"); */
        /* Prompt for a role */
        win = create_nhwindow(NHW_MENU);
        start_menu(win);
        any.a_void = 0; /* zero out all bits */
        for (i = 0; roles[i].name.m; i++) {
            if (ok_role(i, flags.initrace, flags.
      initgend,
                            flags.initalign)) {
            any.a_int = i+1; /* must be non-zero */
            thisch = lowc(roles[i].name.m[0]);
            if (thisch == lastch) thisch = highc(thisch);
            if (flags.initgend != ROLE_NONE && flags.
      initgend != ROLE_RANDOM) {
                if (flags.initgend == 1 && roles[i].name.
      f)
                    Strcpy(rolenamebuf, roles[i].name.f);
                else
                    Strcpy(rolenamebuf, roles[i].name.m);
            } else {
                if (roles[i].name.f) {
                    Strcpy(rolenamebuf, roles[i].name.m);
                    Strcat(rolenamebuf, "/");
                    Strcat(rolenamebuf, roles[i].name.f);
                } else
                    Strcpy(rolenamebuf, roles[i].name.m);
            }
            add_menu(win, NO_GLYPH, &any, thisch,
                0, ATR_NONE, an(rolenamebuf), MENU_UNSELECTED);
            lastch = thisch;
            }
        }
        any.a_int = pick_role(flags.initrace, flags.
      initgend,
                    flags.initalign, PICK_RANDOM)+1;
        if (any.a_int == 0) /* must be non-zero */
            any.a_int = randrole()+1;
        add_menu(win, NO_GLYPH, &any , '*', 0, ATR_NONE,
                "Random", MENU_UNSELECTED);
        any.a_int = i+1; /* must be non-zero */
        add_menu(win, NO_GLYPH, &any , 'q', 0, ATR_NONE,
                "Quit", MENU_UNSELECTED);
        Sprintf(pbuf, "Pick a role for your %s", plbuf);
        end_menu(win, pbuf);
        n = select_menu(win, PICK_ONE, &selected);
        destroy_nhwindow(win);
        /* Process the choice */
        if (n != 1 || selected[0].item.a_int == any.a_int)
            goto give_up; /* Selected quit */
        flags.initrole = selected[0].item.a_int - 1;
        free((genericptr_t) selected), selected = 0;
        }
        (void) root_plselection_prompt(plbuf, QBUFSZ - 1,
            flags.initrole, flags.initrace, flags.
      initgend, flags.initalign);
    }
    
    /* Select a race, if necessary */
    /* force compatibility with role, try for compatibility with
     * pre-selected gender/alignment */
    if (flags.initrace < 0 || !validrace(flags.
      initrole, flags.initrace)) {
        /* pre-selected race not valid */
        if (pick4u == 'y' || flags.initrace == ROLE_RANDOM ||
      flags.randomall) {
        flags.initrace = pick_race(flags.initrole,
      flags.initgend,
                            flags.initalign, PICK_RANDOM);
        if (flags.initrace < 0) {
            /* tty_putstr(BASE_WINDOW, 0, "Incompatible race!"); */
            flags.initrace = randrace(flags.initrole);
        }
        } else { /* pick4u == 'n' */
        /* Count the number of valid races */
        n = 0; /* number valid */
        k = 0; /* valid race */
        for (i = 0; races[i].noun; i++) {
            if (ok_race(flags.initrole, i, flags.
      initgend,
                            flags.initalign)) {
            n++;
            k = i;
            }
        }
        if (n == 0) {
            for (i = 0; races[i].noun; i++) {
            if (validrace(flags.initrole, i)) {
                n++;
                k = i;
            }
            }
        }
        /* Permit the user to pick, if there is more than one */
        if (n > 1) {
            /* tty_clear_nhwindow(BASE_WINDOW); */
            /* tty_putstr(BASE_WINDOW, 0, "Choosing Race"); */
            win = create_nhwindow(NHW_MENU);
            start_menu(win);
            any.a_void = 0; /* zero out all bits */
            for (i = 0; races[i].noun; i++)
            if (ok_race(flags.initrole, i, flags.
      initgend,
                            flags.initalign)) {
                any.a_int = i+1; /* must be non-zero */
                add_menu(win, NO_GLYPH, &any, races[i].noun[0],
                0, ATR_NONE, races[i].noun, MENU_UNSELECTED);
            }
            any.a_int = pick_race(flags.initrole,
      flags.initgend,
                    flags.initalign, PICK_RANDOM)+1;
            if (any.a_int == 0) /* must be non-zero */
            any.a_int = randrace(flags.initrole)+1;
            add_menu(win, NO_GLYPH, &any , '*', 0, ATR_NONE,
                    "Random", MENU_UNSELECTED);
            any.a_int = i+1; /* must be non-zero */
            add_menu(win, NO_GLYPH, &any , 'q', 0, ATR_NONE,
                    "Quit", MENU_UNSELECTED);
            Sprintf(pbuf, "Pick the race of your %s", plbuf);
            end_menu(win, pbuf);
            n = select_menu(win, PICK_ONE, &selected);
            destroy_nhwindow(win);
            if (n != 1 || selected[0].item.a_int == any.a_int)
            goto give_up; /* Selected quit */
            k = selected[0].item.a_int - 1;
            free((genericptr_t) selected), selected = 0;
        }
        flags.initrace = k;
        }
        (void) root_plselection_prompt(plbuf, QBUFSZ - 1,
            flags.initrole, flags.initrace, flags.
      initgend, flags.initalign);
    }
    /* Select a gender, if necessary */
    /* force compatibility with role/race, try for compatibility with
     * pre-selected alignment */
    if (flags.initgend < 0 || !validgend(flags.
      initrole, flags.initrace,
                        flags.initgend)) {
        /* pre-selected gender not valid */
        if (pick4u == 'y' || flags.initgend == ROLE_RANDOM ||
      flags.randomall) {
        flags.initgend = pick_gend(flags.initrole,
      flags.initrace,
                        flags.initalign, PICK_RANDOM);
        if (flags.initgend < 0) {
            /* tty_putstr(BASE_WINDOW, 0, "Incompatible gender!"); */
            flags.initgend = randgend(flags.initrole,
      flags.initrace);
        }
        } else { /* pick4u == 'n' */
        /* Count the number of valid genders */
        n = 0; /* number valid */
        k = 0; /* valid gender */
        for (i = 0; i < ROLE_GENDERS; i++) {
            if (ok_gend(flags.initrole, flags.initrace, i,
                            flags.initalign)) {
            n++;
            k = i;
            }
        }
        if (n == 0) {
            for (i = 0; i < ROLE_GENDERS; i++) {
            if (validgend(flags.initrole, flags.
      initrace, i)) {
                n++;
                k = i;
            }
            }
        }
        /* Permit the user to pick, if there is more than one */
        if (n > 1) {
            /* tty_clear_nhwindow(BASE_WINDOW); */
            /* tty_putstr(BASE_WINDOW, 0, "Choosing Gender"); */
            win = create_nhwindow(NHW_MENU);
            start_menu(win);
            any.a_void = 0; /* zero out all bits */
            for (i = 0; i < ROLE_GENDERS; i++)
            if (ok_gend(flags.initrole, flags.initrace, i,
                                flags.initalign)) {
                any.a_int = i+1;
                add_menu(win, NO_GLYPH, &any, genders[i].adj[0],
                0, ATR_NONE, genders[i].adj, MENU_UNSELECTED);
            }
            any.a_int = pick_gend(flags.initrole,
      flags.initrace,
                        flags.initalign, PICK_RANDOM)+1;
            if (any.a_int == 0) /* must be non-zero */
            any.a_int = randgend(flags.initrole, flags.
      initrace)+1;
            add_menu(win, NO_GLYPH, &any , '*', 0, ATR_NONE,
                    "Random", MENU_UNSELECTED);
            any.a_int = i+1; /* must be non-zero */
            add_menu(win, NO_GLYPH, &any , 'q', 0, ATR_NONE,
                    "Quit", MENU_UNSELECTED);
            Sprintf(pbuf, "Pick the gender of your %s", plbuf);
            end_menu(win, pbuf);
            n = select_menu(win, PICK_ONE, &selected);
            destroy_nhwindow(win);
            if (n != 1 || selected[0].item.a_int == any.a_int)
            goto give_up; /* Selected quit */
            k = selected[0].item.a_int - 1;
            free((genericptr_t) selected), selected = 0;
        }
        flags.initgend = k;
        }
        (void) root_plselection_prompt(plbuf, QBUFSZ - 1,
            flags.initrole, flags.initrace, flags.
      initgend, flags.initalign);
    }
    /* Select an alignment, if necessary */
    /* force compatibility with role/race/gender */
    if (flags.initalign < 0 || !validalign(flags.
      initrole, flags.initrace,
                            flags.initalign)) {
        /* pre-selected alignment not valid */
        if (pick4u == 'y' || flags.initalign == ROLE_RANDOM ||
      flags.randomall) {
        flags.initalign = pick_align(flags.initrole,
      flags.initrace,
                            flags.initgend, PICK_RANDOM);
        if (flags.initalign < 0) {
            /* tty_putstr(BASE_WINDOW, 0, "Incompatible alignment!"); */
            flags.initalign = randalign(flags.
      initrole, flags.initrace);
        }
        } else { /* pick4u == 'n' */
        /* Count the number of valid alignments */
        n = 0; /* number valid */
        k = 0; /* valid alignment */
        for (i = 0; i < ROLE_ALIGNS; i++) {
            if (ok_align(flags.initrole, flags.
      initrace, flags.initgend,
                            i)) {
            n++;
            k = i;
            }
        }
        if (n == 0) {
            for (i = 0; i < ROLE_ALIGNS; i++) {
            if (validalign(flags.initrole, flags.
      initrace, i)) {
                n++;
                k = i;
            }
            }
        }
        /* Permit the user to pick, if there is more than one */
        if (n > 1) {
            /* tty_clear_nhwindow(BASE_WINDOW); */
            /* tty_putstr(BASE_WINDOW, 0, "Choosing Alignment"); */
            win = create_nhwindow(NHW_MENU);
            start_menu(win);
            any.a_void = 0; /* zero out all bits */
            for (i = 0; i < ROLE_ALIGNS; i++)
            if (ok_align(flags.initrole, flags.
      initrace,
                            flags.initgend, i)) {
                any.a_int = i+1;
                add_menu(win, NO_GLYPH, &any, aligns[i].adj[0],
                 0, ATR_NONE, aligns[i].adj, MENU_UNSELECTED);
            }
            any.a_int = pick_align(flags.initrole,
      flags.initrace,
                        flags.initgend, PICK_RANDOM)+1;
            if (any.a_int == 0) /* must be non-zero */
            any.a_int = randalign(flags.initrole,
      flags.initrace)+1;
            add_menu(win, NO_GLYPH, &any , '*', 0, ATR_NONE,
                    "Random", MENU_UNSELECTED);
            any.a_int = i+1; /* must be non-zero */
            add_menu(win, NO_GLYPH, &any , 'q', 0, ATR_NONE,
                    "Quit", MENU_UNSELECTED);
            Sprintf(pbuf, "Pick the alignment of your %s", plbuf);
            end_menu(win, pbuf);
            n = select_menu(win, PICK_ONE, &selected);
            destroy_nhwindow(win);
            if (n != 1 || selected[0].item.a_int == any.a_int)
            goto give_up; /* Selected quit */
            k = selected[0].item.a_int - 1;
            free((genericptr_t) selected), selected = 0;
        }
        flags.initalign = k;
        }
    }
    /* Success! */
    /* tty_display_nhwindow(BASE_WINDOW, FALSE); */
}
Variable Documentation
HBRUSH brush_table[TOTAL_BRUSHES]
Definition at line 44 of file mswproc.c.
Referenced by mswin_color_from_string(), and mswin_exit_nhwindows().
color_table_value color_table[] [static]
Definition at line 2241 of file mswproc.c.
Referenced by mswin_color_from_string().
color_table_brush_value color_table_brush[] [static]
Initial value:
= {
    { "activeborder", COLOR_ACTIVEBORDER },
    { "activecaption", COLOR_ACTIVECAPTION },
    { "appworkspace", COLOR_APPWORKSPACE },
    { "background", COLOR_BACKGROUND },
    { "btnface", COLOR_BTNFACE },
    { "btnshadow", COLOR_BTNSHADOW },
    { "btntext", COLOR_BTNTEXT },
    { "captiontext", COLOR_CAPTIONTEXT },
    { "graytext", COLOR_GRAYTEXT },
    { "greytext", COLOR_GRAYTEXT },
    { "highlight", COLOR_HIGHLIGHT },
    { "highlighttext", COLOR_HIGHLIGHTTEXT },
    { "inactiveborder", COLOR_INACTIVEBORDER },
    { "inactivecaption", COLOR_INACTIVECAPTION },
    { "menu", COLOR_MENU },
    { "menutext", COLOR_MENUTEXT },
    { "scrollbar", COLOR_SCROLLBAR },
    { "window", COLOR_WINDOW },
    { "windowframe", COLOR_WINDOWFRAME },
    { "windowtext", COLOR_WINDOWTEXT },
    { "", -1 },
}
Definition at line 2279 of file mswproc.c.
Referenced by mswin_color_from_string().
const char* killed_by_prefix[]
Definition at line 79 of file topten.c.
Referenced by mswin_outrip().
int max_brush = 0
Definition at line 45 of file mswproc.c.
Referenced by mswin_color_from_string(), and mswin_exit_nhwindows().
HBRUSH menu_bg_brush = NULL
Definition at line 47 of file mswproc.c.
Referenced by mswin_init_nhwindows(), onDrawItem(), and SetMenuListType().
COLORREF menu_bg_color = RGB(0, 0, 0)
Definition at line 56 of file mswproc.c.
Referenced by mswin_init_nhwindows(), onDrawItem(), and SetMenuListType().
HBRUSH menu_fg_brush = NULL
Definition at line 48 of file mswproc.c.
Referenced by mswin_init_nhwindows(), onDrawItem(), and SetMenuListType().
COLORREF menu_fg_color = RGB(0xFF, 0xFF, 0xFF)
Definition at line 57 of file mswproc.c.
Referenced by mswin_init_nhwindows(), onDrawItem(), and SetMenuListType().
HBRUSH message_bg_brush = NULL
Definition at line 53 of file mswproc.c.
Referenced by mswin_init_nhwindows(), onPaint(), register_message_window_class(), and setMsgTextColor().
COLORREF message_bg_color = RGB(0, 0, 0)
Definition at line 62 of file mswproc.c.
Referenced by mswin_init_nhwindows(), onPaint(), and setMsgTextColor().
HBRUSH message_fg_brush = NULL
Definition at line 54 of file mswproc.c.
Referenced by mswin_init_nhwindows(), and setMsgTextColor().
COLORREF message_fg_color = RGB(0xFF, 0xFF, 0xFF)
Definition at line 63 of file mswproc.c.
Referenced by mswin_init_nhwindows(), and setMsgTextColor().
struct window_procs mswin_procs
Definition at line 66 of file mswproc.c.
HBRUSH status_bg_brush = NULL
Definition at line 51 of file mswproc.c.
Referenced by mswin_init_nhwindows(), register_status_window_class(), and StatusWndProc().
COLORREF status_bg_color = RGB(0, 0, 0)
Definition at line 60 of file mswproc.c.
Referenced by mswin_init_nhwindows(), and StatusWndProc().
HBRUSH status_fg_brush = NULL
Definition at line 52 of file mswproc.c.
Referenced by mswin_init_nhwindows(), and StatusWndProc().
COLORREF status_fg_color = RGB(0xFF, 0xFF, 0xFF)
Definition at line 61 of file mswproc.c.
Referenced by mswin_init_nhwindows(), and StatusWndProc().
HBRUSH text_bg_brush = NULL
Definition at line 49 of file mswproc.c.
Referenced by MenuWndProc(), mswin_init_nhwindows(), and NHTextWndProc().
COLORREF text_bg_color = RGB(0, 0, 0)
Definition at line 58 of file mswproc.c.
Referenced by MenuWndProc(), mswin_init_nhwindows(), and NHTextWndProc().
HBRUSH text_fg_brush = NULL
Definition at line 50 of file mswproc.c.
Referenced by MenuWndProc(), mswin_init_nhwindows(), and NHTextWndProc().
COLORREF text_fg_color = RGB(0xFF, 0xFF, 0xFF)
Definition at line 59 of file mswproc.c.
Referenced by MenuWndProc(), mswin_init_nhwindows(), and NHTextWndProc().