nethack/win/win32/mhmain.h File Reference
#include `winMS.h`
*
Functions
HWND mswin_init_main_window (void)
void mswin_layout_main_window (HWND changed_child)
void mswin_select_map_mode (int map_mode)
void mswin_menu_check_intf_mode (void)
Function Documentation
HWND mswin_init_main_window (void)
Definition at line 34 of file mhmain.c.
References GetNHApp(), IDS_APP_TITLE, MAX_LOADSTRING, NULL, panic(), register_main_window_class(), mswin_nhwindow_app::regMainBottom, mswin_nhwindow_app::regMainLeft, mswin_nhwindow_app::regMainMaxX, mswin_nhwindow_app::regMainMaxY, mswin_nhwindow_app::regMainMinX, mswin_nhwindow_app::regMainMinY, mswin_nhwindow_app::regMainRight, mswin_nhwindow_app::regMainShowState, mswin_nhwindow_app::regMainTop, szMainWindowClass, and szTitle.
Referenced by mswin_init_nhwindows().
                               {
    static int run_once = 0;
    HWND ret;
    RECT rc;
    /* register window class */
    if(!run_once) {
        LoadString(GetNHApp()->hApp, IDS_APP_TITLE, szTitle,
      MAX_LOADSTRING);
        register_main_window_class();
        run_once = 1;
    }
    
    /* create the main window */
    SystemParametersInfo(SPI_GETWORKAREA, 0, &rc, 0);
    ret = CreateWindow(
            szMainWindowClass, /* registered class name */
            szTitle, /* window name */
            WS_CLIPCHILDREN, /* window style */
            rc.left, /* horizontal position of window */
            rc.top, /* vertical position of window */
            rc.right - rc.left, /* window width */
            rc.bottom - rc.top, /* window height */
            NULL, /* handle to parent or owner window */
            NULL, /* menu handle or child identifier */
            GetNHApp()->hApp, /* handle to application instance */
            NULL /* window-creation data */
        );
    if(!ret) panic("Cannot create main window");
    return ret;
}
void mswin_layout_main_window (HWND changed_child)
Definition at line 541 of file mhmain.c.
References ALIGN_BOTTOM, ALIGN_LEFT, ALIGN_RIGHT, ALIGN_TOP, mswin_nhwindow_data::dead, GetNHApp(), mswin_nhwindow_app::hMainWnd, iflags, max, MAXWINDOWS, min, mswin_command_window_size(), mswin_hwnd_from_winid(), mswin_menu_window_size(), mswin_message_window_size(), mswin_status_window_size(), NHW_MAP, NHW_MENU, NHW_MESSAGE, NHW_RIP, NHW_STATUS, NHW_TEXT, NULL, plname, SIZE, TRUE, mswin_nhwindow_data::type, type, instance_flags::wc_align_message, instance_flags::wc_align_status, mswin_nhwindow_data::win, WIN_MESSAGE, WIN_STATUS, and mswin_nhwindow_app::windowlist.
Referenced by MainWndProc(), mswin_popup_destroy(), mswin_popup_display(), mswin_preference_update(), onMSNHCommand(), and onWMCommand().
{
    winid i;
    RECT client_rt, wnd_rect;
    POINT status_org;
    SIZE status_size;
    POINT msg_org;
    SIZE msg_size;
    POINT map_org;
    SIZE map_size;
    POINT cmd_org;
    SIZE cmd_size;
    HWND wnd_status, wnd_msg;
    PNHMainWindow data;
#if defined(WIN_CE_POCKETPC)
    SIPINFO sip;
    RECT menu_bar;
    RECT visible_rt;
    POINT pt;
#endif
    GetClientRect(GetNHApp()->hMainWnd, &client_rt);
#if defined(WIN_CE_POCKETPC)
    ZeroMemory(&sip, sizeof(sip));
    sip.cbSize = sizeof(sip);
    SHSipInfo(SPI_GETSIPINFO, 0, &sip, 0);
    if(GetNHApp()->bFullScreen) sip.rcVisibleDesktop.top = 0;
    /* adjust client rectangle size */
    GetWindowRect(GetNHApp()->hMenuBar, &menu_bar);
    client_rt.bottom -= menu_bar.bottom-menu_bar.top;
    /* calcuate visible rect in client coordinates */
    pt.x = sip.rcVisibleDesktop.left;
    pt.y = sip.rcVisibleDesktop.top;
    ScreenToClient(GetNHApp()->hMainWnd, &pt);
    SetRect(&wnd_rect,
            pt.x,
            pt.y,
            pt.x+sip.rcVisibleDesktop.right-sip.rcVisibleDesktop.left,
            pt.y+sip.rcVisibleDesktop.bottom-sip.rcVisibleDesktop.top);
    IntersectRect(&visible_rt, &client_rt, &wnd_rect);
#else
# if !defined(WIN_CE_SMARTPHONE)
    client_rt.top += CommandBar_Height(GetNHApp()->hMenuBar);
# else
    /* Smartphone only */
    if(GetNHApp()->bFullScreen) {
        RECT menu_bar;
        GetWindowRect(GetNHApp()->hMenuBar, &menu_bar);
        client_rt.bottom -= menu_bar.bottom-menu_bar.top;
    }
# endif
#endif
    /* get window data */
    data = (PNHMainWindow)GetWindowLong(GetNHApp()->
      hMainWnd, GWL_USERDATA);
    /* get sizes of child windows */
    wnd_status = mswin_hwnd_from_winid(WIN_STATUS);
    if(IsWindow(wnd_status)) {
        mswin_status_window_size(wnd_status, &status_size);
    } else {
        status_size.cx = status_size.cy = 0;
    }
    wnd_msg = mswin_hwnd_from_winid(WIN_MESSAGE);
    if(IsWindow(wnd_msg)) {
        mswin_message_window_size(wnd_msg, &msg_size);
    } else {
        msg_size.cx = msg_size.cy = 0;
    }
    cmd_size.cx = cmd_size.cy = 0;
    if(GetNHApp()->bCmdPad && IsWindow(GetNHApp()->hCmdWnd)) {
        mswin_command_window_size(GetNHApp()->hCmdWnd, &cmd_size);
    }
    /* set window positions */
    /* calculate the application windows size */
#if defined(WIN_CE_POCKETPC)
    SetRect(&wnd_rect, visible_rt.left, visible_rt.top, visible_rt.right, visible_rt.bottom);
    if(sip.fdwFlags & SIPF_ON)
        cmd_size.cx = cmd_size.cy = 0; /* hide keypad window */
#else
    SetRect(&wnd_rect, client_rt.left, client_rt.top, client_rt.right, client_rt.bottom);
#endif
#if !defined(WIN_CE_SMARTPHONE)
    /* other ports have it at the bottom of the screen */
    cmd_size.cx = (wnd_rect.right-wnd_rect.left);
    cmd_org.x = wnd_rect.left;
    cmd_org.y = wnd_rect.bottom - cmd_size.cy;
    wnd_rect.bottom -= cmd_size.cy;
#endif
    /* status window */
    switch(iflags.wc_align_status) {
    case ALIGN_LEFT:
        status_size.cx = (wnd_rect.right-wnd_rect.left)/4;
        status_size.cy = (wnd_rect.bottom-wnd_rect.top); // that won't look good
        status_org.x = wnd_rect.left;
        status_org.y = wnd_rect.top;
        wnd_rect.left += status_size.cx;
        break;
    case ALIGN_RIGHT:
        status_size.cx = (wnd_rect.right-wnd_rect.left)/4;
        status_size.cy = (wnd_rect.bottom-wnd_rect.top); // that won't look good
        status_org.x = wnd_rect.right - status_size.cx;
        status_org.y = wnd_rect.top;
        wnd_rect.right -= status_size.cx;
        break;
    case ALIGN_TOP:
        status_size.cx = (wnd_rect.right-wnd_rect.left);
        status_org.x = wnd_rect.left;
        status_org.y = wnd_rect.top;
        wnd_rect.top += status_size.cy;
        break;
    case ALIGN_BOTTOM:
    default:
        status_size.cx = (wnd_rect.right-wnd_rect.left);
        status_org.x = wnd_rect.left;
        status_org.y = wnd_rect.bottom - status_size.cy;
        wnd_rect.bottom -= status_size.cy;
        break;
    }
    /* message window */
    switch(iflags.wc_align_message) {
    case ALIGN_LEFT:
#if defined(WIN_CE_SMARTPHONE)
        /* smartphone has a keypad window on the right (bottom) side of the message window */
        msg_size.cx = cmd_size.cx = max(msg_size.cx, cmd_size.cx);
        msg_size.cy = (wnd_rect.bottom-wnd_rect.top) - cmd_size.cy;
        msg_org.x = cmd_org.x = wnd_rect.left;
        msg_org.y = wnd_rect.top;
        cmd_org.y = msg_org.y + msg_size.cy;
#else
        msg_size.cx = (wnd_rect.right-wnd_rect.left)/4;
        msg_size.cy = (wnd_rect.bottom-wnd_rect.top);
        msg_org.x = wnd_rect.left;
        msg_org.y = wnd_rect.top;
#endif
        wnd_rect.left += msg_size.cx;
        break;
    case ALIGN_RIGHT:
#if defined(WIN_CE_SMARTPHONE)
        /* smartphone has a keypad window on the right (bottom) side of the message window */
        msg_size.cx = cmd_size.cx = max(msg_size.cx, cmd_size.cx);
        msg_size.cy = (wnd_rect.bottom-wnd_rect.top) - cmd_size.cy;
        msg_org.x = cmd_org.x = wnd_rect.right - msg_size.cx;
        msg_org.y = wnd_rect.top;
        cmd_org.y = msg_org.y + msg_size.cy;
#else
        msg_size.cx = (wnd_rect.right-wnd_rect.left)/4;
        msg_size.cy = (wnd_rect.bottom-wnd_rect.top);
        msg_org.x = wnd_rect.right - msg_size.cx;
        msg_org.y = wnd_rect.top;
#endif
    
        wnd_rect.right -= msg_size.cx;
        break;
    case ALIGN_TOP:
#if defined(WIN_CE_SMARTPHONE)
        /* smartphone has a keypad window on the right side of the message window */
        msg_size.cy = cmd_size.cy = max(msg_size.cy, cmd_size.cy);
        msg_size.cx = (wnd_rect.right - wnd_rect.left) - cmd_size.cx;
        msg_org.x = wnd_rect.left;
        cmd_org.x = msg_org.x + msg_size.cx;
        msg_org.y = cmd_org.y = wnd_rect.bottom - msg_size.cy;
#else
        msg_size.cx = (wnd_rect.right-wnd_rect.left);
        msg_org.x = wnd_rect.left;
        msg_org.y = wnd_rect.top;
#endif
        wnd_rect.top += msg_size.cy;
        break;
    case ALIGN_BOTTOM:
    default:
#if defined(WIN_CE_SMARTPHONE)
        /* smartphone has a keypad window on the right side of the message window */
        msg_size.cy = cmd_size.cy = max(msg_size.cy, cmd_size.cy);
        msg_size.cx = (wnd_rect.right - wnd_rect.left) - cmd_size.cx;
        msg_org.x = wnd_rect.left;
        cmd_org.x = msg_org.x + msg_size.cx;
        msg_org.y = cmd_org.y = wnd_rect.bottom - msg_size.cy;
#else
        msg_size.cx = (wnd_rect.right-wnd_rect.left);
        msg_org.x = wnd_rect.left;
        msg_org.y = wnd_rect.bottom - msg_size.cy;
#endif
        wnd_rect.bottom -= msg_size.cy;
        break;
    }
    map_org.x = wnd_rect.left;
    map_org.y = wnd_rect.top;
    map_size.cx = wnd_rect.right - wnd_rect.left;
    map_size.cy = wnd_rect.bottom - wnd_rect.top;
    /* go through the windows list and adjust sizes */
    for(i=0; i<MAXWINDOWS; i++) {
        if(GetNHApp()->windowlist[i].win && !GetNHApp()->
      windowlist[i].dead) {
            switch(GetNHApp()->windowlist[i].type) {
            case NHW_MESSAGE:
                MoveWindow(GetNHApp()->windowlist[i].win,
                           msg_org.x,
                           msg_org.y,
                           msg_size.cx,
                           msg_size.cy,
                           TRUE);
                break;
            case NHW_MAP:
                MoveWindow(GetNHApp()->windowlist[i].win,
                           map_org.x,
                           map_org.y,
                           map_size.cx,
                           map_size.cy,
                           TRUE);
                break;
            case NHW_STATUS:
                MoveWindow(GetNHApp()->windowlist[i].win,
                           status_org.x,
                           status_org.y,
                           status_size.cx,
                           status_size.cy,
                           TRUE);
                break;
            case NHW_TEXT:
            case NHW_MENU:
            case NHW_RIP:
            {
                POINT menu_org;
                SIZE menu_size;
                menu_org.x = client_rt.left;
                menu_org.y = client_rt.top;
#if defined(WIN_CE_POCKETPC)
                menu_size.cx = min(sip.rcVisibleDesktop.right-sip.rcVisibleDesktop.left,
                                   client_rt.right - client_rt.left);
                menu_size.cy = min(sip.rcVisibleDesktop.bottom-sip.rcVisibleDesktop.top,
                                   client_rt.bottom - client_rt.top);
#else
                menu_size.cx = client_rt.right - client_rt.left;
                menu_size.cy = client_rt.bottom - client_rt.top;
#endif
#if defined(WIN_CE_SMARTPHONE)
                /* leave room for the command window */
                if(GetNHApp()->windowlist[i].type == NHW_MENU) {
                    menu_size.cy -= cmd_size.cy;
                }
                /* dialogs are popup windows unde SmartPhone so we need
                   to convert to screen coordinates */
                ClientToScreen(GetNHApp()->hMainWnd, &menu_org);
#endif
                MoveWindow(GetNHApp()->windowlist[i].win,
                           menu_org.x,
                           menu_org.y,
                           menu_size.cx,
                           menu_size.cy,
                           TRUE);
            } break;
            }
            ShowWindow(GetNHApp()->windowlist[i].win, SW_SHOW);
            InvalidateRect(GetNHApp()->windowlist[i].win, NULL, TRUE);
        }
    }
    if(IsWindow(GetNHApp()->hCmdWnd)) {
        /* show command window only if it exists and
           the game is ready (plname is set) */
        if(GetNHApp()->bCmdPad && cmd_size.cx>0 && cmd_size.cy>0 && *
      plname) {
            MoveWindow(GetNHApp()->hCmdWnd,
                   cmd_org.x,
                   cmd_org.y,
                   cmd_size.cx,
                   cmd_size.cy,
                   TRUE);
            ShowWindow(GetNHApp()->hCmdWnd, SW_SHOW);
        } else {
            ShowWindow(GetNHApp()->hCmdWnd, SW_HIDE);
        }
    }
}
void mswin_menu_check_intf_mode (void)
Definition at line 868 of file mhmain.c.
References GetNHApp(), and IDM_NHMODE.
Referenced by mswin_init_nhwindows(), and onWMCommand().
{
    HMENU hMenu = GetMenu(GetNHApp()->hMainWnd);
    if (GetNHApp()->regNetHackMode)
        CheckMenuItem(hMenu, IDM_NHMODE, MF_CHECKED);
    else
        CheckMenuItem(hMenu, IDM_NHMODE, MF_UNCHECKED);
}
void mswin_select_map_mode (int map_mode)
Definition at line 1008 of file mhmain.c.
References _get_main_menu(), BUFSZ, error(), GetNHApp(), mswin_nhwindow_app::hMainWnd, ID_MAP, ID_VIEW, IDM_MAP_ASCII10X18, IDM_MAP_FIT_TO_SCREEN, IDM_MAP_TILES, IDS_CAP_ENTIREMAP, IDS_CAP_NORMALMAP, iflags, IS_MAP_ASCII, IS_MAP_FIT_TO_SCREEN, Is_rogue_level, MAP_MODE_TILES, mswin_nethack_main_window::mapAcsiiModeSave, mapmode2menuid(), mswin_hwnd_from_winid(), mswin_map_mode(), mswin_winid_from_type(), NHW_MAP, panic(), u, you::uz, instance_flags::wc_map_mode, WIN_ERR, and WIN_MAP.
Referenced by MainWndProc(), mswin_preference_update(), onMSNHCommand(), and onWMCommand().
{
    HMENU hmenuMap;
    PNHMainWindow data;
    winid map_id;
    map_id = WIN_MAP;
    data = (PNHMainWindow)GetWindowLong(GetNHApp()->
      hMainWnd, GWL_USERDATA);
#if defined(WIN_CE_SMARTPHONE)
    /* Smartphone manu has only 2 items */
    hmenuMap = _get_main_menu(ID_VIEW);
#else
    hmenuMap = _get_main_menu(ID_MAP);
#endif
    /* override for Rogue level */
#ifdef REINCARNATION
    if(Is_rogue_level(&u.uz) && !IS_MAP_ASCII(mode)) return;
#endif
    /* set map mode menu mark */
    if(IS_MAP_ASCII(mode)) {
        CheckMenuRadioItem(
            hmenuMap,
            IDM_MAP_TILES,
            IDM_MAP_FIT_TO_SCREEN,
            mapmode2menuid(IS_MAP_FIT_TO_SCREEN(mode)? data->
      mapAcsiiModeSave : mode),
            MF_BYCOMMAND);
    } else {
        CheckMenuRadioItem(
            hmenuMap,
            IDM_MAP_TILES,
            IDM_MAP_FIT_TO_SCREEN,
            mapmode2menuid(MAP_MODE_TILES),
            MF_BYCOMMAND);
    }
#if defined(WIN_CE_SMARTPHONE)
    /* update "Fit To Screen" item text */
    {
        TCHAR wbuf[BUFSZ];
        TBBUTTONINFO tbbi;
        ZeroMemory(wbuf, sizeof(wbuf));
        if(!LoadString(
            GetNHApp()->hApp,
            (IS_MAP_FIT_TO_SCREEN(mode)? IDS_CAP_NORMALMAP :
      IDS_CAP_ENTIREMAP),
            wbuf,
            BUFSZ)) {
            panic("cannot load main menu strings");
        }
        ZeroMemory(&tbbi, sizeof(tbbi));
        tbbi.cbSize = sizeof(tbbi);
        tbbi.dwMask = TBIF_TEXT;
        tbbi.pszText = wbuf;
        if(!SendMessage(
                GetNHApp()->hMenuBar,
                TB_SETBUTTONINFO,
                IDM_MAP_FIT_TO_SCREEN,
                (LPARAM)&tbbi)) {
            error("Cannot update IDM_MAP_FIT_TO_SCREEN menu item.");
        }
    }
#else
    /* set fit-to-screen mode mark */
    CheckMenuItem(
        hmenuMap,
        IDM_MAP_FIT_TO_SCREEN,
        MF_BYCOMMAND |
        (IS_MAP_FIT_TO_SCREEN(mode)? MF_CHECKED : MF_UNCHECKED)
    );
#endif
    if(IS_MAP_ASCII(iflags.wc_map_mode) && !
      IS_MAP_FIT_TO_SCREEN(iflags.wc_map_mode)) {
        data->mapAcsiiModeSave = iflags.wc_map_mode;
    }
    iflags.wc_map_mode = mode;
    
    /*
    ** first, check if WIN_MAP has been inialized.
    ** If not - attempt to retrieve it by type, then check it again
    */
    if(map_id==WIN_ERR)
        map_id = mswin_winid_from_type(NHW_MAP);
    if(map_id!=WIN_ERR)
        mswin_map_mode(mswin_hwnd_from_winid(map_id), mode);
}