nethack/win/win32/mhrip.h File Reference
#include `winMS.h`
*
#include `config.h`
*
#include `global.h`
*
Functions
void mswin_finish_rip_text (winid wid)
HWND mswin_init_RIP_window (void)
void mswin_display_RIP_window (HWND hwnd)
Function Documentation
void mswin_display_RIP_window (HWND hwnd)
Definition at line 13 of file mhrip.c.
References FALSE, GetNHApp(), mswin_nhwindow_app::hMainWnd, mswin_nhwindow_app::hPopupWnd, mswin_display_text_window(), mswin_get_font(), mswin_hwnd_from_winid(), NHW_TEXT, NULL, RIP_HEIGHT, RIP_OFFSET_X, RIP_OFFSET_Y, RIP_WIDTH, TRUE, WIN_MAP, and mswin_nethack_text_window::window_text.
Referenced by mswin_display_nhwindow().
{
    mswin_display_text_window(hWnd);
}
void mswin_finish_rip_text (winid wid)
Definition at line 262 of file mhrip.c.
References MSNH_MSG_DIED, mswin_hwnd_from_winid(), and WM_MSNH_COMMAND.
Referenced by mswin_outrip().
{
    SendMessage (mswin_hwnd_from_winid(wid),
      WM_MSNH_COMMAND, MSNH_MSG_DIED, 0);
}
HWND mswin_init_RIP_window (void)
Definition at line 8 of file mhrip.c.
References CreateDialog(), GetNHApp(), IDD_NHRIP, malloc(), mswin_init_text_window(), NHRIPWndProc(), and panic().
Referenced by mswin_outrip().
{
    return mswin_init_text_window();
}