nethack/win/win32/mhfont.c File Reference
#include `mhfont.h`
*
Data Structures
struct font_table_entry
Macros
#define MAXFONTS 64
#define NHFONT_CODE(win, attr) (((attr&0xFF)<<8)|(win_type&0xFF))
Functions
static void __cdecl font_table_cleanup (void)
void mswin_init_splashfonts (HWND hWnd)
void mswin_destroy_splashfonts ()
HGDIOBJ mswin_get_font (int win_type, int attr, HDC hdc, BOOL replace)
UINT mswin_charset ()
Variables
static struct font_table_entry font_table [MAXFONTS]
static int font_table_size = 0
HFONT version_splash_font
Macro Definition Documentation
#define MAXFONTS 64
Definition at line 8 of file mhfont.c.
Referenced by mswin_get_font().
#define NHFONT_CODE(win, attr) (((attr&0xFF)<<8)|(win_type&0xFF))
Definition at line 18 of file mhfont.c.
Referenced by mswin_get_font().
Function Documentation
void __cdecl font_table_cleanup (void) [static]
Definition at line 197 of file mhfont.c.
References font_table, and font_table_size.
Referenced by mswin_get_font().
{
    int i;
    for(i=0; i<font_table_size; i++) {
        DeleteObject(font_table[i].hFont);
    }
    font_table_size = 0;
}
UINT mswin_charset (void)
Definition at line 182 of file mhfont.c.
References instance_flags::IBMgraphics, and iflags.
{
    CHARSETINFO cis;
    if(iflags.IBMgraphics)
        if(TranslateCharsetInfo((DWORD*)GetOEMCP(), &cis, TCI_SRCCODEPAGE))
            return cis.ciCharset;
        else
            return OEM_CHARSET;
    else
        if(TranslateCharsetInfo((DWORD*)GetACP(), &cis, TCI_SRCCODEPAGE))
            return cis.ciCharset;
        else
            return ANSI_CHARSET;
}
void mswin_destroy_splashfonts (void)
Definition at line 46 of file mhfont.c.
References version_splash_font.
Referenced by mswin_display_splash_window().
{
    DeleteObject (version_splash_font);
}
HGDIOBJ mswin_get_font (int win_type, int attr, HDC hdc, BOOL replace)
Definition at line 53 of file mhfont.c.
References ATR_BLINK, ATR_BOLD, ATR_INVERSE, ATR_ULINE, font_table_entry::code, FALSE, font_table, font_table_cleanup(), font_table_size, font_table_entry::hFont, iflags, MAXFONTS, mswin_charset(), NH_A2W, NHFONT_CODE, NHW_MENU, NHW_MESSAGE, NHW_STATUS, NHW_TEXT, NULL, panic(), TRUE, instance_flags::wc_font_menu, instance_flags::wc_font_message, instance_flags::wc_font_status, instance_flags::wc_font_text, instance_flags::wc_fontsiz_menu, instance_flags::wc_fontsiz_message, instance_flags::wc_fontsiz_status, and instance_flags::wc_fontsiz_text.
{
    HFONT fnt = NULL;
    LOGFONT lgfnt;
    int font_size;
    int font_index;
    static BOOL once = FALSE;
    if(!once) {
        once = TRUE;
        atexit(font_table_cleanup);
    }
    ZeroMemory(&lgfnt, sizeof(lgfnt));
    /* try find font in the table */
    for(font_index=0; font_index<font_table_size; font_index++)
        if(NHFONT_CODE(win_type, attr)==font_table[font_index].code)
            break;
    if(!replace && font_index<font_table_size)
        return font_table[font_index].hFont;
    switch(win_type) {
    case NHW_STATUS:
        lgfnt.lfHeight = -iflags.wc_fontsiz_status*GetDeviceCaps(hdc,
      LOGPIXELSY)/72; // height of font
        lgfnt.lfWidth = 0; // average character width
        lgfnt.lfEscapement = 0; // angle of escapement
        lgfnt.lfOrientation = 0; // base-line orientation angle
        lgfnt.lfWeight = FW_BOLD; // font weight
        lgfnt.lfItalic = FALSE; // italic attribute option
        lgfnt.lfUnderline = FALSE; // underline attribute option
        lgfnt.lfStrikeOut = FALSE; // strikeout attribute option
        lgfnt.lfCharSet = mswin_charset(); // character set identifier
        lgfnt.lfOutPrecision = OUT_DEFAULT_PRECIS; // output precision
        lgfnt.lfClipPrecision = CLIP_DEFAULT_PRECIS; // clipping precision
        lgfnt.lfQuality = DEFAULT_QUALITY; // output quality
        if(iflags.wc_font_status &&
            *iflags.wc_font_status) {
            lgfnt.lfPitchAndFamily = DEFAULT_PITCH; // pitch and family
            NH_A2W(iflags.wc_font_status, lgfnt.lfFaceName, LF_FACESIZE);
        } else {
            lgfnt.lfPitchAndFamily = FIXED_PITCH; // pitch and family
        }
        break;
    case NHW_MENU:
        lgfnt.lfHeight = -iflags.wc_fontsiz_menu*GetDeviceCaps(hdc,
      LOGPIXELSY)/72; // height of font
        lgfnt.lfWidth = 0; // average character width
        lgfnt.lfEscapement = 0; // angle of escapement
        lgfnt.lfOrientation = 0; // base-line orientation angle
        lgfnt.lfWeight = (attr==ATR_BOLD || attr==ATR_INVERSE)? FW_BOLD :
      FW_NORMAL; // font weight
        lgfnt.lfItalic = (attr==ATR_BLINK)? TRUE: FALSE; // italic
       attribute option
        lgfnt.lfUnderline = (attr==ATR_ULINE)? TRUE : FALSE; // underline
       attribute option
        lgfnt.lfStrikeOut = FALSE; // strikeout attribute option
        lgfnt.lfCharSet = mswin_charset(); // character set identifier
        lgfnt.lfOutPrecision = OUT_DEFAULT_PRECIS; // output precision
        lgfnt.lfClipPrecision = CLIP_DEFAULT_PRECIS; // clipping precision
        lgfnt.lfQuality = DEFAULT_QUALITY; // output quality
        if(iflags.wc_font_menu &&
            *iflags.wc_font_menu) {
            lgfnt.lfPitchAndFamily = DEFAULT_PITCH; // pitch and family
            NH_A2W(iflags.wc_font_menu, lgfnt.lfFaceName, LF_FACESIZE);
        } else {
            lgfnt.lfPitchAndFamily = FIXED_PITCH; // pitch and family
        }
        break;
    case NHW_MESSAGE:
        font_size = (attr==ATR_INVERSE)? iflags.
      wc_fontsiz_message+1 : iflags.wc_fontsiz_message;
        lgfnt.lfHeight = -font_size*GetDeviceCaps(hdc, LOGPIXELSY)/72; // height of font
        lgfnt.lfWidth = 0; // average character width
        lgfnt.lfEscapement = 0; // angle of escapement
        lgfnt.lfOrientation = 0; // base-line orientation angle
        lgfnt.lfWeight = (attr==ATR_BOLD || attr==ATR_INVERSE)? FW_BOLD :
      FW_NORMAL; // font weight
        lgfnt.lfItalic = (attr==ATR_BLINK)? TRUE: FALSE; // italic
       attribute option
        lgfnt.lfUnderline = (attr==ATR_ULINE)? TRUE : FALSE; // underline
       attribute option
        lgfnt.lfStrikeOut = FALSE; // strikeout attribute option
        lgfnt.lfCharSet = mswin_charset(); // character set identifier
        lgfnt.lfOutPrecision = OUT_DEFAULT_PRECIS; // output precision
        lgfnt.lfClipPrecision = CLIP_DEFAULT_PRECIS; // clipping precision
        lgfnt.lfQuality = DEFAULT_QUALITY; // output quality
        if(iflags.wc_font_message &&
            *iflags.wc_font_message) {
            lgfnt.lfPitchAndFamily = DEFAULT_PITCH; // pitch and family
            NH_A2W(iflags.wc_font_message, lgfnt.lfFaceName, LF_FACESIZE);
        } else {
            lgfnt.lfPitchAndFamily = VARIABLE_PITCH; // pitch and family
        }
        break;
    case NHW_TEXT:
        lgfnt.lfHeight = -iflags.wc_fontsiz_text*GetDeviceCaps(hdc,
      LOGPIXELSY)/72; // height of font
        lgfnt.lfWidth = 0; // average character width
        lgfnt.lfEscapement = 0; // angle of escapement
        lgfnt.lfOrientation = 0; // base-line orientation angle
        lgfnt.lfWeight = (attr==ATR_BOLD || attr==ATR_INVERSE)? FW_BOLD :
      FW_NORMAL; // font weight
        lgfnt.lfItalic = (attr==ATR_BLINK)? TRUE: FALSE; // italic
       attribute option
        lgfnt.lfUnderline = (attr==ATR_ULINE)? TRUE : FALSE; // underline
       attribute option
        lgfnt.lfStrikeOut = FALSE; // strikeout attribute option
        lgfnt.lfCharSet = mswin_charset(); // character set identifier
        lgfnt.lfOutPrecision = OUT_DEFAULT_PRECIS; // output precision
        lgfnt.lfClipPrecision = CLIP_DEFAULT_PRECIS; // clipping precision
        lgfnt.lfQuality = DEFAULT_QUALITY; // output quality
        if(iflags.wc_font_text &&
            *iflags.wc_font_text) {
            lgfnt.lfPitchAndFamily = DEFAULT_PITCH; // pitch and family
            NH_A2W(iflags.wc_font_text, lgfnt.lfFaceName, LF_FACESIZE);
        } else {
            lgfnt.lfPitchAndFamily = FIXED_PITCH; // pitch and family
        }
        break;
    }
    fnt = CreateFontIndirect(&lgfnt);
    /* add font to the table */
    if(font_index==font_table_size) {
        if(font_table_size>=MAXFONTS) panic("font table overflow!");
        font_table_size++;
    } else {
        DeleteObject(font_table[font_index].hFont);
    }
    font_table[font_index].code = NHFONT_CODE(win_type, attr);
    font_table[font_index].hFont = fnt;
    return fnt;
}
void mswin_init_splashfonts (HWND hWnd)
Definition at line 22 of file mhfont.c.
References FALSE, NH_A2W, NULL, and version_splash_font.
Referenced by mswin_display_splash_window().
{
    HDC hdc = GetDC(hWnd);
    HFONT fnt = NULL;
    LOGFONT lgfnt;
    ZeroMemory(&lgfnt, sizeof(lgfnt));
    lgfnt.lfHeight = -80; // height of font
    lgfnt.lfWidth = 0; // average character width
    lgfnt.lfEscapement = 0; // angle of escapement
    lgfnt.lfOrientation = 0; // base-line orientation angle
    lgfnt.lfWeight = FW_BOLD; // font weight
    lgfnt.lfItalic = FALSE; // italic attribute option
    lgfnt.lfUnderline = FALSE; // underline attribute option
    lgfnt.lfStrikeOut = FALSE; // strikeout attribute option
    lgfnt.lfCharSet = ANSI_CHARSET; // character set identifier
    lgfnt.lfOutPrecision = OUT_DEFAULT_PRECIS; // output precision
    lgfnt.lfClipPrecision = CLIP_DEFAULT_PRECIS; // clipping precision
    lgfnt.lfQuality = DEFAULT_QUALITY; // output quality
    lgfnt.lfPitchAndFamily = DEFAULT_PITCH; // pitch and family
    NH_A2W("Times New Roman", lgfnt.lfFaceName, LF_FACESIZE);
    version_splash_font = CreateFontIndirect(&lgfnt);
    ReleaseDC(hWnd, hdc);
}
Variable Documentation
struct font_table_entry font_table[MAXFONTS] [static]
Referenced by font_table_cleanup(), and mswin_get_font().
int font_table_size = 0 [static]
Definition at line 15 of file mhfont.c.
Referenced by font_table_cleanup(), and mswin_get_font().
HFONT version_splash_font
Definition at line 16 of file mhfont.c.
Referenced by NHSplashWndProc().