nethack/sys/amiga/winchar.c File Reference
#include <exec/types.h>
*
#include <libraries/iffparse.h>
*
#include <graphics/scale.h>
*
#include <proto/iffparse.h>
*
#include `NH:src/tile.c`
*
#include `NH:win/share/tile.h`
*
#include `NH:sys/amiga/windefs.h`
*
#include `NH:sys/amiga/winext.h`
*
#include `NH:sys/amiga/winproto.h`
*
Data Structures
struct MyBitMap
struct amiv_glyph_node
Macros
#define IMGROWS 12
#define IMGCOLUMNS 20
#define IMGPAGESIZE (IMGROWS*IMGCOLUMNS)
#define ID_BMAP MAKE_ID('B','M','A','P')	/* The type of form we use */
#define ID_BMHD MAKE_ID('B','M','H','D')	/* The ILBM bitmap header */
#define ID_CAMG MAKE_ID('C','A','M','G')	/* The ILBM camg (ignored) */
#define ID_CMAP MAKE_ID('C','M','A','P')	/* Standard ILBM color map */
#define ID_PLNE MAKE_ID('P','L','N','E')	/* The plane data */
#define ID_PDAT MAKE_ID('P','D','A','T')	/* The PDAT structure below */
#define NUMTILEIMAGES 3
#define TBLMONTILE 0
#define TBLOBJTILE 1
#define TBLOTHTILE 2
#define NUMBER_GLYPH_NODES 80
#define GLYPH_BUFFER_SIZE 512
Functions
int main (int, char **)
struct BitMap * MyAllocBitMap (int, int, int, long)
void MyFreeBitMap (struct BitMap *)
void FreeImageFiles (char **, struct BitMap **)
void amiv_flush_glyph_buffer (struct Window *)
void amiv_lprint_glyph (winid, int, int)
void amii_lprint_glyph (winid, int, int)
void amiv_start_glyphout (winid)
void amii_end_glyphout (winid)
void SetMazeType (MazeType)
int GlyphToIcon (int)
void amii_start_glyphout (winid)
void amii_flush_glyph_buffer (struct Window *)
BitMapHeader ReadTileImageFiles ()
BitMapHeader ReadImageFiles (char **filenames, struct BitMap **iffimg, char **errstrp)
void FreeTileImageFiles ()
void flush_glyph_buffer (struct Window *vw)
Variables
int amii_extraplanes = 0
int reclip
struct PDAT pictdata
char * tileimages []
struct BitMap * ifftimg [NUMTILEIMAGES]
struct BitMap * tile
unsigned short glyph_node_index
unsigned short glyph_buffer_index
struct amiv_glyph_node amiv_g_nodes [NUMBER_GLYPH_NODES]
static char amiv_glyph_buffer [GLYPH_BUFFER_SIZE]
static long xsave
static long ysave
static long modesave
static long apensave
static long bpensave
static int usecolor
static maze_type =COL_MAZE_BRICK
Macro Definition Documentation
#define GLYPH_BUFFER_SIZE 512
Definition at line 474 of file winchar.c.
#define ID_BMAP MAKE_ID('B','M','A','P')	/* The type of form we use */
Definition at line 68 of file winchar.c.
Referenced by ReadImageFiles().
#define ID_BMHD MAKE_ID('B','M','H','D')	/* The ILBM bitmap header */
Definition at line 69 of file winchar.c.
Referenced by ReadImageFiles().
#define ID_CAMG MAKE_ID('C','A','M','G')	/* The ILBM camg (ignored) */
Definition at line 70 of file winchar.c.
Referenced by ReadImageFiles().
#define ID_CMAP MAKE_ID('C','M','A','P')	/* Standard ILBM color map */
Definition at line 71 of file winchar.c.
Referenced by ReadImageFiles().
#define ID_PDAT MAKE_ID('P','D','A','T')	/* The PDAT structure below */
Definition at line 73 of file winchar.c.
Referenced by ReadImageFiles().
#define ID_PLNE MAKE_ID('P','L','N','E')	/* The plane data */
Definition at line 72 of file winchar.c.
Referenced by ReadImageFiles().
#define IMGCOLUMNS 20
Definition at line 65 of file winchar.c.
#define IMGPAGESIZE (IMGROWS*IMGCOLUMNS)
Definition at line 66 of file winchar.c.
#define IMGROWS 12
Definition at line 64 of file winchar.c.
#define NUMBER_GLYPH_NODES 80
Definition at line 473 of file winchar.c.
Referenced by amiv_lprint_glyph().
#define NUMTILEIMAGES 3
Definition at line 77 of file winchar.c.
#define TBLMONTILE 0
Referenced by amiv_lprint_glyph().
#define TBLOBJTILE 1
Referenced by amiv_lprint_glyph().
#define TBLOTHTILE 2
Referenced by amiv_lprint_glyph().
Function Documentation
void amii_end_glyphout (winid window)
Definition at line 899 of file winchar.c.
References amii_wins, FLMAP_INGLYPH, iflags, NULL, panic(), usecolor, amii_WinDesc::wflags, and amii_WinDesc::win.
Referenced by amii_display_nhwindow(), and amiv_flush_glyph_buffer().
{
    struct amii_WinDesc *cw;
    struct Window *w;
    if((cw = amii_wins[ window ]) == (struct amii_WinDesc *)
      NULL)
    panic("bad window id %d in amii_end_glyphout()", window);
    if((cw->wflags & FLMAP_INGLYPH) == 0)
    return;
    cw->wflags &= ~(FLMAP_INGLYPH);
    if(!(w = cw->win))
    panic("bad winid %d, no window ptr set", window);
    /*
     * Clean up whatever is left in the buffer
     */
    iflags.use_color = usecolor;
    /*
     * Reset internal data structs
     */
    SetAPen(w->RPort, apensave);
    SetBPen(w->RPort, bpensave);
    SetDrMd(w->RPort, modesave);
    Move(w->RPort, xsave, ysave);
}
void amii_flush_glyph_buffer (struct Window *)
Referenced by flush_glyph_buffer().
void amii_lprint_glyph (winid , int , int)
void amii_start_glyphout (winid)
void amiv_flush_glyph_buffer (struct Window * vw)
Definition at line 497 of file winchar.c.
References amii_end_glyphout(), amii_extraplanes, amii_putstr(), amii_wins, amiv_g_nodes, amiv_start_glyphout(), amiv_glyph_node::bitmap, COLNO, cursor_off(), flags, glyph_node_index, mxsize, MyAllocBitMap(), MyFreeBitMap(), mysize, PDAT::nplanes, NULL, amiv_glyph_node::odstx, amiv_glyph_node::odsty, pictdata, reclip, ROWNO, rp, amiv_glyph_node::srcx, amiv_glyph_node::srcy, tile, WIN_ERR, WIN_MAP, WIN_MESSAGE, WIN_OVER, xsize, PDAT::xsize, ysize, and PDAT::ysize.
Referenced by amiv_lprint_glyph(), and flush_glyph_buffer().
{
#if !defined(DISPMAP) || defined(OPT_DISPMAP)
    int xsize, ysize, x, y;
    struct BitScaleArgs bsa;
    struct BitScaleArgs bsm;
    struct RastPort rast;
    struct Window *w = NULL;
    struct BitMap *imgbm = 0, *bm = 0;
    int i, k;
    int scaling_needed;
    register struct RastPort *rp = vw->RPort;
#endif
    /* If nothing is buffered, return before we do anything */
    if(glyph_node_index == 0)
    return;
    cursor_off(WIN_MAP);
    amiv_start_glyphout(WIN_MAP);
#ifdef OPT_DISPMAP
    if(flags.fast_map){
#endif
#ifdef DISPMAP
    display_map(vw);
#endif
#ifdef OPT_DISPMAP
    } else {
#endif
#if !defined(DISPMAP) || defined(OPT_DISPMAP)
/* XXX fix indent */
    /* This is a dynamic value based on this relationship. */
    scaling_needed = (pictdata.xsize != mxsize || pictdata.
      ysize != mysize);
    /* If overview window is up, set up to render the correct scale there */
    if(WIN_OVER != WIN_ERR && (w = amii_wins[ WIN_OVER ]->win) !=
      NULL)
    {
    InitRastPort(&rast);
    /* Calculate the x and y size of each tile for a ROWNO by COLNO map */
    xsize = (w->Width - w->BorderLeft - w->BorderRight) / COLNO;
    ysize = (w->Height - w->BorderTop - w->BorderBottom) / ROWNO;
    /* Get a chip memory bitmap to blit out of */
    bm = MyAllocBitMap(pictdata.xsize, pictdata.
      ysize,
        pictdata.nplanes + amii_extraplanes, MEMF_CLEAR|MEMF_CHIP);
    if(bm == NULL)
    {
        amii_putstr(WIN_MESSAGE, 0, "Can't allocate bitmap for scaling overview
       window");
    }
    rast.BitMap = bm;
    memset(&bsa, 0, sizeof(bsa));
    bsa.bsa_SrcX = bsa.bsa_SrcY = 0;
    bsa.bsa_SrcBitMap = tile;
    bsa.bsa_SrcWidth = pictdata.xsize;
    bsa.bsa_SrcHeight = pictdata.ysize;
    bsa.bsa_XSrcFactor = pictdata.xsize;
    bsa.bsa_YSrcFactor = pictdata.ysize;
    bsa.bsa_DestX = 0;
    bsa.bsa_DestY = 0;
    bsa.bsa_DestWidth = xsize;
    bsa.bsa_DestHeight = ysize;
    bsa.bsa_XDestFactor = xsize;
    bsa.bsa_YDestFactor = ysize;
    bsa.bsa_DestBitMap = bm;
    }
    if(scaling_needed)
    {
    /* Fill in scaling data for map rendering */
    memset(&bsm, 0, sizeof(bsm));
    bsm.bsa_SrcX = bsm.bsa_SrcY = 0;
    bsm.bsa_SrcBitMap = tile;
    bsm.bsa_SrcWidth = pictdata.xsize;
    bsm.bsa_SrcHeight = pictdata.ysize;
    bsm.bsa_XSrcFactor = pictdata.xsize;
    bsm.bsa_YSrcFactor = pictdata.ysize;
    bsm.bsa_DestWidth = mxsize;
    bsm.bsa_DestHeight = mysize;
    bsm.bsa_XDestFactor = mxsize;
    bsm.bsa_YDestFactor = mysize;
    bsm.bsa_DestBitMap = rp->BitMap;
    bsm.bsa_DestY = bsm.bsa_DestX = 0;
    imgbm = MyAllocBitMap(mxsize, mysize,
        pictdata.nplanes + amii_extraplanes, MEMF_CLEAR|MEMF_CHIP);
    if(imgbm == NULL)
    {
        amii_putstr(WIN_MESSAGE, 0,
        "Can't allocate scaling bitmap for map window");
    }
    else
        bsm.bsa_DestBitMap = imgbm;
    }
    /* Go ahead and start dumping the stuff */
    for(i=0; i<glyph_node_index; ++i)
    {
    /* Do it */
    register int offx, offy, j;
    struct BitMap *nodebm = amiv_g_nodes[ i ].bitmap;
    /* Get the unclipped coordinates */
    x = amiv_g_nodes[ i ].odstx;
    y = amiv_g_nodes[ i ].odsty;
    /* If image is not in CHIP. copy each plane into tile line by line */
    offx = amiv_g_nodes[ i ].srcx / 8; /* 8 is bits per byte */
    offy = amiv_g_nodes[ i ].srcy * nodebm->BytesPerRow;
    for(j = 0; j < pictdata.nplanes + amii_extraplanes; ++j)
    {
        for(k = 0; k < pictdata.ysize; ++k)
        {
            /* For a 16x16 tile, this could just be short assignments, but
             * this code is generalized to handle any size tile image...
             */
            memcpy(tile->Planes[ j ] + ((k * pictdata.ysize) / 8),
            nodebm->Planes[ j ] + offx + offy + (nodebm->BytesPerRow * k),
            pictdata.ysize/8);
        }
    }
    if(!clipping ||
        (x >= clipx && y >= clipy &&
          x < clipxmax && y < clipymax))
    {
        /* scaling is needed, do it */
        if(scaling_needed)
        {
        BitMapScale(&bsm);
        BltBitMapRastPort(imgbm, 0, 0,
            rp, amiv_g_nodes[ i ].dstx, amiv_g_nodes[ i ].dsty,
            mxsize, mysize, 0xc0);
        }
        else
        {
        BltBitMapRastPort(tile, 0, 0,
            rp, amiv_g_nodes[ i ].dstx, amiv_g_nodes[ i ].dsty,
            pictdata.xsize, pictdata.ysize, 0xc0);
        }
    }
    /* Draw the overview window unless we are scrolling the map raster around */
    if(bm && w && reclip != 2)
    {
        BitMapScale(&bsa);
        BltBitMapRastPort(rast.BitMap, 0, 0,
            w->RPort,
            w->BorderLeft + amiv_g_nodes[ i ].odstx*xsize,
            w->BorderTop + amiv_g_nodes[ i ].odsty*ysize,
            xsize, ysize, 0xc0);
    }
    }
    if(imgbm) MyFreeBitMap(imgbm);
    if(bm) MyFreeBitMap(bm);
#endif /* DISPMAP */
#ifdef OPT_DISPMAP
    }
#endif
    amii_end_glyphout(WIN_MAP);
    /* Clean up */
    glyph_node_index = glyph_buffer_index = 0;
}
void amiv_lprint_glyph (winid window, int color_index, int glyph)
Definition at line 677 of file winchar.c.
References PDAT::across, amii_menuBPen, amii_wins, amiv_flush_glyph_buffer(), amiv_g_nodes, amiv_glyph_node::bitmap, amii_WinDesc::cursx, amii_WinDesc::cursy, amii_WinDesc::curx, amii_WinDesc::cury, amiv_glyph_node::dstx, amiv_glyph_node::dsty, flags, FLMAP_CURSUP, glyph_node_index, GlyphToIcon(), ifftimg, min, mxsize, mysize, NHW_MAP, NO_GLYPH, PDAT::nplanes, NULL, NUMBER_GLYPH_NODES, amiv_glyph_node::odstx, amiv_glyph_node::odsty, panic(), pictdata, rp, amiv_glyph_node::srcx, amiv_glyph_node::srcy, TBLMONTILE, TBLOBJTILE, TBLOTHTILE, tile, amii_WinDesc::type, amii_WinDesc::wflags, amii_WinDesc::win, PDAT::xsize, and PDAT::ysize.
{
    int base;
    struct amii_WinDesc *cw;
    struct Window *w;
    int curx;
    int cury;
    int tbl, icon;
    register int xoff, yoff;
    /* Get the real icon index */
    if(glyph != NO_GLYPH)
    icon = GlyphToIcon(glyph);
    if((cw=amii_wins[window]) == (struct amii_WinDesc *)
      NULL)
    panic("bad winid in amiv_lprint_glyph: %d", window);
    w = cw->win;
    if(glyph != NO_GLYPH && glyph < 10000)
    {
    /* decide on which image has the needed picture */
    if(icon <= MAXMONTILE)
    {
        tbl = TBLMONTILE;
        base = 0;
    }
    else if(icon <= MAXOBJTILE)
    {
        tbl = TBLOBJTILE;
        base = MAXMONTILE+1;
    }
    else if(icon <= MAXOTHTILE)
    {
        tbl = TBLOTHTILE;
        base = MAXOBJTILE+1;
    }
    else
        panic("Bad icon #%d, glyph #%d, only %d icons known\n", icon, glyph, MAXOTHTILE);
    /* Get the relative offset in the page */
    /* How many pixels to account for y distance down */
    yoff = ((icon-base) / pictdata.across) * pictdata.
      ysize;
    /* How many pixels to account for x distance across */
    xoff = ((icon-base) % pictdata.across) * pictdata.
      xsize;
    }
    if(glyph >= 10000){
    /* Run a single ASCII character out to the rastport right now */
    char c= glyph-10000;
    int xxx,xxy;
    struct RastPort *rp = w->RPort;
    Move(rp, xxx=(((cw->curx-clipx)*rp->TxWidth) + w->BorderLeft),
      xxy=(w->BorderTop + (((cw->cury-clipy)+1)* rp->TxHeight)+1));
    Text(rp,&c,1);
        /* XXX this shouldn't be necessary: */
    if(cw->cursx == xxx && cw->cursy == xxy){
        cw->wflags &= ~FLMAP_CURSUP;
    }
    cw->curx += rp->TxWidth; /* keep things in sync */
    return;
    }
    
    if(cw->type == NHW_MAP)
    {
    curx = cw->curx - clipx;
    cury = cw->cury - clipy;
    /* See if we're out of glyph nodes */
    if(glyph_node_index >= NUMBER_GLYPH_NODES)
        amiv_flush_glyph_buffer(w);
    /* Fill in the node. */
    amiv_g_nodes[glyph_node_index].dsty = min(w->BorderTop + (cury *
      mysize),
                        w->Height - 1);
#ifdef OPT_DISPMAP
    if(flags.fast_map){
#endif /* keni */
#ifdef DISPMAP
    /* display_map() needs byte-aligned destinations, and we don't want to
     * overwrite the window border.
     */
    amiv_g_nodes[glyph_node_index].dstx =
                (w->BorderLeft + 8 + (curx * mxsize)) & -8;
#endif
#ifdef OPT_DISPMAP
} else {
#endif
#if !defined(DISPMAP) || defined(OPT_DISPMAP)
    amiv_g_nodes[glyph_node_index].dstx = min(w->BorderLeft + (curx *
      mxsize),
                        w->Width - 1);
#endif
#ifdef OPT_DISPMAP
}
#endif
    amiv_g_nodes[glyph_node_index].odsty = cw->
      cury;
    amiv_g_nodes[glyph_node_index].odstx = cw->
      curx;
    amiv_g_nodes[glyph_node_index].srcx = xoff;
    amiv_g_nodes[glyph_node_index].srcy = yoff;
    amiv_g_nodes[glyph_node_index].bitmap =
      ifftimg[ tbl ];
    ++glyph_node_index;
    }
    else
    {
    /* Do it */
    register int j, k, x, y, apen;
    struct RastPort *rp = w->RPort;
    x = rp->cp_x - pictdata.xsize - 3;
#ifdef OPT_DISPMAP
    if(flags.fast_map){
#endif
#ifdef DISPMAP
        x &= -8;
        if(x==0) x = 8;
#endif
#ifdef OPT_DISPMAP
    }
#endif
    y = rp->cp_y - pictdata.ysize + 1;
    if(glyph != NO_GLYPH)
    {
        struct BitMap *bm = ifftimg[ tbl ];
        /* 8 bits per byte */
        xoff /= 8;
        yoff *= bm->BytesPerRow;
        for(j = 0; j < pictdata.nplanes; ++j)
        {
        for(k = 0; k < pictdata.ysize; ++k)
        {
            memcpy(tile->Planes[ j ] + ((k * pictdata.ysize) / 8),
                bm->Planes[ j ] + xoff + yoff + (bm->BytesPerRow * k),
                pictdata.ysize/8);
        }
        }
        BltBitMapRastPort(tile, 0, 0,
        rp, x, y,
        pictdata.xsize, pictdata.ysize, 0xc0);
        apen = rp->FgPen;
        SetAPen(rp, flags.amii_dripens[ SHINEPEN ]);
        Move(rp, x-1, y + pictdata.ysize);
        Draw(rp, x-1, y - 1);
        Draw(rp, x + pictdata.xsize, y - 1);
        SetAPen(rp, flags.amii_dripens[ SHADOWPEN ]);
        Move(rp, x + pictdata.xsize, y);
        Draw(rp, x + pictdata.xsize, y + pictdata.ysize);
        Draw(rp, x, y + pictdata.ysize);
        SetAPen(rp, apen);
    }
    else if(x > w->BorderLeft)
    {
        int apen, bpen;
        apen = rp->FgPen;
        bpen = rp->BgPen;
        SetAPen(rp, amii_menuBPen);
        SetBPen(rp, amii_menuBPen);
        RectFill(rp, x-1, y-1, x + pictdata.xsize, y + pictdata.
      ysize);
        SetAPen(rp, apen);
        SetBPen(rp, bpen);
    }
    }
}
void amiv_start_glyphout (winid window)
Definition at line 863 of file winchar.c.
References amii_wins, FALSE, FLMAP_INGLYPH, iflags, NULL, panic(), amii_WinDesc::wflags, and amii_WinDesc::win.
Referenced by amiv_flush_glyph_buffer().
{
    struct amii_WinDesc *cw;
    struct Window *w;
    if((cw=amii_wins[window]) == (struct amii_WinDesc *)
      NULL)
    panic("bad winid %d in start_glyphout()", window);
    if(cw->wflags & FLMAP_INGLYPH)
    return;
    if(!(w = cw->win))
    panic("bad winid %d, no window ptr set", window);
    /*
     * Save the context of the window
     */
    xsave = w->RPort->cp_x;
    ysave = w->RPort->cp_y;
    modesave = w->RPort->DrawMode;
    apensave = w->RPort->FgPen;
    bpensave = w->RPort->BgPen;
    /*
     * Set the mode, and be done with it
     */
    usecolor = iflags.use_color;
    iflags.use_color = FALSE;
    cw->wflags |= FLMAP_INGLYPH;
}
void flush_glyph_buffer (struct Window * vw)
Definition at line 484 of file winchar.c.
References amii_flush_glyph_buffer(), amiv_flush_glyph_buffer(), and WINVERS_AMIV.
Referenced by amii_cliparound(), amii_curs(), amii_display_nhwindow(), amii_wait_synch(), and EditClipping().
{
    if(WINVERS_AMIV)
    amiv_flush_glyph_buffer (vw);
    else
    amii_flush_glyph_buffer (vw);
}
void FreeImageFiles (char ** filenames, struct BitMap ** img)
Definition at line 453 of file winchar.c.
References ifftimg, MyFreeBitMap(), and tile.
Referenced by FreeTileImageFiles(), and ReadImageFiles().
{
    register int i;
    for(i = 0; filenames[i]; ++i)
    {
    if(img[ i ])
        MyFreeBitMap(img[ i ]);
    }
    /* REALLY ugly hack alert! */
    if(tile && img==ifftimg)
    MyFreeBitMap(tile);
}
void FreeTileImageFiles ()
Definition at line 448 of file winchar.c.
References FreeImageFiles(), ifftimg, and tileimages.
Referenced by amii_exit_nhwindows().
                    {
    FreeImageFiles(tileimages,ifftimg);
}
int GlyphToIcon (int glyph)
Definition at line 937 of file winchar.c.
References glyph2tile.
Referenced by amiv_lprint_glyph().
{
    if(glyph>10000)return glyph;
    return(glyph2tile[glyph]);
}
int main (int , char **)
Definition at line 40 of file cvtsnd.c.
References IFF::_8SVX, alloc(), AmiColorMap::b, basename(), IFF::blen, IFF::BODY, buf, BUFSIZ, xpmscreen::BytesPerRow, chdir(), Close, close(), CM_BLUE, CM_GREEN, CM_RED, ColorMap, xpmscreen::Colors, colorsinmap, COLS, IFF::compress, BitMapHeader::compression, conv_image(), decl_init(), decode(), eos(), error(), exit(), EXIT_FAILURE, EXIT_SUCCESS, FALSE, fatal_error, fclose_text_file(), FCMASK, FILENAME_CMP, IFF::flen, fname, fopen_text_file(), fopen_xpm_file(), IFF::FORM, fp, Fprintf, free(), freopen, IFF::freq, AmiColorMap::g, getcwd(), BitMapHeader::h, xpmscreen::Height, ID_BMAP, ID_BMHD, ID_CAMG, ID_CMAP, ID_PDAT, ID_PLNE, IFFParseBase, IFFScreen, in, index(), infile, init_obj_classes(), init_yyin(), init_yyout(), line_number, lseek(), malloc(), map_colors(), BitMapHeader::masking, monst_init(), AIFF::name, IFF::NAME, IFF::name, AIFF::namelen, x11_header::ncolors, IFF::nlen, nplanes, BitMapHeader::nPlanes, x11_header::ntiles, NULL, O_BINARY, O_CREAT, O_RDONLY, O_RDWR, O_TRUNC, O_WRONLY, objects_init(), IFF::octaves, IFF::oneshot, open(), outfile, OUTNAME, packwritebody(), BitMapHeader::pageHeight, BitMapHeader::pageWidth, x11_header::per_row, perror, planes, PREFIX, printf, process_file(), AmiColorMap::r, read(), read_text_tile(), IFF::repeat, BitMapHeader::reserved1, ROWS, IFF::samples, SCALE, SEEK_END, SEEK_SET, SIZE, Ttable::slot, AIFF::sndlen, stdin, stdout, Strcpy, tile_bytes, x11_header::tile_height, x11_header::tile_width, TILE_X, TILE_Y, TILES_PER_ROW, BitMapHeader::transparentColor, TRUE, ttable, x11_header::version, IFF::VHDR, IFF::vhlen, vms_basename(), IFF::volume, BitMapHeader::w, xpmscreen::Width, WRBMODE, write(), BitMapHeader::x, x11_colormap, BitMapHeader::xAspect, xexit(), XpmScreen, xsize, BitMapHeader::y, BitMapHeader::yAspect, ysize, and yyparse().
Referenced by WinMain().
{
    FILE *in, *out;
    AIFF aiff;
    IFF iff;
    static char buf[16384];
    long n, len;
    if (ac != 3) {
    fprintf(stderr, "Usage: %s input-file output-file\n", av[0]);
    exit(20);
    }
    if (!(in = fopen(av[1], "r"))) {
    fprintf(stderr, "Can't open input file\n");
    exit(20);
    }
    if (!(out = fopen(av[2], "w"))) {
    fprintf(stderr, "Can't open output file\n");
    exit(20);
    }
    fread(&aiff, sizeof(aiff), 1, in);
    memcpy(iff.FORM, "FORM", 4);
    iff.flen = sizeof(iff) + aiff.sndlen - 8;
    memcpy(iff._8SVX, "8SVX", 4);
    memcpy(iff.VHDR, "VHDR", 4);
    iff.vhlen = 20;
    iff.oneshot = aiff.sndlen;
    iff.repeat = 0;
    iff.samples = 32;
    iff.freq = 22000;
    iff.octaves = 1;
    iff.compress= 0;
    iff.volume = 0x10000;
    memcpy(iff.NAME, "NAME", 4);
    iff.nlen = 64;
    strncpy(iff.name, aiff.name, 62); iff.name[aiff.namelen] = 0;
    memcpy(iff.BODY, "BODY", 4);
    iff.blen = aiff.sndlen;
    fwrite(&iff, sizeof(iff), 1, out);
    len = aiff.sndlen;
    do {
    if (len >= sizeof(buf))
        n = fread(buf, 1, sizeof(buf), in);
    else
        n = fread(buf, 1, len, in);
    if (n) {
        fwrite(buf, 1, n, out);
        len -= n;
    }
    } while (len && n);
    if (len)
    fprintf(stderr, "Warning: %ld bytes of sample missing\n", len);
    fclose(in); fclose(out);
    exit(0);
}
struct BitMap * MyAllocBitMap (int xsize, int ysize, int depth, long mflags)
Definition at line 382 of file winchar.c.
References alloc(), MyBitMap::bm, MyFreeBitMap(), NULL, xsize, MyBitMap::xsize, ysize, and MyBitMap::ysize.
Referenced by amiv_flush_glyph_buffer(), and ReadImageFiles().
{
    int j;
    struct MyBitMap *bm;
    bm = (struct MyBitMap *)alloc(sizeof(*bm));
    if(!bm)
    return(NULL);
    bm->xsize = xsize;
    bm->ysize = ysize;
    InitBitMap(&bm->bm, depth, xsize, ysize);
    for(j = 0; j < depth; ++j)
    {
    if(mflags & MEMF_CHIP)
        bm->bm.Planes[ j ] = AllocRaster(xsize, ysize);
    else
        bm->bm.Planes[ j ] = AllocMem(RASSIZE(xsize, ysize),
      mflags);
    if(bm->bm.Planes[ j ] == 0)
    {
        MyFreeBitMap(&bm->bm);
        return(NULL);
    }
    if(mflags & MEMF_CLEAR)
        memset(bm->bm.Planes[ j ], 0, RASSIZE(xsize, ysize));
    }
    return(&bm->bm);
}
void MyFreeBitMap (struct BitMap * bmp)
Definition at line 413 of file winchar.c.
References MyBitMap::bm, free(), MyBitMap::mflags, MyBitMap::xsize, and MyBitMap::ysize.
Referenced by amiv_flush_glyph_buffer(), FreeImageFiles(), and MyAllocBitMap().
{
    int j;
    struct MyBitMap *bm = (struct MyBitMap *)bmp;
    for(j = 0; j < bm->bm.Depth; ++j)
    {
    if(bm->bm.Planes[j])
    {
        if(bm->mflags & MEMF_CHIP)
        FreeRaster(bm->bm.Planes[j], bm->xsize, bm->ysize);
        else
        FreeMem(bm->bm.Planes[j], RASSIZE(bm->xsize, bm->ysize));
    }
    }
    free(bm);
}
BitMapHeader ReadImageFiles (char ** filenames, struct BitMap ** iffimg, char ** errstrp)
Definition at line 205 of file winchar.c.
References amii_extraplanes, amii_initmap, amiv_init_map, buf, Close, cmap, errno, FreeImageFiles(), BitMapHeader::h, ID_BMAP, ID_BMHD, ID_CAMG, ID_CMAP, ID_PDAT, ID_PLNE, IFFParseBase, malloc(), MyAllocBitMap(), BitMapHeader::nPlanes, PDAT::nplanes, NULL, pictdata, tile, BitMapHeader::w, PDAT::xsize, and PDAT::ysize.
Referenced by ReadTileImageFiles().
{
    BitMapHeader *bmhd = NULL, bmhds;
    unsigned char *cmap;
    extern int errno;
    register int i, j;
    struct IFFHandle *iff;
    struct StoredProperty *prop;
    IFFParseBase = OpenLibrary("iffparse.library", 0L);
    if(!IFFParseBase)
    {
    *errstrp = "No iffparse.library";
    return bmhds;
    }
/*
    for(i = 0; filenames[i]; ++i)
    memset(iffimg[i], 0, sizeof(struct BitMap));
*/
    for(i = 0; filenames[i]; ++i)
    {
    iff = AllocIFF();
    if(!iff)
    {
        FreeImageFiles(filenames, iffimg);
        *errstrp = "can't start IFF processing";
        return bmhds;
    }
    iff->iff_Stream = Open(filenames[i], MODE_OLDFILE);
    if(iff->iff_Stream == 0)
    {
        char *buf = malloc(100+strlen(filenames[i]));
        FreeImageFiles(filenames, iffimg);
        sprintf(buf, "Can't open %s: %s", filenames[i], strerror(errno));
        *errstrp = buf;
        return bmhds;
    }
    InitIFFasDOS(iff);
    OpenIFF(iff, IFFF_READ);
    PropChunk(iff, ID_BMAP, ID_BMHD);
    PropChunk(iff, ID_BMAP, ID_CMAP);
    PropChunk(iff, ID_BMAP, ID_CAMG);
    PropChunk(iff, ID_BMAP, ID_PDAT);
    StopChunk(iff, ID_BMAP, ID_PLNE);
    if((j = ParseIFF(iff, IFFPARSE_SCAN)) != 0)
    {
        char *buf = malloc(100);
        FreeImageFiles(filenames, iffimg);
        sprintf(buf,"ParseIFF failed for image %d, failure code: %d",i,j);
        *errstrp = buf;
        return bmhds;
    }
    if(prop = FindProp(iff, ID_BMAP, ID_BMHD))
    {
        bmhd = (BitMapHeader *)prop->sp_Data;
    }
    else
    {
        FreeImageFiles(filenames, iffimg);
        CloseIFF(iff);
        Close(iff->iff_Stream);
        FreeIFF(iff);
        *errstrp = "No BMHD CHUNK in file";
        return bmhds;
    }
    if(prop = FindProp(iff, ID_BMAP, ID_CMAP))
    {
        cmap = prop->sp_Data;
        for(j = 0; j < (1L << bmhd->nPlanes)*3; j+=3)
        {
#if 0
        /* Some day we will want to use the larger palette
         * resolution available under v39 and later. i.e.
         * 32 instead of 12 bits of color. Ususally this
         * just means shifting the color left by 16-20 bits
         * depending on what intensity looks best. Experience
         * says that the higher values are better intensities.
         *
         * For now though we won't do this. The color table
         * structure is incompatible with earlier versions of
         * intuition. We would have to do some funny things
         * to make 3*AMII_MAXCOLORS longs work like 3*AMII_MAXCOLORS
         * UWORD's at run time... A union would help, but...
         */
        if(IntuitionBase->LibNode.lib_Version >= 39)
        {
            /* 8 bits of color, so shift to left end. */
            amiv_init_map[ j+0 ] = cmap[j+0]<<24;
            amiv_init_map[ j+1 ] = cmap[j+1]<<24;
            amiv_init_map[ j+2 ] = cmap[j+2]<<24;
        }
        else
#endif
        {
            /* We can only use 4 bits of the 8 that are stored in the
             * cmap, so mask them and then shift them into position
             * for the UWORD value to store.
             */
#ifndef TESTING
            amii_initmap[ j/3 ] =
            amiv_init_map[ j/3 ] =
                    ((cmap[j+0]>>4)<<8)|
                    ((cmap[j+1]>>4)<<4)|
                    (cmap[j+2]>>4);
#endif
        }
        }
    }
    else
    {
        FreeImageFiles(filenames, iffimg);
        CloseIFF(iff);
        Close(iff->iff_Stream);
        FreeIFF(iff);
        *errstrp = "No CMAP CHUNK in file";
        return bmhds;
    }
    if(prop = FindProp(iff, ID_BMAP, ID_PDAT))
    {
        struct PDAT *pp;
        pp = (struct PDAT *)prop->sp_Data;
        pictdata = *pp;
    }
    else
    {
        FreeImageFiles(filenames, iffimg);
        CloseIFF(iff);
        Close(iff->iff_Stream);
        FreeIFF(iff);
        *errstrp = "No PDAT CHUNK in file";
        return bmhds;
    }
    iffimg[ i ] = MyAllocBitMap(bmhd->w, bmhd->h,
        pictdata.nplanes + amii_extraplanes, MEMF_CHIP|MEMF_CLEAR);
    if(iffimg[ i ] == NULL)
    {
        char *buf = malloc(80);
        FreeImageFiles(filenames, iffimg);
        sprintf(buf, "Can't allocate bitmap for image %d\n", i);
        *errstrp = buf;
        return bmhds;
    }
    for(j = 0; j < pictdata.nplanes + amii_extraplanes; ++j)
    {
        ReadChunkBytes(iff, iffimg[i]->Planes[j], RASSIZE(bmhd->w, bmhd->h));
    }
    bmhds = *bmhd;
    CloseIFF(iff);
    Close(iff->iff_Stream);
    FreeIFF(iff);
    }
    CloseLibrary(IFFParseBase);
    tile = MyAllocBitMap(pictdata.xsize, pictdata.
      ysize,
        pictdata.nplanes + amii_extraplanes, MEMF_CHIP|MEMF_CLEAR);
    if(tile == NULL)
    {
    FreeImageFiles(filenames, iffimg);
    *errstrp = "Can't allocate tile bitmap for scaling";
    }
    return(bmhds);
}
BitMapHeader ReadTileImageFiles (void)
Definition at line 195 of file winchar.c.
References ifftimg, NULL, panic(), ReadImageFiles(), and tileimages.
Referenced by amii_init_nhwindows().
                    {
    char *errstr = NULL;
    BitMapHeader ret = ReadImageFiles(tileimages,
      ifftimg, &errstr);
    if(errstr){
    panic(errstr);
    }
    return ret;
}
void SetMazeType (MazeType t)
Definition at line 932 of file winchar.c.
References maze_type.
{
    maze_type=t;
}
Variable Documentation
int amii_extraplanes = 0
Definition at line 46 of file winchar.c.
Referenced by amiv_flush_glyph_buffer(), and ReadImageFiles().
struct amiv_glyph_node amiv_g_nodes[NUMBER_GLYPH_NODES]
Definition at line 480 of file winchar.c.
Referenced by amiv_flush_glyph_buffer(), and amiv_lprint_glyph().
char amiv_glyph_buffer[GLYPH_BUFFER_SIZE] [static]
Definition at line 481 of file winchar.c.
long apensave [static]
Definition at line 854 of file winchar.c.
long bpensave [static]
Definition at line 854 of file winchar.c.
unsigned short glyph_buffer_index
Definition at line 472 of file winchar.c.
unsigned short glyph_node_index
Definition at line 472 of file winchar.c.
Referenced by amiv_flush_glyph_buffer(), and amiv_lprint_glyph().
struct BitMap* ifftimg[NUMTILEIMAGES]
Definition at line 89 of file winchar.c.
Referenced by amiv_lprint_glyph(), FreeImageFiles(), FreeTileImageFiles(), and ReadTileImageFiles().
maze_type =COL_MAZE_BRICK [static]
Definition at line 930 of file winchar.c.
Referenced by SetMazeType().
long modesave [static]
Definition at line 854 of file winchar.c.
struct PDAT pictdata
Definition at line 75 of file winchar.c.
Referenced by amii_curs(), amiv_flush_glyph_buffer(), amiv_lprint_glyph(), CountLines(), DisplayData(), DoMenuScroll(), FindLine(), and ReadImageFiles().
int reclip
Referenced by amii_clear_nhwindow(), amii_cliparound(), amiv_flush_glyph_buffer(), and EditClipping().
struct BitMap * tile
Definition at line 89 of file winchar.c.
Referenced by amiv_flush_glyph_buffer(), amiv_lprint_glyph(), convert_tiles(), FreeImageFiles(), ghack_image_from_glyph(), map_update(), packwritebody(), and ReadImageFiles().
char* tileimages[]
Initial value:
=
{
#define TBLMONTILE
    "NetHack:tiles/monsters.iff",
#define TBLOBJTILE
    "NetHack:tiles/objects.iff",
#define TBLOTHTILE
    "NetHack:tiles/other.iff",
    0,
}
Definition at line 78 of file winchar.c.
Referenced by FreeTileImageFiles(), and ReadTileImageFiles().
int usecolor [static]
Definition at line 855 of file winchar.c.
Referenced by amii_end_glyphout().
long xsave [static]
Definition at line 854 of file winchar.c.
long ysave [static]
Definition at line 854 of file winchar.c.