nethack/sys/amiga/winkey.c File Reference
#include `NH:sys/amiga/windefs.h`
*
#include `NH:sys/amiga/winext.h`
*
#include `NH:sys/amiga/winproto.h`
*
Functions
amii_nh_poskey (int *x, int *y, int *mod)
int amii_nhgetch ()
void amii_get_nh_event ()
void amii_getret ()
Function Documentation
void amii_get_nh_event (void)
Definition at line 82 of file winkey.c.
{
    /* nothing now - later I have no idea. Is this just a Mac hook? */
}
void amii_getret (void)
Definition at line 88 of file winkey.c.
References HackPort, raw_print, and WindowGetchar().
Referenced by Abort().
{
    register int c;
    raw_print("");
    raw_print("Press Return...");
    c = 0;
    while(c != '\n' && c != '\r')
    {
    if(HackPort)
        c = WindowGetchar();
    else
        c = getchar();
    }
    return;
}
amii_nh_poskey (int* x, int * y, int * mod)
Definition at line 9 of file winkey.c.
References amii_wins, CLICK_1, cursor_on(), amii_WinDesc::disprows, FLMAP_SKIP, FLMSG_FIRST, WEVENT::key, lastevent, MAPFTBASELN, WEVENT::mouse, mxsize, mysize, panic(), rp, scrollmsg, WEVENT::type, type, WEVENT::un, WEKEY, WEMOUSE, WEUNK, amii_WinDesc::wflags, amii_WinDesc::win, WIN_ERR, WIN_MAP, WIN_MESSAGE, and WindowGetevent().
{
    struct amii_WinDesc *cw;
    WETYPE type;
    struct RastPort *rp;
    struct Window *w;
    if(cw = amii_wins[WIN_MESSAGE])
    {
    cw->wflags &= ~FLMAP_SKIP;
    if(scrollmsg)
        cw->wflags |= FLMSG_FIRST;
    cw->disprows = 0;
    }
    if(WIN_MAP != WIN_ERR && (cw = amii_wins[ WIN_MAP ]) && (w = cw->
      win))
    {
    cursor_on(WIN_MAP);
    }
    else
    panic("no MAP window opened for nh_poskey\n");
    rp = w->RPort;
    while(1)
    {
    type = WindowGetevent();
    if(type == WEMOUSE)
    {
        *mod = CLICK_1;
        if(lastevent.un.mouse.qual)
        *mod = 0;
        /* X coordinates are 1 based, Y are 1 based. */
        *x = ((lastevent.un.mouse.x - w->BorderLeft) / mxsize) + 1;
        *y = ((lastevent.un.mouse.y - w->BorderTop -
      MAPFTBASELN) /
            mysize) + 1;
#ifdef CLIPPING
        if(clipping)
        {
        *x += clipx;
        *y += clipy;
        }
#endif
        return(0);
    }
    else if(type == WEKEY)
    {
        lastevent.type = WEUNK;
        return(lastevent.un.key);
    }
    }
}
int amii_nhgetch (void)
Definition at line 65 of file winkey.c.
References amii_wins, cursor_on(), FLMAP_SKIP, amii_WinDesc::wflags, WIN_ERR, WIN_MAP, WIN_MESSAGE, and WindowGetchar().
{
    int ch;
    struct amii_WinDesc *cw=amii_wins[WIN_MESSAGE];
    if(WIN_MAP != WIN_ERR && amii_wins[ WIN_MAP ])
    {
    cursor_on(WIN_MAP);
    }
    if(cw)
    cw->wflags &= ~FLMAP_SKIP;
    ch = WindowGetchar();
    return(ch);
}