nethack/win/X11/winmisc.c File Reference
#include <X11/Intrinsic.h>
*
#include <X11/StringDefs.h>
*
#include <X11/Shell.h>
*
#include <X11/Xaw/Command.h>
*
#include <X11/Xaw/Form.h>
*
#include <X11/Xaw/Label.h>
*
#include <X11/Xaw/Cardinals.h>
*
#include <X11/Xos.h>
*
#include <X11/Xatom.h>
*
#include `hack.h`
*
#include `func_tab.h`
*
#include `winX.h`
*
Macros
#define PRESERVE_NO_SYSV /* X11 include files may define SYSV */
#define PS_RANDOM (-50)
#define PS_QUIT (-75)
#define EC_NCHARS 32
Functions
static void FDECL (popup_delete,(Widget, XEvent *, String *, Cardinal *))
static void NDECL (ec_dismiss)
static Widget FDECL (make_menu,(const char *, const char *, const char *, const char *, XtCallbackProc, const char *, XtCallbackProc, int, const char **, Widget **, XtCallbackProc, Widget *))
static void NDECL (init_extended_commands_popup)
static void FDECL (ps_quit,(Widget, XtPointer, XtPointer))
static void FDECL (ps_random,(Widget, XtPointer, XtPointer))
static void FDECL (ps_select,(Widget, XtPointer, XtPointer))
static void ps_quit (Widget w, XtPointer client_data, XtPointer call_data)
static void ps_random (Widget w, XtPointer client_data, XtPointer call_data)
static void ps_select (Widget w, XtPointer client_data, XtPointer call_data)
void ps_key (Widget w, XEvent *event, String *params, Cardinal *num_params)
void race_key (Widget w, XEvent *event, String *params, Cardinal *num_params)
void gend_key (Widget w, XEvent *event, String *params, Cardinal *num_params)
void algn_key (Widget w, XEvent *event, String *params, Cardinal *num_params)
void X11_player_selection ()
int X11_get_ext_cmd ()
static void extend_select (Widget w, XtPointer client_data, XtPointer call_data)
static void extend_dismiss (Widget w, XtPointer client_data, XtPointer call_data)
static void extend_help (Widget w, XtPointer client_data, XtPointer call_data)
void ec_delete (Widget w, XEvent *event, String *params, Cardinal *num_params)
static void popup_delete (Widget w, XEvent *event, String *params, Cardinal *num_params)
static void ec_dismiss ()
void ec_key (Widget w, XEvent *event, String *params, Cardinal *num_params)
static void init_extended_commands_popup ()
static Widget make_menu (char *popup_name, const char *popup_label, const char *popup_translations, const char *left_name, XtCallbackProc left_callback, const char *right_name, XtCallbackProc right_callback, int num_names, const char **widget_names, Widget **command_widgets, XtCallbackProc name_callback, Widget *formp) const
Variables
static Widget extended_command_popup = 0
static Widget extended_command_form
static Widget * extended_commands = 0
static int extended_command_selected
static int ps_selected
static const char ps_randchars [] = `*@`
static const char ps_quitchars [] = `\033qQ`
static boolean ec_active = FALSE
static int ec_nchars = 0
static char ec_chars [EC_NCHARS]
static Time ec_time
static const char extended_command_translations []
static const char player_select_translations []
static const char race_select_translations []
static const char gend_select_translations []
static const char algn_select_translations []
Macro Definition Documentation
#define EC_NCHARS 32
Definition at line 47 of file winmisc.c.
Referenced by ec_key().
#define PRESERVE_NO_SYSV /* X11 include files may define SYSV */
Definition at line 12 of file winmisc.c.
#define PS_QUIT (-75)
Definition at line 43 of file winmisc.c.
Referenced by algn_key(), gend_key(), popup_delete(), ps_key(), ps_quit(), race_key(), and X11_player_selection().
#define PS_RANDOM (-50)
Definition at line 42 of file winmisc.c.
Referenced by algn_key(), gend_key(), ps_key(), ps_random(), race_key(), and X11_player_selection().
Function Documentation
void algn_key (Widget w, XEvent * event, String * params, Cardinal * num_params)
Definition at line 231 of file winmisc.c.
References exit_x_event, index(), key_event_to_char(), PS_QUIT, ps_quitchars, ps_randchars, PS_RANDOM, ps_selected, TRUE, and X11_nhbell().
{
    char ch, *mark;
    static char algnchars[] = "LNC";
    ch = key_event_to_char((XKeyEvent *) event);
    if (ch == '\0') { /* don't accept nul char/modifier event */
    /* don't beep */
    return;
    }
    mark = index(algnchars, ch);
    if (!mark) mark = index(algnchars, highc(ch));
    if (!mark) {
    if (index(ps_randchars, ch))
        ps_selected = PS_RANDOM;
    else if (index(ps_quitchars, ch))
        ps_selected = PS_QUIT;
    else {
        X11_nhbell(); /* no such alignment */
        return;
    }
    } else
    ps_selected = (int)(mark - algnchars);
    exit_x_event = TRUE;
}
void ec_delete (Widget w, XEvent * event, String * params, Cardinal * num_params)
Definition at line 604 of file winmisc.c.
References ec_dismiss(), extended_command_popup, and popup_delete().
{
    if (w == extended_command_popup) {
    ec_dismiss();
    } else {
    popup_delete(w, event, params, num_params);
    }
}
static void ec_dismiss () [static]
Definition at line 631 of file winmisc.c.
References ec_active, exit_x_event, extended_command_popup, extended_command_selected, extended_commands, FALSE, nh_XtPopdown(), swap_fg_bg(), and TRUE.
Referenced by ec_delete(), and extend_dismiss().
{
    /* unselect while still visible */
    if (extended_command_selected >= 0)
    swap_fg_bg(extended_commands[
      extended_command_selected]);
    extended_command_selected = -1; /* dismiss */
    nh_XtPopdown(extended_command_popup);
    ec_active = FALSE;
    exit_x_event = TRUE; /* leave event loop */
}
void ec_key (Widget w, XEvent * event, String * params, Cardinal * num_params)
Definition at line 644 of file winmisc.c.
References ec_active, ec_chars, EC_NCHARS, ec_nchars, ec_time, ext_func_tab::ef_txt, exit_x_event, extcmdlist, extended_command_popup, extended_command_selected, extended_commands, FALSE, index(), key_event_to_char(), nh_XtPopdown(), swap_fg_bg(), and TRUE.
{
    char ch;
    int i;
    XKeyEvent *xkey = (XKeyEvent *) event;
    ch = key_event_to_char(xkey);
    if (ch == '\0') { /* don't accept nul char/modifier event */
    /* don't beep */
    return;
    } else if (index("\033\n\r", ch)) {
    if (ch == '\033') {
        /* unselect while still visible */
        if (extended_command_selected >= 0)
        swap_fg_bg(extended_commands[
      extended_command_selected]);
        extended_command_selected = -1; /* dismiss */
    }
    nh_XtPopdown(extended_command_popup);
    /* unselect while invisible */
    if (extended_command_selected >= 0)
        swap_fg_bg(extended_commands[
      extended_command_selected]);
    exit_x_event = TRUE; /* leave event loop */
    ec_active = FALSE;
    return;
    }
    /* too much time has elapsed */
    if ((xkey->time - ec_time) > 500)
    ec_active = FALSE;
    if (!ec_active) {
    ec_nchars = 0;
    ec_active = TRUE;
    }
    ec_time = xkey->time;
    ec_chars[ec_nchars++] = ch;
    if (ec_nchars >= EC_NCHARS)
    ec_nchars = EC_NCHARS-1; /* don't overflow */
    for (i = 0; extcmdlist[i].ef_txt; i++) {
    if (extcmdlist[i].ef_txt[0] == '?') continue;
    if (!strncmp(ec_chars, extcmdlist[i].ef_txt, ec_nchars)) {
        if (extended_command_selected != i) {
        /* I should use set() and unset() actions, but how do */
        /* I send the an action to the widget? */
        if (extended_command_selected >= 0)
            swap_fg_bg(extended_commands[
      extended_command_selected]);
        extended_command_selected = i;
        swap_fg_bg(extended_commands[
      extended_command_selected]);
        }
        break;
    }
    }
}
static void extend_dismiss (Widget w, XtPointer client_data, XtPointer call_data) [static]
Definition at line 585 of file winmisc.c.
References ec_dismiss().
Referenced by init_extended_commands_popup().
{
    ec_dismiss();
}
static void extend_help (Widget w, XtPointer client_data, XtPointer call_data) [static]
Definition at line 594 of file winmisc.c.
Referenced by init_extended_commands_popup().
{
    /* We might need to make it known that we already have one listed. */
    (void) doextlist();
}
static void extend_select (Widget w, XtPointer client_data, XtPointer call_data) [static]
Definition at line 560 of file winmisc.c.
References ec_active, exit_x_event, extended_command_popup, extended_command_selected, extended_commands, FALSE, nh_XtPopdown(), swap_fg_bg(), and TRUE.
Referenced by init_extended_commands_popup().
{
    int selected = (int) client_data;
    if (extended_command_selected != selected) {
    /* visibly deselect old one */
    if (extended_command_selected >= 0)
        swap_fg_bg(extended_commands[
      extended_command_selected]);
    /* select new one */
    swap_fg_bg(extended_commands[selected]);
    extended_command_selected = selected;
    }
    nh_XtPopdown(extended_command_popup);
    /* reset colors while popped down */
    swap_fg_bg(extended_commands[
      extended_command_selected]);
    ec_active = FALSE;
    exit_x_event = TRUE; /* leave event loop */
}
static void FDECL (popup_delete , (Widget, XEvent *, String *, Cardinal *)) [static]
static Widget FDECL (make_menu , (const char *, const char *, const char *, const char *, XtCallbackProc, const char *, XtCallbackProc, int, const char **, Widget **, XtCallbackProc, Widget *)) [static]
static void FDECL (ps_quit , (Widget, XtPointer, XtPointer)) [static]
static void FDECL (ps_random , (Widget, XtPointer, XtPointer)) [static]
static void FDECL (ps_select , (Widget, XtPointer, XtPointer)) [static]
void gend_key (Widget w, XEvent * event, String * params, Cardinal * num_params)
Definition at line 199 of file winmisc.c.
References exit_x_event, index(), key_event_to_char(), lowc(), PS_QUIT, ps_quitchars, ps_randchars, PS_RANDOM, ps_selected, TRUE, and X11_nhbell().
{
    char ch, *mark;
    static char gendchars[] = "mf";
    ch = key_event_to_char((XKeyEvent *) event);
    if (ch == '\0') { /* don't accept nul char/modifier event */
    /* don't beep */
    return;
    }
    mark = index(gendchars, ch);
    if (!mark) mark = index(gendchars, lowc(ch));
    if (!mark) {
    if (index(ps_randchars, ch))
        ps_selected = PS_RANDOM;
    else if (index(ps_quitchars, ch))
        ps_selected = PS_QUIT;
    else {
        X11_nhbell(); /* no such gender */
        return;
    }
    } else
    ps_selected = (int)(mark - gendchars);
    exit_x_event = TRUE;
}
static void init_extended_commands_popup () [static]
Definition at line 713 of file winmisc.c.
References alloc(), ext_func_tab::ef_txt, extcmdlist, extend_dismiss(), extend_help(), extend_select(), extended_command_form, extended_command_popup, extended_command_translations, extended_commands, free(), and make_menu().
Referenced by X11_get_ext_cmd().
{
    int i, num_commands;
    const char **command_list;
    /* count commands */
    for (num_commands = 0; extcmdlist[num_commands].ef_txt; num_commands++)
    ; /* do nothing */
    /* If the last entry is "help", don't use it. */
    if (strcmp(extcmdlist[num_commands-1].ef_txt, "?") == 0)
    --num_commands;
    command_list =
        (const char **) alloc((unsigned)num_commands * sizeof(char *));
    for (i = 0; i < num_commands; i++)
    command_list[i] = extcmdlist[i].ef_txt;
    extended_command_popup = make_menu("extended_commands",
                "Extended Commands",
                extended_command_translations,
                "dismiss", extend_dismiss,
                "help", extend_help,
                num_commands, command_list, &extended_commands,
                extend_select, &extended_command_form);
    free((char *)command_list);
}
static Widget make_menu (char	   * popup_name, const char	   * popup_label, const char	   * popup_translations, const char	   * left_name, XtCallbackProc left_callback, const char	   * right_name, XtCallbackProc right_callback, int num_names, const char	   ** widget_names, Widget	   ** command_widgets, XtCallbackProc name_callback, Widget	   * formp) const [static]
Definition at line 765 of file winmisc.c.
References alloc(), free(), xwindow::popup, toplevel, width, and wm_delete_window.
Referenced by init_extended_commands_popup(), and X11_player_selection().
{
    Widget popup, form, label, above, left, right;
    Widget *commands, *curr;
    int i;
    Arg args[8];
    Cardinal num_args;
    Dimension width, max_width;
    int distance, skip;
    commands = (Widget *) alloc((unsigned)num_names * sizeof(Widget));
    num_args = 0;
    XtSetArg(args[num_args], XtNallowShellResize, True); num_args++;
    popup = XtCreatePopupShell(popup_name,
                transientShellWidgetClass,
                toplevel, args, num_args);
    XtOverrideTranslations(popup,
    XtParseTranslationTable("<Message>WM_PROTOCOLS: ec_delete()"));
    num_args = 0;
    XtSetArg(args[num_args], XtNtranslations,
        XtParseTranslationTable(popup_translations)); num_args++;
    *formp = form = XtCreateManagedWidget("menuform",
                formWidgetClass,
                popup,
                args, num_args);
    /* Get the default distance between objects in the form widget. */
    num_args = 0;
    XtSetArg(args[num_args], XtNdefaultDistance, &distance); num_args++;
    XtGetValues(form, args, num_args);
    /*
     * Create the label.
     */
    num_args = 0;
    XtSetArg(args[num_args], XtNborderWidth, 0); num_args++;
    label = XtCreateManagedWidget(popup_label,
                labelWidgetClass,
                form,
                args, num_args);
    /*
     * Create the left button.
     */
    num_args = 0;
    XtSetArg(args[num_args], XtNfromVert, label); num_args++;
/*
    XtSetArg(args[num_args], XtNshapeStyle,
                XmuShapeRoundedRectangle); num_args++;
*/
    left = XtCreateManagedWidget(left_name,
            commandWidgetClass,
            form,
            args, num_args);
    XtAddCallback(left, XtNcallback, left_callback, (XtPointer) 0);
    skip = 3*distance; /* triple the spacing */
    if(!skip) skip = 3;
    /*
     * Create right button.
     */
    num_args = 0;
    XtSetArg(args[num_args], XtNfromHoriz, left); num_args++;
    XtSetArg(args[num_args], XtNfromVert, label); num_args++;
/*
    XtSetArg(args[num_args], XtNshapeStyle,
                XmuShapeRoundedRectangle); num_args++;
*/
    right = XtCreateManagedWidget(right_name,
            commandWidgetClass,
            form,
            args, num_args);
    XtAddCallback(right, XtNcallback, right_callback, (XtPointer) 0);
    XtInstallAccelerators(form, left);
    XtInstallAccelerators(form, right);
    /*
     * Create and place the command widgets.
     */
    for (i = 0, above = left, curr = commands; i < num_names; i++) {
    if (!widget_names[i]) continue;
    num_args = 0;
    XtSetArg(args[num_args], XtNfromVert, above); num_args++;
    if (above == left) {
        /* if first, we are farther apart */
        XtSetArg(args[num_args], XtNvertDistance, skip); num_args++;
    }
    *curr = XtCreateManagedWidget(widget_names[i],
            commandWidgetClass,
            form,
            args, num_args);
    XtAddCallback(*curr, XtNcallback, name_callback, (XtPointer) i);
    above = *curr++;
    }
    /*
     * Now find the largest width. Start with the width dismiss + help
     * buttons, since they are adjacent.
     */
    XtSetArg(args[0], XtNwidth, &max_width);
    XtGetValues(left, args, ONE);
    XtSetArg(args[0], XtNwidth, &width);
    XtGetValues(right, args, ONE);
    max_width = max_width + width + distance;
    /* Next, the title. */
    XtSetArg(args[0], XtNwidth, &width);
    XtGetValues(label, args, ONE);
    if (width > max_width) max_width = width;
    /* Finally, the commands. */
    for (i = 0, curr = commands; i < num_names; i++) {
    if (!widget_names[i]) continue;
    XtSetArg(args[0], XtNwidth, &width);
    XtGetValues(*curr, args, ONE);
    if (width > max_width) max_width = width;
    curr++;
    }
    /*
     * Finally, set all of the single line widgets to the largest width.
     */
    XtSetArg(args[0], XtNwidth, max_width);
    XtSetValues(label, args, ONE);
    for (i = 0, curr = commands; i < num_names; i++) {
    if (!widget_names[i]) continue;
    XtSetArg(args[0], XtNwidth, max_width);
    XtSetValues(*curr, args, ONE);
    curr++;
    }
    if (command_widgets)
    *command_widgets = commands;
    else
    free((char *) commands);
    XtRealizeWidget(popup);
    XSetWMProtocols(XtDisplay(popup), XtWindow(popup), &wm_delete_window, 1);
    return popup;
}
static void NDECL (ec_dismiss) [static]
static void NDECL (init_extended_commands_popup) [static]
static void popup_delete (Widget w, XEvent * event, String * params, Cardinal * num_params) [static]
Definition at line 619 of file winmisc.c.
References exit_x_event, nh_XtPopdown(), PS_QUIT, ps_selected, and TRUE.
Referenced by ec_delete().
{
    ps_selected = PS_QUIT;
    nh_XtPopdown(w);
    exit_x_event = TRUE; /* leave event loop */
}
void ps_key (Widget w, XEvent * event, String * params, Cardinal * num_params)
Definition at line 116 of file winmisc.c.
References exit_x_event, index(), key_event_to_char(), lowc(), RoleName::m, Role::name, name, PS_QUIT, ps_quitchars, ps_randchars, PS_RANDOM, ps_selected, QBUFSZ, roles, TRUE, and X11_nhbell().
{
    char ch, *mark;
    char rolechars[QBUFSZ];
    int i;
    (void)memset(rolechars, '\0', sizeof rolechars); /* for index() */
    for (i = 0; roles[i].name.m; ++i) {
    ch = lowc(*roles[i].name.m);
     /* if (flags.female && roles[i].name.f) ch = lowc(*roles[i].name.f); */
    /* this supports at most two roles with the same first letter */
    if (index(rolechars, ch)) ch = highc(ch);
    rolechars[i] = ch;
    }
    ch = key_event_to_char((XKeyEvent *) event);
    if (ch == '\0') { /* don't accept nul char/modifier event */
    /* don't beep */
    return;
    }
    mark = index(rolechars, ch);
    if (!mark) mark = index(rolechars, lowc(ch));
    if (!mark) mark = index(rolechars, highc(ch));
    if (!mark) {
    if (index(ps_randchars, ch))
        ps_selected = PS_RANDOM;
    else if (index(ps_quitchars, ch))
        ps_selected = PS_QUIT;
    else {
        X11_nhbell(); /* no such class */
        return;
    }
    } else
    ps_selected = (int)(mark - rolechars);
    exit_x_event = TRUE;
}
static void ps_quit (Widget w, XtPointer client_data, XtPointer call_data) [static]
Definition at line 86 of file winmisc.c.
References exit_x_event, PS_QUIT, ps_selected, and TRUE.
Referenced by X11_player_selection().
{
    ps_selected = PS_QUIT;
    exit_x_event = TRUE; /* leave event loop */
}
static void ps_random (Widget w, XtPointer client_data, XtPointer call_data) [static]
Definition at line 96 of file winmisc.c.
References exit_x_event, PS_RANDOM, ps_selected, and TRUE.
Referenced by X11_player_selection().
{
    ps_selected = PS_RANDOM;
    exit_x_event = TRUE; /* leave event loop */
}
static void ps_select (Widget w, XtPointer client_data, XtPointer call_data) [static]
Definition at line 106 of file winmisc.c.
References exit_x_event, ps_selected, and TRUE.
Referenced by X11_player_selection().
{
    ps_selected = (int) client_data;
    exit_x_event = TRUE; /* leave event loop */
}
void race_key (Widget w, XEvent * event, String * params, Cardinal * num_params)
Definition at line 158 of file winmisc.c.
References exit_x_event, index(), key_event_to_char(), lowc(), Race::noun, PS_QUIT, ps_quitchars, ps_randchars, PS_RANDOM, ps_selected, QBUFSZ, races, TRUE, and X11_nhbell().
{
    char ch, *mark;
    char racechars[QBUFSZ];
    int i;
    (void)memset(racechars, '\0', sizeof racechars); /* for index() */
    for (i = 0; races[i].noun; ++i) {
    ch = lowc(*races[i].noun);
    /* this supports at most two races with the same first letter */
    if (index(racechars, ch)) ch = highc(ch);
    racechars[i] = ch;
    }
    ch = key_event_to_char((XKeyEvent *) event);
    if (ch == '\0') { /* don't accept nul char/modifier event */
    /* don't beep */
    return;
    }
    mark = index(racechars, ch);
    if (!mark) mark = index(racechars, lowc(ch));
    if (!mark) mark = index(racechars, highc(ch));
    if (!mark) {
    if (index(ps_randchars, ch))
        ps_selected = PS_RANDOM;
    else if (index(ps_quitchars, ch))
        ps_selected = PS_QUIT;
    else {
        X11_nhbell(); /* no such race */
        return;
    }
    } else
    ps_selected = (int)(mark - racechars);
    exit_x_event = TRUE;
}
int X11_get_ext_cmd ()
Definition at line 534 of file winmisc.c.
References EXIT_ON_EXIT, extended_command_form, extended_command_popup, extended_command_selected, FALSE, init_extended_commands_popup(), nh_XtPopup(), positionpopup(), and x_event().
{
    static Boolean initialized = False;
    if (!initialized) {
    init_extended_commands_popup();
    initialized = True;
    }
    extended_command_selected = -1; /* reset selected value */
    positionpopup(extended_command_popup,
      FALSE); /* center on cursor */
    nh_XtPopup(extended_command_popup, (int)XtGrabExclusive,
                    extended_command_form);
    /* The callbacks will enable the event loop exit. */
    (void) x_event(EXIT_ON_EXIT);
    return extended_command_selected;
}
void X11_player_selection ()
Definition at line 263 of file winmisc.c.
References Gender::adj, Align::adj, algn_select_translations, aligns, alloc(), clearlocks(), EXIT_ON_EXIT, RoleName::f, FALSE, flag::female, flags, free(), gend_select_translations, genders, flag::initalign, flag::initgend, flag::initrace, flag::initrole, RoleName::m, make_menu(), Role::name, nh_XtPopdown(), nh_XtPopup(), Race::noun, ok_align(), ok_gend(), ok_race(), ok_role(), panic(), pick_align(), pick_gend(), pick_race(), PICK_RANDOM, pick_role(), player_select_translations, xwindow::popup, positionpopup(), PS_QUIT, ps_quit(), PS_RANDOM, ps_random(), ps_select(), ps_selected, QBUFSZ, race_select_translations, races, flag::randomall, rigid_role_checks(), ROLE_RANDOM, roles, root_plselection_prompt(), Sprintf, terminate(), validalign(), validgend(), validrace(), X11_exit_nhwindows(), and x_event().
{
    int num_roles, num_races, num_gends, num_algns,
    i, availcount, availindex;
    Widget popup, player_form;
    const char **choices;
    char qbuf[QBUFSZ], plbuf[QBUFSZ];
    /* avoid unnecessary prompts further down */
    rigid_role_checks();
    (void) root_plselection_prompt(plbuf, QBUFSZ - 1,
            flags.initrole, flags.initrace, flags.
      initgend, flags.initalign);
    while (flags.initrole < 0) {
    if (flags.initrole == ROLE_RANDOM || flags.
      randomall) {
        flags.initrole = pick_role(flags.initrace,
                       flags.initgend, flags.initalign,
      PICK_RANDOM);
        break;
    }
    /* select a role */
    for (num_roles = 0; roles[num_roles].name.m; ++num_roles) continue;
    choices = (const char **)alloc(sizeof(char *) * num_roles);
    for (;;) {
        availcount = 0;
        for (i = 0; i < num_roles; i++) {
        choices[i] = 0;
        if (ok_role(i, flags.initrace,
                flags.initgend, flags.initalign)) {
            choices[i] = roles[i].name.m;
            if (flags.initgend >= 0 && flags.female &&
      roles[i].name.f)
            choices[i] = roles[i].name.f;
            ++availcount;
        }
        }
        if (availcount > 0) break;
        else if (flags.initalign >= 0) flags.initalign = -1; /* reset */
        else if (flags.initgend >= 0) flags.initgend = -1;
        else if (flags.initrace >= 0) flags.initrace = -1;
        else panic("no available ROLE+race+gender+alignment combinations");
    }
    Sprintf(qbuf, "Choose your %s Role", s_suffix(plbuf));
    popup = make_menu("player_selection", qbuf,
            player_select_translations,
            "quit", ps_quit,
            "random", ps_random,
            num_roles, choices, (Widget **)0, ps_select, &player_form);
    ps_selected = -1;
    positionpopup(popup, FALSE);
    nh_XtPopup(popup, (int)XtGrabExclusive, player_form);
    /* The callbacks will enable the event loop exit. */
    (void) x_event(EXIT_ON_EXIT);
    nh_XtPopdown(popup);
    XtDestroyWidget(popup);
    free((genericptr_t)choices), choices = 0;
    if (ps_selected == PS_QUIT) {
        clearlocks();
        X11_exit_nhwindows((char *)0);
        terminate(0);
    } else if (ps_selected == PS_RANDOM) {
        flags.initrole = ROLE_RANDOM;
    } else if (ps_selected < 0 || ps_selected >= num_roles) {
        panic("player_selection: bad role select value %d", ps_selected);
    } else {
        flags.initrole = ps_selected;
    }
    }
    (void) root_plselection_prompt(plbuf, QBUFSZ - 1,
            flags.initrole, flags.initrace, flags.
      initgend, flags.initalign);
    while (!validrace(flags.initrole, flags.initrace)) {
    if (flags.initrace == ROLE_RANDOM || flags.
      randomall) {
        flags.initrace = pick_race(flags.initrole,
                       flags.initgend, flags.initalign,
      PICK_RANDOM);
        break;
    }
    /* select a race */
    for (num_races = 0; races[num_races].noun; ++num_races) continue;
    choices = (const char **)alloc(sizeof(char *) * num_races);
    for (;;) {
        availcount = availindex = 0;
        for (i = 0; i < num_races; i++) {
        choices[i] = 0;
        if (ok_race(flags.initrole, i,
                flags.initgend, flags.initalign)) {
            choices[i] = races[i].noun;
            ++availcount;
            availindex = i; /* used iff only one */
        }
        }
        if (availcount > 0) break;
        else if (flags.initalign >= 0) flags.initalign = -1; /* reset */
        else if (flags.initgend >= 0) flags.initgend = -1;
        else panic("no available role+RACE+gender+alignment combinations");
    }
    if (availcount == 1) {
        flags.initrace = availindex;
        free((genericptr_t)choices), choices = 0;
    } else {
        Sprintf(qbuf, "Pick your %s race", s_suffix(plbuf));
        popup = make_menu("race_selection", qbuf,
            race_select_translations,
            "quit", ps_quit,
            "random", ps_random,
            num_races, choices, (Widget **)0,
            ps_select, &player_form);
        ps_selected = -1;
        positionpopup(popup, FALSE);
        nh_XtPopup(popup, (int)XtGrabExclusive, player_form);
        /* The callbacks will enable the event loop exit. */
        (void) x_event(EXIT_ON_EXIT);
        nh_XtPopdown(popup);
        XtDestroyWidget(popup);
        free((genericptr_t)choices), choices = 0;
        if (ps_selected == PS_QUIT) {
        clearlocks();
        X11_exit_nhwindows((char *)0);
        terminate(0);
        } else if (ps_selected == PS_RANDOM) {
        flags.initrace = ROLE_RANDOM;
        } else if (ps_selected < 0 || ps_selected >= num_races) {
        panic("player_selection: bad race select value %d", ps_selected);
        } else {
        flags.initrace = ps_selected;
        }
    } /* more than one race choice available */
    }
    (void) root_plselection_prompt(plbuf, QBUFSZ - 1,
            flags.initrole, flags.initrace, flags.
      initgend, flags.initalign);
    while (!validgend(flags.initrole, flags.initrace,
      flags.initgend)) {
    if (flags.initgend == ROLE_RANDOM || flags.
      randomall) {
        flags.initgend = pick_gend(flags.initrole,
      flags.initrace,
                       flags.initalign, PICK_RANDOM);
        break;
    }
    /* select a gender */
    num_gends = 2; /* genders[2] isn't allowed */
    choices = (const char **)alloc(sizeof(char *) * num_gends);
    for (;;) {
        availcount = availindex = 0;
        for (i = 0; i < num_gends; i++) {
        choices[i] = 0;
        if (ok_gend(flags.initrole, flags.initrace,
                i, flags.initalign)) {
            choices[i] = genders[i].adj;
            ++availcount;
            availindex = i; /* used iff only one */
        }
        }
        if (availcount > 0) break;
        else if (flags.initalign >= 0) flags.initalign = -1; /* reset */
        else panic("no available role+race+GENDER+alignment combinations");
    }
    if (availcount == 1) {
        flags.initgend = availindex;
        free((genericptr_t)choices), choices = 0;
    } else {
        Sprintf(qbuf, "Your %s gender?", s_suffix(plbuf));
        popup = make_menu("gender_selection", qbuf,
            gend_select_translations,
            "quit", ps_quit,
            "random", ps_random,
            num_gends, choices, (Widget **)0,
            ps_select, &player_form);
        ps_selected = -1;
        positionpopup(popup, FALSE);
        nh_XtPopup(popup, (int)XtGrabExclusive, player_form);
        /* The callbacks will enable the event loop exit. */
        (void) x_event(EXIT_ON_EXIT);
        nh_XtPopdown(popup);
        XtDestroyWidget(popup);
        free((genericptr_t)choices), choices = 0;
        if (ps_selected == PS_QUIT) {
        clearlocks();
        X11_exit_nhwindows((char *)0);
        terminate(0);
        } else if (ps_selected == PS_RANDOM) {
        flags.initgend = ROLE_RANDOM;
        } else if (ps_selected < 0 || ps_selected >= num_gends) {
        panic("player_selection: bad gender select value %d", ps_selected);
        } else {
        flags.initgend = ps_selected;
        }
    } /* more than one gender choice available */
    }
    (void) root_plselection_prompt(plbuf, QBUFSZ - 1,
            flags.initrole, flags.initrace, flags.
      initgend, flags.initalign);
    while (!validalign(flags.initrole, flags.
      initrace, flags.initalign)) {
    if (flags.initalign == ROLE_RANDOM || flags.
      randomall) {
        flags.initalign = pick_align(flags.initrole,
      flags.initrace,
                     flags.initgend, PICK_RANDOM);
        break;
    }
    /* select an alignment */
    num_algns = 3; /* aligns[3] isn't allowed */
    choices = (const char **)alloc(sizeof(char *) * num_algns);
    for (;;) {
        availcount = availindex = 0;
        for (i = 0; i < num_algns; i++) {
        choices[i] = 0;
        if (ok_align(flags.initrole, flags.initrace,
                 flags.initgend, i)) {
            choices[i] = aligns[i].adj;
            ++availcount;
            availindex = i; /* used iff only one */
        }
        }
        if (availcount > 0) break;
        else panic("no available role+race+gender+ALIGNMENT combinations");
    }
    if (availcount == 1) {
        flags.initalign = availindex;
        free((genericptr_t)choices), choices = 0;
    } else {
        Sprintf(qbuf, "Your %s alignment?", s_suffix(plbuf));
        popup = make_menu("alignment_selection", qbuf,
            algn_select_translations,
            "quit", ps_quit,
            "random", ps_random,
            num_algns, choices, (Widget **)0,
            ps_select, &player_form);
        ps_selected = -1;
        positionpopup(popup, FALSE);
        nh_XtPopup(popup, (int)XtGrabExclusive, player_form);
        /* The callbacks will enable the event loop exit. */
        (void) x_event(EXIT_ON_EXIT);
        nh_XtPopdown(popup);
        XtDestroyWidget(popup);
        free((genericptr_t)choices), choices = 0;
        if (ps_selected == PS_QUIT) {
        clearlocks();
        X11_exit_nhwindows((char *)0);
        terminate(0);
        } else if (ps_selected == PS_RANDOM) {
        flags.initalign = ROLE_RANDOM;
        } else if (ps_selected < 0 || ps_selected >= num_algns) {
        panic("player_selection: bad alignment select value %d",
      ps_selected);
        } else {
        flags.initalign = ps_selected;
        }
    } /* more than one alignment choice available */
    }
}
Variable Documentation
const char algn_select_translations[] [static]
Initial value:
=
    "#override\n\
     <Key>: algn_key()"
Definition at line 66 of file winmisc.c.
Referenced by X11_player_selection().
boolean ec_active = FALSE [static]
Definition at line 48 of file winmisc.c.
Referenced by ec_dismiss(), ec_key(), and extend_select().
char ec_chars[EC_NCHARS] [static]
Definition at line 50 of file winmisc.c.
Referenced by ec_key().
int ec_nchars = 0 [static]
Definition at line 49 of file winmisc.c.
Referenced by ec_key().
Time ec_time [static]
Definition at line 51 of file winmisc.c.
Referenced by ec_key().
Widget extended_command_form [static]
Definition at line 38 of file winmisc.c.
Referenced by init_extended_commands_popup(), and X11_get_ext_cmd().
Widget extended_command_popup = 0 [static]
Definition at line 37 of file winmisc.c.
Referenced by ec_delete(), ec_dismiss(), ec_key(), extend_select(), init_extended_commands_popup(), and X11_get_ext_cmd().
int extended_command_selected [static]
Definition at line 40 of file winmisc.c.
Referenced by ec_dismiss(), ec_key(), extend_select(), and X11_get_ext_cmd().
const char extended_command_translations[] [static]
Initial value:
=
    "#override\n\
     <Key>: ec_key()"
Definition at line 53 of file winmisc.c.
Referenced by init_extended_commands_popup().
Widget* extended_commands = 0 [static]
Definition at line 39 of file winmisc.c.
Referenced by ec_dismiss(), ec_key(), extend_select(), and init_extended_commands_popup().
const char gend_select_translations[] [static]
Initial value:
=
    "#override\n\
     <Key>: gend_key()"
Definition at line 63 of file winmisc.c.
Referenced by X11_player_selection().
const char player_select_translations[] [static]
Initial value:
=
    "#override\n\
     <Key>: ps_key()"
Definition at line 57 of file winmisc.c.
Referenced by X11_player_selection().
const char ps_quitchars[] = `\033qQ` [static]
Definition at line 45 of file winmisc.c.
Referenced by algn_key(), gend_key(), ps_key(), and race_key().
const char ps_randchars[] = `*@` [static]
Definition at line 44 of file winmisc.c.
Referenced by algn_key(), gend_key(), ps_key(), and race_key().
int ps_selected [static]
Definition at line 41 of file winmisc.c.
Referenced by algn_key(), gend_key(), popup_delete(), ps_key(), ps_quit(), ps_random(), ps_select(), race_key(), and X11_player_selection().
const char race_select_translations[] [static]
Initial value:
=
    "#override\n\
     <Key>: race_key()"
Definition at line 60 of file winmisc.c.
Referenced by X11_player_selection().