nethack/sys/wince/winmain.c File Reference
#include `winMS.h`
*
#include <string.h>
*
Macros
#define MAX_CMDLINE_PARAM 255
Functions
int FDECL (main,(int, char **))
static TCHAR * _get_cmd_arg (TCHAR *pCmdLine)
int APIENTRY WinMain (HINSTANCE hInstance, HINSTANCE hPrevInstance, LPWSTR lpCmdLine, int nCmdShow)
char lowc (char c)
int strncmpi (const char *s1, const char *s2, int n)
Macro Definition Documentation
#define MAX_CMDLINE_PARAM 255
Definition at line 6 of file winmain.c.
Referenced by WinMain().
Function Documentation
TCHAR * _get_cmd_arg (TCHAR * pCmdLine) [static]
Definition at line 48 of file winmain.c.
References NULL, and TRUE.
Referenced by WinMain().
{
    static TCHAR* pArgs = NULL;
    TCHAR *pRetArg;
    BOOL bQuoted;
    if(!pCmdLine && !pArgs) return NULL;
    if(!pArgs) pArgs = pCmdLine;
    /* skip whitespace */
    for(pRetArg = pArgs; *pRetArg && _istspace(*pRetArg); pRetArg = CharNext(pRetArg));
    if(!*pRetArg) {
        pArgs = NULL;
        return NULL;
    }
    /* check for quote */
    if(*pRetArg==TEXT('"')) {
        bQuoted = TRUE;
        pRetArg = CharNext(pRetArg);
        pArgs = _tcschr(pRetArg, TEXT('"'));
    } else {
        /* skip to whitespace */
        for(pArgs = pRetArg; *pArgs && !_istspace(*pArgs); pArgs = CharNext(pArgs));
    }
    
    if(pArgs && *pArgs) {
        TCHAR* p;
        p = pArgs;
        pArgs = CharNext(pArgs);
        *p = (TCHAR)0;
    } else {
        pArgs = NULL;
    }
    return pRetArg;
}
int FDECL (main , (int, char **))
char lowc (char c)
Definition at line 88 of file winmain.c.
Referenced by gend_key(), mswin_yn_function(), parseoptions(), prompt_for_player_selection(), ps_key(), race_key(), strncmpi(), and yn_key().
{
    return((char)(('A' <= c && c <= 'Z') ? (c | 040) : c));
}
int strncmpi (const char * s1, const char * s2, int n)
Definition at line 95 of file winmain.c.
References lowc().
Referenced by assign_soundcard(), convert_line(), dorecover(), dosave0(), dowrite(), initoptions(), main(), match_optname(), mswin_get_ext_cmd(), parseoptions(), process_options(), set_option_mod_status(), str2align(), str2gend(), str2race(), str2role(), and topl_key().
{ /*{ aka strncasecmp }*/
    register char t1, t2;
    while (n--) {
    if (!*s2) return (*s1 != 0); /* s1 >= s2 */
    else if (!*s1) return -1; /* s1 < s2 */
    t1 = lowc(*s1++);
    t2 = lowc(*s2++);
    if (t1 != t2) return (t1 > t2) ? 1 : -1;
    }
    return 0; /* s1 == s2 */
}
int APIENTRY WinMain (HINSTANCE hInstance, HINSTANCE hPrevInstance, LPWSTR lpCmdLine, int nCmdShow)
Definition at line 11 of file winmain.c.
References _get_cmd_arg(), buf, BUFSZ, main(), MAX_CMDLINE_PARAM, NH_W2A, NHSTR_BUFSIZE, and NULL.
{
    int argc;
    char* argv[MAX_CMDLINE_PARAM];
    size_t len;
    TCHAR* p;
    TCHAR wbuf[NHSTR_BUFSIZE];
    char buf[NHSTR_BUFSIZE];
    /* get command line parameters */
    p = _get_cmd_arg(
#if defined(WIN_CE_PS2xx) || defined(WIN32_PLATFORM_HPCPRO)
        lpCmdLine
#else
        GetCommandLine()
#endif
    );
    for(argc = 1; p && argc<MAX_CMDLINE_PARAM; argc++) {
        len = _tcslen(p);
        if(len>0) {
            argv[argc] = _strdup(NH_W2A(p, buf, BUFSZ));
        } else {
            argv[argc] = "";
        }
        p = _get_cmd_arg(NULL);
    }
    GetModuleFileName(NULL, wbuf, BUFSZ);
    argv[0] = _strdup(NH_W2A(wbuf, buf, BUFSZ));
    main(argc, argv);
    return 0;
}