nethack/sys/amiga/winproto.h File Reference
Functions
void EditColor (void)
void EditClipping (void)
void DrawCol (struct Window *w, int idx, UWORD *colors)
void DispCol (struct Window *w, int idx, UWORD *colors)
void amii_change_color (int, long, int)
char * amii_get_color_string ()
void amii_getlin (const char *prompt, char *bufp)
void getlind (const char *prompt, char *bufp, const char *dflt)
int filecopy (char *from, char *to)
char * basename (char *str)
char * dirname (char *str)
void amii_putstr (winid window, int attr, const char *str)
void outmore (struct amii_WinDesc *cw)
void outsubstr (struct amii_WinDesc *cw, char *str, int len, int fudge)
void amii_putsym (winid st, int i, int y, CHAR_P c)
void amii_addtopl (const char *s)
void TextSpaces (struct RastPort *rp, int nr)
void amii_remember_topl (void)
long CountLines (winid)
long FindLine (winid, int)
int amii_doprev_message (void)
void flushIDCMP (struct MsgPort *)
int amii_msgborder (struct Window *)
void amii_scrollmsg (register struct Window *w, register struct amii_WinDesc *cw)
int amii_nh_poskey (int *x, int *y, int *mod)
int amii_nhgetch (void)
void amii_get_nh_event (void)
void amii_getret (void)
void amii_start_menu (winid window)
void FDECL (amii_add_menu,(winid, int, const anything *, CHAR_P, CHAR_P, int, const char *, BOOLEAN_P))
void FDECL (amii_end_menu,(winid, const char *))
int FDECL (amii_select_menu,(winid, int, menu_item **))
int DoMenuScroll (int win, int blocking, int how, menu_item **)
void ReDisplayData (winid win)
void DisplayData (winid win, int start)
void SetPropInfo (struct Window *win, struct Gadget *gad, long vis, long total, long top)
struct Window * OpenShWindow (struct NewWindow *nw)
void CloseShWindow (struct Window *win)
int ConvertKey (struct IntuiMessage *message)
int kbhit (void)
int amikbhit (void)
int WindowGetchar (void)
WETYPE WindowGetevent (void)
void amii_cleanup (void)
void Abort (long rc)
void CleanUp (void)
void flush_glyph_buffer (struct Window *w)
void amiga_print_glyph (winid window, int color_index, int glyph)
void start_glyphout (winid window)
void amii_end_glyphout (winid window)
struct NewWindow * DupNewWindow (struct NewWindow *win)
void FreeNewWindow (struct NewWindow *win)
void bell (void)
void amii_delay_output (void)
void amii_number_pad (int state)
void amiv_loadlib (void)
void amii_loadlib (void)
void preserve_icon (void)
void clear_icon (void)
void amii_destroy_nhwindow (winid win)
int amii_create_nhwindow (int type)
void amii_init_nhwindows (int *, char **)
void amii_setdrawpens (struct Window *, int type)
void amii_sethipens (struct Window *, int type, int attr)
void amii_setfillpens (struct Window *, int type)
void amii_clear_nhwindow (winid win)
void dismiss_nhwindow (winid win)
void amii_exit_nhwindows (const char *str)
void amii_display_nhwindow (winid win, boolean blocking)
void amii_curs (winid window, int x, int y)
void kill_nhwindows (int all)
void amii_cl_end (struct amii_WinDesc *cw, int i)
void cursor_off (winid window)
void cursor_on (winid window)
void amii_suspend_nhwindows (const char *str)
void amii_resume_nhwindows (void)
void amii_bell (void)
void removetopl (int cnt)
void port_help (void)
void amii_print_glyph (winid win, xchar x, xchar y, int glyph)
void amii_raw_print (const char *s)
void amii_raw_print_bold (const char *s)
void amii_update_inventory (void)
void amii_mark_synch (void)
void amii_wait_synch (void)
void amii_setclipped (void)
void amii_cliparound (int x, int y)
void amii_set_text_font (char *font, int size)
BitMapHeader ReadImageFiles (char **, struct BitMap **, char **)
BitMapHeader ReadTileImageFiles (void)
void FreeImageFiles (char **, struct BitMap **)
void FreeTileImageFiles ()
void amii_askname (void)
void amii_player_selection (void)
void RandomWindow (char *name)
int amii_get_ext_cmd (void)
char amii_yn_function (const char *prompt, const char *resp, char def)
void amii_display_file (const char *fn, boolean complain)
void SetBorder (struct Gadget *gd)
void * malloc (register unsigned size)
void free (void *q)
void FDECL (amii_outrip,(winid tmpwin, int how))
void SetMazeType (MazeType)
int GlyphToIcon (int glyph)
Function Documentation
void Abort (long rc)
Definition at line 741 of file amiwind.c.
References Abort(), amii_getret(), amii_procs, chdir(), exit(), orgdir, printf, and windowprocs.
Referenced by Abort(), amii_create_nhwindow(), and amii_init_nhwindows().
{
    int fault = 1;
#ifdef CHDIR
    extern char orgdir[];
    chdir(orgdir);
#endif
#ifdef AMII_GRAPHICS
    if (Initialized
      && ConsoleDevice
      && windowprocs.win_init_nhwindows==amii_procs.win_init_nhwindows) {
      printf("\n\nAbort with alert code %08lx...\n", rc);
      amii_getret();
    } else
#endif
      printf("\n\nAbort with alert code %08lx...\n",rc);
      /* Alert(rc); this is too severe */
#ifdef __SASC
# ifdef INTUI_NEW_LOOK
    if(IntuitionBase->LibNode.lib_Version >= 37)
    {
        struct EasyStruct es =
        {
            sizeof(struct EasyStruct),
            0,
            "NetHack Panic Request",
            "NetHack is Aborting with code == 0x%08lx",
        "Continue Abort|Return to Program|Clean up and exit",
        };
        fault = EasyRequest(NULL, &es, NULL, (long)rc);
        if(fault == 2)
            return;
    }
# endif
    if(fault == 1)
    {
/* __emit(0x4afc); */ /* illegal instruction */
    __emit(0x40fc); /* divide by */
    __emit(0x0000); /* #0 */
      /* NOTE: don't move amii_cleanup() above here - */
      /* it is too likely to kill the system */
      /* before it can get the SnapShot out, if */
      /* there is something really wrong. */
    }
#endif
#ifdef AMII_GRAPHICS
    if(windowprocs.win_init_nhwindows==amii_procs.win_init_nhwindows)
      amii_cleanup();
#endif
#undef exit
#ifdef AZTEC_C
    _abort();
#endif
    exit((int) rc);
}
void amiga_print_glyph (winid window, int color_index, int glyph)
Referenced by amii_print_glyph(), and DisplayData().
void amii_addtopl (const char * s)
void amii_askname (void)
void amii_bell (void)
Definition at line 2000 of file winfuncs.c.
References NULL.
{
    DisplayBeep(NULL);
}
void amii_change_color (int , long , int)
Definition at line 1149 of file winreq.c.
{
    if(rev)
    flags.amii_curmap[ pen ] = ~val;
    else
    flags.amii_curmap[ pen ] = val;
    if(HackScreen)
    LoadRGB4(&HackScreen->ViewPort, flags.amii_curmap,
      amii_numcolors);
}
void amii_cl_end (struct amii_WinDesc * cw, int i)
Definition at line 1817 of file winfuncs.c.
References panic(), and TextSpaces().
Referenced by amii_doprev_message(), amii_putstr(), DisplayData(), outmore(), and removetopl().
{
    register struct Window *w = cw->win;
    register int oy, ox;
    if(!w)
    panic("NULL window pointer in amii_cl_end()");
    oy = w->RPort->cp_y;
    ox = w->RPort->cp_x;
    TextSpaces(w->RPort, cw->cols - curs_pos);
    Move(w->RPort, ox, oy);
}
void amii_cleanup (void)
void amii_clear_nhwindow (winid win)
Definition at line 1414 of file winfuncs.c.
References amii_clear_nhwindow(), amii_curs(), amii_setfillpens(), amii_wins, amii_WinDesc::cols, cursor_off(), amii_WinDesc::curx, amii_WinDesc::cury, FLMAP_CURSUP, NHW_MAP, NHW_MENU, NHW_MESSAGE, NHW_TEXT, NULL, panic(), reclip, scrollmsg, TextSpaces(), amii_WinDesc::type, amii_WinDesc::wflags, amii_WinDesc::win, WIN_ERR, WIN_MAP, WIN_OVER, winpanicstr, and WINVERS_AMIV.
Referenced by amii_clear_nhwindow(), amii_init_nhwindows(), and amii_start_menu().
{
    register struct amii_WinDesc *cw;
    register struct Window *w;
    if(reclip == 2) return;
    if(win == WIN_ERR || (cw = amii_wins[win]) == NULL)
    panic(winpanicstr, win, "clear_nhwindow");
    /* Clear the overview window too if it is displayed */
    if(WINVERS_AMIV && (cw->type == WIN_MAP && WIN_OVER !=
      WIN_ERR && reclip == 0))
    {
    amii_clear_nhwindow(WIN_OVER);
    }
    if(w = cw->win)
    SetDrMd(w->RPort, JAM2);
    else
        return;
    if((cw->wflags & FLMAP_CURSUP))
    {
    if(cw->type != NHW_MAP)
        cursor_off(win);
    else
        cw->wflags &= ~FLMAP_CURSUP;
    }
    amii_setfillpens(w, cw->type);
    SetDrMd(w->RPort, JAM2);
    if(cw->type == NHW_MENU || cw->type == NHW_TEXT)
    {
    RectFill(w->RPort, w->BorderLeft, w->BorderTop,
      w->Width - w->BorderRight-1,
      w->Height - w->BorderBottom-1);
    }
    else
    {
    if(cw->type == NHW_MESSAGE)
    {
        amii_curs(win, 1, 0);
        if(!scrollmsg)
        TextSpaces(w->RPort, cw->cols);
    }
    else
    {
        RectFill(w->RPort, w->BorderLeft, w->BorderTop,
          w->Width - w->BorderRight-1,
          w->Height - w->BorderBottom-1);
    }
    }
    cw->cury = 0;
    cw->curx = 0;
    amii_curs(win, 1, 0);
}
void amii_cliparound (int x, int y)
Definition at line 2249 of file winfuncs.c.
References amii_wins, CO, COLNO, cursor_off(), doredraw(), flush_glyph_buffer(), Is_rogue_level, LI, max, min, moves, mxsize, mysize, reclip, restoring, ROWNO, u, you::uz, you::uz0, amii_WinDesc::win, and WIN_MAP.
{
    extern boolean restoring;
#ifdef CLIPPING
    int oldx = clipx, oldy = clipy;
    int oldxmax = clipxmax, oldymax = clipymax;
    int COx, LIx;
#define SCROLLCNT 1 /* Get there in 3 moves... */
    int scrollcnt = SCROLLCNT; /* ...or 1 if we changed level */
    if (!clipping) /* And 1 in anycase, cleaner, simpler, quicker */
    return;
    if(Is_rogue_level(&u.uz)){
    struct Window *w = amii_wins[WIN_MAP]->win;
    struct RastPort *rp = w->RPort;
    COx = (w->Width-w->BorderLeft-w->BorderRight)/rp->TxWidth;
    LIx = (w->Height-w->BorderTop-w->BorderBottom)/rp->TxHeight;
    }else{
    COx = CO;
    LIx = LI;
    }
        /*
         * On a level change, move the clipping region so that for a
         * reasonablely large window extra motion is avoided; for
         * the rogue level hopefully this means no motion at all.
         */
    {
    static d_level saved_level = {127,127}; /* XXX */
    if(!on_level(&u.uz, &saved_level)){
        scrollcnt = 1; /* jump with blanking */
        clipx=clipy=0;
        clipxmax = COx; clipymax = LIx;
        saved_level = u.uz; /* save as new current level */
    }
    }
    if (x <= clipx + xclipbord) {
    clipx = max(0, x - (clipxmax - clipx)/2);
    clipxmax = clipx + COx;
    }
    else if (x > clipxmax - xclipbord) {
    clipxmax = min(COLNO, x + (clipxmax - clipx)/2);
    clipx = clipxmax - COx;
    }
    if (y <= clipy + yclipbord) {
    clipy = max(0, y - (clipymax - clipy) / 2);
    clipymax = clipy + LIx;
    }
    else if (y > clipymax - yclipbord) {
    clipymax = min(ROWNO, y + (clipymax - clipy) / 2);
    clipy = clipymax - LIx;
    }
    reclip = 1;
    if (clipx != oldx || clipy != oldy || clipxmax != oldxmax || clipymax != oldymax)
    {
#ifndef NOSCROLLRASTER
        struct Window *w = amii_wins[ WIN_MAP ]->win;
        struct RastPort *rp = w->RPort;
        int xdelta, ydelta, xmod, ymod, i;
        int incx, incy, mincx, mincy;
        int savex, savey, savexmax, saveymax;
    int scrx, scry;
    if(Is_rogue_level(&u.uz)){
        scrx = rp->TxWidth;
        scry = rp->TxHeight;
    } else {
        scrx = mxsize;
        scry = mysize;
    }
    /* Ask that the glyph routines not draw the overview window */
    reclip = 2;
    cursor_off(WIN_MAP);
    /* Compute how far we are moving in terms of tiles */
    mincx = clipx - oldx ;
    mincy = clipy - oldy ;
    /* How many tiles to get there in SCROLLCNT moves */
    incx = (clipx - oldx)/scrollcnt;
    incy = (clipy - oldy)/scrollcnt;
    /* If less than SCROLLCNT tiles, then move by 1 tile if moving at all */
    if(incx == 0) incx = (mincx != 0);
    if(incy == 0) incy = (mincy != 0);
    /* Get count of pixels to move each iteration and final pixel count */
        xdelta = ((clipx-oldx)*scrx) / scrollcnt;
        xmod = ((clipx-oldx)*scrx) % scrollcnt;
        ydelta = ((clipy-oldy)*scry) / scrollcnt;
        ymod = ((clipy-oldy)*scry) % scrollcnt;
    /* Preserve the final move location */
        savex = clipx;
        savey = clipy;
    saveymax = clipymax;
    savexmax = clipxmax;
    /*
     * Set clipping rectangle to be just the region that will be exposed so
     * that drawing will be faster
     */
#if 0 /* Doesn't seem to work quite the way it should */
    /* In some cases hero is 'centered' offscreen */
    if(xdelta < 0)
    {
        clipx = oldx;
        clipxmax = clipx + incx;
    }
    else if(xdelta > 0)
    {
        clipxmax = oldxmax;
        clipx = clipxmax - incx;
    }
    else
    {
        clipx = oldx;
        clipxmax = oldxmax;
    }
    if(ydelta < 0)
    {
        clipy = oldy;
        clipymax = clipy + incy;
    }
    else if(ydelta > 0)
    {
        clipymax = oldymax;
        clipy = clipymax - incy;
    }
    else
    {
        clipy = oldy;
        clipymax = oldymax;
    }
#endif
    /* Now, in scrollcnt moves, move the picture toward the final view */
        for(i = 0; i < scrollcnt; ++i)
        {
#ifdef DISPMAP
        if(i == scrollcnt - 1 && (xmod != 0 || ymod != 0) &&
            (xdelta != 0 || ydelta != 0))
        {
        incx += (clipx - oldx)%scrollcnt;
        incy += (clipy - oldy)%scrollcnt;
        xdelta += xmod;
        ydelta += ymod;
        }
#endif
        /* Scroll the raster if we are scrolling */
        if(xdelta != 0 || ydelta != 0)
        {
        ScrollRaster(rp, xdelta, ydelta,
                w->BorderLeft, w->BorderTop,
                w->Width - w->BorderRight - 1,
                w->Height - w->BorderBottom - 1);
        if(mincx == 0) incx = 0;
        else mincx -= incx;
        clipx += incx;
        clipxmax += incx;
        if(mincy == 0) incy = 0;
        else mincy -= incy;
        clipy += incy;
        clipymax += incy;
        /* Draw the exposed portion */
        if (on_level(&u.uz0, &u.uz) && !restoring)
            (void) doredraw();
        flush_glyph_buffer(amii_wins[ WIN_MAP ]->win);
        }
        }
        clipx = savex;
        clipy = savey;
    clipymax = saveymax;
    clipxmax = savexmax;
#endif
    if (on_level(&u.uz0, &u.uz) && !restoring && moves > 1)
        (void) doredraw();
    flush_glyph_buffer(amii_wins[ WIN_MAP ]->win);
    }
    reclip = 0;
#endif
}
int amii_create_nhwindow (int type)
Definition at line 317 of file winfuncs.c.
References Abort(), amii_WinDesc::active, alloc(), amii_oldmsg, amii_oldover, amii_setclipped(), amii_wins, amiIDisplay, bigscreen, buf, C_BLACK, C_GREYBLUE, C_WHITE, amii_WinDesc::canresp, CO, amii_WinDesc::cols, amii_DisplayDesc::cols, ConsoleIO, amii_WinDesc::curx, amii_WinDesc::cury, amii_WinDesc::data, FALSE, fillhook, HackFont, HACKFONT, HackPort, HackScreen, Height, amii_WinDesc::hook, iflags, KbdBuffered, LayerFillHook(), LI, amii_WinDesc::maxcol, win_setup::maxcol, amii_WinDesc::maxrow, win_setup::maxrow, MAXWIN, MenuScroll, MenuStrip, amii_WinDesc::morestr, instance_flags::msg_history, MsgPropScroll, MsgScroll, mxsize, mysize, new_wins, amii_WinDesc::newwin, win_setup::newwin, NHW_BASE, NHW_MAP, NHW_MENU, NHW_MESSAGE, NHW_OVER, NHW_STATUS, NHW_TEXT, NULL, OpenShWindow(), panic(), pr_WindowPtr, PropScroll, raw_print, amii_WinDesc::resp, RogueFont, amii_WinDesc::rows, scrollmsg, TextsFont, TRUE, txbaseline, txheight, txwidth, amii_WinDesc::type, type, wd, amii_WinDesc::wflags, amii_WinDesc::win, WIN_BASE, WIN_ERR, WIN_MAP, WIN_MESSAGE, WIN_STATUS, wincnt, instance_flags::window_inited, amii_WinDesc::wintags, wintags, WINVERS_AMII, WINVERS_AMIV, amii_DisplayDesc::xpix, and amii_DisplayDesc::ypix.
Referenced by amii_init_nhwindows(), and amii_putstr().
{
    register struct Window *w = NULL;
    register struct NewWindow *nw = NULL;
    register struct amii_WinDesc *wd = NULL;
    struct Window *mapwin = NULL, *stwin = NULL, *msgwin = NULL;
    register int newid;
    int maph, stath, scrfontysize;
    scrfontysize = HackScreen->Font->ta_YSize;
    /*
     * Initial mapwindow height, this might change later in tilemode
     * and low screen
     */
    maph = (21 * mxsize) + 2 + (bigscreen ?
    HackScreen->WBorTop + HackScreen->WBorBottom + scrfontysize + 1 : 0);
    /* Status window height, avoids having to calculate many times */
    stath = txheight * 2 + 2 + (WINVERS_AMIV || bigscreen ?
    HackScreen->WBorTop + HackScreen->WBorBottom +
    (bigscreen ? scrfontysize + 1 : 0) : 0);
    if(WIN_STATUS != WIN_ERR && amii_wins[ WIN_STATUS ])
    stwin = amii_wins[ WIN_STATUS ]->win;
    if(WIN_MESSAGE != WIN_ERR && amii_wins[
      WIN_MESSAGE ])
    msgwin = amii_wins[ WIN_MESSAGE ]->win;
    if(WIN_MAP != WIN_ERR && amii_wins[ WIN_MAP ])
    mapwin = amii_wins[ WIN_MAP ]->win;
    /* Create Port anytime that we need it */
    if(HackPort == NULL)
    {
    HackPort = CreateMsgPort();
    if(!HackPort)
        panic("no memory for msg port");
    }
    nw = &new_wins[ type ].newwin;
    nw->Width = amiIDisplay->xpix;
    nw->Screen = HackScreen;
    if(WINVERS_AMIV)
    {
    nw->DetailPen = C_WHITE;
    nw->BlockPen = C_GREYBLUE;
    }
    else
    {
    nw->DetailPen = C_WHITE;
    nw->BlockPen = C_BLACK;
    }
    if (type == NHW_BASE) {
    nw->LeftEdge = 0;
    nw->TopEdge = HackScreen->BarHeight+1;
    nw->Width = HackScreen->Width;
    nw->Height = HackScreen->Height - nw->TopEdge;
    } else if(!WINVERS_AMIV && type == NHW_MAP) {
    nw->LeftEdge = 0;
    nw->Height = maph;
    if(msgwin && stwin) {
        nw->TopEdge = stwin->TopEdge - maph;
    } else {
        panic("msgwin and stwin must open before map");
    }
    if (nw->TopEdge < 0)
        panic("Too small screen to fit map");
    }
    else if(type == NHW_MAP && WINVERS_AMIV)
    {
    struct Window *w;
    w = amii_wins[ WIN_MESSAGE ]->win;
    nw->LeftEdge = 0;
    nw->TopEdge = w->TopEdge + w->Height;
    nw->Width = amiIDisplay->xpix - nw->LeftEdge;
    w = amii_wins[ WIN_STATUS ]->win;
    nw->Height = w->TopEdge - nw->TopEdge;
    nw->MaxHeight = 0xffff;
    nw->MaxWidth = 0xffff;
    if(nw->TopEdge + nw->Height > amiIDisplay->ypix - 1)
        nw->Height = amiIDisplay->ypix - nw->TopEdge - 1;
    }
    else if(type == NHW_STATUS)
    {
    if(!WINVERS_AMIV && (WIN_MAP != WIN_ERR && amii_wins[ WIN_MAP ]))
        w = amii_wins[ WIN_MAP ]->win;
    else if(WIN_BASE != WIN_ERR && amii_wins[ WIN_BASE ])
        w = amii_wins[ WIN_BASE ]->win;
    else
        panic("No window to base STATUS location from");
    nw->Height = stath;
    nw->TopEdge = amiIDisplay->ypix - nw->Height;
    nw->LeftEdge = w->LeftEdge;
    if(nw->LeftEdge + nw->Width >= amiIDisplay->xpix)
        nw->LeftEdge = 0;
    if(nw->Width >= amiIDisplay->xpix - nw->LeftEdge)
        nw->Width = amiIDisplay->xpix - nw->LeftEdge;
    }
    else if(WINVERS_AMIV && type == NHW_OVER)
    {
    nw->Flags |= WINDOWSIZING|WINDOWDRAG|WINDOWCLOSE;
    nw->IDCMPFlags |= CLOSEWINDOW;
    /* Bring up window as half the width of the message window, and make
     * the message window change to one half the width...
     */
    if(amii_oldover.MaxX != 0)
    {
        nw->LeftEdge = amii_oldover.MinX;
        nw->TopEdge = amii_oldover.MinY;
        nw->Width = amii_oldover.MaxX;
        nw->Height = amii_oldover.MaxY;
        ChangeWindowBox(amii_wins[ WIN_MESSAGE ]->win,
            amii_oldmsg.MinX, amii_oldmsg.MinY,
            amii_oldmsg.MaxX, amii_oldmsg.MaxY);
    }
    else
    {
        nw->LeftEdge = (amii_wins[ WIN_MESSAGE ]->win->Width*4)/9;
        nw->TopEdge = amii_wins[ WIN_MESSAGE ]->win->TopEdge;
        nw->Width = amiIDisplay->xpix - nw->LeftEdge;
        nw->Height = amii_wins[ WIN_MESSAGE ]->win->Height;
        SizeWindow(amii_wins[ WIN_MESSAGE ]->win,
            nw->LeftEdge - amii_wins[ WIN_MESSAGE ]->win->Width, 0);
    }
    }
    else if(type == NHW_MESSAGE)
    {
    if(!WINVERS_AMIV && (WIN_MAP != WIN_ERR && amii_wins[ WIN_MAP ]))
        w = amii_wins[ WIN_MAP ]->win;
    else if(WIN_BASE != WIN_ERR && amii_wins[ WIN_BASE ])
        w = amii_wins[ WIN_BASE ]->win;
    else
        panic("No window to base STATUS location from");
    nw->TopEdge = bigscreen ? HackScreen->BarHeight+1 : 0;
    /* Assume highest possible message window */
    nw->Height = HackScreen->Height - nw->TopEdge - maph - stath;
    /* In tilemode we can cope with this */
    if (WINVERS_AMIV && nw->Height < 0)
        nw->Height = 0;
    /* If in fontmode messagewindow is too small, open it with 3 lines
       and overlap it with map */
    if (nw->Height < txheight+2) {
        nw->Height = txheight*4 + 3 + HackScreen->WBorTop +
      HackScreen->WBorBottom;
    }
    if ((nw->Height-2)/txheight < 3) {
        scrollmsg = 0;
        nw->Title = 0;
    } else {
        nw->FirstGadget = &MsgScroll;
        nw->Flags |= WINDOWSIZING|WINDOWDRAG;
        nw->Flags &= ~BORDERLESS;
        if(WINVERS_AMIV || nw->Height == 0) {
        if(WINVERS_AMIV) {
            nw->Height = TextsFont->tf_YSize + HackScreen->WBorTop + 3 +
                HackScreen->WBorBottom;
            if(bigscreen)
            nw->Height += (txheight * 6);
            else
            nw->Height += (txheight * 3);
        }
        else
        {
            nw->Height = HackScreen->Height - nw->TopEdge - stath - maph;
        }
        }
    }
    /* Do we have room for larger message window ?
     * This is possible if we can show full height map in tile
     * mode with default scaling.
     */
    if (nw->Height + stath + maph < HackScreen->Height - nw->TopEdge)
        nw->Height = HackScreen->Height - nw->TopEdge - 1 - maph - stath;
#ifdef INTUI_NEW_LOOK
    if(IntuitionBase->LibNode.lib_Version >= 37)
    {
        MsgPropScroll.Flags |= PROPNEWLOOK;
        PropScroll.Flags |= PROPNEWLOOK;
    }
#endif
    }
    nw->IDCMPFlags |= MENUPICK;
    /* Check if there is "Room" for all this stuff... */
    if((WINVERS_AMIV || bigscreen) &&
    type != NHW_BASE)
    {
    nw->Flags &= ~(BORDERLESS | BACKDROP);
    if(WINVERS_AMIV)
    {
        if(type == NHW_STATUS)
        {
        nw->Flags &= ~(WINDOWDRAG | WINDOWDEPTH | SIZEBRIGHT | WINDOWSIZING);
        nw->IDCMPFlags &= ~NEWSIZE;
        }
        else
        {
        nw->Flags |= (WINDOWDRAG | WINDOWDEPTH | SIZEBRIGHT | WINDOWSIZING);
        nw->IDCMPFlags |= NEWSIZE;
        }
    }
    else
    {
        if(HackScreen->Width < 657)
        {
        nw->Flags |= (WINDOWDRAG | WINDOWDEPTH);
        }
        else
        {
        nw->Flags |= (WINDOWDRAG | WINDOWDEPTH | SIZEBRIGHT);
        }
    }
    }
    if (WINVERS_AMII && type == NHW_MAP)
    nw->Flags &= ~WINDOWSIZING;
    if (type == NHW_MESSAGE && scrollmsg) {
    nw->Flags |= WINDOWDRAG|WINDOWDEPTH|SIZEBRIGHT|WINDOWSIZING;
    nw->Flags &= ~BORDERLESS;
    }
    /* No titles on a hires only screen except for messagewindow */
    if(!(WINVERS_AMIV && type == NHW_MAP) && !bigscreen &&
      type != NHW_MESSAGE)
    nw->Title = 0;
    wd = (struct amii_WinDesc *)alloc(sizeof(struct
      amii_WinDesc));
    memset(wd, 0, sizeof(struct amii_WinDesc));
    /* Both, since user may have changed the pen settings so respect those */
    if(WINVERS_AMII || WINVERS_AMIV)
    {
    /* Special backfill for these types of layers */
    switch(type)
    {
    case NHW_MESSAGE:
    case NHW_STATUS:
    case NHW_TEXT:
    case NHW_MENU:
    case NHW_BASE:
    case NHW_OVER:
    case NHW_MAP:
        if(wd)
        {
#ifdef __GNUC__
        fillhook.h_Entry = (void *)&LayerFillHook;
#else
        fillhook.h_Entry = (ULONG(*)())LayerFillHook;
#endif
        fillhook.h_Data = (void *)type;
        fillhook.h_SubEntry = 0;
        wd->hook = alloc(sizeof(fillhook));
        memcpy(wd->hook, &fillhook, sizeof(fillhook));
        memcpy(wd->wintags, wintags, sizeof(wd->wintags));
        wd->wintags[0].ti_Data = (long)wd->hook;
        nw->Extension = (void *)wd->wintags;
        }
        break;
    }
    }
    /* Don't open MENU or TEXT windows yet */
    if(type == NHW_MENU || type == NHW_TEXT)
    w = NULL;
    else
    w=OpenShWindow((void *)nw);
    if(w == NULL && type != NHW_MENU && type != NHW_TEXT)
    {
    char buf[ 100 ];
    sprintf(buf, "nw type (%d) dims l: %d, t: %d, w: %d, h: %d",
        type,
        nw->LeftEdge, nw->TopEdge,
        nw->Width, nw->Height);
    raw_print(buf);
    panic("bad openwin %d",type);
    }
    /* Check for an empty slot */
    for(newid = 0; newid<MAXWIN + 1; newid++)
    {
    if(amii_wins[newid] == 0)
        break;
    }
    if(newid==MAXWIN+1)
    panic("time to write re-alloc code\n");
    /* Set wincnt accordingly */
    if(newid > wincnt)
    wincnt = newid;
    /* Do common initialization */
    amii_wins[newid] = wd;
    wd->newwin = NULL;
    wd->win = w;
    wd->type = type;
    wd->wflags = 0;
    wd->active = FALSE;
    wd->curx=wd->cury = 0;
    wd->resp = wd->canresp = wd->morestr = 0; /* CHECK THESE */
    wd->maxrow = new_wins[type].maxrow;
    wd->maxcol = new_wins[type].maxcol;
    if(type != NHW_TEXT && type != NHW_MENU)
    {
    if(TextsFont && (type == NHW_MESSAGE || type ==
      NHW_STATUS))
    {
        SetFont(w->RPort, TextsFont);
        txheight = w->RPort->TxHeight;
        txwidth = w->RPort->TxWidth;
        txbaseline = w->RPort->TxBaseline;
        if(type == NHW_MESSAGE)
        {
        if (scrollmsg)
        {
            if(WINVERS_AMIV)
            {
            WindowLimits(w, 100, w->BorderTop +
                w->BorderBottom +
                ((txheight+1)*2) + 1, 0, 0);
            }
            else
            {
            WindowLimits(w, w->Width, w->BorderTop +
                w->BorderBottom +
                ((txheight+1)*2) + 1, 0, 0);
            }
        }
        else
        {
            WindowLimits(w, w->Width, w->BorderTop +
                w->BorderBottom +
                txheight + 2, 0, 0);
        }
        }
    }
    if (type != NHW_MAP) {
        SetFont(w->RPort, TextsFont);
    }
#ifdef HACKFONT
    else if(HackFont)
        SetFont(w->RPort, HackFont);
#endif
    }
    /* Text and menu windows are not opened yet */
    if(w)
    {
    wd->rows = (w->Height - w->BorderTop -
        w->BorderBottom - 2) / w->RPort->TxHeight;
    wd->cols = (w->Width - w->BorderLeft -
        w->BorderRight - 2) / w->RPort->TxWidth;
    }
    /* Okay, now do the individual type initialization */
    switch(type)
    {
    /* History lines for MESSAGE windows are stored in cw->data[?].
     * maxcol and maxrow are used as cursors. maxrow is the count
     * of the number of history lines stored. maxcol is the cursor
     * to the last line that was displayed by ^P.
     */
    case NHW_MESSAGE:
        SetMenuStrip(w, MenuStrip);
        MsgScroll.TopEdge = HackScreen->WBorTop + scrfontysize + 1;
        iflags.msg_history = wd->rows*10;
        if (iflags.msg_history < 40)
        iflags.msg_history = 40;
        if (iflags.msg_history > 400)
        iflags.msg_history = 400;
        iflags.window_inited=TRUE;
        wd->data = (char **)alloc(iflags.msg_history*sizeof(char *));
        memset(wd->data, 0, iflags.msg_history * sizeof(char *));
        wd->maxrow = wd->maxcol = 0;
        /* Indicate that we have not positioned the cursor yet */
        wd->curx = -1;
        break;
        /* A MENU contains a list of lines in wd->data[?]. These
         * lines are created in amii_putstr() by reallocating the size
         * of wd->data to hold enough (char *)'s. wd->rows is the
         * number of (char *)'s allocated. wd->maxrow is the number
         * used. wd->maxcol is used to track how wide the menu needs
         * to be. wd->resp[x] contains the characters that correspond
         * to selecting wd->data[x]. wd->resp[x] corresponds to
         * wd->data[x] for any x. Elements of wd->data[?] that are not
         * valid selections have the corresponding element of
         * wd->resp[] set to a value of '\01'; i.e. a ^A which is
         * not currently a valid keystroke for responding to any
         * MENU or TEXT window.
         */
    case NHW_MENU:
        MenuScroll.TopEdge = HackScreen->WBorTop + scrfontysize + 1;
        wd->resp=(char*)alloc(256);
        wd->resp[0]=0;
        wd->rows = wd->maxrow = 0;
        wd->cols = wd->maxcol = 0;
        wd->data = NULL;
        break;
        /* See the explanation of MENU above. Except, wd->resp[] is not
         * used for TEXT windows since there is no selection of a
         * a line performed/allowed. The window is always full
         * screen width.
         */
    case NHW_TEXT:
        MenuScroll.TopEdge = HackScreen->WBorTop + scrfontysize + 1;
        wd->rows = wd->maxrow = 0;
        wd->cols = wd->maxcol = amiIDisplay->cols;
        wd->data = NULL;
        wd->morestr = NULL;
        break;
        /* The status window has only two lines. These are stored in
         * wd->data[], and here we allocate the space for them.
         */
    case NHW_STATUS:
        SetMenuStrip(w, MenuStrip);
        /* wd->cols is the number of characters which fit across the
         * screen.
         */
        wd->data=(char **)alloc(3*sizeof(char *));
        wd->data[0] = (char *)alloc(wd->cols + 10);
        wd->data[1] = (char *)alloc(wd->cols + 10);
        wd->data[2] = NULL;
        break;
        /* NHW_OVER does not use wd->data[] or the other text
         * manipulating members of the amii_WinDesc structure.
         */
    case NHW_OVER:
        SetMenuStrip(w, MenuStrip);
        break;
        /* NHW_MAP does not use wd->data[] or the other text
         * manipulating members of the amii_WinDesc structure.
         */
    case NHW_MAP:
        SetMenuStrip(w, MenuStrip);
        if(WINVERS_AMIV)
        {
        CO = (w->Width-w->BorderLeft-w->BorderRight)/mxsize;
        LI = (w->Height-w->BorderTop-w->BorderBottom)/mysize;
        amii_setclipped();
        SetFont(w->RPort, RogueFont);
        SetAPen(w->RPort, C_WHITE); /* XXX not sufficient */
        SetBPen(w->RPort, C_BLACK);
        SetDrMd(w->RPort, JAM2);
        }
        else
        {
        if(HackFont)
            SetFont(w->RPort, HackFont);
        }
        break;
        /* The base window must exist until CleanUp() deletes it. */
    case NHW_BASE:
        SetMenuStrip(w, MenuStrip);
        /* Make our requesters come to our screen */
        {
        register struct Process *myProcess =
                    (struct Process *) FindTask(NULL);
        pr_WindowPtr = (struct Window *)(myProcess->pr_WindowPtr);
        myProcess->pr_WindowPtr = (APTR) w;
        }
        /* Need this for RawKeyConvert() */
        ConsoleIO.io_Data = (APTR) w;
        ConsoleIO.io_Length = sizeof(struct Window);
        ConsoleIO.io_Message.mn_ReplyPort = CreateMsgPort();
        if(OpenDevice("console.device", -1L,
                (struct IORequest *) &ConsoleIO, 0L) != 0)
        {
        Abort(AG_OpenDev | AO_ConsoleDev);
        }
        ConsoleDevice = (struct Library *) ConsoleIO.io_Device;
        KbdBuffered = 0;
#ifdef HACKFONT
        if(TextsFont)
        SetFont(w->RPort, TextsFont);
        else if(HackFont)
        SetFont(w->RPort, HackFont);
#endif
        txwidth = w->RPort->TxWidth;
        txheight = w->RPort->TxHeight;
        txbaseline = w->RPort->TxBaseline;
        break;
    default:
        panic("bad create_nhwindow(%d)\n",type);
        return WIN_ERR;
    }
    return(newid);
}
void amii_curs (winid window, int x, int y)
Definition at line 1584 of file winfuncs.c.
References amii_wins, amiIDisplay, C_WHITE, amii_WinDesc::cols, amii_WinDesc::curx, amii_WinDesc::cury, flush_glyph_buffer(), Is_rogue_level, amii_DisplayDesc::lastwin, max, mxsize, mysize, NHW_BASE, NHW_MAP, NHW_MENU, NHW_MESSAGE, NHW_OVER, NHW_STATUS, NHW_TEXT, NULL, panic(), pictdata, printf, amii_WinDesc::rows, rp, scrollmsg, amii_WinDesc::type, u, you::uz, amii_WinDesc::win, WIN_ERR, WIN_INVEN, winpanicstr, WINVERS_AMIV, PDAT::xsize, and PDAT::ysize.
Referenced by amii_clear_nhwindow(), amii_doprev_message(), amii_print_glyph(), amii_putstr(), amii_putsym(), amii_scrollmsg(), DisplayData(), outmore(), and removetopl().
{
    register struct amii_WinDesc *cw;
    register struct Window *w;
    register struct RastPort *rp;
    if(window == WIN_ERR || (cw = amii_wins[window]) == NULL)
    panic(winpanicstr, window, "curs");
    if((w = cw->win) == NULL)
    {
    if(cw->type == NHW_MENU || cw->type == NHW_TEXT)
        return;
    else
        panic("No window open yet in curs() for winid %d\n", window);
    }
    amiIDisplay->lastwin = window;
    /* Make sure x is within bounds */
    if(x > 0)
    --x; /* column 0 is never used */
    else
    x = 0;
    cw->curx = x;
    cw->cury = y;
#ifdef DEBUG
    if(x<0 || y<0 || y >= cw->rows || x >= cw->cols)
    {
    char *s = "[unknown type]";
    switch(cw->type)
    {
        case NHW_MESSAGE: s = "[topl window]"; break;
        case NHW_STATUS: s = "[status window]"; break;
        case NHW_MAP: s = "[map window]"; break;
        case NHW_MENU: s = "[menu window]"; break;
        case NHW_TEXT: s = "[text window]"; break;
        case NHW_BASE: s = "[base window]"; break;
        case NHW_OVER: s = "[overview window]"; break;
    }
    impossible("bad curs positioning win %d %s (%d,%d)", window, s, x, y);
    return;
    }
#endif
#ifdef CLIPPING
    if(clipping && cw->type == NHW_MAP)
    {
    x -= clipx;
    y -= clipy;
    }
#endif
    /* Output all saved output before doing cursor movements for MAP */
    if(cw->type == NHW_MAP)
    {
    flush_glyph_buffer(w);
    }
    /* Actually do it */
    rp = w->RPort;
    if(cw->type == NHW_MENU)
    {
    if(WINVERS_AMIV)
    {
        if(window == WIN_INVEN)
        {
        Move(rp, (x * rp->TxWidth) + w->BorderLeft + 1 + pictdata.xsize + 4,
            (y * max(rp->TxHeight,pictdata.ysize + 3)) +
             rp->TxBaseline + pictdata.ysize - rp->TxHeight + w->BorderTop + 4);
        }
        else
        {
        Move(rp, (x * rp->TxWidth) + w->BorderLeft + 1,
            (y * rp->TxHeight) + rp->TxBaseline + w->BorderTop + 1);
        }
    }
    else
    {
        Move(rp, (x * rp->TxWidth) + w->BorderLeft + 1,
        (y*rp->TxHeight) + rp->TxBaseline + w->BorderTop + 1);
    }
    }
    else if(cw->type == NHW_TEXT)
    {
    Move(rp, (x * rp->TxWidth) + w->BorderLeft + 1,
        (y*rp->TxHeight) + rp->TxBaseline + w->BorderTop + 1);
    }
    else if(cw->type == NHW_MAP || cw->type == NHW_BASE)
    {
    /* These coordinate calculations must be synced with those
     * in flush_glyph_buffer() in winchar.c. curs_on_u() will
     * use this code, all other drawing occurs through the glyph
     * code. In order for the cursor to appear on top of the hero,
     * the code must compute X,Y in the same manner relative to
     * the RastPort coordinates.
     *
     * y = w->BorderTop + (g_nodes[i].y-2) * rp->TxHeight +
     * rp->TxBaseline + 1;
     * x = g_nodes[i].x * rp->TxWidth + w->BorderLeft;
     */
    if(WINVERS_AMIV)
    {
        if(cw->type == NHW_MAP)
        {
          if(Is_rogue_level(&u.uz)){
#if 0
int qqx= (x * w->RPort->TxWidth) + w->BorderLeft;
int qqy= w->BorderTop + ((y+1) * w->RPort->TxHeight) + 1;
printf("pos: (%d,%d)->(%d,%d)\n",x,y,qqx,qqy);
#endif
        SetAPen(w->RPort,C_WHITE); /* XXX should be elsewhere (was 4)*/
        Move(rp, (x * w->RPort->TxWidth) + w->BorderLeft,
            w->BorderTop + ((y+1) * w->RPort->TxHeight) + 1);
          } else {
        Move(rp, (x * mxsize) + w->BorderLeft,
                w->BorderTop + ((y+1) * mysize) + 1);
          }
        }
        else
        {
        Move(rp, (x * w->RPort->TxWidth) + w->BorderLeft,
                w->BorderTop + ((y + 1) * w->RPort->TxHeight) +
                w->RPort->TxBaseline + 1);
        }
    }
    else
    {
        Move(rp, (x * w->RPort->TxWidth) + w->BorderLeft,
            w->BorderTop + (y * w->RPort->TxHeight) +
            w->RPort->TxBaseline + 1);
    }
    }
    else if(WINVERS_AMIV && cw->type == NHW_OVER)
    {
    Move(rp, (x * w->RPort->TxWidth) + w->BorderLeft + 2,
            w->BorderTop + w->RPort->TxBaseline + 3);
    }
    else if(cw->type == NHW_MESSAGE && !scrollmsg)
    {
    Move(rp, (x * w->RPort->TxWidth) + w->BorderLeft + 2,
            w->BorderTop + w->RPort->TxBaseline + 3);
    }
    else if(cw->type == NHW_STATUS)
    {
    Move(rp, (x * w->RPort->TxWidth) + w->BorderLeft + 2,
            (y*(w->RPort->TxHeight+1)) + w->BorderTop +
            w->RPort->TxBaseline + 1);
    }
    else
    {
    Move(rp, (x * w->RPort->TxWidth) + w->BorderLeft + 2,
            (y*w->RPort->TxHeight) + w->BorderTop +
            w->RPort->TxBaseline + 1);
    }
}
void amii_delay_output (void)
void amii_destroy_nhwindow (winid win)
Definition at line 139 of file winfuncs.c.
References alwaysinvent, amii_destroy_nhwindow(), amii_oldmsg, amii_oldover, amii_wins, amiIDisplay, amii_WinDesc::canresp, amii_WinDesc::data, dismiss_nhwindow(), free(), amii_WinDesc::hook, amii_WinDesc::maxrow, amii_WinDesc::morestr, NHW_MAP, NHW_MENU, NHW_MESSAGE, NHW_OVER, NHW_TEXT, NULL, panic(), amii_WinDesc::resp, amii_WinDesc::type, type, amii_WinDesc::win, WIN_ERR, WIN_INVEN, WIN_MAP, WIN_MESSAGE, WIN_OVER, WIN_STATUS, winpanicstr, WINVERS_AMIV, and amii_DisplayDesc::xpix.
Referenced by amii_destroy_nhwindow(), and kill_nhwindows().
{
    int i;
    int type;
    register struct amii_WinDesc *cw;
    if(win == WIN_ERR || (cw = amii_wins[win]) == NULL)
    {
    panic(winpanicstr,win,"destroy_nhwindow");
    }
    if(WINVERS_AMIV)
    {
    if(cw->type == NHW_MAP)
    {
        /* If inventory is up, close it now, it will be freed later */
        if(alwaysinvent && WIN_INVEN != WIN_ERR &&
                amii_wins[ WIN_INVEN ] &&
                amii_wins[ WIN_INVEN ]->win)
        {
        dismiss_nhwindow(WIN_INVEN);
        }
        /* Tear down overview window if it is up */
        if(WIN_OVER != WIN_ERR)
        {
        amii_destroy_nhwindow(WIN_OVER);
        WIN_OVER = WIN_ERR;
        }
    }
    else if(cw->type == NHW_OVER)
    {
        struct Window *w = amii_wins[ WIN_OVER ]->win;
        amii_oldover.MinX = w->LeftEdge;
        amii_oldover.MinY = w->TopEdge;
        amii_oldover.MaxX = w->Width;
        amii_oldover.MaxY = w->Height;
        if(WIN_MESSAGE != WIN_ERR && amii_wins[
      WIN_MESSAGE ])
        {
        w = amii_wins[ WIN_MESSAGE ]->win;
        amii_oldmsg.MinX = w->LeftEdge;
        amii_oldmsg.MinY = w->TopEdge;
        amii_oldmsg.MaxX = w->Width;
        amii_oldmsg.MaxY = w->Height;
        SizeWindow(amii_wins[ WIN_MESSAGE ]->win,
            (amiIDisplay->xpix -
            amii_wins[ WIN_MESSAGE ]->win->LeftEdge) -
            amii_wins[ WIN_MESSAGE ]->win->Width,
            0);
        }
    }
    }
    /* Tear down the Intuition stuff */
    dismiss_nhwindow(win);
    type = cw->type;
    if(cw->resp) {
    free(cw->resp);
    cw->resp = NULL;
    }
    if(cw->canresp) {
    free(cw->canresp);
    cw->canresp = NULL;
    }
    if(cw->morestr) {
    free(cw->morestr);
    cw->morestr = NULL;
    }
    if(cw->hook) {
    free(cw->hook);
    cw->hook = NULL;
    }
    if(cw->data && (cw->type == NHW_MESSAGE ||
                cw->type == NHW_MENU || cw->type == NHW_TEXT))
    {
    for(i = 0; i < cw->maxrow; ++i)
    {
        if(cw->data[ i ])
        free(cw->data[ i ]);
    }
    free(cw->data);
    }
    free(cw);
    amii_wins[win] = NULL;
    /* Set globals to WIN_ERR for known one-of-a-kind windows. */
    if(win == WIN_MAP) WIN_MAP = WIN_ERR;
    else if(win == WIN_STATUS) WIN_STATUS = WIN_ERR;
    else if(win == WIN_MESSAGE) WIN_MESSAGE = WIN_ERR;
    else if(win == WIN_INVEN) WIN_INVEN = WIN_ERR;
}
void amii_display_file (const char * fn, boolean complain)
void amii_display_nhwindow (winid win, boolean blocking)
Definition at line 1541 of file winfuncs.c.
References amii_end_glyphout(), amii_wins, amii_WinDesc::curx, DoMenuScroll(), FLMAP_SKIP, flush_glyph_buffer(), Initialized, NHW_MAP, NHW_MENU, NHW_MESSAGE, NHW_STATUS, NHW_TEXT, NULL, outmore(), panic(), PICK_ONE, TRUE, amii_WinDesc::type, amii_WinDesc::wflags, amii_WinDesc::win, WIN_ERR, WIN_MAP, WIN_MESSAGE, and winpanicstr.
{
    menu_item *mip;
    int cnt;
    static int lastwin = -1;
    struct amii_WinDesc *cw;
    if(!Initialized)
    return;
    lastwin = win;
    if(win == WIN_ERR || (cw = amii_wins[win]) == NULL)
    panic(winpanicstr,win,"display_nhwindow");
    if(cw->type == NHW_MESSAGE)
    cw->wflags &= ~FLMAP_SKIP;
    if(cw->type == NHW_MESSAGE || cw->type == NHW_STATUS)
    return;
    if(WIN_MAP != WIN_ERR && amii_wins[ WIN_MAP ])
    {
    flush_glyph_buffer(amii_wins[ WIN_MAP ]->win);
    }
    if(cw->type == NHW_MENU || cw->type == NHW_TEXT)
    {
    cnt = DoMenuScroll(win, blocking, PICK_ONE, &mip);
    }
    else if(cw->type==NHW_MAP)
    {
    amii_end_glyphout(win);
    /* Do more if it is time... */
    if(blocking == TRUE && amii_wins[ WIN_MESSAGE ]->
      curx)
    {
        outmore(amii_wins[ WIN_MESSAGE ]);
    }
    }
}
int amii_doprev_message (void)
Definition at line 460 of file winstr.c.
References amii_cl_end(), amii_curs(), amii_setdrawpens(), amii_wins, amii_WinDesc::cols, amii_WinDesc::curx, amii_WinDesc::data, DisplayData(), max, amii_WinDesc::maxcol, amii_WinDesc::maxrow, MsgScroll, NHW_MESSAGE, NULL, panic(), scrollmsg, SetPropInfo(), SOFF, amii_WinDesc::vwy, amii_WinDesc::win, WIN_ERR, WIN_MESSAGE, and winpanicstr.
{
    struct amii_WinDesc *cw;
    struct Window *w;
    char *str;
    if(WIN_MESSAGE == WIN_ERR ||
    (cw = amii_wins[ WIN_MESSAGE ]) == NULL || (w = cw->
      win) == NULL)
    {
    panic(winpanicstr,WIN_MESSAGE, "doprev_message");
    }
    /* When an interlaced/tall screen is in use, the scroll bar will be there */
    /* Or in some other cases as well */
    if(scrollmsg)
    {
    struct Gadget *gd;
    struct PropInfo *pip;
    int hidden, topidx, i, total, wheight;
    for(gd = w->FirstGadget; gd && gd->GadgetID != 1;)
        gd = gd->NextGadget;
    if(gd)
    {
        pip = (struct PropInfo *)gd->SpecialInfo;
        wheight = (w->Height - w->BorderTop -
                w->BorderBottom - 2) / w->RPort->TxHeight;
        hidden = max(cw->maxrow - wheight, 0);
        topidx = (((ULONG)hidden * pip->VertPot) + (MAXPOT/2)) >> 16;
        for(total = i = 0; i < cw->maxrow; ++i)
        {
        if(cw->data[i][1] != 0)
            ++total;
        }
        i = 0;
        topidx -= wheight/4 + 1;
        if (topidx < 0)
        topidx = 0;
        SetPropInfo(w, &MsgScroll, wheight, total, topidx);
        DisplayData(WIN_MESSAGE, topidx);
    }
    return(0);
    }
    if(--cw->vwy < 0)
    {
    cw->maxcol = 0;
    DisplayBeep(NULL);
    str = "\0\0No more history saved...";
    }
    else
    str = cw->data[ cw->vwy ];
    amii_cl_end(cw, 0);
    amii_curs(WIN_MESSAGE, 1, 0);
    amii_setdrawpens(amii_wins[WIN_MESSAGE]->win,
      NHW_MESSAGE);
    Text(w->RPort,str+SOFF,strlen(str+SOFF));
    cw->curx = cw->cols + 1;
    return(0);
}
void amii_end_glyphout (winid window)
Definition at line 899 of file winchar.c.
References amii_wins, FLMAP_INGLYPH, iflags, NULL, panic(), usecolor, amii_WinDesc::wflags, and amii_WinDesc::win.
Referenced by amii_display_nhwindow(), and amiv_flush_glyph_buffer().
{
    struct amii_WinDesc *cw;
    struct Window *w;
    if((cw = amii_wins[ window ]) == (struct amii_WinDesc *)
      NULL)
    panic("bad window id %d in amii_end_glyphout()", window);
    if((cw->wflags & FLMAP_INGLYPH) == 0)
    return;
    cw->wflags &= ~(FLMAP_INGLYPH);
    if(!(w = cw->win))
    panic("bad winid %d, no window ptr set", window);
    /*
     * Clean up whatever is left in the buffer
     */
    iflags.use_color = usecolor;
    /*
     * Reset internal data structs
     */
    SetAPen(w->RPort, apensave);
    SetBPen(w->RPort, bpensave);
    SetDrMd(w->RPort, modesave);
    Move(w->RPort, xsave, ysave);
}
void amii_exit_nhwindows (const char * str)
char * amii_get_color_string ()
Definition at line 1163 of file winreq.c.
{
    int i;
    char s[ 10 ];
    static char buf[ BUFSZ ];
    *buf = 0;
    for(i = 0; i < min(32,amii_numcolors); ++i)
    {
        sprintf(s, "%s%03lx", i ? "/" : "", (long)flags.amii_curmap[ i ]);
    strcat(buf, s);
    }
    return(buf);
}
int amii_get_ext_cmd (void)
void amii_get_nh_event (void)
Definition at line 82 of file winkey.c.
{
    /* nothing now - later I have no idea. Is this just a Mac hook? */
}
void amii_getlin (const char * prompt, char * bufp)
Referenced by DoMenuScroll().
void amii_getret (void)
Definition at line 88 of file winkey.c.
References HackPort, raw_print, and WindowGetchar().
Referenced by Abort().
{
    register int c;
    raw_print("");
    raw_print("Press Return...");
    c = 0;
    while(c != '\n' && c != '\r')
    {
    if(HackPort)
        c = WindowGetchar();
    else
        c = getchar();
    }
    return;
}
void amii_init_nhwindows (int * , char **)
Definition at line 892 of file winfuncs.c.
References Abort(), alloc(), alwaysinvent, amii_clear_nhwindow(), amii_create_nhwindow(), amii_init_map, amii_initmap, amii_libvers, amii_numcolors, amii_putstr(), amii_scrnmode, amiIDisplay, bigscreen, BorderVectors1, BorderVectors2, C_BLACK, C_WHITE, amii_DisplayDesc::cols, COPYRIGHT_BANNER_A, COPYRIGHT_BANNER_B, COPYRIGHT_BANNER_C, flags, fname, FONTHEIGHT, FONTWIDTH, GfxBase, GTHackMenu, Hack80, HackFont, HackScreen, Initialized, amii_DisplayDesc::lastwin, max, MenuStrip, NewHackScreen, NHW_BASE, NULL, panic(), PATCHLEVEL, amii_DisplayDesc::rawprint, ReadTileImageFiles(), RogueFont, amii_DisplayDesc::rows, SCREENHEIGHT, scrntags, SIZEOF_DISKNAME, SM_Filter(), TextsFont, TextsFont13, amii_DisplayDesc::toplin, TRUE, VERSION_MAJOR, VERSION_MINOR, VisualInfo, WIDTH, WIN_BASE, WIN_ERR, WIN_INVEN, WIN_MAP, WIN_MESSAGE, WIN_OVER, WIN_STATUS, WINVERS_AMIV, amii_DisplayDesc::xpix, and amii_DisplayDesc::ypix.
{
    int i;
    struct Screen *wbscr;
    int forcenobig = 0;
    if(HackScreen)
    panic("init_nhwindows() called twice", 0);
    /* run args & set bigscreen from -L(1)/-l(-1) */
    {
    int lclargc = *argcp;
    int t;
    char **argv_in = argv;
    char **argv_out = argv;
    for(t=1;t<=lclargc;t++){
        if(!strcmp("-L",*argv_in) || !strcmp("-l",*argv_in)){
        bigscreen = (*argv_in[1]=='l') ? -1 : 1;
        /* and eat the flag */
        (*argcp)--;
        } else {
        *argv_out = *argv_in; /* keep the flag */
        argv_out++;
        }
        argv_in++;
    }
    *argv_out = 0;
    }
    WIN_MESSAGE = WIN_ERR;
    WIN_MAP = WIN_ERR;
    WIN_STATUS = WIN_ERR;
    WIN_INVEN = WIN_ERR;
    WIN_BASE = WIN_ERR;
    WIN_OVER = WIN_ERR;
    if ((IntuitionBase = (struct IntuitionBase *)
      OpenLibrary("intuition.library", amii_libvers)) == NULL)
    {
    Abort(AG_OpenLib | AO_Intuition);
    }
    if ((GfxBase = (struct GfxBase *)
          OpenLibrary("graphics.library", amii_libvers)) == NULL)
    {
    Abort(AG_OpenLib | AO_GraphicsLib);
    }
    if((LayersBase = (struct Library *)
        OpenLibrary("layers.library", amii_libvers)) == NULL)
    {
    Abort(AG_OpenLib | AO_LayersLib);
    }
    if ((GadToolsBase = OpenLibrary("gadtools.library", amii_libvers)) ==
      NULL) {
    Abort(AG_OpenLib | AO_GadTools);
    }
    if ((AslBase = OpenLibrary("asl.library", amii_libvers)) == NULL) {
    Abort(AG_OpenLib);
    }
    amiIDisplay=(struct amii_DisplayDesc *)alloc(sizeof(struct
      amii_DisplayDesc));
    memset(amiIDisplay, 0, sizeof(struct amii_DisplayDesc));
    /* Use Intuition sizes for overscan screens... */
    amiIDisplay->xpix = 0;
#ifdef INTUI_NEW_LOOK
    if(IntuitionBase->LibNode.lib_Version >= 37)
    {
    if(wbscr = LockPubScreen("Workbench"))
    {
        amiIDisplay->xpix = wbscr->Width;
        amiIDisplay->ypix = wbscr->Height;
        UnlockPubScreen(NULL, wbscr);
    }
    }
#endif
    if(amiIDisplay->xpix == 0)
    {
    amiIDisplay->ypix = GfxBase->NormalDisplayRows;
    amiIDisplay->xpix = GfxBase->NormalDisplayColumns;
    }
    amiIDisplay->cols = amiIDisplay->xpix /
      FONTWIDTH;
    amiIDisplay->toplin=0;
    amiIDisplay->rawprint=0;
    amiIDisplay->lastwin=0;
    if(bigscreen == 0)
    {
    if((GfxBase->ActiView->ViewPort->Modes & LACE) == LACE)
    {
        amiIDisplay->ypix *= 2;
        NewHackScreen.ViewModes |= LACE;
        bigscreen = 1;
    }
    else if(GfxBase->NormalDisplayRows >= 300 ||
         amiIDisplay->ypix >= 300)
    {
        bigscreen = 1;
    }
    }
    else if(bigscreen == -1)
    {
    bigscreen = 0;
    forcenobig = 1;
    }
    else if(bigscreen)
    {
    /* If bigscreen requested and we don't have enough rows in
     * noninterlaced mode, switch to interlaced...
     */
    if(GfxBase->NormalDisplayRows < 300)
    {
        amiIDisplay->ypix *= 2;
        NewHackScreen.ViewModes |= LACE;
    }
    }
    if(!bigscreen)
    {
        alwaysinvent = 0;
    }
    amiIDisplay->rows = amiIDisplay->ypix /
      FONTHEIGHT;
#ifdef HACKFONT
    /*
     * Load the fonts that we need.
     */
    if(DiskfontBase =
        OpenLibrary("diskfont.library", amii_libvers))
    {
    Hack80.ta_Name -= SIZEOF_DISKNAME;
    HackFont = OpenDiskFont(&Hack80);
    Hack80.ta_Name += SIZEOF_DISKNAME;
    /* Textsfont13 is filled in with "FONT=" settings. The default is
     * courier/13.
     */
    TextsFont = NULL;
    if(bigscreen)
        TextsFont = OpenDiskFont(&TextsFont13);
    /* Try hack/8 for texts if no user specified font */
    if(TextsFont == NULL)
    {
        Hack80.ta_Name -= SIZEOF_DISKNAME;
        TextsFont = OpenDiskFont(&Hack80);
        Hack80.ta_Name += SIZEOF_DISKNAME;
    }
    /* If no fonts, make everything topaz 8 for non-view windows.
     */
    Hack80.ta_Name = "topaz.font";
    RogueFont = OpenFont(&Hack80);
    if(!RogueFont) panic("Can't get topaz:8");
    if(!HackFont || !TextsFont)
    {
        if(!HackFont)
        {
        HackFont = OpenFont(&Hack80);
        if(!HackFont)
            panic("Can't get a map font, topaz:8");
        }
        if(!TextsFont)
        {
        TextsFont = OpenFont(&Hack80);
        if(!TextsFont)
            panic("Can't open text font");
        }
    }
    CloseLibrary(DiskfontBase);
    DiskfontBase = NULL;
    }
#endif
    /* Adjust getlin window size to font */
    if (TextsFont) {
    extern SHORT BorderVectors1[];
    extern SHORT BorderVectors2[];
    extern struct Gadget Gadget2;
    extern struct Gadget String;
    extern struct NewWindow StrWindow;
    BorderVectors1[2] += (TextsFont->tf_XSize-8)*6; /* strlen("Cancel") == 6 */
    BorderVectors1[4] += (TextsFont->tf_XSize-8)*6;
    BorderVectors1[5] += TextsFont->tf_YSize-8;
    BorderVectors1[7] += TextsFont->tf_YSize-8;
    BorderVectors2[2] += (TextsFont->tf_XSize-8)*6;
    BorderVectors2[4] += (TextsFont->tf_XSize-8)*6;
    BorderVectors2[5] += TextsFont->tf_YSize-8;
    BorderVectors2[7] += TextsFont->tf_YSize-8;
    Gadget2.TopEdge += TextsFont->tf_YSize-8;
    Gadget2.Width += (TextsFont->tf_XSize-8)*6;
    Gadget2.Height += TextsFont->tf_YSize-8;
    String.LeftEdge += (TextsFont->tf_XSize-8)*6;
    String.TopEdge += TextsFont->tf_YSize-8;
    String.Width += TextsFont->tf_XSize-8;
    String.Height += TextsFont->tf_YSize-8;
    StrWindow.Width += (TextsFont->tf_XSize-8)*7;
    StrWindow.Height += (TextsFont->tf_YSize-8)*2; /* Titlebar + 1 row of gadgets */
    }
    /* This is the size screen we want to open, within reason... */
    NewHackScreen.Width = max(WIDTH, amiIDisplay->
      xpix);
    NewHackScreen.Height = max(SCREENHEIGHT,
      amiIDisplay->ypix);
    {
    static char fname[18];
    sprintf(fname,"NetHack %d.%d.%d", VERSION_MAJOR, VERSION_MINOR,
      PATCHLEVEL);
    NewHackScreen.DefaultTitle=fname;
    }
#if 0
    NewHackScreen.BlockPen = C_BLACK;
    NewHackScreen.DetailPen = C_WHITE;
#endif
#ifdef INTUI_NEW_LOOK
    if(IntuitionBase->LibNode.lib_Version >= 37)
    {
        int i;
    struct DimensionInfo dims;
    DisplayInfoHandle handle;
    struct DisplayInfo disp;
    ULONG modeid = DEFAULT_MONITOR_ID|HIRES_KEY;
    NewHackScreen.Width = STDSCREENWIDTH;
    NewHackScreen.Height = STDSCREENHEIGHT;
#ifdef HACKFONT
    if (TextsFont) {
        NewHackScreen.Font = &TextsFont13;
    }
#endif
    if (amii_scrnmode == 0xffffffff) {
        struct ScreenModeRequester *SMR;
#ifdef __GNUC__
        SM_FilterHook.h_Entry = (void *)&SM_Filter;
#else
        SM_FilterHook.h_Entry = (ULONG(*)())SM_Filter;
#endif
        SM_FilterHook.h_Data = 0;
        SM_FilterHook.h_SubEntry = 0;
        SMR = AllocAslRequest(ASL_ScreenModeRequest,NULL);
        if (AslRequestTags(SMR,
                ASLSM_FilterFunc, (ULONG)&SM_FilterHook,
                TAG_END))
        amii_scrnmode = SMR->sm_DisplayID;
        else
        amii_scrnmode = 0;
        FreeAslRequest(SMR);
    }
    if(forcenobig == 0)
    {
        if((wbscr = LockPubScreen("Workbench")) != NULL ||
        (wbscr = LockPubScreen(NULL)) != NULL)
        {
        /* Get the default pub screen's size */
        modeid = GetVPModeID(&wbscr->ViewPort);
        if(modeid == INVALID_ID ||
            ModeNotAvailable(modeid) ||
            (handle = FindDisplayInfo(modeid)) == NULL ||
            GetDisplayInfoData(handle, (char *)&dims, sizeof(dims),
            DTAG_DIMS, modeid) <= 0 ||
            GetDisplayInfoData(handle, (char *)&disp, sizeof(disp),
            DTAG_DISP, modeid) <= 0)
        {
            modeid = DEFAULT_MONITOR_ID|HIRES_KEY;
            /* If the display database seems to not work, use the screen
             * dimensions
             */
            NewHackScreen.Height = wbscr->Height;
            NewHackScreen.Width = wbscr->Width;
        
            /*
             * Request LACE if it looks laced. For 2.1/3.0, we will get
             * promoted to the users choice of modes (if promotion is allowed)
             * If the user is using a dragable screen, things will get hosed
             * but that is life...
             */
            if(wbscr->ViewPort.Modes & LACE)
            NewHackScreen.ViewModes |= LACE;
            modeid = -1;
        }
        else
        {
            /* Use the display database to get the correct information */
            if(disp.PropertyFlags & DIPF_IS_LACE)
            NewHackScreen.ViewModes |= LACE;
            NewHackScreen.Height = dims.StdOScan.MaxY+1;
            NewHackScreen.Width = dims.StdOScan.MaxX+1;
        }
        NewHackScreen.TopEdge = 0;
        NewHackScreen.LeftEdge = 0;
        UnlockPubScreen(NULL, wbscr);
        }
    }
    for(i = 0; scrntags[i].ti_Tag != TAG_DONE; ++i)
    {
        switch(scrntags[i].ti_Tag)
        {
        case SA_DisplayID:
            if(!amii_scrnmode || ModeNotAvailable(amii_scrnmode))
            {
            if(ModeNotAvailable(modeid))
            {
                scrntags[i].ti_Tag = TAG_IGNORE;
                break;
            }
            else
                scrntags[i].ti_Data = (long)modeid;
            }
            else
            modeid = scrntags[i].ti_Data = (long)amii_scrnmode;
            if((handle = FindDisplayInfo(modeid)) != NULL &&
            GetDisplayInfoData(handle, (char *)&dims, sizeof(dims),
                DTAG_DIMS, modeid) > 0 &&
            GetDisplayInfoData(handle, (char *)&disp, sizeof(disp),
                DTAG_DISP, modeid) > 0)
            {
            if(disp.PropertyFlags & DIPF_IS_LACE)
                NewHackScreen.ViewModes |= LACE;
            NewHackScreen.Height = dims.StdOScan.MaxY+1;
            NewHackScreen.Width = dims.StdOScan.MaxX+1;
            }
            break;
        case SA_Pens:
            scrntags[i].ti_Data = (long)flags.amii_dripens;
            break;
        }
    }
    }
#endif
    if(WINVERS_AMIV)
    amii_bmhd = ReadTileImageFiles();
    else
    memcpy(amii_initmap, amii_init_map, sizeof(
      amii_initmap));
    memcpy(flags.amii_curmap,amii_initmap,sizeof(flags.amii_curmap));
    /* Find out how deep the screen needs to be, 32 planes is enough! */
    for(i = 0; i < 32; ++i)
    {
    if((1L << i) >= amii_numcolors)
        break;
    }
    NewHackScreen.Depth = i;
    /* If for some reason Height/Width became smaller than the required,
    have the required one */
    if (NewHackScreen.Height < SCREENHEIGHT)
    NewHackScreen.Height = SCREENHEIGHT;
    if (NewHackScreen.Width < WIDTH)
    NewHackScreen.Width = WIDTH;
#ifdef HACKFONT
    i = max(TextsFont->tf_XSize, HackFont->tf_XSize);
    if (NewHackScreen.Width < 80*i+4)
    NewHackScreen.Width = 80*i+4;
#endif
    /* While openscreen fails try fewer colors to see if that is the problem. */
    while((HackScreen = OpenScreen((void *)&NewHackScreen)) ==
      NULL)
    {
#ifdef TEXTCOLOR
    if(--NewHackScreen.Depth < 3)
#else
    if(--NewHackScreen.Depth < 2)
#endif
        Abort(AN_OpenScreen & ~AT_DeadEnd);
    }
    amii_numcolors = 1L << NewHackScreen.Depth;
    if(HackScreen->Height > 300 && forcenobig == 0)
    bigscreen = 1;
    else
    bigscreen = 0;
#ifdef INTUI_NEW_LOOK
    if(IntuitionBase->LibNode.lib_Version >= 37)
    PubScreenStatus(HackScreen, 0);
#endif
    amiIDisplay->ypix = HackScreen->Height;
    amiIDisplay->xpix = HackScreen->Width;
    LoadRGB4(&HackScreen->ViewPort, flags.amii_curmap,
      amii_numcolors);
    VisualInfo = GetVisualInfo(HackScreen, TAG_END);
    MenuStrip = CreateMenus(GTHackMenu, TAG_END);
    LayoutMenus(MenuStrip, VisualInfo, GTMN_NewLookMenus,
      TRUE, TAG_END);
    /* Display the copyright etc... */
    if(WIN_BASE == WIN_ERR)
    WIN_BASE = amii_create_nhwindow(NHW_BASE);
    amii_clear_nhwindow(WIN_BASE);
    amii_putstr(WIN_BASE, 0, "");
    amii_putstr(WIN_BASE, 0, "");
    amii_putstr(WIN_BASE, 0, "");
    amii_putstr(WIN_BASE, 0, COPYRIGHT_BANNER_A);
    amii_putstr(WIN_BASE, 0, COPYRIGHT_BANNER_B);
    amii_putstr(WIN_BASE, 0, COPYRIGHT_BANNER_C);
    amii_putstr(WIN_BASE, 0, "");
    Initialized = 1;
}
void amii_loadlib (void)
Definition at line 932 of file amiwind.c.
{
}
void amii_mark_synch (void)
Definition at line 2206 of file winfuncs.c.
References amiIDisplay.
{
    if(!amiIDisplay)
    fflush(stderr);
/* anything else? do we need this much? */
}
int amii_msgborder (struct Window *)
Definition at line 324 of file winstr.c.
Referenced by amii_addtopl(), amii_putstr(), amii_scrollmsg(), and outmore().
{
    register int bottom;
    /* There is a one pixel border at the borders, so subtract two */
    bottom = w->Height - w->BorderTop - w->BorderBottom - 2;
    bottom /= w->RPort->TxHeight;
    if(bottom > 0)
    --bottom;
    return(bottom);
}
int amii_nh_poskey (int * x, int * y, int * mod)
Definition at line 9 of file winkey.c.
References amii_wins, CLICK_1, cursor_on(), amii_WinDesc::disprows, FLMAP_SKIP, FLMSG_FIRST, WEVENT::key, lastevent, MAPFTBASELN, WEVENT::mouse, mxsize, mysize, panic(), rp, scrollmsg, WEVENT::type, type, WEVENT::un, WEKEY, WEMOUSE, WEUNK, amii_WinDesc::wflags, amii_WinDesc::win, WIN_ERR, WIN_MAP, WIN_MESSAGE, and WindowGetevent().
{
    struct amii_WinDesc *cw;
    WETYPE type;
    struct RastPort *rp;
    struct Window *w;
    if(cw = amii_wins[WIN_MESSAGE])
    {
    cw->wflags &= ~FLMAP_SKIP;
    if(scrollmsg)
        cw->wflags |= FLMSG_FIRST;
    cw->disprows = 0;
    }
    if(WIN_MAP != WIN_ERR && (cw = amii_wins[ WIN_MAP ]) && (w = cw->
      win))
    {
    cursor_on(WIN_MAP);
    }
    else
    panic("no MAP window opened for nh_poskey\n");
    rp = w->RPort;
    while(1)
    {
    type = WindowGetevent();
    if(type == WEMOUSE)
    {
        *mod = CLICK_1;
        if(lastevent.un.mouse.qual)
        *mod = 0;
        /* X coordinates are 1 based, Y are 1 based. */
        *x = ((lastevent.un.mouse.x - w->BorderLeft) / mxsize) + 1;
        *y = ((lastevent.un.mouse.y - w->BorderTop -
      MAPFTBASELN) /
            mysize) + 1;
#ifdef CLIPPING
        if(clipping)
        {
        *x += clipx;
        *y += clipy;
        }
#endif
        return(0);
    }
    else if(type == WEKEY)
    {
        lastevent.type = WEUNK;
        return(lastevent.un.key);
    }
    }
}
int amii_nhgetch (void)
Definition at line 65 of file winkey.c.
References amii_wins, cursor_on(), FLMAP_SKIP, amii_WinDesc::wflags, WIN_ERR, WIN_MAP, WIN_MESSAGE, and WindowGetchar().
{
    int ch;
    struct amii_WinDesc *cw=amii_wins[WIN_MESSAGE];
    if(WIN_MAP != WIN_ERR && amii_wins[ WIN_MAP ])
    {
    cursor_on(WIN_MAP);
    }
    if(cw)
    cw->wflags &= ~FLMAP_SKIP;
    ch = WindowGetchar();
    return(ch);
}
void amii_number_pad (int state)
void amii_player_selection (void)
void amii_print_glyph (winid win, xchar x, xchar y, int glyph)
Definition at line 2039 of file winfuncs.c.
References amiga_print_glyph(), amii_curs(), amii_wins, amii_WinDesc::curx, d_level::dlevel, Is_rogue_level, mapglyph(), NHW_MAP, NO_COLOR, NULL, panic(), REINCARNATION, amii_WinDesc::type, u, you::uz, WIN_ERR, winpanicstr, and WINVERS_AMIV.
{
    struct amii_WinDesc *cw;
    uchar ch;
    int color, och;
    extern const int zapcolors[];
    unsigned special;
    /* In order for the overview window to work, we can not clip here */
    if(!WINVERS_AMIV)
    {
#ifdef CLIPPING
    /* If point not in visible part of window just skip it */
    if(clipping)
    {
        if(x <= clipx || y < clipy || x >= clipxmax || y >= clipymax)
        return;
    }
#endif
    }
    if(win == WIN_ERR || (cw=amii_wins[win]) == NULL || cw->
      type != NHW_MAP)
    {
    panic(winpanicstr,win,"amii_print_glyph");
    }
#if 0
{
static int x=-1;
if(u.uz.dlevel != x){
 fprintf(stderr,"lvlchg: %d (%d)\n",u.uz.dlevel,Is_rogue_level(&
      u.uz));
 x = u.uz.dlevel;
}
}
#endif
    if(
    WINVERS_AMIV
#ifdef REINCARNATION
    && !Is_rogue_level(&u.uz)
#endif
    )
    {
    amii_curs(win,x,y);
    amiga_print_glyph(win,0,glyph);
    }
    else /* AMII, or Rogue level in either version */
    {
    /* map glyph to character and color */
        mapglyph(glyph, &och, &color, &special, x, y);
                /* XXX next if should be ifdef REINCARNATION */
    ch = (uchar)och;
    if(WINVERS_AMIV){ /* implies Rogue level here */
        amii_curs(win,x,y);
        amiga_print_glyph(win,NO_COLOR,ch + 10000);
    } else {
        /* Move the cursor. */
        amii_curs(win,x,y+2);
#ifdef TEXTCOLOR
        /* Turn off color if rogue level. */
# ifdef REINCARNATION
        if (Is_rogue_level(&u.uz))
        color = NO_COLOR;
# endif
        amiga_print_glyph(win,color,ch);
#else
        g_putch(ch); /* print the character */
#endif
        cw->curx++; /* one character over */
    }
    }
}
void amii_putstr (winid window, int attr, const char * str)
Definition at line 12 of file winstr.c.
References alloc(), amii_cl_end(), amii_create_nhwindow(), amii_curs(), amii_msgborder(), amii_scrollmsg(), amii_sethipens(), amii_wins, amiIDisplay, flag::botlx, amii_WinDesc::cols, CountLines(), amii_WinDesc::curx, amii_WinDesc::cury, amii_WinDesc::data, flags, FLMSG_FIRST, free(), iflags, amii_DisplayDesc::lastwin, max, amii_WinDesc::maxcol, amii_WinDesc::maxrow, instance_flags::msg_history, MsgScroll, NHW_BASE, NHW_MAP, NHW_MENU, NHW_MESSAGE, NHW_STATUS, NHW_TEXT, NULL, outmore(), outsubstr(), panic(), amii_WinDesc::rows, scrollmsg, SEL_ITEM, SetPropInfo(), SOFF, Strcpy, TBUFSZ, TextSpaces(), toplines, amii_WinDesc::type, VATTR, amii_WinDesc::vwy, amii_WinDesc::wflags, amii_WinDesc::win, WIN_BASE, WIN_ERR, WIN_MESSAGE, instance_flags::window_inited, winpanicstr, and WINVERS_AMIV.
Referenced by amii_add_menu(), amii_addtopl(), amii_init_nhwindows(), amii_raw_print(), amii_raw_print_bold(), and amiv_flush_glyph_buffer().
{
    int fudge;
    int len;
    struct Window *w;
    register struct amii_WinDesc *cw;
    char *ob;
    int i, j, n0, bottom, totalvis, wheight;
    static int wrapping = 0;
    /* Always try to avoid a panic when there is no window */
    if(window == WIN_ERR)
    {
    window = WIN_BASE;
    if(window == WIN_ERR)
        window = WIN_BASE = amii_create_nhwindow(
      NHW_BASE);
    }
    if(window == WIN_ERR || (cw = amii_wins[window]) == NULL)
    {
    iflags.window_inited=0;
    panic(winpanicstr,window, "putstr");
    }
    w = cw->win;
    if(!str) return;
    amiIDisplay->lastwin = window; /* do we care??? */
    /* NHW_MENU windows are not opened immediately, so check if we
     * have the window pointer yet
     */
    if(w)
    {
    /* Set the drawing mode and pen colors */
    SetDrMd(w->RPort, JAM2);
    amii_sethipens(w, cw->type, attr);
    }
    else if(cw->type != NHW_MENU && cw->type != NHW_TEXT)
    {
    panic("NULL window pointer in putstr 2: %d", window);
    }
    /* Okay now do the work for each type */
    switch(cw->type)
    {
    case NHW_MESSAGE:
    if(WINVERS_AMIV)
        fudge = 2;
    else
    {
        /* 8 for --more--, 1 for preceeding sp, 1 for putstr pad */
        fudge = 10;
    }
        /* There is a one pixel border at the borders, so subtract two */
        bottom = amii_msgborder(w);
    wheight = (w->Height - w->BorderTop -
                w->BorderBottom - 3) / w->RPort->TxHeight;
    
    if (scrollmsg || wheight > 1)
        fudge = 0;
    amii_scrollmsg(w, cw);
    while (isspace(*str)) str++;
    strncpy(toplines, str, TBUFSZ);
    toplines[ TBUFSZ - 1 ] = 0;
    /* For initial message to be visible, we need to explicitly position the
     * cursor. This flag, cw->curx == -1 is set elsewhere to force the
     * cursor to be repositioned to the "bottom".
     */
    if(cw->curx == -1)
    {
        amii_curs(WIN_MESSAGE, 1, bottom);
        cw->curx = 0;
    }
    /* If used all of history lines, move them down */
    if(cw->maxrow >= iflags.msg_history)
    {
        if(cw->data[ 0 ])
        free(cw->data[ 0 ]);
        memcpy(cw->data, &cw->data[ 1 ],
        (iflags.msg_history - 1) * sizeof(char *));
        cw->data[ iflags.msg_history - 1 ] =
                (char *) alloc(strlen(toplines) + 5);
        strcpy(cw->data[ i = iflags.msg_history - 1 ] +
                SOFF + (scrollmsg!=0), toplines);
    }
    else
    {
        /* Otherwise, allocate a new one and copy the line in */
        cw->data[ cw->maxrow ] = (char *)
                    alloc(strlen(toplines) + 5);
        strcpy(cw->data[ i = cw->maxrow++ ] +
                SOFF + (scrollmsg!=0), toplines);
    }
    cw->data[ i ][ SEL_ITEM ] = 1;
    cw->data[ i ][ VATTR ] = attr+1;
    if(scrollmsg)
    {
        cw->curx = 0;
        cw->data[ i ][2] = (cw->wflags & FLMSG_FIRST) ? '>' : ' ';
    }
    str = cw->data[i] + SOFF;
    if(cw->curx + strlen(str) >= (cw->cols-fudge))
    {
        int i;
        char *ostr = (char *)str;
        char *p;
        while(cw->curx + strlen(str) >= (cw->cols-fudge))
        {
        for(p=((char *)&str[ cw->cols-1 - cw->curx ])-fudge; !isspace(*p) && p > str;)
            --p;
        if (p < str) p = (char *)str;
        if(p == str) {
        /* p = (char *)&str[ cw->cols ]; */
            outmore(cw);
            continue;
        }
        i = (long)p-(long)str;
        outsubstr(cw, (char *)str, i, fudge);
        cw->curx += i;
        while(isspace(*p)) p++;
        str = p;
#if 0
        if(str != ostr) {
            outsubstr(cw, "+", 1, fudge);
            cw->curx+=2;
        }
#endif
        if(*str)
            amii_scrollmsg(w, cw);
        amii_cl_end(cw, cw->curx);
        }
        if(*str)
        {
        if(str != ostr)
        {
            outsubstr(cw, "+", 1, fudge);
            cw->curx+=2;
        }
        while (isspace(*str))
            ++str;
        outsubstr(cw, (char *)str, i = strlen((char *)str), fudge);
        cw->curx += i;
        amii_cl_end(cw, cw->curx);
        }
    }
    else
    {
        outsubstr(cw, (char *)str, i = strlen((char *)str), fudge);
        cw->curx += i;
        amii_cl_end(cw, cw->curx);
    }
    cw->wflags &= ~FLMSG_FIRST;
    len = 0;
    if(scrollmsg)
    {
        totalvis = CountLines(window);
        SetPropInfo(w, &MsgScroll,
          (w->Height-w->BorderTop-w->BorderBottom) / w->RPort->TxHeight,
          totalvis, totalvis);
    }
    i = strlen(toplines + SOFF);
    cw->maxcol = max(cw->maxcol, i);
    cw->vwy = cw->maxrow;
    break;
    case NHW_STATUS:
    if(cw->data[ cw->cury ] == NULL)
        panic("NULL pointer for status window");
    ob = &cw->data[cw->cury][j = cw->curx];
    if(flags.botlx) *ob = 0;
        /* Display when beam at top to avoid flicker... */
    WaitTOF();
    Text(w->RPort,(char *)str,strlen((char *)str));
    if(cw->cols > strlen(str))
        TextSpaces(w->RPort, cw->cols - strlen(str));
    (void) strncpy(cw->data[cw->cury], str, cw->cols);
    cw->data[cw->cury][cw->cols-1] = '\0'; /* null terminate */
    cw->cury = (cw->cury+1) % 2;
    cw->curx = 0;
    break;
    case NHW_MAP:
    case NHW_BASE:
    if (cw->type == NHW_BASE && wrapping) {
        amii_curs(window, cw->curx+1, cw->cury);
        TextSpaces(w->RPort, cw->cols);
        if (cw->cury < cw->rows) {
        amii_curs(window, cw->curx+1, cw->cury+1);
        TextSpaces(w->RPort, cw->cols);
        cw->cury--;
        }
    }
    amii_curs(window, cw->curx+1, cw->cury);
    Text(w->RPort,(char *)str,strlen((char *)str));
    cw->curx = 0;
        /* CR-LF is automatic in these windows */
    cw->cury++;
    if (cw->type == NHW_BASE && cw->cury >= cw->rows) {
        cw->cury = 0;
        wrapping = 1;
    }
    break;
    case NHW_MENU:
    case NHW_TEXT:
    /* always grows one at a time, but alloc 12 at a time */
    if(cw->cury >= cw->rows || !cw->data)
    {
        char **tmp;
        /* Allocate 12 more rows */
        cw->rows += 12;
        tmp = (char**) alloc(sizeof(char*) * cw->rows);
        /* Copy the old lines */
        for(i=0; i<cw->cury; i++)
        tmp[i] = cw->data[i];
        if(cw->data) {
        free(cw->data);
        cw->data = NULL;
        }
        cw->data = tmp;
        /* Null out the unused entries. */
        for(i=cw->cury; i<cw->rows; i++)
        cw->data[i] = 0;
    }
    if(!cw->data)
        panic("no data storage");
        /* Shouldn't need to do this, but... */
    if(cw->data && cw->data[cw->cury]) {
        free(cw->data[cw->cury]);
        cw->data[cw->cury] = NULL;
    }
    n0 = strlen(str)+1;
    cw->data[cw->cury] = (char*) alloc(n0+SOFF);
        /* avoid nuls, for convenience */
    cw->data[cw->cury][VATTR] = attr+1;
    cw->data[cw->cury][SEL_ITEM] = 0;
    Strcpy(cw->data[cw->cury] + SOFF, str);
    if(n0 > cw->maxcol) cw->maxcol = n0;
    if(++cw->cury > cw->maxrow) cw->maxrow = cw->cury;
    break;
    default:
    panic("Invalid or unset window type in putstr()");
    }
}
void amii_putsym (winid st, int i, int y, CHAR_P c)
Definition at line 409 of file winstr.c.
References amii_curs(), and amii_wins.
Referenced by amii_addtopl().
{
    amii_curs(st, i, y);
    Text(amii_wins[st]->win->RPort, &c, 1);
}
void amii_raw_print (const char * s)
Definition at line 2119 of file winfuncs.c.
References amii_putstr(), amii_rawprwin, amii_wins, amiIDisplay, init_nhwindows, Initialized, amii_DisplayDesc::rawprint, stdout, WIN_BASE, WIN_ERR, and WIN_MAP.
{
    int argc = 0;
    if(!s)
    return;
    if(amiIDisplay)
    amiIDisplay->rawprint++;
    if (!Initialized) { /* Not yet screen open ... */
        puts(s);
        fflush(stdout);
        return;
    }
    if(Initialized == 0 && WIN_BASE == WIN_ERR)
        init_nhwindows(&argc, (char **)0);
    if(amii_rawprwin != WIN_ERR)
    amii_putstr(amii_rawprwin, 0, s);
    else if(WIN_MAP != WIN_ERR && amii_wins[ WIN_MAP ])
    amii_putstr(WIN_MAP, 0, s);
    else if(WIN_BASE != WIN_ERR && amii_wins[ WIN_BASE ])
    amii_putstr(WIN_BASE, 0, s);
    else
    {
    puts(s);
    fflush(stdout);
    }
}
void amii_raw_print_bold (const char * s)
Definition at line 2156 of file winfuncs.c.
References amii_putstr(), amii_rawprwin, amii_wins, amiIDisplay, init_nhwindows, Initialized, printf, amii_DisplayDesc::rawprint, stdout, WIN_BASE, WIN_ERR, and WIN_MAP.
{
    int argc = 0;
    if(!s)
    return;
    if(amiIDisplay)
    amiIDisplay->rawprint++;
    if (!Initialized) { /* Not yet screen open ... */
        puts(s);
        fflush(stdout);
        return;
    }
    if(Initialized == 0 && WIN_BASE == WIN_ERR)
        init_nhwindows(&argc, (char **)0);
    if(amii_rawprwin != WIN_ERR)
    amii_putstr(amii_rawprwin, 1, s);
    else if(WIN_MAP != WIN_ERR && amii_wins[ WIN_MAP ])
    amii_putstr(WIN_MAP, 1, s);
    else if(WIN_BASE != WIN_ERR && amii_wins[ WIN_BASE ])
    amii_putstr(WIN_BASE, 1, s);
    else
    {
    printf("\33[1m%s\33[0m\n",s);
    fflush(stdout);
    }
}
void amii_remember_topl (void)
Definition at line 452 of file winstr.c.
{
    /* ignore for now. I think this will be done automatically by
     * the code writing to the message window, but I could be wrong.
     */
}
void amii_resume_nhwindows (void)
Definition at line 1994 of file winfuncs.c.
References HackScreen.
{
    if(HackScreen)
    ScreenToFront(HackScreen);
}
void amii_scrollmsg (register struct Window * w, register struct amii_WinDesc * cw)
void amii_set_text_font (char * font, int size)
Definition at line 1748 of file winfuncs.c.
References amii_libvers, amii_wins, bigscreen, HackScreen, MAXWIN, NHW_BASE, NHW_MAP, NHW_MESSAGE, NHW_OVER, NHW_STATUS, NULL, TextsFont, TextsFont13, amii_WinDesc::type, and amii_WinDesc::win.
Referenced by parse_config_line().
{
    register int i;
    register struct amii_WinDesc *cw;
    int osize = TextsFont13.ta_YSize;
    static char nname[ 100 ];
    strncpy(nname, name, sizeof(nname) - 1);
    nname[ sizeof(nname) - 1 ] = 0;
    TextsFont13.ta_Name = nname;
    TextsFont13.ta_YSize = size;
    /* No alternate text font allowed for 640x269 or smaller */
    if(!HackScreen || !bigscreen)
    return;
    /* Look for windows to set, and change them */
    if(DiskfontBase =
        OpenLibrary("diskfont.library", amii_libvers))
    {
    TextsFont = OpenDiskFont(&TextsFont13);
    for(i = 0; TextsFont && i < MAXWIN; ++i)
    {
        if((cw = amii_wins[ i ]) && cw->win != NULL)
        {
            switch(cw->type)
            {
            case NHW_STATUS:
            MoveWindow(cw->win, 0, -(size - osize) * 2);
            SizeWindow(cw->win, 0, (size - osize) * 2);
            SetFont(cw->win->RPort, TextsFont);
            break;
            case NHW_MESSAGE:
            case NHW_MAP:
            case NHW_BASE:
            case NHW_OVER:
            SetFont(cw->win->RPort, TextsFont);
            break;
            }
        }
    }
    }
    CloseLibrary(DiskfontBase);
    DiskfontBase = NULL;
}
void amii_setclipped (void)
Definition at line 2234 of file winfuncs.c.
References CO, LI, and TRUE.
Referenced by amii_create_nhwindow().
{
#ifdef CLIPPING
    clipping = TRUE;
    clipx=clipy=0;
    clipxmax=CO;
    clipymax=LI;
/* some of this is now redundant with top of amii_cliparound XXX */
#endif
}
void amii_setdrawpens (struct Window * , int type)
Definition at line 1378 of file winfuncs.c.
References amii_menuAPen, amii_menuBPen, amii_msgAPen, amii_msgBPen, amii_otherAPen, amii_otherBPen, amii_statAPen, amii_statBPen, amii_textAPen, amii_textBPen, C_BLACK, C_WHITE, NHW_BASE, NHW_MAP, NHW_MENU, NHW_MESSAGE, NHW_OVER, NHW_STATUS, and NHW_TEXT.
Referenced by amii_doprev_message().
{
    switch(type)
    {
    case NHW_MESSAGE:
    SetAPen(w->RPort, amii_msgAPen);
    SetBPen(w->RPort, amii_msgBPen);
    break;
    case NHW_STATUS:
    SetAPen(w->RPort, amii_statAPen);
    SetBPen(w->RPort, amii_statBPen);
    break;
    case NHW_MENU:
    SetAPen(w->RPort, amii_menuAPen);
    SetBPen(w->RPort, amii_menuBPen);
    break;
    case NHW_TEXT:
    SetAPen(w->RPort, amii_textAPen);
    SetBPen(w->RPort, amii_textBPen);
    break;
    case NHW_MAP:
    case NHW_BASE:
    case NHW_OVER:
    SetAPen(w->RPort, C_WHITE);
    SetBPen(w->RPort, C_BLACK);
    break;
    default:
    SetAPen(w->RPort, amii_otherAPen);
    SetBPen(w->RPort, amii_otherBPen);
    break;
    }
}
void amii_setfillpens (struct Window * , int type)
Definition at line 1343 of file winfuncs.c.
References amii_menuBPen, amii_msgBPen, amii_otherBPen, amii_statBPen, amii_textBPen, C_BLACK, NHW_BASE, NHW_MAP, NHW_MENU, NHW_MESSAGE, NHW_OVER, NHW_STATUS, and NHW_TEXT.
Referenced by amii_clear_nhwindow(), and DoMenuScroll().
{
    switch(type)
    {
    case NHW_MESSAGE:
    SetAPen(w->RPort, amii_msgBPen);
    SetBPen(w->RPort, amii_msgBPen);
    break;
    case NHW_STATUS:
    SetAPen(w->RPort, amii_statBPen);
    SetBPen(w->RPort, amii_statBPen);
    break;
    case NHW_MENU:
    SetAPen(w->RPort, amii_menuBPen);
    SetBPen(w->RPort, amii_menuBPen);
    break;
    case NHW_TEXT:
    SetAPen(w->RPort, amii_textBPen);
    SetBPen(w->RPort, amii_textBPen);
    break;
    case NHW_MAP:
    case NHW_BASE:
    case NHW_OVER:
    default:
    SetAPen(w->RPort, C_BLACK);
    SetBPen(w->RPort, C_BLACK);
    break;
    case -2:
    SetAPen(w->RPort, amii_otherBPen);
    SetBPen(w->RPort, amii_otherBPen);
    break;
    }
}
void amii_sethipens (struct Window * , int type, int attr)
Definition at line 1312 of file winfuncs.c.
References amii_menuAPen, amii_menuBPen, amii_msgAPen, amii_msgBPen, amii_otherAPen, amii_otherBPen, amii_statAPen, amii_statBPen, amii_textAPen, amii_textBPen, C_BLACK, C_RED, C_WHITE, NHW_MENU, NHW_MESSAGE, NHW_STATUS, and NHW_TEXT.
Referenced by amii_putstr().
{
    switch(type)
    {
    default:
        SetAPen(w->RPort, attr ? C_RED : amii_otherAPen);
        SetBPen(w->RPort, C_BLACK);
        break;
    case NHW_STATUS:
        SetAPen(w->RPort, attr ? C_WHITE : amii_statAPen);
        SetBPen(w->RPort, amii_statBPen);
        break;
    case NHW_MESSAGE:
        SetAPen(w->RPort, attr ? C_WHITE : amii_msgAPen);
        SetBPen(w->RPort, amii_msgBPen);
        break;
    case NHW_MENU:
        SetAPen(w->RPort, attr ? C_BLACK : amii_menuAPen);
        SetBPen(w->RPort, amii_menuBPen);
        break;
    case NHW_TEXT:
        SetAPen(w->RPort, attr ? C_BLACK : amii_textAPen);
        SetBPen(w->RPort, amii_textBPen);
    case -2:
        SetBPen(w->RPort, amii_otherBPen);
        SetAPen(w->RPort, attr ? C_RED : amii_otherAPen);
        break;
    }
}
void amii_start_menu (winid window)
Definition at line 11 of file winmenu.c.
References alwaysinvent, amii_clear_nhwindow(), amii_wins, amii_menu::chr, amii_menu::count, menu::count, amii_WinDesc::cury, amii_WinDesc::data, free(), amii_menu::items, amii_WinDesc::maxcol, amii_WinDesc::maxrow, amii_WinDesc::menu, amii_WinDesc::morestr, amii_mi::next, NHW_MENU, NHW_MESSAGE, NHW_TEXT, NULL, panic(), amii_WinDesc::rows, amii_WinDesc::type, amii_WinDesc::wasup, amii_WinDesc::win, WIN_ERR, WIN_INVEN, and winpanicstr.
{
    register int i;
    register struct amii_WinDesc *cw;
    register amii_menu_item *mip;
    if(window == WIN_ERR || (cw = amii_wins[window]) == NULL || cw->
      type != NHW_MENU)
    panic(winpanicstr,window, "start_menu");
    amii_clear_nhwindow(window);
    if(cw->data && (cw->type == NHW_MESSAGE ||
        cw->type == NHW_MENU || cw->type == NHW_TEXT))
    {
    for(i = 0; i < cw->maxrow; ++i)
    {
        if(cw->data[ i ])
        free(cw->data[ i ]);
    }
    free(cw->data);
    cw->data = NULL;
    }
    for(mip = cw->menu.items, i = 0; (mip = cw->menu.items) && i < cw->
      menu.count; ++i)
    {
    cw->menu.items = mip->next;
        free(mip);
    }
    cw->menu.items = 0;
    cw->menu.count = 0;
    cw->menu.chr = 'a';
    if(cw->morestr) free(cw->morestr);
    cw->morestr = NULL;
    if(window == WIN_INVEN && cw->win != NULL)
    {
    if(alwaysinvent)
        cw->wasup = 1;
    }
    cw->cury = cw->rows = cw->maxrow = cw->maxcol = 0;
    return;
}
void amii_suspend_nhwindows (const char * str)
void amii_update_inventory (void)
Definition at line 2192 of file winfuncs.c.
References amii_wins, FALSE, NHW_MENU, NULL, amii_WinDesc::type, amii_WinDesc::win, WIN_ERR, and WIN_INVEN.
{
    register struct amii_WinDesc *cw;
    if(WIN_INVEN != WIN_ERR && (cw = amii_wins[
      WIN_INVEN ]) &&
                cw->type == NHW_MENU && cw->win)
    {
    display_inventory(NULL, FALSE);
    }
}
void amii_wait_synch (void)
Definition at line 2217 of file winfuncs.c.
References amii_wins, amiIDisplay, display_nhwindow, flush_glyph_buffer(), amii_DisplayDesc::rawprint, TRUE, amii_WinDesc::win, WIN_ERR, and WIN_MAP.
{
    if(!amiIDisplay || amiIDisplay->rawprint)
    {
    if(amiIDisplay) amiIDisplay->rawprint=0;
    }
    else
    {
    if(WIN_MAP != WIN_ERR)
    {
        display_nhwindow(WIN_MAP,TRUE);
        flush_glyph_buffer(amii_wins[ WIN_MAP ]->
      win);
    }
    }
}
char amii_yn_function (const char * prompt, const char * resp, char def)
int amikbhit (void)
Referenced by kbhit().
void amiv_loadlib (void)
Definition at line 927 of file amiwind.c.
{
}
char* basename (char * str)
Definition at line 630 of file winreq.c.
Referenced by fqname(), and main().
{
    char *t;
    t = strrchr(str, '/');
    if(!t)
    t = strrchr(str, ':');
    if(!t)
    t = str;
    else
    ++t;
    return(t);
}
void bell (void)
void CleanUp (void)
Definition at line 799 of file amiwind.c.
Referenced by nethack_exit().
{
    amii_cleanup();
}
void clear_icon (void)
void CloseShWindow (struct Window * win)
Referenced by dismiss_nhwindow().
int ConvertKey (struct IntuiMessage * message)
Referenced by DoMenuScroll().
long CountLines (winid)
Definition at line 1277 of file winmenu.c.
References amii_wins, amii_WinDesc::cols, amii_WinDesc::data, amii_menu::items, amii_WinDesc::maxrow, amii_WinDesc::menu, NHW_MESSAGE, panic(), pictdata, SEL_ITEM, SOFF, amii_WinDesc::type, amii_WinDesc::win, WIN_ERR, WIN_INVEN, winpanicstr, WINVERS_AMIV, and PDAT::xsize.
Referenced by amii_putstr(), DoMenuScroll(), and ReDisplayData().
{
    int txwd;
    amii_menu_item *mip;
    register char *t;
    register struct amii_WinDesc *cw;
    register struct Window *w;
    register int i, disprow, len;
    int col = -1;
    if(win == WIN_ERR || !(cw = amii_wins[win]) || !(w = cw->
      win))
    {
    panic(winpanicstr, win, "No Window in CountLines");
    }
    txwd = w->RPort->TxWidth;
    if(WINVERS_AMIV)
    {
    if(win == WIN_INVEN)
    {
        cw->cols = (w->Width - w->BorderLeft -
            w->BorderRight - 4 - pictdata.xsize - 3) / txwd;
    }
    else
        cw->cols = (w->Width - w->BorderLeft - w->BorderRight - 4) / txwd;
    }
    else
    {
    cw->cols = (w->Width - w->BorderLeft - w->BorderRight - 4) / txwd;
    }
    disprow = cw->maxrow;
    mip = cw->menu.items;
    for(col = i = 0; i < cw->maxrow; ++i)
    {
    t = cw->data[ i ] + SOFF;
    if(cw->type == NHW_MESSAGE && cw->data[ i ][ SEL_ITEM ] < 0)
        --disprow;
    else
        col = 0;
    while(*t)
    {
        len = strlen(t);
        if(col + len > cw->cols)
        len = cw->cols - col;
        while(len > 0)
        {
            if(!t[len] || t[len] == ' ')
            break;
            --len;
        }
        if(len == 0) {
        while (*t && *t != ' ') {
            t++; col++;
        }
        } else {
        t += len;
        col += len;
        }
        if(*t)
        {
        while(*t == ' ')
            ++t;
        col = 0;
        ++disprow;
        }
    }
    }
    return(disprow);
}
void cursor_off (winid window)
Definition at line 1836 of file winfuncs.c.
References amii_wins, amii_WinDesc::curs_apen, amii_WinDesc::curs_bpen, CURSOR_CHAR, cursor_common(), amii_WinDesc::cursx, amii_WinDesc::cursy, FLMAP_CURSUP, iflags, Is_rogue_level, NHW_MAP, NULL, panic(), rp, amii_WinDesc::type, u, you::uz, amii_WinDesc::wflags, amii_WinDesc::win, WIN_ERR, instance_flags::window_inited, winpanicstr, and WINVERS_AMIV.
Referenced by amii_clear_nhwindow(), amii_cliparound(), amiv_flush_glyph_buffer(), and cursor_on().
{
    register struct amii_WinDesc *cw;
    register struct Window *w;
    register struct RastPort *rp;
    int curx, cury;
    int x, y;
    long dmode;
    short apen, bpen;
    unsigned char ch;
    if(window == WIN_ERR || (cw = amii_wins[window]) == NULL)
    {
    iflags.window_inited=0;
    panic(winpanicstr,window, "cursor_off");
    }
    if(!(cw->wflags & FLMAP_CURSUP))
    return;
    w = cw->win;
    if(!w)
    return;
    cw->wflags &= ~FLMAP_CURSUP;
    rp = w->RPort;
    /* Save the current information */
    curx = rp->cp_x;
    cury = rp->cp_y;
    x = cw->cursx;
    y = cw->cursy;
    dmode = rp->DrawMode;
    apen = rp->FgPen;
    bpen = rp->BgPen;
    SetAPen(rp, cw->curs_apen);
    SetBPen(rp, cw->curs_bpen);
    SetDrMd(rp, COMPLEMENT);
/*printf("CURSOR OFF: %d %d\n",x,y);*/
    if(WINVERS_AMIV && cw->type == NHW_MAP)
    {
    cursor_common(rp, x, y);
    if(Is_rogue_level(&u.uz))
        Move(rp,curx,cury);
    }
    else
    {
    ch = CURSOR_CHAR;
    Move(rp, x, y);
    Text(rp, &ch, 1);
    /* Put back the other stuff */
    Move(rp, curx, cury);
    }
    SetDrMd(rp, dmode);
    SetAPen(rp, apen);
    SetBPen(rp, bpen);
}
void cursor_on (winid window)
Definition at line 1900 of file winfuncs.c.
References amii_wins, amii_WinDesc::curs_apen, amii_WinDesc::curs_bpen, CURSOR_CHAR, cursor_common(), cursor_off(), amii_WinDesc::cursx, amii_WinDesc::cursy, FLMAP_CURSUP, iflags, Is_rogue_level, NHW_MAP, NULL, panic(), rp, amii_WinDesc::type, u, you::uz, amii_WinDesc::wflags, amii_WinDesc::win, WIN_ERR, instance_flags::window_inited, winpanicstr, and WINVERS_AMIV.
Referenced by amii_nh_poskey(), and amii_nhgetch().
{
    int x, y;
    register struct amii_WinDesc *cw;
    register struct Window *w;
    register struct RastPort *rp;
    unsigned char ch;
    long dmode;
    short apen, bpen;
    if(window == WIN_ERR || (cw = amii_wins[window]) == NULL)
    {
    /* tty does this differently - is this OK? */
    iflags.window_inited=0;
    panic(winpanicstr,window, "cursor_on");
    }
/*printf("CURSOR ON: %d %d\n",cw->win->RPort->cp_x, cw->win->RPort->cp_y);*/
    if((cw->wflags & FLMAP_CURSUP))
    cursor_off(window);
    w = cw->win;
    if(!w)
    return;
    cw->wflags |= FLMAP_CURSUP;
    rp = w->RPort;
    /* Save the current information */
#ifdef DISPMAP
    if(WINVERS_AMIV && cw->type == NHW_MAP && !
      Is_rogue_level(&u.uz))
    x = cw->cursx = (rp->cp_x & -8) + 8;
    else
#endif
    x = cw->cursx = rp->cp_x;
    y = cw->cursy = rp->cp_y;
    apen = rp->FgPen;
    bpen = rp->BgPen;
    dmode = rp->DrawMode;
    /* Draw in complement mode. The cursor body will be C_WHITE */
    cw->curs_apen = 0xff; /* Last color/all planes, regardless of depth */
    cw->curs_bpen = 0xff;
    SetAPen(rp, cw->curs_apen);
    SetBPen(rp, cw->curs_bpen);
    SetDrMd(rp, COMPLEMENT);
    if(WINVERS_AMIV && cw->type == NHW_MAP)
    {
    cursor_common(rp, x, y);
    }
    else
    {
    Move(rp, x, y);
    ch = CURSOR_CHAR;
    Text(rp, &ch, 1);
    Move(rp, x, y);
    }
    SetDrMd(rp, dmode);
    SetAPen(rp, apen);
    SetBPen(rp, bpen);
}
char* dirname (char * str)
Definition at line 609 of file winreq.c.
Referenced by EditColor().
{
    char *t, c;
    static char dir[ 300 ];
    t = strrchr(str, '/');
    if(!t)
    t = strrchr(str, ':');
    if(!t)
    t = str;
    else
    {
        c = *t;
        *t = 0;
        strcpy(dir, str);
        *t = c;
    }
    return(dir);
}
void dismiss_nhwindow (winid win)
Definition at line 1477 of file winfuncs.c.
References amii_wins, CloseShWindow(), FreeNewWindow(), amii_WinDesc::newwin, NHW_BASE, NHW_MAP, NHW_MESSAGE, NHW_OVER, NHW_STATUS, NULL, panic(), amii_WinDesc::type, amii_WinDesc::win, WIN_ERR, WIN_INVEN, and winpanicstr.
Referenced by amii_destroy_nhwindow(), and amii_select_menu().
{
    register struct Window *w;
    register struct amii_WinDesc *cw;
    if(win == WIN_ERR || (cw = amii_wins[win]) == NULL)
    {
    panic(winpanicstr,win, "dismiss_nhwindow");
    }
    w = cw->win;
    if(w)
    {
    /* All windows have this stuff attached to them. */
    if(cw->type == NHW_MAP ||
        cw->type == NHW_OVER ||
        cw->type == NHW_BASE ||
        cw->type == NHW_MESSAGE ||
        cw->type == NHW_STATUS)
    {
        ClearMenuStrip(w);
    }
    /* Save where user like inventory to appear */
    if(win == WIN_INVEN)
    {
        lastinvent.MinX = w->LeftEdge;
        lastinvent.MinY = w->TopEdge;
        lastinvent.MaxX = w->Width;
        lastinvent.MaxY = w->Height;
    }
    /* Close the window */
    CloseShWindow(w);
    cw->win = NULL;
    /* Free copy of NewWindow structure for TEXT/MENU windows. */
    if(cw->newwin)
        FreeNewWindow((void *)cw->newwin);
    cw->newwin = NULL;
    }
}
void DispCol (struct Window * w, int idx, UWORD * colors)
Definition at line 844 of file winreq.c.
References amii_otherBPen, buf, C_RED, Col_Save, COLDEF::defval, COLDEF::name, and WINVERS_AMIV.
Referenced by DrawCol(), and EditColor().
{
    char buf[ 50 ];
    char *colname, *defval;
    if(WINVERS_AMIV)
    {
    colname = amiv_colnames[idx].name;
    defval = amiv_colnames[idx].defval;
    }
    else
    {
    colname = amii_colnames[idx].name;
    defval = amii_colnames[idx].defval;
    }
    if(colname == NULL)
    {
    colname = "unknown";
    defval = "unknown";
    }
    Move(w->RPort, Col_Save.LeftEdge,
    Col_Save.TopEdge - 7);
    sprintf(buf, "%s=%03x default=%s%s", colname, colors[idx], defval,
    " "+strlen(colname)+1);
    SetAPen(w->RPort, C_RED);
    SetBPen(w->RPort, amii_otherBPen);
    SetDrMd(w->RPort, JAM2);
    Text(w->RPort, buf, strlen(buf));
}
void DisplayData (winid win, int start)
Definition at line 1350 of file winmenu.c.
References amiga_print_glyph(), amii_cl_end(), amii_curs(), amii_menuAPen, amii_menuBPen, amii_msgAPen, amii_msgBPen, amii_textAPen, amii_textBPen, amii_wins, C_BLUE, C_RED, amii_WinDesc::cols, amii_WinDesc::data, FindLine(), amii_mi::glyph, amii_menu::items, max, amii_WinDesc::maxrow, amii_WinDesc::menu, amii_mi::next, NHW_MENU, NHW_MESSAGE, NHW_TEXT, NO_GLYPH, panic(), pictdata, amii_WinDesc::rows, rp, SEL_ITEM, amii_mi::selected, SOFF, amii_WinDesc::type, amii_WinDesc::win, WIN_ERR, WIN_INVEN, winpanicstr, WINVERS_AMIV, PDAT::xsize, and PDAT::ysize.
Referenced by amii_doprev_message(), DoMenuScroll(), and ReDisplayData().
{
    int txwd;
    amii_menu_item *mip;
    register char *t;
    register struct amii_WinDesc *cw;
    register struct Window *w;
    register struct RastPort *rp;
    register int i, disprow, len, wheight;
    int whichcolor = -1;
    int col;
    if(win == WIN_ERR || !(cw = amii_wins[win]) || !(w = cw->
      win))
    {
    panic(winpanicstr, win, "No Window in DisplayData");
    }
    rp = w->RPort;
    SetDrMd(rp, JAM2);
    if(WINVERS_AMIV && win == WIN_INVEN)
    {
    wheight = (w->Height - w->BorderTop - w->BorderBottom - 2) /
            max(rp->TxHeight, pictdata.ysize + 3);
    }
    else
    {
    wheight = (w->Height - w->BorderTop - w->BorderBottom - 2) /
            rp->TxHeight;
    }
    cw->rows = wheight;
    txwd = rp->TxWidth;
    if(WINVERS_AMIV)
    {
    if(win == WIN_INVEN)
    {
        cw->cols = (w->Width - w->BorderLeft -
            w->BorderRight - 4 - pictdata.xsize - 3) / txwd;
    }
    else
        cw->cols = (w->Width - w->BorderLeft - w->BorderRight - 4) / txwd;
    }
    else
    {
    cw->cols = (w->Width - w->BorderLeft - w->BorderRight - 4) / txwd;
    }
    /* Get the real line to display at */
    start = FindLine(win, start);
    mip = cw->menu.items;
    for(i = 0; mip && i < start; ++i)
    {
    mip = mip->next;
    }
    /* Skip any initial response to a previous line */
    if(cw->type == NHW_MESSAGE && mip && mip->selected < 0)
    ++start;
    if(WINVERS_AMIV && cw->type == NHW_MESSAGE)
    SetAPen(rp, amii_msgAPen);
    
    for(disprow = i = start; disprow < wheight + start; i++)
    {
    /* Just erase unused lines in the window */
        if(i >= cw->maxrow)
        {
        if (WINVERS_AMIV && win == WIN_INVEN) {
        amii_curs(win, 0, disprow - start);
        amiga_print_glyph(win, 0, NO_GLYPH);
        }
        amii_curs(win, 1, disprow - start);
        amii_cl_end(cw, 0);
        ++disprow;
        continue;
        }
    /* Any string with a highlighted attribute goes
     * onto the end of the current line in the message window.
     */
    if(cw->type == NHW_MESSAGE)
        SetAPen(rp, cw->data[ i ][ SEL_ITEM ] < 0 ? C_RED :
      amii_msgAPen);
    /* Selected text in the message window goes onto the end of the current line */
    if(cw->type != NHW_MESSAGE || cw->data[ i ][ SEL_ITEM ] >= 0)
    {
        amii_curs(win, 1, disprow - start);
        if(WINVERS_AMIV && win == WIN_INVEN)
        {
        if(mip)
            amiga_print_glyph(win, 0, mip->glyph);
        amii_curs(win, 1, disprow - start);
        }
        col = 0;
    }
    /* If this entry is to be highlighted, do so */
    if(mip && mip->selected != 0)
    {
        if(whichcolor != 1)
        {
        SetDrMd(rp, JAM2);
        if(WINVERS_AMIV)
        {
            SetAPen(rp, amii_menuBPen);
            SetBPen(rp, C_BLUE);
        }
        else
        {
            SetAPen(rp, C_BLUE);
            SetBPen(rp, amii_menuAPen);
        }
        whichcolor = 1;
        }
    }
    else if(whichcolor != 2)
    {
        SetDrMd(rp, JAM2);
        if(cw->type == NHW_MESSAGE)
        {
        SetAPen(rp, amii_msgAPen);
        SetBPen(rp, amii_msgBPen);
        }
        else if(cw->type == NHW_MENU)
        {
        SetAPen(rp, amii_menuAPen);
        SetBPen(rp, amii_menuBPen);
        }
        else if(cw->type == NHW_TEXT)
        {
        SetAPen(rp, amii_textAPen);
        SetBPen(rp, amii_textBPen);
        }
        whichcolor = 2;
    }
    /* Next line out, wrap if too long */
    t = cw->data[ i ] + SOFF;
    ++disprow;
    col = 0;
    while(*t)
    {
        len = strlen(t);
        if(len > (cw->cols - col))
        len = cw->cols - col;
        while(len > 0)
        {
            if(!t[len] || t[len] == ' ')
            break;
            --len;
        }
        if(len == 0) {
        Text(rp, t, cw->cols - col);
        while (*t && *t != ' ') {
            t++; col++;
        }
        } else {
        Text(rp, t, len);
        t += len;
        col += len;
        }
        amii_cl_end(cw, col);
        if(*t)
        {
        ++disprow;
        /* Stop at the bottom of the window */
        if(disprow > wheight + start)
            break;
        while(*t == ' ')
            ++t;
        amii_curs(win, 1, disprow - start - 1);
        if(mip && win == WIN_INVEN && WINVERS_AMIV)
        {
            /* Erase any previous glyph drawn here. */
            amiga_print_glyph(win, 0, NO_GLYPH);
            amii_curs(win, 1, disprow - start - 1);
        }
        Text(rp, "+", 1);
        col = 1;
        }
    }
    if(cw->type == NHW_MESSAGE)
    {
        SetAPen(rp, amii_msgBPen);
        SetBPen(rp, amii_msgBPen);
    }
    else if(cw->type == NHW_MENU)
    {
        SetAPen(rp, amii_menuBPen);
        SetBPen(rp, amii_menuBPen);
    }
    else if(cw->type == NHW_TEXT)
    {
        SetAPen(rp, amii_textBPen);
        SetBPen(rp, amii_textBPen);
    }
    amii_cl_end(cw, col);
    whichcolor = -1;
    if(mip) mip = mip->next;
    }
    RefreshWindowFrame(w);
    return;
}
int DoMenuScroll (int win, int blocking, int how, menu_item **)
Definition at line 235 of file winmenu.c.
References alwaysinvent, amii_getlin(), amii_setfillpens(), amii_wins, amiIDisplay, buf, BUFSZ, amii_mi::canselect, amii_WinDesc::cols, ConvertKey(), amii_mi::count, count, CountLines(), CTRL, amii_WinDesc::curx, DisplayData(), DupNewWindow(), FALSE, find_menu_item(), amii_mi::gselector, HackFont, HackScreen, amii_menu::items, LARGEST_INT, lastmsg, make_menu_items(), map_menu_cmd(), max, amii_WinDesc::maxcol, amii_WinDesc::maxrow, amii_WinDesc::menu, MENU_FIRST_PAGE, MENU_INVERT_ALL, MENU_INVERT_PAGE, MENU_LAST_PAGE, MENU_NEXT_PAGE, MENU_PREVIOUS_PAGE, MENU_SEARCH, MENU_SELECT_ALL, MENU_SELECT_PAGE, MENU_UNSELECT_ALL, MENU_UNSELECT_PAGE, MenuScroll, min, morc, amii_WinDesc::morestr, new_wins, amii_WinDesc::newwin, win_setup::newwin, amii_mi::next, NHW_MENU, NHW_TEXT, NULL, OpenShWindow(), panic(), PICK_ANY, PICK_NONE, PICK_ONE, pictdata, pl_character, plname, PropScroll, amii_mi::selected, amii_mi::selector, SetPropInfo(), SOFF, amii_mi::str, TextsFont, TRUE, txheight, txwidth, amii_WinDesc::type, amii_WinDesc::wasup, amii_WinDesc::win, WIN_ERR, WIN_INVEN, WIN_MAP, WIN_MESSAGE, WIN_STATUS, winpanicstr, amii_WinDesc::wintags, WINVERS_AMII, WINVERS_AMIV, amii_DisplayDesc::xpix, xsize, PDAT::xsize, amii_DisplayDesc::ypix, ysize, and PDAT::ysize.
Referenced by amii_display_nhwindow(), and amii_select_menu().
{
    amii_menu_item *amip;
    register struct Window *w;
    register struct NewWindow *nw;
    struct PropInfo *pip;
    register struct amii_WinDesc *cw;
    struct IntuiMessage *imsg;
    struct Gadget *gd;
    register int wheight, xsize, ysize, aredone = 0;
    register int txwd, txh;
    long mics, secs, class, code;
    long oldmics = 0, oldsecs = 0;
    int aidx, oidx, topidx, hidden;
    int totalvis;
    SHORT mx, my;
    static char title[ 100 ];
    int dosize = 1;
    struct Screen *scrn = HackScreen;
    int x1,x2,y1,y2;
    long counting = FALSE, count = 0, reset_counting = FALSE;
    char countString[32];
    if(win == WIN_ERR || (cw = amii_wins[ win ]) == NULL)
    panic(winpanicstr,win,"DoMenuScroll");
    /* Initial guess at window sizing values */
    txwd = txwidth;
    if(WINVERS_AMIV)
    {
    if(win == WIN_INVEN)
        txh = max(txheight, pictdata.ysize + 3); /* interline space */
    else
        txh = txheight; /* interline space */
    }
    else
    txh = txheight; /* interline space */
    /* Check to see if we should open the window, should need to for
     * TEXT and MENU but not MESSAGE.
     */
    w = cw->win;
    topidx = 0;
    if(w == NULL)
    {
#ifdef INTUI_NEW_LOOK
    if(IntuitionBase->LibNode.lib_Version >= 37)
    {
        PropScroll.Flags |= PROPNEWLOOK;
    }
#endif
    nw = (void *)DupNewWindow((void *)(&new_wins[ cw->type ].
      newwin));
    if(!alwaysinvent || win != WIN_INVEN)
    {
        xsize = scrn->WBorLeft + scrn->WBorRight + MenuScroll.Width + 1 +
                (txwd * cw->maxcol);
        if(WINVERS_AMIV)
        {
        if(win == WIN_INVEN)
            xsize += pictdata.xsize + 4;
        }
        if(xsize > amiIDisplay->xpix)
        xsize = amiIDisplay->xpix;
        /* If next row not off window, use it, else use the bottom */
        ysize = (txh * cw->maxrow) + /* The text space */
            HackScreen->WBorTop + txheight + 1 + /* Top border */
            HackScreen->WBorBottom + 3; /* The bottom border */
        if(ysize > amiIDisplay->ypix)
        ysize = amiIDisplay->ypix;
        /* Adjust the size of the menu scroll gadget */
        nw->TopEdge = 0;
        if(cw->type == NHW_TEXT && ysize < amiIDisplay->ypix)
        nw->TopEdge += (amiIDisplay->ypix - ysize) / 2;
        nw->LeftEdge = amiIDisplay->xpix - xsize;
        if(cw->type == NHW_MENU)
        {
        if(nw->LeftEdge > 10)
            nw->LeftEdge -= 10;
        else
            nw->LeftEdge = 0;
        if(amiIDisplay->ypix - nw->Height > 10)
            nw->TopEdge += 10;
        else
            nw->TopEdge = amiIDisplay->ypix - nw->Height - 1;
        }
        if(cw->type == NHW_TEXT && xsize < amiIDisplay->xpix)
        nw->LeftEdge -= (amiIDisplay->xpix - xsize) / 2;
    }
    else if(win == WIN_INVEN)
    {
        struct Window *mw = amii_wins[ WIN_MAP ]->win;
        struct Window *sw = amii_wins[ WIN_STATUS ]->win;
        xsize = scrn->WBorLeft + scrn->WBorRight + MenuScroll.Width + 1 +
                (txwd * cw->maxcol);
        /* Make space for the glyph to appear at the left of the description */
        if(WINVERS_AMIV)
        xsize += pictdata.xsize + 4;
        if(xsize > amiIDisplay->xpix)
        xsize = amiIDisplay->xpix;
        /* If next row not off window, use it, else use the bottom */
        ysize = sw->TopEdge - (mw->TopEdge + mw->Height) - 1;
        if(ysize > amiIDisplay->ypix)
        ysize = amiIDisplay->ypix;
        /* Adjust the size of the menu scroll gadget */
        nw->TopEdge = mw->TopEdge + mw->Height;
        nw->LeftEdge = 0;
    }
    cw->newwin = (void *)nw;
    if(nw == NULL)
        panic("No NewWindow Allocated");
    nw->Screen = HackScreen;
    if(win == WIN_INVEN)
    {
        sprintf(title, "%s the %s's Inventory", plname, pl_character);
        nw->Title = title;
        if(lastinvent.MaxX != 0)
        {
        nw->LeftEdge = lastinvent.MinX;
        nw->TopEdge = lastinvent.MinY;
        nw->Width = lastinvent.MaxX;
        nw->Height = lastinvent.MaxY;
        }
    }
    else if(cw->morestr)
        nw->Title = cw->morestr;
    /* Adjust the window coordinates and size now that we know
     * how many items are to be displayed.
     */
    if((xsize > amiIDisplay->xpix - nw->LeftEdge) &&
        (xsize < amiIDisplay->xpix))
    {
        nw->LeftEdge = amiIDisplay->xpix - xsize;
        nw->Width = xsize;
    }
    else
    {
        nw->Width = min(xsize, amiIDisplay->xpix - nw->LeftEdge);
    }
    nw->Height = min(ysize, amiIDisplay->ypix - nw->TopEdge);
    if(WINVERS_AMIV || WINVERS_AMII)
    {
        /* Make sure we are using the correct hook structure */
        nw->Extension = cw->wintags;
    }
    /* Now, open the window */
    w = cw->win = OpenShWindow((void *)nw);
    if(w == NULL)
    {
        char buf[ 130 ];
        sprintf(buf, "No Window Opened For Menu (%d,%d,%d-%d,%d-%d)",
        nw->LeftEdge, nw->TopEdge, nw->Width, amiIDisplay->xpix,
        nw->Height, amiIDisplay->ypix);
        panic(buf);
    }
#ifdef HACKFONT
    if(TextsFont)
        SetFont(w->RPort, TextsFont);
    else if(HackFont)
        SetFont(w->RPort, HackFont);
#endif
    txwd = w->RPort->TxWidth;
    if(WINVERS_AMIV)
    {
        if(win == WIN_INVEN)
        txh = max(w->RPort->TxHeight, pictdata.ysize + 3); /* interline space */
        else
        txh = w->RPort->TxHeight; /* interline space */
    }
    else
        txh = w->RPort->TxHeight; /* interline space */
    /* subtract 2 to account for spacing away from border (1 on each side) */
    wheight = (w->Height - w->BorderTop - w->BorderBottom - 2) / txh;
    if(WINVERS_AMIV)
    {
        if(win == WIN_INVEN)
        {
        cw->cols = (w->Width - w->BorderLeft -
                w->BorderRight - 4 - pictdata.xsize - 3) / txwd;
        }
        else
        {
        cw->cols = (w->Width - w->BorderLeft - w->BorderRight - 4) / txwd;
        }
    }
    else
    {
        cw->cols = (w->Width - w->BorderLeft - w->BorderRight - 4) / txwd;
    }
    totalvis = CountLines(win);
    }
    else
    {
    txwd = w->RPort->TxWidth;
    if(WINVERS_AMIV)
    {
        if(win == WIN_INVEN)
        txh = max(w->RPort->TxHeight, pictdata.ysize + 3); /* interline space */
        else
        txh = w->RPort->TxHeight; /* interline space */
    }
    else
    {
        txh = w->RPort->TxHeight; /* interline space */
    }
    /* subtract 2 to account for spacing away from border (1 on each side) */
    wheight = (w->Height - w->BorderTop - w->BorderBottom - 2) / txh;
    if(WINVERS_AMIV)
    {
        if(win == WIN_INVEN)
        {
        cw->cols = (w->Width - w->BorderLeft -
                w->BorderRight - 4 - pictdata.xsize - 3) / txwd;
        }
        else
        cw->cols = (w->Width - w->BorderLeft - w->BorderRight - 4) / txwd;
    }
    else
    {
        cw->cols = (w->Width - w->BorderLeft - w->BorderRight - 4) / txwd;
    }
    totalvis = CountLines(win);
    for(gd = w->FirstGadget; gd && gd->GadgetID != 1;)
        gd = gd->NextGadget;
    if(gd)
    {
        pip = (struct PropInfo *)gd->SpecialInfo;
        hidden = max(totalvis - wheight, 0);
        topidx = (((ULONG)hidden * pip->VertPot) + (MAXPOT/2)) >> 16;
    }
    }
    for(gd = w->FirstGadget; gd && gd->GadgetID != 1;)
    gd = gd->NextGadget;
    if(!gd) panic("Can't find scroll gadget");
    morc = 0;
    oidx = -1;
#if 0
    /* Make sure there are no selections left over from last time. */
/* XXX potential problem for preselection if this is really needed */
  for(amip = cw->menu.items; amip; amip = amip->next)
    amip->selected = 0;
#endif
    DisplayData(win, topidx);
    /* Make the prop gadget the right size and place */
    SetPropInfo(w, gd, wheight, totalvis, topidx);
    oldsecs = oldmics = 0;
    /* If window already up, don't stop to process events */
    if(cw->wasup)
    {
        aredone = 1;
        cw->wasup = 0;
    }
    while(!aredone)
    {
    /* Process window messages */
    WaitPort(w->UserPort);
    while(imsg = (struct IntuiMessage *) GetMsg(w->UserPort))
    {
        class = imsg->Class;
        code = imsg->Code;
        mics = imsg->Micros;
        secs = imsg->Seconds;
        gd = (struct Gadget *) imsg->IAddress;
        mx = imsg->MouseX;
        my = imsg->MouseY;
        /* Only do our window or VANILLAKEY from other windows */
        if(imsg->IDCMPWindow != w && class != VANILLAKEY &&
                            class != RAWKEY)
        {
        ReplyMsg((struct Message *) imsg);
        continue;
        }
        /* Do DeadKeyConvert() stuff if RAWKEY... */
        if(class == RAWKEY)
        {
        class = VANILLAKEY;
        code = ConvertKey(imsg);
        }
        ReplyMsg((struct Message *) imsg);
        switch(class)
        {
        case NEWSIZE:
            /*
             * Ignore every other newsize, no action needed,
             * except RefreshWindowFrame() in case borders got overwritten
             * for some reason. It should not happen, but ...
             */
            if(!dosize)
            {
            RefreshWindowFrame(w);
            dosize = 1;
            break;
            }
            if(win == WIN_INVEN)
            {
            lastinvent.MinX = w->LeftEdge;
            lastinvent.MinY = w->TopEdge;
            lastinvent.MaxX = w->Width;
            lastinvent.MaxY = w->Height;
            }
            else if(win == WIN_MESSAGE)
            {
            lastmsg.MinX = w->LeftEdge;
            lastmsg.MinY = w->TopEdge;
            lastmsg.MaxX = w->Width;
            lastmsg.MaxY = w->Height;
            }
            /* Find the gadget */
            for(gd = w->FirstGadget; gd && gd->GadgetID != 1;)
            gd = gd->NextGadget;
            if(!gd)
            panic("Can't find scroll gadget");
            totalvis = CountLines(win);
            wheight = (w->Height - w->BorderTop -
                        w->BorderBottom - 2) / txh;
            if(WINVERS_AMIV)
            {
            if(win == WIN_INVEN)
            {
                cw->cols = (w->Width - w->BorderLeft -
                    w->BorderRight - 4 - pictdata.xsize - 3) / txwd;
            }
            else
                cw->cols = (w->Width - w->BorderLeft - w->BorderRight - 4) / txwd;
            }
            else
            {
            cw->cols = (w->Width - w->BorderLeft - w->BorderRight - 4) / txwd;
            }
            if(wheight < 2)
            wheight = 2;
            /*
             * Clear the right side & bottom. Parts of letters are not erased by
             * amii_cl_end if window shrinks and columns decrease.
             */
            if (WINVERS_AMII || WINVERS_AMIV) {
            amii_setfillpens(w, cw->type);
            SetDrMd(w->RPort, JAM2);
            x2 = w->Width - w->BorderRight;
            y2 = w->Height - w->BorderBottom;
            x1 = x2 - w->IFont->tf_XSize - w->IFont->tf_XSize;
            y1 = w->BorderTop;
            if (x1 < w->BorderLeft)
                x1 = w->BorderLeft;
            RectFill(w->RPort, x1, y1, x2, y2);
            x1 = w->BorderLeft;
            y1 = y1 - w->IFont->tf_YSize;
            RectFill(w->RPort, x1, y1, x2, y2);
            RefreshWindowFrame(w);
            }
            /* Make the prop gadget the right size and place */
            DisplayData(win, topidx);
            SetPropInfo(w, gd, wheight, totalvis, topidx);
            /* Force the window to a text line boundary <= to
             * what the user dragged it to. This eliminates
             * having to clean things up on the bottom edge.
             */
            SizeWindow(w, 0, (wheight * txh) +
                w->BorderTop + w->BorderBottom + 2 - w->Height);
            /* Don't do next NEWSIZE, we caused it */
            dosize = 0;
            oldsecs = oldmics = 0;
            break;
        case VANILLAKEY:
#define CTRL(x) ((x)-'@')
            morc = code = map_menu_cmd(code);
            if (code == MENU_SELECT_ALL) {
            if (how == PICK_ANY) {
                amip = cw->menu.items;
                while (amip) {
                if (amip->canselect && amip->selector) {
                /*
                 * Select those yet unselected
                 * and apply count if necessary
                 */
                    if (!amip->selected) {
                    amip->selected = TRUE;
                    if (counting) {
                        amip->count = count;
                        reset_counting = TRUE;
                    /*
                     * This makes the assumption that
                     * the string is in format "X - foo"
                     * with additional selecting and formatting
                     * data in front (size SOFF)
                     */
                        amip->str[SOFF+2] = '#';
                    } else {
                        amip->count = -1;
                        amip->str[SOFF+2] = '-';
                    }
                    }
                }
                amip=amip->next;
                }
                DisplayData(win, topidx);
            }
            } else if (code == MENU_UNSELECT_ALL) {
            if (how == PICK_ANY) {
                amip = cw->menu.items;
                while (amip) {
                if (amip->selected) {
                    amip->selected = FALSE;
                    amip->count = -1;
                    amip->str[SOFF+2] = '-';
                }
                amip=amip->next;
                }
                DisplayData(win, topidx);
            }
            } else if (code == MENU_INVERT_ALL) {
            if (how == PICK_ANY) {
                amip = cw->menu.items;
                while (amip) {
                if (amip->canselect && amip->selector) {
                    amip->selected = !amip->selected;
                    if (counting && amip->selected) {
                    amip->count = count;
                    amip->str[SOFF+2] = '#';
                    reset_counting = TRUE;
                    } else {
                    amip->count = -1;
                    amip->str[SOFF+2] = '-';
                    }
                }
                amip=amip->next;
                }
                DisplayData(win, topidx);
            }
            } else if (code == MENU_SELECT_PAGE) {
            if (how == PICK_ANY) {
                int i = 0;
                amip = cw->menu.items;
                while (amip && i++ < topidx)
                amip = amip->next;
                for (i=0;i < wheight && amip; i++, amip=amip->next) {
                if (amip->canselect && amip->selector) {
                    if (!amip->selected) {
                    if (counting) {
                        amip->count = count;
                        reset_counting = TRUE;
                        amip->str[SOFF+2] = '#';
                    } else {
                        amip->count = -1;
                        amip->str[SOFF+2] = '-';
                    }
                    }
                    amip->selected = TRUE;
                }
                }
                DisplayData(win, topidx);
            }
            } else if (code == MENU_UNSELECT_PAGE) {
            if (how == PICK_ANY) {
                int i = 0;
                amip = cw->menu.items;
                while (amip && i++ < topidx)
                amip = amip->next;
                for (i=0;i < wheight && amip; i++, amip=amip->next) {
                if (amip->selected) {
                    amip->selected = FALSE;
                    amip->count = -1;
                    amip->str[SOFF+2] = '-';
                }
                }
                DisplayData(win, topidx);
            }
            } else if (code == MENU_INVERT_PAGE) {
            if (how == PICK_ANY) {
                int i = 0;
                amip = cw->menu.items;
                while (amip && i++ < topidx)
                amip = amip->next;
                for (i=0;i < wheight && amip; i++, amip=amip->next) {
                if (amip->canselect && amip->selector) {
                    amip->selected = !amip->selected;
                    if (counting && amip->selected) {
                    amip->count = count;
                    amip->str[SOFF+2] = '#';
                    reset_counting = TRUE;
                    } else {
                    amip->count = -1;
                    amip->str[SOFF+2] = '-';
                    }
                }
                }
                DisplayData(win, topidx);
            }
            } else if (code == MENU_SEARCH && cw->type ==
      NHW_MENU) {
            if (how == PICK_ONE || how == PICK_ANY) {
                char buf[BUFSZ];
                amip = cw->menu.items;
                amii_getlin("Search for:", buf);
                if (!*buf || *buf == '\033')
                break;
                while (amip) {
                if (amip->canselect && amip->selector && amip->str &&
                    strstri(&amip->str[SOFF], buf)) {
                    if (how == PICK_ONE) {
                    amip->selected = TRUE;
                    aredone = 1;
                    break;
                    }
                    amip->selected = !amip->selected;
                    if (counting && amip->selected) {
                    amip->count = count;
                    reset_counting = TRUE;
                    amip->str[SOFF+2] = '#';
                    } else {
                    amip->count = -1;
                    reset_counting = TRUE;
                    amip->str[SOFF+2] = '-';
                    }
                }
                amip = amip->next;
                }
            }
            DisplayData(win, topidx);
            } else if (how == PICK_ANY && isdigit(code) &&
                   (counting || (!counting && code !='0'))) {
            if (count < LARGEST_INT) {
                count = count*10 + (long)(code-'0');
                if (count > LARGEST_INT)
                count = LARGEST_INT;
                if (count > 0) {
                counting = TRUE;
                reset_counting = FALSE;
                } else {
                reset_counting = TRUE;
                }
                sprintf(countString, "Count: %d", count);
                pline(countString);
            }
            } else if(code == CTRL('D') || code == CTRL('U') ||
                   code == MENU_NEXT_PAGE || code ==
      MENU_PREVIOUS_PAGE ||
                   code == MENU_FIRST_PAGE || code ==
      MENU_LAST_PAGE)
            {
            int endcnt, i;
            for(gd = w->FirstGadget; gd && gd->GadgetID != 1;)
                gd = gd->NextGadget;
            if(!gd)
                panic("Can't find scroll gadget");
            endcnt = wheight; /* /2; */
            if(endcnt == 0)
                endcnt = 1;
            if (code == MENU_FIRST_PAGE) {
                topidx = 0;
            } else if (code == MENU_LAST_PAGE) {
                topidx = cw->maxrow - wheight;
            } else for(i = 0; i < endcnt; ++i)
            {
                if (code == CTRL('D') || code == MENU_NEXT_PAGE)
                {
                if(topidx + wheight < cw->maxrow)
                    ++topidx;
                else
                    break;
                }
                else if (code = CTRL('U') || code == MENU_PREVIOUS_PAGE)
                {
                if(topidx > 0)
                    --topidx;
                else
                    break;
                }
            }
            /* Make prop gadget the right size and place */
            DisplayData(win, topidx);
            SetPropInfo(w,gd, wheight, totalvis, topidx);
            oldsecs = oldmics = 0;
            }
            else if(code == '\b')
            {
            for(gd = w->FirstGadget; gd && gd->GadgetID != 1;)
                gd = gd->NextGadget;
            if(!gd)
                panic("Can't find scroll gadget");
            if(topidx - wheight - 2 < 0)
            {
                topidx = 0;
            }
            else
            {
                topidx -= wheight - 2;
            }
            DisplayData(win, topidx);
            SetPropInfo(w, gd, wheight, totalvis, topidx);
            oldsecs = oldmics = 0;
            }
            else if(code == ' ')
            {
            for(gd = w->FirstGadget; gd && gd->GadgetID != 1;)
                gd = gd->NextGadget;
            if(!gd)
                panic("Can't find scroll gadget");
            if(topidx + wheight >= cw->maxrow)
            {
                morc = 0;
                aredone = 1;
            }
            else
            {
                /* If there are still lines to be seen */
                if(cw->maxrow > topidx + wheight)
                {
                if(wheight > 2)
                    topidx += wheight - 2;
                else
                    ++topidx;
                DisplayData(win, topidx);
                SetPropInfo(w, gd, wheight,
                            totalvis, topidx);
                }
                oldsecs = oldmics = 0;
            }
            }
            else if(code == '\n' || code == '\r')
            {
            for(gd = w->FirstGadget; gd && gd->GadgetID != 1;)
                gd = gd->NextGadget;
            if(!gd)
                panic("Can't find scroll gadget");
            /* If all line displayed, we are done */
            if(topidx + wheight >= cw->maxrow)
            {
                morc = 0;
                aredone = 1;
            }
            else
            {
                /* If there are still lines to be seen */
                if(cw->maxrow > topidx + 1)
                {
                ++topidx;
                DisplayData(win, topidx);
                SetPropInfo(w, gd, wheight,
                            totalvis, topidx);
                }
                oldsecs = oldmics = 0;
            }
            }
            else if(code == '\33')
            {
            if (counting) {
                reset_counting = TRUE;
            } else {
                aredone = 1;
            }
            }
            else
            {
            int selected = FALSE;
            for(amip = cw->menu.items; amip; amip = amip->next)
            {
                if(amip->selector == code)
                {
                if(how == PICK_ONE)
                    aredone = 1;
                amip->selected = !amip->selected;
                if (counting && amip->selected) {
                    amip->count = count;
                    reset_counting = TRUE;
                    amip->str[SOFF+2] = '#';
                } else {
                    amip->count = -1;
                    reset_counting = TRUE;
                    amip->str[SOFF+2] = '-';
                }
                selected = TRUE;
                } else if (amip->gselector == code)
                {
                amip->selected = !amip->selected;
                if (counting) {
                    amip->count = count;
                    reset_counting = TRUE;
                    amip->str[SOFF+2] = '#';
                } else {
                    amip->count = -1;
                    reset_counting = TRUE;
                    amip->str[SOFF+2] = '-';
                }
                selected = TRUE;
                }
            }
            if (selected)
                DisplayData(win, topidx);
            }
            break;
        case CLOSEWINDOW:
            if(win == WIN_INVEN)
            {
            lastinvent.MinX = w->LeftEdge;
            lastinvent.MinY = w->TopEdge;
            lastinvent.MaxX = w->Width;
            lastinvent.MaxY = w->Height;
            }
            else if(win == WIN_MESSAGE)
            {
            lastmsg.MinX = w->LeftEdge;
            lastmsg.MinY = w->TopEdge;
            lastmsg.MaxX = w->Width;
            lastmsg.MaxY = w->Height;
            }
            aredone = 1;
            morc = '\33';
            break;
        case GADGETUP:
            if(win == WIN_MESSAGE)
            aredone = 1;
            for(gd = w->FirstGadget; gd && gd->GadgetID != 1;)
            gd = gd->NextGadget;
            pip = (struct PropInfo *)gd->SpecialInfo;
            totalvis = CountLines(win);
            hidden = max(totalvis - wheight, 0);
            aidx = (((ULONG)hidden * pip->VertPot) + (MAXPOT/2)) >> 16;
            if(aidx != topidx)
            DisplayData(win, topidx = aidx);
            break;
        case MOUSEMOVE:
            for(gd = w->FirstGadget; gd && gd->GadgetID != 1;)
            gd = gd->NextGadget;
            pip = (struct PropInfo *)gd->SpecialInfo;
            totalvis = CountLines(win);
            hidden = max(totalvis - wheight, 0);
            aidx = (((ULONG)hidden * pip->VertPot) + (MAXPOT/2)) >> 16;
            if(aidx != topidx)
            DisplayData(win, topidx = aidx);
            break;
        case INACTIVEWINDOW:
            if(win == WIN_MESSAGE || (win == WIN_INVEN &&
      alwaysinvent))
            aredone = 1;
            break;
        case MOUSEBUTTONS:
            if((code == SELECTUP || code == SELECTDOWN) &&
                    cw->type == NHW_MENU && how != PICK_NONE)
            {
            /* Which one is the mouse pointing at? */
            aidx = ((my - w->BorderTop - 1) / txh) + topidx;
            /* If different lines, don't select double click */
            if(aidx != oidx)
            {
                oldsecs = 0;
                oldmics = 0;
            }
            /* If releasing, check for double click */
            if(code == SELECTUP)
            {
                amip = find_menu_item(cw, aidx);
                if(aidx == oidx)
                {
                if(DoubleClick(oldsecs,
                            oldmics, secs, mics))
                {
                    aredone = 1;
                }
                oldsecs = secs;
                oldmics = mics;
                }
                else
                {
                amip = find_menu_item(cw, oidx);
                amip->selected = 0;
                amip->count = -1;
                reset_counting = TRUE;
                if (amip->canselect && amip->selector)
                    amip->str[SOFF+2] = '-';
                }
                if (counting && amip->selected && amip->canselect && amip->selector) {
                amip->count = count;
                reset_counting = TRUE;
                amip->str[SOFF+2] = '#';
                }
                DisplayData(win, topidx);
            }
            else if(aidx - topidx < wheight &&
                aidx < cw->maxrow && code == SELECTDOWN)
            {
                /* Remove old highlighting if visible */
                amip = find_menu_item(cw, oidx);
                if(amip && oidx != aidx &&
                    (oidx > topidx && oidx - topidx < wheight))
                {
                if(how != PICK_ANY) {
                    amip->selected = 0;
                    amip->count = -1;
                    reset_counting = TRUE;
                    if (amip->canselect && amip->selector)
                    amip->str[SOFF+2] = '-';
                }
                oidx = -1;
                }
                amip = find_menu_item(cw, aidx);
                if(amip && amip->canselect && amip->selector && how !=
      PICK_NONE)
                {
                oidx = aidx;
                if(!DoubleClick(oldsecs,
                            oldmics, secs, mics))
                {
                    amip->selected = !amip->selected;
                    if (counting && amip->selected) {
                    amip->count = count;
                    reset_counting = TRUE;
                    amip->str[SOFF+2] = '#';
                    } else {
                    amip->count = -1;
                    reset_counting = TRUE;
                    if (amip->canselect && amip->selector)
                        amip->str[SOFF+2] = '-';
                    }
                }
                }
                else
                {
                DisplayBeep(NULL);
                oldsecs = 0;
                oldmics = 0;
                }
                DisplayData(win, topidx);
            }
            }
            else
            {
            DisplayBeep(NULL);
            }
            break;
        }
        if (!counting && morc == '\33') {
        amip = cw->menu.items;
        while (amip) {
            if (amip->canselect && amip->selector) {
            amip->selected = FALSE;
            amip->count = -1;
            amip->str[SOFF+2] = '-';
            }
            amip=amip->next;
        }
        }
        if (reset_counting) {
        count = 0;
        if (counting)
            pline("Count: 0");
        counting = FALSE;
        }
    }
    }
    /* Force a cursor reposition before next message output */
    if(win == WIN_MESSAGE)
    cw->curx = -1;
    return(make_menu_items(cw, retmip));
}
void DrawCol (struct Window * w, int idx, UWORD * colors)
Definition at line 754 of file winreq.c.
References amii_numcolors, C_BLACK, Col_BluePen, Col_GreenPen, Col_Okay, Col_RedPen, DispCol(), flags, and txheight.
Referenced by EditColor().
{
    int bxorx, bxory, bxxlen, bxylen;
    int i, incx, incy, r, g, b;
    long mflags;
    bxylen = Col_Okay.TopEdge - (Col_BluePen.TopEdge +
      Col_BluePen.Height) - 1
        - txheight - 3;
    bxxlen = Col_BluePen.Width - 2;
    bxorx = Col_BluePen.LeftEdge + 1;
    bxory = Col_BluePen.TopEdge + Col_BluePen.Height + 2;
    incx = bxxlen / amii_numcolors;
    incy = bxylen - 2;
    bxxlen /= incx;
    bxxlen *= incx;
    bxxlen += 2;
    for(i = 0; i < amii_numcolors; ++i)
    {
    int x, y;
    x = bxorx + 2 + (i*incx);
    y = bxory + 2;
    if(i == idx)
    {
        SetAPen(w->RPort, flags.amii_dripens[ SHADOWPEN ]);
        Move(w->RPort, x, y+bxylen-4);
        Draw(w->RPort, x, y);
        Draw(w->RPort, x+incx-1, y);
        Move(w->RPort, x+1, y+bxylen-5);
        Draw(w->RPort, x+1, y+1);
        Draw(w->RPort, x+incx-2, y+1);
        SetAPen(w->RPort, flags.amii_dripens[ SHINEPEN ]);
        Move(w->RPort, x+incx-1, y+1);
        Draw(w->RPort, x+incx-1, y+bxylen-4);
        Draw(w->RPort, x, y+bxylen-4);
        Move(w->RPort, x+incx-2, y+2);
        Draw(w->RPort, x+incx-2, y+bxylen-5);
        Draw(w->RPort, x+1, y+bxylen-5);
    }
    else
    {
        SetAPen(w->RPort, C_BLACK);
        Move(w->RPort, x, y);
        Draw(w->RPort, x +incx-1, y);
        Draw(w->RPort, x +incx-1, y +bxylen - 4);
        Draw(w->RPort, x, y + bxylen - 4);
        Draw(w->RPort, x, y);
        SetAPen(w->RPort, C_BLACK);
        Move(w->RPort, x+1, y+1);
        Draw(w->RPort, x +incx-2, y+1);
        Draw(w->RPort, x +incx-2, y +bxylen - 6);
        Draw(w->RPort, x+1, y + bxylen - 6);
        Draw(w->RPort, x+1, y+1);
    }
    SetAPen(w->RPort, i);
    RectFill(w->RPort, x + 3, y + 3, x + incx - 4, y + bxylen - 6);
    }
    DispCol(w, idx, colors);
    r = (colors[ idx ] & 0xf00) >> 8;
    g = (colors[ idx ] & 0x0f0) >> 4;
    b = colors[ idx ] & 0x00f;
    mflags = AUTOKNOB|FREEHORIZ;
#ifdef INTUI_NEW_LOOK
    if(IntuitionBase->LibNode.lib_Version >= 37)
    {
    mflags |= PROPNEWLOOK;
    }
#endif
    NewModifyProp(&Col_RedPen, w, NULL, mflags, (r * MAXPOT) / 15, 0,
                                MAXPOT/15, 0, 1);
    NewModifyProp(&Col_GreenPen, w, NULL, mflags, (g * MAXPOT) / 15, 0,
                                MAXPOT/15, 0, 1);
    NewModifyProp(&Col_BluePen, w, NULL, mflags, (b * MAXPOT) / 15, 0,
                                MAXPOT/15, 0, 1);
}
struct NewWindow* DupNewWindow (struct NewWindow * win)
Referenced by DoMenuScroll().
void EditClipping (void)
Definition at line 383 of file winreq.c.
References amii_otherBPen, amii_wins, buf, ClipCancel, ClipNewWindowStructure1, ClipOkay, ClipXCLIP, ClipXSIZE, ClipYCLIP, ClipYSIZE, done, doredraw(), fillhook, flush_glyph_buffer(), GADCANCEL, GADOKAY, HackScreen, LayerFillHook(), mxsize, mysize, okay(), reclip, SetBorder(), ShowClipValues(), WIN_MAP, wintags, WINVERS_AMII, WINVERS_AMIV, XCLIP, XSIZE, YCLIP, and YSIZE.
{
    int i;
    long mflags;
    static int sizes[] = { 8, 16, 20, 24, 28, 32, 36 };
    char buf[ 40 ];
    int done = 0, okay = 0;
    long code, qual, class;
    register struct Gadget *gd, *dgad;
    register struct Window *nw;
    register struct IntuiMessage *imsg;
    register struct PropInfo *pip;
    register struct Screen *scrn;
    long aidx;
    int lmxsize = mxsize, lmysize = mysize;
    int lxclipbord = xclipbord, lyclipbord = yclipbord;
    int msx, msy;
    int drag = 0;
    static int once = 0;
    scrn = HackScreen;
    if(!once)
    {
    SetBorder(&ClipOkay);
    SetBorder(&ClipCancel);
    once = 1;
    }
    ClipNewWindowStructure1.Screen = scrn;
#ifdef INTUI_NEW_LOOK
    if(IntuitionBase->LibNode.lib_Version >= 37)
    {
    ((struct PropInfo *)ClipXSIZE.SpecialInfo)->Flags |= PROPNEWLOOK;
    ((struct PropInfo *)ClipYSIZE.SpecialInfo)->Flags |= PROPNEWLOOK;
    ((struct PropInfo *)ClipXCLIP.SpecialInfo)->Flags |= PROPNEWLOOK;
    ((struct PropInfo *)ClipYCLIP.SpecialInfo)->Flags |= PROPNEWLOOK;
    }
#endif
    if(WINVERS_AMIV || WINVERS_AMII)
    {
# ifdef INTUI_NEW_LOOK
    ClipNewWindowStructure1.Extension = wintags;
    ClipNewWindowStructure1.Flags |= WFLG_NW_EXTENDED;
# ifdef __GNUC__
    fillhook.h_Entry = (void *)&LayerFillHook;
# else
    fillhook.h_Entry = (ULONG(*)())LayerFillHook;
# endif
    fillhook.h_Data = (void *)-2;
    fillhook.h_SubEntry = 0;
# endif
    }
    nw = OpenWindow((void *)&ClipNewWindowStructure1);
    if(nw == NULL)
    {
    DisplayBeep(NULL);
    return;
    }
    ShowClipValues(nw);
    mflags = AUTOKNOB|FREEHORIZ;
#ifdef INTUI_NEW_LOOK
    if(IntuitionBase->LibNode.lib_Version >= 37)
    {
    mflags |= PROPNEWLOOK;
    }
#endif
    for(i = 0; i < 7; ++i)
    {
    if(mxsize <= sizes[ i ])
        break;
    }
    NewModifyProp(&ClipXSIZE, nw, NULL, mflags, (i * MAXPOT) / 6, 0,
                                MAXPOT/6, 0, 1);
    for(i = 0; i < 7; ++i)
    {
    if(mysize <= sizes[ i ])
        break;
    }
    NewModifyProp(&ClipYSIZE, nw, NULL, mflags, (i * MAXPOT) / 6, 0,
                                MAXPOT/6, 0, 1);
    NewModifyProp(&ClipXCLIP, nw, NULL, mflags, ((xclipbord-2) * MAXPOT) / 6, 0,
                                MAXPOT/6, 0, 1);
    NewModifyProp(&ClipYCLIP, nw, NULL, mflags, ((yclipbord-2) * MAXPOT) / 6, 0,
                                MAXPOT/6, 0, 1);
    while(!done)
    {
    WaitPort(nw->UserPort);
    while(imsg = (struct IntuiMessage *)GetMsg(nw->UserPort))
    {
        gd = (struct Gadget *)imsg->IAddress;
        code = imsg->Code;
        class = imsg->Class;
        qual = imsg->Qualifier;
        msx = imsg->MouseX;
        msy = imsg->MouseY;
        ReplyMsg((struct Message *)imsg);
        switch(class)
        {
        case VANILLAKEY:
        if(code == '\33')
            okay = 0, done = 1;
        else if(code == 'v' && qual == AMIGALEFT)
            okay = done = 1;
        else if(code == 'b' && qual == AMIGALEFT)
            okay = 0, done = 1;
        else if(code == 'o' || code == 'O')
            okay = done = 1;
        else if(code == 'c' || code == 'C')
            okay = 0, done = 1;
        break;
        case CLOSEWINDOW:
        done = 1;
        break;
        case GADGETUP:
        drag = 0;
        if(gd->GadgetID == XSIZE || gd->GadgetID == YSIZE ||
            gd->GadgetID == XCLIP || gd->GadgetID == YCLIP)
        {
            pip = (struct PropInfo *)gd->SpecialInfo;
            aidx = pip->HorizPot / (MAXPOT/6);
            if(gd->GadgetID == XSIZE)
            {
            mxsize = sizes[ aidx ];
            }
            else if(gd->GadgetID == YSIZE)
            {
            mysize = sizes[ aidx ];
            }
            else if(gd->GadgetID == XCLIP)
            {
            xclipbord = aidx + 2;
            }
            else if(gd->GadgetID == YCLIP)
            {
            yclipbord = aidx + 2;
            }
            ShowClipValues(nw);
#ifdef OPT_DISPMAP
            dispmap_sanity();
#endif
        }
        else if(gd->GadgetID == GADOKAY)
        {
            done = 1;
            okay = 1;
        }
        else if(gd->GadgetID == GADCANCEL)
        {
            done = 1;
            okay = 0;
        }
        ReportMouse(0, nw);
        reclip = 2;
        doredraw();
        flush_glyph_buffer(amii_wins[ WIN_MAP ]->win);
        reclip = 0;
        break;
        case GADGETDOWN:
        drag = 1;
        dgad = gd;
        ReportMouse(1, nw);
        break;
        case MOUSEMOVE:
        if(!drag)
            break;
        pip = (struct PropInfo *)dgad->SpecialInfo;
        aidx = pip->HorizPot / (MAXPOT/6);
        Move(nw->RPort, dgad->LeftEdge + (nw->Width + dgad->Width) + 8,
                dgad->TopEdge + nw->RPort->TxBaseline);
        if(dgad->GadgetID == XSIZE)
        {
            mxsize = sizes[ aidx ];
            sprintf(buf, "%d ",lmxsize);
        }
        else if(dgad->GadgetID == YSIZE)
        {
            mysize = sizes[ aidx ];
            sprintf(buf, "%d ", mysize);
        }
        else if(dgad->GadgetID == XCLIP)
        {
            xclipbord = aidx + 2;
            sprintf(buf, "%d ", xclipbord);
        }
        else if(dgad->GadgetID == YCLIP)
        {
            yclipbord = aidx + 2;
            sprintf(buf, "%d ", yclipbord);
        }
        SetAPen(nw->RPort, 5);
        SetBPen(nw->RPort, amii_otherBPen);
        SetDrMd(nw->RPort, JAM2);
        Text(nw->RPort, buf, strlen(buf));
#ifdef OPT_DISPMAP
         dispmap_sanity();
#endif
        break;
        }
    }
    }
    CloseWindow(nw);
    /* Restore oldvalues if cancelled. */
    if(!okay)
    {
    mxsize = lmxsize;
    mysize = lmysize;
    xclipbord = lxclipbord;
    yclipbord = lyclipbord;
    }
}
void EditColor (void)
Definition at line 58 of file winreq.c.
References AMII_MAXCOLORS, amii_numcolors, buf, ClearCol(), Col_BluePen, Col_Cancel, Col_GreenPen, Col_IntuiTextList1, Col_NewWindowStructure1, Col_Okay, Col_RedPen, Col_Save, configfile, dirname(), DispCol(), done, DrawCol(), filecopy(), fillhook, flags, fp, GADBLUEPEN, GADCOLCANCEL, GADCOLOKAY, GADCOLSAVE, GADGREENPEN, GADREDPEN, HackScreen, LayerFillHook(), okay(), SetBorder(), unlink(), UWORD, wintags, WINVERS_AMII, and WINVERS_AMIV.
{
    extern const char *configfile;
    int i, done = 0, okay = 0;
    long code, qual, class;
    register struct Gadget *gd, *dgad;
    register struct Window *nw;
    register struct IntuiMessage *imsg;
    register struct PropInfo *pip;
    register struct Screen *scrn;
    long aidx;
    int msx, msy;
    int curcol = 0, drag = 0;
    int bxorx, bxory, bxxlen, bxylen;
    static UWORD colors[ AMII_MAXCOLORS ];
    static UWORD svcolors[ AMII_MAXCOLORS ];
    static int once = 0;
    scrn = HackScreen;
    if(!once)
    {
        if(WINVERS_AMIV)
        {
            Col_NewWindowStructure1.Width += 300;
            Col_NewWindowStructure1.Height += 20;
            Col_NewWindowStructure1.LeftEdge -= 150;
            Col_BluePen.Width += 300;
            Col_RedPen.Width += 300;
            Col_GreenPen.Width += 300;
            Col_Cancel.LeftEdge += 300;
            Col_Okay.LeftEdge += 150;
            Col_Cancel.TopEdge += 20;
            Col_Save.TopEdge += 20;
            Col_Okay.TopEdge += 20;
        }
        SetBorder(&Col_Okay);
        SetBorder(&Col_Cancel);
        SetBorder(&Col_Save);
        once = 1;
    }
    bxylen = Col_NewWindowStructure1.Height -
                (Col_BluePen.TopEdge + Col_BluePen.Height + 6);
    bxxlen = Col_BluePen.Width;
    bxorx = Col_BluePen.LeftEdge;
    bxory = Col_BluePen.TopEdge + Col_BluePen.Height + 2;
    /* Save the current colors */
    for(i = 0; i < amii_numcolors; ++i)
        svcolors[ i ] = colors[ i ] = GetRGB4(scrn->ViewPort.ColorMap, i);
    Col_NewWindowStructure1.Screen = scrn;
#ifdef INTUI_NEW_LOOK
    if(IntuitionBase->LibNode.lib_Version >= 37)
    {
        ((struct PropInfo *)Col_BluePen.SpecialInfo)->Flags |= PROPNEWLOOK;
        ((struct PropInfo *)Col_RedPen.SpecialInfo)->Flags |= PROPNEWLOOK;
        ((struct PropInfo *)Col_GreenPen.SpecialInfo)->Flags |= PROPNEWLOOK;
    }
#endif
    if(WINVERS_AMIV || WINVERS_AMII)
    {
#ifdef INTUI_NEW_LOOK
        Col_NewWindowStructure1.Extension = wintags;
        Col_NewWindowStructure1.Flags |= WFLG_NW_EXTENDED;
# ifdef __GNUC__
        fillhook.h_Entry = (void *)&LayerFillHook;
# else
        fillhook.h_Entry = (ULONG(*)())LayerFillHook;
# endif
        fillhook.h_Data = (void *)-2;
        fillhook.h_SubEntry = 0;
#endif
    }
    nw = OpenWindow((void *)&Col_NewWindowStructure1);
    if(nw == NULL)
    {
    DisplayBeep(NULL);
    return;
    }
    PrintIText(nw->RPort, &Col_IntuiTextList1, 0, 0);
    ClearCol(nw);
    DrawCol(nw, curcol, colors);
    while(!done)
    {
    WaitPort(nw->UserPort);
    while(imsg = (struct IntuiMessage *)GetMsg(nw->UserPort))
    {
        gd = (struct Gadget *)imsg->IAddress;
        code = imsg->Code;
        class = imsg->Class;
        qual = imsg->Qualifier;
        msx = imsg->MouseX;
        msy = imsg->MouseY;
        ReplyMsg((struct Message *)imsg);
        switch(class)
        {
        case VANILLAKEY:
        if(code == 'v' && qual == AMIGALEFT)
            okay = done = 1;
        else if(code == 'b' && qual == AMIGALEFT)
            okay = 0, done = 1;
        else if(code == 'o' || code == 'O')
            okay = done = 1;
        else if(code == 'c' || code == 'C')
            okay = 0, done = 1;
        break;
        case CLOSEWINDOW:
        done = 1;
        break;
        case GADGETUP:
        drag = 0;
        if(gd->GadgetID == GADREDPEN ||
                    gd->GadgetID == GADBLUEPEN ||
                    gd->GadgetID == GADGREENPEN)
        {
            pip = (struct PropInfo *)gd->SpecialInfo;
            aidx = pip->HorizPot / (MAXPOT/15);
            if(gd->GadgetID == GADREDPEN)
            {
            colors[ curcol ] =
                (colors[ curcol ] & ~0xf00) | (aidx << 8);
            LoadRGB4(&scrn->ViewPort, colors, amii_numcolors);
            }
            else if(gd->GadgetID == GADBLUEPEN)
            {
            colors[ curcol ] =
                (colors[ curcol ] & ~0xf) | aidx;
            LoadRGB4(&scrn->ViewPort, colors, amii_numcolors);
            }
            else if(gd->GadgetID == GADGREENPEN)
            {
            colors[ curcol ] = (colors[ curcol ] & ~0x0f0) | (aidx << 4);
            LoadRGB4(&scrn->ViewPort, colors, amii_numcolors);
            }
            DispCol(nw, curcol, colors);
        }
        else if(gd->GadgetID == GADCOLOKAY)
        {
            done = 1;
            okay = 1;
        }
        else if(gd->GadgetID == GADCOLSAVE)
        {
            FILE *fp, *nfp;
            char buf[ 300 ], nname[ 300 ], oname[ 300 ];
            int once = 0;
            fp = fopen(configfile, "r");
            if(!fp)
            {
            pline("can't find NetHack.cnf");
            break;
            }
            strcpy(oname, dirname((char *)configfile));
            if(oname[ strlen(oname)-1 ] != ':')
            {
            sprintf(nname, "%s/New_NetHack.cnf", oname);
            strcat(oname, "/");
            strcat(oname, "Old_NetHack.cnf");
            }
            else
            {
            sprintf(nname, "%sNew_NetHack.cnf", oname);
            strcat(oname, "Old_NetHack.cnf");
            }
            nfp = fopen(nname, "w");
            if(!nfp)
            {
            pline("can't write to New_NetHack.cnf");
            fclose(fp);
            break;
            }
            while(fgets(buf, sizeof(buf), fp))
            {
            if(strncmp(buf, "PENS=", 5) == 0)
            {
                once = 1;
                fputs("PENS=", nfp);
                for(i = 0; i < amii_numcolors; ++i)
                {
                fprintf(nfp, "%03x", colors[i]);
                if((i + 1) < amii_numcolors)
                    putc('/', nfp);
                }
                putc('\n', nfp);
            }
            else
            {
                fputs(buf, nfp);
            }
            }
            /* If none in the file yet, now write it */
            if(!once)
            {
            fputs("PENS=", nfp);
            for(i = 0; i < amii_numcolors; ++i)
            {
                fprintf(nfp, "%03x", colors[i]);
                if((i + 1) < amii_numcolors)
                putc(',', nfp);
            }
                putc('\n', nfp);
            }
            fclose(fp);
            fclose(nfp);
            unlink(oname);
            if(filecopy((char *)configfile, oname) == 0)
            if(filecopy(nname, (char *)configfile) == 0)
                unlink(nname);
            done = 1;
            okay = 1;
        }
        else if(gd->GadgetID == GADCOLCANCEL)
        {
            done = 1;
            okay = 0;
        }
        break;
        case GADGETDOWN:
        drag = 1;
        dgad = gd;
        break;
        case MOUSEMOVE:
        if(!drag)
            break;
        pip = (struct PropInfo *)dgad->SpecialInfo;
        aidx = pip->HorizPot / (MAXPOT/15);
        if(dgad->GadgetID == GADREDPEN)
        {
            colors[ curcol ] =
                (colors[ curcol ] & ~0xf00) | (aidx << 8);
            LoadRGB4(&scrn->ViewPort, colors, amii_numcolors);
        }
        else if(dgad->GadgetID == GADBLUEPEN)
        {
            colors[ curcol ] = (colors[ curcol ] & ~0xf) | aidx;
            LoadRGB4(&scrn->ViewPort, colors, amii_numcolors);
        }
        else if(dgad->GadgetID == GADGREENPEN)
        {
            colors[ curcol ] =
                (colors[ curcol ] & ~0x0f0) | (aidx << 4);
            LoadRGB4(&scrn->ViewPort, colors, amii_numcolors);
        }
        DispCol(nw, curcol, colors);
        break;
        case MOUSEBUTTONS:
        if(code == SELECTDOWN)
        {
            if(msy > bxory && msy < bxory + bxylen - 1 &&
                msx > bxorx && msx < bxorx + bxxlen - 1)
            {
            curcol = (msx - bxorx)/(bxxlen / amii_numcolors);
            if(curcol >= 0 && curcol < amii_numcolors)
            DrawCol(nw, curcol, colors);
            }
        }
        break;
        }
    }
    }
    if(okay)
    {
    for(i = 0; i < (amii_numcolors); ++i)
        flags.amii_curmap[ i ] = colors[ i ];
    LoadRGB4(&scrn->ViewPort, flags.amii_curmap, amii_numcolors);
    }
    else
    LoadRGB4(&scrn->ViewPort, svcolors, amii_numcolors);
    CloseWindow(nw);
}
void FDECL (amii_add_menu , (winid, int, const anything *, CHAR_P, CHAR_P, int, const char *, BOOLEAN_P))
void FDECL (amii_end_menu , (winid, const char *))
int FDECL (amii_select_menu , (winid, int, menu_item **))
void FDECL (amii_outrip , (winid tmpwin, int how))
int filecopy (char * from, char * to)
Definition at line 645 of file winreq.c.
References alloc(), buf, and free().
Referenced by EditColor().
{
    char *buf;
    int i = 0;
    buf = (char *)alloc(strlen(to) + strlen(from) + 20);
    if(buf)
    {
        sprintf(buf, "c:copy \"%s\" \"%s\" clone", from, to);
        /* Check SysBase instead? Shouldn't matter */
#ifdef INTUI_NEW_LOOK
    if(IntuitionBase->LibNode.lib_Version >= 37)
        i = System(buf, NULL);
    else
#endif
        Execute(buf, NULL, NULL);
        free(buf);
    }
    else
    {
        return(-1);
    }
    return(i);
}
long FindLine (winid , int)
Definition at line 1204 of file winmenu.c.
References amii_wins, amii_WinDesc::cols, amii_WinDesc::data, amii_WinDesc::maxrow, panic(), pictdata, SOFF, amii_WinDesc::win, WIN_ERR, WIN_INVEN, winpanicstr, WINVERS_AMIV, and PDAT::xsize.
Referenced by DisplayData().
{
    int txwd;
    register char *t;
    register struct amii_WinDesc *cw;
    register struct Window *w;
    register int i, disprow, len;
    int col = -1;
    if(win == WIN_ERR || !(cw = amii_wins[win]) || !(w = cw->
      win))
    {
    panic(winpanicstr, win, "No Window in FindLine");
    }
    txwd = w->RPort->TxWidth;
    if(WINVERS_AMIV)
    {
    if(win == WIN_INVEN)
    {
        cw->cols = (w->Width - w->BorderLeft -
            w->BorderRight - 4 - pictdata.xsize - 3) / txwd;
    }
    else
        cw->cols = (w->Width - w->BorderLeft - w->BorderRight - 4) / txwd;
    }
    else
    {
    cw->cols = (w->Width - w->BorderLeft - w->BorderRight - 4) / txwd;
    }
    disprow = 0;
    for(col = i = 0; line > disprow && i < cw->maxrow; ++i)
    {
    t = cw->data[ i ] + SOFF;
    if(cw->data[i][1] >= 0)
    {
        ++disprow;
        col = 0;
    }
    while(*t)
    {
        len = strlen(t);
        if(col + len > cw->cols)
        len = cw->cols - col;
        while(len > 0)
        {
            if(!t[len] || t[len] == ' ')
            break;
            --len;
        }
        if(len == 0) {
        while (*t && *t != ' ') {
            t++; col++;
        }
        } else {
        t += len;
        col += len;
        }
        if(*t)
        {
        while(*t == ' ')
            ++t;
        col = 0;
        ++disprow;
        }
    }
    }
    return(i);
}
void flush_glyph_buffer (struct Window * w)
Definition at line 484 of file winchar.c.
References amii_flush_glyph_buffer(), amiv_flush_glyph_buffer(), and WINVERS_AMIV.
Referenced by amii_cliparound(), amii_curs(), amii_display_nhwindow(), amii_wait_synch(), and EditClipping().
{
    if(WINVERS_AMIV)
    amiv_flush_glyph_buffer (vw);
    else
    amii_flush_glyph_buffer (vw);
}
void flushIDCMP (struct MsgPort *)
Definition at line 2445 of file winfuncs.c.
Referenced by outmore().
{
    struct Message *msg;
    while(msg = GetMsg(port))
        ReplyMsg(msg);
}
void free (void * q)
Referenced by add_line(), add_mon_to_reg(), add_rect_to_reg(), add_region(), amii_destroy_nhwindow(), amii_putstr(), amii_start_menu(), append_text_buffer(), bitmap_to_img(), choose_classes_menu(), clear_id_mapping(), clear_regions(), convert(), create_engraving(), delete_dirty_rect(), depack_img(), destroy_fancy_status(), destroy_map_window(), destroy_menu_window(), destroy_message_window(), destroy_status_window(), destroy_text_window(), doset(), dospellmenu(), fclose_gif_file(), fclose_ppm_file(), filecopy(), fixup_special(), free_menu(), free_region(), free_saved_games(), free_text_buffer(), freedynamicdata(), Gem_start_menu(), Gem_yn_function(), gnome_display_file(), gnome_player_selection(), half_img(), help_menu(), in_or_out_menu(), init_extended_commands_popup(), init_tiles(), main(), MainWndProc(), make_menu(), MapWndProc(), mar_destroy_nhwindow(), menu_loot(), MenuWndProc(), mkmap(), mswin_display_splash_window(), mswin_free_text_buffer(), mswin_render_text(), mswin_yn_function(), mv_bubble(), MyFreeBitMap(), new_dirty_rect(), next_opt(), nhcmdlayout_destroy(), nhcmdset_destroy(), NHCommandWndProc(), NHMessageWndProc(), NHRIPWndProc(), NHTextWndProc(), onMSNHCommand(), parseoptions(), pickup(), prompt_for_player_selection(), restdamage(), save_oracles(), savedamage(), savelevchn(), savenames(), set_circle_buf(), set_duplicate_opt_detection(), special_handling(), StatusWndProc(), TextWndProc(), tmp_at(), unload_qtlist(), unsetup_waterlevel(), wc_set_font_name(), wc_set_window_colors(), WinMain(), X11_display_file(), X11_display_nhwindow(), X11_player_selection(), and yy_flex_free().
void FreeImageFiles (char ** , struct BitMap **)
Definition at line 453 of file winchar.c.
References ifftimg, MyFreeBitMap(), and tile.
Referenced by FreeTileImageFiles(), and ReadImageFiles().
{
    register int i;
    for(i = 0; filenames[i]; ++i)
    {
    if(img[ i ])
        MyFreeBitMap(img[ i ]);
    }
    /* REALLY ugly hack alert! */
    if(tile && img==ifftimg)
    MyFreeBitMap(tile);
}
void FreeNewWindow (struct NewWindow * win)
Referenced by dismiss_nhwindow().
void FreeTileImageFiles ()
Definition at line 448 of file winchar.c.
References FreeImageFiles(), ifftimg, and tileimages.
Referenced by amii_exit_nhwindows().
                    {
    FreeImageFiles(tileimages,ifftimg);
}
void getlind (const char * prompt, char * bufp, const char * dflt)
int GlyphToIcon (int glyph)
Definition at line 937 of file winchar.c.
References glyph2tile.
Referenced by amiv_lprint_glyph().
{
    if(glyph>10000)return glyph;
    return(glyph2tile[glyph]);
}
int kbhit (void)
Definition at line 544 of file amiwind.c.
References amii_procs, amikbhit(), and windowprocs.
{
    int c;
# ifdef TTY_GRAPHICS
        /* a kludge to defuse the mess in allmain.c */
        /* I hope this is the right approach */
    if(windowprocs.win_init_nhwindows==amii_procs.win_init_nhwindows)return 0;
# endif
    c = amikbhit();
    if(c <= 0)
        return(0);
    return(c);
}
void kill_nhwindows (int all)
Definition at line 1799 of file winfuncs.c.
References amii_destroy_nhwindow(), amii_wins, MAXWIN, NHW_BASE, and amii_WinDesc::type.
Referenced by amii_exit_nhwindows().
{
    register int i;
    register struct amii_WinDesc *cw;
    /* Foreach open window in all of amii_wins[], CloseShWindow, free memory */
    for(i = 0; i < MAXWIN; ++i)
    {
    if((cw = amii_wins[ i ]) && (cw->type != NHW_BASE || all))
    {
        amii_destroy_nhwindow(i);
    }
    }
}
void* malloc (register unsigned size)
Referenced by alloc(), bitmap_to_img(), fopen_xpm_file(), m_alloc(), main(), MainWndProc(), MenuWndProc(), mswin_display_splash_window(), mswin_init_RIP_window(), mswin_init_status_window(), mswin_init_text_buffer(), mswin_init_text_window(), mswin_menu_window_select_menu(), nhcmdlayout_create(), nhcmdset_create(), onCreate(), onMSNHCommand(), ReadImageFiles(), and VDECL().
struct Window* OpenShWindow (struct NewWindow * nw)
Referenced by amii_create_nhwindow(), and DoMenuScroll().
void outmore (struct amii_WinDesc * cw)
Definition at line 338 of file winstr.c.
References amii_cl_end(), amii_curs(), amii_msgborder(), FLMAP_SKIP, flushIDCMP(), HackPort, WEVENT::key, lastevent, scrollmsg, WEVENT::type, WEVENT::un, WEKEY, amii_WinDesc::win, WIN_MESSAGE, and WindowGetchar().
Referenced by amii_display_nhwindow(), amii_putstr(), amii_scrollmsg(), and outsubstr().
{
    struct Window *w = cw->win;
    if((cw->wflags & FLMAP_SKIP) == 0)
    {
    if(scrollmsg)
    {
        int bottom;
        bottom = amii_msgborder(w);
        ScrollRaster(w->RPort, 0, w->RPort->TxHeight,
            w->BorderLeft, w->BorderTop+1,
            w->Width - w->BorderRight-1,
            w->Height - w->BorderBottom - 1);
        amii_curs(WIN_MESSAGE, 1, bottom); /* -1 for inner border */
        Text(w->RPort, "--more--", 8);
    }
    else
        Text(w->RPort, " --more--", 9);
    /* Make sure there are no events in the queue */
    flushIDCMP(HackPort);
    /* Allow mouse clicks to clear --more-- */
    WindowGetchar();
    if(lastevent.type == WEKEY && lastevent.un.key == '\33')
        cw->wflags |= FLMAP_SKIP;
    }
    if(!scrollmsg)
    {
    amii_curs(WIN_MESSAGE, 1, 0);
    amii_cl_end(cw, cw->curx);
    }
}
void outsubstr (struct amii_WinDesc * cw, char * str, int len, int fudge)
Definition at line 377 of file winstr.c.
References outmore(), scrollmsg, spaces, and amii_WinDesc::win.
Referenced by amii_putstr().
{
    struct Window *w = cw->win;
    if(cw->curx)
    {
    /* Check if this string and --more-- fit, if not,
     * then put out --more-- and wait for a key.
     */
    if((len + fudge) + cw->curx >= cw->cols)
    {
        if(!scrollmsg)
        outmore(cw);
    }
    else
    {
        /* Otherwise, move and put out a blank separator */
        Text(w->RPort, spaces, 1);
        cw->curx += 1;
    }
    }
    Text(w->RPort,str,len);
}
void port_help (void)
Definition at line 2555 of file macwin.c.
References display_file, PORT_HELP, and TRUE.
Referenced by dohelp().
             {
    display_file (PORT_HELP, TRUE);
}
void preserve_icon (void)
void RandomWindow (char * name)
BitMapHeader ReadImageFiles (char ** , struct BitMap ** , char **)
Definition at line 205 of file winchar.c.
References amii_extraplanes, amii_initmap, amiv_init_map, buf, Close, cmap, errno, FreeImageFiles(), BitMapHeader::h, ID_BMAP, ID_BMHD, ID_CAMG, ID_CMAP, ID_PDAT, ID_PLNE, IFFParseBase, malloc(), MyAllocBitMap(), BitMapHeader::nPlanes, PDAT::nplanes, NULL, pictdata, tile, BitMapHeader::w, PDAT::xsize, and PDAT::ysize.
Referenced by ReadTileImageFiles().
{
    BitMapHeader *bmhd = NULL, bmhds;
    unsigned char *cmap;
    extern int errno;
    register int i, j;
    struct IFFHandle *iff;
    struct StoredProperty *prop;
    IFFParseBase = OpenLibrary("iffparse.library", 0L);
    if(!IFFParseBase)
    {
    *errstrp = "No iffparse.library";
    return bmhds;
    }
/*
    for(i = 0; filenames[i]; ++i)
    memset(iffimg[i], 0, sizeof(struct BitMap));
*/
    for(i = 0; filenames[i]; ++i)
    {
    iff = AllocIFF();
    if(!iff)
    {
        FreeImageFiles(filenames, iffimg);
        *errstrp = "can't start IFF processing";
        return bmhds;
    }
    iff->iff_Stream = Open(filenames[i], MODE_OLDFILE);
    if(iff->iff_Stream == 0)
    {
        char *buf = malloc(100+strlen(filenames[i]));
        FreeImageFiles(filenames, iffimg);
        sprintf(buf, "Can't open %s: %s", filenames[i], strerror(errno));
        *errstrp = buf;
        return bmhds;
    }
    InitIFFasDOS(iff);
    OpenIFF(iff, IFFF_READ);
    PropChunk(iff, ID_BMAP, ID_BMHD);
    PropChunk(iff, ID_BMAP, ID_CMAP);
    PropChunk(iff, ID_BMAP, ID_CAMG);
    PropChunk(iff, ID_BMAP, ID_PDAT);
    StopChunk(iff, ID_BMAP, ID_PLNE);
    if((j = ParseIFF(iff, IFFPARSE_SCAN)) != 0)
    {
        char *buf = malloc(100);
        FreeImageFiles(filenames, iffimg);
        sprintf(buf,"ParseIFF failed for image %d, failure code: %d",i,j);
        *errstrp = buf;
        return bmhds;
    }
    if(prop = FindProp(iff, ID_BMAP, ID_BMHD))
    {
        bmhd = (BitMapHeader *)prop->sp_Data;
    }
    else
    {
        FreeImageFiles(filenames, iffimg);
        CloseIFF(iff);
        Close(iff->iff_Stream);
        FreeIFF(iff);
        *errstrp = "No BMHD CHUNK in file";
        return bmhds;
    }
    if(prop = FindProp(iff, ID_BMAP, ID_CMAP))
    {
        cmap = prop->sp_Data;
        for(j = 0; j < (1L << bmhd->nPlanes)*3; j+=3)
        {
#if 0
        /* Some day we will want to use the larger palette
         * resolution available under v39 and later. i.e.
         * 32 instead of 12 bits of color. Ususally this
         * just means shifting the color left by 16-20 bits
         * depending on what intensity looks best. Experience
         * says that the higher values are better intensities.
         *
         * For now though we won't do this. The color table
         * structure is incompatible with earlier versions of
         * intuition. We would have to do some funny things
         * to make 3*AMII_MAXCOLORS longs work like 3*AMII_MAXCOLORS
         * UWORD's at run time... A union would help, but...
         */
        if(IntuitionBase->LibNode.lib_Version >= 39)
        {
            /* 8 bits of color, so shift to left end. */
            amiv_init_map[ j+0 ] = cmap[j+0]<<24;
            amiv_init_map[ j+1 ] = cmap[j+1]<<24;
            amiv_init_map[ j+2 ] = cmap[j+2]<<24;
        }
        else
#endif
        {
            /* We can only use 4 bits of the 8 that are stored in the
             * cmap, so mask them and then shift them into position
             * for the UWORD value to store.
             */
#ifndef TESTING
            amii_initmap[ j/3 ] =
            amiv_init_map[ j/3 ] =
                    ((cmap[j+0]>>4)<<8)|
                    ((cmap[j+1]>>4)<<4)|
                    (cmap[j+2]>>4);
#endif
        }
        }
    }
    else
    {
        FreeImageFiles(filenames, iffimg);
        CloseIFF(iff);
        Close(iff->iff_Stream);
        FreeIFF(iff);
        *errstrp = "No CMAP CHUNK in file";
        return bmhds;
    }
    if(prop = FindProp(iff, ID_BMAP, ID_PDAT))
    {
        struct PDAT *pp;
        pp = (struct PDAT *)prop->sp_Data;
        pictdata = *pp;
    }
    else
    {
        FreeImageFiles(filenames, iffimg);
        CloseIFF(iff);
        Close(iff->iff_Stream);
        FreeIFF(iff);
        *errstrp = "No PDAT CHUNK in file";
        return bmhds;
    }
    iffimg[ i ] = MyAllocBitMap(bmhd->w, bmhd->h,
        pictdata.nplanes + amii_extraplanes, MEMF_CHIP|MEMF_CLEAR);
    if(iffimg[ i ] == NULL)
    {
        char *buf = malloc(80);
        FreeImageFiles(filenames, iffimg);
        sprintf(buf, "Can't allocate bitmap for image %d\n", i);
        *errstrp = buf;
        return bmhds;
    }
    for(j = 0; j < pictdata.nplanes + amii_extraplanes; ++j)
    {
        ReadChunkBytes(iff, iffimg[i]->Planes[j], RASSIZE(bmhd->w, bmhd->h));
    }
    bmhds = *bmhd;
    CloseIFF(iff);
    Close(iff->iff_Stream);
    FreeIFF(iff);
    }
    CloseLibrary(IFFParseBase);
    tile = MyAllocBitMap(pictdata.xsize, pictdata.
      ysize,
        pictdata.nplanes + amii_extraplanes, MEMF_CHIP|MEMF_CLEAR);
    if(tile == NULL)
    {
    FreeImageFiles(filenames, iffimg);
    *errstrp = "Can't allocate tile bitmap for scaling";
    }
    return(bmhds);
}
BitMapHeader ReadTileImageFiles (void)
Definition at line 195 of file winchar.c.
References ifftimg, NULL, panic(), ReadImageFiles(), and tileimages.
Referenced by amii_init_nhwindows().
                    {
    char *errstr = NULL;
    BitMapHeader ret = ReadImageFiles(tileimages,
      ifftimg, &errstr);
    if(errstr){
    panic(errstr);
    }
    return ret;
}
void ReDisplayData (winid win)
Definition at line 1174 of file winmenu.c.
References amii_wins, clear_nhwindow, CountLines(), DisplayData(), max, amii_WinDesc::win, and WIN_ERR.
{
    int totalvis;
    register struct amii_WinDesc *cw;
    register struct Window *w;
    register struct Gadget *gd;
    unsigned long hidden, aidx, wheight;
    struct PropInfo *pip;
    
    if(win == WIN_ERR || !(cw = amii_wins[win]) || !(w = cw->
      win))
    return;
    for(gd = w->FirstGadget; gd && gd->GadgetID != 1;)
    gd = gd->NextGadget;
    if(!gd)
    return;
    wheight = (w->Height - w->BorderTop - w->BorderBottom-2)/w->RPort->TxHeight;
    pip = (struct PropInfo *)gd->SpecialInfo;
    totalvis = CountLines(win);
    hidden = max(totalvis - wheight, 0);
    aidx = (((ULONG)hidden * pip->VertPot) + (MAXPOT/2)) >> 16;
    clear_nhwindow(win);
    DisplayData(win, aidx);
}
void removetopl (int cnt)
Definition at line 2006 of file winfuncs.c.
References amii_cl_end(), amii_curs(), amii_wins, amii_WinDesc::curx, amii_WinDesc::cury, and WIN_MESSAGE.
{
    struct amii_WinDesc *cw=amii_wins[WIN_MESSAGE];
                    /* NB - this is sufficient for
                     * yn_function, but that's it
                     */
    if(cw->curx < cnt)cw->curx=0;
    else cw->curx -= cnt;
    amii_curs(WIN_MESSAGE, cw->curx+1, cw->cury);
    amii_cl_end(cw, cw->curx);
}
void SetBorder (struct Gadget * gd)
Referenced by EditClipping(), and EditColor().
void SetMazeType (MazeType)
Definition at line 932 of file winchar.c.
References maze_type.
{
    maze_type=t;
}
void SetPropInfo (struct Window * win, struct Gadget * gad, long vis, long total, long top)
Definition at line 1558 of file winmenu.c.
References max, and NULL.
Referenced by amii_doprev_message(), amii_putstr(), and DoMenuScroll().
{
    long mflags;
    register long hidden;
    register int body, pot;
    hidden = max(total-vis, 0);
    /* Force the last section to be just to the bottom */
    if(top > hidden)
    top = hidden;
    /* Scale the body position. */
    /* 2 lines overlap */
    if(hidden > 0 && total > 2)
    body = (ULONG) ((vis - 2) * MAXBODY) / (total - 2);
    else
    body = MAXBODY;
    if(hidden > 0)
    pot = (ULONG) (top * MAXPOT) / hidden;
    else
    pot = 0;
    mflags = AUTOKNOB|FREEVERT;
#ifdef INTUI_NEW_LOOK
    if(IntuitionBase->LibNode.lib_Version >= 37)
    {
    mflags |= PROPNEWLOOK;
    }
#endif
    NewModifyProp(gad, win, NULL,
                mflags, 0, pot, MAXBODY, body, 1);
}
void start_glyphout (winid window)
void TextSpaces (struct RastPort * rp, int nr)
Definition at line 435 of file winstr.c.
References spaces.
Referenced by amii_cl_end(), amii_clear_nhwindow(), and amii_putstr().
{
    if(nr < 1)
    return;
    while (nr > sizeof(spaces) - 1)
    {
    Text(rp, spaces, (long)sizeof(spaces) - 1);
    nr -= sizeof(spaces) - 1;
    }
    if (nr > 0)
    Text(rp, spaces, (long)nr);
}
int WindowGetchar (void)
Referenced by amii_getret(), amii_nhgetch(), and outmore().
WETYPE WindowGetevent (void)
Referenced by amii_nh_poskey().