nethack/sys/amiga/winstr.c File Reference
#include `NH:sys/amiga/windefs.h`
*
#include `NH:sys/amiga/winext.h`
*
#include `NH:sys/amiga/winproto.h`
*
Functions
void amii_putstr (winid window, int attr, const char *str)
void amii_scrollmsg (struct Window *w, struct amii_WinDesc *cw)
int amii_msgborder (struct Window *w)
void outmore (struct amii_WinDesc *cw)
void outsubstr (struct amii_WinDesc *cw, char *str, int len, int fudge)
void amii_putsym (winid st, int i, int y, CHAR_P c)
void amii_addtopl (char *s) const
void TextSpaces (struct RastPort *rp, int nr)
void amii_remember_topl ()
int amii_doprev_message ()
Function Documentation
void amii_addtopl (char * s) const
Definition at line 421 of file winstr.c.
References amii_msgborder(), amii_putstr(), amii_putsym(), amii_wins, amii_WinDesc::cols, amii_WinDesc::curx, amii_WinDesc::win, and WIN_MESSAGE.
{
    register struct amii_WinDesc *cw = amii_wins[
      WIN_MESSAGE];
    while(*s) {
    if(cw->curx == cw->cols - 1)
        amii_putstr(WIN_MESSAGE, 0, "");
    amii_putsym(WIN_MESSAGE, cw->curx + 1,
      amii_msgborder(cw->win), *s++);
    cw->curx++;
    }
}
int amii_doprev_message (void)
Definition at line 460 of file winstr.c.
References amii_cl_end(), amii_curs(), amii_setdrawpens(), amii_wins, amii_WinDesc::cols, amii_WinDesc::curx, amii_WinDesc::data, DisplayData(), max, amii_WinDesc::maxcol, amii_WinDesc::maxrow, MsgScroll, NHW_MESSAGE, NULL, panic(), scrollmsg, SetPropInfo(), SOFF, amii_WinDesc::vwy, amii_WinDesc::win, WIN_ERR, WIN_MESSAGE, and winpanicstr.
{
    struct amii_WinDesc *cw;
    struct Window *w;
    char *str;
    if(WIN_MESSAGE == WIN_ERR ||
    (cw = amii_wins[ WIN_MESSAGE ]) == NULL || (w = cw->
      win) == NULL)
    {
    panic(winpanicstr,WIN_MESSAGE, "doprev_message");
    }
    /* When an interlaced/tall screen is in use, the scroll bar will be there */
    /* Or in some other cases as well */
    if(scrollmsg)
    {
    struct Gadget *gd;
    struct PropInfo *pip;
    int hidden, topidx, i, total, wheight;
    for(gd = w->FirstGadget; gd && gd->GadgetID != 1;)
        gd = gd->NextGadget;
    if(gd)
    {
        pip = (struct PropInfo *)gd->SpecialInfo;
        wheight = (w->Height - w->BorderTop -
                w->BorderBottom - 2) / w->RPort->TxHeight;
        hidden = max(cw->maxrow - wheight, 0);
        topidx = (((ULONG)hidden * pip->VertPot) + (MAXPOT/2)) >> 16;
        for(total = i = 0; i < cw->maxrow; ++i)
        {
        if(cw->data[i][1] != 0)
            ++total;
        }
        i = 0;
        topidx -= wheight/4 + 1;
        if (topidx < 0)
        topidx = 0;
        SetPropInfo(w, &MsgScroll, wheight, total, topidx);
        DisplayData(WIN_MESSAGE, topidx);
    }
    return(0);
    }
    if(--cw->vwy < 0)
    {
    cw->maxcol = 0;
    DisplayBeep(NULL);
    str = "\0\0No more history saved...";
    }
    else
    str = cw->data[ cw->vwy ];
    amii_cl_end(cw, 0);
    amii_curs(WIN_MESSAGE, 1, 0);
    amii_setdrawpens(amii_wins[WIN_MESSAGE]->win,
      NHW_MESSAGE);
    Text(w->RPort,str+SOFF,strlen(str+SOFF));
    cw->curx = cw->cols + 1;
    return(0);
}
int amii_msgborder (struct Window * w)
Definition at line 324 of file winstr.c.
Referenced by amii_addtopl(), amii_putstr(), amii_scrollmsg(), and outmore().
{
    register int bottom;
    /* There is a one pixel border at the borders, so subtract two */
    bottom = w->Height - w->BorderTop - w->BorderBottom - 2;
    bottom /= w->RPort->TxHeight;
    if(bottom > 0)
    --bottom;
    return(bottom);
}
void amii_putstr (winid window, int attr, const char * str)
Definition at line 12 of file winstr.c.
References alloc(), amii_cl_end(), amii_create_nhwindow(), amii_curs(), amii_msgborder(), amii_scrollmsg(), amii_sethipens(), amii_wins, amiIDisplay, flag::botlx, amii_WinDesc::cols, CountLines(), amii_WinDesc::curx, amii_WinDesc::cury, amii_WinDesc::data, flags, FLMSG_FIRST, free(), iflags, amii_DisplayDesc::lastwin, max, amii_WinDesc::maxcol, amii_WinDesc::maxrow, instance_flags::msg_history, MsgScroll, NHW_BASE, NHW_MAP, NHW_MENU, NHW_MESSAGE, NHW_STATUS, NHW_TEXT, NULL, outmore(), outsubstr(), panic(), amii_WinDesc::rows, scrollmsg, SEL_ITEM, SetPropInfo(), SOFF, Strcpy, TBUFSZ, TextSpaces(), toplines, amii_WinDesc::type, VATTR, amii_WinDesc::vwy, amii_WinDesc::wflags, amii_WinDesc::win, WIN_BASE, WIN_ERR, WIN_MESSAGE, instance_flags::window_inited, winpanicstr, and WINVERS_AMIV.
Referenced by amii_add_menu(), amii_addtopl(), amii_init_nhwindows(), amii_raw_print(), amii_raw_print_bold(), and amiv_flush_glyph_buffer().
{
    int fudge;
    int len;
    struct Window *w;
    register struct amii_WinDesc *cw;
    char *ob;
    int i, j, n0, bottom, totalvis, wheight;
    static int wrapping = 0;
    /* Always try to avoid a panic when there is no window */
    if(window == WIN_ERR)
    {
    window = WIN_BASE;
    if(window == WIN_ERR)
        window = WIN_BASE = amii_create_nhwindow(
      NHW_BASE);
    }
    if(window == WIN_ERR || (cw = amii_wins[window]) == NULL)
    {
    iflags.window_inited=0;
    panic(winpanicstr,window, "putstr");
    }
    w = cw->win;
    if(!str) return;
    amiIDisplay->lastwin = window; /* do we care??? */
    /* NHW_MENU windows are not opened immediately, so check if we
     * have the window pointer yet
     */
    if(w)
    {
    /* Set the drawing mode and pen colors */
    SetDrMd(w->RPort, JAM2);
    amii_sethipens(w, cw->type, attr);
    }
    else if(cw->type != NHW_MENU && cw->type != NHW_TEXT)
    {
    panic("NULL window pointer in putstr 2: %d", window);
    }
    /* Okay now do the work for each type */
    switch(cw->type)
    {
    case NHW_MESSAGE:
    if(WINVERS_AMIV)
        fudge = 2;
    else
    {
        /* 8 for --more--, 1 for preceeding sp, 1 for putstr pad */
        fudge = 10;
    }
        /* There is a one pixel border at the borders, so subtract two */
        bottom = amii_msgborder(w);
    wheight = (w->Height - w->BorderTop -
                w->BorderBottom - 3) / w->RPort->TxHeight;
    
    if (scrollmsg || wheight > 1)
        fudge = 0;
    amii_scrollmsg(w, cw);
    while (isspace(*str)) str++;
    strncpy(toplines, str, TBUFSZ);
    toplines[ TBUFSZ - 1 ] = 0;
    /* For initial message to be visible, we need to explicitly position the
     * cursor. This flag, cw->curx == -1 is set elsewhere to force the
     * cursor to be repositioned to the "bottom".
     */
    if(cw->curx == -1)
    {
        amii_curs(WIN_MESSAGE, 1, bottom);
        cw->curx = 0;
    }
    /* If used all of history lines, move them down */
    if(cw->maxrow >= iflags.msg_history)
    {
        if(cw->data[ 0 ])
        free(cw->data[ 0 ]);
        memcpy(cw->data, &cw->data[ 1 ],
        (iflags.msg_history - 1) * sizeof(char *));
        cw->data[ iflags.msg_history - 1 ] =
                (char *) alloc(strlen(toplines) + 5);
        strcpy(cw->data[ i = iflags.msg_history - 1 ] +
                SOFF + (scrollmsg!=0), toplines);
    }
    else
    {
        /* Otherwise, allocate a new one and copy the line in */
        cw->data[ cw->maxrow ] = (char *)
                    alloc(strlen(toplines) + 5);
        strcpy(cw->data[ i = cw->maxrow++ ] +
                SOFF + (scrollmsg!=0), toplines);
    }
    cw->data[ i ][ SEL_ITEM ] = 1;
    cw->data[ i ][ VATTR ] = attr+1;
    if(scrollmsg)
    {
        cw->curx = 0;
        cw->data[ i ][2] = (cw->wflags & FLMSG_FIRST) ? '>' : ' ';
    }
    str = cw->data[i] + SOFF;
    if(cw->curx + strlen(str) >= (cw->cols-fudge))
    {
        int i;
        char *ostr = (char *)str;
        char *p;
        while(cw->curx + strlen(str) >= (cw->cols-fudge))
        {
        for(p=((char *)&str[ cw->cols-1 - cw->curx ])-fudge; !isspace(*p) && p > str;)
            --p;
        if (p < str) p = (char *)str;
        if(p == str) {
        /* p = (char *)&str[ cw->cols ]; */
            outmore(cw);
            continue;
        }
        i = (long)p-(long)str;
        outsubstr(cw, (char *)str, i, fudge);
        cw->curx += i;
        while(isspace(*p)) p++;
        str = p;
#if 0
        if(str != ostr) {
            outsubstr(cw, "+", 1, fudge);
            cw->curx+=2;
        }
#endif
        if(*str)
            amii_scrollmsg(w, cw);
        amii_cl_end(cw, cw->curx);
        }
        if(*str)
        {
        if(str != ostr)
        {
            outsubstr(cw, "+", 1, fudge);
            cw->curx+=2;
        }
        while (isspace(*str))
            ++str;
        outsubstr(cw, (char *)str, i = strlen((char *)str), fudge);
        cw->curx += i;
        amii_cl_end(cw, cw->curx);
        }
    }
    else
    {
        outsubstr(cw, (char *)str, i = strlen((char *)str), fudge);
        cw->curx += i;
        amii_cl_end(cw, cw->curx);
    }
    cw->wflags &= ~FLMSG_FIRST;
    len = 0;
    if(scrollmsg)
    {
        totalvis = CountLines(window);
        SetPropInfo(w, &MsgScroll,
          (w->Height-w->BorderTop-w->BorderBottom) / w->RPort->TxHeight,
          totalvis, totalvis);
    }
    i = strlen(toplines + SOFF);
    cw->maxcol = max(cw->maxcol, i);
    cw->vwy = cw->maxrow;
    break;
    case NHW_STATUS:
    if(cw->data[ cw->cury ] == NULL)
        panic("NULL pointer for status window");
    ob = &cw->data[cw->cury][j = cw->curx];
    if(flags.botlx) *ob = 0;
        /* Display when beam at top to avoid flicker... */
    WaitTOF();
    Text(w->RPort,(char *)str,strlen((char *)str));
    if(cw->cols > strlen(str))
        TextSpaces(w->RPort, cw->cols - strlen(str));
    (void) strncpy(cw->data[cw->cury], str, cw->cols);
    cw->data[cw->cury][cw->cols-1] = '\0'; /* null terminate */
    cw->cury = (cw->cury+1) % 2;
    cw->curx = 0;
    break;
    case NHW_MAP:
    case NHW_BASE:
    if (cw->type == NHW_BASE && wrapping) {
        amii_curs(window, cw->curx+1, cw->cury);
        TextSpaces(w->RPort, cw->cols);
        if (cw->cury < cw->rows) {
        amii_curs(window, cw->curx+1, cw->cury+1);
        TextSpaces(w->RPort, cw->cols);
        cw->cury--;
        }
    }
    amii_curs(window, cw->curx+1, cw->cury);
    Text(w->RPort,(char *)str,strlen((char *)str));
    cw->curx = 0;
        /* CR-LF is automatic in these windows */
    cw->cury++;
    if (cw->type == NHW_BASE && cw->cury >= cw->rows) {
        cw->cury = 0;
        wrapping = 1;
    }
    break;
    case NHW_MENU:
    case NHW_TEXT:
    /* always grows one at a time, but alloc 12 at a time */
    if(cw->cury >= cw->rows || !cw->data)
    {
        char **tmp;
        /* Allocate 12 more rows */
        cw->rows += 12;
        tmp = (char**) alloc(sizeof(char*) * cw->rows);
        /* Copy the old lines */
        for(i=0; i<cw->cury; i++)
        tmp[i] = cw->data[i];
        if(cw->data) {
        free(cw->data);
        cw->data = NULL;
        }
        cw->data = tmp;
        /* Null out the unused entries. */
        for(i=cw->cury; i<cw->rows; i++)
        cw->data[i] = 0;
    }
    if(!cw->data)
        panic("no data storage");
        /* Shouldn't need to do this, but... */
    if(cw->data && cw->data[cw->cury]) {
        free(cw->data[cw->cury]);
        cw->data[cw->cury] = NULL;
    }
    n0 = strlen(str)+1;
    cw->data[cw->cury] = (char*) alloc(n0+SOFF);
        /* avoid nuls, for convenience */
    cw->data[cw->cury][VATTR] = attr+1;
    cw->data[cw->cury][SEL_ITEM] = 0;
    Strcpy(cw->data[cw->cury] + SOFF, str);
    if(n0 > cw->maxcol) cw->maxcol = n0;
    if(++cw->cury > cw->maxrow) cw->maxrow = cw->cury;
    break;
    default:
    panic("Invalid or unset window type in putstr()");
    }
}
void amii_putsym (winid st, int i, int y, CHAR_P c)
Definition at line 409 of file winstr.c.
References amii_curs(), and amii_wins.
Referenced by amii_addtopl().
{
    amii_curs(st, i, y);
    Text(amii_wins[st]->win->RPort, &c, 1);
}
void amii_remember_topl (void)
Definition at line 452 of file winstr.c.
{
    /* ignore for now. I think this will be done automatically by
     * the code writing to the message window, but I could be wrong.
     */
}
void amii_scrollmsg (struct Window * w, struct amii_WinDesc * cw)
Definition at line 294 of file winstr.c.
References amii_curs(), amii_msgborder(), outmore(), scrollmsg, and WIN_MESSAGE.
Referenced by amii_putstr().
{
    int bottom, wheight;
    bottom = amii_msgborder(w);
    wheight = (w->Height - w->BorderTop -
            w->BorderBottom - 3) / w->RPort->TxHeight;
    
    if(scrollmsg)
    {
    if(++cw->disprows > wheight)
    {
        outmore(cw);
        cw->disprows = 1; /* count this line... */
    }
    else
    {
        ScrollRaster(w->RPort, 0, w->RPort->TxHeight,
            w->BorderLeft, w->BorderTop + 1,
            w->Width - w->BorderRight-1,
            w->Height - w->BorderBottom - 1);
    }
    amii_curs(WIN_MESSAGE, 1, bottom);
    }
}
void outmore (struct amii_WinDesc * cw)
Definition at line 338 of file winstr.c.
References amii_cl_end(), amii_curs(), amii_msgborder(), FLMAP_SKIP, flushIDCMP(), HackPort, WEVENT::key, lastevent, scrollmsg, WEVENT::type, WEVENT::un, WEKEY, amii_WinDesc::win, WIN_MESSAGE, and WindowGetchar().
Referenced by amii_display_nhwindow(), amii_putstr(), amii_scrollmsg(), and outsubstr().
{
    struct Window *w = cw->win;
    if((cw->wflags & FLMAP_SKIP) == 0)
    {
    if(scrollmsg)
    {
        int bottom;
        bottom = amii_msgborder(w);
        ScrollRaster(w->RPort, 0, w->RPort->TxHeight,
            w->BorderLeft, w->BorderTop+1,
            w->Width - w->BorderRight-1,
            w->Height - w->BorderBottom - 1);
        amii_curs(WIN_MESSAGE, 1, bottom); /* -1 for inner border */
        Text(w->RPort, "--more--", 8);
    }
    else
        Text(w->RPort, " --more--", 9);
    /* Make sure there are no events in the queue */
    flushIDCMP(HackPort);
    /* Allow mouse clicks to clear --more-- */
    WindowGetchar();
    if(lastevent.type == WEKEY && lastevent.un.key == '\33')
        cw->wflags |= FLMAP_SKIP;
    }
    if(!scrollmsg)
    {
    amii_curs(WIN_MESSAGE, 1, 0);
    amii_cl_end(cw, cw->curx);
    }
}
void outsubstr (struct amii_WinDesc * cw, char * str, int len, int fudge)
Definition at line 377 of file winstr.c.
References outmore(), scrollmsg, spaces, and amii_WinDesc::win.
Referenced by amii_putstr().
{
    struct Window *w = cw->win;
    if(cw->curx)
    {
    /* Check if this string and --more-- fit, if not,
     * then put out --more-- and wait for a key.
     */
    if((len + fudge) + cw->curx >= cw->cols)
    {
        if(!scrollmsg)
        outmore(cw);
    }
    else
    {
        /* Otherwise, move and put out a blank separator */
        Text(w->RPort, spaces, 1);
        cw->curx += 1;
    }
    }
    Text(w->RPort,str,len);
}
void TextSpaces (struct RastPort * rp, int nr)
Definition at line 435 of file winstr.c.
References spaces.
Referenced by amii_cl_end(), amii_clear_nhwindow(), and amii_putstr().
{
    if(nr < 1)
    return;
    while (nr > sizeof(spaces) - 1)
    {
    Text(rp, spaces, (long)sizeof(spaces) - 1);
    nr -= sizeof(spaces) - 1;
    }
    if (nr > 0)
    Text(rp, spaces, (long)nr);
}