nethack/win/X11/wintext.c File Reference
#include <X11/Intrinsic.h>
*
#include <X11/StringDefs.h>
*
#include <X11/Shell.h>
*
#include <X11/Xos.h>
*
#include <X11/Xaw/Form.h>
*
#include <X11/Xaw/AsciiText.h>
*
#include <X11/Xaw/Cardinals.h>
*
#include <X11/Xatom.h>
*
#include `hack.h`
*
#include `winX.h`
*
#include `xwindow.h`
*
Macros
#define PRESERVE_NO_SYSV /* X11 include files may define SYSV */
#define TRANSIENT_TEXT /* text window is a transient window (no positioning) */
Functions
void delete_text (Widget w, XEvent *event, String *params, Cardinal *num_params)
void dismiss_text (Widget w, XEvent *event, String *params, Cardinal *num_params)
void key_dismiss_text (Widget w, XEvent *event, String *params, Cardinal *num_params)
void add_to_text_window (struct xwindow *wp, int attr, const char *str)
void display_text_window (struct xwindow *wp, boolean blocking)
void create_text_window (struct xwindow *wp)
void destroy_text_window (struct xwindow *wp)
void clear_text_window (struct xwindow *wp)
void append_text_buffer (struct text_buffer *tb, const char *str, boolean concat)
void init_text_buffer (struct text_buffer *tb)
void clear_text_buffer (struct text_buffer *tb)
void free_text_buffer (struct text_buffer *tb)
Variables
static const char text_translations []
Macro Definition Documentation
#define PRESERVE_NO_SYSV /* X11 include files may define SYSV */
Definition at line 12 of file wintext.c.
#define TRANSIENT_TEXT /* text window is a transient window (no positioning) */
Definition at line 40 of file wintext.c.
Function Documentation
void add_to_text_window (struct xwindow * wp, int attr, const char * str)
Definition at line 135 of file wintext.c.
References append_text_buffer(), FALSE, text_info_t::fs, text_info_t::max_width, text_info_t::text, and width.
Referenced by X11_putstr().
{
    struct text_info_t *text_info = wp->text_information;
    int width;
    append_text_buffer(&text_info->text, str, FALSE);
    /* Calculate text width and save longest line */
    width = XTextWidth(text_info->fs, str, (int) strlen(str));
    if (width > text_info->max_width)
    text_info->max_width = width;
}
void append_text_buffer (struct text_buffer * tb, const char * str, boolean concat)
Definition at line 349 of file wintext.c.
References alloc(), free(), index(), panic(), and printf.
Referenced by add_to_text_window(), and adjust_status().
{
    char *copy;
    int length;
    if (!tb->text) panic("append_text_buffer: null text buffer");
    if (str) {
    length = strlen(str);
    } else {
    length = 0;
    }
    if (length + tb->text_last + 1 >= tb->text_size) {
    /* we need to go to a bigger buffer! */
#ifdef VERBOSE
    printf("append_text_buffer: text buffer growing from %d to %d bytes\n",
                tb->text_size, 2*tb->text_size);
#endif
    copy = (char *) alloc((unsigned)tb->text_size*2);
    (void) memcpy(copy, tb->text, tb->text_last);
    free(tb->text);
    tb->text = copy;
    tb->text_size *= 2;
    }
    if (tb->num_lines) { /* not first --- append a newline */
    char appchar = '\n';
    if(concat && !index("!.?'\")", tb->text[tb->text_last-1])) {
        appchar = ' ';
        tb->num_lines--; /* offset increment at end of function */
    }
    *(tb->text + tb->text_last) = appchar;
    tb->text_last++;
    }
    if (str) {
    (void) memcpy((tb->text+tb->text_last), str, length+1);
    if(length) {
        /* Remove all newlines. Otherwise we have a confused line count. */
        copy = (tb->text+tb->text_last);
        while ((copy = index(copy, '\n')) != (char*)0)
        *copy = ' ';
    }
    tb->text_last += length;
    }
    tb->text[tb->text_last] = '\0';
    tb->num_lines++;
}
void clear_text_buffer (struct text_buffer * tb)
Definition at line 419 of file wintext.c.
References text_buffer::text_last.
Referenced by adjust_status(), and clear_text_window().
{
    tb->text_last = 0;
    tb->text[0] = '\0';
    tb->num_lines = 0;
}
void clear_text_window (struct xwindow * wp)
Definition at line 338 of file wintext.c.
References clear_text_buffer().
Referenced by X11_clear_nhwindow().
{
    clear_text_buffer(&wp->text_information->text);
}
void create_text_window (struct xwindow * wp)
Definition at line 242 of file wintext.c.
References alloc(), text_info_t::blocked, text_info_t::destroy_on_ack, text_info_t::extra_height, text_info_t::extra_width, FALSE, text_info_t::fs, init_text_buffer(), killer, text_info_t::max_width, NHW_TEXT, text_info_t::text, text_translations, toplevel, TRUE, WIN_ERR, and WIN_MAP.
Referenced by X11_create_nhwindow().
{
    struct text_info_t *text_info;
    Arg args[8];
    Cardinal num_args;
    Position top_margin, bottom_margin, left_margin, right_margin;
    Widget form;
    wp->type = NHW_TEXT;
    wp->text_information = text_info =
            (struct text_info_t *) alloc(sizeof(struct
      text_info_t));
    init_text_buffer(&text_info->text);
    text_info->max_width = 0;
    text_info->extra_width = 0;
    text_info->extra_height = 0;
    text_info->blocked = FALSE;
    text_info->destroy_on_ack = TRUE; /* Ok to destroy before display */
#ifdef GRAPHIC_TOMBSTONE
    text_info->is_rip = FALSE;
#endif
    num_args = 0;
    XtSetArg(args[num_args], XtNallowShellResize, True); num_args++;
    XtSetArg(args[num_args], XtNtranslations,
        XtParseTranslationTable(text_translations)); num_args++;
#ifdef TRANSIENT_TEXT
    wp->popup = XtCreatePopupShell("text", transientShellWidgetClass,
                   toplevel, args, num_args);
#else
    wp->popup = XtCreatePopupShell("text", topLevelShellWidgetClass,
                   toplevel, args, num_args);
#endif
    XtOverrideTranslations(wp->popup,
    XtParseTranslationTable("<Message>WM_PROTOCOLS: delete_text()"));
    num_args = 0;
    XtSetArg(args[num_args], XtNallowShellResize, True); num_args++;
    form = XtCreateManagedWidget("form", formWidgetClass, wp->popup,
        args, num_args);
    num_args = 0;
    XtSetArg(args[num_args], XtNdisplayCaret, False); num_args++;
    XtSetArg(args[num_args], XtNresize, XawtextResizeBoth); num_args++;
    XtSetArg(args[num_args], XtNtranslations,
        XtParseTranslationTable(text_translations)); num_args++;
    wp->w = XtCreateManagedWidget(
        killer && WIN_MAP == WIN_ERR ?
                  "tombstone" : "text_text", /* name */
        asciiTextWidgetClass,
        form, /* parent widget */
        args, /* set some values */
        num_args); /* number of values to set */
    /* Get the font and margin information. */
    num_args = 0;
    XtSetArg(args[num_args], XtNfont, &text_info->fs); num_args++;
    XtSetArg(args[num_args], XtNtopMargin, &top_margin); num_args++;
    XtSetArg(args[num_args], XtNbottomMargin, &bottom_margin); num_args++;
    XtSetArg(args[num_args], XtNleftMargin, &left_margin); num_args++;
    XtSetArg(args[num_args], XtNrightMargin, &right_margin); num_args++;
    XtGetValues(wp->w, args, num_args);
    text_info->extra_width = left_margin + right_margin;
    text_info->extra_height = top_margin + bottom_margin;
}
void delete_text (Widget w, XEvent * event, String * params, Cardinal * num_params)
Definition at line 58 of file wintext.c.
References text_info_t::blocked, text_info_t::destroy_on_ack, destroy_text_window(), exit_x_event, find_widget(), nh_XtPopdown(), xwindow::popup, and TRUE.
{
    struct xwindow *wp;
    struct text_info_t *text_info;
    wp = find_widget(w);
    text_info = wp->text_information;
    nh_XtPopdown(wp->popup);
    if (text_info->blocked) {
    exit_x_event = TRUE;
    } else if (text_info->destroy_on_ack) {
    destroy_text_window(wp);
    }
}
void destroy_text_window (struct xwindow * wp)
Definition at line 314 of file wintext.c.
References text_info_t::blocked, text_info_t::destroy_on_ack, free(), free_text_buffer(), NHW_NONE, text_info_t::text, and TRUE.
Referenced by delete_text(), dismiss_text(), and X11_destroy_nhwindow().
{
    /* Don't need to pop down, this only called from dismiss_text(). */
    struct text_info_t *text_info = wp->text_information;
    /*
     * If the text window was blocked, then the user has already ACK'ed
     * it and we are free to really destroy the window. Otherwise, don't
     * destroy until the user dismisses the window via a key or button
     * press.
     */
    if (text_info->blocked || text_info->destroy_on_ack) {
    XtDestroyWidget(wp->popup);
    free_text_buffer(&text_info->text);
    free((genericptr_t)text_info), wp->text_information = 0;
    wp->type = NHW_NONE; /* allow reuse */
    } else {
    text_info->destroy_on_ack = TRUE; /* destroy on next ACK */
    }
}
void dismiss_text (Widget w, XEvent * event, String * params, Cardinal * num_params)
Definition at line 86 of file wintext.c.
References text_info_t::blocked, text_info_t::destroy_on_ack, destroy_text_window(), exit_x_event, find_widget(), nh_XtPopdown(), xwindow::popup, and TRUE.
Referenced by key_dismiss_text().
{
    struct xwindow *wp;
    struct text_info_t *text_info;
    wp = find_widget(w);
    text_info = wp->text_information;
    nh_XtPopdown(wp->popup);
    if (text_info->blocked) {
    exit_x_event = TRUE;
    } else if (text_info->destroy_on_ack) {
    destroy_text_window(wp);
    }
}
void display_text_window (struct xwindow * wp, boolean blocking)
Definition at line 152 of file wintext.c.
References text_info_t::blocked, text_info_t::destroy_on_ack, EXIT_ON_EXIT, text_info_t::extra_height, text_info_t::extra_width, FALSE, height, text_info_t::max_width, nh_XtPopdown(), nh_XtPopup(), nhFontHeight(), text_buffer::num_lines, positionpopup(), text_buffer::text, text_info_t::text, width, wm_delete_window, and x_event().
Referenced by X11_display_nhwindow().
{
    struct text_info_t *text_info;
    Arg args[8];
    Cardinal num_args;
    Dimension width, height, font_height;
    int nlines;
    text_info = wp->text_information;
    width = text_info->max_width + text_info->extra_width;
    text_info->blocked = blocking;
    text_info->destroy_on_ack = FALSE;
    font_height = nhFontHeight(wp->w);
    /*
     * Calculate the number of lines to use. First, find the number of
     * lines that would fit on the screen. Next, remove four of these
     * lines to give room for a possible window manager titlebar (some
     * wm's put a titlebar on transient windows). Make sure we have
     * _some_ lines. Finally, use the number of lines in the text if
     * there are fewer than the max.
     */
    nlines = (XtScreen(wp->w)->height - text_info->extra_height) / font_height;
    nlines -= 4;
    if (nlines > text_info->text.num_lines)
    nlines = text_info->text.num_lines;
    if (nlines <= 0) nlines = 1;
    height = nlines * font_height + text_info->extra_height;
    num_args = 0;
    if (nlines < text_info->text.num_lines) {
    /* add on width of scrollbar. Really should look this up,
     * but can't until the window is realized. Chicken-and-egg problem.
     */
    width += 20;
    }
#ifdef GRAPHIC_TOMBSTONE
    if (text_info->is_rip) {
    Widget rip = create_ripout_widget(XtParent(wp->w));
    XtSetArg(args[num_args], XtNfromVert, rip); num_args++;
    }
#endif
    if (width > (Dimension) XtScreen(wp->w)->width) { /* too wide for screen */
    /* Back off some amount - we really need to back off the scrollbar */
    /* width plus some extra. */
    width = XtScreen(wp->w)->width - 20;
    }
    XtSetArg(args[num_args], XtNstring, text_info->text.text); num_args++;
    XtSetArg(args[num_args], XtNwidth, width); num_args++;
    XtSetArg(args[num_args], XtNheight, height); num_args++;
    XtSetValues(wp->w, args, num_args);
#ifdef TRANSIENT_TEXT
    XtRealizeWidget(wp->popup);
    XSetWMProtocols(XtDisplay(wp->popup), XtWindow(wp->popup),
            &wm_delete_window, 1);
    positionpopup(wp->popup, FALSE);
#endif
    nh_XtPopup(wp->popup, (int)XtGrabNone, wp->w);
    /* Kludge alert. Scrollbars are not sized correctly by the Text widget */
    /* if added before the window is displayed, so do it afterward. */
    num_args = 0;
    if (nlines < text_info->text.num_lines) { /* add vert scrollbar */
    XtSetArg(args[num_args], XtNscrollVertical, XawtextScrollAlways);
                                num_args++;
    }
    if (width >= (Dimension) (XtScreen(wp->w)->width-20)) { /* too wide */
    XtSetArg(args[num_args], XtNscrollHorizontal, XawtextScrollAlways);
                                num_args++;
    }
    if (num_args) XtSetValues(wp->w, args, num_args);
    /* We want the user to acknowlege. */
    if (blocking) {
    (void) x_event(EXIT_ON_EXIT);
    nh_XtPopdown(wp->popup);
    }
}
void free_text_buffer (struct text_buffer * tb)
Definition at line 429 of file wintext.c.
References free().
Referenced by destroy_text_window().
{
    free(tb->text);
    tb->text = (char *) 0;
    tb->text_size = 0;
    tb->text_last = 0;
    tb->num_lines = 0;
}
void init_text_buffer (struct text_buffer * tb)
Definition at line 407 of file wintext.c.
References alloc(), START_SIZE, and text_buffer::text.
Referenced by create_status_window(), and create_text_window().
{
    tb->text = (char *) alloc(START_SIZE);
    tb->text[0] = '\0';
    tb->text_size = START_SIZE;
    tb->text_last = 0;
    tb->num_lines = 0;
}
void key_dismiss_text (Widget w, XEvent * event, String * params, Cardinal * num_params)
Definition at line 109 of file wintext.c.
References dismiss_text(), and key_event_to_char().
{
    char ch = key_event_to_char((XKeyEvent *) event);
    if (ch) dismiss_text(w, event, params, num_params);
}
Variable Documentation
const char text_translations[] [static]
Initial value:
=
    "#override\n\
     <BtnDown>: dismiss_text()\n\
     <Key>: key_dismiss_text()"
Definition at line 42 of file wintext.c.
Referenced by create_text_window().