nethack/win/X11/winval.c File Reference
#include <stdio.h>
*
#include <X11/Intrinsic.h>
*
#include <X11/StringDefs.h>
*
#include <X11/Xaw/Label.h>
*
#include <X11/Xaw/Form.h>
*
#include <X11/Xaw/Cardinals.h>
*
#include `hack.h`
*
#include `winX.h`
*
Macros
#define PRESERVE_NO_SYSV /* X11 include files may define SYSV */
#define WNAME `name`
#define WVALUE `value`
Functions
Widget create_value (Widget parent, const char *name_value)
void set_name (Widget w, char *new_label)
void set_name_width (Widget w, int new_width)
int get_name_width (Widget w)
void set_value (Widget w, const char *new_value)
void set_value_width (Widget w, int new_width)
int get_value_width (Widget w)
void hilight_value (Widget w)
void swap_fg_bg (Widget w)
Macro Definition Documentation
#define PRESERVE_NO_SYSV /* X11 include files may define SYSV */
Definition at line 12 of file winval.c.
#define WNAME `name`
Definition at line 31 of file winval.c.
Referenced by create_value(), get_name_width(), set_name(), and set_name_width().
#define WVALUE `value`
Definition at line 32 of file winval.c.
Referenced by create_value(), get_value_width(), hilight_value(), set_value(), and set_value_width().
Function Documentation
Widget create_value (Widget parent, const char * name_value)
Definition at line 36 of file winval.c.
References name, WNAME, and WVALUE.
Referenced by create_widget().
{
    Widget form, name;
    Arg args[8];
    Cardinal num_args;
    num_args = 0;
    XtSetArg(args[num_args], XtNborderWidth, 0); num_args++;
    XtSetArg(args[num_args], XtNdefaultDistance, 0); num_args++;
    form = XtCreateManagedWidget(name_value,
                formWidgetClass,
                parent, args, num_args);
    num_args = 0;
    XtSetArg(args[num_args], XtNjustify, XtJustifyRight); num_args++;
    XtSetArg(args[num_args], XtNborderWidth, 0); num_args++;
    XtSetArg(args[num_args], XtNlabel, name_value); num_args++;
    XtSetArg(args[num_args], XtNinternalHeight, 0); num_args++;
    name = XtCreateManagedWidget(WNAME,
                labelWidgetClass,
                form, args, num_args);
    num_args = 0;
    XtSetArg(args[num_args], XtNjustify, XtJustifyRight); num_args++;
    XtSetArg(args[num_args], XtNborderWidth, 0); num_args++;
    XtSetArg(args[num_args], XtNfromHoriz, name); num_args++;
    XtSetArg(args[num_args], XtNinternalHeight, 0); num_args++;
    (void) XtCreateManagedWidget(WVALUE,
                labelWidgetClass,
                form, args, num_args);
    return form;
}
int get_name_width (Widget w)
Definition at line 98 of file winval.c.
References name, width, and WNAME.
Referenced by get_widths().
{
    Arg args[1];
    Dimension width;
    Widget name;
    name = XtNameToWidget(w, WNAME);
    XtSetArg(args[0], XtNwidth, &width);
    XtGetValues(name, args, ONE);
    return (int) width;
}
int get_value_width (Widget w)
Definition at line 139 of file winval.c.
References width, and WVALUE.
Referenced by get_widths().
{
    Arg args[1];
    Widget val;
    Dimension width;
    val = XtNameToWidget(w, WVALUE);
    XtSetArg(args[0], XtNwidth, &width);
    XtGetValues(val, args, ONE);
    return (int) width;
}
void hilight_value (Widget w)
Definition at line 155 of file winval.c.
References swap_fg_bg(), and WVALUE.
Referenced by check_turn_events(), and update_val().
{
    swap_fg_bg(XtNameToWidget(w, WVALUE));
}
void set_name (Widget w, char * new_label)
Definition at line 72 of file winval.c.
References name, and WNAME.
Referenced by update_val().
{
    Arg args[1];
    Widget name;
    name = XtNameToWidget(w, WNAME);
    XtSetArg(args[0], XtNlabel, new_label);
    XtSetValues(name, args, ONE);
}
void set_name_width (Widget w, int new_width)
Definition at line 85 of file winval.c.
References name, and WNAME.
Referenced by set_widths().
{
    Arg args[1];
    Widget name;
    name = XtNameToWidget(w, WNAME);
    XtSetArg(args[0], XtNwidth, new_width);
    XtSetValues(name, args, ONE);
}
void set_value (Widget w, const char * new_value)
Definition at line 113 of file winval.c.
References WVALUE.
Referenced by create_widget(), null_out_status(), and update_val().
{
    Arg args[1];
    Widget val;
    val = XtNameToWidget(w, WVALUE);
    XtSetArg(args[0], XtNlabel, new_value);
    XtSetValues(val, args, ONE);
}
void set_value_width (Widget w, int new_width)
Definition at line 126 of file winval.c.
References WVALUE.
Referenced by set_widths().
{
    Arg args[1];
    Widget val;
    val = XtNameToWidget(w, WVALUE);
    XtSetArg(args[0], XtNwidth, new_width);
    XtSetValues(val, args, ONE);
}
void swap_fg_bg (Widget w)
Definition at line 163 of file winval.c.
Referenced by ec_dismiss(), ec_key(), extend_select(), and hilight_value().
{
    Arg args[2];
    Pixel fg, bg;
    XtSetArg(args[0], XtNforeground, &fg);
    XtSetArg(args[1], XtNbackground, &bg);
    XtGetValues(w, args, TWO);
    XtSetArg(args[0], XtNforeground, bg);
    XtSetArg(args[1], XtNbackground, fg);
    XtSetValues(w, args, TWO);
}