nethack/src/worm.c File Reference
#include `hack.h`
*
#include `lev.h`
*
Data Structures
struct wseg
Macros
#define newseg() (struct wseg *) alloc(sizeof(struct wseg))
#define dealloc_seg(wseg) free((genericptr_t) (wseg))
Functions
STATIC_DCL void FDECL (toss_wsegs,(struct wseg *, BOOLEAN_P))
STATIC_DCL void FDECL (shrink_worm,(int))
STATIC_DCL void FDECL (random_dir,(XCHAR_P, XCHAR_P, xchar *, xchar *))
STATIC_DCL struct wseg * FDECL (create_worm_tail,(int))
int get_wormno ()
void initworm (struct monst *worm, int wseg_count)
STATIC_OVL void toss_wsegs (struct wseg *curr, boolean display_update)
STATIC_OVL void shrink_worm (int wnum)
void worm_move (struct monst *worm)
void worm_nomove (struct monst *worm)
void wormgone (struct monst *worm)
void wormhitu (struct monst *worm)
void cutworm (struct monst *worm, xchar x, xchar y, struct obj *weap)
void see_wsegs (struct monst *worm)
void detect_wsegs (struct monst *worm, boolean use_detection_glyph)
void save_worm (int fd, int mode)
void rest_worm (int fd)
void place_wsegs (struct monst *worm)
void remove_worm (struct monst *worm)
void place_worm_tail_randomly (struct monst *worm, xchar x, xchar y)
STATIC_OVL void random_dir (xchar x, xchar y, xchar *nx, xchar *ny)
int count_wsegs (struct monst *mtmp)
STATIC_OVL struct wseg * create_worm_tail (int num_segs)
boolean worm_known (struct monst *worm)
Variables
struct wseg * wheads [MAX_NUM_WORMS] = DUMMY
struct wseg * wtails [MAX_NUM_WORMS] = DUMMY
long wgrowtime [MAX_NUM_WORMS] = DUMMY
Macro Definition Documentation
#define dealloc_seg(wseg) free((genericptr_t) (wseg))
Definition at line 9 of file worm.c.
Referenced by save_worm(), and toss_wsegs().
#define newseg() (struct wseg *) alloc(sizeof(struct wseg))
Definition at line 8 of file worm.c.
Referenced by create_worm_tail(), initworm(), rest_worm(), and worm_move().
Function Documentation
int count_wsegs (struct monst * mtmp)
Definition at line 682 of file worm.c.
References wseg::nseg.
{
    register int i=0;
    register struct wseg *curr = (wtails[mtmp->wormno])->nseg;
/* if (!mtmp->wormno) return 0; bullet proofing */
    while (curr) {
    i++;
    curr = curr->nseg;
    }
    return i;
}
STATIC_OVL struct wseg* create_worm_tail (int num_segs)
Definition at line 704 of file worm.c.
References newseg, wseg::nseg, wseg::wx, and wseg::wy.
Referenced by initworm().
{
    register int i=0;
    register struct wseg *new_tail, *curr;
    if (!num_segs) return (struct wseg *)0;
    new_tail = curr = newseg();
    curr->nseg = (struct wseg *)0;
    curr->wx = 0;
    curr->wy = 0;
    while (i < num_segs) {
    curr->nseg = newseg();
    curr = curr->nseg;
    curr->nseg = (struct wseg *)0;
    curr->wx = 0;
    curr->wy = 0;
    i++;
    }
    return (new_tail);
}
void cutworm (struct monst * worm, xchar x, xchar y, struct obj * weap)
Definition at line 315 of file worm.c.
References flags, get_wormno(), is_blade, monst::m_lev, max, monst::mhp, monst::mhpmax, flag::mon_moving, wseg::nseg, place_wsegs(), remove_monster, shrink_worm(), toss_wsegs(), TRUE, wseg::wx, and wseg::wy.
Referenced by known_hitum(), and thitmonst().
{
    register struct wseg *curr, *new_tail;
    register struct monst *new_worm;
    int wnum = worm->wormno;
    int cut_chance, new_wnum;
    if (!wnum) return; /* bullet proofing */
    if (x == worm->mx && y == worm->my) return; /* hit on head */
    /* cutting goes best with a bladed weapon */
    cut_chance = rnd(20); /* Normally 1-16 does not cut */
                /* Normally 17-20 does */
    if (weap && is_blade(weap)) /* With a blade 1- 6 does not cut */
    cut_chance += 10; /* 7-20 does */
    if (cut_chance < 17) return; /* not good enough */
    /* Find the segment that was attacked. */
    curr = wtails[wnum];
    while ((curr->wx != x) || (curr->wy != y)) {
    curr = curr->nseg;
    if (!curr) {
        impossible("cutworm: no segment at (%d,%d)", (int) x, (int) y);
        return;
    }
    }
    /* If this is the tail segment, then the worm just loses it. */
    if (curr == wtails[wnum]) {
    shrink_worm(wnum);
    return;
    }
    /*
     * Split the worm. The tail for the new worm is the old worm's tail.
     * The tail for the old worm is the segment that follows "curr",
     * and "curr" becomes the dummy segment under the new head.
     */
    new_tail = wtails[wnum];
    wtails[wnum] = curr->nseg;
    curr->nseg = (struct wseg *) 0; /* split the worm */
    /*
     * At this point, the old worm is correct. Any new worm will have
     * it's head at "curr" and its tail at "new_tail".
     */
    /* Sometimes the tail end dies. */
    if (rn2(3) || !(new_wnum = get_wormno())) {
    if (flags.mon_moving)
        pline("Part of the tail of %s is cut off.", mon_nam(worm));
    else
        You("cut part of the tail off of %s.", mon_nam(worm));
    toss_wsegs(new_tail, TRUE);
    if (worm->mhp > 1) worm->mhp /= 2;
    return;
    }
    remove_monster(x, y); /* clone_mon puts new head here */
    new_worm = clone_mon(worm, x, y);
    new_worm->wormno = new_wnum; /* affix new worm number */
    /* Devalue the monster level of both halves of the worm. */
    worm->m_lev = ((unsigned)worm->m_lev <= 3) ?
           (unsigned)worm->m_lev : max((unsigned)worm->m_lev - 2, 3);
    new_worm->m_lev = worm->m_lev;
    /* Calculate the mhp on the new_worm for the (lower) monster level. */
    new_worm->mhpmax = new_worm->mhp = d((int)new_worm->m_lev, 8);
    /* Calculate the mhp on the old worm for the (lower) monster level. */
    if (worm->m_lev > 3) {
    worm->mhpmax = d((int)worm->m_lev, 8);
    if (worm->mhpmax < worm->mhp) worm->mhp = worm->mhpmax;
    }
    wtails[new_wnum] = new_tail; /* We've got all the info right now */
    wheads[new_wnum] = curr; /* so we can do this faster than */
    wgrowtime[new_wnum] = 0L; /* trying to call initworm(). */
    /* Place the new monster at all the segment locations. */
    place_wsegs(new_worm);
    if (flags.mon_moving)
    pline("%s is cut in half.", Monnam(worm));
    else
    You("cut %s in half.", mon_nam(worm));
}
void detect_wsegs (struct monst * worm, boolean use_detection_glyph)
Definition at line 439 of file worm.c.
References detected_monnum_to_glyph, monnum_to_glyph, wseg::nseg, show_glyph(), what_mon, wseg::wx, and wseg::wy.
Referenced by monster_detect().
{
    int num;
    struct wseg *curr = wtails[worm->wormno];
/* if (!mtmp->wormno) return; bullet proofing */
    while (curr != wheads[worm->wormno]) {
    num = use_detection_glyph ?
        detected_monnum_to_glyph(what_mon(PM_LONG_WORM_TAIL)) :
        monnum_to_glyph(what_mon(PM_LONG_WORM_TAIL));
    show_glyph(curr->wx,curr->wy,num);
    curr = curr->nseg;
    }
}
STATIC_DCL void FDECL (toss_wsegs , (struct wseg *, BOOLEAN_P))
STATIC_DCL void FDECL (shrink_worm , (int))
STATIC_DCL void FDECL (random_dir , (XCHAR_P, XCHAR_P, xchar *, xchar *))
STATIC_DCL struct wseg* FDECL (create_worm_tail , (int))
int get_wormno ()
Definition at line 86 of file worm.c.
References MAX_NUM_WORMS.
Referenced by cutworm().
{
    register int new_wormno = 1;
    while (new_wormno < MAX_NUM_WORMS) {
    if (!wheads[new_wormno])
        return new_wormno; /* found an empty wtails[] slot at new_wormno */
    new_wormno++;
    }
    return(0); /* level infested with worms */
}
void initworm (struct monst * worm, int wseg_count)
Definition at line 111 of file worm.c.
References create_worm_tail(), newseg, wseg::nseg, wseg::wx, and wseg::wy.
{
    register struct wseg *seg, *new_tail = create_worm_tail(wseg_count);
    register int wnum = worm->wormno;
/* if (!wnum) return; bullet proofing */
    if (new_tail) {
    wtails[wnum] = new_tail;
    for (seg = new_tail; seg->nseg; seg = seg->nseg);
    wheads[wnum] = seg;
    } else {
    wtails[wnum] = wheads[wnum] = seg = newseg();
    seg->nseg = (struct wseg *) 0;
    seg->wx = worm->mx;
    seg->wy = worm->my;
    }
    wgrowtime[wnum] = 0L;
}
void place_worm_tail_randomly (struct monst * worm, xchar x, xchar y)
Definition at line 590 of file worm.c.
References FALSE, goodpos(), newsym(), wseg::nseg, place_worm_seg, random_dir(), toss_wsegs(), wseg::wx, and wseg::wy.
Referenced by rloc_to().
{
    int wnum = worm->wormno;
    struct wseg *curr = wtails[wnum];
    struct wseg *new_tail;
    register xchar ox = x, oy = y;
/* if (!wnum) return; bullet proofing */
    if (wnum && (!wtails[wnum] || !wheads[wnum])) {
    impossible("place_worm_tail_randomly: wormno is set without a tail!");
    return;
    }
    wheads[wnum] = new_tail = curr;
    curr = curr->nseg;
    new_tail->nseg = (struct wseg *) 0;
    new_tail->wx = x;
    new_tail->wy = y;
    while(curr) {
    xchar nx, ny;
    char tryct = 0;
    /* pick a random direction from x, y and search for goodpos() */
    do {
        random_dir(ox, oy, &nx, &ny);
    } while (!goodpos(nx, ny, worm, 0) && (tryct++ < 50));
    if (tryct < 50) {
        place_worm_seg(worm, nx, ny);
        curr->wx = ox = nx;
        curr->wy = oy = ny;
        wtails[wnum] = curr;
        curr = curr->nseg;
        wtails[wnum]->nseg = new_tail;
        new_tail = wtails[wnum];
        newsym(nx, ny);
    } else { /* Oops. Truncate because there was */
        toss_wsegs(curr, FALSE); /* no place for the rest of it */
        curr = (struct wseg *) 0;
    }
    }
}
void place_wsegs (struct monst * worm)
Definition at line 544 of file worm.c.
References wseg::nseg, place_worm_seg, wseg::wx, and wseg::wy.
Referenced by cutworm(), and getlev().
{
    struct wseg *curr = wtails[worm->wormno];
/* if (!mtmp->wormno) return; bullet proofing */
    while (curr != wheads[worm->wormno]) {
    place_worm_seg(worm,curr->wx,curr->wy);
    curr = curr->nseg;
    }
}
STATIC_OVL void random_dir (xchar x, xchar y, xchar * nx, xchar * ny)
Definition at line 647 of file worm.c.
References COLNO, and ROWNO.
Referenced by place_worm_tail_randomly().
{
    *nx = x;
    *ny = y;
    *nx += (x > 1 ? /* extreme left ? */
        (x < COLNO ? /* extreme right ? */
            (rn2(3) - 1) /* neither so +1, 0, or -1 */
        : -rn2(2)) /* 0, or -1 */
       : rn2(2)); /* 0, or 1 */
    *ny += (*nx == x ? /* same kind of thing with y */
        (y > 1 ?
            (y < ROWNO ?
            (rn2(2) ?
                1
            : -1)
            : -1)
        : 1)
        : (y > 1 ?
            (y < ROWNO ?
            (rn2(3) - 1)
            : -rn2(2))
        : rn2(2)));
}
void remove_worm (struct monst * worm)
Definition at line 566 of file worm.c.
References newsym(), wseg::nseg, remove_monster, wseg::wx, and wseg::wy.
Referenced by movebubbles(), and rloc_to().
{
    register struct wseg *curr = wtails[worm->wormno];
/* if (!mtmp->wormno) return; bullet proofing */
    while (curr) {
    remove_monster(curr->wx, curr->wy);
    newsym(curr->wx, curr->wy);
    curr = curr->nseg;
    }
}
void rest_worm (int fd)
Definition at line 511 of file worm.c.
References count, MAX_NUM_WORMS, mread(), newseg, wseg::nseg, temp, wseg::wx, and wseg::wy.
Referenced by getlev().
{
    int i, j, count;
    struct wseg *curr, *temp;
    for (i = 1; i < MAX_NUM_WORMS; i++) {
    mread(fd, (genericptr_t) &count, sizeof(int));
    if (!count) continue; /* none */
    /* Get the segments. */
    for (curr = (struct wseg *) 0, j = 0; j < count; j++) {
        temp = newseg();
        temp->nseg = (struct wseg *) 0;
        mread(fd, (genericptr_t) &(temp->wx), sizeof(xchar));
        mread(fd, (genericptr_t) &(temp->wy), sizeof(xchar));
        if (curr)
        curr->nseg = temp;
        else
        wtails[i] = temp;
        curr = temp;
    }
    wheads[i] = curr;
    }
    mread(fd, (genericptr_t) wgrowtime, sizeof(wgrowtime));
}
void save_worm (int fd, int mode)
Definition at line 465 of file worm.c.
References bwrite(), count, dealloc_seg, MAX_NUM_WORMS, wseg::nseg, perform_bwrite, release_data, temp, wseg::wx, and wseg::wy.
Referenced by savelev().
{
    int i;
    int count;
    struct wseg *curr, *temp;
    if (perform_bwrite(mode)) {
    for (i = 1; i < MAX_NUM_WORMS; i++) {
        for (count = 0, curr = wtails[i]; curr; curr = curr->nseg) count++;
        /* Save number of segments */
        bwrite(fd, (genericptr_t) &count, sizeof(int));
        /* Save segment locations of the monster. */
        if (count) {
        for (curr = wtails[i]; curr; curr = curr->nseg) {
            bwrite(fd, (genericptr_t) &(curr->wx), sizeof(
      xchar));
            bwrite(fd, (genericptr_t) &(curr->wy), sizeof(
      xchar));
        }
        }
    }
    bwrite(fd, (genericptr_t) wgrowtime, sizeof(wgrowtime));
    }
    if (release_data(mode)) {
    /* Free the segments only. savemonchn() will take care of the
     * monsters. */
    for (i = 1; i < MAX_NUM_WORMS; i++) {
        if (!(curr = wtails[i])) continue;
        while (curr) {
        temp = curr->nseg;
        dealloc_seg(curr); /* free the segment */
        curr = temp;
        }
        wheads[i] = wtails[i] = (struct wseg *) 0;
    }
    }
}
void see_wsegs (struct monst * worm)
Definition at line 420 of file worm.c.
References newsym(), wseg::nseg, wseg::wx, and wseg::wy.
Referenced by mon_set_minvis(), and see_monsters().
{
    struct wseg *curr = wtails[worm->wormno];
/* if (!mtmp->wormno) return; bullet proofing */
    while (curr != wheads[worm->wormno]) {
    newsym(curr->wx,curr->wy);
    curr = curr->nseg;
    }
}
STATIC_OVL void shrink_worm (int wnum)
Definition at line 175 of file worm.c.
References wseg::nseg, toss_wsegs(), and TRUE.
Referenced by cutworm(), worm_move(), and worm_nomove().
{
    struct wseg *seg;
    if (wtails[wnum] == wheads[wnum]) return; /* no tail */
    seg = wtails[wnum];
    wtails[wnum] = seg->nseg;
    seg->nseg = (struct wseg *) 0;
    toss_wsegs(seg, TRUE);
}
STATIC_OVL void toss_wsegs (struct wseg * curr, boolean display_update)
Definition at line 142 of file worm.c.
References dealloc_seg, newsym(), wseg::nseg, and remove_monster.
Referenced by cutworm(), place_worm_tail_randomly(), shrink_worm(), and wormgone().
{
    register struct wseg *seg;
    while (curr) {
    seg = curr->nseg;
    /* remove from level.monsters[][] */
    /* need to check curr->wx for genocided while migrating_mon */
    if (curr->wx) {
        remove_monster(curr->wx, curr->wy);
        /* update screen before deallocation */
        if (display_update) newsym(curr->wx,curr->wy);
    }
    /* free memory used by the segment */
    dealloc_seg(curr);
    curr = seg;
    }
}
boolean worm_known (struct monst * worm)
Definition at line 736 of file worm.c.
References cansee, FALSE, wseg::nseg, TRUE, wseg::wx, and wseg::wy.
Referenced by lookat().
{
    struct wseg *curr = wtails[worm->wormno];
    while (curr) {
    if(cansee(curr->wx,curr->wy)) return TRUE;
    curr = curr->nseg;
    }
    return FALSE;
}
void worm_move (struct monst * worm)
Definition at line 196 of file worm.c.
References MHPMAX, moves, newseg, newsym(), wseg::nseg, place_worm_seg, rn1, shrink_worm(), wseg::wx, and wseg::wy.
Referenced by use_defensive(), and use_misc().
{
    register struct wseg *seg, *new_seg; /* new segment */
    register int wnum = worm->wormno; /* worm number */
/* if (!wnum) return; bullet proofing */
    /*
     * Place a segment at the old worm head. The head has already moved.
     */
    seg = wheads[wnum];
    place_worm_seg(worm, seg->wx, seg->wy);
    newsym(seg->wx,seg->wy); /* display the new segment */
    /*
     * Create a new dummy segment head and place it at the end of the list.
     */
    new_seg = newseg();
    new_seg->wx = worm->mx;
    new_seg->wy = worm->my;
    new_seg->nseg = (struct wseg *) 0;
    seg->nseg = new_seg; /* attach it to the end of the list */
    wheads[wnum] = new_seg; /* move the end pointer */
    if (wgrowtime[wnum] <= moves) {
    if (!wgrowtime[wnum])
        wgrowtime[wnum] = moves + rnd(5);
    else
        wgrowtime[wnum] += rn1(15, 3);
    worm->mhp += 3;
    if (worm->mhp > MHPMAX) worm->mhp = MHPMAX;
    if (worm->mhp > worm->mhpmax) worm->mhpmax = worm->mhp;
    } else
    /* The worm doesn't grow, so the last segment goes away. */
    shrink_worm(wnum);
}
void worm_nomove (struct monst * worm)
Definition at line 244 of file worm.c.
References shrink_worm().
{
    shrink_worm((int) worm->wormno); /* shrink */
    if (worm->mhp > 3)
    worm->mhp -= 3; /* mhpmax not changed ! */
    else
    worm->mhp = 1;
}
void wormgone (struct monst * worm)
Definition at line 263 of file worm.c.
References toss_wsegs(), and TRUE.
{
    register int wnum = worm->wormno;
/* if (!wnum) return; bullet proofing */
    worm->wormno = 0;
    /* This will also remove the real monster (ie 'w') from the its
     * position in level.monsters[][].
     */
    toss_wsegs(wtails[wnum], TRUE);
    wheads[wnum] = wtails[wnum] = (struct wseg *) 0;
}
void wormhitu (struct monst * worm)
Definition at line 288 of file worm.c.
References distu, wseg::nseg, wseg::wx, and wseg::wy.
{
    register int wnum = worm->wormno;
    register struct wseg *seg;
/* if (!wnum) return; bullet proofing */
/* This does not work right now because mattacku() thinks that the head is
 * out of range of the player. We might try to kludge, and bring the head
 * within range for a tiny moment, but this needs a bit more looking at
 * before we decide to do this.
 */
    for (seg = wtails[wnum]; seg; seg = seg->nseg)
    if (distu(seg->wx, seg->wy) < 3)
        (void) mattacku(worm);
}
Variable Documentation
long wgrowtime[MAX_NUM_WORMS] = DUMMY
Definition at line 70 of file worm.c.
struct wseg* wheads[MAX_NUM_WORMS] = DUMMY
Definition at line 69 of file worm.c.
struct wseg * wtails[MAX_NUM_WORMS] = DUMMY
Definition at line 69 of file worm.c.