nethack/src/worn.c File Reference
#include `hack.h`
*
Data Structures
struct worn
Macros
#define w_blocks(o, m)
#define RACE_EXCEPTION TRUE
Functions
STATIC_DCL void FDECL (m_lose_armor,(struct monst *, struct obj *))
STATIC_DCL void FDECL (m_dowear_type,(struct monst *, long, BOOLEAN_P, BOOLEAN_P))
STATIC_DCL int FDECL (extra_pref,(struct monst *, struct obj *))
void setworn (struct obj *obj, long mask)
void setnotworn (struct obj *obj)
void mon_set_minvis (struct monst *mon)
void mon_adjust_speed (struct monst *mon, int adjust, struct obj *obj)
void update_mon_intrinsics (struct monst *mon, struct obj *obj, boolean on, boolean silently)
int find_mac (struct monst *mon)
void m_dowear (struct monst *mon, boolean creation)
STATIC_OVL void m_dowear_type (struct monst *mon, long flag, boolean creation, boolean racialexception)
struct obj * which_armor (struct monst *mon, long flag)
STATIC_OVL void m_lose_armor (struct monst *mon, struct obj *obj)
void clear_bypasses ()
void bypass_obj (struct obj *obj)
void mon_break_armor (struct monst *mon, boolean polyspot)
static int extra_pref (struct monst *mon, struct obj *obj)
int racial_exception (struct monst *mon, struct obj *obj)
Variables
const struct worn worn []
Macro Definition Documentation
#define RACE_EXCEPTION TRUE
Referenced by m_dowear().
#define w_blocks(o, m)
Value:
((o->otyp == MUMMY_WRAPPING && ((m) & W_ARMC)) ? INVIS : \
         (o->otyp == CORNUTHAUM && ((m) & W_ARMH) && \
            !Role_if(PM_WIZARD)) ? CLAIRVOYANT : 0)
Definition at line 37 of file worn.c.
Referenced by setnotworn(), setworn(), and update_mon_intrinsics().
Function Documentation
void bypass_obj (struct obj * obj)
Definition at line 586 of file worn.c.
References flag::bypasses, flags, and TRUE.
Referenced by mon_break_armor().
{
    obj->bypass = 1;
    flags.bypasses = TRUE;
}
void clear_bypasses ()
Definition at line 546 of file worn.c.
References flag::bypasses, DEADMONSTER, FALSE, flags, fmon, fobj, migrating_mons, migrating_objs, monst::minvent, newsym(), monst::nmon, obj::nobj, nobj, objects, otmp, and obj::otyp.
Referenced by savebones().
{
    struct obj *otmp, *nobj;
    struct monst *mtmp;
    for (otmp = fobj; otmp; otmp = nobj) {
        nobj = otmp->nobj;
        if (otmp->bypass) {
        otmp->bypass = 0;
        /* bypass will have inhibited any stacking, but since it's
           used for polymorph handling, the objects here probably
           have been transformed and won't be stacked in the usual
           manner afterwards; so don't bother with this */
#if 0
        if (objects[otmp->otyp].oc_merge) {
            xchar ox, oy;
            (void) get_obj_location(otmp, &ox, &oy, 0);
            stack_object(otmp);
            newsym(ox, oy);
        }
#endif /*0*/
        }
    }
    /* invent and mydogs chains shouldn't matter here */
    for (otmp = migrating_objs; otmp; otmp = otmp->nobj)
        otmp->bypass = 0;
    for (mtmp = fmon; mtmp; mtmp = mtmp->nmon) {
        if (DEADMONSTER(mtmp)) continue;
        for (otmp = mtmp->minvent; otmp; otmp = otmp->nobj)
        otmp->bypass = 0;
    }
    for (mtmp = migrating_mons; mtmp; mtmp = mtmp->nmon) {
        for (otmp = mtmp->minvent; otmp; otmp = otmp->nobj)
        otmp->bypass = 0;
    }
    flags.bypasses = FALSE;
}
static int extra_pref (struct monst * mon, struct obj * obj) [static]
Definition at line 759 of file worn.c.
References MFAST, and obj::otyp.
Referenced by m_dowear_type().
{
    if (obj) {
    if (obj->otyp == SPEED_BOOTS && mon->permspeed != MFAST)
        return 20;
    }
    return 0;
}
STATIC_DCL void FDECL (m_lose_armor , (struct monst *, struct obj *))
STATIC_DCL void FDECL (m_dowear_type , (struct monst *, long, BOOLEAN_P, BOOLEAN_P))
STATIC_DCL int FDECL (extra_pref , (struct monst *, struct obj *))
int find_mac (struct monst * mon)
Definition at line 328 of file worn.c.
References ARM_BONUS, obj::nobj, and obj::owornmask.
Referenced by drag_ball(), experience(), find_roll_to_hit(), mbhitm(), and thitmonst().
{
    register struct obj *obj;
    int base = mon->data->ac;
    long mwflags = mon->misc_worn_check;
    for (obj = mon->minvent; obj; obj = obj->nobj) {
        if (obj->owornmask & mwflags)
        base -= ARM_BONUS(obj);
        /* since ARM_BONUS is positive, subtracting it increases AC */
    }
    return base;
}
void m_dowear (struct monst * mon, boolean creation)
Definition at line 359 of file worn.c.
References bimanual, cantweararm, FALSE, is_animal, m_dowear_type(), mindless, MON_WEP, mons, MZ_SMALL, nohands, RACE_EXCEPTION, S_CENTAUR, S_MUMMY, slithy, verysmall, W_AMUL, W_ARM, W_ARMC, W_ARMF, W_ARMG, W_ARMH, and W_ARMS.
Referenced by mk_mplayer(), and savebones().
{
#define RACE_EXCEPTION TRUE
    /* Note the restrictions here are the same as in dowear in do_wear.c
     * except for the additional restriction on intelligence. (Players
     * are always intelligent, even if polymorphed).
     */
    if (verysmall(mon->data) || nohands(mon->data) ||
      is_animal(mon->data))
        return;
    /* give mummies a chance to wear their wrappings
     * and let skeletons wear their initial armor */
    if (mindless(mon->data) && (!creation ||
        (mon->data->mlet != S_MUMMY && mon->data != &mons[PM_SKELETON])))
        return;
    m_dowear_type(mon, W_AMUL, creation, FALSE);
#ifdef TOURIST
    /* can't put on shirt if already wearing suit */
    if (!cantweararm(mon->data) || (mon->misc_worn_check &
      W_ARM))
        m_dowear_type(mon, W_ARMU, creation, FALSE);
#endif
    /* treating small as a special case allows
       hobbits, gnomes, and kobolds to wear cloaks */
    if (!cantweararm(mon->data) || mon->data->msize ==
      MZ_SMALL)
        m_dowear_type(mon, W_ARMC, creation, FALSE);
    m_dowear_type(mon, W_ARMH, creation, FALSE);
    if (!MON_WEP(mon) || !bimanual(MON_WEP(mon)))
        m_dowear_type(mon, W_ARMS, creation, FALSE);
    m_dowear_type(mon, W_ARMG, creation, FALSE);
    if (!slithy(mon->data) && mon->data->mlet != S_CENTAUR)
        m_dowear_type(mon, W_ARMF, creation, FALSE);
    if (!cantweararm(mon->data))
        m_dowear_type(mon, W_ARM, creation, FALSE);
    else
        m_dowear_type(mon, W_ARM, creation, RACE_EXCEPTION);
}
STATIC_OVL void m_dowear_type (struct monst * mon, long flag, boolean creation, boolean racialexception)
Definition at line 399 of file worn.c.
References AMULET_CLASS, ARM_BONUS, buf, BUFSZ, canseemon, extra_pref(), FALSE, has_horns, is_boots, is_cloak, is_flimsy, is_gloves, is_helmet, is_shield, is_shirt, is_suit, makeknown, nambuf, obj::nobj, objects, objclass::oc_delay, obj::oclass, obj::otyp, obj::owornmask, racial_exception(), See_invisible, Sprintf, Strcpy, TOURIST, TRUE, update_mon_intrinsics(), W_AMUL, W_ARM, W_ARMC, W_ARMF, W_ARMG, W_ARMH, W_ARMS, and which_armor().
Referenced by m_dowear().
{
    struct obj *old, *best, *obj;
    int m_delay = 0;
    int unseen = !canseemon(mon);
    char nambuf[BUFSZ];
    if (mon->mfrozen) return; /* probably putting previous item on */
    /* Get a copy of monster's name before altering its visibility */
    Strcpy(nambuf, See_invisible ? Monnam(mon) : mon_nam(mon));
    old = which_armor(mon, flag);
    if (old && old->cursed) return;
    if (old && flag == W_AMUL) return; /* no such thing as better amulets */
    best = old;
    for(obj = mon->minvent; obj; obj = obj->nobj) {
        switch(flag) {
        case W_AMUL:
            if (obj->oclass != AMULET_CLASS ||
                (obj->otyp != AMULET_OF_LIFE_SAVING &&
                obj->otyp != AMULET_OF_REFLECTION))
            continue;
            best = obj;
            goto outer_break; /* no such thing as better amulets */
#ifdef TOURIST
        case W_ARMU:
            if (!is_shirt(obj)) continue;
            break;
#endif
        case W_ARMC:
            if (!is_cloak(obj)) continue;
            break;
        case W_ARMH:
            if (!is_helmet(obj)) continue;
            /* (flimsy exception matches polyself handling) */
            if (has_horns(mon->data) && !is_flimsy(obj)) continue;
            break;
        case W_ARMS:
            if (!is_shield(obj)) continue;
            break;
        case W_ARMG:
            if (!is_gloves(obj)) continue;
            break;
        case W_ARMF:
            if (!is_boots(obj)) continue;
            break;
        case W_ARM:
            if (!is_suit(obj)) continue;
            if (racialexception && (racial_exception(mon, obj) < 1)) continue;
            break;
        }
        if (obj->owornmask) continue;
        /* I'd like to define a VISIBLE_ARM_BONUS which doesn't assume the
         * monster knows obj->spe, but if I did that, a monster would keep
         * switching forever between two -2 caps since when it took off one
         * it would forget spe and once again think the object is better
         * than what it already has.
         */
        if (best && (ARM_BONUS(best) + extra_pref(mon,best) >=
      ARM_BONUS(obj) + extra_pref(mon,obj)))
        continue;
        best = obj;
    }
outer_break:
    if (!best || best == old) return;
    /* if wearing a cloak, account for the time spent removing
       and re-wearing it when putting on a suit or shirt */
    if ((flag == W_ARM
#ifdef TOURIST
      || flag == W_ARMU
#endif
              ) && (mon->misc_worn_check & W_ARMC))
        m_delay += 2;
    /* when upgrading a piece of armor, account for time spent
       taking off current one */
    if (old)
        m_delay += objects[old->otyp].oc_delay;
    if (old) /* do this first to avoid "(being worn)" */
        old->owornmask = 0L;
    if (!creation) {
        if (canseemon(mon)) {
        char buf[BUFSZ];
        if (old)
            Sprintf(buf, " removes %s and", distant_name(old, doname));
        else
            buf[0] = '\0';
        pline("%s%s puts on %s.", Monnam(mon),
              buf, distant_name(best,doname));
        } /* can see it */
        m_delay += objects[best->otyp].oc_delay;
        mon->mfrozen = m_delay;
        if (mon->mfrozen) mon->mcanmove = 0;
    }
    if (old)
        update_mon_intrinsics(mon, old, FALSE, creation);
    mon->misc_worn_check |= flag;
    best->owornmask |= flag;
    update_mon_intrinsics(mon, best, TRUE, creation);
    /* if couldn't see it but now can, or vice versa, */
    if (!creation && (unseen ^ !canseemon(mon))) {
        if (mon->minvis && !See_invisible) {
            pline("Suddenly you cannot see %s.", nambuf);
            makeknown(best->otyp);
        } /* else if (!mon->minvis) pline("%s suddenly appears!", Amonnam(mon)); */
    }
}
STATIC_OVL void m_lose_armor (struct monst * mon, struct obj * obj)
Definition at line 529 of file worn.c.
References FALSE, newsym(), obj::owornmask, and update_mon_intrinsics().
Referenced by mon_break_armor().
{
    mon->misc_worn_check &= ~obj->owornmask;
    if (obj->owornmask)
        update_mon_intrinsics(mon, obj, FALSE, FALSE);
    obj->owornmask = 0L;
    obj_extract_self(obj);
    place_object(obj, mon->mx, mon->my);
    /* call stackobj() if we ever drop anything that can merge */
    newsym(mon->mx, mon->my);
}
void mon_adjust_speed (struct monst * mon, int adjust, struct obj * obj)
Definition at line 144 of file worn.c.
References canseemon, FALSE, FAST, flags, in_mklev, makeknown, MFAST, MSLOW, obj::nobj, objects, objclass::oc_class, objclass::oc_oprop, otmp, obj::otyp, obj::owornmask, SPBOOK_CLASS, TRUE, and flag::verbose.
Referenced by damageum(), mon_consume_unstone(), update_mon_intrinsics(), and use_misc().
{
    struct obj *otmp;
    boolean give_msg = !in_mklev, petrify = FALSE;
    unsigned int oldspeed = mon->mspeed;
    switch (adjust) {
     case 2:
    mon->permspeed = MFAST;
    give_msg = FALSE; /* special case monster creation */
    break;
     case 1:
    if (mon->permspeed == MSLOW) mon->permspeed = 0;
    else mon->permspeed = MFAST;
    break;
     case 0: /* just check for worn speed boots */
    break;
     case -1:
    if (mon->permspeed == MFAST) mon->permspeed = 0;
    else mon->permspeed = MSLOW;
    break;
     case -2:
    mon->permspeed = MSLOW;
    give_msg = FALSE; /* (not currently used) */
    break;
     case -3: /* petrification */
    /* take away intrinsic speed but don't reduce normal speed */
    if (mon->permspeed == MFAST) mon->permspeed = 0;
    petrify = TRUE;
    break;
    }
    for (otmp = mon->minvent; otmp; otmp = otmp->nobj)
    if (otmp->owornmask && objects[otmp->otyp].oc_oprop ==
      FAST)
        break;
    if (otmp) /* speed boots */
    mon->mspeed = MFAST;
    else
    mon->mspeed = mon->permspeed;
    if (give_msg && (mon->mspeed != oldspeed || petrify) && canseemon(mon)) {
    /* fast to slow (skipping intermediate state) or vice versa */
    const char *howmuch = (mon->mspeed + oldspeed == MFAST + MSLOW) ?
                "much " : "";
    if (petrify) {
        /* mimic the player's petrification countdown; "slowing down"
           even if fast movement rate retained via worn speed boots */
        if (flags.verbose) pline("%s is slowing down.", Monnam(mon));
    } else if (adjust > 0 || mon->mspeed == MFAST)
        pline("%s is suddenly moving %sfaster.", Monnam(mon), howmuch);
    else
        pline("%s seems to be moving %sslower.", Monnam(mon), howmuch);
    /* might discover an object if we see the speed change happen, but
       avoid making possibly forgotten book known when casting its spell */
    if (obj != 0 && obj->dknown &&
        objects[obj->otyp].oc_class != SPBOOK_CLASS)
        makeknown(obj->otyp);
    }
}
void mon_break_armor (struct monst * mon, boolean polyspot)
Definition at line 594 of file worn.c.
References buf, BUFSZ, bypass_obj(), cansee, DISMOUNT_FELL, Dragon_mail_to_pm, Dragon_scales_to_pm, has_horns, Is_dragon_mail, Is_dragon_scales, is_flimsy, is_whirly, m_lose_armor(), mhim, mhis, permonst::mlet, MON_WEP, nohands, obj::oartifact, otmp, S_CENTAUR, slithy, Sprintf, Stone_resistance, touch_petrifies, u, verysmall, W_ARM, W_ARMC, W_ARMF, W_ARMG, W_ARMH, W_ARMS, and which_armor().
{
    register struct obj *otmp;
    struct permonst *mdat = mon->data;
    boolean vis = cansee(mon->mx, mon->my);
    boolean handless_or_tiny = (nohands(mdat) || verysmall(mdat));
    const char *pronoun = mhim(mon),
            *ppronoun = mhis(mon);
    if (breakarm(mdat)) {
        if ((otmp = which_armor(mon, W_ARM)) != 0) {
        if ((Is_dragon_scales(otmp) &&
            mdat == Dragon_scales_to_pm(otmp)) ||
            (Is_dragon_mail(otmp) && mdat == Dragon_mail_to_pm(otmp)))
            ; /* no message here;
               "the dragon merges with his scaly armor" is odd
               and the monster's previous form is already gone */
        else if (vis)
            pline("%s breaks out of %s armor!", Monnam(mon), ppronoun);
        else
            You_hear("a cracking sound.");
        m_useup(mon, otmp);
        }
        if ((otmp = which_armor(mon, W_ARMC)) != 0) {
        if (otmp->oartifact) {
            if (vis)
            pline("%s %s falls off!", s_suffix(Monnam(mon)),
                cloak_simple_name(otmp));
            if (polyspot) bypass_obj(otmp);
            m_lose_armor(mon, otmp);
        } else {
            if (vis)
            pline("%s %s tears apart!", s_suffix(Monnam(mon)),
                cloak_simple_name(otmp));
            else
            You_hear("a ripping sound.");
            m_useup(mon, otmp);
        }
        }
#ifdef TOURIST
        if ((otmp = which_armor(mon, W_ARMU)) != 0) {
        if (vis)
            pline("%s shirt rips to shreds!", s_suffix(Monnam(mon)));
        else
            You_hear("a ripping sound.");
        m_useup(mon, otmp);
        }
#endif
    } else if (sliparm(mdat)) {
        if ((otmp = which_armor(mon, W_ARM)) != 0) {
        if (vis)
            pline("%s armor falls around %s!",
                 s_suffix(Monnam(mon)), pronoun);
        else
            You_hear("a thud.");
        if (polyspot) bypass_obj(otmp);
        m_lose_armor(mon, otmp);
        }
        if ((otmp = which_armor(mon, W_ARMC)) != 0) {
        if (vis) {
            if (is_whirly(mon->data))
            pline("%s %s falls, unsupported!",
                     s_suffix(Monnam(mon)), cloak_simple_name(otmp));
            else
            pline("%s shrinks out of %s %s!", Monnam(mon),
                        ppronoun, cloak_simple_name(otmp));
        }
        if (polyspot) bypass_obj(otmp);
        m_lose_armor(mon, otmp);
        }
#ifdef TOURIST
        if ((otmp = which_armor(mon, W_ARMU)) != 0) {
        if (vis) {
            if (sliparm(mon->data))
            pline("%s seeps right through %s shirt!",
                    Monnam(mon), ppronoun);
            else
            pline("%s becomes much too small for %s shirt!",
                    Monnam(mon), ppronoun);
        }
        if (polyspot) bypass_obj(otmp);
        m_lose_armor(mon, otmp);
        }
#endif
    }
    if (handless_or_tiny) {
        /* [caller needs to handle weapon checks] */
        if ((otmp = which_armor(mon, W_ARMG)) != 0) {
        if (vis)
            pline("%s drops %s gloves%s!", Monnam(mon), ppronoun,
                    MON_WEP(mon) ? " and weapon" : "");
        if (polyspot) bypass_obj(otmp);
        m_lose_armor(mon, otmp);
        }
        if ((otmp = which_armor(mon, W_ARMS)) != 0) {
        if (vis)
            pline("%s can no longer hold %s shield!", Monnam(mon),
                                ppronoun);
        else
            You_hear("a clank.");
        if (polyspot) bypass_obj(otmp);
        m_lose_armor(mon, otmp);
        }
    }
    if (handless_or_tiny || has_horns(mdat)) {
        if ((otmp = which_armor(mon, W_ARMH)) != 0 &&
            /* flimsy test for horns matches polyself handling */
            (handless_or_tiny || !is_flimsy(otmp))) {
        if (vis)
            pline("%s helmet falls to the %s!",
              s_suffix(Monnam(mon)), surface(mon->mx, mon->my));
        else
            You_hear("a clank.");
        if (polyspot) bypass_obj(otmp);
        m_lose_armor(mon, otmp);
        }
    }
    if (handless_or_tiny || slithy(mdat) || mdat->mlet == S_CENTAUR) {
        if ((otmp = which_armor(mon, W_ARMF)) != 0) {
        if (vis) {
            if (is_whirly(mon->data))
            pline("%s boots fall away!",
                       s_suffix(Monnam(mon)));
            else pline("%s boots %s off %s feet!",
            s_suffix(Monnam(mon)),
            verysmall(mdat) ? "slide" : "are pushed", ppronoun);
        }
        if (polyspot) bypass_obj(otmp);
        m_lose_armor(mon, otmp);
        }
    }
#ifdef STEED
    if (!can_saddle(mon)) {
        if ((otmp = which_armor(mon, W_SADDLE)) != 0) {
        if (polyspot) bypass_obj(otmp);
        m_lose_armor(mon, otmp);
        if (vis)
            pline("%s saddle falls off.", s_suffix(Monnam(mon)));
        }
        if (mon == u.usteed)
        goto noride;
    } else if (mon == u.usteed && !can_ride(mon)) {
    noride:
        You("can no longer ride %s.", mon_nam(mon));
        if (touch_petrifies(u.usteed->data) &&
            !Stone_resistance && rnl(3)) {
        char buf[BUFSZ];
        You("touch %s.", mon_nam(u.usteed));
        Sprintf(buf, "falling off %s",
                an(u.usteed->data->mname));
        instapetrify(buf);
        }
        dismount_steed(DISMOUNT_FELL);
    }
#endif
    return;
}
void mon_set_minvis (struct monst * mon)
Definition at line 132 of file worn.c.
References newsym(), and see_wsegs().
Referenced by use_misc().
{
    mon->perminvis = 1;
    if (!mon->invis_blkd) {
        mon->minvis = 1;
        newsym(mon->mx, mon->my); /* make it disappear */
        if (mon->wormno) see_wsegs(mon); /* and any tail too */
    }
}
int racial_exception (struct monst * mon, struct obj * obj)
Definition at line 778 of file worn.c.
References is_elven_armor, and mons.
Referenced by m_dowear_type().
{
    const struct permonst *ptr = raceptr(mon);
    /* Acceptable Exceptions: */
    /* Allow hobbits to wear elven armor - LoTR */
    if (ptr == &mons[PM_HOBBIT] && is_elven_armor(obj))
    return 1;
    /* Unacceptable Exceptions: */
    /* Checks for object that certain races should never use go here */
    /* return -1; */
    return 0;
}
void setnotworn (struct obj * obj)
Definition at line 109 of file worn.c.
References prop::blocked, prop::extrinsic, objects, objclass::oc_oprop, you::twoweap, u, update_inventory, you::uprops, uswapwep, uwep, w_blocks, worn::w_mask, and worn::w_obj.
{
    register const struct worn *wp;
    register int p;
    if (!obj) return;
    if (obj == uwep || obj == uswapwep) u.twoweap = 0;
    for(wp = worn; wp->w_mask; wp++)
        if(obj == *(wp->w_obj)) {
        *(wp->w_obj) = 0;
        p = objects[obj->otyp].oc_oprop;
        u.uprops[p].extrinsic = u.uprops[p].extrinsic & ~wp->
      w_mask;
        obj->owornmask &= ~wp->w_mask;
        if (obj->oartifact)
            set_artifact_intrinsic(obj, 0, wp->w_mask);
        if ((p = w_blocks(obj,wp->w_mask)) != 0)
            u.uprops[p].blocked &= ~wp->w_mask;
        }
    update_inventory();
}
void setworn (struct obj * obj, long mask)
Definition at line 47 of file worn.c.
References prop::blocked, prop::extrinsic, I_SPECIAL, is_weptool, obj::oartifact, objects, objclass::oc_oprop, obj::otyp, obj::owornmask, you::twoweap, u, update_inventory, you::uprops, uskin, W_ARM, w_blocks, worn::w_mask, worn::w_obj, W_QUIVER, W_SWAPWEP, W_WEP, and WEAPON_CLASS.
Referenced by dorecover(), ini_inv(), restgamestate(), setuqwep(), setuswapwep(), setuwep(), throwit(), uqwepgone(), uswapwepgone(), and uwepgone().
{
    register const struct worn *wp;
    register struct obj *oobj;
    register int p;
    if ((mask & (W_ARM|I_SPECIAL)) == (W_ARM|I_SPECIAL)) {
        /* restoring saved game; no properties are conferred via skin */
        uskin = obj;
     /* assert(!uarm); */
    } else {
        for(wp = worn; wp->w_mask; wp++) if(wp->w_mask & mask) {
        oobj = *(wp->w_obj);
        if(oobj && !(oobj->owornmask & wp->w_mask))
            impossible("Setworn: mask = %ld.", wp->w_mask);
        if(oobj) {
            if (u.twoweap && (oobj->owornmask & (W_WEP|
      W_SWAPWEP)))
            u.twoweap = 0;
            oobj->owornmask &= ~wp->w_mask;
            if (wp->w_mask & ~(W_SWAPWEP|W_QUIVER)) {
            /* leave as "x = x <op> y", here and below, for broken
             * compilers */
            p = objects[oobj->otyp].oc_oprop;
            u.uprops[p].extrinsic =
                    u.uprops[p].extrinsic & ~wp->w_mask;
            if ((p = w_blocks(oobj,mask)) != 0)
                u.uprops[p].blocked &= ~wp->w_mask;
            if (oobj->oartifact)
                set_artifact_intrinsic(oobj, 0, mask);
            }
        }
        *(wp->w_obj) = obj;
        if(obj) {
            obj->owornmask |= wp->w_mask;
            /* Prevent getting/blocking intrinsics from wielding
             * potions, through the quiver, etc.
             * Allow weapon-tools, too.
             * wp_mask should be same as mask at this point.
             */
            if (wp->w_mask & ~(W_SWAPWEP|W_QUIVER)) {
            if (obj->oclass == WEAPON_CLASS || is_weptool(obj) ||
                        mask != W_WEP) {
                p = objects[obj->otyp].oc_oprop;
                u.uprops[p].extrinsic =
                    u.uprops[p].extrinsic | wp->w_mask;
                if ((p = w_blocks(obj, mask)) != 0)
                u.uprops[p].blocked |= wp->w_mask;
            }
            if (obj->oartifact)
                set_artifact_intrinsic(obj, 1, mask);
            }
        }
        }
    }
    update_inventory();
}
void update_mon_intrinsics (struct monst * mon, struct obj * obj, boolean on, boolean silently)
Definition at line 211 of file worn.c.
References ACID_RES, ANTIMAGIC, canseemon, CLAIRVOYANT, COLD_RES, DISINT_RES, DISMOUNT_FELL, DISPLACED, FAST, FIRE_RES, FUMBLING, in_mklev, INVIS, JUMPING, LEVITATION, mon_adjust_speed(), newsym(), obj::nobj, objects, objclass::oc_oprop, otmp, obj::otyp, obj::owornmask, POISON_RES, PROTECTION, REFLECTING, SHOCK_RES, SLEEP_RES, STEALTH, STONE_RES, TELEPAT, TRUE, u, w_blocks, and WWALKING.
Referenced by loot_mon(), m_dowear_type(), m_lose_armor(), and steal_it().
{
    int unseen;
    uchar mask;
    struct obj *otmp;
    int which = (int) objects[obj->otyp].oc_oprop;
    unseen = !canseemon(mon);
    if (!which) goto maybe_blocks;
    if (on) {
    switch (which) {
     case INVIS:
        mon->minvis = !mon->invis_blkd;
        break;
     case FAST:
      {
        boolean save_in_mklev = in_mklev;
        if (silently) in_mklev = TRUE;
        mon_adjust_speed(mon, 0, obj);
        in_mklev = save_in_mklev;
        break;
      }
    /* properties handled elsewhere */
     case ANTIMAGIC:
     case REFLECTING:
        break;
    /* properties which have no effect for monsters */
     case CLAIRVOYANT:
     case STEALTH:
     case TELEPAT:
        break;
    /* properties which should have an effect but aren't implemented */
     case LEVITATION:
     case WWALKING:
        break;
    /* properties which maybe should have an effect but don't */
     case DISPLACED:
     case FUMBLING:
     case JUMPING:
     case PROTECTION:
        break;
     default:
        if (which <= 8) { /* 1 thru 8 correspond to MR_xxx mask values */
        /* FIRE,COLD,SLEEP,DISINT,SHOCK,POISON,ACID,STONE */
        mask = (uchar) (1 << (which - 1));
        mon->mintrinsics |= (unsigned short) mask;
        }
        break;
    }
    } else { /* off */
    switch (which) {
     case INVIS:
        mon->minvis = mon->perminvis;
        break;
     case FAST:
      {
        boolean save_in_mklev = in_mklev;
        if (silently) in_mklev = TRUE;
        mon_adjust_speed(mon, 0, obj);
        in_mklev = save_in_mklev;
        break;
      }
     case FIRE_RES:
     case COLD_RES:
     case SLEEP_RES:
     case DISINT_RES:
     case SHOCK_RES:
     case POISON_RES:
     case ACID_RES:
     case STONE_RES:
        mask = (uchar) (1 << (which - 1));
        /* If the monster doesn't have this resistance intrinsically,
           check whether any other worn item confers it. Note that
           we don't currently check for anything conferred via simply
           carrying an object. */
        if (!(mon->data->mresists & mask)) {
        for (otmp = mon->minvent; otmp; otmp = otmp->nobj)
            if (otmp->owornmask &&
                (int) objects[otmp->otyp].oc_oprop == which)
            break;
        if (!otmp)
            mon->mintrinsics &= ~((unsigned short) mask);
        }
        break;
     default:
        break;
    }
    }
 maybe_blocks:
    /* obj->owornmask has been cleared by this point, so we can't use it.
       However, since monsters don't wield armor, we don't have to guard
       against that and can get away with a blanket worn-mask value. */
    switch (w_blocks(obj,~0L)) {
     case INVIS:
    mon->invis_blkd = on ? 1 : 0;
    mon->minvis = on ? 0 : mon->perminvis;
    break;
     default:
    break;
    }
#ifdef STEED
    if (!on && mon == u.usteed && obj->otyp == SADDLE)
        dismount_steed(DISMOUNT_FELL);
#endif
    /* if couldn't see it but now can, or vice versa, update display */
    if (!silently && (unseen ^ !canseemon(mon)))
    newsym(mon->mx, mon->my);
}
struct obj* which_armor (struct monst * mon, long flag)
Definition at line 516 of file worn.c.
References obj::nobj, and obj::owornmask.
Referenced by find_offensive(), fix_worst_trouble(), hurtmarmor(), in_trouble(), loot_mon(), m_dowear_type(), m_slips_free(), mon_break_armor(), mon_reflects(), muse_newcham_mon(), rnd_offensive_item(), rndcurse(), and use_offensive().
{
    register struct obj *obj;
    for(obj = mon->minvent; obj; obj = obj->nobj)
        if (obj->owornmask & flag) return obj;
    return((struct obj *)0);
}
Variable Documentation
const struct worn worn[]
Initial value:
= {
    { W_ARM, &uarm },
    { W_ARMC, &uarmc },
    { W_ARMH, &uarmh },
    { W_ARMS, &uarms },
    { W_ARMG, &uarmg },
    { W_ARMF, &uarmf },
    { W_RINGL, &uleft },
    { W_RINGR, &uright },
    { W_WEP, &uwep },
    { W_SWAPWEP, &uswapwep },
    { W_QUIVER, &uquiver },
    { W_AMUL, &uamul },
    { W_TOOL, &ublindf },
    { W_BALL, &uball },
    { W_CHAIN, &uchain },
    { 0, 0 }
}